### ISSUE TITLE
[Code Signing] Missing documentation on public key config

### ISSUE THREAD

**Issue by fungilation** [Microsoft/react-native-code-push#1001]
Reading docs: https://github.com/Microsoft/code-push/blob/master/cli/README.md#code-signing for how to implement code signing, I can follow everything except where/how do I put in a generated public key. Since it should be part of the bundle binary, I assume as a config for code-push sdk, is it supplied as part of the `react-native link` setup process? The docs make no mention of this.

On doing a `react-native link`, I also currently don't see the link script asking to supply a public key for code signing, so I don't know if that's the place to configure it? Perhaps it's because of bug https://github.com/Microsoft/react-native-code-push/issues/999 that `link` stalls before the script can ask for a public key?

Thanks for any clarification and for docs updating.

**Comment by ruslan-bikkinin** [comment]
@fungilation thanks for interest in code signing feature! We have a plans to update link scripts to provide support for code-signing feature, but for now you need to do it manually. Please, refer to [iOS](https://github.com/microsoft/react-native-code-push/blob/master/docs/api-ios.md) or [Android](https://github.com/microsoft/react-native-code-push/blob/master/docs/api-android.md) API documentation sections to get more information how to setup public key for your application.

**Comment by ruslan-bikkinin** [comment]
Fix in the master, so I close it for now. @fungilation please feel free to reopen it if you will have any questions.

**Comment by fungilation** [comment]
Ah, was the wrong link giving me lack of docs. Thanks for the update, issue is closed.

Automating it in link scripts would be an improvement.
