### ISSUE TITLE
[5.1.0-beta] android: DexIndexOverflowException due to com.auth0.jwt

### ISSUE THREAD

**Issue by slicejunk** [Microsoft/react-native-code-push#1002]
### Steps to Reproduce
1. compile the android app
2. count the methods with https://github.com/KeepSafe/dexcount-gradle-plugin for instance

### Expected Behavior
the library should not consume ~ 25.000 methods !!
we should not add multidex support just for one dependency

### Actual Behavior
DexIndexOverflowException

**Comment by sergey-akhalkov** [comment]
Hi @slicejunk, thanks for pointing to this. I'm going to investigate if we could use another jwt lib to avoid this issue, we'll let you know if any updates.

**Comment by slicejunk** [comment]
@sergey-akhalkov  you can also use this package to count the number of methods used
https://github.com/mihaip/dex-method-counts
proguard can shrink this number to only ~3.000 but it is a pain to use it on dev
I guess some people will get this ```DexIndexOverflowException``` just after upgrading to 5.1.0-beta

**Comment by mortezaalizadeh** [comment]
Got the same issue this morning after upgrading from 5.0.0-beta to 5.1.0-beta. I am going to enable multidex: https://stackoverflow.com/questions/26515378/dexindexoverflowexception-issue-after-updating-to-latest-appcompat-and-support-l

**Comment by sergey-akhalkov** [comment]
Hi @slicejunk, @mortezaalizadeh, I've fixed the issue in https://github.com/Microsoft/react-native-code-push/pull/1007, please verify. We are also going to test and merge it.

**Comment by max-mironov** [comment]
Hey everybody, we've released [5.1.1-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v5.1.1-beta) that should fix the problem. Please let us know if you see any issues with this.
