### ISSUE TITLE
Images load slower after app updates to latest release - Background image shows background for a split second before loading

### ISSUE THREAD

**Issue by slickdev** [Microsoft/react-native-code-push#1006]
### Steps to Reproduce
1. Configure everything and verify it works
2. Push a new release
3. Allow the app to download the update. Restart the app so it installs

### Expected Behavior
The updated app and assets should load at the same speeds as the original.

### Actual Behavior
Images are loading slower. I have an ImageBackground element that now has a split-second delay when the screen loads, and I can see the grey color of the container in the background.

### Environment

* react-native-code-push version: "^5.1.0-beta"
* react-native version: "0.48.3"
* iOS/Android/Windows version: IOS
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Physical Device, haven't tested on simulator.

**Comment by sergey-akhalkov** [comment]
Hi @slickdev, thanks for reaching us. I believe you have the similar issue as here https://github.com/Microsoft/react-native-code-push/issues/739#issuecomment-290639575
Actually, CodePush changes link to jsbundle to load from another location on device storage. And this another location could be probably slower for data access than access to `ipa` contents.

By the way, could you please provide us with minimum version of your app where the issue reproduces - we'll try to investigate it and see if we would be able to resolve the issue or not.

**Comment by slickdev** [comment]
Thanks for the response, I will see when I can get a chance to try out previous versions. Until then I've had to remove it from my project due to the flickering images. Will try to get to it this week.

**Comment by sergey-akhalkov** [comment]
Got it, I'm closing this for now, please feel free to reopen or create new one.
