### ISSUE TITLE
Deployment strategies

### ISSUE THREAD

**Issue by wholcman** [Microsoft/react-native-code-push#1008]
Hi -

Need advice.
Scenario:
 - An app is submitted 1.0 and approved.
 - Hotfixes are deployed via "codepush"
 - Users which already have the app got the hotfixes (that's a good news).
 - When a new user download the app from the store, how can I force him to get the latest version I have deployed via "codepush"? I would like to get all my users up-to-date. 
 - Actually, a new user which download the app get the version I have submitted on the store, if he goes on background / kill the app and re-open he gets the latest version I have on codepush.

I would like to know if there is a way to avoid this last step.
TY.

**Comment by max-mironov** [comment]
Hello @wholcman, you can use different [check Frequency](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#checkfrequency) modes to verify if update exist. I believe the fastest should be `codePush.CheckFrequency.ON_APP_RESUME`  especially when used with combination of `codePush.InstallMode.IMMEDIATE`.

**Comment by wholcman** [comment]
Hi @max-mironov,

I got a solution but I don't know if this is the optimized way.
Indeed, each start of the app I check `codePush.checkForUpdate()`. 
If there is an update, I force sync with `codePush.InstallMode.IMMEDIATE`
If not, I hide the splashscreen.

But, now I find the starting of the app slow due to the request.
:(

**Comment by max-mironov** [comment]
@wholcman 
You can also checkout [how this is done](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/demo.js#L160) in our demo app to see other ways to integrate codepush that probably should be easier. You can e.g. change `codePushOptions` here to try different workflows which suit best for you.

**Comment by max-mironov** [comment]
Closing this, please feel free to reach us if you have more questions.
