### ISSUE TITLE
Update crashes on production but not staging

### ISSUE THREAD

**Issue by TheRohitSharma** [Microsoft/react-native-code-push#1011]
Steps to Reproduce
1. Promote Staging to Production.
2. Restart app either when prompted or manually.
3. App crashes instead of smoothly restarting.

Expected Behavior
Expected Production to work since Staging works with the same update. 

Actual Behavior
I get an error that the app has stopped working after Code Push begins to fetch the bundle. ADB log says it's in regards to a createtimer function.

<img width="1190" alt="screen shot 2017-09-23 at 11 13 52 am" src="https://user-images.githubusercontent.com/9807835/30777104-4b192410-a079-11e7-928b-062919164848.png">

Environment

* react-native-code-push version: 1.6.0-beta
* react-native version: 0.36.0 update, 0.33.0 current
* iOS/Android/Windows version: Android 8
* Does this reproduce on a debug build or release build? Release build but only on production.
* Does this reproduce on a simulator, or only on a physical device? Both.

Is there any possible reason an update would crash on Production but would be fine on Staging? I've tried everything. I'm not sure what to do about the createtimer function as it only appears in the bundle.

You can upgrade React Native through Code Push, right? Or do you have to go through the store?

**Comment by max-mironov** [comment]
Hi @TheRohitSharma, you are right, it make sense to update to the latest RN and RNCP if possible. 
And yes, you should go through the store this way, this is required.
As for your issue - as stated in [our compatibility](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms) table RN 0.36 is nit compatible with RNCP 1.6.0.

**Comment by TheRohitSharma** [comment]
@max-mironov 

Sorry, I meant to type 1.16.0-beta, not 1.6.0-beta. That is the code-push version I am using.

I got past that issue, but my issue now is that when you first open the app after installing a binary update, the app crashes on the codepush sync. I verified this by temporarily removing this:

```
@Override
    protected String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }
```

Here is what happens:

I install the update, either through the Play Store or by uploading the updated .apk to my phone, and then I open the app, and it immediately closes after flashing open for a second. The only thing the log shows at this point is: 

``` 
09-25 10:49:36.067 32650 32650 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.channelmobile/files/CodePush/[removed for privacy]/CodePush/index.android.bundle"
```

Then, if I reopen the app, it works fine and is updated. 

<img width="1613" alt="screen shot 2017-09-25 at 10 49 47 am" src="https://user-images.githubusercontent.com/9807835/30818065-266fd42a-a1e0-11e7-9b1d-d295b47a4c80.png">

So you can see that the first line of the log is what shows when the app crashes in the beginning. Everything after that is when I reopen the app. The user shouldn't have to clear their app data or reopen the app after updating. What could the issue be? It's always trying to load the JS bundle from the same exact path: 
```
/data/user/0/com.channelmobile/files/CodePush/[removed for privacy]/CodePush/index.android.bundle
```

**Comment by max-mironov** [comment]
@TheRohitSharma 
The rule of thumb here is that when you produce new binary update you should always increment app version. That really make sense and if you do this old updates which could be possibly incompatible should never be applied again. ([here](https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java#L213) is the logic which handles this situation).
Could you please increment app version, install apk on device and verify if it is working?

**Comment by TheRohitSharma** [comment]
@max-mironov 
I always increment when I'm uploading an alpha, beta, or production release to the Play Store. Where does Code Push expect this to change? The version code in build.gradle and AndroidManifest? Or does it also expect it to change in package.json? Are we strictly referring to "versionCode" when we say "app version" or also "versionName"?

**Comment by max-mironov** [comment]
@TheRohitSharma 
For android you should change `versionName` parameter in app `build.gradle` file.

**Comment by TheRohitSharma** [comment]
@max-mironov
I haven't had any issues since I did this. I thought changing the version code was enough. Thanks for your help!

**Comment by max-mironov** [comment]
Thanks for reply @TheRohitSharma, closing the issue now since it has been resolved.
