### ISSUE TITLE
404: The specified resource does not exist.

### ISSUE THREAD

**Issue by zhaoheqi** [Microsoft/react-native-code-push#1013]
I dont't know what happen

**Comment by max-mironov** [comment]
@zhaoheqi hi, and thanks for reaching us.
Could you please be more specific about your issue, i.e. what you've done/what happens/what you expected to see/your environment etc.
We have a good template [here](https://github.com/Microsoft/react-native-code-push/issues/new), so probably if you could follow this it would be easier for us to determine what happens.

**Comment by max-mironov** [comment]
Closing the issue, will reopen when we'll have more info regarding this.
