### ISSUE TITLE
[Question] Can i add codepush to an already live app?

### ISSUE THREAD

**Issue by shubhnik** [Microsoft/react-native-code-push#1015]
I have published an app to playstore and appstore without codepush. I feel the need to integrate codepush to the apps now. Is it possible to integrate codepush to the live apps now? If possible, than is there any guide to follow?

My RN version 0.43.0.
Thanks 😃

**Comment by sergey-akhalkov** [comment]
Hi @shubhnik, thanks for reaching us. 
You cannot integrate CodePush into existing apps without releasing new binary versions of your apps and publishing them to the stores.
To integrate CodePush into the apps you should do the following:
1. Follow up this guides: [iOS setup](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md), [Android setup](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md)
2. increment your binary app versions both for Android and iOS apps
3. publish your apps to the stores

Please let me know if you have any questions.
