### ISSUE TITLE
Javascript SyncStatus object and TypeScript SyncStatus enum mismatch

### ISSUE THREAD

**Issue by balesz** [Microsoft/react-native-code-push#1016]
The Javascript SyncStatus object and the TypeScript SyncStatus enum definition is different:

JS: https://github.com/Microsoft/react-native-code-push/blob/f5e6de5f4a0cdd7a8b7b4d42d0811fd742521e62/CodePush.js#L544

TS: https://github.com/Microsoft/react-native-code-push/blob/f5e6de5f4a0cdd7a8b7b4d42d0811fd742521e62/typings/react-native-code-push.d.ts#L324

**Comment by sergey-akhalkov** [comment]
Hi @balesz, thanks for pointing to this. I just want to clarify - is that mismatch brakes something? I mean, usually, devs using `SyncStatus` enum this way: 
https://github.com/Microsoft/react-native-code-push/blob/f5e6de5f4a0cdd7a8b7b4d42d0811fd742521e62/Examples/CodePushDemoApp/demo.js#L25
So, do you experiencing the issue while using it in typescript?

**Comment by balesz** [comment]
@sergey-akhalkov
Yes. Completely useless the TypeScript definition, because the wrong order of the names in the enum.

http://www.typescriptlang.org/docs/handbook/enums.html

**Comment by sergey-akhalkov** [comment]
Hi @balesz, the issue has been fixed in https://github.com/Microsoft/react-native-code-push/commit/32a1653e128b919579ca05be5a2a6edad4d7da67
I'm closing this for now, please feel free to reopen if you see any other issues with typings.
