### ISSUE TITLE
Codepush still use old bundle after newer version of the app is installed

### ISSUE THREAD

**Issue by smaradona** [Microsoft/react-native-code-push#1017]
Hello there! I'm having some issues with Codepush and React Native. I use TestFlight and TestFairy to distribute production builds of the app to test users. A few days ago I sent an update through Codepush and the update was successfully installed. That was app version 4.3.0. I did it over Codepush only, not uploading a new binary to TestFlight/Fairy. All worked as expected.

Now I uploaded a new binary with a newer version (4.4.0) of my app to TestFlight/TestFairy and not through Codepush. When I install this new version it all works fine until I restart the app. When I restart the app, the old Codepush bundle with version 4.3.0 is used.

I thought the jsbundle shipped with that binary would take precedence over any CodePush updates downloaded under the old binary version.

This is happening both on Android and iOS.

* react-native-code-push version: 1.17.3-beta
* react-native version: 0.40.0
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? I've only tested it on a physical device

**Comment by max-mironov** [comment]
Hello @smaradona! Yep, binary update should take precedence over any CodePush updates unless old code push update is not targeting multiple binary versions.
Could you share the output of `code-push deployment history <appName> <deploymentName>` with us?

**Comment by smaradona** [comment]
That's exactly what was going on! The update was done with *, to any device configured to consume updates from your CodePush app. So, if I do now a new Codepush update targeted specifically to 4.3.0, if I then install 4.4.0 via TestFlight/TestFairy the app shouldn't use that Codepush update, right? Thanks a lot for your help!

**Comment by max-mironov** [comment]
@smaradona yeah that should work! Also you can just disable this update targeting '*' versions.

**Comment by smaradona** [comment]
Awesome! Thank you very much! 👍

**Comment by max-mironov** [comment]
Great :) I'll close the issue as it seems to be resolved, feel free to reach us if you need any help with code-push.

**Comment by amanthegreatone** [comment]
seeing similar behaviour https://stackoverflow.com/questions/46613103/codepush-updating-a-newly-installed-app
