### ISSUE TITLE
Failing signature check on iOS 9.3, working on iOS 10.3

### ISSUE THREAD

**Issue by vintercider** [Microsoft/react-native-code-push#1021]
For some reason, update signature verification fails on iOS 9.3. It fails on Release and Debug builds on a real device and on a simulator. It is working on a 10.3 simulator.

I'm getting following log events.

`2017-09-27 22:33:48.457 TestApp[55907:6252813] 
[CodePush] Applying full update.
2017-09-27 22:33:48.458 TestApp[55907:6252813] 
[CodePush] Verifying hash for folder path: /Users/johndoe/Library/Developer/CoreSimulator/Devices/CC2C18EB-28EE-4FDE-A670-DBD3F4A96982/data/Containers/Data/Application/69705261-E679-45A9-A682-2BB20A4A7690/Library/Application Support/CodePush/088bcf512618474c43725cba827ec7608933f39f1d3617e7953927b70468bbaa
2017-09-27 22:33:48.473 TestApp[55907:6252813] 
[CodePush] Manifest string: (
    "CodePush/assets/app/images/arrow_left.png:276b8d4abff1c4f1892621f46e155bd0efac1a3850ecbf20599d12fd815de752",
    "CodePush/assets/app/images/ic_calender.png:1e703073df749df5003d976abaeb214e229127a1c658568454bc141464721729",
    "CodePush/assets/app/images/ic_check_box.png:58b0914817b4f69ac5cb42d8845acd361c5db0d33118611e756a632878abd89c",
    "CodePush/assets/app/images/ic_check_box_outline_blank.png:b880634b2f5262f3995d8310663ac015d273c532f2d341382be9ab91956333e2",
    "CodePush/assets/app/images/ic_menu_delete.png:e151fc60f21a1d93ea9b747fe19c5d831e5f8df3108409e88a14d4d82c0e1027",
    "CodePush/assets/app/images/login_bg.png:7dae2bceeebc8359732dcb1d2caf7bf8f19678ebfc42050b1cb12f494c6a7644",
    "CodePush/assets/app/images/logo.png:b490cda1c95bb648de3603844a1360e98fc6efa104242c1992ff748ee2f32bf7",
    "CodePush/assets/app/images/overflow.png:21db99eb9d63585910d0ac25b83958888ffcb6a7ac881c34ff1edb790e9af3ea",
    "CodePush/assets/app/images/splash_screen_logo.png:263ffd986592f368464a230f8226a0c6bc01acba251567fecdc76252bb8d6a02",
    "CodePush/assets/node_modules/react-native-datepicker/date_icon.png:6a7b6423bb29810ad371a1fe11efad99dc32b61a4e65d4c84bf57723e6460652",
    "CodePush/main.jsbundle:36d532b4692680341a4a317438e9e80f44ef1c0cb43d400179065f5c26565710",
    "CodePush/main.jsbundle.meta:7b6fc4992c408e6e5f279cdb9c8078cf143a7690f2c6dc210666838f166bda38"
)
2017-09-27 22:33:48.474 TestApp[55907:6252813] 
[CodePush] Expected hash: 088bcf512618474c43725cba827ec7608933f39f1d3617e7953927b70468bbaa, actual hash: 088bcf512618474c43725cba827ec7608933f39f1d3617e7953927b70468bbaa
2017-09-27 22:33:48.474 TestApp[55907:6252813] 
[CodePush] The update contents succeeded the data integrity check.
2017-09-27 22:33:48.474 TestApp[55907:6252813] Verifying signature for folder path: /Users/johndoe/Library/Developer/CoreSimulator/Devices/CC2C18EB-28EE-4FDE-A670-DBD3F4A96982/data/Containers/Data/Application/69705261-E679-45A9-A682-2BB20A4A7690/Library/Application Support/CodePush/088bcf512618474c43725cba827ec7608933f39f1d3617e7953927b70468bbaa
2017-09-27 22:33:48.479 TestApp[55907:6252813] 
[CodePush] The update could not be verified because it was not signed by a trusted party. Error Domain=io.jwt Code=-97 "Invalid signature! It seems that signed part of jwt mismatch generated part by algorithm provided in header." UserInfo={errorDescription=JWTInvalidSignatureError, NSLocalizedDescription=Invalid signature! It seems that signed part of jwt mismatch generated part by algorithm provided in header.}
2017-09-27 22:33:48.480 TestApp[55907:6252813] 
[CodePush] The update contents failed code signing check.`

* react-native-code-push version: 5.0.0-beta
* react-native version: 0.47.1
* iOS/Android/Windows version: 9.3
* Does this reproduce on a debug build or release build? BOTH
* Does this reproduce on a simulator, or only on a physical device? BOTH

**Comment by max-mironov** [comment]
Hello @vintercider thanks for letting us know. Indeed there is an issue with iOS 9. We're using [this](https://github.com/yourkarma/JWT) library to verify JWT on iOS and it appears that it fails to execute correctly at the following lines:
https://github.com/yourkarma/JWT/blob/a8829959acd7fbc79bdb47f433e3b9243e1c304f/Core/Algorithms/RSFamily/RSKeys/JWTCryptoSecurity.m#L111

Unfortunately all iOS devices that uses iOS9 will be unable to use code signing feature correctly at that moment.  Though the number of devices with this version of iOS is less than 5% we will try to find out how to overcome this problem.

**Comment by max-mironov** [comment]
Hi @vintercider this issue is fixed in [5.1.3-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v5.1.3-beta) release, could you please verify and let us know if it works for you.
