### ISSUE TITLE
[Android] Update is Invalid (React Native 0.48)

### ISSUE THREAD

**Issue by FredyC** [Microsoft/react-native-code-push#1025]
> Update is invalid - A JS bundle file named "index.android.bundle" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.

### Expected Behavior
I don't understand what's wrong here. Why would be bundle name different? I am not renaming bundle in any way. In the `MainApplication` I do have recommended code...

```
    @Override
    protected String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }
```

### Actual Behavior
```
$ code-push release-react APPNAME android --mandatory
Detecting android app version:

Using the target binary version value "1.0" from "android\app\build.gradle".

Running "react-native bundle" command:

node node_modules\react-native\local-cli\cli.js bundle --assets-dest D:\users\DARKMA~1\AppData\Local\Temp\CodePush --bundle-output D:\users\DARKMA~1\AppData\Local\Temp\CodePush\index.android.bundle --dev false --entry-file index.android.js --platform android
Scanning 1014 folders for symlinks in D:\workspace\app\node_modules (69ms)
Scanning 1014 folders for symlinks in D:\workspace\app\node_modules (78ms)
Loading dependency graph, done.
bundle: start
bundle: finish
bundle: Writing bundle output to: D:\users\DARKMA~1\AppData\Local\Temp\CodePush\index.android.bundle
bundle: Done writing bundle output
bundle: Copying 63 asset files
bundle: Done copying assets

Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
Successfully released an update containing the "D:\users\DARKMA~1\AppData\Local\Temp\CodePush" directory to the "Staging" deployment of the "APPNAME" app.
Done in 111.83s.
```

```
$ code-push debug android
Listening for android debug logs (Press CTRL+C to exit)
[09:41:59] Loading JS bundle from "assets://index.android.bundle"
[09:42:01] Sync already in progress.
[09:42:01] Checking for update.
[09:42:02] Reporting binary update (1.0)
[09:42:08] Downloading package.
[09:42:19] An unknown error occurred.
[09:42:19] Update is invalid - A JS bundle file named "index.android.bundle" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.
[10:00:05] Checking for update.
[10:00:06] An update is available, but it is being ignored due to having been previously rolled back.
[10:00:06] App is up to date.
```

### Reproducible Demo

Sadly, since I am on Windows, I was not able to use an example to create demo. It has been failing because of some iOS related stuff. However, I tried to make a new app from scratch with just CodePush added and that one is working smoothly. Only my actual app is giving out kicks for some unclear reason.

### Environment

* react-native-code-push version: 5.1.2-beta
* react-native version: 0.48.3
* Android version: 6
* Does this reproduce on a debug build or release build? 
  * Release build, I have codepush disabled for debug using `__DEV__` variable
* Does this reproduce on a simulator, or only on a physical device?
  * Both

(The more info the faster we will be able to address it!)

**Comment by FredyC** [comment]
Ok, I have figured it out and I feel somewhat stupid. The problem was that I copy pasted iOS deployment key to the Android build :)

The error message it kept giving me is rather misleading on this matter. Especially when I am rookie on all this stuff. It could be perhaps improved by logging contents of failing release or even giving a link for downloading that release to verify what might be wrong.

**Comment by sergey-akhalkov** [comment]
Hi @FredyC, thanks for reaching us.
In our docs we have the following point:
>Note, if you are targeting both platforms it is recommended to create separate CodePush applications for each platform.

Probably we should change `recommended` word to `needed` one, also I believe we should change our log message to display the fact that the error can have place due to using the same deployment key both for android and ios, what do you think?

**Comment by FredyC** [comment]
@sergey-akhalkov Thanks for a quick reply.

To me it was kinda obvious there need to be two apps, it's kinda clear from [the main site ](http://microsoft.github.io/code-push/) step 3 where the platform is required argument. I am also using Mobile Center which corresponds to same apps so nothing surprising there.

What misled me here was simply the log message stating there is a bundle missing from the deployment. It's not really super obvious it might be a deployment from another platform. As I said, it would help if I could see actual contents of deployment somewhere. Or at least extend the error message and give out hint to verify deployment key.

**Comment by sergey-akhalkov** [comment]
@FredyC, to see the content of update package you could use `checkForUpdate` method - received metadata will contain `blobUrl` that actually maps to the update zip archive, so you can download it, unzip and verify its content.

**Comment by FredyC** [comment]
Ah, that's helpful, haven't noticed that. Thanks. Still, I think it's worth it to update error message to at least suggest checking that deployment key for a correct platform is used.
