### ISSUE TITLE
updateCheck call stuck and returns 503

### ISSUE THREAD

**Issue by feiyingx** [Microsoft/react-native-code-push#1028]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
Dont have an exact repro yet, but it happens frequently enough that we are becoming concerned and need to find the cause/resolution for this.

1. We call `codePush.sync` when our app boots which goes through the different statuses of: CHECKING_FOR_UPDATE, DOWNLOADING_PACKAGE, INSTALLING_UPDATE, UPDATE_TO_DATE. 

2. However recently we've noticed that our users have been reporting that they are getting stuck on our update screen which is when we are doing the code push syncing. So we dug into the network calls and noticed that the call to check for update `https://codepush.azurewebsites.net/updateCheck` sometimes would get stuck for up to 1-2 minutes and then finally return `503 Service Unavailable`. 

Please advise on what may be causing this issue and also what are some suggested approaches to handle this. One idea we had internally was to have a timer that just times out and force skips the sync if the sync process exceeds a certain time limit. Would love to hear the team's thoughts.

Thanks for your help.

### Environment

* react-native-code-push version: 2.1.0-beta
* react-native version: 0.44.3
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device? On both simulator and physical device

(The more info the faster we will be able to address it!)

**Comment by sergey-akhalkov** [comment]
Hi @feiyingx , please take a look at [this response ](https://github.com/Microsoft/code-push/issues/511#issuecomment-328940251) regarding this issue. Sorry for the inconvenience and thanks for the patience.

**Comment by feiyingx** [comment]
Got it thanks @sergey-akhalkov ! So sounds like other users have taken a similar approach to use some kind of timer. In that ticket, it says that the code push team is working on a fix and will be implemented within the next 30 days, would love to get a quick status update on whether that's still on target and it's something we can safely expect to be resolved soon. Thanks!

**Comment by pniko** [comment]
Hi @feiyingx, we got a bit backlogged working on the new CodePush service and code-signing features, but are still underway. We are wrapping up creating the management service so CLI users won't run into 503's during releases, but are a bit behind on the service responsible for handling device checkins. Realistic timeframe would be towards the end of the year for everything to be finished. The timer approach is your best bet for now, but rest assured we are working to have this nailed down and resolved asap. Thanks!

**Comment by sergey-akhalkov** [comment]
Hey guys, let's continue discussion in the common place https://github.com/Microsoft/code-push/issues/547 due to the issue affects not React Native users only.
