### ISSUE TITLE
[Question] Do I have to make a code-push update when I do a binary update?

### ISSUE THREAD

**Issue by joarwilk** [Microsoft/react-native-code-push#1029]
Let's say I make some changes to my code push integrated app, archive it and then release it as an updated binary on the app store. I do not make a code push release containing these new changes. When a new user downloads the app, will he run the latest code that was bundled with the binary or will he run an older release from code push? Do I have to make sure to always couple a code push release with every binary release?

Not a problem, just want to know.

**Comment by max-mironov** [comment]
Hi @joarwilk, so in general when you do new AppStore release (with binary update) you should always increment AppVersion. So this way old codepush updates will not be applied (of course if you do not change target binary version of the codepush release manually to something line `*`). 
With this workflow you should never worry about old codepush updates and also as far as your new app version would contain latest code there is no need to apply any of old updates.
Please let me know if you have more questions or something is unclear.

**Comment by joarwilk** [comment]
@max-mironov This answers my question. Thank you.

**Comment by max-mironov** [comment]
@joarwilk np, you are welcome :)
