### ISSUE TITLE
Rolling out an update takes more time than expected

### ISSUE THREAD

**Issue by joarwilk** [Microsoft/react-native-code-push#1030]
After I make a new release with code push it takes upwards an hour (more commonly in the 5-10 minutes range) before devices start getting the update. I have set the sync mode to ON_APP_RESUME, but it doesnt seem to do anything even if I completely restart the app. Usually I have to leave it for 10-30 minutes before it registers that there is an update and starts downloading it. Nothing in the console output as far as I can see. Is this expected or is something not right? How can I debug this? Thanks

**Comment by max-mironov** [comment]
Hi @joarwilk, probably you could inspect your app network calls to see what's going on. Yesterday we have a temporary problem with service availability (please see #1028) and I think that it could be the reason of your issue. 
Do you still have problems with updates?

**Comment by max-mironov** [comment]
Closing this issue as seems to be relative to #1028, please let us know if any further questions.

**Comment by joarwilk** [comment]
@max-mironov Sorry, forgot to reply. Yes that was most likely it, thanks!
