### ISSUE TITLE
Patching/TargetBinaryVersion doesn't work as expected

### ISSUE THREAD

**Issue by el-lsan** [Microsoft/react-native-code-push#1031]
### Steps to Reproduce
1. My old `versionName` (`/android/app/build.gradle`) was `4.0.1` and `TargetBinaryVersion` for code-push was `>=4.0.1`
2. Then I updated `versionName` to `4.1.0` and patched `TargetBinaryVersion` using` code-push patch app-name Production --targetBinaryVersion "4.0.1"` and here's the output of code-push history:
![image](https://user-images.githubusercontent.com/1249548/31169672-b1aa3ca4-a8f9-11e7-8aa0-1d3c9c056a3b.png)

### Expected Behavior
I'm expecting that latest build won't get pushed by the old bundle and only `4.0.1` version of the app get affected.

### Actual Behavior
The new build (`4.1.0`) is overridden by the old bundle (`4.0.1`) . Even disabling (` code-push patch app-name Production --disabled true`) couldn't help. As well as changing `targetBinaryVersion` to other values, like `<=4.0.1`. 

Even though all the metadata for production and staging are matched:
![image](https://user-images.githubusercontent.com/1249548/31170339-ffa1945a-a8fb-11e7-8ef2-3b640b63d9c4.png)

This issue only happen on release build.

### Environment

* react-native-code-push version: ^1.17.4-beta
* react-native version: ^0.42.3
* Android version: 6-7
* Does this reproduce on a debug build or release build? release build only
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by sergey-akhalkov** [comment]
Hi @el-lsan, thanks for reaching us.
If I get your use case right - the behavior you are experiencing is expected. Actually, [CodePush uses semver for check target binary version conditions](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter), and condition `4.1.0 >= 4.0.1` is true for semver check. That is the reason why the update targeting to 4.0.1 has been applied to app having version 4.1.0

To fix the issue you should disable or patch all releases that have no an upper bound.

Please let me know if you have any questions.

**Comment by el-lsan** [comment]
@sergey-akhalkov Thanks for your hint. 
After changing `targetBinaryVersion` of all old releases, it worked as I was expecting.
