### ISSUE TITLE
Confused about versioning

### ISSUE THREAD

**Issue by GregTheGreek** [Microsoft/react-native-code-push#1033]
I'm a bit puzzled at how versioning is controlled.

Let's say I have iOS & Android deployed at versions 1.1.0
I make some code push changes....
and
Now let's say we upgrade both to version to 1.2.0
If I do a code push everyone who stayed at version 1.1.0 is receiving the 1.2.0 updates.
Is there a way to prevent this?

**Comment by sergey-akhalkov** [comment]
Hi @GregTheGreek, thanks for reaching us, please take a look at target binary version chapter - it should resolve your problem. 

Please let me know if you have any other questions.

**Comment by max-mironov** [comment]
@GregTheGreek please let us know if you have a chance to look at this?

**Comment by max-mironov** [comment]
Closing this for now, please reopen or let us know if any questions.
