### ISSUE TITLE
Typings are wrong for default export

### ISSUE THREAD

**Issue by esprehn** [Microsoft/react-native-code-push#1036]
### Steps to Reproduce
1. The typings have "export default CodePush;"
2. So you write `import CodePush from 'react-native-code-push'`
3. Try compiling your app in commonjs mode.
4. Runtime error because CodePush.default is not defined.
5. So you write `import CodePush = require('react-native-code-push')`
6. Compile time error because CodePush is not the right type.

### Expected Behavior
Should work in commonjs mode.

I think the typings want `exports = CodePush;` since that's what the code actually does as `module.exports = CodePush;`. It does not use ES6 modules with default exports, so having `export default` in the typings produces error messages in tsc.

**Comment by ruslan-bikkinin** [comment]
hi @esprehn ans thanks for reaching us! Please try to replace 
```javascript
import CodePush from 'react-native-code-push'
```
with
```javascript
let CodePush = require('react-native-code-push').default
```
and double check that you've been correctly configured code-push SDK on native side for you app (otherwise CodePush wouldn't be initialized on client side and `CodePush` variable will be equal to `undefined`).

Please, let us know if it helps you.

**Comment by ruslan-bikkinin** [comment]
@esprehn did you have a chance to look at this?

**Comment by ruslan-bikkinin** [comment]
So I am closing this for now due to prolonged absence of response, please, feel free to reopen this if needed.

**Comment by kg-currenxie** [comment]
`let CodePush = require('react-native-code-push').default` just gives me an `any` type, as well as making the enums not working `CodePush.SyncStatus`

2 years later... most projects/codebases now use `import`s.
`import codePush from 'react-native-code-push'` should work imo..

**Comment by JHPG** [comment]
`import { default as codePush } from 'react-native-code-push';` seems to work.
