### ISSUE TITLE
[iOS] Release build crash "Something went wrong. Please verify if generated JS bundle is correct"

### ISSUE THREAD

**Issue by omeraplak** [Microsoft/react-native-code-push#1040]
Debug build on an iOS device works fine.

A release build crashes throws RCTFatal from CodePush.m

2017-10-10 14:43:08.994 [fatal][tid:main] Something went wrong. Please verify if generated JS bundle is correct. 
2017-10-10 14:43:09.001275+0300 MyApp[1574:603067] Something went wrong. Please verify if generated JS bundle is correct.
2017-10-10 14:43:09.010640+0300 MyApp[1574:603067] *** Terminating app due to uncaught exception 'RCTFatalException: Something went wrong. Please verify if generated JS bundle is correct. ', reason: 'Something went wrong. Please verify if generated JS bundle is correct. '
*** First throw call stack:
(0x186617d38 0x185b2c528 0x186617c80 0x1012c3858 0x10120b4dc 0x10120a9c4 0x1011a4008 0x18fa97050 0x18fc8a898 0x18fc8f6e4 0x18ff1d454 0x1901ed1f0 0x18ff1d0b8 0x18ff1d928 0x1906866e8 0x19068658c 0x1904029c0 0x190597fc8 0x190402870 0x1901ec850 0x18fc8de28 0x1900916ec 0x188cb9768 0x188cc2070 0x101e4d45c 0x101e59b74 0x188ceda04 0x188ced6a8 0x188cedc44 0x1865c0358 0x1865c02d8 0x1865bfb60 0x1865bd738 0x1864de2d8 0x18836ff84 0x18fa8b880 0x1011a45b0 0x18600256c)
libc++abi.dylib: terminating with uncaught exception of type NSException

Environment

react-native-code-push version: 5.1.3-beta

react-native version: 0.48.2

iOS 10 and iOS 11

Xcode 8 and Xcode 9

Reproduce on Release build ONLY

Reproduce on both iOS Simulator and Physical device

I am using Podfile to install Amplitude-iOS and Mixpanel

The xcode project shows libCodePush.a is being linked.

Running react-native link react-native-code-push did not help.

Could not determine correct xcode proj path to retrieve related plist file, there are multiple xcodeproj under the solution.

find ios -name '*.xcodeproj'
ios/MyApp.xcodeproj
ios/Pods/Pods.xcodeproj

ios/MyApp.xcworkspace

**Comment by ruslan-bikkinin** [comment]
Hello @omeraplak and thanks for your question. 

Please verify if you are able to build main.jsbundle file using following command:
`react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle`.
If so, could you please provide me with content of AppDelegate.m file?

**Comment by omeraplak** [comment]
Hello @ruslan-bikkinin and thanks for your answer.

I understand this case. Totally my mistake. i separated CI and development build pipeline and used  difference configs. I forgot this pipeline. I fix it. 
Thanks,
Ömer

**Comment by ruslan-bikkinin** [comment]
@omeraplak glad to here your issue is resolved. Feel free to come back if you will have any more issues or questions.

**Comment by youngjuning** [comment]
```bash
react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle
```

now, rn has no index.ios.js
