### ISSUE TITLE
[IOS] Unexpected behavior of silent update on ios11

### ISSUE THREAD

**Issue by wack17s** [Microsoft/react-native-code-push#1041]
### Steps to Reproduce
1. make release-react
2. close the app to background
3. open it from background
4. w8 for update
5. kill the app
6. open it again

### Expected Behavior
To have a last build of js bundle

### Actual Behavior
We have prev build on open and then the app updates again (blinking)

### Reproducible Demo

video: https://drive.google.com/open?id=0B-YxdSCgiYefNzhZUmVIU3VNdW8

### Code
```
export default codePush({
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.IMMEDIATE
})(App);
```

### Environment

* react-native-code-push version: 5.1.3-beta (same on 3.0.1-beta)
* react-native version: 0.49.3 (same on 0.45.1)
* iOS/Android/Windows version: 11.0.1
* Does this reproduce on a debug build or release build? - Release
* Does this reproduce on a simulator, or only on a physical device? - Real device

#### Prev version of ios work fine.
On ios 10.3 it works perfect. One update of js and then after killing and re-opening the app i had last version of js without any blinking.

### Update
Looks like it's expected behavior and not depends of ios version. I made demo on iphone 5s, but iphone 7 with ios11 work ok too.

**Comment by ruslan-bikkinin** [comment]
@wack17s thanks for submitting issue. I tried to reproduce your problem on simulator using our demo project, but it is working without troubles. Could you please confirm that issue is reproducing only on real device?

**Comment by wack17s** [comment]
@ruslan-bikkinin Yeap, simulator works fine. I suppose that this issue depends on device hardware, because iphone 7 works fine too. As i said, demo was made on iphone 5s.

**Comment by ruslan-bikkinin** [comment]
@wack17s very strange. Could you please share with us any logs producing by your test application (app log on device, app log in xcode)?

**Comment by ruslan-bikkinin** [comment]
@wack17s just a friendly ping on this.

**Comment by wack17s** [comment]
@ruslan-bikkinin sry for delay, i just made video with logs from debug version, but in debug it overrides changes from RN server. Do i have to load this video or is any other way to take logs from release build or something else i can do?

**Comment by ruslan-bikkinin** [comment]
@wack17s thanks for your response! You can always collect logs from Xcode no matter what mode you've been used to compile application (debug or release). If you are using real device all you need is to follow these steps:

1. Connect device to mac
2. Select Window -> Devices.
3. Select your device in the left panel.
4. Click the little arrow as shown in the screenshot below.
![logs from device](https://i.stack.imgur.com/acpO7.png)
5. Do some stuff on device
6. Click `Save console` button and send us output.

**Comment by sergey-akhalkov** [comment]
Hi @wack17s, I'm closing this for now, please feel to reopen if you have a chance to take a look at the message above.
