### ISSUE TITLE
[IOS] Rollback after closing app (iOS 11)

### ISSUE THREAD

**Issue by ViraRodionova** [Microsoft/react-native-code-push#1042]
### Steps to Reproduce
1. Install app and open
2. Close the app to background
3. Open the app from background
4. Wait for updates
5. Kill the app
6. Reopen the app

### Expected Behavior
After reopen: to have a last build of js bundle

### Actual Behavior
After reopen: we have bundle from build

### Code

```
export default codePush({
    checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
    installMode: codePush.InstallMode.ON_NEXT_SUSPEND
})(App);
```

### Environment

* react-native-code-push version: 3.0.1-beta
* react-native version: 0.45.1
* iOS version: 11
* Does this reproduce on a debug build or release build? - Release
* Does this reproduce on a simulator, or only on a physical device? - Physical device

**Comment by max-mironov** [comment]
@ViraRodionova sorry, could you please check if is is a duplicate case for https://github.com/Microsoft/react-native-code-push/issues/1041 or not?

**Comment by ViraRodionova** [comment]
No it isn't a duplicate, but it is related to each other.

**Comment by ViraRodionova** [comment]
We found the problem: just didn't set getting js bundle from codepush while manual linking, react-native link react-native-code-push fix this

**Comment by phongbksneep** [comment]
> We found the problem: just didn't set getting js bundle from codepush while manual linking, react-native link react-native-code-push fix this

Still roll back, on rn 0.59.9 and code push 0.57.0
