### ISSUE TITLE
App no updating after update is available

### ISSUE THREAD

**Issue by percyz** [Microsoft/react-native-code-push#1043]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.React Native:0.45.1  Code Push:3.0.1-beta for android:5
2.code-push release-react <myAppName> android, get following info:

Detecting android app version:
Using the target binary version value "1.0" from "android\app\build.gradle".
Running "react-native bundle" command:
...
Loading dependency graph, done.
bundle: start
bundle: finish
bundle: Writing bundle output to: C:\Users\...\AppData\Local\Temp\CodePush\index.android.bundle
bundle: Done writing bundle output
Releasing update contents to CodePush:
Successfully released an update containing the "C:\Users\..." directory to the "Staging" deployment of the "project..." app.

No progress bar at this step??

3. Change some text on frontend, run "react-native run-android", then get prompt message but nothing get changed. 

### Expected Behavior
The code should be updated

### Actual Behavior
There is a prompt message about "update is available...", I click install, then app reloaded but nothing gets updated.
```
  STACK TRACE AND/OR SCREENSHOTS
```
My MainApplication.java:

```
import android.app.Application;
import com.airbnb.android.react.maps.MapsPackage;
import com.facebook.react.ReactApplication;
import com.microsoft.codepush.react.CodePush;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.eguma.barcodescanner.BarcodeScannerPackage;
import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new BarcodeScannerPackage(),
            new CodePush("xo...", MainApplication.this, BuildConfig.DEBUG),
              new MapsPackage()
      );
    }
  };
  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }
  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```
Code for frontend:
```
  componentDidMount() {
    CodePush.sync({ updateDialog: true, installMode: CodePush.InstallMode.IMMEDIATE },
    console.log("Status:",status),
      (status) => {
        switch (status) {
          case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
            this.setState({ showDownloadingModal: true });
            this._modal.open();
            break;
          case CodePush.SyncStatus.INSTALLING_UPDATE:
            this.setState({ showInstalling: true });
            break;
          case CodePush.SyncStatus.UPDATE_INSTALLED:
            this._modal.close();
            this.setState({ showDownloadingModal: false });
            break;
          default:
            break;
        }
      },
      ({ receivedBytes, totalBytes }) => {
        this.setState({ downloadProgress: (receivedBytes / totalBytes) * 100 });
      }
    );
  }
```
code-push deployment history codePushTest Staging

```
│ Label │ Release Time │ App Version │ Mandatory │ Description │ Install Metrics       │
│ v1    │ 3 hours ago  │ 1.0         │ No        │             │ Active: 0% (0 of 1)    │ Total: 1             │
│ v2    │ 2 hours ago  │ 1.0         │ No        │             │ Active: 0% (0 of 1)   │ Total: 1              │
│ v3    │ 2 hours ago  │ 1.0         │ No        │             │ Active: 0% (0 of 1)   │ Total: 1              │
...
```
### Environment
*React Native:0.45.1  Code Push:3.0.1-beta for android:5
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? physical

(The more info the faster we will be able to address it!)

**Comment by ruslan-bikkinin** [comment]
Hi, @percyz and thanks for reaching us. We have explanation for this behavior in our documentation is this [section](https://github.com/Microsoft/react-native-code-push#releasing-updates):

> NOTE: CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply.

If you want to test CodePush updates in debug mode, despite everything, you need to set 
```
project.ext.react = [
...
        bundleInDebug: true
]
```
in `app/build.gradle`.

Please let us know if it helps you.

**Comment by percyz** [comment]
Hi, @ruslan-bikkinin thanks for your reply.
I tried what you suggested, and there was no error but nothing was getting changed, (exact problem as before) where it says there is an update and when I accept it - nothing changes. I was thinking the issue could be that It is not uploading correctly, Is there anyway for me to check what is being uploaded correctly?

**Comment by ruslan-bikkinin** [comment]
@percyz Could you please release new update for your app, then install it on device and share app logs with us (from logcat or android studio)?

**Comment by ruslan-bikkinin** [comment]
Hello again, @percyz, just a friendly ping on this.

**Comment by percyz** [comment]
Hi @ruslan-bikkinin , many thanks for your help! As you said, it's not working for debug version, but it's working well for my release version.
Thank you again!

**Comment by ruslan-bikkinin** [comment]
I am glad your problem is resolved, so I'am closing this issue for now, please reopen if will have any more questions.

**Comment by jinghun1999** [comment]
`buildTypes {
        debug {
            applicationIdSuffix ".debug"
            // Note: CodePush updates should not be tested in Debug mode as they are overriden by the RN packager. However, because CodePush checks for updates in all modes, we must supply a key.
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }
        releaseStaging {
            buildConfigField "String", "CODEPUSH_KEY", '"Tav4hMqdxSed61fbdc-e98a-4455-aa57-e9c3d4d56d92"'
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
            buildConfigField "String", "CODEPUSH_KEY", '"w2LsMpJH721Rv8uyued61fbdc-e98a-4455-aa57-e9c3d4d56d92"'
        }
    }`

as the same question, my release version works well,but how can i test the staging version, my staging version wasn't update for any device. i want to test the push code first ,but now i can't test it with any version

**Comment by jinghun1999** [comment]
`buildTypes { debug { applicationIdSuffix ".debug" // Note: CodePush updates should not be tested in Debug mode as they are overriden by the RN packager. However, because CodePush checks for updates in all modes, we must supply a key. buildConfigField "String", "CODEPUSH_KEY", '""' } releaseStaging { buildConfigField "String", "CODEPUSH_KEY", '"Tav4hMqdxSed61fbdc-e98a-4455-aa57-e9c3d4d56d92"' } release { minifyEnabled enableProguardInReleaseBuilds proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro" signingConfig signingConfigs.release buildConfigField "String", "CODEPUSH_KEY", '"w2LsMpJH721Rv8uyued61fbdc-e98a-4455-aa57-e9c3d4d56d92"' } }`

**Comment by sergey-akhalkov** [comment]
Hi @jinghun1999, please take a look at https://github.com/Microsoft/react-native-code-push/issues/991#issuecomment-328074153 , there you can find the working example.
