### ISSUE TITLE
React native 0.49 compability on Android

### ISSUE THREAD

**Issue by omeraplak** [Microsoft/react-native-code-push#1048]
### Steps to Reproduce
1. install react-native 0.49
2. react native has breaking change on index.[android|ios].js file to only index.js [(Release note)](https://github.com/facebook/react-native/releases/tag/v0.49.0)

### Expected Behavior
CodePush.getJSBundleFile(); can want entry file name. For 0.49 and <0.49 RN versions.

### Actual Behavior
What actually happens?
```
Cannot find entry file index.android.js in any of the roots.
```
### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.49.3 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app.

### Environment

* react-native-code-push version: 5.1.3-beta
* react-native version: 0.49.3
* iOS/Android/Windows version: 
Only Android
* Does this reproduce on a debug build or release build? 
All
* Does this reproduce on a simulator, or only on a physical device? 
All

**Comment by ruslan-bikkinin** [comment]
Hi, @omeraplak and thanks for submitting this issue. It seems to be a bug in example app, thanks for pointing to this, I'll we fix it soon!

**Comment by max-mironov** [comment]
Hey @omeraplak we have updated [CodePushDemoApp](https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp) to latest RN49 and verified that it works. Thanks for letting us know.

**Comment by jay1337** [comment]
@max-mironov What about the documentation here https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-android---manual ?

**Comment by max-mironov** [comment]
@jay1337 - sorry, probably I've missed something. Do you see anything wrong with this?

**Comment by jay1337** [comment]
@max-mironov Look at the last changes in Examples/CodePushDemoApp/android/app/src/main/java/com/codepushdemoapp/MainApplication.java : https://github.com/Microsoft/react-native-code-push/commit/c43b0b16ce27c97f86ba7dee4ef525d3f69c1df3#diff-33381e96e8d64db4b13e3e3e9b8e9c16

There is a new `getJSMainModuleName` function.

**Comment by max-mironov** [comment]
@jay1337 - fixed (https://github.com/Microsoft/react-native-code-push/commit/3bce5a1100d5da7c236315217317d7ea1e0851b4), thanks for pointing!
