### ISSUE TITLE
IOS failure - Something went wrong. Please verify if generated JS bundle is correct. 

### ISSUE THREAD

**Issue by valinaga** [Microsoft/react-native-code-push#1049]
### Steps to Reproduce
1. run project in release mode 

### Expected Behavior
What you expected to happen?
should work

### Actual Behavior
fails at start with:

```
2017-10-14 19:54:18.694 [fatal][tid:main] Something went wrong. Please verify if generated JS bundle is correct. 
2017-10-14 19:54:18.696913+0300 up[55982:833336] Something went wrong. Please verify if generated JS bundle is correct.
2017-10-14 19:54:18.717443+0300 up[55982:833336] *** Terminating app due to uncaught exception 'RCTFatalException: Something went wrong. Please verify if generated JS bundle is correct. ', reason: 'Something went wrong. Please verify if generated JS bundle is correct. '

```
### Environment

JavaScript
  node               7.7.2        /usr/local/bin/node
  npm                5.4.2        /usr/local/bin/npm
  yarn               0.27.5       /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.47.2

iOS
  xcode              9.0
(The more info the faster we will be able to address it!)

**Comment by omeraplak** [comment]
Hello @valinaga ,

Please verify if you are able to build main.jsbundle file using following command:
react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle.
If so, could you please provide me with content of AppDelegate.m file?

**Comment by valinaga** [comment]
@omeraplak 
The issue appeared after a RN update to 0.47.2. Actually the Bundle React Native code and images phase vanished from XCode.
I added this to XCode build phases and now it's ok.
`
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
`
I reinstalled rn-code-push and it's ok now.
thanks.

**Comment by berakoccc** [comment]
> [@omeraplak](https://github.com/omeraplak) The issue appeared after a RN update to 0.47.2. Actually the Bundle React Native code and images phase vanished from XCode. I added this to XCode build phases and now it's ok. `export NODE_BINARY=node ../node_modules/react-native/scripts/react-native-xcode.sh` I reinstalled rn-code-push and it's ok now. thanks.

I also did remove the `Bundle React Native code and images` phase and adding this line do the trick.
