### ISSUE TITLE
codePush.SyncStatus.UNKNOWN_ERROR

### ISSUE THREAD

**Issue by duoduo2012** [Microsoft/react-native-code-push#1050]
android 端 code push 热更新时 出现 codePush.SyncStatus.UNKNOWN_ERROR

**Comment by max-mironov** [comment]
Hey @duoduo2012, please follow the [issue template](https://github.com/Microsoft/react-native-code-push/issues/new) so we could be able to help you with your issue.

**Comment by max-mironov** [comment]
Closing the issue, please resubmit with provided template from above when you get a chance.
