### ISSUE TITLE
White flashes after releasing new update 

### ISSUE THREAD

**Issue by danieldelouya** [Microsoft/react-native-code-push#1053]
### Steps to Reproduce
1. IPA/APK file identical to latest code on CodePush = everything works fine
2. I release some changes via Code Push, which results in white flashes after loading loading view, and white flashes when navigating between views. ([React Navigation](https://reactnavigation.org/)).
3. This wont go away ever again unless i create a new IPA/APK file with the code == the code on CodePush. 

### Expected Behavior
What you expected to happen?
Expected it to work.

### Actual Behavior
What actually happens?
Doesn't work as described above. 

### Environment
* react-native-code-push version: 5.1.3-beta
* react-native version: 0.49.3
* iOS/Android/Windows version: iOS 11.1
* Does this reproduce on a debug build or release build? Release build.
* Does this reproduce on a simulator, or only on a physical device? Both.

**Comment by ruslan-bikkinin** [comment]
Hi @danieldelouya and thanks for submitting the issue, could you please provide small reproducable demo for this?

**Comment by max-mironov** [comment]
@danieldelouya please let us know if you have a chance to look at this?

**Comment by danieldelouya** [comment]
Hey guys. Sorry for the delay. 
I had to uninstall codepush for now as it was causing bad user experience while starting up. 
I will try to make time to provide a demo to highlight the issue shortly.

**Comment by sergey-akhalkov** [comment]
Hi @danieldelouya, got it, closing this for now, please feel free to reopen.
