### ISSUE TITLE
Gradle clean: "The SDK Build Tools revision (23.0.1) is too low for project ':react-native-code-push'. Minimum required is 25.0.0"

### ISSUE THREAD

**Issue by sunweiyang** [Microsoft/react-native-code-push#1055]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Perform `./gradlew clean` from `android` directory
2. See the failure related to 

### Behavior
The following is displayed in the terminal:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-code-push'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-code-push'. Minimum required is 25.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

### Environment

* react-native-code-push version: 5.1.3-beta
* react-native version: 0.49.2

**Comment by sunweiyang** [comment]
I'm currently working around this issue by manually editing the `android/app/build.gradle` file and replacing `23.0.1` with `25.0.0`:
`buildToolsVersion "25.0.0"`

**Comment by max-mironov** [comment]
Hey @sunweiyang we have several similar issues before, currently we are not going to upgrade to 25.0.0, please see this for more info: https://github.com/Microsoft/react-native-code-push/issues/919
As a workarond - please take a look at the following comment: https://github.com/Microsoft/react-native-code-push/pull/725#issuecomment-284979977 hope it helps.

**Comment by max-mironov** [comment]
Closing this, let us know if you have any questions with this.
