### ISSUE TITLE
Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by josesuero** [Microsoft/react-native-code-push#1056]
I'm getting this error when I exit my app on android:

import CodePush from 'react-native-code-push';
10-23 14:59:33.021 12775-12841/com.example.testapp E/unknown:ReactNative: TypeError: Cannot read property 'remove' of undefined
                                                                            
                                                                            This error is located at:
                                                                                in App (at CodePush.js:503)
                                                                                in CodePushComponent (at renderApplication.js:35)
                                                                                in RCTView (at View.js:113)
                                                                                in View (at AppContainer.js:102)
                                                                                in RCTView (at View.js:113)
                                                                                in View (at AppContainer.js:126)
                                                                                in AppContainer (at renderApplication.js:34), stack:
                                                                            App.componentWillUnmount@59515:32
                                                                            App.proxiedComponentWillUnmount@27503:43
                                                                            callComponentWillUnmountWithTimerInDev@4787:74
                                                                            Object._invokeGuardedCallback@2532:18
                                                                            invokeGuardedCallback@2506:36
                                                                            safelyCallComponentWillUnmount@4790:17
                                                                            commitUnmount@4914:88
                                                                            commitNestedUnmounts@4860:21
                                                                            unmountHostComponents@4889:78
                                                                            commitDeletion@4907:13

 I found https://github.com/Microsoft/react-native-code-push/issues/790#issuecomment-294148452 which talks about react-native-navigation, i'm using react-navigation on this project, tried to apply the same fix but couldn't figure out how to do it since react-navigation is not a native module

### Environment

* react-native-code-push version: 5.1.3-beta
* react-native version: 0.49.3
* iOS/Android/Windows version: android API 24

thanks in advance

**Comment by sergey-akhalkov** [comment]
Hi @josesuero, thanks for reaching us. Could you please provide us a small reproducible demo so we would be able to investigate it and help you?

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to provide the demo app where the issue reproduces so we would be glad to help you.
