### ISSUE TITLE
Loading JS bundle always local (assets://index.android.bundle) insted of CodePush URL

### ISSUE THREAD

**Issue by srinuch1981** [Microsoft/react-native-code-push#1058]
### Steps to Reproduce
1. react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug
2. cd android
   ./gradlew assembleDebug
3. adb install "app_debug.apk"

### Expected Behavior
code-push release-react sampleApp android

The JS and Image changes not reflecting after the above command. I can see the changes pushed to server.
 Label │ Release Time   │ App Version │ Mandatory │ Description │ Install Metrics      │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v1    │ 18 hours ago   │ 1.0         │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v2    │ 17 hours ago   │ 1.0         │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v3    │ an hour ago    │ 1.0         │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v4    │ an hour ago    │ 1.0         │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v5    │ an hour ago    │ 1.0         │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v6    │ an hour ago    │ 1.0         │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v7    │ an hour ago    │ 1.0         │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v8    │ 41 minutes ago │ 1.0         │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v9    │ 19 minutes ago │ 1.0         │ No        │             │ No installs recorded 

### Actual Behavior
The bundle is fetched always from local only not referring code-push url.

[09:33:37] Loading JS bundle from "assets://index.android.bundle"
[09:33:37] Sync already in progress.
[09:33:37] Checking for update.
[09:33:37] Reporting binary update (1.0)
[09:33:37] Loading JS bundle from "assets://index.android.bundle"
[09:33:37] Sync already in progress.
[09:33:37] Checking for update.
[09:33:37] Reporting binary update (1.0)
[09:34:00] Loading JS bundle from "assets://index.android.bundle"
[09:34:25] Loading JS bundle from "assets://index.android.bundle"

Note: I have add override method & code push key as per the documentation. 

### Environment
* "react-native": "0.49.3",
* "react-native-code-push": "^1.14.1-beta"
react-native version:
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by max-mironov** [comment]
Hey there @srinuch1981, please consider that code push updates should not be tested in debug mode, could you please try it in release mode and let us know the results? 

From [docs](https://github.com/Microsoft/react-native-code-push#releasing-updates):

> NOTE: CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply.

**Comment by srinuch1981** [comment]
Thanks, it's working in release mode .
