### ISSUE TITLE
Error:Execution failed for task ':app:recordFilesBeforeBundleCommandDebug'. > A problem occurred starting process 'command 'node''

### ISSUE THREAD

**Issue by tianweicc** [Microsoft/react-native-code-push#1062]
android gradld upgrade to 4.1 after the report d

**Comment by linjson** [comment]
i had same problem in androidstudio3.0,but I run "./gradlew build" is successful in Cammand,why?

**Comment by ruslan-bikkinin** [comment]
Hi @tianweicc and thanks for reaching us.
Please follow the [issue template](https://github.com/Microsoft/react-native-code-push/issues/new) so we could be able to help you with your issue.

**Comment by linjson** [comment]
i had resolved :

it seem can't find 'node' path,I fix "*nodeExecutableAndArgs"->"/usr/local/bin/node" then it is work

**Comment by ruslan-bikkinin** [comment]
Glad to here that @linjson! I am closing this issue for now. @tianweicc if solution suggested by @linjson will not help you please feel free to reopen it.

**Comment by fhad-getmaple** [comment]
@linjson Hi, I'm getting the same errors...

I don't understand what you mean by
 _it seem can't find 'node' path,I fix "*nodeExecutableAndArgs"->"/usr/local/bin/node" then it is work_

Can you please explain how you fixed this issue? 
Thank you,

**Comment by linjson** [comment]
@fhad-getmaple 
to find "react-native-code-push/android/codepush.gradle" this file

**Comment by Biplab2014** [comment]
@linjson How did you resolve this issue?

**Comment by suxindao** [comment]
find "react-native-code-push/android/codepush.gradle" file,
change 
def nodeExecutableAndArgs = config.nodeExecutableAndArgs ?: ["node"]
to
def nodeExecutableAndArgs = config.nodeExecutableAndArgs ?: ["/usr/local/bin/node"]

It works for me!

**Comment by jebora** [comment]
Just for reference, there's a workaround that can be found here: https://github.com/facebook/react-native/issues/6875#issuecomment-293220175

I got this issue when upgrading to Android Studio 3, using api 26. Similar issue to https://github.com/Microsoft/react-native-code-push/issues/1069
