### ISSUE TITLE
CP does not download correct CP update after App Store update

### ISSUE THREAD

**Issue by brendan-rius** [Microsoft/react-native-code-push#1063]
Here is my history

<img width="813" alt="screenshot 2017-10-26 15 43 54" src="https://user-images.githubusercontent.com/5605817/32056308-a0c799b4-ba64-11e7-97d1-53bc22fe1a7d.png">

As you can see, starting from v8, I target another binary version (1.23.3). However, when opening devices running 1.23.3, the code push version is v5 !!! This should not happen as 1) the latest version is v9 and 2) v5 does not target 1.23.3 but 1.22.1

It looks like maybe Code Push did not clear the version it previously downloaded before updating the app from the store.

Anyway, this is very very annoying.

Also out of 3 devices that are running 1.23.3 that I tested, only 2 fail and the other one is working properly (??)

react-native: 0.48.3
react-native-code-push: 5.1.3-beta

For information, here are two screenshots of the app from 2 different devices:

![img_3325](https://user-images.githubusercontent.com/5605817/32056896-1dfd2452-ba66-11e7-8ac5-06130e894d58.PNG)

As you can see this one is working properly (code push version is v9 and binary version is 1.23.3)

![22882421_10155694636355295_1420309883_o 1](https://user-images.githubusercontent.com/5605817/32056792-ded297b2-ba65-11e7-8142-7f5ed0c8e06e.jpg)

But on this one, binary version is 1.23.3 but CodePush detects the binary version as being 1.22.1 and thus uses v5

Any clue?

**Comment by ruslan-bikkinin** [comment]
Hello @brendan-rius and thanks for submitting the issue. Could you please:

* Clarify which platform your application is using: android or ios? 
* Could you share app logs with us: one from app with correct CP version and one from app with incorrect CP version. Please, pay attention whether logs contains 503 errors came from CodePush service.

**Comment by brendan-rius** [comment]
Ok after a more careful checking, what happens is that the displayed version number from CodePush is the wrong one.

So, in this case: 

![22882421_10155694636355295_1420309883_o 1](https://user-images.githubusercontent.com/5605817/32056792-ded297b2-ba65-11e7-8142-7f5ed0c8e06e.jpg)

The version is 1.23.1, and there is actually no Code Push version applied (contrary to what is shown). The big problem though is that the app will not receive further CodePush updates!

Also, interesting discovery:

The problem only happens when you update the app from the app store. If you delete the app, and then install it from the app store, there is no such problem.

That makes me think that somehow CodePush keeps an archive of an old version of the code and:
  1) reads version number from it (without executing the code)
  2) disallows further updates
I think this archive is deleted when the app is deleted

**Comment by ruslan-bikkinin** [comment]
@brendan-rius thanks for your answer, could you please:

* Clarify which platform your application is using: android or ios?
* Share app logs with us: one from app with correct CP version and one from app with incorrect CP version. Please, pay attention whether logs contains 503 errors came from CodePush service.

**Comment by brendan-rius** [comment]
I am using ios. Will try to get the logs today

**Comment by ruslan-bikkinin** [comment]
@brendan-rius thanks for response, we will be waiting for them.

**Comment by max-mironov** [comment]
Closing the issue for now, please feel free to reopen when you get more info regarding this
