### ISSUE TITLE
Something went wrong. Please verify if generated JS bundle is correct.

### ISSUE THREAD

**Issue by kohei-takata** [Microsoft/react-native-code-push#1066]
### Steps to Reproduce
1. On Xcode, select `Edit Scheme > Run`.
2. Change `Build Configuration` from `Debug` to `Release`.
3. Press `cmd + R` to run app.

### Expected Behavior
What you expected to happen?
Run app correctly with no error.
Export a log like `[CodePush] Loading JS bundle from file:///~` , I think.

### Actual Behavior
What actually happens?
```
*** Terminating app due to uncaught exception 'RCTFatalException: Something went wrong. Please verify if generated JS bundle is correct. ', reason: 'Something went wrong. Please verify if generated JS bundle is correct. '
```
### Environment

* react-native-code-push version: `2.1.1-beta`
* react-native version: `0.44.0`
* iOS/Android/Windows version: Every version of iOS I tried.
* Does this reproduce on a debug build or release build? Only release build
* Does this reproduce on a simulator, or only on a physical device? Both of them.

**Comment by kohei-takata** [comment]
The error was fixed.
Process is below.
1. Create `main.jsbundle` file manually.
I run `react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output iOS/main.jsbundle` command.
2. Reattach `main.jsbundle` file to Xcode.
Remove reference of `main.jsbundle` from Xcode and add `main.jsbundle` to Xcode again

**Comment by JakeRawr** [comment]
Hi,

I think I’m running into the same issue. With @kohei-takata fixes, my assets don’t load. What should I do in this case?

**Comment by Pranit-Harekar** [comment]
@kohei-takata 's answer worked for me. _I think_ CodePush requires you to ship a jsbundle with the app binary (in release mode). @JakeRawr you need to specify assets destination dir while bundling. Here is the complete script:
```bash
react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle  --assets-dest ios
```

**Comment by spacesuitdiver** [comment]
I'm trying to bundle my main.jsbundle separately and I always end up with this error. It maps up in the xcodeproj properly though, any ideas?

**Comment by emilioheinz** [comment]
> The error was fixed.
> Process is below.
> 
> 1. Create `main.jsbundle` file manually.
>    I run `react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output iOS/main.jsbundle` command.
> 2. Reattach `main.jsbundle` file to Xcode.
>    Remove reference of `main.jsbundle` from Xcode and add `main.jsbundle` to Xcode again

Worked for me, thanks!
