### ISSUE TITLE
Connectivity Issues to server

### ISSUE THREAD

**Issue by seanadkinson** [Microsoft/react-native-code-push#1070]
Are there current issues with the code-push servers?  I'm having spotty connectivity issues right now, and if it does connect, the download is extremely slow.  Is there a better place to file an issue, or look for open status events?  Right now it is Nov 2 at about 1:20pm PST.  Thanks.

**Comment by ruslan-bikkinin** [comment]
Hi @seanadkinson and thanks for reporting, we’ll check this as soon as possible.

**Comment by max-mironov** [comment]
@seanadkinson - hi and sorry for inconvenience, please see https://github.com/Microsoft/cordova-plugin-code-push/issues/314#issuecomment-342398757 answer for details.
