### ISSUE TITLE
Release update to multiple version

### ISSUE THREAD

**Issue by sandropoluan** [Microsoft/react-native-code-push#1071]
My app already on market with these versions. 1.0 ,1.1 ,1.2, 1.2.1 and 1.2.2
And now I need to release an update to version **1.0 , 1.1 , 1.2**
I have try with 
`code-push release-react myaap-Android Android --deploymentName Production --targetBinaryVersion=1.0-1.2`

But I got this error
`[Error]  Please use a semver-compliant target binary version range, for example "1.0.0", "*" or "^1.2.3"`

My first 3 version is not using semantic versioning, so how can I send update to them?
Thank you

**Comment by ruslan-bikkinin** [comment]
Hi @sandropoluan and thanks for reaching us. 
You can try to release update using `code-push release-react myaap-Android Android --deploymentName Production --targetBinaryVersion ">=1.0.0 <1.2.1"`
Please let us know if this helps or any updates.

**Comment by sandropoluan** [comment]
Thank you.
