### ISSUE TITLE
does the bundle.js and assets live on a code push server?

### ISSUE THREAD

**Issue by jqn** [Microsoft/react-native-code-push#1075]
I wasn't able to find an answer to this question anywhere, if I missed it please point me in the right direction. Does the bundle.js and assets get stored in a code push server?

**Comment by ruslan-bikkinin** [comment]
Hi @jqn and thanks for your question. Yes, bundle and assets are storing on CodePush server.

**Comment by sergey-akhalkov** [comment]
Hi @jqn, closing this, please feel free to reopen.

**Comment by jqn** [comment]
@ruslan-bikkinin thanks for your quick answer
