### ISSUE TITLE
How to display the code-push popup in a different language?

### ISSUE THREAD

**Issue by tk-pivotus** [Microsoft/react-native-code-push#1077]
I want to create an in a language that is different than English, how to localize the code-push popup message?

**Comment by sergey-akhalkov** [comment]
Hi @tk-pivotus, thanks for reaching us. Please take a look at [updateDialog](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushoptions) to see how the dialog can be customized. Please let me know if you have any questions.

**Comment by tk-pivotus** [comment]
Looks good to me.  Sorry, somehow I skimmed through the docs and didn't find that.  Closing.

**Comment by yamila-fraiman** [comment]
Hello, I am using i18next so translations are not available immediately and codepush options are configured outside the index component. How could I use translations for the dialog?
