### ISSUE TITLE
RecreateReactContextInBackground does not exist in RN-Windows 50

### ISSUE THREAD

**Issue by adricl** [Microsoft/react-native-code-push#1078]
Hello All,

I am having an issue where RecreateReactContextInBackground does not exist in React Native 50 RC2.

I think its due to ReactPage being Obsoleted.
When I add the project to the sample react native windows project I get the following error in Visual Studio 2017.

Error	CS1061	'ReactInstanceManager' does not contain a definition for 'RecreateReactContextInBackground' and no extension method 'RecreateReactContextInBackground' accepting a first argument of type 'ReactInstanceManager' could be found (are you missing a using directive or an assembly reference?)	CodePush	C:\New Pos\migration\node_modules\react-native-code-push\windows\CodePushNativeModule.cs	263	Active

I have checked in React Native and this no longer exits.

* react-native-code-push version: react-native-code-push@1.17.0-beta
* react-native version: Windows
* Does this reproduce on a debug build or release build? Debug 
* Does this reproduce on a simulator, or only on a physical device? NA

**Comment by adricl** [comment]
#1051 This is the fix for this issue.

**Comment by max-mironov** [comment]
Hey @adricl, closing this due to fix merged!
