### ISSUE TITLE
Code signing does not work when pushing code to iOS from windows/linux machine

### ISSUE THREAD

**Issue by pcguru** [Microsoft/react-native-code-push#1079]
### Steps to Reproduce
1. Use a linux or windows machine to push code from.
2. Enable code signing in a react app.
3. Push code for the iOS app, use code signing.
4. Perform an update check in the matching iOS app.

### Expected Behavior
The iOS app should update.

### Actual Behavior
The app downloads the bundle but does not update.
Using the `code-push log ios` command shows this output:

```
[11:41:15] Applying full update.
[11:41:15] Verifying hash for folder path: /Users/---/Library/Developer/CoreSimulator/Devices/---/data/Containers/Data/Application/---/Library/Application Support/CodePush/---
[11:41:16] Manifest string: (
[11:41:16] Expected hash: ---, actual hash: ---
[11:41:16] The update contents succeeded the data integrity check.
[11:41:16] The update could not be verified because it was not signed by a trusted party. Error Domain=io.jwt.crypto.stripping_public_header Code=-199 "Provided key doesn't have a valid ASN.1 structure (first byte should be 0x30 == SEQUENCE)" UserInfo={NSLocalizedDescription=Provided key doesn't have a valid ASN.1 structure (first byte should be 0x30 == SEQUENCE), Parameters=null}
[11:41:16] The update contents failed code signing check.
```

### Environment
* code-push-cli: 2.1.1-beta
* react-native-code-push version: 5.1.3-beta
* react-native version: 0.47.2
* iOS/Android/Windows version: Device: iOS 10.3.1, Build machines: Windows 10 Pro / OSX
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by ruslan-bikkinin** [comment]
Hi @pcguru and thanks for submitting the issue. Could you please share with us how have you created public/private key pair (commands you used, tools etc) and share with us CodePushPublicKey section from your `Info.plist` file?

**Comment by pcguru** [comment]
I created the public/private key pair on Windows using the commands from the guide. I used Git Bash as shell in windows. https://github.com/Microsoft/code-push/blob/master/cli/README.md#code-signing

```
openssl genrsa -out private.pem
openssl rsa -pubout -in private.pem -out public.pem
```

I then copied the key files to the OSX machine and built a new binary. Started it in the simulator.

The plist file is:
```
<plist version="1.0">
<dict>
	<key>CodePushDeploymentKey</key>
	<string>$(CODEPUSH_DEPLOYMENT_KEY)</string>
	<key>CodePushPublicKey</key>
	<string>$(CODEPUSH_PUBLIC_KEY)</string>
```

The variables are replaced at build by XCode as user defined variables.

This is the command I used to push the code, I used the same command on both the Windows and OSX machine:

```
$ code-push release-react FooBar-iOS ios --targetBinaryVersion 3.5 --privateKeyPath buildConfig/code-push-keys/private.pem
```

So the same command, with the same private key file, works when run from OSX, but not from Windows.

**Comment by pcguru** [comment]
My fault. Somehow XCode broke the public key, seems related to line endings. Pasted the public key variables into the pbxproj file with external editor instead. After that pushes work from any machine. Don't know why the push worked from the OSX machine, perhaps an old release. :(

The good news is Code Push just as expected.

**Comment by Anuj-logiciel** [comment]
@pcguru - Had You faced an issue like - `Unable to verify the signature for package: Signature verification failed` while using this plugin? Or have any solutions for this?

![Screenshot 2019-10-30 at 6 10 44 PM](https://user-images.githubusercontent.com/22930446/67946976-8c94a300-fc08-11e9-943f-9fd164ad2e0b.png)
