### ISSUE TITLE
Staging keys for both Android and iOS in one app

### ISSUE THREAD

**Issue by rizwanahmed19** [Microsoft/react-native-code-push#1082]
So I have an app, let's call it MyApp. Now I've created/registered separate apps for both platforms using `code-push app add MyApp-Android android react-native` and `code-push app add MyApp-iOS ios react-native`.

Now the documentation says that I will be prompted for the staging key when I run `react-native link react-native-code-push`. So what should I do next cause there's a single project and I've registered 2 apps. How would I add staging keys of both iOS and Android in my single project?

Thanks

**Comment by max-mironov** [comment]
Hello @rizwanahmed19, you will be prompted to add both keys, first for android and then for iOS. If you want you can skip one of this step - just hit `enter` and no key will be injected at all. 
From my point of view it would be better if you have two apps (one for iOS, one for android) and will enter the required keys on linking.

**Comment by rizwanahmed19** [comment]
@max-mironov Thanks a lot for clearing.
