### ISSUE TITLE
Android App crashes with FATAL EXCEPTION: java.lang.RuntimeException: AsyncTask: doInBackground function

### ISSUE THREAD

**Issue by s-shiva1995** [Microsoft/react-native-code-push#1084]
I followed the instructions of react-native-code-push to setup my react-native application. When I am building my release version and release the update my application crashes. This behaviour is seen by me only in android as I have never used my application in iOS .

https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#a-namereleasing-app-updates-releasing-updates I followed the steps available here to setup my app with appcenter but when I am releasing an update it says it is successfully released. When I am clicking on download button in my android phone the app crashes with the following log.

```
11-20 17:13:47.298 6290-6347/com.askin.qoti E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2 Process: com.askin.qoti, PID: 6290 java.lang.RuntimeException: An error occurred while executing doInBackground() at android.os.AsyncTask$3.done(AsyncTask.java:353) at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) at java.util.concurrent.FutureTask.setException(FutureTask.java:252) at java.util.concurrent.FutureTask.run(FutureTask.java:271) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) at java.lang.Thread.run(Thread.java:764) Caused by: com.microsoft.codepush.react.CodePushUnknownException: Error in getting binary resources modified time at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:158) at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:209) at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:204) at android.os.AsyncTask$2.call(AsyncTask.java:333) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)  at java.lang.Thread.run(Thread.java:764)  Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0 at android.content.res.Resources.getText(Resources.java:338) at android.content.res.Resources.getString(Resources.java:432) at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:155) at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:209)  at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:204)  at android.os.AsyncTask$2.call(AsyncTask.java:333)  at java.util.concurrent.FutureTask.run(FutureTask.java:266)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)  at java.lang.Thread.run(Thread.java:764)  11-20 17:13:47.304 6290-6333/com.askin.qoti D/EGL_emulation: eglMakeCurrent: 0x99b7c900: ver 3 1 (tinfo 0x9a07f110) 11-20 17:13:47.317 6290-6347/com.askin.qoti I/zygote: Deoptimizing void com.microsoft.appcenter.ingestion.models.json.JSONUtils.writeArray(org.json.JSONStringer, java.lang.String, java.util.List) due to JIT inline cache 11-20 17:13:47.327 6290-6347/com.askin.qoti E/UncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground() at android.os.AsyncTask$3.done(AsyncTask.java:353) at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) at java.util.concurrent.FutureTask.setException(FutureTask.java:252) at java.util.concurrent.FutureTask.run(FutureTask.java:271) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) at java.lang.Thread.run(Thread.java:764) Caused by: com.microsoft.codepush.react.CodePushUnknownException: Error in getting binary resources modified time at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:158) at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:209) at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:204) at android.os.AsyncTask$2.call(AsyncTask.java:333) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)  at java.lang.Thread.run(Thread.java:764)  Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0 at android.content.res.Resources.getText(Resources.java:338) at android.content.res.Resources.getString(Resources.java:432) at com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime(CodePush.java:155) at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:209)  at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:204)  at android.os.AsyncTask$2.call(AsyncTask.java:333)  at java.util.concurrent.FutureTask.run(FutureTask.java:266)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)  at java.lang.Thread.run(Thread.java:764)  11-20 17:13:47.551 6290-6444/com.askin.qoti I/FirebaseCrash: Sending crashes

```

my screen where I have implemented codepush

```
let codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_RESUME };
class App extends Component {
render() {
return (
null
);
}
componentWillMount() {
codePush.sync({
updateDialog: true,
installMode: codePush.InstallMode.IMMEDIATE
});
}
}
export default codePush(codePushOptions)(App);
```

for installing I have done
```
npm install --save react-native-code-push`
`react-native link react-native-code-push`
```

Project Dependencies:
```
"dependencies": { "appcenter": "^1.0.1", "appcenter-analytics": "^1.0.1", "appcenter-crashes": "^1.0.1", "crypto-js": "^3.1.9-1", "lodash": "^4.17.4", "react": "16.0.0", "react-native": "0.50.3", "react-native-calendars": "^1.9.2", "react-native-code-push": "^5.1.3-beta", "react-native-eventemitter": "0.0.1", "react-native-fetch-blob": "^0.10.8", "react-native-firebase": "^3.0.3", "react-native-masked-text": "^1.6.2", "react-native-mixpanel": "0.0.16", "react-native-svg": "^5.4.1", "react-native-vector-icons": "^4.3.0", "react-navigation": "^1.0.0-beta.11", "react-redux": "^5.0.6", "recyclerlistview": "^1.1.5", "redux": "^3.7.2", "redux-logger": "^3.0.6", "redux-persist": "^4.9.1", "redux-persist-filesystem-storage": "^1.0.2", "redux-thunk": "^2.2.0" }, "devDependencies": { "babel-jest": "20.0.3", "babel-preset-react-native": "3.0.0", "jest": "20.0.4", "react-test-renderer": "16.0.0-alpha.12" },
```

Versions:
`react-native-cli: 2.0.1 react-native: 0.50.3 npm: 5.3.0`

**Comment by max-mironov** [comment]
Hello @s-shiva1995, could you please take a look at the issues from below having the similar problem:
1) https://github.com/Microsoft/react-native-code-push/issues/771
2) https://github.com/Microsoft/react-native-code-push/issues/1046

Please double check that `codePush.gradle`is correctly referenced in `build.gradle` (also please check the following comment https://github.com/Microsoft/react-native-code-push/issues/873#issuecomment-306776546)

Let us know if helps or any questions.

**Comment by s-shiva1995** [comment]
I have checked the above issues and I think I have linked codePush.gradle file correctly. Here is my app/build.gradle


`apply plugin: "com.android.application"
//firebase performance monitoring plugins
apply plugin: "com.android.application"
apply plugin: "com.google.firebase.firebase-perf"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 * 
 * `apply from: "../../node_modules/react-native/react.gradle"`
 * `apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"`
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.vectoricons = [
    iconFontNames: [ 'MaterialIcons.ttf', 'FontAwesome.ttf'] // Name of the font files you want to copy
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"


/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.2'

    defaultConfig {
        applicationId "com.askin.qoti"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.1.0"
        //was used with firebase conflict 
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        //Used for increasing the heap size memory of java
        dexOptions { javaMaxHeapSize "4g" }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        debug {
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }
        releaseStaging {
            buildConfigField "String", "CODEPUSH_KEY", '"Staging Key"'
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
            buildConfigField "String", "CODEPUSH_KEY", '"Production Key"'
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, setplay-services-base a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}
dependencies {
    compile project(':appcenter-crashes')
    compile project(':appcenter-analytics')
    compile project(':appcenter')
    compile project(':react-native-fetch-blob')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+" 
    
    //Mix Panel dependency
    compile project(':react-native-mixpanel')

    //filesystem
    compile project(':react-native-fs')
    
    //code push
    compile project(':react-native-code-push')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}`

In issue 771 I am not getting any CODEPUSH_APK_BUILD_TIME key in app.debug but codePush.gradle has the same structure defined for the string.

Please correct me if I am doing something wrong.

**Comment by s-shiva1995** [comment]
Sorry wrong placement of codePush.gradle

**Comment by grahamyesfit** [comment]
@max-mironov Please update the instructions for [Plugin Installation (Android - RNPM)](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-android---rnpm) to include the `codepush.gradle` step. I ran into the same issue, but I didn't even look at the Manual steps because I assumed `react-native link` did everything that was required, as the instructions indicate you do either one or the other.
