### ISSUE TITLE
Codepush.sync() return '1'

### ISSUE THREAD

**Issue by wd** [Microsoft/react-native-code-push#1087]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
```
        codePush.sync({
            updateDialog: false,
            installMode: codePush.InstallMode.ON_NEXT_RESUME,
            minimumBackgroundDuration: 60 * 5
        },(status)=>{
             // Get 1 here
        })
```

### Expected Behavior
![image](https://user-images.githubusercontent.com/58177/33208560-0267f3e0-d14d-11e7-96b9-cf3a48a5194f.png)

There is an update available, but, as the doc said, it should be return one of 4,5,6,7, why return 1? I think it should return 6.

### Actual Behavior
Always return 1.

### Environment

* react-native-code-push version: 5.2.0-beta
* react-native version: 0.50.3
* iOS/Android/Windows version: Android Oreo
* Does this reproduce on a debug build or release build?  Staging build
* Does this reproduce on a simulator, or only on a physical device? All

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hey @wd is it possible that update is just installed? https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L549
If you release another update will you always get this status? Does updates applied at all?

**Comment by wd** [comment]
Ah, yes. That's should be the right status. I forget to check the source code. Thanks.

**Comment by max-mironov** [comment]
@wd got it, thanks for update! As for docs - it make sense to keep them in sync with actual code, we can update them a little bit later or if you would like you can create a PR for this, that would be much appreciated!
