### ISSUE TITLE
Can`t update. Info 'An update is available but it is not targeting the binary version of your app.'

### ISSUE THREAD

**Issue by xclidongbo** [Microsoft/react-native-code-push#1091]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. current app version is 3.0.0.and run `code-push release-react Traveller-ios ios`
2. There is an Info 'An update is available but it is not targeting the binary version of your app.' 
3. Can not update.

┌───────┬────────────────┬─────────────┬───────────┬─────────────┬──────────────────────┐
│ Label │ Release Time   │ App Version │ Mandatory │ Description │ Install Metrics      │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v1    │ 39 minutes ago │ 3.0.1       │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v2    │ 34 minutes ago │ 3.0.2       │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v3    │ 25 minutes ago │ 3.0.3       │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v4    │ a minute ago   │ 3.0.4       │ No        │             │ No installs recorded │
└───────┴────────────────┴─────────────┴───────────┴─────────────┴──────────────────────┘

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: react-native-code-push@5.2.0-beta
* react-native version: 0.48.3
* iOS/Android/Windows version: iOS 11
* Does this reproduce on a debug build or release build?  0.48.3
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

**Comment by ruslan-bikkinin** [comment]
Hi @xclidongbo and thanks for reaching us.

Please double check your application targeting the same version that code-push update targets. In your case, `CFBundleVersion` should be `3.0` within `Info.plist`.

**Comment by xclidongbo** [comment]
@ruslan-bikkinin  Thanks a lot.  The problem has resolve.
Within `Info.plist`, `CFBundleVersion` is `3.0.0`.
