### ISSUE TITLE
Why code push is not supporting gradle 3.+

### ISSUE THREAD

**Issue by chandansharma786** [Microsoft/react-native-code-push#1092]
My project is using react and codepush which is successfully running on gradle 2.3.3 but I have a third party library to integrate and it is supporting sdk version 26 and gradle 3.+ and it is not able to running on oreo emulator, because code push is not supporting gradle 3.+ as i checked this code push version in gradle file on github. 
Please suggest me i want to update my app for oreo features and integrate that third party library .

### Steps to Reproduce
1. I just run my app which is on sdk version 23 on  oreo emulator and it is showing a gradle build error. 

gradle build error message:
Error:Execution failed for task ':app:recordFilesBeforeBundleCommandAlpha'.
> A problem occurred starting process 'command 'node''

**Comment by ruslan-bikkinin** [comment]
Hi @chandansharma786  and thanks for asking. Please take a look at this [comment](https://github.com/Microsoft/react-native-code-push/issues/1069#issuecomment-344927050), you'll find instructions how to run codepush on gradle 3.
