### ISSUE TITLE
Update to users with different APK

### ISSUE THREAD

**Issue by Ehesp** [Microsoft/react-native-code-push#1093]
Hello - I'm using code push in an app I'm developing but I currently see a problem during the workflow of new features:

1) Release an app with Code Push installed
2) Develop new feature which has a new native module
3) Deploy app to Play Store
4) Push up new changes to Code Push

Users who open the app and download the new code push changes will see a crash as the native module is not available. The only way to get around this is for them to download the new app from the store which contains the new module.

I'd of thought that the bundle would be linked to some sort of SHA1 of the app build, so changes are only pulled in if the app itself hasn't changed?

Note: I am using the `--mandatory` flag if that matters?

Sorry for the question in an issue!

### Environment

* react-native-code-push version: 5.0.0-beta
* react-native version: 0.50.3

**Comment by ruslan-bikkinin** [comment]
Hi @Ehesp and thanks for submitting the issue. In your case the better way to avoid such problems is to create new major version of app including native side changes, e.g. for example v1.0 -> v2.0 . Then release new update via codepush targeting new binary version using `--target-binary-version` or `-t` option:

```appcenter codepush release-react -a yourapp -t 2.0```

Please refer to relevant [documentation section](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter) for more information.

Let us know if it helps you or any updates.

**Comment by ruslan-bikkinin** [comment]
Hi @Ehesp, did you have a chance to look at this?

**Comment by Ehesp** [comment]
Hey thanks for the reply. Yeah that makes sense - I'll just have to be more careful with the updates which are pushed out!

Cheers
