### ISSUE TITLE
code-push ls myApp -k  [Error]  Cannot GET /apps/ios.it/ZMClient/deployments/

### ISSUE THREAD

**Issue by xiaoyongchen** [Microsoft/react-native-code-push#1094]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.code-push -v :2.1.0-beta
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hey @xiaoyongchen do you still see the issue? Could you please provide us an exact command and the output for the error message?
I've tried e.g. `code-push deployment ls MyTestOrganization_maximi/max-rename -k` but don't see any issues.

**Comment by max-mironov** [comment]
@xiaoyongchen do you have a chance to look at this?

**Comment by max-mironov** [comment]
Closing this, please create new issue if needed.
