### ISSUE TITLE
App crashes with bundles produced with unbundle command

### ISSUE THREAD

**Issue by sercand** [Microsoft/react-native-code-push#1102]
### Steps to Reproduce
1. Build bundle manually
```
node node_modules/react-native/local-cli/cli.js unbundle \
    --platform 'android' \
    --entry-file 'index.js' \
    --bundle-output ./build/index.android.bundle \
    --assets-dest ./build \
    --dev false \
    --reset-cache
```
2. Deploy bundle
`code-push release appname ./build 3.8.5 --deploymentName Staging --mandatory`

### Actual Behavior
What actually happens?
```
Fatal Exception: java.lang.RuntimeException
com.facebook.react.devsupport.JSException: Requiring unknown module "38". (/data/user/0/com.otsimo.app/files/CodePush/8f0cb1101eaccd6e95f7804ebc2e4815fd27c9b2d14581d8c62f53fa0360d711/tmpIQL0EVotsimo/index.android.bundle:2)
com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException (DefaultNativeModuleCallExceptionHandler.java:24)
com.facebook.react.devsupport.DisabledDevSupportManager.handleException (DisabledDevSupportManager.java:172)
com.facebook.react.bridge.CatalystInstanceImpl.onNativeException (CatalystInstanceImpl.java:496)
com.facebook.react.bridge.CatalystInstanceImpl.access$900 (CatalystInstanceImpl.java:41)
com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException (CatalystInstanceImpl.java:512)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:33)
```

### Environment

* react-native-code-push version: **5.1.3-beta**
* react-native version: **0.50.4**
* iOS/Android/Windows version: **Android 6.0.1**
* Does this reproduce on a debug build or release build? **Release**
* Does this reproduce on a simulator, or only on a physical device? **Physical**

**Comment by ruslan-bikkinin** [comment]
Hi @sercand and thanks for submitting the issue. We already have this in our backlog https://github.com/Microsoft/react-native-code-push/issues/778 and we are planning to implement it in Appcenter React-native SDK after Codepush migration into it.

**Comment by sercand** [comment]
@ruslan-bikkinin Thaks for the quick reply. We really need this using because app starting time decreases drastically when using unbundle command. It took 4 seconds to loading js with bundle command vs 1 second.

**Comment by sergey-akhalkov** [comment]
Hi @sercand, thanks for reaching us! Yes, it makes sense due to the diffing feature will return only the file has been changed instead of whole js bundle. As of now, we are going to start migrating CodePush SDK to the  https://github.com/Microsoft/AppCenter-SDK-Android and https://github.com/Microsoft/AppCenter-SDK-Apple So most of the new features will be implemented there. 

Thank you for the feedback, please let us know if you have any questions/concerns/considerations.
