### ISSUE TITLE
code-push app add APPName failed

### ISSUE THREAD

**Issue by freddy24** [Microsoft/react-native-code-push#1103]
I just wanna add a new app .
`code-push app add myApp `
```
[Error]  The 'app add' command requires extra arguments now that CodePush is part of Mobile Center.
Please upgrade to the latest version of the CodePush CLI by running 'npm install -g code-push-cli@latest'.
```
then I upgrade my code-push to the latest version. 
`code-push app add myApp `
still have the same problem. then I run 
`code-push app add myApp  android react-native`  
still does't work.
what should I do? I just add a new app

**Comment by sergey-akhalkov** [comment]
Hi @freddy24, thanks for reaching us. CodePush has been migrated to the AppCenter, so for apps management, you can use appcenter-cli now. In case you still want to use old code-push-cli you need to perform the following command to create an app:
`code-push app add <appName> <os> <platform>`

For example: `code-push app add MyApp ios react-native`

Please let me know if you have any questions or see any issues.

**Comment by freddy24** [comment]
I try to run
`code-push app add MyApp ios react-native`
then these message comes:
```
Usage: code-push app add <appName>

Options:
  -v, --version  Show version number  [boolean]

Examples:
  app add MyApp  Adds app "MyApp"
```
still doesn't work.

**Comment by sergey-akhalkov** [comment]
@freddy24, what version of code-push-cli are you using? Please update and try again.

**Comment by sergey-akhalkov** [comment]
JFYI - I've just tried to perform the `code-push app add rncp1103 ios react-native` command - everything works fine.

**Comment by freddy24** [comment]
@sergey-akhalkov thank you so much . I removed  it and re-install. then run 
`code-push app add MyApp ios react-native`
it works. thank you !

**Comment by sergey-akhalkov** [comment]
👍  , closing this, let us know if you have any other questions or see any issues.
