### ISSUE TITLE
Installing React 0.11.0 times out when running `react-native link` 

### ISSUE THREAD

**Issue by imdadahad** [Microsoft/react-native-code-push#1107]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Install codepush into an RN project 
2. Run `react-native link`, follow the wizard

### Expected Behavior
Subdependencies to install, specifically for `React 0.11.0` to not time out

### Actual Behavior
What actually happens?

![image](https://user-images.githubusercontent.com/5855115/34006288-a86271dc-e0f5-11e7-9f63-6563555ecd27.png)

Installing React (0.11.0) eventually times out. It continues to prompt for the next step:

![image](https://user-images.githubusercontent.com/5855115/34006318-beffa20c-e0f5-11e7-930a-7ffe87cb185a.png)

However, scrolling above and see the folllowing error when it timed out:

![image](https://user-images.githubusercontent.com/5855115/34006344-dafc610c-e0f5-11e7-88c4-2c279625bc58.png)

**Comment by ruslan-bikkinin** [comment]
Hi @imdadahad and thanks for sunmitting the issue. I believe this issue is related to connection problems with github. Please, try again later or check your network settings. 

PLease let us know if it helps or any updates.

**Comment by imdadahad** [comment]
My mistake, I never defined the necessary dependencies in the Podfile.
