### ISSUE TITLE
Can we give a tips when no update avilable?

### ISSUE THREAD

**Issue by jinghun1999** [Microsoft/react-native-code-push#1108]
When i call the method codepush.sync, there is no update , but no tips to the user, how can i give a tips to the user like 'The app is up to date already.' Thx for replay

**Comment by sergey-akhalkov** [comment]
Hi @jinghun1999, thanks for reaching us, please take a look at 
https://github.com/Microsoft/react-native-code-push/blob/553e2eaef00583ce1fdf24b76f6025b7f0a9d8fc/Examples/CodePushDemoApp/App.js#L35

Let me know if you have any other questions.

**Comment by sergey-akhalkov** [comment]
Hi @jinghun1999, closing this, please feel free to reopen or create new one in case of any questions/issues.
