### ISSUE TITLE
[Error]  The uploaded package is identical to the contents of the specified deployment's current release.

### ISSUE THREAD

**Issue by qingfeng** [Microsoft/react-native-code-push#111]
```
(*'-') < react-native bundle --platform ios --entry-file index.ios.js --bundle-output main.jsbundle
bundle: Created ReactPackager
bundle: Closing client
bundle: start
bundle: finish
bundle: Writing bundle output to: main.jsbundle
bundle: Done writing bundle output
Assets destination folder is not set, skipping...
```

next:
```
(*'-') < code-push release say main.jsbundle 0.0.1                                               15-12-16 18:39
[Error]  The uploaded package is identical to the contents of the specified deployment's current release.
```

why?

thanks

**Comment by geof90** [comment]
Sometimes this happens: https://github.com/facebook/react-native/issues/4289
Try again with the --reset-cache option.

**Comment by qingfeng** [comment]
`code-push --reset-cache` ?
Where is `$TMPDIR `?
thanks

**Comment by ohtangza** [comment]
As of today, better to try "--noDuplicateReleaseError"

**Comment by bhagwans** [comment]
i tried  "--noDuplicateReleaseError"  but same error it is giving even though i changed code.
im implementing codepush with ionic 2(IOS).
my ionic info

Cordova CLI: 7.0.1 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v6.10.3

**Comment by ruslan-bikkinin** [comment]
Hello, @bhagwans, and thanks for reaching us. I have created test application with such configuration:
```
Cordova CLI: 7.0.1
cordova-plugin-code-push: v1.9.5-beta
```
 then I have executed three sequential `release-cordova` commands: 
* `code-push release-cordova testapp_cordova android`, which have produced successful release;
* `code-push release-cordova testapp_cordova android`, which have produced `duplicate release` error;
* `code-push release-cordova testapp_cordova android --noDuplicateReleaseError`, which have produced `duplicate release` warning.

In my case, code-push cli had been working as expected. If you need additional help regarding your question, please, feel free to open new issue in https://github.com/Microsoft/cordova-plugin-code-push repo using issue template specified there.

**Comment by bhagwans** [comment]
Hi @ruslan-bikkinin , thanks for commenting
Actually it is working in android as expected but not in ios.

**Comment by ruslan-bikkinin** [comment]
@bhagwans I tried to reproduce this behavior on macOs Sierra 10.12.5, but it works as expected there too.

**Comment by sergey-akhalkov** [comment]
Hi @bhagwans, could you please provide us with the version of your code-push-cli? In bash please execute `code-push -v` command.

**Comment by bhagwans** [comment]
hello @sergey-akhalkov, thanks for commenting. my code-push version is 2.0.2-beta

**Comment by wuyunqiang** [comment]
I met this bug,how to do?

**Comment by bhagwans** [comment]
i met with same error in android as well and it got solved by changing version in xml.

**Comment by bhagwans** [comment]
version should be less than the previously specified version.

**Comment by youngjuning** [comment]
same issues

**Comment by chhornponleu** [comment]
I recently face the same issue and could not find helpful solution. I tried to understand the message and found out that I was `trying to release the same code` as new version.

I change few lines of code and retry. 
....
It works then!!!

**Comment by ChangerHe** [comment]
It appeared when your code does not change everything, but you pushed twice.

**Comment by shravanpillow** [comment]
I got a solution for this. You need to change 2-3 lines in your code and if it is not working then add more.It should work.

Best of luck.

**Comment by caturadjiprasetyo** [comment]
> I got a solution for this. You need to change 2-3 lines in your code and if it is not working then add more.It should work.
> 
> Best of luck.

still got this error after change the code, i use Github action for automatic the process
