### ISSUE TITLE
code-push overwrite build with superior build version

### ISSUE THREAD

**Issue by tirrorex** [Microsoft/react-native-code-push#1110]
### Steps to Reproduce
1. code-push release-react yourApp ios (build is 1.0)
2. code-push promote yourApp staging production
3. publish a testflight build with a new version number (build is 1.0.1)
4. js bundle will be overwritten by code-push on second run

### Expected Behavior
What you expected to happen?

Since i bumped the version to prevent code-push for overwritting my bundle i expect it not to do it obviously.

### Actual Behavior
What actually happens?

Bundle got rewritten on second run on every device

### Environment

* react-native-code-push version: 5.2.0-beta
* react-native version: ^0.50.3
* iOS/Android/Windows version: ios 11.2
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device?

I assume it is a bug as i fail to understand how this can be expected behaviour.
code-push deployment ls youApp gives me version 1.0 so the build shouldn't be target version 1.0.1 ?

**Comment by sergey-akhalkov** [comment]
Hi @tirrorex, thanks for reaching us, this is the expected behavior, please see https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter

Another words 1.0 is a wildcard constraint matching >=1.0.0 <1.1.0.

Please let me know if you have any other questions.

**Comment by tirrorex** [comment]
Is there anything to do in order to overwritte this once the build is in production ?
The only solution i found was to clear the production build since we had no build to rollback to.

**Comment by sergey-akhalkov** [comment]
@tirrorex, you can use [patch](https://github.com/Microsoft/code-push/tree/master/cli#patching-update-metadata) command of the `code-push` or `appcenter` CLIs to target the exact version you want.

**Comment by tirrorex** [comment]
Will look into that, thanks for your time mate
