### ISSUE TITLE
react-native link continually prompts for crash report configuration

### ISSUE THREAD

**Issue by imdadahad** [Microsoft/react-native-code-push#1111]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Integrate codepush into a react-native project
2. Run `react-native link` and complete first step (key config)
3. Run `react-native link` going forward and it always prompts for crash report configuration options:

It prompts twice (ios & android).

### Expected Behavior

Not to prompt for this again (only on the first time of setup).

### Actual Behavior
What actually happens?

![image](https://user-images.githubusercontent.com/5855115/34159070-be502624-e4bf-11e7-9c11-6b058d51a73f.png)

**Comment by ruslan-bikkinin** [comment]
Hi @imdadahad and thanks for submitting the issue. Codepush doesn't provide such steps for linking. The only things that CodePush is asking during the link are Deployment Keys for iOS and Android. I believe your issue relates to `appcenter-crashes` or `appcenter-analytics` module for RN. Please, feel free to submit new issue in related [repo](https://github.com/Microsoft/appcenter-sdk-react-native/issues), so guys who are familiar with this workarea will be able to help you much faster.

**Comment by ruslan-bikkinin** [comment]
So I am closing this, feel free to re-open this if you will have any questions or any updates.
