### ISSUE TITLE
Local SSZipArchive Build Error

### ISSUE THREAD

**Issue by LiuYibin** [Microsoft/react-native-code-push#1123]
You import the  source code of lib "SSZipArchive"  into your node package manually, but maybe you modify the code or the lib's version you are using is an version with build error.
when I import SSZipArchive in a separated Xcode project, there is no error when building.

**Comment by LiuYibin** [comment]
I import youor lib not via react-native-code-push, and no error any more.

**Comment by ruslan-bikkinin** [comment]
Hi @LiuYibin and thanks for reaching us. Could you please share with us detailed info about build error that was occurred during the building of your app (text output, screenshots)?

**Comment by LiuYibin** [comment]
<img width="1390" alt="wx20171228-171115 2x" src="https://user-images.githubusercontent.com/7300267/34406150-5e628e8e-ebf2-11e7-8e2d-0186e7386f65.png">
<img width="1400" alt="wx20171228-171142 2x" src="https://user-images.githubusercontent.com/7300267/34406151-5e9f2240-ebf2-11e7-9b08-4ec0b85fa246.png">
<img width="1400" alt="wx20171228-171154 2x" src="https://user-images.githubusercontent.com/7300267/34406152-5edc8fa4-ebf2-11e7-829a-e62b0947b823.png">
<img width="1279" alt="wx20171228-171236 2x" src="https://user-images.githubusercontent.com/7300267/34406153-5f1e1460-ebf2-11e7-98cf-bd545339ae6b.png">

as the pictures above, The error will disappear after I delete the code in your CodePush.podspec file and import the SSZipArchive lib dividually.
`s.subspec 'SSZipArchive' do |ss|
    ss.source_files = 'ios/CodePush/SSZipArchive/*.{h,m}', 'ios/CodePush/SSZipArchive/aes/*.{h,c}', 'ios/CodePush/SSZipArchive/minizip/*.{h,c}'
    ss.private_header_files = 'ios/CodePush/SSZipArchive/*.h', 'ios/CodePush/SSZipArchive/aes/*.h', 'ios/CodePush/SSZipArchive/minizip/*.h'
  end`

**Comment by ruslan-bikkinin** [comment]
@LiuYibin so you are trying to add `react-native-code-push` to your app via cocoa pods but your app has it's own `SSZipArchive` lib installed before? Please correct me if I missed something.

**Comment by LiuYibin** [comment]
YES.  The other npm package I import into RN project depend on SSZipArchive, too. But before I import your package,  every thing is OK. I found the source code of SSZipArchive imported via your CodePush.podspec file is not the latest code comparing with  its official latest version

**Comment by ruslan-bikkinin** [comment]
@LiuYibin please try to do the following steps and let us know if it would help you or not:

1. Re-add CodePush in your `ios/Podspec` file using approach from our [docs](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---cocoapods):

```
# `SSZipArchive` already in use
pod 'CodePush', :path => '../node_modules/react-native-code-push', :subspecs => ['Core', 'JWT', 'Base64']
```

2. Run `pod update` from `ios` directory

**Comment by LiuYibin** [comment]
Thank you very much. My issues are resolved by the steps you told.

**Comment by rendomnet** [comment]
@ruslan-bikkinin 
`pod 'CodePush', :path => '../node_modules/react-native-code-push', :subspecs => ['Core', 'JWT', 'Base64'] 
`gives error
```
[!] CocoaPods could not find compatible versions for pod "CodePush/Base64":
  In Podfile:
    CodePush/Base64 (from `../node_modules/react-native-code-push`)
```
