### ISSUE TITLE
How can I use my node modules instead of the modules & dependencies that codepush build system generates ?

### ISSUE THREAD

**Issue by prashantvv** [Microsoft/react-native-code-push#1124]
Hello, I'd like to know that how can I use my own dependency modules instead of modules that codepush build system generates. Reason being that when I saw the build output, it generated fresh dependencies as my git repo also don't have node_modules. So if I add the node_modules to git, will the codepush build system will use those or creates its own at build time. Actually I made some changes in the core dependencies so I need those edited dependencies only.

**Comment by ruslan-bikkinin** [comment]
Hi @prashantvv and thanks for questioning. Could you please clarify what build system you are talking about and also give us detailed example of what are trying to do?

**Comment by prashantvv** [comment]
What I did here is I developed a react native app, git hub it & connect the repo to codepush than start the building that by following basic intructions. As react native uses node_modules as dependencies (which are not uploaded on github) & I think codepush download that dependencies during its build process. Now my question here is that I edit some of those dependencies inside node modules, some are deprecated or not suits my react native version while some are UI changes in those dependencies which are local to my pc. The code push build system downloads fresh dependencies  (as per the build logs) but I dont need those fresh ones, I need the local edited dependencies. How can I achieve this ?

Secondly, if I put some node_modules on git and some not, will the code push build system will use my node modules or it will download the fresh ones again?

**Comment by ruslan-bikkinin** [comment]
Got it. Codepush itself doesn't have any custom tools to resolve nodejs dependencies during the build, control over the packages is in `react-native bundle` and `npm` hands. Generally, npm can handle conflicting dependencies by keeping package's own dependent package version within it. For example, `react-native-code-push` depends on `glob@^5.0.15`. If you want to use `glob@3.0.0` or `glob@my_custom_local_version` for your application npm will download your custom version and will be keeping 5.0.15 version for `react-native-code-push` separately so they will not be crossed with your one.

As for your second question, my advice is to run `npm i` after any changes with dependencies that take place in `package.json`.

Please let us know if it helps you or any updates.

**Comment by prashantvv** [comment]
hello, I'll do some testing & then I'll update my findings over here & then we can proceed to close the issue.

**Comment by sergey-akhalkov** [comment]
@prashantvv, closing this, please feel free to reopen if you see any issues after testing.
