### ISSUE TITLE
Randomly getting [Error]  socket hang up while releasing the build. 

### ISSUE THREAD

**Issue by sujitpk-perennial** [Microsoft/react-native-code-push#1125]
I am getting `[Error]  socket hang up`. I am trying to release the android build. It succeed 2 times out of 10. 

> $ code-push release-react App_Name android
> Detecting android app version:
> Using the target binary version value "1.0" from "android/app/build.gradle".
> Running "react-native bundle" command:
> node node_modules/react-native/local-cli/cli.js bundle --assets-dest /var/folders/wv/ztrkb6qx1yd5n8c8bs58s5r40000gq/T/CodePush --bundle-output /var/folders/wv/ztrkb6qx1yd5n8c8bs58s5r40000gq/T/CodePush/index.android.bundle --dev false --entry-file index.android.js --platform android
> Scanning 682 folders for symlinks in /Users/username/Desktop/appName/node_modules (10ms)
> Scanning 682 folders for symlinks in /Users/username/Desktop/appName/node_modules (51ms)
> Loading dependency graph, done.
> 
> bundle: start
> bundle: finish
> bundle: Writing bundle output to: /var/folders/wv/ztrkb6qx1yd5n8c8bs58s5r40000gq/T/CodePush/index.android.bundle
> bundle: Done writing bundle output
> bundle: Copying 12 asset files
> bundle: Done copying assets
> 
> Releasing update contents to CodePush:
> 
> [Error]  socket hang up
>

**Comment by ruslan-bikkinin** [comment]
Hi @sujitpk-perennial and thanks for your question. Did `Releasing update contents to CodePush:` action take more time than usual before throwing error? Could you please also share with us user name and app name you used and approximate time when you was making release so we could search for it in our backend logs.

**Comment by sujitpk-perennial** [comment]
@ruslan-bikkinin  Approximate time is 5 to 6 min. UserName is sujit and app name is AdPost_home_copy.  Is this happen when internet connection is slow ? Because I am facing low internet connection problem here.

**Comment by ruslan-bikkinin** [comment]
@sujitpk-perennial I checked our server statistics and didn't find any requests in past 48 hours that includes `sujit` or `AdPost_home_copy` entries. So please make sure you are connecting to official CodePush server for releasing updates.

**Comment by sujitpk-perennial** [comment]
@ruslan-bikkinin Sorry for sharing wrong information. Actually username is sujit.kaulavkar@perennialsys.com and app name is AdPost_Home.

**Comment by ruslan-bikkinin** [comment]
Hi @sujitpk-perennial I found several requests at December, 28 and all of them succeeded but had long response time. So in this case I think low internet connection speed was the reason for your issue. If this issue persists and you consider that low connection isn't the cause of it, please, feel free to re-open this.
