### ISSUE TITLE
Android application integration rn

### ISSUE THREAD

**Issue by wuyunqiang** [Microsoft/react-native-code-push#1128]
### Steps to Reproduce
1.I have android application and integration react native ,add codepush to app.
2. like that.
 ![androidtoRN文件目录.png](http://upload-images.jianshu.io/upload_images/3353755-f621b90453e1a9a2.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
3.
I click update.
![codepushupdate.gif](http://upload-images.jianshu.io/upload_images/3353755-e33941a339213d63.gif?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

4:
![codepushbug.png](http://upload-images.jianshu.io/upload_images/3353755-ba17c262187af2b3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### Expected Behavior
update app.

### Actual Behavior
bug like that.
![codepushbug.png](http://upload-images.jianshu.io/upload_images/3353755-ba17c262187af2b3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### Reproducible Demo
code:https://github.com/wuyunqiang/AndroidToRN

### Environment
"react": "^16.2.0",
 "react-native": "^0.50.4",
 "react-native-code-push": "^5.2.1",
 "react-navigation": "^1.0.0-beta.22"

I need help.
please.

**Comment by sergey-akhalkov** [comment]
Hi @wuyunqiang, thanks for reaching us!
Please double check if CodePush is installed correctly, especially step 3 from the [manual installation guide](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-android---manual).

**Comment by wuyunqiang** [comment]
@sergey-akhalkov 
https://github.com/Microsoft/react-native-code-push/issues/1133

**Comment by sergey-akhalkov** [comment]
Hi @wuyunqiang, got it, so I'm closing this because of #1133
