### ISSUE TITLE
android not running

### ISSUE THREAD

**Issue by showtan** [Microsoft/react-native-code-push#1131]
version:
 "react-native": "^0.49.3"    "react-native-code-push": "^5.1.1-beta"
error:
`Bundling `index.js`  [development, non-minified]  98.7% (1259/1267), failed.
error: bundling failed: UnableToResolveError: Unable to resolve module `react-na
tive-code-push` from `D:\project\read\src\containers\login\Splash.js`: Module do
es not exist in the module map`

I've configured it.

**Comment by sergey-akhalkov** [comment]
Hi @showtan, thanks for reaching us! 
Could you please provide us more info regarding your issue by filling out [this issue template ](https://github.com/Microsoft/react-native-code-push/issues/new). Please also double check if you've installed CodePush plugin correctly using [manual installation guide](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-android---manual).

**Comment by showtan** [comment]
@sergey-akhalkov 

version:
```
"react": "^16.0.0-alpha.12",
 "react-native": "^0.46.4",
"react-native-code-push": "^5.1.3-beta",
```

My settings:

`MainApplication.java`:

```
 import com.microsoft.codepush.react.CodePush;
@Override
    protected String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }
new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG),
```

`build.gradle`:

```
buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            buildConfigField "String", "CODEPUSH_KEY", '"xxxxxxxxxxxxxxx"'
        }
        releaseStaging {
            signingConfig signingConfigs.release
            buildConfigField "String", "CODEPUSH_KEY", '"xxxxxxxxxxxxxxx"'
        }
        debug {
            buildConfigField "String", "CODEPUSH_KEY", '"xxxxxxxxxxxxxxx"'
        }
    }
compile project(':react-native-code-push')
```

`settings.gradle`:

```
include ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
```

你帮我看看，少了什么
You help me to see, what's less？ thanks!

**Comment by showtan** [comment]
@sergey-akhalkov  
Also
build.gradle:
`apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"`

**Comment by sergey-akhalkov** [comment]
@showtan, please take a look and analyse configured with CodePush sample apps here https://github.com/Microsoft/react-native-code-push/tree/master/Examples and let us know if you have any questions or see any issues.

**Comment by max-mironov** [comment]
Closing the issue for now. If you are still facing the problem with configuration please reach us (even better would be to provide us a minimum example of the app which is not working).
