### ISSUE TITLE
update available alert pops up unexpected on the same code base

### ISSUE THREAD

**Issue by EthanChouTW** [Microsoft/react-native-code-push#1132]
### Steps to Reproduce
1. release a new staging build v2.1.0 on crashlytics
2. code-push my-App staging -t 2.1.0
3. `Update Available` pops up

### Expected Behavior
no pop up because it's the same code base, no difference

### Actual Behavior
update alert pops up,
and after click update button there's no difference

```
  STACK TRACE AND/OR SCREENSHOTS
```

### Environment

* react-native-code-push version: 5.1.1-beta
* react-native version: 0.51.0
* iOS/Android/Windows version: ios 11
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by ruslan-bikkinin** [comment]
Hi @EthanChouTW and thanks for reaching us. Could you please share with us native application logs generated by CodePush during update (they have `[CodePush]` prefix)?

**Comment by EthanChouTW** [comment]
[CodePush] Sync already in progress.
[CodePush] Checking for update.
[CodePush] Awaiting user action.
[CodePush] User cancelled the update.

looks like it's really something on remote need to update, but the code base is the same

**Comment by ruslan-bikkinin** [comment]
@EthanChouTW So you mean that you have application running with binary version `2.1.0`, then you are releasing 2.1.0 update via codepush, checking for update on real device (expecting that this update will be ignored due to version match) and codepush still suggests you to install update for v2.1.0? Did I get right or missed something?

**Comment by max-mironov** [comment]
@EthanChouTW please let us know if you have a chance to look at this.

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen.
