### ISSUE TITLE
Android application integration rn (2)

### ISSUE THREAD

**Issue by wuyunqiang** [Microsoft/react-native-code-push#1133]
### Steps to Reproduce
1.yarn add react-native-code-push
2.
settings.gradle：
```
include ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, 'node_modules/react-native-code-push/android/app')
```

build.gradle
```
apply from: "../node_modules/react-native/react.gradle"
apply from: "../node_modules/react-native-code-push/android/codepush.gradle"
dependencies {
    compile project(':react-native-code-push')
}
```
3.android studio run

### Expected Behavior
run success

### Actual Behavior
![buildbug.png](http://upload-images.jianshu.io/upload_images/3353755-9b998a898ab7e1c7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### Environment

* react-native-code-push version:"5.1.3-beta"
* react-native version:"^0.50.4"
* react: "^16.2.0",

I think this bug maybe about with
```
apply from: "../node_modules/react-native/react.gradle"
apply from: "../node_modules/react-native-code-push/android/codepush.gradle"
```
but I dont konw how to do.

**Comment by wuyunqiang** [comment]
额 OK。I konw how to fix this bug.
I change build.gradle like that:https://github.com/wuyunqiang/ReactNativeUtil/issues/19
and change codepush.gradle like that.
![codepushgradle.png](http://upload-images.jianshu.io/upload_images/3353755-556775a7c87ade9e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
now I have new problem.
<img width="621" alt="codepushapplicationnotfound" src="https://user-images.githubusercontent.com/13480948/34658333-106d49ba-f469-11e7-9987-d478d80c0fef.png">

HOW TO FIX?

**Comment by wuyunqiang** [comment]
ok I copy codepush package to my project.and is ok.

**Comment by sergey-akhalkov** [comment]
Hi @wuyunqiang, great! So, do I get it right if you've resolved the issue and it can be closed? Please let me know if you have any questions or see any issues.

**Comment by wuyunqiang** [comment]
OK。
code is here https://github.com/wuyunqiang/AndroidToRN
