### ISSUE TITLE
tabBar icons styles for iOS are gone after code-push update (RN 0.52)

### ISSUE THREAD

**Issue by abrel** [Microsoft/react-native-code-push#1138]
After having moved to react native 0.52 code push does not update my tabBar icons correctly (all styles seems to be ignored) for iOS
I have been using code-push from 0.44 to 0.47, this issue never happened to me.
This, I guess it is due to the update to 0.52.

### Steps to Reproduce
1. Open an app with a working tabBar (i.e. styles are correctly applied)
2. Wait for any update from code-push
3. Styles for tabBar icons are gone

### Expected Behavior
Styles for tabBar icons should be applied after a code push update

### Actual Behavior
Styles for tabBar icons styles are gone
See below: 

<img width="286" alt="screen shot 2018-01-11 at 19 52 45" src="https://user-images.githubusercontent.com/6062799/34841585-09c0d4d6-f709-11e7-832e-b941fc7f551b.png">

### Environment

* react-native-code-push version: 5.2.1
* react-native version: 0.52
* iOS/Android/Windows version: iOS
* Does this reproduce on a debug build or release build: Both
* Does this reproduce on a simulator, or only on a physical device: Physical device

**Comment by ruslan-bikkinin** [comment]
Hi @abrel and thanks for reaching us. Did you increment binary version of your application and release new codepush update using `--targetBinaryVersion` targetting this version? In case of changes to application that touches native side (including incrementing minor version of `reac- native` and `react-antive-code-push`) it is extremely necessary to release new binary version of application and do not mix up on-air updates for different binary versions. Please refer to relevant documentation [section](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter) if needed.

**Comment by sergey-akhalkov** [comment]
Hi @abrel, please also take a look at this issue https://github.com/Microsoft/react-native-code-push/issues/775 - you can probably have the same use case.

**Comment by abrel** [comment]
Hi Sergey, Ruslan,

Actually it happens on my dev env where to be fair I do not set --targetBinaryVersion but I do not think it can be due something like incompatible bundles:

Basically I deploy in dev using my CI. The process is quite straightforward:

- Pass tests (code rules, unit, e2e)
- update code-push for dev env
- Deploy ios build through testflight

Thus, in my code push history (in dev) I always have a code push version up to date with what I release in dev (as I could not care less about what happen to my previous dev versions due to the code push update). So far so good.

Then if i add a minor change and release it manually without going though the CI (Use case: I test the code push update in dev when I want to quickly patch a bug (JS only) in production to make sure nothing bad will happen). Then I get the update in dev and it starts messing with the tabBar icon styles

I can confirm that both the original build (released from the CI) and the code push update (that comes from my mac) have been bundled with the same RN version i.e. 0.52

**Comment by sergey-akhalkov** [comment]
HI @abrel, sorry for the delayed response. 

Could you please perform the following steps just to make sure your issue does not somehow relate to compatibility issues?
1. Build and install new binary version of your app on device 
2. Create new CodePush "test" deployment 
3. Release CodePush update to this deployment 
4. Verify if everything is ok an try to release another one update once again

Please let me know if you still have the issue with styles after performing steps above. If so, please share what kind of changes you are making while releasing a CodePush update, also the minimum working version of your app where the issue reproduces would be very helpful for us.

**Comment by max-mironov** [comment]
@abrel please let us know if you have a chance to look at this.

**Comment by ruslan-bikkinin** [comment]
I am closing this for now, please feel free to re-open it if needed.
