### ISSUE TITLE
Help --targetBinaryVersion and 'code-push promote' 

### ISSUE THREAD

**Issue by aliceathens** [Microsoft/react-native-code-push#1140]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Have two Binaries supported at the same time --targetBinaryVersion "~1.0" && --targetBinaryVersion "~2.0"
2. run 'code-push promote' on 2.0 bundle
3. code-push deployment ls <appName>

This only display the last promoted bundle 2.0 but where has my 1.0 targetBinaryVersion gone and is it still available to those with the app binary version 1.0?

### Expected Behavior
Have two Production code-push deployments targeting different Binaries and check they are are both still active and being downloaded and used...

### Actual Behavior
I'm not sure if this is possible I can't find any information about it and would like to know if this is in fact how code-push works before i release 2.0 to the app store.

**Comment by max-mironov** [comment]
Hello @aliceathens,  thanks for asking, could you please share exact commands you have executed?
Also please share with us the output of `code-push deployment history <appName> <deploymentName>` before and after you have executed promote command (for both deployments).

**Comment by aliceathens** [comment]
Exact order of commands below:

code-push release-react <appName> <deploymentName> --entryFile index.js --targetBinaryVersion "~1.0" --dev false

code-push promote <appName> Staging Production

code-push release-react <appName> <deploymentName> --entryFile index.js --targetBinaryVersion "2.0.0" --dev false

code-push promote <appName> Staging Production


┌───────┬───────────────────────────────┬─────────────┬───────────┬─────────────┬──────────────────────────┐
│ Label │ Release Time                  │ App Version │ Mandatory │ Description │ Install Metrics          │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v12   │ Nov 21, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v17 from "Staging") │             │           │             │ Total: 1                 │
│       │                               │             │           │             │ Rollbacks: 1             │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v13   │ Nov 22, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v18 from "Staging") │             │           │             │ Total: 2                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v14   │ Nov 22, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v19 from "Staging") │             │           │             │ Total: 5                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v15   │ Nov 24, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v20 from "Staging") │             │           │             │ Total: 3                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v16   │ Nov 24, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v21 from "Staging") │             │           │             │ Total: 3                 │
│       │                               │             │           │             │ Rollbacks: 1             │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v17   │ Nov 24, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v22 from "Staging") │             │           │             │ Total: 3                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v18   │ Nov 27, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v23 from "Staging") │             │           │             │ Total: 2                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v19   │ Nov 28, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v24 from "Staging") │             │           │             │ Total: 3                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v20   │ Nov 28, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v25 from "Staging") │             │           │             │ Total: 1                 │
│       │                               │             │           │             │ Rollbacks: 1             │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v21   │ Nov 28, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v26 from "Staging") │             │           │             │ Total: 2                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v22   │ Nov 28, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v27 from "Staging") │             │           │             │ Total: 4                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v23   │ Nov 29, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v28 from "Staging") │             │           │             │ Total: 1                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v24   │ Nov 29, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v29 from "Staging") │             │           │             │ Total: 1                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v25   │ Nov 30, 2017                  │ ~1.0        │ No        │             │ Active: 0.74% (1 of 136) │
│       │ (Promoted v30 from "Staging") │             │           │             │ Total: 4                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v26   │ Dec 1, 2017                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v31 from "Staging") │             │           │             │ Total: 5                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v27   │ Dec 1, 2017                   │ ~1.0        │ No        │             │ Active: 0.74% (1 of 136) │
│       │ (Promoted v32 from "Staging") │             │           │             │ Total: 5                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v28   │ Dec 3, 2017                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v33 from "Staging") │             │           │             │ Total: 2                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v29   │ Dec 3, 2017                   │ ~1.0        │ No        │             │ Active: 0.74% (1 of 136) │
│       │ (Promoted v36 from "Staging") │             │           │             │ Total: 4                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v30   │ Dec 4, 2017                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v39 from "Staging") │             │           │             │ Total: 1                 │
│       │                               │             │           │             │ Rollbacks: 1             │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v31   │ Dec 4, 2017                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v40 from "Staging") │             │           │             │ Total: 2                 │
│       │                               │             │           │             │ Rollbacks: 1             │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v32   │ Dec 4, 2017                   │ ~1.0        │ No        │             │ Active: 1.5% (2 of 136)  │
│       │ (Promoted v41 from "Staging") │             │           │             │ Total: 5                 │
│       │                               │             │           │             │ Rollbacks: 1             │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v33   │ Dec 6, 2017                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v42 from "Staging") │             │           │             │ Total: 1                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v34   │ Dec 6, 2017                   │ ~1.0        │ No        │             │ Active: 1.5% (2 of 136)  │
│       │ (Promoted v43 from "Staging") │             │           │             │ Total: 4                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v35   │ Dec 6, 2017                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v44 from "Staging") │             │           │             │ Total: 1                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v36   │ Dec 6, 2017                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v45 from "Staging") │             │           │             │ Total: 5                 │
│       │                               │             │           │             │ Rollbacks: 1             │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v37   │ Dec 7, 2017                   │ ~1.0        │ No        │             │ Active: 0.74% (1 of 136) │
│       │ (Promoted v46 from "Staging") │             │           │             │ Total: 2                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v38   │ Dec 7, 2017                   │ ~1.0        │ No        │             │ Active: 2.2% (3 of 136)  │
│       │ (Promoted v47 from "Staging") │             │           │             │ Total: 6                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v39   │ Dec 8, 2017                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v48 from "Staging") │             │           │             │ Total: 1                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v40   │ Dec 8, 2017                   │ ~1.0        │ No        │             │ Active: 0.74% (1 of 136) │
│       │ (Promoted v49 from "Staging") │             │           │             │ Total: 4                 │
│       │                               │             │           │             │ Rollbacks: 1             │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v41   │ Dec 8, 2017                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v50 from "Staging") │             │           │             │ Total: 1                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v42   │ Dec 8, 2017                   │ ~1.0        │ No        │             │ Active: 0.74% (1 of 136) │
│       │ (Promoted v51 from "Staging") │             │           │             │ Total: 4                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v43   │ Dec 11, 2017                  │ ~1.0        │ No        │             │ Active: 0.74% (1 of 136) │
│       │ (Promoted v52 from "Staging") │             │           │             │ Total: 1                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v44   │ Dec 11, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v53 from "Staging") │             │           │             │ Total: 3                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v45   │ Dec 11, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v54 from "Staging") │             │           │             │ Total: 5                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v46   │ Dec 12, 2017                  │ ~1.0        │ No        │             │ Active: 1.5% (2 of 136)  │
│       │ (Promoted v55 from "Staging") │             │           │             │ Total: 8                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v47   │ Dec 13, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v56 from "Staging") │             │           │             │ Total: 3                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v48   │ Dec 13, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v57 from "Staging") │             │           │             │ Total: 1                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v49   │ Dec 13, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v58 from "Staging") │             │           │             │ Total: 2                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v50   │ Dec 13, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v59 from "Staging") │             │           │             │ Total: 2                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v51   │ Dec 13, 2017                  │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v60 from "Staging") │             │           │             │ Total: 8                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v52   │ 22 days ago                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v62 from "Staging") │             │           │             │ Total: 2                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v53   │ 22 days ago                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v63 from "Staging") │             │           │             │ Total: 3                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v54   │ 21 days ago                   │ ~1.0        │ No        │             │ No installs recorded     │
│       │ (Promoted v64 from "Staging") │             │           │             │                          │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v55   │ 21 days ago                   │ ~1.0        │ No        │             │ Active: 0.74% (1 of 136) │
│       │ (Promoted v65 from "Staging") │             │           │             │ Total: 2                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v56   │ 21 days ago                   │ ~1.0        │ No        │             │ Active: 0.74% (1 of 136) │
│       │ (Promoted v66 from "Staging") │             │           │             │ Total: 4 (1 pending)     │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v57   │ 21 days ago                   │ ~1.0        │ No        │             │ Active: 0.74% (1 of 136) │
│       │ (Promoted v68 from "Staging") │             │           │             │ Total: 2                 │
│       │                               │             │           │             │ Rollbacks: 1             │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v58   │ 21 days ago                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v69 from "Staging") │             │           │             │ Total: 4                 │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v59   │ 15 days ago                   │ ~1.0        │ No        │             │ Active: 0% (0 of 136)    │
│       │ (Promoted v70 from "Staging") │             │           │             │ Total: 3 (6 pending)     │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v60   │ 14 days ago                   │ ~1.0        │ No        │             │ No installs recorded     │
│       │ (Promoted v71 from "Staging") │             │           │             │                          │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v61   │ 14 days ago                   │ ~1.0        │ No        │             │ Active: 46% (63 of 136)  │
│       │ (Promoted v72 from "Staging") │             │           │             │ Total: 64 (45 pending)   │
└───────┴───────────────────────────────┴─────────────┴───────────┴─────────────┴──────────────────────────┘

**Comment by max-mironov** [comment]
@aliceathens 
So `code-push deployment ls` command is showing only the latest release for the deployment.
`code-push deployment history <appName> <deploymentName>` is showing the whole picture. Here it looks like you have both releases, v12 for 1.0 ver and v13 for 2.0. Seems to  be correct.
Please let me know if I'm missing something or any questions.

**Comment by max-mironov** [comment]
Hey @aliceathens, I believe we can close the question for now, but please let us know if you still have more questions about this - we are gladly to look at!
