### ISSUE TITLE
react-native link react-native-code-push fails on a clean project build

### ISSUE THREAD

**Issue by di9it** [Microsoft/react-native-code-push#1141]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Get react-native-code-push
2. cd CodePushDemoApp
3. npm install
4. react-native link react-native-code-push

Scanning folders for symlinks in /Users/Alexander/src/react-native-code-push/Examples/CodePushDemoApp/node_modules (18ms)
rnpm-install info Android module react-native-code-push is already linked 
rnpm-install info iOS module react-native-code-push is already linked 
module.js:491
    throw err;
    ^

Error: Cannot find module '../../../../../package.json'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Alexander/src/react-native-code-push/scripts/postlink/ios/postlink.js:8:15)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
/Users/Alexander/src/react-native-code-push/Examples/CodePushDemoApp/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (/Users/Alexander/src/react-native-code-push/Examples/CodePushDemoApp/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

### Expected Behavior
What you expected to happen?
I'm expecting a working command "react-native link react-native-code-push"

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: **1000.0.0-beta**
* react-native version: **0.49.5**
* iOS/Android/Windows version: **-**
* Does this reproduce on a debug build or release build? **-**
* Does this reproduce on a simulator, or only on a physical device? **-**

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hello @di9it, I've tried it with new react native app and don't have any issues, my repro steps"
1) react-native init RNIssue1141
2) cd RNIssue1141
3) npm i
4) npm i --save react-native-code-push
5) react-native link react-native-code-push

Could you please try this and let me know if it works.

**Comment by max-mironov** [comment]
@di9it please let us know if you have a chance to look at this!

**Comment by max-mironov** [comment]
Closing the issue for now, please let us know if you still have this problem or have more questions.

**Comment by cq920702** [comment]
@di9it I have the same issue.Do you have resolved it?
