### ISSUE TITLE
how do I change entry file for Android?

### ISSUE THREAD

**Issue by kdong007** [Microsoft/react-native-code-push#1146]
in MainApplication.java, these codes were generated

```
 @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
```
But jsBundleFile is defined in library's constants

```
    public static String getJSBundleFile() {
        return CodePush.getJSBundleFile(CodePushConstants.DEFAULT_JS_BUNDLE_NAME);
    }
```
Is there some way to override this?

**Comment by sergey-akhalkov** [comment]
Hi @kdong007, thanks for reaching us, please take a look at https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-android.md#static-methods

**Comment by sergey-akhalkov** [comment]
Closing this, please feel free to reopen if you have any questions.
