### ISSUE TITLE
CodePush updating app only on manual sync (not updating with other frequencies)

### ISSUE THREAD

**Issue by mdsaddam** [Microsoft/react-native-code-push#1147]
Integrated CodePush in ReactNative (android) app (on real device) with following guide 
https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native

Working fine with the following code (Manual Update)
```

export default class App extends Component<{}> {

  checkForUpdates = () => {
    codePush.sync({
      updateDialog: true,
      installMode: codePush.InstallMode.IMMEDIATE
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Button
          title='Check for Updates'
          onPress={this.checkForUpdates}
        />
      </View>
    );
  }
}

let codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };
App = codePush(codePushOptions)(App);
```

Not working for the following code (Update on Resume, On Start etc)
```

export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Update On App Resume
        </Text>
      </View>
    );
  }
}

let codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_RESUME };
App = codePush(codePushOptions)(App);
```

### Environment

* react-native-code-push version: 5.2.1
* react-native version: 0.52.0
* iOS/Android/Windows version: 7.1.2 (Nougat)
* Does this reproduce on a simulator, or only on a physical device?
I tried on physical device.

**Comment by max-mironov** [comment]
Hello @mdsaddam, thanks for asking. 
Could you please try to follow the logic as we have in our demo app https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/App.js#L162 and let us know if it helps. In yes - we will update the docs accordingly. Thanks!

**Comment by mdsaddam** [comment]
Thanks @max-mironov 

Now it's working :+1:

**Comment by sergey-akhalkov** [comment]
Hi @mdsaddam, great! So I'm closing this, please feel free to reopen in case of any other issues or questions.

**Comment by max-mironov** [comment]
@mdsaddam thanks for update! We've added PR to make docs more clear (https://github.com/Microsoft/react-native-code-push/pull/1151).
