### ISSUE TITLE
Is codePush.sync required to be used with codePush HOC?

### ISSUE THREAD

**Issue by leoskyrocker** [Microsoft/react-native-code-push#1148]
This is a request for clarification regarding react-native-code-push's `codePush.sync()` method.
Do we always need to wrap the app with the `codePush()` HOC?
This is not playing well sometimes with other react-native packages like `react-native-navigation` for example.

FWIW I have tested on my app and it works without the HOC, it'd be nice though if current version *AND* future updates
can guarantee that `codePush.sync` can be used as a standalone method.

**Comment by max-mironov** [comment]
Hello @leoskyrocker, thanks for the interest to our project! 
You are right, no need to wrap the app with codepush, it is just a convenient way of integration for most of the users.
You can freely use e.g. a combination of [checking for update]( https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushcheckforupdate), [downloading](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#methods-1) remote package  and later [installing](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#methods) local package. Just be sure that [NotifyAppReady](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushnotifyappready) is called properly.

Please let us know if you have more questions.

**Comment by leoskyrocker** [comment]
Thank you. I'm assuming that means this behavior (ability to use these methods standalone without wrapping it with the convenience HOC) is intended and will be kept in future updates.
Closing since my question is answered. You guys are quick and awesome! :)

**Comment by max-mironov** [comment]
@leoskyrocker yeah, Im not aware of any plans for changing this!
Thanks for feedback :)
