### ISSUE TITLE
codepush.tools domain has expired

### ISSUE THREAD

**Issue by TheRusskiy** [Microsoft/react-native-code-push#1150]
Am I crazy or this domain is not working and nobody noticed?
<img width="756" alt="screen shot 2018-01-19 at 19 58 31" src="https://user-images.githubusercontent.com/2538374/35159354-68711c48-fd53-11e7-8848-6add192e7469.png">

**Comment by Zakeelm** [comment]
That was an error on our part, it should be working now!
