### ISSUE TITLE
Set deployment key asynchronously

### ISSUE THREAD

**Issue by pyr0hu** [Microsoft/react-native-code-push#1152]
Hello!

I'm currently using CodePush in my application, everything is running smoothly atm.

But I want to use the dynamic deployment feature. Currently the CodePush syncing is automatic and is installing on app background/resumes. CodePush is setup in index.js with the following:
```javascript
const opts = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.ON_NEXT_RESUME,
};

const app = codePush(opts)(appElement);
```

But I want to use the key from my user object, which is stored in AsyncStorage, so I cannot set it during app initialization. Is there any way I can set the current deployment key on the codePush object later in the app lifecycle (e.g. after login, after logout) or if I want to use dynamic deployment, I have to use manual syncing?

Thank you for the answers, the good job with this product, really loving it :)

**Comment by ruslan-bikkinin** [comment]
Hi @pyr0hu and thanks for questioning. Actually, you don't have to use `codePush()` - it is just a handy way to integrate CodePush for the most of the users and under the hood it wraps your root component with the new one that already integrated with codePush and calls predefined `sync` method within ([details](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L455-L509)). So, yes, you have to manually run `codePush.sync({deploymentKey: 'your-key-here'})` for dynamic deployment usage. 
Please let us know if this information was helpful for you or you need any more help from us.

**Comment by pyr0hu** [comment]
Hi @ruslan-bikkinin , thanks for the answer. Yes, this clear things up, I was just wondering if there was any way to change the config of the automatic syncing in run-time, but after checking out the source of the `codePush` decorator, I can tweak my setup for dynamic deployment :) (It's even easier than I tought :o )

**Comment by ruslan-bikkinin** [comment]
Glad to hear that @pyr0hu! So I am closing this, don't hesitate to re-open if you will need any more assistance from our side.
