### ISSUE TITLE
undefined is not an object (evaluating 'StatusBarManager.HEIGHT')

### ISSUE THREAD

**Issue by ghyzx** [Microsoft/react-native-code-push#1153]
It appear this error when i enter the React Native view from Native conditions. 

### Steps to Reproduce
mReactInstanceManager = ReactInstanceManager.builder()
            .setApplication(getApplication())
            .setBundleAssetName("index.bundle")
            .setJSMainModulePath("index")
            .addPackage(new CodePush(CodePush_DeploymentKey, RN_Activity.this, BuildConfig.DEBUG))
            .setJSBundleFile(CodePush.getJSBundleFile()) 
            .setUseDeveloperSupport(BuildConfig.DEBUG)
            .setInitialLifecycleState(LifecycleState.RESUMED)
            .build();

### Environment
"react": "16.2.0",
 "react-native": "0.52.0",
 "react-native-code-push": "^5.2.1"
Android 7.0 device

**Comment by ghyzx** [comment]
![question](https://user-images.githubusercontent.com/5229158/35224521-36e32526-ffc0-11e7-9111-732007bcf45f.jpg)

**Comment by iTOYS** [comment]
Hi @ghyzx 
Is this error reproduce without CodePush? How can I repro this? 
Could you please make a little project to repro?

**Comment by iTOYS** [comment]
@ghyzx 
Just a friendly ping. Do you still have this issue? Could you please provide information that I requested above.
