### ISSUE TITLE
"An update is available but it is not targeting the binary version of your app."What should I do?Next

### ISSUE THREAD

**Issue by zhaohailog** [Microsoft/react-native-code-push#1154]
I submitted a new version to CodePush, but there was a problem----"An update is available but it is not targeting the binary version of your app.". I was developed using the latest iOS RN and CodePush. Your document that can use this handleBinaryVersionMismatchCallback to handle, could you tell me how to deal with? I don't speak the JS language, please help me.

**Comment by annakocheshkova** [comment]
Hi @zhaohailog, thank you for reaching us. 
First of all, though this is unlikely, make sure that you have not been reinstalling the app on your device before releasing an update.
The common scenario is that you have released a wrong update. Could you please specify the command you used to release an update?
Could you also provide your release history via `code-push deployment history <appName> <deploymentName>` and specify the version of the app you are trying to update? You can find it in `Info.pslist` on iOS and in `build.gradle` on android.

**Comment by max-mironov** [comment]
@zhaohailog just a friendly ping on this :)

**Comment by zhaohailog** [comment]
@annakocheshkova 
<img width="955" alt="image" src="https://user-images.githubusercontent.com/34649662/35425087-3d7e58a8-0293-11e8-84be-df4c03f64d3d.png">

**Comment by zhaohailog** [comment]
@max-mironov  What do you mean? I have resolved the problem  .

**Comment by max-mironov** [comment]
@zhaohailog good to know, just want to be sure that the issue has been resolved for you :)
I'm closing this one now.
