### ISSUE TITLE
Can't release modifyed *.ttf from node_modules

### ISSUE THREAD

**Issue by MackYang** [Microsoft/react-native-code-push#1155]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. replace node_modules\react-native-vector-icons\fonts\iconfont.ttf
2. code-push release-react xxx Android -d Staging  --mandatory true
3.run xxx in android phone,can't display new vector-icons

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:2.1.6
* react-native version:0.51
* iOS/Android/Windows version:android 6.0
* Does this reproduce on a debug build or release build? staging
* Does this reproduce on a simulator, or only on a physical device? both

(The more info the faster we will be able to address it!)

**Comment by iTOYS** [comment]
Hi @MackYang, sorry for delay!
Seems like you [should rebuild](https://www.npmjs.com/package/react-native-vector-icons#option-with-gradle-recommended) your native application each time that you change fonts.
Or [copy](https://www.npmjs.com/package/react-native-vector-icons#option-manually-1) the contents in the Fonts folder to `android/app/src/main/assets/fonts`

Thanks!
