### ISSUE TITLE
How can I re-start my app programically?

### ISSUE THREAD

**Issue by quy1403** [Microsoft/react-native-code-push#1164]
How can I re-start my app programically. Because I want to alert a dialog to notify when The update was installed, then users can press 'Restart now' button, then my app will restart...
thanks u so much!

**Comment by quy1403** [comment]
@geof90 @lostintangent @max-mironov...  please help me, thanks

**Comment by sergey-akhalkov** [comment]
Hi @quy1403, thanks for reaching us.

>How can I re-start my app programically.

Please take a look at [codepush.restartApp](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushrestartapp) method.

Let me know if it helps or if you have any questions.

**Comment by ajwhite** [comment]
☝️ We do this by calling `CodePush.restartApp()`

**Comment by sergey-akhalkov** [comment]
Closing this, please feel free to reopen if you have any questions or see any issues.
