### ISSUE TITLE
react-native 0.52 gradle compile error

### ISSUE THREAD

**Issue by birkir** [Microsoft/react-native-code-push#1166]
### Steps to Reproduce
- Fresh react-native project with react-native-navigation and react-native-code-push.

While using wix/react-native-navigation and following the android installation guide for code-push (https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md#wix-react-native-navigation-applications)

```
/Users/***/Projects/***/android/app/src/main/java/com/***/MainApplication.java:25: error: cannot find symbol
public class MainApplication extends NavigationApplication implements ReactInstanceHolder {
                                                                      ^
  symbol: class ReactInstanceHolder
/Users/***/Projects/***/android/app/src/main/java/com/***/MainApplication.java:59: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
```

I know React Native 0.52.0 introduces a new way for rendering dev support related views on Android so ReactInstanceDevCommandsHandler has been renamed to ReactInstanceManagerDevHelper.

Maybe this has something to do with that.

### Environment

* react-native-code-push version: 5.2.1
* react-native version: 0.52.1
* react-native-navigation version: 1.1.361
* iOS/Android/Windows version: N/A
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? N/A

### Stacktrace
https://gist.github.com/birkir/97215f0bb0d725acfc8d32024f43e0b5

**Comment by ruslan-bikkinin** [comment]
Hi @birkir and thanks for reaching us. Did you add `ReactInstanceHolder` import:
```java
import com.microsoft.codepush.react.ReactInstanceHolder;
```
?

**Comment by birkir** [comment]
Yes, I have the import.
For clarification this works well for react native 0.51.x, once I upgraded react native to 0.52.x it won't compile.

**Comment by iTOYS** [comment]
Hi @birkir
Is this issue still happen with latest version of react-native-code-push?

**Comment by birkir** [comment]
All is good now!

**Comment by birkir** [comment]
Let me validate and get back to you

**Comment by iTOYS** [comment]
Closed. If you still facing this issue feel free to reopen
