### ISSUE TITLE
Force update on first open after fresh install from store

### ISSUE THREAD

**Issue by maxaggedon** [Microsoft/react-native-code-push#1170]
I think it would be awesome if CodePush could install its first update as if it were mandatory, so that users who install from store could directly benefit from the latest features and hotfixes released through CodePush.

### Use case
1. Publish an app to the store
2. Publish a non mandatory js update through CodePush
3. Install the app from the store

_Today_

4. Assuming CodePush is running on default config (non intrusive install), the latest release js bundle is only downloaded and the freshly installed app is not up-to-date until next resume/restart.

_In a perfect world_

4. CodePush downloads and installs the latest js bundle immediately.

**Comment by iTOYS** [comment]
Hi @maxaggedon 

It's impossible to download bundle before the first run.
In your case you can check first run inside your code and use following codepush config:
```
{ updateDialog: false, installMode: codePush.InstallMode.IMMEDIATE }
```

Thanks!
