### ISSUE TITLE
Using higher-order component does not download updates

### ISSUE THREAD

**Issue by lyahdav** [Microsoft/react-native-code-push#1179]
### Steps to Reproduce
1. Follow Option 1 under https://github.com/Microsoft/react-native-code-push#plugin-usage.
2. Launch app.
3. Push update.
4. Restart app to try and trigger download of update.

### Expected Behavior
Update is downloaded.

### Actual Behavior
Update doesn't get downloaded.

I found out this happened because of a mistake I made with `export` and `default` in my `App.js`:
```
export default class App extends Component<{}> {
...
}

App = CodePush(App);
```

The docs I linked to above don't have mention of `export` or `default` on the `MyApp` class, while the React Native project template by default produces a `export default App` component. I found the fix in the [demo project](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/App.js):
```
class App extends Component<{}> {
...
}

App = CodePush(App);
export default App;
```

Ideally the docs should be updated to explain this.

### Environment

* react-native-code-push version: 5.2.1
* react-native version: 0.48.4
* iOS/Android/Windows version: iOS 11.2 simulator
* Does this reproduce on a debug build or release build? Debug build configured to use CodePush
* Does this reproduce on a simulator, or only on a physical device? Simulator

**Comment by max-mironov** [comment]
Hey there @lyahdav thanks for pointing at this. 
We have added a little bit more explanation for CodePush integration in this PR: https://github.com/Microsoft/react-native-code-push/pull/1151/files
Probably this could be further improved, if you get a chance to create a PR to improve it that would be very much appreciated!

**Comment by iTOYS** [comment]
Readme updated on #1151
