### ISSUE TITLE
ReferenceError: Can't find variable: CodePush

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/react-native-code-push#1187]
### Steps to Reproduce
1. Installing all packages
2. Execute `react-native run-ios`

### Expected Behavior
Works well with CodePush

### Actual Behavior
<img width="559" alt="captura de pantalla 2018-02-06 a la s 5 48 08 p m" src="https://user-images.githubusercontent.com/2154886/35888518-e8c94b48-0b65-11e8-9453-f66ea41d88e3.png">

### Demo (Code)
```
import { AppRegistry } from 'react-native'
import App from './src/components/App'

//Configue Code Push
import codePush from 'react-native-code-push'
let codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL }

AppRegistry.registerComponent('bevyUp', () => codePush(codePushOptions)(App))
```

### Environment
  OS: macOS High Sierra 10.13.3
  Node: 6.11.4
  Yarn: 1.1.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.1 => 0.52.1

* react-native-code-push version: 5.2.1

Thanks in advance

**Comment by Chamode** [comment]
Heyy does anyone know the solution to this problem. I am facing it in iOS.

**Comment by alexandergoncharov** [comment]
Hi @Chamode,
Thanks for reporting!

Could you please check that you successfully installed plugin and imported it?

Thanks,
Alexander

**Comment by Chamode** [comment]
[CodePush] The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.

I did `react-native link react-native-code-push` and then ` pod install` . It works as expected on Android but not on iOS.

**Comment by Chamode** [comment]
the issue was with my podfile, it is solved now. Thanks
