### ISSUE TITLE
The feature of rollback when app crashes is not working

### ISSUE THREAD

**Issue by oney** [Microsoft/react-native-code-push#119]
I didn't dig where the bug is yet, but in my test, when app crashes, it doesn't rollback in next launch.
The version is 1.5.1-beta.
My step is releasing a version that will cause crash. The code is like
```javascript
componentDidMount() {
  this.ddd();  // <- crash because no this function
  CodePush.sync(...);
},
```

**Comment by lostintangent** [comment]
Are you seeing this on iOS or Android?

**Comment by oney** [comment]
Sorry. iOS.

**Comment by oney** [comment]
Hmm.... My steps are more complex.
If no update is installed and it installs a update that will crash, the rollback works.
If it install a update that works before, and then it installs a update that will crash, the rollback doesn't work. It means the app will crash in next launch.

**Comment by lostintangent** [comment]
Hmm interesting. Did this happen with 1.5.0? I didn't think we made any changes to rollback in 1.5.1 but we will investigate this ASAP. Also, does his happen to you on Android as well? Or only iOS?

**Comment by oney** [comment]
I don't test 1.5.0 and on Android.

**Comment by oney** [comment]
OK.
If I put `CodePush.sync` in front of crash code, the rollback works in both situation that is mentioned in above comment.
```javascript
componentDidMount() {
  CodePush.sync(...);
  this.ddd();  // <- crash because no this function
},
```

**Comment by lostintangent** [comment]
Interesting. OK we're investigating why that ordering dependency exists. Thanks for reporting this!

**Comment by oney** [comment]
Thanks! There is another information, I face the issue on both React Native 0.16.0 and 0.17.0.

**Comment by geof90** [comment]
Thanks @oney! We found the bug. Incremental diff updates had the side effect of causing rollbacks to fail, because files from the previous package were being moved instead of copied to the new update.

**Comment by oney** [comment]
Good! The bug is fixed in my test! :+1:

**Comment by lostintangent** [comment]
Yay! Thanks for the continued amazing feedback @oney!
