### ISSUE TITLE
js and css files (from assets) not loaded in device

### ISSUE THREAD

**Issue by sujitpk-perennial** [Microsoft/react-native-code-push#1198]
Currently working on react native app and using codepush to update the app data. I am terribly stuck in a problem where js and css files on webView are not downloading. I checked the 'application support' from home directory. I found that only images are downloaded from codePush but cannot see js or css files.

Provided the folder structure from Xocde and the response getting from CodePush in application support path.

Following command used to create main.jsbundle.

react-native bundle --platform ios --assets-dest ./ --dev false --entry-file index.ios.js --bundle-output iOS/main.jsbundle
To send update to codePush used following command.

code-push release-react app_name ios --description "message" 
I will really appreciate if you can at least point me in a right direction.

![a0vt3](https://user-images.githubusercontent.com/23031821/36146944-4fb6e9c0-10dc-11e8-9e88-00266783c2d7.png)
![ip0ha](https://user-images.githubusercontent.com/23031821/36146948-54a5a246-10dc-11e8-9855-e493aac26da4.png)

**Comment by iTOYS** [comment]
Hi @sujitpk-perennial 
`code-push release-react` runs bundler inside, and seems like `react-native bundle` doesn't bundle index.html dependencies.
Could you please try to publish CodePush release with `code-push release` command, e.g.:
```
code-push release app_name iOS/ *
```

**Comment by sujitpk-perennial** [comment]
Sorry for the late reply. I tried above command. But it is saying command is not correct. 
I tried other options from suggestions but no luck.

1. code-push release app_name ios/ *
2. code-push release app_name ./ios *
3. code-push release app_name specitic_path_a_single_js_file *

**Comment by iTOYS** [comment]
Please try to wrap asterisk in quotes:
```
code-push release AwesomeProjectCodePush-iOS ./ios "*"
```

**Comment by sujitpk-perennial** [comment]
I am getting error as 
[Error]  ENOENT: no such file or directory, stat 'ios/build/Intermediates/ArchiveIntermediates/AppName/BuildProductsPath/Release-iphoneos/AppName.app'

**Comment by iTOYS** [comment]
Seem like it's not a CodePush error, pleas try to bundle you app in separate folder and add needed assets manually:
```
$ react-native bundle --platform ios --assets-dest /tmp/codepush/app_name --dev false --entry-file index.ios.js --bundle-output /tmp/codepush/app_name/main.jsbundle
$ code-push release app_name /tmp/codepush/app_name "*"
```

If it's possible, could you please create some example project that i can use to reproduce your error.

**Comment by sujitpk-perennial** [comment]
I tried now above command. Now it is not giving me any error. But still not getting all files. 
I will share sample app.

**Comment by sujitpk-perennial** [comment]
@iTOYS I have uploaded created sample project and you will find it [here](https://files.fm/u/8qma3fmf) . Here I am just loading js on webView to show a alert.

**Comment by iTOYS** [comment]
@sujitpk-perennial 
Thanks a lot! I'll take a look ASAP!

**Comment by sujitpk-perennial** [comment]
@iTOYS have you find any reason. There is a same question was asked https://github.com/Microsoft/react-native-code-push/issues/1086#issuecomment-367747052.

**Comment by iTOYS** [comment]
Hi @sujitpk-perennial 
Unfortunately React doesn't bundle assets that not mentioned directly in JS(RN) code and we can't include they in a patch. You can try to add required files to `./assets` folder and publish new CodePush release

Just for clarification. If you publish(or build release) your application without CodePush is it work?

**Comment by sujitpk-perennial** [comment]
@iTOYS Thanks for your reply. I have already added js, css files into assets folder. But again it is not downloading those files on the phone. iOS app is not yet released on App Store as I am stuck at this stage.

**Comment by Arshiamidos** [comment]
follow my answer  
i hope it help you  
[this](https://github.com/Microsoft/react-native-code-push/issues/1086)

**Comment by sujitpk-perennial** [comment]
@Arshiamidos I already installed the app on my iPhone. Now I am doing some changes in js file which loads on webView. I am not able to update the app for those js files using codepush. Are you ?

**Comment by Arshiamidos** [comment]
@sujitpk-perennial  all assets and bundles are readonly so you can't change them if you want a config just save them in DOCEMUENT (NSHOMEDIRE i think)
so you can't modify read only objects
