### ISSUE TITLE
Can app update on first open?

### ISSUE THREAD

**Issue by xuan9230** [Microsoft/react-native-code-push#1200]
By default, when opening an app for the first time, app will download updates silently and perform the update when it's restarted. Is there any method I can let the app update on the very first time opening it?

Have tried adding a button which triggers
`codePush.sync({ updateDialog: true, installMode: codePush.InstallMode.IMMEDIATE });`
with the default `checkFrequence`: `on-app-start` .

It works when there's a new update available. However, if I just installed the app, and click the button to trigger `sync()`, then nothing happens. Console log shows:
```
[CodePush] Installing update.
[CodePush] Update is installed and will be run on the next app restart.
[CodePush] Checking for update.
```
Seems like the app first downloaded an update, and then when I call `sync()`, it just stuck.

Is there any way I can install that downloaded update immediately?

Thanks for any help.

**Comment by iTOYS** [comment]
Hi @xuan9230 
If you trigger `sync()` manually, please set checkFrequency to [MANUAL](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#checkfrequency)

Also please see this solution which should work perfect for you:
```
App = codePush({ updateDialog: true, installMode: codePush.InstallMode.IMMEDIATE })(App);
export default App;
```
Please let me know any results
Thanks!

**Comment by xuan9230** [comment]
Hi @iTOYS , thanks for your solution, now the app prompts user to update on the first open.
However, Apple doesn't allow this kind of dialog:

> While Apple's developer agreement fully allows performing over-the-air updates of JavaScript and assets (which is what enables CodePush!), it is against their policy for an app to display an update prompt. Because of this, we recommend that App Store-distributed apps don't enable the updateDialog option when calling sync, whereas Google Play and internally distributed apps (e.g. Enterprise, Fabric, HockeyApp) can choose to enable/customize it.

> 

That being said, click on the button to update is preferred. Not sure should I change checkFrequency to `MANUAL`? I still want the auto-update on app restart work, just wanting to add an extra button as an additional manual option on top of the silent update process.

**Comment by iTOYS** [comment]
I think you can use default options for CodePush wrapper function. And use following options in case of first run(you should detect it by himself):
```javascript
if (firstRun) {
   codePush.sync({ updateDialog: false, installMode: codePush.InstallMode.IMMEDIATE });
}
```

Thanks!

**Comment by xuan9230** [comment]
@iTOYS Yep, this solution does solve the problem, though jeopardizing user experience - the app will automatically update and restart, without the user knowing what's happening.

Above all, guess I'll have the dialog prompt for Android, and just let ios app update on the second time start, plus the manual solution. Thanks for help!
