### ISSUE TITLE
Unable to build Application if UWP app target UWP SDK >= 10.0.15063.0

### ISSUE THREAD

**Issue by adam-bratin** [Microsoft/react-native-code-push#1207]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.  Create a new react-native-windows project based on documentation provided from their [Getting Started Guide](https://github.com/Microsoft/react-native-windows/blob/master/docs/GettingStarted.md)
2.  yarn add react-native-code-push@latest
3. Added CodePush.csproj to project sln
4. Add Reference to UWP proj
5. Set TargetPlatformVersion to 10.0.16299.0
6. TargetPlatformMinVersion to 10.0.15063.0
7. Run MSBuild.exe /t:clean;restore;Rebuild /p:Configuration=Release /p:Platform=x64 /p:AppxBundle=Never <project.sln>

### Expected Behavior
The UWP should successfully build

### Actual Behavior

"ReactNativeTest\windows\ReactNativeTest.sln" (clean;restore;Rebuild target) (1) ->
(Restore target) ->
  ReactNativeTest\node_modules\react-native-code-push\windows\CodePush\CodePush.csproj :
 error NU1201: Project ReactNative is not compatible with uap10.0 (UAP,Version=v10.0). Project ReactNative supports: ua
p10.0.10240 (UAP,Version=v10.0.10240) [ReactNativeTest\windows\ReactNativeTest.sln]
  ReactNativeTest\node_modules\react-native-code-push\windows\CodePush\CodePush.csproj :
 error NU1201: Project ReactNative is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm. Project ReactNative
supports: uap10.0.10240 (UAP,Version=v10.0.10240) [ReactNativeTest\windows\ReactNativeTe
st.sln]
  ReactNativeTest\node_modules\react-native-code-push\windows\CodePush\CodePush.csproj :
 error NU1201: Project ReactNative is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm-aot. Project ReactNat
ive supports: uap10.0.10240 (UAP,Version=v10.0.10240) [ReactNativeTest\windows\ReactNati
veTest.sln]
  ReactNativeTest\node_modules\react-native-code-push\windows\CodePush\CodePush.csproj :
 error NU1201: Project ReactNative is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64. Project ReactNative
supports: uap10.0.10240 (UAP,Version=v10.0.10240) [ReactNativeTest\windows\ReactNativeTe
st.sln]
  ReactNativeTest\node_modules\react-native-code-push\windows\CodePush\CodePush.csproj :
 error NU1201: Project ReactNative is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64-aot. Project ReactNat
ive supports: uap10.0.10240 (UAP,Version=v10.0.10240) [ReactNativeTest\windows\ReactNati
veTest.sln]
  ReactNativeTest\node_modules\react-native-code-push\windows\CodePush\CodePush.csproj :
 error NU1201: Project ReactNative is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Project ReactNative
supports: uap10.0.10240 (UAP,Version=v10.0.10240) [ReactNativeTest\windows\ReactNativeTe
st.sln]
  ReactNativeTest\node_modules\react-native-code-push\windows\CodePush\CodePush.csproj :
 error NU1201: Project ReactNative is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Project ReactNat
ive supports: uap10.0.10240 (UAP,Version=v10.0.10240) [ReactNativeTest\windows\ReactNati
veTest.sln]
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo
https://github.com/adam-bratin/ReactNativeTest

### Environment
related to issue: Microsoft/react-native-windows#1644
* react-native-code-push version: react-native-code-push@^5.2.1
* react-native version: react-native@0.53.0
* iOS/Android/Windows version: Windows 10.0.16299.0
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Physical Device

(The more info the faster we will be able to address it!)

**Comment by Grosskopf** [comment]
i have a similar problem, scons fails at some thirdparty libraries:

[ 34%] Compiling ==> thirdparty\mbedtls\library\xtea.c
x509write_csr.c
xtea.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2def.h(355): error C2061: syntax error: identifier 'SOCKADDR_STORAGE'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2def.h(355): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2def.h(356): error C2143: syntax error: missing '{' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(840): error C2061: syntax error: identifier 'SOCKADDR_STORAGE'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(841): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(849): error C2061: syntax error: identifier 'SOCKADDR_STORAGE'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(850): error C2061: syntax error: identifier 'gsr_source'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(850): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(851): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(859): error C2061: syntax error: identifier 'SOCKADDR_STORAGE'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(862): error C2061: syntax error: identifier 'gf_slist'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(862): error C2059: syntax error: ';'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(862): error C2059: syntax error: '['
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared\ws2ipdef.h(863): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\ws2tcpip.h(832): error C2143: syntax error: missing ')' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\ws2tcpip.h(832): error C2143: syntax error: missing '{' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\ws2tcpip.h(833): error C2059: syntax error: ')'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\ws2tcpip.h(834): error C2054: expected '(' to follow 'SourceList'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\ws2tcpip.h(880): error C2143: syntax error: missing ')' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\ws2tcpip.h(880): error C2081: 'SOCKADDR_STORAGE': name in formal parameter list illegal
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\ws2tcpip.h(880): error C2143: syntax error: missing '{' before '*'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\ws2tcpip.h(881): error C2059: syntax error: ')'
C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um\ws2tcpip.h(882): error C2054: expected '(' to follow 'SourceList'
[ 34%] scons: *** [thirdparty\mbedtls\library\net_sockets.uwp.debug.32.x86.obj] Error 2

**Comment by adam-bratin** [comment]
pending fix in Microsoft/react-native-code-push#1209

**Comment by iTOYS** [comment]
Fixed in #1209
