### ISSUE TITLE
Upgrading to react-native 0.17.0 broke my  project

### ISSUE THREAD

**Issue by anback** [Microsoft/react-native-code-push#121]
Just tried to upgrade and i got this:

```
TypeError: One of the sources to assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.
```

on this line here:

![image](https://cloud.githubusercontent.com/assets/2440382/11918750/b7ee2ac6-a73e-11e5-8554-187545f48300.png)

**Comment by lostintangent** [comment]
Hey @anback. I'm not able to repro this issue unfortunately. After you upgraded to RN 0.17.0, did you make sure to run `react-native upgrade` and ensure to stop any running packager instances? Both of those can be potentially responsible for issues like this.

**Comment by lostintangent** [comment]
If after doing those steps, and you still repro this, could you let me know whether you're seeing this on Android or iOS? Whether you're debugging in Chrome or not? And whether this is a debug or release build? We tested all permutations and never noticed any issues, so it would be great to know if we missed something. Thanks!

**Comment by lostintangent** [comment]
I did a bunch more testing and can't repro this, so I'm going to close it, assuming that the issue was an incomplete RN upgrade or a packager caching issue. Please re-open if you tried the steps I mentioned above and still hit this problem.

**Comment by anback** [comment]
I got it working now when i reinstalled everything, closing issue

**Comment by lostintangent** [comment]
Awesome! Thanks for confirming. Apologies for the pain here. We've noticed that React upgrades really do require the upgrade, and it isn't specific to CodePush, it just looks like it is :)
