### ISSUE TITLE
How to setup codePush in eject RN project with third-party lib which already have SSZipArchive?

### ISSUE THREAD

**Issue by canyara** [Microsoft/react-native-code-push#1215]
I am trying to integrate codePush in eject RN project and manually install codePush plugin. But I cannot find a way to manual strip internal SSZipArchive code, because a third-party lib already have it. And the podfile intergration way need React dependency in podfile, but there is no need to react dependency podfile setting in eject RN project.

How to setup codePush in eject RN project with third-party lib which already have SSZipArchive?

* react-native-code-push version: 5.2.1
* react-native version: 0.52

**Comment by iTOYS** [comment]
Hi @canyara 
Please see 
https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---cocoapods

If you will have any questions let me know!

Thanks!
