### ISSUE TITLE
Timeline for RN 0.53 support?

### ISSUE THREAD

**Issue by peacechen** [Microsoft/react-native-code-push#1218]
### Steps to Reproduce
1.  Install react-native 0.53

### Expected Behavior
Build success

### Actual Behavior
`cannot find symbol class CodePush` (Android)

### Environment

* react-native-code-push version: 5.2.2
* react-native version: 0.53.3
* iOS/Android/Windows version:  Android 8.0
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? all

**Comment by Titozzz** [comment]
I'm using 0.53 without any issues

**Comment by peacechen** [comment]
@Titozzz 
Would you mind sharing your MainApplication.java code?  Mine is:
```
import com.microsoft.codepush.react.CodePush;
//...

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    protected String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }

//...
```

**Comment by iTOYS** [comment]
Hi @peacechen 
What's exactly should be updated in documentation?

**Comment by peacechen** [comment]
@iTOYS 
The main Readme at https://github.com/Microsoft/react-native-code-push has under the supported versions table:

| React Native version(s) | Supporting CodePush version(s)                       |
|-------------------------|------------------------------------------------------|
...
| v0.46-v0.52             | v5.1+ *(RN removed unused registration of JS modules)*|
| v0.53+                  | TBD :) We work hard to respond to new RN releases, but they do occasionally break us. We will update this chart with each RN release, so that users can check to see what our "official" support is.

It would help new users or people upgrading their CodePush by updating the supported RN version to v0.46-0.53 for CodePush v5.1
