### ISSUE TITLE
Both Andrroid and iOS apps did not update after following the steps to setup

### ISSUE THREAD

**Issue by ethanyuwang** [Microsoft/react-native-code-push#1220]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Followed the steps to setup codePush. Have made sure the keys are correct codepush staging and release keys.

2. Tried both the default sync and on background sync:
`App = codePush(App);`
```

App = codePush({
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.ON_NEXT_RESUME
})(App);
```
3. Running staging build on both an iOS simulator and an Android device

4. Uploaded a codepush update for each platform

5. Can see the update on AppCenter -> CodePush -> Staging

6. Restarted staging apps multiple times but apps didn't receive updates. In AppCenter it shows 0 installs too. 

### Expected Behavior
Apps should update after restart or resume

### Actual Behavior
Nothing happens

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: "^5.2.2"
* react-native version: "0.53.0"
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? Staging and release
* Does this reproduce on a simulator, or only on a physical device? iOS simulator and Android device

(The more info the faster we will be able to address it!)

**Comment by iTOYS** [comment]
Hi @ethanyuwang, sorry for delay!
You should `export` App after wrapping e.g:
```
class App extends React.Component {
...
}
...
export default App = codePush({
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.ON_NEXT_RESUME
})(App);
`

With this code all works fine for me!

Thanks!
