### ISSUE TITLE
AppCenter CodePush SDK release date?

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [Microsoft/react-native-code-push#1221]
As I saw in the CodePush welcome page: `http://microsoft.github.io/code-push/`

The new AppCenter CodePush SDK will be launched in Late Feb. 2018, but there is no announcement (yet?). Can I ask about the release date please?

**Comment by Zakeelm** [comment]
We've had some internal changes that have caused there to be some shifts in our proposed timeline. We're working on getting this straightened out and will updated the website with a new timeline as soon as possible!

**Comment by ajwhite** [comment]
@Zakeelm, our product is in a unique position when it comes to Code Push. Is there a good method of contact that I could reach out with our situation? We've been using Code Push since it came out and worked closely with folks like Jonathan Carter in the early days.
