### ISSUE TITLE
Android staging build crashes after manual sync

### ISSUE THREAD

**Issue by ethanyuwang** [Microsoft/react-native-code-push#1223]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Have followed all the steps to setup the sdk and keys
2. Used the code snippet from the tutorial for manual sync:

```
import React, { Component } from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import codePush from "react-native-code-push";

export default class App extends React.Component {

  codePushStatusDidChange(status) {
    switch(status) {
        case codePush.SyncStatus.CHECKING_FOR_UPDATE:
            console.log("Checking for updates.");
            break;
        case codePush.SyncStatus.DOWNLOADING_PACKAGE:
            console.log("Downloading package.");
            break;
        case codePush.SyncStatus.INSTALLING_UPDATE:
            console.log("Installing update.");
            break;
        case codePush.SyncStatus.UP_TO_DATE:
            console.log("Up-to-date.");
            break;
        case codePush.SyncStatus.UPDATE_INSTALLED:
            console.log("Update installed.");
            break;
    }
  }

  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <TouchableOpacity
          style = {{height: 70, width: 200, backgroundColor: 'grey'}}
          onPress={() => {
             codePush.sync({
                  updateDialog: true,
                  installMode: codePush.InstallMode.IMMEDIATE
              });
          }}>

        <Text>update</Text> 

      </TouchableOpacity>
      </View>

    )
  }
}

let codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };
App = codePush(codePushOptions)(App);
```

### Expected Behavior
App should update

### Actual Behavior
App crashes with logs below:
```

03-01 13:58:32.145  9261  9307 I ReactNativeJS: [CodePush] Checking for update.
03-01 13:58:32.149  9261  9307 I ReactNativeJS: [CodePush] Reporting binary update (0.9.7)
03-01 13:58:32.667  9261  9307 I ReactNativeJS: [CodePush] Awaiting user action.
03-01 13:58:34.322  9261  9307 I ReactNativeJS: [CodePush] Downloading package.
03-01 13:58:34.770  9261  9261 D ReactNative: ReactInstanceManager.detachViewFromInstance()


```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: "^5.2.2"
* react-native version: "0.53.0"
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? staging build
* Does this reproduce on a simulator, or only on a physical device? tested on a physical device

(The more info the faster we will be able to address it!)

**Comment by iTOYS** [comment]
Hi @ethanyuwang 
I've just tried your code example with react-native@0.54 and react-native-code-push@5.2.2
All works fine fo me:
```
[CodePush] Checking for update.
[CodePush] Reporting binary update (1.0)
[CodePush] App is up to date.
[CodePush] Checking for update.
[CodePush] Awaiting user action.
[CodePush] Downloading package.
[CodePush] Installing update.
[CodePush] Restarting app
```

Could you please try again with react-native@0.54?
Feel free to reopen issue if you still have the issue
