### ISSUE TITLE
Codepush fails to build with RN 0.54

### ISSUE THREAD

**Issue by amardeepranu** [Microsoft/react-native-code-push#1224]
### Steps to Reproduce
1. Fresh install of RN project (v0.54)
2. Cocoapods used to install dependencies for native iOS project
3. Install latest version of codepush
4. Try to build the app w/ Xcode

### Expected Behavior
The app should build successfully.

### Actual Behavior
Fails to build with the following error:
<img width="318" alt="screen shot 2018-03-02 at 11 14 59 am" src="https://user-images.githubusercontent.com/7548096/36909040-f84b8d08-1e0a-11e8-9b17-bf502fdfdbf1.png">

### Environment

* react-native-code-push version: 5.2.2
* react-native version: 0.54

**Comment by iTOYS** [comment]
Hi @amardeepranu, thanks for reporting!
Just for clarification. Does plugin work correct with RN@0.53?
Which cocoapods deps do you use?
Could you please attach your `CodePush.m` here?

Thanks!

**Comment by amardeepranu** [comment]
- Not sure I upgraded from RN@0.51.0
- Cocoapods deps:
```
def react_native
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'DevSupport',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTImage',
  'RCTLinkingIOS',
  'CxxBridge'
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # CxxBridge Dependencies
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end
```

**Comment by amardeepranu** [comment]
Any updates on this?

**Comment by iTOYS** [comment]
@amardeepranu 
Sorry for delay, I've just tested RN with Podfile, and all works fine for me.
If you add `)` to the end of your CodePush.m line 1, is it fix your problem?

Actually  we have correct `CodePush.m` in package and we doesn't modify it while working
