### ISSUE TITLE
[Question] This is the correct behavior?

### ISSUE THREAD

**Issue by lucianomlima** [Microsoft/react-native-code-push#1226]
I configured my app with CodePush in Android. Everything is ok and app is running well.
My config is simple:
```js
const codePushOptions = {
    checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME
};
export default CodePush(codePushOptions)(App);
```
Now I want to show custom alert only once, after update is installed and running.
Reading docs I found this approach:
```js
    componentDidMount() {
        CodePush.checkForUpdate()
        .then((update) => {
            if (!update) {
                console.log('>>>>> The app is up to date!');
            } else {
                console.log('>>>>> An update is available! Should we download it?', update);
            }
        });
        CodePush.getUpdateMetadata()
        .then((current) => {
            console.log('>>>>> Current version detected:', current);
            if (current && current.isFirstRun) {
                this.showAlert('Your app is updated!');
            }
        })
        .catch();
    }
```

### Steps to Reproduce
1. I install my app. In logs I see that new version is founded and installed. Logs:
```log
>>>>> Current version detected: null
>>>>> An update is available! Should we download it?', { deploymentKey: 'xxxxxxxxxxxxxxxxxxxx',
description: 'Rollback to version 0.7.6',
label: 'v13',
appVersion: '0.7.6',
isMandatory: false,
packageHash: '085a9c9a79f98248331662b9f45a888be4daaa4008d41099000d1dcd3ae3331a',
packageSize: 6625172,
downloadUrl: 'https://codepushupdates.azureedge.net/storagev2/WEVw83NCbHyZqoZJIAVDasgh5Xv48092a080-5fd4-4c5b-9941-df1cb825377d',
download: [Function],
isPending: false,
failedInstall: false }
```
2. Restart app and nothing changed because is the first codepush install. Logs:
```
>>>>> Current version detected: null
>>>>> The app is up to date!
```
3. I patch a pre-released version to appcenter to be enabled. Logs:
```
>>>>> Current version detected: null
>>>>> An update is available! Should we download it?', { deploymentKey: 'xxxxxxxxxxsdvfbgxxxxx',
description: 'Testing CodePush update alert',
label: 'v14',
appVersion: '0.7.6',
isMandatory: false,
packageHash: 'ab0cc41ffee505ce4568952b9897fb7935cc13f34a1a75df44320cfaed7c76b3',
packageSize: 1291664,
downloadUrl: 'https://codepushupdates.azureedge.net/storagev2/gh4ISUKqfZWmk4W6sRzq_IsHLCUc8092a080-5fd4-4c5b-9941-df1cb825377d',
download: [Function],
isPending: false,
failedInstall: false
```
4. Close My app through back button and open again: Logs:
```
>>>>> Current version detected: null
>>>>> The app is up to date!
```
5. My app don't show nothing different. I put some changes like background colors and the alert too, but remains at the same previous behavior.
6. Then I test remove App from background|applist (not using back button) and open again. This time, current version log don't returns null. Logs:
```
>>>>> Current version detected: { install: [Function],
isPending: false,
bundlePath: '/CodePush/index.android.bundle',
packageSize: 1291664,
binaryModifiedTime: '1520418731445',
packageHash: 'ab0cc41ffee505ce4568952b9897fb7935cc13f34a1a75df44320cfaed7c76b3',
isMandatory: false,
appVersion: '0.7.6',
label: 'v14',
downloadUrl: 'https://codepushupdates.azureedge.net/storagev2/gh4ISUKqfZWmk4W6sRzq_IsHLCUc8092a080-5fd4-4c5b-9941-df1cb825377d',
description: 'Testing CodePush update alert',
failedInstall: false,
deploymentKey: 'xxxxxxxxxxxxxxxxxxxxxxxx',
isFirstRun: true }
>>>>> The app is up to date!
```
7. If I exit (by back button) and open App again, this time the alert and bundle differences is showed correctly. But, all the time I'm exit by back button and open app again, alert is showed up! Even if I check that current.isFirstRun is true, because all the time this param is true.
8. Only if I remove app from background|applist (not using back button) and open again, The new version is applied with current.isFirstRun with false.

### Expected Behavior
After install the app, I'm expecting see only one alert and in next exit by back button and open again, alerts no show until next update.

### Actual Behavior
Alert always show after app opens until user manually remove app from AppList ou background.

### Environment

* react-native-code-push version: 5.2.2
* react-native version: 0.49.5
* iOS/Android/Windows version: latest
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? Android device

**Comment by iTOYS** [comment]
Hi @lucianomlima, sorry for delay!
Yes, this is correct behavior. Let me explain!
`current.isFirstRun` - means that you use package installed from codepush and it's run for the first time. If you just install binary version of application you won't have `current`.
In your case I can recommend add variable and store your custom state:

```javascript
let isFirstRun = true;
...
if (isFirstRun) {
   isFirstRun = false;
   this.showAlert('Your app is updated!');
}

```
 
Thanks!

**Comment by lucianomlima** [comment]
@iTOYS Thanks, but this is a bit confuse.
I open my app, then CodePush detects a new version and install it. Then I exit app with back button (Android) and open again... Instead of use downloaded version, still use previous version. It's needed to remove app from opened app list to finally use downloaded version.

In production this is totally unproductive for end users. If we do not explain that he needs to remove the application from the opened app list, he will never use the last downloaded version (except when it's a mandatory release).

So when the last downloaded version is finally applied, the user again needs to remove the application from the opened app list so that the isFirstRun is setted to false.

I can not understand this.

**Comment by iTOYS** [comment]
@lucianomlima 
I see. This is default behavior, if you would like to install new version `ON_RESUME`, just set up following options:
```
const codePushOptions = {
    checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME,
    installMode: codePush.InstallMode.ON_NEXT_RESUME
};
export default CodePush(codePushOptions)(App);
```
