### ISSUE TITLE
[Feature Request] Support codepush updating via a background service

### ISSUE THREAD

**Issue by AndrewJack** [microsoft/react-native-code-push#1233]
~Before this project becomes closed source~, I'd like to request this feature. If there's somewhere more appropriate to post this please let me know.

The ability to trigger a code push download in a Android JobScheduler service or ios background task would help speed up the deployment time of a code push.

I have attempted to do this with the current APIs however it requires starting up the JS runtime to trigger the bundle fetch. Additionally, the code that runs isn't optimised or supported in the background and only occasionally works.

Let me know if you need anymore detail or suggestions for implementation.

**Comment by yaronlevi** [comment]
+1 Could come as a very handy feature.

**Comment by Zakeelm** [comment]
Thanks for this feature request. This is a really cool idea. I would love to hear some additional details regarding the use cases and how you envision this feature would improve the current CodePush release flow!

**Comment by AndrewJack** [comment]
The release flow could look something like:

1) Release a CodePush update
2) Send a remote push trigger (APN, FCM, etc) or scheduled background job starts
3) Call CodePush api in Java or Objective C to sync the CodePush bundle
4) CodePush download the new bundle, if new bundle is available
5) CodePush can then wait for next app start to load the new bundle. Or if it is currently running follow some similar logic to the `installMode` used in the current JS sync method (ON_NEXT_RESTART or ON_NEXT_RESUME).

**Comment by Zakeelm** [comment]
Ah, I see. That makes sense. I can definitely see how that would improve the deployment time. I'm going to keep this open for now to see if others are interested in this as well!

**Comment by thevolcanomanishere** [comment]
@AndrewJack Codepush is becoming closed source?

**Comment by yogieputra8** [comment]
+1 Please support this feature :)

**Comment by yaronlevi** [comment]
@Zakeelm "App Center" is a dashboard (and a set of SDKs). It dose not replaces code push. If I am not mistaken, it will be baked into app centers sdk.

**Comment by Zakeelm** [comment]
@kelset At the moment, we don't have any updates to share on the roadmap. Our team has had a priority shift, so new feature work isn't happening as fast. We do recommend switching over to the App Center CLI whenever you find time though. There will not be in disruptions in your workflow when using the CodePush CLI though

**Comment by Zakeelm** [comment]
@yaronlevi The plan is to move CodePush SDK into the App Center SDK. CodePush isn't going anywhere.

**Comment by FrenchMajesty** [comment]
How is this looking? This seems to be a popular feature and a practical use case for CodePush.

If I detect a bug in my mobile app, update it and send in a hot update then I don't want my users to have to open my app and potentially run into the patched bug. It would make more sense to have the new bundle downloaded and installed so that when users use the app, they always experience the latest version.

**Comment by never00miss** [comment]
is there any update about this feature?

**Comment by DominikHinc** [comment]
Are there any updates? Has someone tried to implement it themselves?

**Comment by kanadgodse-lh** [comment]
+1 We would love to have this feature looking at our abysmal CodePush install rates and rollbacks!
