### ISSUE TITLE
How to specify binary app version directly?

### ISSUE THREAD

**Issue by L-Jovi** [Microsoft/react-native-code-push#1238]
Thanks for your smart project :)

It's not issue as title said, I have detached native and react-native projects that different from regular RN project structure.

If I type `code-push release-react ...`, this command will find `Info.plist` which provide binary app version(CFBundleShortVersionString), but we replace the key with variable like `$(xxx)`, thus code-push cli can not find the version string.

My simple question is, how could I specify binary app version string to code-push cli directly?

Thanks for your time.

**Comment by iTOYS** [comment]
Hi @L-Jovi,
You can use `--targetBinaryVersion| -t ` flag e.g.:
```
code-push release-react <appName> ios -t 1.0.0
```

Thanks!

**Comment by L-Jovi** [comment]
Thanks for your reply :)
