### ISSUE TITLE
Better error message when unable to connect to the network

### ISSUE THREAD

**Issue by qingfeng** [Microsoft/react-native-code-push#124]
[Error]  getaddrinfo ENOTFOUND codepush.azurewebsites.net codepush.azurewebsites.net:443

**Comment by CarlosLCervantes** [comment]
Seeing this today from the cli

**Comment by silhouettes** [comment]
@CarlosLCervantes, what command were you running when you got this? Are you able to get a consistent repro?

**Comment by CarlosLCervantes** [comment]
Any command that needed to hit the codepush server was failing with this.
I was able to diagnose it as an issue with our network. For some reason a DNS lookup to codepush.azurewebsites.net was failing for every box in our network.
I was able to push my updates out by tethering to my phone call network.

**Comment by silhouettes** [comment]
Thanks for the info, this was very useful and I'm glad you figured it out. We could maybe show a better error message here, I'll re-open this issue just to track that. Feel free to let us know if you run into anything else!

**Comment by silhouettes** [comment]
Thanks for reporting this! We have fixed our handling of network failures in code-push-cli@1.12.5-beta: https://github.com/Microsoft/code-push/releases/tag/v1.12.5-beta
