### ISSUE TITLE
Updating the Android Plugin for Gradle 

### ISSUE THREAD

**Issue by krunalsshah** [Microsoft/react-native-code-push#1242]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Open the Android project 
2. Open the react-native-code-push/android/ project

### Expected Behavior
What you expected to happen?
Project must compile

### Actual Behavior
```
  Error:Unsupported method: BaseConfig.getApplicationIdSuffix().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

Consult IDE log for more details (Help | Show Log)
```
Upgrading  to Android Gradle Plugin`2.3.0` will fix the problem above, although still not compatible with Android Studio `ver 3.x`

Upgrading to  Android Gradle Plugin `3.0.1` could be a move forward approach. 
https://developer.android.com/studio/build/gradle-plugin-3-0-0.html

- I plan to make changes to the `android` native module & can't get the project to compile (unless I download way old IDE) or upgrade `build.gradle` locally on fork
- I can volunteer to upgrade and engage with the core team after hearing back

**Comment by iTOYS** [comment]
Hi @krunalsshah 

Could you please clarify, what do you want to do?
This plugin perfectly builds with React-Native project in last Android studio.
gradle:2.2.3 and gradle:3.0.0
It's not a correct to build `react-native-code-push` separately 

Thanks!

**Comment by krunalsshah** [comment]
@iTOYS thanks for reaching out. Yes the plugin builds with React-Native Project.

Although `react-native-code-push`is a library project that can be build independently, correct?

Opening  the `react-native-code-push` project https://github.com/Microsoft/react-native-code-push/blob/master/android/build.gradle results in   `Error:Unsupported method: BaseConfig.getApplicationIdSuffix().` 

Error line : https://github.com/Microsoft/react-native-code-push/blob/master/android/build.gradle#L8
 
Android Studio Version : 3.0.1

Let's say if I were to make changes in the file https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java ,I'd need to open the `react-native-code-push` project & get it to compile.

**Comment by alexandergoncharov** [comment]
Hi @krunalsshah ,
Sorry for long delay.

You don't have to compile `react-native-code-push` android native module for developing. You can make changes in local package and then `npm install` it locally for testing changes or you can make changes in installed package for your project(`node_modules/react-native-code-push`).

About build issue of `react-native-code-push` android native module: I'm not sure that it is necessary to build module independently as it is module and it is good work with app but I'll investigate it.

Please let me know if my suggestions for development was useful for you or you have any questions.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @krunalsshah,

I'll close this issue for now as I haven't heard from you in a while. But please feel free to reopen it if you will have any questions.

Thanks,
Alexander
