### ISSUE TITLE
Can you change deployment keys and thus code push package with the same app build?

### ISSUE THREAD

**Issue by Catpants** [Microsoft/react-native-code-push#1244]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Call codePush.sync(deploymentKey: x, codePush.InstallMode.IMMEDIATE) from a button within the app. App does nothing.
2. Call codePush.sync(deploymentKey: y, codePush.InstallMode.IMMEDIATE) from another button within the app. App does nothing.

### Expected Behavior
What you expected to happen?
I expect the app to restart and apply a new code push package based on the different deployment key.
### Actual Behavior
What actually happens?
```
Nothing happens on the ui.
  STACK TRACE AND/OR SCREENSHOTS
logs:
An update is available, but it is being ignored due to having been previously rolled back
```

### Environment

* react-native-code-push version:5.1.3-beta
* react-native version:0.53.0
* iOS/Android/Windows version: tested on ios 11
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? only tested on device

(The more info the faster we will be able to address it!)

**Comment by iTOYS** [comment]
Hi @Catpants 
Please see [example usage](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#syncoptions) of SyncOptions.
Shortly, in your case:
```javascript
codePush.sync({ 
   deploymentKey: "KEY", 
   installMode: codePush.InstallMode.IMMEDIATE
});
```

Thanks!

**Comment by Catpants** [comment]
@iTOYS I apologise, my original code example was not accurate. I am indeed calling it like this:
      codePush.sync(
        { installMode: codePush.InstallMode.IMMEDIATE, deploymentKey: Config.CODEPUSH_KEY_IOS }
      )
I still have the issue where code push is rolling back and not syncing on demand with two different keys. I would like to know, is it even possible to do this?

**Comment by newyankeecodeshop** [comment]
I have noticed that calling `sync` to change deployment from Production to Staging will not install the staging build if CodePush determines that the current (production) bundle is up-to-date. We had to write native code which calls `CodePush.clearUpdates()` before calling `sync` so that the requested bundle would be downloaded.

**Comment by iTOYS** [comment]
@Catpants 
I've checked again with this config:
```
let codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };
export default App = codePush(codePushOptions)(App);
```
and with this `sync` call:
```
const Staging = "key_staging";
const Production = "key_production";
...
<TouchableOpacity
  style = {{height: 70, width: 200, backgroundColor: 'green'}}
  onPress={() => {
     codePush.sync({
          deploymentKey: Production, 
          updateDialog: true,
          installMode: codePush.InstallMode.IMMEDIATE
      },
      this.codePushStatusDidChange,
      this.codePushDownloadDidProgress);
  }}>
  <Text>Current version: 68(S)</Text> 
</TouchableOpacity>
...
```
So I haven't faced any issue.

**Could you please describe your flow?**

Thanks!

**Comment by NickToropov** [comment]
Hi @Catpants,
I am going to close this issue for now, but please feel free to reopen it if you still have any questions.

**Comment by samerdernaika** [comment]
i can`t update the app after changing the deploy key remotely plz help
