### ISSUE TITLE
Is it necessary to add the codepush bundle to new ipa app store builds?

### ISSUE THREAD

**Issue by thatjuan** [Microsoft/react-native-code-push#1248]
I've seen related questions, but I have yet to find a direct answer.

Every time I push a new ipa to TestFlight or the AppStore, any user who installs the ipa fresh (e.g. they didn't have the app before) will face a codepush update despite there not being any bundles in codepush newer than what's built into the ipa.

I assume this happens because the bundle that gets added to the ipa by RN resides in a different place where CodePush doesn't look? I see that after `codePush.sync()`, a new Application Support/CodePush folder gets created and the bundle gets downloaded there.

How can I prevent this update on fresh ipa installs when there's no legitimate codepush update available? Can I add the latest codepush bundle to the ipa before I release it? Or is there a better way?

**Comment by iTOYS** [comment]
Hi @thatjuan 
We are compare binaryHash and updateHash, if they are equal, we haven't update binary version.
If I right understand, you've built Release configuration and tested on real devices?

I've checked this case and all work as expected.

**Comment by iTOYS** [comment]
Hi @thatjuan, just a friendly ping)
Are you still facing this issue, do you have any updates?

Thanks!

**Comment by iTOYS** [comment]
Closing now. Feel free to reopen if you still facing this.
Thanks!
