### ISSUE TITLE
Re: Error 500 resulted on crash (in production)

### ISSUE THREAD

**Issue by SudoPlz** [Microsoft/react-native-code-push#1249]
Hi again @iTOYS , I received the same crash again, this is the new stacktrace:

```
Error 500:  
    /Users/idynopia/Development/Acuity/mobile/node_modules/code-push/script/acquisition-sdk.js:143:20 
    /Users/idynopia/Development/Acuity/mobile/node_modules/react-native-code-push/request-fetch-adapter.js:30:34 
    /Users/idynopia/Development/Acuity/mobile/node_modules/regenerator-runtime/runtime.js:65:15 _invoke
    /Users/idynopia/Development/Acuity/mobile/node_modules/regenerator-runtime/runtime.js:294:25 
    /Users/idynopia/Development/Acuity/mobile/node_modules/regenerator-runtime/runtime.js:65:15 _invoke
    /Users/idynopia/Development/Acuity/mobile/node_modules/regenerator-runtime/runtime.js:154:4 arg
    /Users/idynopia/Development/Acuity/mobile/node_modules/regenerator-runtime/runtime.js:164:39 
    /Users/idynopia/Development/Acuity/mobile/node_modules/promise/setimmediate/core.js:35 ex
    /Users/idynopia/Development/Acuity/mobile/node_modules/promise/setimmediate/core.js:114:62 
    /Users/idynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:151:6 callbacks
    /Users/idynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:201:9 k
    /Users/idynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:242:17 callImmediates
    /Users/idynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:327:17 value
    /Users/idynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:146:17 
    /Users/idynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:313:14 value
    /Users/idynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:145:17 value
    [native code] value
    [native code] value
```

Here's a more info:

batteryLevel
0.550000011920929
charging
0
freeDisk
27406671872
freeMemory
31031296
id
a3a0dc83c684a4955b7dea6c61e163b45fcff4ae
isAppStoreVersion
false
isMobile
true
jailbroken
false
latestAppStoreVersion
2.1.10
locale
en_US
manufacturer
Apple
model
iPhone 8 Plus (CDMA)
modelNumber
D21AP
orientation
portrait
orientationLocked
true
osName
iOS
osVersion
11.2.6
screenHeight
736
screenWidth
414
shakeGestureInvokesFeedback
false
shouldUpdateNativeVersion
false
timezone
null
totalMemory
2179104768

I've been getting that for a long time now every now and then.

Bugsnag says that's an unhandled exception, so the app did crash... :/

### Environment

* react-native-code-push version: **5.2.0-beta**
* react-native version: **0.51.0**
* iOS/Android/Windows version: **iOS**
* Does this reproduce on a debug build or release build? **release**
* Does this reproduce on a simulator, or only on a physical device? **device --> iPhone 7 Plus, iPhone 8 Plus**

**Comment by iTOYS** [comment]
Hi @SudoPlz 
I'm pretty sure that this our code can't crash your app.
As you can see we're just call callback at this point:
> https://github.com/Microsoft/code-push/blob/master/sdk/script/acquisition-sdk.ts#L224-L227

(there are equal to `acquisition-sdk.js:143:20`)

p.s. I recommend you to update `react-native-code-push` to latest version

**Comment by SudoPlz** [comment]
Got it, do you think it *could* crash the app in a previous version? (i.e the one I'm using `5.2.0-beta`) ?

**Comment by iTOYS** [comment]
Actually not, I've especially checked it with the old version

Could you tell me please where you got output above?(stacktrace)

**Comment by SudoPlz** [comment]
I got it from Bugsnag, the crash reporting service we're using and it's super weird because the first line doesn't give much information (`Error 500:` is super generic), any idea where it originates from?

**Comment by iTOYS** [comment]
Is it possible that Bugsnag reports all `unhandled promise rejection`?
And at this time app works fine

**Comment by iTOYS** [comment]
@SudoPlz 
https://docs.bugsnag.com/platforms/nodejs/other/#reporting-unhandled-errors

**Comment by SudoPlz** [comment]
Yes there is such an option but I surely don't have it enabled.
In fact I wasn't even aware it exists, and by default it's off.

Still that looks like a callback, it's not a Promise is it?

**Comment by iTOYS** [comment]
@SudoPlz 
> As of v2.0.0, Bugsnag reports process#unhandledRejection events by default.

**Comment by SudoPlz** [comment]
Hmm interesting find but if a Promise is unhandled the app is going to crash anyway won't it?

**Comment by SudoPlz** [comment]
Ok I'll try disabling that and check if the issue is gone.

Thanks for eyeballing this with me Artem.

**Comment by iTOYS** [comment]
@SudoPlz 
Could you please check if my fix works for you? #1253 

Thanks!

**Comment by SudoPlz** [comment]
Will do, thank you so much Artem.
I'm closing this for now, feel free to merge the PR, and I'll keep an eye open for incoming crash reports.

**Comment by SudoPlz** [comment]
The fix is still
