### ISSUE TITLE
Error 403 resulted on crash (in production)

### ISSUE THREAD

**Issue by SudoPlz** [Microsoft/react-native-code-push#1250]
Another one @iTOYS 

Here's the stacktrace:

	Error 403:  
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/code-push/script/acquisition-sdk.js:143:20 
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/react-native-code-push/request-fetch-adapter.js:30:34 
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/regenerator-runtime/runtime.js:65:15 _invoke
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/regenerator-runtime/runtime.js:294:25 
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/regenerator-runtime/runtime.js:65:15 _invoke
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/regenerator-runtime/runtime.js:154:4 arg
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/regenerator-runtime/runtime.js:164:39 
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/promise/setimmediate/core.js:35 ex
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/promise/setimmediate/core.js:114:62 
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:151:6 callbacks
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:201:9 k
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:242:17 callImmediates
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:327:17 value
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:146:17 
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:313:14 value
	    /Users/Dynopia/Development/Acuity/mobile/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:145:17 value
	    [native code] value
	    [native code] value

That looks very similar to https://github.com/Microsoft/react-native-code-push/issues/1249

### Environment

* react-native-code-push version: **5.2.0-beta**
* react-native version: **0.51.0**
* iOS/Android/Windows version: **iOS**
* Does this reproduce on a debug build or release build? **release**
* Does this reproduce on a simulator, or only on a physical device? **device --> iPhone 7 Plus, iPhone 8 Plus**

**Comment by iTOYS** [comment]
Duplicate #1249
