### ISSUE TITLE
Android Code Signing React Native

### ISSUE THREAD

**Issue by aliceathens** [Microsoft/react-native-code-push#1252]
Added code signing to my React Native application iOS seems to work fine however the new binary version of my Android app doesn't seem to show anything in the deployment history for picking up that there is a new bundle to download... I have no way to debug this please advise

### Steps to Reproduce
1. Followed steps here: https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md#code-signing-setup
2. Ran: code-push release-react app-android android --entryFile index.js --targetBinaryVersion "2.0.1" --dev false --privateKeyPath private.pem
3. code-push promote app-android Staging Production
4. Install new binary open and close the app multiple times
5. code-push deployment history app-android Production
6. result: 'No installs recorded'. 

### Expected Behavior
Active and total count of at least 1 for deployment history.

### Actual Behavior
What actually happens?
 'No installs recorded'. 

### Environment

* react-native-code-push version: 5.2.0-beta
* react-native version: "0.52.0
* iOS/Android/Windows version: NA
* Does this reproduce on a debug build or release build? NA
* Does this reproduce on a simulator, or only on a physical device? Physical Device

**Comment by iTOYS** [comment]
Hi @aliceathens,
Just for clarification, you are sure that installs were successful, but you don't see statistics, right?

**Comment by aliceathens** [comment]
@iTOYS no I don't think they were successful - it's almost like the app isn't detecting that there is an updated bundle thats available but my APK version is 2.0.1 and its been promoted and released for 2.0.1? or its rejecting the install but nothing is in the application logs on the phone..

**Comment by iTOYS** [comment]
Can you run app in Android Studio? If yes you would able to see codepush logs (`[CodePush]`)

**Comment by aliceathens** [comment]
[CodePush] logs from running the signed APK in the emulator with Android Studio:

04-10 21:32:08.058 24689-24689/com.app D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
04-10 21:32:11.128 24689-24739/com.app I/ReactNativeJS: Checking for updates.
04-10 21:32:11.256 24689-24739/com.app I/ReactNativeJS: [CodePush] Reporting binary update (2.0.1)

That's all I can see in Logcat entires for CodePush

**Comment by iTOYS** [comment]
Seem like you can't call `CodePush.sync()`.
There in my output:
```
04-10 12:01:16.722 4883-4883/com.awesomeproject D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
04-10 12:02:17.068 4883-4933/com.awesomeproject I/ReactNativeJS: [CodePush] Reporting binary update (1.0)
04-10 12:03:00.227 4883-4933/com.awesomeproject I/ReactNativeJS: [CodePush] Checking for update.
04-10 12:03:00.740 4883-4933/com.awesomeproject I/ReactNativeJS: [CodePush] Awaiting user action.
```

Could you please share your `codePushOptions` and how you setup CodePush in `App.js`?

**Comment by aliceathens** [comment]
FYI: The same code seems to work fine for iOS this has been live for a few months now with no deployment issues until I decided to add 'Code Signing' feature to my deployments. Never the less here are my options and setup:
```
let codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_START, updateDialog: false, installMode: codePush.InstallMode.ON_NEXT_RESTART };

class App extends React.Component {
....
   codePushStatusDidChange(status) {
		switch(status) {
				case codePush.SyncStatus.CHECKING_FOR_UPDATE:
						console.log("Checking for updates.");
						break;
				case codePush.SyncStatus.DOWNLOADING_PACKAGE:
						console.log("Downloading package.");
						break;
				case codePush.SyncStatus.INSTALLING_UPDATE:
						console.log("Installing update.");
						break;
				case codePush.SyncStatus.UP_TO_DATE:
						console.log("Up-to-date.");
						break;
				case codePush.SyncStatus.UPDATE_INSTALLED:
						console.log("Update installed.");
						break;
		}
	}

	codePushDownloadDidProgress(progress) {
		console.log(progress.receivedBytes + " of " + progress.totalBytes + " received.");
	}
       ....

       render() {
		return (
			<Provider store={store}>
				<AppWithNavigationState />
			</Provider>
		)
	}

}

export default App = codePush(codePushOptions)(App);

```

**Comment by iTOYS** [comment]
I've checked with the latest and with your versions of RN and plugin, still don't have any issues:
```
04-12 13:26:49.956 12819-12819/com.awesomeproject D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
04-12 13:26:56.493 12819-13057/com.awesomeproject I/ReactNativeJS: Checking for updates.
04-12 13:26:58.534 12819-13057/com.awesomeproject I/ReactNativeJS: Downloading package.
04-12 13:26:59.428 12819-13057/com.awesomeproject I/ReactNativeJS: 17997 of 155323 received.
04-12 13:26:59.444 12819-13057/com.awesomeproject I/ReactNativeJS: 26189 of 155323 received.
04-12 13:26:59.461 12819-13057/com.awesomeproject I/ReactNativeJS: 65101 of 155323 received.
04-12 13:26:59.477 12819-13057/com.awesomeproject I/ReactNativeJS: 81485 of 155323 received.
04-12 13:26:59.494 12819-13057/com.awesomeproject I/ReactNativeJS: 122445 of 155323 received.
04-12 13:26:59.503 12819-13057/com.awesomeproject I/ReactNativeJS: 155323 of 155323 received.
04-12 13:26:59.791 12819-13055/com.awesomeproject D/ReactNative: [CodePush] Applying diff update.
    [CodePush] Verifying hash for folder path: /data/user/0/com.awesomeproject/files/CodePush/01262515fce01c475db38347023acea024b4ffe9ba9424a2fba332e4759172c2
04-12 13:26:59.819 12819-13055/com.awesomeproject D/ReactNative: [CodePush] Manifest string: ["CodePush/drawable-mdpi/a.png:307337dfef87a15a738386105df8afd11fdd9ad85d73b50601132e67cc182b1b","CodePush/index.android.bundle.meta:5bca4df51258343720287ab9cf96df8909ae3014e83243babda2d87c660237ab","CodePush/index.android.bundle:55891a501674a80afd70a1ce0f1eabfdd9e922f3ba61d0c2425d169517762e8f"]
04-12 13:26:59.821 12819-13055/com.awesomeproject D/ReactNative: [CodePush] Expected hash: 01262515fce01c475db38347023acea024b4ffe9ba9424a2fba332e4759172c2, actual hash: 01262515fce01c475db38347023acea024b4ffe9ba9424a2fba332e4759172c2
    [CodePush] The update contents succeeded the data integrity check.
    [CodePush] Verifying signature for folder path: /data/user/0/com.awesomeproject/files/CodePush/01262515fce01c475db38347023acea024b4ffe9ba9424a2fba332e4759172c2
04-12 13:26:59.866 12819-13055/com.awesomeproject D/ReactNative: [CodePush] JWT verification succeeded, payload content: {claimVersion=1.0.0, iat=Thu Apr 12 13:25:23 GMT+03:00 2018, contentHash=01262515fce01c475db38347023acea024b4ffe9ba9424a2fba332e4759172c2}
    [CodePush] The update contents succeeded the code signing check.
04-12 13:26:59.913 12819-13057/com.awesomeproject I/ReactNativeJS: Installing update.
04-12 13:27:00.028 12819-13057/com.awesomeproject I/ReactNativeJS: Update installed.
```

**Comment by iTOYS** [comment]
Hi @aliceathens, just a friendly ping)
Are you still facing this issue, do you have any updates?

Thanks!

**Comment by iTOYS** [comment]
Closing now. Feel free to reopen if you still facing this.
Thanks!
