### ISSUE TITLE
Trigger hot fix logic from objC native side.

### ISSUE THREAD

**Issue by L-Jovi** [Microsoft/react-native-code-push#1254]
Hi, it's not a issue, if l caused any trouble, feel free to close it.

For some reason I want to call `sync` method from objC native side, how should I implement it?

Thanks for your time.

regards.

**Comment by iTOYS** [comment]
Hi @L-Jovi 
I hope that this article would be helpful for you
https://facebook.github.io/react-native/docs/communication-ios.html#calling-react-native-functions-from-native-events

Thanks!

**Comment by L-Jovi** [comment]
@iTOYS Thanks for your reply, maybe I didn't express clearly.

we have native project which have several page implemented by react-native,

I have no idea that where the best place to call `sync()` method, because when user launch app, they have no chance to request whole js bundle from server if they don't arrive pages which implements by react-native.

**Comment by iTOYS** [comment]
We've never faced this before. Did you try something? What result?
I guess the best place to call `sync` it's after your customer have loaded RN bundle, the same as in regular RN app
