### ISSUE TITLE
Why is it so slow to pull a hot update pack on a 4g network?

### ISSUE THREAD

**Issue by aijason** [Microsoft/react-native-code-push#1255]
Why is it so slow to pull a hot update pack on a 4g network?

**Comment by thevolcanomanishere** [comment]
@aijason you are not going to get any answers to your question unless you give more details. Just because it is a 4G network, doesn't mean that is guarantees high speed. 4G is just the protocol.

**Comment by iTOYS** [comment]
Closing for now. Feel free to reopen if you still faced this issue and provide all possible info that would be helpful for us!

Thanks!
