### ISSUE TITLE
Cannot push updates when using dynamic version name for different build types

### ISSUE THREAD

**Issue by kevindavee** [Microsoft/react-native-code-push#1256]
I'm using React Native to develop a mobile app for Android and iOS. I have 3 different build types/configuration (Android/iOS). On Android, I have debug, releaseStaging, and release (for production). And on iOS I have debug, release, production.

To differentiate version name between production and development, I use versionNameSuffix on release build Android. On iOS, I create some variables which is VERSION_NAME (e.g 1.0), VERSION_NAME_SUFFIX (I use -beta for debug and release build config), and VERSION_NAME_STRING which is the concatenation of VERSION_NAME and VERSION_NAME_SUFFIX (so on debug/release I get 1.0-beta, and production 1.0)

Now I want to push some updates to codepush. I use command

```appcenter codepush release-react -a org/appName -t "1.0-beta" -d Staging --mandatory```

And I got an error

```Error: Invalid binary version(s) for a release.```

Can anybody help me ? I need different version name for development and production, and I also need to use App Center Code Push

**Comment by iTOYS** [comment]
Hi @kevindavee 
This repo is not related for your issue. 
[Microsoft/appcenter-cli](https://github.com/Microsoft/appcenter-cli/) is better place for it:)
`appcenter-cli` uses [`semver.validRange`](https://www.npmjs.com/package/semver#ranges-1) under the hood. So `1.0-beta` isn't valid range, but `1.0.0-beta` is!

Thanks for reaching us!
