### ISSUE TITLE
Under what circumstances is there a rollback?

### ISSUE THREAD

**Issue by hannigand** [Microsoft/react-native-code-push#1260]
This isn't an issue per se, more like a request for some knowledge.

Yesterday, I released an updated bundle to CodePush. After I loaded up my app, I saw on AppCenter that there was a rollback on my device.

I then deleted the application and re-installed it, after that the bundle downloaded successfully.

I want to know, under what circumstances is there a rollback?

Could it be:
- Network dropped off during download?
- Erroneous JavaScript bundle? (I immediately ran the app on my Android Emulator and everything worked fine)

**Comment by ikhilko** [comment]
https://github.com/Microsoft/react-native-code-push/issues/880#issuecomment-342463583

**Comment by iTOYS** [comment]
Hi @hannigand,
There may be various circumstances. Was comment above helpful for you?
If you still faced this issue please try to log possible errors. All additional info would be helpful to faster resolve this issue!

Please let us know any result, Thanks!

**Comment by iTOYS** [comment]
Closing now. Feel free to reopen if you still facing this.
Thanks!
