### ISSUE TITLE
i just want to ask a question

### ISSUE THREAD

**Issue by xiaogaofudao** [Microsoft/react-native-code-push#1263]
my react-native version is 0.55. does codepush support now?

**Comment by xiaogaofudao** [comment]
when it will be supported?

**Comment by iTOYS** [comment]
@alexandergoncharov PTAL

**Comment by alexandergoncharov** [comment]
Hi @xiaogaofudao,

Thanks for reporting!
I tested plugin with RN@0.55.3: No issues found.
Created PR for updating Readme.
I'll close this issue. If you will have any questions please feel free to reopen it or create new.


Thanks,
Alexander
