### ISSUE TITLE
Code-signing on windows (clients)

### ISSUE THREAD

**Issue by achipa** [Microsoft/react-native-code-push#1265]
Windows (as a target platform, ie react-native-windows) does not seem to be supported wrt to code-signing according to

https://github.com/Microsoft/code-push/blob/master/cli/README.md#code-signing

... which only lists Android and iOS as supported OSs. Is windows support for code-signing on the roadmap, or is there something else missing on the windows platform/parts of code push that prevents this functionality (or is it simple a case of "we take patches")?

**Comment by Zakeelm** [comment]
Going to go ahead and close this for now. We've spoken via email regarding this. If you would like to take the steps regarding contribution for this item, please follow up in this thread and we can try to help steer you in the right direction.
