### ISSUE TITLE
index.android.bundle: No such file or directory

### ISSUE THREAD

**Issue by tarunkonda123** [Microsoft/react-native-code-push#1266]
I/ReactNativeJS: [CodePush] Checking for update.
I/ReactNativeJS: [CodePush] Checking for update.
I/ReactNativeJS: [CodePush] Downloading package.
I/ReactNativeJS: [CodePush] Downloading package.
D/ReactNative: [CodePush] Error deleting file download.zip
D/ReactNative: [CodePush] Applying full update.
I/ReactNativeJS: [CodePush] Installing update.
I/ReactNativeJS: [CodePush] An unknown error occurred.
eactexample/files/CodePush/unzipped/CodePush/index.android.bundle.meta: open failed: ENOENT (No such file or directory)
I/ReactNativeJS: [CodePush] Update is installed and will be run on the next app restart.

After restart

 Process: t.com.reactexample, PID: 13949
    com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/data/t.com.reactexample/files/CodePush/d0eba7f5a364cac891fc23cf0353bdc675d0aee9793afade0787ea3e3acca6a3/CodePush/index.android.bundle: No such file or directory
        at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
        at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:221)
        at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:52)
        at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:234)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1114)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
        at java.lang.Thread.run(Thread.java:818)

**Comment by alexandergoncharov** [comment]
Hi @tarunkonda123,

Thanks for reporting!
Could you please provide some part of code which can help me reproduce your issue?
Also, would be great if you will provide your Android version.

Thanks,
Alexander

**Comment by tarunkonda123** [comment]
Hi @alexandergoncharov Thanks for your valuable time
build gradle ::
apply plugin: 'com.android.application'

import com.android.build.OutputFile




apply from: "../node_modules/react-native/react.gradle"
apply from: "../node_modules/react-native-code-push/android/codepush.gradle"

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 */
project.ext.react = [
        // the name of the generated asset file containing your JS bundle
        bundleAssetName: "index.android.bundle",

        // the entry file for bundle generation
        entryFile: "index.android.js",

        // whether to bundle JS and assets in debug mode
        bundleInDebug: true,

        // whether to bundle JS and assets in release mode
        bundleInRelease: true,

        // whether to bundle JS and assets in another build variant (if configured).
        // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
        // The configuration property can be in the following formats
        //         'bundleIn${productFlavor}${buildType}'
        //         'bundleIn${buildType}'
        // bundleInFreeDebug: true,
        // bundleInPaidRelease: true,
        // bundleInBeta: true,

        // the root of your project, i.e. where "package.json" lives
        root: "../../",

        // where to put the JS bundle asset in debug mode
        jsBundleDirDebug: "$buildDir/intermediates/assets/debug",

        // where to put the JS bundle asset in release mode
        jsBundleDirRelease: "$buildDir/intermediates/assets/release",

        // where to put drawable resources / React Native assets, e.g. the ones you use via
        // require('./image.png')), in debug mode
        resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",

        // where to put drawable resources / React Native assets, e.g. the ones you use via
        // require('./image.png')), in release mode
        resourcesDirRelease: "$buildDir/intermediates/res/merged/release",

        // by default the gradle tasks are skipped if none of the JS files or assets change; this means
        // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
        // date; if you have any other folders that you want to ignore for performance reasons (gradle
        // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
        // for example, you might want to remove it from here.
        inputExcludes: ["android/**", "ios/**"],

        // override which node gets called and with what additional arguments
        nodeExecutableAndArgs: ["node"],

        // supply additional arguments to the packager
        extraPackagerArgs: []
]




/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false



android {
    signingConfigs {
        ReactNatveExample {
            keyAlias 'ReactNatveExample'
            keyPassword 'ReactNatveExample'
            storeFile file('/home/shirin/Desktop/ReactExample/KeyStore.jks')
            storePassword 'ReactNatveExample'
        }
    }
    compileSdkVersion 27
    defaultConfig {
        applicationId "t.com.reactexample"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.ReactNatveExample
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.facebook.react:react-native:+'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation project(':react-native-code-push')
}
// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

MainActivity:

import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.view.KeyEvent;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactRootView;
import com.facebook.react.common.LifecycleState;
import com.facebook.react.modules.core.DefaultHardwareBackBtnHandler;
import com.facebook.react.shell.MainReactPackage;
import com.microsoft.codepush.react.CodePush;
import com.microsoft.codepush.react.ReactInstanceHolder;

public class MainActivity  extends ReactActivity implements DefaultHardwareBackBtnHandler {
    private ReactRootView mReactRootView;
    private ReactInstanceManager mReactInstanceManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            if (!Settings.canDrawOverlays(this)) {
                Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,
                        Uri.parse("package:" + getPackageName()));
                startActivityForResult(intent, 101);
            }
        }

        mReactRootView = new ReactRootView(this);

        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .addPackage(new CodePush("0C-Uc5S_URsMNVhwd2AuXp3vQNIH68fcaff9-73ca-4ffe-9efe-******", getApplicationContext(), BuildConfig.DEBUG))
                .setJSBundleFile(CodePush.getJSBundleFile())
                .setBundleAssetName("index.android.bundle")
                //.setJSMainModulePath("index")
                .addPackage(new MainReactPackage())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        mReactRootView.startReactApplication(mReactInstanceManager, "MyReactNativeApp", null);

        setContentView(mReactRootView);

        CodePush.setReactInstanceHolder(new ReactInstanceHolder() {
            @Override
            public ReactInstanceManager getReactInstanceManager() {
                return mReactInstanceManager;
            }
        });


    }


    @Override
    protected String getMainComponentName() {
        return "MyReactNativeApp";
    }


    @Override
    public void invokeDefaultOnBackPressed() {
        super.onBackPressed();
    }
    @Override
    protected void onPause() {
        super.onPause();

        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostPause(this);
        }
    }

    @Override
    protected void onResume() {
        super.onResume();

        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostResume(this, this);
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        if (mReactInstanceManager != null) {
            mReactInstanceManager.onHostDestroy(this);
        }
        if (mReactRootView != null) {
            mReactRootView.unmountReactApplication();
        }
    }
    @Override
    public void onBackPressed() {
        if (mReactInstanceManager != null) {
            mReactInstanceManager.onBackPressed();
        } else {
            super.onBackPressed();
        }
    }
    @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_MENU && mReactInstanceManager != null) {
            mReactInstanceManager.showDevOptionsDialog();
            return true;
        }
        return super.onKeyUp(keyCode, event);
    }

}

Application Class
import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.microsoft.codepush.react.CodePush;

import java.util.Arrays;
import java.util.List;

public class MainApp extends Application implements ReactApplication {

    @Override
    public void onCreate() {
        SoLoader.init(this,false);

        super.onCreate();
    }



    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }


        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new CodePush("0C-Uc5S_URsMNVhwd2AuXp3vQNIH68fcaff9-73ca-4ffe-9efe-********", MainApp.this, BuildConfig.DEBUG)
            );

        }
        @Override
        protected String getJSMainModuleName() {
            return "index";
        }

    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }


}

Index.js
import React from 'react';
import {AppRegistry, StyleSheet, Text, View} from 'react-native';
import codePush from "react-native-code-push";
class HelloWorld extends React.Component {
  
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.hello}>Hello, World from indiaaaa</Text>
      </View>
    );
  }
}

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  hello: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
});
let codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_START };



AppRegistry.registerComponent('MyReactNativeApp', () => codePush(codePushOptions)(HelloWorld));

**Comment by tarunkonda123** [comment]
hi

**Comment by leotm** [comment]
@tarunkonda123 Do you remember what was wrong with those paths in the end?

I too have `build.gradle`

```gradle
...
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
...
```

CodePush generally works great, but error reporting still logging few events

```bash
Error: /data/user/0/io.x.y/files/CodePush/download.zip (No such file or directory)
```

```bash
Error: /data/user/0/io.x.y/files/CodePush/download.zip: open failed: ENOENT (No such file or directory)
```

On Android 9 and Android 10 devices, but unsure why.

**Comment by cq0702** [comment]
@leotm  I met the same issue.Did you solve it?

**Comment by leotm** [comment]
@cq0702 Unfortunately not, still and unresolved :/

<img width="1061" alt="Screenshot 2020-04-28 at 10 32 57" src="https://user-images.githubusercontent.com/1881059/80471954-05688380-893c-11ea-8661-35d56c32646c.png">

**Comment by swetht** [comment]
still facing some instances of this, did anyone figure this out yet?

**Comment by feiyingx** [comment]
Same issue, has anyone found the solution

**Comment by plus24-library** [comment]
Same issue, has anyone found the solution ?

**Comment by songxiaoliang** [comment]
Same issue, has anyone found the solution ?
