### ISSUE TITLE
Can I use codePush in a non root component?

### ISSUE THREAD

**Issue by ay5000** [Microsoft/react-native-code-push#1267]
The documentation says to currently wrap the root component with codePush() but I want to force mandatory updates only on users who have been logged in, so would it be possible to wrap my "AuthedHomeScreen" component with codePush? (instead of App.js) ?

Thanks.

**Comment by Zakeelm** [comment]
Yes! You can use CodePush in a non root component, but you must also  use `notifyAppReady()` in the root component when doing so

**Comment by NickToropov** [comment]
Hi ay5000,
I’ll close this issue for now as there are no questions from you. But please feel free to reopen it if you will have any questions.

**Comment by psaikali** [comment]
Hi @Zakeelm,

Would you be kind enough to demonstrate how to do what you're saying?
I'm not sure if both root component and non-root component should be wrapped by `codePush()`, and how to implement this `notifyAppReady()` notification.

Thanks a lot for your help.

**Comment by psaikali** [comment]
Replying to myself, in case this could help someone:

```javascript
class App extends Component {
	componentDidMount() {
		codePush.notifyAppReady();
	}

	render() {
		...
	}
}

export default App;
```

And then use `codePush.sync()` and other API functions somewhere else!
