### ISSUE TITLE
demo can not run ,flshback

### ISSUE THREAD

**Issue by 841660202** [Microsoft/react-native-code-push#1270]
demo can not run ,flshback ,how to solve?
<img width="954" alt="wx20180503-221926 2x" src="https://user-images.githubusercontent.com/18305361/39582312-47430a44-4f20-11e8-82da-92f18543323d.png">
<img width="1322" alt="wx20180503-222037 2x" src="https://user-images.githubusercontent.com/18305361/39582317-48509488-4f20-11e8-9694-3d88e244c856.png">

**Comment by iTOYS** [comment]
Hi @841660202 
Could you please fill this issue by [template](https://github.com/Microsoft/react-native-code-push/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by alexandergoncharov** [comment]
Hi @841660202,

I'll close this issue for now as I haven't heard answer form you in while. Please feel free to reopen it if you will have any questions.

Thanks,
Alexander
