### ISSUE TITLE
how can i get deployment key for development?

### ISSUE THREAD

**Issue by ycman0307** [Microsoft/react-native-code-push#1278]
I cannot find the documents and procedure in App center and github.

**Comment by alexandergoncharov** [comment]
HI @ycman0307,

Thanks for reporting!
If I understand correctly you need deployment key for codePush?
If yes, for example, you can use this commands:

> appcenter codepush deployment add -a {UserName}/{ProjectNameInAppCenter} Staging
> appcenter codepush deployment list -a {UserName}/{ProjectNameInAppCenter}

Please for more information check documentation: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli

Please let me know if it was helpful or you still have any questions.

Thanks,
Aleander

**Comment by ycman0307** [comment]
Thank you for your reply. 

It is difficult for me to understand. Is there any tutorial for me to create codePush project step by step?

**Comment by alexandergoncharov** [comment]
I think that Microsoft docs have enough full steps for setup codePush for app.
You can start here: https://docs.microsoft.com/en-us/appcenter/distribution/codepush and go ahead with visiting internal links in steps.
Also you can use example project for setup: https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp

Good luck in studying and feel free to ask any questions!

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @ycman0307 ,

I'll close this issue for now as I did not hear any questions from you. But please feel free to reopen it if you will have any questions.

Thanks.
Alexander

**Comment by gtjamesa** [comment]
If anyone from Google stumbles upon this and has run the commands above, and the keys are not being displayed, you need to append `--displayKeys`

```bash
appcenter codepush deployment list -a {UserName}/{ProjectNameInAppCenter} --displayKeys
```

**Comment by prakas25** [comment]
code-push deployment list <app_name> -k

**Comment by felixus95** [comment]
Thank you @gtjamesa

**Comment by FilipIlievski** [comment]
Check the [docs](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#account-management) please.

To see on which apps you have access to `appcenter apps list`. You should see something like this  

> {UserName}/{ProjectNameInAppCenter}

Then, to display the app key based on the environment, execute `appcenter codepush deployment list -a About-You/About-You-Android --displayKeys`

**Comment by temitope** [comment]
worth noting that appending  _--displayKeys _ argument caused an error.  and I had to run it twice to get keys to show up. very odd.

**Comment by Hung-san** [comment]
@temitope 
Maybe my answer late, but if you need, 
Make sure appcenter is installed "sudo npm instal -g appcenter-cli"
code-push deployment add <appname> --d (--d: default will be generate Staging and Production)
