### ISSUE TITLE
Cannot build react native project after adding "react-native-code-push"

### ISSUE THREAD

**Issue by ycman0307** [Microsoft/react-native-code-push#1279]
I create a new project and then run two command
"yarn add react-native-code-push"
"react-native link react-native-code-push"

and then i run in android with "react-native run-android"

after that i run the program, i get the following error. 

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-code-push'.
      > Could not resolve all dependencies for configuration ':react-native-code-push:_debugPublishCopy'.
         > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
           Required by:
               testCodePush:react-native-code-push:unspecified > com.nimbusds:nimbus-jose-jwt:5.1
            > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
               > Failed to list versions for net.minidev:json-smart.
                  > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
                     > Could not GET 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
                        > jcenter.bintray.com

Anyone have solution for solving these error??

**Comment by NickToropov** [comment]
Hi @ycman0307, thanks for reporting the issue.

I tried your repro steps and finished without any error. Then I turned off my Internet and got the same error:

➜  Issue1279 react-native run-android
…
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-code-push'.
      > Could not resolve all dependencies for configuration ':react-native-code-push:_debugPublishCopy'.
         > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
           Required by:
               Issue1279:react-native-code-push:unspecified > com.nimbusds:nimbus-jose-jwt:5.1
            > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
               > Failed to list versions for net.minidev:json-smart.
                  > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
                     > Could not GET 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
                        > jcenter.bintray.com

 
Please, check your internet connection and try `react-native run-android` again.

Please, let me know if it was helpful or you still have any questions.

**Comment by ycman0307** [comment]
Thank you for your reply. 
I find that it should be internet connection. My proxy server seems that it don't allow codePush to have connection.

Here is the log in chrome.
[CodePush] Checking for update.
[CodePush] Reporting binary update (1.0)
[CodePush] Report status failed: {"appVersion":"1.0"}
[CodePush] An unknown error occurred.
[CodePush] Network request failed 

Can i set proxy config for using codePush in my company??

**Comment by NickToropov** [comment]
Hi @ycman0307,
react-native-code-push plugin should work without any configuration. Please check if you have access to the following addresses from your device:
https://codepush.azurewebsites.net
https://codepush.blob.core.windows.net
https://codepushupdates.azureedge.net

If not, please, try to configure proxy for your wifi connection and try to get access to the specified addresses again.
Let me know if it was helpful or there are any questions.

**Comment by NickToropov** [comment]
Hi @ycman0307, 

I'll close this issue for now. Please feel free to open it again if you have any questions.

**Comment by alisn72** [comment]
Hi
I'm trying to update my android application but i get this:

[06:20:26] Network request failed
[06:20:26] Report status failed: {"appVersion":"1.2"}
[06:20:26] Reporting binary update (1.2)
[06:20:26] Report status failed: {"appVersion":"1.2"}
[06:20:39] Loading JS bundle from "assets://index.android.bundle"
[06:20:40] Checking for update.
[06:20:40] Reporting binary update (1.2)
[06:20:42] Report status failed: {"appVersion":"1.2"}
[06:20:42] An unknown error occurred.
[06:20:42] Network request failed

i have correct access to https://codepush.azurewebsites.net , https://codepush.blob.core.windows.net and https://codepushupdates.azureedge.net . 
i used `code-push deployment ls MY-APP -k` and put Staging Deployment Key to my android buid.gradle file. 
also i used `code-push release-react MY-APP android --deploymentName Staging` to release app bundle.
here is my project configuration:

`"react-native": "^0.55.4",
  "react-native-code-push": "^5.5.2",
  "code-push-cli": "2.1.9",`

Any help will be appreciated.

**Comment by wkmcyz** [comment]
This problem is gone after I restarted my PC. I guess it is something about the cache of gradle. My device is MacBook Pro

**Comment by evolvingkid** [comment]
iam having the save issues

**Comment by mohity777** [comment]
Same Issue.

**Comment by seyedmostafahasani** [comment]
Add mavenCentral inside buildscript repositories and allprojects repositories is working for me.
![Screen Shot 2022-05-09 at 12 37 29 PM](https://user-images.githubusercontent.com/3009224/167367364-56a23d76-a7bf-43a1-91c4-68c5dc17587e.png)

**Comment by seyedmostafahasani** [comment]
> iam having the save issues
Add mavenCentral inside buildscript repositories and allprojects repositories is working for me.
![Screen Shot 2022-05-09 at 12 37 29 PM](https://user-images.githubusercontent.com/3009224/167367582-a0a860b0-6db8-47b2-9e63-f7417fd52706.png)

**Comment by seyedmostafahasani** [comment]
> Same Issue.
https://github.com/Microsoft/react-native-code-push/issues/1279#issuecomment-1120780710
