### ISSUE TITLE
WPF support - documentation not updated?

### ISSUE THREAD

**Issue by LolliDepp** [Microsoft/react-native-code-push#1281]
Hi,
I can see that the pull request https://github.com/Microsoft/react-native-code-push/pull/813 is referring to WPF applications in react-native, while in the documentation, supported platforms section, there is no mention of WPF. https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms 
Is WPF supported?

**Comment by Zakeelm** [comment]
WPF is supported. Thanks for pointing this out! Going to close this and update the documentation.
