### ISSUE TITLE
Android build fails - cannot find symbol (1.17.4-beta + RN 0.42.3)

### ISSUE THREAD

**Issue by ben-snaize** [Microsoft/react-native-code-push#1282]
Since a successful set of Android builds on 11th May, I am encountering the following Android build error. This affects two different Macs used for building so it doesn't seem to be an environment issue. No changes to package.json etc. have been made recently.

### Steps to Reproduce

See example demo below or from an existing project:

1. `npm i react-native-code-push@1.17.4-beta`
2. Link to Android project as per usual
3. `cd android && ./gradlew assembleRelease`

### Expected Behavior

Build compiles

### Actual Behavior

Build does not compile:

```
/Users/me/App/App/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java:22: error: cannot find symbol
import com.facebook.react.uimanager.ReactChoreographer;
                                   ^
  symbol:   class ReactChoreographer
  location: package com.facebook.react.uimanager
/Users/me/App/App/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java:295: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/me/App/App/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java:257: error: package ReactChoreographer does not exist
                                    ReactChoreographer.getInstance().postFrameCallback(ReactChoreographer.CallbackType.TIMERS_EVENTS, new Choreographer.FrameCallback() {
                                                                                                         ^
/Users/me/App/App/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java:257: error: cannot find symbol
                                    ReactChoreographer.getInstance().postFrameCallback(ReactChoreographer.CallbackType.TIMERS_EVENTS, new Choreographer.FrameCallback() {
                                    ^
  symbol: variable ReactChoreographer
4 errors

```
### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.42.3 react-native-code-push@1.17.4-beta` command to generate plain CodePushified React Native app. 

* `cd appName/android`
* `./gradlew assembleRelease`

### Environment

* react-native-code-push version: 1.17.4-beta
* react-native version: 0.42.3
* iOS/Android/Windows version: Android build
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Build issue

**Comment by Borovensky** [comment]
Started facing pretty the same issue today...Successfully build Android like a few days ago, since those time didn't do any changes to package.json. Also trying to build the app on another PC, but still review the same issue. 

<img width="1036" alt="screen shot 2018-05-16 at 1 54 35 pm" src="https://user-images.githubusercontent.com/16164749/40113322-c1cfb32a-5911-11e8-896f-f34bb3f38b37.png">

### Environment 
- react-native-code-push version: 3.0.1-beta
- react-native version: 0.45.1

If someone have any suggestion, please help.

**Comment by waltermvp** [comment]
Same here with RN version .44

**Comment by ajwhite** [comment]
This is due to https://github.com/facebook/react-native/issues/19259

**Comment by Borovensky** [comment]
Yeah, I also find the solution here: https://github.com/facebook/react-native/issues/19272

**Comment by ben-snaize** [comment]
Cheers @Borovensky @ajwhite. Sorted.

**Comment by ben-snaize** [comment]
Update: you don't even need the fix any more because of [this fix from JCenter](https://github.com/facebook/react-native/issues/13094#issuecomment-389568018)

**Comment by Borovensky** [comment]
@ben-snaize Thanks for update!
