### ISSUE TITLE
how does code-push decide there's an update?

### ISSUE THREAD

**Issue by fatfatson** [Microsoft/react-native-code-push#1288]
i'm using the staging->production promotion solution
i have only one build (final, no beta) and i hope to test as below:
1) release a `staging` update
2) normal user won't see it because the default update channel is `production`
3) developer(me) could open a test update UI by some magic click and get the latest update in 1)
4) after testing everything is ok, promote the update to `production`.
5) but now ,the app which has installed the latest update from `staging` still get a new update notification from `production` channel,  and if it install the later and restart, it will see the same one from `staging` channel, infinite looping...

why doesn't the app know that's the same update?

**Comment by alexandergoncharov** [comment]
Hi @fatfatson ,
Thanks for reporting!

About your 5 step: It shouldn't be as different deployments should have different `deploymentKey`.

CodePush doesn't decide from which deployment should get updates. CodePush just use key for current build type. You should set different keys for different build types of your app.
For more information please check docs: https://github.com/Microsoft/react-native-code-push#multi-deployment-testing

Please let me know if it was helpful or I understand your incorrect.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @fatfatson ,

I'll close this issue for now as I haven't heard from you in a while unfortunately. But please feel free to reopen it if you will have any questions.

Thanks,
Alexander
