### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeCodePush2.default.CheckFrequency')

### ISSUE THREAD

**Issue by borkess** [Microsoft/react-native-code-push#1291]
I installed code-push today and tried it with a new react-native project and it worked ok. But, when I tried to run an already existent react-native project, that doesn't use code-push, I got this:
```
undefined is not an object (evaluating '_reactNativeCodePush2.default.CheckFrequency')
<unknown>
    App.js:67:51
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:148:36
_require
    require.js:132:20
<unknown>
    index.js:2
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:141:45
_require
    require.js:132:20
global code
```

**Comment by alexandergoncharov** [comment]
Hi @borkess ,
Thanks for reporting!

Could you please provide more additional info:
* Versions of `react-native-code-push` and your `react-native`
* How do you use `codePush` in code
* Would be great if you will provide test project with steps what did you do which can help me reproduce your issue.

Also please double check that you did all steps as in docs for getting started: https://github.com/Microsoft/react-native-code-push#getting-started


Thanks,
Alexander

**Comment by borkess** [comment]
Hi @alexandergoncharov I think I accidentally installed some stuff on my non-CodePush app. I rolled back the changes in my `package.json` file, deleted `node_modules`, and ran `npm install`. Now it' working OK. Thank you for your time.

**Comment by alexandergoncharov** [comment]
Good news!

Thanks for keeping in touch. I'll close this issue for now as it was resolved but please feel free to reopen it if you will have any questions.

Thanks,
Alexander

**Comment by saurav-bhagat** [comment]
Hi @alexandergoncharov-zz 

I'm facing the same issue:
I have a monorepo setup and in the root package.json, i have all the packages:-

```
"react-native": "0.63.3",
"react-native-code-push": "^7.0.5",
 "appcenter": "^4.4.5",
```
 
 - root/packages/mobile/android/settings.gradle
 ```
include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../../../node_modules/react-native-code-push/android/app')
 
```
 - root/packages/mobile/android/app/build.gradle
` apply from: "../../../../node_modules/react-native-code-push/android/codepush.gradle"`

- root/packages/mobile/android/app/src/main/res/values
`<string moduleConfig="true" name="CodePushDeploymentKey"> "deployment key" </string>
` 
- MainApplication.java
```
import com.microsoft.codepush.react.CodePush;

        @Override
        protected String getJSBundleFile() {
            if (BuildConfig.DEBUG) {
              return super.getJSBundleFile();
            } else {
              return CodePush.getJSBundleFile();
            }
        }
```

In my App.tsx file:

```
import CodePush from 'react-native-code-push';

const CODE_PUSH_OPTIONS = {
  checkFrequency: CodePush.CheckFrequency.ON_APP_START
};

export default CodePush(CODE_PUSH_OPTIONS)(App);
```

Could you please check if there is any issue or anything missing here?
Let me know if you need more details/

Thanks
