### ISSUE TITLE
Why my App only Update in Wifi

### ISSUE THREAD

**Issue by duckscorpion13** [Microsoft/react-native-code-push#1292]
I find device close Wifi

codepush is not woking and App will crash

please tell me how to fix?

### Environment

* react-native-code-push version:
* react-native version:0.54.0
* iOS/Android/Windows version: ios  11.3
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? physical

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @duckscorpion13 ,
Thanks for reporting.

Do you mean that you app can't be updated using 3G/3G network?
If yes please provide more additional info:
* Logs
* How do you use CodePush in your code
* Your `react-native-code-push` version
* Would be great if you will provide test project with detailed steps which can help me reproduce issue
Also, please double check that you have good 3G/4G connection.

Thanks,
Alexander

**Comment by duckscorpion13** [comment]
![2018-05-24 4 06 58](https://user-images.githubusercontent.com/20702440/40473761-aa1068d8-5f6f-11e8-9434-ec6251e25d36.png)

thx
I reset Exception Domains 
then it's workng

**Comment by alexandergoncharov** [comment]
@duckscorpion13  Good news =)

So, I'll close this issue for now as it was resolved. But please feel free to reopen it if you will have any questions.
