### ISSUE TITLE
Could not find any version that matches com.facebook.react:react-native:0.18.+.Versions that do not match:0.20.10.19.10.17.10.16.00.15.0+ 5 moreRequired by:test:ReactNativeAutoUpdater:unspecified

### ISSUE THREAD

**Issue by sangdesigner** [Microsoft/react-native-code-push#1293]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @sangdesigner ,
Could you please fill issue template?
https://github.com/Microsoft/react-native-code-push/blob/master/.github/ISSUE_TEMPLATE.md

Thanks,
Alexander

**Comment by sangdesigner** [comment]
issue fixed

**Comment by sangdesigner** [comment]
now i am facing update invalid metadata aborting

**Comment by alexandergoncharov** [comment]
Hi @sangdesigner,

Unfortunately, it is difficult to help with without your provided additional info as in issue template.
Could you please fill it and provide to us as much additional info as possible? Any logs, code example, repro steps would really help to understand your issue. 

Thanks,
Alexander

**Comment by sangdesigner** [comment]
Hi I have fix this issue

Now invalid update meta data aborting error comes

**Comment by alexandergoncharov** [comment]
@sangdesigner , if I understand you correctly you have issue with updating metadata at now?

**Comment by sangdesigner** [comment]
Yes

**Comment by sangdesigner** [comment]
im using reactnative auto updater plugin

**Comment by alexandergoncharov** [comment]
Could you please provide details about it? Unfortunately I can't help you without details.
You can do it here or you can open new issue as it is separate issue.

**Comment by sangdesigner** [comment]
Environment:
  OS: Windows 7
  Node: 8.11.1
  Yarn: Not Found
  npm: 3.10.9
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by sangdesigner** [comment]
Using Reactnative auto updater 0.2.5 version

When i running the app its checking update after invalid update meta data Aborting messages show

**Comment by alexandergoncharov** [comment]
I noted that you are using react-native-auto-updater. It is alternative project. So if you are just using react-native-auto-updater I think you should to ask your question in their repo: https://github.com/redbooth/react-native-auto-updater

Thanks,
Alexander

**Comment by sangdesigner** [comment]
yes i refer this but i know how to fix the issue

**Comment by sangdesigner** [comment]
im posting the issue there also but no reply

**Comment by alexandergoncharov** [comment]
Got it. So, if you don't have any issue with CodePush I'll close this issue for now. But please feel free to reopen it if you will have any question.

Thanks,
Alexander

**Comment by sangdesigner** [comment]
Hi Alexander

I need some help to fix this following issue
 invalid update meta data Aborting messages show
in reactnative auto updater

**Comment by alexandergoncharov** [comment]
Hi @sangdesigner ,

Unfortunately I didn't work with react-native-auto-updater and I don't know what is reason of issue =(
I think that the best place where someone can help you is  react-native-auto-updater repo: https://github.com/redbooth/react-native-auto-updater.

Thanks,
Alexander
