### ISSUE TITLE
E/ReactNativeJS: undefined is not an object (evaluating 'n.props.url.indexOf')

### ISSUE THREAD

**Issue by jiaoxuebing2014** [Microsoft/react-native-code-push#1294]
installMode: codePush.InstallMode.IMMEDIATE

Once the update is completed, it will crash immediately after starting and then manually update the application again.

<img width="1037" alt="wx20180525-170248 2x" src="https://user-images.githubusercontent.com/8436801/40536051-7b38d620-603d-11e8-9d38-2a3dcc92b4c0.png">

**Comment by NickToropov** [comment]
Hi @jiaoxuebing2014, the most likely reason is that your `n.props.url` object is undefined. So please, check if `n.props.url` is initialized with some value. 

Please, let me know of it was helpful or there are any other questions.

**Comment by jiaoxuebing2014** [comment]
@NickToropov Thank you very much. I solved the problem according to your prompt.

**Comment by NickToropov** [comment]
@jiaoxuebing2014, Good news =)

So, I'll close this issue for now as it was resolved. But please feel free to reopen it if you will have any questions.

**Comment by ssnanda** [comment]
Hello I am new to nocodb, can somebody please point me to instruction on how to setup  n.props.url ?
