### ISSUE TITLE
The update contents failed the data integrity check

### ISSUE THREAD

**Issue by yulianger** [Microsoft/react-native-code-push#1296]
First time the app can work.But after that,I ran into an error:The update contents failed the data integrity check.
react native version: 0.44
code push viersion:5.2.2。
Anyone knows how can I fix it?

**Comment by alexandergoncharov** [comment]
Hi @yulianger ,
Thanks for reporting!

This issue arises if verifying hash folder is failed.
Could you please provide as more additional info as possible using template: https://github.com/Microsoft/react-native-code-push/blob/master/.github/ISSUE_TEMPLATE.md ?

Also, Are you using codeSign for updates? (more info: https://github.com/Microsoft/code-push/tree/master/cli#code-signing) and It would be great if you will provide test project with reproducing issue with detailed repro-steps.

Thanks,
Alexander

**Comment by yulianger** [comment]
@alexandergoncharov thanks for your reply.
react-native-code-push version:5.2.2
react-native version:0.44
iOS/Android/Windows version: ios
debug build and release build, simulator andphysical device both have this problem...

I try to use react-native bundle and code-push release  command,I can see that If I have assets folder,it will have this problem.
without assets folder the project works well...

**Comment by zhaoziliang** [comment]
I also encountered this problem. I have compiled it with a Mac computer. So there is a .DS_Store file in the folder. After I delete this file and publish it using codepush, the problem is not there. I can try it.

**Comment by yulianger** [comment]
@zhaoziliang I have delete .DS_Store files,still can not work....

**Comment by alexandergoncharov** [comment]
Hi @zhaoziliang and @yulianger ,

I'm working on your issue. Could you please also share command for for releasing updates, using sign updates or not?
And other details would be helpful. Please provide as much as possible.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
@zhaoziliang , @yulianger also, could you please provide your release history?
You can use `code-push deployment history <appName> <deploymentName>` command for this.

Thanks,
Alexander

**Comment by zhaoziliang** [comment]
@alexandergoncharov 

./code-push release b-android ../android_js/ 1.0.2    --deploymentName Production

./code-push release b-ios ../ios_js/ 1.0.2    --deploymentName Production

**Comment by zhaoziliang** [comment]
@yulianger 
Integrity checking means that the summary calculated by the update package on the server is not the same as the one calculated by the client, so I suspect it is caused by a similar hidden file. You can find the reason from this aspect. Please forgive my bad English

**Comment by zhaoziliang** [comment]
@yulianger 
Integrity checking means that the summary calculated by the update package on the server is not the same as the one calculated by the client, so I suspect it is caused by a similar hidden file. You can find the reason from this aspect.

**Comment by yulianger** [comment]
@zhaoziliang You have solved this problem by finding hidden files?

**Comment by zhaoziliang** [comment]
@yulianger 
Yes, when I deleted the.DS_Store file, I solved the problem, but it was not guaranteed that all the mistakes were due to the file, and it could be caused by other reasons.

**Comment by yulianger** [comment]
@alexandergoncharov First time the app can updated from codepush, from second time, code push cannot update..
I try to use code-push release-react  and  code-push release  commands, still not worked..  The same code and images assets under android version can work, just IOS Version cannot work

**Comment by alexandergoncharov** [comment]
@yulianger Could you please provide test project with detailed steps which can help me reproduce your issue? 
I can't reproduce it unfortunately.

Also, have you tried to use `appenter` cli for releasing? Docs: https://github.com/Microsoft/appcenter-cli (for example: `appcenter codepush release-react -a <your-name>/<ProjectNameInAppCenter> -d Staging`).
There was similar issue from user who fixed it using appCenter cli.

Please let me know if it was helpful or not.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @yulianger and @zhaoziliang ,

Are you still facing this issue?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi all,

I'm going to close this issue for now as I haven't heard from you in a while and I can't reproduce it.
Please feel free to reopen it if you'll have any questions or you'll provide test project with reproducing issue.

Thanks,
Alexander

**Comment by yqz0203** [comment]
@yulianger 

Have you resolved it?

**Comment by yqz0203** [comment]
@yulianger 

I change the source folder name from `../ios_js` to `../ios_js/`, update works fine.

Hope can help.

**Comment by AndriyZahura** [comment]
In case someone is still having the same issue:

I had it on android after messing with gradle/modules/caches etc.

The flow was the following:
Install the binary;
Get ANY update;
Try to get another update;
The `The update contents failed the data integrity check` error in logcat appears.

What helped me is simply adding this before my sync:

`    if (Platform.OS === 'android') {
      CodePush.clearUpdates();
    }
`

Before that, I checked if there is an available update. So whole code looks like this

`
updateApp = () => {
    this.props.setCodePushUpdateAvailable(false);
    if (this.props.codePushUpdateInstalled) {
      CodePush.restartApp();
      return;
    }

    //Need to clear previous cache because android may rollback.
    //TODO: Test if we need this on the next binary release
    if (Platform.OS === 'android') {
      CodePush.clearUpdates();
    }
    const installMode = CodePush.InstallMode.IMMEDIATE;
    CodePush.sync(
      {
        installMode,
      },
      this.codePushStatusDidChange.bind(this),
      this.codePushDownloadDidProgress.bind(this),
    );
  };
`
updateApp is called manually by user
