### ISSUE TITLE
React native code push supported on WPF platform but lack of support documentation.

### ISSUE THREAD

**Issue by piyush965** [microsoft/react-native-code-push#1304]
React native code push supported on WPF platform but due to lack of documentation I had to spent lot of time to figure out how to setup Codepush on RN WPF application.

It would be helpful for the community if ReadMe document is added for how to add Codepush support on RN WPF (.NET46) application. 

### Environment

* react-native-code-push version: NA
* react-native version: NA
* iOS/Android/Windows version: WPF
* Does this reproduce on a debug build or release build? NA
* Does this reproduce on a simulator, or only on a physical device? NA

(The more info the faster we will be able to address it!)

**Comment by piyush965** [comment]
@matthargett - Codepush integration on WPF app also require a UWP project solution which can be generated using react-native windows cmd. This info must be documented because in our case we only targeted to .NET46 and UWP project was not added to solution and had to spent lot of time to find such info.

**Comment by alexandergoncharov** [comment]
Hi @piyush965 ,
Thanks for reporting!

Could you please clarify did you get a chance to check this doc for windows setup: https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-windows.md ?
Please let me know If it isn't full for you or you have any question.

Thanks,
Alexander

**Comment by piyush965** [comment]
@alexandergoncharov  Yes I went through this document. But it no where says what are the steps to setup code push support on RN WPF application. I had to read - https://github.com/Microsoft/react-native-code-push/pull/684 to follow some setup steps also along with that it requires UWP project as mentioned in my previous comment, this information is missing. 

If you could update document to refer all these steps would be helpful for everyone.

**Comment by alexandergoncharov** [comment]
Hi @piyush965 ,

Got it. Good catch. I'll investigate it and update doc a little bit later. Sorry for this long delay.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @piyush965 ,
Sorry for long delay.

Could you please clarify how exactly did you create your RN WPF application without UWP?


Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @piyush965 

I found the way to create wpf project without uwp and tested this case.
Created PR for updating doc: https://github.com/Microsoft/react-native-code-push/pull/1322

Thanks for suggestion about improving docs!

Thanks,
Alexander

**Comment by piyush965** [comment]
@alexandergoncharov  Thanks for the update.

**Comment by alexandergoncharov** [comment]
Hi @piyush965 ,

Sorry for long delay.  I'll investigate it and create doc for setup WPF a little bit later. 

Thanks,
Alexander
