### ISSUE TITLE
While running Jest tests CodePush module setup warning appears

### ISSUE THREAD

**Issue by carloscuesta** [Microsoft/react-native-code-push#1306]
Hey! Since some weeks ago when I run my tests with Jest, I've got some warnings regarding to the setup of CodePush.

https://github.com/Microsoft/react-native-code-push/blob/14c2530a5f41d3831cd99a777a935ad773f72ea7/CodePush.js#L590

### Steps to Reproduce

1.  Run the tests with Jest.

### Expected Behavior

To not get logging related with the setup of CodePush when running tests. CodePush works fine on our application.

### Actual Behavior

> console.log node_modules/react-native-code-push/logging.js:3
[CodePush] The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.

<img width="1202" alt="screen shot 2018-06-05 at 12 20 37" src="https://user-images.githubusercontent.com/7629661/40970458-f6852998-68ba-11e8-92b5-5ad3c40df625.png">

### Environment

* react-native-code-push version: **5.2.2**
* react-native version: **0.49.5**

### Solution

This could be solved by mocking the `NativeCodePush` variable.

```js
jest.mock('react-native-code-push', () => ({
  NativeCodePush: {},
}))
```

**Comment by NickToropov** [comment]
Hi @carloscuesta, thanks for posting the issue! I think I've fixed it a few days ago. Please look at the  [commit](https://github.com/Microsoft/react-native-code-push/commit/9662c85ba6ff1bec251bf9ea9bcff9ac3954f9c1).

Please, let me know if it was helpful or you have any other question.

**Comment by NickToropov** [comment]
I'll close the issue. Please reach us if you have more questions.
