### ISSUE TITLE
Question RE: diffing, downloads

### ISSUE THREAD

**Issue by tomauty** [Microsoft/react-native-code-push#1307]
Hi, this is mostly a question so no reproduction steps or anything like that. 

Background: We have a production app and use CodePush primarily for hotfixes. However, because we have to bundle it with assets, the downloads take quite some time to apply if they're mandatory. Marking them optional is not always a good answer, in case there is something that affects users early on in the application lifecycle.

I noticed that _subsequent_ CodePush releases to the same client will download very quickly in comparison. I'm assuming there is some fancy diffing at work on the server-side. Would it be possible to upload a disabled update package when we release the binary, such that if we have to patch that binary later, the new CP package will be diffed against the original, disabled one? That is, make our download speeds very fast for mandatory updates?

Hope this makes sense, thanks!

**Comment by alexandergoncharov** [comment]
Hi @tomauty ,
Thanks for reporting!

Could you please clarify one moment:
>  downloads take quite some time

How long for about?  And in comparison with others?

I'm not sure that there should be big difference in downloading but I'll investigate it on server side a little bit later.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @tomauty ,

I'll close this issue for now as I haven't heard from you in a while. Also I tested it and didn't found any big differences in time.
Please feel free to reopen it if you'll have any questions.

Thanks,
Alexander
