### ISSUE TITLE
Environment variables to build the app from AppCenter

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/react-native-code-push#1311]
Hello guys,
Exist any option to build the app from **AppCenter** with the correct deployment key depending of the current branch? for example build the app for **Staging** if the branch is `develop` or build the app for **Production** if the branch is `master`

Thanks in advance and sorry for the question, I can't see any easy way using environment variables or something like that from the build configuration of **AppCenter** to do that
Best regards, Nicholls

**Comment by NickToropov** [comment]
Hi @jdnichollsc, I think you can specify custom [Environment variable](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/) with correct deployment key for every branch and then use [appcenter-pre-build.sh](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#pre-build) to write it inside Android or iOS application.

**Comment by jdnichollsc** [comment]
@NickToropov thanks for the response! I already made the following configuration https://github.com/Microsoft/react-native-code-push#multi-deployment-testing
But do you have any example to change the deployment name using `appcenter-pre-build.sh`? I want to use a new deployment called `Develop` instead of `Staging` for the development build

**Comment by jdnichollsc** [comment]
@NickToropov How can I change the build configuration to use **Debug** for my `develop` branch?
Example:
```
ios-setBuildConfiguration { buildConfiguration: 'Debug' }
```

Thanks in advance, Nicholls

**Comment by NickToropov** [comment]
Hi @jdnichollsc 
> How can I change the build configuration to use Debug for my develop branch?

As I understood you correctly you just need to create a new shared build scheme **Debug**:
<img width="870" alt="screen shot 2018-06-08 at 12 35 42 pm" src="https://user-images.githubusercontent.com/31315772/41151214-c794c336-6b18-11e8-851a-f946f83d87a1.png">
and push changes to your `develop` branch

Then go to appcenter.m, select your `develop` branch and select `Debug` scheme in `Shared Scheme` section:
![screen shot 2018-06-08 at 12 44 12 pm](https://user-images.githubusercontent.com/31315772/41151821-8ff8b804-6b1a-11e8-8cef-ef5fe3d7f337.png)

Now you'll build your `develop` branch using **Debug** configuration.

**Comment by NickToropov** [comment]
> But do you have any example to change the deployment name using `appcenter-pre-build.sh`? I want to use a new deployment called `Develop` instead of `Staging` for the development build.

please, clarify if `Develop` deployment belongs to CodePush? If so then you need just to pass it to appcenter cli:
`appcenter codepush release-react -a <user-name>/<app-name> -d **Develop**`
_Note, that you should update deployment key in your application before and release new version with updated keys._

`appcenter-pre-build.sh` is executed only during appcenter build process.

**Comment by jdnichollsc** [comment]
Ohh thanks @NickToropov, the example of the scheme is very important, we need that step from the documentation of Multi-Deployment Testing 👍

**Comment by NickToropov** [comment]
@jdnichollsc glad to hear that I could help you! :)

**Comment by MikePodgorniy** [comment]
Hello there! 

I want to change "Shared Scheme" in my app in appcenter.ms
But appcenter show me schemes MCourses & MCourses-tvOS
and I don't have any scheme from my workspace or project in the list on appcenter "Build configuration"

How to update this f#$X@ list?
I tried to create new brunch, build project but list still including only 2 items:  MCourses & MCourses-tvOS

@jdnichollsc  could you know how it works?

**Comment by jdnichollsc** [comment]
@MikePodgorniy you need to create the schema from Xcode, publish the changes to the branch and later update the configuration of that branch from appcenter to use that schema :)

**Comment by MikePodgorniy** [comment]
@jdnichollsc  you are right, it's easy :D
problem was in my "gitlab to bitbucket" solution
thanks

**Comment by jdnichollsc** [comment]
@NickToropov sorry, what's the configuration for Staging? I can see the following issue from AppCenter:
`2018-08-24T00:19:09.6933720Z ld: library not found for -lPods-MyApp`

**Comment by filiphosko** [comment]
@jdnichollsc You can try looking at this https://github.com/Microsoft/react-native-code-push/issues/426

**Comment by jdnichollsc** [comment]
thanks @filiphosko. I fixed my issues using this configuration: https://medium.com/@royprashenjeet25/solution-of-appcenter-codepush-multi-deployment-issue-ios-which-i-have-faced-c149813f84dd

**Comment by karm435** [comment]
Is there any way to have a shared variable among different configurations?

**Comment by github4es** [comment]
Is there any existing documentation for `Multi-Deployments` - we got an app that we want to build once and push to a Dev and QA environment each environment with its own set of "testers" (e.g. Collaborators).

**Comment by shubhambajoria1993** [comment]
I have react native config library setup with dev, qa, staging and production within the react native. How can i integrate this with app center build?

> Hi @jdnichollsc, I think you can achieve it by specifying custom [Environment variable](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/) with correct deployment key for every branch and then use [appcenter-pre-build.sh](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#pre-build) to write it inside Android or iOS application.
> 
> Please, let me know if is was helpful for you situation.
