### ISSUE TITLE
Not found a file in path Writing bundle output to: C:\Users\<myUser>\AppData\Local\Temp\CodePush\CodePush\index.android.bundle and can't update newest code

### ISSUE THREAD

**Issue by zxccvvv** [Microsoft/react-native-code-push#1312]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

No file in directory when using `code-push release-react <MyApp> android` and can't update newest `Javascript` code in `staging` Apps

I have a file in './index.js :
```
import { AppRegistry } from 'react-native';
import App from './src/App';

AppRegistry.registerComponent('iCare', () => App);
```

and in `./src/App.js` I add the push code like this :
```
import React, { Component } from 'react';
import { Check } from './router/router';
import codePush from "react-native-code-push";

class App extends Component {
  render() {
    console.disableYellowBox = true;
    return <Check />;
  }
}

const codePushOptions = { 
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME, 
  installMode: codePush.InstallMode.ON_NEXT_RESUME 
}

export default codePush(codePushOptions)(App);
```

### Steps to Reproduce
1. run command `code-push release-react <MyApp> android`
2. the log showing this output:
```Running "react-native bundle" command:

node node_modules\react-native\local-cli\cli.js bundle --assets-dest C:\Users\<myUser>\AppData\Local\Temp\CodePush\CodePush --bundle-output C:\Users\<myUser>\AppData\Local\Temp\CodePush\CodePush\index.android.bundle --dev false --entry-file index.js --platform android
Scanning folders for symlinks in D:\Project\ST.Corolus\List template App\<MyApp>\node_modules (30ms)
Scanning folders for symlinks in D:\Project\ST.Corolus\List template App\<MyApp>\node_modules (87ms)
Loading dependency graph, done.

bundle: start
bundle: finish
bundle: Writing bundle output to: C:\Users\<myUser>\AppData\Local\Temp\CodePush\CodePush\index.android.bundle
bundle: Done writing bundle output
bundle: Copying 13 asset files
bundle: Done copying assets

Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
Successfully released an update containing the "C:\Users\<myUser>\AppData\Local\Temp\CodePush\CodePush" directory to the "Staging" deployment of the "<MyApp>" app.
```
3.  check the `C:\Users\<MyUser>\AppData\Local\Temp\CodePush\CodePush\index.android.bundle` but there's no file and my path stop at  `C:\Users\<MyUser>\AppData\Local\Temp\CodePush`

### Expected Behavior
What you expected to happen?

To update a simple `Code` of my releaseStaging Apps

### Actual Behavior
What actually happens?

when I running `code-push debug android`,
the log showing me :
```
Listening for android debug logs (Press CTRL+C to exit)
[02:42:20] Sync already in progress.
[02:42:20] Sync already in progress.
[02:42:20] Exception
[02:42:20] Update is invalid - A JS bundle file named "null" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.
[02:42:20] Sync already in progress.
[02:42:20] Sync already in progress.
[02:42:20] Sync already in progress.
[02:42:20] An update is available, but it is being ignored due to having been previously rolled back.
[02:42:20] Sync already in progress.
```

```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: *__"react-native-code-push": "^5.3.4",__*
* react-native version: *__"react-native": "^0.53.0",__*
* iOS/Android/Windows version: *__Android [Emulator Nox]__*
* Does this reproduce on a debug build or release build? *__On releaseStaging__*
* Does this reproduce on a simulator, or only on a physical device? *__Both of them__*

(The more info the faster we will be able to address it!)

**Comment by zxccvvv** [comment]
Thanks for the response Nick,

Actually, I'm missed some word on docs, I'm just looking out some "Sub header" and find some code without read the information before,
because I'm too lazy to read all "normal" words at [Plugin Configuration](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#plugin-configuration-android) so I'm looking for the code and seeking there's 3 method to edit some code at *__MainApplication__*

Also I'm not aware if the folder already cleaned after uploading bundle to the server, because the log itself doesn't give an information if the file is deleted after that,

I'm sorry for this useless issues,

**Comment by NickToropov** [comment]
@zxccvvv thanks for reply! I'm glad to hear that the issue is finally resolved.
