### ISSUE TITLE
Cannot sync on android

### ISSUE THREAD

**Issue by jeffreymendez1993** [Microsoft/react-native-code-push#1314]
Cant fetch or sync on android.  I can get analytics from the users connect but for some reason I cant check for updates. Follow the install documentation and I am on the latest version of react-native and this repo. 
[
<img width="813" alt="screen shot 2018-06-08 at 5 06 52 pm" src="https://user-images.githubusercontent.com/8095978/41181056-738262c8-6b3e-11e8-9cdb-b9af8fea8943.png">
](url)

**Comment by jeffreymendez1993** [comment]
This error does nothing for me and is a pain to try to figure out.

**Comment by jeffreymendez1993** [comment]
wrong api key closing .

**Comment by half-ogre** [comment]
@jeffreymendez1993 I'm sorry the error message wasn't better, but glad to see you worked it out.

@keerthanakumar It would be nice for us to look at improving the error we show when the deployment key isn't valid.

**Comment by jeffreymendez1993** [comment]
Yeah I couldn’t figure it out and spent 4 hours or so on it. Figured that I was doing something stupid simple since I couldn’t debug it.
