### ISSUE TITLE
Why when fresh install and open the app, CodePush notify to update?

### ISSUE THREAD

**Issue by zxccvvv** [Microsoft/react-native-code-push#1315]
### Steps to Reproduce
1. Install Fresh App
2.  First time open the app
3. Notify to update

why the code push tell user to update the bundle when first time installing and opened the app or when user `Clear Data` the app? does it mean the bundle not yet installed on fresh APK?

if so, how to handle the codePush to not force update the bundle while opening installed app, and wait to update if installed bundle version < codePush bundle version?

### Environment

* react-native-code-push version: *__"^5.3.4",__*
* react-native version: *__"^0.53.0",__*
* iOS/Android/Windows version: *__Nougat__*
* Does this reproduce on a debug build or release build? *__Both__*
* Does this reproduce on a simulator, or only on a physical device? *__Both__*

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @zxccvvv,
Thanks for reporting.

Your request is in queue and we will investigate it a little bit later. Sorry for this delay.

Thanks,
Alexander

**Comment by zxccvvv** [comment]
Hi alexandet,
Thanks for the response,

I'll wait some good news later

**Comment by zxccvvv** [comment]
Hi @alexandergoncharov

I close this issue because of duplicated issue https://github.com/Microsoft/react-native-code-push/issues/112

Thanks for the response,

My issue appears because i've used same version of the app (because of this apps still on development, that i think i dont need to use different version for internal testing)
