### ISSUE TITLE
Error: Cannot find module 'pseudomap'

### ISSUE THREAD

**Issue by Symous** [Microsoft/react-native-code-push#1318]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. execute code-push command
2. such as code-push app list

### Expected Behavior
execute command and print result

### Actual Behavior
```
module.js:487
    throw err;
    ^

Error: Cannot find module 'pseudomap'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/code-push-cli/node_modules/lru-cache/index.js:7:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

### Environment

* react-native-code-push version:3.0.1-beta
* react-native version:0.45.1
* OS: macOS 10.13.4

**Comment by NickToropov** [comment]
Hi @Symous, the most likely reason of the issue is that `code-push-cli` isn't properly installed. Please try to reinstall it and try to execute `code-push app list` again.

**Comment by Symous** [comment]
Hi @NickToropov, I have try to re-install the code-push-cli. but still the same error.
code-push  version: 2.1.8
npm  version: 6.0.1
node version: 8.1.2

**Comment by NickToropov** [comment]
@Symous, please try the following:
```
cd /usr/local/lib/node_modules/code-push-cli
rm -rf node_modules
yarn (or npm intall)
code-push app ls
```
After executing `yarn` or `npm install` there should be `pseudomap` module installed in `./node_modules` folder.

**Comment by Symous** [comment]
@NickToropov Hi, friend, I solved it by reinstall it just now:
```
npm uninstall -g code-push-cli
npm install -g code-push-cli
```

**Comment by Symous** [comment]
And before that reinstall it I also have try to install pesudomap and yallist globally:
```
npm install -g pesudemap 
npm install -g yallist
```
that's works too.

**Comment by NickToropov** [comment]
Hi @Symous, glad to hear the problem was solved!
