### ISSUE TITLE
Android code push encountering java.lang.NullPointerException 

### ISSUE THREAD

**Issue by brzonsea** [Microsoft/react-native-code-push#1320]
My React Native project runs both iOS and Android. Recently I added Code Push to my project, which seems to work well with iOS but crashes with Android on every launch ever since I've integrated in.
The error occurs after CodePush logs the following lines.

`[CodePush] Checking for update.`
`[CodePush] Reporting binary update (1.0.1)`

Then, in debug mode, the app shows the following error.
`java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.facebook.react.bridge.ReadableMap.getString(java.lang.String)' on a null object reference`

### Steps to Reproduce
I tried reproducing this problem in a demo project, but failed. 
I checked and rechecked the setup steps for code push on Android. Could this be a dependency issue? Because my original project uses quite a lot of third party packages, but the demo I tried to reproduce didn't have any.

### Expected Behavior
Expect app to run without crashing.

### Actual Behavior
App crashes on launch, with following logs.

Below is the logcat for the debug run: 
`06-18 01:45:00.044 15502 15769 I ReactNativeJS: [CodePush] Checking for update.
06-18 01:45:00.052 15502 15769 I ReactNativeJS: [CodePush] Reporting binary update (1.0.1)
06-18 01:45:00.308 15502 15770 E unknown:ReactNative: Exception in native call
06-18 01:45:00.308 15502 15770 E unknown:ReactNative: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.facebook.react.bridge.ReadableMap.getString(java.lang.String)' on a null object reference`

Below is the logcat for the release mode run: 
`06-18 01:41:57.604 14809 14847 I ReactNativeJS: [CodePush] Checking for update.
06-18 01:41:57.607 14809 14847 I ReactNativeJS: [CodePush] Reporting binary update (1.0.1)
06-18 01:41:57.622 14809 14883 E linker  : readlink('/proc/self/fd/73') failed: Permission denied [fd=73]
06-18 01:41:57.622 14809 14883 E linker  : warning: unable to get realpath for the library "/data/app/com.classumreactnativeapp.android-1/lib/arm/libimagepipeline.so". Will use given name.
06-18 01:41:57.681   378  1854 D BandwidthController: [LG DATA] No such appUid: 10185
06-18 01:41:57.681   378  1854 D DnsProxyListener: App 10185 tries DNS query. Accept family:0 protocol:0
06-18 01:41:57.984 19868 19894 D Timer-0 : NetStateManager.java   225  ++ NetStateManager.isEnableWifi()
06-18 01:41:57.986 19868 19894 I Timer-0 : NetStateManager.java   238  >> strSSID = "Welcome_KAIST"
06-18 01:41:57.987 19868 19894 I Timer-0 : NetStateManager.java   239  >> nWifiState = 3
06-18 01:41:57.988 19868 19894 I Timer-0 : NetStateManager.java   240  >> WifiManager.WIFI_STATE_ENABLED = 3
06-18 01:41:57.988 19868 19894 D Timer-0 : NetStateManager.java   244  -- NetStateManager.isEnableWifi(true)
06-18 01:41:58.280  2410  3434 V WifiServerServiceExt: checkPollTimer Cnt= 0 rssi =-42 threshold=-85
06-18 01:41:58.396 14809 14848 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
06-18 01:41:58.396 14809 14848 E AndroidRuntime: Process: com.classumreactnativeapp.android, PID: 14809
06-18 01:41:58.396 14809 14848 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.facebook.react.bridge.ReadableMap.getString(java.lang.String)' on a null object reference
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at com.facebook.react.modules.blob.FileReaderModule.readAsText(FileReaderModule.java:45)
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
06-18 01:41:58.396 14809 14848 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
06-18 01:41:58.398  2410  4147 W ActivityManager:   Force finishing activity com.classumreactnativeapp.android/.MainActivity
`

### Reproducible Demo
I could not reproduce this on a demo project.

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.54.4 => 0.54.4

  react-native-code-push version: 5.3.4
  Android version: 6.0

* Does this reproduce on a debug build or release build? : Happens on both debug and release build
* Does this reproduce on a simulator, or only on a physical device? : I've only tested on physical devices. Happens on physical device.

My package.json : 
`{
  "name": "ClassumReactNativeApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@expo/react-native-action-sheet": "^1.0.2",
    "appcenter": "^1.5.1",
    "appcenter-analytics": "^1.5.1",
    "appcenter-crashes": "^1.5.1",
    "axios": "^0.17.1",
    "bulma": "^0.6.2",
    "emoji-utils": "^1.0.1",
    "firebase": "^4.9.0",
    "javascript-time-ago": "^1.0.26",
    "moment": "^2.20.1",
    "npm": "^5.10.0",
    "react": "16.3.1",
    "react-native": "0.54.4",
    "react-native-action-button": "^2.8.3",
    "react-native-android-keyboard-adjust": "^1.1.1",
    "react-native-code-push": "^5.3.4",
    "react-native-device-info": "0.18.0",
    "react-native-elements": "^0.19.1",
    "react-native-facebook-login": "https://github.com/magus/react-native-facebook-login.git#master",
    "react-native-fcm": "14.1.2",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-firebase": "^3.3.1",
    "react-native-firebase-auth": "^1.0.1",
    "react-native-gifted-chat": "https://github.com/brzonsea/react-native-gifted-chat.git#invertMessagesFix",
    "react-native-i18n": "^2.0.10",
    "react-native-icon-badge": "^1.1.3",
    "react-native-image-crop-picker": "^0.19.1",
    "react-native-image-gallery": "^2.1.5",
    "react-native-image-picker": "^0.26.7",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-modal": "^6.0.0",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-router-flux": "^4.0.0-beta.28",
    "react-native-splash-screen": "^3.0.6",
    "react-native-tab-view": "^0.0.74",
    "react-native-vector-icons": "^4.5.0",
    "react-native-version-number": "^0.3.3",
    "react-navigation": "1.5.11",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.5.0",
    "redux-thunk": "^2.2.0",
    "string-format": "^0.5.0"
  },
  "devDependencies": {
    "babel-jest": "22.0.3",
    "babel-plugin-transform-decorators": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native": "4.0.0",
    "eslint-config-rallycoding": "^3.2.0",
    "jest": "22.0.3",
    "react-test-renderer": "16.4.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts"
    ]
  }
}
`

**Comment by alexandergoncharov** [comment]
Hi @brzonsea,
Thanks for reporting!


>  Could this be a dependency issue? 

Yes, I think it can be. I Investigate your logs and found that your app got permissions issue. I'm not sure that it is CodePush issue. Please check that you added all necessary permissions for your app.

Please let me know if it was helpful or could you please provide test project with detailed reprosteps which help me reproduce your issue?

Thanks,
Alexander

**Comment by brzonsea** [comment]
Hi @alexandergoncharov 
Thank you for your reply. 
My `AndroidManifest.xml` file contains the following permissions.
`
<uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
`
Shouldn't these be sufficient for using CodePush? I believe `WRITE_EXTERNAL_STORAGE` and `READ_EXTERNAL_STORAGE` should be sufficient for CodePush?

**Comment by brzonsea** [comment]
I fixed the issue by reverting my React Native version back to 0.53.0
It seems the error was caused by some of the newly introduced React Native Blob features, which were introduced at version 0.54. 
After downgrading React Native, the error doesn't occur anymore. I guess code push and React Native's compatibility with the Blob features aren't so stable yet? 
Anyway thank you for the help. @alexandergoncharov

**Comment by alexandergoncharov** [comment]
Good news that your issue was resolved.

I haven't seen compatibility issue with `react-native@0.54` version before.
And I can't to reproduce it.
Anyway could you please test project or code example which can help me reproduce this issue for investigation?

Thanks,
Alexander

**Comment by brzonsea** [comment]
Yes, I will inform you when I have a reproducible demo at the ready. @alexandergoncharov

**Comment by alexandergoncharov** [comment]
Hi @brzonsea 

Just a friendly ping about reproducing demo.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @brzonsea ,

Unfortunately I'm going to close this issue for now as I haven't heard from you in a while.
Please feel free to reopen it if you have any questions or provide reproducing demo.

Thanks,
Alexander
