### ISSUE TITLE
Why task[bundleJsAndAssets] & task[generateBundledResourcesHash] don't run when start task [assembleRelease] in Android studio?

### ISSUE THREAD

**Issue by marekchen** [Microsoft/react-native-code-push#1321]
Why task[bundleJsAndAssets] & task[generateBundledResourcesHash] don't run when start task [assembleRelease] in Android studio?
But run geadlew assembleRelease in command line,it runs ok!

### Steps to Reproduce
1.start task [assembleRelease] in Android studio

### Environment

* react-native-code-push version: 5.3.4
* react-native version: 0.55.4
* iOS/Android/Windows version: 
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by NickToropov** [comment]
Hi @marekchen, thanks for posting the issue!
Please try to turn off `Configure on demand` option:
![screen shot 2018-06-19 at 1 53 59 pm](https://user-images.githubusercontent.com/31315772/41593502-eebca70e-73c8-11e8-984a-cab211bc3675.png)

Please let me know if it was helpful.

**Comment by marekchen** [comment]
It works. Thank you very much

**Comment by NickToropov** [comment]
Glad to hear the problem was solved! 
I'll close this issue for now but please feel free to reopen it or create a new one if you have any questions.
