### ISSUE TITLE
5.3.5 is on npm, but no docs on what changed

### ISSUE THREAD

**Issue by fungilation** [Microsoft/react-native-code-push#1324]
Looking at commits, I only see changes in documentation with no code changes since 5.3.4.

Is the version bump on npm a mistake?

**Comment by alexandergoncharov** [comment]
Hi @fungilation ,
Thanks for reporting.

No any mistakes. There is code changes in adding method API for Android: https://github.com/Microsoft/react-native-code-push/commit/201735ebad5ddac232be8ab6c96670c1b2102e07
List of changes for this version is here: https://github.com/Microsoft/react-native-code-push/releases/tag/v5.3.5

Please let me know if you have any questions.

Thanks,
Alexander
