### ISSUE TITLE
I don't want to enter a Deployment key in the terminal or skip it by enter, which prevents me from taking the next step in the batch file command

### ISSUE THREAD

**Issue by yangxiang1994** [Microsoft/react-native-code-push#1327]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.yarn add react-native-code-push
2. react-native link react-native-code-push
3. I need to enter the Deployment key in the terminal, but I don't want this step. Could you please remove it? Because I cannot handle this step in the batch file command in the automated deployment, thank you!

### Expected Behavior
There is no need to enter a Deployment key during the link process, nor do I need to skip it by enter because I have already configured it in info.plist and build.gradle

### Actual Behavior
I need to enter a Deployment key or skip it by enter, but I've actually configured it on both ends, so I don't need this step
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:5.3.4
* react-native version:0.55.4
* iOS/Android/Windows version:11.2
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @yangxiang1994,
Thanks for reporting!

Unfortunately, We can't remove it at all as many users would like to setup deployment key with this approach.
Anyway,  I found that `link` doesn't ask deployment key for Ios in case if it already exist. But in Android case `link` ask key for every calling.
So, I'll investigate and fix this. 
If I understand you correct, you setup keys manually and in this case when I fix it `link` command doesn't ask keys. 
Please let me know if this approach will block you anyway.
I let you now when create PR for this.

Thanks,
Alexander

**Comment by yangxiang1994** [comment]
Hi @alexandergoncharov ,Thank you very much for providing such excellent components to help us update the program more easily. I have solved this problem. I found that when running the program through the `Yarn` command, there is no need to manually set the Deployment key again. I think I have solved it.
Thank you!
yangxiang

**Comment by alexandergoncharov** [comment]
Good news =)

Thanks for keeping us in touch.
