### ISSUE TITLE
Execution failed for task ':brut.apktool:apktool-cli:proguard'.

### ISSUE THREAD

**Issue by prizoner627** [Microsoft/react-native-code-push#1328]
root@kali:~/Apktool# ./gradlew

> Configure project : 
Building SNAPSHOT (master): 92bec5

> Task :brut.apktool:apktool-cli:proguard FAILED
Warning: android.content.res.XmlResourceParser: can't find superclass or interface java.lang.Object
Warning: android.util.AttributeSet: can't find superclass or interface java.lang.Object
Warning: android.util.TypedValue: can't find superclass or interface java.lang.Object
Warning: antlr.ANTLRError: can't find superclass or interface java.lang.Error
Warning: antlr.ANTLRException: can't find superclass or interface java.lang.Exception
Warning: antlr.ANTLRGrammarParseBehavior: can't find superclass or interface java.lang.Object
......................
Warning: there were 101767 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 185 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':brut.apktool:apktool-cli:proguard'.
> java.io.IOException: Please correct the above warnings first.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

how to fix this problem?

**Comment by alexandergoncharov** [comment]
Hi @prizoner627 ,
Thanks for reporting!

Could you please provide test project with detailed repro steps which can help me reproduce this issue? 

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @prizoner627 

Unfortunately I'm going to close this issue as I haven't heard from you in a while. =(
Please feel free to reopen it if you have any questions or you provide test project for reproduce issue.

Thanks,
Alexander

**Comment by efsfssf** [comment]
Faced the same problem when compiling
