### ISSUE TITLE
Linker error while archiving iOS

### ISSUE THREAD

**Issue by iosfitness** [Microsoft/react-native-code-push#1330]
### Steps to Reproduce
1. Follow the steps mentioned here https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md
2. Archive the build

### Expected Behavior
What you expected to happen?

Archive the project successfully.

### Actual Behavior
What actually happens?

Build fails with linker error

### STACK TRACE AND/OR SCREENSHOTS

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CodePush", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Environment

* react-native-code-push version:  **react-native-code-push: ^5.3.5**
* react-native version: **react-native: 0.55.4**
* iOS/Android/Windows version: **iOS**
* Does this reproduce on a debug build or release build?  **Release** 
* Does this reproduce on a simulator, or only on a physical device? **Simulator**

**Comment by alexandergoncharov** [comment]
Hi @iosfitness ,
Thanks for reporting!

Could you please provide more details about archiving? What exactly were commands you ran?

Thanks,
Alexander

**Comment by iosfitness** [comment]
@alexandergoncharov Thanks for the reply 

I tried to build the archive via Xcode

**Comment by alexandergoncharov** [comment]
Hi @iosfitness ,
Sorry for delay.

Could you please clarify what exactly approach have you used for installing code-push? rnpm, cocoaPods or manual? (https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md)

And it s possible to provide test project with reproducing issue? 

Thanks,
Alexander
