### ISSUE TITLE
react-native how to get current version ，after code push how to git label v20

### ISSUE THREAD

**Issue by yupuyang** [Microsoft/react-native-code-push#1331]
│ Label │ Release Time │ App Version │ Mandatory │ Description │ Install Metrics │
│ v20 │ Mar 5 │ 1.3.1 │ No │ │ Active: 11% (541 of 5,046) │

**Comment by alexandergoncharov** [comment]
Hi @yupuyang ,
Thanks for reporting!

Could you please provide context and more details for your question?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @yupuyang,

Unfortunately I'm going to close this issue as I haven't heard from you in a while. =(
Please feel free to reopen it if you have any questions or provide more details.

Thanks,
Alexander
