### ISSUE TITLE
Is there any callback function could be set when optionalIgnoreButtonLabel of updateDialog be clicked? 

### ISSUE THREAD

**Issue by tsaohucn** [Microsoft/react-native-code-push#1333]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
expected call back params of optionalIgnoreButtonLabel  of updateDialog

### Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.6.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by alexandergoncharov** [comment]
Hi @tsaohucn ,
Thanks for reporting!

There isn't any callback for customisation updateDialog buttons.
But you can use `syncStatus` for checking if update was ignored and add there your custom logic.
Please check example project for this: https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/App.js#L37

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @tsaohucn ,

Unfortunately I'm going to close this issue as I haven't heard from you in a while.
Please feel free to reopen it or open one more if you have any questions.

Thanks,
Alexander
