### ISSUE TITLE
once server code is change , the next time of restart , an update dialogs must to be show , how could I choose to hidden this update dialog  for the special purpose .

### ISSUE THREAD

**Issue by kaixiniOSTT** [Microsoft/react-native-code-push#1334]

**Comment by kaixiniOSTT** [comment]
为什么 静默更新 也会有弹窗。 只是没有更新内容。
codePush.sync({
            updateDialog: false,
            installMode:codePush.InstallMode.ON_NEXT_RESTART        
 })

**Comment by alexandergoncharov** [comment]
Hi @kaixiniOSTT,

If I understand you correctly you would like to make silence update without any pop-ups.
Could you please check this example silence update from example project: https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/App.js#L71

Please let me know if you have any questions.

Thanks,
Alexander

**Comment by kaixiniOSTT** [comment]
code-push release-react codepushdemo  ios   --dev true --d Staging

after run the up code , it also pop-ups the default page, the show the normal page

**Comment by kaixiniOSTT** [comment]
I got it , this because in Xcode project ,I configure wrong, no use for code-push . then cause pop-ups dialog.

#ifdef DEBUG
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  jsCodeLocation = [CodePush bundleURL];
#endif

waste me one day to resolve this problem. God!

**Comment by showtan001** [comment]
@kaixiniOSTT   你code-push版本是多少？你有没有遇到更新成功后重新没问题， 但是 IOS再次重启app后又恢复到以前版本   我rn0.51.0  code-push 5.3.5  @alexandergoncharov

**Comment by alexandergoncharov** [comment]
Hi @kaixiniOSTT ,

Could you please fill issue template: https://github.com/Microsoft/react-native-code-push/blob/master/.github/ISSUE_TEMPLATE.md with detailed description of your issue and provide more details like code samples, logs, test project with reproducing issue?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @kaixiniOSTT ,

Unfortunately I'm going to close this issue as I haven't heard from you in a while. 
Please feel free to reopen it or open one more if you have any questions. 

Thanks, 
Alexander
