### ISSUE TITLE
build failure with react-native 0.56 (The SDK Build Tools revision (23.0.1) is too low)

### ISSUE THREAD

**Issue by krystofbe** [Microsoft/react-native-code-push#1336]
### Steps to Reproduce
1. Upgrade to react-native 0.56 according to https://facebook.github.io/react-native/docs/upgrading.html
2. Clean everything
3. run `react-native run-android`

### Expected Behavior
Build to run successfuilly

### Actual Behavior
What actually happens?
```
 FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-code-push'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-code-push'. Minimum required is 25.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

### Environment

* react-native-code-push version: react-native-code-push@^5.3.4:
* react-native version: react-native@0.56.0
* iOS/Android/Windows version: Nexus_5X_API_23
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? simulator

**Comment by alexandergoncharov** [comment]
Hi @krystofbe ,
Thanks for reporting!

Yeah, it is so because react-native has updated buildTools in @0.56 version. It is known issue. Fix in progress.

Thanks,
Alexander

**Comment by mouthzipper** [comment]
+1

**Comment by krystofbe** [comment]
"fixed" this by editing my `build.gradle`

```
subprojects {
   afterEvaluate {
     project -> if (project.hasProperty("android")) {
       android {
            compileSdkVersion 26
            buildToolsVersion "26.0.3"
       }
      }
    }
}
```

**Comment by alexandergoncharov** [comment]
Hi @krystofbe  and @mouthzipper 

Created PR for this: https://github.com/Microsoft/react-native-code-push/pull/1342
Could you please test it when you get the chance?

Thanks,
Alexander

**Comment by xaviraol** [comment]
Hi @alexandergoncharov  
Would it be possible to use the proposed approach [here](https://github.com/react-community/react-native-maps/pull/2047)?

**Comment by alexandergoncharov** [comment]
Hi @xaviraol,

Do you mean use project-wide properties? Yeah, It is good approach. Thanks for this.

**Comment by alexandergoncharov** [comment]
Hi all,

#1342 is updates with project-wide properties.

**Comment by alexandergoncharov** [comment]
Hi all,

I'm going to close this issue as fix in master and already in new release.
Please feel free to reopen it if you have any questions or you face this issue again.

Thanks,
Alexander
