### ISSUE TITLE
Execution failed for task ':react-native-code-push:verifyReleaseResources'.

### ISSUE THREAD

**Issue by deehuey** [Microsoft/react-native-code-push#1337]
### Steps to Reproduce
1. `./gradlew assembleRelease` on RN 0.56 

### Expected Behavior

Running `react-native run-android --variant=release` works, but when attempting to run `./gradlew assembleRelease` it outputs:

```
Execution failed for task ':react-native-code-push:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

### Environment

* react-native-code-push version: 5.3.5
* react-native version: 0.56
* iOS/Android/Windows version: Android Build Process
* Does this reproduce on a debug build or release build? Release build only, but `react-native run-android --variant=release` build works properly. Its assembly only.
* Does this reproduce on a simulator, or only on a physical device? Neither, its a build process issue.

(The more info the faster we will be able to address it!)

**Comment by deehuey** [comment]
So here is how I fixed it, pretty simple really though I don't know if this will cause any issues, I will report back if code-push isn't working properly:

I just hopped in to your build.gradle in the node_modules and updated compileSdkVersion to 26, and build tools version to 27.0.3

If I may suggest a solution moving forward: many RN packages have been using the project's build tools / compile version by properties set in the root projects `build.gradle`.

It was a recommendation by `react-native-background-geolocation-android` and `react-native-maps` which helps ensure all sub projects are using the same versions.

## Solution

Their solution was in our projects `android/build.gradle` add:

```
ext {
    compileSdkVersion   = 26
    targetSdkVersion    = 22
    buildToolsVersion   = "27.0.3"
    supportLibVersion   = "26.1.0"
    playServicesVersion = "15.0.0"
    firebaseVersion = "15.0.2"
}
```

because in their `build.gradle` of the geolocation and maps plugins, they reference the root projects versions with the following code:

```
def DEFAULT_COMPILE_SDK_VERSION     = 26
def DEFAULT_BUILD_TOOLS_VERSION     = "26.0.2"
def DEFAULT_TARGET_SDK_VERSION      = 26
def DEFAULT_PLAY_SERVICES_VERSION   = "11.8.0"

android {
    compileSdkVersion project.hasProperty('compileSdkVersion') ? project.compileSdkVersion : DEFAULT_COMPILE_SDK_VERSION
    buildToolsVersion project.hasProperty('buildToolsVersion') ? project.buildToolsVersion : DEFAULT_BUILD_TOOLS_VERSION
```

I'm not sure if this is risky or more bug prone to have in your project, since I have no clue how Android works, but this has my builds passing so =)

**Comment by deehuey** [comment]
Feel free to close this issue =)

**Comment by alexandergoncharov** [comment]
Hi @deehuey,
Thanks for reporting!

Yeah, it is so because react-native has updated buildTools in @0.56 version. It is known issue. Fix in progress.
Also, thanks for your investigation and suggested fix =)
As we have already issue for comparability with new version lets keep it in one place: https://github.com/Microsoft/react-native-code-push/issues/1336
So, I'll close this issue for now but please feel free to reopen it if you have any questions.
 

Thanks,
Alexander

**Comment by phsantiago** [comment]
In my case we upgrade RN and CodePush and then to solve this issue we needed to `rm -rf node_modules` and `yarn install`
