### ISSUE TITLE
After the update is successful, there is no problem, but IOS restarts the app again and then reverts to the previous version.

### ISSUE THREAD

**Issue by showtan001** [Microsoft/react-native-code-push#1339]
After the update is successful, there is no problem, but IOS restarts the app again and then reverts to the previous version.

### Environment

* react-native-code-push version:  5.3.5
* react-native version:  0.51.0
* only iOS

### code
`constructor(props) {
CodePush.notifyAppReady();
}
componentDidMount() {
CodePush.sync({
            updateDialog: {
                appendReleaseDescription: true,
                title: 1111,
                descriptionPrefix: 111,
                mandatoryUpdateMessage: 1111,
                mandatoryContinueButtonLabel: 11111,
            },
            mandatoryInstallMode: CodePush.InstallMode.IMMEDIATE 
        })
}`

help me! thanks

**Comment by JslinSir** [comment]
the same problem

**Comment by alexandergoncharov** [comment]
Hi @showtan001  and @JslinSir ,
Thanks for reporting!

Could you please share mectrics(installs, downloads) and your logs for this? Logs should be from checking updates to reopening app and getting previous version.


Thanks,
Alexander

**Comment by iloveyumiforever** [comment]
same problem + 1

**Comment by alexandergoncharov** [comment]
@iloveyumiforever , Could you please provide additional info which I described above?

**Comment by showtan001** [comment]
@iloveyumiforever    hi, what is your react native version?

**Comment by showtan001** [comment]
Can you see your update code? @iloveyumiforever

**Comment by NickToropov** [comment]
Hi guys! Could anyone provide us with demo app that reproduces the issue?

**Comment by iloveyumiforever** [comment]
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.6.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by NickToropov** [comment]
Hi @showtan001, based on your initial post it's hard to detect the problem as you use CodePush in not typical way. So we require demo app to figure out a issue.

Also it's important to know how CodePush was setup: RNPM, CocoaPods or Manual . Please see the following [doc](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios).

**Comment by alexandergoncharov** [comment]
@iloveyumiforever , Great to see that your issue was resolved. Thanks for keeping us in touch.

@showtan001 I'm going to close this issue as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
