### ISSUE TITLE
react-native link broken for react-native-windows

### ISSUE THREAD

**Issue by rozele** [Microsoft/react-native-code-push#1343]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Create a new react-native project with `react-native init` (v55 or earlier)
2. Add `react-native-windows` with `yarn add --dev rnpm-plugin-windows` and `react-native windows`
3. Install `react-native-code-push` with `yarn add react-native-code-push`
4. Try to run `react-native link`

### Expected Behavior
What you expected to happen?

The native dependency should be linked into the react-native-windows project.

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

The .csproj and IReactPackage are not linked.

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

Any default template will do.

### Environment

* react-native-code-push version: 5.3.2
* react-native version: 0.54.*
* iOS/Android/Windows version: Windows 10 RS4
* Does this reproduce on a debug build or release build? N/A
* Does this reproduce on a simulator, or only on a physical device? N/A

(The more info the faster we will be able to address it!)

**Comment by rozele** [comment]
The issue is actually caused by the "shared project" approach used to implement both UWP and WPF support for react-native-windows. The link command in react-native-windows works similar to Android - it looks for a class matching `IReactPackage` and grabs the .csproj in that directory. In the case of `react-native-code-push`, the `IReactPackage` file is only in the same folder as the .shproj, not the `.csproj` for UWP.

**Comment by alexandergoncharov** [comment]
Hi @rozele 
Thanks for reporting!

Could you please clarify have you tried to setup codepush for windows using this docs?
https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-windows.md

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @rozele ,

For now react-native-code-push doesn't support `link` command for windows. For setup code-push to react-native-windows we have only manual approach which described here: https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-windows.md

Unfortunately I'm going to close this issue as I haven't heard from you in a while.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
