### ISSUE TITLE
Whitelisting codepush servers

### ISSUE THREAD

**Issue by EdwardNickson** [Microsoft/react-native-code-push#1345]
Briefly: Is there an official list of CodePush servers which I can whitelist?

Our business is working on a RN application using CodePush and some of our users have environments which are quite locked down. We're going to have to advise our users of the codepush servers to add to their whitelists.

Currently it looks like there's just these two:
https://codepush.azurewebsites.net
https://codepushupdates.azureedge.net

Are there any others?
And are the above likely to change?

**Comment by alexandergoncharov** [comment]
Hi @EdwardNickson ,
Thanks for reporting!

Yeah, we have this one: https://codepush.blob.core.windows.net
So, in general, Here is 3 codepush servers which should be allowed to your users: 
https://codepush.azurewebsites.net
https://codepushupdates.azureedge.net
https://codepush.blob.core.windows.net

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Please let me know it was helpful for you or you have more questions.

**Comment by EdwardNickson** [comment]
Thanks @alexandergoncharov,
That's all I needed to now
