### ISSUE TITLE
code push update.isFirstRun keep calling when the apps not closed yet

### ISSUE THREAD

**Issue by zxccvvv** [Microsoft/react-native-code-push#1346]
I have `SwitchNavigator` from `React Navigation`, 
let say I have two possible screen:

1. for logged user I've set displaying 3 screen (Home, MainScreen, and My Account)
2. for unlogin user I've set displaying 2 screen (Home and Login)

I'm put `codePush code` at `Home.js` so if the user not yet login or already logged in, the apps will redirecting to `Home.js`, I have set Modal `What's New` at `Home.js` but everytime the screen goes to `Home`, The Modal triggered to show,

Step to reproduce:

1. open App and notify to download the update
2. after restart the bundle js, Modal `What's New` appear to show the news update
3. log in into the apps,
4. redirect to home, and the Modal `What's New` appear the same news update
5. logout from apps, and redirect to home
6. Modal `What's New` appear the same news update
7. repeating step 3-6 will always showing Modal `What's New`

the issue would annoying some user, so i want to avoid it, how can i do that with the existing code?

> The reason I don't put `codePush` at `App.js` because the Modal won't show and goes to Home itself

Home.js:

 ```
{import foo from 'bar'}

class Home extends React.Component{
componentDidMount(){
    codePush.sync({
      updateDialog: {
        title: "Pembaruan Tersedia",
        optionalUpdateMessage: "Mohon untuk membarui aplikasi anda ke versi terbaru!",
        optionalIgnoreButtonLabel: null,
        optionalInstallButtonLabel: "Perbarui Sekarang",
      },
      installMode: codePush.InstallMode.IMMEDIATE
    },
      (status)=>{
        switch (status) {
          case codePush.SyncStatus.CHECKING_FOR_UPDATE:
            console.log("Checking for updates.");
            break;
          case codePush.SyncStatus.DOWNLOADING_PACKAGE:
            console.log("Downloading...", "Please wait...")
            this.setState({ModalDownload:true})
            break;
            case codePush.SyncStatus.INSTALLING_UPDATE:
            this.setState({ModalDownload:false})
            console.log("Installing update.");
            break;
          case codePush.SyncStatus.UP_TO_DATE:
            console.log("Up-to-date.");
            break;
          case codePush.SyncStatus.UPDATE_INSTALLED:
            console.log("Update installed.");
            break;
          default:
            break;
        }
      }, ({receivedBytes, totalBytes})=>{
        this.setState({DLProgress: (receivedBytes / totalBytes) * 100})
      });
   //here's the code triggering Modal What's New
    codePush.getCurrentPackage().then((update)=>{
      if(update.isFirstRun){
        console.log("TAMPILIN MODAL", "MODALNYA DITAMPILIN YA KALO BERHASIL")
        this.setState({ModalWhatsNew:true})
        codePush.notifyAppReady()
      }
    })
    codePush.getUpdateMetadata().then((metadata) =>{
      this.setState({label: metadata.label, version: metadata.appVersion});
    });
  }

  render() {
    return (
      <Modal
         {Showing Download Progress}
        </Modal>

        <Modal
         {Showing What'sNew}
        </Modal>
    );
  }
}
```

### Environment

* react-native-code-push version: **^5.3.4**
* react-native version: **^0.53.0**
* iOS/Android/Windows version: **Android Lolipop**
* Does this reproduce on a debug build or release build? **Staging (not yet release)**
* Does this reproduce on a simulator, or only on a physical device? **both**

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @zxccvvv ,
Thanks for reporting!

Yeah, `update.isFirstRun` will be `true`  as long as app will be reopened. I think that you should add some logic for prevent additional showing your Modal. You can add one more bool variable for checking if Modal already was shown or something like that.

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @zxccvvv ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
