### ISSUE TITLE
Module JSTimers is not a registered callable module

### ISSUE THREAD

**Issue by sankalpgoibibo** [Microsoft/react-native-code-push#1348]
### Steps to Reproduce

1. Upgrade to react-native@0.49.3 and react-native-code-push to 5.1.3-beta. 
This is supposed to work as per supported versions table in README.md.

### Expected Behavior
On resume `codepush.sync` should not fail.

### Actual Behavior

1. Open my app.
2. On navigating to some other app and coming back to my app, the following logs appear in logcat.
3. After this the app crashes and it crashes continuously and we have to reinstall it.

### Logs
`
07-12 15:00:11.609  3658  3678 I ReactNativeJS: 'Encountered multiple fatals in a row. The latest:', { [Invariant Violation: Module JSTimers is not a registered callable module (calling callTimers)]
07-12 15:00:11.609  3658  3678 I ReactNativeJS:   name: 'Invariant Violation',
07-12 15:00:11.609  3658  3678 I ReactNativeJS:   framesToPop: 1,
07-12 15:00:11.609  3658  3678 I ReactNativeJS:   line: 14,
07-12 15:00:11.609  3658  3678 I ReactNativeJS:   column: 374,
07-12 15:00:11.609  3658  3678 I ReactNativeJS:   sourceURL: '/data/user/0/com.sank/files/CodePush/5bd178e97cf095ff537b2g7g6f61b20ac2cf92ff609655cea8397f4af261b874/CodePush/index.android.bundle' }
07-12 15:00:11.641  3658  3679 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
07-12 15:00:11.641  3658  3679 E AndroidRuntime: Process: com.sank, PID: 3658
07-12 15:00:11.641  3658  3679 E AndroidRuntime: com.facebook.react.bridge.NativeArgumentsParseException: Networking.sendRequest got 8 arguments, expected 9
07-12 15:00:11.641  3658  3679 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:344)
07-12 15:00:11.641  3658  3679 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
07-12 15:00:11.641  3658  3679 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-12 15:00:11.641  3658  3679 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
07-12 15:00:11.641  3658  3679 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-12 15:00:11.641  3658  3679 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
07-12 15:00:11.641  3658  3679 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-12 15:00:11.641  3658  3679 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
07-12 15:00:11.641  3658  3679 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
07-12 15:00:11.643  1635  1991 W ActivityManager:   Force finishing activity com.sank/.MainActivity
07-12 15:00:11.654  1283  1319 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1019904
`

### Environment

* react-native-code-push version: **5.1.3-beta**
* react-native version: **0.49.3**
* iOS/Android/Windows version: **android-24 - 7.0 Nougat**
* Does this reproduce on a debug build or release build? **Only release build.**
* Does this reproduce on a simulator, or only on a physical device? **Both on emulator and device.**

> build.gradle

`
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
compile project(':react-native-code-push')
`

> settings.gradle

`
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
`

> main.js

```
class Main extends Component {
  render() {
    if(Platform.OS === "android") {
    //Removing the below line, the app does not crash.
    codePush.sync({
            updateDialog: false,
            checkFrequency: codePush.CheckFrequency.ON_APP_START,
            installMode: codePush.InstallMode.ON_NEXT_RESUME
                   });
                 }

 return (
        <Provider store={store}>
            <View style={{ overflow: "visible", flex:1}}>
                <NavigationDrawer />
            </View>
        </Provider>
    );
  }
}
export default Main;

```

> React-native link output

```
Running ios postlink script
"CodePush.h" header already imported.
"jsCodeLocation" already pointing to "[CodePush bundleURL]".
Could not determine correct xcode proj path to retrieve related plist file, there are multiple xcodeproj under the solution.
"CodePushDeploymentKey" already specified in the plist file.
Running android postlink script
"getJSBundleFile" is already overridden
"codepush.gradle" is already linked in the build definition
```

**Comment by alexandergoncharov** [comment]
Hi @sankalpgoibibo ,
Thanks for reporting!

Unfortunately I can't reproduce your issue. Could you please test project with reproducing issue and detailed repro steps?

Thanks,
Alexander

**Comment by sankalpgoibibo** [comment]
Removed all earlier references of codepush in the app and then did a fresh install followed by npm link.
This lead to a modification in file `MainApplication.java`; though the changes were already there, but now the code is a little different from what it was earlier.

Thanks Alexander.

**Comment by alexandergoncharov** [comment]
Good news. 
Thanks for keeping us in touch!

**Comment by 452MJ** [comment]
+1

rn:0.47.2 code-push:5.1.3-beta

**Comment by 452MJ** [comment]
I got it. Because RN 0.47.2 merge JSTimers and JSTimersExecution. So in your old version app load JSTimersExecution fail. I think you can copy `/node_modules/react-native/Libraries/Core/Timers/JSTimersExecution.js` from rn 0.46 and merge it into your 0.47+ branch.

Then, in `node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js`. You can load JSTimers by below code

```
 __callImmediates() {
    Systrace.beginEvent('JSTimers.callImmediates()');
    if (!JSTimers) {
      JSTimers = checkYourAppVersion? require('JSTimers') : require('JSTimersExecution');
    }
    JSTimers.callImmediates();
    Systrace.endEvent();
  }
```
