### ISSUE TITLE
[Android] Images disappear after installing CodePush update

### ISSUE THREAD

**Issue by chocky335** [Microsoft/react-native-code-push#1350]
Android only, iOS works as expected

### Steps to Reproduce
1. Add local image like:
```
import img1 from "@path/toImg"
<Image source={img1} />
```
2. send codepush update for android
3. update android app

### Expected Behavior
Image should renders

### Actual Behavior
No image renders, only transparent container.

### Reproducible Demo
----

### Environment

* react-native-code-push version: 5.4.0
* react-native version: 0.56
* Android version: 7.0
* on release build
* reproduce on a simulator and on a  physical device?

**Comment by alexandergoncharov** [comment]
Hi @chocky335,
Thanks for reporting!

Unfortunately I can't reproduce it. I made new update with image and successfully got image in app with CodePush.
Could you please provide test project with reproducing issue and detailed repro steps? 

Thanks,
Alexander

**Comment by chocky335** [comment]
@alexandergoncharov It started happening after upgrade to RN 0.56 maybe smth with dependencies.
These are our android project configs:
1) android/build.gradle
```

}

buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:3.1.0'
    }
}

allprojects {
    repositories {
        google()
				// Add jitpack repository (added by react-native-spinkit)
				maven { url "https://jitpack.io" }

                maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        configurations.all {
            resolutionStrategy {
                force 'com.facebook.android:facebook-android-sdk:4.28.0'
                force 'com.google.android.gms:play-services-gcm:11.8.0'
            }
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
```
2) android/app/build.gradle
```
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId appId
        minSdkVersion 16
        targetSdkVersion 20
        ...
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

...

dependencies {
    implementation project(':react-native-firebase')

    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:11.8.0"
    implementation "com.google.firebase:firebase-core:11.8.0"
    implementation 'com.google.firebase:firebase-messaging:11.8.0'
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-fast-image')
    compile project(':react-native-splash-screen')
    compile project(':react-native-bottom-action-sheet')
    compile project(':react-native-prompt-android')
    compile project(':react-native-code-push')
    compile project(':react-native-config')
    compile project(':react-native-sentry')
    compile project(':react-native-zendesk-support')
    compile project(':react-native-device-info')
    compile project(':react-native-branch')
    compile project(':react-native-svg')
    compile project(':react-native-fbsdk')
    compile project(':react-native-image-picker')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-vector-icons')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support:design:26.0.2'
    compile 'com.facebook.react:react-native:+'
    // From node_modules
    compile 'com.zopim.android:sdk:1.3.5.1'
    compile project(':react-native-zendesk-chat')
    compile 'com.android.support:multidex:1.0.3'
}
...

**Comment by chocky335** [comment]
app without codepush update: 
![screenshot_20180717-131732_knipsterbeta](https://user-images.githubusercontent.com/17751725/42814372-45eadb7a-89c4-11e8-897c-072c412faace.jpg)

app with codepush update: 
![screenshot_20180717-131623_knipsterbeta](https://user-images.githubusercontent.com/17751725/42814381-500fa144-89c4-11e8-9572-3edf1f5b05be.jpg)

our package.json dependencies:
```
"dependencies": {
    "moment": "^2.18.1",
    "pusher-js": "^4.2.2",
    "react": "16.4.1",
    "react-native": "^0.56.0",
    "react-native-bottom-action-sheet": "^0.0.5",
    "react-native-branch": "^2.2.4",
    "react-native-code-push": "^5.4.0",
    "react-native-config": "0.9.1",
    "react-native-device-info": "^0.21.5",
    "react-native-fast-image": "^4.0.0",
    "react-native-fbsdk": "^0.7.0",
    "react-native-firebase": "^4.1.0",
    "react-native-image-picker": "^0.26.3",
    "react-native-linear-gradient": "^2.0.0",
    "react-native-notifications": "^1.1.17",
    "react-native-prompt-android": "https://github.com/Noitidart/react-native-prompt-android#patch-1",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-sentry": "^0.38.0",
    "react-native-snap-carousel": "^2.1.4",
    "react-native-splash-screen": "^3.0.6",
    "react-native-svg": "^6.1.3",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-vector-icons": "^4.5.0",
    "react-native-zendesk-chat": "^0.2.2",
    "react-native-zendesk-support": "^1.0.9",
    "react-navigation": "^2.3.1",
    "tinycolor2": "^1.4.1",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "babel-jest": "20.0.3",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-preset-react-native": "^5.0.1",
    "elm-format": "^0.6.1-alpha",
    "eslint": "^4.10.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-babel": "^4.1.2",
    "eslint-plugin-flowtype": "^2.39.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jest": "^20.0.3",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.4.0",
    "eslint-plugin-react-native": "^3.1.0",
    "flow-bin": "^0.74.0",
    "flow-typed": "^2.1.2",
    "husky": "^0.14.3",
    "jest": "^21.1.0",
    "jest-mock-now": "^1.1.1",
    "lint-staged": "^4.3.0",
    "react-native-schemes-manager": "^1.0.1",
    "react-test-renderer": "16.0.0-alpha.12",
    "xcode": "^0.9.3"
  }
```

**Comment by alexandergoncharov** [comment]
Hi @chocky335 ,

Unfortunately I'm going to close this issue as I haven't heard from you in while.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by sijad** [comment]
we have similar issue with `react-native` `0.56.0` and `react-native-code-push` `5.4.0`, code push was working alright before.

**Comment by raghvendrapacholi** [comment]
I am facing same issue with react-native: 0.62.2 and  "react-native-code-push": "^6.4.0". Any thought/quick fix from anyone will be very thankful?

**Comment by ZeroCho** [comment]
This is happening if I codepush more than once. One time codepush is OK, but if I do twice or more, images are gone.

**Comment by marsoochan** [comment]
We stuck in the same situation in a RN for Android project, still trying all the way out..will post results here when it's done.

**Comment by marsoochan** [comment]
It is solved in my environment.
Problem: Android RN APP failed to render images after Code-Push updates
ENV: Private Code-Push-Server on Ubuntu 16.04
Cause Found:  using RN assets system to load images, MUST release assets with JS bundle to CodePush (refers to https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-troubleshooting)
Solution: change to new bundle commands.

Before : react-native bundle --platform android --entry-file index.js --bundle-output ./CodePush/main.jsbundle --assets-dest ./CodePush --dev false

After :react-native bundle --entry-file index.js --bundle-output ./bundles/index.android.bundle
 --platform android --assets-dest ./bundles --dev false

code-push release PRJ_NAME ./bundles/ 1.0.0 --deploymentName Production --description "Update 1.0.4" --mandatory true

**Comment by ocmg-dev** [comment]
> It is solved in my environment.
> Problem: Android RN APP failed to render images after Code-Push updates
> ENV: Private Code-Push-Server on Ubuntu 16.04
> Cause Found: using RN assets system to load images, MUST release assets with JS bundle to CodePush (refers to https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-troubleshooting)
> Solution: change to new bundle commands.
> 
> Before : react-native bundle --platform android --entry-file index.js --bundle-output ./CodePush/main.jsbundle --assets-dest ./CodePush --dev false
> 
> After :react-native bundle --entry-file index.js --bundle-output ./bundles/index.android.bundle
> --platform android --assets-dest ./bundles --dev false
> 
> code-push release PRJ_NAME ./bundles/ 1.0.0 --deploymentName Production --description "Update 1.0.4" --mandatory true

I also stuck in the same situation, will try this out and post the result, thx a lot

**Comment by december1990** [comment]
I'm experiencing this issue with the following versions

"react-native": "0.64.4",
"react-native-code-push": "^7.0.5",

creating release with the following command 

appcenter codepush release-react -a email/app -m -d Production

**Comment by MikhailSuendukov** [comment]
Hi @december1990 

Could you please confirm what this issue still persist on latest version (8.2.1)? If the problem is still present, could you please try this [solution](https://github.com/microsoft/react-native-code-push/issues/1350/#issuecomment-915972333)?

**Comment by MufeedaFi** [comment]
Can we get to know from where the images in React native is being loaded from natively? ie, in android native side, where should we look up for the images? Or is there any way we can override the resources used in native android side for a React native project like  @Override
        protected String getJSBundleFile() {
