### ISSUE TITLE
[Question] What is the best choice?

### ISSUE THREAD

**Issue by lucianomlima** [Microsoft/react-native-code-push#1352]
[appcenter-cli](https://github.com/Microsoft/appcenter-cli) or [code-push](https://github.com/Microsoft/code-push)?

Nowhere in the docs does it make it clear if it's to stop using the `code-push` in favor of `appcenter-cli`, if it will be discontinued or if there is any deadline to become deprecated.

**Comment by alexandergoncharov** [comment]
Hi @lucianomlima ,
Thanks for reporting!

You can use both, just what you prefer. But in our recommendation is to use `appcenter-cli`.
At now there isn't any reason for deprecate it.
If there will be some deprecate deadline we will put this information in docs.

Please let me know if it was helpful.

Thanks,
Alexander

**Comment by lucianomlima** [comment]
Thanks.
