### ISSUE TITLE
[iOS] JS bundle has been updated but all of the assets have disappeared. 

### ISSUE THREAD

**Issue by ryanliszewski** [Microsoft/react-native-code-push#1355]
### Steps to Reproduce

- appcenter codepush release-react -a volta-admin/volta-iOS -d Development --description -t 3.3.1
- appcenter codepush promote -a volta-admin/volta-iOS -s Development -d Production

- I was testing out Codepush in production through testflight by adding another text label. The JS bundle was updated, and I can see the new text label, but then all my apps assets have disappeared. 

- I tried the exact same change on Android and everything worked fine. This is just an iOS problem for me.

### Expected Behavior
What you expected to happen?
- To add a text label.

### Actual Behavior
What actually happens?
- The text label was added but all my assets disappeared. 

### STACK TRACE AND/OR SCREENSHOTS

![image from ios](https://user-images.githubusercontent.com/5275250/42970624-a3cb2308-8b5e-11e8-85b0-564596ae1421.png)

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: **5.4.0**
* react-native version: **0.55.4**
* iOS/Android/Windows version: **11.4 iOS**
* Does this reproduce on a debug build or release build? **Release**
* Does this reproduce on a simulator, or only on a physical device? **Physical iOS 7 Device**
- Wix React Native Navigation: **1.1.473**

**Comment by alexandergoncharov** [comment]
Hi @ryanliszewski ,
Thanks for reporting!

Is it possible to provide test project with reproducing issue and detailed repro steps?  as I can't reproduce it.
And also, I see that this issue appears in Release. Could  you please clarify have you tested it in debug mode?

Thanks,
Alexander

**Comment by ryanliszewski** [comment]
1. I can't create a test project because the code is sensitive but I can try to create a dummy project when I have time this week. 
2. I've tested this in debug and have not been able to reproduce the bug. The issue only appears in release.

**Comment by ryanliszewski** [comment]
Hey @NickToropov . I've been working on other projects and haven't had time. I will try to create a dummy project this weekend.

**Comment by alexandergoncharov** [comment]
Hi @ryanliszewski ,

Just a friendly ping about dummy project =)

**Comment by alexandergoncharov** [comment]
Hi @ryanliszewski ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen this issue if you have dummy project or you have any questions.

Thanks,
Alexander
