### ISSUE TITLE
RN 0.56.0 - Codepush.sync() crashes in production build but not development.

### ISSUE THREAD

**Issue by keshk26** [Microsoft/react-native-code-push#1359]
Hello, after upgrading RN to 0.56.0 my production app is crashing for iOS, and I believe it is an issue with react-native-code-push. If I remove/comment the codePush.sync() call the app does not crash. I have had codePush sync called like this since RN 0.48 but I don't see it called when a component mounts in the latest documentation. Thanks for any help! 

### Steps to Reproduce
1. Point your app to production. 
2. In CodePush.sync callback, log or display the syncStatus
3. Run your app.

### Expected Behavior
App is updated successfully after syncing codepush.  

### Actual Behavior
What actually happens?
The native iOS build is successfully but calling codePush.sync() in App.js crashes in production. Stacktrace below: 
```
 2018-07-23 13:08:50.902 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'Sn[e]')
2018-07-23 13:08:50.903 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'Sn[e]')
2018-07-23 13:08:50.904 [error][tid:main][RCTUIManager.m:1107] Exception thrown while executing UI block: -[__NSDictionaryM dataUsingEncoding:]: unrecognized selector sent to instance 0x1d0433720
libc++abi.dylib: terminating with uncaught exception of type NSException
```

### Reproducible Demo
I have staging and production envs for iOS and Android. And those keys are being set correctly. In the below code sample, the syncMessage, CHECKING_FOR_UPDATE and DOWNLOADING_PACKAGE displays but then the app crashes.
```
import React, { Component } from 'react'
import { Platform, View, Text } from 'react-native'
import CodePush from 'react-native-code-push'
import { Provider } from 'react-redux'
import CONFIG from 'ServiceNative/app/config'
import store from './store';

class App extends Component {

  state = {
    syncMessage: ''
  }

  codePushStatusDidChange = (syncStatus) => {
    switch(syncStatus) {
      case CodePush.SyncStatus.CHECKING_FOR_UPDATE:
        this.setState({ syncMessage: 'Checking for update.' });
        break;
      case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
        this.setState({ syncMessage: 'Downloading package' });
        break;
      case CodePush.SyncStatus.AWAITING_USER_ACTION:
        this.setState({ syncMessage: 'Awaiting user action.' });
        break;
      case CodePush.SyncStatus.INSTALLING_UPDATE:
        this.setState({ syncMessage: 'Installing update.' });
        break;
      case CodePush.SyncStatus.UP_TO_DATE:
        this.setState({ syncMessage: 'App up to date.', progress: false });
        break;
      case CodePush.SyncStatus.UPDATE_IGNORED:
        this.setState({ syncMessage: 'Update cancelled by user.', progress: false });
        break;
      case CodePush.SyncStatus.UPDATE_INSTALLED:
        this.setState({ syncMessage: 'Update installed and will be applied on restart.', progress: false });
        break;
      case CodePush.SyncStatus.UNKNOWN_ERROR:
        this.setState({ syncMessage: 'An unknown error occurred.', progress: false });
        break;
    }
  }

  componentDidMount () {
    const codePushKey = Platform.OS === 'ios' ? CONFIG.iosCodepushDeploymentKey : CONFIG.androidCodepushDeploymentKey
    CodePush.sync({
      deploymentKey: codePushKey,
      installMode: CodePush.InstallMode.IMMEDIATE
    }, this.codePushStatusDidChange)
  }

  render () {
    return (
      <Provider store={store}>
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
          <Text>{this.state.syncMessage || ''}</Text>
        </View>
      </Provider>
    )
  }
}

const codePushOptions = {
  checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME
}

export default CodePush(codePushOptions)(App)
```

### Environment

* react-native-code-push version: 0.5.4
* react-native version: 0.56.0
* iOS/Android/Windows version: iOS 11.4
* Xcode version: 9.4
* Does this reproduce on a debug build or release build? Release production build
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by NickToropov** [comment]
Hi @keshk26, I wasn't able to reproduce your issue. Could you please provide us with demo project that reproduce the problem?

**Comment by keshk26** [comment]
Sorry for the trouble, this crash was occurring because my codepush version was not synced with the lastest code. Once I pushed up a new codepush version, it worked as expected.

**Comment by NickToropov** [comment]
@keshk26 glad to hear that you solved your problem!
