### ISSUE TITLE
request specific version from codepush to be downloaded

### ISSUE THREAD

**Issue by BatDroid** [Microsoft/react-native-code-push#1361]
is it possible to request a specific version (not the last version which is pushed) to be downloaded or is there any workaround for such a job?

**Comment by NickToropov** [comment]
Hi @BatDroid, 
Thanks for reporting!

It can be done if your binary and pushed versions have the most precise format and are equal.
For example: 1.0.1, 2.2.3, etc.
If you specify `1.0` for your pushed version then it will be available for downloading for all binary versions in range from 1.0 to 1.1 (for example 1.0.1, 1.0.213)

**Comment by BatDroid** [comment]
hi @NickToropov 
thanks for your response but what i had in mind is a scenario like this:
1. i have added a featured and pushed it to codepush (Label=V1)
2. i have added another feature and pushed it to codepush (Label=V2)
3. another feature and push (Label=V3) and so on.
4. and now in client (for any reason) i request the V1. the default mode is that i get the last one which is V3 (or anything else if it is pushed)

**Comment by NickToropov** [comment]
Hi @BatDroid 
Yeah, the codepush just iterates through releases and compares your binary version(passed in request) and release targetBinaryVersion param(every pushed release has `targetBinaryVersion` [param](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter)) and choose the latest one that satisfy this condition. So in your scenario if all releases have the same `targetBinaryVersion` (for example `1.0`) than the latest `v3` release will be chosen.

**Comment by NickToropov** [comment]
Hi @BatDroid, I'll close this issue for now but please fill free to reopen this one or create new issue if you have any questions.

**Comment by nzaghini-phorest** [comment]
hey @BatDroid I think your question is still very relevant, have you ever found a solution/approach to what you have described ?
