### ISSUE TITLE
Codepush in China is Slow...

### ISSUE THREAD

**Issue by fzyzcjy** [Microsoft/react-native-code-push#1369]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Use codepush in China
2. 
3.

### Expected Behavior
What you expected to happen?
Get fast speed when the app updates

### Actual Behavior
What actually happens?
It is slow in China...
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by fzyzcjy** [comment]
@NickToropov Thank you for th reply! Is it possible that I create a server myself? :/

**Comment by NickToropov** [comment]
@fzyzcjy, yes it's possible but **not recommended** and **not supported** by our team. You can look at one implementation: https://github.com/lisong/code-push-server and user/fork this one or create your own implementation.

**Comment by fzyzcjy** [comment]
@NickToropov Thank you very much! Do you have any plan about deploying some servers/mirrors which are fast in China?

**Comment by Zakeelm** [comment]
@fzyzcjy As of now, we don't currently have any plans to do so. This is something we wan definitely look into though and investigate further though as we've had other requests. I'll run it by the rest of the team and see if this is something we can accomplish in the future.
