### ISSUE TITLE
NoClassDefFoundError: java.util.Objects Android

### ISSUE THREAD

**Issue by willchu** [Microsoft/react-native-code-push#137]
Running Code Push for react native for phones that are using sdk version 16 fails because there is no support of java.util.Objects until sdk version (API Level) 19

You can reproduce easily at compile time by enabling lint. 

![screen shot 2016-01-04 at 2 38 08 pm](https://cloud.githubusercontent.com/assets/182378/12102600/cc85899e-b2f0-11e5-8cfb-3acfce16b101.png)

**Comment by lostintangent** [comment]
Thanks for reporting this @willchu! All of our testing up till this point has used KitKat and newer devices/emulators, so I apologize that you're hitting this. We'll make sure to address this and any other issues with Jellybean ASAP!

**Comment by willchu** [comment]
Thanks @lostintangent! Do you have a time estimate for when you would release a fix? It would be really helpful.

**Comment by geof90** [comment]
Hi @willchu, I was able to run CodePush on an API level 16 device with the latest version of the plugin. Please let us know if you are still seeing errors.
