### ISSUE TITLE
Detailed break down of "bug fixing" in changelog

### ISSUE THREAD

**Issue by GregoryCollett** [Microsoft/react-native-code-push#1374]
### Steps to Reproduce
1. View a change log
2. See there has been "Bug fixing"

### Expected Behavior
I expect to see which bugs have been fixed potentially with related issues where applicable

### Actual Behavior
I just see "Bug fixing" in the change log

### Reproducible Demo

Navigate to https://github.com/Microsoft/react-native-code-push/releases/tag/v5.4.0

Sorry!.. I thought I should follow the expected format!

As a code-push user, It would be beneficial if I knew which bugs where fixed, so that they can determine if I want to take the jump and perform the upgrade (and migration when required).

**Comment by alexandergoncharov** [comment]
Hi @GregoryCollett,
Thanks for reporting!

We use "Bug fixing" text for small bugs. For big bugs or changes we add more info.
For example for 5.4.0 release "Bug fixing" is just fix this issue: https://github.com/Microsoft/react-native-code-push/issues/1272

Hope it was helpful for you.
Please let me know if you have any questions or suggestions.

Thanks,
Alexander

**Comment by GregoryCollett** [comment]
Hi @alexandergoncharov,

Thank you for your response. This is definitely helpful.

Out of curiosity are issue linked to pr's? I think this could be a helpful step - This should give me the ability to manually dig around to determine the changes.

Again, thanks for the response! Appreciated!
Greg

**Comment by alexandergoncharov** [comment]
@GregoryCollett , Sure. Pr attached in that issue. 
It is this PR: https://github.com/Microsoft/react-native-code-push/pull/1332

Please let me know if you have any questions.

**Comment by GregoryCollett** [comment]
I somehow missed that. 

Thanks for your help!
