### ISSUE TITLE
appcenter build ios only has production

### ISSUE THREAD

**Issue by Jazk-Z** [Microsoft/react-native-code-push#1376]
I read this guide  [https://docs.microsoft.com/en-us/appcenter/build/react-native/ios/](url)
I want to build in APPcenter. According to the above document, how to distinguish the environment? Need to pass a script or an environment variable? ? ? Very confused

**Comment by NickToropov** [comment]
Hi @Jazk-Z! to setup environment variables and build scripts please see these docs: 
- [https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/)
- [https://docs.microsoft.com/en-us/appcenter/build/custom/variables/](https://docs.microsoft.com/en-us/appcenter/build/custom/variables/) 

Please let me know if it was helpful or you have any other questions.

**Comment by NickToropov** [comment]
Hey!
We haven’t heard from you in a while, so I am going to go ahead and close this issue. If you still have any questions, you can reopen this issue; or if you prefer you can create a new one.
