### ISSUE TITLE
linker command failed with exit code 1 

### ISSUE THREAD

**Issue by sidhusubhash** [Microsoft/react-native-code-push#1377]
duplicate symbol _zipOpenNewFileInZip3_64 in:
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/libCodePush.a(zip.o)
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/SSZipArchive/libSSZipArchive.a(zip.o)
duplicate symbol _zipOpen3_64 in:
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/libCodePush.a(zip.o)
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/SSZipArchive/libSSZipArchive.a(zip.o)
duplicate symbol _zipOpenNewFileInZip2_64 in:
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/libCodePush.a(zip.o)
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/SSZipArchive/libSSZipArchive.a(zip.o)
duplicate symbol _zipOpen2_64 in:
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/libCodePush.a(zip.o)
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/SSZipArchive/libSSZipArchive.a(zip.o)
duplicate symbol _zipOpenNewFileInZip3 in:
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/libCodePush.a(zip.o)
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/SSZipArchive/libSSZipArchive.a(zip.o)
duplicate symbol _zipOpen3 in:
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/libCodePush.a(zip.o)
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/SSZipArchive/libSSZipArchive.a(zip.o)
duplicate symbol _zipOpenNewFileInZip2 in:
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/libCodePush.a(zip.o)
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/SSZipArchive/libSSZipArchive.a(zip.o)
duplicate symbol _zipOpen2 in:
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/libCodePush.a(zip.o)
    /Users/commutatus-1/Library/Developer/Xcode/DerivedData/dvdApp-ehmnrlsesyixbihiukjxoiomsalw/Build/Products/Debug-iphonesimulator/SSZipArchive/libSSZipArchive.a(zip.o)
ld: 252 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sidhusubhash** [comment]
after integrating code push in to my project, I am getting this error while building.

**Comment by sidhusubhash** [comment]
hi @alexandergoncharov 
"react-native": "0.49.3", 
"react-native-code-push": "^5.3.5",

after pod install,  build fails with linker error

**Comment by alexandergoncharov** [comment]
If you use pod install you don't have to use `link` command. And in the other side if you use `link` command you don't have to use cocoaPods. So, you should use only one of this approaches.

Please let me know if it was helpful you have any questions.

**Comment by sidhusubhash** [comment]
thank you, anyways its  fixed.

**Comment by alexandergoncharov** [comment]
Good news =) 
Thanks for keeping us in touch!

**Comment by Balanced02** [comment]
@sidhusubhash Please can you share how you fixed it? I'm having same error here after adding `react-native-code-push` Thanks.

**Comment by Aleksion** [comment]
@abodalevsky - 

This happened to me when I had to do a pod update for another dependency. Any ideas as to how to resolve this?

**Comment by keung7252** [comment]
still not working after Manual installation

**Comment by AceSpadeAble** [comment]
We're facing the same issue. We are stuck for 3 days already trying to make codepush work :/

**Comment by andrewhartwig** [comment]
Same here, anybody know what's up?

**Comment by gustavo-franco-iw** [comment]
+1

**Comment by master96** [comment]
+1 any help ?? 

tried following solution didnt work thought : 

https://github.com/Microsoft/react-native-code-push/issues/241#issuecomment-260898702

pod 'CodePush', :path => '../node_modules/react-native-code-push',subspecs: ['Core']

above line throws error

CocoaPods could not find compatible versions for pod "CodePush/Core":

**Comment by pedrosimao** [comment]
@master96 Same here! Did you find a solution?

**Comment by master96** [comment]
> @master96 Same here! Did you find a solution?

Hi @pedrosimao ,
I actually ended up manually removing reference to libSSZipArchive from react-native-code-push folder. That worked
