### ISSUE TITLE
Podspec dependencies causing duplicate symbol errors

### ISSUE THREAD

**Issue by dkadlecek** [Microsoft/react-native-code-push#1378]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Update to v5.4.1 ("react-native-code-push": "^5.4.1")
2. run pod install
3. let the errors ensue

### Expected Behavior
Errorless build via react-native run-ios or XCode build

### Actual Behavior
pod sub-dependencies cause duplicate symbol build errors that took a while to sort, and caused grey hair, as i didn't want to have to mess with the .CodePush.podspec to resolve; commenting out these lines facilitated a correct build:

#  s.dependency 'SSZipArchive', '~> 2.1'
#  s.dependency 'JWT', '~> 3.0.0-beta.7'
#  s.dependency 'Base64', '~> 1.1'

  STACK TRACE AND/OR SCREENSHOTS
Well, I hacked around by removing the dependencies from the podspec to resolve, but was getting duplicate symbols errors from these dependencies.

### Reproducible Demo
N/A

### Environment
Here's my podfile (relevant stuff):
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'BatchedBridge', # Required For React Native 0.45.0+
  'Core',
  ]
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

* react-native-code-push version: 5.4.1
* react-native version: 0.53.3
* iOS/Android/Windows version: 9+
* Does this reproduce on a debug build or release build? Yup
* Does this reproduce on a simulator, or only on a physical device? Yup

I am a pretty senior developer and I went through a lot of pain today to sort out the root of the issue. This was a project that I hadn't worked on for a few months that broke when I updated CodePush and Firebase.  I am still not sure what exactly changed to break this, but I did notice CodePush changed the podspec file and dependencies. I am starting to dig into where the duplicate references are defined, but I don't have the time to spend on this, and it seems like a poor implementation of an upgrade by MS/CodePush team. There are a lot of moving parts with RN, and I don't think this update was tested adequately.

**Comment by NickToropov** [comment]
Hi @dkadlecek we're sorry you've faced this issue. Please could you provide us with some more details: 
- what mechanisms was use to integrate CodePush plugin? (take a look at [this doc](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios))
- what exactly steps was used for updating plugin
It would be great if you could create a basic demo app that reproduces the issue.

**Comment by NickToropov** [comment]
I tried to reproduce the issue but with no success. I've performed the following steps:
1. create a basic RN app: `react-native init Issue1378 --version=0.53.3`
2. added CodePush plugin: `yarn add react-native-code-push@5.2.2` and linked it: `react-native link react-native-code-push`
3. created in `ios` folder Podfile from [here](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---cocoapods)
4. ran `pod install` in `ios` directory
5. opened generated Issue1378.xcworkspace in XCode and built it. Result - success
6. updated CodePush plugin: `yarn add react-native-code-push@latest` (in project root directory) and linked it: `react-native link react-native-code-push`
7. closed XCode and cleared `~/Library/Developer/Xcode/DerivedData` directory
8. deintegrated pods: `pod deintegrate` and install it again `pod install` (in `ios` directory)
9. opened Issue1378.xcworkspace in XCode and built it. Result - success.

Please try to follow my steps and check if your build is successful. (if I missed some steps/details please specify them)

**Comment by NickToropov** [comment]
Hi @dkadlecek! I've prepared a demo app
[Issue1378.zip](https://github.com/Microsoft/react-native-code-push/files/2294206/Issue1378.zip). Take a look at it.
To setup do the following steps:
- unzip `Issue1378.zip` and go to unzipped folder
- execute `yarn`
- go to `ios` directory and execute `pod install`
- open generated Issue1378.xcworkspace in XCode and built it

_Note:_
If you have error `The name of the given podspec 'GLog' doesn't match the expected one 'glog'`
fix the Glog spec name in:
/Issue1378/node_modules/react-native/third-party-podspecs/GLog.podspec
`spec.name = 'glog'`
and in
/Issue1378/node_modules/react-native/third-party-podspecs/Folly.podspec
`spec.dependency 'glog'`

**Comment by dkadlecek** [comment]
OK, I dug into this and thought about it a bit deeper today. The problem is that another framework, not included via CocoaPods (but via ‘Link Frameworks and Libraries) is also including these dependencies, hence causing the duplicate symbol errors:
'SSZipArchive'
'JWT'
'Base64'
The problem is that is is very difficult to isolate the framework that is already including these dependencies. If I can track it down, I can (hopefully) move into my Podfile, if that is supported.

I’ve seen some chatter about adding a feature to Cocoapods to remove/disable subspecs, but nothing is implemented yet.

For now, I am going to patch the podspec file. If you can think of a better solution I’m all ears.

**Comment by NickToropov** [comment]
Hey! How is your progress? Is the issue solved or do you have any other questions?

**Comment by dkadlecek** [comment]
I think I have found the answer in the CodePush documentation (https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#plugin-installation-ios---cocoapods <https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#plugin-installation-ios---cocoapods> ):

CodePush depends on an internal copy of the SSZipArchive library, so if your project already includes it (either directly or via a transitive dependency), then you can install a version of CodePush which excludes it by depending specifically on the Core subspec:
Ruby

Copy
pod 'CodePush', :path => '../node_modules/react-native-code-push', :subspecs => ['Core']
Note
The above paths needs to be relative to your app's Podfile, so adjust it as nec cessary.*

**Comment by dkadlecek** [comment]
Strike my previous email. I get this error:

[!] CocoaPods could not find compatible versions for pod "CodePush/Core":
  In Podfile:
    CodePush/Core (from `../node_modules/react-native-code-push`)

None of your spec sources contain a spec satisfying the dependency: `CodePush/Core (from `../node_modules/react-native-code-push`)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Please fix the podspec/Pod to support the documentation.


d

**Comment by NickToropov** [comment]
Hi @dkadlecek, the docs are outdated. Will fix them soon. Use manual in this repository: https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md

**Comment by alexandergoncharov** [comment]
Hi @dkadlecek ,

ms docs already update: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#plugin-installation-ios---cocoapods

I'm going to close this issue for now as it was resolved.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
