### ISSUE TITLE
Unable to run debug mode after implementing Multi-Deployment Testing

### ISSUE THREAD

**Issue by mattcolman** [Microsoft/react-native-code-push#1380]
Basically reopening an old issue that I think still exists, or the answer wasn't entirely clear how to fix it. (https://github.com/Microsoft/react-native-code-push/issues/474)

The error occurs after implementing Multi-Deployment Testing and then running the app in debug mode.
`[CodePush] 400，An update check must include a valid deployment key - please check that your app has been configured correctly. To view available deployment keys, run 'code-push deployment ls <appName> -k'.`

I'm experiencing this issue after updating packages from:
```
"react-native": "0.42.3",
"react-native-code-push": "1.17.4-beta",
```
to
```
"react-native": "0.56.0",
"react-native-code-push": "5.4.1",
```
When running Staging or Release build it works fine, but running a Debug build throws an error. I want to run Debug builds so I don't have to codepush new code for every change while I'm testing.

I followed the [Multi-Deployment Testing](https://github.com/Microsoft/react-native-code-push#ios) link so I have not defined a deployment key for DEBUG.
I also have this code to read the jsCodeLocation from the local bundle and not codepush.

#ifdef DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif

My codepush implementation is:
export default codePush({ checkFrequency: codePush.CheckFrequency.ON_APP_RESUME })(App);

### Steps to Reproduce
1. Setup with [Multi-Deployment Testing](https://github.com/Microsoft/react-native-code-push#ios) 
2. Run a debug build
3. Notice error

### Expected Behavior
Expect a debug build to run the local js bundle and see changes without having to code push.

### Actual Behavior
`[CodePush] 400，An update check must include a valid deployment key - please check that your app has been configured correctly. To view available deployment keys, run 'code-push deployment ls <appName> -k'.`

### Environment

"react-native": "0.56.0",
"react-native-code-push": "5.4.1",
Debug build
Simulator or physical device.

**Comment by NickToropov** [comment]
Hi @mattcolman! Did you specify deployment key for Debug configuration? If no then it's expected behavior. Checking for updated (which is in the specified code:
`export default codePush({ checkFrequency: codePush.CheckFrequency.ON_APP_RESUME })(App);`) is performed regardless of whether it is Debug or Release or Staging.
If it's critical for you to avoid such error you can one of the following approaches:
- comment code `export default codePush({ checkFrequency: codePush.CheckFrequency.ON_APP_RESUME })(App);`
- create Debug deployment and specified key for Debug configuration

**Comment by mattcolman** [comment]
Yep, I was experiencing my app freezing in debug mode only and assume it was due to this error, but it was something else. I understand now this error is the expected behaviour. Thanks!
