### ISSUE TITLE
How to close all  update?

### ISSUE THREAD

**Issue by Jeijie** [Microsoft/react-native-code-push#1381]
how to close  or delete all update i publiced?when I publiced update more tiem ,I have to rollback more time,It's inconvenient to operate.I want to close  or delete all update I publied,but I did't find the command,please help

### Steps to Reproduce
1.public the first update
2. public the second update
3.rollback

### Expected Behavior
app is up to date

### Actual Behavior

app checking the first update

### Environment

System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 29.73 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by alexandergoncharov** [comment]
I think that it is mean that question was answered.

I'm going to close this issue for now but please feel free to reopen it if you have any questions.
