### ISSUE TITLE
React/RCTEventEmitter.h file not found

### ISSUE THREAD

**Issue by antonsivogrivov** [Microsoft/react-native-code-push#1383]
### Steps to Reproduce
1. Duplicate staging schema from main schema in XCode
2. Product -> Archive

### Expected Behavior

Product -> Archive will succeed

### Actual Behavior

React/RCTEventEmitter.h file not found in CodePush.h

### Environment

* react-native-code-push version: 5.3.4
* react-native version: 0.53.3
* This reproduce only in release build (Product -> Archive for staging schema), and in debug mode it works well
* Don't use CocoaPods in my project and CodePush was installed manually

As a result I can't make release for my staging env :(

**Comment by alexandergoncharov** [comment]
Hi @antonsivogrivov ,
Thanks for reporting!

Could you please share your issue schema?

**Comment by antonsivogrivov** [comment]
[TurtleChat-staging.xcscheme.zip](https://github.com/Microsoft/react-native-code-push/files/2302325/TurtleChat-staging.xcscheme.zip)

**Comment by NickToropov** [comment]
Hi @antonsivogrivov, please take a loot at [this doc](https://github.com/Microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md) and check if you set `Per-configuration Build Products Path` as specified in manual.

**Comment by NickToropov** [comment]
@antonsivogrivov glad to hear that was able to help you!

**Comment by NickToropov** [comment]
@antonsivogrivov glad to hear that we were able to help you!
