### ISSUE TITLE
How to Refresh Version from package.json After CodePush Reload

### ISSUE THREAD

**Issue by gchallen** [Microsoft/react-native-code-push#1389]
### Steps to Reproduce
1. Bump the version in `package.json`
2. Push an update via CodePush
3. Via the version from an app settings screen
4. See the old version until the app is force killed and restarted

### Expected Behavior
I expected to see the new version

### Actual Behavior
I see the old version until the app is force killed

This is more of a question than a bug report. I have an app status page that I want to use to view both the app version and the bundle version, which I pull out of the `package.json` file via an import when that part of my Redux container is loaded. I was hoping to be able to use this to differentiate between base versions (one's distributed via the app stores) and update versions.

What I'm seeing is that after an update the bundle version doesn't change. However, if I force kill the app I see the correct (updated) bundle version. I would have assumed that CodePush reloaded the entire JavaScript bundle, but I guess it's more clever than that (because if it did this would get updated). I suppose I can try to put this into something that gets triggered when the app is reloaded, but does anyone know "the right way" to do this?

Thanks in advance.

**Comment by alexandergoncharov** [comment]
Hi @gchallen,
Thanks for reporting!

Yeah, you right. If I understand your issue correct you would like to check version of update. I think that you should check label of release or just put information about version in description of release.
`Label` is a serial number of release for deployment. Just run `appcenter codepush deployment history -a <userName>/<appName> <deployment>` and check `label` column.
For putting some info in description field just use `--description` field during release.

For check this info in code you can use `localPackage` for getting metadata of release and check necessary field. For more info please check docs: https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#localpackage

Please let me know if it was helpful or you have any questions. 

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @gchallen ,

I'm going to close this issue as I haven't heard from you in a while unfortunately.
Also, I hope that you questions was answered =)

Please feel free to reopen it if you have any questions.

Thanks,
Alexander
