### ISSUE TITLE
Can we initiate sync on the Native (android/iOS)?

### ISSUE THREAD

**Issue by krunalsshah** [Microsoft/react-native-code-push#1391]
I do not see any public method to initiate the `CodePush` sync on the Native side. 

Wondering If I am missing anything. The reason I ask this question, is to work on a situation, where I want to have the bundle downloaded on HomeScreen(Native), so that when the user clicks on the button that loads the react native component, the native app already references the newly installed bundle.

@NickToropov @alexandergoncharov 

I'll continue looking into source, to find any obvious answer, why `sync` is only initiated on the client side. One of which could be `code-dup` , as If i see the `js` implementation, it sync's the state.

**Comment by NickToropov** [comment]
Hi @krunalsshah! Initially the development direction was aimed to have most part of logic in js side and use native side only in case we cannot do somehting without it. That’s why we have `checkForUpdates` and `sync` in js code. Going further we aimed to move to the point when we would like to support [brownfield apps](https://github.com/Microsoft/code-push/issues/423) so I believe sooner or later that will be merged and supported completely. As for now please take a look at [brownfield-apps-dev](https://github.com/Microsoft/react-native-code-push/tree/brownfield-apps-dev) branch (for example [here](https://github.com/Microsoft/react-native-code-push/blob/2c77292a1d7a8df8eb10a1b7c17b211eb5dbc076/android/app/src/main/java/com/microsoft/codepush/common/core/CodePushBaseCore.java#L536)). So you can implement you own `sync` based on the code in brownfield-apps-dev branch.

Please let me know if it was helpful or you have any other questions.

**Comment by NickToropov** [comment]
Hi @krunalsshah, I'll close the issue as it seems to be resolved, feel free to reach us if you need any help with code-push.
