### ISSUE TITLE
ON_NEXT_SUSPEND   rollback

### ISSUE THREAD

**Issue by betsun2017** [Microsoft/react-native-code-push#1394]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.create react-native project and add react-native-code-push
2. modfiy AppDelegate.m 
`jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];` to 
`jsCodeLocation = [CodePush bundleURL];`
3.Connect to iphone run
4.code-push push a update
5.After the APP receives the update，Press Home.
6.wait > minimumBackgroundDuration ,open app 

### Expected Behavior
Normal update

### Actual Behavior
rollback update.
My own debugging results：
Both applicationWillResignActive and  applicationWillEnterForeground execute.
loadBundle two. notifyApplicationReady not call. so rollback.
my codepush options
```
codePushOptions = {
	checkFrequency: CodePush.CheckFrequency.MANUAL
};
 CodePush.sync({
				installMode: CodePush.InstallMode.ON_NEXT_SUSPEND,
				mandatoryInstallMode: CodePush.InstallMode.ON_NEXT_SUSPEND,
				minimumBackgroundDuration: 60,

			},
			this.codePushStatusDidChange.bind(this),
			this.codePushDownloadDidProgress.bind(this)
		);
```

### Environment

* react-native-code-push version: 5.2.2
* react-native version:0.50.3
* iOS/Android/Windows version:ios11.2.6
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device?physical device

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @betsun2017 ,
Thanks for reporting!

Could you please fill issue template with more details? It can help us to understand issue faster.
https://github.com/Microsoft/react-native-code-push/blob/master/.github/ISSUE_TEMPLATE.md

Thanks,
Alexander

**Comment by NickToropov** [comment]
Hi @betsun2017, do you have code something like 
```let codePushOptions = { checkFrequency: CodePush.CheckFrequency.MANUAL };
App = CodePush(codePushOptions)(App);

export default App;```

**Comment by betsun2017** [comment]
@NickToropov yes ,I have.
demo https://github.com/betsun2017/testpush  
my ios version is 11.2.6

**Comment by NickToropov** [comment]
Is this issue reproduced stably? Also please could you share logs from XCode(tagged with `[CodePush]`)?

**Comment by alexandergoncharov** [comment]
Hi @betsun2017 ,

Thanks for demo project.  I reproduce your issue. Also I tested `ON_NEXT_SUSPEND` on other dummy project, no issue found.
I think that you issue that you use `AppState` for calling sync method.

Please let me know if it was helpful or you have any questions.

**Comment by NickToropov** [comment]
Hey! 
We haven’t heard from you in a while, so I am going to go ahead and close this issue. Should you still have any questions, you can reopen the issue or if you prefer you can create a new one. Please don’t hesitate to contact us again.
