### ISSUE TITLE
Pushed changes to Staging deployment, but the changes aren't reflected in the signed apk.

### ISSUE THREAD

**Issue by shubhnik** [Microsoft/react-native-code-push#1395]
I created a signed apk. After that, I pushed some changes to the Staging deployment on CodePush.

### Expected Behavior
What you expected to happen?
I was expecting the changes to reflect in the signed apk.

### Actual Behavior
What actually happens?
The changes aren't reflected in the signed apk.
 ### Commands I followed:
* `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ --sourcemap-output android/app/src/main/assets/index.android.bundle.map`

* `appcenter codepush release -a Niyo/Assistant -t 1.0 -c android/app/src/main/assets/index.android.bundle -d Staging`

### Environment

* react-native-code-push version: `^5.4.2`
* react-native version: `0.55.4`
* iOS/Android/Windows version: Android version `8.1.0`
* Does this reproduce on a debug build or release build? `release build` (signed apk)
* Does this reproduce on a simulator, or only on a physical device? Both

Please let me know if further information is needed.

P.S The CodePush dashboard is showing downloads and install numbers.

**Comment by alexandergoncharov** [comment]
Hi @shubhnik ,
Thanks for reporting!

This is strange issue. Could you please share logs during update?

**Comment by shubhnik** [comment]
@alexandergoncharov CodePush does logs out that update is downloaded and will be installed during the next app session, but couldn't see the changes. Or are you looking for some specific logs?

**Comment by alexandergoncharov** [comment]
@shubhnik , Got it. It is strange behavior. Yeah, CodePush logs marked with `[CodePush]` tag. Could you please also check logs after reloading app? Possible there can be some Error or something else.
Could you please also provide dummy project with detailed repro steps? It can help us reproduce issue.

**Comment by shubhnik** [comment]
@alexandergoncharov I solved the issue, actually there was a problem in native linking. Thanks for your help :+1:

**Comment by alexandergoncharov** [comment]
Great! Thanks for keeping us in touch.

So, as issue was resolved I'm going to close this issue. Please feel free to reopen it if you have any questions.

Thanks,
Alexander
