### ISSUE TITLE
String resource ID #0x0 at CodePush.java line 155 in com.microsoft.codepush.react.CodePush.getBinaryResourcesModifiedTime

### ISSUE THREAD

**Issue by thecachedbyte** [Microsoft/react-native-code-push#1397]
"react-native": "^0.49.3",
 "react-native-code-push": "5.3.2"

We are getting this weird crash. We have a complex hybrid application where few screens are of native and a few screens are on react native. We use [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) for routing, which internally handles landing/rendering of different-different screens based on initial props. Something can be wrong with our implementation.

We mount(runApplication) same component(which gets registered like [this](https://facebook.github.io/react-native/docs/appregistry#registercomponent)) on different activities. And multiple react native activities can be present at the same time in memory (routing stack). Can this be an issue?

Please guide us to identify this issue. What can be possibly wrong?

**Comment by NickToropov** [comment]
Hi @thecachedbyte!
Is `<your_project>/node_modules/react-native-code-push/android/codepush.gradle` executed during your build process?

**Comment by NickToropov** [comment]
Hey! 
We haven’t heard from you in a while, so I am going to go ahead and close this ticket. Should you still have any questions, you can reopen the ticket; or if you prefer you can create a new one.
Thanks for using CodePush!
