### ISSUE TITLE
no packageHash in android

### ISSUE THREAD

**Issue by nextdooroldwang** [Microsoft/react-native-code-push#1398]
"react": "16.2.0",
"react-native": "0.53.0",
"react-native-code-push": "^5.4.2",

Android

syncStatus === CodePush.SyncStatus.UNKNOWN_ERROR

![image](https://user-images.githubusercontent.com/18671240/45205824-ed9b4200-b2b5-11e8-959e-7e81d5873de0.png)

**Comment by NickToropov** [comment]
Hi @nextdooroldwang! 
Yes, `updateCheck` request doesn't contains packageHash param for Android. See this [line](https://github.com/Microsoft/react-native-code-push/blob/82b3336adb0a0bc2168b81d91499b13df7ad585c/CodePush.js#L49) please.

**Comment by NickToropov** [comment]
Hey @nextdooroldwang! Was my answer helpful for you or do you have any other questions?

**Comment by NickToropov** [comment]
Hey! 
We haven’t heard from you in a while, so I am going to go ahead and close this issue. Should you still have any questions, you can reopen the issue or if you prefer you can create a new one.
