### ISSUE TITLE
Process 'command 'node'' finished with non-zero exit value 1。Error: ENOENT: no such file or directory, open 'E:\Work\PunchCard\code\Daka\android\app\build\intermediates\assets\debug/CodePushHash'

### ISSUE THREAD

**Issue by yueqch** [Microsoft/react-native-code-push#1401]
Process 'command 'node'' finished with non-zero exit value 1。

Error: ENOENT: no such file or directory, open 'E:\Work\PunchCard\code\Daka\android\app\build\intermediates\assets\debug/CodePushHash'

Project cannot run。Prompt the above two errors.

ide : android studio;
gradle-wrapper : gradle-4.6-all;
gradle plugin : com.android.tools.build:gradle:3.1.4

**Comment by NickToropov** [comment]
Hi @yueqch! I've just created a basic RN app with integrated CodePush plugin. Then I've updated gradle-wrapper version to 4.6 and built the app. Result: `BUILD SUCCESSFUL`. Please take a look at attached [demo](https://github.com/Microsoft/react-native-code-push/files/2371191/Issue1401.zip) and change it so that your issue could be reproduced there and share with us. We'll try so figure out what is going wrong.

Note: please execute `yarn` command in the root of unzipped app before start to build

**Comment by NickToropov** [comment]
Hey! 
We haven’t heard from you in a while, so I am going to go ahead and close this issue. Should you still have any questions, you can reopen the issue or if you prefer you can create a new one.

**Comment by jannoteelem** [comment]
I also experienced the same issue. Workaround is to create the folder manually.

**Comment by pehagg** [comment]
We're experiencing this too. Got it after upgrading to Gradle 4.6. Updating code push to latest version didn't help.

**Comment by yuri-kulikov** [comment]
Hi @pehagg,

It's actually related to **react-native**, you can find the answer [here](https://github.com/Microsoft/react-native-code-push/issues/1427#issuecomment-430913598).
I hope it will help you. Otherwise feel free to ask any questions!

**Comment by pehagg** [comment]
@yuri-kulikov, thanks a bunch!

**Comment by joshuapinter** [comment]
For those wondering, the real answer is to upgrade to `react-native` version `0.57.2` or greater.

**Comment by gorojou** [comment]
Hello guys, i have the same error, i tried what i see here and i have those versions, but still the same
react-native-cli: 2.0.1
react-native: 0.57.3

Any help? Thank you

**Comment by yusuf987** [comment]
> I also experienced the same issue. Workaround is to create the folder manually.

what folder ???
