### ISSUE TITLE
[RN 0.57] Error: searchPaths.filter is not a function... on unlinking

### ISSUE THREAD

**Issue by fungilation** [Microsoft/react-native-code-push#1402]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Run `react-native unlink react-native-code-push`
2. Error below

### Expected Behavior
`unlink` cleanly

### Actual Behavior
What actually happens?
```
$ react-native unlink react-native-code-push
rnpm-install info Unlinking react-native-code-push ios dependency 
rnpm-install ERR! It seems something went wrong while unlinking. Error: searchPaths.filter is not a function 

searchPaths.filter is not a function

TypeError: searchPaths.filter is not a function
    at pbxProject.removeFromLibrarySearchPaths (/Users/garyfung/Documents/code/WonderSwipe/node_modules/react-native/node_modules/xcode/lib/pbxProject.js:1161:39)
    at removeFromStaticLibraries (/Users/garyfung/Documents/code/WonderSwipe/node_modules/react-native/local-cli/link/ios/removeFromStaticLibraries.js:26:11)
    at getTargets.forEach.target (/Users/garyfung/Documents/code/WonderSwipe/node_modules/react-native/local-cli/link/ios/unregisterNativeModule.js:52:5)
    at Array.forEach (<anonymous>)
    at unregisterNativeModule (/Users/garyfung/Documents/code/WonderSwipe/node_modules/react-native/local-cli/link/ios/unregisterNativeModule.js:51:33)
    at Object.unregisterNativeModule [as unregister] (/Users/garyfung/Documents/code/WonderSwipe/node_modules/react-native/local-cli/link/ios/common/unregisterNativeModule.js:19:5)
    at Object.keys.forEach.platform (/Users/garyfung/Documents/code/WonderSwipe/node_modules/react-native/local-cli/link/unlink.js:57:16)
    at Array.forEach (<anonymous>)
    at unlinkDependency (/Users/garyfung/Documents/code/WonderSwipe/node_modules/react-native/local-cli/link/unlink.js:31:32)
    at tasks (/Users/garyfung/Documents/code/WonderSwipe/node_modules/react-native/local-cli/link/unlink.js:115:3)

```

### Environment

* react-native-code-push version: 5.4.2
* react-native version: below
* iOS/Android/Windows version: below
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? Neither, cli error before building/running

```
$ react-native info

  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      Memory: 160.72 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.1, 25.0.3, 26.0.1, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.0 => 0.57.0 
    npmGlobalPackages:
      eslint-plugin-react-native: 3.3.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

As an aside, I ran `react-native unlink` and re-`link` as I usually do to make sure packages and upgraded. Is this not wanted with `react-native-code-push`?

**Comment by NickToropov** [comment]
Hi @fungilation! I think that specified issue should be fixed by this [commit](https://github.com/apache/cordova-node-xcode/commit/be8498daf8159033c884c03622eead34a3ea1e90) a year ago. Also I've just created a basic RN app with integrated CodePush plugin and tried to `unlink`:
```
➜  Issue1402 react-native unlink react-native-code-push
rnpm-install info Unlinking react-native-code-push ios dependency
rnpm-install info Platform 'ios' module undefined has been successfully unlinked
rnpm-install info Unlinking react-native-code-push android dependency
rnpm-install info Platform 'android' module undefined has been successfully unlinked
```
Could you provide us with more info about your project and which dependencies do you have? It would be very helpful if you could prepare a demo app that reproduce the issue or specify exactly steps to reproduce it.

**Comment by NickToropov** [comment]
Hey! 
We haven’t heard from you in a while, so I am going to go ahead and close this issue. Should you still have any questions, you can reopen the issue or if you prefer you can create a new one.

**Comment by TRIPTI-JAIN** [comment]
I change the follow bit of code in the /node_modules/xcode/lib/pbxProject.js

if (searchPaths) {
            var matches = searchPaths.filter(function(p) {
                return p.indexOf(new_path) > -1;
            });
            matches.forEach(function(m) {
                var idx = searchPaths.indexOf(m);
                searchPaths.splice(idx, 1);
            });
        }
to

if (searchPaths) {
            if(typeof searchPaths === 'string'){
                searchPaths = [searchPaths]
            }
            var matches = searchPaths.filter(function(p) {
                return p.indexOf(new_path) > -1;
            });
            matches.forEach(function(m) {
                var idx = searchPaths.indexOf(m);
                searchPaths.splice(idx, 1);
            });
        }
and it seemed to have fixed the issue as well.
