### ISSUE TITLE
Native api to directly invoke new update check and new install?

### ISSUE THREAD

**Issue by thecachedbyte** [Microsoft/react-native-code-push#1406]
Is there an API or a way to control/trigger new update check and install new update from native code (Java for Android and Swift/Objective C for IOS). We have a hybrid app where few screens are in react native and a few screens are in native. We want to have a better update adoption but at the same time, we don't want to break the user flow. So we need to implement custom invocation for new update check and new install from native code. So that when user will not be in react native flow we can safely restart react native application.

Current implementation

export default codePush({checkFrequency: codePush.CheckFrequency.ON_APP_RESUME, installMode: codePush.InstallMode.ON_NEXT_SUSPEND, minimumBackgroundDuration: 600})(App);

**Comment by NickToropov** [comment]
Hi @thecachedbyte! We have a similar question asked recently. Please take a look at it: [issue#1391](https://github.com/Microsoft/react-native-code-push/issues/1391#issuecomment-416923507).
Let me know if it was helpful or you have any other questions.

**Comment by NickToropov** [comment]
Hey! I'll close the issue as it seems to be resolved, feel free to reach us if you need any help with code-push.
