### ISSUE TITLE
RNN v2 + CodePush + config

### ISSUE THREAD

**Issue by dungnguyen10989** [Microsoft/react-native-code-push#1409]
Anyone have had handled react-native-navigation[v2] with react-native-code-push please provide me a sample code, I've config many times but it's not working. If thei are combine with react-native-config, that is great. Tks all !

**Comment by alexandergoncharov** [comment]
Hi @dungnguyen10989 ,
Thanks for reporting!

Could you please clarify what is your difficulty and issue?
I mean like your steps and actual behavior.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @dungnguyen10989 ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
