### ISSUE TITLE
React native unbundling with --indexed-unbundle

### ISSUE THREAD

**Issue by thecachedbyte** [Microsoft/react-native-code-push#1410]
As I can clearly see unbundling is not supported by code push right now #778 #1102 

Just wondering if code push will be able to support unbundling with --indexed-unbundle?

Just for reference
--indexed-unbundle is an option provided by react-native unbundle to create a single indexed file instead of multiple bundles. [Check here](https://facebook.github.io/react-native/docs/0.49/performance#enable-unbundling)

Since "react native bundle" and "react native unbundle with --indexed-unbundle" is creating a single bundle then ideally it should work.

Currently, we are getting an error (Could not get BatchedBridge, make sure your bundle is packaged correctly). We are still investigating if its a core react native issue or code push unbundle issue or a miss at our end.

Till then I just want to validate this thought of code push supporting unbundling with --indexed-unbundle. Please let me know if my assumption holds true or not.

Thanks in advance.

Versions
React native - ^0.49.3
React native code push - 5.3.2

**Comment by kelset** [comment]
Hey @sergey-akhalkov @ruslan-bikkinin, sorry to bother you for this issue, but it seems that in the past two issues related to this there have not been many steps forward (#1102, #778) to supporting it and the plan from the RN Core is to push for this feature to be "on by default" in a future release - you can read the [details here](https://github.com/react-native-community/discussions-and-proposals/blob/master/core-meetings/2018-09-metro-meeting.md).

**Comment by lithin** [comment]
👍 for this, unbundling has significant performance increase on app load and this stops us from using code push on android at the moment

**Comment by Zakeelm** [comment]
As of now, we don't have plans to support unbundle, but we can definitely see the value in it and why it could be a great addition to the CodePush feature set. Our backlog is pretty filled at the moment, but this is something the team is going to look into. I'm going to close this for now, but will revisit and update this after discussion/investigation with the team.

**Comment by NickToropov** [comment]
Hi all! I've just tested unbundling with CodePush and it seems that single unbundled indexed file works like ordinary RN bundle on both iOS and Android.

@thecachedbyte you mentioned that now you are blocked by `Could not get BatchedBridge` error. Could you provide more details about that issue as I haven't faced with it?(perhaps it would be better to start new thread)

@lithin did you get performance increasing by using default unbundling or with option `--indexed-unbundle`? The question is if it's enough for you to have a single unbundled indexed file to get performance improvements? During my investigation I've faced with crash if I try to run multiple files  unbundled package from file system not from apk assets.

**Comment by lithin** [comment]
@NickToropov Unfortunately we never got it working, and from what I've gathered here and on Twitter, I . understood that it's not actually possible to do this at the moment. If you got it working though, it'd be great to see an example repo?

**Comment by NickToropov** [comment]
Hi guys! I may have been a bit hasty. Yesterday I've faced with `Could not get BatchedBridge` error on Android when tried to prepare demo app. The error occurs even on pure RN application with `--indexed-ram-bundle`(replacement for `--indexed-unbundle`) option. So we have to wait until it's fixed in RN or a workaround is suggested. Here is a link to RN issue: https://github.com/facebook/react-native/issues/21282

**Comment by vivek-walecha-657** [comment]
Thanx for update.

**Comment by vivek-walecha-657** [comment]
@lithin hi you dint get any issue like this?
