### ISSUE TITLE
Core Bluetooth CentralManager state is unsupported after a code push update

### ISSUE THREAD

**Issue by izarov** [Microsoft/react-native-code-push#1411]
When the app launches on the phone bluetooth state becomes poweredOn as expected. However, after a code push update and a reload of the JS part bluetooth state is unsupported.

### Steps to Reproduce
1.  Start from a basic app which loads an iOS module that instantiates CBCentralManager with a delegate that just prints state updates.
2. Publish a code push update for the app.
3. After the app launches state becomes poweredOn, after the javascript update state is and remains unsupported.
4. Close app and reopen - state is back to poweredOn.

This can also be reproduced using a dev build on a physical devices by reloading from the dev tools menu, so it might be something to do with how React Native reinitialises. It's a bigger issue for code push however - using code push in production means that bluetooth is disabled in updated apps until apps are restarted..

### Expected Behavior
Bluetooth state changes back to poweredOn after code push update (https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerstate/poweredon)

### Actual Behavior
Bluetooth state remains unsupported after update.

### Environment
* react-native-code-push version: 5.4.0
* react-native version: 0.55.4
* iOS/Android/Windows version: iOS 11 and 12
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Physical only as simulator does not support bluetooth.

**Comment by alexandergoncharov** [comment]
Hi @izarov,
Thanks for reporting!

Is it possible to provide test project with configured Bluetooth?

**Comment by alexandergoncharov** [comment]
Hi @izarov ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if your have any questions or you provide dummy project.

Thanks,
Alexander
