### ISSUE TITLE
CodePush asking for deployment keys on CI environments

### ISSUE THREAD

**Issue by carloscuesta** [Microsoft/react-native-code-push#1415]
### Steps to Reproduce

1. `react-native link`

### Expected Behavior

To not be asked on a CI machine, to enter deployment keys, since they are already provided.

### Actual Behavior

Asks for deployment keys.

![screen shot 2018-09-25 at 14 52 13](https://user-images.githubusercontent.com/7629661/46015445-9cbb8400-c0d2-11e8-81eb-dd6c62e8bb7b.png)

### Environment

* react-native-code-push version: 5.3.5
* react-native version: 0.55.4
* iOS/Android/Windows version: Not applies.
* Does this reproduce on a debug build or release build? Not applies.
* Does this reproduce on a simulator, or only on a physical device? Not applies.

**Comment by carloscuesta** [comment]
It could be sorted out easily, but I think the `link` functionality should handle this.

**Comment by carloscuesta** [comment]
Thanks @alexandergoncharov, taking a quick look at the code I think that's because 

At the `android/postlink.js` script you're not checking if the codePushDeploymentKey is already provided or not.

https://github.com/Microsoft/react-native-code-push/blob/aa3ae8e8e997891edb97a70587df6d0748da937f/scripts/postlink/android/postlink.js#L1-L95

Then it's always asking for it

**Comment by alexandergoncharov** [comment]
Hi @carloscuesta,
Sorry for this delay.

I implemented fix for this issue. Could you please test it?
https://github.com/Microsoft/react-native-code-push/pull/1538

**Comment by alexandergoncharov** [comment]
Hi @carloscuesta ,

Fix already released in new version: https://github.com/Microsoft/react-native-code-push/releases/tag/v5.5.3
So, I'm going to close this issue as it was fixed. Please feel free to reopen it if you have any questions.

Thanks,
Alexander
