### ISSUE TITLE
React Native 0.57 - Android : Circular dependency between tasks

### ISSUE THREAD

**Issue by MatthieuLemoine** [Microsoft/react-native-code-push#1418]
While building for Android, Gradle complains about a circular dependency in build tasks. 

`app:bundleDebugJsAndAssets -> :app:recordFilesBeforeBundleCommandDebug -> :app:mergeDebugResources -> :app:bundleDebugJsAndAssets`

This issue was already raised in #1368 which was closed without a proper solution as it requires to modify the node_modules (deleting https://github.com/Microsoft/react-native-code-push/blob/master/android/codepush.gradle#L101). Furthermore I'm not sure that removing this line is without consequences.

### Steps to Reproduce
1. yarn add react-native@0.57.1
2. yarn react-native run-android

### Expected Behavior
✅ Should build and run on device/simulator  

### Actual Behavior
❌ Android build fails
```
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:app:bundleDebugJsAndAssets
\--- :app:recordFilesBeforeBundleCommandDebug
     \--- :app:mergeDebugResources
          \--- :app:bundleDebugJsAndAssets (*)
```

### Environment

* react-native-code-push version: 5.1.3
* react-native version: 0.57.1
* Android version: 27
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by NickToropov** [comment]
Hi @MatthieuLemoine! We had a pair of similar issues: https://github.com/Microsoft/react-native-code-push/issues/1368, https://github.com/Microsoft/react-native-code-push/issues/679. Could you try solutions suggested there? If they don't help please provide us with demo project that reproduce the issue. Currently we have no `Circular dependency` errors so the cause of the issue may be related to specific versions of gradle/gradle plugin or dependencies structure.

**Comment by MatthieuLemoine** [comment]
My bad I was still on code-push 5.1.3-beta

**Comment by joshuapinter** [comment]
Can confirm. Was also on `5.1.3-beta` and using React Native 0.57.2. Upgraded to `5.5.3` and the error went away. Thanks!
