### ISSUE TITLE
React Native Windows 0.57 not compliling due to minimum target version difference

### ISSUE THREAD

**Issue by jmcginty** [Microsoft/react-native-code-push#1421]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
Upgrade/Create a new project using ReactNativeWindows 0.57
Get compile error :

> Project ReactNative is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-arm64-aot. Project ReactNative supports: uap10.0.14393 (UAP,Version=v10.0.14393)	

### Expected Behavior
Compile project

### Environment

* react-native-code-push version: 5.4.2
* react-native version: 0.57.1
* iOS/Android/Windows version: Windows 10
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Can't get that far

**Comment by alexandergoncharov** [comment]
Hi @jmcginty,

Your PR already merged in Master. SO, I'm going to close this issue for now.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
