### ISSUE TITLE
CodePush downgraded app version back to binary version

### ISSUE THREAD

**Issue by trubi** [Microsoft/react-native-code-push#1423]
Hello,
we are experiencing weird issue where my only explanation is that something is wrong with code push. It could be also code push interacting with other components. 
First of all, we are using manual sync. Syncing is turned off and we are manually downloading update with `checkForUpdate` method. We are logging our app activity and what I see is that app was at version 1.22.15 (latest code push) and then for some reason from the same device I see 1.22.5 (app store binary). After about an hour it got updated again to 1.22.15 but without any logs indicating it would download latest version again (I could be wrong about these logs here but definitely not with downgrade and upgrade) which bring the idea that code push didn't find it's bundle at first and then after some time it did (What does code push use as a storage for downloaded JS bundles?).
We are also using redux-persist and the first log after downgrade is empty rehydrate, so it didn't find any previous state which was definitely there before (which could be somehow connected).

Do you have any idea how this could happen? Version are bellow, We are just in process of upgrading react native to 0.56.0 and code push 5.4.2 but anyway I need to make sure either we somehow fix this or new version fixes this.

I tried to provide as much information as possible. If you have any other questions I am more than happy to cooperate. Thanks!

### Steps to Reproduce
Unfortunately I don't have any steps to reproduce since it's happening randomly (happened already ~4 times with no common pattern)

### Expected Behavior
App will not downgrade itself.

### Actual Behavior
App downgraded to binary app store version.

### Reproducible Demo
No reproducible demo

### Environment

* react-native-code-push version: `5.3.2`
* react-native version: `0.51.0`
* iOS/Android/Windows version: `iOS 11.4.1`
* Does this reproduce on a debug build or release build? `release`
* Does this reproduce on a simulator, or only on a physical device? `physical device`

**Comment by NickToropov** [comment]
Hi @trubi! Yes, it's very weird issue. Here is a [link](https://github.com/Microsoft/react-native-code-push/blob/617949a52bc17c5db4be7385210dcf152ca18f63/ios/CodePush/CodePush.m#L139) to method that returns url(in local file system) from where bundle will be launched.
At the moment the only assumption is that something is wrong with CurrentPackage metadata so the code decides to use binary version. 
CodePush downloads and unpacks bundle in ` file:///var/mobile/Containers/Data/Application/{app_id}/Library/Application Support/CodePush/{package_hash}/CodePush/` directory. So if nothing is found here than binary version will be launched.

If you have any updates or repro steps/demo please share with us.

**Comment by NickToropov** [comment]
Hi @trubi! Do you have any updates/additional info on this issue?

**Comment by trubi** [comment]
Hey Nick, sorry I don't. I've been monitoring it, but since the last time, it looks it didn't happen again.

**Comment by NickToropov** [comment]
Glad to hear! So I'll close this issue for now. Please reopen it if you face it again.

**Comment by chhornponleu** [comment]
I have received several cases reported from users for the same issue. All of them are using Vivo phone. I am not sure if it is related to OS itself or CodePush.
