### ISSUE TITLE
[Android] - Wrong location for CodePushHash and index.android.bundle

### ISSUE THREAD

**Issue by ferrannp** [Microsoft/react-native-code-push#1430]
I have a `stagingRelease` configuration. It places `CodePushHash` and `index.android.bundle` into `build/generated/assets/react/stagingRelease`.

If I run it, then I'll get the following error:

```
[CodePush] Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.
```
 
What I need to do to make it work is copy **manually** those two files into `intermediates/merged_assets/stagingRelease/mergeStagingReleaseAssets/out`

Anything that I am missing? Some steps?

### Environment

* react-native-code-push version: 5.4.2
* react-native version: 0.57.x
* iOS/Android/Windows version: Android Studio 3.2.1, gradlePluginVersion 3.2.0 and gradle 4.6.
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

### Edit

Posible solution?

```gradle
project.ext.react = [
    entryFile: "app/index.js",
    jsBundleDirDebug: "${buildDir}/intermediates/merged_assets/debug/mergeDebugAssets/out",
    jsBundleDirRelease: "${buildDir}/intermediates/merged_assets/release/mergeReleaseAssets/out",
    jsBundleDirStagingRelease: "${buildDir}/intermediates/merged_assets/stagingRelease/mergeStagingReleaseAssets/out"
]
```

**Comment by alexandergoncharov** [comment]
Hi @ferrannp,
Thanks for reporting!

Could you please point setup approach? RNPM or manually? For more info please check this docs: https://github.com/srinuch1981/ReduxNavigation/blob/master/android/app/src/main/java/com/reduxnavigation/MainApplication.java#L36

Thanks,
Alexander

**Comment by ferrannp** [comment]
Hey @alexandergoncharov, manual set up when including it into an existing native app.

**Comment by yuri-kulikov** [comment]
Hi @ferrannp,
Can you specify which version of **react-native** you are using?  
As far as I know this issue was fixed in **react-native** [0.57.2](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#0572)
> #### Android specific changes
>...
>Add workaround for Android Gradle Plugin 3.2 change to asset dir ([a4fed6e](https://github.com/facebook/react-native/commit/a4fed6e203efd481175e61b7d2aa1c2b037a4279) by @edilaic)
>...

**Comment by ferrannp** [comment]
Oh I am using `0.57.0`. Ok I need to check if the update fixes it. Thank you !

**Comment by yuri-kulikov** [comment]
@ferrannp I hope it will help, please share the results with us!

**Comment by yuri-kulikov** [comment]
Hi, @ferrannp
I'll close this issue for now as it seems to be resolved.
Please feel free to reopen this issue or create a new one if you have any other question.
