### ISSUE TITLE
Can I trigger the Sync before react activity starts in Android? 

### ISSUE THREAD

**Issue by RajeshBatth** [Microsoft/react-native-code-push#1434]
Can I trigger the Sync before react activity starts in Android? 
Use case: I have a home page implemented in native, and subsequent screens in react-native, I was wondering If I can start the Sync before my react native screens open. This will significantly improve the % of users seeing my updates since I'm using ON_NEXT_RESTART as install Mode

* react-native-code-push version: 5.4.2
* react-native version: 0.51
* Android: API 23+

**Comment by NickToropov** [comment]
Hi @RajeshBatth! Currently there is no possibility to do that as `sync` is javascript function that is called when RN context is already initialized and root component is mounted.

**Comment by NickToropov** [comment]
Hi @RajeshBatth! Currently there is not possibility to do that. To solve your issue please try to use `ON_NEXT_RESUME`(restart the app the next time it is resumed from the background) option.

Please let me know if it was helpful or you have any other questions.

**Comment by NickToropov** [comment]
Hi @RajeshBatth! Currently there is not possibility to do that. To solve your issue please try to use `ON_NEXT_RESUME`(restart the app the next time it is resumed from the background) option.

Please let me know if it was helpful or you have any other questions.

**Comment by NickToropov** [comment]
Hi @RajeshBatth! Currently there is not possibility to do that. To solve your issue please try to use `ON_NEXT_RESUME`(restart the app the next time it is resumed from the background) option.

Please let me know if it was helpful or you have any other questions.

**Comment by NickToropov** [comment]
Sorry I have no such information.

**Comment by NickToropov** [comment]
@RajeshBatth I'll close this issue for now as it seems to be answered. Please feel free to reopen this issue or create a new one if you have any other question.
