### ISSUE TITLE
New version identified but is not installing on-demand

### ISSUE THREAD

**Issue by lnfnunes** [Microsoft/react-native-code-push#1436]
The App is not installing last updated version after user accepted in the modal dialog. The new version is only shown after restarting!
Obs: I've tried both _normal_ and _mandatory_ releases
Obs2: I've tried `installMode`s: IMMEDIATE, ON_APP_RESUME, ON_APP_SUSPEND

### Steps to Reproduce
1. react-native init codepushdemo
1. replace App.js to with the [master's example](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/App.js)
1. Change some string in the App.js
1. Publish a new version to app center (CodePush)
1. In the app, click on the button `Press for dialog-driven sync`

### Expected Behavior
What you expected to happen?
1. Identifies the new version
1. Download the bundle 
1. Update the app in the foreground
1. Restart the app

### Actual Behavior
What actually happens?
1. Identifies the new version ✅ 
1. Download the bundle ✅ 
1. Update the app in the foreground ❗️ 
1. Restart the app ❗️ 

### Environment

* react-native-code-push version: 5.4.2
* react-native version: 0.57.3
* iOS/Android/Windows version: Android (not tested on iOS)
* Does this reproduce on a debug build or release build? release apk
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @lnfnunes ,
Thanks for reporting!

Could you please also share logs during update?
For Android you can get it with Android Studio or with `adb logcat` command.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
@lnfnunes , Thanks for logs and screens and sorry for delay.

So, I would like to clarify, your issue is that app doesn't installing update at all or just installing update only after restart app in case when should be installed `IMMEDIATE`?

**Comment by alexandergoncharov** [comment]
@lnfnunes, Yeah, even `IMMEDIATE` setting has state when it waiting the restart as update can be applied only after restart. But in this case restart should be called from CodePush, not from user action.
Could you please try to wait a few seconds in this state? The app should be restarted automatically.
Please let me know your results.

**Comment by alexandergoncharov** [comment]
Hi @lnfnunes ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please fell free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by lnfnunes** [comment]
Hi @alexandergoncharov ,

I was travelling on vacation :P sorry for delay!
Unfortunately the behavior hasn't changed in my testes!!!
Check [this video (screen recorded)](https://drive.google.com/open?id=1qJrbbC6ZU7lsJlE-FhMs2d-rq8FvUmO5)

Observe the app only updates after I restart it.

If this can help in the investigation, I'm publishing the new version with this command
```appcenter codepush release-react -a katinguele/luavai -m```

**Comment by alexandergoncharov** [comment]
Hi @lnfnunes,
Sorry for delay.

I investigated your `app.js` example, put it in my app and all worked correct.
[Here](https://drive.google.com/open?id=1wEtXlitBy9paQ1iq53U6C3FpxsgM3T6-) is my dummy proj with your `app.js` file. For setup it just unzip it and run `yarn install`.

Also, `mandatory`'s install mode  is IMMEDIATE by default. So, you don't have to setup it here: https://gist.github.com/lnfnunes/9569912f1be3d89bc11cc21abdd8f470#file-app-js-L151

Please test my app and let me know your results.
