### ISSUE TITLE
Why app's document and data get bigger and bigger after every update?

### ISSUE THREAD

**Issue by jamessawyer** [Microsoft/react-native-code-push#1438]
### Steps to Reproduce
1.Install my app on an iPhone, PS: my app's bundle and assets  size is around 10MB
2.Check app's initial document and data(open 'system settings -> general -> iPhone Storage' then choose my app) is 11.8kb
3.Change some text in my app, then using code-push update app (iOS version)
4.check app's document and data, now it becomes 10MB around
5.Repeat steps 3 and 4, check app's document and data again, I find it adds up to about 20MB
6.I did one more cycle, it adds up to 30MB  

### Expected Behavior
App's document and data keeps small and delete old document data

### Actual Behavior
app becomes more and more bloating

### Reproducible Demo

codebase about code push
```
import codePush from 'react-native-code-push';

const codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME
}
@codePush(codePushOptions)
class App extends React.Component {
  // ...
}
```

### Environment

* react-native-code-push version: 5.3.2
* react-native version: 0.54.0
* iOS/Android/Windows version: real iOS devices 9.3.3 ,10.3.2 and 12.1 ,not test in Android
* release build
* on a physical device?

**Comment by alexandergoncharov** [comment]
Hi @jamessawyer ,
Thanks for reporting!

Size of app should be increase noticeably only after first update. All next updates can increase the size of app but unnoticeably.

Could you please provide dummy project with reproducing issue?

Thanks,
Alexander

**Comment by jamessawyer** [comment]
Thanks for your help @alexandergoncharov .I will try to provide a project later when I am free.

**Comment by alexandergoncharov** [comment]
Sure, you are always welcome =)

Just a friendly ping about dummy project.

**Comment by alexandergoncharov** [comment]
Hi @jamessawyer ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
