### ISSUE TITLE
Separate bundling and compiling of app

### ISSUE THREAD

**Issue by deecewan** [Microsoft/react-native-code-push#1439]
I have had to split our bundling out of `bundle<config>JsAndAssets`. This is for a couple of reasons, but a big one is source maps.

Either way, for Android, to get a successful build, I compile the assets using `react-native bundle ...` and place the bundle at `android/app/src/main/assets/index.android.bundle` and the assets at `android/app/src/main/res`. This works great for packaging (I get a working build from react-native) but it seems to break code-push because it can't find the `build/generated` directories it's looking for.

My current work-around is to just create those directories manually, but I suspect that this will break code-push (I haven't actually tested it).

Any advice on this?

### Environment

* react-native-code-push version: 5.4.2
* react-native version: 0.57.3
* iOS/Android/Windows version: Android <all>
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @deecewan,
Thanks for reporting!

If you would like to make release from custom folder you should use `appcenter codepush release` command. But for this command you should keep bundle and assets in one folder as you should release folder with all necessary components.
Please let me know if it was helpful or you have any questions.

Also, I'm not sure that codepush require `build/generated` folder. Could you please share command which you used for release and error message?

Thanks,
Alexander

**Comment by deecewan** [comment]
hey @alexandergoncharov 

The command is a part of `codepush.gradle` - it tries to generate some kind of hash using the files that have been added. This happens, as it seems, completely separate to actually pushing OTA updates.

I imagine it's some kind of integrity check to make sure there is no new native code running when a release is pushed out?

**Comment by alexandergoncharov** [comment]
Yeah, you are right. `codepush.gradle` generate hash with `scripts/generateBundledResourcesHash.js` file. No any native code calling.

So, I think that your workaround shouldn't break CodePush but it should be tested before.

Please let me know if it was helpful or you have any questions.

**Comment by alexandergoncharov** [comment]
Hi @deecewan ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by carloslibardo** [comment]
I found a lot of issues about that, my case is the same from @deecewan, i just have the index.android.bundle, i know that generated/res/react/release folder only is created when i run bundleRelease task and generate bundle, but i can't do that, i already has the bundled file.

In my case i'm running a pipeline and the pipeline run ./gradlew clean removing generated folder (i created manually), one solution should create the repo after gradlew clean, but i don't know how do that, has any solution to change the directory folder? 

As i understood, this generateBundledResourcesHashEdpRelease task is to check if current bundle at app is the same from appcenter repo, and avoid update all time, right?

I don't know if i made myself clear, but this is the problem, has any solution? @alexandergoncharov
