### ISSUE TITLE
[iOS] An update check must include a valid deployment key - please check that your app has been configured correctly. 

### ISSUE THREAD

**Issue by nitish1099** [Microsoft/react-native-code-push#1440]
An update check must include a valid deployment key - please check that your app has been configured correctly. To view available deployment keys, run 'code-push deployment ls <appName> -k'.
### Steps to Reproduce
1. Run the app in release or debug build

### Expected Behavior
What you expected to happen?
Update should be downloaded

### Actual Behavior
What actually happens?
Can't dowload any updates on sync
```
  STACK TRACE AND/OR SCREENSHOTS
```
<img width="526" alt="screenshot 2018-10-28 at 3 29 41 pm" src="https://user-images.githubusercontent.com/1907440/47614470-550b8c00-dac6-11e8-8f48-910f9651f38b.png">
<img width="830" alt="screenshot 2018-10-28 at 3 30 22 pm" src="https://user-images.githubusercontent.com/1907440/47614480-6b194c80-dac6-11e8-87c5-be18178bf5df.png">

### Environment

* react-native-code-push version: 5.4.2
* react-native version: 0.56.0
* iOS/Android/Windows version: iOS 12
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? Simulator, haven't tested on a physical device

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @nitish1099 ,
Thanks for reporting!

Could you please ensure that you have correct field of `CodePushDeploymentKey` in `Info.plist`?
There should be correct deployment key as from `appcenter codepush deployment list -a {userName}/{appName} -k`

Please let me know if it was helpful or you still have this issue.

Thanks,
Alexander

**Comment by nitish1099** [comment]
Got it! There was an added space in my development key in the plist. Thanks!
