### ISSUE TITLE
ionic 3 [CodePush] An error has occured while installing the package. Could not get the package start page 

### ISSUE THREAD

**Issue by ismailcse11** [Microsoft/react-native-code-push#1441]
console.log: [CodePush] Reported status:
[app-scripts]             {"status":0,"appVersion":"0.0.1","deploymentKey":"xxxxx"}
[app-scripts] [13:22:35]  console.log: [CodePush] An update is available.
[app-scripts]             {"appVersion":"0.0.1","deploymentKey":"xxxxx","description":"Modified
[app-scripts]             app","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/ZThrCJXwsQu9Hv8evd6D9C9DSjEb3485857a-6fe9-4501-b521-228920abce45","isMandatory":true,"label":"v29","packageHash":"0eb7b1733d1cea385b74b0141927a5189a85f56d8911fac45e8ec546cce2027b","packageSize":499859,"failedInstall":false}
[app-scripts] [13:22:35]  console.log: [CodePush] Awaiting user action.
[app-scripts] [13:22:35]  console.log: CODE PUSH UPDATE: 6
[app-scripts] [13:22:35]  console.log: [CodePush] An update is available.
[app-scripts]             {"appVersion":"0.0.1","deploymentKey":"xxxxx","description":"Modified
app","downloadUrl":"https://codepushupdates.azureedge.net/storagev2/ZThrCJXwsQu9Hv8evd6D9C9DSjEb3485857a-6fe9-4501-b521-228920abce45","isMandatory":true,"label":"v29","packageHash":"0eb7b1733d1cea385b74b0141927a5189a85f56d8911fac45e8ec546cce2027b","packageSize":499859,"failedInstall":false}
[app-scripts] [13:22:40]  console.log: [CodePush] Downloading update
[app-scripts] [13:22:43]  console.log: [CodePush] Package download success:
[app-scripts]             {"deploymentKey":"xxxxx","description":"Modified       app","label":"v29","appVersion":"0.0.1","isMandatory":true,"packageHash":"0eb7b1733d1cea385b74b0141927a5189a85f56d8911fac45e8ec546cce2027b","isFirstRun":false,"failedInstall":false,"localPath":"cdvfile://localhost/files/codepush/download/update.zip"}
[app-scripts] [13:22:43]  console.log: CODE PUSH UPDATE: 8
[app-scripts] [13:22:43]  console.log: [CodePush] Installing update
[app-scripts] [13:22:45]  console.log: [CodePush] Applying full update
[app-scripts] [13:22:45]  console.error: [CodePush] Preinstall failure. Could not get the package start page
[app-scripts] [13:22:45]  console.log: CODE PUSH ERROR: Error: An error has occured while installing the package. Could not get the
[app-scripts]             package start page
[app-scripts] [13:22:45]  console.error: [CodePush] An error has occured while installing the package. Could not get the package start
[app-scripts]             page. StackTrace: Error: An error has occured while installing the package. Could not get the package start
[app-scripts]             page at preInstallFailure
[app-scripts]             (http://192.168.0.103:8100/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41) at
[app-scripts]             Object.callbackFromNative (http://192.168.0.103:8100/cordova.js:293:52) at processMessage
[app-scripts]             (http://192.168.0.103:8100/cordova.js:1115:17) at processMessages
[app-scripts]             (http://192.168.0.103:8100/cordova.js:1138:9) at t.invoke
[app-scripts]             (http://192.168.0.103:8100/build/polyfills.js:3:14976) at r.run
[app-scripts]             (http://192.168.0.103:8100/build/polyfills.js:3:10143) at
[app-scripts]             http://192.168.0.103:8100/build/polyfills.js:3:20242 at t.invokeTask
[app-scripts]             (http://192.168.0.103:8100/build/polyfills.js:3:15660) at r.runTask
[app-scripts]             (http://192.168.0.103:8100/build/polyfills.js:3:10834) at o
[app-scripts]             (http://192.168.0.103:8100/build/polyfills.js:3:7894)
[app-scripts] [13:22:45]  console.error: [CodePush] An error occurred during sync. An error has occured while installing the package.
[app-scripts]             Could not get the package start page. StackTrace: Error: An error has occured while installing the package.
[app-scripts]             Could not get the package start page at preInstallFailure
[app-scripts]             (http://192.168.0.103:8100/plugins/cordova-plugin-code-push/bin/www/localPackage.js:246:41) at
[app-scripts]             Object.callbackFromNative (http://192.168.0.103:8100/cordova.js:293:52) at processMessage
[app-scripts]             (http://192.168.0.103:8100/cordova.js:1115:17) at processMessages
[app-scripts]             (http://192.168.0.103:8100/cordova.js:1138:9) at t.invoke
[app-scripts]             (http://192.168.0.103:8100/build/polyfills.js:3:14976) at r.run
[app-scripts]             (http://192.168.0.103:8100/build/polyfills.js:3:10143) at
[app-scripts]             http://192.168.0.103:8100/build/polyfills.js:3:20242 at t.invokeTask
[app-scripts]             (http://192.168.0.103:8100/build/polyfills.js:3:15660) at r.runTask
[app-scripts]             (http://192.168.0.103:8100/build/polyfills.js:3:10834) at o
[app-scripts]             (http://192.168.0.103:8100/build/polyfills.js:3:7894)

**Comment by alexandergoncharov** [comment]
Hi @ismailcse11 ,
Thanks for reporting!

This is react-native repo. Please open this issue in according repo: https://github.com/Microsoft/cordova-plugin-code-push/issues

Please provide also commands which you used for release update after opening new issue? 

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
And I'm going to close this issue. Please feel free to ask any questions in according repo: https://github.com/Microsoft/cordova-plugin-code-push/issues
