### ISSUE TITLE
How to get metadata info in the Native side?

### ISSUE THREAD

**Issue by ferrannp** [Microsoft/react-native-code-push#1443]
Same as here: https://stackoverflow.com/questions/39796511/how-do-i-show-the-current-codepush-version-label-in-my-react-native-android-app but not from React Native but from Native. I don't seem to figure that out (is it exposed?).

On Android I can do:

```kt
val codePush = CodePush(args.codePushKey, args.hostApplication, BuildConfig.DEBUG)
// And access codePush.appVersion
```

However this only gives me the target binary version. How can I get the label (internal version) and description from Native Android and from Native iOS?

Something like:

`"1.0.0", "v20", "Some description for this version"`

### Environment

* react-native-code-push version: 5.4.2
* react-native version: 0.57.x
* iOS/Android/Windows version: Android Studio 3.2.1, gradlePluginVersion 3.2.0 and gradle 4.6.
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by ferrannp** [comment]
@NickToropov I tried that but probably I do it too early because `currentPackage` is always null.

**Comment by NickToropov** [comment]
If you have CodePush update then it doesn't depend when you check it. Our plugin just reads  metadata from two json files sequentially. So if your `currentPackage` is null then there is no codepush update yet or one of metadata files is damaged. Please try to debug from [this line](https://github.com/Microsoft/react-native-code-push/blob/ac5472ee2ab9dc8f384384a3f66d7ab5010afa3e/android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateManager.java#L115).

**Comment by NickToropov** [comment]
Hi @ferrannp! Were you able to get current package metadata? Or do you have any other questions?

**Comment by NickToropov** [comment]
Hey! 
We haven’t heard from you in a while, so I am going to go ahead and close this issue. Should you still have any questions, you can reopen the issue or if you prefer you can create a new one.
