### ISSUE TITLE
How to make the updateDialog descriptionPrefix content align left

### ISSUE THREAD

**Issue by s349856186** [Microsoft/react-native-code-push#1444]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
### Expected Behavior
What you expected to happen?
Custom update content layout

### Actual Behavior
What actually happens?

![image](https://user-images.githubusercontent.com/2498958/47828603-bda48280-ddbe-11e8-87a0-7a38be5760b8.png)
Anybody help me？Thanks

**Comment by NickToropov** [comment]
Hi @s349856186! As I know unfortunately there is no possibility to customize this Alert from javascript code.

Let me know if you have any other questions.

**Comment by s349856186** [comment]
OK, Thanks. @NickToropov
