### ISSUE TITLE
Is there a way to set a code-push policy to download and install in background?

### ISSUE THREAD

**Issue by krunalsshah** [Microsoft/react-native-code-push#1445]
Is there a way to set a code-push policy to download and install the bundle in background?

1. We do not want to use CodePush.InstallMode.IMMEDIATE
2. We currently use CodePush.InstallMode.ON_NEXT_RESUME, so when the app goes to background it installs the bundle & now foreground it
3. Now put the app 2nd time the background and foreground it (new content is displayed)

Can we combine, 2 & 3, meaning install in background and update in background, so that new content shows up?

Adding a video for reference. 

@vasanthk 

[CodePush-SubTitle-480.zip](https://github.com/Microsoft/react-native-code-push/files/2540359/CodePush-SubTitle-480.zip)

**Comment by krunalsshah** [comment]
@alexandergoncharov

**Comment by krunalsshah** [comment]
@alexandergoncharov

**Comment by alexandergoncharov** [comment]
Hi @krunalsshah ,
Thanks for reporting and sorry for this delay!

So, you would like to get update in background while app is minimised and then when user open app update should be installed. Is it correct?

Thanks,
Alexander

**Comment by vasanthk** [comment]
Yes @alexandergoncharov .

**Comment by alexandergoncharov** [comment]
@krunalsshah @vasanthk , I got it. Thanks. Yeah, unfortunately it isn't possible for now but we have this feature on our roadmap. I can't provide any ETA for now but i'll let you know any news about this. 

So, I'm going to close this issue for now but please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by JofBigHealth** [comment]
@alexandergoncharov Is there a way we can keep tabs on the progress of this specific feature? I.e. whether it's under consideration, in progress, in testing etc? As with others this would be huge for us.

**Comment by vasanthk** [comment]
+1

**Comment by Jaybee4real** [comment]
@alexandergoncharov-zz It's been 4 years, can we please consider adding this feature or get an update on if has been worked on or if it being worked on?

**Comment by elouisramsey** [comment]
hello @alexandergoncharov-zz has this feature been added?
