### ISSUE TITLE
Did we delay the status report updating in newer versions?

### ISSUE THREAD

**Issue by krunalsshah** [Microsoft/react-native-code-push#1446]
We upgraded the `react-native-code-push` that is compatible with `react-native@0.55.4`

What we notice is a lot of pending and currently have a mandatory install mode.

```Total: 223 (2,541 pending)```

Do you think the bundle status reporting is delayed to the next restart or back ground/foreground? Prior on immediate instal mode we use to observe stats update instantly with very fewer pending.

I am observing the Rollback count and it's negligible that tells me the the bundle is fine.

**Comment by krunalsshah** [comment]
@alexandergoncharov

**Comment by alexandergoncharov** [comment]
Hi @krunalsshah ,
Thanks for reporting!

It is strange issue. Do you have any logs about that?

Thanks,
Alexander

**Comment by krunalsshah** [comment]
I doubt if I can capture the logs for the same. It's in production build.
Although positive, only of the app restarts the pending status gets to Total count. 
We are using mandatory install mode. (IMMEDIATE)

**Comment by alexandergoncharov** [comment]
@krunalsshah , Yeah. It is strange. 
I'm not sure what is the reason of this behavior without any additional logs.
Could you please clarify what is situation at now?

Also, if this issue still here I think you can make one more release for testing.
And my recommendation is add some bug trackers for your app for knowing what is going in your app on user devices.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @krunalsshah ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
