### ISSUE TITLE
in android,cant find audio after code-push realease-react,beause have uppercase letters in the folder inside

### ISSUE THREAD

**Issue by LDty** [Microsoft/react-native-code-push#1449]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
in android
### Steps to Reproduce
1. import Sound from 'react-native-sound'
2. let whoosh1 = new Sound(require('../music/0001_0001_001.mp3'), (error, sound) => { });
3.after code push,0001_0001_001.mp3 have download but cant play

### Expected Behavior
require('../music/0001_0001_001.mp3')
can play this music

### Actual Behavior

There are uppercase letters in the folder.
but cant require 'uppercase letters .mp3'
So it can't be played.

(因为react-native-sound要求文件夹里不能有大写字母,但codepush后保存mp3的文件夹包含大写字母,导致音乐文件不能被正确访问到,我尝试了下require('../MUSIC/0001_0001_001.mp3'),只要有大写字母 reactnative就会报错... 不知道咋解决)
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo



### Environment

* react-native-code-push version:5.4.2
* react-native version:0.55.4
* iOS/Android/Windows version:android
* Does this reproduce on a debug build or release build?  release build
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @LDty ,
Thanks for reporting!

Could you please clarify provide more details about your issue. So, If path has only lowercase letters then you successful can use use `0001_0001_001.mp3` file. In case if uppercase letters exist in path you can't use `0001_0001_001.mp3` file after updating?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
oh, I see. So your main issue that after using CodePush your files contains in folder like `CodePush/<hash>/CodePush`?
If it is so I would like to recommend you to use relative path if is possible instead of absolute path. It should fix your issue.

Please let me know if it was helpful or you have any issues.

Thanks,
Alexander

**Comment by LDty** [comment]
i try like this 
`"env": {
    "production": {
      "plugins": [
        [
          "babel-plugin-root-import",
          {
            "rootPathSuffix": "src/music",
            "rootPathPrefix": "#"
          }
        ]
      ]
    }`

and use like this:
`new Sound(require('#/000100010001.mp3'), (error, sound) => { });`

If there is no mistake the way i use relative path instead of absolute path,it had no effect.

maybe i should download audio in another way

thanks anyway

**Comment by LDty** [comment]
i try setting babelrc like this 
`"env": {
    "production": {
      "plugins": [
        [
          "babel-plugin-root-import",
          {
            "rootPathSuffix": "src/music",
            "rootPathPrefix": "#"
          }
        ]
      ]
    }`

and use like this:
`new Sound(require('#/000100010001.mp3'), (error, sound) => { });`

If there is no mistake the way i use relative path instead of absolute path,it had no effect.

maybe i should download audio in another way

thanks anyway

**Comment by SimonSimya** [comment]
@LDty did you solve this? I'm having the same problem.

**Comment by alexandergoncharov** [comment]
Hi @LDty ,
Sorry for delay.

So, you would like to keep mp3 files as part of release but after updating app path to them is changed to lowercase. Is it correct?

Is it possible to provide some dummy project with repro steps? I would like to debug it.

Also, you said that possible you should use another way. Do you have any ideas about this approach?

**Comment by alexandergoncharov** [comment]
Hi @LDty ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions or prepare dummy project.

Thanks,
Alexander

**Comment by EmperorEarth** [comment]
@alexandergoncharov, is this [related to this](https://github.com/zmxv/react-native-sound/blame/master/README.md#L99)

> Save your sound clip files under the directory `android/app/src/main/res/raw`. Note that **files in this directory must be lowercase and underscored (e.g. my_file_name.mp3) and that subdirectories are not supported by Android**

I'm using relative imports and I'm [experiencing this](https://github.com/zmxv/react-native-sound/issues/656) as well. iPhone works fine but Android is unable to find the file after a CodePush update. Normal builds work fine on Android.

Are Code Push bundles/updates/assets in a directory with capital letters?
