### ISSUE TITLE
Code push not updating app to the latest version

### ISSUE THREAD

**Issue by monicse09ku** [Microsoft/react-native-code-push#1450]
Hello,

My app version in the Google Play Store is 1.0.2. My first push to the code push is 1.0.3 which is two weeks earlier. Not I have updated to version 1.0.6 and pushed to code push. But my installed apps which is updated to version 1.0.3 by code push is not updating to latest version. And if I install again from play store, the app is still updating to version 1.0.3

I have used following codes for pushing to code push 

`code-push release-react <app-name> android`
`code-push promote <app-name> Staging Production`

Why is this happening?

**Comment by alexandergoncharov** [comment]
Hi @monicse09ku ,
Thanks for reporting!

But I found that you already open same issue in `code-push` repo: https://github.com/Microsoft/code-push/issues/602

So, I'm going to close this issue for now as duplicate and continue conversation on original issue.
Please feel free to reopen if if you have any questions.

Thanks,
Alexander
