### ISSUE TITLE
How can I make the update description support multiple languages?

### ISSUE THREAD

**Issue by s349856186** [Microsoft/react-native-code-push#1452]
What you expected to happen?
update dialog show description multiple languages

**Comment by s349856186** [comment]
@NickToropov Thanks you reply.
But the currently running version does not know what the next version will update, so I can only get the update instructions (--des) when I release the update. I don't understand what to do, I use the custom dialog and the sync method.  What should I do? Thanks

**Comment by nighttiger1990** [comment]
@s349856186 set appendReleaseDescription to 'true'

**Comment by s349856186** [comment]
@nighttiger1990 Sorry, i don't understand how to do. Can you make it clear? Thanks
I can now get the update description from (--des), I want the description to support different languages to display different descriptions, what should I do? Thanks

**Comment by Symous** [comment]
@s349856186 Hi friend, did you find any way to support multi language update description?

**Comment by s349856186** [comment]
NO, but you can customize your des as "en:123,zh:123" and split it
