### ISSUE TITLE
[CodePush] The file “unzipped” couldn’t be opened - unzippedFolderPath appears as a file instead of a folder

### ISSUE THREAD

**Issue by andrewrt** [microsoft/react-native-code-push#1457]
### Steps to Reproduce
1. Install CodePush via manual method to xcode project
2. Ensure that CodePush is using its own SSZipArchive library
3. In react native - app.js: 
```js
import codePush from 'react-native-code-push';
class App extends React.Component {

  codePushDownloadDidProgress = (progress) => {
    console.log(`${progress.receivedBytes} of  ${progress.totalBytes}  received.`);
  }

  componentDidMount() {
    codePush.sync(
      {
        updateDialog: true,
        installMode: codePush.InstallMode.IMMEDIATE,
      },
      (syncStatus) => {/*log status*/},
      (progress) => { this.codePushDownloadDidProgress(progress); }
    );
  }
 }

const codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };
// const codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_RESUME };
const MyApp = codePush(codePushOptions)(App);
export default MyApp;
```

### Expected Behavior
Bundle downloads and installs

### Actual Behavior

Console outputs:
```sh
2018-11-20 14:47:59.576 [info][tid:com.facebook.react.JavaScript] 'CodePush syncStatus: ', 7
2018-11-20 14:48:00.031 [info][tid:com.facebook.react.JavaScript] 17996 of  1247495  received.
2018-11-20 14:48:00.063 [info][tid:com.facebook.react.JavaScript] 50764 of  1247495  received.
2018-11-20 14:48:00.097 [info][tid:com.facebook.react.JavaScript] 99916 of  1247495  received.
2018-11-20 14:48:00.403 [info][tid:com.facebook.react.JavaScript] 1247495 of  1247495  received.
2018-11-20 14:48:00.499 [info][tid:com.facebook.react.JavaScript] 'CodePush syncStatus: ', 3
2018-11-20 14:48:00.500 [info][tid:com.facebook.react.JavaScript] [CodePush] The file “unzipped” couldn’t be opened.
```

Bundle downloads successfully, but then the unzip inside of CodePush appears to unzip the package as a file instead of a folder, so in CodePushPackage.m
```objc
 [SSZipArchive2 unzipFileAtPath:downloadFilePath  toDestination:unzippedFolderPath];
```
the phone's folder structure looks like:
/Library/Application Support/CodePush: 
 - download.zip (correct 1.2MB zip with my package, assets, etc etc)
 - unzipped (a 3.6MB file without type)

### Environment

* react-native-code-push version: "react-native-code-push": "^5.4.2",
* react-native version: "react-native": "0.56.x",
* iOS version: iOS 12.0.1
* Does this reproduce on a debug build or release build? Happens on both release and debug
* Does this reproduce on a simulator, or only on a physical device? Physical device & simulator

**Comment by andrewrt** [comment]
(I've renamed SSZipArchive to SSZipArchive2 in order to avoid naming collision as I saw that CodePush appears to be rolling your own version of SSZipArchive - and I wanted to be sure to run CodePush as you had intended).

**Comment by yuri-kulikov** [comment]
## [CodePush] The file “unzipped” couldn’t be opened - unzippedFolderPath appears as a file instead of a folder
(https://github.com/Microsoft/react-native-code-push/issues/1457)

Hi @andrewrt,
Thanks for reporting!

I've tested it and in my case it works as it should:
![screenshot 2018-11-21 at 14 46 34](https://user-images.githubusercontent.com/42337914/48840421-9dedf200-ed9f-11e8-9c14-b262b82bcfba.png)

I've also renamed `SSZipArchive` to `SSZipArchive2` for clarity.
It would be very helpful if you could provide us with a simple reproducible demo because I cannot reproduce the issue.

**Comment by yuri-kulikov** [comment]
@andrewrt, I don't use cocoapods in this project either.

I'm using very simple project:
- `react-native init ...`
- `yarn add react-native-code-push`
- `react-native link react-native-code-push`

**Comment by andrewrt** [comment]
@yuri-kulikov - 
It appears that react-native link react-native-code-push will search for CocoaPods and if it finds something - it tries to link CodePush via cocoapods instead of using the non-cocoapods method...

Do you know what specifically the react-native-code-push link script is looking for?

(I have cocoapods for some external stuff - but don't want to use it for this as per the above)

**Comment by andrewrt** [comment]
Looks like it was looking for the PodFile... and maybe a few other things. 
Removing the podfile, pods, etc temporarily and then running link appears to be working. 
Additionally - your tests as well were working. 

I must have missed something in the manual setup based on ^^^

Thanks again!

**Comment by zim-lee** [comment]
I have the same issue. How to fix it? @andrewrt

**Comment by yuri-kulikov** [comment]
Hey @zim-lee,
Sorry for the delay.

Do you use CocoaPods in your application? You can check [this part of docs](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---cocoapods) in this case. Maybe this could help you, please let me know.

**Comment by zim-lee** [comment]
@yuri-kulikov yes, I use CocoaPods in my project.
```
use_frameworks!

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
  pod 'React', path: '../node_modules/react-native/', :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTLinkingIOS',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport',
    'CxxBridge',
    'RCTSettings'
  ]
    
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
```

**Comment by yuri-kulikov** [comment]
@zim-lee have you tried to delete "Pods" folder and use `pod install` in "ios" directory?

**Comment by zim-lee** [comment]
@yuri-kulikov Thank you for reply. I tried many times, but it didn't work.

**Comment by andrewrt** [comment]
the hack I used to get around this, since i don't use cocoapods for react native itself, was to delete both cocoapods pods directory, and the podspec file or whatnot (temporarily), then run react native link on this library, then bring back cocoapods....

**Comment by yuri-kulikov** [comment]
@andrewrt, so, as I understood it:
You use Pods, but not for `react-native`, and if you use the `react-native link react-native-code-push` command, it will lead to this problem.

Did I understand you correctly?

**Comment by zim-lee** [comment]
any solutions for this? I remove libCodePush.a from `Link Binary With Libraries`, it resolved this issue, but when I archive project, meet this issue #645 .-_-

**Comment by kennym** [comment]
We're seeing this behavior, too.

RN 0.61.2
react-native-code-push 5.7.0

**Comment by andrewrt** [comment]
@yuri-kulikov  - yes - you understood correctly.

**Comment by alexandergoncharov** [comment]
Hi all,
Sorry for that long delay.

Could please someone provide some demo app with reproducing issue and reprosteps?
We would like to reproduce this issue and investigate it.

**Comment by alexandergoncharov** [comment]
Hi all,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
