### ISSUE TITLE
Androidx support

### ISSUE THREAD

**Issue by floynn** [Microsoft/react-native-code-push#1462]
Hi,

Basically https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java#L7 is the only place where `android.support.annotation.NonNull` used. However in androidx package name changed to `androidx.annotation.NonNull` which causes build errors. 

Are there any plans to migrate this project to androidx? Or as a short term solution is it possible to just remove `android.support.annotation.NonNull` from `CodePush.java` since none of the other project files use android nullability annotations?

### Steps to Reproduce
Use `react-native-code-push` in any androidx project.

### Expected Behavior
Project successfully compiles.

### Actual Behavior
Build fails with `package android.support.annotation does not exist` error.

**Comment by yuri-kulikov** [comment]
Hi @floynn,  
Thanks for reporting and sorry for the delay!

This is actually a pretty good idea, we need some time to investigate this question a bit more and I think we will fix it. I'll let you know about any changes.

**Comment by floynn** [comment]
@yuri-kulikov Thank you for the fixes!

**Comment by DSteve595** [comment]
@yuri-kulikov There's a remaining issue when using this on AndroidX projects: Some classes have changed their packages and now they fail to be resolved. For example, CodePush.java imports `android.support.annotation`, but after AndroidX, that package is `androidx.annotation`.
