### ISSUE TITLE
Background music stop playing after use react-native-code-push force hot reload.

### ISSUE THREAD

**Issue by Spicely** [Microsoft/react-native-code-push#1465]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.When app loaded.Use react-native-sound play background music(file.mp3)
2. react-native-code-push check update and then load latest bundle.
3.When loading done and force hot reload.The background music stop and use code to play music again does not work either.

### Expected Behavior
What you expected to happen?
After hot loading,the background keep playing.
### Actual Behavior
What actually happens?
```After hot loading,the background stop playing.
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @Spicely ,
Thanks for reporting!

Could you please provide some dummy project with reproducing issue? I would like to debug.
At now, I think that issue can be in absolute path of your mp3 files. Could you please try to use related path if this possible?

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
@Spicely, @cq0702, Thanks for providing this example.

Could you please clarify is it possible to provide full dummy project with configured music package and example music which possible to build and run without any additional settings?

**Comment by alexandergoncharov** [comment]
Hi @Spicely, @cq0702,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions or provide a dummy project.

Thanks,
Alexander

**Comment by zhilianghuang** [comment]
@Spicely I also encountered the same problem.
@alexandergoncharov The app can also be played before it is updated.
Cannot play after updating

**Comment by Spicely** [comment]
> @alexandergoncharov 
The problem was that the file could not be found after the update and could not be played.

Solution uses packaged static files

But this method is silent during debugging.

**Comment by Spicely** [comment]
@zhilianghuang 
The problem was that the file could not be found after the update and could not be played.

Solution uses packaged static files

But this method is silent during debugging.

**Comment by zhilianghuang** [comment]
![image](https://user-images.githubusercontent.com/17289763/52630824-38218a00-2ef8-11e9-8b5b-0df0bd481e61.png)
this is my code push server path

**Comment by Spicely** [comment]
@zhilianghuang 
![image](https://user-images.githubusercontent.com/10075622/52632185-c1868b80-2efb-11e9-859d-659675992bb7.png)This is my solution.

**Comment by zhilianghuang** [comment]
@Spicely thank, I will try

**Comment by zhilianghuang** [comment]
@Spicely assets/src/assets/music

 this you files folder? Can take a picture to see it? 
Tq

**Comment by zhilianghuang** [comment]
@Spicely 
Tried you this way, the same does not play after the update is completed.
![image](https://user-images.githubusercontent.com/17289763/52637410-1df0a780-2f0a-11e9-85f4-010d4c9c24a5.png)

**Comment by Spicely** [comment]
This can only be used in the official version.



发自我的小米手机
在 zhilianghuang <notifications@github.com>，2019年2月12日 下午9:07写道：

@Spicely<https://github.com/Spicely>
Tried you this way, the same does not play after the update is completed.
[image]<https://user-images.githubusercontent.com/17289763/52637410-1df0a780-2f0a-11e9-85f4-010d4c9c24a5.png>

**Comment by zhilianghuang** [comment]
@Spicely  

打中文吧 我就是打包出来放到测试环境走的，也是这种方式codepush发送版本更新完成后是不行哟。

**Comment by zhilianghuang** [comment]
@Spicely  
Thanks You method is ok 
Solution
