### ISSUE TITLE
Play Store rejecting app due to an unsafe implementation of X509TrustManager-interface

### ISSUE THREAD

**Issue by KasperOlesenMagnetix** [Microsoft/react-native-code-push#1470]
### Expected Behavior
The app should be approved by Google Play Store

### Actual Behavior
The app is rejected by Google Play Store

#### Screenshot

![screen shot 2018-12-12 at 10 47 25](https://user-images.githubusercontent.com/34027672/49861182-98625580-fdfb-11e8-8540-e7884d9eec4c.png)

The text is in danish, but it basically states:
Your app uses an unsafe implementation of the X509TrustManager-interface with an Apache-HTTP-Client.

The issue can only be linked to the react-native-code-push library as it is the only place where the X509TrustManager is used.

According to google this is an issue that should have been handled back in 2016, but I haven't experienced it before now. 

### Environment

* react-native-code-push version: 5.4.2
* react-native version: 57.3

**Comment by alexandergoncharov** [comment]
Hi @KasperOlesenMagnetix,
Thanks for reporting!

Could you please provide link or something like that to the place where X509TrustManager is used?

**Comment by KasperOlesenMagnetix** [comment]
The only instances of anything related to 'X509' in my project is located in the file CodePushUpdateUtils.java, which can be found in react-native-code-push/android/app/src/main/java/com/microsoft/codepush/

Other than the references in that file, I have no idea.

**Comment by alexandergoncharov** [comment]
Hi @KasperOlesenMagnetix,
Sorry for delay.

Yeah, `CodePushUpdateUtils.java` uses `X509EncodedKeySpec`. But I'm not sure if this can be reason of this issue as you are only single reporter about this issue. Aslo, I see on your screen that issue package(If I correct understand Danish language on screen :)) is `org.acra.util.NativeTrustManager` but we are using instance of `java.security.spec.X509EncodedKeySpec`.

Could you please run global searching in your project? There should be some more places which using `X509`.

Please let me know your results.

**Comment by KasperOlesenMagnetix** [comment]
Hi @alexandergoncharov 

I've tried searching through the project and can't any uses of anything related to 'x509' outside of this library. However, I tried removing the code-push library completely and it is still rejected in the google play store, so I assume that the rejection has nothing to do with this library.

**Comment by alexandergoncharov** [comment]
Got it. Thanks for letting us know!

So, I'm going to close this issue for now as this issue has nothing to do with CodePush.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
