### ISSUE TITLE
Code Push roll backs on app restart on RN 0.57.8

### ISSUE THREAD

**Issue by 2hyjun** [Microsoft/react-native-code-push#1473]
### Steps to Reproduce
1. react-native init CodePushTest --version 0.57.8
2. integrate CodePush via `code-push-cli` (not tested on `appcenter-cli`)
3. publish new release, apply it and restart the application

### Expected Behavior
New release will be kept on next app start.

### Actual Behavior
What actually happens?

![s1](https://i.ibb.co/ChZLnDj/Simulator-Screen-Shot-i-Phone-8-2018-12-17-at-12-06-07.png)
before updates
![s2](https://i.ibb.co/715kx5B/Simulator-Screen-Shot-i-Phone-8-2018-12-17-at-12-06-12.png)
while updating
![s3](https://i.ibb.co/h1Hbtwf/Simulator-Screen-Shot-i-Phone-8-2018-12-17-at-12-06-15.png)
after update (install IMMEDIATE)
![s4](https://i.ibb.co/ChZLnDj/Simulator-Screen-Shot-i-Phone-8-2018-12-17-at-12-06-07.png)
when app restarts, automatically rolled back to prev version that build & installed by Xcode.

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: ^5.5.0
* react-native version: 0.57.8
* iOS/Android/Windows version: ios 12.1
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? both of all

(The more info the faster we will be able to address it!)

**Comment by tanmaybhatt** [comment]
I think [this PR](https://github.com/facebook/react-native/pull/22531) on react-native is the problem.
So after upgrading to react-native 0.57.8 and react-native link this happens in AppDelegate.m
```objective-c
  #ifdef DEBUG
    
    #ifdef DEBUG
        jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
    #else
        jsCodeLocation = [CodePush bundleURL];
    #endif
  #else
    jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
  #endif
```
As far as I can see, this will never load the latest bundle.

**Comment by alexandergoncharov** [comment]
Hi @tanmaybhatt,
Thanks for reporting!

Yeah, you are right. I reproduced it. Working on fix. Thanks.

**Comment by joaovpmamede** [comment]
It's happening to me but on `0.56.0`, is it normal?

**Comment by alexandergoncharov** [comment]
@joaovpmamede, No, It isn't. I see that you opened new issue for this: https://github.com/Microsoft/react-native-code-push/issues/1483
Let's continue our conversation there.

**Comment by alexandergoncharov** [comment]
Hi @2hyjun and @tanmaybhatt,

Fix already in Master and in new Release: https://github.com/Microsoft/react-native-code-push/releases/tag/v5.5.1
So, I'm going to close this issue. Please feel free to reopen it if you have any questions or face this issue again.

Thanks,
Alexander
