### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/Users/yangtaotao/Documents/gitos/qiyun_zx/android/app/build/intermediates/assets/debug/CodePushHash'

### ISSUE THREAD

**Issue by ytt123** [Microsoft/react-native-code-push#1476]
<img width="1301" alt="wx20181218-170616 2x" src="https://user-images.githubusercontent.com/13364695/50143316-45027280-02e7-11e9-9a06-9db0a9c24fb5.png">

**Comment by yuri-kulikov** [comment]
Hi @ytt123,
Thanks for reporting!

Could you clarify some information:

* `react-native-code-push` version:
* `react-native` version:
* `gradle` version:
* `gradle plugin` version:

**Comment by yuri-kulikov** [comment]
Hey!
Unfortunately, we haven’t heard from you in a while, so I'll close the issue for now. Please, feel free to reopen it if you still have some questions.

**Comment by ashutosh-akss** [comment]
This issue is occurring on latest version also, needs to be reopened

"react-native-code-push": "^1002.0.0",
"react": "^16.4.1",
 "react-native": "^0.56.0",
Gradle plugin : 3.2.1

**Comment by yuri-kulikov** [comment]
Hi @ashutosh-akss, I think it might help you: https://github.com/Microsoft/react-native-code-push/issues/1427#issuecomment-430913598.

**Comment by ashutosh-akss** [comment]
Thanks @yuri-kilokov I read this thread of yours and got the issue fixed.

**Comment by yuri-kulikov** [comment]
Great! Glad to help 👍
