### ISSUE TITLE
android bundle no find

### ISSUE THREAD

**Issue by baicuhaha** [Microsoft/react-native-code-push#1479]
What you expected to happen?
The new version works fine when updated on android
### Actual Behavior
After the update, the flash back
What actually happens?
The new version works fine when updated on android
  STACK TRACE AND/OR SCREENSHOTS
```
![921a8ba9-3df0-49a9-9ee4-7d0993da45bc](https://user-images.githubusercontent.com/20334376/50266743-c3822000-045f-11e9-8925-fe16852810d7.png)


### Environment

* react-native-code-push version: 5.5.0
* react-native version:0.57.7
* iOS/Android/Windows version:Android
* Does this reproduce on a debug build or release build: release
* Does this reproduce on a simulator, or only on a physical device: hawei

**Comment by alexandergoncharov** [comment]
Hi @baicuhaha,
Thanks for reporting!

If I understand correct your new update can't be applied and device rolls back to old version. Is it correct?
Could you please provide logs during update?
You can grab it with AndroidStudio or `adb logcat` command. There should be logs with `[CodePush]` tag.

Please let me know if you have any questions.

Thanks,
Alexander

**Comment by baicuhaha** [comment]
I have updated it successfully and reported an error after restart 
![2018-12-20 5 02 31](https://user-images.githubusercontent.com/20334376/50274931-31871100-0479-11e9-8600-ab1f2f9a7222.png)
![2018-12-20 5 02 39](https://user-images.githubusercontent.com/20334376/50274934-321fa780-0479-11e9-806b-994f4e9dea1a.png)

**Comment by alexandergoncharov** [comment]
oh, I see. It looks like that you running debug version with running dev server. Could you please try to close dev server or run release mode and try to update your app one more time?

**Comment by baicuhaha** [comment]
It's not that I actually had an error message on it. After I updated it, the app was restarted and then I couldn't find the path of the bundle. The version react-native 0.55 I used before can be upgraded to 0.57, and ios will have no problem after that, but android has been reporting an error. This is the specific error information of android under the release:


![2018-12-20 2 00 26](https://user-images.githubusercontent.com/20334376/50275887-7dd35080-047b-11e9-988e-7b18ee4c32aa.png)

**Comment by baicuhaha** [comment]
Did my update fail because I changed the code in node_modules? Can you give me some advice?

**Comment by baicuhaha** [comment]
I changed the file in node_moudles and changed the source code. Will the update fail? Please give me some advice. Thank you very much!

**Comment by baicuhaha** [comment]
I have modified the node_modules file, modify the source code here, will the update fail? Please give me some advice. Thank you very much!

**Comment by baicuhaha** [comment]
I have found the reason. Thank you
