### ISSUE TITLE
can't silently update

### ISSUE THREAD

**Issue by s349856186** [Microsoft/react-native-code-push#1480]
componentWillMount(){
      CodePush.disallowRestart();
      this.silentSync();
}

componentDidMount(){
             CodePush.allowRestart();
             CodePush.notifyAppReady();
    }

silentSync() {
        CodePush.sync(
            {},
            this.codePushStatusDidChange.bind(this),
            this.codePushDownloadDidProgress.bind(this)
        );
}

12-20 15:20:16.434 8324-8344/? I/ReactNativeJS: [CodePush] Disallowing restarts
12-20 15:20:16.554 8324-8344/? I/ReactNativeJS: [CodePush] Re-allowing restarts
12-20 15:20:16.594 8324-8344/? I/ReactNativeJS: ===language=err=[object Object]
12-20 15:20:17.354 8324-8344/? I/ReactNativeJS: 'checkForUpdate', '', '{"deploymentKey":"z6xJWQ72ojeKgXsh57NH5dHDZgPx8083febc-8402-71dfa4879dd7","description":"","label":"v1","appVersion":"1.0.6","isMandatory":false,"packageHash":"df90b47dd610ccb2cd764ff2bbc6be40a39feef2bbf75679788891d173209d47","packageSize":6404349,"downloadUrl":"https://codepushupdates.azureedge.net/storagev2/OElmQf-yxepZEcI5ouqCOzfGBJ6r8083febc-5fa5-4c39-8402-71dfa4879dd7","isPending":false,"failedInstall":false}'
12-20 15:20:17.354 8324-8344/? I/ReactNativeJS: Checking for update.
12-20 15:20:17.584 8324-8344/? I/ReactNativeJS: App is up to date.

I want to silently update ,not show dialog. But not update. what should I do？Thanks

### Environment
* react-native-code-push version: "^5.3.5",
* react-native version: "0.51.0",
* iOS/Android/Windows version: Android 4.4
* Does this reproduce on a debug build or release build? denug && release
* Does this reproduce on a simulator, or only on a physical device? physical device

**Comment by alexandergoncharov** [comment]
Hi @s349856186,
Thanks for reporting!

For disabling confirmation dialog you should just add `updateDialog: false` to codepush settings.
Full code example should be like so: 
```
silentSync() {
    CodePush.sync(
        { updateDialog: false },
        this.codePushStatusDidChange.bind(this),
        this.codePushDownloadDidProgress.bind(this)
    );
}
```
For more info please check this docs: https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushoptions
Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by s349856186** [comment]
@alexandergoncharov Thanks
