### ISSUE TITLE
[Error] Unable to find either of the following plist files in order to infer your app's binary version

### ISSUE THREAD

**Issue by IceApriler** [Microsoft/react-native-code-push#1481]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. ```
   code-push release-react operator_app_ios ios
   ```

### Expected Behavior
Release app

### Actual Behavior
Wrong report
```
Detecting ios app version:

[Error]  Unable to find either of the following plist files in order to infer your app's binary version: "ios/operator-app/Info.plist", "ios/Info.plist". If your plist has a different name, or is located in a different directory, consider using either the "--plistFile" or "--plistFilePrefix" parameters to help inform the CLI how to find it.
```


### Environment

* react-native-code-push version: 5.5.0
* react-native version: 0.57.7
* iOS/Android/Windows version: xcode ios simullator
* Does this reproduce on a debug build or release build? develop build
* Does this reproduce on a simulator, or only on a physical device? simulator

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @IceApriler,
Thanks for reporting!

Could you please ensure that your app have `plist.info` in this path "ios/operator-app/Info.plist" or "ios/Info.plist"?

**Comment by IceApriler** [comment]
> Hi @IceApriler,
> Thanks for reporting!
> 
> Could you please ensure that your app have `plist.info` in this path "ios/operator-app/Info.plist" or "ios/Info.plist"?

Yes, I have `info.plist` in the path `ios/operator-app/Info.plist`

**Comment by IceApriler** [comment]
> Hi @IceApriler,
> Thanks for reporting!
> 
> Could you please ensure that your app have `plist.info` in this path "ios/operator-app/Info.plist" or "ios/Info.plist"?
@alexandergoncharov 
Uh, it's my fault. Sorry, it's my path name that went wrong. I'm very sorry.!

**Comment by alexandergoncharov** [comment]
Sure, no worries :)
Thanks for keeping us in touch!

**Comment by pragneshpj** [comment]
can you please tell how can i solve this issue?

**Comment by vinicanuto** [comment]
> can you please tell how can i solve this issue?

Hi, i did fix it by looking at my folder: "ios/appName", after i saw that the "name" of my package.json was different : "aplicationName". All that i had to do was to change the "name" of my package.json to "appName", to match the folder inside ios directory.

**Comment by chramos** [comment]
the name in package.json should match exactly the same project name

**Comment by darron1217** [comment]
![image](https://user-images.githubusercontent.com/8064923/101727204-69b90b80-3af7-11eb-9b38-6cdfbcbcca61.png)
The problem is, my IDE (webstorm) suggests to use kebab-case on package.json's "name". (While react-native automatically creates ios project name with PascalCase)

**Comment by gabrielmoncea** [comment]
You can fix that error and pass `-p|--plist-file <arg>` to link the plist file location
