### ISSUE TITLE
An update is available but it is not targeting the binary version of your app.

### ISSUE THREAD

**Issue by eyalabadi98** [Microsoft/react-native-code-push#1485]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. I upload a version of my app (1.75) to my phone
2.  I change 1 line of code (something i can distinguish)
3. I use the command code-push release-react MyAppName ios -d "Production" --description "changed number to 29" -m
4. I then check the logs from xcode of my physical device and see "An update is available but it is not targeting the binary version of your app."

### Expected Behavior
I expect my app to update to this version

### Actual Behavior
The app doesnt update and throws the error "An update is available but it is not targeting the binary version of your app." I dont change the app version anywhere in this setup. My History is: 
![image](https://user-images.githubusercontent.com/3536706/50375915-38ac4b80-0640-11e9-8d28-3387d86ab7fc.png)

```
  STACK TRACE AND/OR SCREENSHOTS
![image](https://user-images.githubusercontent.com/3536706/50375891-de12ef80-063f-11e9-90a6-625e5407212b.png)

```

### Environment

* react-native-code-push version: ^5.5.1
* react-native version:^0.57.2
* iOS/Android/Windows version: IOS 12
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? my physical device (on release) says the above error, on my simulator (debug) it has another rollout error, but its not in the scope of this question)

(The more info the faster we will be able to address it!)

**Comment by yuri-kulikov** [comment]
Hi @eyalabadi98,
Thanks for reporting!

Can you please make sure you are running version 1.75 of the app on your device? Yes, it's kinda obvious :) , but something could have happened, for example, some problems with updating the app or something else.

**Comment by eyalabadi98** [comment]
Hey, thanks for the reply.

But yes, I uploaded by app through Xcode (and the app is on 1.75) so it’s by default the latest version

Eyal Abadi

On Dec 24, 2018, at 6:52 AM, Yuri Kulikov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @eyalabadi98<https://github.com/eyalabadi98>,
Thanks for reporting!

Can you please make sure you are running version 1.75 of the app on your device? Yes, it's kinda obvious :) , but something could have happened, for example, some problems with updating the app or something else.

**Comment by eyalabadi98** [comment]
Hello @yuri-kulikov.

I am getting: 
[tid:com.facebook.react.JavaScript] [CodePush] queryPackage: 1.73
2018-12-26 08:30:02.807 [info][tid:com.facebook.react.JavaScript] [CodePush] update: 1.76

The update version is correct, but not the queryPackage.

Here is my Xcode
![image](https://user-images.githubusercontent.com/3536706/50447363-9fec2900-08e8-11e9-96fc-3f667a28ef3a.png)

**Comment by yuri-kulikov** [comment]
@eyalabadi98 and if you change the version of the app and run the app using Xcode, do you get this log message?
![screenshot 2018-12-27 at 20 40 15](https://user-images.githubusercontent.com/42337914/50489297-f0ae6f80-0a17-11e9-8795-d3cf82fdc805.png)

**Comment by yuri-kulikov** [comment]
Hi @eyalabadi98, unfortunately, we haven’t heard from you in a while, so I'll close the issue for now, but please feel free to reopen it if you have any further questions or new details.

**Comment by hadare1** [comment]
Hi , I have the same issue.
I added the console.logs that you requested. 

I also console.logged the update, localPackage and config objects: 

![Screen Shot 2020-01-22 at 10 14 32 PM](https://user-images.githubusercontent.com/32154203/72961053-be7b5880-3d64-11ea-869e-b17d2c2d83e5.png)


as you can see the localPackage is undefined and therefore I get the error.

am I missing something?

**Comment by Kevin452** [comment]
update  {updateAppVersion: true, appVersion: '4.1.5'}
CodePush.js:56 queryPackage  {appVersion: '4.1.4'}
logging.js:3 [CodePush] An update is available but it is not targeting the binary version of your app.
logging.js:3 [CodePush] App is up to date.

Hi , I have the same issue，No prompt to update

**Comment by CoryWritesCode** [comment]
Still an issue on latest `react-native-code-push: 7.1.0`
This is what I get

![image](https://user-images.githubusercontent.com/34924300/220741209-f0012356-8dc4-416c-ac08-05a04833f407.png)
