### ISSUE TITLE
Update build.gradle to get rid of compile deprecation warnings

### ISSUE THREAD

**Issue by MrLoh** [Microsoft/react-native-code-push#1486]
Please update the build.gradle to use `implementation` instead of compile. Currently gradle errors on new RN projects with

```
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```

This applies to appcenter-analytics and appcenter-crashes as well. It seems like the standalone Android packages of appcenter have already been updated.

### Environment

* react-native-code-push version: 5.5.1
* react-native version: 0.57.8

**Comment by MrLoh** [comment]
See related appcenter issue: https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/501

**Comment by yuri-kulikov** [comment]
Hi @MrLoh,
Thanks for reporting!

Yes, we know about this issue and have plans to fix it in the nearest future. You can read more about it [here](https://github.com/Microsoft/react-native-code-push/pull/1477).
