### ISSUE TITLE
react-native's bridge.bundleURL is read-only

### ISSUE THREAD

**Issue by jedlau** [Microsoft/react-native-code-push#149]
Running react-native-code-push@1.5.2-beta and react-native@0.18.0-rc. RCTBridge.h defines bundleURL as follows:

```objc
@property (nonatomic, strong, readonly) NSURL *bundleURL;
```

This breaks the build with the following error in CodePush.m:224:
```
CodePush.m:224:31: Assignment to readonly property
```

**Comment by jedlau** [comment]
Problem doesn't exist in react-native-code-push@1.5.3-beta.

**Comment by lostintangent** [comment]
Hey @jedlau, yeah RN 0.18.0 broke us so we had to release an update to fix this issue. You should be good to go with the latest bits but let us know if you run into any new issues. Thanks!

**Comment by JRJian** [comment]
Hey @lostintangent , how do you fix it?

**Comment by JRJian** [comment]
finally, i found the solution in #139 ! thks
