### ISSUE TITLE
Can I rollback to the very begining version?

### ISSUE THREAD

**Issue by jamessawyer** [Microsoft/react-native-code-push#1490]
### Steps to Reproduce
1.bundle app with version 1.0.0
2.update app in production using codepush, generate update Label V1
3. I update some native side code, so bundle new app with version 1.0.1
4. update app again in production using codepush, only target version 1.0.1 release, generate update Label V2
5. However I found something wrong in my V2 updation, so I want to rollback to the very begining verion 1.0.1, I search hard to find a solution, but no luck.

### Expected Behavior
Roll back to the begining version 1.0.1

### Actual Behavior
Try to use command 'code-push rollback my_app Production --targetRelease V1', but says 'no rollback version available', I know this command is wrong, but I have no idea what to do.

### Environment

* react-native-code-push version: 5.4.2
* react-native version: 0.57.2
* iOS/Android/Windows version: 1.0.1
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? physical device

Thanks in advance!

**Comment by yuri-kulikov** [comment]
Hi @jamessawyer,
Thanks for your question!

I noticed one mistake in your rollback command: `code-push rollback my_app Production --targetRelease V1`
The right way to set release label is `v1`.

But you can't do a rollback if target binary versions do not match (`1.0.0` for `v1` and `1.0.1` for `v2`).
You can use [this command](https://github.com/Microsoft/code-push/tree/master/cli#patching-update-metadata) to fix it:
```
code-push patch my_app Production -l v1 --targetBinaryVersion "<=1.0.1"
code-push patch my_app Production -l v2 --targetBinaryVersion "<=1.0.1"
```
and then this command should work:
```
code-push rollback my_app Production --targetRelease v1
```
you'll get a new release with label `v3`, and it will a copy of `v1` (with target binary version `<=1.0.1`).
And after that you can restore your target versions for your releases, if you want:
```
code-push patch my_app Production -l v1 --targetBinaryVersion "1.0.0"
code-push patch my_app Production -l v2 --targetBinaryVersion "1.0.1"
code-push patch my_app Production -l v3 --targetBinaryVersion "1.0.1"
```

**Comment by jamessawyer** [comment]
@yuri-kulikov I tried command `code-push patch my_app Production -l v1 --targetBinaryVersion "<=1.0.1"` ,but got an error:   '--targetBinaryVersion <=1.0.1' not support.

**Comment by jamessawyer** [comment]
PS,I use code-push cli version 2.1.9, if it matters

**Comment by jamessawyer** [comment]
Thanks so much for your help. Actually I use [this library](https://github.com/lisong/code-push-server) for my custom file hoisting. I thought it has no effect on code-push cli, so I didn't mension it at first. Now I think it maybe it does matter to codepush cli, I will make it clear first. I'll close it for moment. And reopen it if I still have doubts Later. Thanks again! @yuri-kulikov

**Comment by yuri-kulikov** [comment]
Sure, always glad to help! 👍
