### ISSUE TITLE
[Question] Is this expected? Non mandatory update shows as mandatory on Staging

### ISSUE THREAD

**Issue by vrgimael** [Microsoft/react-native-code-push#1495]
Hi all, thanks for helping!

This is pretty simple to understand: basically, **codePush.checkForUpdate** returns **isMandatory: true** even when the update is NOT mandatory, but only on Staging. It works fine in production.

Obviously the Staging version isn't my greatest concern but I'm wondering whether this is the expected behaviour or is there something wrong on my build?

### Steps to Reproduce
1. Make a staging non-mandatory update
2. Run **codePush.checkForUpdate** and check **isMandatory** value
3. It returns **true** even though the update isn't mandatory

### Expected Behavior
> isMandatory should be false

### Actual Behavior
> isMandatory is true

This code results in the image below:

```javascript
const deploymentKey = await getCodepushKey()
const update = await codePush.checkForUpdate(deploymentKey)
console.log('[codepushCheck] response', { update, initial })
```
<img width="382" alt="screenshot 2019-01-05 at 15 32 59" src="https://user-images.githubusercontent.com/14969223/50726163-ff281580-1100-11e9-8296-fcb5814f0c3b.png">

And as you can see, the update is NOT supposed to be mandatory.

<img width="542" alt="screenshot 2019-01-05 at 15 33 26" src="https://user-images.githubusercontent.com/14969223/50726162-ff281580-1100-11e9-9db7-52accacaf0e0.png">

### Reproducible Demo

Not sure how to reproduce this as data that is coming from the server seems incorrect.

### Environment

* react-native-code-push version: 
> 5.4.2
* react-native version: 
> 0.57.8
* iOS/Android/Windows version: 
> iOS 12
* Does this reproduce on a debug build or release build?
> Haven't tested it on release but can't see how it would be different
* Does this reproduce on a simulator, or only on a physical device?
> Happens on both

**Comment by alexandergoncharov** [comment]
Hi @vrgimael ,
Thanks for reporting!

No, it isn't expected and strange issue. I just tested it on my test project and I can't reproduce it. All works correct for me.

Also, `Staging` deployment differs from `Production` deployment only in name and this names just default example names. You can create new deployment with any name.

So, Could you please try to release one more update and check if result is the same? Please let me know your results or if you have any questions.

Thanks,
Alexander

**Comment by vrgimael** [comment]
Hi @alexandergoncharov, thanks for getting back. 

Working on a different project now, will test again and get back asap

**Comment by alexandergoncharov** [comment]
Hi @vrgimael, just a friendly ping :)

**Comment by alexandergoncharov** [comment]
Hi @vrgimael,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by codesinghanoop** [comment]
@alexandergoncharov The same thing is happening with me in the production deployment. The meta data of codepush return isMandatory as true however it shows false in the appcenter dashboard. Stuck here for a while any help would be appreciated.

**Comment by yijinc** [comment]
The same problem is happening with me in the production deployment

**Comment by letam245** [comment]
same happen for me on Staging as well. I also got random result for checkForUpdate(), run on staging scheme from Xcode but sometime, update return true sometime false. not sure what I have to do to debug that. There are new version available on appCenter on Staging. Can we reopen this issue please?

**Comment by lybrooks** [comment]
the same problem is happening with me

 "react-native-code-push": "^7.0.3",
"react-native": "0.64.2",

**Comment by saczuac** [comment]
Same issue happening with me.

**Comment by saczuac** [comment]
Reopen this issue please, it has no sense that you release a code-push with `--mandatory false` and when you check with `checkForUpdate` in stating is `true`

**Comment by saczuac** [comment]
@alexandergoncharov-zz
