### ISSUE TITLE
Updates not displaying on Appcenter Builds (iOS)

### ISSUE THREAD

**Issue by itsandrewsmith** [Microsoft/react-native-code-push#1497]
I've just followed all the steps to adding code-push to my React Native app and have sent out a few tester updates. I can see from the Appcenter CLI and the Appcenter GUI that I've successfully pushed and installed these updates on my device here, but I don't actually see any changes in the app. 

Here's where I'm confused -- when I tried doing this without Appcenter, e.g just running release mode locally through Xcode, things seemed to work fine, which leads me to believe I'm missing something when updating/releasing the Appcenter builds.

A new build takes ~20 minutes to complete on Appcenter so this has become somewhat difficult to debug, and after looking through the issues here I see some similar issues, but nothing quite the same. 

Any help/guidance would be greatly appreciated, thanks!

I'm using: "react-native-code-push": "^5.5.1" and my React Native info: 
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
      Memory: 81.20 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 3.10.10 - ~/development/work/sessionz/sessionz-app/node_modules/.bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.3, 28.0.2
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
```

This is where I wrap my app component: 
```
const options = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.ON_NEXT_RESUME
}

AppRegistry.registerComponent("MyApp", () => codePush(options)(MyApp))
```

This is just for iOS, haven't tried Android. Thanks again!

**Comment by itsandrewsmith** [comment]
Just an update on this -- I was able to get the Appcenter build to update with a new CodePush deployment, however after toggling foreground and background and closing/opening the app, it's reverted back to the old (unchanged) build. Weird, I'm wondering what I've done wrong...

**Comment by yuri-kulikov** [comment]
Hi @itsandrewsmith,
Unfortunately, we haven’t heard from you in a while, so I'll close the issue for now, but please feel free to reopen it if you have some additional details or questions.
