### ISSUE TITLE
"React-native link" request android development key always

### ISSUE THREAD

**Issue by HighSoftWare96** [Microsoft/react-native-code-push#1498]
### Steps to Reproduce
1. Install codepush in the application
2. react-native link [react-native-code-push]
3. The api asks the android code push development key even it is already in the strings.xml file

### Expected Behavior
It should not request it if already present.

### Actual Behavior
It request always the development key and sometimes it duplicates it generating more errors.

### Environment

* react-native-code-push version: 5.5.1
* react-native version: 0.57.7
* iOS/Android/Windows version: iOs 12

**Comment by yuri-kulikov** [comment]
Hi @HighSoftWare96,
Thanks for reporting!

You're right, we already know about this problem, we have a [similar open issue](https://github.com/Microsoft/react-native-code-push/issues/1415) at the moment, so I'll close this issue, and start working on it in the nearest future!
