### ISSUE TITLE
Signature validation silently skipped if no CodePushDeploymentKey specified in Info.plist

### ISSUE THREAD

**Issue by dgobaud** [Microsoft/react-native-code-push#1500]
### Steps to Reproduce
In Info.plist set a CodePushPublicKey but no CodePushDeploymentKey.

### Expected Behavior
Unsigned CodePush updates to NOT install - CodePushPublicKey is set.

### Actual Behavior
Unsigned CodePush updates install.

### Bug
https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/CodePushConfig.m#L52

`initWithObjectsAndKeys` ends assignment early if `deploymentKey` is `nil` thus skipping the assignment of `publicKey`

```
    _configDictionary = [[NSMutableDictionary alloc] initWithObjectsAndKeys:
                            appVersion,AppVersionConfigKey,
                            buildVersion,BuildVersionConfigKey,
                            serverURL,ServerURLConfigKey,
                            clientUniqueId,ClientUniqueIDConfigKey,
                            deploymentKey,DeploymentKeyConfigKey,
                            publicKey,PublicKeyKey,
                            nil];
```

**Comment by alexandergoncharov** [comment]
Hi @dgobaud ,

PR https://github.com/Microsoft/react-native-code-push/pull/1501 already in Master and will be in the next release.
So, I'm going to close this issue for now. Please feel free to reopen it if you have any questions or face this issue again.
