### ISSUE TITLE
codepush.tools linkrot

### ISSUE THREAD

**Issue by jhabdas** [Microsoft/react-native-code-push#1503]
IIRC this was your domain: http://codepush.tools. Please renew your domain to prevent linkrot. GoDaddy is waiting...

**Comment by alexandergoncharov** [comment]
Hi @jhabdas,
Thanks for reporting!

Yeah, http://codepush.tools has expired but we replaced all this links with this one: https://microsoft.github.io/code-push/
This site is the same. So, you can use it as old site.

I'm going to close this issue for now but please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by jhabdas** [comment]
Fair enough. I'm preserving link vestiges so I'll add a strikethrough and a link to the archived redirect: https://web.archive.org/web/20160402102250/http://codepush.tools/
