### ISSUE TITLE
[CodePush] An error occurred during sync. 404: Not found deployment, check deployment key is right..

### ISSUE THREAD

**Issue by ervivek40** [Microsoft/react-native-code-push#1506]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. I've cloned this repository.
2. Then i have added app in code push with name CodePushCordovaDemo.
3. I got keys staging and production.
4. Changed the keys in both config.xml file
5. Then run the application.
6. Changed version number in both the xml and some text in index.html in staging.
7. Then released.
8. Then closed and opened the app and i'm getting error [CodePush] An error occurred during sync. 
9. debug in safari 404: Not found deployment, check deployment key is right.. StackTrace:

### Expected Behavior
What you expected to happen?
Get And update alert even update there or not
### Actual Behavior
What actually happens?
error : 
[CodePush] An error occurred during sync. 404: Not found deployment, check deployment key is right.. StackTrace: #5

```
  STACK TRACE AND/OR SCREENSHOTS
https://drive.google.com/open?id=1gMWT7VqRgSHD2YNEz016qs4ATADDWRg4
https://drive.google.com/open?id=1VKEaymNmx2tiTZxztKVZUjNZCSqdu-gG
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* cordova-code-push version:4.2.1
* iOS/Android/Windows version:12
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? simulator

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @ervivek40,

This is `react-native-code-push` repo but I see that you opened similar issue in cordova-plugin-code-push: https://github.com/Microsoft/cordova-plugin-code-push/issues/495
So, let's continue our conversation there.
I'll close this issue as duplicate.

**Comment by ervivek40** [comment]
Sorry, Thanks 👍
