### ISSUE TITLE
How do I get back to the local version?

### ISSUE THREAD

**Issue by lhjzzu** [Microsoft/react-native-code-push#1510]
When I update the binary version, at this point, I have a js version locally， I packed it myself。Later， I use "promote" publish a new js version to "Production"。However, I find the js version is broken。 At the moment, I want to rollback to my local js version。When I excute "code-push rollback xxxxx Production", It reported such an error, "Cannot perform rollback because there are no prior releases to rollback to"。 How do I get back to my local version?

**Comment by yuri-kulikov** [comment]
Hey @lhjzzu,
Thanks for reporting!

You can disable this CodePush release and no one will be able to download this broken update, but it won't fix the problem for devices that have already downloaded the update. Also, you can release a new update with the fixed or old (if you still have the previous version of your code) js code to fix the app for those who downloaded your first release. 

There is a way to roll back (on a particular device) to the local version without releasing a new CodePush update if you reinstall the app or delete the app data (after disabling the first CodePush release).

Please let me know if it was helpful for you and ask me if you have any questions!

**Comment by lhjzzu** [comment]
I got it, thank you very much for your answer。

**Comment by yuri-kulikov** [comment]
Great, glad to help!
I'll close the issue for now, but please feel free to reopen it if you have any further questions.
