### ISSUE TITLE
Allow manual versioning for code-push release-react

### ISSUE THREAD

**Issue by rnagella** [Microsoft/react-native-code-push#1511]
Hi there,

The `code-push release-react` command auto update the version from it's previously uploaded. Is there a way to manually control this versioning ?

> Current Behavior

- Previous version on App Center `v1`
- Next version on App Center is `v2` when pushed a release via `code-push release-react`

> Expecting Behavior

- Previous version on App Center `v1`
- Next version on App Center I want to see `v10` or `some sort` instead of `v2` by passing version value of my choice `code-push release-react --customVersion v10`

**Comment by alexandergoncharov** [comment]
Hi @rnagella,
Thanks for reporting!

Unfortunately it isn't possible to set specific label for release. It is implemented like this for preventing version confusion and CodePush just take last available version.
Could you please describe why would you like to set specific label version?

**Comment by rnagella** [comment]
@alexandergoncharov One of the main reasons is issue with error tracking tool like Bugsnag, when uploaded source map we need to mention CodePush release number, so the errors are grouped approximately by version.

1. since not each version promoted from staging to beta to production, I don't have a single source of truth for my source map on bug tracking system.

Let say, I have the following scenarios 
v1 released to staging -> Staging is on version v1 
v2 released to staging -> Staging on version v2
v2 is now promoted from staging to beta -> Beta is now on version v1
v3 released to staging -> Staging is on v3
v3 is now promoted from staging to beta -> Beta is on v2
v2 Beta is now promoted to production -> Production version is version v1

so, my source map now fails because Staging is on V3, Beta is on V2, Production is on V1. Where my uploaded source map on my bug tracking system is with v3.

**Comment by rnagella** [comment]
Another reason, I have white label of apps and I would like the release to be numbered same across the apps. In addition, I want to see the release version to be the same across the platforms(iOS and Android)

Allowing manual version which help me to
Solve the above problems.

**Comment by AshleyMedway** [comment]
Is there still no way to achieve this? We'd like for the codepush versions to match the version from our build server.

The [documentation here](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#releasing-updates-general) shows a `-v | --version` parameter but looking at the source code for the cli there is no parameter.
