### ISSUE TITLE
App Center Error Saying CodePush Not Supported for UWP

### ISSUE THREAD

**Issue by nbwiller** [microsoft/react-native-code-push#1514]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Follow the instructions for setting up a React-Native UWP at: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#windows-setup
2. Follow the instructions for making a CodePush release at: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#releasing-updates-react-native
3. Try releasing an update with 'appcenter codepush release -c .\windows\CodePushPrototype\ -t * -d Staging'
4. Receive error 'App CodePush-Prototype uses a platform type not supported by CodePush: "UWP"'

### Expected Behavior
Expected a release to properly be made

### Actual Behavior
What actually happens?
```
  App CodePush-Prototype uses a platform type not supported by CodePush: "UWP"
```

### Reproducible Demo

This appears to be an issue with App Center CLI, not the UWP and so I do not have a demo to upload.

### Environment

* react-native-code-push version: 6.4.1
* react-native version: 6.4.1
* iOS/Android/Windows version: N/A
* Does this reproduce on a debug build or release build? N/A
* Does this reproduce on a simulator, or only on a physical device? N/A

(The more info the faster we will be able to address it!)

I should also note a similar issue to this was opened quite a while ago with no clarification on why it was closed and whether or not it was every fixed: https://github.com/Microsoft/code-push/issues/462

**Comment by yuri-kulikov** [comment]
Hi @nbwiller,
Thanks for report and sorry for the delay!

We tried to reproduce the issue, but `appcenter codepush release` works fine even with UWP applications. 

For example:
- I've created an app `appcenter apps create -p React-Native -o Windows -d uwpApp`.
- then I've created a deployment `appcenter codepush deployment add -a yuri.kulikov/uwpApp Staging`
- and then released an update `appcenter codepush release -a yuri.kulikov/uwpApp -c ./windows/uwpApp -d Staging -t="*"`

Result:
![screenshot 2019-01-29 at 19 21 42](https://user-images.githubusercontent.com/42337914/51923611-62555100-23fc-11e9-82fd-d2fe8a2738f8.png)

Can you please clarify which AppCenter CLI version you are using (`appcenter -v`)?
You also can try the old CodePush CLI (`code-push release` command) or you can try `appcenter codepush release-react -a [your_app_full_name] -d Staging -t="*"` command.

Please share the results and let us know if it helped!

**Comment by nbwiller** [comment]
Hey @yuri-kulikov, thanks for looking into this. So I tried the commands you gave and they did work. My mistake when attempting this from the command line was I did 'appcenter apps create -o Windows -p "_React Native_"' -d Name' which did not work because I used a space instead of a hyphen in the -p argument. This method of creating a React-Native app is not specified anywhere in the documentation for windows (it only mentions iOS and Android). In addition, the UI of App Center does not allow for this, as shown in the attached picture.
![appcenterpic](https://user-images.githubusercontent.com/7489644/51929712-b8e76e80-23ad-11e9-8e91-0eb480099d8f.PNG)

As an aside, I was able to get CodePush working for my UWP by ingesting it as an Android React-Native app. I doubt this is really an issue, but thought I'd mention it in case that was not intended to be possible. 

Thanks for the response! Any chance you can update the App Center docs to include this info?

**Comment by yuri-kulikov** [comment]
@karlFrascari2, thanks for your feedback!

> Any chance you can update the App Center docs to include this info?

Sure, we'll fix the docs. Until then, we'll keep the issue open.

**Comment by MakhouT** [comment]
@yuri-kulikov So is code-push usable with react native and UWP? In Appcenter I cannot select the combination react native and uwp.
Like this screenshot
![image](https://user-images.githubusercontent.com/3041165/58387533-2c258800-8010-11e9-8385-1ddf38ad843c.png)

**Comment by yuri-kulikov** [comment]
@MakhouT the main problem is that **UWP** and **React-Native** are platforms, so you can't just choose both at the same time.

The easiest way to create such an application is to use the AppCenter CLI:
```sh
appcenter apps create -p React-Native -o Windows -d AppName
```

**Comment by MakhouT** [comment]
Ok got it. Will be using the CLI then.

Suggestion though. Won't it make sense to add a Platform that says 'UWP - React native' then?

Any way, I can move on using the CLI for now.

**Comment by yuri-kulikov** [comment]
> Won't it make sense to add a Platform that says 'UWP - React native' then?

@MakhouT yeah, sounds reasonable, I'll raise the question.

**Comment by kgstew** [comment]
Using appcenter cli v2.4.0 
Running `appcenter apps create -p React-Native -o Windows -d Foo_application` 

This works and generates the new app and displays it on the web. However the Appcenter UI shows `Your app currently isn’t supported, but you can continue to use the CodePush CLI and service with it.` No options are available for the app.

For now is this the only option for interacting with this type of app? Is there another set of configuration options that will work for both the cli and the web UI? Say configuring with android as the os and using React-Native as the platform as @nbwiller suggested?

Any plans to add this configuration to AppCenter in the future?

<img width="1407" alt="Screen Shot 2020-04-08 at 6 39 37 PM" src="https://user-images.githubusercontent.com/1108959/78849406-41599a00-79c9-11ea-95e7-2762703850a1.png">

**Comment by ramya298** [comment]
Hi,

I want to integrate React-Native Window application in AppCenter .
i tried creating cli using same command mentioned above.
"appcenter apps create -p React-Native -o Windows -d Foo_application" but below error.

Could any one clarify us telling will the  Appcenter Codepush  is possible for React-Native Window application ?



![image](https://user-images.githubusercontent.com/32768142/93794840-3f715380-fc56-11ea-8d22-828ba0ceff62.png)

**Comment by ShaoGongBra** [comment]
有人解决吗

**Comment by WilliamWelsh** [comment]
Anyone? Seems maintainers ignored and closed without solution. React Native/Windows combo still isn't available, despite code push docs showing how to set up CodePush but not how to release it or set it up on AppCenter

**Comment by lucen-ms** [comment]
We do not officially support this combination and we do not have plans to add support for it.
But of course, you can try to make it work with CLIs.
