### ISSUE TITLE
Hot update content on IOS is restored, help me!!!

### ISSUE THREAD

**Issue by giantss** [Microsoft/react-native-code-push#1516]
Using the hot update to refresh the interface immediately after updating on ios, but if the user restarts the app, the hot update will be restored to the previous content, which looks like `main.jsbundle` is not saved.
### Steps to Reproduce
1. execute` code-push release-react appName ios  --t 5.6.0 --dev false --d Staging --des "\n1、xxx。" --m false`
2. Open a previous app that requires a hot update.
3. Click the OK button to update the interface automatically after waiting for the hot update.

The first three steps are all normal。

4. When the user restarts the app, the content of the hot update is no longer available (revert to the version before the hot update), and there is no hot update prompt box.

### Expected Behavior
When the user restarts the app, the content is already the latest hot update.

### Actual Behavior
When the user restarts the app, the content of the hot update is no longer available (revert to the version before the hot update), and there is no hot update prompt box.

### my key code

```
let codePushOptions = {
  checkFrequency : CodePush.CheckFrequency.MANUAL
}

  componentWillMount() {
    CodePush.disallowRestart()
    this.syncImmediate()
  }

  componentDidMount() {
    CodePush.allowRestart()
  }

CodePush.sync(
      {
        deploymentKey: CODE_PUSH_KEY,
        // updateDialog: {},
        installMode: CodePush.InstallMode.IMMEDIATE,
        updateDialog : {
          appendReleaseDescription : false ,
          mandatoryContinueButtonLabel : "极速下载" ,
          mandatoryUpdateMessage : "下载更新内容" ,
          optionalIgnoreButtonLabel : '取消' ,
          optionalInstallButtonLabel : '极速下载' ,
          optionalUpdateMessage : '下载更新内容' ,
          title : '更新提示'
        } ,
      },

export default CodePush(codePushOptions)(UpdateComp)

```

### Environment

* react-native-code-push version: 5.4.2
* react-native version: 0.53.0
* iOS/Android/Windows version: iOS all versions
* Does this reproduce on a debug build or release build? Yes
* Does this reproduce on a simulator, or only on a physical device?  physical device

**Comment by yuri-kulikov** [comment]
Hi @giantss,
Thanks for reporting!

Could you please share the logs from Xcode console (there should be some messages tagged with `[CodePush]`)?
Also, is it a debug build?

**Comment by giantss** [comment]
Sorry. I forgot to annotate `AppDelegate` on the code below.
`jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];`
