### ISSUE TITLE
File not found: assets://index.js in any of the project roots

### ISSUE THREAD

**Issue by itayga** [Microsoft/react-native-code-push#1517]
### Steps to Reproduce
1. integrate the code push library as described in the [docs](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native) 
2.run the app on dev or release  

we are using react native navigation V2 on our project but when I execute CodePush.getJSBundleFile("index") it can't find the assets://index.js in any of the project roots

### Expected Behavior
the app should run and cade updates should be applied once available 
### Actual Behavior
can't run the app since the js bundle can't be found when calling CodePush.getJSBundleFile("index")

### Environment

* react-native-code-push version:5.4.0
* react-native version:0.56.0
* iOS/Android/Windows version:8.1.0
* Does this reproduce on a debug build or release build? debug and release
* Does this reproduce on a simulator, or only on a physical device? physical device
* gradle plugin : gradle-4.4
* gradle build version : com.android.tools.build:gradle:3.1.4
* react-native-navigation V2

**Comment by alexandergoncharov** [comment]
Hi @itayga,
Thanks for reporting!

Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by alexandergoncharov** [comment]
Hi @itayga,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
