### ISSUE TITLE
android bundling requires outputdir to be CodePush/CodePush

### ISSUE THREAD

**Issue by bars0um** [Microsoft/react-native-code-push#1520]
### Steps to Reproduce
1. bundle your code manually ( i wanted to so I could run a --reset-cache and ensure my env vars were refreshed)

```
ENVFILE=.env.test react-native bundle --reset-cache --assets-dest ../CodePush/1.0/android/test --bundle-output ../CodePush/1.0/android/test/index.android.bundle --dev false --entry-file index.js --platform android
```
2. try to push this bundle

```
 code-push release myapp ../CodePush/1.0/android/test/ -d Test 1.0 -k ../privkey.pem  -m --description "'version 1.0"
```

3. run your application...it may or may not update bundles but either way the update fails...

### Expected Behavior
What you expected to happen?

Successful update...

### Actual Behavior
What actually happens?

No update happens unless I add CodePush/CodePush into my directory path, then everything works as expected...like this:

```
ENVFILE=.env.test react-native bundle --reset-cache --assets-dest ../CodePush/1.0/android/test/CodePush/CodePush/ --bundle-output ../CodePush/1.0/android/test/CodePush/CodePush/index.android.bundle --dev false --entry-file index.js --platform android

code-push release myapp ../CodePush/1.0/android/test/CodePush/CodePush -d Test 1.0 -k ../privkey.pem  -m --description "'version 1.0"
```

Please note that this does NOT happen with ios bundling...

### Environment

* react-native-code-push version: 2.1.9
* react-native version: 0.57
* iOS/Android/Windows version: android sdk 28
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? simulator and physical

**Comment by alexandergoncharov** [comment]
Hi @bars0um,
Thanks for reporting!

Could you please try to test this scenario with [appcenter](https://github.com/Microsoft/appcenter-cli) cli instead of `code-push` cli and let me know your results?

Please let me know if you have any questions.

**Comment by alexandergoncharov** [comment]
Hi @bars0um,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
