### ISSUE TITLE
New Production deployment not received after previous one rolled back (Android)

### ISSUE THREAD

**Issue by srishanbhattarai** [Microsoft/react-native-code-push#1523]
I'm using separate apps for my `dev`, `staging` and `production` environments, and only releasing to the `Production` deployment for each app.

### Steps to Reproduce
1. Release to the `Production` deployment for the `dev` app. Consider this label to be: `v9`.
I use the following command to do this (inside another JS script which is a small wrapper)
```
code-push release-react my-app-dev Android -m -d Production --noDuplicateReleaseError --outputDir ./build
```
2. The app receives the update, but it's a broken update. So, the app rolls back to `v8`.
3. Release to `Production` again.

### Expected Behavior
Expected the second `Production` release to be received on the app.

### Actual Behavior
I successfully release to `Production` again, expecting the new label to be `v10`. But, I do not see it on the deployment list and it is not received on the app.
```
code-push deployment history my-app-dev Production
```

If I release a new build to `Staging`, and then promote it to `Production`, then it works alright, and I get a `v10` release. I used the following command to promote it, and then checked the history as before.
```
code-push promote my-app-dev Staging Production
```

`code-push debug-android` gives me:
```
An update is available, but it is being ignored due to having been previously rolled back.
```

### Environment

* react-native-code-push version:  `^5.5.2`
* react-native version: `0.55.4`
* iOS/Android/Windows version: `Android 8.1.0`
* Does this reproduce on a debug build or release build? `Release`
* Does this reproduce on a simulator, or only on a physical device? `Physical device`

**Comment by alexandergoncharov** [comment]
Hi @srishanbhattarai,
Thanks for reporting!

So, Your update haven't released to CodePush if there is some rollbacks in current deployment? Is it correct?

Could you please ensure that your released your update in correct app and deployment. Also you can check it with UI in [appcenter.ms](https://appcenter.ms/apps).

I just tested you case and all works correct for me.
Please let me know if you have any questions.

Thanks,
Alexander

**Comment by srishanbhattarai** [comment]
@alexandergoncharov 
Hi, 

That is correct. As explained in the example, if `v9` fails and is rolled back to `v8` then a new `v10` release is not shown by the CLI and in appcenter.ms . This all for the `Production` deployment. If I push a new deployment to `Staging`, and promote it to `Production`, then it's all good. 

Also, the reason `v9` fails in the first place seems to be related to #1144, my app crashes when it tries to restart:

```
[04:02:27] Applying full update.
[04:02:28] Loading JS bundle from "/data/user/0/com.<my_app>.dev/files/CodePush/3d5c2b4f7144a1f8dd8686791b650576d23dfe769c8a1dca4649ab9e616d98d6/CodePush/index.android.bundle"
[04:02:28] Restarting app
[04:02:37] Update did not finish loading the last time, rolling back to a previous version.
[04:02:38] Loading JS bundle from "assets://index.android.bundle"
[04:02:41] Reporting CodePush update rollback (v13)
[04:02:43] An update is available, but it is being ignored due to having been previously rolled back.

```

**Comment by srishanbhattarai** [comment]
Changing my `installMode` to use  `ON_NEXT_RESTART` instead of `IMMEDIATE` as suggested [here](https://github.com/Microsoft/react-native-code-push/issues/1144#issuecomment-359760008) seems to do the trick. My app does not crash anymore when applying the update (since it applies it on the next restart?) and if I release a new update it shows up as well.

I also had to change the [`mandatoryInstallMode`](https://github.com/Microsoft/react-native-code-push/blob/099ab06bdcac9f15a65090271e28977953efe456/docs/api-js.md#codepushoptions) since I'm using the `-m` flag on the CLI.

```diff
 /**
 * CodePush options for customized updates.
 */
 const options = {
   updateDialog: true,
-   installMode: codepush.InstallMode.IMMEDIATE,
+   installMode: codepush.InstallMode.ON_NEXT_RESTART,
+   mandatoryInstallMode: codepush.InstallMode.ON_NEXT_RESTART
 }
```

**Comment by alexandergoncharov** [comment]
@srishanbhattarai , Sorry for delay.

I tested your scenario with missed releases after rollback and all works correct for me.

Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug missing releases and your rollback.

**Comment by alexandergoncharov** [comment]
Hi @srishanbhattarai,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
