### ISSUE TITLE
react-native unlink doesnt do a thing?

### ISSUE THREAD

**Issue by isaaclem** [microsoft/react-native-code-push#1525]
I've tried to installed the package and trying to remove it by running below command

```
react-native unlink react-native-code-push
yarn remove react-native-code-push
```

Both commands executed successfully without error however I noticed whatever changes to `AppDelegate.m`/`Info.plist` or `build.gradle` still remain there?

**Comment by alexandergoncharov** [comment]
Hi @isaaclem ,
Thanks for reporting!

Yeah, I reproduced this issue. It removes changes for android but not full changes. And for IOS it doesn't remove changes at all. Investigating.

**Comment by alexandergoncharov** [comment]
Hi @isaaclem 
Sorry for the delay.

PR with adding unlink command already merged in Master and will be released soon.
https://github.com/microsoft/react-native-code-push/pull/1588

So, I'm going to close this issue as it was resolved.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
