### ISSUE TITLE
Cannot read property 'CheckFrequency' of undefined 

### ISSUE THREAD

**Issue by xqwIOS** [Microsoft/react-native-code-push#1526]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.run android  have this problem
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:5.4.2
* react-native version:0.51.0
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? debug build
* Does this reproduce on a simulator, or only on a physical device? simulator

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @xqwIOS ,
Thanks for reporting!

Please ensure that you successfully imported CodePush object. If it was not helpful could you please provide some dummy project with reproducing issue and reporsteps? I would like to debug it.

**Comment by alexandergoncharov** [comment]
Hi @xqwIOS,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

**Comment by baninaveen** [comment]
I am getting the same issue

**Comment by AlmeidaKing** [comment]
Hi,
I having the same issue and try everything i found with no success.

worked for me when i installed another device emulator and run the project again
