### ISSUE TITLE
Builds fail on React Native < 0.58

### ISSUE THREAD

**Issue by TylerNRobertson** [Microsoft/react-native-code-push#1527]
### Steps to Reproduce
1. React native init
2. Link library
3. Try to build the android project

### Expected Behavior
Android project builds with no errors.

### Actual Behavior
<img width="1018" alt="screen shot 2019-02-21 at 2 42 22 pm" src="https://user-images.githubusercontent.com/23481122/53193264-fa52ee80-35e6-11e9-80ac-ae0fec805ecb.png">
```
  STACK TRACE AND/OR SCREENSHOTS
```
See above.

### Reproducible Demo
Unfortunately cannot create a whole new project. But the problem is very simple to recreate.

### Environment
* react-native-code-push version: 5.5.2
* react-native version: 0.58.5
* iOS/Android/Windows version: IOS 10.3, Android API 28
* Does this reproduce on a debug build or release build? Only any android build
* Does this reproduce on a simulator, or only on a physical device? No device

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @TylerNRobertson,
Thanks for reporting!

Unfortunately I can't reproduce it. I created new react-native project, installed code-push plugin, linked and used Android Studio for building and got successfully build.

Could you please share some dummy project with reproducing issue? I would like to debug it.

**Comment by TylerNRobertson** [comment]
Hey apologies but you can close this issue. Turns out it had to do with my migration from RN 0.57.8 to 0.58.5. No issues with the code push library :)

**Comment by alexandergoncharov** [comment]
@TylerNRobertson, got it. Thanks for keeping us in touch!
Please feel free to ping us if you have any questions or issues.
