### ISSUE TITLE
codepush doesn't sync after app relaunch

### ISSUE THREAD

**Issue by devyu** [microsoft/react-native-code-push#1528]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

When I update App with code push, and then killed app. App reset to previous version after app relaunch. 
 

### Actual Behavior

I've just added following code in App.js 

```
// App.js
 componentDidMount () {
    codePush.sync(
      { updateDialog: true, installMode: codePush.InstallMode.IMMEDIATE },
      (syncStatus) => {
        Alert.alert(`status: ${syncStatus}`)
        switch (syncStatus) {
          case codePush.SyncStatus.UP_TO_DATE:
            Alert.alert('UP_TO_DATE')
            break
          case codePush.SyncStatus.UPDATE_INSTALLED:
            Alert.alert('UPDATE_INSTALLED')
            codePush.notifyAppReady()
            break
          case codePush.SyncStatus.UPDATE_IGNORED:
            Alert.alert('UPDATE_IGNORED')
            break
          case codePush.SyncStatus.UNKNOWN_ERROR:
            Alert.alert('UNKNOWN_ERROR')
            break
          case codePush.SyncStatus.SYNC_IN_PROGRESS:
            Alert.alert('SYNC_IN_PROGRESS')
            break
          case codePush.SyncStatus.CHECKING_FOR_UPDATE:
            Alert.alert('CHECKING_FOR_UPDATE')
            break
          case codePush.SyncStatus.AWAITING_USER_ACTION:
            Alert.alert('AWAITING_USER_ACTION')
            break
          case codePush.SyncStatus.DOWNLOADING_PACKAGE:
            Alert.alert('DOWNLOADING_PACKAGE')
            break
          case codePush.SyncStatus.INSTALLING_UPDATE:
            Alert.alert('INSTALLING_UPDATE')
            break
        }
      },
    )
  }


const codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_START }
export default codePush(codePushOptions)(App)
```

When I release new updates, pop up `CHECKING_FOR_UPDATE` alert, and then pop up `UP_TO_DATE`，and then the app update success, but when I kill app and relaunch it, the app goes back to previous updates.

This is a very strange question, did I missing something？

### Environment
* "react-native-code-push": "^5.4.2",
* "react": "16.3.1",
* "react-native": "0.55.4",
* "react-navigation": "^2.6.0",

**Comment by alexandergoncharov** [comment]
Hi @devyu ,
Thanks for reporting!

Yeah, That's strange issue. I just tested it on test project and all works fine for me. Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by alexandergoncharov** [comment]
And what is your issue platform? (Android/IOS)

**Comment by JonsonLius** [comment]
It's a problem with ios and android
+1

**Comment by JonsonLius** [comment]
"react-navigation": "^2.17.0"
 "react-native-code-push": "^5.5.2"
 "react": "16.2.0",
  "react-native": "0.55.4"

CodePush.sync(
            { updateDialog: true},
            (syncStatus) => {
              Alert.alert(`status: ${syncStatus}`)
              switch (syncStatus) {
                case codePush.SyncStatus.UP_TO_DATE:
                  Alert.alert('UP_TO_DATE')
                  break
                case codePush.SyncStatus.UPDATE_INSTALLED:
                  Alert.alert('UPDATE_INSTALLED')
                  codePush.notifyAppReady()
                  break
                case codePush.SyncStatus.UPDATE_IGNORED:
                  Alert.alert('UPDATE_IGNORED')
                  break
                case codePush.SyncStatus.UNKNOWN_ERROR:
                  Alert.alert('UNKNOWN_ERROR')
                  break
                case codePush.SyncStatus.SYNC_IN_PROGRESS:
                  Alert.alert('SYNC_IN_PROGRESS')
                  break
                case codePush.SyncStatus.CHECKING_FOR_UPDATE:
                  Alert.alert('CHECKING_FOR_UPDATE')
                  break
                case codePush.SyncStatus.AWAITING_USER_ACTION:
                  Alert.alert('AWAITING_USER_ACTION')
                  break
                case codePush.SyncStatus.DOWNLOADING_PACKAGE:
                  Alert.alert('DOWNLOADING_PACKAGE')
                  break
                case codePush.SyncStatus.INSTALLING_UPDATE:
                  Alert.alert('INSTALLING_UPDATE')
                  break
              }
            },
          )
          CodePush.notifyAppReady()

**Comment by JonsonLius** [comment]
> 你的问题平台是什么？（机器人/ IOS）

index.js

CodePush.sync();
AppRegistry.registerComponent('screen', () => CodePush(codePushOptions)(screen));
AppRegistry.registerComponent('EndData', () => CodePush(EndData));
AppRegistry.registerComponent('Withdraw', () => CodePush(Withdraw));
AppRegistry.registerComponent('Record', () => CodePush(Record));
AppRegistry.registerComponent('Insurancequotes', () => CodePush(Insurancequotes));
AppRegistry.registerComponent('Allow', () => CodePush(Allow));
AppRegistry.registerComponent('ForgotPWD', () => CodePush(ForgotPWD));

**Comment by devyu** [comment]
> And what is your issue platform? (Android/IOS)

This issue was discovered on iOS.

**Comment by devyu** [comment]
> And what is your issue platform? (Android/IOS)

@alexandergoncharov This issue was discovered on iOS

**Comment by JonsonHI** [comment]
> > And what is your issue platform? (Android/IOS)
> 
> @alexandergoncharov This issue was discovered on iOS

Have you repaired it plese ?

**Comment by alexandergoncharov** [comment]
@devyu, Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by devyu** [comment]
Hi @alexandergoncharov . Sorry, it's too late to reply to you. I wrote a demo in [there](https://github.com/devyu/codepush_issue_1528). This demo was build whit Xcode9.3, you should replace CODEPUSH_KEY, and resigning app. thanks a lot! How can I fix this issue?

**Comment by devyu** [comment]
> @devyu, unfortunately I can't reproduce it. Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

Hi @alexandergoncharov . Sorry, it's too late to reply to you. I wrote a demo in [there](https://github.com/devyu/codepush_issue_1528). This demo was build whit Xcode9.3, you should replace CODEPUSH_KEY, and resigning app. thanks a lot! How can I fix this issue?

**Comment by alexandergoncharov** [comment]
@devyu , Thanks for demo project! I'll investigate it as soon as possible and let you know my results.

**Comment by devyu** [comment]
> @devyu , Thanks for demo project! I'll investigate it as soon as possible and let you know my results.

@alexandergoncharov Thank u, I update the demo project and  recorded a video to find out the problem easily.

**Comment by JonsonHI** [comment]
I'm looking forward to solving this problem. I can't create a demo and my demo will work

**Comment by JonsonHI** [comment]
> > @devyu , Thanks for demo project! I'll investigate it as soon as possible and let you know my results.
> 
> @alexandergoncharov Thank u, I update the demo project and recorded a video to find out the problem easily.

Has your problem been solved yet?

**Comment by devyu** [comment]
> > > @devyu , Thanks for demo project! I'll investigate it as soon as possible and let you know my results.
> > 
> > 
> > @alexandergoncharov Thank u, I update the demo project and recorded a video to find out the problem easily.
> 
> Has your problem been solved yet?

@JonsonHI  Not yet. Do you have a better way?

**Comment by xinghuoliaoyuan45** [comment]
I have this problem too   "react-native": "0.56.0", "react-native-code-push": "^5.3.5",

**Comment by JonsonHI** [comment]
> > > > @devyu，感谢您的演示项目！我会尽快调查，让你知道我的结果。
> > > 
> > > 
> > > @alexandergoncharov谢谢你，我更新了演示项目并录制了一个视频，以便轻松找到问题所在。
> > 
> > 
> > 你的问题已经解决了吗？
> 
> @JonsonHI 还没有。你有更好的方法吗？

Has your problem been solved yet?

**Comment by xinghuoliaoyuan45** [comment]
no

**Comment by xinghuoliaoyuan45** [comment]
I wonder if the reduced version can solve this problem?

**Comment by terijyu** [comment]
+1. We've had multiple code pushes since this issue's first filing in Feb, but we're experiencing this issue on iOS now.

**Comment by terijyu** [comment]
@alexandergoncharov any update on status?

**Comment by alexandergoncharov** [comment]
Hi @devyu,

I'm sorry for this long delay.
I tried to run your app but got next issue: 
![image](https://user-images.githubusercontent.com/13234108/56829846-7b3f9800-686d-11e9-8c31-231e7f82ef91.png)

Also, I investigated your code and I can suggest some changes for test:
1) If you use `codepush.sync()` method then you don't have to check updates manually. `sync()` method do it for you. So, removed this checking.
2) In `codePushOption` you set `checkFrequency` as `ON_APP_START`. This settings means that CodePush will check updates on each starting of App. For more info please check this docs: https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#checkfrequency. And then you used manually `sync` method. So, you should remove `sync` method or change sync method to `MANUAL`. 

Here is commit for this changes: https://github.com/alexandergoncharov/codepush_issue_1528/commit/a5464f825105ea09d486743e403573f8197572c7?diff=split

Could you please tried to test your app with this changes and let me know your results?

**Comment by xinghuoliaoyuan45** [comment]
I finally found out why.so sorry，I  forget this  =》  【export default codePush(codePushOptions)(App)】，

**Comment by xinghuoliaoyuan45** [comment]
The old version of my RNAapp didn't do this either, but there was no problem.

**Comment by xinghuoliaoyuan45** [comment]
Thank you  @alexandergoncharov . I'm like noob on this issue.

**Comment by alexandergoncharov** [comment]
@xinghuoliaoyuan45 That's great! Thanks for letting us know!

@JonsonHI Thanks for help with testing!

@devyu, I'm going to close this issue for now as I haven't heard from you in a while and I can't run your demo app unfortunately.

Please feel free to reopen this issue if you have any questions or fix your demo project.

Thanks,
Alexander

**Comment by Akash-T2S** [comment]
I'm facing this issue, with RN version - 59.9, codepush version - 5.7.2.
