### ISSUE TITLE
Loading mode change

### ISSUE THREAD

**Issue by JonsonHI** [microsoft/react-native-code-push#1533]
Loading mode change
https://github.com/Microsoft/react-native-code-push/issues/1530  
This problem has been fixed. It is my own problem

Can you load it this way?

```
 RCTRootView * rnView = [[RCTRootView alloc] `initWithBridge`:self.bridge
                                                    moduleName:viewName
                                             initialProperties:initialProperty];
```

Not this way
```
 RCTRootView *rootView = [[RCTRootView alloc] `initWithBundleURL`:jsCodeLocation
                                                        moduleName:@""
                                                 initialProperties:nil
                                                     launchOptions:launchOptions];
```

**Comment by devyu** [comment]
@JonsonHI How to fix this issue?

**Comment by JonsonHI** [comment]
> @JonsonHI如何解决这个问题？
I used initWithBridge to create the rootview
Codepush, however, can only be updated using initWithBundleURL.

So the problem is solved

**Comment by alexandergoncharov** [comment]
@JonsonHI so, was your issue #1530 fully fixed?

**Comment by JonsonHI** [comment]
> @JonsonHI so, was your issue #1530 fully fixed?

Yes, Has been resolved.

Can I use it  "initWithBridge"    load  codepush

**Comment by devyu** [comment]
@JonsonHI Could you provide some code in `AppDelegate.m` ?  The default code is:

```
 RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"ModuleName"
                                                 initialProperties:nil
                                                     launchOptions:launchOptions];
```

Maybe you changed AppDelegate load behavior？

**Comment by JonsonHI** [comment]
> @JonsonHI你能提供一些代码`AppDelegate.m`吗？默认代码是：
> 
> ```
>  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
>                                                         moduleName:@"ModuleName"
>                                                  initialProperties:nil
>                                                      launchOptions:launchOptions];
> ```
> 也许你改变了AppDelegate的加载行为？

并没有改变”Appdelegate.m”的代码  
使用
```
RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                        moduleName:@"ModuleName"
                                                 initialProperties:nil
                                                     launchOptions:launchOptions];
```

I used preloading to preload the jsbundle file into memory

**Comment by alexandergoncharov** [comment]
Hi @JonsonHI,

Could you please describe your issue more detailed and why you would like to change `AppDelegate.m` by this way?

**Comment by JonsonHI** [comment]
```
[[RCTRootView alloc] `initWithBridge`:self.bridge
                                                    moduleName:viewName
                                             initialProperties:initialProperty];
```

I used initWithbridge to create the loading of jsbundle so that the program can be optimized

But code-push is to get jsbundle package by means of initWithBundleURL

So there's no way to do that in my program

I can only choose one from two

**Comment by alexandergoncharov** [comment]
Yeah, I see. But I think this code part is not from CodePush as this should be created by react-native project. Could you please share place where you got this code part?

Also, new react-native@0.59 version uses `initWithBridge` method in `AppDelegate.m` file.

**Comment by JonsonHI** [comment]
> Yeah, I see. But I think this code part is not from CodePush as this should be created by react-native project. Could you please share place where you got this code part?
> 
> Also, new react-native@0.59 version uses `initWithBridge` method in `AppDelegate.m` file.

AppDelegate.m

```
 [[ReactRootViewManager manager]  preLoadRootViewWithName:@"Screen"];
```


```
@interface ReactRootViewManager ()
// 以 viewName-rootView 的形式保存需预加载的RN界面
@property (nonatomic, strong) NSMutableDictionary<NSString *, RCTRootView*> * rootViewMap;
@end

@implementation ReactRootViewManager

- (void)dealloc {
    _rootViewMap = nil;
    [_bridge invalidate];
}

+ (instancetype)manager {
    static ReactRootViewManager * _rootViewManager = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _rootViewManager = [[ReactRootViewManager alloc] init];
    });
    return _rootViewManager;
}

- (instancetype)init {
    if (self = [super init]) {
        _rootViewMap = [NSMutableDictionary dictionaryWithCapacity:0];
        _bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:nil];
    }
    return self;
}

- (void)preLoadRootViewWithName:(NSString *)viewName {
    [self preLoadRootViewWithName:viewName initialProperty:nil];
}

- (void)preLoadRootViewWithName:(NSString *)viewName initialProperty:(NSDictionary *)initialProperty {
    if (!viewName && [_rootViewMap objectForKey:viewName]) {
        return;
    }
    // 由bridge创建rootView
    RCTRootView * rnView = [[RCTRootView alloc] initWithBridge:self.bridge
                                                    moduleName:viewName
                                             initialProperties:initialProperty];
    [_rootViewMap setObject:rnView forKey:viewName];
}

- (RCTRootView *)rootViewWithName:(NSString *)viewName {
    if (!viewName) {
        return nil;
    }
    return [self.rootViewMap objectForKey:viewName];
}

#pragma mark - RCTBridgeDelegate
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
    return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
}

@end
```

**Comment by alexandergoncharov** [comment]
Hi @JonsonHI,
I'm sorry for this delay.

Yeah, your provided code from `react-native`. Not from CodePush. Could you please try to use your provided code version?

Please let me know if you have any questions or I missed something

**Comment by alexandergoncharov** [comment]
Hi @JonsonHI,

I'm going to close this issue for now as I haven't heard from you in while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by Andriiklymiuk** [comment]
Has anyone tried to make this library work with initWithBridge ? i tried to do it, but some native events aren't working, if setup is done with initWithBridge instead of initWithBundleURL. Is there right way to do it on latest react native 0.65.1 ?
