### ISSUE TITLE
Support for additional "root" directories

### ISSUE THREAD

**Issue by GioLogist** [Microsoft/react-native-code-push#1534]
### Steps to Reproduce
1. Install babel's [module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) plugin
2. Utilize newly supported imports
3. Build with codepush

### Expected Behavior
App should build fine, as it does with default react native.

### Actual Behavior
Imports are unable to resolve

**Comment by alexandergoncharov** [comment]
Hi @GioLogist,
Thanks for reporting!

Could you please provide more detailed reprosteps or some dummy project with reproducing issue and reprosteps? I would like to reproduce it and debug.

**Comment by GioLogist** [comment]
Sure, i'll try and throw something up this weekend.

**Comment by alexandergoncharov** [comment]
Hi @GioLogist , Just a friendly ping :)

**Comment by alexandergoncharov** [comment]
Hi @GioLogist,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
