### ISSUE TITLE
Execution failed for task ':react-native-code-push:verifyReleaseResources'.

### ISSUE THREAD

**Issue by telmen** [Microsoft/react-native-code-push#1541]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Install react-native@0.58.6, react-native-code-push@5.5.2
### Expected Behavior
What you expected to happen?

Successfully build apk

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
```sh
* What went wrong:
Execution failed for task ':react-native-code-push:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  PROJECT/node_modules/react-native-code-push/android/app/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  PROJECT/node_modules/react-native-code-push/android/app/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  PROJECT/node_modules/react-native-code-push/android/app/build/intermediates/res/merged/release/values/values.xml:957: error: resource android:attr/fontVariationSettings not found.
  PROJECT/node_modules/react-native-code-push/android/app/build/intermediates/res/merged/release/values/values.xml:958: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 5.5.2
* react-native version: 0.58.6
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? It happens when I try to assembleRelease

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @telmen ,
Thanks for reporting!

Could you please clarify more details of approach which you used for creating apk?

**Comment by telmen** [comment]
Hi @alexandergoncharov, I'm closing this issue due to I wasn't using latest version of it. After upgrading to latest version, it works. (My bad for creating a unclear issue)

**Comment by alexandergoncharov** [comment]
@telmen That's great that your issue was resolved. Thanks for keeping us in touch!

**Comment by shibbyy** [comment]
Can we reopen it? Facing exact same issue in:
react-native-code-push version: 5.6.1
react-native version: 0.60.4
