### ISSUE TITLE
disallowRestart stop push

### ISSUE THREAD

**Issue by vance-liu** [Microsoft/react-native-code-push#1542]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Install react-native@0.58.6, react-native-code-push@5.5.2
2. react-native init test --version 0.58.6

### Expected Behavior
What you expected to happen?
Successfully build app

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

```
componentWillMount = () => {
    CodePush.disallowRestart();
    this.checkUpdate();
  };

  componentDidMount = () => {
    CodePush.allowRestart();
  };
```
normal steps follow docs, I found that 'codePushDownloadDidProgress' not call, code push fail, no wrong.

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 5.5.2
* react-native version: 0.58.6
* iOS/Android/Windows version: IOS
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? physical

(The more info the faster we will be able to address it!)

**Comment by vance-liu** [comment]
working well，delete 'disallowRestart' row，why?

**Comment by alexandergoncharov** [comment]
Hi @vance-liu,
Thanks for reporting!

We will investigate it a bit later as soon as possible. Sorry for this delay.

**Comment by vance-liu** [comment]
check

**Comment by alexandergoncharov** [comment]
Hi @vance-liu ,

Sorry for this delay.
I just used `disallowRestart` and `allowRestart` in [example](https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp) project and all works correctly.

Could you please clarify why do you need disallow restart in your code example? You can also use CodePush without allowing methods in mounting life circle methods.

Please let me know if I missed something or you have any questions.

**Comment by vance-liu** [comment]
You are right, disallow restart is no need, thanks!
