### ISSUE TITLE
push success but App no update，what should i do?

### ISSUE THREAD

**Issue by yinxh2016** [Microsoft/react-native-code-push#1547]
┌───────┬───────────────────┬─────────────┬───────────┬─────────────┬───────────────────────┐
│ Label │ Release Time      │ App Version │ Mandatory │ Description │ Install Metrics       │
├───────┼───────────────────┼─────────────┼───────────┼─────────────┼───────────────────────┤
│ v1    │ 7 minutes ago     │ 1.0.0       │ Yes       │ 1次上传。       │ Active: 100% (1 of 1) │
│       │                   │             │           │             │ Total: 1              │
├───────┼───────────────────┼─────────────┼───────────┼─────────────┼───────────────────────┤
│ v2    │ 3 minutes ago     │ 1.0.1       │ Yes       │ 21次上传。      │ No installs recorded  │
├───────┼───────────────────┼─────────────┼───────────┼─────────────┼───────────────────────┤
│ v3    │ a few seconds ago │ 1.0.2       │ Yes       │ 231次上传。     │ No installs recorded  │
└───────┴───────────────────┴─────────────┴───────────┴─────────────┴───────────────────────┘

**Comment by yinxh2016** [comment]
only 1.0.0 can use ,other can not use

**Comment by alexandergoncharov** [comment]
Hi @yinxh2016,

Looks like your binary app has `1.0.0` binary version and `target-binary-version` field is mean that specified version which should be use for install current update.
For more info please check this docs: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli#target-binary-version-parameter

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander
