### ISSUE TITLE
[IOS] Does code push support changes at mainBundle resources ?

### ISSUE THREAD

**Issue by MinaFSedrak** [Microsoft/react-native-code-push#1548]
I have changed 2 files (.zip, .db) at project resources (MainBundle Path) then deployed on Staging using command (code-push release-react "projectName" "platform") but files still the same after upgrading new version. Does code push support changes at mainBundle resources ?

**Comment by alexandergoncharov** [comment]
Hi @MinaFSedrak,
Thanks for reporting!

Yeah, CodePush supports resources. Possible your update doesn't have this resources. Could you please check that your resources in your update bundle? You can download it with UI. Go to your release and use `Download Bundle` button in the upper right corner.

Please let me know if you have any questions.

**Comment by alexandergoncharov** [comment]
Hi @MinaFSedrak,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
