### ISSUE TITLE
[IOS] 'React/RCTBridge.h' file not found 

### ISSUE THREAD

**Issue by yasir-netlinks** [Microsoft/react-native-code-push#1549]
Hi there, my build fails after I moved my project to a different machine/macbook. Im not sure if this is related, but I also did remove `node_modules` and did `npm install`

<img width="1037" alt="Screen Shot 2019-03-20 at 2 34 45 PM" src="https://user-images.githubusercontent.com/26054956/54676062-77598100-4b1d-11e9-8f11-eed29dc73fe4.png">

### Environment

* react-native-code-push version: "^5.5.2"
* react-native version: "^0.57.8"

**Comment by alexandergoncharov** [comment]
Hi @yasir-netlinks ,
Thanks for reporting!

Could you please try to run `react-native link` command and try to build again?
If this was not helpful could you please provide some dummy project with reproducing issue and reprosteps?
