### ISSUE TITLE
Setup guidelines for Android react-native 0.18

### ISSUE THREAD

**Issue by hrlarsen** [Microsoft/react-native-code-push#155]
It seems that the RN team moved the MainActivity into a seperate base acitivity ReactActivity. The setup guidelines does not reflect this change yet, and I'm not aware of how to fix this as I am not an Android developer.

**Comment by lostintangent** [comment]
Yeah we noticed this change as well, but haven't had a chance to respond to it yet. I'll be investigating this today and will update the docs as appropriate. Thanks for reporting this!

**Comment by ecjs** [comment]
+1 For this..I am just getting started with React Native + Code Push, and got held up here.

**Comment by lostintangent** [comment]
Apologies for the slower-than-hoped response here! We got iOS working on RN 0.18.0 but we still need to address Android. This will definitely happen tomorrow!

**Comment by ecjs** [comment]
![screenshot 2016-01-20 23 56 17](https://cloud.githubusercontent.com/assets/8406471/12474691/d8d56370-bfd1-11e5-834b-a7178a5995a5.png)
Is this a problem with React 0.18.0 or something that I did wrong during setup?

**Comment by lostintangent** [comment]
That error is usually a manifestation of either the plugin not having been properly installed, or the packager needing a restart. You shouldn't be hitting that otherwise on iOS with RN 0.18.0, so let us know if you've double checked those two conditions and this error persists.

**Comment by lostintangent** [comment]
Hey guys, I just submitted #156, which includes config instructions for 0.18.0 (it's not the prettiest code in the world but it works for now). If you're planning on implementing a silent install, then you can use the existing plugin bits with these instructions. However, if you want to display an update dialog, this PR also makes a product change that allows this feature in Android 0.18.0. I'll release it to NPM tomorrow after I get sign-off.

**Comment by lostintangent** [comment]
I just released an update to NPM that unblocks Android on RN 0.18.0 along with the added setup docs. I want to make some changes to make the Java code a little cleaner, but in the meantime, you should be good to go. Let us know if you run into any problems. Thanks!
