### ISSUE TITLE
Code Push Error - The folder “unzipped” doesn’t exist.

### ISSUE THREAD

**Issue by faisal-aym** [microsoft/react-native-code-push#1552]
Hi,

I am getting this error on app install when checking for update. Its coming randomly not on each and every install. I have implemented 
`codePushDownloadDidProgress`

What could cause this error? 

Environment:

react-native-code-push: ^5.4.2
react-native: 0.55.4

<img width="586" alt="codepush error" src="https://user-images.githubusercontent.com/46099206/54681391-125a5700-4b2e-11e9-83f7-cf5d6406ed24.png">

_Originally posted by @faisal-aym in https://github.com/Microsoft/react-native-code-push/issues/516#issuecomment-474792914_

**Comment by dneprDroid** [comment]
I got a similar error (iOS):

```Error Domain=NSCocoaErrorDomain Code=256 "The file “unzipped” couldn’t be opened." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/1922C8E5-E8C7-4833-998B-0CC3EE503332/Library/Application Support/CodePush/unzipped,
 NSUserStringVariant=(
    Folder
), 
NSUnderlyingError=0x2812af0c0 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}}```

**Comment by yuri-kulikov** [comment]
Hi @faisal-aym, @dneprDroid 
Thanks for reporting!

Can you please clarify some moments:
- Platform (iOS?)
- Does this reproduce on a debug build or release build?
- Does this reproduce on a simulator, or only on a physical device?

It looks very similar to [this issue](https://github.com/Microsoft/react-native-code-push/issues/1457).

**Comment by dneprDroid** [comment]
- ios, "react-native": "0.57.7", "react-native-code-push": "^5.6.0",
- debug build,
- tested only on a physical device

**Comment by dneprDroid** [comment]
I opened internal files from` ../Application Support/CodePush` and noticed that zip-file is valid but it uncompressed to invalid `unzipped` file.
In my case, `unzipped` is one image from app's resource folder (from zip archive), but it should be a folder.

**Comment by dneprDroid** [comment]
Example of this zip file: 
[download.zip](https://github.com/Microsoft/react-native-code-push/files/3008248/download.zip)
<img width="440" alt="Screen Shot 2019-03-26 at 3 13 56 PM" src="https://user-images.githubusercontent.com/13742733/54999843-d0bc2700-4fd9-11e9-8a88-a1fe1cc6374a.png">

**Comment by faisal-aym** [comment]
- Platform: iOS 12
- Notice issue on release then logged issue on debug
- Logged while using simulator.

**Comment by dneprDroid** [comment]
@yuri-kulikov It seems that CodePush has invalid SSZipArchive dependency, I've deleted SSZipArchive  from CodePush and replaced with my SSZipArchive from Pods and it's working properly for me.

**Comment by yuri-kulikov** [comment]
Hey @faisal-aym, @dneprDroid
Sorry for the delay!

I just tested a simple app with `react-native-code-push` connected via pods, and it works correctly.
Maybe this issue occurs when the project already has a `SSZipArchive` dependency?

**Comment by faisal-aym** [comment]
hey @yuri-kulikov ,

My problem is when i install app its not getting the latest build/updates instead it installs some old build. But when i kill app and bring it to foreground again, it updates the app. I have 2 different keys for two different user groups. Following is my implementation:

try {
        codePush.notifyAppReady()
        ;(await codePush.checkForUpdate())
          ? codePush.sync(
              {
                deploymentKey: platform.group,
                installMode: codePush.InstallMode.IMMEDIATE
              },
              this.codePushStatusDidChange,
              this.codePushDownloadDidProgress
            )
          : console.log('already updated')
      } catch (e) {
        console.log(e)
      }

**Comment by yuri-kulikov** [comment]
As far as I understand, these

- `The folder "unzipped" doesn't exist`
- `The file "unzipped" couldn’t be opened`

seem to be two completely different problems.

@faisal-aym Do you wrap your App component with `codePush` or you only use `codePush.sync` method?

**Comment by faisal-aym** [comment]
@yuri-kulikov 

I am not wrapping App component with codepush, i need to check for update on install and when user comes to foreground from background so i am using codepush.sync method from within my update method.

i am getting "The folder unzipped doesn't exist".

**Comment by yuri-kulikov** [comment]
@faisal-aym Maybe you can provide us a simple reproducible demo so we could test it directly?

**Comment by yuri-kulikov** [comment]
@faisal-aym Just a friendly ping :)

**Comment by faisal-aym** [comment]
@yuri-kulikov thanks :) I am working on a demo project and will share with you soon.

**Comment by yuri-kulikov** [comment]
That's great, thank you! :)

**Comment by zim-lee** [comment]
`[CodePush] The file “unzipped” couldn’t be opened.`

@yuri-kulikov I met this problem. #1457 not work for me.

react-native-code-push: `5.6.0`

```
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 824.89 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 25, 26, 27, 28
        Build Tools: 26.0.3, 28.0.1
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.3 => 0.59.3 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

**Comment by alexandergoncharov** [comment]
Hi @dneprDroid , @faisal-aym ,

I'm going to close this issue for now as we haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions or if you provide a demo app for reproducing this issue.

**Comment by bonnmh** [comment]
:(

**Comment by CacaoRick** [comment]
I have same issue in:
`expo: 50.0.4`
`react-native: 0.73.2`
`react-native-code-push: 8.1.0`

install with `react-native-code-push-plugin` (for expo plugin, I'm using custom build)

Build Native App work fine.
But after install any codepush update will always restart with crash then rollback to bundle's version.

Also see error: `The folder “unzipped” doesn’t exist.`
In `Podfile.lock` CodePush dependency is `~> 2.2.2` and have another `2.2.3` outside:
```yaml
PODS:
...
- CodePush (8.2.0):
  - Base64 (~> 1.1)
  - JWT (~> 3.0.0-beta.12)
  - React-Core
  - SSZipArchive (~> 2.2.2)
- SSZipArchive (2.2.3)
...
```

So I add `SSZipArchive 2.2.2` to `Podfile`:
```ruby
target 'APP' do
  # Other dependencies...

  pod 'SSZipArchive', '2.2.2'
end
```
then delete `Podfile.lock`, run `pod install` and build native App.
And It's fixed!
