### ISSUE TITLE
[Error]  App insuApp-android uses a platform type not supported by CodePush: "Java"

### ISSUE THREAD

**Issue by byk04712** [Microsoft/react-native-code-push#1553]
Run `code-push deployment add xxx-android --default`

Then returns `[Error]  App insuApp-android uses a platform type not supported by CodePush: "Java"`

How resolve it ?

### Environment

* react-native-code-push version:5.6.0
* react-native version:0.57.4

**Comment by yuri-kulikov** [comment]
Hey @byk04712,
Thanks for your question!

I think you can try to set `React-Native` (not `Java`) as a platform when creating your application.
![Screenshot 2019-03-22 at 19 01 19](https://user-images.githubusercontent.com/42337914/54836660-c0eccc00-4cd5-11e9-8421-9e3ed90fc54a.png)

**Comment by yuri-kulikov** [comment]
Unfortunately, we haven’t heard from you in a while, so I'll close the issue for now, but please feel free to reopen it if you have some additional details or questions.
