### ISSUE TITLE
Update index.html file via code push on Android Release

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [Microsoft/react-native-code-push#1554]
### Steps to Reproduce
1. Create a react native project with a WebView (We are using WebView from `react-native`, but the issue is the same with `react-native-webview`)
2. On the WebView source, add something like:
```js
        source={{
          uri: 'file:///android_asset/index.html'
        }}
```
3. Place your index.html file on `android/app/src/main/index.html`

### Expected Behavior
I want to be able to hot update this file via code push

### Actual Behavior
The file is not hot updated. My guess is that since it is a file that exists on the Native side, code push is not able to pick it up and send it via code push to users
unfortunately, im not able to pass this file to webview as a `require('./index.html')` due to a strange webview behaviour on Android release mode (it only works on debug mode)

### Environment

* react-native-code-push version: 5.5.2
* react-native version: 0.57.1
* iOS/Android/Windows version: Android 7.1.1
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by yuri-kulikov** [comment]
Hey @rafaelcorreiapoli 
Thanks for the question!

We had a similar issue not so long ago, maybe you'll find some answers [there](https://github.com/Microsoft/react-native-code-push/issues/1460). Please let me know if you have any additional questions!

**Comment by rafaelcorreiapoli** [comment]
Hi! Thanks for you response
I could not find any answers on the Issue you pointed...
If you have any updates, please let me know. My team and I are really struggling with this for days and days.. we have a react-native app that only loads an html file (our website) and we need to be able to code-push the updates on the html file. On iOS it works out of the box with `require`

**Comment by yuri-kulikov** [comment]
@rafaelcorreiapoli, I'm sorry, I didn't notice that you wrote a message in that issue. We spent a lot of time working on this problem but did not find a solution. It seems that `<WebView>` do not allow us to use `require(...)` as a source in Android.

**Comment by yuri-kulikov** [comment]
@rafaelcorreiapoli Unfortunately, we do not have information on how to work with this. I'll close the issue for now, but if you find a way, please let us know here!
