### ISSUE TITLE
[Error]  connect ETIMEDOUT 23.101.203.117

### ISSUE THREAD

**Issue by JonsonHI** [Microsoft/react-native-code-push#1556]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:5.6
* react-native version:0.59.2
* iOS/Android/Windows version: ios  android
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? phone

(The more info the faster we will be able to address it!)

This always happens and occasionally updates succeed

[Error]  connect ETIMEDOUT 23.101.203.117

Upload progress:[==========                                        ] 21% 0.0s[Error]  connect ETIMEDOUT 23.101.203.117

**Comment by yuri-kulikov** [comment]
Hey @JonsonHI 
Thanks for reporting!

Can you please clarify what do you use to release updates (command, code-push/appcenter CLI)?

**Comment by songxiaoliang** [comment]
code-push

**Comment by yuri-kulikov** [comment]
Hey @songxiaoliang, are you from the same team? What version of `code-push-cli` do you use?
Can you also try to release an update via `appcenter-cli`?

**Comment by yuri-kulikov** [comment]
Hi @JonsonHI,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
