### ISSUE TITLE
Exception when building releaseStaging variant on Android

### ISSUE THREAD

**Issue by chetstone** [Microsoft/react-native-code-push#1557]
It appears that the instructions for multi-deployment on Android are outdated. The instructions [here](https://github.com/Microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-android.md) have been working fine for me on react-native 0.33. Now that I have updated to RN 0.59, this no longer works. 

A number of issues have been filed about this. A recent one is #1431, which was closed because the OP couldn't provide a reproducible demo. So here are the steps to reproduce the problem.
### Steps to Reproduce
```
react-native init AwesomeProject
cd AwesomeProject
yarn
yarn add react-native-code-push
react-native link react-native-code-push
```
Then add the signing config to your project as directed [here](https://facebook.github.io/react-native/docs/signed-apk-android)
Then
```
react-native run-android --variant=release
```
It works!!

Now follow the [instructions](https://github.com/Microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-android.md)  to add a Staging variant.

```
 react-native run-android --variant=releaseStaging
```

### Expected Behavior
Expected it to work

### Actual Behavior
What actually happens?
```
 info JS server already running.
info Building and installing the app on the device (cd android && ./gradlew app:installReleaseStaging)...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preReleaseStagingBuild'.
> Could not resolve all task dependencies for configuration ':app:releaseStagingRuntimeClasspath'.
   > Could not resolve project :react-native-code-push.
     Required by:
         project :app
      > Unable to find a matching variant of project :react-native-code-push:
          - Variant 'debugApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'releaseStaging' and found incompatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
          - Variant 'debugRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'releaseStaging' and found incompatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'releaseApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'releaseStaging' and found incompatible value 'release'.
              - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
          - Variant 'releaseRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'releaseStaging' and found incompatible value 'release'.
              - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installReleaseStaging.
```

### Reproducible Demo
Please follow instructions above.
### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.3 
* iOS/Android/Windows version: N/A
* Does this reproduce on a debug build or release build? Staging
* Does this reproduce on a simulator, or only on a physical device? N/A

Apparently gradle is now requiring a releaseStaging variant in the linked libraries as well as the main project. Note that the error message from gradle (shown above relating to react-native-code-push) is repeated for each 3rd-party library linked into the project.

**Comment by yuri-kulikov** [comment]
Hey @chetstone
Thanks for reporting!

As far as I understand, it was introduced in `Gradle 3.0 beta 4`.
Now we need to set `matchingFallbacks` for custom build variants:

```gradle
releaseStaging {
  ...
  matchingFallbacks = ['release']
}
release {
  ...
}
```

So you're right, we need to update the documentation. Until then, we'll keep the issue open. Thank you!

**Comment by ferdicus** [comment]
heads-up, if you're using app center, this will fail nevertheless

**Comment by yuri-kulikov** [comment]
@chetstone We [updated](https://github.com/Microsoft/react-native-code-push/pull/1562) the docs, thanks again for your feedback!

I'll close the issue for now, but feel free to reopen it if you have some additional details or questions.

**Comment by baninaveen** [comment]
include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')

Please add this exactly solve the problem
[https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android](url)
