### ISSUE TITLE
Network is unreachable, can't download new bundle version

### ISSUE THREAD

**Issue by Gerlison** [Microsoft/react-native-code-push#1558]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Install react-native-code-push
2. Run the app, release or debbug
3. In debbug shows an error on console

### Expected Behavior
I just installed code-push in a fresh project, so i started the app, first in debbug mode on a real device, the app opens, verify if exists some new bundle to update, it seems like to find one, start to try download it, but immediatly show the error in the image

### Actual Behavior

![WhatsApp Image 2019-04-04 at 3 18 53 PM](https://user-images.githubusercontent.com/28146931/55578794-1c16b980-56ed-11e9-9f4f-3b7e235cacc9.jpeg)

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.58.6
* iOS/Android/Windows version:
 Android 4.4.2
* Does this reproduce on a debug build or release build?
 Both
* Does this reproduce on a simulator, or only on a physical device?
 Physical

**Comment by yuri-kulikov** [comment]
Hi @Gerlison
Thanks for reporting!

You can check my [message](https://github.com/Microsoft/react-native-code-push/issues/1551#issuecomment-475672654) from a similar issue.
We have found a workaround and are working on a fix.

I'll close the issue, but we'll keep the initial issue updated!
