### ISSUE TITLE
set updateDialog to null or {},do not disable the update dialog to show

### ISSUE THREAD

**Issue by gwl002** [Microsoft/react-native-code-push#1560]
### Expected Behavior

I wish to custom the updateDialog and want the default dialog will not show.

### Actual Behavior

The update dialog shows no matter what I set the updateDialog parameter to

# Environment

```ts
CodePush.sync(
  {
    // updateDialog: {
    //     // appendReleaseDescription: true,
    //     // descriptionPrefix: '\n\n更新内容：\n',
    //     // title: '更新',
    //     // mandatoryUpdateMessage: '',
    //     // mandatoryContinueButtonLabel: '更新',
    // },
    updateDialog: null,
    // mandatoryInstallMode: CodePush.InstallMode.IMMEDIATE,
    installMode: CodePush.InstallMode.IMMEDIATE,
    // deploymentKey: 'D_cFC_2V-E_18nHpZxj7I-kbPC0zryQPBZQtN',
  },
  this.handleCodePushStatusChange.bind(this),
  this.handleCodePushProgressChange.bind(this)
);
```

**Comment by yuri-kulikov** [comment]
Hey @gwl002,
Thanks for reporting!

Can you show how you initialize `CodePush` and what options do you use?
It's possible that this dialog appears not during the call of the `sync()` method .

I tried this in my testing project:

```ts
codePush.sync({
  updateDialog: null,
  installMode: codePush.InstallMode.IMMEDIATE
});
```

and everything works as expected (without the dialog).

**Comment by gwl002** [comment]
Thanks for your reply!It seems works now!I don't know why the first time I tried,It failed.

**Comment by yuri-kulikov** [comment]
@gwl002 Great, thanks for keeping in touch!

I'll close the issue for now, but feel free to ask any questions or reopen the issue if needed.
Thanks for using CodePush!

**Comment by yuhang04210** [comment]
I had the same problem with ios.
"react-native-code-push": "^5.7.0",
"react-native": "0.60.5",

**Comment by harshlakhanpal** [comment]
found a simple hack which works 90% of the times,
simply switch the network/wifi you're connected to and the run the command.
