### ISSUE TITLE
when i  code-push release-react, [Error]  Internal Server Error, what should i do

### ISSUE THREAD

**Issue by duanpf** [Microsoft/react-native-code-push#1561]
when i  code-push release-react, [Error]  Internal Server Error, what should i do

**Comment by alexandergoncharov** [comment]
Hi @duanpf,
Thanks for reporting!

Could you please try to use appcenter-cli? https://github.com/Microsoft/appcenter-cli

Please let me know if it was helpful or you have any questions?

**Comment by duanpf** [comment]
thanks @alexandergoncharov ， i release my app success by appcenter-cli

**Comment by alexandergoncharov** [comment]
@duanpf, That's great!

So, I'm going to close this issue for now as it was resolved.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
