### ISSUE TITLE
i update myapp by code push successful，but after  i restart myapp，the latest version is miss。

### ISSUE THREAD

**Issue by duanpf** [microsoft/react-native-code-push#1563]
When I first updated the app code push, is was the latest version. But when I restarted the app, my app returned to its previous state.

**Comment by duanpf** [comment]
I guess the code bundle update did not replace the original bundle file, but I don't know how to handle this.

**Comment by duanpf** [comment]
I am using this command： 
`appcenter codepush release-react -a userName/appName -d Production -m --description "first update"`

**Comment by alexandergoncharov** [comment]
Hi @duanpf ,
Thanks for reporting!

Could you please share your logs during update?
You can grab it with AndroidStudio for Android or with Xcode for IOS.

Please feel free to ask any questions.

**Comment by terijyu** [comment]
+1

**Comment by alexandergoncharov** [comment]
Hi @terijyu ,
Thanks for reporting
Could you please share your logs during update?

**Comment by alexandergoncharov** [comment]
Hi @terijyu , @duanpf ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen this issue if you have any questions.

Thanks,
Alexander
