### ISSUE TITLE
checkupdate after app installed,but It always rollback after restart

### ISSUE THREAD

**Issue by gwl002** [Microsoft/react-native-code-push#1564]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.First open the app,It works fine.Check update and downloading the new version,and then restart,show the newest content successfully.
2. However, quit the app and restart,then the logcat shows  "An update is available, but it is being ignored due to having been previously rolled back."

### Expected Behavior
What you expected to happen?
The second time the app start  the checkUpdate function should return null
### Actual Behavior
What actually happens?
The checkUpdate function return a obj with info about the newest version.
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
   5.6.0,
* react-native version: 
  0.58.6,
* iOS/Android/Windows version:
  android
* Does this reproduce on a debug build or release build?
  release
* Does this reproduce on a simulator, or only on a physical device?
 android phone

`
export default class BoardingScreen extends React.Component {
     static navigationOptions = {
         header:null
     };

     constructor(props) {
         super(props);
         this.state = {
            currProgress:0,
            showProgressBar:false,
         };

         this.syncImmediate = this.syncImmediate.bind(this);
         this._immediateUpdate = this._immediateUpdate.bind(this);
     }

     componentDidMount(){
        this.syncImmediate();        
     }

     syncImmediate(){
        CodePush.checkForUpdate().then(update=>{
            SplashScreen.hide();
            console.log(update);
            if(!update){
                this.setState({
                    showProgressBar:false
                })
                this.props.navigation.navigate("Main");
            }else{
                this.setState({
                    showProgressBar:true
                })
                this._immediateUpdate();
            }
        }).catch(err=>{

        })
        
     }

     _immediateUpdate(){
        CodePush.sync(
            {
                updateDialog:null,
                installMode: CodePush.InstallMode.IMMEDIATE,
            },
            this.handleCodePushStatusChange.bind(this),
            this.handleCodePushProgressChange.bind(this)
        );
     }

     handleCodePushStatusChange(syncStatus){
        let syncMessage;
            switch(syncStatus) {
                case CodePush.SyncStatus.CHECKING_FOR_UPDATE:
                  syncMessage = 'Checking for update'
                  break;
                case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
                  syncMessage = 'Downloading package'
                  break;
                case CodePush.SyncStatus.AWAITING_USER_ACTION:
                  syncMessage = 'Awaiting user action'
                  break;
                case CodePush.SyncStatus.INSTALLING_UPDATE:
                  syncMessage = 'Installing update'
                  break;
                case CodePush.SyncStatus.UP_TO_DATE:
                  syncMessage = 'App up to date.'
                  break;
                case CodePush.SyncStatus.UPDATE_IGNORED:
                  syncMessage = 'Update cancelled by user'
                  break;
                case CodePush.SyncStatus.UPDATE_INSTALLED:
                  syncMessage = 'Update installed and will be applied on restart.'
                  break;
                case CodePush.SyncStatus.UNKNOWN_ERROR:
                  syncMessage = 'An unknown error occurred'
                  break;
            this.setState({
                syncMessage
            })
        }
     }

     handleCodePushProgressChange(progress){
        let currProgress = parseFloat(progress.receivedBytes / progress.totalBytes).toFixed(2);
        this.setState({
            currProgress:currProgress,
        })
     }

     render() {
         return (
            <View style={{flex:1}}>
                <Image source={{uri :'asset:/images/launch_screen.png'}} style={{width:"100%",height:"100%"}}/>
                {!this.state.showProgressBar &&
                    <View style={{position:"absolute",justifyContent:"center",alignItems:"center",width:winWidth,height:winHeight,backgroundColor:"transparent",}}>
                        <Progress progress={this.state.currProgress} />
                        <Text>{this.state.syncMessage}</Text>
                    </View>
                }
            </View>
         );
     }
 }

`
(The more info the faster we will be able to address it!)

**Comment by gwl002** [comment]
I check some similar issues,But just doesn't work!
1. wrapper the root component with codepush
2.notifyAppReady() ; I don't know where to place it .I tried call it after the status change to installed,it do not work.

**Comment by yuri-kulikov** [comment]
Hey @gwl002
Thanks for the question!

You can just use it like this:

```ts
componentDidMount(){
  codePush.notifyAppReady();
  this.syncImmediate();        
}
```

**Comment by InformaticaComergrup** [comment]
I have the same error:

"An update is available, but it is being ignored due to have been previously rolled back."



`codePush.checkForUpdate(function (update) {
							if (update) {
								var updateDialogOptions = {
									updateTitle: "Actualitzacio pendent",
									optionalUpdateMessage: "Vols actualitzar ara?",
									optionalIgnoreButtonLabel: "No",
									optionalInstallButtonLabel: "Si"
								};

								var syncStatus = function (status) {
									console.log("SyncStatus =", status);
									switch (status) {
										case SyncStatus.UP_TO_DATE:
											break;
										case SyncStatus.UPDATE_INSTALLED:
											console.log("SyncStatus.UPDATE_INSTALLED");
											Utilitats.pantallaEspera(false);
											codePush.restartApplication();
											break;
										case SyncStatus.DOWNLOADING_PACKAGE:
											Utilitats.pantallaEspera(true);
											console.log("SyncStatus.DOWNLOADING_PACKAGE");
											break;
										case SyncStatus.INSTALLING_UPDATE:
											// Hide "downloading" modal
											console.log("SyncStatus.INSTALLING_UPDATE");
											break;
										case SyncStatus.ERROR:
											// Hide "downloading" modal
											console.log("SyncStatus.ERROR");
											Utilitats.pantallaEspera(false);
											break;
									}
								};
								codePush.sync(syncStatus, { updateDialog: updateDialogOptions });
								//codePush.sy nc(syncStatus);														
							}
						});`

**Comment by yuri-kulikov** [comment]
Hi @InformaticaComergrup 

> I have the same error:
> 
> "An update is available, but it is being ignored due to have been previously rolled back."

There is a good [comment](https://github.com/Microsoft/react-native-code-push/issues/880#issuecomment-342463583) on how rollbacks work.

**Comment by yuri-kulikov** [comment]
Hi @gwl002,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately. I hope your issue is resolved!
Please feel free to reopen it if you have any questions.

**Comment by rmamtaventures** [comment]
Same issue in android in react native version 0.60.4.

**Comment by mcruz20** [comment]
Same issue in iOS in react native v0.61.5

**Comment by Cchumi** [comment]
Same issue on Android and iOS on 0.61.5

**Comment by dmydry** [comment]
Same issue on both platforms. Updates with `codepush.sync()` method are all installed successfully, but after restart our app launches with an initial bundle and `codePush.checkForUpdate()` method returns an update object again (instead of `null`) with `failedInstall: true`.

**Comment by sephiroth56** [comment]
Same issue on Android 0.59.9

**Comment by yadimuhammad** [comment]
any updates?

**Comment by knifedge** [comment]
Same issue here. Any updates?

**Comment by AnkitPandey14ap** [comment]
Same issue on android, any update

**Comment by hongsa** [comment]
Same issue on both platform. Any solution?????

**Comment by benorgan** [comment]
We are also having this issue on Android with RN 0.63.4

**Comment by hfarhanahmed** [comment]
We are also having the same issue on IOS with React Native 0.63.4

Did anyone resolved this issue or know why this is happening?

**Comment by DeMeng33** [comment]
Same issue on both platform with ionic cordova. Any solution???

**Comment by shllg** [comment]
Still the same issue

**Comment by MAKARD** [comment]
The same issue for me. 
<img width="475" alt="image" src="https://user-images.githubusercontent.com/25794983/163255592-531588d0-cb39-4bac-a2f5-ba4bb5539e1e.png">
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/25794983/163255743-9e53699d-9cec-4b59-b345-9b0b285b6194.png">

**Comment by ahmadsyed** [comment]
Same issue , Please reopen this ticket

**Comment by Kunal-Airtel2022** [comment]
Same issue on codepush version 7.0.4

**Comment by TacticCoder** [comment]
Same here

**Comment by roger-ngx** [comment]
for me, that because i forgot to setup at the native side https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md
