### ISSUE TITLE
React/RCTEventEmitter.h file not found

### ISSUE THREAD

**Issue by felixchan** [microsoft/react-native-code-push#1565]
I followed the instructions to install this on iOS.
The `react-native link` and `manual` methods result in this error during build.

When using CocoaPods to install, `pod install` fails.

```
$ pod install
Ignoring unf_ext-0.0.7.4 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.4
Analyzing dependencies
Fetching podspec for `CodePush` from `../node_modules/react-native-code-push`
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] CocoaPods could not find compatible versions for pod "React/Core":
  In snapshot (Podfile.lock):
    React/Core

  In Podfile:
    React/Core (from `../node_modules/react-native`)

None of your spec sources contain a spec satisfying the dependencies: `React/Core (from `../node_modules/react-native`), React/Core`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by yuri-kulikov** [comment]
Hey @felixchan,
Thanks for reporting!

Could you clarify some points about your environment?

* `react-native-code-push` version?
* `react-native` version?
* Does this reproduce on a debug build or release build?

Maybe you could provide us with some simple demo project so we can check it directly?

**Comment by rdewolff** [comment]
Same issue. Followed install instructions, project was working fine but since I updated, cannot compile the iOS project anymore.

**Comment by rdewolff** [comment]
Current workaround found : 
<img width="1095" alt="Screen Shot 2019-05-06 at 21 08 45" src="https://user-images.githubusercontent.com/130704/57248646-2ce78180-7043-11e9-8456-40a31af53684.png">

**Comment by yuri-kulikov** [comment]
Hey @rdewolff, thanks for reporting!

> Followed install instructions, project was working fine but since I updated, cannot compile the iOS project anymore.

You mean this [instructions](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---cocoapods)?

**Comment by rdewolff** [comment]
I think the issue came from double install : via node_module include and via Cocoapods.
Anyway, I solved it.

**Comment by erandagan** [comment]
For anyone who might encounter this - In my project, React Native was included through CocoaPods. However, when including CodePush **through CocoaPods**, the `React/RCTEventEmitter.h file not found` error would arise from the CodePush project. When the project was added manually (not via Pods), everything worked.

In order to use CodePush as a pod, I had to remove the React Native libraries from the Xcode project, so they are only included through CocoaPods. If you do this, make sure to properly configure the React pod subspecs to match the libraries you're using.

**Comment by yuri-kulikov** [comment]
Hey @erandagan,
Thanks for your explanation, it's really helpful!

@felixchan We haven't heard from you in a while, unfortunately. I'm going to close this issue for now. Please let us know if you still need our help, feel free to reopen the issue if needed!

**Comment by gh7800** [comment]
> Current workaround found, adding the missing lib manually to the CodePush Pods project :
> <img alt="Screen Shot 2019-05-06 at 21 08 45" width="1095" src="https://user-images.githubusercontent.com/130704/57248646-2ce78180-7043-11e9-8456-40a31af53684.png">

I click " +" ,but i donot find RCTEventEmitter.h ,how do you find that

**Comment by WowJesse** [comment]
@gh7800 me too. help

**Comment by aangeles2807** [comment]
this worked for me!

https://github.com/microsoft/react-native-code-push/issues/1565#issuecomment-489738672

**Comment by SamiChab** [comment]
I cannot find RCTEventEmitter.h either... Can someone help?

**Comment by u-l-y** [comment]
> I cannot find RCTEventEmitter.h either... Can someone help?

After you press "+" you must then press "add other" as it is outside the Pods folder. It should be within node_modules/react-native/React/Modules.

I'm not sure anyway if this is the right way to fixing the issue as per this comment: https://github.com/facebook/react-native/issues/12042#issuecomment-275729402

**Comment by u-l-y** [comment]
> > I cannot find RCTEventEmitter.h either... Can someone help?
> 
> After you press "+" you must then press "add other" as it is outside the Pods folder. It should be within node_modules/react-native/React/Modules.
> 
> I'm not sure anyway if this is the right way to fixing the issue as per this comment: [facebook/react-native#12042 (comment)](https://github.com/facebook/react-native/issues/12042#issuecomment-275729402)

My issue was resolved by removing the line from my Pod file that was pointing the library that caused the issue to the node_modules path `pod $libraryName, :path => $libraryPath`

**Comment by jiteshstack** [comment]
Replace `#import RCTEventEmitter.h` or `#import React/RCTEventEmitter.h` with `#import <React/RCTEventEmitter.h>`

Its work for me

**Comment by walaa23** [comment]
Replace 

#import <React/RCTEventEmitter.h>

With

#if __has_include("RCTEventEmitter.h")
  #import "RCTEventEmitter.h"
#else
 #import <React/RCTEventEmitter.h>
#endif
