### ISSUE TITLE
"codepush.gradle" may have not been added to the build definition.

### ISSUE THREAD

**Issue by Xdomino** [Microsoft/react-native-code-push#1567]
### Steps to Reproduce
1.execute assembleRelase

### Expected Behavior
I can found the codepushhash file in packaged apk's assets folder.

### Actual Behavior
There is no codepushhash file.

### Environment

* react-native-code-push version: 5.5.1
* react-native version: 0.59.4
* Does this reproduce on a debug build or release build? release

![4E2B3637-B73A-4AEE-9982-85F55A596A13](https://user-images.githubusercontent.com/18133132/56551475-10ffcc80-65bb-11e9-8cf7-09a21e267b03.png)
As you can see. Hash task is existed. But when i execute him. i got task not found.
![E8C2D1A0-F89F-4B01-BA81-209700E76690](https://user-images.githubusercontent.com/18133132/56551592-591eef00-65bb-11e9-8ae5-69527cb56d14.png)
I'm searching for days. It's drew me nuts. SOS

**Comment by alexandergoncharov** [comment]
Hi @Xdomino ,
Thanks for reporting!

Could you please clarify why do you need codepushhash file?

**Comment by Xdomino** [comment]
@alexandergoncharov 
Becasuse of no this file, the codepush not working.

**Comment by Xdomino** [comment]
I don't kown why. Now it's working normally.

**Comment by alexandergoncharov** [comment]
@Xdomino, oh, great! Thanks for letting us know.
Please feel to reopen it if you have any questions or face this issue again.

**Comment by NicWickman** [comment]
I am facing this issue. CodePush has worked fine for me in the past, but does not anymore. I do not know what has changed.

There is no codepushhash file generated by `gradlew assembleRelease`

**Comment by ramki1979** [comment]
same thing here using 

> bundleRelease

RN - 0.59.8
Code-push - 2.0.7
