### ISSUE TITLE
Can I codepush to two Android Apps? 

### ISSUE THREAD

**Issue by arunharidas** [microsoft/react-native-code-push#1568]
Can I codepush to two React Native Android Apps (they are running the same codebase) ?

**Comment by alexandergoncharov** [comment]
Hi @arunharidas,
Thanks for reporting!

If you mean that you have 2 different apps in appcenter but you would like to keep it with the same codebase then Yes, you can do it. Just change name of your app during release your update in cli command.
And please be careful with deployment keys. Each deployment has unique key.

Please let me know if it was helpful or your have any questions.

**Comment by arunharidas** [comment]
I can use same deployment key for both apps ?

**Comment by alexandergoncharov** [comment]
Unfortunately no. Deployment key is unique and generated with creating deployment.

Could you please clarify your case? Why do you need 2 apps with the same codebase?

**Comment by arunharidas** [comment]
My three clients require same app functionality. So thought of providing them same codebase. I load configuration file from a remote database so in appearance the apps will look different. I want to manage them under one code push since they are using identical code.

**Comment by alexandergoncharov** [comment]
Got it. At first I think that you can use one app for you case and just separate it by deployments. 
I'm not sure if I understand your case fully but you can think about CodePush as just box with code. if you prefer use exactly same code you can use one deployment and your one release will be downloaded from all your app on devices. But this case have one con: Your metrics will be summarised for all your apps.
f you agree with that then it ok but my recommendation is using separate app and deployment for more flexible using. If you wouldn't like to run several same commands for release for different app just create script file for this with release commands .

Please let me know if it was helpful or you have any questions.

**Comment by alexandergoncharov** [comment]
Hi @arunharidas ,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen this issue if you have any questions.

Thanks,
Alexander
