### ISSUE TITLE
No installed number on Appcenter website with 'checkForUpdate()' (iOS)

### ISSUE THREAD

**Issue by raykle** [Microsoft/react-native-code-push#1569]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Deploy new bundle to appcenter.
2. In my code, I use the way of `checkForUpdate()`.
3. The logic is like:

```js
checkForUpdate() {
  CodePush.checkForUpdate()
    .then((remotePackage)=> {
      if (remotePackage && remotePackage.download) {
       // download
       remotePackage.download()
         .then((localPackage) => {
            if (localPackage && localPackage.install) {
              // install
              localPackage.install()
                .then(() => {
                  CodePush.notifyAppReady()
                })
              }
           })
        }
    })
}
```

### Expected Behavior
I want to see the installed num and download number of the package deployed to the appcenter website.

### Actual Behavior
Currently, the update is all fine and I can see the update on the device and simulator.
But, on the appcenter website, I can only see the download number, the installed number is always 0. (See the screenshots below)
It happens on iOS device (both debug and release env) and simulator, the android is fine.

Can anybody point out the problem? Thank you.

### Environment

* react-native-code-push version:
  > 5.4.2
* react-native version:
  > 0.55.4
* iOS/Android/Windows version:
  > iOS 12.2
* Does this reproduce on a debug build or release build?
  > both
* Does this reproduce on a simulator, or only on a physical device?
   >  both

---

#### Screenshots:

> Staging:

![image](https://user-images.githubusercontent.com/3097366/56711644-3547de80-675e-11e9-9773-9e71cae3c0f9.png)

> Production:

![image](https://user-images.githubusercontent.com/3097366/56711658-4abd0880-675e-11e9-8c0b-6dba38ac7fc8.png)

**Comment by alexandergoncharov** [comment]
Hi @raykle !
Thank you for reporting.

I tried reproduce your issue with indicated versions of react-native and react-native-code-push and also using the code you provided. But installs counter in appCenter worked fine. After relaunch app update took effect and counter is incremented.

Could you please provide some dummy project with reproducing issue?  I would like explore it.

**Comment by raykle** [comment]
Hi @alexandergoncharov ,

I was using `sync()` before and worked fine. The new version of my app is changed to `checkForUpdate()` for I add a screen to show the download progress.

I will start a new project to check if has the same issue.
Thank you.

**Comment by alexandergoncharov** [comment]
Sure. Thanks. Could you please let me know your results.

**Comment by raykle** [comment]
Hi, @alexandergoncharov !
I have checked by creating a new app with the `Examples/create-app.js` and find the reason.

In my app, I don't wrap the App component with `CodePush(App)`, but my check frequency is `MANUAL` actually, and I don't call `CodePush.notifyAppReady()` manually, which result in the call of `CodePush.notifyAppReady()` after `install()` succeed removing the pending-updates.

Then, when I restart the app, the `_isFirstRunAfterRestart` of CodePush is `NO`, because the `pendingUpdate` in the `UserDefaults` is `nil`, so the `getNewStatusReport` won't upload the label to increase the install counter.

Finally, the issue is resolved by wraping My `App` with:
```js
const codePushOptions = { checkFrequency: CodePush.CheckFrequency.MANUAL }
const App = CodePush(codePushOptions)(App)
```
Thank you :)

**Comment by yuri-kulikov** [comment]
@raykle It's great! Thanks for letting us know.
I'll close the issue for now. Please feel to reopen it if you have any questions!
