### ISSUE TITLE
The guideline should state that `.bundle` or `.jsbundle` file extension of bundle output is required for Releasing Updates (JavaScript + images)

### ISSUE THREAD

**Issue by alexlau811** [Microsoft/react-native-code-push#157]
Although the sample showed `--bundle-output ./release/main.jsbundle`, no documentation states that this does not accept other extensions besides `.bundle` or `.jsbundle`.

If a developer passed other extensions (e.g. `index.ios.js`), the update will stuck and no error messages are prompted nor logged.

(I have spent a morning to figure it out why my app won't update. 😭)

**Comment by lostintangent** [comment]
This is a very good point! I apologize for the confusion and lack of docs here. We should accept files with the `.js`, `.jsbundle`, and `.bundle` extensions, so I'll use this bug to track adding support for `.js` files, as well as updating the docs to specify that the extension is relevant.

**Comment by lostintangent** [comment]
Hey @alexlau811! Check out the PR I just submitted and let me know what you think. Thanks again for the feedback here! It means a lot to us since it can be easy to glaze over things that aren't documented well enough :)

**Comment by alexlau811** [comment]
Wow! Your action is just so quick and that PR is super great. Thank you so much!

**Comment by lostintangent** [comment]
Great! Thanks dude. I just merged this PR. If you're cool using the `.jsbundle` or `.bundle` extensions for now, I'll release an update to NPM later that adds the support for `.js` files as well.
