### ISSUE TITLE
[iOS] crash after finished downloading the update

### ISSUE THREAD

**Issue by ranran2** [microsoft/react-native-code-push#1570]
![image](https://user-images.githubusercontent.com/17609120/56790540-69430280-6837-11e9-86a8-522278bfca4d.png)

 Codepush work perfectly until i include a native library, ios crashed ,after downloading the update just like the screenshot.

i have searched all the similar issues, include:
 <a href="https://github.com/Microsoft/react-native-code-push/issues/1417">#1417</a>、<a href="https://github.com/Microsoft/react-native-code-push/issues/757">#757</a>、<a href="https://github.com/Microsoft/react-native-code-push/issues/816">#816</a>、<a href="https://github.com/Microsoft/react-native-code-push/issues/815">#815</a>、<a href="https://github.com/Microsoft/react-native-code-push/issues/879">#879</a>、 <a href="https://github.com/Microsoft/react-native-code-push/issues/775#issuecomment-291534691">#775</a>

i try all the solutions inside them but the problem still exist.

### usage demo 

![image](https://user-images.githubusercontent.com/17609120/56791958-07849780-683b-11e9-8766-af4fc943ee3c.png)

### Environment

* react-native-code-push version:"2.1.1-beta"
* react-native version:"0.44.3"
* iOS/Android/Windows version:ios 10,ios 11,ios 12
* Does this reproduce on a debug build or release build? both of them 
* Does this reproduce on a simulator, or only on a physical device? only on a physical device

### Reproduce 
for some reason we will not consider to upgrade the RN version temporarily .so we dont't try to  reproduce it in new version of RN .

**Comment by andrewhartwig** [comment]
You can not ship native code in a code-pushed update. If you make native changes, you need to ship a new release to the app store, and never code-push the new code to the older versions.

Code-push only bundles the javascript portion of your app. If javascript is pushed that didn't have the native code shipped, your app will crash.

**Comment by ranran2** [comment]
@andrewhartwig   sorry for my unclear description. i have shipped a new realease and all test are based on it. i  only push the new changes in js to this new version.thanks for your remind.

**Comment by alexandergoncharov** [comment]
Hi, @ranran2,
Thanks for reporting and sorry for delay.

Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @ranran2,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
