### ISSUE TITLE
Multi-Deployment Documentation

### ISSUE THREAD

**Issue by GioLogist** [microsoft/react-native-code-push#1571]
In the [muti deployment](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#android) documentation, it explicitly states:

> // Note: CodePush updates should not be tested in Debug mode as they are overriden by the RN packager. However, because CodePush checks for updates in all modes, we must supply a key.

However, a later note states

> And that's it! Now when you run or build your app, your debug builds will automatically be configured to sync with your Staging deployment, and your release builds will be configured to sync with your Production deployment.

Which can mislead devs into thinking that debug mode will actually pull from staging.

**Comment by alexandergoncharov** [comment]
Hi @GioLogist ,
Thanks for reporting!

Yeah, thanks for a good catch. But I think that it should not be an issue as just `your debug builds will automatically be configured to sync with your Staging deployment`. Here is no any info about pulling from `Staging`, just configured for `Staging`. And yeah, it is possible to test CodePush in debug mode if the developer closes dev server. In this case, an update should be applied.

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by alexandergoncharov** [comment]
Hi @GioLogist,

I'm going to close this issue for now as I haven't heard from you in a while unfortunately.
Please feel free to reopen this issue if you have any questions.
