### ISSUE TITLE
Add Support for Gradle Plugin >= 3.2

### ISSUE THREAD

**Issue by mcgloneleviROOT** [Microsoft/react-native-code-push#1572]
Hello RNCP Maintainers,

We have a 0.55.4 React App that we are upgrading to 0.59.4.  We are hitting an issue with using the latest Android Plugin with React Native 0.59.4, React Native Code Push 5.6.0, and Android plugin 3.3.1.  Here is the error we receive:

```
> Task :app:generateBundledResourcesHashProductionRelease FAILED
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/android/app/build/generated/res/react/production/release'
```

The issue appears to be related to where our bundle and assets are stored.  Our bundle is being put in `android/app/build/intermediates/merged_assets/localDebug/mergeLocalDebugAssets/out`, but it looks like RNCP is looking in the old directory for Android Plugin < 3.2

### Expected Behavior
RNCP should look in the merged_assets directory for the bundle and assets required for the app.

### Actual Behavior
We receive an error related to a directory that does not exist.

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.4
* iOS/Android/Windows version: N/A
* Does this reproduce on a debug build or release build? N/A
* Does this reproduce on a simulator, or only on a physical device? N/A

**Comment by mcgloneleviROOT** [comment]
As a side note, it looks like a similar issue has been raised here:

https://github.com/Microsoft/react-native-code-push/issues/1427

**Comment by yuri-kulikov** [comment]
Hey @mcgloneleviROOT,
Thanks for reporting!

I've just created a simple app with:

- react-native-code-push 5.6.0
- react-native 0.59.4
- gradle plugin 3.3.1

and it works correctly.

Maybe you could send us a simple demo so we could try to find the problem?

**Comment by bhollander-root** [comment]
Hey @yuri-kulikov,

I am working with @mcgloneleviROOT to figure this out. We are only seeing this issue with release builds ([due to this line in `codepush.gradle`](https://github.com/Microsoft/react-native-code-push/blob/c4a9c987bd4bebc6532d18184af01a5ef443bbc7/android/codepush.gradle#L64)). Are you able to build your app with a build type of `release`?

**Comment by mcgloneleviROOT** [comment]
Looking into this issue a bit further, here is what we found.

react.gradle is ignoring the JS Bundle Dir paths set in our gradle config.

https://github.com/facebook/react-native/blob/master/react.gradle

generatedResFolders and generatedAssetsFolders are pointing at the values specified in react.gradle, and not the new location in merged_assets per the newest gradle convention.  When generateBundledResourcesHash against our release targets, it looks in a directory that no longer exists due to the files having been moved in react.gradle (see line with `// pre bundle build task for Android plugin 3.2+`)

**Comment by mcgloneleviROOT** [comment]
@bhollander-root and our boss were able to figure out what was going on in our Gradle build process that were causing our issues.

**Comment by yuri-kulikov** [comment]
Hey @mcgloneleviROOT,
Sorry for the delay!

It's great that you found the problem!
If you could share some information about the cause and solution, that would be great, maybe it would save a lot of time for someone with a similar issue.

**Comment by snmishra** [comment]
@bhollander-root and @mcgloneleviROOT I think I'm running into the same problem. Could I ask you to post your findings?

**Comment by mcgloneleviROOT** [comment]
Hey snmishra,

Basically, the issue was that when we upgraded our React Native app the file paths for resources and the JS bundle changed.  We ended up setting different values for jsBundleDirRelease and sourcemapPath.

Here is our project.ext block if it helps:

```
project.ext {
    bundleAssetName = "index.android.bundle"
    jsBundleDirRelease = "$buildDir/generated/assets/react/production/release"
    sourcemapPath = "$buildDir/generated/assets/react/index.android.bundle.map"
    versionCode = json.versionCode
    versionName = json.versionName
    googlePlayServicesVersion = '16.1.0'
    supportLibVersion = '28.0.0'
}
```

My gradle knowledge is a little rough.  @bhollander-root might be able to add more if I forgot anything.
