### ISSUE TITLE
notifyAppReady seems inevitable?

### ISSUE THREAD

**Issue by GioLogist** [Microsoft/react-native-code-push#1576]
As per documentation, it states that `notifyAppReady` isn't necessary when using sync.
> notifyAppReady: Notifies the CodePush runtime that an installed update is considered successful. If you are manually checking for and installing updates (i.e. not using the sync method to handle it all for you), then this method MUST be called; otherwise CodePush will treat the update as failed and rollback to the previous version when the app next restarts.

Here's an example of a component using `sync`, similar to this article
https://medium.com/react-coach/using-codepush-with-wix-react-native-navigation-a6a7938cee24

```js
import React from 'react'
import codePush from 'react-native-code-push'

let codePushOptions = {
  installMode: codePush.InstallMode.ON_NEXT_RESUME,
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
}

export class CodePushComponent extends React.Component {
  componentDidMount() {
    codePush.sync()
  }

  render() {
    return null
  }
}

CodePushComponent = codePush(codePushOptions)(CodePushComponent)

module.exports = CodePushComponent

```

This component alone won't re-install the app, without calling `notifyAppReady` from `App.js` (as mentioned in the article above)

**Comment by GioLogist** [comment]
Update: It seems that `codePush.sync` is not necessary. 

Using the following works fine, without the need for `notifyAppReady`
```js
import React from 'react'
import codePush from 'react-native-code-push'

let codePushOptions = {
  installMode: codePush.InstallMode.ON_NEXT_RESUME,
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
}

class CodePushComponent extends React.Component {
  render() {
    return null
  }
}

export default codePush(codePushOptions)(CodePushComponent)```

**Comment by charleston10** [comment]
@GioLogist Can you show what version of gradle, react and also the codepush you are using?
Also same problem

**Comment by songxiaoliang** [comment]
@charleston10 same error
