### ISSUE TITLE
Rollback not working

### ISSUE THREAD

**Issue by lhphancs** [Microsoft/react-native-code-push#1577]
When I rollback, the application remains on the undesired latest change.

### Steps to Reproduce
1. Run app on android emulator
2. Add Text AAA to .js code and run `code-push release-react testApp android -d Production`
3. Reload app on emulator and install change
4. Modify .js code to Text BBB and run `code-push release-react testApp android -d Production`
5. Run `code-push rollback testApp Production`
6. Reload app on emulator and install change

### Expected Behavior
Upon step 6, after clicking "Install", it should install/reload and display AAA

### Actual Behavior
Upon step 6, after clicking "Install", it installs/reloads the app with no rollback, displaying BBB

Running `code-push debug android`
does show a match in  "Loading JS bundle from"... from the AAA bundle and it does show
 `Reporting CodePush update success (vTHE_NEWEST_RELEASE_CREATED_BY_ROLLBACK)`

I have
```
componentDidMount() {
    CodePush.sync({
      updateDialog: true,
      installMode: CodePush.InstallMode.IMMEDIATE,
    })
      .catch(err => console.warn('update error', err));
  }
```
and
```
const codePushOptions = { checkFrequency: CodePush.CheckFrequency.MANUAL };
export default App = CodePush(codePushOptions)(App);
```

Am I missing something?
Thanks.

### Environment
react-native-code-push: 5.6.0
react-native: 16.8.6

**Comment by yuri-kulikov** [comment]
Hey @lhphancs,
Thanks for reporting!

I've created a simple example app to test it.
Here is a demo: https://vimeo.com/333722178
The rollback works as expected.

Maybe there's some other problem (not related to "Rollback" command itself)?

**Comment by lhphancs** [comment]
Thanks for the quick reply.

It's good to know that it seems to be working. Can you link me to the project you used?

I loaded up the example at:
https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp

However, it's giving me
```
A problem occurred evaluating project ':react-native-code-push'. > Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by yuri-kulikov** [comment]
@lhphancs, yes, sorry, I forgot to mention this.
You need to test CodePush updates in **release mode** because debug mode uses a locally generated bundle when the application starts.

Please let me know if you have any questions.

**Comment by lhphancs** [comment]
Good to know! Thank you very much. It has helped a lot.

**Comment by yuri-kulikov** [comment]
Great!
Thanks for using CodePush!
