### ISSUE TITLE
Failed to capture fingerprint of output files for task ':app:mergeDebugResources' property 'incrementalFolder' during up-to-date check

### ISSUE THREAD

**Issue by dragonStandard123** [microsoft/react-native-code-push#1579]
I am getting this error when I link react-native-code-push with my project.
Whenever I do react-native run-android, I am facing this error.

> Failed to capture fingerprint of output files for task ':app:mergeDebugResources' property 'incrementalFolder' during up-to-date check.
> Could not read path 'D:\test\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values'.

So I have cleaned and rebuilt every time, it is a heavily troublesome.
How can I resolve this problem?

**Comment by yuri-kulikov** [comment]
Hey @dragonStandard123,
Thanks for asking! Sorry for the delay.

**Could you please clarify some points about your environment?**
* react-native-code-push version? 
* react-native version?
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

**Comment by dragonStandard123** [comment]
Hi @yuri-kulikov 
> react-native-code-push version?

5.6.0

> react-native version?

0.59.5

> Does this reproduce on a debug build or release build?

Debug build

> Does this reproduce on a simulator, or only on a physical device?

A physical device.

**Comment by yuri-kulikov** [comment]
@dragonStandard123, sorry, and one more thing, which versions of Gradle and gradle plugin do you use?

**Comment by dragonStandard123** [comment]
@yuri-kulikov 
Thanks for your attention

> com.android.tools.build:gradle:3.3.1

> apply from: "../../node_modules/react-native/react.gradle"
> apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
> apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

**Comment by yuri-kulikov** [comment]
Hey @dragonStandard123,
Sorry for the delay!

I've created a simple example app:

- react-native 0.59.5
- react-native-code-push 5.6.0
- gradle-plugin: 3.3.1

I've used `react-native run-android` (several times) to launch it and haven't experienced any problems. Should I make some changes in the project to reproduce the issue, or maybe you could provide us with a simple reproducible demo app?

**Comment by dragonStandard123** [comment]
I will soon create a repo and inform you. Thanks.

**Comment by HydroBirous** [comment]
https://github.com/wix/react-native-navigation/issues/4858#issuecomment-488726200
This worked for me !

**Comment by dragonStandard123** [comment]
Thanks @HydroBirous  
I have already read that issue.
But every rebuilding needs my patience.

**Comment by yuri-kulikov** [comment]
> I will soon create a repo and inform you. Thanks.

@dragonStandard123 just a friendly ping :)

**Comment by dragonStandard123** [comment]
Sorry to keep you waiting... 
The deadline of mine is approaching, I cant take a break. :runner::weary:
I intend to make the demo this weekend.
Thanks again !!!

**Comment by yuri-kulikov** [comment]
@dragonStandard123 don't worry! No need to rush, we'll wait 🙂 thank you!

**Comment by alexandergoncharov** [comment]
Hi @dragonStandard123 ,

I'm going to close this issue for now as we haven't heard from you in a while, unfortunately.
Please feel free to open it if you have any questions.
