### ISSUE TITLE
Could not connect server to get update (https://codepush.azurewebsites.net/)

### ISSUE THREAD

**Issue by mark5566** [microsoft/react-native-code-push#1583]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Calling function of  getting update from server

### Expected Behavior
To get updates successfully

### Actual Behavior
when I call the function of "CodePush.checkForUpdate(CODE_PUSH_KEY)", it always get error about network fail and  "https://codepush.azurewebsites.net/" could not be connected
![image](https://user-images.githubusercontent.com/11515695/57285726-645b3a00-70e6-11e9-923e-f23700892122.png)

### Environment

* react-native-code-push version:5.3.2
* react-native version:0.53.3
* iOS/Android/Windows version:11.4
* Does this reproduce on a debug build or release build? any
* Does this reproduce on a simulator, or only on a physical device? any

(The more info the faster we will be able to address it!)

**Comment by mark5566** [comment]
当我调用codepush对象的checkForUpdate方法，经常性没法连接，https://codepush.azurewebsites.net/

**Comment by yz1311** [comment]
Same issue.Can't get update now!

**Comment by mark5566** [comment]
> Same issue.Can't get update now!

Did you get update by the function of "CheckForUpdate" or "CodePush.sync({...})"?

**Comment by yz1311** [comment]
> > Same issue.Can't get update now!
> 
> Did you get update by the function of "CheckForUpdate" or "CodePush.sync({...})"?

I works now....Looks like a network fluctuation.

**Comment by mark5566** [comment]
> > > Same issue.Can't get update now!
> > 
> > 
> > Did you get update by the function of "CheckForUpdate" or "CodePush.sync({...})"?
> 
> I works now....Looks like a network fluctuation.

At the moment , Beijing 2019.05.10 09:44, it's work, made me crazy

**Comment by yuri-kulikov** [comment]
Hi @mark5566, @yz1311 
Thanks for reporting!

You're right, we've been having some performance issues during _peak hours (13:00 - 15:00 UTC+00)_ lately. Sorry about that. We are working on resolving this situation but we have no ETA at the moment.

**Comment by mark5566** [comment]
Thanks for replying

**Comment by mark5566** [comment]
> Hi @mark5566, @yz1311
> Thanks for reporting!
> 
> You're right, we've been having some performance issues during _peak hours (13:00 - 15:00 UTC+00)_ lately. Sorry about that. We are working on resolving this situation but we have no ETA at the moment.

Thanks for replying !

**Comment by JackClown** [comment]
Can not connect to the server for hours last Saturday😔.

**Comment by canyara** [comment]
It is always failed to connect the server in China

**Comment by nimo007** [comment]
I have the same issue in China

**Comment by buffge** [comment]
l'm chinese developer, my apps can't connect update server

**Comment by yz1311** [comment]
> Hi @mark5566, @yz1311
> Thanks for reporting!
> 
> You're right, we've been having some performance issues during _peak hours (13:00 - 15:00 UTC+00)_ lately. Sorry about that. We are working on resolving this situation but we have no ETA at the moment.

Most of a day,it cannot connect the server now!

**Comment by mark5566** [comment]
@yz1311 I am tring to buy and build a server for code-push-server

**Comment by LewinJun** [comment]
> It is always failed to connect the server in China

me too

var requestUrl = this._serverUrl + this._publicPrefixUrl + "update_check?" + queryStringify(updateRequest);
        this._httpRequester.request(0 /* GET */, requestUrl, function (error, response) {
            if (error) {
                callback(error, null);
                return;
            }

this error  is  Network request failed

**Comment by LewinJun** [comment]
react-native-codepush  version  5.7.0

**Comment by quanzaiyu** [comment]
Two months ago, I can update my app in China. But recently, always can't connect to the update server.

**Comment by TrustTheBoy** [comment]
> 两个月前，我可以在中国更新我的应用程序。但是最近，始终无法连接到更新服务器。

I have the same issue in China

**Comment by alexandergoncharov** [comment]
Hi all,
Sorry for the delay!

If I understand correctly that issue should be fixed now. So, I'm going t close this issue for now.
Please feel free to reopen it if you have questions or faced this issue again.
