### ISSUE TITLE
In RN0.59.5,  always get "Network request " in physical device

### ISSUE THREAD

**Issue by Jeijie** [microsoft/react-native-code-push#1586]
react-native-code-push works well in similator, but always get "Network request " in physical device

### Steps to Reproduce
1.react-native init  project
2. add react-native-code-push plugin add call sync method
3.code-push app add project and release a project
4.react-native run-ios
5.go to Xcode "build and run" in device

### Expected Behavior
show update dialogue in simulator and device

### Actual Behavior
show update dialogue in simulator but get "Network request failed" error

![image](https://user-images.githubusercontent.com/9338052/57676844-0c798180-7658-11e9-8f8b-75bc7e6c9113.png)

### Environment

* react-native-code-push version: 5.6.0
* react-native version:0.59.5
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?  yes
* Does this reproduce on a simulator, or only on a physical device?  works well in simulator, get error in physical device

(The more info the faster we will be able to address it!)

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 55.04 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 26.0.3, 27.0.3, 28.0.1, 28.0.3
        System Images: a...-tv | Android TV ARM EABI v7a System..., a... | Android TV Intel x86 Atom Syst..., a...ear | Android Wear ARM EABI v7a Syst..., a...ndroid-wear | Android Wear Intel x86 Atom Sy..., a... | Intel x86 Atom_64
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by alexandergoncharov** [comment]
Hi @Jeijie,
Thanks for reporting!

I just tested your case and successfully got update. Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

Thanks,
Alexander

**Comment by Jeijie** [comment]
thanks for your reply,It seems that sometimes can't connect server codepush.azurewebsites.net. sometimes works well. #1583

**Comment by canyara** [comment]
There are some network issue in China when connect to codepush.azurewebsites.net

**Comment by alexandergoncharov** [comment]
Hi @Jeijie. Could you please clarify issue is still here?

@canyara, Yeah, sometimes we have connection issues in China. Could you please clarify have you tested it with VPN?

**Comment by buffge** [comment]
china network can't connect. l can't let my customers use vpn

**Comment by canyara** [comment]
> Hi @Jeijie. Could you please clarify issue is still here?
> 
> @canyara, Yeah, sometimes we have connection issues in China. Could you please clarify have you tested it with VPN?

I test with it with VPN, its ok. And I test from different locations in China, almost every connect is timeout. I found there is only 1, 2 services IPs now.I also tested several months ago, that time there are lots of services IP and all connect speed is fast and only 100ms-500ms delay. Is there any way to used Chinese Azure service to deploy codepush?

**Comment by Jeijie** [comment]
Hi @alexandergoncharov , I just tested it in IOS simulator,the connection issue still here.
     @canyara I also tested several months ago, almost every check update works.


![A2B18919-FF39-4EA1-AF3F-FBFBB3CD8DDC](https://user-images.githubusercontent.com/9338052/58692471-3bfeec80-83c1-11e9-939d-69996b7ac08c.png)

**Comment by canyara** [comment]
> Hi @alexandergoncharov , I just tested it in IOS simulator,the connection issue still here.
> @canyara I also tested several months ago, almost every check update works.
> 
> ![A2B18919-FF39-4EA1-AF3F-FBFBB3CD8DDC](https://user-images.githubusercontent.com/9338052/58692471-3bfeec80-83c1-11e9-939d-69996b7ac08c.png)

It seems codepush azure server ip is changed. Serveral months ago there were money servers from all around the world and now there is only one server in US.

@alexandergoncharov Is there any way we can deploy the service in China Azure?

**Comment by alexandergoncharov** [comment]
Hi @canyara, @Jeijie ,
Sorry for so long delay.

It looks like that connection is stable for now. Could you please let me know if the connection issue is still here or you still face this issue?

**Comment by alexandergoncharov** [comment]
Hi @canyara , @Jeijie ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
