### ISSUE TITLE
CodePush update successfully after restart some times

### ISSUE THREAD

**Issue by thaitanloi365** [microsoft/react-native-code-push#1590]
I customized a dialog to show when there has new version. Here my source for custom dialog: https://github.com/thaitanloi365/rn-codepush-dialog

But the issue described below always happen. Please help to fix this issue.

### Steps to Reproduce
1. Open app, downloading package, click restart button after package installed.
2. After app restart , the popup still show, try to do same as step 1.
3. After 3 times step 1, app is updated successfully.

https://vimeo.com/user98598441/review/336652606/97125810eb

### Expected Behavior
App shouldn't restart a few times.

### Actual Behavior
App update successfully after restart 3 times.

### Environment
* react-native-code-push version: 5.5.2
* react-native version: 0.59.8
* iOS/Android/Windows version: iOS & Android.
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by yuri-kulikov** [comment]
Hey @thaitanloi365,
Thanks for asking!

Sorry, the video isn't available at the moment.

I tried using the app from your package example folder, but I had troubles testing it in release mode, the app just didn't check for updates. I managed to see the dialog only in debug (and only with working Metro bundler). Do you have such problems with this example app or is it just me?

**Comment by thaitanloi365** [comment]
Thanks for your response.
Are you replace current key with your new key ?. The issue above only happened in release mode sometimes. In debug, It working as expected.
Could you download and look the issue from this link ? [https://ufile.io/jf49gwdp](url)

**Comment by yuri-kulikov** [comment]
@thaitanloi365 Yes, I replaced the key and released some updates.
I've downloaded and watched the video. Yeah, looks strange, but I still can't reproduce it stably on the example app.

**Comment by thaitanloi365** [comment]
@yuri-kulikov , Yes, I tested with debug this issue not happened, but when running on release mode, sometime this issue happened cause I couldn't debug in release mode.

**Comment by yuri-kulikov** [comment]
@thaitanloi365, I forgot to mention, I used the Android version of the app, maybe that's why we have a different experience. You can try to test your package in the release on the Android platform.

I'm not sure why, but I can't make this example app to get the update on iOS.

Could you please provide us with instruction on how we can reproduce the issue consistently?

**Comment by thaitanloi365** [comment]
@yuri-kulikov , Both platform same behavior. I don't known why but when I change version from 1.0 to 1.0.0 (iOS) and code push working on release mode.

The issue sometime happens when I release a version to the user. Some user installed successfully with status CodePush.SyncStatus.UPDATE_INSTALLED and press restart button in app to take effect. But the function CodePush.checkForUpdate always return new version package cause the popup update always show.

I check and show dialog manually, you can view it from my code.

Thanks you.

**Comment by yuri-kulikov** [comment]
@thaitanloi365 I've updated the package from your repo and now I'm can test the app in release build on Android (but I think it was my mistake because I mixed up the deployment keys).
It works fine now (without the issue):
![Kapture 2019-06-03 at 17 31 23](https://user-images.githubusercontent.com/42337914/58815775-e466b800-8630-11e9-995c-6c7f110235c4.gif)

As a next step, I will retry it in iOS.

**Comment by yuri-kulikov** [comment]
The same with iOS:

![Kapture 2019-06-03 at 19 25 12](https://user-images.githubusercontent.com/42337914/58817927-90120700-8635-11e9-9fe3-0545d0fda21d.gif)

Maybe it was fixed by the latest commit in your repository?

**Comment by thaitanloi365** [comment]
@yuri-kulikov Many thanks for your support. This issue didn't happen when I try to test 4-5 times. Maybe It fixed, let me close this issue.

**Comment by yuri-kulikov** [comment]
@thaitanloi365 Glad to help!
Thanks for using CodePush 👍
