### ISSUE TITLE
[Android] Support versionNameSuffix for builds with flavours

### ISSUE THREAD

**Issue by wojteg1337** [microsoft/react-native-code-push#1591]
### Motivation
I'm unable to update application via CodePush when Android app is using versionNameSuffix

### Steps to Reproduce
1. Add versionNameSuffix to Android app in app/build.gradle.
2. Release new version.
3. Unexpected error in the logcat console.

![image](https://user-images.githubusercontent.com/18573330/57919931-25717500-789a-11e9-8974-5a5e71c27f03.png)

### Expected Behavior
What did you expect to happen?

Allow user to add custom app version in CLI command
`code-push release-react madzia2019ios -d Staging -t 1.1_staging`

### Actual Behavior
What actually happens?

When syncing with CP, I can see the error in the console - I'm unable to download an update.
![image](https://user-images.githubusercontent.com/18573330/57920011-4f2a9c00-789a-11e9-9b3b-f83354a5ba48.png)

**Comment by yuri-kulikov** [comment]
Hey @wojteg1337,
Thanks for asking!

You can use a valid `semver` version, for example `1.1.0-staging`.

**Comment by wojteg1337** [comment]
Hey @yuri-kulikov,
will check that :) thanks for quick response
