### ISSUE TITLE
(ios) after restart app, read local information instead of updated

### ISSUE THREAD

**Issue by flutterhope** [microsoft/react-native-code-push#1592]
### Steps to Reproduce
1. install app from app store(ios)
2. update from codepush successful
3. turn off the app
4. turn on the app again, and then read local information instead of updated information.

I know there are articles that have similar symptoms to me.
But the solution in those articles does not seem to help me.

this is my App.js
![image](https://user-images.githubusercontent.com/39448892/58060805-1813fd80-7bae-11e9-85e9-5e960a55d2d4.png)

this is initialize scene (Init.js)
.......
async processCodePush() {
        return new Promise((resolve, reject) => {
            CodePush.sync(
                {
                    installMode: CodePush.InstallMode.IMMEDIATE,
                    updateDialog: true,
                },
                syncStatus => {
                    ....
                },
                this.codePushDownloadDidProgress.bind(this)
            ).catch(err => {

            })
        })
    }
.......

this is codepush production
actually no rollback.

![image](https://user-images.githubusercontent.com/39448892/58060908-a1c3cb00-7bae-11e9-9caf-951c58e50528.png)

### Environment

* react-native-code-push version:5.6.0
* react-native version: 0.59.5
* iOS/Android/Windows version: ios 12.2
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? physical device

**Comment by alexandergoncharov** [comment]
Hi @flutterhope,
Thanks for reporting!

>4. turn on the app again, and then read local information instead of updated information

Could you please clarify what kind of information you see and where? Screenshot would be great. =)

Thanks,
Alexander

**Comment by flutterhope** [comment]
@alexandergoncharov 
Hello, Sorry I could not prepare the screenshot.

Simply telling that, after getting update with codepush, it is rolled back when I turn off the app and restart it.

CodePush.checkForUpdate says there are no new updates.
(only ios problem)

**Comment by alexandergoncharov** [comment]
Hi @flutterhope,
Thanks for reporting!

Oh, I see. So, it looks like you have some issues in your update. Could you please share your logs during update and restart?

**Comment by alexandergoncharov** [comment]
Hi @flutterhope 
Thanks for reporting!

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
