### ISSUE TITLE
RN 0.59.8 after linked libraries  has no CodePush

### ISSUE THREAD

**Issue by CangJL** [microsoft/react-native-code-push#1594]
yarn add react-native-code-push
react-native link react-native-code-push

Terminal display has link successfully，but there's no in Xcode libraries.

"react": "^16.8.6",
"react-native": "0.59.8",

**Comment by yuri-kulikov** [comment]
Hey @CangJL,
Thanks for reporting!

> Terminal display has link successfully，but there's no in Xcode libraries.

Could you explain a bit what do you mean?

I've created a simple project:

- `react-native init Issue1594 --version react-native@0.59.8`
- `cd Issue1594`
- `yarn add react-native-code-push`
- `react-native link react-native-code-push`
- Opened `Issue1594/ios/Issue1594.xcodeproj` with Xcode
- I can see `CodePush.xcodeproj` in **Libraries**
  ![Screenshot 2019-05-24 at 12 11 49](https://user-images.githubusercontent.com/42337914/58317170-ed2fe080-7e1d-11e9-8913-d9d8a9ff92f6.png)

**Comment by sercanov** [comment]
I also had the same problem. 

Before installing `react-native-code-push`, I've installed` appcenter` `appcenter-analytics` and `appcenter-crashes` so it created Podfile and xcworkspace, it may related to this.

**Comment by thekevinbrown** [comment]
I've found you need to run `react-native link react-native-code-push` twice. The first time you run it it adds the pods, the second time you run it it'll actually install them.

**Comment by yuri-kulikov** [comment]
Sorry for the delay!

So, if you are using **Pods** you need to run a `pod install` after `link`.
I think we should add the `pod install` step to our postlink script. It will be more convenient.

**Comment by yuri-kulikov** [comment]
Hey, guys, I checked it out and discussed it with the team. We decided that it's better to leave it as is.  As stated in our [documentation](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---cocoapods), **rnpm** and **pods** are two different ways to install `react-native-code-push` plugin. It was not originally planned that the two methods would be used together. So it's a kind of overkill to run `pod install` on post-link.

The proper way to install the `react-native-code-push` plugin with pods is:

1. Add CodePush plugin dependency in a Podfile:
   ```ruby
   # CodePush plugin dependency
   pod 'CodePush', :path => '../node_modules/react-native-code-push'
   ```
2. Use `pod install`.
3. Perform further [configuration steps](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-configuration-ios).

**Comment by alexandergoncharov** [comment]
Hi all,

As the decision was to keep it so and we don't have an additional conversation for a while, I'm going to close this issue for now.
Please feel free to reopen it if you have any questions.
