### ISSUE TITLE
[iOS] duplicate symbols for architecture (libSSZipArchive.a and libJWT.a)

### ISSUE THREAD

**Issue by mistikk** [microsoft/react-native-code-push#1597]
When I try to get build for iOS project, it is getting error about duplicate symbols. It is about libSSZipArchive.a and libJWT.a libraries. 

I investigated all issues about that. Before v5.2.2, we could ignore jwt and SSZipArchive libraries with subspecs. But this feature removed with this pr #1210. I think we can find a solution for that or add again to subspecs.

Same issues before v5.2.2;
#1378
#1123
#1114
#241

### Steps to Reproduce
1. react-native link react-native-code-push
2. react-native run-ios

### Expected Behavior
Successful build

### Actual Behavior
What actually happens?

![image](https://user-images.githubusercontent.com/8211075/58440480-f7363580-80e2-11e9-9f66-8715e2f88ee6.png)

/Users/XXX/Library/Developer/Xcode/DerivedData/eSteem-ecgmyvokxqytbxcykhiowcvasalg/Build/Products/Debug-iphonesimulator/libCodePush.a(SSZipArchive.o)
    /Users/XXX/Library/Developer/Xcode/DerivedData/eSteem-ecgmyvokxqytbxcykhiowcvasalg/Build/Products/Debug-iphonesimulator/SSZipArchive/libSSZipArchive.a(SSZipArchive.o)
ld: 271 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Reproducible Demo

* Download https://github.com/esteemapp/esteem-mobile

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.8
* iOS/Android/Windows version: iOS 12
* Does this reproduce on a debug build or release build? Both of them
* Does this reproduce on a simulator, or only on a physical device? All of them

**Comment by yuri-kulikov** [comment]
Hey @mistikk,
Thanks for reporting!

I've cloned your project and used this:

- `react-native link react-native-code-push`
  ![Screenshot 2019-05-31 at 18 05 58](https://user-images.githubusercontent.com/42337914/58715654-044b7100-83d0-11e9-8666-4d49295c6171.png)
- `react-native run-ios`

App launched without this error. What should I do to reproduce the issue?

**Comment by mistikk** [comment]
@yuri-kulikov did you link all of libraries, because it throws duplicate library error on me, so if you linked just code-push, it launches as successfully

**Comment by yuri-kulikov** [comment]
@mistikk, Oh, you're right, I guess I missed that moment. I'll link all the libs and test it again, thanks!

**Comment by yuri-kulikov** [comment]
Hey @mistikk, Sorry for the delay, I have some problems reproducing the issue.
As far as I can see, the libraries are already linked in your app and you use updated react-native-code-push plugin. Could you help me with a simple step-by-step instruction on how to reproduce the issue using your application?

**Comment by mistikk** [comment]
Yes right I updated to code push library for fix to this issue.

1 - Change react-native-code-push version with lastest on package json (v5.6.0)
2 - run `react-native link` code
3 - run `react-native run-ios` code

After that you should see this error. If you cannot see, please remove cache and get clean build

**Comment by yuri-kulikov** [comment]
@mistikk, thanks!

I've tried to do it but faced this as:
![Screenshot 2019-06-06 at 17 47 07](https://user-images.githubusercontent.com/42337914/59042517-41f24300-8883-11e9-8913-2e5fc2928215.png)

Could you try to test these steps on the fresh `git clone` folder?

**Comment by jkepps** [comment]
I'm also seeing this same error now that I've begun migrating from the Legacy Build System to the Modern Build System. happy to provide any information that might help get to the bottom of this.

**Comment by yuri-kulikov** [comment]
Hey @jkepps, I would be very grateful if you could help me with some simple demo app to reproduce the issue or at least some steps to reproduce it!

**Comment by rodrigomf24** [comment]
Is there any update on this? I am getting the same issues with duplicate symbols 🤦‍♂

**Comment by rodrigomf24** [comment]
For those who are still stumbling with this issue and are using a RN version < 0.59 try these steps:
```bash
yarn add react-native-code-push@5.2.2 
react-native link react-native-code-push
cd ios && pod install
```

then open xcode worskpace and rebuild

This worked for me

**Comment by infostreams** [comment]
The above didn't work for me. What did work was [a solution to a similar issue](https://github.com/react-native-community/react-native-maps/issues/718#issuecomment-257476236) that I found for another React Native library. That solution is as follows:

(ref.: http://stackoverflow.com/questions/24298144/duplicate-symbols-for-architecture-x86-64)

1.    Open Xcode > Pods > Targets Support Files > Pods-{TARGET-NAME}
2.   find "OTHER_LDFLAGS" and remove '-l"Base64"', '-l"SSZipArchive"' and '-l"JWT"' in these two files: Pods-{TARGET-NAME}.release.xcconfig & Pods-{TARGET-NAME}.debug.xcconfig
3.   I deleted the build/Build folder in ios and run-ios again. It works now.

Side effects from the link above: the app may become larger as there may be duplicated symbols during compile

**Comment by infostreams** [comment]
The solution above breaks once you do 'pod update' or 'pod install'. You can address that by adding the following to your Podfile:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "Pods-MYPROJECT"
            puts "Updating #{target.name} OTHER_LDFLAGS"
            target.build_configurations.each do |config|
                xcconfig_path = config.base_configuration_reference.real_path

                # read from xcconfig to build_settings dictionary
                build_settings = Hash[*File.read(xcconfig_path).lines.map{|x| x.split(/\s*=\s*/, 2)}.flatten]

                # modify OTHER_LDFLAGS to prevent certain libraries from (double) linking
                build_settings['OTHER_LDFLAGS'] = build_settings['OTHER_LDFLAGS'].sub('-l"Base64"', '').sub('-l"SSZipArchive"', '').sub('-l"JWT"', '')

                # write build_settings dictionary to xcconfig
                File.open(xcconfig_path, "w") {
                  |file| build_settings.each do |key,value| file.puts "#{key} = #{value}" end
                }
            end
        end
    end
end
```

**Comment by alexandergoncharov** [comment]
Hi all,
Sorry for that big delay!

Could you please test your issue apps with the latest versions of `react-native` and `react-native-code-push` with `autolink` and please let me know if this issue is still here?

**Comment by alexandergoncharov** [comment]
Hi all,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
