### ISSUE TITLE
Registered apps that don't differentiate between platforms

### ISSUE THREAD

**Issue by vitozyf** [microsoft/react-native-code-push#1599]
There was no platform distinction, just for android updates. Now that I want to differentiate between IOS and android, what should I do?

**Comment by yuri-kulikov** [comment]
Hey @vitozyf,
Thanks for asking!

If I get this right, you have one application in AppCenter and you use the same CodePush deployment for Android and iOS.
In that case, you can create a new app in AppCenter (for example, "AppName-iOS"), create CodePush deployments and use a new deployment key in the next version of your iOS application. This way, you to make releases for both versions of your app separately.

This is typically used for different versions of the application. Please let me know if you have any questions!

**Comment by vitozyf** [comment]
> Hey @vitozyf,
> Thanks for asking!
> 
> If I get this right, you have one application in AppCenter and you use CodePush deployments for Android.
> In that case, you can create a new app in AppCenter (for example, "AppName-iOS"), create CodePush deployments and use a new deployment key in the iOS version of your application. This way, you to make releases for both versions of your app separately.
> 
> This is typically used for different versions of the application. Please let me know if you have any questions!

Thank you for your reply

**Comment by yuri-kulikov** [comment]
Glad to help, thanks for using CodePush!
