### ISSUE TITLE
React Native - iOS - Update is downloaded and installed but old bundle is loaded

### ISSUE THREAD

**Issue by Luke-Gurgel** [microsoft/react-native-code-push#1600]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Install, link (w/ `react-native link react-native-code-push`) and configure `react-native-code-push` v5.6.0
2. Add `codePush.sync().then(() => codePush.notifyAppReady())` to `App.js`
3. Run `react-native run-ios --device` to install the app on the device
4. Close the app and the development server 
5. Make changes in javascript code (e.g. UI change) 
6. Run `appcenter codepush release-react ... Staging` command 
7. Reopen the app on device (w/o dev server running)

### Expected Behavior
What you expected to happen?

I expected to see the changes I made to the UI, given that the update was downloaded and installed.

### Actual Behavior
What actually happens?

The old bundle that was installed when I ran  `react-native run-ios --device` is loaded instead of the new one, so the changes are not applied.

### Reproducible Demo

* I've added the staging key to `info.plist`
* **I've added `return [CodePush bundleURL];` to the `sourceURLForBridge`.**  (this is probably the problem)
* I've added `codePush.sync()` to perform a silent update so that changes are applied on next restart, but still, the app loads the old bundle.
* I've added `codePush.notifyAppReady()` after the promise that's returned from `codePush.sync()` resolves, but still same issue. 
I* 'm using `codePush.getUpdateMetadata(CodePush.UpdateState.RUNNING)` to get information about the current package and it displays the correct info, meaning, the new updated package (although the app doesn't reflect its contents).

If the `installMode` is set to `ON_NEXT_RESTART`, the updated bundle never takes over, but if set to `IMMEDIATE`, the new bundle does take over. But if I close the app and reopen it, the old bundle is loaded again, which makes me think that the problem lies in `AppDelegate.m`, on how `sourceURLForBridge` is being set.

```
// AppDelegate.m

#import "AppDelegate.h"
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <CodePush/CodePush.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"myProject"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [CodePush bundleURL];
#endif
}

@end
```

```
// App.js

import React from 'react';
import codePush from 'react-native-code-push';
import { Provider } from 'react-redux';
import Amplify from 'aws-amplify';
import { Rehydrated } from 'aws-appsync-react';
import { ApolloProvider } from 'react-apollo';
import Bootstrap from 'src/components/rootComponents/Bootstrap';
import AppSyncClient from './src/aws/AppSyncClient';
import configureStore from './src/redux/store';
import awsconfig from './aws-exports';

Amplify.configure(awsconfig);
const store = configureStore(); 

const App = (): JSX.Element => {
  // tried this without the config object in the codePush HOC
  codePush.sync();

  return (
    <ApolloProvider client={AppSyncClient}>
      <Rehydrated>
        <Provider store={store}>
          <Bootstrap />
        </Provider>
      </Rehydrated>
    </ApolloProvider>
  );
};

// Tried adding a config object here w/o calling codePush.sync()
// Also called codePush.notifyAppReady() but not luck

export default codePush({
  checkFrequency: codePush.CheckFrequency.ON_APP_START,
  installMode: codePush.InstallMode.IMMEDIATE,
  updateDialog: {
    appendReleaseDescription: true,
  },
})(App);
```

```
// Some component that's just displaying package info
// The info that's retrieved is always right, which means the
// update was downloaded and installed, it's just not being used

const PackageInfo = (): JSX.Element => {
  const [pkg, setPkg] = useState({
    label: '',
    description: '',
    isPending: true,
    failedInstall: true,
  });

  useEffect(() => {
    codePush.getUpdateMetadata(CodePush.UpdateState.RUNNING)
      .then((res) => {
        if (res) {
          const { isPending, failedInstall, description, label } = res;
          setPkg({ label, description, isPending, failedInstall });
        }
      });
  }, [pkg]);

  return (
    <View>
      <Text>
        { JSON.stringify(pkg) }
      </Text>
    </View>
  );
};
```

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.8
* iOS/Android/Windows version: iOS 12.3.1 
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @Luke-Gurgel,
Thanks for reporting!

Could you please provide also logs during update? You can grab it with XCode.

**Comment by alexandergoncharov** [comment]
Also, I see that you used debug build. In this case, with running dev server, you will always download sev server version bundle instead for CodePush bundle. For fixing this you should close dev server or run your app with release build.

Please let me know if it was helpful or you have any questions.

**Comment by Luke-Gurgel** [comment]
@alexandergoncharov switching the scheme from debug to release made it work. Thanks so much.

**Comment by alexandergoncharov** [comment]
Great! Thanks for letting us know.

I'm going to close this issue as it was resolved.
Please feel free to reopen it if you have any questions.
