### ISSUE TITLE
React Native, code push update remove previous images

### ISSUE THREAD

**Issue by VincenzoCarlino** [microsoft/react-native-code-push#1602]
When I install the app everything is ok, all images are loaded, if I make a normal update with code push (where for e.g. I change only a string and nothing more) every asset of the app disappear. Please help!

React Native version: 0.56.0
Code push version: 5.6.0

**Comment by yuri-kulikov** [comment]
Hey @VincenzoCarlino, 
Thanks for reporting!

Could you please clarify a few more things?

1. iOS/Android/Windows version?
2. Does this reproduce on a debug build or release build?
3. Does this reproduce on a simulator, or only on a physical device?
4. How do you use CodePush package in your js code?

**Comment by yuri-kulikov** [comment]
Hi @VincenzoCarlino,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
