### ISSUE TITLE
Codepush update is loaded but code doesn't take affect after restart

### ISSUE THREAD

**Issue by MrLoh** [microsoft/react-native-code-push#1603]
I am encountering a very strange issue on iOS that I cannot make sense of at all. 

I am deploying a CodePush update and I also get it at first in my app, but after restarting the app, the update doesn't take affect anymore. I first though that the update was rolled back of course, so I added extensive logging to our app, but then I realized that `getUpdateMetadata` still displays the label of the latest release, and that `notifyAppReady` never returns a `statusReport.status` of `DeploymentStatus.FAILED` but is called after installing the update with `DeploymentStatus.SUCCESS`. So somehow the update seems to be there as `getUpdateMetadata` proves but the code doesn't take affect anymore after a restart. 

I am starting to run out of ideas for what could be happening here. Any help would be greatly appreciated.

* react-native-code-push version: 5.6.0
* react-native version: 0.59.5
* iOS version: iOS 12.3.1
* Does this reproduce on a debug build or release build? production build
* Does this reproduce on a simulator, or only on a physical device? not tried on simulator, reproducible on all iOS devices I have tested

**Comment by MrLoh** [comment]
It turned out, that I broke our CodePush setup while updating to RN 0.59, where the js bundle loading API changed

**Comment by yuri-kulikov** [comment]
Hey @MrLoh, I've been investigating the issue, thanks for letting us now. Good to know that everything is ok now 👍 
Thanks for using CodePush!

**Comment by WickyLeung** [comment]
same issue

**Comment by MrLoh** [comment]
@WickyLeung did you make sure that you have everything implemented as per the reader instruction in your AppDeegate. I broke my setup when updating react native.

**Comment by WickyLeung** [comment]
@MrLoh yeah, but I still get error like this issue.

**Comment by MrLoh** [comment]
@WickyLeung open your own new issue with a clear description of your specific problem. I doubt it’s the same, since you have provided no details. I debugged this for a day, read the codepush source code and added error handling to make sure a lot of cases where ruled out.

**Comment by AdamGold** [comment]
@MrLoh Can you share your updated code after fixing this? The same thing happened to me after upgrading to RN 0.59.

**Comment by WickyLeung** [comment]
@MrLoh hey bro,i had fixed my bug and the reason is my assets files named with chinese.  you can refer to this:http://www.uedlinker.com/2019/01/23/yi-ci-codepushre-geng-shi-bai-de-zong-jie/

**Comment by MrLoh** [comment]
@AdamGold just make sure to go through the setup instructions again and verify all is still set up correctly in app delegate

**Comment by lighthx** [comment]
me too

**Comment by MrLoh** [comment]
@lighthx did you read the comments??? What are you trying to say.
