### ISSUE TITLE
How to test code push changes manually with android device

### ISSUE THREAD

**Issue by cullsin** [microsoft/react-native-code-push#1605]
Hi, 

It's not an Issue. 

I have generated an apk and Installed in the device. Now, I made a change for code-push and suggest me what I suppose to do to test code-push effect?

Maybe you can mention in the README Section.

Raja K

**Comment by alexandergoncharov** [comment]
Hi @cullsin 
Thanks for reporting!

I see that you already asked the same questions in other repo: https://github.com/microsoft/code-push/issues/633 and it is already answered =)

Let's keep our conversation in one place. So, I'm going to close this issue for now as duplicate and continue our conversation in original issue https://github.com/microsoft/code-push/issues/633.

Please feel free to reopen this issue if you have any questions.
