### ISSUE TITLE
Invalid variable name Error

### ISSUE THREAD

**Issue by itzsaga** [microsoft/react-native-code-push#1606]
### Steps to Reproduce
1. Run `react-native run-android`

### Expected Behavior
The app to run.

### Actual Behavior

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/seth/Airship/coth/highlandsApp/android/app/build.gradle' line: 125

* What went wrong:
Could not compile build file '/Users/seth/Airship/coth/highlandsApp/android/app/build.gradle'.
> startup failed:
  build file '/Users/seth/Airship/coth/highlandsApp/android/app/build.gradle': 125: Invalid variable name. Must start with a letter but was: “String”
  . At [125:30]  @ line 125, column 30.
                 buildConfigField “String”, “CODEPUSH_KEY”, ‘"******************************"’
                                  ^

  1 error
```

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.9
* iOS/Android/Windows version: Android 8.1.0
* Does this reproduce on a debug build or release build? Debug.
* Does this reproduce on a simulator, or only on a physical device? Both.

React Native 0.59.9 made this change:

> Bump Gradle to 5.4.1 & Android Gradle plugin to 3.4.0

Could this be the culprit?

**Comment by itzsaga** [comment]
Figured it out, copy/paste issue. The quote wasn't a real quote.

**Comment by shuzootani** [comment]
Hi @itzsaga,
Was there any changes that you had to do when you updated react native 0.59.9 for code push?

**Comment by itzsaga** [comment]
@shuzootani I upgraded to 0.59.9 before I setup code push. So no.
