### ISSUE TITLE
AppCenter Fails when not Universal Apk

### ISSUE THREAD

**Issue by alanjonesrios** [microsoft/react-native-code-push#1607]
### Steps to Reproduce
1. Build any app in appcenter with build.gradle config :
def enableSeparateBuildPerCPUArchitecture = true

splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }

He will build and sign normally, but when he tries to send to the store he fails to find the apk's folder with this message:

2. ##errorPublishing build artifacts failed with an error: Not found PathtoPublish: /Users/vsts/agent/2.150.3/work/1/a/build

### Expected Behavior
If build.gradle is config to use an universal apk, it works normally and send the store

### Actual Behavior
He fails to find the resultant build apk folder

![8gRG9XLETaeus7mB0xZiGA](https://user-images.githubusercontent.com/47225665/59113827-33a43580-891c-11e9-9f2a-6e4a00f8fa1e.png)

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.8
* Does this reproduce on a debug build or release build? Release Mode

**Comment by alexandergoncharov** [comment]
Hi @alanjonesrios,
Thanks for reporting!

I'm not sure that this issue form CodePush. Could you please ensure this? You should just remove CodePush plugin and check if it works.
If it isn't from CodePush then I can suggest you write this to support. This is a message icon in right down corner on `appcenter.ms`.

**Comment by alanjonesrios** [comment]
Not an issue related to codepush, its actually an appcenter problem. thks any way.
AppCenter don't support building separate APKs per architecture. For now.

**Comment by alexandergoncharov** [comment]
oh, year, I see. Thanks for letting us know.
So, I'm going to close this issue for now as issue is external.

Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by thienthaitechnology** [comment]
<img width="1022" alt="Screen Shot 2020-04-23 at 1 18 23 AM" src="https://user-images.githubusercontent.com/63989332/80018632-7ce38080-8500-11ea-92fa-13dfde7b7be4.png">
it still not support

**Comment by ryantando** [comment]
Seems, its still not support

**Comment by eflorespalma** [comment]
Hi folks, 
any updates about this?

**Comment by RexkentZheng** [comment]
> Hi folks, any updates about this?

Seems like it's stil not support
