### ISSUE TITLE
Staging Deployment key has changed a new one

### ISSUE THREAD

**Issue by dao-wkm** [microsoft/react-native-code-push#1608]
I initialized Code Push, I had a Production and Staging key, them seem the same on format. Recently, I deploy the app, it catch error `Error: 404: {}`. Then i check my keys and found that Staging deployment key has changed a new one, it's not same as before.

### Steps to Reproduce
1. `code-push deployment ls My-App-iOS -k`
### Actual Behavior
Staging Deployment key has changed a new one.
Look at the Production and Staging key, it's not same format

Old Keys:
<img width="783" alt="Screen Shot 2019-06-08 at 1 32 35 PM" src="https://user-images.githubusercontent.com/42726313/59143166-0aee6f80-89f2-11e9-8a25-315eebf045dd.png">

New Keys:
<img width="1103" alt="Current keys" src="https://user-images.githubusercontent.com/42726313/59143003-b39bcf80-89f0-11e9-8bf4-7669083db067.png">

### Environment
* react-native-code-push version: 5.6.0
* react-native version: 0.56.1

**Comment by yuri-kulikov** [comment]
Hey @dao-wkm,
Thanks for reporting!

As far as can I see, it looks like your deployments were created using the CodePush CLI, and then one of these deployments was deleted and then created again with the same name using AppCenter CLI or AppCenter portal (I can see this by the key format). Is it possible that you or someone who has access did this unintentionally?

**Comment by dao-wkm** [comment]
Hi @yuri-kulikov
Thanks for reply

Maybe, i tried some commands with APP with CLI AppCenter. How do I fix this problem (get back the Key of Code Push CLI).
Have the previously released App including the old key still work with this new key?

**Comment by dao-wkm** [comment]
Hi @yuri-kulikov
Thanks for reply

Maybe i tried some commands with CLI AppCenter. How do I fix this problem (reverse to old key).
Have the previously released App including the old key still work with this new key?

**Comment by yuri-kulikov** [comment]
@dao-wkm Unfortunately, deleting a deployment is an irreversible operation and it's not possible to recreate the key of the deleted deployment. When you delete a deployment, no one can download updates using its deployment key.

The application can't use the previous deployment key to receive new updates, so you can update your application and set the new deployment key and then use this new deployment to deliver further updates.

**Comment by yuri-kulikov** [comment]
@dao-wkm, please let me know if it was helpful or you have any questions 🙂

**Comment by dao-wkm** [comment]
Thanks for help
