### ISSUE TITLE
React Native 0.19.0-RC changed the signature of RCTPromiseRejectBlock

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/react-native-code-push#161]
The RCTPromiseRejectBlock typedef was changed to accept three arguments, instead of one, and therefore, anyone trying to use CodePush with React Native 0.19.0-RC will have compilation errors on iOS. 

This is an obviously easy fix to make, but I'd like to add support for RN 0.19.0 without having to break compat with previous versions of RN. I validated the behavior of our plugin with this new platform version and everything works great, other than our need to respond to this typedef change.

**Comment by respectTheCode** [comment]
Any progress on this? RN 0.19 has been released.

**Comment by lostintangent** [comment]
@respectTheCode We'll be releasing the fix to NPM today. If you need to get unblocked sooner, you can take a look at PR #164 for the fix. Sorry for the delay!

**Comment by lostintangent** [comment]
This fix is now in master and will be released to NPM in the morning.
