### ISSUE TITLE
CodePush Deploy not picking up in US region

### ISSUE THREAD

**Issue by jake41** [microsoft/react-native-code-push#1612]
Hi Team,

I am able to perform codepush deploys for my app. We havent released the app to play-store. Currently we are running beta-release for android and testflight testing in IOS.

The issue is I am able to download/receive codepush react-native updates for my local region(India). But my counterpart sitting in LosAngeles is not receiving any updates. 

Can someone help me with this.

Thanks.

**Comment by yuri-kulikov** [comment]
Hey @jake41,
Thanks for reporting!

Do you and your counterpart use the same app build? First, you need to make sure that your applications use the same deployment key.
Also, do you have some logs (for example you can look in Android/iOS logcat for the logs with `[CodePush]` tag, to find out what's going on)?

**Comment by jake41** [comment]
@yuri-kulikov  thanks for the quick reply. We are using the same deployment key. Regarding logs, how will I get codepush logs from a real device. If in emulator, I can use the console logging, to see codepush events.

**Comment by yuri-kulikov** [comment]
@jake41, you can check android studio logcat when the device is connected (and USB debugging is enabled on the device).

**Comment by jake41** [comment]
@yuri-kulikov I am able to see code push logs in emulator. It is working fine. Issue is occuring for teammates in the US region

**Comment by alexandergoncharov** [comment]
Hi @jake41 ,
Sorry for that big delay.

Is this issue still actual for you?

**Comment by alexandergoncharov** [comment]
Hi @jake41 ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
