### ISSUE TITLE
When I call checkForUpdate method,report a error

### ISSUE THREAD

**Issue by 826327700** [microsoft/react-native-code-push#1617]
When I call checkForUpdate method:
CodePush.checkForUpdate('my deployment key').then((update) => {
            if (!update) {
                Alert.alert("Tips","no update")
            } else {
                Alert.alert("Tips","has update")
            }
        }).catch((err)=>{
            Alert.alert("Tips",JSON.stringify(err))
  });

some errors from the catch of promise will be returned:
**{"line":1135,"column":565,"sourceURL":"/var/containers/Bundle/Application/F11A86E9-F95F-414D-BEDB-687793DBC64B/cztecmerchant.app/main.jsbundle"}**

**Comment by yuri-kulikov** [comment]
Hey @826327700,
Thanks for reporting!

1. Do you have more detailed logs?
2. How often do you face this issue? 
3. Can you reproduce it stably?

Your problems may probably be related to the long response time of the CodePush server, but that's just a guess and we need more information.

**Comment by 826327700** [comment]
Thanks for your reply.
No more detailed logs. This issue is only existed in my project (I used cocopods in this project). I created another demo project and everything is well.

**Comment by yuri-kulikov** [comment]
@826327700 And this error occurs every time or only periodically?

**Comment by 826327700** [comment]
Hi Yuri,


It occurs all the time.


发自我的iPhone

------------------ Original ------------------

**Comment by phamhoaivu911** [comment]
Hi @yuri-kulikov , I'm facing the same issue. It works fine on my simulator. But it failed with the similar error above after I deploy the app to app center and install it to a real device.

Could you please help me with this issue? Please let me know if you need more information.

Thank you

**Comment by phamhoaivu911** [comment]
Hi @yuri-kulikov , I found the root cause of my issue. 

I use fastlane to deploy the app to AppCenter. During the deployment process, I append the branch to the version number so that I can distinguish different builds. So on AppCenter, the version is something like `1.1.0-fix-abc-xyz`, which is not a valid version. That's why it returned error `400: An update check must include a binary version that conforms to the semver standard (e.g. '1.0.0')`

@826327700 you should update your code to 
```javascript
CodePush.checkForUpdate('my deployment key').then((update) => {
  if (!update) {
    Alert.alert("Tips","no update")
  } else {
    Alert.alert("Tips","has update")
  }
}).catch((err)=>{
  Alert.alert("Tips", `Error: ${err.name}, Message: ${err.message}`)
});
```
Because the most important information of an error is name and message.

Hope this helps.

**Comment by 826327700** [comment]
> ```js
> CodePush.checkForUpdate('my deployment key').then((update) => {
>   if (!update) {
>     Alert.alert("Tips","no update")
>   } else {
>     Alert.alert("Tips","has update")
>   }
> }).catch((err)=>{
>   Alert.alert("Tips", `Error: ${err.name}, Message: ${err.message}`)
> });
> ```

![WechatIMG1](https://user-images.githubusercontent.com/23014381/61426219-39922b00-a94c-11e9-855d-70759fc3d7d5.jpeg)

**Comment by 826327700** [comment]
fetch is undefined

**Comment by oYangPingo** [comment]
Hi @yuri-kulikov, I'm facing the same issue. It works fine when I called codePush.checkForUpdate(deploymentKey) in the root Component of App.
But throw an error(the same to @826327700 ) when I called this function in the setting page(I want to check for update manually).

你好@yuri-kulikov，我也遇到和 @826327700 一样的问题，当我在App的根组件调用codePush.checkForUpdate(deploymentKey)的时候，是正常的。但是当我想在设置页加一个检测更新按钮，手动调用这个方法的时候，返回了和 @826327700 一样的错误，是必现的bug。

期待你的回复。

**Comment by alexandergoncharov** [comment]
Hi @826327700 , @phamhoaivu911 , @oYangPingo ,
Sorry for the delay!

Could please someone provide some demo app with reproducing issue and reprosteps? I would like to reproduce this issue and investigate it.

**Comment by marlti7** [comment]
same problem do you fix it @alexandergoncharov

**Comment by alexandergoncharov** [comment]
Hi @marlti7 , @826327700 , @phamhoaivu911 , @oYangPingo ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
