### ISSUE TITLE
[iOS] Staging build fails - framework not found Pod_[NameOfApp]

### ISSUE THREAD

**Issue by huseyin39** [microsoft/react-native-code-push#1619]
Hello,

Firstly, I would like to thank the CodePush team, the service is really nice and you do a great job. However I face an issue... :( 

I set up CodePush by following the procedures. Using CodePush through Debug (providing a key) & Release mode works well! I am able to make build.

When trying to build Staging on iOS, it fails while on Android it works.
The problem seems occurring when linking.
![Screen Shot 2019-07-01 at 2 02 50 PM](https://user-images.githubusercontent.com/32784666/60417196-07719100-9c0a-11e9-8fd7-6f2f0eff7cc6.jpg)

The issue looks more like React Native issue than CodePush itself.

* react-native-code-push version: 5.6.0
* react-native version: 0.59.9
* iOS/Android/Windows version: 12.3.2
* This happens on both simulator and device.

Thank you in advance, if you need any additional information, ask me!

I have tried the different solutions proposed but no one has worked yet.

**### EDIT: If I first build Release then building staging works (since Pods_framework exists in Release-iphone.../). Is the flow of creating staging imply to create first a Production build then a Staging one?**

**Comment by huseyin39** [comment]
I get back to you to tell you that I solved this issue. Actually the problem was in the step 7 of the multi-deployment-testing for iOS. Skipping this step allows to compiler correctly. I still had to re-link a few libraries.

But now it works!

**Comment by EternalChildren** [comment]
@huseyin39 hi i have the same problem . can you tell me how to solve it in ios platform.

**Comment by huseyin39** [comment]
As I said, I skipped the step 7 with the 'Per-configuration Build Products Path'.
I spent so much time on setting up CodePush. Wish you good luck man.
