### ISSUE TITLE
App always crashing on release build but crashes only once initially on debug

### ISSUE THREAD

**Issue by softCompound** [microsoft/react-native-code-push#1620]
I faced this issue while trying to update my project to react-native 0.59.8. The app builds just fine but crashes only once during the initial run on debug mode. However, from the second run after, everything functions properly. The release apk can be generated without any issue with ```gradlew assembleRelease``` but it crashes on every run.

It seems that the JSBundle is packaged correctly by the metro on debug but on release it cannot load the required resources correctly. In an effort to find out the cause, i commented out the function from MainApplication.java

```
@Override
protected String getJSBundleFile() {
  return CodePush.getJSBundleFile();
}
```
This stopped the app crashes on both debug and release mode which leads me to think that the cause might be the react-native-code-push library. The output of ```adb logcat``` shows Codepush activity during app initialisation.

### Is this a bug?
Potentially.

### Steps to Reproduce
1. Install react-native-code-push@5.6.0
2. link the library
3. reat-native run-android

### Expected Behavior
Build the app without any issues during inital Codepush-update.

### Actual Behavior
A few second after the app starts the screen momentarily flashes (perhaps. CodePush trying to access JSBundle) and the app crashes.

![app_crash](https://user-images.githubusercontent.com/20586602/60837268-aa547d00-a1bf-11e9-9018-16caf6916e32.png)

![logcat_3](https://user-images.githubusercontent.com/20586602/60837279-b3dde500-a1bf-11e9-81e3-f1fa3523f753.png)

![logcat_2](https://user-images.githubusercontent.com/20586602/60837304-c0623d80-a1bf-11e9-956f-dcf78c82eee1.png)

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.8
* Ubuntu: 18.4.2 LTS
* gradle plugin: 3.3.2
* gradle version: 4.10.1

Currently, i have removed code-push from my project and both debug and release builds are fine.

**Comment by softCompound** [comment]
This is probably not a bug because on a clean project with react-native@0.59.8 and react-native-code-push@5.6.0,  i was not able to reproduce the same error.

**Comment by alexandergoncharov** [comment]
Hi @softCompound,
Thanks for reporting!

Yeah, I can't reproduce it on a clear project too. Could you please provide some dummy project with reproducing issue and reprosteps? I would like to debug it.

**Comment by alexandergoncharov** [comment]
Looks like related to https://github.com/microsoft/react-native-code-push/issues/1272

**Comment by Frekansapp** [comment]
i have same problem too RN version 0.59.10 after install codepush update app crash on some devices with release build.
I'm also using react-native-navigation v2

**Comment by qingjiaowochengzd** [comment]
"react-native": "0.55.4",
"react-native-code-push": "^5.6.0",

push new bundle then update dev app, get this error

facebook::react::Recoverable: Could not open file/data/user/0/com.***/files/ReactNativeDevBundle.js: No such file or directory

**Comment by alexandergoncharov** [comment]
Hi @softCompound ,

I'm going to close this issue ofr now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions or provide more info.
