### ISSUE TITLE
Update sends user to home page, and URL (hash) is lost

### ISSUE THREAD

**Issue by ryanmtaylor** [microsoft/react-native-code-push#1621]
I believe this is a Feature Request.

### Steps to Reproduce
1. Using vue, vue-router and "hash mode" (the full URL is stored in the hash, it's a single-page app and it doesn't use the HTML5 History API)

### Expected Behavior
When a codePush update is sent it simply should refresh the current page.

### Actual Behavior
When a codePush update is sent/installed it moves the user back to the home page.

### Environment

code-push@2.0.6
cordova-plugin-code-push@1.11.19

**Comment by andreidubov** [comment]
Hi @ryanmtaylor,
Thank you for reporting!

As I can see, you are using cordova-plugin-code-push but this does not apply to react-native-code-push. If you still have this problem, please, open issue in the appropriate repository, here is the link: https://github.com/Microsoft/cordova-plugin-code-push
