### ISSUE TITLE
Is it possible to publish a node module in NPM that uses Code Push?

### ISSUE THREAD

**Issue by frags51** [microsoft/react-native-code-push#1624]
Is it possible to publish a node module in NPM that uses Code Push? If so, what would be the steps required to do so (i.e. publishing and using this node module within some other application)

 

Details:
We have an Application comprising of component A (as a parent component) , and component B (child component embedded within Component A). Component B is also published as a NPM package (as it is some UI component for e.g.).  
While creating Component B, We have added Code Push in it to push updates to it and have published it using npm publish.
Then, in Component A, We installed Component B using npm install.
Now:
1.    If Component A also uses Code Push (different deployment key than Component B), can I still publish my separate Code Push updates to Component B (which is now a node module)?
2.    If Component A does not use Code Push, is it possible to do the same?

**Comment by frags51** [comment]
Also, is it possible to do so if we have multiple ReactInstanceManagers in a single app. with each loading their own js bundle file?

**Comment by alexandergoncharov** [comment]
Hi @frags51 ,
Thanks for reporting and interesting question!

I'm not sure about this approach since originally CodePush work with mobile app, not node modules.
Could you please provide more details about this approach: Am I understand correctly that you would like to get update for your users that use your npm package in their apps?

**Comment by alexandergoncharov** [comment]
Hi @frags51 ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
