### ISSUE TITLE
RN 0.60.4 warning about deprecated "rnpm" config with Code Push 5.6.1

### ISSUE THREAD

**Issue by AdemKerenci** [microsoft/react-native-code-push#1633]
React Native gives the following warning when installing the last version of code-push:

```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-code-push: https://microsoft.github.io/code-push
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

```

* react-native-code-push version: 5.6.1
* react-native version: 0.60.4

**Comment by jishuke** [comment]
Yes, I am the same.How can I solve this problem?

**Comment by forsen** [comment]
This issue will be solved when #1645 is merged, in the mean time, just keep calm. It's a warning, not an error.

**Comment by sagarhudge** [comment]
@forsen same warning I am getting any update on this ?please update

**Comment by alexandergoncharov** [comment]
Hi all,

We opened PR for updating docs with setup CodePush for react-native@0.60 and above. If fix this warning.
For more info please check here: https://github.com/microsoft/react-native-code-push/issues/1625#issuecomment-560489061

I'm going to close this issue as duplicate. Please feel free to ask any questions.

Thanks,
Alexander
