### ISSUE TITLE
Add support for autolinking in RN 0.60.x

### ISSUE THREAD

**Issue by kennym** [microsoft/react-native-code-push#1634]
### Steps to Reproduce
1. Create a RN 0.60.x app
2. Add `react-native-code-push` as a dep
3. Run `react-native run-android`

### Expected Behavior
To work seamlessly

### Actual Behavior
Error:  
```- react-native-code-push (to unlink run: "react-native unlink react-native-code-push")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

### Environment

* react-native-code-push version: 5.6.1
* react-native version: 0.60.4
* iOS/Android/Windows version: 12.2
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

**Comment by kennym** [comment]
Anything?

**Comment by nicolasdanelon** [comment]
it's solve #1645 also #1640 #1626

**Comment by alexandergoncharov** [comment]
Hi all,

We opened PR for updating docs with setup CodePush for react-native@0.60 and above. If fix this warning.
For more info please check here: https://github.com/microsoft/react-native-code-push/issues/1625#issuecomment-560489061

I'm going to close this issue as duplicate. Please feel free to ask any questions.

Thanks,
Alexander
