### ISSUE TITLE
Dealing with different app environments. 

### ISSUE THREAD

**Issue by jake41** [microsoft/react-native-code-push#1635]
How do I specify a xcode scheme or an android build variant  during react-native bundle phase for code-push deployment? 

**In ios:**

I have StagingRelease build configuration which is duplicated from release build configuration and contains staging related settings. 

Similary I have ProductionRelease build configuration which contains production related settings.
<img width="646" alt="Screenshot 2019-07-21 at 10 19 51 PM" src="https://user-images.githubusercontent.com/48177034/61594259-5efe8d80-ac07-11e9-86ea-30457ad9930f.png">

Each of this build configuration is connected to a ios scheme. And I want to do a codepush build based on a particular IOS scheme. Can someone explain this ?

**In Android:** 

```
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        stagingrelease {
            initWith release
            // applicationIdSuffix ".staging"
            matchingFallbacks = ['debug']
        }
        productionrelease {
            initWith release
            // applicationIdSuffix ".production"
            matchingFallbacks = ['release']
        }
    }
```

I have the above for android. How to pick , lets say productionrelease  for codepush bundling ? 

How do I specify which xcode scheme to use for codepush bundling? Can someone explain what how Staging and Production env in codepush gets connected to debug/release in IOS or Android ?

**Comment by andreidubov** [comment]
Hi @jake41,
Thank you for reporting!

All you need is in the documentation for multi-deployment-testing, here is the current link: https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-ios.md

Please let me know if you have problems with any step. I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
