### ISSUE TITLE
Including arbitrary binary assets in a bundle?

### ISSUE THREAD

**Issue by ehynds** [microsoft/react-native-code-push#1638]
I'm trying to use CodePush to keep PDF assets updated in my application. I'm using [react-native-pdf](https://www.npmjs.com/package/react-native-pdf) to view them, which uses [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob) to perform the actual disk I/O of the PDF assets.

I ran a test by including a new PDF file in my project & imported it via the following syntax:

```js
<PdfView source={require('../assets/test.pdf')} />
```
`react-native-pdf` wasn't able to render the PDF, which leaves me wondering if the file even made it into the new bundle.

Is this a use case CodePush is able to handle? If so, how do I instruct CodePush to include my PDF assets in the bundle?

**Comment by raldred** [comment]
Did you ever find out if this was possible @ehynds ?

**Comment by ehynds** [comment]
@raldred I did not, unfortunately.

**Comment by andreidubov** [comment]
Hi @ehynds,
Thank you for reporting!

Code Push allows you to create bundle update for various assets, could you describe in more detail all steps for reproducing your problem and the exact versions of all the modules that you use.

I'm going to close this issue for now. Please let me know if you have any other questions.
