### ISSUE TITLE
RN 0.60 auto link

### ISSUE THREAD

**Issue by duringg** [microsoft/react-native-code-push#1639]
"react-native": "0.60.3",
    "react-native-code-push": "^5.6.1",

yarn install react-native-code-push
then
react-native link react-native-code-push

Android  miss String reactNativeCodePush_androidDeploymentKey
I fix Android bug myself.
iOS 'CodePush/CodePush.h' file not found.
I don't know how to fix it.

**Comment by karltaylor** [comment]
try 
```
yarn install react-native-code-push@latest
# then
react-native link react-native-code-push
# clean build
# build project
```

**Comment by jeremy-deutsch** [comment]
How did you fix the missing `reactNativeCodePush_androidDeploymentKey`?

**Comment by duringg** [comment]
> How did you fix the missing `reactNativeCodePush_androidDeploymentKey`?

![image](https://user-images.githubusercontent.com/12458476/61843965-57bdd500-aed0-11e9-8cce-c5e7ff17c9dc.png)

add the String in your Android String file

**Comment by duringg** [comment]
> try
> 
> ```
> yarn install react-native-code-push@latest
> # then
> react-native link react-native-code-push
> # clean build
> # build project
> ```

it doesn't work ,still 'CodePush/CodePush.h' file not found

**Comment by mzupek** [comment]
> yarn install react-native-code-push@latest

yarn **add** react-native-code-push

**Comment by codyhazelwood** [comment]
I had to run:
```
npm i react-native-code-push@latest
react-native link react-native-code-push
cd ios
pod install
```

**Comment by duringg** [comment]
> I had to run:
> 
> ```
> npm i react-native-code-push@latest
> react-native link react-native-code-push
> cd ios
> pod install
> ```

it work!!!
> cd ios
> pod install
it should do myself.
