### ISSUE TITLE
Randomly getting HTTP 403 error on updateCheck

### ISSUE THREAD

**Issue by mieszko4** [microsoft/react-native-code-push#1641]
I randomly experience issue `403 Forbidden` on my production mobile app when it checks for updates.

I narrowed down this issue to conclude that the problem is with the server.

### Steps to Reproduce
**Replace `DEPLOYMENT_KEY` for real key and run it multiple times in a short time, possibly in parallel:**
```sh
curl -v 'https://codepush.azurewebsites.net/updateCheck?deploymentKey=DEPLOYMENT_KEY&appVersion=18&packagep-alive' -H 'Cache-Control: max-age=0' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: pl,hr;q=0.9,en-US;q=0.8,en;q=0.7,sr;q=0.6,sv;q=0.5,zh-TW;q=0.4,zh;q=0.3,zh-CN;q=0.2,ko;q=0.1' -H 'Cookie: ARRAffinity=b727f0ff82c4495d9c0aebd16262ea91a179e978603b8c1c65c70e7ff65ea9a5' --compressed
```
* It is a `Copy as cURL` from developer tools after running https://codepush.azurewebsites.net/updateCheck?deploymentKey=DEPLOYMENT_KEY&appVersion=18&packagep-alive
* I took this url from my mobile app logs

### Expected Behavior

The result most of the time is valid, i.e
```sh
[...]
< HTTP/1.1 200 OK
[...]
{"updateInfo":[...]}
```
### Actual Behavior
However once in a while the respond results with `403`:

#### Detailed wrong response
```sh
*   Trying 23.101.203.117...
* TCP_NODELAY set
* Connected to codepush.azurewebsites.net (23.101.203.117) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; CN=*.azurewebsites.net
*  start date: May 10 00:00:00 2019 GMT
*  expire date: May 10 12:00:00 2021 GMT
*  subjectAltName: host "codepush.azurewebsites.net" matched cert's "*.azurewebsites.net"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /updateCheck?deploymentKey=DEPLOYMENT_KEY&appVersion=18&packageHash=&isCompanion=&label=&clientUniqueId=c3735f51fe56efd6 HTTP/1.1
> Host: codepush.azurewebsites.net
> Connection: keep-alive
> Cache-Control: max-age=0
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
> Accept-Encoding: gzip, deflate, br
> Accept-Language: pl,hr;q=0.9,en-US;q=0.8,en;q=0.7,sr;q=0.6,sv;q=0.5,zh-TW;q=0.4,zh;q=0.3,zh-CN;q=0.2,ko;q=0.1
> Cookie: ARRAffinity=b727f0ff82c4495d9c0aebd16262ea91a179e978603b8c1c65c70e7ff65ea9a5
> 
< HTTP/1.1 403 Forbidden
< Server: Microsoft-IIS/10.0
< X-Powered-By: ASP.NET
< Date: Wed, 24 Jul 2019 16:14:47 GMT
< Content-Length: 0
< 
* Connection #0 to host codepush.azurewebsites.net left intact
```

Perhaps it is the server is throttling requests. If it does shouldn't that be `429` then?

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.10
* iOS/Android/Windows version: both iOS and Android
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? physical

**Comment by mtford90** [comment]
Also dealing with this. Caused an app store rejection today.

**Comment by esbenvb** [comment]
I have an iOS and an Android app with CodePush, every time I deploy a new iOS update, it rolls back after relaunch. However, when loading the app status on appcenter.ms, it shows as 0 rollbacks, although I just witnessed two iOS devices roll back to the built in version.

Tried starting the app in acode (removing the `if DEBUG` clause) - this gives me errors like this:

```
2019-07-30 13:59:29.100 [info][tid:com.facebook.react.JavaScript] [CodePush] Checking for update.
2019-07-30 13:59:29.099714+0200 LoudstandApp[441:3657435] [CodePush] Checking for update.
2019-07-30 13:59:29.808 [info][tid:com.facebook.react.JavaScript] [CodePush] An unknown error occurred.
2019-07-30 13:59:29.808550+0200 LoudstandApp[441:3657435] [CodePush] An unknown error occurred.
2019-07-30 13:59:29.809 [info][tid:com.facebook.react.JavaScript] [CodePush] 403: 
2019-07-30 13:59:29.808784+0200 LoudstandApp[441:3657435] [CodePush] 403:
2019-07-30 13:59:31.812 [warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 0):
Error: 403: 

```

**Comment by dkpalmer** [comment]
We also started seeing 403s start recently (surfaced by Sentry).

**Comment by turbohappy** [comment]
I've been getting this in my Sentry logs recently as well.

**Comment by esbenvb** [comment]
@dkpalmer @turbohappy does your iOS app also roll back to initial bundle, after restarting it, even though the updated bundle ran fine?

**Comment by mayconmesquita** [comment]
i'm getting random 403 errors at production.

**Comment by ohjeyong** [comment]
Same here.

In `codePush.sync`, `codePush.SyncStatus.CHECKING_FOR_UPDATE` is fired first inside of syncStatusChangedCallback. After that, randomly `codePush.SyncStatus.UNKNOWN_ERROR` is fired. I dived into sentry(error tracking tool), and it said there were 403 error.
Below is error stack.
```
Error: 403: 
  at callback(node_modules/code-push/script/acquisition-sdk.js:49:30)
  at call(node_modules/react-native-code-push/request-fetch-adapter.js:31:7)
  at tryCatch(node_modules/regenerator-runtime/runtime.js:45:40)
  at call(node_modules/regenerator-runtime/runtime.js:271:22)
  at tryCatch(node_modules/regenerator-runtime/runtime.js:45:40)
  at invoke(node_modules/regenerator-runtime/runtime.js:135:20)
  at fn(node_modules/regenerator-runtime/runtime.js:145:13)
  at tryCallOne(node_modules/promise/setimmediate/core.js:37:12)
  at callback(node_modules/promise/setimmediate/core.js:123:15)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:7)
  at _callImmediatesPass(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:7)
  at callImmediates(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:12)
  at [native code] callImmediates(:0:0)
  at __callImmediates(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:366:12)
  at fn(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:12)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:343:9)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:10)
  at [native code] value(:0:0)
  at [native code] value(:0:0)
```

**Comment by ekrapfl** [comment]
I would just like to put in that I am investigating using CodePush for my company for an Ionic/Cordova app, and I am seeing the same issues pop up fairly frequently (really slow update checks, and frequent 403 errors).  The service is pretty awesome, but it is a non starter if we have this sort of performance and reliability issues.

**Comment by dkpalmer** [comment]
> does your iOS app also roll back to initial bundle, after restarting it, even though the updated bundle ran fine?

@esbenvb This is happening even without deploying any new bundles. I'm not sure about whether it would roll back if we were on a newer bundle.

**Comment by alexandergoncharov** [comment]
Hi all,
Thanks for reporting!

Looks like this is issue occured becasue we were updating CodePush server side. We are sorry for that. :disappointed:
It works correctly now.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or if you faced this issue again.

**Comment by clementinoux** [comment]
Hi @alexandergoncharov !

I just set up the module in my app and I'm facing the same 403 error. 
Anyone else? Is there another CodePush server side update right now ?

Thanks for your help !

**Comment by haorh** [comment]
I'm using
- react-native-code-push version: 5.6.0
- react-native version: 0.59.9

I gotten the update from appcenter but bugsnag reported this issue at production. I see your september 2019 roadplan involved upgrade server and we must upgrade the version to use it. Can anyone confirm newer version of code push resolved this problem?
