### ISSUE TITLE
React native warning about deprecated "rnpm" config

### ISSUE THREAD

**Issue by LusineGasparyan** [microsoft/react-native-code-push#1642]
React Native gives the following warning when installing the last version of push-notification:
```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-push-notification: https://npmjs.com/package/react-native-push-notification
```

* react-native-push-notification version:
* react-native version:

**Comment by joseph-d-p** [comment]
The package emitting the warning is `react-native-push-notification`. 

See: https://github.com/thecodrr/react-native-push-notification/pull/5
```
"react-native-push-notification": "^3.1.9",
```

P.S. I've added https://github.com/microsoft/react-native-code-push/pull/1678 to resolve warning for `react-native-code-push`

**Comment by alexandergoncharov** [comment]
Hi all,

We opened PR for updating docs with setup CodePush for react-native@0.60 and above. If fix this warning.
For more info please check here: https://github.com/microsoft/react-native-code-push/issues/1625#issuecomment-560489061

I'm going to close this issue as duplicate. Please feel free to ask any questions.

Thanks,
Alexander
