### ISSUE TITLE
The following packages use deprecated “rnpm” config that will stop working from next release.

### ISSUE THREAD

**Issue by komal1212** [microsoft/react-native-code-push#1643]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
i want to close this warning when i run project it gives this warning everytime.

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
![error](https://user-images.githubusercontent.com/52229170/61990310-a64baa80-b05b-11e9-8bd1-606e1eca5e0a.PNG)

### Reproducible Demo

* 

### Environment

* react-native-code-push version:
* react-native version:
 "@react-native-community/slider": "^2.0.0",
    "geolib": "^3.0.4",
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-easy-toast": "^1.2.0",
    "react-native-geolocation-service": "^3.0.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-google-places": "^3.1.1",
    "react-native-maps": "0.25.0",
    "react-native-responsive-screen": "^1.2.2",
    "react-native-sqlite-storage": "^3.3.11",
    "react-native-system-setting": "^1.7.2",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.1"

* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, 
(The more info the faster we will be able to address it!)

**Comment by karltaylor** [comment]
There is a duplicate literally right below this issue. C'mon... #1642

**Comment by joseph-d-p** [comment]
The packages emitting the warnings are `react-native-maps` and `react-native-sqlite-storage`. 

Probably you just need to update your package version. For it seems both packages already has `react-native.config.js` in their repo.

See: https://github.com/react-native-community/react-native-maps/pull/2975
See: https://github.com/andpor/react-native-sqlite-storage/pull/361

P.S. I've added https://github.com/microsoft/react-native-code-push/pull/1678 to resolve warning for `react-native-code-push`

**Comment by alexandergoncharov** [comment]
Hi all,

We opened PR for updating docs with setup CodePush for react-native@0.60 and above. If fix this warning.
For more info please check here: https://github.com/microsoft/react-native-code-push/issues/1625#issuecomment-560489061

I'm going to close this issue as duplicate. Please feel free to ask any questions.

Thanks,
Alexander
