### ISSUE TITLE
Trying to push JS bundle Only - Unknown argument --update-contents-path

### ISSUE THREAD

**Issue by trdisc** [microsoft/react-native-code-push#1648]
### Steps to Reproduce
1. Trying to send just the JS bundle without graphics :  [-с|--update-contents-path <updateContentsPath>] 
2. 
```
appcenter codepush release -a <ownerName>/<appName> -c <updateContentsPath>
```
3. results in: "Unknown argument -c" .  or "Unknown argument --update-contents-path" (in case I try --update-contents-path )

### Expected Behavior
Able to push just the bundle without graphics. This will make the push much smaller if needed.

### Actual Behavior
What actually happens?
```
  "Unknown argument -c" .  or "Unknown argument --update-contents-path" (in case I try --update-contents-path )
```

**Comment by trdisc** [comment]
Do we know if "-с" OR "--update-contents-path" command does not work in current "appcenter codepush" version ?
I'm getting error trying to use it.
Thanks.

**Comment by trdisc** [comment]
Hi, Following up on "-с" OR "--update-contents-path" command. Anyone was able to use this feature? I'm trying to push only the JS bundle without graphics.

**Comment by alexandergoncharov** [comment]
Hi @trdisc 
Thanks for reporting!

It is strange issue. All works correctly for me. Could you pelase provide your `node` and `appcenter-cli` versions?
