### ISSUE TITLE
App installs codepush release immediately

### ISSUE THREAD

**Issue by codesinghanoop** [microsoft/react-native-code-push#1649]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Do a codepush release to a targetBinary say 4.9.9 as non-mandatory
2. Now when the signed app is opened first time after downloading from play store the codepush release is applied immediately. 

###NOTE :- There is no previous mandatory release of the targetbinary 4.9.9  

### Expected Behavior
What you expected to happen?
User should see the update once is return next time to the app. The codepush sync config i'm using is :- `checkFrequency: CodePush.InstallMode.ON_APP_RESUME,
        installMode: CodePush.InstallMode.ON_NEXT_SUSPEND`

### Actual Behavior
What actually happens?
App receives the codepush release immediately even though the config to sync is different than that of immediate sync. 

```
[CodePush] Loading JS bundle from "assets://index.android.bundle"
[CodePush] Checking for update.
[CodePush] Reporting binary update (4.9.9)
[CodePush] Downloading package.
[CodePush] Applying full update.
[CodePush] Installing update.
[CodePush] Loading JS bundle from "/data/user/0/[packageName]/files/CodePush/4687235380327511326e4de25b26ad3c8164ed0865f2914708fa61081b792c4a/CodePush/index.android.bundle"
[CodePush] Restarting app
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 5.6.1
* react-native version: 0.60.0
* iOS/Android/Windows version: All devices
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

Any help would be appreciated. Stuck here for a while. Please help me.

**Comment by codesinghanoop** [comment]
@geof90 @lostintangent waiting for the reply.

**Comment by ewendel** [comment]
We're experiencing the same behaviour as well. We are about to start using CodePush in our app, but will delay until this issue has been resolved.

**Comment by codesinghanoop** [comment]
@ewendel Did you find any work around?

**Comment by MugeshM** [comment]
+1 ios app restarts automatically when update is available even without sync or checkupdate method. Android works as expected.

**Comment by codesinghanoop** [comment]
@MugeshM What i found as a workaround this is change the major version of build number for android you can try the same for iOS

**Comment by andreidubov** [comment]
Hi @codesinghanoop,
Thank you for reporting!

As I can see, you are using react-native v0.60.0 and react-native-code-push v5.6.1 but these are incompatible versions, you can take a look at supporting CodePush versions here: https://github.com/microsoft/react-native-code-push#supported-react-native-platforms

Not so long ago we released a new version of Code Push which supports react-native v0.60-v0.61.
All steps for installing the latest version of the plugin are described in our documentation.
iOS: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md
Android: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.
