### ISSUE TITLE
How long is ”the next few months”?

### ISSUE THREAD

**Issue by davidpaulsson** [microsoft/react-native-code-push#1650]
I'm just wondering how long ”the next few months” is? You mention this right at the top of the repo readme. 

> UPDATE: Over the next few months, we will be working on a new version of CodePush that will address some of the most common performance issues our customers are facing. This updated version will allow a better experience, our team to better support CodePush moving forward and have a faster development cycle for new features. We are prioritizing this work because we believe this to be the most valuable thing we can do for our CodePush customers in the long run. Starting June 11th 2019, support will slow down, bug fixes will be limited to critical bugs, and new feature development will pause until we finish this core update.

This was added two months ago. I want to add code push to my app, but it feels silly with this paragraph at the top. 

Thank you for all your hard work!

**Comment by andreidubov** [comment]
Hey @davidpaulsson,
Sorry for the delay.

As you know, we were working on updating the core of our service, unfortunately it took longer than we expected. Now we're back to support, but still continue to do some work to improve.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.
