### ISSUE TITLE
How can I set server url with react-native-navigation v2

### ISSUE THREAD

**Issue by dreamhb** [microsoft/react-native-code-push#1651]
Hi there,

I've integrated CodePush and react-native-navigation V2 into my existing android project.  But now I need to get server url from my own server and set it, but CodePush is initialized in Application.oncreate(), there is no time to retrieve url from server :-(

How can I fix this issue?

Thanks a lot!

**Comment by andreidubov** [comment]
Hi @dreamhb,
Thank you for reporting!

As I understand it, you want to specify the CodePush Server URL.  You can find all the necessary information for the current version of react-native-code-push in the documentation at this link: https://github.com/microsoft/react-native-code-push/blob/master/docs/api-android.md#api-for-react-native-060-version-and-above

You should override it by adding your path to strings.xml with name CodePushServerUrl like this: <string moduleConfig="true" name="CodePushServerUrl">https://yourcodepush.server.com</string>

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
