### ISSUE TITLE
An unknown error occurred，[CodePush] 404

### ISSUE THREAD

**Issue by xiaomei991** [microsoft/react-native-code-push#1653]
![image](https://user-images.githubusercontent.com/20355401/62845724-0483b900-bcfd-11e9-85ad-8eef319b0104.png)

I don't know how to solve this problem，my deploy records is：
![image](https://user-images.githubusercontent.com/20355401/62845732-0f3e4e00-bcfd-11e9-9312-08dcd5cb809f.png)

Can you give me some advice？

**Comment by jstheoriginal** [comment]
You should remove your deployment keys from this post.

**Comment by youngjuning** [comment]
你是如何解决这个问题的？@xiaomei991

**Comment by dimlksin2** [comment]
How did you solve this problem?

**Comment by rmamtaventures** [comment]
same issue.

**Comment by shenl923** [comment]
“You should remove your deployment keys from this post.？” ， What does that mean？

**Comment by TaekwanMin** [comment]
it means you should not exposure your deployment keys to anyone who see this post.... for your security...
