### ISSUE TITLE
How can I set the mServerUrl in React-Native 0.60.4

### ISSUE THREAD

**Issue by pig3800** [microsoft/react-native-code-push#1654]
Try to Use MySelf server, The React Native Version is 0.60.4
How can i fix this issues?

**Comment by zkkg2018** [comment]
帅哥 你解决这个问题了吗？我是  我用的 0.60.5  使用 react-native-server 一直报错404

**Comment by pig3800** [comment]
in react-native-code-push/package.json,
change  
`    "android": {
      "packageInstance": "new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG,'your url')"
    },`

**Comment by darkfiredarkhalo** [comment]
或者还按以前的手动配置,只不过要在项目根目录下添加`react-native.config.js`文件,内容如下:  
```
module.exports = {
	dependencies: {
		'react-native-code-push': {
			platforms: {
				android: null, // 取消code-push Android的自动link,其他平台依旧
			},
		},
	},
};  
```

**Comment by marlti7** [comment]
@pig3800 
我试了你的方法还是不行啊   编译之后的packageList里 packageInstance 并没有按照改的变化
