### ISSUE TITLE
CodePush is not initialized on Android causing app crashes.

### ISSUE THREAD

**Issue by ricbermo** [microsoft/react-native-code-push#1655]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Install the library.
2. run the android project.

### Expected Behavior
The app should not crash.

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/2601363/62889088-3d745b80-bd06-11e9-87cc-ae224caf4a33.png)

### Reproducible Demo
https://github.com/ricbermo/open-source-contrib

### Environment

* react-native-code-push version: 5.6.1
* react-native version: 60.0
* iOS/Android/Windows version: Android 8
* Does this reproduce on a debug build or release build?: debug
* Does this reproduce on a simulator, or only on a physical device?: Both

**Comment by alexandergoncharov** [comment]
Hi @ricbermo  ,
Thanks for reporting!

Could you please upgrade your `react-native-code-push` version to the latest and follow this docs for setup:  https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
