### ISSUE TITLE
Works with Static Libiraries

### ISSUE THREAD

**Issue by jinguohao1991** [microsoft/react-native-code-push#1659]
### Steps to Reproduce
1. In my React Native app, I am using FBSDK which works only in Documents directory.
2. Building from local is working because FBSDK was located in $(HOME)/Documents.
3. But when using Code Push, there was an error related to FBSDK which says 'can't find FBSDK'
4. I think I need to copy FBSDK to Document/FBSDK so that make project to be same as my local environment.

### Expected Behavior
How to place FBSDK to the appropriate place, ideally in 'Document' directory.

### Actual Behavior
Cannot build project because couldn't find FBSDK.

* react-native-code-push version: 5.6.0
* react-native version: 0.59.8
* Does this reproduce on a debug build or release build? A: Release build
* Does this reproduce on a simulator, or only on a physical device? Answer: on pushing by Code push on Code push dashboard()
![image](https://user-images.githubusercontent.com/31640360/63291773-d141bb00-c2f6-11e9-88d4-3fad6ef912e0.png)
![image](https://user-images.githubusercontent.com/31640360/63291848-f33b3d80-c2f6-11e9-8385-f2cc5a4d06b6.png)

**Comment by alexandergoncharov** [comment]
Hi @jinguohao1991 ,
Thanks for reporting!

CodePush can update just JS bundle of the app and don't use the native part.
release command uses `react-native bundle` command. Could you please ensure that this command works for you?
Also, could you please provide command that you use for releasing updates?

**Comment by alexandergoncharov** [comment]
Hi @jinguohao1991 ,

I'm going to close this issue for now as we haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
