### ISSUE TITLE
Missing typescript definition for CodePush.getConfiguration()

### ISSUE THREAD

**Issue by spyr0s** [microsoft/react-native-code-push#1661]
### Steps to Reproduce
1. import CodePush from 'react-native-code-push';
2.  CodePush.getConfiguration().then((config)=>{....});

### Expected Behavior
No typescript error

### Actual Behavior
Typescript error "Property 'getConfiguration' does not exist on type 'typeof CodePush'.ts(2339)"

### Environment

* react-native-code-push version:5.3.4
* react-native version:0.59.10
* iOS/Android/Windows version: All
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by andreidubov** [comment]
Hi @spyr0s,
Thank you for reporting!

The getConfiguration () function is private and is used only inside the react-native-code-push module. You should not call it from your code. You can see all available API Reference here: https://github.com/microsoft/react-native-code-push/blob/master/docs/api-js.md#javascript-api-reference

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Comment by peterkuiper** [comment]
@andreidubov I know this is an old issue but I am curious as to why this function is private. Is there another way to check which deploymentKey is currently being used? I am implementing [Dynamic Deployment Assignment](https://github.com/microsoft/react-native-code-push#dynamic-deployment-assignment) and I want to verify that the app is on the correct deployment.
