### ISSUE TITLE
What CAN'T I update through codepush?

### ISSUE THREAD

**Issue by Zabi-Progton** [microsoft/react-native-code-push#1662]
If I am making changes inside the build.gradle files and gradle.properties file in android and then pushing it, will this cause any problems? What is the alternative to this?

**Comment by WeslleyNasRocha** [comment]
This files, change the way the app is compiled, codepush don't recompile your app, it basically change the javascript, like the reload when your developing in debug mode. An alternative to this its, recompile your app, launch an update via store (Play Store/App Store).

**Comment by alexandergoncharov** [comment]
Hi @Zabi-Progton,
Thanks for reporting!

Yeah, @WeslleyNasRocha is right. Thanks!

But it depends on your changes. Could you please provide some example of your changes?

I'm going to cose this issue for now. Please feel free to reopen it when you provide some change example or if you have any questions.
