### ISSUE TITLE
About when should react native 0.60

### ISSUE THREAD

**Issue by zkkg2018** [microsoft/react-native-code-push#1663]

**Comment by Adrxx** [comment]
I think you are able to make it run on RN 0.60 right now by following the instructions on some other threads. Am I right?

**Comment by alexandergoncharov** [comment]
Hi all,

We opened PR for updating docs with setup CodePush for react-native@0.60 and above. If fix this warning.
For more info please check here: https://github.com/microsoft/react-native-code-push/issues/1625#issuecomment-560489061

I'm going to close this issue as duplicate. Please feel free to ask any questions.

Thanks,
Alexander
