### ISSUE TITLE
Can't download bundle on new devices - Getting 503

### ISSUE THREAD

**Issue by yaronlevi** [microsoft/react-native-code-push#1664]
Hi,

We have a problem with code push in production.
Today our production app stopped fetching the updated code push bundle on new installs. 

Meaning, when a new app is installed on a device, and the code push library tries to get the current JS bundle it fails with:
```
08-22 18:56:01.428 31287 31333 I ReactNativeJS: [CodePush] Reporting binary update (1.0.50)
08-22 18:56:02.708 31287 31333 I ReactNativeJS: [CodePush] 503: 
08-22 18:58:08.591 31287 31333 I ReactNativeJS: [CodePush] Report status failed: {"appVersion":"1.0.50"}
```
We have'nt touched any code in production or pushed/rollbacked anything.

Any help or a direction for investigation would be much appreciated. We are currently hurting all users in production.

**Comment by JakeRawr** [comment]
I'm seeing the same thing for both Staging and Production on iOS and Android

This is an urgent issue. Also would be helpful to have a code push status webpage

**Comment by yaronlevi** [comment]
Adding to what JakeRawr said, a status webpage and an SLA is crucial for us.
Right now we are bleeding in production and there nothing we can do about it.
If we use code push under one of  AppCenter's paid plan, can we get better downtime?

**Comment by koyin** [comment]
Actually there is a status page
https://status.appcenter.ms/

**Comment by Joaojuby** [comment]
Having the same problem, new iOS installs can't fetch the bundle, and since our codepush flow is totally managed now our users can't even go past our loading screen (some lessons learned here)

**Comment by danielvportlandia** [comment]
> Having the same problem, new iOS installs can't fetch the bundle, and since our codepush flow is totally managed now our users can't even go past our loading screen (some lessons learned here)

Same here as we make our updates mandatory.

**Comment by cjonsmith** [comment]
Hey all, I addressed this issue in [a comment](https://github.com/microsoft/appcenter/issues/814#issuecomment-526411546) on a similar issue on the main App Center issue tracker that goes over some of our findings around the issue. Feel free to continue the discussion if you have any further questions or concerns about the outage. Thank you for your patience while we addressed this issue!
