### ISSUE TITLE
    java.lang.IllegalStateException: Native module CodePush tried to override CodePushNativeModule. Check the getPackages() method in MainApplication.java, it might be that module is being created twice. If this was your intention, set canOverrideExistingModule=true

### ISSUE THREAD

**Issue by trinadhkoya9** [microsoft/react-native-code-push#1666]
Not able to launch the app on on both modes (release and debug).It is giving me the error. I did not find any duplicates  to check .

**Comment by pfulop** [comment]
Either create or add this to your react-native.config.js
```
module.exports = {
  dependencies: {
    "react-native-code-push": {
      platforms: {
        android: null
      }
    }
  }
};
```

**Comment by fanzhiri** [comment]
> Either create or add this to your react-native.config.js
> 
> ```
> module.exports = {
>   dependencies: {
>     "react-native-code-push": {
>       platforms: {
>         android: null
>       }
>     }
>   }
> };
> ```

not work

**Comment by fadak0828** [comment]
> Either create or add this to your react-native.config.js
> 
> ```
> module.exports = {
>   dependencies: {
>     "react-native-code-push": {
>       platforms: {
>         android: null
>       }
>     }
>   }
> };
> ```

Worked for me
Thanks :)

**Comment by FaiChou** [comment]
Put `react-native.config.js` to `/node_modules/react-native-code-push/`, am I right ?

@pfulop 
@fadak0828

**Comment by rockneverdies55** [comment]
What does this snippet do? A link to documentation etc would be helpful. Will codepush continue to work when this gets added?

**Comment by theslyone** [comment]
@rockneverdies55 This simply disables autolinking native modules for the selected configuration.

Ref: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

**Comment by alexandergoncharov** [comment]
Hi @trinadhkoya9 ,
Thanks for reporting!

Could you please update your `react-native-code-push` version to the latest and do steps from this docs: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android
This should fix your issue.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
