### ISSUE TITLE
App restarts during dissalowRestart on InstallMode.IMMEDIATE

### ISSUE THREAD

**Issue by viewpnt1** [microsoft/react-native-code-push#1667]
### Steps to Reproduce
1. Configure codePush with Manual checkfrequency and IMMEDIATE sync call
2. call disallowRestart
3. wait for update to queue
4. scan an NFC card from the app
5. app restarts

### Expected Behavior
What you expected to happen?
- app not to restart

### Environment
* Only tested on Android
* react-native-code-push version: 5.6.0
* react-native version: 0.58.6
* Android version: 8.0
* Does this reproduce on a debug build or release build? both

Code:
```
//perform check every 1 min in root App component
setInterval(() => {
            try {
                codePush.sync({
                    installMode: codePush.InstallMode.IMMEDIATE,
                    mandatoryInstallMode: codePush.InstallMode.IMMEDIATE,
                })
            } catch (e) {
                console.log('Exception occured during codePush.sync');
                console.warn(e);
            }
        }, 60*1000);
```
```
// root (App) component wrapping
export default codePush({
    checkFrequency : codePush.CheckFrequency.MANUAL,
})(App);
```
Console log before card scan:
[CodePush] Disallowing restarts
[CodePush] Checking for update.
[CodePush] Downloading package.
[CodePush] Installing update.
[CodePush] Restart request queued until restarts are re-allowed

Console log immediately after card scan:
console.clear() was prevented due to 'Preserve log'
Api.js:88 initialize api 

As you can see, console output doesn't show "[CodePush] Re-allowing restarts" at any point. Also, no output "Executing pending restart" is found. The app just restarts.

Is it possible that NFC scaning (react-native-nfc-manager) is messing with lifecycle or something?

**Comment by achou11** [comment]
I'm experiencing something similar with `InstallMode.ON_NEXT_RESUME`. Context for mine: 

1. Opens an in-app-browser for auth. The `Disallowing restarts` log is present.
2. After successful credentials, redirects to the app but CodePush causes a restart even though `allowRestart` hasn't been called.

I can create a separate issue if necessary since the specs are a little different (e.g. this is on React Native 0.61.3)

**Comment by alexandergoncharov** [comment]
Hi @viewpnt1 , @achou11 ,
Thanks for reporting!

It is known issue and we already have opened issue for this: https://github.com/microsoft/react-native-code-push/issues/788
Let's continue our conversation there.

I'm going to close this issue as duplicated. Please feel free to reopen it if you have any questions.
