### ISSUE TITLE
code-push release error 

### ISSUE THREAD

**Issue by virtoolswebplayer** [Microsoft/react-native-code-push#167]
```bash
code-push release wealth-android  ./release/android/index.android.bundle  1.0.0
```
[Error]  getaddrinfo ENOTFOUND codepush.azurewebsites.net codepush.azurewebsites.net:443

**Comment by lostintangent** [comment]
Is this still occurring for you? That is a DNS error, and we haven't had any service outages. It may have been a temporal issue on your end to resolve the domain. If you could try again and let us know, that would be great.

**Comment by lostintangent** [comment]
I haven't been able to repro this and we haven't had any connectivity problems, so I'm going to close this under the assumption that your DNS server had a temporary issues resolving our server's domain. If you try to release again, do you get the issue reliably every time? If so, please activate this. Thanks!
