### ISSUE TITLE
App Center status: "App Center is experiencing degraded availability with the Code Push Service."

### ISSUE THREAD

**Issue by sunweiyang** [microsoft/react-native-code-push#1671]
On Aug 22, the App Center status page (https://status.appcenter.ms) reported the following:
```
Investigating - App Center is experiencing degraded availability with the Code Push Service. We apologize for the inconvenience while we work to resolve this issue. 
```
Our app's users are adversely impacted by this; bundle checks (not just downloads) are taking anywhere from a few seconds to over 10 minutes.

There has not been an update on the App Center status page regarding possible resolutions as of today (Aug 28). When can the community expect an update?

Thanks so much for what is otherwise a great package!

**Comment by andreidubov** [comment]
Hi @sunweiyang ,
Sorry for the delay.

Looks like this is issue occured becasue we were updating CodePush server side. We are sorry for that. 😞
It works correctly now.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or if you faced this issue again.
