### ISSUE TITLE
切换新的账号

### ISSUE THREAD

**Issue by sky-ZKD** [microsoft/react-native-code-push#1673]
首先我自己注册了一个测试环境，然后跑通整个热更新流程，然后我在自己公司的环境内跑热更新流程，就总是报错，我要怎么把我测试环境的信息提交到我们公司的环境下

**Comment by sky-ZKD** [comment]
以前有命令能把权限转移到另一个账号内，现在没有这命令了，我该怎么办

**Comment by alexandergoncharov** [comment]
Hi @sky-ZKD ,

I'm sorry but I have to close this issue. Could you please reopen this issue on English language?
