### ISSUE TITLE
syncOptions.deploymentKey is null

### ISSUE THREAD

**Issue by fanzhiri** [microsoft/react-native-code-push#1674]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. react-native link react-native-code-push
info Android module "react-native-code-push" is already linked
Running android postlink script
"getJSBundleFile" is already overridden
"codepush.gradle" is already linked in the build definition
reactNativeCodePush_androidDeploymentKey already specified in the strings.xml

2. add my log at node_modules/react-native-code-push/CodePush.js  at line 413
    await CodePush.notifyApplicationReady();
    syncStatusChangeCallback(CodePush.SyncStatus.CHECKING_FOR_UPDATE);
+    **log("codepush before await checkForUpdate deploymentKey:"+syncOptions.deploymentKey);**
    const remotePackage = await checkForUpdate(syncOptions.deploymentKey, handleBinaryVersionMismatchCallback);

3.  codePush.sync(.....

### Expected Behavior
What you expected to happen?
log show that syncOptions.deploymentKey is null

### Actual Behavior
What actually happens?
syncOptions.deploymentKey not null

### Environment

* react-native-code-push version:5.7.0
* react-native version:0.60.5
* iOS/Android/Windows version: android
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by fanzhiri** [comment]
because the readme does not mention how to setup the private serverUrl , so I try to find out where is the problem block working . 
ohh , I forgot the serverUrl
1、android/app/src/main/res/values/strings.xml
+<string moduleConfig="true" name="serverUrl">https://xxx.com</string>
2、node_modules/react-native-code-push/package.json
add BuildConfig.DEBUG,getResources().getString(R.string.serverUrl) to the new CodePush func.
like this below
"rnpm": {
    "android": {
      "packageInstance": "new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG,getResources().getString(R.string.serverUrl))"
    }

**Comment by benyasin** [comment]
cool!

**Comment by benyasin** [comment]
> cool!



> because the readme does not mention how to setup the private serverUrl , so I try to find out where is the problem block working .
> ohh , I forgot the serverUrl
> 1、android/app/src/main/res/values/strings.xml
> add `<string moduleConfig="true" name="serverUrl">https://xxx.com</string>`
> 2、node_modules/react-native-code-push/package.json
> add BuildConfig.DEBUG,getResources().getString(R.string.serverUrl) to the new CodePush func.
> like this below
> "rnpm": {
> "android": {
> "packageInstance": "new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG,getResources().getString(R.string.serverUrl))"
> }

cool!

**Comment by Runtime007** [comment]
or do it like this, set `postinstall` in your project's package.json file.
```
...
 "scripts": {
    "postinstall": "sed -ig 's/new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG)/new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG, "YOUR_SERVER_URL")/g' node_modules/react-native-code-push/package.json",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
...
```

**Comment by Nayan014** [comment]
Getting Error
`sed: 1: "s/new CodePush(getResou ...": bad flag in substitute command: '/'`
