### ISSUE TITLE
 linker command failed with exit code 1

### ISSUE THREAD

**Issue by chrislincp** [microsoft/react-native-code-push#1679]
### Steps to Reproduce
1. yarn add react-native-code-push@5.6.0
2. react-native link react-native-code-push
3. cd ios && pod install
4. open Xcode and build

### Actual Behavior
i have already cleared DerivedData and pod install, but it did not work
```
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.10
* iOS/Android/Windows version: ios
* Does this reproduce on a debug build or release build? debug build

(The more info the faster we will be able to address it!)

**Comment by pilot4u** [comment]
we have the same issue, where the error is:
`In file included from node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:1:
node_modules/react-native-code-push/ios/CodePush/CodePush.h:146:34: warning: this block declaration is not a prototype [-Wstrict-prototypes]
           doneCallback:(void (^)())doneCallback
                                 ^
                                  void
node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:4:2: warning: missing submodule 'React.React.RCTConvert' [-Wincomplete-umbrella]
#import <React/RCTConvert.h>
 ^      ~
node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:11:17: error: declaration of 'RCTConvert' must be imported from module 'React' before it is required
@implementation RCTConvert (CodePushUpdateState)
                ^
In module 'React' imported from node_modules/react-native-code-push/ios/CodePush/CodePush.h:2:
ios/Pods/Headers/Public/React/React/RCTConvert.h:27:12: note: previous declaration is here
@interface RCTConvert : NSObject
           ^
node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:13:42: error: expected ')'
RCT_ENUM_CONVERTER(CodePushUpdateState, (@{ @"codePushUpdateStateRunning": @(CodePushUpdateStateRunning),
                                         ^
node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:13:41: note: to match this '('
RCT_ENUM_CONVERTER(CodePushUpdateState, (@{ @"codePushUpdateStateRunning": @(CodePushUpdateStateRunning),
                                        ^
node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:13:42: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
RCT_ENUM_CONVERTER(CodePushUpdateState, (@{ @"codePushUpdateStateRunning": @(CodePushUpdateStateRunning),
                                         ^
node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:17:20: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
                   CodePushUpdateStateRunning, // Default enum value
                   ^
node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:18:20: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
                   integerValue)
                   ^
node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:20:1: error: expected function body after function declarator
@end
^
node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:20:5: error: missing '@end'
@end
    ^
node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:11:1: note: implementation started here
@implementation RCTConvert (CodePushUpdateState)
^
5 warnings and 4 errors generated.
`

**Comment by chrislincp** [comment]
> we have the same issue, where the error is:
> `In file included from node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:1: node_modules/react-native-code-push/ios/CodePush/CodePush.h:146:34: warning: this block declaration is not a prototype [-Wstrict-prototypes] doneCallback:(void (^)())doneCallback ^ void node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:4:2: warning: missing submodule 'React.React.RCTConvert' [-Wincomplete-umbrella] #import <React/RCTConvert.h> ^ ~ node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:11:17: error: declaration of 'RCTConvert' must be imported from module 'React' before it is required @implementation RCTConvert (CodePushUpdateState) ^ In module 'React' imported from node_modules/react-native-code-push/ios/CodePush/CodePush.h:2: ios/Pods/Headers/Public/React/React/RCTConvert.h:27:12: note: previous declaration is here @interface RCTConvert : NSObject ^ node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:13:42: error: expected ')' RCT_ENUM_CONVERTER(CodePushUpdateState, (@{ @"codePushUpdateStateRunning": @(CodePushUpdateStateRunning), ^ node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:13:41: note: to match this '(' RCT_ENUM_CONVERTER(CodePushUpdateState, (@{ @"codePushUpdateStateRunning": @(CodePushUpdateStateRunning), ^ node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:13:42: warning: type specifier missing, defaults to 'int' [-Wimplicit-int] RCT_ENUM_CONVERTER(CodePushUpdateState, (@{ @"codePushUpdateStateRunning": @(CodePushUpdateStateRunning), ^ node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:17:20: warning: type specifier missing, defaults to 'int' [-Wimplicit-int] CodePushUpdateStateRunning, // Default enum value ^ node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:18:20: warning: type specifier missing, defaults to 'int' [-Wimplicit-int] integerValue) ^ node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:20:1: error: expected function body after function declarator @end ^ node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:20:5: error: missing '@end' @end ^ node_modules/react-native-code-push/ios/CodePush/RCTConvert+CodePushUpdateState.m:11:1: note: implementation started here @implementation RCTConvert (CodePushUpdateState) ^ 5 warnings and 4 errors generated. `

do you fixed this problem?

**Comment by xclidongbo** [comment]
the same error.

**Comment by alexandergoncharov** [comment]
Hi all,

Unfortunately, I can'teproduce your issue. Could you pelase provide some test project example?

I'm going to close this issue for now. Please feel free to reopen it when you provide sme test project or if oyu have any questions.
