### ISSUE TITLE
ios React native 0.60.5 dont work

### ISSUE THREAD

**Issue by zhllucky** [microsoft/react-native-code-push#1682]
# Steps to Reproduce
1.npm i
2. pod install
3. update Appdelegate.m

### Expected Behavior
I can use it, and install,then restart app, can show new code

### Actual Behavior
What actually happens?
```
I can install new code,then restart app,but also show old code,and then I add codePush.notifyAppReady() to my index.js componentDidMount, but also dont work.
```

### Environment

* react-native-code-push version:5.6.1
* react-native version:0.60.5

**Comment by wzulfikar** [comment]
Hi @zhllucky, I was working with rn 0.60.5 and react-native-code-push 5.7.0. I can confirm that it works correctly in iOS (in my case it was iOS 12.5, on simulator). Not sure what error messages you get, maybe you can try put this code in your `componentDidMount`?

```
componentDidMount() {
  codePush
    .checkForUpdate()
    .then(update => {
      if (update) {
        console.log('[INFO][codePush] update found:', update);
      } else {
        console.log('[INFO][codePush] no updates available');
      }
    })
    .catch(e => {
      console.log('[INFO][codePush] could not check for update:', e.message);
      console.log('[INFO][codePush] error trace:', e);
    });
}
```

The code will check if there's an update available. If it works, then you get (at least) these following rights:
- react-native-code-push is correctly installed and integrated with iOS
- code push deployment key is correct

When I was debugging my app, above code helped me figure out that I actually used wrong deployment key: I deployed new update to staging, but the key installed in the app was for production.

**Comment by alexandergoncharov** [comment]
Hi all,

We opened PR for updating docs with setup CodePush for react-native@0.60 and above. If fix this warning.
For more info please check here: https://github.com/microsoft/react-native-code-push/issues/1625#issuecomment-560489061

I'm going to close this issue as duplicate. Please feel free to ask any questions.

Thanks,
Alexander
