### ISSUE TITLE
Upload progress:[==                                                ] 4% 1.1s[Error]  Not Found

### ISSUE THREAD

**Issue by JmStefanAndroid** [microsoft/react-native-code-push#1683]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/15886002/65207904-f24c2600-dac5-11e9-90b1-535ff33d4c3b.png">

my workmates run the same command with no problem

what's wrong with my environment?

### Environment

* react-native-code-push version:5.4.2
* react-native version:0.55.4

**Comment by JmStefanAndroid** [comment]
could anybody help me?

**Comment by alexandergoncharov** [comment]
Hi @JmStefanAndroid ,
Thanks for reporting!

Looks like this is issue occured becasue we were updating CodePush server side. We are sorry for that. :disappointed:
It works correctly now.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or if you faced this issue again.
