### ISSUE TITLE
Sync already in progress for every relaunch.

### ISSUE THREAD

**Issue by Akash-T2S** [microsoft/react-native-code-push#1689]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Fresh launch, status 6 working fine
2. Kill the app and relaunch again. Status 4 (Sync already in progress)

### Expected Behavior
Status 6 should be expected with updated available dialog

### Actual Behavior
Status 4 appears says Sync already in progress
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 5.7.2
* react-native version: 59.9
* iOS/Android/Windows version:Android Version - 9
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? Samsung S8

This issue reproduced with Samsung S8, but with Redmi note 4 and Huawei p30 pro its working fine.
It will be helpful if i get to know how to stop the ongoing sync whenever the app is relaunched.

Redmi android version - 7,
Huawei android version - 9
(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @Akash-T2S 
Thanks for reporting!

I tried to reproduce your issue but attempts were unsuccessfull. Could you please provide test project with reproducing issue?

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or provide test project.

**Comment by Appkidd** [comment]
Also experiencing this issue.

**Comment by jshinrock** [comment]
For anyone coming here to try to solve this–

I can't say exactly what version this changes, but one of the upgrades we did for CodePush started showing this message. Our problem was the use of the `codePush.sync({...options})` declaration in the app. Previously, codepush seemed init with these options, but now we must pass them to the decorator to produce the desired functionality.

Ex:
`const codePushOptions = {
   checkFrequency: codePush.CheckFrequency.MANUAL,
   ...otherOptions,
};

App = codePush(codePushOptions)(App);`

**Comment by JohnBerd** [comment]
@jshinrock indeed it seems to work only with the `checkFrequency: codePush.CheckFrequency.MANUAL` option.

Definitely not the option I want for my app
