### ISSUE TITLE
Any ETA for new update?

### ISSUE THREAD

**Issue by seriiix** [microsoft/react-native-code-push#1690]
Thank you for this amazing project. I know you are working on a new version but can you give us an ETA of this new version? We don't feel comfortable to use CodePush on RN60+ because it seems there are a few problems with it. So it'll be helpful if you give us an ETA over the next update.

**Comment by bitlab-code** [comment]
+1

**Comment by miller345** [comment]
+1

**Comment by ValterSantosMatos** [comment]
+1

**Comment by andreidubov** [comment]
Hi @FuriioS ,
Thank you for reporting!

Not so long ago we released a new version of Code Push which supports react-native v0.60-v0.61.
All steps for installing the latest version of the plugin are described in our documentation.
For iOS: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md
For Android: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues
