### ISSUE TITLE
Code push not working properly on IOS

### ISSUE THREAD

**Issue by winardis** [microsoft/react-native-code-push#1691]
### Expected Behavior
Install updated version of app via codepush

### Actual Behavior
[Android] Installs properly to what i have expected, prompts update popup, installs update, restarted with updated code
[IOS] Only prompts that there is an update available but nothing is installed, and the app didnt restart also after closing and opening the app, no updates are installed
```
    codePush.sync({
      updateDialog: true,
      installMode: codePush.InstallMode.IMMEDIATE
    }).then(()=> codePush.notifyAppReady());
```

### Environment

* react-native-code-push version: 5.7.0
* react-native version: 0.60.5
* iOS version: 
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)
![IMG_0017](https://user-images.githubusercontent.com/48976564/66029323-3f4de480-e529-11e9-99a4-24989ba344da.png)

**Comment by sunweiyang** [comment]
This is also happening with my app (RN 0.61.2, react-native-code-push 5.7.0).

**Comment by sunweiyang** [comment]
Never mind, my issue was actually #1694 and microsoft/code-push#665 (503 error originating from AppCenter). Looks like it's resolved.

**Comment by thuann-vn** [comment]
My app facing the same issue :(

**Comment by wnabil** [comment]
Just in case if someone did not notice the mention yet, its caused because of codePush.notifyAppReady()
you should call it BEFORE .sync not in the success callback as it will reinit the plugin and delete the downloaded update.zip file 
https://github.com/microsoft/cordova-plugin-code-push/issues/571#issuecomment-561875520

**Comment by andreidubov** [comment]
Hi @winardis,
Thank you for reporting!

Yeah, @wnabil is right. Thanks!
Also, here here is README section with this info: https://github.com/microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushnotifyappready

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.
