### ISSUE TITLE
Missing required property: deployment_key

### ISSUE THREAD

**Issue by xralphack** [microsoft/react-native-code-push#1692]
### Steps to Reproduce
1. I want to use Dynamic Deployment Assignment in ReactNative iOS

### Expected Behavior
What you expected to happen?

I want to put my deployment key in js only, so I did not add the key in info.plist

### Actual Behavior

<img width="730" alt="Screen Shot 2019-10-03 at 2 14 42 PM" src="https://user-images.githubusercontent.com/9164448/66103518-9cf53600-e5e8-11e9-9144-df1ac7de192f.png">

error message is
`
The "release_metadata" body parameter is invalid ({"app_version":"1.0","client_unique_id":"xxx"}) JSON Schema validation error. Data path: "" Schema path: "/required/0" Missing required property: deployment_key
`
However I can successfully update via code push. Just in curious is this a bug for Dynamic Deployment Assignment

The 400 status code only happens for the first time before update via code push.
After updated, the request did brings the deployment_key

### Environment

* react-native-code-push version: 5.7.0
* react-native version: 0.61.1
* iOS/Android/Windows version: iOS 12
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? simulator

**Comment by daheeahn** [comment]
any solution?

**Comment by yogeshwarnair-gep** [comment]
any updates regarding same ?

**Comment by andreidubov** [comment]
Hi @xralphack ,
Thank you for reporting!

As I can see, you are using react-native v0.61.1 and react-native-code-push v5.7.0 but these are incompatible versions, you can take a look at supporting CodePush versions here: https://github.com/microsoft/react-native-code-push#supported-react-native-platforms

Not so long ago we released a new version of Code Push which supports react-native v0.60-v0.61.
All steps for installing the latest version of the plugin are described in our documentation: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Comment by leotm** [comment]
Might be including it in the decorator

```tsx
// ...
export default codePush({
  deploymentKey: getCodepushDeploymentKey(), // Dynamic assignment works np
  checkFrequency: codePush.CheckFrequency.MANUAL // Don't auto-check for updates, I'll manually codePush.sync()
})(App);
```

But forgot to again manually later

```tsx
codePush.sync() // oops
```

👀

```tsx
// Check, download then install
codePush.sync({
  deploymentKey: getCodepushDeploymentKey()
}); // boom
```
