### ISSUE TITLE
CodePush.checkForUpdate returns 503

### ISSUE THREAD

**Issue by ronilitman** [microsoft/react-native-code-push#1694]
### Steps to Reproduce
1. run CodePush.checkForUpdate and get 503

### Expected Behavior
return null or object

### Actual Behavior
503
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:  5.3.2
* react-native version: 0.59.9
* iOS/Android/Windows version: 
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by komaldeep** [comment]
Happening to me also

**Comment by yogeshchoudhary147** [comment]
+1 Happening for me also. My users are not able to update from last 2 days. `sync` method is also throwing 503.

**Comment by GabrielMachado11** [comment]
Happening here too, at friday everything was working fine...

**Comment by komaldeep** [comment]
Till Friday .. everything was working fine

**Comment by williamtdepaula** [comment]
When the application checks the update status, returns UNKNOWN ERROR

**Comment by twelve17** [comment]
We're seeing a mix of endless waiting for a response, and HTTP 500.

**Comment by sagarv1997** [comment]
Happening here too since saturday, sync method returns UNKNOWN ERROR!

**Comment by esthor** [comment]
happening here

**Comment by yfuks** [comment]
Also facing this issue.
Looks like there are aware of this issue:
https://status.appcenter.ms/

**Comment by GabrielMachado11** [comment]
I sent a message to appcenter support and they answered me it: "Hi there, sorry for the issues our engineers are aware and currently investigating ways to mitigate the issue with App Center - CodePush

I'll keep you up to date while we investigate this issue."

We have to wait :' )

**Comment by ronilitman** [comment]
More info here:
https://github.com/microsoft/code-push/issues/665

**Comment by ronilitman** [comment]
Looks like everything is back to normal 🎉

**Comment by yogeshchoudhary147** [comment]
@ronilitman I would love to understand what went wrong, how did you fix it and possibilities of happening this again in future.

**Comment by alexandergoncharov** [comment]
Hi all,
Thanks for reporting!

Looks like this is issue occured becasue we were updating CodePush server side. We are sorry for that. :disappointed:
It works correctly now.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or if you faced this issue again.
