### ISSUE TITLE
 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed 

### ISSUE THREAD

**Issue by felixchan** [microsoft/react-native-code-push#1696]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
`appcenter codepush release-react -a APPNAME.com/APPNAME-ios -d Production --mandatory --output-dir ./build -t 1.x.x;`

### Expected Behavior
Codepush successfully builds and uploads to server.

### Actual Behavior
```
transform[stderr]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
transform[stderr]: 
transform[stderr]: Writing Node.js report to file: report.20191010.093411.22661.001.json
transform[stderr]: Node.js report completed
transform[stderr]:  1: 0x100062df2 node::Abort() [/usr/local/bin/node]
transform[stderr]:  2: 0x1000634eb node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
transform[stderr]:  3: 0x1001aeda7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
transform[stderr]:  4: 0x1001aed44 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
transform[stderr]:  5: 0x1005b5bd2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
transform[stderr]:  6: 0x1005b8103 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
transform[stderr]:  7: 0x1005b4638 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
transform[stderr]:  8: 0x1005b27f5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
transform[stderr]:  9: 0x1005bf09c v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
transform[stderr]: 10: 0x1005bf11f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
transform[stderr]: 11: 0x10058e314 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
transform[stderr]: 12: 0x100840c54 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
transform[stderr]: 13: 0x23da4894fc7d
```
### Environment

* react-native-code-push version: 
* react-native version: 0.61.1
* iOS/Android/Windows version: 5.7.0

Notes:

Originally, I had this error running a release build on iOS (non-code-push related).  I was able to get it to build by doing:

```
export NODE_BINARY='node  --max_old_space_size=8192 '
```

inside "Bundle React Native code and images"

How can I modify node on CodePush?

**Comment by felixchan** [comment]
```
$ export NODE_MEMORY=8000 appcenter codepush release-react -a APPNAME/APPNAME-ios -d Production --mandatory --output-dir ./build -t 1.x.x;[D
-bash: export: `release-react': not a valid identifier
-bash: export: `-a': not a valid identifier
-bash: export: `fc-sp8cetime.com/sp8cetime-ios': not a valid identifier
-bash: export: `-d': not a valid identifier
-bash: export: `--mandatory': not a valid identifier
-bash: export: `--output-dir': not a valid identifier
-bash: export: `./build': not a valid identifier
-bash: export: `-t': not a valid identifier
-bash: export: `1.x.x': not a valid identifier
-bash: [D: command not found

```

**Comment by andreidubov** [comment]
Hi @felixchan ,
Thank you for reporting!

As I can see, you are using react-native v0.61.1 and react-native-code-push v5.7.0 but these are incompatible versions, you can take a look at supporting CodePush versions here: https://github.com/microsoft/react-native-code-push#supported-react-native-platforms

Not so long ago we released a new version of Code Push which supports react-native v0.60-v0.61.
All steps for installing the latest version of the plugin are described in our documentation.
iOS:  https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md
Android:  https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md

Also remember that you must specify the path not to the build of your application, but to the root directory where your react-native app is located.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.
