### ISSUE TITLE
codepush undefined

### ISSUE THREAD

**Issue by zhonggithub** [microsoft/react-native-code-push#1697]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
like this:
import codePush from 'react-native-code-push';
console.log(codePush)

i get undefiend. I dont konw why?

### Environment

* react-native-code-push version:  5.7.0
* react-native version: 0.61.2
* iOS/Android/Windows version: ios 13

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @zhonggithub,
Thanks for reporting!

Could you please import `CodePush` with first upper case char.
This example should works:

```javascript
import CodePush from 'react-native-code-push';
console.log(CodePush)
```

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Comment by sanjaypojo** [comment]
> Hi @zhonggithub,
> Thanks for reporting!
> 
> Could you please import `CodePush` with first upper case char.
> This example should works:
> 
> ```js
> import CodePush from 'react-native-code-push';
> console.log(CodePush)
> ```
> 
> I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

How is this possible @alexandergoncharov? We are investigating a related issue and came across this. When we import this way, shouldn't we be able to rename it with whatever name? How does code push know what name we use for the import and why does it need to be uppercased?

Any help / docs on this will be helpful!
