### ISSUE TITLE
checkForUpdate method find update but sync method didn't find

### ISSUE THREAD

**Issue by Ryabchikus** [microsoft/react-native-code-push#1701]
### Steps to Reproduce
1. npm i react-native --save
2. react-native link
3. update Info.plist
4. update AppDelegate.m 
5. 

code of my check function 
```
codePush.checkForUpdate().then((update) => {
  console.log('update', update)
})

codePush.sync(
    {
      installMode: codePush.InstallMode.IMMEDIATE,
      deploymentKey,
    },
    syncStatusChangeCallback,
    progressCallback,
)
```

### Expected Behavior
Start downloading update

### Actual Behavior
What actually happens?
codePush.checkForUpdate method  log:
```
 update  { 
    "deploymentKey":"<.......>",
  "label":"v41",
  "appVersion":"11.0",
  "isMandatory":false,
  "packageHash":"6a3e3e5e20f0bd1abdbf00ea37ff69fbeadc5730b296eb2e3b2f817e2d525ad5",
  "packageSize":6308628,
  "downloadUrl":"https://codepushupdates.azureedge.net/storagev2/jq2iEXqg8_JgdvHTUNou1pdo3jgD16b3c45e-2a7f-4216-a642-bcaf8d80525c",
  "isPending":false,
  "failedInstall":false 
}
```

codePush.sync method log:
```
syncStatus 5
syncStatus 0
```
### Environment

```
  "dependencies": {
    ...
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-code-push": "^5.7.0",
    ...
  },
  "devDependencies": {
    ...
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.9.0",
    "flow-bin": "^0.108.0",
    "metro-react-native-babel-preset": "^0.56.0",
    ...
  },
```

-  iOS/Android/Windows version: iOS && Android
-  Does this reproduce on a debug build or release build? debug && release
-  Does this reproduce on a simulator, or only on a physical device? emulator &  physical device

it's start on 06.10 with the symptoms like a #1694, then update check process returns to normal, but app didn't receive no one update

**Comment by alexandergoncharov** [comment]
Hi @Ryabchikus ,
Thanks for reporting!

Could you pelase upgrade your `react-native-code-push` plugin to `6+` version because your vesion is not compatable with your react-native.
And check this new docs for setup code-push of new version: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-ios

I'm going to close this issue for now. Please feel free to reopen it if you have any qeustions or issues.

**Comment by xamgore** [comment]
@alexandergoncharov as I can see, v6.0.0 was [released on 11 Dec 2019](https://github.com/microsoft/react-native-code-push/releases/tag/v6.0.0), so @Ryabchikus could not update it at that time. Thanks for the reply though!

**Comment by alexandergoncharov** [comment]
@Ryabchikus , Yeah, I appreciate it  :)
Yeah, for more fast answer you can use Intercom. You can start dialog on `appcenter.ms` site in the right buttom corner.  
![image](https://user-images.githubusercontent.com/13234108/74532120-6ee11480-4f3f-11ea-99b9-fbd1bc43d5bb.png)
