### ISSUE TITLE
Code Push crash Android app only on Release version

### ISSUE THREAD

**Issue by FuriioS** [microsoft/react-native-code-push#1706]
### Steps to Reproduce
1. Create a React Native (that uses RNFirebase)
2. Add react-native-code-push library
3. Uses react-native link react-native-code-push library and add Android and iOS release keys
4. Follow the steps like the Android & iOS installation tutorials on the Gettin Started section
5. Wrap the root component like this:

```

import React, {Component} from 'react';
import codePush from "react-native-code-push";

class App extends Component {
  render() {
    return (
      ...
    )
  }
}

let codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.ON_NEXT_RESTART,
  updateDialog: true
};

App = codePush(codePushOptions)(App);
```

6. Build and start the debug app version (Android & iOS) start fine.
7. Build and start the release app version on iOS works fine, but in Android crash.

### Expected Behavior
Android Release Version starts normally

### Actual Behavior
Android release crash with the following stack trace:

> FATAL EXCEPTION: mqt_native_modules
> Process: es.myrealfood.myrealfood, PID: 11013
> java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String **com.facebook.react.bridge.ReadableMap.getString**(java.lang.String)' on a null object reference
>  	**at com.facebook.react.modules.blob.FileReaderModule.readAsText**(FileReaderModule.java:41)
>  	at java.lang.reflect.Method.invoke(Native Method)
>  	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
>  	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
>  	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
>  	at android.os.Handler.handleCallback(Handler.java:873)
>  	at android.os.Handler.dispatchMessage(Handler.java:99)
>  	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
>  	at android.os.Looper.loop(Looper.java:193)
>  	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
>  	at java.lang.Thread.run(Thread.java:764)
> 

If I completelly remove react-native-code-push implementation, app works fine.

I can see the following messages on logcat:

> 
>  [CodePush] Loading JS bundle from "assets://index.android.bundle"
>  [CodePush] Checking for update.
>  [CodePush] Sync already in progress.
>  [CodePush] Reporting binary update (1.2.8)
> 

A few lines later app crashes

### Environment

* react-native-code-push version: ^5.7.0
* react-native version: 0.61.2
* react version: 16.9.0
* Android version: 9
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Physical device

**I think that it can be a problem with Fetch Blob library. I am using rn-fetch-blob: ^0.11.2...**

**UPDATED 2019-10-22**
iOS debug build throws the following:

> 
>  LOG  [CodePush] Sync already in progress.
>  LOG  [CodePush] Checking for update.
>  LOG  [CodePush] Reporting binary update (1.2.9)
>  LOG  [CodePush] An unknown error occurred.
>  LOG  [CodePush] **Unable to resolve data for blob: (null)**
>  LOG  [CodePush] Report status failed: {"appVersion":"1.2.9"}
> 

**UPDATED 2019-10-25**
I made the following changes on request-fetch-adapter.js file:

```
const packageJson = require("./package.json");
**import RNFetchBlob from 'rn-fetch-blob'**

module.exports = {
  async request(verb, url, requestBody, callback) {
    if (typeof requestBody === "function") {
      callback = requestBody;
      requestBody = null;
    }

    const headers = {
      "Accept": "application/json",
      "Content-Type": "application/json",
      "X-CodePush-Plugin-Name": packageJson.name,
      "X-CodePush-Plugin-Version": packageJson.version,
      "X-CodePush-SDK-Version": packageJson.dependencies["code-push"]
    };

    if (requestBody && typeof requestBody === "object") {
      requestBody = JSON.stringify(requestBody);
    }

    try {
      **const response = await RNFetchBlob.fetch(getHttpMethodName(verb), url, headers, requestBody);**
      const statusCode = response.status;
      const body = await response.text();
      callback(null, { statusCode, body });
    } catch (err) {
      callback(err);
    }
  }
};
```
And now CodePush logs throws:

>  LOG  [CodePush] Sync already in progress.
>  LOG  [CodePush] Checking for update.
**>  LOG  [CodePush] An unknown error occurred.**
>  LOG  [CodePush] undefined: {"update_info":{"download_url":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","is_available":true,"is_disabled":false,"target_binary_range":"1.3.1","package_hash":"582ca1058c05658a1bec18c45b23bcb62c494be52dfcb8eb086e7f6a3cc74adc","label":"v8","package_size":5398299,"update_app_version":false,"should_run_binary_version":false,"is_mandatory":true}}
> 

Regards

**Comment by longnk-1447** [comment]
the same issue

**Comment by sourabhkheterpal** [comment]
@FuriioS @longnk-1447  Same issue here. Have you found any solution regarding this issue? Thanks!

**Comment by andreidubov** [comment]
Hi @FuriioS ,
Thank you for reporting!

As I can see, you are using react-native v0.61.2 and react-native-code-push v5.7.0 but these are incompatible versions, you can take a look at supporting CodePush versions here: https://github.com/microsoft/react-native-code-push#supported-react-native-platforms

Not so long ago we released a new version of Code Push which supports react-native v0.60-v0.61.
All steps for installing the latest version of the plugin are described in our documentation: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.
