### ISSUE TITLE
[CodePush] An unknown error occurred

### ISSUE THREAD

**Issue by flutterhope** [microsoft/react-native-code-push#1709]
### Steps to Reproduce
1. react-native init codetest

2. yarn add react-native-code-push
autolink

3. strings.xml
<string name="reactNativeCodePush_androidDeploymentKey" moduleConfig="true">key</string>

4. android/app/src/main/assets/appcenter-config.json
{
    "app_secret": "key"
}

### Actual Behavior
What actually happens?
this is log when I start react-native project
 LOG  Running "codetest" with {"rootTag":31}
 LOG  [CodePush] Checking for update.
 LOG  [CodePush] Downloading package.
 LOG  [CodePush] An unknown error occurred.
 LOG  [CodePush] Error in getting binary resources modified time

codepush does not work properly. What is the reason?

### Environment

* react-native-code-push version:5.7.0
* react-native version:0.61.2
* iOS/Android/Windows version:Android 
buildToolsVersion = "28.0.3"
minSdkVersion = 16
compileSdkVersion = 28
targetSdkVersion = 28
* Does this reproduce on a debug build or release build?debug build
* Does this reproduce on a simulator, or only on a physical device? simulator

(The more info the faster we will be able to address it!)

**Comment by qwertypomy** [comment]
+
Same on Anrdroid debug and release build
iOS works fine

react-native-code-push version:5.7.0
react-native version:0.61.2

**Comment by ThanhNghia944** [comment]
same issue

**Comment by ThanhNghia944** [comment]
for react native v61 you can add into MainApplication
 @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }

**Comment by qwertypomy** [comment]
Works on android with manually linked code-push.

**Comment by ghyzx** [comment]
I met the same problem.

"react": "16.9.0",
 "react-native": "0.61.3",
 "react-native-code-push": "^5.7.0",

**Comment by luskin** [comment]
@qwertypomy We're having issues getting this to work on RN 0.61.4 on iOS - how did you get this working? We are plagued with the following problem:

https://github.com/microsoft/react-native-code-push/issues/1704

Would you mind providing some quick guidance on how you got this properly setup on iOS?

**Comment by quanzaiyu** [comment]
The same issue.

I use debug build and physical device.

![image](https://user-images.githubusercontent.com/13745132/69301317-cf1e2e00-0c50-11ea-88f8-2a86404c44a4.png)

**Comment by ahartzog** [comment]
@quanzaiyu removing the --development flag from my codepush release build process resolved this error for me.

**Comment by guiherzog** [comment]
The solution that worked for me was manually linking it. To do that, you just need to follow all instructions on this link: [Android Setup RN 0.60+](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android)

**Comment by alexandergoncharov** [comment]
Hi all,

Yeah, @guiherzog is right. Thanks!
Please ensure that you have did all in that docs: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android

Also, please update your `react-native-code-push` to `6+` version if you would like to use `react-native@0.60+` versions.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Comment by gagangoku** [comment]
Thanks @guiherzog your solution works !

**Comment by maxdelemos** [comment]
bro, thank you very much @guiherzog
