### ISSUE TITLE
Is there any risk of being rejected in iOS by using react-native-code-push?

### ISSUE THREAD

**Issue by changpk** [microsoft/react-native-code-push#1711]

**Comment by anthonyhumphreys** [comment]
So long as you follow the guidelines, then no.

See here: https://microsoft.github.io/code-push/faq/#1-does-the-apple-app-store-allow-developers-to-perform-these-types-of-updates

The only issue you would face is if you radically change the app's purpose etc via codepush

**Comment by changpk** [comment]
@anthonyhumphreys Thanks for your reply, because [pushy](https://github.com/reactnativecn/react-native-pushy/issues/285) is also a hot update third-party library used in react-native, but recently some apps using this third-party library were rejected by apple。

**Comment by alexandergoncharov** [comment]
Hi @changpk ,
Thanks for reporting!

Yeah, @anthonyhumphreys is right. Thanks!

Also, here here is README section with this info: https://github.com/microsoft/react-native-code-push#store-guideline-compliance

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
