### ISSUE TITLE
RN 61.2

### ISSUE THREAD

**Issue by chalarlie** [microsoft/react-native-code-push#1712]
Has anyone gotten this to successfully work with RN 61?

It seems as though it is downloading and installing the updates correctly, which means my deployment keys are set up correctly. However, **I am not actually seeing any changes** when the update is installed and applied. It does not appear that the updates are getting rolled back from the console.

I have wrapped my app in the higher-order component, like so:

```
const CodePushApp = codePush()(App);

export default CodePushApp;
```

Could it be that CodePush does not support functional components, and I need to refactor my main app to be a class component?

**Comment by Darkhorse-Fraternity** [comment]
0.61.2 Download succeeded, but no replacement

**Comment by chalarlie** [comment]
@matejkriz Thank you! I made those two changes and everything seems to be working now.

@Darkhorse-Fraternity  -- I suggest you try these things as well (making your root a PureComponent and doing the sync manually on the JS side).

**Comment by AdrianoBiolchi** [comment]
Hi @chalarlie, how did you set up your MainApplication.java in the package part?

**Comment by chalarlie** [comment]
Hey @AdrianoBiolchi , my apologies for the late response. I actually have not yet tried this on the Android side but will taking a look at that in a couple of weeks. I will follow up here if you haven't found a solution.

**Comment by zanechua** [comment]
You guys can refer to https://github.com/MicrosoftDocs/appcenter-docs/pull/767 for the updated documentation.

**Comment by alexandergoncharov** [comment]
Hi all,

We opened PR for updating docs with setup CodePush for react-native@0.60 and above.
For more info please check here: https://github.com/microsoft/react-native-code-push/issues/1625#issuecomment-560489061

I'm going to close this issue as duplicate. Please feel free to ask any questions.

Thanks,
Alexander

**Comment by dwilt** [comment]
@alexandergoncharov FYI we followed [the new](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#ios-setup) iOS setup docs and it all works well, except, if you don't define the `deploymentKey` _on the JS side_ like [@matejkriz suggested](https://github.com/microsoft/react-native-code-push/issues/1712#issuecomment-547956577), the updates don't install in _release mode_ but do work install correctly in debug mode.

I did not see this mentioned in the setup guide and I think it should be noted or it's a bug that needs to be fixed.
