### ISSUE TITLE
Unable to push code from command line

### ISSUE THREAD

**Issue by jpr-longgame** [microsoft/react-native-code-push#1717]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Attempt to codepush from command line

### Expected Behavior
What you expected to happen?

App would assemble and release to CodePush

### Actual Behavior
What actually happens?

App seems to assemble and upload for a while, then fail suddenly without a useful error message.

```
  Detecting android app version:

Using the target binary version value "3.9.0" from "android/app/build.gradle".

Running "react-native bundle" command:

node node_modules/react-native/local-cli/cli.js bundle --assets-dest /var/folders/hz/gnn5zh5d6tlb96cs9rhhn65xrl7r_6/T/code-push119101-10568-1oknb3a.ouar/CodePush --bundle-output /var/folders/hz/gnn5zh5d6tlb96cs9rhhn65xrl7r_6/T/code-push119101-10568-1oknb3a.ouar/CodePush/index.android.bundle --dev false --entry-file index.android.js --platform android
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-code-push: https://microsoft.github.io/code-push
  - react-native-extra-dimensions-android: https://github.com/Sunhat/react-native-extra-dimensions-android#readme
  - react-native-fabric: https://github.com/corymsmith/react-native-fabric
  - react-native-sms: https://github.com/tkporter/react-native-sms
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
Loading dependency graph, done.

info Writing bundle output to:, /var/folders/hz/gnn5zh5d6tlb96cs9rhhn65xrl7r_6/T/code-push119101-10568-1oknb3a.ouar/CodePush/index.android.bundle
info Done writing bundle output
info Copying 993 asset files
info Done copying assets

Releasing update contents to CodePush:

Error: 
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 3.0.1
* react-native version: 0.61.3
* iOS/Android/Windows version: Android (any)
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? n/a

(The more info the faster we will be able to address it!)

I was able to release the iOS version of the same app just a few minutes prior.

**Comment by jpr-longgame** [comment]
A subsequent try resulted in some 502 error HTML being displayed where I've previously only seen `Error:`

The try after that yielded only the nondescript `Error:`

**Comment by AndrewMorsillo** [comment]
I also can't code push anymore. Every attempt errors with:

```
Error: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.15.8</center>
</body>
</html>
```

**Comment by mlazari** [comment]
@AndrewMorsillo Seeing the same error.

**Comment by SasukeJimmyChang** [comment]
@AndrewMorsillo same error

**Comment by Lalksy** [comment]
@AndrewMorsillo same error here too. I tried uploading an budle identical to one that successfully uploaded last week, but I got this error.

**Comment by hamzaehsan95** [comment]
Same issue. Unable to push the update.

**Comment by yogeshchoudhary147** [comment]
Getting same error since yesterday.

**Comment by factionfour** [comment]
Same here

**Comment by wenlynnchen** [comment]
Same here! Is there any solution to fix this problem?

**Comment by abdulbasit1248** [comment]
Please help us in this matter

**Comment by factionfour** [comment]
Is there any alternative approach to create a release bundle?  I need to push something out for a customer ASAP.

BTW, I am encountering this on cordova.

**Comment by amit4j** [comment]
What is the ETA to fix this issue? Blocking a release for me.

**Comment by AndrewMorsillo** [comment]
Any movement on this issue? Codepush still appears to be broken on Appcenter's side. Nothing has changed about my build or process and CodePush suddenly stopped working.

**Comment by AndrewMorsillo** [comment]
@amit4j @factionfour @abdulbasit1248 @wenlynnchen @yogeshchoudhary147 @hamzaehsan95 @Lalksy @SasukeJimmyChang @mlazari You can message the appcenter team though intercom on appcenter.ms, it might be worth trying to get their attention. I did it 4 days ago but unfortunately they have been very slow with responses and haven't acknowledged the issue yet. Could also try twitter. 

Are there alternative solutions for hot code push for react-native and Cordova? If AppCenter is going to go down for 4+ days at a time without warning and no response from the team I might need to use a different solution.

**Comment by cainejette** [comment]
Hey there! Apologies for the slow reply. Thanks for the report, we are investigating!🕵️‍♂️

**Comment by AndrewMorsillo** [comment]
@cainejette Thanks! Is there a better way to reach the AppCenter team in critical outage cases like this? I tried intercom but the person who responded to me there didn't appear to take the issue seriously and communication was painfully slow.

**Comment by Lalksy** [comment]
@cainejette @AndrewMorsillo Some movement on this issue. Instead of 403 error I am seeing a "Bad Gateway" error.

**Comment by cainejette** [comment]
@AndrewMorsillo Intercom is the correct method. I am sorry you did not have a good experience there.

We are deploying a fix, stay tuned.

**Comment by cainejette** [comment]
We should no longer be seeing 413s! :tada: Please let me know if you are still seeing issues.

**Comment by mlazari** [comment]
It's fixed for us.

**Comment by pfleidi** [comment]
Is anybody else still seeing these issues? We're trying to make sure we caught everything with our fix.

**Comment by AndrewMorsillo** [comment]
All fixed! Thanks for patching it up =)

**Comment by wenlynnchen** [comment]
> We should no longer be seeing 413s! 🎉 Please let me know if you are still seeing issues.

It's all fixed! Thank you :)

**Comment by pfleidi** [comment]
From what we can see, this issue seems to be resolved. I'm closing it for now.

**Comment by lilicoder** [comment]
![image](https://user-images.githubusercontent.com/24731304/98652171-30fe0900-2376-11eb-95ef-5e8a6a05ec52.png)
Getting same error since today
