### ISSUE TITLE
'React/RCTEventDispatcher.h' file not found

### ISSUE THREAD

**Issue by tmdeginal** [microsoft/react-native-code-push#1718]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.   "react-native-code-push": "^5.6.0",
2.  "react-native": "0.60.5",
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by andreidubov** [comment]
Hi @xralphack ,
Thank you for reporting!

As I can see, you are using react-native v0.60.5 and react-native-code-push v5.6.0 but these are incompatible versions, you can take a look at supporting CodePush versions here: https://github.com/microsoft/react-native-code-push#supported-react-native-platforms

Not so long ago we released a new version of Code Push which supports react-native v0.60-v0.61.
All steps for installing the latest version of the plugin are described in our documentation: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md

If you still have this issue, could you please provide more detailed reprosteps or test project with reproducing issue?

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.
