### ISSUE TITLE
How to set the mServerUrl in Rn 0.60+

### ISSUE THREAD

**Issue by buffge** [microsoft/react-native-code-push#1720]
现在的解决方案是修改codepush 的 package.json 里面的 packageInstance
但是我觉得这个问题应该是可以配置的,而不是修改源码包

**Comment by Runtime007** [comment]
set `postinstall` in your project's package.json file, like this:
```
 "scripts": {
    "postinstall": "sed -ig 's/new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG)/new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG, "your server url")/g' node_modules/react-native-code-push/package.json",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
  },
```
after `npm install`, it will excute `postinstall` and replace packageInstance.

**Comment by RodolfoGS** [comment]
Please write in english.

**Comment by buffge** [comment]
The current solution is to modify the packageinstance in the package.json of codepush

But I think this problem should be configurable rather than modifying the source package

**Comment by andreidubov** [comment]
Hi @buffge,
Thank you for reporting!

As I understand it, you want to specify the CodePush Server URL. You shouldn't modify the `packageinstance` in the `package.json` for this. You can find all the necessary information in the documentation at this link: https://github.com/microsoft/react-native-code-push/blob/master/docs/api-android.md#api-for-react-native-060-version-and-above

You should override it by adding your path to `strings.xml` with name `CodePushServerUrl` like this: `<string moduleConfig="true" name="CodePushServerUrl">https://yourcodepush.server.com</string>`

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
