### ISSUE TITLE
[help] is there any method to push a absolutely new apk download url to user?

### ISSUE THREAD

**Issue by iaminvictus1993** [microsoft/react-native-code-push#1721]

**Comment by andreidubov** [comment]
Hi @iaminvictus1993 ,
Thank you for reporting!

Code Push allows you to create bundle update only for js part of your application. Any changes which touch native code (e.g. modifying your AppDelegate.m file, info.plist, adding a new plugin) cannot be distributed via CodePush, and therefore, must be updated via the appropriate store. Keep in mind, you cannot distribute your new apk via CodePush. Also you cannot override download url.

I'm going to close this issue for now. Please let me know if you have any other questions.
