### ISSUE TITLE
Please clean up branches

### ISSUE THREAD

**Issue by friederbluemle** [microsoft/react-native-code-push#1722]
This repo contains branches with prefix `Goncharov/` **and** `goncharov/`.

On case insensitive file systems (unfortunately the default on macOS and Windows), fetching from this repo results in never ending messages (on every fetch):

```
Fetching origin
From https://github.com/microsoft/react-native-code-push
 - [deleted]         (none)     -> origin/Goncharov/change_docs_for_59_react-native
 - [deleted]         (none)     -> origin/Goncharov/fix_vulnerable_dependencies
 - [deleted]         (none)     -> origin/Goncharov/update_dev_dependecies
 * [new branch]      goncharov/change_docs_for_59_react-native -> origin/goncharov/change_docs_for_59_react-native
 * [new branch]      goncharov/fix_vulnerable_dependencies     -> origin/goncharov/fix_vulnerable_dependencies
 * [new branch]      goncharov/update_dev_dependecies          -> origin/goncharov/update_dev_dependecies
```

The reason is Git is unable to create the underlying file structure on disk (a `/` in a branch name translates into a directory in `.git/refs/remotes/..`)

It would be great if these stale branches could be cleaned up from this repo.

As a general suggestion, it's best to avoid upper case characters (and if possible slashes) in branch names altogether.

**Comment by alexandergoncharov** [comment]
Hi @friederbluemle,
Thanks for reporting!
I just cleaned the branches.

Please feel free to ask any questions.
