### ISSUE TITLE
update assets only

### ISSUE THREAD

**Issue by FansPro** [microsoft/react-native-code-push#1723]
####  "react-native-code-push": "5.6.0"

> I need to update the react-native app only with the image assets(no js code update),  i get the assets with react-native bundle like: 
```
react-native bundle --entry-file ./index.js --bundle-output ./bundles/main.jsbundle --platform ios --assets-dest ./bundles --dev false
```
then i update with code: 
```
code-push release <app name> ./bundles/assets <version>  --deploymentName Production --noDuplicateReleaseError
```
##### I get an update in react-native app, but i can't update the assets. should i push update contents without main.jsbundle ?

**Comment by alexandergoncharov** [comment]
Hi @FansPro ,
Thanks for reporting!

CodePush has diffworker which checks each CodePush release and makes diff update. This update contains only changed items of your update.
For example for your case: if you changed just assets(js code is the same), you should make full CodePush update. DiffWorker checked that only assets were changed and your end users download exaclty this changed assets.
I hope it was helpful for you.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
