### ISSUE TITLE
Code push cli returns `[Error]  Internal Server Error`

### ISSUE THREAD

**Issue by pho3nixf1re** [microsoft/react-native-code-push#1724]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. login with the cli
2. run the command `code-push deployment history <app> <environment>`
3. see error `[Error]  Internal Server Error`

### Expected Behavior
To see a list of releases.

### Actual Behavior

```
  [Error]  Internal Server Error
```

### Reproducible Demo
n/a

### Environment

- MacOS Catalina
- code-push cli version `2.1.9`

### Other info

I am unsure how to get more info or otherwise run the CLI with debug flags. It would be great if I could see more detail other than that generic error in the console. This is happening across our team and seems to have only cropped up this morning. I have submitted support requests through appcenter.ms but so far have not received a response. The above command did succeed one time earlier today but has since not worked again.

**Comment by pho3nixf1re** [comment]
Update: the appcenter cli with `--debug` on returns this error:

```
/ Getting CodePush deployments metrics...Response status code: 400
Body: {"message":"OOM command not allowed when used memory > 'maxmemory'."}
```

**Comment by ribamarsantos** [comment]
Getting the same error here too. Yesterday I did a codepush and worked fine. If you check also in the appcenter is getting 404 in the console and active devices and rollback is empty.

**Comment by ribamarsantos** [comment]
I think this issue should be post here as other people did https://github.com/microsoft/appcenter-cli/issues/699

**Comment by pho3nixf1re** [comment]
I'll close this in preference for that one.
