### ISSUE TITLE
Crash after codepush update

### ISSUE THREAD

**Issue by learnyst** [microsoft/react-native-code-push#1727]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.We cannot reproduce the issue. We are getting crashes in bugsnag.

### Expected Behavior
After codepush there should not be any crash.

### Actual Behavior
After code push many users are facing app crash. We are getting below stacktrace in bugsnag:
java.lang.RuntimeException java.lang.IllegalStateException: Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{4a99197 V.E...... ......ID 0,0-1080,2004}
ReactContext.java:335 com.facebook.react.bridge.ReactContext.handleException
GuardedRunnable.java:26 com.facebook.react.bridge.GuardedRunnable.run
Handler.java:873 android.os.Handler.handleCallback
Handler.java:99 android.os.Handler.dispatchMessage
Looper.java:214 android.os.Looper.loop
ActivityThread.java:7045 android.app.ActivityThread.main
Method.java:-2 java.lang.reflect.Method.invoke
RuntimeInit.java:493 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
ZygoteInit.java:964 com.android.internal.os.ZygoteInit.main

Caused by: java.lang.IllegalStateException Expect view tag to be set for com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{4a99197 V.E...... ......ID 0,0-1080,2004}
RNGestureHandlerRootHelper.java:45 com.swmansion.gesturehandler.react.RNGestureHandlerRootHelper.<init>
RNGestureHandlerEnabledRootView.java:49 com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.initialize
RNGestureHandlerModule.java:603 com.swmansion.gesturehandler.react.RNGestureHandlerModule$2.execute
UIViewOperationQueue.java:530 com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute
UIViewOperationQueue.java:844 com.facebook.react.uimanager.UIViewOperationQueue$1.run
UIViewOperationQueue.java:952 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
UIViewOperationQueue.java:44 com.facebook.react.uimanager.UIViewOperationQueue.access$2200
UIViewOperationQueue.java:910 com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded
GuardedRunnable.java:24 com.facebook.react.bridge.GuardedRunnable.run
Handler.java:873 android.os.Handler.handleCallback
Handler.java:99 android.os.Handler.dispatchMessage
Looper.java:214 android.os.Looper.loop
ActivityThread.java:7045 android.app.ActivityThread.main
Method.java:-2 java.lang.reflect.Method.invoke
RuntimeInit.java:493 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
ZygoteInit.java:964 com.android.internal.os.ZygoteInit.main

### Environment

* react-native-code-push version:5.7.0
* react-native version:0.60.4
* iOS/Android/Windows version: All versions in android
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? physical device

We are using react-native-code-push. In android we are getting many rollbacks. We have checked our bugsnag and found the above crash reports.

this exception happens only after codepush. I have checked many react-native-code-push issues. for many crashes the solution was to remove state updates(this.setState) in the app component. But there is no official confirmation for this from codepush team. Also react-native-code-push sample app has state updates

Can you please clarify whether we should not have state updates in app.js? If we should not have state updates then what is the reason and what is the alternative way?

**Comment by ozican** [comment]
same here, I got lots of crash report.

**Comment by xyxabcdiy** [comment]
same here, but my error trace is 
```
java.lang.AssertionError:Root node with tag 1 doesn't exist
--
com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:35)
com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:290)
com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:462)
java.lang.reflect.Method.invoke(Native Method)
com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
android.os.Handler.handleCallback(Handler.java:873)
android.os.Handler.dispatchMessage(Handler.java:99)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
android.os.Looper.loop(Looper.java:222)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
java.lang.Thread.run(Thread.java:764)
```

this error only occur for  `installMode = CodePush.InstallMode.IMMEDIATE` and `checkFrequency = ON_APP_RESUME`

**Comment by andreidubov** [comment]
Hi @learnyst ,
Thank you for reporting!

As I can see, you are using react-native v0.60.4 and react-native-code-push v5.6.0 but these are incompatible versions, you can take a look at supporting CodePush versions here: https://github.com/microsoft/react-native-code-push#supported-react-native-platforms

Not so long ago we released a new version of Code Push which supports react-native v0.60-v0.61.
All steps for installing the latest version of the plugin are described in our documentation: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md

I'm going to close this issue for now. Please feel free to reopen if you still have this issue.

**Comment by TheRohitSharma** [comment]
> Hi @learnyst ,
> Thank you for reporting!
> 
> As I can see, you are using react-native v0.60.4 and react-native-code-push v5.6.0 but these are incompatible versions, you can take a look at supporting CodePush versions here: https://github.com/microsoft/react-native-code-push#supported-react-native-platforms
> 
> Not so long ago we released a new version of Code Push which supports react-native v0.60-v0.61.
> All steps for installing the latest version of the plugin are described in our documentation: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md
> 
> I'm going to close this issue for now. Please feel free to reopen if you still have this issue.

@andreidubov Is the only option to update the production version of the app to have a compatible version of CodePush?

**Comment by andreidubov** [comment]
Hey @TheRohitSharma, 
Yes, react-native v0.60+ have breaking changes that disrupt older versions of react-native-code-push. To avoid various problems you should update code-push to the latest version and update the production app accordingly.
