### ISSUE TITLE
Deprecated "rnpm" in React Native v0.60+

### ISSUE THREAD

**Issue by quanzaiyu** [microsoft/react-native-code-push#1728]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Use React Native CLI create a rn project
2. Install code-push and react-native-code-push
3. Run this project and there is a warning

### Expected Behavior
What you expected to happen?

No warning

### Actual Behavior
What actually happens?

When run rn project, there is a warning: 

```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-code-push: https://microsoft.github.io/code-push
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
```

![image](https://user-images.githubusercontent.com/13745132/69107717-4915b200-0aad-11ea-8e67-c4d45031dbae.png)

### Environment

* react-native-code-push version: latest
* react-native version: 0.61.4

(The more info the faster we will be able to address it!)

I didn't use `rnpm link` or `react-native link` to associate the react-native-code-push

**Comment by RodolfoGS** [comment]
Any update about this?

**Comment by rossenahuh** [comment]
Would there be an update in library which makes it compatible with react-native v0.60+?

**Comment by alexandergoncharov** [comment]
Hi all,

We opened PR for updating docs with setup CodePush for react-native@0.60 and above.
For more info please check here: https://github.com/microsoft/react-native-code-push/issues/1625#issuecomment-560489061

I'm going to close this issue as duplicate. Please feel free to ask any questions.

Thanks,
Alexander
