### ISSUE TITLE
build React Native android app at App center But it's Error

### ISSUE THREAD

**Issue by MahmoudAziz1996** [microsoft/react-native-code-push#1729]
##[error]Error: /Users/runner/runners/2.160.1/work/1/s/android/gradlew failed with return code: 1

**Comment by jmy10241024** [comment]
Hi, you can create app on the appcenter website, not  in terminal.Here is the site
[appcenter](https://appcenter.ms/apps)

**Comment by alexandergoncharov** [comment]
Hi @MahmoudAziz1996,
Thanks for reporting!

This repo for react-native-code-push plugin. If you have issue with AppCenter build service you should to open issue there: https://github.com/microsoft/appcenter

I'm going to close this issue for now. please feel free to reopen it if you have an yquestions.
