### ISSUE TITLE
Contradictory docs - is minimumBackgroundDuration honored on ON_NEXT_SUSPEND?

### ISSUE THREAD

**Issue by dgobaud** [microsoft/react-native-code-push#1731]
Docs first say minimumBackgroundDuration ONLY applies to ON_NEXT_RESUME

Then ON_NEXT_SUSPEND says it uses it too

1. https://github.com/microsoft/react-native-code-push/blob/master/typings/react-native-code-push.d.ts#L124

"This property ONLY applies to updates which are installed using InstallMode.ON_NEXT_RESUME..."

2. https://github.com/microsoft/react-native-code-push/blob/master/typings/react-native-code-push.d.ts#L326

"Indicates that you want to install the update when the app is in the background, * but only after it has been in the background for "minimumBackgroundDuration" seconds (0 by default),"

**Comment by afeichuanqi** [comment]
This group of codepush people are themselves pigs.
The documentation was written upside down.
There is more than just this one.
Written on github and very messy

**Comment by matthiaswenz** [comment]
@afeichuanqi I understand there might be frustration around documentation and issues with CodePush individually. However, this does not warrant and we will not tolerate any kind of abusive language targeted at anyone - be it part of the community or staff working on CodePush.

**Comment by dgobaud** [comment]
@afeichuanqi CodePush is actually surprisingly good as is App Center

**Comment by andreidubov** [comment]
Hi @dgobaud,
Sorry for the delay.

We updated this information, thanks for the comment.
