### ISSUE TITLE
Will codepush update info.plist LSApplicationQueriesSchemes?

### ISSUE THREAD

**Issue by swingywc** [microsoft/react-native-code-push#1732]
## Situation
My iOS app needs to update the `LSApplicationQueriesSchemes` dynamically in order to check if users have installed some specific apps. I have tried to update `LSApplicationQueriesSchemes` and code push a new version.

### Expected Result
The `LSApplicationQueriesSchemes` is updated. The new-added app's URLScheme can be detected.

### Current Behavior
Seem only content of the application is updated while `LSApplicationQueriesSchemes` is not updated. The new URLScheme cannot be detected.

### Question
I am not sure if this is a normal situation. 
I have tried to find solution in official document but nothing found.
Does `code push` provide a parameter/ a solution to update info.plist parameters other than the version number?

## Environment

* react-native-code-push version: ^5.3.2
* react-native version: 0.59.10
* iOS/Android/Windows version: 13.2
* Does this reproduce on a debug build or release build? debug build
* Does this reproduce on a simulator, or only on a physical device? physical device (iPhone XR)

**Comment by andreidubov** [comment]
Hi @swingywc,
Thank you for reporting!

Code Push allows you to create bundle update only for js part of your application. Any changes which touch native code (e.g. modifying your AppDelegate.m file, info.plist, adding a new plugin) cannot be distributed via CodePush, and therefore, must be updated via the appropriate store.

I'm going to close this issue for now. Please let me know if you have any other questions.
