### ISSUE TITLE
React Native 0.61.5 doesn't update App.js

### ISSUE THREAD

**Issue by RodolfoGS** [microsoft/react-native-code-push#1734]
Hi guys,
I'm trying to implemente Code Push with **React Native 0.61.5** (the latest version right now). All works good, the update is detected, but when I try to install the update I get the error `CodePush.SyncStatus.UNKNOWN_ERROR` (on **Android**, I didn't test on iOS)

I followed the steps mentioned by @yuri-kulikov in this comment https://github.com/microsoft/react-native-code-push/issues/1625#issuecomment-516784994 
Also I followed the documentation from this PR: https://github.com/MicrosoftDocs/appcenter-docs/pull/767/files?short_path=1f83030#diff-1f83030a25a6cb39626f59c398896414

Always with the same problem, the update is detected but I get `UNKNOWN_ERROR` and the js isn't updated.

I created a repository with the issue to check the bug: https://github.com/RodolfoGS/react-native-code-push-061

### Steps to Reproduce
1. `git clone https://github.com/RodolfoGS/react-native-code-push-061`
2. Change build variant to "Release"
3. Run and test application
4. `appcenter codepush release-react -a rodolfogs/React-Native-0.61` (change with your app name)
5. Tap on `Check for updates` in the app
6. Prompt to install the update will appear.
7. You will see "An unknown error occurred." message in the app.

### Expected Behavior
Update App.js

### Actual Behavior
Doesn't update App.js

### Screenshots
![image](https://user-images.githubusercontent.com/870365/69843612-f31fd780-122d-11ea-8814-7c2fcead0791.png)

### Reproducible Demo

* git clone https://github.com/RodolfoGS/react-native-code-push-061

### Environment

* react-native-code-push version: 5.7.0
* react-native version: 0.61.5
* iOS/Android/Windows version: Android 10
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? Simulator and Physical device

**Comment by RodolfoGS** [comment]
I found the solution, I was using this command:
`appcenter codepush release-react -a rodolfogs/React-Native-0.61`

But the correct command is:
`code-push release-react React-Native-0.61 android`

my fault 🤦‍♂️

**Comment by RadiRS** [comment]
> I found the solution, I was using this command:
> `appcenter codepush release-react -a rodolfogs/React-Native-0.61`
> 
> But the correct command is:
> `code-push release-react React-Native-0.61 android`
> 
> my fault 🤦‍♂️

I have same issue, but not worked for me. i tried the command but got command not found

**Comment by RodolfoGS** [comment]
> > I found the solution, I was using this command:
> > `appcenter codepush release-react -a rodolfogs/React-Native-0.61`
> > But the correct command is:
> > `code-push release-react React-Native-0.61 android`
> > my fault 🤦‍♂️
> 
> I have same issue, but not worked for me. i tried the command but got command not found

You need to install the CodePush CLI with:
`npm install -g code-push-cli`

https://github.com/microsoft/code-push/tree/master/cli#installation

**Comment by RadiRS** [comment]
Yah i forget that i'm used appcenter not code-push-cli. Thanks.
