### ISSUE TITLE
Class CodePush was not exported. Did you forget to use RCT_EXPORT_MODULE()?

### ISSUE THREAD

**Issue by sombizbuzzz** [microsoft/react-native-code-push#1737]
i am facing this issue ,

Class CodePush was not exported. Did you forget to use RCT_EXPORT_MODULE()
Class CodePush was not exported. Did you forget to use RCT_EXPORT_MODULE()

import codePush from "react-native-code-push";

[console.log ('codePush===', codePush)](url) , getting undefined , and not able open debug menu also , reload and all is stoped working

```
"react": "16.8.3",
  "react-native": "0.59.8",
 "react-native-code-push": "5.6.0",
```

pod file :

 ```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
 ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
 pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
 pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
 pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
 pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # CodePush plugin dependency
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
```

why this issue i am getting 

more details i added here 

https://stackoverflow.com/questions/59137529/react-native-code-push-not-working-in-react-native-setup

(The more info the faster we will be able to address it!)

**Comment by samie820** [comment]
@sombizbuzzz  The documentation shows 3 methods to setup code push for IOS, could you please try the [manual method](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---manual) for setting up code push?

**Comment by andreidubov** [comment]
Hi @sombizbuzzz,
Thank you for reporting!

It looks like the module was installed incorrectly, could you describe how you installed Code Push? If you have a problem with the installation, use this link https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md

Check out the `react-native` version, how can i see you use `react-native v0.59.8` that's why use this section of the document https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-for-react-native-lower-than-060-ios

**Comment by andreidubov** [comment]
I'm going to close this issue for now. Please let me know if you have any other questions.
