### ISSUE TITLE
Jitsi and CodePush not working

### ISSUE THREAD

**Issue by ljcp** [microsoft/react-native-code-push#1748]
### Steps to Reproduce
1. Add Jitsi plugin
2. Add CodePush plugin

### Expected Behavior
What you expected to happen?
Code Push works on Android 

### Actual Behavior
What actually happens?
```
12-26 15:06:01.610 27889 27991 E ReactNativeJS: TypeError: null is not an object (evaluating 'n.IsAndroid')
12-26 15:06:01.620 27889 27991 E ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
12-26 15:06:01.623 27889 27991 E ReactNativeJS: TypeError: null is not an object (evaluating 't.NativeModules.LocaleDetector.locale')
12-26 15:06:01.632 27889 27992 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
12-26 15:06:01.632 27889 27992 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'n.IsAndroid'), stack:
12-26 15:06:01.632 27889 27992 E AndroidRuntime: <unknown>@759:85
12-26 15:06:01.632 27889 27992 E AndroidRuntime: v@2:1474

```

### Reproducible Demo

Trying to add code push to github.com/RocketChat/Rocket.Chat.ReactNative

iOS works just fine , Android throws that error

### Environment

* react-native-code-push version:  6.0.0
* react-native version: 0.61.1
* iOS/Android/Windows version: Android 9
* Does this reproduce on a debug build or release build?  Release Build only
* Does this reproduce on a simulator, or only on a physical device? Both

Related issue https://github.com/jitsi/jitsi-meet/issues/4960

**Comment by caritasverein** [comment]
I doubt this is an issue with codepush. We use the SDK with react-native and without codepush and get the exact same error

**Comment by alexandergoncharov** [comment]
Hi @ljcp ,
Thanks for reporting and sorry for the delay.

Unfortunately, I can't reproduce your issue. Could you please provide an example with installed CodePush plugin and repro steps?

Thanks,
Alexander

**Comment by ljcp** [comment]
thank you for getting back on this, that approach didn't work for me, going to make a reproducible example

**Comment by alexandergoncharov** [comment]
Hi @ljcp ,
Just a friendly ping :)

**Comment by alexandergoncharov** [comment]
Hi @ljcp ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen this issue.
