### ISSUE TITLE
Is it possible to check for update before JS code starts? (in AppDelegate.m)

### ISSUE THREAD

**Issue by pie6k** [microsoft/react-native-code-push#1752]
If there is required update, I want to download it asap, and I'd like to start checking for it before JS code even starts loading.

Is it possible to initialize check inside native iOS code (AppDelegate.m)?

**Comment by alexandergoncharov** [comment]
Hi @pie6k,

Unfortunatelly, it isn't possible because checking-for-update logic places in js part. =(

I'm going to close this issue for now. Please let me know if you have any other questions.

**Comment by KingAmo** [comment]
when integrate `React Native` into existing native application，i want to check for update as soon as possible(before React Native page is initialized)，so could we move the `check for update` logic to native side ?

**Comment by KingAmo** [comment]
https://github.com/microsoft/react-native-code-push/issues/1774
