### ISSUE TITLE
docs:  Broken Links in README.md

### ISSUE THREAD

**Issue by adamdune** [microsoft/react-native-code-push#1755]
On line 255 of [README.md](https://github.com/microsoft/react-native-code-push/blob/master/README.md), the following links are broken: 

- [CLI docs](https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-react-native)
- [`release` command](https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-general)

**Comment by andreidubov** [comment]
Thanks for your reporting. We fixed it by #1756
