### ISSUE TITLE
`InstallMode.ON_NEXT_SUSPEND` not supported on iOS?

### ISSUE THREAD

**Issue by jd20** [microsoft/react-native-code-push#1762]
### Steps to Reproduce
1. Create a React Native project
2. Add `@CodePush` decorator, with `installMode: InstallMode.ON_NEXT_SUSPEND`.

### Expected Behavior
Bundle should update when app is suspended.

### Actual Behavior
Works on Android, but not on iOS, even after leaving app foregrounded for several minutes, then backgrounded for several minutes, and repeating the process several times. Force restarting the app also does not cause it to update on iOS. Other InstallMode's work as expected.

Looking at the source code, I don't even see any iOS-specific logic for this `InstallMode`, if not supported for iOS shouldn't the docs be updated to reflect that?

Version:
react-native-code-push: 6.0.0
react-native: 0.61.5
react: 16.9.0

**Comment by lbelavoir** [comment]
@jd20 Have you found any work around ?

**Comment by jd20** [comment]
I did not, I just switched to using `InstallMode.ON_NEXT_RESUME` until this issue is fixed.

**Comment by andreidubov** [comment]
Hi @jd20, @lbelavoir 
Thank you for reporting and sorry for delay!

We reproduced this problem and opened a fix PR for this. Сurrent PR: #1863.
I will let you know when this will be finally fixed.

**Comment by andreidubov** [comment]
Hi @jd20, @lbelavoir,

We released a new version for **react-native-code-push** v6.2.1 with a fix for this issue.

Please let me know if you have any questions.

**Comment by rusakovic** [comment]
@andreidubov 
Hello.
Seems `InstallMode.ON_NEXT_SUSPEND` not working again.
"react-native-code-push": "^7.0.1",
ios: 14.4
"react-native": "0.63.4",

`codePush({
      checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
      updateDialog: false,
      mandatoryInstallMode: codePush.InstallMode.IMMEDIATE,
      installMode: codePush.InstallMode.ON_NEXT_SUSPEND,
    })(App);`

It's downloading, but not installed the update
![image](https://user-images.githubusercontent.com/17801144/115574843-47fc3c00-a2c2-11eb-90b7-e88a88cd1980.png)


`InstallMode.ON_NEXT_RESTART` - working perfect.

**Comment by ioannisGiak89** [comment]
We are getting the same problem with 
```
"react-native": "0.64.0"
"react-native-code-push": "^7.0.1",
```

sync options are:
```
{
       installMode: codePush.InstallMode.ON_NEXT_SUSPEND,
       minimumBackgroundDuration: SECONDS_PER_MINUTES * 30,
}
```
running on

iOS 14.4.2

We don't use the annotation syntax
