### ISSUE TITLE
Codepush/Native update? in RN 0.61

### ISSUE THREAD

**Issue by HannanShaikYara** [microsoft/react-native-code-push#1764]
I have been using code-push in production for more than 2 years. 

### How I implemented?

1. Whenever `android` folder of my react native app was modified, I assumed there is a native change and my CI/CD tool created a native apk file. 
2. In all other cases, I generated an JS bundle and pushed via CodePush.

In the latest RN version >=0.60, we have auto-linking of native modules. Because of this, I am not able to identify if any library newly added requires a native APK to be generated or just a bundle update. 

Please provide suggestion how can this be done?

### Environment

* react-native-code-push version: 6.0.0
* react-native version: 0.61.4

**Comment by pcguru** [comment]
I lock down versions of libs in package-lock.json. If I upgrade a lib I check if it has binary code. If it does I assume the built binary will be incompatible with new js, so I bump the major version of the app and distribute new binaries.

code-pushes in this scheme are always compatible in the same major range.

**Comment by HannanShaikYara** [comment]
> I lock down versions of libs in package-lock.json. If I upgrade a lib I check if it has binary code. If it does I assume the built binary will be incompatible with new js, so I bump the major version of the app and distribute new binaries.
> 
> code-pushes in this scheme are always compatible in the same major range.

When you say `I check if it has binary code` you do this manually? or do you have a script?

**Comment by pcguru** [comment]
Manually unfortunately. Not that many libs to go through though.

**Comment by andreidubov** [comment]
Hi @HannanShaikYara,
Thank you for reporting!

Code Push allows you to create bundle update only for js part of your application. If the package you added has a native code (This happens in most cases), it cannot be distributed via CodePush.

I'm going to close this issue for now. Please let me know if you have any other questions.

**Comment by HannanShaik** [comment]
Thanks for clarification @andreidubov. 

For others who may have similar need. I did it with comparing if `ios/Podfile.lock` to decide if it is a native build to be generated or a JS build. 

I use circle CI v.2.1 and have followed documentation here https://medium.com/labs42/monorepo-with-circleci-conditional-workflows-69e65d3f1bd0.
