### ISSUE TITLE
How to release to TestFlight (staging) and separately to App Store (production)

### ISSUE THREAD

**Issue by svipas** [microsoft/react-native-code-push#1766]
Hi.

1. I'm not quite sure how to release separately to TestFlight (staging) and to App Store (production).
2. Also, do I need to install `appcenter-cli` and use it together with `react-native-code-push` or it's enough to have `react-native-code-push`.

Thank you!

**Comment by codecog** [comment]
You need to ensure you've setup multi environments. This is where you should be looking: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#android

**Comment by alexandergoncharov** [comment]
Hi @svipas ,

Yeah, you have to use `appcenter-cli` for releasing new CodePush updates.
You can make sepparate releasing by making 2 different releases with specified your target deployments(one is Staging and one more is Production).

Please check docs that was provided by @codecog and let me know if you have any questions.

@codecog , thanks for help!

**Comment by alexandergoncharov** [comment]
I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Comment by jaredswenson** [comment]
I'm having issues with too and would love some clarification on it.

**Comment by bencagri** [comment]
is there any updated documentation for this? current one goes to 404.
