### ISSUE TITLE
When you disable a build and release a new one. What happens to the pending installations? And when will those users pick up the new install?

### ISSUE THREAD

**Issue by harriot** [microsoft/react-native-code-push#1768]
When you disable a build and release a new one. What happens to the pending installations? And when will those users pick up the new install?

**Comment by lesmo** [comment]
I think that if you're using a typical setup (checking for updates on next resume, and install on next resume) your pending updates **will** be installed and the next update should be fetched and then get into a pending state. It's almost the same as just releasing a new update.

For example:
- `v1` is downloaded
- `v1` is pending activation
- `v1` is disabled
- `v2` is uploaded
- `v1` is activated (restart)
- `v1` install checks for update
- `v2` is downloaded
- `v2` is now pending update

**Comment by alexandergoncharov** [comment]
Hi @harriot ,
Thanks for reporting!

Yeah, @lesmo is right. Thanks for helping!

Please let me know if it was helpfuk or you have any questions.

**Comment by alexandergoncharov** [comment]
I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
