### ISSUE TITLE
Perform the update from native instead of JS

### ISSUE THREAD

**Issue by yvbeek** [microsoft/react-native-code-push#1774]
Would it be possible to do the bundle update entirely in the native code, instead of from the JavaScript?

Moving it over to the native code would give the following advantages:

- you can't destroy the update mechanism by uploading a bundle that doesn't work well
- you can update the bundle while the splash screen is still visible
- you are not starting the React-Native app multiple times (messes up analytics on # app starts)
- you are never showing an outdated bundle to the user (like the bundle bundled with the app)

It would probably require only a little bit of native code. So there would be little downside. And you can always use the existing JS calls to trigger an update whenever you want.

**Comment by andreidubov** [comment]
Hi @yvbeek,
Thank you for reporting!

We will discuss your suggestion with the team and will keep you updatedю

**Comment by andreidubov** [comment]
Hey @yvbeek,

After some discussion, we came to the conclusion that we currently don’t have the resources for a big project like that, but we keep the issue open to keep on gathering folks interest in it.

**Comment by kmcvey** [comment]
+1 on this topic. @doomkit @andreidubov 

We have been discussing the feasibility of sending a silent push notification to our users and updating the CodePush bundle in the background. This would ensure both standard and mandatory CodePushes could be auto-installed without the user having to open the app.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
