### ISSUE TITLE
react-native-code-push error in react-native 0.61

### ISSUE THREAD

**Issue by yINFeCTiiOnz** [microsoft/react-native-code-push#1777]
### Error
> Task :react-native-code-push:compileDebugJavaWithJavac
> Task :app:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
23 actionable tasks: 17 executed, 6 up-to-date
Note: /home/robot/Pictures/CodePushCM/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/home/robot/Pictures/CodePushCM/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:64: error: cannot find symbol
      new CodePush(getResources().getString(R.string.CodePushDeploymentKey), getApplicationContext(), BuildConfig.DEBUG)

### Problem
I'm trying to use code-push in react-native 0.61, but this is giving error when compiling for android, I'm using autolink, already tried to upgrade gradle to 6.0

### Steps to Reproduce
1. yarn add react-native-code-push
2. react-native run-android

### Environment

* react-native-code-push version: 6.0.0
* react-native version: 0.61.5
* Android/Linux mint: 19.3
* Gradle: 5.5
* NodeJS: 12.14.0
* openjdk: 11.0.6

**Comment by henrymoulton** [comment]
I had to manually link CodePush for Android, does that work for you?

**Comment by codecog** [comment]
You shouldn't need to upgrade gradle to 6.0, i believe this is and error based on another part of the setup. Have you tried doing multi environments? You also should be fine with auto-linking, that definitely works.

**Comment by yINFeCTiiOnz** [comment]
@henrymoulton I tried autolink and manual nothing works, are you managing to use code-push in RN 0.61?
@codecog Tested it in a slightly different environment, but it also gave the same error

**Comment by alexandergoncharov** [comment]
Hi @yINFeCTiiOnz,
Thanks for reporting!

Since `react-native-code-push@6.0.0+` you have to do manual steps for setup. Please check this docs: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android

Please let me know if it was helpful or you have any questions.

Thanks,
Alexander

**Comment by BharathMG-ShareChat** [comment]
I'm not able to "Import the plugin class" without linking the project in `settings.gradle`. Android project can't find references to `com.microsoft.***` without having it as a dependency in `build.gradle`. 

Is there a working example which shows autolinking react-native-code-push? Current example folders all have `settings.gradle` linking.

**Comment by alexandergoncharov** [comment]
I'm going to close this issue for now. Please feel free to reoepn it if you have any questions.

**Comment by haksatryabhaswara** [comment]
Hey @alexandergoncharov, i've the same problem, i'm followed all the step in https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android, and i can't event react-native run-android...

Here's my codes:

`settings.gradle`
![image](https://user-images.githubusercontent.com/68752883/124416803-fec86e00-dd81-11eb-8b87-86866c3e5fd9.png)

`build.gradle`
![image](https://user-images.githubusercontent.com/68752883/124416843-14d62e80-dd82-11eb-8731-c2401e82eb30.png)

`MainApplication.java`
![image](https://user-images.githubusercontent.com/68752883/124416874-24557780-dd82-11eb-943e-594a03d9bd78.png)

`String.xml`
![image](https://user-images.githubusercontent.com/68752883/124416899-31726680-dd82-11eb-84be-af29265f5494.png)

**Comment by zhonggithub** [comment]
> Hey @alexandergoncharov, i've the same problem, i'm followed all the step in https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android, and i can't event react-native run-android...
> 
> Here's my codes:
> 
> `settings.gradle` ![image](https://user-images.githubusercontent.com/68752883/124416803-fec86e00-dd81-11eb-8b87-86866c3e5fd9.png)
> 
> `build.gradle` ![image](https://user-images.githubusercontent.com/68752883/124416843-14d62e80-dd82-11eb-8731-c2401e82eb30.png)
> 
> `MainApplication.java` ![image](https://user-images.githubusercontent.com/68752883/124416874-24557780-dd82-11eb-943e-594a03d9bd78.png)
> 
> `String.xml` ![image](https://user-images.githubusercontent.com/68752883/124417008-739ba800-dd82-11eb-84b8-f74b2c1daf46.png)
> 
> **EDIT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!** i think i know where's the problem is.. in my `MainApplication.java`, i have 2 `getJSBundleFile()`, one with `@Nullable` one without.. but i'm still not pretty sure if i need to elimanate the other one..

i have the same problem ,  can you tell me how to fix this problem

**Comment by PanamaDonne** [comment]
👍

**Comment by Saad-Bashar** [comment]
The same issue, did anyone find a solution? I can not even run the app.
