### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by 164580084** [microsoft/react-native-code-push#1780]
1. After I use this command
code-push release-react android android -t \"5.0.2\" --des \"热更新(添加:确定订单备注功能)\" -m true -d Production

2. code-push-server 
 server display  "404 Not Found

![TIM图片20200203160254](https://user-images.githubusercontent.com/28852068/73635748-21db8380-469f-11ea-9bfa-79e6ee9b51cb.png)
"
 
* react-native-code-push version: 5.6.1
* react-native version: 0.59.9
* iOS/Android/Windows version: all

**Comment by pfleidi** [comment]
Code=push-server is a third party component that is not supported by CodePush. The only official server we support is https://appcenter.ms.

I'm sorry to say that we can't provide support for third party backends.

**Comment by 164580084** [comment]
> Code=push-server is a third party component that is not supported by CodePush. The only official server we support is https://appcenter.ms.
> 
> 代码推送服务器是 CodePush 不支持的第三方组件。 我们唯一支持的官方服务器是 google https://appcenter.ms。
> 
> I'm sorry to say that we can't provide support for third party backends.
> 
> 很抱歉，我们不能为第三方后台提供支持。

But I've been using it for more than a month, and suddenly it doesn't work.
