### ISSUE TITLE
An update is available, but it is being ignored due to having been previously rolled back. - Android

### ISSUE THREAD

**Issue by hadare1** [microsoft/react-native-code-push#1785]
HI, 
I'm trying to integrate code-push in my app. everything works on iOS but on android I can't get it to work.. I get this error : 

    [CodePush] An update is available, but it is being ignored due to having been previously rolled 
    back.
    logging.js:3 [CodePush] Sync already in progress.
    logging.js:3 [CodePush] App is up to date.

this is my MainApplication.java file : 

`package app;

import android.app.Application;
import com.facebook.react.ReactApplication;
import me.jhen.devsettings.DevSettingsPackage;
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import com.swmansion.gesturehandler.react.RNGestureHandlerPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import java.util.Arrays;
import java.util.List;
import com.krazylabs.OpenAppSettingsPackage;
import com.chirag.RNMail.*;
import com.airbnb.android.react.maps.MapsPackage;
import com.microsoft.codepush.react.CodePush;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
     protected String getJSBundleFile() {
        return CodePush.getJSBundleFile();
    }
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new CodePush(
              "_w6JPjQWU8CZkH8EP-z1tn-KxXEE8Dk3s_MdZF",
              getApplicationContext(),
              BuildConfig.DEBUG,
              R.string.CodePushPublicKey
               ),
          new MainReactPackage(),
          new GeolocationPackage(),
          BugsnagReactNative.getPackage(),
          new RNFirebasePackage(),
          new RNGestureHandlerPackage(),
          new RNFirebaseAuthPackage(),
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);

  }
}`

this is my strings.xml file : 
`<resources>
    <string name="app_name">Jesta</string>
    <string moduleConfig="true" name="CodePushDeploymentKey">{key}</string>
    <string name="CodePushPublicKey"> {publicKey} </string>
</resources>`

### Steps to Reproduce
1.npm i react-native-code-push
2. react-native run-android

### Expected Behavior
App will update according to code push distribution

### Environment

* react-native-code-push version: 6.0.0
* react-native version: 0.61.5
* Does this reproduce on a debug build or release build? -  both
* Does this reproduce on a simulator, or only on a physical device? - physical device

**Comment by MaffooBristol** [comment]
Might be a dupe of https://github.com/Microsoft/react-native-code-push/issues/524

What comes up for `code-push deployment history <appName> <deploymentName>`?

Might be useful to provide your root component React code too, to check it's definitely calling `notifyAppReady()` properly

**Comment by hadare1** [comment]
Turned out I had another issue, I was able to solve this.

**Comment by Kunal-Airtel2022** [comment]
This issue still persists in 7.0.4. Once an update rolled back due to some reason. Now it is not installing on the device even when we increase the targeted binary version of the app and push a fresh bundle to codepush.
