### ISSUE TITLE
Crash if change npm package version

### ISSUE THREAD

**Issue by Ankarrr** [microsoft/react-native-code-push#1790]
### Steps to Reproduce
1. Change npm package version
2. Push to app center
3. Sync and install

### Expected Behavior
Install successfully and will not rollback

### Actual Behavior
Crash and rollback when open app again

### Environment

* react-native-code-push version: ^5.5.2
* react-native version: 0.59.3 
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? devices

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @Ankarrr ,
Thanks for reporting!

I tried to reprodice your issue but attempts are unsuccessful. I changed version in `package.json`, made CodePush release and successfully got update.
Could you pelase provide test project with reproducing issue?

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
