### ISSUE TITLE
iOS Build Error - RN 0.61 - Code Push - ^6.1.0

### ISSUE THREAD

**Issue by naveenvignesh5** [microsoft/react-native-code-push#1791]
Getting the following error.

![Screenshot 2020-02-13 at 11 50 37 AM](https://user-images.githubusercontent.com/19146999/74407144-61505f80-4e57-11ea-83b9-f52318b62ce2.png)

Steps I did:

1. Added the CodePush.xcodeproj to `Libraries`.
2. Imported `libz.tbd` and `libCodePush.a` to Build Phases - Link Binary with libraries.
3. Updated the `AppDelegate.m` with the following code

```cpp
#import "AppDelegate.h"

#import <Firebase.h>
#import <CodePush/CodePush.h>

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <ReactNativeNavigation/ReactNativeNavigation.h>
#import <React/RCTLinkingManager.h>


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    if ([FIRApp defaultApp] == nil) {
      [FIRApp configure];
    }
  
    NSURL *jsCodeLocation;

    #ifdef DEBUG
         jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
    #else
        jsCodeLocation = [CodePush bundleURL];
    #endif

    [ReactNativeNavigation bootstrap:jsCodeLocation launchOptions:launchOptions];

    return YES;
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}

@end
```

**P.S:**
* Ignore the firebase library code. Also, mention anything regarding it if it is responsible for deterring code push functionality.

* Code push library didn't auto-link as mentioned in docs. So I had to do manual import even though RN version is greater than 0.60.

* Issue is in code push library it is not able to refer to `React/RCTBridge.h` header. Please suggest any solutions.
  * Tried updating search-header path didn't work. I also tried to remove manual codepush.xcodeproj reference but throws the error that `Codepush/Codepush.h` file not found.

Any, more clarifications please tell me I will include.

**Comment by andreidubov** [comment]
Hi @naveenvignesh5 ,
Thank you for reporting!

As I can see, you are using react-native v0.61 and react-native-code-push v6.1.0 but at the same time your installation steps apply (1-2) to the old react-native-code-push version. 

All steps for installing the latest version of the plugin are described in our documentation: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-ios

I'm going to close this issue for now. Please feel free to reopen it if you still have this issue after installation update.
