### ISSUE TITLE
Implicit rollback after upgrading react-native-code-push; getUpdateMetadata displays wrong data

### ISSUE THREAD

**Issue by MiloszFilimowski** [microsoft/react-native-code-push#1792]
# Steps to Reproduce
1. Upgrade react-native-codepush from 2.0.6 to 3.0.1 and update app version for e.g. 1.0 -> 1.1 
2. Deploy new codepush version for 1.1 2-3 times (important step -  you should have 1.0v1 1.1v2, 1.1v3 etc)
3. Release new 1.1 version to App Store
4. Download upgrade from AppStore / override currently installed app.

### Expected Behavior
`getUpdateMetadata.appVersion` and `getUpdateMetadata.label` should return correct version => 1.0v3

### Actual Behavior
`getUpdateMetadata.appVersion` returns old version (1.0v1) however the app was updated, meaning, I can see changes from 1.1, but `appVersion` is 1.0 and the app was somehow rollbacked to 1.1v2.

![IMG_6659](https://user-images.githubusercontent.com/12846004/74664922-f5476180-519e-11ea-8383-ba1314d82ddc.PNG)
![IMG_6679](https://user-images.githubusercontent.com/12846004/74664929-f6788e80-519e-11ea-82ed-963210006ba1.PNG)

At the first image at first row you can see version bundled with the app - hardcoded. 
Below it, is version taken from `getUpdateMetadata`. 

Second image shows what I can see if I uninstall the app and download it again from app store. 

### Environment

* react-native-code-push version: 2.0.6 / 3.0.1
* react-native version: 0.61.5
* iOS/Android/Windows version: 13.2.2
* Does this reproduce on a debug build or release build? **Release**
* Does this reproduce on a simulator, or only on a physical device? **Both**

**Comment by alexandergoncharov** [comment]
Hi @MiloszFilimowski ,
Thanks for reporting!

I see that the main reason here that your update was rollbacked. Could you please share your logs during update for this version? I think we can find some information about reasons for that rollback.

**Comment by rmartinez-paack** [comment]
Hi @alexandergoncharov, 

I'm facing a similar issue... All the Android updates are rollbacked, but the iOS not... 

How or where can I get those logs during updating the version?

Thanks.

**Comment by alexandergoncharov** [comment]
Hi @rmartinez-paack ,

You can use Android Studio for getting logs. It is `logcat` tab. Or use cli command `adb logcat`. There should be logs with `[CodePush]` tag.

**Comment by alexandergoncharov** [comment]
Hi @rmartinez-paack , @MiloszFilimowski ,

Just friendly ping :)

**Comment by rmartinez-paack** [comment]
Hi @alexandergoncharov,

What I could see is this crash report:

```
Fatal Exception: com.facebook.react.common.JavascriptException: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), stack:
exports@8:286
value@27:3403
<unknown>@27:840
value@27:2798
value@27:812
value@-1

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:241)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:919)
```

We are using Code Push with react-native-navigation.

**Comment by alexandergoncharov** [comment]
Yeah. It is interesting.

Could you please provide some demo app with reproducing issue and reprosteps? I would like to reproduce and investigate it.

**Comment by qwertypomy** [comment]
Same issue: 
After upgrade to `react-native 0.61.5 -> 0.62.2` and `react-native-code-push 6.0.0 -> 6.2.0`  3 months ago I see high increase of rollbacks on Android (from 0-30 -> to 700-1000) when on iOS number of rollbacks stays stable at 0 even tho number of downloads is higher on iOS.

So my point is this issue is quite painful and related to 6.2.* version Android only.
Can't reproduce it myself now, but I'll try to find a way.

**Comment by alexandergoncharov** [comment]
Hi all,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
