### ISSUE TITLE
HIPAA Compliance

### ISSUE THREAD

**Issue by kceb** [microsoft/react-native-code-push#1797]
I was wondering if I could get clarification on what data code-push collects.

I'm developing a HIPAA compliant application and we are hoping we could restrict any IP logging addresses/device metadata to Microsoft.

**Comment by gwmccull** [comment]
this would be helpful for me also

**Comment by hsavit1** [comment]
Any updates on this?

**Comment by andreidubov** [comment]
Hi @kceb, sorry for the late response.

As App Center is not a medical organization, and doesn't collect or distribute patient data, it's unlikely HIPAA is directly applicable to us. I investigated your request and found out that we collect the **IP addresses** of requests coming to the service, so I think it makes app non compliant.

I'm going to close this issue for now please feel free to reopen it if you have any other questions.
