### ISSUE TITLE
Why rollback on IPhone11pro Simulator

### ISSUE THREAD

**Issue by devsoonote** [microsoft/react-native-code-push#1804]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Why rollback just Iphone11pro and IPhone11proMax Simulator?(Not other Simulator)

### Expected Behavior
What you expected to happen?
I know rollback reason. And I wonder that Is this my mistake or bug?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS

[CodePush] An update is available, but it is being ignored due to having been previously rolled back.
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: "5.7.0"
* react-native version: "0.60.0"
* iOS/Android/Windows version: IOS: "13.3"
* Does this reproduce on a debug build or release build? maybe both
* Does this reproduce on a simulator, or only on a physical device?
simulator
(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @devsoonote ,
Thanks for reporting!

There are can be a lot of reasons for rollbacking. It means that during installing updates it occurs some issue. You can find it in the logs. Could you please share your logs during installing update?
Also, it will be useful if you provide some demo app for reproducing issue and reprosteps? I would like to reproduce and investigate it.
