### ISSUE TITLE
Starting app for the first time triggers a codepush update even though the binary version bundle is the same as the released codepush bundle

### ISSUE THREAD

**Issue by mole440** [microsoft/react-native-code-push#1805]
Is the hash of the react native package included in the binary used when checking for codepush packages? Codepush reports that an update is available even when the same RN code is included in the native build as what has been released via codepush.

### Steps to Reproduce
1. Create a native Release binary (apk or iOS)
2. Code push release the same react native bundle
3. Start the app

### Expected Behavior
Code push should report "up to date" as the bundle that was included in the native binary build is the same bundle as what has been code pushed out.

### Actual Behavior
Code push reports that an update is available.

### Environment

* react-native-code-push version: 6.0.0
* react-native version: 0.61.5
* iOS/Android/Windows version: Any iOS and Android version
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by alexandergoncharov** [comment]
Hi @mole440 ,
Thanks for reporting!

Yeah, It is the known case. Unfortunately, we can't compare the native bundle and CodePush bundle. And CodePush update will be installed always for first checking updates even if there are no diffs.

I hope it was helpful. Please let me know if it was helpful or you have more questions.
