### ISSUE TITLE
project can't build after upgrade IDE XCode from 10 to 11:

### ISSUE THREAD

**Issue by zhsunsea** [microsoft/react-native-code-push#1807]
project can't build after upgrade IDE XCode from 10 to 11:

### Steps to Reproduce
1. Successful developed a project  with XCode 10 in Nov. last year with react-native-code-push
2. Last week create a new project based on 1's project, but can't build  
3. Errors shows in attached image file
![截屏2020-03-09下午5 59 22](https://user-images.githubusercontent.com/2910633/76274133-b5b1f800-62ba-11ea-92db-23165d41a2f2.png)

Noticed some parameters diffs from XCode 10 to 11, and configuration of code-push are different.

In article https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#multi-deployment-testing said:
"Go to Build Location > Per-configuration Build Products Path > Staging and change Staging value from $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME) to $(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)"

#
![image](https://user-images.githubusercontent.com/2910633/76274150-c06c8d00-62ba-11ea-92c4-a8bffefc44d7.png)
## Expected Behavior

Hope a new guidebook for code-push configure in XCode 11

  

### Environment

* react-native-code-push version: 2.1.9
* react-native version: 0.55.4
* iOS version: 13.3
* Does this reproduce on a debug build or release build? No
### Steps to Reproduce
1. Successful developed a project  with XCode 10 in Nov. last year with react-native-code-push
2. Last week create a new project based on 1's project, but can't build  
3. Errors shows in attached image file

Noticed some parameters diffs from XCode 10 to 11, and configuration of code-push are different.

In article https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#multi-deployment-testing said:
"Go to Build Location > Per-configuration Build Products Path > Staging and change Staging value from $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME) to $(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)"

### Expected Behavior

Hope a new guidebook for code-push configure in XCode 11

```
  



### Environment

* react-native-code-push version: 2.1.9
* react-native version: 0.55.4
* iOS version: 13.3
* Does this reproduce on a debug build or release build? No

**Comment by alexandergoncharov** [comment]
Hi @zhsunsea ,
Thanks for reporting!

I see that you use old versions of `react-native-code-push`. Possibly there are some issues with compatibility. Could you please test latest version of `react-native-code-push` and let me know if it fixes your issue?

**Comment by flogspace** [comment]
@alexandergoncharov 
On Xcode 11.5 there's no "Per-configuration Build Products Path", at least not by default.
![Screen Shot 2020-06-22 at 4 33 36 AM](https://user-images.githubusercontent.com/1832016/85260971-e79e3300-b441-11ea-96d2-7eb79f820564.png)

**Comment by alexandergoncharov** [comment]
@flogspace , looks like here is your solution. Could you please try to do this steps and let me know if was helpful to you?
And also we will update our docs.

**Comment by Krasavinigor** [comment]
Hi there! 
@flogspace, @zhsunsea 
I created PR (https://github.com/microsoft/react-native-code-push/pull/1901) for updating information on Multi-Deployment Testing. Take a look if you have time.

**Comment by alexandergoncharov** [comment]
Hi @flogspace , @zhsunsea ,

We merged https://github.com/microsoft/react-native-code-push/pull/1901 and also updated Microsoft docs here: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-deployment

So, I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
