### ISSUE TITLE
code push doesn't sync with android 4.4.4

### ISSUE THREAD

**Issue by mohammad-amin-hesam** [microsoft/react-native-code-push#1814]
code push working with most devices that i did test them.
but i did test it with sumsong galexsy j1 and it doesn't sync with my release.

how i can solve this problem ?

android version: 4.4.4

**Comment by alexandergoncharov** [comment]
Hi @mohammad-amin-hesam ,
Thanks for reporting!

Could you please provide your logs during update?
Also, it would be useful if you provide demo app with reproducing issue and reprosteps. I would like to reproduce and investigate it.

**Comment by alexandergoncharov** [comment]
Hi @mohammad-amin-hesam ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions or provide a demo app.
