### ISSUE TITLE
Codepush bundle is downloaded and installed but old bundle is still loaded [iOS]

### ISSUE THREAD

**Issue by smaradona** [microsoft/react-native-code-push#1816]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Released a QA build through TestFlight for iOS and TestFairy for Android
2. Released a codepush update targeting that specific version of the app to both platforms (Android and iOS). The update is just a UI change.
3. Update is downloaded and installed on both platforms, but the new bundle is only loaded on Android. On iOS, the old bundle is still loaded (even though I can see on AppCenter that the update was successfully downloaded and installed and also can see that on some event tracking we're doing through mixpanel, so technically the update seems to be downloaded and installed without issues)

### Expected Behavior
What you expected to happen?
I'd expect for the iOS app to load the downloaded and installed codepush update instead of the old one.

### Environment

* react-native-code-push version: 5.5.3
* react-native version: 0.59.9
* iOS/Android/Windows version: iOS 12.3.1
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Physical device

(The more info the faster we will be able to address it!)

**Comment by dmydry** [comment]
We have almost the same issue on both platforms. Trying to get updates with codepush.sync() method, they are all installed successfully, but after app restarts it launches with an initial bundle and codePush.checkForUpdate() method returns an update object again (instead of null) with failedInstall: true.

**Comment by smaradona** [comment]
Closed it cause I found that, in our case, the codepush library wasn't correctly setup on iOS. Thanks!

**Comment by dmydry** [comment]
@smaradona could you please share what was a mistake about with some short example? It can help probably

**Comment by smaradona** [comment]
Hey @dmydry! Sure, not too sure if it will help you, but the issue for us was that we updated our RN version to 0.59.9 and during that migration we didn't update `AppDelegate.m` accordingly, so the code there was following the setup steps for `React Native 0.58 and below` instead of following the steps described for `React Native 0.59 - 0.59.10` in the [docs for iOS setup](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md). Hope you find a solution for your problem!

**Comment by pragneshpj** [comment]
> We have almost the same issue on both platforms. Trying to get updates with `codepush.sync()` method.
> 
> What we did
> 
> 1. Call the `codepush.sync()` a few components deeper from our app root.
> 2. It is a simple FC with a `useEffect` where we check for available updates.
> 3. After the app is just started it behave as expected - a new update is installed successfully. Changes made in this update were all there.
> 4. After the app restarts it suddenly launches with an initial js bundle.
> 5. `codePush.checkForUpdate()` method returns a previous update object again (instead of null) with `failedInstall: true`.


@dmydry how you solve this issue? because i'm getting same issue in ios
