### ISSUE TITLE
Whitescreen after new app bundle is installed

### ISSUE THREAD

**Issue by helciofranco** [microsoft/react-native-code-push#1818]
Whenever there's a mandatory code push update, it restarts the application and white screen flashes for a few seconds (while app is restarting).

Is there a way to show a custom screen instead of that white screen?

Obs.: I always publish updates using mandatory flag and my check frequency is ON_APP_RESUME).

Thanks!

**Comment by dmydry** [comment]
The only way I figure out so far is to install this update on a next restart. At least it does that without any blinking. 
`mandatoryInstallMode: codePush.InstallMode.ON_NEXT_RESTART`

**Comment by helciofranco** [comment]
> The only way I figure out so far is to install this update on a next restart. At least it does that without any blinking.
> `mandatoryInstallMode: codePush.InstallMode.ON_NEXT_RESTART`

Actually, I really want to do mandatory updates.

I did a `<Modal />` which is displayed during the update downloading / installation, I think it's the best workaround to give to the user a feedback of what is going one.

Since doesn't exist a solution for it, I will close it and keep my workaround here.

**Comment by raldred** [comment]
@helciofranco any chance of sharing your workaround in a gist or something?

**Comment by yjb94** [comment]
my solution for this was displaying splash screen until you get codepush update meta data.(`getUpdateMetadata`)
