### ISSUE TITLE
 error when trying to run the appcenter codepush release-react command

### ISSUE THREAD

**Issue by leonardo1294** [microsoft/react-native-code-push#1819]
### Steps to Reproduce
1. using "react-native": "0.61.5"
2. usong "react-native-code-push": "^6.1.1",
3. following all the steps in the documentation

### Actual Behavior
What actually happens?
```
 node node_modules\.bin\react-native bundle --assets-dest C:\Users\Leonardo\AppData\Local\Temp\code-push2020219-13780-10hnpfi.czeo\CodePush --bundle-output C:\Users\Leonardo\AppData\Local\Temp\code-push2020219-13780-10hnpfi.czeo\CodePush\index.android.bundle --dev false --entry-file index.js --platform android
C:\Users\Leonardo\guiam
aisgv\node_modules\.bin\react-native:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Error: Failed to release a CodePush update.
```

**Comment by Adr1ann** [comment]
There's someone who solved that?

**Comment by leonardo1294** [comment]
@Adr1ann, apparently there is no one interested in the problem, but it has not yet been solved, I have already tested it on other machines and the problem persists

**Comment by alz10** [comment]
same error here :(

**Comment by 404-html** [comment]
Possible duplicate with https://github.com/microsoft/react-native-code-push/issues/1813.

**Comment by ZodiacGemini** [comment]
I am using appcenter code push in a CI/CD pipeline, and it works when using ubuntu but not when using windows. Getting the same exception as you guys when I'm trying to run it locally.

**Comment by azilberbaum** [comment]
Getting the same error - anyone figure this out yet?

**Comment by mhmdiqbal** [comment]
https://github.com/microsoft/appcenter-cli/issues/759#issuecomment-601322412 maybe can help

**Comment by azilberbaum** [comment]
I rolled back t version  2.3.3

`npm install appcenter@2.3.3 -g`

And it is working again

**Comment by leonardo1294** [comment]
installing version 2.3.3 solves the problem

**Comment by bry-guy** [comment]
This appears to be a duplicate of https://github.com/microsoft/react-native-code-push/issues/1813. Please refer there for on-going investigations into this issue with App Center CLI v3.0.0.

**Comment by ajiehatajie** [comment]
using code-push i was succesfully
code-push release-react your-app android -d Development

**Comment by zenkriztao** [comment]
back version appcenter cli

**Comment by phuvinhng** [comment]
I backed to 2.3.3 but still error? How can I resolve it?
