### ISSUE TITLE
got UNKNOWN_ERROR  only on Android release

### ISSUE THREAD

**Issue by ceressteven** [microsoft/react-native-code-push#1827]
I can't see any error messages from the log, but it works  on IOS and debug  successful

and  can get the update and install it, but it only got UNKNOWN_ERROR on Android release  it seems that an error occurred before the update was requested

**Comment by Adr1ann** [comment]
same here

**Comment by alexandergoncharov** [comment]
Hi @ceressteven and @Adr1ann ,
Thanks for reporting!

Unfortunately it is hard to say what is going on. Could you please provide logs during update?
Also, it will be useful if you provide demo app with reproducing issue and reprosteps. I would like to reproduce and investigate it.

**Comment by alexandergoncharov** [comment]
Hi @Adr1ann , @ceressteven 

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions or provide logs and demo app.
