### ISSUE TITLE
Could not resolve project :react-native-code-push. RN 0.62

### ISSUE THREAD

**Issue by ajiehatajie** [microsoft/react-native-code-push#1831]
Could not determine the dependencies of task ':app:compileDevDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:devDebugCompileClasspath'.
   > Could not resolve project :react-native-code-push.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-code-push:
          - None of the consumable configurations have attributes

### Environment

* react-native-code-push version: ^6.1.1
* react-native version:0.62
* iOS/Android/Windows version: 9
* Does this reproduce on a debug build or release build? debug build
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

**Comment by PaitoAnderson** [comment]
Do you have these additional changes in your `android/settings.gradle`? Just replace `include ':app'` with those two lines.

https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android

**Comment by dntzee** [comment]
Same issues, follow the steps to install the documentation, and the same is true。


react-native-code-push version: ^6.2.0
react-native version:0.62
iOS/Android/Windows version: 9
Does this reproduce on a debug build or release build? debug build
Does this reproduce on a simulator, or only on a physical device? physical device

**Comment by tiendn** [comment]
Same too 
```
react-native-code-push version: ^6.2.0
react-native version:0.62
iOS/Android/Windows version: 9
Does this reproduce on a debug build or release build? debug build
Does this reproduce on a simulator, or only on a physical device? physical device
```
build in AppCenter failed too.

**Comment by tiendn** [comment]
Here is an new fresh project. I tried to build with code-push, but it always failed.
https://github.com/tiendn/covid

**Comment by wencongsheng** [comment]
filepath android/settings.gradle
like this: 
`rootProject.name = 'your_project_name'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')`

build success

**Comment by tiendn** [comment]
That's amazing. You save my life @wencongsheng 💯 
Thank you very much!

**Comment by ashlyWeiting** [comment]
Use
react-native: 0.62.0
react-native-code-push ^6.2.0
still not working 

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-code-push.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-code-push:
          - None of the consumable configurations have attributes.
```

**Comment by rewieer** [comment]
Thanks @wencongsheng 
I ended up doing something like this :
```
rootProject.name = 'myproject'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

include ':react-native-webview'
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')

// Other dependencies //

include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
```

**Comment by trickyc0d3r** [comment]
i've fix this issue by only move code-push line into the bottom of all lines

**Comment by iosLongFeng** [comment]
I find fix the react-native to  "0.61.5" is ok.

**Comment by lucasfronza** [comment]
Yep, the order was the problem for me too.

**Comment by chenyu1990** [comment]
> i've fix this issue by only move code-push line into the bottom of all lines

u save my life, thanks.

**Comment by andreidubov** [comment]
Hi @ajiehatajie,
Thanks for reporting!

All steps for installing the latest version of the plugin are described in our documentation: https://github.com/microsoft/react-native-code-push/blob/master/docs/api-android.md

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Comment by pasine** [comment]
@andreidubov I think there is a bit of confusion with the documentation.
I found
1. [Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started#android-setup)
2. [Your link above](https://github.com/microsoft/react-native-code-push/blob/master/docs/api-android.md)
3. [Another setup in your docs](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android).

I guess the most recent and correct one is number 3.

**Comment by andreidubov** [comment]
@pasine, yes you are right, I mistakenly sent the wrong link.

link to the setup documentation for android: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#android-setup

As for [Microsoft Docs](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started#android-setup), we will update this soon, thanks.

**Comment by TonnyRogers** [comment]
> i've fix this issue by only move code-push line into the bottom of all lines

Oh man... so magic! IT WORKS

**Comment by WGwangguan** [comment]
> filepath android/settings.gradle
> like this:
> `rootProject.name = 'your_project_name'
> apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
> 
> include ':app', ':react-native-code-push'
> 
> project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')`
> 
> build success

work for me!
Thx!!!

**Comment by DavideValdo** [comment]
Shouldn't autolinking take care of this?

**Comment by chellongCoder** [comment]
> i've fix this issue by only move code-push line into the bottom of all lines

Magic, thanks to save a day for me

**Comment by nyowusu** [comment]
thank you 

> filepath android/settings.gradle
> like this:
> `rootProject.name = 'your_project_name'
> apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
> 
> include ':app', ':react-native-code-push'
> 
> project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')`
> 
> build success

Thank you!

**Comment by cesarAugusto1994** [comment]
> filepath android/settings.gradle
> like this:
> `rootProject.name = 'your_project_name'
> apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
> 
> include ':app', ':react-native-code-push'
> 
> project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')`
> 
> build success

Thanx

**Comment by gildniy** [comment]
> i've fix this issue by only move code-push line into the bottom of all lines

I confirm this worked for me too!

**Comment by lavisar** [comment]
> Do you have these additional changes in your `android/settings.gradle`? Just replace `include ':app'` with those two lines.
> 
> https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md#plugin-installation-and-configuration-for-react-native-060-version-and-above-android

I have same problem with react native 0.75.X and this solved my problem. 
Thank you so much!
