### ISSUE TITLE
Upgrade xcode version to latest, to tackle security issue in xmlbuilder 8.2.2

### ISSUE THREAD

**Issue by KSR001** [microsoft/react-native-code-push#1832]
Latest version of react-native-code-push still depends on xcode 1.0.0, which in the dependency hierarchy depends on xmlbuilder 8.2.2 which is vulnerable to a denial of service due to a regular expression issue.

### Expected Behavior
No known issues. Upgrading to xcode version latest, will resolve this.

### Actual Behavior
![image](https://user-images.githubusercontent.com/26419238/78336920-c7cb4180-75ad-11ea-9954-b9a43f75fcb1.png)

### Environment

* react-native-code-push version: 5.7.0 (But latest still depends on old xcode)
* react-native version: 0.61.2

**Comment by alexandergoncharov** [comment]
Hi @KSR001 ,
Thanks for reporting!

It is a good catch!
We will update all our dependencies including `xcode`. We will keep you posted.

**Comment by andreidubov** [comment]
Hi @

As I can see, you are using react-native-code-push 5.7.0. Therefore, you have this vulnerability. In the latest version, this is fixed. Moreover, [here](https://github.com/microsoft/react-native-code-push/pull/1880) is the PR in which we updated the current dependencies.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.
