### ISSUE TITLE
[IOS] Report status failed and 404: No deployment found

### ISSUE THREAD

**Issue by rhayart** [microsoft/react-native-code-push#1835]
Hi,

I'm facing for the first time an unknow issue after using CodePush on a lot of apps.
How to know what is the exact problem and the meaning of the error "404: No deployment found" ? (see "Actual Behavior")

### Expected Behavior
What you expected to happen?
The iOS release APP should download and install the last update.

### Actual Behavior
What actually happens?

On android everything works fine.
**EDIT :** On iOS it works on staging but not on release.
On iOS CodePush log error and does not download the last update.

I double checked my CodePush Keys and they are fine.
I also double checked the AppCenter-Config.plist key and it's ok.
I'm using multi-deployment settings (with User Defined and Info.plist keys settings).
I'm experiencing this issue for several days.

Error logs : 
```
  CodePush status : CHECKING FOR UPDATE ... (0)
  Reporting binary update (1.0.1)
  CodePush status : UNKNOWN ERROR (-1)
  404: No deployment found.
  Report status failed: {"appVersion":"1.0.1"}
```

CodePush options : 
```
let options = {
  installMode: CodePush.InstallMode.IMMEDIATE,
  checkFrequency: CodePush.CheckFrequency.MANUAL,
  updateDialog: false,
};
```

AppDelegate.m : 
```
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

@import Firebase;
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <AppCenterReactNativeShared/AppCenterReactNativeShared.h>
#import <AppCenterReactNative.h>
#import <AppCenterReactNativeAnalytics.h>
#import <AppCenterReactNativeCrashes.h>

#import <CodePush/CodePush.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }

  [AppCenterReactNativeCrashes registerWithAutomaticProcessing];  // Initialize AppCenter crashes
  [AppCenterReactNativeAnalytics registerWithInitiallyEnabled:true];  // Initialize AppCenter analytics
  [AppCenterReactNative register];  // Initialize AppCenter

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                      moduleName:@"xxxxx"
                                               initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [CodePush bundleURL];
#endif
}

@end
```

### Environment

* react-native-code-push version: 6.1.0
* react-native version: 0.61.5
* iOS version: 13.3.1
* Does this reproduce on a debug build or release build? On both

**EDIT :** 
I have created a new Deployment Type on Appcenter named "Release", changed the keys on the iOS App and everything start to work. It seems to be a problem of the Production Deployment Type on Appcenter, maybe at the creation of it. It could be worth to invastigate on it.

**Comment by alexstanbury** [comment]
I am also seeing this issue but using 'Staging' environment on iOS (Android fine) which was set up according to code-push docs.

**Comment by alexandergoncharov** [comment]
Hi @alexstanbury , @rhayart ,
Thanks for reporting!

The differences between `Staging` and `Production` in just name. You can create new deployments with any names.

It looks like that server hasn't known your deployment key. It means that possibly there is some typo in your deployment key or your removed your deployment.
Also, I see that your issues was resolved and I'm going to close this issue for now.
Please feel free to reopen it if you have any questions.
