### ISSUE TITLE
Release-react command doesn't invoke "converting JS bundle to byte code via hermes.."

### ISSUE THREAD

**Issue by hengki01** [microsoft/react-native-code-push#1836]
Recently, I try to migrate from JSC to hermes-engine for my RN app. Released build (using hermes) has been successfully created. 
<img width="269" alt="Screen Shot 2020-04-07 at 17 58 25" src="https://user-images.githubusercontent.com/48044171/78661841-a6de5580-78f9-11ea-8912-130c4e3a7e11.png">
(./android/app/build.gradle)

I expect for releasing hermes-generated bytecode instead of JS bundle, but release command from appcenter cli didn't invoke JS bundle to bytecode step.

> appcenter codepush release-react -a hengki/testingAndroidExplorer -d Staging -t '*'

### Expected Behavior
'Converting JS Bundle to byte code via Hermes, running command:' invoked after writing bundle output finished. (based on [microsoft/appcenter-cli#627](https://github.com/microsoft/appcenter-cli/pull/627))

<img width="640" alt="Screen Shot 2020-04-07 at 17 55 01" src="https://user-images.githubusercontent.com/48044171/78661461-05570400-78f9-11ea-86f9-b92e0cc0cd41.png">

### Actual Behavior
Releasing update contents to CodePush, instead of 'Converting JS Bundle to byte code via Hermes..."

<img width="887" alt="Screen Shot 2020-04-07 at 17 50 08" src="https://user-images.githubusercontent.com/48044171/78661189-8792f880-78f8-11ea-8966-14c907c2d225.png">

### Environment
* react-native-code-push version: 6.2.0
* react-native version: 0.61.5
* appcenter version: 2.4.0
* OS: macOS Catalina 10.15.4

**Comment by naum43312016** [comment]
Hi, @hengki01 we have the same problem, did you find a solution for this?

**Comment by hengki01** [comment]
@naum43312016
It's been a long time ago, actually I don't really remember how I could solve the problem.
As far as I can recall, I did ./gradlew clean and restart my machine.

React native code push library definitely works with Hermes, since I heavily use it in my RN project up until now.

**Comment by naum43312016** [comment]
@hengki01 thanks

**Comment by MouliMohanN** [comment]
Hey @naum43312016 ,

You need to make sure **enableHermes: true** to be the in the exact format.

If you have the flag in different format like - 
1. enableHermes:true
2. enableHermes   :   true
- It won't work.

I've explained the issue and fix in details here - https://medium.com/@moulimohann/reactnative-app-becomes-slow-after-codepush-how-did-i-fix-951f913a5084

**Comment by engeslamadell** [comment]
So for me, I'm using NX for our monorepo setup and I had this issue for days and I decided to look into the appcenter-cli code.

and at `appcenter-cli/dist/commands/codepush/lib/react-native-utils.js` i found this function 
```sh
function getHermesOSExe() {
  const react63orAbove =
    semver_1.compare(
      semver_1.coerce(getReactNativeVersion()).version,
      "0.63.0",
    ) !== -1;
  const hermesExecutableName = react63orAbove ? "hermesc" : "hermes";
  switch (process.platform) {
    case "win32":
      return hermesExecutableName + ".exe";
    default:
      return hermesExecutableName;
  }
}
```
which compares the react native version against `0.63.0` because of a change in the hermes command name

and in the monorepo setup, the appcenter-cli was looking for the react-native version inside the package.json for the project and it was like the following
```sh
"dependencies": {
    "react-native": "*",
    ....
}
```

and the reason of this is, in monorepos you have a global package.json file and all projects can share the packages in there
but with react native you need to have a sub package.json with the native libraries you use in your app so auto-linking can as expected.

and changing my package.json and include the react-native version, everything related to appcenter and codepush start to work as expected

```sh
"dependencies": {
    "react-native": "0.64.0",
    ....
}
```

**Comment by burakkgunduzz** [comment]
@engeslamadell solution also worked for me (I am also using nx and in a monorepo setup). However, my colleagues with exactly the same setup , repo and versions (appcenter-cli etc) does not have to specify RN version in package.json and their codepush works out of the box. What could be the factor here I wonder?

**Comment by engeslamadell** [comment]
@burakkgunduzz not sure exactly, but I think they somehow configured their workspace to look in the root package.json, not the sub one, that way appcenter knows the version and can make decisions.
