### ISSUE TITLE
[Question] self hosting assets 

### ISSUE THREAD

**Issue by samithaf** [microsoft/react-native-code-push#1840]
Hello All,
First of all thank you for creating this awesome library! We would like to use code push to release patches in our React Native App and seems like a perfect candidate for it. 
I am working for a financial organisation and due to the governing rules we can only use cloud services hosted within Australia. So I am keen to know is there a way to self host all the assets instead of using MS servers?

**Comment by chris1299** [comment]
@samithaf you can try the https://github.com/lisong/code-push-server

**Comment by samithaf** [comment]
Thank you @chris1299 for the suggestion and I actually had a closer look at this library as well. But it seems like there are lot of open issues and I am bit nervous to use it.

**Comment by chris1299** [comment]
@samithaf It does has some issues. My previous project successfully set up my own hot update service. unfortunately something went wrong recently, and I am trying to solve it

**Comment by samithaf** [comment]
Looks like we can configure code push server URL. But unable to find how to deploy the server or even to have a custom static assets location. https://github.com/microsoft/react-native-code-push/pull/1658/files

**Comment by samithaf** [comment]
Anyone who would like to self-host assets, give a try to expo OTA solution. Our App is not based on Expo but still able to wire it up.

https://docs.expo.io/versions/latest/guides/configuring-ota-updates/
