### ISSUE TITLE
Dependency resolution errors

### ISSUE THREAD

**Issue by chezhe** [microsoft/react-native-code-push#1844]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. build

### Expected Behavior
build successfully

### Actual Behavior
What actually happens?
```
> Task :app:checkDirectDebugDuplicateClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDirectDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class net.jcip.annotations.GuardedBy found in modules jcip-annotations-1.0-1.jar (com.github.stephenc.jcip:jcip-annotations:1.0-1) and jcip-annotations-1.0.jar (net.jcip:jcip-annotations:1.0)
  Duplicate class net.jcip.annotations.Immutable found in modules jcip-annotations-1.0-1.jar (com.github.stephenc.jcip:jcip-annotations:1.0-1) and jcip-annotations-1.0.jar (net.jcip:jcip-annotations:1.0)
  Duplicate class net.jcip.annotations.NotThreadSafe found in modules jcip-annotations-1.0-1.jar (com.github.stephenc.jcip:jcip-annotations:1.0-1) and jcip-annotations-1.0.jar (net.jcip:jcip-annotations:1.0)
  Duplicate class net.jcip.annotations.ThreadSafe found in modules jcip-annotations-1.0-1.jar (com.github.stephenc.jcip:jcip-annotations:1.0-1) and jcip-annotations-1.0.jar (net.jcip:jcip-annotations:1.0)
```
I checked the dependency, only react-native-code-push depends both `stephenc.jcip` and `net.jcip`

### Environment

* react-native-code-push version: 6.2.0
* react-native version: 0.62.1
* iOS/Android/Windows version: Android 8.0
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by chezhe** [comment]
Fixed by exclude group

**Comment by minhchienwikipedia** [comment]
@chezhe can you show me how to resolve this issue?

**Comment by sahilleap** [comment]
@chezhe Can you explain how to resolve this using `exclude group`?

**Comment by chezhe** [comment]
> @chezhe Can you explain how to resolve this using `exclude group`?

Sorry, it's long time ago, I don't work for that project anymore, and I can't remember what it is now. I guess you may use `exclude group` in gradle file to exclude duplicated dependencies, I don't know the details.

**Comment by chenweigh** [comment]
@sahilleap how to fix ?
