### ISSUE TITLE
No documented method of using Code Push with functional root component

### ISSUE THREAD

**Issue by crystalneth** [microsoft/react-native-code-push#1846]
React has been moving away from stateful components and new apps are likely not to be built with them, having dependencies on hooks instead.

Please release (or document) how to use Code Push with a functional root component.

**Comment by crystalneth** [comment]
I got around this by creating a component wrapper:

```
export class ComponentApp extends Component {
  // codePushDownloadDidProgress(progress) {
  //   console.log(progress.receivedBytes + " of " + progress.totalBytes + " received.");
  // }

  render() {
    return <App/>
  }
}

export const CodePushApp = codePush(codePushOptions)(ComponentApp)

export default CodePushApp
```

**Comment by robertvorthman** [comment]
I just pass the functional component into the Codepush wrapper.

```js
function App() {
  return (
      <StoreProvider store={store}>
        <Theme />
      </StoreProvider>
  );
}

export default codePush(App);

**Comment by alexandergoncharov** [comment]
Hi @crystalneth and @robertvorthman ,
Thanks for reporting!

It is a good catch! We will update the documentation with some examples. We will keep you posted.

**Comment by Krasavinigor** [comment]
Hi everyone!
I merged PR: https://github.com/microsoft/react-native-code-push/pull/1877 with examples of using functional components and closed this issue. 
Please let me know if you have any questions.

**Comment by langerkirill** [comment]
Can we add examples of how can we use codepush hooks in functional components?

**Comment by md-cooper** [comment]
> Can we add examples of how can we use codepush hooks in functional components?

Hooks are called when you use codepush's own wrapper `codepush(options)(App).` For functional, you don't need this wrapper and can just use codepush.sync() yourself - first arg is options and next 2 provide the hooks in the form of callbacks
