### ISSUE TITLE
An update is available, but it is being ignored due to having been previousl 

### ISSUE THREAD

**Issue by TianShun2018** [microsoft/react-native-code-push#1847]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.CodePush 加载完最新资源包，还没有更新完成的时候，就立即退出 rn 页面。在没有再次进入有 codePush 相关代码的 rn 界面的情况下，就杀死应用退出程序。当你再次进入应用，打开 rn 容器时，资源包会自动回滚。自动回滚完成后，再也不会去更新服务端当前最新的资源包了
2. 
3.

### Expected Behavior
What you expected to happen?
下次打开app，仍然会继续更新最新的资源包
### Actual Behavior
What actually happens?
自动回滚完成后，再也不会去更新服务端当前最新的资源包了
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @TianShun2018 ,
Thanks for reporting!

Unfortunately, I don't know Chinese, and I'm afraid to make some mistakes in the translation. Could you please change your description of English?
I'm going to close this issue for now. Please feel free to reopen it if you have any questions or when you update the description.

**Comment by ShaoGongBra** [comment]
你这个问题怎么解决的，我也遇到结束进程就回滚代码

**Comment by baixjian** [comment]
> 你这个问题怎么解决的，我也遇到结束进程就回滚代码

+1

**Comment by newyoung21** [comment]
@ShaoGongBra @baixjian 
请问你们找到解决方法了吗？

**Comment by newyoung21** [comment]
@TianShun2018  有解决方案吗？我也遇到会滚了，下次进来就不会触发更新了

**Comment by ShaoGongBra** [comment]
升级到新版本之后好像没遇到过
