### ISSUE TITLE
xcode 11 library not found for  XXX

### ISSUE THREAD

**Issue by chrislincp** [microsoft/react-native-code-push#1848]
Xcode:  11.3.1
react-native: 0.59.10
react-native-code-push：5.6.0
Error when archive in Staging: 

```
ld: library not found for -lBVLinearGradient
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Release works

##  Target Build Settings

![1587714686651](https://user-images.githubusercontent.com/22828515/80188546-eb7d2700-8643-11ea-8c20-329d068a272b.jpg)
![1587714702736](https://user-images.githubusercontent.com/22828515/80188566-f33ccb80-8643-11ea-9762-a8873ab8685e.jpg)

**Comment by guilhermecomum** [comment]
I'm having this problem too =\

**Comment by alexandergoncharov** [comment]
Hi @chrislincp and @guilhermecomum ,
Thanks for reporting!

Unfortunately I can't reproduce it. Could you please provide some demo app with reproducing issue and reprosteps? I would like to reproduce and investigate it.

**Comment by alexandergoncharov** [comment]
Hi @chrislincp , @guilhermecomum ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions or provide demo app.
