### ISSUE TITLE
targetBinaryVersion 10036.0.0 not support 

### ISSUE THREAD

**Issue by cq0702** [microsoft/react-native-code-push#1849]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.code-push release-react iosapp ios -m --t 10036.0.0 -d Staging --des 04283iios
2. Releasing update contents to CodePush:Upload progress:[==================================================] 100% 0.0s
3.[Error]  targetBinaryVersion ~10036.0.0 not support.

### Expected Behavior
What you expected to happen?
update success
### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
I
### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:6.2.0
* react-native version:0.61.5
* iOS/Android/Windows version:13.3
* Does this reproduce on a debug build or release build?yes
* Does this reproduce on a simulator, or only on a physical device?yes

(The more info the faster we will be able to address it!)
When I set version to 2.0.0. It works. But when I set version to 10036.0.0.It will return the error: [Error]  targetBinaryVersion ~10036.0.0 not support after uploadling progress to 100%; Actually,I have to set the vetsion to 10036.0.0.  Is there any way that I can upload success using 10036.0.0.Thanks!

**Comment by alexandergoncharov** [comment]
Hi @cq0702 ,
Thanks for reporting!

Our recommendation is using `appcenter` cli instead of `code-push` cli. I just tested it with `appcenter` cli and successfully made a new release with the `10036.0.0` target version.

So, I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
