### ISSUE TITLE
installMode with ON_NEXT_SUSPEND trigger a rollback

### ISSUE THREAD

**Issue by lyqeyes** [microsoft/react-native-code-push#1854]
#1394   2020.05.08.  I met the same issue.

## My Environment: 
iOS(the platform I am using) version:  13.3 
react-native-code-push version: 6.1.1
React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 24.75 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
* Does this reproduce on a debug build or release build?  ==> debug
* Does this reproduce on a simulator, or only on a physical device?  ==>  only tried on physical device 

## Description
when the config is
`
    checkFrequency: CodePush.CheckFrequency.ON_APP_START,
    installMode: CodePush.InstallMode.ON_NEXT_RESUME,
    minimumBackgroundDuration: 10,
`
everything is OK. 

when the config is 
`
    checkFrequency: CodePush.CheckFrequency.ON_APP_START,
    installMode: CodePush.InstallMode.ON_NEXT_SUSPEND,
    minimumBackgroundDuration: 10,
`
then: release a new version --> restart app to download the new package --> press home key and wait 10 seconds  --> reopen the app --> trigger failure and **rollback** to the previous version. 

Meanwhile , a report request was sent:
path: /v0.1/public/codepush/report_status/deploy

request body: 
{
	"app_version": "1.0.0",
	"deployment_key": "xxx",
	"client_unique_id": "xxx",
	"label": "v8",
	"status": "DeploymentFailed",
	"previous_deployment_key": "xxx"
}

PS: I tried this issue in two projects.

**Comment by andreidubov** [comment]
Hi @lyqeyes,
Thank you for reporting!

Yes, we know about this problem and now are working on it, current PR: #1863 
I will keep you posted and let you know how this will be fixed.

**Comment by andreidubov** [comment]
Hi @lyqeyes,

We released a new version for **react-native-code-push** v6.2.1 with a fix for this issue.

Please let me know if you have any questions.
