### ISSUE TITLE
errors hapends when upload .ipa to Distribute-Release

### ISSUE THREAD

**Issue by zhsunsea** [microsoft/react-native-code-push#1855]
errors happends when upload .ipa to Distribute-Release:

### Steps to Reproduce
1. In chrome web-browser, goto url https://appcenter.ms/ and find my app, goto Distribute-Release page
2. when up load a Release .ipa file to the server , error happends 
3. error info shows "errors happends when upload .ipa to Distribute-Release" (image behind)

I had checked code-push key in info.plist file of the app and it's just as same as the one in appcenter.ms.
 
![error-01](https://user-images.githubusercontent.com/2910633/81466315-316cea00-9203-11ea-8ffa-dc30b2acb1c6.jpg)

Please help me ASAP.

**Comment by alexandergoncharov** [comment]
Hi @zhsunsea ,
Thanks for reporting!

Unfortunately, it is a repo for `react-native-code-push` project. You can report your issue to `appcenter` repo: https://github.com/Microsoft/appcenter
In that repo, you will get an answer faster.

I'm going to close this issue. Please feel free to reopen it if you have any questions.
