### ISSUE TITLE
React Native 62.2 - Cannot sync.

### ISSUE THREAD

**Issue by Huseyinnurbaki** [microsoft/react-native-code-push#1856]
Hello Team,

Here's the problem, 

### Steps 
1  I deployed app on simulator in release mode.
2. I updated the javascript code, successfully released it by using  code-push cli.
3. I list the deployments from terminal, I confirm deployment.
4. I try to sync and expect to be able to sync. 

### Expected Behavior
App should have recognized the update.

### Actual Behavior
I get 404 every time.

### Details

I can successfully deploy bundles. 
**code-push release-react client-ios  ios  -d Production -m **
I can list what i deployed. 
I override deployment key inside javascript with the wrong deployment key. (I want to deploy for production, and I'm overriding the correct key with staging key ) then I cannot deploy. This is expected behaviour. When I revert it, I can deploy perfectly. Correct me If I'm wrong, This means ota server is working. 

The problem starts when I want to sync or check, I get 404 every time. 

- My OTA server is running locally (electrode) and allows http connections. 
- Ios application also allows http connections.
- I am using Mariadb (standard db scheme)
- App is in release mode (AppDelegate set correctly, there is the repository down the page)
-  I am working in non-secure mode, I've done everything what had to be done to work in http mode.  Totally sticked with the latest code-push and ota document.
- I used github authentication.
- I also tried updating info.plist server url with my local ip, and used physical device to see if it will work, it didn't work.
- I added console.logs inside react-native-code-push module. 

This is the output when I want to sync or do anything inside the application.

`
2020-05-11 05:18:23.358 [info][tid:com.facebook.react.JavaScript] ' config-->', { deploymentKey: 'cccccccccccc',
  serverUrl: 'http://localhost:9001',
  clientUniqueId: 'B8FDB62E-DCD7-4CB1-A429-E535C8972DF5',
  appVersion: '1.2',
  buildVersion: '1',
  packageHash: 'ba7d72cce27798c2324f39b5678cff4601813a6d63f18b242d0a73814d7c6e61' }`

So configurations are recognized by react-native-code-push
There are actual keys instead of cccccs
`
2020-05-11 05:18:06.757 [info][tid:com.facebook.react.JavaScript] [CodePush] Report status failed: {"appVersion":"1.2"}
2020-05-11 05:18:06.776 [info][tid:com.facebook.react.JavaScript] [CodePush] 404: 
2020-05-11 05:18:06.779 [info][tid:com.facebook.react.JavaScript] [CodePush] Reporting binary update (1.2)
2020-05-11 05:18:06.792 [info][tid:com.facebook.react.JavaScript] 'response -->', { type: 'default',
  status: 404,
  ok: false,
  statusText: undefined,
  headers: 
   { map: 
      { 'content-length': '0',
        connection: 'keep-alive',
        'cache-control': 'no-cache',
        date: 'Mon, 11 May 2020 02:18:06 GMT',
        'content-type': 'text/plain' } },
  url: 'http://localhost:9001/v0.1/public/codepush/report_status/deploy',
  _bodyInit: 
   { _data: 
      { size: 0,
        offset: 0,
        blobId: '145B570A-8A50-4A2E-A231-BEE209F69E5F',
        type: 'text/plain',
        name: 'deploy.txt',
        __collector: {} } },
  _bodyBlob: 
   { _data: 
      { size: 0,
        offset: 0,
        blobId: '145B570A-8A50-4A2E-A231-BEE209F69E5F',
        type: 'text/plain',
        name: 'deploy.txt',
        __collector: {} } } }
`

`'response -->', { type: 'default',
  status: 404,
  ok: false,
  statusText: undefined,
  headers: 
   { map: 
      { 'content-length': '0',
        connection: 'keep-alive',
        'cache-control': 'no-cache',
        date: 'Mon, 11 May 2020 02:18:23 GMT',
        'content-type': 'text/plain' } },
  url: 'http://localhost:9001/v0.1/public/codepush/update_check?deployment_key=cccccccccccc&app_version=1.2&package_hash=ba7d72cce27798c2324f39b5678cff4601813a6d63f18b242d0a73814d7c6e61&client_unique_id=B8FDB62E-DCD7-4CB1-A429-E535C8972DF5',
  _bodyInit: 
   { _data: 
      { size: 0,
        offset: 0,
        blobId: '1FD7FF82-F74B-4CD4-B18D-BB7214A4D79C',
        type: 'text/plain',
        name: 'update_check.txt',
        __collector: {} } },
  _bodyBlob: 
   { _data: 
      { size: 0,
        offset: 0,
        blobId: '1FD7FF82-F74B-4CD4-B18D-BB7214A4D79C',
        type: 'text/plain',
        name: 'update_check.txt',
        __collector: {} } } }
2020-05-11 05:18:23.371 [info][tid:com.facebook.react.JavaScript] [CodePush] 404: 
`

My Info.plist

![Screen Shot 2020-05-11 at 5 08 03 AM](https://user-images.githubusercontent.com/22790534/81518035-726d1780-9345-11ea-887e-d9057ec987b6.png)

### Reproducible Demo

https://github.com/Huseyinnurbaki/ota-server
React Native app is under Client.

Bring database up from under the electrode-ota-mariadb-schema directory with following command.
**docker-compose up -d**

Then from ota directory, under config/production.json
clientId and clientSecret must be filled according to the following document,
http://www.electrode.io/docs/what_is_electrode.html

### Environment

* react-native-code-push version: 6.2.0
* react-native version: 62.2
* iOS - version: ios: 13.3
* Does this reproduce on a debug build or release build? Yes
* Does this reproduce on a simulator, or only on a physical device? both

I can provide more details if needed. 

Thanks in advance.

**Comment by alexandergoncharov** [comment]
Hi @Huseyinnurbaki ,
Thanks for reporting!

Unfortunately, I have to say that we are not supporting a non-official CodePush server.
But by your logs, it looks like that there is some connection issue between device and server.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

Thanks,
Alexander
