### ISSUE TITLE
[CodePush] An update is available, but it is being ignored due to having been previously rolled back

### ISSUE THREAD

**Issue by gursesl** [microsoft/react-native-code-push#1859]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. appcenter codepush release-react -a xxxx/android-app -d Production -m --description "Version bump" -t "*"
2. [CodePush] An update is available, but it is being ignored due to having been previously rolled back

### Expected Behavior
Working on iOS, failing on Android

### Actual Behavior
What actually happens?
```
[CodePush] An update is available, but it is being ignored due to having been previously rolled back
```
App update does not take place in Android.

### Reproducible Demo

* appcenter codepush release-react -a xxxx/android-app -d Production -m --description "Version bump" -t "*"

### Environment

* react-native-code-push version: 6.2.0
* react-native version: 0.62.2
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by gursesl** [comment]
Jumped the gun on this. The issue was caused by a wrong key.

**Comment by yangwei2011** [comment]
but some devices of Android are worded, a littile devices of Android are not worded,so strange
