### ISSUE TITLE
add codepush to exist contain library android app error

### ISSUE THREAD

**Issue by papastar** [microsoft/react-native-code-push#1861]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.add my android exist app to reactnative
my android app contain two library(library1 appId:io.rong.imlib,library2 appId:com.papa.lib) and a main module(appid:com.aaa.bbb)
2. add codepush from doc [codepush api_android ](https://github.com/microsoft/react-native-code-push/blob/master/docs/api-android.md)
3.add string item `<string name="CodePushDeploymentKey" moduleConfig="true">xxx</string>` in my main module strings.xml,(i also try set resvalue in app build.gradle)
then get error like this  in PackageList.java
`      new CodePush(getResources().getString(io.rong.imlib.R.string.CodePushDeploymentKey), getApplicationContext(), io.rong.imlib.BuildConfig.DEBUG),
`

### Expected Behavior
in PackageList.java it should be 
`      new CodePush(getResources().getString(com.aaa.bbb.R.string.CodePushDeploymentKey), getApplicationContext(), com.aaa.bbb.BuildConfig.DEBUG),
`

### Actual Behavior
in PackageList.java
`      new CodePush(getResources().getString(io.rong.imlib.R.string.CodePushDeploymentKey), getApplicationContext(), io.rong.imlib.BuildConfig.DEBUG),
**io.rong.imlib** is my app  libaray appid,it doesnot have  string  'CodePushDeploymentKey',
i have set 'CodePushDeploymentKey' in my app main module  strings.xml
how can I  fix it ? 

otherwise
   I want disable code push autolink ,i have set below code in react-native.config.js
`module.exports = {
  dependencies: {
    'react-native-code-push': {
      platforms: {
        android: null, // disable Android platform, other platforms will still autolink if provided
      },
    },
  },
};`   
but after i do that,in my android app setting.gradle,i cannot include android module like this
`include ':react-native-code-push'`
so  I cannnot import com.microsoft.codepush.react.CodePush and connot add Codepush
in my ReactNativeHost 

how can I  do to  disable autolink codepush, i want set CodePushServerUrl and CodePushDeploymentKey by java code ,not  in strings.xml

thank you very much 

### Reproducible Demo

I am sorry ,it my company project ,in cannot show it

### Environment

* react-native-code-push version:6.2.0
* react-native version:0.62.2
* iOS/Android/Windows version:mac os
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? simulator & physical

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @papastar ,
Thanks for reporting!

I see that you have a complicated project with several modules. It is hard to fully understand what is going on.
If it will be helpful, you can set deployment key and server url with CodePush constructor. Here are docs for that: https://github.com/microsoft/react-native-code-push/blob/master/docs/api-android.md#codepush .

Please let me know if it was helpful or you have other questions.

**Comment by alexandergoncharov** [comment]
Hi @papastar ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

**Comment by rajbopched11** [comment]
@alexandergoncharov-zz hey this is happening for me too.
Code push is incorrectly importing deployment key from library module. It should import it from main app module.

I've defined the deployment key in main app module's string.xml. However in  `PackageList`, new  CodePush() is trying to import key's from library module's string.xml. Since the key's are not defined in library module, the build fails.

Please let me know if you need more details..
