### ISSUE TITLE
Android: App crashing on initial launch, afterwards it does not crash and gets code pushed without problems

### ISSUE THREAD

**Issue by afilp** [microsoft/react-native-code-push#1864]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Install Android app to device (having the code push code inside)
2. Run it
3. It crashes
4. Re-run it
5. All is OK, it does not crash and it also gets code pushed. From then on, it never crashes.

### Expected Behavior
What you expected to happen?
Not to crash on initial launch

### Actual Behavior
What actually happens?
App crashes (on 1st launch only)

### Environment
We use 'react-navigation' and https://github.com/zoontek/react-native-bootsplash

* react-native-code-push version: 
"^6.2.0"
* react-native version: 
"^0.61.5"
* iOS/Android/Windows version: 
Android 10
* Does this reproduce on a debug build or release build? 
Release
* Does this reproduce on a simulator, or only on a physical device?
Physical device

(The more info the faster we will be able to address it!)

**Comment by afilp** [comment]
I am also using the "react-native-firebase". Maybe this is related to it (messaging?). I am investigating this now.

**Comment by ali-io** [comment]
i'm also having the same issue on IOS

**Comment by ali-io** [comment]
@afilp any luck?

**Comment by ali-io** [comment]
ok the result of three hours of searching and debugging it appears to be a firebase messaging issue. update it to the latest version and you should be good.

check: https://github.com/invertase/react-native-firebase/issues/3556

**Comment by afilp** [comment]
@ali-io 
Indeed! I disabled firebase messaging and now it does not crash. 
Sorry to have bothered you, I thought it was code-push. 

Thanks!

**Comment by alexandergoncharov** [comment]
Hi @afilp  and @ali-io ,
Thanks for reporting!

I see that you already found the reason for the issue and it isn't related to CodePush.
So, I'm going to close this issue for now. Please feel free to reopen it if you have any questions.
