### ISSUE TITLE
import com.microsoft.codepush.react.CodePush; error

### ISSUE THREAD

**Issue by MianMUAmer** [microsoft/react-native-code-push#1869]
Followed the tutorial and upon building it gives this error.

React Native version: "react-native": "0.57.0",

> Task :app:generateBundledResourcesHashRelease
c9673498d318c4eb4764468a8ba7dd7c38bdcdfa156d11ca5e6435755e990d08

> Task :app:compileReleaseJavaWithJavac
C:\Users\umair.amer\Desktop\Proj\WMS_ECommerce\RTWMS.OperasyonApp\android\app\src\main\java\com\operasyonapp\MainActivity.java:4: error: package com.microsoft.codepush.react does not exist
import com.microsoft.codepush.react.CodePush;
                                   ^
C:\Users\umair.amer\Desktop\Proj\WMS_ECommerce\RTWMS.OperasyonApp\android\app\src\main\java\com\operasyonapp\MainActivity.java:5: error: package com.microsoft.codepush.react does not exist
import com.microsoft.codepush.react.CodePush;
                                   ^
C:\Users\umair.amer\Desktop\Proj\WMS_ECommerce\RTWMS.OperasyonApp\android\app\src\main\java\com\operasyonapp\MainActivity.java:6: error: package com.microsoft.codepush.react does not exist
import com.microsoft.codepush.react.CodePush;
                                   ^
C:\Users\umair.amer\Desktop\Proj\WMS_ECommerce\RTWMS.OperasyonApp\android\app\src\main\java\com\operasyonapp\MainApplication.java:4: error: package com.microsoft.codepush.react does not exist
import com.microsoft.codepush.react.CodePush;
                                   ^
C:\Users\umair.amer\Desktop\Proj\WMS_ECommerce\RTWMS.OperasyonApp\android\app\src\main\java\com\operasyonapp\MainApplication.java:29: error: cannot find symbol
            return CodePush.getJSBundleFile();
                   ^
  symbol: variable CodePush
C:\Users\umair.amer\Desktop\Proj\WMS_ECommerce\RTWMS.OperasyonApp\android\app\src\main\java\com\operasyonapp\MainApplication.java:42: error: cannot find symbol
          new CodePush("BoZSX8VjQgVQClSL7H1W-k3dx9AA_ikTOFjZ_", MainApplication.this, BuildConfig.DEBUG),
              ^
  symbol: class CodePush
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
107 actionable tasks: 5 executed, 102 up-to-date
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! operasyonapp@0.0.1 build-android-prod: `cd android && SET ENVFILE=.env.production && gradlew assembleRelease && cd ..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the operasyonapp@0.0.1 build-android-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\umair.amer\AppData\Roaming\npm-cache\_logs\2020-06-03T10_33_12_762Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! operasyonapp@0.0.1 build: `npm run bundle-android-prod && npm run build-android-prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the operasyonapp@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\umair.amer\AppData\Roaming\npm-cache\_logs\2020-06-03T10_33_12_855Z-debug.log

**Comment by alexandergoncharov** [comment]
Hi @MianMUAmer ,
Thanks for reporting!

Looks like CodePush hasn't added to the project. Could you please ensure that you did all the installation steps correctly?
If it was not helpful, could you please provide a test project with reproducing issue and reprosteps because I would like to reproduce and investigate it?

Thanks,
Alexander

**Comment by ganjargal** [comment]
I'm using NX (monorepo). This problem is on my case not added "react-native-code-push": "*" in package.json of my mobile-app. I manually added to this line and problem solved.
