### ISSUE TITLE
Consider making setDeploymentKey() static

### ISSUE THREAD

**Issue by Gentlee** [microsoft/react-native-code-push#1871]
### Expected Behavior
I should be able to set deployment key programatically (same as for ios), and you should never set private static vars in public constructors.

### Actual Behavior
Android code is terrible and it doesn't allow to change deployment key programmatically as it allows for ios. It sets static variable in constructor 🤦 , and this static singleton is private 🤦  while constructor is public 🤦 .

```
private static CodePush mCurrentInstance;

public CodePush(String deploymentKey, Context context, boolean isDebugMode) {
    ...
    mCurrentInstance = this;
    ...
}

public void setDeploymentKey(String deploymentKey) {
    mDeploymentKey = deploymentKey;
}
```

**Comment by alexandergoncharov** [comment]
Hi @Gentlee ,
Thanks for reporting!

Could you please provide more detailes info on why you can't set `deploymentKey` for Android? We have `setDeploymentKey` method and also it is possible to put it in the constructor.

**Comment by andreidubov** [comment]
Since there is no answer and we cannot reproduce it I’m going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Comment by Gentlee** [comment]
Again, `setDeploymentKey` is public, but it is `instance` method, and singleton instance is `private`. So i cannot access this method.

And constructor is public, but sets private singleton. Do i need to exlain why this is a very bad code that can break everything?

**Comment by Gentlee** [comment]
If you still don't understand the problem, just tell me what line of code i need to write to set deployment key from my MainApplication.

**Comment by ruslan-bikkinin** [comment]
Hi @Gentlee and sorry for the late response. Yes, you are right, the way `setDeploymentKey` implemented right now for Android API is a bit confusing and should be re-implemented the correct way to consolidate iOS Api. We added this to our backlog list and will consider picking it up in order of priorities.

As for now workaround for the issue would be getting CodePush instance manually and then call aforementioned method, i.e. in your case you can try to add this code snippet to `MainApplication`:

```java
    List<ReactPackage> packages = getReactNativeHost().getReactInstanceManager().getPackages();
    CodePush codePushInstance = (CodePush) packages.stream()
            .filter(p -> p instanceof CodePush)
            .findFirst()
            .get();
    codePushInstance.setDeploymentKey("DIFFERENT_DEPLOYMENT_KEY");
```
