### ISSUE TITLE
Does automatic rollback really work?

### ISSUE THREAD

**Issue by itenl** [microsoft/react-native-code-push#1874]
### Steps to Reproduce
1. Publish an APK containing RN Bundlejs
2. Use command code-push release-react ... something lable v1
3. Open APK upgrade to label v1, restart-app upgrade was rolled back(In some phones)
4. Added a line of code on the prev-code [console.log(123123)], some unimportant code.
5. And try code-push release-react .. to label v2, and open APK upgrade to label v2, The rollback did unhappen.

### Expected Behavior
hope did't roolback

### Actual Behavior
upgrade fail to v1 and automatic roolback

### Reproducible Demo
-

### Environment

* react-native-code-push version:[6.2.0]
* react-native version:[0.62.2]
* iOS/Android/Windows version:[Android]
* Does this reproduce on a debug build or release build? [release]
* Does this reproduce on a simulator, or only on a physical device?[physical device]

For the code changes from v1 to v2, I only added a Console.log, and then hot update on the same device. Why did the v1 version fail, but v2 succeeded? Obviously the program did not crash, because v1 and v2 The code is almost the same; I want to try to expose the number of rollbacks in the internal API, and add a switch for automatic rollback, In the branch after Fork, ask for your help. This automatic rollback has greatly affected us.

and CodePush.notifyAppReady() method has been added in componentDidMount in index.js of the root directory.

**Comment by itenl** [comment]
![image](https://user-images.githubusercontent.com/16585374/84111986-826a3b00-aa5a-11ea-8c50-ba983aedbecd.png)

![image](https://user-images.githubusercontent.com/16585374/84112707-dc1f3500-aa5b-11ea-88ba-e82f3e9e2465.png)

When I use CodePush to check for updates, the version is v3. When the v4 version is available and available, the returned PackageSize is only 198B??? and I tried to download it with download_url, it cannot be opened.

**Comment by andreidubov** [comment]
Hi @itenl 
Thanks for reporting!

I tried to reproduce your case but did not get any problem with the rollback. 
Unfortunately, I'm not sure how your application is configured with code-push. Could you provide more information on how you installed and configured code-push in your application or provide test project with this issue?

I checked 3 options for setup code push project:

1) Wrap the root component with the codePush higher-order component:

```js
import codePush from "react-native-code-push";

class MyApp extends Component {
}

MyApp = codePush(MyApp);
```

2) Use CodePush.sync():

```js
import codePush from "react-native-code-push";

let codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };

class MyApp extends Component {
    onButtonPress() {
        codePush.sync({
            updateDialog: true,
            installMode: codePush.InstallMode.IMMEDIATE
        });
    }

    render() {
        return (
            <View>
                <TouchableOpacity onPress={this.onButtonPress}>
                    <Text>Check for updates</Text>
                </TouchableOpacity>
            </View> 
        )
    }
}

MyApp = codePush(codePushOptions)(MyApp);
```

3) Manual installation using notifyAppReady:

```js
import codePush from "react-native-code-push";

let codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };

class MyApp extends Component {
    componentDidMount() {
        CodePush.notifyAppReady();
    }

    async onButtonPress() {
      const update = await CodePush.checkForUpdate();
       if (!update) {
            alert('The app is up to date!');
       } else {
         const res = await update.download();
         await res.install();
         CodePush.restartApp();
    }

    render() {
        return (
            <View>
                <TouchableOpacity onPress={this.onButtonPress}>
                    <Text>Check for updates</Text>
                </TouchableOpacity>
            </View> 
        )
    }
}

MyApp = codePush(codePushOptions)(MyApp);
```

Each of these options worked as expected and there wasn’t any unexpected rollback.

**Comment by itenl** [comment]
@andreidubov As you said, there wasn’t any unexpected rollback. But, does not mean that it does not exist.
I can be sure that the crash did not happen, the code was not a problem, but the rollback happened and there is a 3% probability that a rollback will occur.
So, I need your assistance. I will try to modify the source code to delete the rollback to ensure that the business is up to date, even if there is a crash. Please give me a hint, which file and which line can be modified? thx guys.

![image](https://user-images.githubusercontent.com/16585374/84406318-f57ed780-ac3b-11ea-93f7-8685f448d009.png)

**Comment by andreidubov** [comment]
@itenl If I understood correctly, you want to block rollback's logic in your application.
 I want to warn you that rejection of rollback's logic may lead to the fact that your customers may receive a broken update. 

If you want to do this, here are some places where this logic is used:

- You can explicitly set `updateIsLoading` to false [here](https://github.com/microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java#L305). This will lead to disabling rollback and in case of receiving a broken update the user will have a broken version of the application.

Before: 

 ```java
boolean updateIsLoading = pendingUpdate.getBoolean(CodePushConstants.PENDING_UPDATE_IS_LOADING_KEY);
```
 After:

```java
boolean updateIsLoading = false;
```

- Also, you can prevent ignoring the update [here](https://github.com/microsoft/react-native-code-push/blob/master/CodePush.js#L430). In any case, this will lead to the download of the update, even if the rollback is registered, but in general, it will not protect you from rollbacks.

Before: 

 ```js
const updateShouldBeIgnored = await shouldUpdateBeIgnored(remotePackage, syncOptions);
```
 After:

```js
 const updateShouldBeIgnored = false;
```

Based on the information that you provided, the probable cause of rollbacks is an error in the generated bundle or its incorrect generation (198B is very strange). Also, the reason could be the fact that some user devices could not start this update, which was the reason for the rollback (OS incompatibility, etc.). I want to continue to investigate this issue, can you provide some more information:

- Could you tell me does this error occur with each of your updates or any specific?
- Can you provide information with the size of your releases?
- Are you using appcenter-cli or code-push cli?
- How long have you encountered this problem for the first time?

Thank you very much for your involvement.

P.S. If I do not understand your problem correctly, let me know abought it.

**Comment by itenl** [comment]
@andreidubov OKay, I will conduct [Fork](https://www.npmjs.com/package/@itenl/react-native-code-push) and secondary development in the near future, btw. Compared to Rollback, we hope to be able to accurately push the latest business. Even if it crashes, we can also report the crashed logs for analysis and resolution.
Thank you for your reminder, I will control whether the rollback is allowed and whether the rollback has occurred through the parameters, and extract it into the API.

- Could you tell me does this error occur with each of your updates or any specific?
   `No, it only happened once.`

- Can you provide information with the size of your releases?
   `Sometimes 1.4MB or sometimes 400KB maybe delta update? Is my guess right?`

- Are you using appcenter-cli or code-push cli?
   `Yes, code-push cli`

- How long have you encountered this problem for the first time?
   `Just once, A few days ago.`

- How did you set up code-push in your project?
   `Use code-push release-react in Jenkins.`

**Comment by andreidubov** [comment]
@itenl Thank you very much for your answers.

I wanted to inform you that a 3% rollback is normal value and is not a code-push bug. The reason for rollbacks may be third-party problems, such as the phone might turn off 
during an update or the user performed incorrect actions, etc.


To reduce the number of rollbacks you can use `rollbackRetryOptions`. This will allow devices to re-request updates after rollbacks, moreover, it will protect your business even if a broken update is released.
You can find more detailed information about rollbackRetryOptions` [here](https://github.com/microsoft/react-native-code-push/blob/master/docs/api-js.md).

I also wanted to recommend you use appcenter-cli for releases. Code-push cli is officially depreciated and may contain various malfunctions.
You can find all the necessary information on using code-push in appcenter-cli [here](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/cli).

**Comment by itenl** [comment]
@andreidubov You're wlc, i already set rollbackRetryOptions and use upgrade component reduce users from exiting the APP during the update process, btw, if a rollback occurs, will using `CodePush.checkForUpdate` maybe not return update-content and until rollbackRetryOptions takes effect, Right?

**Comment by itenl** [comment]
@andreidubov 
I have modified the source code [checkForUpdate](https://github.com/itenl/react-native-code-push/blob/c6f0646127acf5b117fdc6c0d90225245751a4d4/CodePush.js#L91) to check whether it contains rollback and  has been posted to npmjs.

Finally, Thank you for your reply.
