### ISSUE TITLE
Readme erroneously  states that the Video component isn't supported

### ISSUE THREAD

**Issue by district-michael** [microsoft/react-native-code-push#1879]
The readme is out of date when it states that the <Video> component isn't supported.  It can use require('asset.mp4'), which allows the video to be bundled and distributed OTA

**Comment by alexandergoncharov** [comment]
Hi @district-michael ,
Thanks for reporting!

Is it correct that your suggestion is adding an additional example to docs with videos?

**Comment by district-michael** [comment]
Hi @alexandergoncharov,
Yes that is correct.  At the moment, the table states that the Video component cannot be used with `react-native-code-push`, as seen in the below table:

> The following list represents the set of components (and props) that don't currently support their assets being updated via CodePush, due to their dependency on static images (i.e. using the `{ uri: "foo" }` syntax):
> 
> | Component   | Prop(s)                                                              |
> |-------------|----------------------------------------------------------------------|
> | `SliderIOS` | `maximumTrackImage`, `minimumTrackImage`, `thumbImage`, `trackImage` |
> | `Video`     | `source`                                                             |
> 

I would suggest we need to add something to clarify that it works when using `source={require('./filename.mp4'}` but not `source={{uri: "filename.mp4"}}`

**Comment by alexandergoncharov** [comment]
Oh, I see, cool! Thanks for your suggestion!
We will update the docs a bit later. We will keep you posted.

**Comment by Krasavinigor** [comment]
Hi @district-michael!
I opened PR: https://github.com/microsoft/react-native-code-push/pull/1900 for updating documents. Could you please take a look if you have time?

**Comment by alexandergoncharov** [comment]
Hi @district-michael ,

As https://github.com/microsoft/react-native-code-push/pull/1900 was merged I'm going to close this issue for now.
Please feel free to reopen it if you have any questions.
