### ISSUE TITLE
let user ignore update

### ISSUE THREAD

**Issue by xralphack** [microsoft/react-native-code-push#1882]
### Expected Behavior

How can I implement let user ignore a certain version?
I did not use dialog update and I read from doc
```
codePush.SyncStatus.UPDATE_IGNORED (2) - The app had an optional update which the end user chose to ignore. (This is only applicable when the updateDialog is used)
```

Is it possible to report update ignore to server?

**Comment by alexandergoncharov** [comment]
Hi @xralphack ,
Thanks for reporting!

If you would like to let user possibility to choose ignoring update the main approach is using the update dialog: https://github.com/microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushoptions
If you would like to customize this approach you can call `checkForUpdate` for getting all metadata of the update and then add your logic for asking users and then call `sync` method if the user decide to get an update. Here is more info about it: https://github.com/microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushcheckforupdate 

Please let me know if it was helpful or you have any questions.

**Comment by alexandergoncharov** [comment]
Hi @xralphack ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
But I hope I answered your question. :)
Please feel free to reopen this issue if you have questions.

**Comment by xralphack** [comment]
Thanks for your reply @alexandergoncharov 

I thought codepush server can record which device ignore certain version.
However, it seems not.
So now I just record it in my own database

anyways, thx
