### ISSUE TITLE
react-native-code-push on android release apk screen goes blank  - invalid hook call

### ISSUE THREAD

**Issue by jihyeonjeong11** [microsoft/react-native-code-push#1890]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. make a release apk of app.
2. codepush runs, update on next run.
3. screen goes blank.

### Expected Behavior
What you expected to happen?

app restarted or app runs normally.

### Actual Behavior
What actually happens?

apk goes blank and gives me invalid hook call error

```
  2020-06-29 12:11:18.904 2426-2509/? E/unknown:ReactNative: Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
    1. You might have mismatching versions of React and the renderer (such as React DOM)
    2. You might be breaking the Rules of Hooks
    3. You might have more than one copy of React in the same app
    See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    
    This error is located at:
        in h
        in RCTView
        in RCTScrollView
        in AndroidSwipeRefreshLayout
        in N
        in N
        in f
        in O
        in RCTView
        in RCTView
        in Unknown
        in RCTView
        in RNCSafeAreaView
        in Unknown
        in o
        in Unknown
        in A
        in Unknown
        in Unknown
        in Unknown
        in Unknown
        in RCTView
        in RCTView
        in RCTView
        in ForwardRef
        in RCTView
        in P
        in PanGestureHandler
        in Unknown
        in RCTView
        in P
        in RCTView
        in G
        in Unknown
        in RCTView
        in Unknown
        in RCTView
        in Unknown
        in P
        in y
        in Unknown
        in GestureHandlerRootView
        in Unknown
        in w
        in Unknown
        in De
        in Unknown
        in Unknown
        in Unknown
        in Unknown
        in RCTView
        in x
        in RCTView
        in RCTView
        in V
        in RCTView
        in c
        in RCTView
        in Unknown
        in S
        in Unknown
        in Ae
        in Unknown
        in Unknown
        in Unknown
        in Unknown
        in Unknown
        in Unknown
        in E
        in Unknown
        in ForwardRef
        in Unknown
        in ForwardRef
        in RNCSafeAreaView
        in Unknown
        in _
        in c
        in c
        in RCTView
        in L
        in A
        in RCTView
        in RCTView
        in x, stack:
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: ^6.2.1
* react-native version: 0.61.1
* iOS/Android/Windows version: android 10
* Does this reproduce on a debug build or release build? on release
* Does this reproduce on a simulator, or only on a physical device? anywhere with new code-push implemented released version.

Thanks for the great feature.

I tried to implement codepush in my app(on release version apk), seems ok with these verboses
```
2020-06-29 12:10:58.296 2204-2277/? I/ReactNativeJS: [CodePush] Checking for update.
2020-06-29 12:10:58.329 2204-2277/? I/ReactNativeJS: [CodePush] Sync already in progress.
2020-06-29 12:10:59.455 2204-2277/? I/ReactNativeJS: [CodePush] Downloading package.
2020-06-29 12:11:02.609 2204-2247/? D/ReactNative: [CodePush] Applying full update.
2020-06-29 12:11:02.617 2204-2277/? I/ReactNativeJS: [CodePush] Installing update.
2020-06-29 12:11:02.653 2204-2277/? I/ReactNativeJS: [CodePush] Update is installed and will be run on the next app restart.

after app restarts

2020-06-29 12:11:18.248 2426-2507/? I/ReactNativeJS: [CodePush] Checking for update.
2020-06-29 12:11:18.250 2426-2507/? I/ReactNativeJS: [CodePush] Reporting CodePush update success (v8)
2020-06-29 12:11:18.280 2426-2507/? I/ReactNativeJS: [CodePush] Sync already in progress.
2020-06-29 12:11:19.477 2426-2507/? I/ReactNativeJS: [CodePush] App is up to date.
```

this looks fine but I got above error, invalid hook call.
Yes I'm using hooks for index screen of app, but my index.js is still class, so I feel clueless for now.

Is there anyone experienced same issue as I have ? 

Thanks again for the great service.

P.S.: this could related with my react native and react version. I'm looking into it.

(The more info the faster we will be able to address it!)

**Comment by alexandergoncharov** [comment]
Hi @jihyeonjeong11 ,
Thanks for reporting!

Could you please provide some demo app with reproducing issue and reprosteps? I would like to reproduce and debug it.

**Comment by alexandergoncharov** [comment]
Hi @jihyeonjeong11,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by vinaydrevankar** [comment]
@jihyeonjeong11  - Were you able to find the solution?

**Comment by pierroo** [comment]
This is super late, BUT facing the issue today!
And it is super impactful, and there is no reason for this error to trigger since we haven't made changes to the screen that crashes and calls this hook issue.
@alexandergoncharov-zz or @vinaydrevankar or @jihyeonjeong11  if you are still around?

**Comment by MikhailSuendukov** [comment]
Hi @pierroo! Let's continue discussing it [here](https://github.com/microsoft/react-native-code-push/issues/2653/).
