### ISSUE TITLE
Android cashes on launch. Codepush unable to install latest deployment

### ISSUE THREAD

**Issue by jeroen-van-dijk** [microsoft/react-native-code-push#1891]
After uploading a new deployment the Android app does download the deployment as show in [](https://appcenter.ms/) dashboard. But once I reopen the app to install te latest deployment in instantly cashes and logging the following error

```
FATAL EXCEPTION: create_react_context
Could not open file/data/user/0/{package-name}/files/CodePush/95ea67377f3aeb81ff6bde79f6c934f851803b7a009e35cd2eb3e49652264753/CodePush/index.android.bundle: No such file or directory
```

Seems like the error is happing due to:
```
[CodePush] An unknown error occurred.
06-30 14:11:06.094 17198 17272 I ReactNativeJS: [CodePush] Update is invalid - A JS bundle file named "null" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.
```

RN-version: 0.61.5
Codepush: 6.2.1

**Comment by Sotatek-NinhTran** [comment]
I have the same problem 
try checkForUpdate has new version
codePush.asyn() still unable to install latest deployment

RN-version: 0.62.2
Codepush: 6.2.1

**Comment by alexandergoncharov** [comment]
Hi @jeroen-van-dijk, @Sotatek-NinhTran ,
Thanks for reporting!

Could you please provide some demo app with reproducing issue and reprosteps? I would like to reproduce and debug it.

**Comment by jeroen-van-dijk** [comment]
Thanks for replying @alexandergoncharov

The issue was resolved after I removed all the old expo code that was still in the project after ejecting to vanilla RN.

**Comment by alexandergoncharov** [comment]
@jeroen-van-dijk , cool! Thanks for letting us know. I'm closing this issue for now.

Please feel free to reopen it if you have any questions.
