### ISSUE TITLE
Reopen issue 1871

### ISSUE THREAD

**Issue by Gentlee** [microsoft/react-native-code-push#1892]
Need to reopen issue https://github.com/microsoft/react-native-code-push/issues/1871

**Comment by Adr1ann** [comment]
Need to reopen issue #1821

**Comment by ruslan-bikkinin** [comment]
Hello and thanks for reaching us. In case if you would like to get particular issue re-opened please leave a comment in it and it will be revisited by the team. I'm closing this.
