### ISSUE TITLE
Codepush updates not working on iOS

### ISSUE THREAD

**Issue by pragyajha** [microsoft/react-native-code-push#1893]
There is a very weird issue happening where the new codepush changes is not reflecting on iOS but works perfectly on android.

I have followed the codepush integrations steps as described in the official docs for both platforms [ios](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started#ios-setup) & [android](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started#android-setup)

This is how my codepush options in root App file looks like

<img width="524" alt="Screenshot 2020-06-30 at 8 37 46 PM" src="https://user-images.githubusercontent.com/3938228/86143250-d1633780-bb11-11ea-9d08-0a37a78979d2.png">

The changes seems to be updating and even being installed in the codepush section within Appcenter, this is what it looks like for iOS app

<img width="1081" alt="Screenshot 2020-06-30 at 8 41 53 PM" src="https://user-images.githubusercontent.com/3938228/86143577-39b21900-bb12-11ea-8f0f-c6a9240a6bc9.png">

### Steps to Reproduce
1. Release new updates via appcenter build pipeline setup for codepush( majorly has all the environment based codepush release commands specified in appcenter-post-build.sh )
2. Triggers new codepush release under codepush tab
3. No changes displayed for the iOS user, works for Android user

There are also some solutions I tried from the discussions on various forums but none of them seem to work
1. Use mandatory flag in release command
2. Use description tag in release command
3. Use target version in release command
4. Redoing manual ios-rnpm plugin installation

Could you please help me resolve this issue, as I've been breaking my head on this for past few days!

### Expected Behavior
User should be able to view codepush changes on both the platforms

### Actual Behavior
What actually happens?
No changes displayed for the iOS user, works for Android user

### Environment
* react-native-code-push version: 6.2.1
* react-native version:0.62.2

**Comment by alexandergoncharov** [comment]
Hi @pragyajha ,
Thanks for reporting!

Could you please provide logs during the update? It helps us to understand what is going on in the app? There should be logs with `[CodePush]` tag.

**Comment by pragyajha** [comment]
Hi @alexandergoncharov, Happy to let you know that it worked for ios using the command line when we ran on a different environment. Most probably it had something to do with our staging environment configurations. Hence marking this as closed. Thanks!

**Comment by jitish2** [comment]
@pragyajha  Hi Pragya , I'm facing the same issue on IOS , In android it's working fine. Can you please help me out of this? 

<img width="866" alt="Screenshot 2020-07-15 at 4 59 20 PM" src="https://user-images.githubusercontent.com/56391170/87544377-f3d58300-c6c3-11ea-97b0-66d84b235373.png">
