### ISSUE TITLE
Update did not finish loading the last time, rolling back to a previous version

### ISSUE THREAD

**Issue by BAE86AEC1946B6AB60CCD7452DC811F0** [microsoft/react-native-code-push#1896]
### Steps to Reproduce

```
AppRegistry.registerComponent(appName, () =>
  CodePush({
    checkFrequency: CodePush.CheckFrequency.ON_APP_START,
    installMode: CodePush.InstallMode.ON_NEXT_RESTART,
    mandatoryInstallMode: CodePush.InstallMode.ON_NEXT_RESTART,
  })(App),
);
```

### Expected Behavior

Install updates

### Actual Behavior

```
07-02 02:29:28.025  I/ReactNativeJS: [CodePush] Checking for update.
07-02 02:29:28.404  I/ReactNativeJS: [CodePush] Reporting binary update (1.0.1)
07-02 02:29:29.156  I/ReactNativeJS: [CodePush] Downloading package.
07-02 02:29:34.050  D/ReactNative: [CodePush] Applying full update.
07-02 02:29:34.069  I/ReactNativeJS: [CodePush] Installing update.
07-02 02:29:34.101  I/ReactNativeJS: [CodePush] Update is installed and will be run on the next app restart.
07-02 02:29:42.112  I/ReactNativeJS: [CodePush] Checking for update.
07-02 02:35:30.107  D/ReactNative: [CodePush] Update did not finish loading the last time, rolling back to a previous version.
07-02 02:35:30.192  D/ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
```

### Environment

* react-native-code-push version: ^6.2.1
* react-native version: 0.61.5
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? release 
* Does this reproduce on a simulator, or only on a physical device? simulator

MainApplication.java：

```diff
+ import com.microsoft.codepush.react.CodePush;
// ...
private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

+    @Override
+    protected String getJSBundleFile() {
+      return CodePush.getJSBundleFile();
+    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
+      for (ReactPackage rp : packages) {
+        if (rp instanceof CodePush) {
+          packages.remove(rp);
+          break;
+        }
+      }
+      packages.add(
+          new CodePush(BuildConfig.CODEPUSH_KEY, getApplicationContext(), BuildConfig.DEBUG, "http://myserverUrl.com"));
      return packages;
    }
```

build.gradle:

```diff
+ apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
```

settings.gradle:

```diff
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); 
applyNativeModulesSettingsGradle(settings)

+ include ':app', ':react-native-code-push'
+ project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
```
![1](https://user-images.githubusercontent.com/64393724/86324978-f2db3500-bc71-11ea-80c8-394fd027414b.png)

Why does this error occur?

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> If you're not calling sync on app start (like within componentDidMount of your root component), then you need to explicitly call notifyApplicationReady on app start, otherwise, the plugin will think your update failed and roll it back.

Do I need to execute `notifyApplicationReady` ?

**Comment by alexandergoncharov** [comment]
Hi @BAE86AEC1946B6AB60CCD7452DC811F0 ,
Thanks for reporting!

I'm not sure that you have to call `notifyApplicationReady` since you are wrapped the root component with CodePush wrapper.

Could you please provide a demo app with reproducing issue and reprosteps? I would like to reproduce this issue and investigate it.

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> Hi @BAE86AEC1946B6AB60CCD7452DC811F0 ,
> Thanks for reporting!
> 
> I'm not sure that you have to call `notifyApplicationReady` since you are wrapped the root component with CodePush wrapper.
> 
> Could you please provide a demo app with reproducing issue and reprosteps? I would like to reproduce this issue and investigate it.

demo:  https://github.com/BAE86AEC1946B6AB60CCD7452DC811F0/c_1896

Please help me to see, thank you very much

**Comment by Krasavinigor** [comment]
Hi @BAE86AEC1946B6AB60CCD7452DC811F0!
I tested your demo project. It seems like, all works correctly. I created a few releases and got them.
![Screenshot 2020-07-09 at 10 26 37](https://user-images.githubusercontent.com/48414875/87010054-aee6b380-c1ce-11ea-94e8-a843cfabc183.png)

**Comment by Krasavinigor** [comment]
Hi @BAE86AEC1946B6AB60CCD7452DC811F0! 

Unfortunately, I'm going to close this issue for now as I haven't heard from you in a while.
Please feel free to reopen this issue if you have questions.

**Comment by atifaziz1** [comment]
Hi @Krasavinigor !

I am facing same issue `Update did not finish loading the last time, rolling back to a previous version`.

please let me know what's the issue is.

`react-native: 0.64.2`
`react-native-code-push: ^6.4.1`
`OS: Android`
