### ISSUE TITLE
Code Push is rejected by Apple again?

### ISSUE THREAD

**Issue by hengkx** [microsoft/react-native-code-push#1898]
2. 3 Performance: Accurate Metadata
Hello,

Thank you for your response. It would be appropriate to remove any and all remote code importing functionality from this app, such as CodePush support, before resubmitting for review. We look forward to reviewing your revised submission.

Best regards,

App Store Review

Hello,

Thank you for your reply.

We continue to find that your app contains hidden features or functionality that can change the behavior of the app after review. To resolve this issue, it would be appropriate to ensure that all features and functions in the app are visible and fully accessible during review.

Deliberate disregard of the App Store Review Guidelines and attempts to deceive users or undermine the review process are unacceptable and is a direct violation Section 3.2(f) of the Apple Developer Program License Agreement. Continuing to violate the Terms & Conditions of the Apple Developer Program will result in the termination of your account, as well as any related or linked accounts, and the removal of all your associated apps from the App Store.

We look forward to reviewing your resubmitted app.

Best regards,

App Store Review

**Comment by alexandergoncharov** [comment]
Hi @hengkx ,
Thanks for reporting!

Yeah, sometimes we get rejections from Apple, unfortunately. But CodeOush is fully applied by Apple Developer Program License Agreement. Could you please check this docs: https://github.com/microsoft/react-native-code-push#store-guideline-compliance

Please let me know if it was helpful or you have any questions.

**Comment by hengkx** [comment]
2. 3 Performance: Accurate Metadata
Hello,

Thank you for your response. It would be appropriate to remove any and all remote code importing functionality from this app, such as CodePush support, before resubmitting for review.

It would be additionally appropriate to submit any bug fixes by submitting the revised binary via App Store Connect. We look forward to reviewing your revised submission.

Best regards,

App Store Review

**Comment by hengkx** [comment]
Full compliance with the above rules is still rejected

**Comment by alexandergoncharov** [comment]
Hi @hengkx ,
Sorry for the delay.

It is strange as Apple documentation is fully allowed CodePush as we don't change any native part.
Could you please clarify Apple still rejects your app?

**Comment by hengkx** [comment]
I re-listed an APP that did not use CodePush. I updated and added CodePush in future versions and successfully approved it.

Directly rejected for the first use.
