### ISSUE TITLE
Targeted updates/deployments

### ISSUE THREAD

**Issue by nevir** [Microsoft/react-native-code-push#190]
Two somewhat intertwined ideas here:

1. Have some way of specifying groups of devices, and when releasing, provide an option to target _just_ those devices.
2. Have support for slowly rolling out updates over N minutes/hours/days (partitioning users based on a prefix of their UDID, probably)

---

The motivation for both of these is to have better control over deployments to app store builds (since we can't exactly match the bits that Apple deploys to end user devices).

The first suggestion is to allow us to target developer/tester phones directly before rolling a release out to the world.

The second is to allow for canarying on a subset of real world users; giving developers a chance to roll back before a problem affects all of their users

**Comment by lostintangent** [comment]
We're definitely extremely keen to support targeted deployments very very soon, once we finish up some of our core feature set in the next couple of weeks. 

For #2, are you not interested in a percentage based rollout (as requested in #174), but rather, a time-based roll out that would allow you to specify a time that you want the service to incrementally increase the availability from 0% to 100%?

**Comment by nevir** [comment]
Doh! I totally missed #174 - percentage based rollout would cover that just fine (time based could be built on top of it pretty trivially)

**Comment by lostintangent** [comment]
@nevir We're currently investigating staged rollouts with the hope to land this in production in the next couple of weeks. Could we use #174 to drive the discussion around this feature and "convert" this issue to focus on the targeted updates? Any feedback you had on the other thread would be hugely appreciated!

**Comment by lostintangent** [comment]
I'm going to close this issue for now, since we shipped the ability to release canary builds already, and when we get to addressing the targeted updates feature, we'll open an issue to get feedback on the design. Thanks again!

**Comment by nevir** [comment]
👍
