### ISSUE TITLE
Deprecated App Center

### ISSUE THREAD

**Issue by builtbyproxy** [microsoft/react-native-code-push#1902]
Hello

I'm very sorry for not sticking to the format on this ticket, but I'm struggling to find mention at all about the [deprecation of `app center push` on the 31st of December 2020](https://devblogs.microsoft.com/appcenter/migrating-off-app-center-push/)

Is there a discussion about this anywhere? 

Thank you!

**Comment by andreidubov** [comment]
Hi @builtbyproxy 
Thanks for your question!

You have probably mixed up **app center push** and **app center code-push**. We have no plans to retire code-push. You can find more information about the **app center push** [here](https://docs.microsoft.com/en-us/appcenter/push/).

Please let me know if you have any questions.

**Comment by builtbyproxy** [comment]
Beauty! I thought there was a chance of that but wanted to double check and get on top of it, thanks a lot @andreidubov
