### ISSUE TITLE
please help me i got this error i do all steps properly yet i got this error 

### ISSUE THREAD

**Issue by anujec722** [microsoft/react-native-code-push#1905]
> Could not resolve project :react-native-code-push.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-code-push:

**Comment by Krasavinigor** [comment]
Hi @anujec722, 
Thanks for reporting!

Could you please fill a description of the issue and provide some details like logs or/and demo app with reproducing issue and reprosteps that help us reproduce and investigate the issue?

**Comment by alexandergoncharov** [comment]
Hi @anujec722,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
