### ISSUE TITLE
IOS - code is not reflecting after install code push bundle by user 

### ISSUE THREAD

**Issue by jitish2** [microsoft/react-native-code-push#1906]

**Comment by Krasavinigor** [comment]
Hi @jitish2,
Thanks for reporting!

Could you please fill a description of the issue and provide some details like logs or/and demo app with reproducing issue and reprosteps that help us reproduce and investigate the issue?

**Comment by alexandergoncharov** [comment]
Hi @jitish2 ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
