### ISSUE TITLE
[Error]  Internal Server Error when code-push release-react

### ISSUE THREAD

**Issue by bosung90** [microsoft/react-native-code-push#1908]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. code-push release-react PROJECT_ID/PROJECT_NAME android -d Staging

### Expected Behavior
Code Push Android

### Actual Behavior
I get error saying "[Error]  Internal Server Error" in red text

### Reproducible Demo

I didn't change much code other than JS since last time I did a release

### Environment

* react-native-code-push version: 2.1.9
* react-native version: 0.62.2
* iOS/Android/Windows version: Android SDK 28 buildToolsVersion 28.0.3
* Does this reproduce on a debug build or release build? releasing build to Staging
* Does this reproduce on a simulator, or only on a physical device? N/A

(The more info the faster we will be able to address it!)

**Comment by 383131600** [comment]
same....

**Comment by Jobel91** [comment]
Issue Discovered

https://status.appcenter.ms/

**Comment by 383131600** [comment]
when can it fix?

**Comment by marioot** [comment]
I'm experiencing the same issue at this moment.

Only on iOS, Android works.

**Comment by Krasavinigor** [comment]
Hi @bosung90!

Could you please use **appcenter-cli** for creating releases? Use: `npm install -g appcenter-cli`
Also could you please update react-native-code-push to the latest version? (6.3.0)
Use flag `--debug` with appcenter-cli for more details.

**Comment by alexandergoncharov** [comment]
Hi all,

As the issue was resolved, I'm going to close this issue for now.
Please feel free to reopen it if you have any questions.

Thanks,
Alexander
