### ISSUE TITLE
Unable to resolve module './RestartManager'

### ISSUE THREAD

**Issue by Adr1ann** [microsoft/react-native-code-push#1910]
I configured appcenter and codepush exactly as in the documentation but when I run both on the emulator from android studio and on the device this error appears. 

### Actual Behavior
![110842754_2699398007007458_2601343351188351286_n](https://user-images.githubusercontent.com/44664966/87948780-cfa3e880-caad-11ea-8d8c-0a8376ff34d7.jpg)

### Environment

* react-native-code-push version: ^6.3.0
* react-native version: 0.60.5
* appcenter: 3.1.0
* yarn: 1.7.0

Additional Information
Does this reproduce on a debug build or release build? Both
Does this reproduce on a simulator, or only on a physical device? Both

I integrate it on App.js like this
`class App extends React.Component {

  constructor() {
    super();
    if (Text.defaultProps == null) Text.defaultProps = {};
    Text.defaultProps.allowFontScaling = false;
    if (TextInput.defaultProps == null) TextInput.defaultProps = {};
    TextInput.defaultProps.allowFontScaling = false;
  }

  render() {
    return (
      <Provider store={store}>
        <AppContainer uriPrefix={prefix}/>
      </Provider>
    );
  }
}

App = codePush(App);

export default App;`

Can anyone please help?

**Comment by jgking2** [comment]
@Adr1ann did you have an old version before?  I ran across the same issue when upgrading, but ran `react-native start --reset-cache` - it worked fine from there!

**Comment by Adr1ann** [comment]
That was. Thank you very much. @jgking2

**Comment by andreidubov** [comment]
Hi @jgking2 
Thanks for your find, I'm sure this should help.

@Adr1ann I'm going to close this issue, if you have any questions or other issues, feel free to reopen it.
