### ISSUE TITLE
minimumBackgroundDuration not working for ON_NEXT_SUSPEND when there are permission prompts

### ISSUE THREAD

**Issue by triplehenry** [microsoft/react-native-code-push#1911]
### Steps to Reproduce
1. Have code such as
```
codePush.sync({
    installMode: codePush.InstallMode.ON_NEXT_SUSPEND,
    minimumBackgroundDuration: 20,
})
```
2. Trigger prompt such as for push notification, contacts, camera, etc. and then dismiss it.
3. App will auto restart after 20 seconds from the time the prompt is shown.

### Expected Behavior
Prompts shouldn't trigger the minimumBackgroundDuration counter and if it does, it should be canceled after dismissing it.

### Actual Behavior
The app auto restarts despite not being in background.  I was only able to test on iOS device but this could also be an issue on Android as well.

### Environment

* react-native-code-push version: "6.2.1"
* react-native version: "0.61.5"

**Comment by Krasavinigor** [comment]
Hi @triplehenry,
Thank you for reporting!

I reproduced this issue. We'll investigate it a soon as possible. The issue's in a queue.
