### ISSUE TITLE
code push sometimes not update app content when I open vpn

### ISSUE THREAD

**Issue by keung7251** [microsoft/react-native-code-push#1912]
code push sometimes not update app content when I open vpn, anyone has this problem?

"react-native-code-push": "^6.0.0",
  "react-native": "0.61.4",

**Comment by alexandergoncharov** [comment]
Hi @keung7251,
Thanks for reporting!

It can be some connection issue. Could you please provide some logs during the update? There should be `[CodePuhs]` tag.

**Comment by alexandergoncharov** [comment]
Hi @keung7251 ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
