### ISSUE TITLE
Rollback devices are not getting code-push anymore

### ISSUE THREAD

**Issue by sayeed545** [microsoft/react-native-code-push#1915]
We have submitted application with version 2.1 to production and later tried to provide a code-push with a few changes, but while checking there are around 11 rollbacks and 140 downloads.

We do not know what are the exact devices who got rolled-back. Some of them did not get the updates.

So my questions are:

1. Is there a way to find out the devices or members who got rolled back
2. Can we send code push update to the specific devices
3. Is there any retry mechanism when the device gets rolled back
4. If there is an exception can we find it out

We also have google analytics added but could not figure out exact issue.

### Environment

* react-native-code-push version: "5.4.0",
* react-native version: "0.59.10",
* iOS/Android: both
* Does this reproduce on a debug build or release build: both

**Comment by sayeed545** [comment]
Any update on the above issue. This issue is causing in production. Please provide an update.

**Comment by alexandergoncharov** [comment]
Hi @sayeed545,
Thanks for reporting!

1. Unfortunately no. Or if you just some additional logic for that.
2. Unfortunately no. It isn't possible.
3. Yeah, we have one for this. Could you please check `rollbackRetryOptions ` option in this docs: https://github.com/microsoft/react-native-code-push/blob/6ae9392d81eb5a8377664681da7ca673e630c481/docs/api-js.md#codepushoptions
4. Unfortunately no but you also use some bug tracker for getting it. We don't collect this info as it isn't secure for end-users.

Also, rollback can be for some unexpected cases. For example if device was OFF during update.

Please let me know if it was helpful or you have any other questions.

**Comment by sayeed545** [comment]
Thanks for the reply. I need to update the code push version to check Point.3. Will check and get back, if I found any issues.

Thanks again,
Best Regards

**Comment by ruslan-bikkinin** [comment]
Closing this due to the long period of inactivity. Please feel free to reopen if you have any other questions related to the issue.
