### ISSUE TITLE
Invalid Image Exception

### ISSUE THREAD

**Issue by ankitsolanki** [microsoft/react-native-code-push#1916]
Hi All, 
The app by itself runs fine. CodePush.sync function gets the update.
Once the updated is downloaded following exception occurs. 
com.digiview W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid byte order: ffff8950

This leads to a rollback and a failed update. Though the app start properly on new the update and on restart it rollsback.

Looks like a nosiy log/exception but there is no way to suppress the same which is leading to rollback. 

Thoughts?

Thanks
Ankit

**Comment by ankitsolanki** [comment]
anyone?

**Comment by alexandergoncharov** [comment]
Hi @ankitsolanki ,
Thanks for reporting!

It is a strange issue. Could you please provide a demo app with reproducing issue and reprostpes? I would like to reproduce and debug it.

**Comment by alexandergoncharov** [comment]
Hi @ankitsolanki ,

I'm going to close this issue for now as I haven't heard from you in a while, unfortunately.
Please feel free to reopen it if you have any questions.
