### ISSUE TITLE
mandatoryInstallMode seems to affect installMode even for not mandatory updates

### ISSUE THREAD

**Issue by s-aleinik** [microsoft/react-native-code-push#1917]
#1537 # Steps to Reproduce

1. Add the following CodePush config:

```
import CodePush from 'react-native-code-push';

CodePush.sync({
  minimumBackgroundDuration: 60 * 5,
  installMode: CodePush.InstallMode.ON_NEXT_SUSPEND
});
```
2. Install the app and launch it for the first time.

### Expected Behavior
CodePush update will be downloaded, but installed after app is being on a background for at least 5 minutes.

### Actual Behavior

```
BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 LOG  Running "App" with {"rootTag":1}
 LOG  [CodePush] Checking for update.
 LOG  [CodePush] Reporting binary update (1.0)
 LOG  [CodePush] Downloading package.
 LOG  [CodePush] Installing update.
 LOG  [CodePush] Restarting app
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1/1), done.

 LOG  Running "App" with {"rootTag":11}
 LOG  [CodePush] Checking for update.
 LOG  [CodePush] Reporting CodePush update success (v32)
 LOG  [CodePush] App is up to date.
```

### Reproducible Demo

This is pretty much all the info I could provide. Have tried `InstallMode.ON_NEXT_RESUME and InstallMode.ON_NEXT_SUSPEND` - both are behaving the same way.

What I have found out is: while `mandatoryInstallMode` is not set update is installed immediately, no matter what is set for `installMode`.

Here is how I'm doing a CodePush: `code-push release-react appname --noDuplicateReleaseError`. So there is no `mandatory` flag set, and I can see it on App Center -> Distribute -> CodePush.

I also noticed that rollbacks have highly increased after setting `mandatoryInstallMode: InstallMode.ON_NEXT_SUSPEND`

<img width="640" alt="Screen Shot 2020-07-31 at 13 27 53" src="https://user-images.githubusercontent.com/31858187/89026947-4359b700-d332-11ea-93a6-24d517246fcc.png">

### Environment

* react-native-code-push version: 6.2.0
* react-native version: 0.62.2
* iOS: 13.3.1, Android: 9
* Both debug and release builds.
* Both simulator and physical device

**Comment by andreidubov** [comment]
Hi @s-aleinik 
Thanks for the reporting.

I see you are using **code-push-cli** to release updates. I want to remind you that the **code-push-cli** is outdated and may contain some issues. Could you try to test your flow with [appcenter-cli](https://github.com/microsoft/appcenter-cli)?

It would also be helpful if you run the `appcenter codepush release-react` command with the -debug flag.
Also, could you provide more detailed logs with time indication (for example logs from Logcat) and provide a more detailed description of actual behavior.

**Comment by s-aleinik** [comment]
Hi @andreidubov , thank you for responding!

I will try to test it with `appcenter-cli` tomorrow. Also I will provide a more detailed logs.

Regarding description:
The app is currently in developing, so the actual version is 1.0. When I'm uploading new build to the test flight, I should also update CodePush, because on release mode actual info is taking from the CodePush. After first installation, application is opening, and reloads almost instantly to install update downloaded from the CodePush

**Comment by ruslan-bikkinin** [comment]
Hi @s-aleinik did you have a chance to try to test `appcenter-cli` and see if your issue is still persist?

**Comment by s-aleinik** [comment]
@ruslan-bikkinin I'm really sorry, but have't got a chance till now. Will try to do it in a foreseeable future and comment here.

**Comment by ruslan-bikkinin** [comment]
Got it, I am closing this for now then. Feel free to re-open the issue when you are ready to get back to discuss it.

**Comment by s-aleinik** [comment]
@ruslan-bikkinin @andreidubov as you suggested `appcenter codepush release-react` helps. Haven't tried for android yet, but iOS works fine.

Thank you!
