### ISSUE TITLE
CodePush for React Native: A Complete Getting Started Guide

### ISSUE THREAD

**Issue by naishe** [microsoft/react-native-code-push#1920]
Hey guys,

I was working on getting CodePush integrated with my React Native project recently. I found that it is a little confusing to the new user with old code-push cli and new appcenter CLI, and I fumbled a couple of times. So, I authored a two part blog post using the tooling available as of Aug 2020 specifically to have the following goals in mind:

1. Step by step process of integrating CodePush with React Native project (>= 0.60.0)
2. Incorporates diffs of the files to be changed
3. Includes copy-paste-able codes
4. Introduces with various deployment strategies and how to achieve them with CodePush

My aim is to target the newbies to get going quickly and at the same time, introduce them with some of the fascinating features of CodePush.

*I would greatly appreciate if you incorporate these links in the repo's `README.md`.* (The tutorials provided in the read me seems a little outdated to me)

These tutorials have no ads, no paywall (the query parameter `sk` bypasses the paywall, it is for the author of the blog to let people access their contents freely), and it has no other agenda than teaching (and sharing my good experience with CodePush). It has appropriate code snippets, and screenshots. It links back to the repo and App Center's documentation for further reading.

Here are the links:

[Mastering Over-the-Air Updates in React Native with CodePush: Part 1](https://medium.com/cybermonkey/mastering-over-the-air-updates-in-react-native-with-codepush-part-1-faf241a7f84b?source=friends_link&sk=27b35de7307202e6be3759a5f056e580): https://medium.com/cybermonkey/mastering-over-the-air-updates-in-react-native-with-codepush-part-1-faf241a7f84b?source=friends_link&sk=27b35de7307202e6be3759a5f056e580

[Mastering Over-the-Air Updates in React Native with CodePush: Part 2](https://medium.com/cybermonkey/mastering-over-the-air-updates-in-react-native-with-codepush-part-2-37df58de6e7e?source=friends_link&sk=9067be9acab3ff5caf6970df0a02c2da): https://medium.com/cybermonkey/mastering-over-the-air-updates-in-react-native-with-codepush-part-2-37df58de6e7e?source=friends_link&sk=9067be9acab3ff5caf6970df0a02c2da 

Thanks,
Nishant

**Comment by alexandergoncharov** [comment]
Hi @naishe ,
Thanks for reporting and contributing!
It is a helpful link!

I will review it and discuss it with my team.
Also a good note about deprecated  `code-push` cli in our docs. We will update it too.

I'll keep you posted.

**Comment by naishe** [comment]
Thanks. I am open to suggestions and edits on the post.

**Comment by andreidubov** [comment]
This issue was mistakenly closed, sorry for the inaccuracy.

**Comment by alexandergoncharov** [comment]
Hi @naishe ,
I'm sorry about this delay.

We updated our docs and fully removed `code-push cli` mentions.
Also, thank you for your efforts on these topics! I discussed it with my team and I have to say that we can't add some external links to our documentation because if the project will be changed we will not be able to change that topic and it will be inconsistent.
I'm really sorry about that. You've done a really good job.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

Thanks,
Alexander

**Comment by naishe** [comment]
Thanks! Cool, I can understand. 

My motivation to write and then suggest it to be included in the README started only after I found the articles mentioned in the README were not quite useful and old (Jul 2016):

> ...you can check out the awesome getting started videos produced by [Bilal Budhani](https://www.youtube.com/watch?v=uN0FRWk-YW8&feature=youtu.be) and/or [Deepak Sisodiya ](https://www.youtube.com/watch?v=f6I9y7V-Ibk).

Refer: https://github.com/microsoft/react-native-code-push/blame/master/README.md#L121

And 

CI/CD integration reference from the same time liking to a website either not available in my region or down.

See: https://github.com/microsoft/react-native-code-push/blame/master/README.md#L434

-- Nishant
