### ISSUE TITLE
Android app crashes on release mode, while trying to download the latest code-push version, causes the version to roll back

### ISSUE THREAD

**Issue by kaushil111** [microsoft/react-native-code-push#1925]
Android app crashes on release mode, while trying to download the latest code-push version. The app downloads latest version and tries to apply it which results in a crash. This causes the version to rollback in the next release and the app stops receiving codepush updates

### Steps to Reproduce
1. Build the app in release mode with either `./gradlew assembleRelease` or `bundleRelease`
2. Push update to CP
3. Install the app on the device
4. Open the.device and the device will crash

### Expected Behavior
What you expected to happen?
Codepush should update to latest version immediately

### Actual Behavior
What actually happens?
```
Loading JS bundle from "assets://index.android.bundle"
Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.
Checking for update.
Reporting binary update (XXXX)
Downloading package.
Applying full update.
Installing update.
Loading JS bundle from "/data/user/0/MY_PACKAGE_NAME/files/CodePush/CODEPUSH_HASH/CodePush/index.android.bundle"
Restarting app
Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.

**APP CRASHES**
AFTER CRASH:

Update did not finish loading the last time, rolling back to a previous version.
Loading JS bundle from "assets://index.android.bundle"
Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.
Checking for update.
Reporting CodePush update rollback (v33)
An update is available, but it is being ignored due to having been previously rolled back.
App is up to date.
```

### Java crash:
```
--------- beginning of crash
2020-08-09 16:31:22.374 20045-20269/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: PACKAGE_NAME, PID: 20045
    com.facebook.react.common.JavascriptException: TypeError: undefined is not an object (evaluating 'r(d[4]).NativeModules.SourceCode.scriptURL.split('://')[1].split'), stack:
    <unknown>@623:130
    v@2:1473
    <unknown>@431:181
    v@2:1473
    <unknown>@6:69
    v@2:1473
    d@2:875
    global code@1606:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:79)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
2020-08-09 16:31:22.401 762-1208/? E/Netd: getNetworkForDns: getNetId from enterpriseCtrl is netid 0
2020-08-09 16:31:22.404 1360-11728/? W/ActivityManager: crash : PACKAGE_NAME,0
2020-08-09 16:31:22.408 1360-11728/? W/ActivityTaskManager:   Force finishing activity PACKAGE_NAME/.MainActivity
```

### Environment

* react-native-code-push version: "6.2.0"
* react-native version: "0.62.2"
* iOS/Android/Windows version: Any android. Works fine on iOS
* Does this reproduce on a debug build or release build? -> release build
* Does this reproduce on a simulator, or only on a physical device? all

**Comment by alexandergoncharov** [comment]
Hi @kaushil111 ,
Thanks for reporting!

I see in your logs `Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.`. Could you please ensure that you setup CodePush correctly? Possible you missed some steps. Here is a docs for that: https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md

If it was not helpful could you please provide a demo app with reproducing issue and reprosteps? I would like to reproduce and investigate it.

**Comment by kaushil111** [comment]
Hey! So I figured my reactotron [setup](https://github.com/infinitered/reactotron/issues/272#issuecomment-272013885) was conflicting with the codepush setup and causing the crash. Although I had fix for reactotron on my local env, it would still download the older binary and crash while trying to set it up. This made it difficult to identify the issue.

Note: It is an issue only on android

**Comment by duyta7598** [comment]
I'am still having this issue, it crashes while build release, debug build is fine and only happened on android, ios worked fine

- react-native-code-push version: "7.0.4"
- react-native version: "0.63.2"

**Comment by reynacho** [comment]
I'm also having this same issue, code push 7.0.4, react-native 0.66.2

**Comment by nguyenNCphpFox** [comment]
Hi @duyta7598 @reynacho. Any solutions for this?

**Comment by reynacho** [comment]
@nguyenNCphpFox I ended up re-building the entire project from scratch, re-setting up the code-push deployment in appcenter.ms and re-downloading the config file, then it started working.  I also downgraded react-native to 0.66.1, still with react-native-code-push ^7.0.4.  So, either the 0.66.2 was the issue or there was something misconfigured along the way that re-doing everything fixed for me

**Comment by duyta7598** [comment]
> Hi @duyta7598 @reynacho. Any solutions for this?

In my case, i found that the problem is the library react-native-jitsi-meet is conflict with code push. I think you should be able to fix it if your case is the same
Just search it on google!

**Comment by Linuhusainnk** [comment]
> > Hi @duyta7598 @reynacho. Any solutions for this?
> 
> In my case, i found that the problem is the library react-native-jitsi-meet is conflict with code push. I think you should be able to fix it if your case is the same Just search it on google!

got any solution for conflict with jitsi ?
