### ISSUE TITLE
Plugin is broken on iOS when using RN 0.20.0-rc1 (Android works fine)

### ISSUE THREAD

**Issue by geof90** [Microsoft/react-native-code-push#193]
Link to the related issue: https://github.com/facebook/react-native/issues/5851

**Comment by skevy** [comment]
FYI: https://github.com/facebook/react-native/commit/c9a1956c4fd9cfb6bf883c835b501d097181e1a4

**Comment by lostintangent** [comment]
@skevy Awesome! Thanks for the heads up. Any idea if this will make it into 0.20.0 "RTM"?

**Comment by skevy** [comment]
Hmm. Probably should. Let me check on that and I'll report back.

**Comment by skevy** [comment]
Added: https://github.com/facebook/react-native/issues/5762

**Comment by lostintangent** [comment]
Beautiful! Thanks so much @skevy!

**Comment by skevy** [comment]
Np. This fix got turned around pretty quickly...but if you ever have a critical bug in the future, don't hesitate to ping me on the issue/PR. Sometimes super critical stuff can get lost in the fray. Code-push is great...want to make sure we keep it running with each release :)

**Comment by geof90** [comment]
Closing. The latest RN release includes the RCTPromise fix.
