### ISSUE TITLE
Repeatedly getting this error: [CodePush] The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.

### ISSUE THREAD

**Issue by ganeshpadhayay** [microsoft/react-native-code-push#1931]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Setup the js and android part of the push code
2. try to run the project first time
3. getting error, not able to run, it is saying undefined function for codePush reference

### Expected Behavior
App should run perfectly

### Actual Behavior
White blank screen with error 
[Tue Aug 25 2020 17:43:22.108]  LOG      [CodePush] The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.
[Tue Aug 25 2020 17:43:22.108]  ERROR    TypeError: undefined is not a function, js engine: hermes
[Tue Aug 25 2020 17:43:22.109]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
[Tue Aug 25 2020 17:43:22.109]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes

```
  STACK TRACE AND/OR SCREENSHOTS
[Tue Aug 25 2020 17:42:39.901]  BUNDLE  ./index.js 

[Tue Aug 25 2020 17:42:43.715]  LOG      [CodePush] The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.
[Tue Aug 25 2020 17:42:43.715]  LOG      Running "CallingReactNativeActivity" with {"rootTag":21}
[Tue Aug 25 2020 17:43:02.128]  BUNDLE  ./index.js 

[Tue Aug 25 2020 17:43:04.530]  LOG      [CodePush] The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.
[Tue Aug 25 2020 17:43:04.530]  LOG      Running "CallingReactNativeActivity" with {"rootTag":41}
[Tue Aug 25 2020 17:43:15.950]  ERROR    TypeError: undefined is not a function, js engine: hermes
[Tue Aug 25 2020 17:43:15.969]  ERROR    TypeError: undefined is not a function, js engine: hermes
[Tue Aug 25 2020 17:43:19.727]  BUNDLE  ./index.js 

[Tue Aug 25 2020 17:43:22.108]  LOG      [CodePush] The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.
[Tue Aug 25 2020 17:43:22.108]  ERROR    TypeError: undefined is not a function, js engine: hermes
[Tue Aug 25 2020 17:43:22.109]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes
[Tue Aug 25 2020 17:43:22.109]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication), js engine: hermes

```

index.js
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
AppRegistry.registerComponent('CallingReactNativeActivity',() => App);

App.js
import React from 'react';
import {Provider} from 'react-redux';
import ReduxThunk from 'redux-thunk';
import {createStore, applyMiddleware} from 'redux';
import reducers from './src/reducers';
import SampleNetworkCall from './src/components/SampleNetworkCall';

import codePush from "react-native-code-push";    //if I remove this, it works fine

const App = () => {
const store = createStore(reducers, {}, applyMiddleware(ReduxThunk));
  return (
    <Provider store={store}>
      <SampleNetworkCall />
    </Provider>
  );
};

export default codePush(App);     //if I make it 'export default App; it works fine

I have done 4 changes at Android side,
1. include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')

2. ...
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
...

3. import com.microsoft.codepush.react.CodePush;

public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        ...

        // 2. Override the getJSBundleFile method in order to let
        // the CodePush runtime determine where to get the JS
        // bundle location from on each app start
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
    };
}

4. in strings.xml I have added my production deployment key
    <string moduleConfig="true" name="CodePushDeploymentKey">MY_KEY_FROM_APPCENTER_PORTAL</string>

Please help here, 
I made a fresh react native project and it works perfectly fine there
Also, if i build and run a release build, it crashes, I can't attach logs as it is a release build but problem is same I guess

### Environment

* react-native-code-push version:     "react-native-code-push": "^6.3.0",
* react-native version:     "react-native": "0.63.1",
* iOS/Android/Windows version: Android Studio 4.0, Gradle version: 6.3, Gradle Plugin Version: 4.0.1
* Does this reproduce on a debug build or release build? error and white screen on debug build, crash on release build
* Does this reproduce on a simulator, or only on a physical device? on the emulator and on a physical device

**Comment by shah0070** [comment]
I am Facing the same issue

**Comment by ganeshpadhayay** [comment]
Hi, I resolved it by adding packages in both MainApplication and ReactNativeActivity
I was adding code push to an existing project that is why these steps were extra and had to be implemented.

.addPackage(new MainReactPackage())
                .addPackage(new CodePush(getString(R.string.CodePushDeploymentKey), getApplicationContext(), BuildConfig.DEBUG))

to both MainApplication and ReactNativeActivity

**Comment by ddikodroid** [comment]
> @ganeshpadhayay , I tried to do the same but failed. can you please share a copy of the code?

i'm able to resolve the issue by moving the `getJSBundleFile()` after `getUseDeveloperSupport()`
```
      @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }
        
        // <- react-native-code-push
        @Override
        protected String getJSBundleFile() {
          return CodePush.getJSBundleFile();
        }
```
