### ISSUE TITLE
Error: Failed to release a CodePush update. (appcenter cli 2.6.7)

### ISSUE THREAD

**Issue by luatnd** [microsoft/react-native-code-push#1939]
I got an issue with appcenter cli 2.3.3, exactly here:
https://github.com/microsoft/react-native-code-push/issues/1886

After upgrade to newest version  appcenter cli 2.6.7, I got the error:
> Error: Failed to release a CodePush update.
> error Command failed with exit code 3.

### Steps to Reproduce
1. Using react-native custom build
   package.json
   ```
    "react": "16.13.1",
    "react-native": "mobiletechvn/react-native#v0.63.2.fix-shadow-node",
   ```
2. Then run codepush: `appcenter codepush release-react -a MY_REPO -d Development -t 3.0.490 -x`
3. Got the error

If i use `"react-native": "0.63.2",` => It work!

### Expected Behavior
Should work without error

### Actual Behavior
Here log output
```
Running "react-native bundle" command:

node node_modules/.bin/react-native bundle --assets-dest /var/folders/vk/d6dx88ld467_n1j2bxyvprzh0000gn/T/code-push202087-5764-16r58ub.1rv8/CodePush --bundle-output /var/folders/vk/d6dx88ld467_n1j2bxyvprzh0000gn/T/code-push202087-5764-16r58ub.1rv8/CodePush/index.android.bundle --dev false --entry-file index.js --platform android
Welcome to React Native!
                Learn once, write anywhere

info Writing bundle output to:, /var/folders/vk/d6dx88ld467_n1j2bxyvprzh0000gn/T/code-push202087-5764-16r58ub.1rv8/CodePush/index.android.bundle
info Done writing bundle output
info Copying 195 asset files
info Done copying assets
Converting JS bundle to byte code via Hermes, running command:

Error: Failed to release a CodePush update.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducible Demo
Please see reproduction steps

### Environment

* react-native-code-push version: 6.3.0
* react-native version: 0.63.2 custom core
* iOS/Android/Windows version: all
* Does this reproduce on a debug build or release build? => Debug
* Does this reproduce on a simulator, or only on a physical device? => N/A

**Comment by andreidubov** [comment]
Hi @luatnd 
Thanks for reporting!

Thanks for this case, we will try to fix it as soon as possible.

**Comment by yfuks** [comment]
Hi

I was also able to reproduce the issue with
```
"react-native": "^0.63.3",
```

Working fine with
```
"react-native": "0.63.3",
```

**Comment by snowpardx** [comment]
@yfuks your issue seem to be different one, related to semver version, which is discussed in #1676 so if you have a working example on which we can try to repro, could you please share it in the aforementioned issue?

**Comment by n-kurdiukov-akvelon** [comment]
I've created the [PR:1104](https://github.com/microsoft/appcenter-cli/pull/1104) with fix for appcenter-cli. Let's wait review and release.

**Comment by n-kurdiukov-akvelon** [comment]
It's fixed in https://github.com/microsoft/appcenter-cli/releases/tag/v2.7.3

**Comment by maxired** [comment]
@n-kurdiukov-akvelon I have a similar issue if using ` "react-native": "github:jitsi/react-native#efd2aff5661d75a230e36406b698cfe0ee545be2",` in my package.json, even when using appcenter version 2.7.3

please tell me if you want me to open a new issue.
