### ISSUE TITLE
Method to determine current JS version

### ISSUE THREAD

**Issue by jdmunro** [Microsoft/react-native-code-push#194]
I checked the docs and I couldn't see a way to determine what the currently running JS bundle version is. 
I've tried ```codePush.getCurrentPackage()``` but it does not return the version number.
Can anyone point me in the right direction or does this functionality need to be implemented?

**Comment by jdmunro** [comment]
Never mind - user error!

**Comment by lostintangent** [comment]
OK :) Let us know if you hit any other issues/etc. Thanks for using CodePush!
