### ISSUE TITLE
Code Push bundle download slow

### ISSUE THREAD

**Issue by codeflows** [microsoft/react-native-code-push#1942]
Hi!

And thanks for an awesome product, we've been happy users of CodePush for many years now!

We have noticed a slowdown in CodePush bundle downloads. Before the summer, our downloads were usually taking just a few seconds and now we're routinely seeing 10-20s on most devices. We checked our bundle size and it hasn't grown significantly.

### Steps to Reproduce
Download a bundle from `https://codepush.blob.core.windows.net/storagev2/...`

### Expected Behavior
Bundle is downloaded in a couple of seconds.

### Actual Behavior
Downloading a 6MB bundle takes a long time.

### Reproducible Demo

`curl https://codepush.blob.core.windows.net/storagev2/... --output blob`

On a 4G connection we're seeing approx 0,5MB/s leading to a download time of 10-20s.

To compare, we're getting 10MB/s on the same connection when downloading a file from Dropbox.

We're located in Helsinki, Finland and were wondering if there has been some changes with regards to the CDN, and whether the CDN has mirrors in Europe? The IP address for `codepush.blob.core.windows.net` resolves to `52.241.88.36` and seems to be located on the US west coast.

### Environment

- Location: Helsinki, Finland
- Tested on Android/iOS devices and via `curl` on a MBP.
- Tested over a regular (unlimited) 4G connection, as well as a cable modem connection + wifi.

Any help is appreciated 👍

**Comment by Zestpond** [comment]
I have same issue. And ios/android has updated but force app and re-open app retry many update

**Comment by yfuks** [comment]
Same issue with slow download on android and iOS.
Located in Paris Europe.

**Comment by andreidubov** [comment]
Hello everybody, and sorry for the late response.

Recently we had an incident on the Azure side that could lead to this issue. Do you still experience such a problem?

**Comment by Ankarrr** [comment]
@andreidubov Hi. Yes, we still experience problems like this.

**Comment by codeflows** [comment]
We managed to shrink our bundle size considerably, so the immediate problem disappeared for us.

But downloading still seems slow, `curl` :ing from https://codepush.blob.core.windows.net/ still only gives me an average download speed of 500k/s on a 100Mbit/s wired connection.

**Comment by VrajSolanki** [comment]
@andreidubov This is still happening, with the build downloads taking considerable amount of time to download. At the same time the 503 issue also keeps happening. 
Have been using code-push very frequently for OTA pushes. These issues have started poping up since a month back. 
Please suggest, what can be done here ?

**Comment by andreidubov** [comment]
Hi @VrajSolanki,
Thanks for reporting!

I don’t think both of these problems are related, but we are Investigating them. You can find more detailed information about 503 issue here https://github.com/microsoft/react-native-code-push/issues/1952.

**Comment by VrajSolanki** [comment]
@andreidubov in addition to download issue, seems like the code push checkUpdate itself takes too much time to come back and code push gets delayed.
thank you so much. 
if you need anything from my end like curl or something, would be glad to share.

**Comment by andreidubov** [comment]
@VrajSolanki Yes, I think it would be useful for us to find out your curl, as well as your location if it's not confidential. Thanks for your participation.

**Comment by ruslan-bikkinin** [comment]
Hi @VrajSolanki do you have a chance to look at this?

**Comment by codeflows** [comment]
Hi again!

We're currently experiencing super slow download speeds again. We have a couple of apps with bundle sizes from 3MB to about 5MB and all are downloading painfully slow. (Download speeds were just fine this afternoon EET).

One thing I noticed:

Downloading our bundle (4,8MB) from the AppCenter UI's "Download Bundle" button takes a couple of seconds, peaks at 1,5MB/s and uses this host: https://codepush.blob.core.windows.net/storagev2/...

While inside our app, the CodePush SDK uses https://codepushupdates.azureedge.net/storagev2/... for the download instead and the download speed is about 20kB/s as I write this. Updating the bundle in the app takes about 5 minutes.

Pinging the slow host is quick and has no packet loss for me:

```
ping codepushupdates.azureedge.net
PING a1879.dscw14.akamai.net (62.183.170.106): 56 data bytes
64 bytes from 62.183.170.106: icmp_seq=0 ttl=59 time=10.385 ms
64 bytes from 62.183.170.106: icmp_seq=1 ttl=59 time=11.212 ms
64 bytes from 62.183.170.106: icmp_seq=2 ttl=59 time=14.656 ms
64 bytes from 62.183.170.106: icmp_seq=3 ttl=59 time=9.144 ms
64 bytes from 62.183.170.106: icmp_seq=4 ttl=59 time=11.595 ms
64 bytes from 62.183.170.106: icmp_seq=5 ttl=59 time=12.274 ms
...
--- a1879.dscw14.akamai.net ping statistics ---
20 packets transmitted, 20 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 9.144/11.226/15.099/1.670 ms
```

Are you being throttled by Akamai? 😅 Sorry to throw wild guesses. Anyways, happy to provide more info e.g. over email and help debug this thing. Thanks!

**Comment by codeflows** [comment]
Hi! Reporting back, right now download speed from  https://codepushupdates.azureedge.net/ is again as fast from https://codepush.blob.core.windows.net/ ... Would be interesting to get to the bottom of this, as we're now wary of doing new CodePush releases (disabled our latest deployments yesterday to make sure clients aren't stuck downloading.)

**Comment by julianD77** [comment]
Did you ever make any progress getting to the bottom of this issue @codeflows? We have also been experiencing issues with CodePush that may also have been caused by this.

**Comment by codeflows** [comment]
@julianD77 with regards to the download speed, not really (not actively maintaining the project I was referring to anymore.)

Our bigger problem ended up being the fact that the `checkUpdate` call was slow quite often, and we waited for this at app start-up time. For this, we simply implemented a basic timeout for the `checkUpdate` part only so that our clients could proceed in case the API was slow. We did this by calling the lower level APIs, so basically copying what `CodePush.sync()` does but adding a timeout.

Something like this:

```typescript
import CodePush from 'react-native-code-push'

const withTimeout = <T>(operation: () => Promise<T>, timeoutSeconds: number): Promise<T> => {
  const timeout = delay(timeoutSeconds * 1000).then(() => {throw new Error('timeout')})
  return Promise.race([timeout, operation()])
}

const doUpdate = async () => {
  const update = await withTimeout(() => CodePush.checkForUpdate(), 5)
  if (update.failedInstall) {
     // ...
  } else {
    const localPackage = await update.download()
    await localPackage.install()
  }
}
```

**Comment by julianD77** [comment]
Thanks, that really useful - I appreciate the detail @codeflows 🙏🏻
