### ISSUE TITLE
Receiving Status code 500 with error "Internal server error"

### ISSUE THREAD

**Issue by tristanyong** [microsoft/react-native-code-push#1944]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. run code-push release-react OutsidePlatform/Outside-App-Android android

### Expected Behavior
What you expected to happen?
Bundle gets uploaded to 
appcenter

### Actual Behavior
What actually happens?
Following error is received: [Error]  { "statusCode": 500, "message": "Internal server error", "activityId": "c376c41f-c2f3-4d77-b28d-0b5f01092945" }
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project
N.A
### Environment

* react-native-code-push version: ^6.1.1
* react-native version: 0.61.5
* iOS/Android/Windows version: n.a
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? n.a

(The more info the faster we will be able to address it!)

**Comment by nfjones87** [comment]
Why was this closed? I am having the exact same issue, 10 hours later. Running code-push release kicks a 
 { "statusCode": 500, "message": "Internal server error", "activityId": "a52bdcc7-fccb-4d87-a20b-917af7b4550a" }

**Comment by HeMa321** [comment]
same ...

**Comment by Zestpond** [comment]
same . So In android & ios update every time when open app !!! Pls check. Thanks

**Comment by MAhtishamShahzad** [comment]
same

**Comment by OmarBasem** [comment]
Any solutions??
