### ISSUE TITLE
How to build my own server?

### ISSUE THREAD

**Issue by wcly** [microsoft/react-native-code-push#1949]
the app center server form microsoft is not stable for Chinese user

**Comment by 452MJ** [comment]
自建服务器用这个 https://github.com/lisong/code-push-server

**Comment by ruslan-bikkinin** [comment]
Hi @wcly and thanks for contacting us.

Currently CodePush supports only it's own server for managing updates, deployments and so on. This is something we would definitely look into and investigate further though as we've had other requests. I'll run it by the rest of the team and see if this is something we can accomplish in the future.
