### ISSUE TITLE
App Center Not Updating the status of Code Push for the client in real time.

### ISSUE THREAD

**Issue by VrajSolanki** [microsoft/react-native-code-push#1958]
### Steps to Reproduce
1. Just trigger a code push
2. login to your app-center
3. check for the code push updates

### Expected Behavior
Up until last month the code push updates about downloads and installs was almost realtime and most accurate.

### Actual Behavior

![image](https://user-images.githubusercontent.com/28093589/96000098-694c0f00-0deb-11eb-997a-aefc07b553ec.png)

App Center taking way too long to show the code push status
The counts are not updated accurately, ref shows -2
I believe the issue is more on the handshake of Code Push and App Center rather than react-native application

### Environment

* react-native-code-push version: 5.5.2
* react-native version: 0.57.8
* iOS/Android/Windows version: iOS
* Does this reproduce on a debug build or release build? Release Build
* Does this reproduce on a simulator, or only on a physical device? App Center

**Comment by andreidubov** [comment]
Hi @VrajSolanki ,
Thanks for reporting!

A few days ago we saw an error with recording metrics on our part. Now everything looks stable and I am registering all the metrics on our side. Also if you are using RNCP lower than [v.5.7.0](https://github.com/microsoft/react-native-code-push/releases/tag/v5.7.0) then this problem may be using our legacy service, which is currently experiencing low availability. We are currently in the process of restoring it (see #1952 ). You can monitor your situation with metrics within a week and if it persists, re-inform us about it.

**Comment by VrajSolanki** [comment]
Thanks @andreidubov, I thought so that it might be linked just wanted a confirmation.

**Comment by ruslan-bikkinin** [comment]
Hi @VrajSolanki do you still experiencing the problem?
