### ISSUE TITLE
Usage in windows UWP with react-native-windows 0.61+

### ISSUE THREAD

**Issue by giregk** [microsoft/react-native-code-push#1960]
I'm using react-native-windows 0.61.14, which is implemented in C++.
Could you explain how I could add react-native-codepush to my windows project in that case ?

Thank you very much

**Comment by alexChernyatiev** [comment]
Hi @giregk,
Thanks for reporting!

Sorry but now we have problem with compatibility that why it doesn't work. We will investigate it and will keep you updated.

**Comment by giregk** [comment]
ok, thank you @alexChernyatiev
