### ISSUE TITLE
[Android ] React Native Failed to release a CodePush update.  

### ISSUE THREAD

**Issue by jotish** [microsoft/react-native-code-push#1964]
### Issue:
Whenever `project.ext.react` is not present in the `build.gradle` file the code push release fails without much information.

### Screenshot

<img width="1138" alt="Screenshot 2020-10-24 at 12 42 23 AM" src="https://user-images.githubusercontent.com/3390136/97044482-ce44f900-1591-11eb-88f8-af955739f0a1.png">

<img width="948" alt="Screenshot 2020-10-24 at 12 43 23 AM" src="https://user-images.githubusercontent.com/3390136/97044601-f0d71200-1591-11eb-9675-512ef6d34bbb.png">

### Steps to Reproduce
1. In the android folder, within build.gralde file if `project.ext.react` is not present. The build fails silently

### Expected Behavior

Maybe we can display a proper error that `project.ext.react` is required.

### Actual Behavior
What actually happens?

  
<img width="948" alt="Screenshot 2020-10-24 at 12 43 23 AM" src="https://user-images.githubusercontent.com/3390136/97044728-23810a80-1592-11eb-876a-31dffd7eca20.png">
<img width="1138" alt="Screenshot 2020-10-24 at 12 42 23 AM" src="https://user-images.githubusercontent.com/3390136/97044734-267bfb00-1592-11eb-9206-fc4a286536f8.png">

### Environment

* appcenter version 2.7.1

**Comment by alexandergoncharov** [comment]
Hi @jotish ,
Thanks for reporting!

Unfortunately, I can't reproduce this issue. Could you please provide some demo app with reproducing issue and reprosteps? I would like to reproduce and investigate it.
Please let me know if you have any questions.

**Comment by DmitriyKirakosyan** [comment]
Closing as stale.
