### ISSUE TITLE
Question: support for Hermes on iOS

### ISSUE THREAD

**Issue by osdnk** [microsoft/react-native-code-push#1966]
We're quite advanced in releasing Hermes on iOS (https://github.com/facebook/react-native/pull/29914). Do you have any plans for supporting code-push on iOS for Hermes?

**Comment by andreidubov** [comment]
Hi @osdnk, 
Thanks for your question and information.

Yes, in the future we will definitely pay attention to this, but at the moment we have a number of other tasks. As soon as we have the opportunity and we receive enough requests from the customers we will add support for Hermes on iOS.

**Comment by mrousavy** [comment]
The 0.64 release is pretty much around the corner and I've got my iOS running stable on hermes, only thing not working is codepush 😬

**Comment by slorber** [comment]
Ping

RN 0.64 is here :)
https://reactnative.dev/blog/2021/03/12/version-0.64

Was wondering if we can reliably have OTA for iOS + Android on Hermes with CodePush?

**Comment by SudoPlz** [comment]
Guys have you tested and it's not working?
This guy has been using hermes with codepush without issues https://github.com/microsoft/react-native-code-push/issues/1986#issuecomment-759345497 afaik.

@andreidubov do you know for a fact that it wouldn't work?

**Comment by mrousavy** [comment]
I'm also using codepush on Hermes without any issues. I think this issue can be closed - do you guys have any problems getting it working? @SudoPlz @osdnk @slorber

**Comment by slorber** [comment]
No problem, didn't actually try, was just wondering if it was working or not :)
