### ISSUE TITLE
codePushStatusDidChange reports UNKNOWN_ERROR frequently in production

### ISSUE THREAD

**Issue by watadarkstar** [microsoft/react-native-code-push#1970]
### Steps to Reproduce

Launch the app and sometimes `codePushStatusDidChange` fails for an unknown reason and the status is `codePush.SyncStatus.UNKNOWN_ERROR`

What does `UNKNOWN_ERROR` usually mean? What are some examples of reasons why the status would be `UNKNOWN_ERROR`? I can't seem to find docs on this.

### Expected Behavior

`codePushStatusDidChange` does not report `codePush.SyncStatus.UNKNOWN_ERROR` and tells us a bit more about the error to give us some context.

### Actual Behavior

`codePushStatusDidChange` reports `codePush.SyncStatus.UNKNOWN_ERROR`

### Reproducible Example

Here is my code:
https://gist.github.com/watadarkstar/396485efa2b9e44f23fddaac2b3534ec

### Environment

* "react-native-code-push": **"^6.3.0",**
* "react-native": **"0.63.2",**
* iOS/Android/Windows version: **iOS - iPhone XR**
* Does this reproduce on a debug build or release build? **Release** 
* Does this reproduce on a simulator, or only on a physical device? Not sure.

**Comment by IAmSudhirGupta** [comment]
Able to fix this issue?

I'm also getting UNKNOWN_ERROR (Releae Debug mode) with react-native-0.59 & react-native-code-push-5.6.3.

**Comment by watadarkstar** [comment]
@IAmSudhirGupta I have not been able to fix this yet.

**Comment by watadarkstar** [comment]
Looking at the code more closely, it would be nice if we could bubble this error up instead of just sending an unknown status with no context: 

https://github.com/microsoft/react-native-code-push/blob/0a3db5a139991e5a103576a7d3ad581b8fe523ca/CodePush.js#L507

**Comment by deggertsen** [comment]
Running into this issue as well. It would be nice if there were more details provided in the error message as this is extremely difficult to debug.
