### ISSUE TITLE
Question : How many times can we call CodePush.sync() in an app?

### ISSUE THREAD

**Issue by Yandamuri** [microsoft/react-native-code-push#1972]
I have called CodePush.sync() in my roor file as follows,

      CodePush.sync({ 
		updateDialog: true, 
		installMode: CodePush.InstallMode.IMMEDIATE, 
		checkFrequency: CodePush.CheckFrequency.ON_APP_START,
       });

I would like to call `CodePush.sync()` once again in my app.js file where i can get dynamic deployment key

     CodePush.sync({
            deploymentKey: deploymentKey
     });

If i push code to deployment key which is assigned in app.js, My app never receives those updates. But if i push the code to the deployment key which i gave in xml file, My app receives those updates. It seems like `CodePush.sync()` is not being called second time.

Can anybody confirm that `CodePush.sync()` cannot be called second time? or If i am wrong in this regard please let me know what the issue is in above described scenario.

**Comment by ahartzog** [comment]
Call it as many times as you like. We call it on app start and then also every 60 seconds.

**Comment by Yandamuri** [comment]
I didn't mean to call same instance multiple times. But calling multiple instances. Say I will call in app startup and then in app.js and then somewhere in some other .js file. is it allowed?
