### ISSUE TITLE
🐛 Can not disable a release via promote ([Warning] The uploaded package was not promoted because it is identical to the contents of the targeted deployment's current release.)

### ISSUE THREAD

**Issue by A-Tokyo** [microsoft/react-native-code-push#1973]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

Attempting to disable a release via the `promote` command results in a `identical contents` error. Which doesn't make sense since we are only interested in disabling the release.

### Steps to Reproduce
1. `yarn code-push promote $CODE_PUSH_APP_NAME $CODE_PUSH_DEPLOYMENT_NAME $CODE_PUSH_DEPLOYMENT_NAME --disabled true --noDuplicateReleaseError true --label $LABEL`

### Expected Behavior
What you expected to happen?
The release should be disabled

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
```
[Warning] The uploaded package was not promoted because it is identical to the contents of the targeted deployment's current release.
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:"^6.3.0",
* react-native version:"0.63.3",
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? cli

(The more info the faster we will be able to address it!)

**Comment by CyberMew** [comment]
I found that you can use the rollback function or just go to the UI and disable that latest release.

**Comment by A-Tokyo** [comment]
@CyberMew I found out that the ideal way of disabling a release is using the `patch` command:

```
yarn code-push patch $APP_NAME $DEPLOYMENT_NAME --disabled true
```

If you want the above command to always exit with success even if no release was disabled you can add ` || : ` to the end of the line.
