### ISSUE TITLE
Unable to resolve module './RestartManager'

### ISSUE THREAD

**Issue by NKGS** [microsoft/react-native-code-push#1978]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Upgrade react native to 0.63.3
2. Update react-native-codepush to 6.4.0
3. Try to build release app using following steps
 -  cd android && ./gradlew clean && cd ..
 -  npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

This command gives error :
![Screenshot from 2020-11-07 11-35-11](https://user-images.githubusercontent.com/39052061/98433694-4dd4db00-20ef-11eb-8239-dd1dd4858e38.png)

### Expected Behavior
What you expected to happen?
This error should not be produced

### Actual Behavior
What actually happens?
![Screenshot from 2020-11-07 11-55-09](https://user-images.githubusercontent.com/39052061/98433769-2e8a7d80-20f0-11eb-9591-2964dbaf6aa5.png)

### Reproducible Demo
import React, { Component } from 'react';
import { LogBox, View, Text } from 'react-native';
import codePush from "react-native-code-push";

class App extends Component {

    componentDidMount() {
        LogBox.ignoreAllLogs(true)
    }

    render() {
        return (
            <View>
                <Text>Welcome to hellow world !!Codepush</Text>
            </View>
        );
    }
}

export default codePush((App));

### Environment

* react-native-code-push version: 6.4.0
* react-native version: 0.63.3
* iOS/Android/Windows version: Android: 29 SDK
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? yes
* React Version :  "17.0.1"

Package.json
`
`{
    "name": "Test",
    "version": "0.0.1",
    "private": true,
    "scripts": {
      "start": "node node_modules/react-native/local-cli/cli.js start",
      "test": "jest"
    },
    "dependencies": {
      "@react-native-community/async-storage": "^1.8.1",
      "@react-native-community/cli-platform-android": "^4.13.0",
      "@react-native-community/datetimepicker": "^3.0.4",
      "@react-native-community/netinfo": "^5.9.7",
      "@react-native-firebase/app": "^8.4.7",
      "@react-native-firebase/messaging": "^7.9.2",
      "accordion-collapse-react-native": "^0.4.0",
      "axios": "^0.21.0",
      "base64-arraybuffer": "^0.2.0",
      "lodash": "^4.17.20",
      "moment": "^2.29.1",
      "native-base": "^2.13.14",
      "react": "17.0.1",
      "react-native": "0.63.3",
      "react-native-circular-progress": "^1.3.6",
      "react-native-code-push": "^6.3.0",
      "react-native-device-info": "^7.0.2",
      "react-native-document-picker": "^4.1.0",
      "react-native-gesture-handler": "^1.8.0",
      "react-native-html-to-pdf": "^0.8.0",
      "react-native-image-picker": "^2.3.4",
      "react-native-inappbrowser-reborn": "^3.5.1",
      "react-native-input-outline": "^1.0.2",
      "react-native-modal": "^11.5.6",
      "react-native-outline-input": "^1.0.8",
      "react-native-reanimated": "^1.13.1",
      "react-native-rename": "^2.5.0",
      "react-native-router-flux": "^4.2.0",
      "react-native-screens": "^2.12.0",
      "react-native-speedometer": "^1.0.5",
      "react-native-svg": "^12.1.0",
      "react-native-svg-charts": "^5.4.0",
      "react-native-swipe-list-view": "^3.2.5",
      "react-native-vector-icons": "^7.1.0",
      "react-native-view-overflow": "0.0.5",
      "react-native-view-pdf": "^0.11.0",
      "react-redux": "^7.2.2",
      "redux": "^4.0.5",
      "redux-logger": "^3.0.6",
      "redux-saga": "^1.1.3",
      "redux-storage": "^4.1.2",
      "redux-storage-engine-reactnativeasyncstorage": "^1.0.7",
      "rn-fetch-blob": "^0.12.0",
      "save": "^2.4.0"
    },
    "devDependencies": {
      "@babel/core": "^7.12.3",
      "@babel/runtime": "^7.12.1",
      "babel-jest": "^26.6.2",
      "jest": "^26.6.2",
      "jetifier": "^1.6.6",
      "metro-react-native-babel-preset": "^0.63.0",
      "react-test-renderer": "17.0.1",
      "tslint-eslint-rules": "^5.4.0",
      "@react-native-community/eslint-config": "^2.0.0",
      "eslint": "^7.12.1"
    },
    "jest": {
      "preset": "react-native"
    }
  }
  `
`
Kindly help to solve this issue as it is a blocker for App Release.

**Comment by plus24-library** [comment]
To reload the app press "r"
To open developer menu press "d"

error: bundling failed: Error: Unable to resolve module `./RestartManager` from `node_modules/react-native-code-push/CodePush.js`:

**Comment by plus24-library** [comment]
[v6.3.0]

**Comment by plus24-library** [comment]
react-native start --reset-cache
helped
