### ISSUE TITLE
Report status failed

### ISSUE THREAD

**Issue by xralphack** [microsoft/react-native-code-push#1982]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. release new code push version
2. click button for check update on ios simulator
3. download new version

### Expected Behavior
It did update, however report status show failed

2020-11-13 18:47:31.105769+0800 [60251:1694267] [javascript] [CodePush] Reporting binary update (3.16)
2020-11-13 18:47:31.105943+0800[60251:1694267] [javascript] [CodePush] Report status failed: ...

I can see installed number incremented on appcenter codepush ui

### Environment

* react-native-code-push version: 6.4.0
* react-native version: 0.63.3
* iOS/Android/Windows version: iOS 13.6
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? simulator

**Comment by gustavopch** [comment]
Getting the same with:
- react-native-code-push version: 6.4.0
- react-native version: 0.63.4
- Android version: Android 9
- Does this reproduce on a debug build or release build? I've only tested on a debug build
- Does this reproduce on a simulator, or only on a physical device? I've only tested on a physical device

**Comment by rajscet** [comment]
same error
