### ISSUE TITLE
How to set download only on wifi

### ISSUE THREAD

**Issue by CyberMew** [microsoft/react-native-code-push#1983]
I would like to configure it to **only** check and/or download (especially download) when on **wifi**, is this possible? I do not see any configurable settings on this. Or if there is a workaround?

**Comment by fabricio0915** [comment]
You could use [https://github.com/react-native-netinfo/react-native-netinfo](https://github.com/react-native-netinfo/react-native-netinfo) to discover if there is an wifi connection and then check manually the updates from code push server.

**Comment by CyberMew** [comment]
How do i emulate the current automated behaviour using MANUAL setting?
