### ISSUE TITLE
Unable to find a matching configuration of project :react-native-code-push: upgrade RN to v 0.63.2.   

### ISSUE THREAD

**Issue by yrjwcharm** [microsoft/react-native-code-push#1984]

**Comment by hyun940630** [comment]
Same problem🥲

**Comment by fabricio0915** [comment]
Appers you not complete the setup with android, please follow the steps in the setup for RN 60+ https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md

**Comment by yrjwcharm** [comment]
@fabricio0915  don't soluve !!! I already configured  it.

**Comment by hyun940630** [comment]
I solved this problem.

I reset and `npx react-native start --reset-cache` succeeded!
