### ISSUE TITLE
[BUG] CodePush Releases only updating once

### ISSUE THREAD

**Issue by LuisRodriguezDev** [microsoft/react-native-code-push#1985]
Hi! This last week we've been experimenting with CodePush updates and realized that the releases only update once on a given device (after doing `appcenter codepush release-react -a <ownerName>/MyApp` multiple times, we only get the first one, and on the subsequent calls to `codePush.checkForUpdate()` after the first update is applied, we always receive that the app is up to date), and that if we want to do multiple updates, we have to delete and reinstall the app. 

Are there any solutions for this, or this is the default behaviour? We'd like the app to be updated on the devices for every codepush release we deploy without them having to uninstall and reinstall the app.

So far we have tried

1) with this set of codePush options:

```
codePush({ 
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.IMMEDIATE,
  mandatoryInstallMode: codePush.InstallMode.IMMEDIATE,
})
```

And 2) Setting `checkFrequency: codePush.CheckFrequency.MANUAL`, and inside our code, on a wrapper screen, use:

```
    codePush.checkForUpdate(CODEPUSH_DEPLOYMENT_KEY).then((update) => {
      if (!update) {
        Alert.alert("The app is up to date!");
      } else {
        Alert.alert(
          "The app is NOT up to date!",
          "Update data - appVersion: ${update.appVersion} description: ${update.description} isMandatory: ${update.isMandatory} label: ${update.label}"
        );
        
        codePush.sync({
          deploymentKey: CODEPUSH_DEPLOYMENT_KEY,
          updateDialog: {},
          installMode: codePush.InstallMode.IMMEDIATE,
          mandatoryInstallMode: codePush.InstallMode.IMMEDIATE,
        });
      }
    });
```

And the same thing happens, the first time the app is installed "The app is NOT up to date!" is displayed, the app updates, and then we do another codepush release from the terminal, close and open the app, and "The app is up to date!" is displayed, when it should update to that last version.

We also tried running `codePush.clearUpdates();` before the `checkUpdate()` code but the same thing happens. Any help?

**Comment by owlstronaut** [comment]
Hey @LuisRodriguezDev! Thanks for getting in touch. I'm not seeing the same issue.

I just set up a [barebones react-native android app with your same settings](https://github.com/owlstronaut/CodePush-RN-Android)

```javascript
let codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.IMMEDIATE,
  mandatoryInstallMode: codePush.InstallMode.IMMEDIATE
};
App = codePush(codePushOptions)(App);
```

- If I install & open the app (v0), restarting the app will check for the update (v1), and it will be applied on the next restart.
- If I install & open the app (v0), create 2 codepush releases (v1 & v2), restart the app will detect the codepush releases, and I'll be on the latest (v2) on next restart.

I then tried with your manual code as well, and found the same thing. I would have to force-close the app to trigger the update, but certainly never have to uninstall the app. Could it be that you are putting the app in the background and not closing it? It may check for update on resume, but I don't think it would update until it had a full restart.

**Comment by raen79** [comment]
I am running into the same issue. After the first update, the app doesn't update anymore.

**Comment by raen79** [comment]
@owlstronaut the issue is not as you describe. The following is the issue:

1. Install the app
2. Push an update to codepush
3. Open the app and update
4. Push a second update to codepush
5. Open the app

After step 5, updates no longer download.

**Comment by quocthanh2694** [comment]
Same issue. Anyone help?

**Comment by NiuGuohui** [comment]
This is a very serious problem, can anyone help?

**Comment by MajidNajafi** [comment]
this might help: https://github.com/microsoft/react-native-code-push/issues/2148#issuecomment-943161890

**Comment by voids** [comment]
Same issue.
It works when set mode to CodePush.InstallMode.IMMEDIATE,  or explicit call CodePush.restartApp(),
and then, CodePush. getUpdateMetadata() is not null.

**Comment by ZaharGusyatin** [comment]
any updates? becouse it`s working only with (IOS)CodePush.InstallMode.IMMEDIATE and CodePush.restartApp().
I want to make quiet update, if my update doesnt REQUIRED
On android I can`t reproduce it...
Help guys!
