### ISSUE TITLE
Support for Hermes on iOS (RN 0.64)

### ISSUE THREAD

**Issue by mrousavy** [microsoft/react-native-code-push#1986]
The first release candidate of 0.64 relased (React Native 0.64-rc0), which includes support for using the Hermes JS Executor on iOS.

While it's still a pre-release, it makes sense to support it once 0.64 officially releases, as now CodePush does not work with hermes enabled on iOS.

Is this already planned?

**Comment by mrousavy** [comment]
Of course the `appcenter codepush` command needs to be able to create the Hermes bundle on iOS first, so I've created an issue for that here: https://github.com/microsoft/appcenter-cli/issues/1164

**Comment by gilbertl** [comment]
On app is on rc64-2 with Hermes enabled on iOS. I just made a codepush OTA update to our app and it worked perfectly.

What am I missing?

**Comment by mrousavy** [comment]
@gilbertl how did you create the bundle?

**Comment by gilbertl** [comment]
We run

`appcenter codepush release-react -d #{ENV['IOS_CODEPUSH_DEPLOYMENT_NAME']} -a #{ENV['APPCENTER_USERNAME']}/#{ENV['IOS_APPCENTER_APP_ID']} --target-binary-version \"#{targetVersion}\" --description \"#{release_notes}\" --disable-duplicate-release-error`

to bundle and release the update

**Comment by a-eid** [comment]
@mrousavy could you please let us know if this works for you ( with hermes enabled on IOS ) ?

**Comment by mrousavy** [comment]
Works for me now. Not sure what the original issue was, maybe I had a weird `node` version.

**Comment by ivanmoskalev** [comment]
@mrousavy @gilbertl The bundle that gets built is an old format jsbundle and not Hermes bytecode.

**Comment by mrousavy** [comment]
@ivanmoskalev can you elaborate? How did you find that out? Does it still run when it's text-based?

**Comment by ivanmoskalev** [comment]
@mrousavy It does run, Hermes supports running JS source. 

How I found this out: in the Appcenter portal there is a button that allows you to download the Codepush update bundle that gets served by the Appcenter to your users. You can access by clicking on a specific CP deployment.

I pressed it and inspected the iOS Codepush bundle manually. It contained JS source. 

When I checked the Android Codepush bundle the same way, it had Hermes bytecode.

Then I checked `appcenter-cli` sources and found out that the algorithm that determines whether the `release-react` should run `hermesc` when building is implemented only for Android.

**Comment by mrousavy** [comment]
I see, that is a problem. I assume this affects overall app performance, as the bundle is not fully optimized in that case. I'll reopen this issue then, hopefully a maintainer might look at this. Could you create an issue at the [appcenter-cli](https://github.com/microsoft/appcenter-cli) repo in the meantime? @ivanmoskalev 

cc @alexandergoncharov or other maintainers

**Comment by ivanmoskalev** [comment]
I went ahead and created [microsoft/appcenter-cli#1399](https://github.com/microsoft/appcenter-cli/issues/1399)

**Comment by alexandergoncharov** [comment]
Hi there,

Thanks for reopening the issue.

Hermes for IOS is on our roadmap but we don't have ETA for this.
We will do it as soon as possible and will keep this issue and others posted.


Thanks,
Alexander

**Comment by bryansum** [comment]
Probably fine to close this issue right? It being open made me think it wasn't supported yet (it is!). Excited to try this out
