### ISSUE TITLE
After downloading the package the update isn't installing

### ISSUE THREAD

**Issue by ajoykarmakar** [microsoft/react-native-code-push#1987]
### Expected Behavior
Download the package and install the update every time.

### Actual Behavior
Downloading the updates working for the first time but after the 2nd update package is downloading but it's not installing. This happens with android device and emulator both. I need to clear the app data and then working fine. 

### Environment

* react-native-code-push version: ^6.4.0
* react-native version: 0.63.2

**Comment by LuisRodriguezDev** [comment]
The same thing happens to me. How do you clear the app data? Uninstalling and re-installing the app?

**Comment by tdoran** [comment]
Experiencing the same here.
Seems like we're experiencing the same issue as detailed [here](https://github.com/microsoft/react-native-code-push/issues/1904) and [here](https://github.com/microsoft/react-native-code-push/issues/2020)

**Comment by SutharRohit** [comment]
Hi,

I am getting the same issue in iOS only, but for the android it is working fine.

```
"react-native": "0.66.4",
"react-native-code-push": "^7.1.0",
```

tried all the above solutions, but did not get success.
