### ISSUE TITLE
Build error: 'CodePush/Codepush.h' file not found from AppDelegate.m

### ISSUE THREAD

**Issue by xuan9230** [microsoft/react-native-code-push#1988]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
Followed this "Getting Started" part strictly. But Xcode gives error:

Build error: 'CodePush/Codepush.h' file not found from AppDelegate.m

Seems when I added the package with `yarn add react-native-code-push`, auto linking didn't work. Had to manually add `pod 'CodePush', :path => '../node_modules/react-native-code-push'` to Podfile. This fixes my problem.

### Environment

* react-native-code-push version: 6.4.0
* react-native version: 0.63.3
* iOS/Android/Windows version: ios 14.2 (Xcode 12.2)
* Does this reproduce on a debug build or release build? debug build
* Does this reproduce on a simulator, or only on a physical device? simulator

(The more info the faster we will be able to address it!)

**Comment by IvanKabetskyi** [comment]
same problem after update xcode

**Comment by dabakovich** [comment]
@xuan9230 Did you run the next command?
```$ cd ios && pod install && cd ..```

**Comment by omarkhaled11** [comment]
I am having the same issue with react-native version 0.63.4 and on MacOS BigSur with latest Xcode
any updates on this?

**Comment by brascene** [comment]
Same here, react-native version 0.64.2.

**Comment by Acetyld** [comment]
Any update?

**Comment by bestinepayyappilly** [comment]
any update on this issue ? //commented to keep this alive//

**Comment by shivanitp** [comment]
I'm also facing this issue, does anyone have a solution?
