### ISSUE TITLE
Codepush loads an old version of the code

### ISSUE THREAD

**Issue by maihemboom** [microsoft/react-native-code-push#1996]
### Steps to Reproduce
Tried to codepush my staging Android app (after downloading it from Google PlayStore).

1. appcenter codepush release-react -a <user>/<app>

### Expected Behavior
The new version of the code should be loaded.

### Actual Behavior
A very old version of the code is loaded.

I do get a success message after deploying the command: 
Your target-binary-version "1.1" will be treated as "1.1.X".

Successfully released an update containing the "<path>" directory to the "Staging" deployment of the "<appName>" app.

Am I doing something wrong by only using the command `appcenter codepush release-react -a <user>/<app>`?
Should I update anything else but the code?
There is a change in the app for sure, but it loads an old version of my code.

Thank you for your help!

**Comment by neildevas** [comment]
I'm getting a similar issue on iOS with an app downloaded from TestFlight. I get a success message too and I even see on the app that codepush updates are downloading. However, once I restart the app, my app reverts to the old binary version that was installed from TestFlight, without the codepush changes.

**Comment by maihemboom** [comment]
I think the problem was not declaring it under Production. After adding `-d Production` it works well.
