### ISSUE TITLE
Only update JS and not the assets

### ISSUE THREAD

**Issue by Almouro** [microsoft/react-native-code-push#1998]
Hello,
Is it possible to use CodePush only to update the JS and not the assets?

## Background

The JS bundle for our app is only 2MB, but with all the assets it goes up to 30MB.

If I understand correctly from issues such as [this one](https://github.com/microsoft/appcenter-cli/issues/388), the first download will always be a full download of the 30MB then. 
By the way, is there any plan to change this behavior? Having differential updates from the start would be such a dream 🤩 

CodePush seems like a great solution to hot fix issues in production, but 30MB seems like an excessive first download.
While changing the assets on the fly would be nice, we care more about changing the JS to hotfix bugs.

### Steps to Reproduce

It seemed like bundling React Native without assets was [documented here](https://github.com/microsoft/code-push/tree/v3.0.1/cli#update-contents-parameter) and bundling only the JS used to be the default (a loooong time ago 😅). So we thought that was just possible to do that:

1. Run `react-native bundle  --entry-file index.js --bundle-output ./CodePush/main.jsbundle --dev false --reset-cache`
2. Release to CodePush `appcenter codepush release -a "Org/MyApp -c ./CodePush`

But perhaps this is not actually an option

### Expected Behavior
I would have expected JS to be updated and the assets to remain unchanged.

### Actual Behavior

JS was updated, but all the assets disappeared from the app

### Reproducible Demo

Didn't make one since I think maybe this is not an issue, but just something that isn't possible or not documented at the moment

### Environment

* react-native-code-push version: **6.4.0**
* react-native version: **0.62.2**
* iOS/Android/Windows version: **iOS 14.3**
* Does this reproduce on a debug build or release build? **release**
* Does this reproduce on a simulator, or only on a physical device? **physical**

**Comment by jamesone** [comment]
Did you figure out a way to do this?

**Comment by Almouro** [comment]
@jamesone sadly no 😞

**Comment by jamesone** [comment]
@almirfilho I figured out a solution

You can move your heavy assets out of the JS bundle and into your native ios/android projects. This is what I have done for the few videos which I needed in the app (for UX reasons)

For iOS, I suggest adding your assets in the xcode -> 'Target Name' -> 'Build Phases' -> **'Copy Bundle Resources'** | Add your videos/images in here. You can then directly reference the video/image name in your image/video component

E.g if you add an mp4 named test-video.mp4, you can reference that name in your URI. 

```
<RNVideo
  source={{ uri: "test-video.mp4" }}
  style={{ flex: 1 }}
  onEnd={skipToLogin}
  onError={skipToLogin}
 />
```

**Comment by syxxjgh** [comment]
anyone has resolve this problem ?
i can not resolve all the image asset after update by  codepush
react-native version: 0.64.2
react-native-code-push version: 7.0.2
