### ISSUE TITLE
CodePush bundle size issue

### ISSUE THREAD

**Issue by neeldream11** [microsoft/react-native-code-push#2008]
For our common code base, i have noticed that CodePush bundle size for android and iOS are different.

While we have almost same JS code for android and iOS, the bundle sizes shown in AppCenter are 7.5 MB and 5.9 MB respectively. But the main.jsbundle is of same size for both.

I am unable to find anything related to this. I want  to know is this something default or which direction should i take to know further.

**Comment by anirudhagarwal1** [comment]
Facing the same issue. My guess is this is because of Hermes enabled on android. 
Can someone confirm this and also tell me the reason for the same?

**Comment by anirudhagarwal1** [comment]
@andreidubov Can you help here?

**Comment by Mkaleem-neslit** [comment]
code push bundle size is upto 90 mb . how can i reduce it
