### ISSUE TITLE
Slow down support

### ISSUE THREAD

**Issue by alexandergoncharov-zz** [microsoft/react-native-code-push#2009]
Hi all,
Thanks for using CodePush plugin in your apps!

For providing a better user-experience and making service more reliable, support will slow down, new feature development will pause. We will continue to fix only compatibility issues with new versions and some critical bugs.
For more info and our next plans, please check the info in the main AppCenter repo: https://github.com/microsoft/appcenter#planning

Thanks,
Alexander

**Comment by ball-hayden** [comment]
@alexandergoncharov for the avoidance of doubt, are there any plans to deprecate/remove the CodePush service?

(I'm assuming not based on the above, but we're about to commit to integrating so I'd like to confirm 🙂)

**Comment by alexandergoncharov** [comment]
Hi @ball-hayden,

Thanks for the question!
No, the CodePush service will not be deprecated or removed from AppCenter. It will continue working as usual. :blush:

**Comment by nguyenduclong-ict** [comment]
Image disappear after update, please fix it!

**Comment by Hemistone** [comment]
Hi @alexandergoncharov, is there any plan to make paid plan(business/enterprise plan etc.) for codepush?

I'm keep getting suffered by randomly happening very slow `checkForUpdates` and downloading packages, which sometimes takes over a minute for downloading 7MB bundle file(Some how very ridiculous and awkward user experience for a bloody fast internet speed in South Korea).

This issue seems to be related with limited server/storage resource via _open source-free service_ but since its really critical for our app retention rate, I hope if I can solve this problem by supporting or pay some fees for more faster service.

If you guys are not willing to add a paid plan, I'm considering running my own codepush service if I can. Is this issue a problem that can be solved through running my own codepush service?

**Comment by ball-hayden** [comment]
^ I'd love to see an official open-source CodePush server so we've the option of self-hosting.
There is mention elsewhere of some unofficial ones, but I don't think they have all features implemented.

**Comment by dkahdwk** [comment]
@Hemistone @ball-hayden  The speed issue is driving me crazy. Did you find an alternative?

**Comment by ball-hayden** [comment]
Nope. Maybe @alexandergoncharov might be able to let us know what Microsoft's plans are.

I really hope Microsoft aren't trying to kill CodePush quietly by degrading service until it's unusable. If the plan is to kill it, please just tell us.

The only thing I've found close to CodePush is "Expo Updates", but I haven't really been able to work out whether that properly replaces CodePush's functionality (and whether it works properly outside of the Expo ecosystem).

**Comment by Hemistone** [comment]
@ball-hayden  @dkahdwk 
I've searched and asked some questions to expo team about their professional level(=the paid version) `expo-updates` and `EAS` service, but they gave me answers as below. 

Using expo-updates might be possible on bare RN projects by setting `react-native-unimodules`, but it will not solve some critical functionalities like `mandatory`, `targetVersioning`, and `Admin Backoffice` page like MS AppCenter.

> HI Peter,
> I checked in with our Dev team and here's the answers to your 3 questions:
> 1. I'm curious about statistics about Expo EAS systems' average new bundle download time. What is the average download time and distribution of download time? I would be grateful if you could share any numbers with Expo-updates. (If I set the waiting time limit at 3 sec, 85% of total users will be able to get the new version in South Korea / Expo-updates take 5 sec on average for downloading a 8.5MB bundle ,etc)
> > We don't collect this information so we don't have useful data here.
> 2. Is there any option to force users to wait until download&install is completed for hotfixs or must-do-updates? For now, on codepush there is an optional value of isMandatory which forces users to wait until download/install is complete if the update is mandatory.
> > We don't have this feature currently but it is on our roadmap for development.
> 3. Is there any callback function to get status about OTA updates? On codepush, there is a callback function of returning how much percent of download is complete in real time(4.4/8.5MB), etc.
> > We don't have this at the moment but acknowledge it would be a useful addition.

**Comment by dkahdwk** [comment]
@Hemistone Thank you very much!!!!

**Comment by aqweider** [comment]
Codepush stopped working today, is it related to this announcement? 

<img width="1107" alt="Screenshot 2022-04-10 at 14 41 25" src="https://user-images.githubusercontent.com/11158733/162618648-594dc774-595e-4454-9935-7706c4aefb8f.png">

**Comment by ball-hayden** [comment]
> I really hope Microsoft aren't trying to kill CodePush quietly by degrading service until it's unusable. If the plan is to kill it, please just tell us.

I reiterate this point.

Either support it, or don't.

**Comment by sunweiyang** [comment]
The CodePush service has been down for the past 3.5 hours -- maybe it's related to another AppCenter outage today. https://status.appcenter.ms/incidents/4pw8ddc9d0zy

**Comment by quicksilverr** [comment]
Guys, I'm planning to integrate codepush to our app, is it advisable to integrate in a new app or shall I look for other alternatives?

**Comment by ball-hayden** [comment]
> is it advisable to integrate in a new app

My opinion: no.
Use Expo Updates.

**Comment by Hemistone** [comment]
> I decided to wait and not to use codepush as possible until either codepush team releases paid versions or `expo-updates` gets more matured.

Finally, [might be available in Expo SDK 50 expo-updates](https://expo.dev/changelog/2023/12-12-sdk-50-beta) 😎

It would be painful to adopt `expo-updates` in old react-native-cli projects, but at least from now on I won't use CodePush for OTA updates for production level services.

**Comment by WilliamWelsh** [comment]
> Finally, [might be available in Expo SDK 50 expo-updates](https://expo.dev/changelog/2023/12-12-sdk-50-beta) 😎

But that's not available for React Native Windows users :(

**Comment by johnf** [comment]
The retirement is now official - https://learn.microsoft.com/en-au/appcenter/retirement 

It looks like maybe the code push server is going to be open-sourced. (At least there is an email to ask for access)

@MikhailSuendukov @AnatolyPristensky What does the future of this project hold? Will it be deprecated?

**Comment by lucen-ms** [comment]
We will archive all public repositories after March 31 2025.

**Comment by WilliamWelsh** [comment]
> We will archive all public repositories after March 31 2025.

All *appcenter* repositories right?
