### ISSUE TITLE
Is it possible to customize the update confirmation window?

### ISSUE THREAD

**Issue by Yandamuri** [microsoft/react-native-code-push#2010]
### Steps to Reproduce
1. Please place this line codePush.sync({ updateDialog: true, installMode: codePush.InstallMode.IMMEDIATE }); in componentDidMount()
2. Then try to modify anything in the code and push

### Expected Behavior
The expected Behavior is having flexibility to style the update confirmation window

### Actual Behavior

![Screenshot_1609330764](https://user-images.githubusercontent.com/31983789/103351617-c80b5580-4ac9-11eb-871a-d9072dc7ca0e.png)

**Comment by vinagrito-getpocketful** [comment]
@Yandamuri 
@lionerezpk and I were looking for this type of behavior and [found this](https://github.com/microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushoptions). Which states that you can pass a configuration object. It is not clear that you can only set one button, forcing the customer to perform the update right away...so what we did is setting the `optionalIgnoreButtonLabel` option to `''` (empty string) and... 🎉  That gave us exactly. what you're attempting to achieve.
