### ISSUE TITLE
Is there a way to rollback to the original AppStore version?

### ISSUE THREAD

**Issue by alexfoxy** [microsoft/react-native-code-push#2012]
### Steps to Reproduce
n/a

### Expected Behavior
From looking at the code push documentation it doesn't specify a way to rollback to the original app store version. For example if I release an appstore version 1.0.0 and later push a codepush update to 1.0.0 (v1) is there a way I can get back to the original appstore version. I tried disabling the version in the app center but that did not work. 

Any pointers welcome!

**Comment by rajputrvm** [comment]
+1
