### ISSUE TITLE
Codepush not updating on new release 404 from codepushupdates.azureedge.net

### ISSUE THREAD

**Issue by koreus7** [microsoft/react-native-code-push#2014]
### Steps to Reproduce
1. Deploy a mandatory codepush update
2. Open app
3. Press 'Continue'

### Expected Behavior
The app updates to the new version

### Actual Behavior
The app reverts back to the original binary, ignoring previous codepush updates and the new update.
```
[Wed Jan 06 2021 15:21:44.289]  LOG      Code Push: Checking for updates.
[Wed Jan 06 2021 15:21:46.898]  LOG      Code Push: Downloading package.
[Wed Jan 06 2021 15:21:47.270]  LOG      [CodePush] Received 404 response from https://codepushupdates.azureedge.net/storagev2/[BLOB ID]
```

### Environment

* react-native-code-push version
6.3.0
* react-native version
0.63.2
* iOS/Android/Windows version
iOS 13.4
* Does this reproduce on a debug build or release build?
Both
* Does this reproduce on a simulator, or only on a physical device?
Both

I have double and triple checked the codepush deployment key and figure it is correct since the app does detect the update it just fails to install it.

I can also see the update in appcenter and download the bundle. I notice that the blob ID and base URL is different for this download than the one the app is trying to download.

App Center URL `https://codepush.blob.core.windows.net/storagev2/[Blob ID A]`
Codepush Logs URL `https://codepushupdates.azureedge.net/storagev2/[Blob ID B]`

**Comment by vbro1293** [comment]
@koreus7 Did you manage to get this working?
I had some codepush issues with updating to a new version on the day you reported this issue, appears to be working ok again now though (with no changes made). I didn't manage to get round to debugging it though, so may be unrelated.

**Comment by parth-koshta** [comment]
This issue still exists, shouldn't have been closed.

**Comment by Gamote** [comment]
I can confirm that this is still happening.
```
2023-05-25 16:06:04.065306+0200 Ønskeskyen[99456:9149076] [javascript] [CodePush] Downloading package.
2023-05-25 16:06:04.560066+0200 Ønskeskyen[99456:9149076] [javascript] [CodePush] An unknown error occurred.
2023-05-25 16:06:04.560368+0200 Ønskeskyen[99456:9149076] [javascript] [CodePush] Received 404 response from https://codepush-secondary.blob.core.windows.net/storagev2/...
```

For us is whenever we push 2 updates one after another.

**Comment by jameskennethrobinson** [comment]
Also seeing this.

**Comment by Zakyyy** [comment]
Same here

**Comment by jamesholcomb** [comment]
+1 on this too...both iOS and Android.  I use dynamic deployment keys for staging and production.  I use the HOC to initialize with production, but have the ability to override with staging key + CodePush.sync() call at runtime.

**Comment by DmitriyKirakosyan** [comment]
Please try this workaround:
https://github.com/microsoft/react-native-code-push/issues/2585#issuecomment-1749375271

**Comment by jamesholcomb** [comment]
Thanks @DmitriyKirakosyan.  I tried these steps:

- modify some JS, create and push a new Staging release with `--disabled`
- wait 5 minutes
- enable via the appcenter dashboard web UI
- opened production app from killed state, ran `sync` with Staging keys

But had the same 404 result.

Production app is `react-native-code-push@8.0.2`

**Comment by MikhailSuendukov** [comment]
Since this issue is already closed, let's continue the discussion in an open duplicate with high activity - in this [issue](https://github.com/microsoft/react-native-code-push/issues/2527).
