### ISSUE TITLE
`checkForUpdate` very slow on iOS

### ISSUE THREAD

**Issue by drop-george** [microsoft/react-native-code-push#2019]
### Steps to Reproduce

1. Release updates over codepush to a react-native app on both iOS and Android
2. Open app (triggering the `checkForUpdate` method)

### Expected Behavior
3. The `checkForUpdate` method takes roughly the same amount of time on both iOS and Android

### Actual Behavior
3. The `checkForUpdate` method takes much longer on average on iOS than on Android

Below is a graph showing results of some instrumentation we added. The instrumentation specifically measures the average time taken by the `checkForUpdate` method. 
 
![image](https://user-images.githubusercontent.com/38255501/105056045-bcb0a780-5a41-11eb-9265-6bd92f3b63ea.png)

### Things we've tried: 

* Updated to the latest version of `react-native-code-push`
* Set up a [mitm proxy](https://mitmproxy.org/) on a test device to inspect calls to `https://codepush.appcenter.ms/v0.1/public/codepush/update_check`. We're seeing that this is always quick (`<500ms`), indicating that the slowdown is elsewhere in the `checkForUpdate` block of code

### Environment

* react-native-code-push version: `6.4.1`
* react-native version: `0.63.4`
* iOS/Android/Windows version: Most of our users are on iOS `14.3`
* Does this reproduce on a debug build or release build? Happens on release builds
* Does this reproduce on a simulator, or only on a physical device? Seems to only happen on real devices

### Related issues we've looked at: 

- https://github.com/microsoft/react-native-code-push/issues/1646
- https://github.com/microsoft/appcenter/issues/814

**Comment by Hemistone** [comment]
This issue should not be closed. I'm also getting very bad experience with codepush recently.
- Slow `checkForUpdates`
- Slow bundle downloading
I would rather pay for solving these problems, since it's critical for app retention.
Is there any plan to make business plan(paying option) for more intense support?

**Comment by qasim483** [comment]
this is a valid issue and its happening for ios. checkForUpdates is very very slow compare to android.

**Comment by zereight** [comment]
Me too, same problem happening around the same time
