### ISSUE TITLE
Disabled the latest codepush and the App rollback

### ISSUE THREAD

**Issue by Chi-AnTai** [microsoft/react-native-code-push#2029]
Hi,
I found that when my App update to the latest codepush version(suppose v5) and then disabled the version from App Center, it will update to the previous version(v4) when I restart App. I already use react-native-code-push for a year and my poor memory said in the past it does not work this way, my v5 will stay v5 even if I disabled this version. Can anyone tell me this is expected behavior or a bug? Thanks!

### Steps to Reproduce
1. Codepush the latest version for example v5
2. App update to v5
3. DIsabled the v5 from App Center
4. Restart App
5. App update to previous code push version v4

### Expected Behavior
What you expected to happen?

The v5 version should not rollback to v4 since v5 > v4
### Actual Behavior
What actually happens?

The v5 version rollback to v4

### Environment

* react-native-code-push version: 5.6.0
* react-native version: 0.59.3

(The more info the faster we will be able to address it!)

**Comment by mkaarthick** [comment]
This is still happening
