### ISSUE TITLE
Changes are not reflecting after download and install on IOS 

### ISSUE THREAD

**Issue by jitish2** [microsoft/react-native-code-push#2030]
Hi Code Push Team, I'm facing an issue On IOS after bundle downloaded and Install on IOS devices new changes are not reflecting and android it is working fine.

Check Screenshot of App Center and Code Implementation

App Center Dashboard
<img width="869" alt="Screenshot 2021-02-08 at 9 37 08 PM" src="https://user-images.githubusercontent.com/56391170/107253171-119d7780-6a5c-11eb-8b25-2990156fb212.png">

App.js
<img width="795" alt="Screenshot 2021-02-08 at 10 32 34 PM" src="https://user-images.githubusercontent.com/56391170/107254706-92a93e80-6a5d-11eb-924f-e3c12fe2e395.png">

AppDelegate.m
<img width="965" alt="Screenshot 2021-02-08 at 10 24 23 PM" src="https://user-images.githubusercontent.com/56391170/107253533-6a6d1000-6a5c-11eb-9d9a-8dc857863d0f.png">

### Environment

* react-native-code-push": "^6.4.0"
* react-native": "^0.62.2",
* iOS 10.15.6
* Does this reproduce on a debug build or release build? => Both 
* Does this reproduce on a simulator, or only on a physical device? => Both

Please help me out and Let me know if you need anything else.

**Comment by npjoge** [comment]
I having same issue. +1

**Comment by Biciato** [comment]
I'm having the same issue and logs show this:

2021-03-16 08:17:41.743217-0300 BePay[1352:373134] [javascript] [CodePush] Checking for update.
2021-03-16 08:17:42.888652-0300 BePay[1352:373134] [javascript] [CodePush] Downloading package.
2021-03-16 08:17:44.782845-0300 BePay[1352:373133] [native] Sending `CodePushDownloadProgress` with no listeners registered.
2021-03-16 08:17:45.088156-0300 BePay[1352:373784] 
[CodePush] Applying diff update.
2021-03-16 08:17:45.088334-0300 BePay[1352:373784] 
[CodePush] Verifying hash for folder path: /var/mobile/Containers/Data/Application/87207FE7-B1AD-45E0-81E3-671F42E5DE9B/Library/Application Support/CodePush/847f7f9b9f26d69b076962d3d30e241b0a867c2bcdfc35dfabc1cffa50514a1f
2021-03-16 08:17:45.296074-0300 BePay[1352:373784] 
[CodePush] Manifest string: (
    "CodePush/main.jsbundle:29c695d0a62c3eb1f56ce1ff1e4d223bc08d4e290e03153cbf0ef4d0839964be",
    "CodePush/assets/node_modules/native-base/dist/src/basic/Icon/NBIcons.json:847455488cfa40f5bb722b4fae0cd8b364027f0b695a6f9a2f876ae3c71ab603",
    "CodePush/assets/node_modules/moment-timezone/data/packed/latest.json:7e453bc469cb078cf1f72d68b473002272633802363ee3493311d98c495d6a93",
    "CodePush/assets/node_modules/css-tree/package.json:7cd252b1712172128335e795c76c55b34ea63bb51a2e3cf9b7ba9305c5adcf44",
    "CodePush/assets/node_modules/css-tree/data/patch.json:5d263d5256ffe03fed507823c1d62f252a107d9b86f9451c1929bb5ebf34d8ec",
    "CodePush/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon@3x.png:3ddd0773ed27e23d25789f301731b3ac455ad8be5aa27a0a1b838f89c6d27225",
    "CodePush/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon@2x.png:2b7443a9a58e92ca11a575bdc11598615a57dde305cd8ce70d602606b302cd98",
    "CodePush/assets/node_modules/@react-na
2021-03-16 08:17:45.300838-0300 BePay[1352:373784] 
[CodePush] Expected hash: 847f7f9b9f26d69b076962d3d30e241b0a867c2bcdfc35dfabc1cffa50514a1f, actual hash: fca52e98324dea2cfee187c75c6cfe7c179b543aa7f2009cdef6c7811fcffcae
2021-03-16 08:17:45.301045-0300 BePay[1352:373784] 
[CodePush] The update contents failed the data integrity check.
2021-03-16 08:17:45.311875-0300 BePay[1352:373134] [javascript] [CodePush] An unknown error occurred.
2021-03-16 08:17:45.312034-0300 BePay[1352:373134] [javascript] [CodePush] The update contents failed the data integrity check.

So, we can conclude that it's not getting the right hashes. It's only on iOS

**Comment by raen79** [comment]
We are having the same issue, have you found a solution?

**Comment by raen79** [comment]
With the same data integrity error:

```[javascript] [CodePush] Checking for update.
2021-04-01 18:07:27.985351+0200 paters_rn[62827:6524162] [javascript] [CodePush] Downloading package.
2021-04-01 18:07:28.384039+0200 paters_rn[62827:6534108] [native] Sending CodePushDownloadProgress with no listeners registered.
[CodePush] Applying diff update.
[CodePush] Verifying hash for folder path: /Users/eranpeer/Library/Developer/CoreSimulator/Devices/206E0D93-38F4-4273-A468-D05FC0D84BDE/data/Containers/Data/Application/BD5B1BAE-7B46-488D-AFF8-003FB6EE10CA/Library/Application Support/CodePush/401429e0ef823eb3ef4f091553ade7fce228120ac195ddc3dcfd18ca4e99e2d9
[CodePush] Manifest string: (
"CodePush/main.jsbundle:e2abe4e022d9699100ad1322a9792e47984c3a66e9cecbc9ad2c7da8c5acde54",
"CodePush/assets/locales/en.json:7f9e37482cecda411947d763d2486775b6fb0e590770469207a672a787123db3",
"CodePush/assets/app.json:590f86d6cd11f7aadcbbbd3b368307878c420dc609ed10f0350a70ec82721d0e",
"CodePush/assets/node_modules/react-native/package.json:0087a3a7be0dd03690b6c32626875ac2db1b5b19f4fa2e78f35e15bcb1e92057",
"CodePush/assets/node_modules/css-color-keywords/colors.json:354f1816e82e3aa407d5493a59ff75f6d073d18e39db48e792b3bde951419ff5",
"CodePush/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon@3x.png:3ddd0773ed27e23d25789f301731b3ac455ad8be5aa27a0a1b838f89c6d27225",
"CodePush/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon@2x.png:2b7443a9a58e92ca11a575bdc11598615a57dde305cd8ce70d602606b302cd98",
"CodePush/assets/node_modules/@react-navigation/stack/src/views/assets/back-icon.png:2cdfeb8e5ccde7976f7012fb8cce73
[CodePush] Expected hash: 401429e0ef823eb3ef4f091553ade7fce228120ac195ddc3dcfd18ca4e99e2d9, actual hash: ac957e370d67678f22e843ccd046f1bed67ebe100e62ae56844d8a77822048b6
[CodePush] The update contents failed the data integrity check.
2021-04-01 18:07:28.963611+0200 paters_rn[62827:6524162] [javascript] [CodePush] An unknown error occurred.
2021-04-01 18:07:28.963829+0200 paters_rn[62827:6524162] [javascript] [CodePush] The update contents failed the data integrity check.```

**Comment by jitish2** [comment]
Did anyone get the solution?

**Comment by raen79** [comment]
No, I looked through every file and could not find an issue..

**Comment by raen79** [comment]
This PR fixes the problem for me: #2078, it seems to be caused by foreign (Japanese in my case) characters.

**Comment by jitish2** [comment]
@raen79  I also did the same thing but it won't work for me.

**Comment by Abhinandan-Kushwaha** [comment]
@raen79 I am still facing the same issue. I don't have any foreign characters in my app. When I release an update using Codepush, the changes are not reflected in the iOS app.

**Comment by rhydvik** [comment]
We are having the same issue, I am not seeing any errors while doing code push. It gets installed on the device without any crashes but changes are not reflecting. 

![Screenshot 2021-05-26 at 1 21 22 PM](https://user-images.githubusercontent.com/15020668/119622946-5095e400-be25-11eb-92c6-c4b74586625e.png)

**Comment by gourav-singhal** [comment]
Facing same in android build

**Comment by viveksharma8130** [comment]
I didn't get any kind of error 
Everything is successful but nothing is happen in the app

No New Changes are reflect

**Comment by MatthiasDh** [comment]
Same issue here. Codepush shows installed & downloaded but changes are not reflecting to app.

Android works fine, iOs doesn't

**Comment by MatthiasDh** [comment]
@rhydvik were you able to fix this?

**Comment by rhydvik** [comment]
@MatthiasDh I ended up upgrading the app-center and code push version and it works. I was not able to figure out why it was not working on the earlier version.

**Comment by johnhaup** [comment]
We're facing this on Android only.

```javascript
"appcenter": "^3.0.0"
"appcenter-analytics": "^3.0.0"
"appcenter-crashes": "^3.0.0"
"react-native": "0.63.4"
"react-native-code-push": "^6.3.0"
```

We have verified in Logcat that the bundles downloads and installs and the app restarts from the bundle, but we don't see any changes.

Should we be able to see changes on the Android emulator?

**Comment by RahulPant-coder** [comment]
Its saying **_[CodePush] Reporting CodePush update success_**

**Comment by FadiAboMsalam** [comment]
why was this closed ! i am facing same issue

**Comment by hashkazi00** [comment]
Facing this issue on IOS

**Comment by yadavmurari111** [comment]
facing the same issue in android , build is pushed successfully but changes are not reflecting in app

**Comment by renanbronchart** [comment]
+1 on iOS

**Comment by alexrogo** [comment]
+1 on iOS

**Comment by alexrogo** [comment]
Our problem was that we had overlooked an important step in the documentation.
Actually, some tutorials are completly missing this step.

In your AppDelegate.m file, make sure to import `#import <CodePush/CodePush.h>` and have this line included:
**`return [CodePush bundleURL];`**

@jitish2  set it up correctly, but for us it was the solution.

the file should look like this:
![image](https://user-images.githubusercontent.com/35710230/180450159-6d2d9bbd-4bd5-423a-a821-88f9d0ac1172.png)

**Comment by thenriquedb** [comment]
I managed to solve it by passing the `-m` flag in the command.
Example: `appcenter codepush release-react -a <ownerName>/MyApp-iOS  -m --description "Modified the header color"`

**Comment by vksgautam1** [comment]
+1 on iOS

**Comment by mateomarconi** [comment]
+1 on IOS

**Comment by MoamberRaza** [comment]
+1 Android  is not reflecting newest changes. however i tried by disable multi-deployment and test it by using one production key.

**Comment by mashad6** [comment]
@MoamberRaza did you find any solution? iam facing the same issue

**Comment by MoamberRaza** [comment]
@mashad6  it been fixed now can you share the ( @overrided )  code of MainApplication.java.

**Comment by Overrided** [comment]
Guess I'm tagget by mistake @MoamberRaza ))
Have a good day)

**Comment by mashad6** [comment]
@MoamberRaza
     @ Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }

**Comment by MoamberRaza** [comment]
@mashad6  are you trying to use multi deployment feature. ?  and  you are sure you have followed properly documentation.

**Comment by mashad6** [comment]
@MoamberRaza no i am not using multi deployment. 
 and are convenient assisting me over the whatsapp? you can send me your number on mashadsyed6@gmail.com
 I would really appreciate it. I need to deliver it on urgent basis.
 Thanks

**Comment by hypesol** [comment]
react-native: "0.70.6"
react-native-code-push: "^7.0.5"

Changes are not reflecting on iPhone

**Comment by AnYuku** [comment]
I got the same issue. RN ver 0.66.5 and CodePush ver 7.0.4 (Because ver 8.0.0 cause some error).
I got Reporting Codepush update success (v3). But nothing changed.
My code here:
import React from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';
import codePush from "react-native-code-push";

const App = () => {
  const green = "#00FF00";
  const blue = '#00BFFF';
  const gray = "#888";
  const white = '#FFFFFF';
  const black = '#000';
  const version = {
	V1: {
		name: '0.1.1',
		colorBackground: blue,
		colorFont: black
	},
	V2: {
		name: '0.1.2',
		colorBackground: gray,
		colorFont: white
	}
  }
  const selectedVersion = version.V1;
  return (
    <View 
        style={{
            width: '100%',
            height: '100%',
            backgroundColor: selectedVersion.colorBackground,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center'
        }}>
        <Text 
			style={{
				color: selectedVersion.colorFont,
				fontSize: 25
			}}
        >
			App version {selectedVersion.name}
		</Text>
    </View>
  );
}
const deploymentKey = "o-ok5XyJlOr8vV3VyBW31aqrelcEB1V9YmUw6";

export default codePush({
    checkFrequency: codePush.CheckFrequency.ON_APP_START,
    installMode: codePush.InstallMode.IMMEDIATE,
    deploymentKey: deploymentKey
})(App);

**Comment by xuandac** [comment]
I'm having the same problem on Android. Who can help me ?

**Comment by tgp-fk** [comment]
@yadavmurari111  @MoamberRaza @xuandac anyone of you were able to solve this issue? facing the same on android for a while now.
