### ISSUE TITLE
Fatal Exception: com.facebook.jni.CppException

### ISSUE THREAD

**Issue by kevalvasaniya** [microsoft/react-native-code-push#2031]
facebook::react::Recoverable: Could not open file/data/user/0/appBundleID/files/CodePush/02b7b6fbcec7a4c01f73f83f2524adafbd2473191ea4aeb76f55ba114ac4f102/app.bundle: No such file or directory

I'm getting this issue after update the app and restart it using CodePush.allowRestart() for android 

Anyone can help me to resolve this issue?

**Comment by plus24-library** [comment]
05-21 15:05:56.953  7580  7652 E unknown:ReactNative: ReactInstanceManager.createReactContext: mJSIModulePackage null
05-21 15:05:56.953  7580  7657 E ReactNativeJNI: logMarker CREATE_REACT_CONTEXT_END
05-21 15:05:56.954  7580  7652 E unknown:DisabledDevSupportManager: Caught exception
05-21 15:05:56.954  7580  7652 E unknown:DisabledDevSupportManager: com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/*/files/CodePush/*/CodePush/index.android.bundle: No such file or directory
05-21 15:05:56.954  7580  7652 E unknown:DisabledDevSupportManager:     at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
05-21 15:05:56.954  7580  7652 E unknown:DisabledDevSupportManager:     at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:240)
05-21 15:05:56.954  7580  7652 E unknown:DisabledDevSupportManager:     at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:48)
05-21 15:05:56.954  7580  7652 E unknown:DisabledDevSupportManager:     at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:258)
05-21 15:05:56.954  7580  7652 E unknown:DisabledDevSupportManager:     at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1293)
05-21 15:05:56.954  7580  7652 E unknown:DisabledDevSupportManager:     at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
05-21 15:05:56.954  7580  7652 E unknown:DisabledDevSupportManager:     at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
05-21 15:05:56.954  7580  7652 E unknown:DisabledDevSupportManager:     at java.lang.Thread.run(Thread.java:761)
--------- beginning of crash

**Comment by songxiaoliang** [comment]
same error

**Comment by LiuIos** [comment]
same error

**Comment by iGroza** [comment]
I have similar issue


com.facebook.jni.CppException: facebook::react::Recoverable: Could not open file/data/user/0/com.instar/files/CodePush/e1cce612c50ddf01577e35b43101bf613ad2129f34939d8567d37b4f2c07ef3e/CodePush/index.android.bundle: No such file or directory
 at com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)
 at com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:245)
 at com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:48)
 at com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:268)
 at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1371)
 at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
 at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
 at java.lang.Thread.run(Unknown Source:4)

**Comment by iGroza** [comment]
i deleted the node_modules folder and installed the dependencies again, then rebuild the android app and uploaded the new version in code push. it helped me.

**Comment by shivam-gupta1996** [comment]
Any resolution? Still facing this.
react-native: 0.68.6
react-native-code-push: 7.0.4

**Comment by arpit203** [comment]
any resolution ?

**Comment by a-petrenko-muse** [comment]
same error
