### ISSUE TITLE
Codepush Crashes on app loading in IOS

### ISSUE THREAD

**Issue by Saeid-Barzegar** [microsoft/react-native-code-push#2033]
first should say everything is okay in android and created APK file is working fine
---------------------
But the issue is the app crashing on loading
I think the main reason is this line
**jsCodeLocation = [CodePush bundleURLForResource:@"artifacts/index" withExtension:@"js"];**
because on ios simulator everything works fine just after build the installed app on real phone crashes on the app loading

AppDeligate.m related code

NSURL *jsCodeLocation;
#ifdef DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"artifacts/index" fallbackResource:nil];
#else
    jsCodeLocation = [CodePush bundleURLForResource:@"artifacts/index" withExtension:@"js"];
#endif

react native version: **0.62** _(upgraded from **0.52**)_
appcenter version: **7**
main jsboundle: **"artifacts/index.js"**

**Comment by Saeid-Barzegar** [comment]
any idea?
did anyone face this issue?

**Comment by keithdmoore** [comment]
I have the same problem.  I am seeing the app crash on iOS and Android upon first launch after codepush is enabled in AppCenter

**Comment by gabrielbull** [comment]
I too, have CodePush crashing when the app launches. Even on a new React Native project, just adding CodePush and making a release crashes. Here is the logs:

```
2021-03-24 09:41:09.727363-0400 rqnative[1224:273238] 
[CodePush] Loading JS bundle from file:///private/var/containers/Bundle/Application/3D7DBBD6-FC31-4AFA-BC98-2D5537B1304C/rqnative.app/main.jsbundle
2021-03-24 09:41:09.727407-0400 rqnative[1224:273238] /private/var/containers/Bundle/Application/3D7DBBD6-FC31-4AFA-BC98-2D5537B1304C/rqnative.app/main.jsbundle
2021-03-24 09:41:09.727576-0400 rqnative[1224:273238] 
[CodePush] Loading JS bundle from file:///private/var/containers/Bundle/Application/3D7DBBD6-FC31-4AFA-BC98-2D5537B1304C/rqnative.app/main.jsbundle
2021-03-24 09:41:09.731180-0400 rqnative[1224:273238] [native] Running application ReturnQueen ({
    initialProps =     {
    };
    rootTag = 1;
})
2021-03-24 09:41:09.844854-0400 rqnative[1224:273491] [javascript] Running "ReturnQueen" with {"rootTag":1,"initialProps":{}}
2021-03-24 09:41:09.848255-0400 rqnative[1224:273491] [javascript] TypeError: Cannot call a class as a function
2021-03-24 09:41:09.850458-0400 rqnative[1224:273483] [native] Unhandled JS Exception: TypeError: Cannot call a class as a function
2021-03-24 09:41:09.852622-0400 rqnative[1224:273483] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: TypeError: Cannot call a class as a function', reason: 'Unhandled JS Exception: TypeError: Cannot call a class as a function, stack:
<unknown>@32:92
A@418:12395
run@357:1312
runApplication@357:2322
value@27:3350
<unknown>@27:747
value@27:2610
value@27:719
value@(null):(null)
'
*** First throw call stack:
(0x1a56c29d8 0x1b9a48b54 0x100af7c18 0x100b747c4 0x100b751fc 0x1a56c7130 0x1a55aa1d0 0x1a55aa730 0x100b27de0 0x100b29f74 0x100b29cd8 0x1014f7ce4 0x1014f9528 0x1015005ac 0x101501234 0x10150ca5c 0x1edee95a4 0x1edeec874)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: TypeError: Cannot call a class as a function', reason: 'Unhandled JS Exception: TypeError: Cannot call a class as a function, stack:
<unknown>@32:92
A@418:12395
run@357:1312
runApplication@357:2322
value@27:3350
<unknown>@27:747
value@27:2610
value@27:719
value@(null):(null)
'
terminating with uncaught exception of type NSException
```

**Comment by gabrielbull** [comment]
@andreidubov Can you guys address this one as well? It's preventing us from using codepush

**Comment by georgewwindsor** [comment]
same... any hints?

**Comment by hanifmhd** [comment]
any update on this issue?

**Comment by alantoledo007** [comment]
same... RN 0.65

**Comment by gabrielbull** [comment]
Not stale

**Comment by hakymz** [comment]
Any update facing this issue

**Comment by Saeid-Barzegar** [comment]
Hey guys
I didn't think this issue is still open
here is the code that resolved my issue

**NSURL *jsCodeLocation;
#ifdef DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"artifacts/index" fallbackResource:nil];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif**
  
 it tested with the version of react-native that I mentioned in the first post and it was working fine
 sorry for the late reply
 hope to be helpful for you like me

**Comment by hakymz** [comment]
Please where did you add the code

**Comment by Saeid-Barzegar** [comment]
> Please where did you add the code

[#root]/ios/[ProjectName]/AppDelegate.m
