### ISSUE TITLE
Release React command fails with hermes = true

### ISSUE THREAD

**Issue by anuragdani16** [microsoft/react-native-code-push#2036]
### Steps to Reproduce
1. Create react native app
2. Enable Hermes in android/app/build.gradle:
 ```
project.ext.react = [
          enableHermes: true,  // clean and rebuild if changing
      ]
```
3. Run appcenter codepush release-react

### Expected Behavior
What you expected to happen?

Successfully release update to appcenter

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

Converting JS bundle to byte code via Hermes, running command:

node_modules\hermesvm\win64-bin\hermes -emit-binary -out C:\Users\Anurag\AppData\Local\Temp\code-push2021114-21312-14yfd70.opmj\CodePush\index.android.bundle.hbc C:\Users\Anurag\AppData\Local\Temp\code-push2021114-21312-14yfd70.opmj\CodePush\index.android.bundle -w
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\hermesvm\win64-bin\hermes ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn node_modules\\hermesvm\\win64-bin\\hermes',
  path: 'node_modules\\hermesvm\\win64-bin\\hermes',
    '-emit-binary',
    '-out',
    'C:\\Users\\Anurag\\AppData\\Local\\Temp\\code-push2021114-21312-14yfd70.opmj\\CodePush\\index.android.bundle.hbc',
    'C:\\Users\\Anurag\\AppData\\Local\\Temp\\code-push2021114-21312-14yfd70.opmj\\CodePush\\index.android.bundle',
    '-w'
  ]
}

Error

![codepush_error](https://user-images.githubusercontent.com/49194726/107858541-bc49d780-6e5a-11eb-9b83-4c385425058b.png)

### Environment

* react-native-code-push version: "^7.0.0"
* react-native version: "0.63.4"
* appcenter-cli: "^2.7.4"
* iOS/Android/Windows version: 
* Does this reproduce on a debug build or release build? --
* Does this reproduce on a simulator, or only on a physical device? --

**Comment by psyzz** [comment]
same for me with hermes running `appcenter codepush release-react`

**Comment by rodsei** [comment]
Same here, even using the latest versions

> ### Environment
> * react-native-code-push version: "^7.0.1"
> * react-native version: "0.64.1"
> * appcenter-cli: "^2.9.0"
> * Running in MacOS Big Sur 11.3.1

**Comment by JeffGuKang** [comment]
Do not close. same issue is happening.

**Comment by JavanHuang** [comment]
Just encountered this issue as well while trying to setup codepush to upload a bundle with `enableHermes: true`
```
"react-native": "0.66.3".
"react-native-code-push": "~7.0.4",
```

```
Converting JS bundle to byte code via Hermes, running command:

node_modules/hermesvm/osx-bin/hermes -emit-binary -out /var/folders/35/jmmktdq97nd7x6ndb7b__hph0000gp/T/code-push2022125-33617-vrh37.vm295/CodePush/main.jsbundle.hbc /var/folders/35/jmmktdq97nd7x6ndb7b__hph0000gp/T/code-push2022125-33617-vrh37.vm295/CodePush/main.jsbundle -w
node:events:346
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/hermesvm/osx-bin/hermes ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node_modules/hermesvm/osx-bin/hermes',
  path: 'node_modules/hermesvm/osx-bin/hermes',
  spawnargs: [
    '-emit-binary',
    '-out',
    '/var/folders/35/jmmktdq97nd7x6ndb7b__hph0000gp/T/code-push2022125-33617-vrh37.vm295/CodePush/main.jsbundle.hbc',
    '/var/folders/35/jmmktdq97nd7x6ndb7b__hph0000gp/T/code-push2022125-33617-vrh37.vm295/CodePush/main.jsbundle',
    '-w'
  ]
}
```

**Comment by electricfeel1979** [comment]
I am having the same issue with enableHermes: true. I'm not really sure what I did why it doesnt work anymore, I remember updating the cli something.

`    "react-native": "0.66.1",
   "appcenter-cli": "^2.10.8",
    "react-native-code-push": "^6.4.1",
`

`
node_modules/hermesvm/osx-bin/hermes -emit-binary -out /tmp/code-push202249-4187-xcekea.xs8/CodePush/index.android.bundle.hbc /tmp/code-push202249-4187-xcekea.xs8/CodePush/index.android.bundle -w
node:events:498
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/hermesvm/osx-bin/hermes ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node_modules/hermesvm/osx-bin/hermes',
  path: 'node_modules/hermesvm/osx-bin/hermes',
  spawnargs: [
    '-emit-binary',
    '-out',
    '/tmp/code-push202249-4187-xcekea.xs8/CodePush/index.android.bundle.hbc',
    '/tmp/code-push202249-4187-xcekea.xs8/CodePush/index.android.bundle',
    '-w'
  ]
}
`

**Comment by mattisaa** [comment]
Encountered this problem as well. Has anyone managed to resolve this?

`"react-native": "0.67.4", "appcenter-cli": "2.10.8", "react-native-code-push": "^7.0.4",`

```
node_modules/hermesvm/osx-bin/hermes -emit-binary -out /var/folders/pw/4bv4gvhj0xn1rd30jyyw2cr80000gn/T/code-push202259-89306-4gq3nw.17qz5/CodePush/main.jsbundle.hbc /var/folders/pw/4bv4gvhj0xn1rd30jyyw2cr80000gn/T/code-push202259-89306-4gq3nw.17qz5/CodePush/main.jsbundle -w
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/hermesvm/osx-bin/hermes ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node_modules/hermesvm/osx-bin/hermes',
  path: 'node_modules/hermesvm/osx-bin/hermes',
  spawnargs: [
    '-emit-binary',
    '-out',
    '/var/folders/pw/4bv4gvhj0xn1rd30jyyw2cr80000gn/T/code-push202259-89306-4gq3nw.17qz5/CodePush/main.jsbundle.hbc',
    '/var/folders/pw/4bv4gvhj0xn1rd30jyyw2cr80000gn/T/code-push202259-89306-4gq3nw.17qz5/CodePush/main.jsbundle',
    '-w'
  ]
}

```

**Comment by felipejh** [comment]
I've the issue :(

**Comment by Chronostyle** [comment]
has anyone know how to fix it?I also got the issue from the latest version of appcenter-cli and react-native-codepush,

"react-native": "0.70.1", "appcenter-cli": "2.11.0", "react-native-code-push": "^7.0.5",

Error: spawn node_modules\hermesvm\win64-bin\hermes ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn node_modules\\hermesvm\\win64-bin\\hermes',
  path: 'node_modules\\hermesvm\\win64-bin\\hermes',
  spawnargs: [
    '-emit-binary',
    '-out',
    'C:\\Users\\Widyanto\\AppData\\Local\\Temp\\code-push2022829-43728-3i2q1t.h50lx\\CodePush\\index.android.bundle.hbc',
    'C:\\Users\\Widyanto\\AppData\\Local\\Temp\\code-push2022829-43728-3i2q1t.h50lx\\CodePush\\index.android.bundle',
    '-w'
  ]
}

**Comment by SMKH-PRO** [comment]
same problem after upgrading to 0.70.1

**Comment by Chronostyle** [comment]
> same problem after upgrading to 0.70.1

make sure to check appcenter version first, i thought i'm using the latest version of appcenter cli by using **appcenter -v**, but when i checked, i'm still using appcenter@2.10.10, to make it to the latest version, run **npm install -g appcenter-cli@latest** ,and i also add hermesCommand in build.gradle(app level), 

project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing

    // added to prevent "wrong bytecode version" in RN 0.69.1 
    **hermesCommand: '../../node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc'** 
]

**Comment by juuc** [comment]
@Chronostyle Great thanks to you, **npm install -g appcenter-cli@latest** worked
