### ISSUE TITLE
[QUESTION] Adding Code Push to React Native Windows > 0.63.6 in C#

### ISSUE THREAD

**Issue by aalbaharnah** [microsoft/react-native-code-push#2038]
I wanted to ask if there is any new documentation for implementing code push in a react-native-windows application that uses C# as a native language.

the current windows set up documentation in C# work on react-native-windows < 0.60 and ever since rnw 0.63.6 the structure of native solution have changed.

does anyone have an idea on how to make code push work on react-native-windows > 0.63.6 with C#?

### Environment
* react-native-code-push version: ^6.4.1
* react-native version: 0.63.4
* react-native-windows: ^0.63.0-0

**Comment by Omar-Belghaouti** [comment]
I would like to see documentation or an example about this too!
