### ISSUE TITLE
[Question][Android] switch bundle depends on build environment

### ISSUE THREAD

**Issue by rnike** [microsoft/react-native-code-push#2039]
Hi, we are starting to use react-native-code-push in our project(Android/iOS), I'm confused about the difference between changing the bundle URL on the Android and iOS platform.

In the iOS part, the document `recommend using the DEBUG pre-processor macro to dynamically switch between using the packager server and CodePush`

```Objective-C
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  #if DEBUG
    return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  #else
    return [CodePush bundleURL];
  #endif
}
```
But in the android part, this is not mentioned, and the implementation is as below
```Java
...
// 1. Import the plugin class.
import com.microsoft.codepush.react.CodePush;

public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        ...

        // 2. Override the getJSBundleFile method in order to let
        // the CodePush runtime determine where to get the JS
        // bundle location from on each app start
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
    };
}
```
If we want Android to behave as same as iOS `"only get bundle from codepush if isn't debug"`, should we need to implement it by ourselves like something below?

```Java
        @Override
        protected String getJSBundleFile() {
            if(BuildConfig.DEBUG == Boolean.TRUE){
              // react-native will get bundle from 'index.android.bundle' if getJSBundleFile returns null
              return null;
            }else{
              return CodePush.getJSBundleFile();
            }
        }
```
Or this is handled by `CodePush.getJSBundleFile` already?

### Environment

* react-native-code-push version: 7.0.0
* react-native version:0.63.3

**Comment by rnike** [comment]
Since there is no response, I've run into the source code and found out that we surely need to implement the "if statement" to determine whether it should get the bundle file from CodePush or from the default path on Android.

However, I've implemented it differently from the document, here's what I did:

iOS
```Objective-C
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  #define hasCodePushKey ([[ReactNativeConfig envFor:@"CODE_PUSH_KEY"] length]!=0)

  if(hasCodePushKey){
    return [CodePush bundleURL];
  }else{
    return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  }
}
```

Android
```Java
    @Override
    protected String getJSBundleFile() {
      boolean hasCodePushKey = !BuildConfig.CODE_PUSH_KEY.isEmpty();

      if(hasCodePushKey){
        return CodePush.getJSBundleFile();
      }else{
        // react-native will get bundle from 'index.android.bundle' if getJSBundleFile returns null
        return null;
      }
    }
```

Enable it by the environment variable is more convenient for us to integrate with CI/CD, hope this helps anyone who is also confusing about it.

**Comment by rdsedmundo** [comment]
@rnike I think you should keep this issue open so an official response can be made and maybe the docs updated. Also faced the same problem today.

**Comment by rnike** [comment]
@rdsedmundo Sure, I'll keep it open
