### ISSUE TITLE
JS Functions are not convertible to dynamic

### ISSUE THREAD

**Issue by luskin** [microsoft/react-native-code-push#2040]
Our application remains very stable until we push any codepush update, as soon as the codepush update goes out we begin seeing a tremendous increase in crashes and it's always this crash:

https://github.com/facebook/react-native/issues/27203

We have tested this by pushing a native update to iOS and Android app stores, then waiting a week to monitor no crashes, then pushing a one line codepush update (in our case we changed the string of a log). Immediately we started seeing a tremendous increase in crashes (1 / 3 runs). When you push the native code out to the appstores the crashes resolve themselves. At this point, nothing else seems to be the cause of the crashes except codepush itself.

### Steps to Reproduce
1. Build native app on iOS and Android
2. Monitor no crashes for as long as you want
3. Push a codepush update and immediately see increase in crashes

### Expected Behavior
The app should not crash

### Actual Behavior
What actually happens?
https://github.com/facebook/react-native/issues/27203

```
Fatal Exception: com.facebook.jni.CppException: JS Functions are not convertible to dynamic

no stack
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:37)
       at java.lang.Thread.run(Thread.java:919)
```

### Environment

* react-native-code-push version: 7.0.0
* react-native version: 0.63.4
* iOS/Android/Windows version: Latest
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? physical

**Comment by alita-moore** [comment]
@luskin did you find a solution to this?

**Comment by luskin** [comment]
@alita-moore yes we did, and it's going to be very difficult for you to find it in your application, but for us we were passing an object that contained a function as a parameter to a function that was expecting a string. I'm not sure that is going to be much help for you but that's what solved it for us.

**Comment by ap1969** [comment]
Hi,
I just had the same problem using a different plugin (Branch.io SDK), so thought I'd share the results here:

I had

```
branch.getFirstReferringParams(installParams => {
  console.log('Got installation params', installParams);
});
```

I missed out the then(). It should have been:
```
branch.getFirstReferringParams().then(installParams => {
  console.log('Got installation params', installParams);
});
```
