### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException java.lang.IndexOutOfBoundsException: index=1 count=0 

### ISSUE THREAD

**Issue by aamir-ans** [microsoft/react-native-code-push#2045]
@andreidubov @alexandergoncharov Got the firebase crash report where crash happens when user gets updates from code push, I'm not able to reproduce the same on my end. Kindly help me on this as large number of users are affected.

* react-native-code-push version: 7.0.0
* react-native version:0.62.1
* Android version:
 59%
Android 10
14%
Android 9
14%
Android 11
7%
Android 8
6%
Other (3)

**Comment by aamir-ans** [comment]
@andreidubov @alexandergoncharov Please provide me possible solution for now as many users facing issue with update

**Comment by n76i** [comment]
same with you

**Comment by liplylie** [comment]
Same
