### ISSUE TITLE
appcenter codepush release-react does not go beyond Running "react-native bundle command"

### ISSUE THREAD

**Issue by ravinhwg** [microsoft/react-native-code-push#2049]
### Steps to Reproduce
1. Intergrate CodePush into an existing React Native project.
2. Run appcenter codepush release-react -a <username>/<ProjectName> -d Production

### Expected Behavior
Successful bundling and then going to the next steps.
### Actual Behavior
appcenter exits with 
```
Error: Failed to release a CodePush update.
```
What actually happens?
```
 Detecting android app version:

Using the target binary version value "1.0" from "android/app/build.gradle".

Running "react-native bundle" command:

node node_modules/.bin/react-native bundle --assets-dest /tmp/code-push2021225-468113-1nqqps3.4w2/CodePush --bundle-output /tmp/code-push2021225-468113-1nqqps3.4w2/CodePush/index.android.bundle --dev false --entry-file index.js --platform android
Error: Failed to release a CodePush update.

```

### Reproducible Demo
N/A

### Environment

* react-native-code-push version: 7.0.0
* react-native version: 0.63.4
* iOS/Android/Windows version: 11
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? N/A

(The more info the faster we will be able to address it!)

**Comment by six0h** [comment]
Im getting a similar error, but i'm also getting the following with it:

> node node_modules/.bin/react-native bundle --assets-dest build/android/CodePush --bundle-output build/android/C
> odePush/index.android.bundle --dev false --entry-file index.js --platform android --sourcemap-output build/andr
> oid/CodePush/index.android.bundle.map                                                                          
> Welcome to Metro!                                                                                              
>               Fast - Scalable - Integrated                                                                     
>                                                                                                                
> error node_modules/react-native-code-push/CodePush.js: function (path) {                                       
>           return fn.call(state, path, state);                                                                  
>         } could not be cloned.                                                                                 
> Error: function (path) {                                                                                       
>           return fn.call(state, path, state);                                                                  
>         } could not be cloned.                                                                                 
>     at Object.serialize (v8.js:267:7)                                                                          
>     at _default (/home/cody/grizzlyforce/grizzlyforcenew/node_modules/@babel/core/lib/transformation/util/clone
> -deep.js:22:34)                                                                                                
>     at normalizeFile (/home/cody/grizzlyforce/grizzlyforcenew/node_modules/@babel/core/lib/transformation/norma
> lize-file.js:79:36)                                                                                            
>     at normalizeFile.next (<anonymous>)                                                                        
>     at run (/home/cody/grizzlyforce/grizzlyforcenew/node_modules/@babel/core/lib/transformation/index.js:29:50)
>     at run.next (<anonymous>)                                                                                  
>     at /home/cody/grizzlyforce/grizzlyforcenew/node_modules/@babel/core/lib/transform-ast.js:26:41             
>     at Generator.next (<anonymous>)                                                                            
>     at evaluateSync (/home/cody/grizzlyforce/grizzlyforcenew/node_modules/gensync/index.js:251:28)             
> info Run CLI with --verbose flag for more details.

**Comment by HZHAIX** [comment]
Anymore updates for this issue ?

**Comment by drop-george** [comment]
```
error: node_modules/react-native-code-push/CodePush.js: function (path) {
          return fn.call(state, path, state);
        } could not be cloned.
```
Have this exact same issue. 
- `react-native: 0.66.0`
- `react-native-code-push: 6.4.1`

**Comment by HZHAIX** [comment]
@drop-george this issue is caused by the babel, make sure you babel version is latest one `7.15.5`

**Comment by leticiamrosa** [comment]
> @drop-george this issue is caused by the babel, make sure you babel version is latest one `7.15.5`

Hi @drop-george, i was trying to use the latest version of babel, but i get the same error

- `"react-native": "0.66.0"`
- `"@babel/core": "7.15.5"`
- `"@babel/runtime": "7.15.4"`
- `"react-native-code-push": "6.2.0"`

i start to get this error just after i tried to update the RN version

**Comment by Nikos410** [comment]
For me it helped to upgrade to the latest babel version and then delete package-lock.json

**Comment by HZHAIX** [comment]
Yeah, don't forget to remove the yarn.lock or  package-lock.json and regenerate again

**Comment by OmarBasem** [comment]
I was able to get around this problem by using `"@babel/core": "^7.13.0"` and `"metro-transform-worker": "^0.64.0"` in dev dependencies

**Comment by TheRusskiy** [comment]
Removing `yarn.lock` is a nuclear solution, thankfully there's a better way.
Go to `yarn.lock`, see where `"@babel/***` start and delete all of them, dependencies are in alphabetical order, so it's easy selecting them.
The next time you do `yarn install` it's going to re-generate only babel dependencies which should solve this problem.
