### ISSUE TITLE
Question: How to check how many users are holding the latest code push bundle?

### ISSUE THREAD

**Issue by TommyLeong** [microsoft/react-native-code-push#2051]
### Disclaimer: This is not an issue
Since there's "Discussions" tab for Q&A, I'll post my ques here and close this ticket asap after answered. Have also posted on [Stackoverflow](https://stackoverflow.com/questions/66839350/how-to-check-how-many-users-are-holding-the-latest-code-push-bundle), unfortunately there's no respond.

---
**Question**

We have recently release a new code push to our application, is there a way for me to find out how many users out there are holding the application with latest code push?

![image](https://user-images.githubusercontent.com/9990179/112751079-9dfcfd00-8ffe-11eb-87f9-9d18d13a1311.png)

FYI, a bad mistake perhaps. But we code push to the same version as the current. Example, we are on Version 1.2.0, we are pushing the new codepush with 1.2.0 instead of 1.2.1. Hence we can't judge based on the versioning : /

From app-center, I can see the following screenshot which tells me the amount of people who `Installs` and `Downloads`. I however didn't understand what the difference, could anyone help me with this?

**Comment by filipef101** [comment]
They choses to not install the update afaik

**Comment by TommyLeong** [comment]
@filipef101  We don't provide option on updating or not, code level wise we forced the update.
