### ISSUE TITLE
Unable to resolve module code-push/script/acquisition-sdk

### ISSUE THREAD

**Issue by RigottiG** [microsoft/react-native-code-push#2060]
After build app, the following error appears. 

### Steps to Reproduce
1. `react-native run-ios`

### Expected Behavior
No issue happens.

### Actual Behavior

```
  error: Error: Unable to resolve module code-push/script/acquisition-sdk from /Users/guilhermerigotti/Documents/Projects/Work/ecommerce-super-app/node_modules/react-native-code-push/CodePush.js: code-push/script/acquisition-sdk could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
> 1 | import { AcquisitionManager as Sdk } from "code-push/script/acquisition-sdk";
    |                                            ^
  2 | import { Alert } from "./AlertAdapter";
  3 | import requestFetchAdapter from "./request-fetch-adapter";
  4 | import { AppState, Platform } from "react-native";
    at ModuleResolver.resolveDependency (/Users/guilhermerigotti/Documents/Projects/Work/ecommerce-super-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:191:15)
    at DependencyGraph.resolveDependency (/Users/guilhermerigotti/Documents/Projects/Work/ecommerce-super-app/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at Object.resolve (/Users/guilhermerigotti/Documents/Projects/Work/ecommerce-super-app/node_modules/metro/src/lib/transformHelpers.js:271:42)
    at resolve (/Users/guilhermerigotti/Documents/Projects/Work/ecommerce-super-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:571:33)
    at /Users/guilhermerigotti/Documents/Projects/Work/ecommerce-super-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/guilhermerigotti/Documents/Projects/Work/ecommerce-super-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:586:33)
    at /Users/guilhermerigotti/Documents/Projects/Work/ecommerce-super-app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/guilhermerigotti
```

![simulator_screenshot_9CE87FC3-D772-46BC-9407-26DDB680914C](https://user-images.githubusercontent.com/13246770/113298461-3da5de00-92d2-11eb-91a6-7b2e54df9e80.png)

### Environment

* react-native-code-push version: **7.0.0**
* react-native version: **0.63.4**
* iOS/Android/Windows version: **iOS 14.4 and Android**
* Does this reproduce on a debug build or release build? **both**
* Does this reproduce on a simulator, or only on a physical device? **both**

**Comment by bhishakBitcanny** [comment]
+1

**Comment by RigottiG** [comment]
> +1
> `npx react-native start --reset-cache` not helping

Yep, same here.

**Comment by IsmaelMiber** [comment]
Same here +1

**Comment by emilioheinz** [comment]
@andreidubov or @alexandergoncharov could you please take a look at this? It is blocking us from releasing a new production build.

**Comment by HimiGame** [comment]
npx react-native start --reset-cache not helping

**Comment by HimiGame** [comment]
pls  help

**Comment by exneval** [comment]
also facing same problem, what's the matter?

**Comment by pczar1** [comment]
Same problem

react-native-code-push 6.4.1
react-native 0.63.2

**Comment by WallysonGalvao** [comment]
These changes worked for me, I have not tested them in production, only in development as a temporary solution.

1 - In the _node_modules/react-native-code-push/CodePush.js_ file, change the import path from "code-push/script/acquisition-sdk" to "code-push/src/script acquisition-sdk".

2 - In the _node_modules/code-push/src/script/acquisition-sdk.ts_ file

![code](https://user-images.githubusercontent.com/14004866/113312837-0e4a9d80-92e1-11eb-878d-7190a6fef5c7.png)

**Comment by ilyausorov** [comment]
Looks like the issue is caused by the underlying package "code-push" being updated to version 4.0.3 on NPM 7 hours ago, which doesn't seem to be compatible with the current "react-native-code-push".

I added "code-push": "4.0.2" as a dependency to package.json so that it forces the older 4.0.2 version. Seems to work after you rm -rf node_modules, rm yarn.lock and yarn install again. Remember to remove this when they actually fix things!

**Comment by garanguillorycapitalrx** [comment]
@HimiGame issue here

**Comment by atemiz** [comment]
Editing the underlying code push package in the lock file fixes the problem until you re-upgrade the packages. 

```
code-push@^4.0.2:
  version "4.0.2"
  resolved "https://registry.yarnpkg.com/code-push/-/code-push-4.0.2.tgz#e5d963c291c5206b47c294e6077e8167baaea581"
  integrity sha512-sJitS/KVFT136z3LUbiZXWsvi9Ub1eIDkmtZvKQ4/0N2RyegKqbSa+Ybozt6IJrvozLahdkSp8Yl9BgYcmCCvg==
  dependencies:
    appcenter-file-upload-client "0.0.24"
    recursive-fs "^2.1.0"
    slash "^3.0.0"
    superagent "^5.3.1"
    superagent-proxy "^2.0.0"
    yazl "^2.5.1"
```

**Comment by jcederholmdivisions** [comment]
Run `yarn upgrade code-push@4.0.2` to change your yarn file. v4.0.3 has a broken import statement.

**Comment by chgsilva** [comment]
same issue here, any workarounds?

**Comment by mayuanyang** [comment]
any update on this one? our CI server pull down codes and reset cache, changing the package.json file might only work for developer machine

**Comment by pczar1** [comment]
> any update on this one? our CI server pull down codes and reset cache, changing the package.json file might only work for developer machine

Workaround which worked for me is the one shared by @ilyausorov. You can add in your package.json file dependency to package:

'code-push': '4.0.2'

**Comment by bhishakBitcanny** [comment]
Yes, @pczar1 this will solve the problem in the development environment but when you go for a release with any ci/cd pipeline this will fail. As this is a package.json change we can't just simply patch this package and release it.

**Comment by exneval** [comment]
> Yes, @pczar1 this will solve the problem in the development environment but when you go for a release with any ci/cd pipeline this will fail. As this is a package.json change we can't just simply patch this package and release it.

you can push the package.json changes, there's no harm doin' it, so the ci will work on it, cause there's no update from the dev

**Comment by bhishakBitcanny** [comment]
I have added a patch for the import -
`--- a/node_modules/react-native-code-push/CodePush.js
+++ b/node_modules/react-native-code-push/CodePush.js
@@ -1,4 +1,4 @@
-import { AcquisitionManager as Sdk } from "code-push/script/acquisition-sdk";
+import { AcquisitionManager as Sdk } from "code-push/src/script/acquisition-sdk";
 import { Alert } from "./AlertAdapter";
 import requestFetchAdapter from "./request-fetch-adapter";
 import { AppState, Platform } from "react-native";`

Then I am getting another error -
`error: node_modules/code-push/src/script/acquisition-sdk.ts: /Users/bhishak/Documents/Projects/RenterApp-master/RenterApp/node_modules/code-push/src/script/acquisition-sdk.ts: 'const' enums are not supported.
  3 |
  4 | export module Http {
> 5 |     export const enum Verb {
    |            ^
  6 |         GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, CONNECT, PATCH
  7 |     }
  8 |
`

**Comment by HimiGame** [comment]
> @HimiGame issue here

tyty

**Comment by HimiGame** [comment]
@garanguillorycapitalrx  thx

**Comment by ilyausorov** [comment]
@alexandergoncharov this feels like a "compatibility issue" and "critical bug". Perhaps we can get Microsoft to patch this up proper?

**Comment by gabrielbull** [comment]
I think Microsoft has abandoned code-push 😕

**Comment by ThallyssonKlein** [comment]
Same problem here using 6.2.1

**Comment by emilioheinz** [comment]
> Same problem here using 6.2.1. I'm trying to use version 4.0.2 and yarn says it doesn't exist.

you need to add `'code-push': '4.0.2'` to your package.json instead of changing the library version to 4.0.2.

**Comment by fungilation** [comment]
Facepalm MS.

**Comment by andreidubov** [comment]
Hi guys, 
This is a really big mistake from our side, now we have fixed it and released a new corrected version of code-push v4.0.4. In the future, we will try to be more careful with releases and will test them more closely. **Microsoft will continue to support Code-push, there are no plans to deprecate it**. Thanks to the community for the quick reaction to the problem, from our side we will check the repositories for critical errors and bugs more often and will fix all vulnerabilities in code-push repos soon.

Thank you for your understanding and we apologize for the inconvenience.

**Comment by ilyausorov** [comment]
Thanks for the update @andreidubov!!

**Comment by emilioheinz** [comment]
@andreidubov Thanks for the update. 

I was thinking about, and fixing the `code- push` library version on your side would prevent us from this type of bugs, no?
Instead of using `"code-push": "^4.0.2",` use `"code-push": "4.0.2",`. The only downside would be that minor fixes would need library releases, or is there any other?
