### ISSUE TITLE
code-push@7.0.0 is not working for android in react-native@0.64.0

### ISSUE THREAD

**Issue by nghia11110** [microsoft/react-native-code-push#2063]
https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-android.md
I'm following this guide and trying to setup code-push@7.0.0 for react-native@0.64.0.
iOS was ok but android is not working.

could anyone help me with this?

### Environment

* react-native-code-push version: 7.0.0
* react-native version: 0.64.0

**Comment by TheSolly** [comment]
Same issue here with the same versions of codepush and react-native with Android only...
Pushing a codepush totally crash our Android App on start.

**Comment by Grewer** [comment]
Now I want to roll it back to version 6.x and hope that it works

**Comment by Zestpond** [comment]
same issue

**Comment by Zestpond** [comment]
@nghia11110 @Grewer  @TheSolly I tried add default config in android `android/app/build.gradle` and worked
```
defaultConfig {
       .....
        resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())
    }
```

**Comment by nghia11110** [comment]
> @nghia11110 @Grewer @TheSolly I tried add default config in android `android/app/build.gradle` and worked
> 
> ```
> defaultConfig {
>        .....
>         resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())
>     }
> ```
> 
> react-native-code-push version: 7.0.0
> react-native version: 0.64.0

@Zestpond worked for me. you saved my day. thanks you so much.

**Comment by Grewer** [comment]
it works

**Comment by gabrielmoncea** [comment]
> @nghia11110 @Grewer @TheSolly I tried add default config in android `android/app/build.gradle` and worked
> 
> ```
> defaultConfig {
>        .....
>         resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())
>     }
> ```

This solution should be added in the docs!

**Comment by JamesGs1994** [comment]
Not working for me mentioningversions and code

 defaultConfig {
     
        resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())

`
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-firebase/app": "^16.3.0",
    "@react-native-firebase/auth": "^16.3.0",
    "@react-native-firebase/firestore": "^16.3.0",
    "@react-native-firebase/functions": "^16.4.6",
    "@react-native-masked-view/masked-view": "^0.2.7",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/stack": "^6.3.1",
    "axios": "1.2.0-alpha.1",
    "geofirestore": "^5.2.0",
    "lodash": "^4.17.21",
    "lottie-react-native": "^5.1.4",
    "moment": "^2.29.4",
    "native-base": "^3.4.19",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-card-flip": "^1.0.7",
    "react-native-code-push": "7.0.4",
    "react-native-config": "^1.4.11",
    "react-native-countdown-circle-timer": "^3.0.9",
    "react-native-device-info": "^10.3.0",
    "react-native-error-boundary": "^1.1.16",
    "react-native-exception-handler": "^2.10.10",
    "react-native-geolocation-service": "^5.3.1",
    "react-native-gesture-handler": "^2.6.2",
    "react-native-hole-view": "^2.1.1",
    "react-native-image-picker": "^4.10.0",
    "react-native-kiosk": "^0.1.1",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-qrcode-scanner": "^1.5.5",
    "react-native-reanimated": "2.10.0",
    "react-native-restart": "^0.0.24",
    "react-native-rsa-native": "^2.0.5",
    "react-native-safe-area-context": "^4.3.4",
    "react-native-screens": "^3.17.0",
    "react-native-snackbar": "^2.4.0",
    "react-native-svg": "^13.4.0",
    "react-native-text-ticker": "^1.14.0",
    "react-native-tts": "^4.1.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.1",
    "react-native-vision-camera": "2.14.1",
    "react-redux": "^8.0.4",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.2.1",
    "redux-saga-firebase": "^0.15.0",
    "vision-camera-code-scanner": "0.2.0",
    "vision-camera-face-detector": "0.1.8",
    "ws": "^8.11.0"
  },
`
