### ISSUE TITLE
Integrating CodePush in a Swift project

### ISSUE THREAD

**Issue by praveenApk** [Microsoft/react-native-code-push#207]
Hi,
I integrated React Native in a swift project. I followed the steps in the following link https://github.com/Microsoft/react-native-code-push#ios-setup to add code push to the project.
Since being a swift project, I added the line #import "CodePush.h" to the bridging header file. But when i try to build my project it says 'CodePush.h file not found' error. Any help on this?

**Comment by lostintangent** [comment]
@praveenApk Unfortunately I don't have much Swift experience so I'm not immediately sure what the issue could be. I know we have many users using Swift, so it works, but I'll have to investigate this tomorrow. Sorry for the inconvenience. Stay tuned!

**Comment by praveenApk** [comment]
@lostintangent Many thanks for the prompt reply. Somehow i **fixed** the issue by following the steps below.
1. Add the CodePush to the swift project.
    `npm install --save react-native-code-push` 
2. Give the path of CodePush directory in the podfile.
    `pod 'CodePush', :path => './node_modules/react-native-code-push'`
3. Install the pod. This takes care the automatic linking of libraries to the xcode.
    `pod install`
4. Add the CodePush header file to the bridging header file.
    `#import "CodePush.h"`
That's it. I am able to access CodePush from my swift files.
