### ISSUE TITLE
BSON Warning - crypto.getRandomValues

### ISSUE THREAD

**Issue by Malikkhoja-zz** [microsoft/react-native-code-push#2079]
Hi,

I have been using react-native-code-push for quite a while now and recently I have been getting a warning "BSON: For React Native please polyfill crypto.getRandomValues, e.g. using: https://www.npmjs.com/package/react-native-get-random-values."

I have noticed that react-native-code-push uses crypto.getRandomValues in the library and it seems the warning is generated from that piece of code.

Steps to Produce the Warning
1. Launch/Reload the app
2. Warning Appears(As CodePush is implemented on App.js)

Version:
Code Push - 7.0.1
RN - 0.63.5

I have tried to look for answers but couldnt find any. Anyone who can help?

**Comment by incompetent-tester** [comment]
A bit late but you can solve it by 
1. npm i react-native-get-random-values
2. And adding `import 'react-native-get-random-values'` to your main js or ts for it to polyfill
