### ISSUE TITLE
How can I use react-native-code-push with react-native-navigation wix version 7?

### ISSUE THREAD

**Issue by 1fabiopereira** [microsoft/react-native-code-push#2081]
I've been trying to find a way to make RNN v7 work correctly with react-native-code-push for a few days, but so far I haven't been successful.

**Comment by abhisriC2fo** [comment]
Hey, did you get anything on this?

**Comment by 1fabiopereira** [comment]
@abhisriC2fo I fixed this adding the config to code push on my loading screen and not over the point that wrapped all application, my loading screen is called every time that application is started and this fixed the issue for me.

**Comment by quanduong97** [comment]
@1fabiopereira  please show your code to use code push with Wix ! I have same issue
