### ISSUE TITLE
[Android] CodePush updates break asset source resolution for local SVGs

### ISSUE THREAD

**Issue by mzdon-ema** [microsoft/react-native-code-push#2082]
### Steps to Reproduce
1. Install a React Native Android app that renders an SVG from the local raw resource directory (res/raw/ in the APK).
2. Open the app and observe the locally rendered SVG.
3. Deploy a CodePush update and ensure the assets are delivered in the CodePush update contents.
4. Install the CodePush update and observe the locally rendered SVG is no longer displayed.

### Expected Behavior
We expected that locally rendered images will still be rendered after a CodePush update as long as the assets are bundled and included in the CodePush update contents.  This is not an issue on iOS.

### Actual Behavior
When the APK is built, the JS code renders SVG images that exist in android-app.apk/res/raw/img_name.svg.  I threw some `console.error` statements in the React Native `resolveAssetSrouce.js` file to debug the asset source resolution and we see something like this when printing out some of the variables involved:

#### SVG Working - Asset Resolution Log
```
2021-04-28 05:31:25.596 2991-4799/? E/ReactNativeJS: FINDME::resolveAssetSource source 58
2021-04-28 05:31:25.596 2991-4799/? E/ReactNativeJS: FINDME::resolveAssetSource asset {"__packager_asset":true,"httpServerLocation":"/assets/src/images/demo","width":39,"height":43,"scales":[1],"hash":"57295412052de063ecc4af407e38316c","name":"challenge-badge","type":"svg"}
2021-04-28 05:31:25.596 2991-4799/? E/ReactNativeJS: FINDME::resolveAssetSource return {"__packager_asset":true,"width":39,"height":43,"uri":"src_images_demo_challengebadge","scale":1}
```
#### Explanation of logs
We import the local image for rendering like `import challengeBadge from 'images/demo/challenge-badge.svg';` and `challengeBadge` is assigned an id of `58`, an asset is pulled from the `AssetRegistry` matching that id, and the `AssetSourceResolver` resolves the asset source to an object whose `uri` is a resource identifier.  The resource identifier is mapped to the resource location on the file system in android-app.apk/resources.arsc.  `src_images_demo_challengebadge` is mapped to `res/raw/src_images_demo_challengebadge.svg` in the arsc file.  All is well.

#### SVG Not Working - Asset Resolution Log
```
2021-04-28 05:33:56.167 3738-5703/? E/ReactNativeJS: FINDME::resolveAssetSource source 58
2021-04-28 05:33:56.171 3738-5703/? E/ReactNativeJS: FINDME::resolveAssetSource asset {"__packager_asset":true,"httpServerLocation":"/assets/src/images/demo","width":39,"height":43,"scales":[1],"hash":"57295412052de063ecc4af407e38316c","name":"challenge-badge","type":"svg"}
2021-04-28 05:33:56.173 3738-5703/? E/ReactNativeJS: FINDME::resolveAssetSource scriptURL file:///data/user/0/com.[redacted].[redacted]/files/CodePush/fb96c59f629ca1a5b2a44b358cedc1a1b0c53b8c44cf56a6745a4409ce883879/CodePush/
2021-04-28 05:33:56.177 3738-5703/? E/ReactNativeJS: FINDME::resolveAssetSource return {"__packager_asset":true,"width":39,"height":43,"uri":"file:///data/user/0/com.[redacted].[redacted]/files/CodePush/fb96c59f629ca1a5b2a44b358cedc1a1b0c53b8c44cf56a6745a4409ce883879/CodePush/drawable-mdpi/src_images_demo_challengebadge.svg","scale":1}
```
#### Explanation of logs
After the CodePush update is installed, we have the same SVG with an id of `58` which gives us the same asset object as before.  However, now the code has a `scriptURL`, which was `undefined` before the CodePush update was installed.  This changes how the asset source resolution behaves.  Since the JS bundle is loaded from the file system, the `AssetSourceResolver` tries to determine the drawable folder that the asset should live in based on image scale instead of returning the resource identifier like it did before.  Since the scale is `1` and SVGs are considered drawable, the resolved directory is `drawable-mdpi/` when in actuality the SVG is still in the `raw/` directory.  The image is no longer found and displayed.

#### Some additional screenshots

APK CONTENTS
![apk_contents](https://user-images.githubusercontent.com/59847077/116416178-23dfb400-a808-11eb-80ed-a2e7ef40312f.png)

CODEPUSH UPDATE CONTENTS
![CodePush_update_contents](https://user-images.githubusercontent.com/59847077/116416188-25a97780-a808-11eb-9719-c3a45c66626b.png)

### Reproducible Demo

I tried to put together a reproducible demo, but I was getting errors while running the commands to generate the project.
```
...
React Native Module for CodePush has been installed 

Linking React Native Module for CodePush...
internal/fs/utils.js:259
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'android/app/src/main/res/values/strings.xml'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at androidSetup (/Users/mzdon/workspaces/react-native-code-push-master/Examples/create-app.js:248:38)
    at linkCodePush (/Users/mzdon/workspaces/react-native-code-push-master/Examples/create-app.js:145:9)
    at Object.<anonymous> (/Users/mzdon/workspaces/react-native-code-push-master/Examples/create-app.js:78:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'android/app/src/main/res/values/strings.xml'
}
```

### Environment

* react-native-code-push version: 7.0.0
* react-native version: 0.63.4
* iOS/Android/Windows version: 11 (Samsung Galaxy S10)
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? Physical device

### Closing Thoughts

I'm sure there are work arounds for this... such as creating duplicate SVG files with the @1x @2x etc extensions so they end up in the various drawable-{density} directories and resolution doesn't fail, or maybe introducing a custom source transformer.  My goal here is just to inform the Code Push team of something I came across.  Thanks for all the hard work.  Code Push is seriously super awesome and I would recommend it to anyone doing React Native development.

**Comment by mzdon-ema** [comment]
To anyone else facing this issue here is a potential workaround:
```
import { Platform } from 'react-native';
import codePush from 'react-native-code-push';
import type {
  AssetSourceResolver,
  ResolvedAssetSource,
} from 'react-native/Libraries/Image/AssetSourceResolver';
import { setCustomSourceTransformer } from 'react-native/Libraries/Image/resolveAssetSource';

/*
If the defaultAsset URI is loading the resource from the file system and the resource is an SVG
return the resource idenfitier instead of the newly resolved file system location... the binary
will know where the resource identifier is actually located.

LIMITATION
We can't update locally rendered SVGs on Android with a CodePush update.
*/
function customSourceTransformer(resolver: AssetSourceResolver): ResolvedAssetSource | undefined {
  const defaultAsset = resolver.defaultAsset();
  if (defaultAsset) {
    const { uri } = defaultAsset;
    if (uri.startsWith('file://') && uri.endsWith('.svg')) {
      return resolver.resourceIdentifierWithoutScale();
    }
  }
  return defaultAsset;
}

let installed = false;
function installCustomSourceTransformer() {
  installed = true;
  setCustomSourceTransformer(customSourceTransformer);
}

async function maybeInstallCustomSourceTransformer(): Promise<void> {
  const codePushPackage = await codePush.getUpdateMetadata(codePush.UpdateState.RUNNING);
  const codePushVersion = codePushPackage?.label;
  // if there's a codepush update installed
  // if the OS is Android
  // if the transformer wasn't already installed
  if (!installed && codePushVersion && Platform.OS === 'android') {
    // install the source transformer
    installCustomSourceTransformer();
  }
}

export { maybeInstallCustomSourceTransformer };
```

`maybeInstallCustomSourceTransformer` is called during app bootstrapping.

**Comment by marsoochan** [comment]
it's solved in my environment.
Problem: Android RN APP failed to render images after Code-Push updates
ENV: Private Code-Push-Server on Ubuntu 16.04
Cause Found:  using RN assets system to load images, MUST release assets with JS bundle to CodePush (refers to https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-troubleshooting)
Solution: change to new bundle commands.

Before : react-native bundle --platform android --entry-file index.js --bundle-output ./CodePush/main.jsbundle --assets-dest ./CodePush --dev false

After :react-native bundle --entry-file index.js --bundle-output ./bundles/index.android.bundle
 --platform android --assets-dest ./bundles --dev false

code-push release PRJ_NAME ./bundles/ 1.0.0 --deploymentName Production --description "Update 1.0.4" --mandatory true
