### ISSUE TITLE
[Android]:  Update is invalid - A JS bundle file named "null" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary. RN version - 0.64.0 and react-native-code-push version - 7.0.1

### ISSUE THREAD

**Issue by aashray-systango** [microsoft/react-native-code-push#2083]
The code push changes are not reflecting as expected on android, works fine for iOS, the integration was done properly following android setup guide : https://github.com/microsoft/react-native-code-push/blob/HEAD/docs/setup-android.md

### Steps to Reproduce
1. Create a release build, having  
2. Do some changes, to test 
3. Ran code push release command: appcenter codepush release-react -a <ownerName>/<appName> -d test-variant-one
4. Code push changes released successfully
5. had "updateDialog: true" so go the alert stating new update once clicked on install, it installed the update but the changes didn't reflected

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?

Should reflect the changes

Got error-  com.microsoft.codepush.react.CodePushInvalidUpdateException: Update is invalid - A JS bundle file named "null" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.

Complete Error: 

com.microsoft.codepush.react.CodePushInvalidUpdateException: Update is invalid - A JS bundle file named "null" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.
        at com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage(CodePushUpdateManager.java:255)
        at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:290)
        at com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground(CodePushNativeModule.java:284)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run

### Environment

* react-native-code-push version: 7.0.1
* react-native version: 0.64.0
* Android version: 11
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by XB-Paul** [comment]
me too

**Comment by hero70312** [comment]
Both android and iOS work normally at react-native 0.63.0.
But android update **fail** while I use react-native 0.64.0.
(iOS work normally at react-native 0.64.0)

**Comment by ambisign-gavin** [comment]
I had the same issue too. 
In my project,  the update works fine on the debug mode, but not working on the release mode, and I found out the problem might be related to the expo, because of the expo using the ReactNativeHostWrapper class to wrapper the ReactNativeHost, and when I removed the ReactNativeHostWrapper the code push is working fine on the release mode, so I guess the ReactNativeHostWrapper might have the different logic and flow for getJSBundleFile method on the release mode.

**Comment by casaumayman** [comment]
Me too, any update?

**Comment by Klemminn** [comment]
Same here :(

**Comment by Klemminn** [comment]
> I had the same issue too. In my project, the update works fine on the debug mode, but not working on the release mode, and I found out the problem might be related to the expo, because of the expo using the ReactNativeHostWrapper class to wrapper the ReactNativeHost, and when I removed the ReactNativeHostWrapper the code push is working fine on the release mode, so I guess the ReactNativeHostWrapper might have the different logic and flow for getJSBundleFile method on the release mode.

Is it okay to remove ReactNativeHostWrapper?
What did you change, and were there any drawbacks?

**Comment by ambisign-gavin** [comment]
> Is it okay to remove ReactNativeHostWrapper?
> What did you replace it with, and were there any drawbacks?

The react-native-code-push is the experimental feature for my project, so I haven't replaced it yet.

**Comment by Dooqp** [comment]
**-----FIX-----**
@doomkit  @aashray-systango @casaumayman @Klemminn @ambisign-gavin 

I've faced with the same issue and fixed it by overriding getJSBundleFile method inside MainApplicationReactNativeHost class. The problem was I was using new architecture for android but documentation only talks about overriding getJSBundleFile method inside ReactNativeHost (which is used if newarchitecture is disabled)

```java
...
// 1. Import the plugin class.
import com.microsoft.codepush.react.CodePush;

public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        ...

        // 2. Override the getJSBundleFile method in order to let
        // the CodePush runtime determine where to get the JS
        // bundle location from on each app start
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
    };
}
```

but if the new architecture is enabled react-native uses MainApplicationReactNativeHost which is inside  "newarchitecture" folder of your project. So just override this method there as well and it will work. (It did work on my case at least).

NOTE: My project is not an Expo project so you probably should make some tweaks for expo but I assume that logic is same.

**Comment by mizhipeng** [comment]
thank you @Dooqp

**Comment by DmitriyKirakosyan** [comment]
Closing as resolved.

**Comment by mrenann** [comment]
@Dooqp 

> `MainApplicationReactNativeHost which is inside "newarchitecture" folder of your project. So just override this method there as well and it will work. (It did work on my case at least).`

Sorry for the question,
I didn't quite understand where I would put it, because there is no "newarchitecture" folder, or this MainApplicationReactNativeHost

**Comment by cholazzzb** [comment]
> **-----FIX-----** [@doomkit](https://github.com/doomkit) [@aashray-systango](https://github.com/aashray-systango) [@casaumayman](https://github.com/casaumayman) [@Klemminn](https://github.com/Klemminn) [@ambisign-gavin](https://github.com/ambisign-gavin) [@XB-Paul](https://github.com/XB-Paul) [@hero70312](https://github.com/hero70312) [@mahaaoo](https://github.com/mahaaoo)
> 
> I've faced with the same issue and fixed it by overriding getJSBundleFile method inside MainApplicationReactNativeHost class. The problem was I was using new architecture for android but documentation only talks about overriding getJSBundleFile method inside ReactNativeHost (which is used if newarchitecture is disabled)
> 
> ...
> // 1. Import the plugin class.
> import com.microsoft.codepush.react.CodePush;
> 
> public class MainApplication extends Application implements ReactApplication {
> 
>     private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
>         ...
> 
>         // 2. Override the getJSBundleFile method in order to let
>         // the CodePush runtime determine where to get the JS
>         // bundle location from on each app start
>         @Override
>         protected String getJSBundleFile() {
>             return CodePush.getJSBundleFile();
>         }
>     };
> }

Kotlin version

```kotlin
// MainApplication.kt

package your.package.name

import android.app.Application
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.react.soloader.OpenSourceMergedSoMapping
import com.facebook.soloader.SoLoader

import com.microsoft.codepush.react.CodePush // To fix codepush -> https://github.com/microsoft/react-native-code-push/issues/2083

class MainApplication : Application(), ReactApplication {

  override val reactNativeHost: ReactNativeHost =
      object : DefaultReactNativeHost(this) {
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage())
            }

        override fun getJSMainModuleName(): String = "index"

        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

        // To fix codepush -> https://github.com/microsoft/react-native-code-push/issues/2083
        override fun getJSBundleFile(): String? = CodePush.getJSBundleFile() // CodePush integration

        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
      }

  override val reactHost: ReactHost
    get() = getDefaultReactHost(applicationContext, reactNativeHost)

  override fun onCreate() {
    super.onCreate()
    SoLoader.init(this, OpenSourceMergedSoMapping)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      load()
    }
  }
}


```
> but if the new architecture is enabled react-native uses MainApplicationReactNativeHost which is inside "newarchitecture" folder of your project. So just override this method there as well and it will work. (It did work on my case at least).
> 
> NOTE: My project is not an Expo project so you probably should make some tweaks for expo but I assume that logic is same.

**Comment by Bartolace** [comment]
I corrected the getJSBundleFile method in .kt, but I still have the error, I have newArchEnabled active in gradle.properties, but there is no newarchitecture folder

**Comment by DordeDimitrijev** [comment]
Hello @Bartolace  as NA isn't officially supported with RNCP you could try out this workaround https://github.com/microsoft/react-native-code-push/issues/2781#issuecomment-2519480160
