### ISSUE TITLE
[Android] Update is invalid, Code push changes released successfully, android can't get the change but ios can.

### ISSUE THREAD

**Issue by yanwzhang** [microsoft/react-native-code-push#2085]
The code push changes are not reflecting as expected on android, works fine for iOS, the integration was done properly following android setup guide : https://github.com/microsoft/react-native-code-push/blob/HEAD/docs/setup-android.md
### Steps to Reproduce
1. Create a release build
2. Do some changes, to test
3. Ran code push release command:  appcenter codepush release-react -a / -d Production
4. Code push changes released successfully
5. IOS get the change, but Android can't get the change

### Expected Behavior
IOS and Android both get the change

### Actual Behavior
Only IOS get the change, but android don't
```
  there is no error 
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:7.0.1
* react-native version:0.64
* Android version: 11
* Does this reproduce on a debug build or release build?release build
* Does this reproduce on a simulator, or only on a physical device? both

(The more info the faster we will be able to address it!)

**Comment by Jumpis** [comment]
Having exactly same issue here.

**Comment by hero70312** [comment]
Both android and iOS work normally at react-native 0.63.0.
But android update **fail** while I use react-native 0.64.0.
(iOS work normally at react-native 0.64.0)

**Comment by hkbrain** [comment]
Same issue facing
React-native: 0.61.5
codepush: 6.1.1

**Comment by hero70312** [comment]
> Both android and iOS work normally at react-native 0.63.0.
> But android update **fail** while I use react-native 0.64.0.
> (iOS work normally at react-native 0.64.0)

When I used codepush.sync() function,
I got a CodePush.SyncStatus.UNKNOWN_ERROR from SyncStatusChangedCallback function.

**Comment by vestronv** [comment]
When we'll be getting 0.64 RN support, team ?  :)

**Comment by skdev24** [comment]
Having same issue, no update reflecting in android, iOS works.

```
"react-native": "0.63.4"
"react-native-code-push": "^7.0.1"
```

**Comment by adnxy** [comment]
Facing the same issue: 

"react-native": "0.63.4",
"react-native-code-push": "6.2.1"

Any updates on this?

**Comment by elliotmrodriguez** [comment]
Same here. 0.63.4 RN, code push 6.4.0

**Comment by ManhVuAmela** [comment]
Downgrade tools.build to 4.0.1 in `android/build.gradle` 
`classpath("com.android.tools.build:gradle:4.0.1")`
and can fix this

**Comment by limminyeong** [comment]
I experienced the same problem.
This solution works. 

https://github.com/microsoft/react-native-code-push/issues/1961#issuecomment-710698621

**Comment by watadarkstar** [comment]
Same problem for us!

**Comment by yanwzhang** [comment]
> Downgrade tools.build to 4.0.1 in `android/build.gradle`
> `classpath("com.android.tools.build:gradle:4.0.1")`
> and can fix this

Yes, it works to me, thank you!

**Comment by hero70312** [comment]
> Downgrade tools.build to 4.0.1 in `android/build.gradle`
> `classpath("com.android.tools.build:gradle:4.0.1")`
> and can fix this

It works to me, too.
Thank you!

**Comment by GarryLaly** [comment]
> Downgrade tools.build to 4.0.1 in `android/build.gradle`
> `classpath("com.android.tools.build:gradle:4.0.1")`
> and can fix this

It's work for me. Thanks

**Comment by karthick1231** [comment]
I have tried not working!

**Comment by JamesGs1994** [comment]
I am using React native Version 0.70.5
Gradle version **distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-all.zip**

> `

"react": "18.1.0",
"react-native": "0.70.5",
"react-native-code-push": "7.0.4",
"react-native-config": "^1.4.11",
"react-native-countdown-circle-timer": "^3.0.9",
"react-native-device-info": "^10.3.0",
"react-native-vision-camera": "2.14.1",
"redux-saga": "^1.2.1",
"redux-saga-firebase": "^0.15.0",
"vision-camera-code-scanner": "0.2.0",
"vision-camera-face-detector": "0.1.8",
`

I am getting every information in [Code Push] has syncing and checking but Update is not happening

I tried to add default config in **android android/app/build.gradle**
`defaultConfig {
       .....
        resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())
    }`

**Comment by PallavAtUnacademy** [comment]
+1
