### ISSUE TITLE
[Android] restartApp crashes the app, this breaks any install mode other than ON_NEXT_RESTART

### ISSUE THREAD

**Issue by filipef101** [microsoft/react-native-code-push#2088]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Call CodePush.restartApp(false)
2. Crash.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    java.lang.RuntimeException: Could not invoke CodePush.restartApp
```

### Environment

* react-native-code-push version: 7
* react-native version: 0.63.4
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? all
* Does this reproduce on a simulator, or only on a physical device?all

This breaks any install mode other than ON_NEXT_RESTART

(The more info the faster we will be able to address it!)

**Comment by Lumivescence** [comment]
I'm experiencing the same issue, does anyone have a fix for this?

**Comment by newbanker-tu** [comment]
I'm experiencing the same issue, does anyone have a fix for this?

**Comment by newbanker-tu** [comment]
@filipef101

**Comment by newbanker-tu** [comment]
@filipef101 @Lumivescence

**Comment by Namnp1521** [comment]
any update? i got this error on android device
```
"react": "18.1.0",
"react-native": "0.70.0",
"react-native-code-push": "^7.1.0",
```
