### ISSUE TITLE
[Error] Update check must include a binary version that conforms to the semver standard

### ISSUE THREAD

**Issue by retyui** [microsoft/react-native-code-push#2094]
Seems codepush ignore semver with suffix like `1.0.0-alpha.1`, `1.0.0-beta.1`, `1.0.0-pre-release.1`

See:
- https://semver.org/spec/v2.0.0.html#spec-item-9
- https://semver.org/spec/v2.0.0.html#spec-item-10

### Steps to Reproduce
1. Open `android/app/build.gradle`
2. Set `versionName "1.0.0-beta.1"`
3. Build an app
4. Try to sync codepush deployment 
5. **ERROR:** `CodePushHttpError: 400: An update check must include a binary version that conforms to the semver standard (e.g. `1.0.0`). The binary version is normally inferred from the App Store/Play Store version configured with your app.`

### Expected Behavior

Sync should finished without an error 

### Actual Behavior

Promise resolve with error:

```
CodePushHttpError: 400: An update check must include a binary version that conforms to the semver standard (e.g. `1.0.0`). The binary version is normally inferred from the App Store/Play Store version configured with your app.
```

### Reproducible Demo

-

### Environment

* react-native-code-push version: 7.0.1
* react-native version: 0.63.4
* iOS/Android/Windows version: latest
* Does this reproduce on a debug build or release build? **yes, build & release**
* Does this reproduce on a simulator, or only on a physical device? **yes**

**Comment by retyui** [comment]
what's new?

**Comment by doomkit** [comment]
Hi @retyui!
I've tried to reproduce this issue with react-native-code-push version: 7.0.1 and react-native version: 0.63.4. The `versionName` I used was `"2.0.0-beta.2"` and couldn't get the error that you have. I've also checked the version validation in our service and found no issues there.
If you can prepare a demo app with this issue, I would investigate this further.

**Comment by retyui** [comment]
@doomkit no problem, I will create a demo for you!

**Comment by retyui** [comment]
I also tested, issue not reproduce anymore!
