### ISSUE TITLE
Android static assets images are not loading after update over codepush

### ISSUE THREAD

**Issue by prakashjais99** [microsoft/react-native-code-push#2095]
React native app with Hermes enabled has below res folder structure when release build built from IDE 
<img width="835" alt="Screenshot 2021-05-18 at 7 13 43 PM" src="https://user-images.githubusercontent.com/5467335/118662400-97745000-b80d-11eb-8b2b-03f0091cbd8f.png">

We have a mono repo setup due to which I can't use `appcenter  codepush release` command 
Below are are steps we follow to upload new bundle to appcenter 
1. yarn react-native bundle --platform android  --entry-file index.js --bundle-output ./codepush/index.android.bundle.js  --assets-dest ./codepush/assets  --dev false
2. ./../node_modules/hermes-engine/osx-bin/hermesc -emit-binary ./index.android.bundle.js -out index.android.bundle -w
3. appcenter  codepush release -a <username>/<project> -c ./codepush   -d Staging -t "*"

Below is the generated folder structure

<img width="634" alt="Screenshot 2021-05-18 at 7 24 48 PM" src="https://user-images.githubusercontent.com/5467335/118664088-cd660400-b80e-11eb-952d-414f95e4f404.png">

Codepush is updating app successfully. But Static asset images are not getting loaded after the update. 

### Expected [Behavior](url)
Images should work without any issues

### Environment

* react-native-code-push version: 7.0
* react-native version: 0.63.1-4
* Android: 7.0
* Does this reproduce on a debug build or release build - Release build
* Does this reproduce on a simulator, or only on a physical device: Both device and simulator

**Comment by mzdon-ema** [comment]
Looks like you might be having a similar issue I had rendering static SVGs after a CodePush update.  I posted the workaround I've been using to fix this.  The only limitation is that you can't update static images on Android using a CodePush update.

https://github.com/microsoft/react-native-code-push/issues/2082#issuecomment-828562945

**Comment by alexandergoncharov** [comment]
Hi there :)
We merged and published this PR: https://github.com/microsoft/react-native-code-push/pull/2149

Could you please try to reproduce your issue with a new version and let us know if it was successful or not?
