### ISSUE TITLE
CodePush Error: Binary version mismatch, CodePush doesn't support SemVer with suffix (1.0.0-beta.1)

### ISSUE THREAD

**Issue by retyui** [microsoft/react-native-code-push#2099]
### Steps to Reproduce
1. Set a version with suffix (`1.0.0-beta.1`, `1.0.0-rc.4`, `1.0.0-experimental`, `1.0.0-a8964649b`)
2. Build prod app
3. Run the app and try to invoke `CodePush.sync(...)`

### Expected Behavior

`CodePush.sync` should work as expect

### Actual Behavior

Fail with an error: `Binary version mismatch`

### Reproducible Demo
...

### Environment

* react-native-code-push version: latest
* react-native version: latest
* iOS/Android/Windows version: any
* This reproduces on release build

**Comment by jarod-legault** [comment]
I think we are having this issue as well. I think CodePush stopped working for us when we added a suffix to our version on Android.

**Comment by retyui** [comment]
up

**Comment by retyui** [comment]
Fixed
