### ISSUE TITLE
Downloading code push in the background causes it to rollback

### ISSUE THREAD

**Issue by vasutrantor** [microsoft/react-native-code-push#2103]
### Steps to Reproduce
1. Launch the React Native App.
2. Move the App to background.
3. While moving to background I check if application is in background state then trigger codePush.sync with install mode on next restart.
4. Wait for code push to download in background.
5. Kill the App.

### Expected Behavior
On next launch it should install the code push downloaded in background.
This works fine if I launch the App from background and then re-start instead of killing the App. But user may not necessarily open the App everytime from background.

### Actual Behavior
The code push goes in rollback state.

React native version: 0.62.x
Code push version:latest

I am checking for mandatory code push and installing on App launch but if it is not mandatory I do not even want to download the code push on launch to avoid any friction.

**Comment by songxiaoliang** [comment]
same error

**Comment by songxiaoliang** [comment]
@vasutrantor hi，Is this problem solved?
