### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ajoykarmakar** [microsoft/react-native-code-push#2114]
### Actual Behavior
After download the update, the undefined function issue is arrived. 

![image](https://user-images.githubusercontent.com/32778214/125599518-f90326c5-c064-485f-aab9-c0f600c50331.png)

### Environment

* react-native-code-push version: 7.0.1
* react-native version: 0.63.4
* Android version: 7.1.1
* This reproduce on a debug build or release build both.
* This reproduce on a simulator, or only on a physical device both.

**Comment by ronlobo01** [comment]
@ajoykarmakar any luck ?
