### ISSUE TITLE
Bundled update allows fonts but OTA update does not

### ISSUE THREAD

**Issue by Pinwheeler** [microsoft/react-native-code-push#2115]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Download my testflight build of the staging version of my app (link can be provided if you like)
2. Launch the app and see that react-native-vector-icon is working as expected
3. Force-quit and relaunch the app
4. See that the react-native-vector-icons are now missing

### Expected Behavior
The icons should render the same for both the bundled bundle.js as well as the OTA one

### Actual Behavior
What actually happens?

I've circled my version information in the following screenshots. "edge" is the bundled bundle.js. "v17" is the result of `CodePush.getUpdateMetadata()....promise...label`

![IMG_0008](https://user-images.githubusercontent.com/4139124/125719457-5e07d098-3e15-49e0-baaa-2fabce3a8b7a.PNG)
![IMG_0009](https://user-images.githubusercontent.com/4139124/125719463-bfb592a4-a998-4bd8-88af-8677755f34e6.PNG)

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 7.0.1
* react-native version: 0.64.2
* iOS/Android/Windows version: iOS 14.6
* Does this reproduce on a debug build or release build? release (well, staging)
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

**Comment by Pinwheeler** [comment]
Just a side-note, I'd also be happy with suggestions about how to get logs about the exact error that is occurring :)

**Comment by Klemminn** [comment]
Same happening for me, using a custom font which is **sometimes** not loaded after a CodePush OTA update.

**Comment by Pinwheeler** [comment]
@Klemminn I ended up scrapping the icon font in favor of just using static image icons. Not my favorite solution, but it works.

**Comment by Klemminn** [comment]
> @Klemminn I ended up scrapping the icon font in favor of just using static image icons. Not my favorite solution, but it works.

Thanks Pinwheeler, unfortunately my problem is not with icons, we are using custom fonts for the whole application, so when this happens, everything is in the incorrect font.
I haven't been able to pinpoint when or why this happens, it's not failing with every OTA update, just some.
