### ISSUE TITLE
Update published in App Center and fully rolled out but not reflected in app

### ISSUE THREAD

**Issue by alexander126** [microsoft/react-native-code-push#2128]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Expected Behavior
What you expected to happen?
Show update in the app
### Actual Behavior
What actually happens?
Update not reflected in the app

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: latest
* react-native version: 0.63.4
* iOS/Android/Windows version: - 
* Does this reproduce on a debug build or release build? -  Release
* Does this reproduce on a simulator, or only on a physical device? - Physical

(The more info the faster we will be able to address it!)

I have set up the codepush app with production key in info.plist and the production push from codepen cli seems to be working as I can see the release in the dashboard, however the app is not reflecting the changes. Its just text changes (only js) so its a bit strange as to why is it not working

**Comment by tradebulls** [comment]
We are facing the same issue. Please help

**Comment by chentselee** [comment]
Same here
