### ISSUE TITLE
App crash after download and install (via sync method) after upgrading to RN 0.65

### ISSUE THREAD

**Issue by D10S60948** [microsoft/react-native-code-push#2131]
### Steps to Reproduce
1. call `codePush.sync({ installMode: codePush.InstallMode.IMMEDIATE });`

### Expected Behavior
App should restart

### Actual Behavior
App is crashing

### Environment

* react-native-code-push version: 7.0.1
* react-native version: 0.65.1
* iOS/Android/Windows version: Android 11
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? physical

It worked as expected up until upgrading react-native to version 0.65

**Comment by D10S60948** [comment]
Sorry but it's too much for me to do.
If there is no error in a brand new project I can only assume the issue is with something I'm doing wrong (and who gave the issue thumb up).
I'll try to solve it soon by making some changes in the `build.gradle`. will let you know how it went.

**Comment by D10S60948** [comment]
Hi Andrey,

I've made some changes that I thought are the reason this crashes happened but unfortunately nothing helped.
I thought it was because I kept using jcenter but that not it.

I can send you in private my build.gradlew 's or any other doc that will help figuring out the problem.
The issue is obviously coming from existing code in existing projects as it not happens on new projects. the 3 thumbs-up are supporting the fact that it's not only me facing with this crashes.

Thanks

**Comment by D10S60948** [comment]
So I installed release version on my emulator and updated code-push version and here is the logcat output:
`
09-05 22:13:24.935  8369  8414 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
09-05 22:13:24.935  8369  8414 E AndroidRuntime: Process: com.peloton.ride.together, PID: 8369
09-05 22:13:24.935  8369  8414 E AndroidRuntime: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Could find root view for a given ancestor with tag 135
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at com.swmansion.gesturehandler.react.RNGestureHandlerModule.tryInitializeHandlerForReactRootView(RNGestureHandlerModule.java:577)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at com.swmansion.gesturehandler.react.RNGestureHandlerModule.attachGestureHandler(RNGestureHandlerModule.java:487)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
09-05 22:13:24.935  8369  8414 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
`
I think it's possible tht it might be [related to this](https://github.com/software-mansion/react-native-reanimated/issues/2365)

**Comment by heekyu-pu** [comment]
@D10S60948 
https://github.com/microsoft/react-native-code-push/issues/1961#issuecomment-710698621
This change solved my problem.

**Comment by D10S60948** [comment]
Thanks @heekyu-pu I tried it but unfortunately it still crashes.

**Comment by bradstiff** [comment]
I get the exact same stack trace with 0.65.1 when I call codePush.restartApp(true). My stack trace also has RNGestureHandler at the top. 

It didn't happen ever on earlier RN versions.
