### ISSUE TITLE
Bridge is not set. This is probably because you've explicitly synthesized the bridge in CodePush

### ISSUE THREAD

**Issue by PhoenixLeeSin** [microsoft/react-native-code-push#2133]
iOS project insert jsbundle;
when ios -> RN and RN -> ios, it will cause memory growth and app crash.
code like this:
```
RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation moduleName: moduleName initialProperties:userInfoDic launchOptions:nil]; GXBaseRNViewController *navtiveVC = [[GXBaseRNViewController alloc]initWithNavType:GXNavTypeNone]; navtiveVC.view = rootView;
In order to solve the memory growth ， i write
- (void)dealloc { [[NSNotificationCenter defaultCenter] removeObserver:self]; RCTRootView *rootView = (RCTRootView *)self.view; RCTBridge *bridge = rootView.bridge; [bridge invalidate]; bridge = nil; }
```

`

but it crash
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: CodePushDownloadProgress with body: { receivedBytes = 6933551, totalBytes = 6933551, }. Bridge is not set. This is probably because you've explicitly synthesized the bridge in CodePush, even though it's inherited from RCTEventEmitter.' *** First throw call stack: (0x18696a754 0x19b4317a8 0x18686c3f8 0x187c93a6c 0x1080afa0c 0x105fd99b4 0x105fdb6d8 0x105fde628 0x1871dcaa0 0x187cf4fa8 0x187be2878 0x187cf73d0 0x187be2500 0x187cf7e74 0x187cf7900 0x1093c69c8 0x1093b5de0 0x1093bdef0 0x1093bed14 0x1093cba50 0x1d25e67a4 0x1d25ed74c) libc++abi: terminating with uncaught exception of type NSException *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: CodePushDownloadProgress with body: { receivedBytes = 6933551, totalBytes = 6933551, }. Bridge is not set. This is probably because you've explicitly synthesized the bridge in CodePush, even though it's inherited from RCTEventEmitter.' terminating with uncaught exception of type NSException`

how can i solve it, ths

**Comment by KingTortoise** [comment]
+1

**Comment by KingTortoise** [comment]
+1  version：6.4.1

**Comment by PhoenixLeeSin** [comment]
https://github.com/PhoenixLeeSin/PhoenixLeeSin.github.io/blob/main/RN/iOS%E5%92%8CRN%E6%B7%B7%E7%BC%96%E8%A7%A3%E5%86%B3%E5%86%85%E5%AD%98%E6%97%A0%E9%99%90%E5%A2%9E%E9%95%BF.md
看一下我的这篇文章 已经解决这个问题
