### ISSUE TITLE
[Android] 7.0.2 Image asset not working after apply new codepush release 

### ISSUE THREAD

**Issue by KoreanThinker** [microsoft/react-native-code-push#2138]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Release build to android physical device
2. change some file
3. run codepush release
4. reopen app (until applied codepush)

### Expected Behavior
Right after the release build
![KakaoTalk_Photo_2021-09-08-00-33-12 001](https://user-images.githubusercontent.com/48207131/132372174-75156d39-d0ad-474f-882b-ed16b0a96f83.jpeg)

### Actual Behavior
after reopened the app (when applied codepush)
![KakaoTalk_Photo_2021-09-08-00-33-12 002](https://user-images.githubusercontent.com/48207131/132372207-f0501e21-842f-41f1-ab05-e12d2e62aceb.jpeg)

### Environment

* react-native-code-push version: 7.0.2
* react-native version: 0.65.1
* iOS/Android/Windows version: Android 11
* Does this reproduce on a debug build or release build: release
* Does this reproduce on a simulator, or only on a physical device: I tested only physical, I don't know about simulator

(The more info the faster we will be able to address it!)

**Comment by KoreanThinker** [comment]
Additionally I disabled hermes

**Comment by blueberry6401** [comment]
I though this is an issue with RN 0.65.1. Codepush works fine for me before upgrading to newer version of RN.

**Comment by KoreanThinker** [comment]
I solved with `enableHermes: true`

**Comment by dkahdwk** [comment]
I'm in the same situation...Did you find a solution?

**Comment by KoreanThinker** [comment]
> I'm in the same situation...Did you find a solution?

The best way is enable `hermes`. But this solution not working on seconed codepush update. It's work on first codepush update.

**Comment by dkahdwk** [comment]
> > 저도 같은 상황인데...해결책은 찾으셨나요?
> 
> 가장 좋은 방법은 enable `hermes`입니다. 그러나이 솔루션은 두 번째 코드 푸시 업데이트에서 작동하지 않습니다. 첫 번째 코드 푸시 업데이트 작업입니다. 7.0.3을 기다리고 있습니다

Thank you for your answer! I'll have to wait for 7.0.3.

**Comment by KoreanThinker** [comment]
> > > 저도 같은 상황인데...해결책은 찾으셨나요?
> > 
> > 
> > 가장 좋은 방법은 enable `hermes`입니다. 그러나이 솔루션은 두 번째 코드 푸시 업데이트에서 작동하지 않습니다. 첫 번째 코드 푸시 업데이트 작업입니다. 7.0.3을 기다리고 있습니다
> 
> Thank you for your answer! I'll have to wait for 7.0.3.

You can solve to downgrading RN 0.64.2 & codepush 6.2+

**Comment by apexglory** [comment]
I have the same issue, images show in first codepush update but disappear on second, when i downgrading RN to 0.64.2 and specify react-native-code-push version to 7.0.1, it proper functioning!

**Comment by ZeroCho** [comment]
I think this is because images are in wrong folder, wrong names.
under `build/CodePush`
I expected assets are located like this(which is iOS way that working fine)
```
build/CodePush
--src/assets
  --example.png
```

but actually like this(in Android)
```
build/CodePush
--drawable-mdpi
  --src_assets_example.png
```

**Comment by Andriiklymiuk** [comment]
has anyone tried to make it work with 0.65.1 ?

**Comment by Andriiklymiuk** [comment]
Try to downgrade to 7.0.1, no need to downgrade react native from 0.65.1
https://github.com/microsoft/react-native-code-push/issues/2136#issuecomment-919097996

**Comment by blueberry6401** [comment]
Confirmed, downgrade to 7.0.1 and still works with 0.65.1
By the way, did code-push team test before releasing?

**Comment by mcAnastasiou** [comment]
Same issue here

**Comment by KoreanThinker** [comment]
> Same issue here

https://github.com/microsoft/react-native-code-push/issues/2138#issuecomment-919104133 It's work for me

**Comment by mcAnastasiou** [comment]
I tried to downgrade and it still doesn't work. The second update always removes the images

**Comment by mcAnastasiou** [comment]
I downgraded to ^6.4.1 in order to work

**Comment by ChrisWiles** [comment]
I just updated to 7.0.3, and spent like 8 hours trying to figure out why android lost images on 2nd+ codepush
Installing 7.0.1 fixes the issue... 😢 

```
 "dependencies": {
    "@fortawesome/fontawesome-svg-core": "1.2.30",
    "@fortawesome/free-brands-svg-icons": "5.14.0",
    "@fortawesome/free-regular-svg-icons": "5.14.0",
    "@fortawesome/free-solid-svg-icons": "5.14.0",
    "@fortawesome/react-native-fontawesome": "0.2.5",
    "@react-native-community/art": "1.0.2",
    "@react-native-community/async-storage": "1.6.2",
    "@react-native-community/blur": "3.4.1",
    "@react-native-community/netinfo": "4.6.0",
    "@react-native-community/push-notification-ios": "1.0.3",
    "@reduxjs/toolkit": "1.6.1",
    "@sentry/react-native": "2.6.2",
    "appcenter": "2.5.0",
    "appcenter-analytics": "2.5.0",
    "appcenter-crashes": "2.5.0",
    "color": "3.1.2",
    "cookie": "0.4.1",
    "cookieparser": "0.1.0",
    "currency-formatter": "1.5.8",
    "formik": "2.2.6",
    "geolib": "3.3.1",
    "lodash": "4.17.21",
    "moment": "2.29.1",
    "moment-timezone": "0.5.33",
    "native-base": "2.15.2",
    "password-validator": "5.1.1",
    "path": "0.12.7",
    "phone": "2.4.21",
    "prop-types": "15.7.2",
    "pubnub": "4.32.0",
    "re-reselect": "4.0.0",
    "react": "16.13.1",
    "react-native": "0.61.5",
    "react-native-app-link": "1.0.0",
    "react-native-auto-height-image": "1.1.3",
    "react-native-background-fetch": "4.0.3",
    "react-native-background-geolocation": "4.3.0",
    "react-native-camera": "3.9.0",
    "react-native-code-push": "7.0.1",
    "react-native-device-info": "5.3.0",
    "react-native-elements": "1.2.7",
    "react-native-fast-image": "7.0.2",
    "react-native-fs": "2.16.2",
    "react-native-gesture-handler": "1.5.0",
    "react-native-image-picker": "1.1.0",
    "react-native-image-resizer": "1.1.0",
    "react-native-maps": "0.29.3",
    "react-native-maps-directions": "1.7.6",
    "react-native-masked-text": "1.13.0",
    "react-native-modal": "11.5.3",
    "react-native-orientation-locker": "1.1.7",
    "react-native-paper": "4.7.2",
    "react-native-parallax-scroll-view": "0.21.3",
    "react-native-permissions": "2.2.2",
    "react-native-progress": "4.0.1",
    "react-native-push-notification": "3.1.9",
    "react-native-reanimated": "1.4.0",
    "react-native-signature-capture": "0.4.10",
    "react-native-sound": "0.11.0",
    "react-native-svg": "9.13.6",
    "react-native-svg-uri": "1.2.3",
    "react-native-vector-icons": "6.6.0",
    "react-native-webview": "7.5.1",
    "react-navigation": "4.0.10",
    "react-navigation-drawer": "2.3.3",
    "react-navigation-header-buttons": "3.0.4",
    "react-navigation-stack": "1.10.3",
    "react-navigation-tabs": "2.5.6",
    "react-redux": "7.2.1",
    "reanimated-bottom-sheet": "1.0.0-alpha.18",
    "recompose": "0.30.0",
    "redux": "4.0.5",
    "redux-persist": "5.10.0",
    "redux-saga": "1.1.3",
    "reselect": "4.0.0",
    "styled-components": "5.3.0",
    "superagent": "5.1.0",
    "url": "0.11.0",
    "validator": "13.6.0",
    "yup": "0.32.9"
  },
```

**Comment by jcxswc** [comment]
This is an active issue for 7.0.3. Our production app for Android is not showing any bundled images after upgrading.

**Comment by HikoVinhHo** [comment]
Does anything update these issues? How to resolve this issue?

**Comment by fbartho** [comment]
We're experiencing this issue as well, but this is our first time working with CodePush, so we thought it was a configuration error on our side.

**Comment by knro** [comment]
Have to downgrade to get this fixed. This is a critical issue.

**Comment by ianitararache** [comment]
Same here, updated to 7.0.4 and the problem is still there

**Comment by knro** [comment]
@jcxswc This was with a new binary version. I trusted this would work well then I got hammered with bug reports on missing icons again in the updated binary release.

**Comment by jcxswc** [comment]
Interesting. Do you have Hermes enabled in the build @knro?

**Comment by knro** [comment]
Correct, I do.
