### ISSUE TITLE
Install Mode Error!

### ISSUE THREAD

**Issue by DHidee66** [Microsoft/react-native-code-push#214]
Hi,

I just got this error when my app was closed.
![screen shot 2016-02-27 at 4 24 35 pm](https://cloud.githubusercontent.com/assets/6751025/13373690/cb094558-dd6e-11e5-849d-f5922146b854.png)

Thank You!

**Comment by lostintangent** [comment]
@DHidee66 That error indicates that the CodePush module hasn't been fully installed, and therefore, the "proxy" object isn't being exposed to JS. Could you double check the install instructions to make sure everything is setup?

**Comment by DHidee66** [comment]
Hey @lostintangent , 
I have a GCM module that does something in the background when my app is closed and it receives a notification. Then is when the error appears. 
When i run the project normally I get the usual CodePush logs that it checked for a new version and there was no updates.

**Comment by lostintangent** [comment]
Ah OK that's interesting. Are you calling any CodePush APIs in response to the notification?

**Comment by lostintangent** [comment]
Also out of curiosity, are you using this module for handling the notifications? https://github.com/oney/react-native-gcm-android?

**Comment by DHidee66** [comment]
@lostintangent Yes that's the one. And the sync() method is not called.

**Comment by lostintangent** [comment]
Hmm OK. I just pinged Howard who is the owner of that module (and also uses CodePush in his apps) to see if he has any insight. I'll investigate into it as well to see what might be going on. We haven't seen this issue before so I appreciate you reporting it!

Just to make sure I'm trying to repro the same scenario, could you let me know which React Natice you're using? RN 0.20.?

Additionally, does the JS file that includes your notification handler also include a require/import statement for the "react-native-code-push" module? The error you're seeing would actually come from simply loading our JS module, as opposed to calling sync.

**Comment by lostintangent** [comment]
It seems possible that this issue isn't related to CodePush, but rather, is being caused by this bug in the RN GCM module: https://github.com/oney/react-native-gcm-android/issues/26.

If you removed any imports/require statements for CodePush and any sync calls from your project, does this issue go away entirely? Or do you see a similar error but for a different module? I'm just wondering if the CodePush error you're seeing is just a symptom of an underlying issue.

**Comment by DHidee66** [comment]
Yes I am using RN 0.20 and I do import CodePush in the main file. Well that library has some issues which I just reported but I don't think those are related to this one. The import statement will always get called when the app uses these kind of libraries. One solution is to call the import  only when the app is active. If that works, then it might be helpful in the documentation. I will check it in a moment.

**Comment by lostintangent** [comment]
We could definitely update the docs if that works, but it seems really unlikely that only the CodePush native module isn't loaded while inactive. The "NativeCodePush" object is simply the proxy object generated by the React Native bridge, so the fact that it is undefined seems more like a sign of the bridge itself not being fully operational, than an issue with CodePush.

I'll keep investigating and will look forward to hearing what you find as well. Thanks dude!

**Comment by DHidee66** [comment]
Of course `import' and 'export' may only appear at the top level` .. what was I thinking. 
Since it's a single bundle you either have it or you don't.

**Comment by lostintangent** [comment]
If you remove the CodePush import and call to sync entirely, does everything work properly, or do you get a different error when the app isn't active? I'm curious if you would have issues trying to evaluate any native module or not. For example, if you grab the Linking module off of the react-native and  called Linking.getInitialURL(), would that work or would "Linking" be undefined?

**Comment by lostintangent** [comment]
Either way, what we can do is stop doing any JS module initialization if the RN bridge doesn't include the CodePush module ("NativeCodePush" is undefined). That way, simply importing the JS module wouldn't throw an error in this case. If you called sync, that would error, but since you're not doing that, it wouldn't be an issue for your scenario.

I can send out a PR for this in a bit.

**Comment by DHidee66** [comment]
Great idea .. Thank you :)

**Comment by lostintangent** [comment]
@DHidee66 Check out #215. If you want to cherry-pick that change, you could unblock yourself right now. We'll likely release an update to NPM next week that will include this fix as well.

**Comment by DHidee66** [comment]
@lostintangent Thank you :) You are blazing fast :zap:

**Comment by oney** [comment]
I think it should be related to my GCM module.
Please use [this configuration](https://github.com/Neson/react-native-system-notification#push-notifications-on-android) to solve the problem

**Comment by DHidee66** [comment]
@oney That's what I'm using. This happened when the app was closed and 
`(GCMAndroid.launchNotification)` was undefined instead of having a value.
So in your code this is always false when the app is closed. 
```js```
if (GcmAndroid.launchNotification) {
  var notification = GcmAndroid.launchNotification
...
else 
```

**Comment by oney** [comment]
Hmm.. If you follow [this configuration](https://github.com/Neson/react-native-system-notification#push-notifications-on-android), you won't have `if (GcmAndroid.launchNotification) {` scope.

**Comment by DHidee66** [comment]
@oney The code is in your Readme file. 
How are you supposed to know that you have a notification when the app is shut down?

**Comment by oney** [comment]
The code in my README will cause this issue, and there is no way to solve it now. So, I recommended using [this configuration](https://github.com/Neson/react-native-system-notification#push-notifications-on-android) to avoid the issue.

**Comment by DHidee66** [comment]
@oney  I already installed `react-native-system-notification` and did replace `com..RNGcmListenerService` w/ `io.neson.react.notification.GCMNotificationListenerService`.
I just can't understand how do you show a notification when the app is completely shut down, not in background but terminated.

**Comment by oney** [comment]
Oh, got it.
Yes, you can. On Android, although the app is closed, it still can be launched by receiving GCM notification.
