### ISSUE TITLE
[Ios] 7.0.2 Crashed when first open app that download from testflight

### ISSUE THREAD

**Issue by KoreanThinker** [microsoft/react-native-code-push#2140]
### Steps to Reproduce
1. Relesae app to testflight
2. Download app from testflight
3. open app (crash)
4. never crashed after second open (reopen) the app

### Environment

* react-native-code-push version: 7.0.2
* react-native version: 0.65.1
* iOS/Android/Windows version: ios14.7.1
* Does this reproduce on a debug build or release build: release
* Does this reproduce on a simulator, or only on a physical device: only physical device

(The more info the faster we will be able to address it!)

**Comment by FengDaoCeYin** [comment]
I've encountered the same problem and look forward to repairing or answering it as soon as possible.Thanks!

**Comment by FengDaoCeYin** [comment]
I set hermes_enabled in Podfile to false,It's alright now.

**Comment by KoreanThinker** [comment]
> I set hermes_enabled in Podfile to false,It's alright now.

It's work well! But I need hermes. Do you have a any other idea?

**Comment by FengDaoCeYin** [comment]
> > I set hermes_enabled in Podfile to false,It's alright now.
> 
> It's work well! But I need hermes. Do you have a any other idea?

You can compare packaging scripts of reactnative and CodePush to see if there are any differences. Of course, it's best to wait for the authorities to sort it out. Looking forward to your success ~!
