### ISSUE TITLE
Update Event Listener (EventEmitter.removeListener('change', ...) has been deprecated)

### ISSUE THREAD

**Issue by felipeaugusto1** [microsoft/react-native-code-push#2142]
### Steps to Reproduce
1. Install `react-native-code-push` and check the AppState warning

### Expected Behavior
Update `react-native-code-push/CodePush.js` to use the new AppState logic (https://reactnative.dev/docs/appstate)

### Actual Behavior
What actually happens?

There's a warning right after open the app.

![Image from iOS](https://user-images.githubusercontent.com/6455124/133325906-68fc627c-8179-4c24-a0ff-07c82a3db673.png)

### Environment

* react-native-code-push version: 7.0.2
* react-native version: 0.65.1
* iOS/Android/Windows version: iOS 14.8
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

**Comment by rodgomesc** [comment]
same here

**Comment by kristijantomic** [comment]
@felipeaugusto1  this seems to be fixed with 7.0.3, but there is a problem with Android with https://github.com/microsoft/react-native-code-push/issues/2141 :)
