### ISSUE TITLE
CodePush showing 0 active installs

### ISSUE THREAD

**Issue by marklanhamhc** [microsoft/react-native-code-push#2154]
I've just setup CodePush on my React Native app (iOS and Android). I've successfully deployed the apps to **App Store Connect** and **Google Play Console**. I've installed the latest versions on the respective devices but App Center is still showing that I have no active installs? 

I have also tried deploying a CodePush on both platforms for a simple text change, maintaining the same versioning and deploying to **Pre-Production** and **Production** but nothing happens. Terminal is showing that the CodePush was successful and I can see the releases in App Center.

![Screenshot 2021-10-01 at 17 54 45](https://user-images.githubusercontent.com/19590762/135658683-69550539-c16e-45ac-bc83-f8e43d840ad6.png)

![Screenshot_20211001-180812](https://user-images.githubusercontent.com/19590762/135660288-6ca53107-3cf8-4298-b34c-d393ee54e731.jpg)

### Environment

* react-native-code-push version: **v7.0.2**
* react-native version: **v0.64.2**
* iOS version: **v15.0**
* Android version: **Android 9**
* Does this reproduce on a debug build or release build: **This is a release build**
* Does this reproduce on a simulator, or only on a physical device: **This has only been tested on physical devices**

**Comment by chirag-jain-furlenco** [comment]
@marklanhamhc Is your native app getting updated via codepush ?

**Comment by chiragiem36** [comment]
@marklanhamhc Is your native app getting updated via codepush ?

**Comment by 100sarthak100** [comment]
![Screenshot 2022-01-03 190021](https://user-images.githubusercontent.com/35603506/147936160-e57a2598-8d29-432c-8eec-21ec25d6f1a0.png)
Tried to integrate 5-6 times. Doesn't even work.

**Comment by MariaFF** [comment]
@100sarthak100  is target version the same of the published version ?

**Comment by saarukaadevi** [comment]
I too have a same issue ..(if i give one release in direct playstore then another one updated via codepush)is this releated to this scenerio?

**Comment by marklanhamhc** [comment]
> @marklanhamhc Is your native app getting updated via codepush ?

Sorry for the delayed reply, no, the app isn't getting updated via CodePush either.

**Comment by saarukaadevi** [comment]
> 

check the connection between play store and codepush.in my case it works

**Comment by chiragiem36** [comment]
@marklanhamhc You can use codepush's lifecycle method `codePushStatusDidChange (status)` to check if it is able to discover available update build
This function is called, every time status of codepush changes. You can use it to log status, `checking update/downloading/installing/install failed`
