### ISSUE TITLE
Confirmation react-native-code-push Supported Platform and Error CodePushNativeModule.java uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by zxccvvv** [microsoft/react-native-code-push#2155]
I just created React Native App `init` yesterday, and newest version of RN is `"react-native": "0.65.1"`, i've tried following https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-android.md , but i got an error:

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: [PersonalPath]/MyApp/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java uses unchecked or unsafe operations.

[another error caused by [PersonalPath]/debug/java/com/myapp/ReactNativeFlipper.java]
```

I recheck the installation guide and found Supported Platform RN https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms:
v0.65 | v7.2+ (RN updated iPhone-target-version)
-- | --

but the latest version of RNCP is 7.0+ not 7.2+

# Question
1. how do i get the latest version of RNCP? have tried used `npm install react-native-code-push@latest --save` but the installed version is 7.0.3
2. how do i run release Staging? i've tried using this command `npx react-native run-android --variant=releaseStaging` but i got an error `Task 'installReleaseStaging' not found in project ':app'. Some candidates are: 'uninstallReleaseStaging'.`

**Comment by myckhel** [comment]
Checkout https://stackoverflow.com/a/42288238/9241085 for No.2 solution
> You have to add signingConfig to the releaseStaging.
>
> releaseStaging {
        signingConfig signingConfigs.release
        buildConfigField "String", "CODEPUSH_KEY", CODEPUSH_KEY_STAGING
    }
