### ISSUE TITLE
No property named env.get(VERSION_NAME) exists in the android/gradle.properties file

### ISSUE THREAD

**Issue by dentep** [microsoft/react-native-code-push#2159]
I have built an app that collects the env props in React Native, but codepush is unable to read the version name from those files.

### Steps to Reproduce
1. Create .env file with VERSION_NAME param in it
2. Read it from app/build.gradle (versionName project.env.get("VERSION_NAME"))
3. Build and run your app
4. Try to codepush the app

### Expected Behavior
Command runs without errors and finishes the codepush process

### Actual Behavior
Command throws an error: "No property named env.get(VERSION_NAME) exists in the android/gradle.properties file".

### Environment

* react-native-code-push version: 7.0.3
* react-native version: 0.65
* Does this reproduce on a debug build or release build: both
* Does this reproduce on a simulator, or only on a physical device: all

**Comment by imran-hossain03** [comment]
Getting the same error

**Comment by anhquan291** [comment]
I'm also facing the same issue. Any updates please? Thanks a lot

**Comment by levi218** [comment]
I think you should export the VERSION_NAME variable manually before running codepush, or running this command to load the .env file into the console
```
export $(grep -v '^#' .env | xargs)
```

**Comment by vagnerlandio** [comment]
I was gettings the same error with the following files and settings:
```properties
# android/gradle.properties
versionName=1.23.5
```
```gradle
# android/app/build.gradle
android {
    ...
    defaultConfig {
        ...
        versionCode project.getProperties().get("versionCode").toInteger()
        versionName project.getProperties().get("versionName")
    }
    ...
}
```

To solve the issue, I just made the following change in the build.gradle file:
```diff
# android/app/build.gradle
android {
    ...
    defaultConfig {
        ...
        versionCode project.getProperties().get("versionCode").toInteger()
-       versionName project.getProperties().get("versionName")
+       versionName project.versionName
    }
    ...
}
```
