### ISSUE TITLE
Task :react-native-code-push:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by dayaki** [microsoft/react-native-code-push#2167]
I upgraded to react-native 0.66.0 and codepush stopped working, I keeping the error:

`> Task :react-native-code-push:compileDebugJavaWithJavac FAILED
An exception has occurred in the compiler (1.8.0_301). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)`

Any help would be appreciated.

* react-native-code-push version: 7.0.4
* react-native version: 0.66.0

**Comment by lucaswhitman** [comment]
Same issue, unfortunately @pedroraft's solution doesn't work on my end. But the cause is likely the same. I had to update the sdk to 31 for another library while upgrading our app to RN `0.66.3`.

**Comment by quanghoang2110** [comment]
RN: 0.66.3
Same issues, but after upgrade jdk to 11 and it's working fine
Try to upgrade jdk to 11 :)

**Comment by mertbo** [comment]
in my case, i had set `compileSdkVersion` 31 and `targetSdkVersion` 30 before. now, i set both to 30 and worked well.

**Comment by parth-koshta** [comment]
> RN: 0.66.3 TargetSdkVersion 31 Same issues, but after upgrade jdk to 11 and it's working fine Try to upgrade jdk to 11 :)

This works 🎉

**Comment by faustoct** [comment]
upgrading to jdk 11 worked

**Comment by faustoct** [comment]
upgrading to jdk 11 worked

**Comment by alexco2** [comment]
For me updating to JDK 11 unfortunaltly does not work. To use react-native-vision-camera I need sdk 31 though. If anybody has an idea how to solve this dilemma I would be greatfull.

**Comment by alexco2** [comment]
I was able to solve it. I had to upgrade the jdk that is referenced in JAVA_HOME in the environment variables, not only in Android studio.

**Comment by kyle-ssg** [comment]
https://github.com/microsoft/appcenter/issues/2067#issuecomment-888853402

For me, I had to force AppCenter to use JDK 11 for native builds

**Comment by bensonz** [comment]
I had java 8, saw this error, then I just did:
```
sdk use java 11.0.14-ms
```
To install it if you dont have this version, it's just 
```
sdk install java 11.0.14-ms
```
and it worked. I am on M1 Mac, not rosetta 2 terminal.
Hope it helps!

**Comment by dexiouz** [comment]
> in my case, i had set `compileSdkVersion` 31 and `targetSdkVersion` 30 before. now, i set both to 30 and worked well.

This worked for me

**Comment by mattgle** [comment]
If you don't want to downgrade the `compileSdkVersion` or `targetSdkVersion` you can try downloading JDK 11 (worked for me).

Here's a guide on how to install it via homebrew for Mac users:
https://medium.com/@kirebyte/using-homebrew-to-install-java-jdk11-on-macos-2021-4a90aa276f1c

**Comment by alita-moore** [comment]
I was having trouble and nothing was working. I was trying to debug in android studio by running the `react-native-code-push:compileDebugJavaWithJavac` directly like so
![Screen Shot 2022-11-04 at 4 36 30 PM](https://user-images.githubusercontent.com/26529820/200078625-836734db-76bf-4d70-a483-4735c24613f4.png)
I right clicked it and hit "edit run configuration" and then added the three flags `--debug --stacktrace --scan`; for whatever the reason, now it compiles just fine. I'm assuming it has something to do with some kind of gradle caching issue. But I don't know how to best clean that cache.

**Comment by vannydevelopper** [comment]
ca ca m'a aide 
android {
[...]
    configurations.all {
        resolutionStrategy {
            force 'androidx.browser:browser:1.3.0'
        }
    }
}
