### ISSUE TITLE
Issue has returned in our environment

### ISSUE THREAD

**Issue by markl-vesper** [microsoft/react-native-code-push#2170]
It was solved in my environment.
Problem: Android RN APP failed to render some icons & images after Code-Push updates
"react-native-code-push": "7.0.2",

Original Cause Found:  using RN assets system to load images, MUST release assets with JS bundle to CodePush (refers to https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-troubleshooting)

Original Solution: change to new bundle commands.

```
npx react-native bundle --entry-file index.js --bundle-output ./bundles/index.android.bundle --platform android --assets-dest ./bundles --dev false
npx appcenter codepush release -a VesperMarine/Cortex-Monitoring -c ./bundles/ -t $PACKAGE_VERSION -d Production --mandatory true
```

Image is imported via 

```
import vesperLogo from '../../../img/vesper_logo_color_800W.png'
```

After codepush update the image is not longer displayed but was present in the app store build

_Originally posted by @marsoochan in https://github.com/microsoft/react-native-code-push/issues/1350#issuecomment-915972333_

**Comment by markl-vesper** [comment]
currently testing 7.0.4 as i see some chatter about it resolving the issue

**Comment by Gerlison** [comment]
I have the same issue happening here. It seems like multiple codepush uploads to a unique version causes this. It´s almost like it loses the references to the assets. 
When this bug happens, reinstall the app from the store and the latest codepush after that, "solves" the issue.

I'm gonna try change the bundle command to use react-native bundle instead the appcenter CLI. Any updates I'll let you know.
