### ISSUE TITLE
[Android] Code push update, SVG image now shown

### ISSUE THREAD

**Issue by mileverse** [microsoft/react-native-code-push#2172]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. import { WithLocalSvg } from 'react-native-svg'
2. Insert an image through WithLocalSvg.
3. release build
4. code-push update

### Expected Behavior

The svg image should appear.

### Actual Behavior

The svg image disappear

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.63.2
* iOS/Android/Windows version: Android 9
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

**Comment by majirosstefan** [comment]
No stale, please.

**Comment by TommasoTate** [comment]
Any update on that? We are currently experiencing similar issue with .png images rendered on <Image> component, only for Android.

**Comment by leandrosimoes** [comment]
No stale, please.

**Comment by rajgupta027** [comment]
No Stale please. Its an important feature request.

**Comment by DmitriyKirakosyan** [comment]
Anyone still facing this issue, please try this workaround https://github.com/microsoft/react-native-code-push/issues/2684#issuecomment-2026917475
