### ISSUE TITLE
Does code push support the target version x.x.00x . 

### ISSUE THREAD

**Issue by jaindahersoftware** [microsoft/react-native-code-push#2181]
### Steps to Reproduce
The application apple store version is 1.0.001. When I try to code push to this target version. I got 

`Error:` Invalid binary version(s) for a release.`

But I try to release a 1.0, its successfully uploaded the patch in code push appcenter. But the app is not downloading this version from code push appcenter

### Expected Behavior

Need to upload a version with 1.0.001

### Actual Behavior
What actually happens?

`Error:` Invalid binary version(s) for a release.`

### Environment

* react-native-code-push version: 6.3.0
* react-native version: 0.62.1

**Comment by SMKH-PRO** [comment]
Did you find any solution to this?
