### ISSUE TITLE
Changes are not reflecting after code push in Android Only

### ISSUE THREAD

**Issue by rishabh9141** [microsoft/react-native-code-push#2183]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Environment

* react-native-code-push version: "^7.0.4"
* react-native version: "0.64.2"

**Comment by ToshKoevoets** [comment]
Yes same here; spend few hours debugging. In the process also my emulator is broken in debug mode. Not sure if it's related.

Also on
react-native-code-push version: "^7.0.4"

But downgraded to latest verions of 6 and 7.0.1. But didn't matter.

```
  codePush.checkForUpdate('xxx')
      .then((update) => {
        if (!update) {
          Alert.alert("The app is up to date!");
        } else {
          Alert.alert("Update available");
        }
      })
      .catch((err) => {
        Alert.alert('err', JSON.stringify(err));
      })
  ```

Comes to an error

<img width="1063" alt="Screen Shot 2021-09-15 at 5 34 19 PM" src="https://user-images.githubusercontent.com/1196672/142741334-ada591a1-b9bc-4d79-a5ec-32bd5724fe00.png">

Not really sure; but it seems like there is an error, maybe a syntax error, in the generated android file.

**Comment by ToshKoevoets** [comment]
Ok was solved quickly in my case when I got it running in debug mode android.

For me the issue was that android expects semver versionName "1.0.1" in the manifest otherwise gives an error.

**Comment by ToshKoevoets** [comment]
It ended up being the issue that I didn't have proper versionName in the android manifest: 159 instead of 1.5.9. 

iOS works fine no matter what, but Android needs this.
