### ISSUE TITLE
Support compileSdkVersion 31

### ISSUE THREAD

**Issue by christophemenager** [microsoft/react-native-code-push#2184]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Change compileSdkVersion to 31 in build.gradle
2. `react-native run-android`

### Expected Behavior
No error during build

### Actual Behavior
Following error during build : 
What actually happens?
```
  Execution failed for task ':react-native-code-push:compileDebugJavaWithJavac'.
```

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.66.3
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by parth-koshta** [comment]
+1
@christophemenager Did you find a workaround for this?

**Comment by parth-koshta** [comment]
> +1 @christophemenager Did you find a workaround for this?

This issue can be fixed by updating jdk version to 11

**Comment by Mohamed-kassim** [comment]
@parth-koshta what was your previous version before updating?

**Comment by eliyahu-kriel** [comment]
same problem

**Comment by parth-koshta** [comment]
> @parth-koshta what was your previous version before updating?

@Mohamed-kassim  It was 8

**Comment by eliyahu-kriel** [comment]
@parth-koshta thanks, work great after updating to jdk 11 !

**Comment by karim-mohammed** [comment]
how to update to jdk 11 on mac os ??

**Comment by eliyahu-kriel** [comment]
@karim-mohammed - [i followed this tutorial ](https://www.youtube.com/watch?v=p_ielKr3k7U&t=233s)
