### ISSUE TITLE
APP is checking for updates everytime as the app starts

### ISSUE THREAD

**Issue by puneetkansal04** [microsoft/react-native-code-push#2185]
I am using this but this is not useful as it loads bundle everytime the app starts

codePush.sync(
{
installMode: codePush.InstallMode.IMMEDIATE,
},

I want that it will check for updates Only when a new update is live. So how can i do that.

**Comment by doomkit** [comment]
The `installMode` option only controls the moment when the update would be applied. If you want to control the frequency of update checks, you need to set the `CheckFrequency` option. To check for an update only when it's available you probably need to use:
```js
CodePush({ checkFrequency: CodePush.CheckFrequency.MANUAL });
```
and implement your logic around it, which will trigger the updateCheck only when you want.
