### ISSUE TITLE
Set the app secret in environment variables

### ISSUE THREAD

**Issue by hansyulian** [microsoft/react-native-code-push#2187]
Is it possible to set the `app_secret` which should be set in `android/app/src/main/assets/appcenter-config.json` and `Info.plist` to be taken from environment? 

I use the `react-native-config` to set the environment variables if this detail also matter.

**Comment by mben1981** [comment]
Hey you MS you have all the money in the world and can't answer a simple questions ?

**Comment by clementvtrd** [comment]
+1
