### ISSUE TITLE
[Android] Why rollback exists only Android?

### ISSUE THREAD

**Issue by mym0404** [microsoft/react-native-code-push#2192]
I don't expect why rollback happens on Android only but iOS. I don't think I missed any configuration or api usage fault... Any idea?

### Android appcenter app
![image](https://user-images.githubusercontent.com/33388801/145534405-274174a2-a328-46a3-bdf3-74fd2debee9e.png)
### iOS appcenter app
![image](https://user-images.githubusercontent.com/33388801/145534416-eee00087-7933-4976-ba7f-a5b55b2fa8d0.png)

### JS api

```js
AppRegistry.registerComponent('MathKing', () => App);
```

```tsx
const App = ({ isHeadless }) => {
  if (isHeadless) {
    return null;
  }
  return <CodePushApp />;
};
```

```tsx
const CodePushApp = () => {
  useMount(() => {
    AsyncStorage.getItem('__QA_USER').then((value) => {
      if (value && value === TRUE) {
        return;
      }
      CodePushUtil.downloadBundle({ type: 'production', installMode: codePush.InstallMode.ON_NEXT_RESTART }).catch(
        (e) => {
          SentryWrapper.throw('CodePush sync in CodePushApp 실패', e);
        },
      );
    });
  });
  return <RootProvider />;
};

export default codePush({
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.ON_NEXT_RESTART,
  mandatoryInstallMode: codePush.InstallMode.ON_NEXT_RESTART,
  rollbackRetryOptions: {
    delayInHours: 6,
    maxRetryAttempts: 5,
  },
})(CodePushApp);
```

#### RootProvider(Root component, call notfiyAppReady function)
```tsx
const RootProvider = ({ preloadedState, children }: PropsWithChildren<Props>) => {

  useMount(() => {
    CodePushUtil.notifyAppReady();
  });
```

### Expected Behavior
What you expected to happen? No rollback on Android too

### Environment

* react-native-code-push version: `7.0.4`
* react-native version: `0.65.1`
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? `release`
* Does this reproduce on a simulator, or only on a physical device? `physical`

(The more info the faster we will be able to address it!)

**Comment by nchase** [comment]
@mym0404 check out the recent discussion in this issue and see if it provides any clues: https://github.com/software-mansion/react-native-gesture-handler/issues/1675#issuecomment-998322769

I haven't had time to test the solution proposed there, but the hypothesis seems reasonable 😄

**Comment by mym0404** [comment]
Well, I didn't call `restartApp` manually in my application. It seems to not related to my situation Thanks.

**Comment by fabriciosautner** [comment]
same problem

**Comment by rnike** [comment]
same issue here, can't reproduce and felt almost blind without further information of rollbacks
