### ISSUE TITLE
java.lang.NullPointerException in FileUtils.java

### ISSUE THREAD

**Issue by simonchengbbyca** [microsoft/react-native-code-push#2193]
Hi,
We had a production crash on in FileUtils.java. We had to try-catch in the source file to avoid unnecessaries:

        try {
            sourceDir = new File(sourceDirectoryPath);
            destDir = new File(destinationDirectoryPath);
        } catch (NullPointerException e) {
            throw new CodePushUnknownException("Error creating directories", e);
        }

Would you please add similar protection in the Code Push project so we do not need to patch by ourselves? Moreover, it would be even better if you can figure out the root cause of the issue.

Thanks,

Simon

Here is the location of the issue:
https://github.com/microsoft/react-native-code-push/blob/3f6219cca18b2aced4381935ca00a08cc54e3a13/android/app/src/main/java/com/microsoft/codepush/react/FileUtils.java#L19

Call stacks:
java.io.File.<init> (File.java:283)
com.microsoft.codepush.react.FileUtils.copyDirectoryContents (FileUtils.java:19)
com.microsoft.codepush.react.CodePushUpdateUtils.copyNecessaryFilesFromCurrentPackage (CodePushUpdateUtils.java:100)
com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage (CodePushUpdateManager.java:242)
com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground (CodePushNativeModule.java:290)
com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground (CodePushNativeModule.java:284)
android.os.AsyncTask$3.call (AsyncTask.java:394)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:923)

**Comment by simonchengbbyca** [comment]
Duplicated https://github.com/microsoft/react-native-code-push/issues/2087

**Comment by jamninetyfive** [comment]
Have you solved it@[simonchengbbyca](https://github.com/simonchengbbyca)
