### ISSUE TITLE
Could not get BatchedBridge, make sure your bundle is packaged correctly

### ISSUE THREAD

**Issue by gentlee** [microsoft/react-native-code-push#2194]
### Steps to Reproduce
1. Make any ts file changes
2. Code push to staging (appcenter codepush release-react -a appname -d Staging -t 1.2.3)
3. `CodePush.sync({ installMode: CodePush.InstallMode.IMMEDIATE })` is called on next app launch, update is downloaded and app restarted
4. App crashes with that error
5. Next app launch is fine but without new changes

### Expected Behavior
App shouldn't crash on codepush updates

### Actual Behavior
```
RCTFatalException: Could not get BatchedBridge, make sure your bundle is packaged correctly

facebook::react::JSIExecutor::defaultTimeoutInvoker
```

### Environment

* react-native-code-push version: 6.4.1, 7.0.2, 7.04
* react-native version: 0.63.4
* appcenter-cli version: 2.10.7
* iOS/Android/Windows version: iOS 15.1
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? simulator and physical device

**Comment by Gentlee** [comment]
Bundling manually and using "-c ios/main.jsbundle" option with "appcenter codepush release-react" doesn't help. Seems that there is a bug on appcenter backend side while reformatting js bundle.

**Comment by Gentlee** [comment]
Issue fixed by using appcenter-cli 2.9.0, but bundle is not converted to hermes format.

**Comment by dubinam** [comment]
Hey, got the same issue with android build.

**Comment by NomanAfzal26** [comment]
Hey got the same problem with cross application

**Comment by slrwinter** [comment]
Any update? I got the same issue

**Comment by NomanAfzal26** [comment]
hi,
I was using EXPO and resolved the issue by upgrading and then downgrading
it to the previous one.

**Comment by NomanAfzal26** [comment]
thenkx man for your time

Noman Afzal
+92 308 383 3433
***@***.***

**Comment by FiratYildiz-Lingua** [comment]
Hello, I'm having this exact issue on a newer version of React Native and CodePush, the app crashes immediately when the update is downloaded, and rolls back on the next launch.

Here's the crash log from Firebase Crashlytics:

`Fatal Exception: RCTFatalException: Could not get BatchedBridge, make sure your bundle is packaged correctly
0  CoreFoundation                 0x1217e0 (Missing UUID b02805dc7bce35718eb6ff671506488b)
1  libobjc.A.dylib                0x25144 (Missing UUID ebfccc6696d434d386b4a0b3937a18ac)
2  <appName>                         0x28dd58 RCTFormatError + 167 (RCTAssert.m:167)
3  <appName>                         0x2a315c -[RCTCxxBridge handleError:] + 1180 (RCTCxxBridge.mm:1180)
4  <appName>                         0x2a1a58 __34-[RCTCxxBridge _initializeBridge:]_block_invoke + 688 (RCTCxxBridge.mm:688)
5  <appName>                         0x2b4c34 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) + 73 (RCTMessageThread.mm:73)
6  <appName>                         0x2b49d0 invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>) + 46 (RCTMessageThread.mm:46)
7  CoreFoundation                 0x85fa4 (Missing UUID b02805dc7bce35718eb6ff671506488b)
8  CoreFoundation                 0x856ec (Missing UUID b02805dc7bce35718eb6ff671506488b)
9  CoreFoundation                 0x7fef0 (Missing UUID b02805dc7bce35718eb6ff671506488b)
10 CoreFoundation                 0x7f7f4 (Missing UUID b02805dc7bce35718eb6ff671506488b)
11 <appName>                         0x29f5e8 +[RCTCxxBridge runRunLoop] + 335 (RCTCxxBridge.mm:335)
12 Foundation                     0x4e4aac (Missing UUID 532aae62f6cf3de28988170389a83ad5)
13 libsystem_pthread.dylib        0x74e4 (Missing UUID 030d2641514f373f9688582d9d3b369a)
14 libsystem_pthread.dylib        0x26cc (Missing UUID 030d2641514f373f9688582d9d3b369a)`

# Environment
- react-native-code-push version: 7.0.4
- react-native version: 0.70.6
- appcenter-cli version: 2.12.0
- iOS/Android/Windows version: iOS 16.1
- Does this reproduce on a debug build or release build? release
- Does this reproduce on a simulator, or only on a physical device? simulator

**Comment by Pavel-Lunin** [comment]
`npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res `

**Comment by privatepej** [comment]
Any update? I got the same issue

**Comment by hepoblet** [comment]
I have this problem on iOS, any idea how to solve it?
