### ISSUE TITLE
new nativeeventemitter() was called with a non-null argument without the required `removeListener` method

### ISSUE THREAD

**Issue by ChrisWiles** [microsoft/react-native-code-push#2196]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Try to download & install a codepush 

### Actual Behavior
What actually happens?
![Screenshot_20211221-083955r](https://user-images.githubusercontent.com/9455409/146948654-9de4b357-6388-4b97-891b-ddd73305e19f.jpg)

This may be the issue https://github.com/microsoft/react-native-code-push/blob/9947037a985a04927c64624318e4ce64d43d2049/package-mixins.js#L17

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.66.4

**Comment by Rodrigo816** [comment]
Same problem, any hotfix?

**Comment by Udbhav12** [comment]
This issue is being faced in multiple rn packages

Seems similar to https://github.com/react-native-netinfo/react-native-netinfo/issues/486

Something of this sort needs to be added - https://github.com/react-native-netinfo/react-native-netinfo/issues/486#issuecomment-902029567

**Comment by layeng** [comment]
Hi I have faced this issue since Jan 2022. I saw in the my code that the 2 listeners are available but the problem still happens. Any solution or just ignore the warnings?

 @ReactMethod
    public void addListener(String eventName) {
        // Keep: Required for RN built in Event Emitter Calls.
        mConnectivityReceiver.hasListener = true;
    }

    @ReactMethod
    public void removeListeners(Integer count) {
        // Keep: Required for RN built in Event Emitter Calls.
        if (count == 0) {
            mConnectivityReceiver.hasListener = false;
        }
    }
