### ISSUE TITLE
Local Image not loading in IOS release version but working fine in android.

### ISSUE THREAD

**Issue by rj7shakya** [microsoft/react-native-code-push#2197]
### Steps to Reproduce
1. Used "react-native-code-push": "^7.0.4"
2.After using this package "Something went wrong. Please verify if generated JS bundle is correct." issue is shown. 
3.Used "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'" command 
    to remove above issue.
4.Now production ios app is running but local image not loading.

### Environment

* react-native-code-push version:^7.0.4
* react-native version:0.63.2
* iOS/Android/Windows version: macOS Big Sur v11.6
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by doomkit** [comment]
@rj7shakya what steps are required to do to get this error `Something went wrong. Please verify if generated JS bundle is correct`?

**Comment by Ruchit-Bhanderi** [comment]
same
