### ISSUE TITLE
[iOS] Always rollback to load from mainBundle.

### ISSUE THREAD

**Issue by voids** [microsoft/react-native-code-push#2200]
### Steps to Reproduce
1. AppDelegate.m
    ```Objective-C
    - (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
    #if DEBUG
        return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
    #else
        return [CodePush bundleURL];
    #endif
    }
    ```
2. index.js
    ```typescript
    global.Buffer = global.Buffer || require('buffer').Buffer;
    global.process = require('process');
    import 'react-native-gesture-handler';
    import CodePush from 'react-native-code-push';
    import App from './src/App';
    import {AppRegistry} from 'react-native';
    import {name as appName} from './app.json';
    
    const options = {checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME};
    AppRegistry.registerComponent(appName, () => CodePush(options)(App));
    ```

### Actual Behavior
After double-click home and kill process, load from mainBundle again. 
see the screen capture below:

![image](https://user-images.githubusercontent.com/7220523/147634165-f878ed66-21aa-4bc5-9115-9d3c6035e713.png)

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.66.4
* iOS version: 14.8.1
* Does this reproduce on a debug build or release build?  **release**
* Does this reproduce on a simulator, or only on a physical device?  **physical device**

**Comment by tuandinh0801** [comment]
@voids I also met this issue on RN 0.66.4. You found any reasons for that?

**Comment by voids** [comment]
@tuandinh0801  

I found that iOS use "ON_NEXT_RESTART", and Android use "IMMEDIATE" works well.

> index.js

```javascript
const options = {checkFrequency: CodePush.CheckFrequency.MANUAL};
AppRegistry.registerComponent(appName, () => CodePush(options)(App));
```

> updater.ts 

```typescript
private check = () => {
    await CodePush.notifyAppReady();
    this.setState({package: await CodePush.checkForUpdate(undefined, this.mismatch)});
};

private mismatch = () => NativeUtil.upgrade();

private install = async () => {
    const mode = Platform.OS === 'ios' ? CodePush.InstallMode.ON_NEXT_RESTART : CodePush.InstallMode.IMMEDIATE;
    const options: SyncOptions = {
        installMode: mode,
        mandatoryInstallMode: mode
    };
    if (!this.state.package) return;
    this.setState({progress: 0, info: `${calcSize(0)}/${calcSize(this.state.package.packageSize)}`});
    await CodePush.sync(options, undefined, this.renderProgress);
};

private renderProgress = (progress: DownloadProgress) => {
    this.setState({
        progress: progress.totalBytes / progress.totalBytes,
        info: `${calcSize(progress.totalBytes)}/${calcSize(progress.totalBytes)}`
    });
};
```

**Comment by tuandinh0801** [comment]
@voids Thanks, but I tried 'ON_NEXT_START' already and it's crashed on reopening the app as well, Android works fine with 'ON_NEXT_START'

**Comment by newbanker-tu** [comment]
> @voids Thanks, but I tried 'ON_NEXT_START' already and it's crashed on reopening the app as well, Android works fine with 'ON_NEXT_START'

my project iOS is fine ,but android is crash when use ON_NEXT_START,

**Comment by tuandinh0801** [comment]
I just found a workaround solution. Idea is that lazy load the App to force some packages re-init after updating codepush
```javascript
const RootApp = () => {
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    setIsLoading(false)
  }, [])

  if (isLoading) {
    return <LoadingApp />
  }

  const App = require('./src/App').default

  return <App />
}
```

**Comment by newbanker-tu** [comment]
> @tuandinh0801
> 
> I found that iOS use "ON_NEXT_RESTART", and Android use "IMMEDIATE" works well.
> 
> > index.js
> 
> ```js
> const options = {checkFrequency: CodePush.CheckFrequency.MANUAL};
> AppRegistry.registerComponent(appName, () => CodePush(options)(App));
> ```
> 
>  > updater.ts
> 
> ```ts
> private check = () => {
>     await CodePush.notifyAppReady();
>     this.setState({package: await CodePush.checkForUpdate(undefined, this.mismatch)});
> };
> 
> private mismatch = () => NativeUtil.upgrade();
> 
> private install = async () => {
>     const mode = Platform.OS === 'ios' ? CodePush.InstallMode.ON_NEXT_RESTART : CodePush.InstallMode.IMMEDIATE;
>     const options: SyncOptions = {
>         installMode: mode,
>         mandatoryInstallMode: mode
>     };
>     if (!this.state.package) return;
>     this.setState({progress: 0, info: `${calcSize(0)}/${calcSize(this.state.package.packageSize)}`});
>     await CodePush.sync(options, undefined, this.renderProgress);
> };
> 
> private renderProgress = (progress: DownloadProgress) => {
>     this.setState({
>         progress: progress.totalBytes / progress.totalBytes,
>         info: `${calcSize(progress.totalBytes)}/${calcSize(progress.totalBytes)}`
>     });
> };
> ```

seem to you, did you resolve ?

**Comment by newbanker-tu** [comment]
> I just found a workaround solution. Idea is that lazy load the App to force some packages re-init after updating codepush
> 
> ```js
> const RootApp = () => {
>   const [isLoading, setIsLoading] = useState(true)
> 
>   useEffect(() => {
>     setIsLoading(false)
>   }, [])
> 
>   if (isLoading) {
>     return <LoadingApp />
>   }
> 
>   const App = require('./src/App').default
> 
>   return <App />
> }
> 
> const codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL }
> const CodePushedApp = codePush(codePushOptions)(RootApp)
> 
> AppRegistry.registerComponent(appName, () => CodePushedApp)
> ```

I'm trying to solve it. Mine doesn't seem to apply
Or maybe I didn't use it correctly
