### ISSUE TITLE
Code is not getting Update in IOS on TestFlight build or on Release build

### ISSUE THREAD

**Issue by raaidkh-tsa** [microsoft/react-native-code-push#2201]
### Expected Behavior
I am Updating code to production through
code-push release-react <AppName> ios -d Production -t "2.4.6"
Code should be update in on TestFlight App

### Actual Behavior
My code is not reflecting in TestFlight release or running app in release mode

info.plist

<key>NSExceptionDomains</key>
			<dict>
		<key>codepush.azurewebsites.net</key>
        	<dict>
            	<key>NSExceptionAllowsInsecureHTTPLoads</key>
            	<true/>
        	</dict>
        	<key>codepush.blob.core.windows.net</key>
        	<dict>
            	<key>NSExceptionAllowsInsecureHTTPLoads</key>
            	<true/>
        	</dict>
        	<key>codepushupdates.azureedge.net</key>
        	<dict>
            	<key>NSExceptionAllowsInsecureHTTPLoads</key>
            	<true/>
       		</dict>
			<key>localhost</key>
			<dict>
				<key>NSExceptionAllowsInsecureHTTPLoads</key>
				<true/>
				<key>NSTemporaryExceptionMinimumTLSVersion</key>
				<string>TLSv1.1</string>
			</dict>

<key>CodePushDeploymentKey</key>
<string>Key</string>

Podfile also Added 
# CodePush plugin dependency
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

App.js

React.useEffect(() => {
    codePush.sync({
      installMode: codePush.InstallMode.IMMEDIATE,
    })
  }, [])

const codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_START,
  installMode: codePush.InstallMode.IMMEDIATE
}
export default codePush(codePushOptions)(App);

![Screenshot 2022-01-06 at 11 20 33 AM](https://user-images.githubusercontent.com/70013991/148335255-a307a5d3-bf7f-4784-b02c-f949b1066f35.png)

Also getting App is up to date in logs and CodePush is working

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.63.3
* iOS/Android/Windows version: 15.2
* Does this reproduce on a debug build or release build?
* Release build
* Does this reproduce on a simulator, or only on a physical device?
* physical Device

**Comment by doomkit** [comment]
@raaidkh-tsa have you checked the binary version, that is running on your device? Is it the same version you're releasing?
