### ISSUE TITLE
Sometimes it takes about 10 minutes to get a code push down.

### ISSUE THREAD

**Issue by dkahdwk** [microsoft/react-native-code-push#2206]
### Steps to Reproduce
1. I run my app.
2. Check whether the code is pushed and download it.
3. ReceivedBytes levels sometimes rise and take 10 minutes. (sometimes)

Usually, I download it in 3 to 5 seconds.
There is no problem with the data download environment. (Wifi)

Sometimes it takes 10 minutes to download the code push. If I shut down the app and download it again, I sometimes 

At a slow point in time, all other devices are slow to code- push. From this problem, I think it's a ms server problem.

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.64.2
* iOS/Android/Windows version: 
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by dkahdwk** [comment]
@alexnekrashevich help me... I'm frustrated because there's no response....

**Comment by dkahdwk** [comment]
The reason why i'm sure it's MS server is because : the progress is going up slowly.
```jsx
                    CodePush.sync(
                        {
                            installMode: CodePush.InstallMode.IMMEDIATE,
                            mandatoryInstallMode: CodePush.InstallMode.IMMEDIATE
                        },
                        async (status) => {
                            switch (status) {
                                case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
                                    break;
                                case CodePush.SyncStatus.INSTALLING_UPDATE:
                                    break;
                                case CodePush.SyncStatus.UPDATE_INSTALLED:
                                    break;
                                case CodePush.SyncStatus.SYNC_IN_PROGRESS:
                                    break;
                            }
                        },
                        (progress) => {

                            // Getting the code push data!
                            // When code push is slow, data is received, but data is downloaded at about 10 minutes.
                            setSyncProgress(progress);
                        },
                    );
```

**Comment by jaekwangLee** [comment]
Is there any ideas?
This issue continues to create an uncomfortable situation. 😥

**Comment by dkahdwk** [comment]
@alexandergoncharov The speed issue drives me crazy. Did you stop developing it?

**Comment by Hemistone** [comment]
@jaekwangLee 
I've also suffered slow codepush download speed. 
It's not a solution, but this was my personal conclusion.
https://github.com/microsoft/react-native-code-push/issues/2009#issuecomment-1041216770

**Comment by Mai-Hong-Son** [comment]
same problem :((

**Comment by witalobenicio** [comment]
same problem here.

**Comment by cnx-renansoares** [comment]
same here

**Comment by shawarmaz** [comment]
same 

`Distribute is Experiencing Issues` for 5 days now 

<https://status.appcenter.ms/>

Ngl feels like CodePush is getting sunset

Anybody know of an alternative ?
