### ISSUE TITLE
No known class method for selector 'startSession'

### ISSUE THREAD

**Issue by Yandamuri** [microsoft/react-native-code-push#2225]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Please follow this [guide](https://appcenter.ms/orgs/Grosmart/apps/CodepushTesting) to add `Add App Center’s SDK to your app.`
2. Then run project from Xcode
3. Eventually you will end-up with an error,
4. This is the file where this is error is showing  =>`/node_modules/appcenteranalytics/ios/AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.m`
5. This is the block of code where error is showing

<img width="765" alt="Screenshot 2022-02-21 at 2 45 55 PM" src="https://user-images.githubusercontent.com/31983789/154924595-7fcb1668-f270-4216-ab5b-23a7119148e6.png">

### Expected Behavior
As per this [guide](https://appcenter.ms/orgs/Grosmart/apps/CodepushTesting) project should run without any errors

### Actual Behavior
facing following error

<img width="898" alt="Screenshot 2022-02-21 at 2 33 17 PM" src="https://user-images.githubusercontent.com/31983789/154922405-4c957358-1d2d-40ed-9a00-fea611fcdc07.png">

### Reproducible Demo

Please find the reproducible demo here -- https://github.com/Yandamuri/CodepushTesting

### Environment

     * react-native-code-push version: "^7.0.4"
     * react-native version: "0.67.2",
     * iOS/Android/Windows version: iOS
     * Does this reproduce on a debug build or release build? Both Debug and Release
     * Does this reproduce on a simulator, or only on a physical device? Both simulator and physical device

(The more info the faster we will be able to address it!)

**Comment by pgiki** [comment]
I cannot compile code-push for android on React Native 0.67.2 either. Maybe my issue and yours are related to code-push compatibility with React Native 0.67.2? Per the readme doc only up to RN 0.65 is listed so far. If anyone was able to ever compile react-native-code-push@7.0.4 please let me know.

**Comment by RouteMars** [comment]
same issue

**Comment by peter-h-fortum-partner** [comment]
I had this issue too. My app uses React Native 0.66.4 which is also above the official compatibility for CodePush. I got the app building again by downgrading appcenter, appcenter-analytics and appcenter-crashes from 4.4.3 to 4.3.0 and re-installing pods. Not sure exactly why but I had to edit Podfile.lock to force the 4.3.0 version there too.

Looking quickly at the appcenter issue linked above there might other ways to solve this that don't require downgrading, though.

**Comment by Adnan-Bacic** [comment]
i updated appcenter from `4.2.0` to the currently newest version of `4.4.4` and had this error. running `pod update` fixed it for me. apparently not all my ios pods were updated initially.

though im curious as to why the versions of appcenter arent all the same, here is some of my `Podfile.lock`:

```
PODS:
  - appcenter-analytics (4.4.4):
    - AppCenter/Analytics (~> 4.0)
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - appcenter-core (4.4.4):
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - appcenter-crashes (4.4.4):
    - AppCenter/Crashes (~> 4.0)
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - AppCenter/Analytics (4.4.2):
    - AppCenter/Core
  - AppCenter/Core (4.4.2)
  - AppCenter/Crashes (4.4.2):
    - AppCenter/Core
  - AppCenterReactNativeShared (4.4.4):
    - AppCenter/Core (= 4.4.2)
```

as you can see all the lowercase appcenter dependencies(`appcenter-analytics`, `appcenter-core`, `appcenter-crashes`) were all updated from `4.2.0` to `4.4.4` when i updated appcenter.

meanwhile `AppCenter/Analytics`, `AppCenter/Core` and `AppCenter/Crashes` show version `4.4.2` after updating but there were version `4.3.0` before updating, also not matching the all lowercase versions just above them.

looking at: https://cocoapods.org/pods/AppCenter

the newest version seems to be `4.4.2`

maybe im missing something, but why does the `Podfile.lock` contain 2 different lists of appcenter dependencies with different versions?
