### ISSUE TITLE
Feature: Simulating Codepush in development

### ISSUE THREAD

**Issue by stopachka** [microsoft/react-native-code-push#2233]
Hey team. I want to create my own mix of minimally intrusive + fast updates. For example, in certain situations I want to show a loading screen, etc 

When doing this though, it's a bit hard because in dev, I can't tell how the code will actually behave. Hence an idea: perhaps we could have a function on codepush that we can run in dev, something like: 

```
codePush.simulateUpdate({mandatory: true, downloadMs: 200}); 
```

I could get around this function by an indirection, but thought this would be valuable for the community as a whole

**Comment by italomlp** [comment]
Agreed. I'm in the same situation here. The way that I'm working is using some mocks for the values that would come from CodePush event handlers. Did you manage to do it more reliably?
