### ISSUE TITLE
CodePush not working on iOS Simulator

### ISSUE THREAD

**Issue by BranislavBrnjos** [microsoft/react-native-code-push#2242]
Hello i am able to get the logs in the Terminal when Android Simulator is on, but i cant seem to get the logs for iOS Simulator:

<img width="693" alt="Screen Shot 2022-04-08 at 3 12 17 PM" src="https://user-images.githubusercontent.com/51318860/162442608-8f7212ec-fff2-4f58-a469-4ed2764d0321.png">

I have followed the iOS Implementation:
AppDelegate.m
<img width="267" alt="Screen Shot 2022-04-08 at 3 13 09 PM" src="https://user-images.githubusercontent.com/51318860/162442804-49eda58c-4b89-4791-8a97-67d3085e7db7.png">
<img width="806" alt="Screen Shot 2022-04-08 at 3 19 46 PM" src="https://user-images.githubusercontent.com/51318860/162443894-04a10ee0-fafb-4973-bc5e-18e445b7f088.png">

Info.plist
<img width="422" alt="Screen Shot 2022-04-08 at 3 14 07 PM" src="https://user-images.githubusercontent.com/51318860/162442917-25c1db31-3293-4397-956b-4e3f5f6a31e7.png">

App.js
<img width="374" alt="Screen Shot 2022-04-08 at 3 24 35 PM" src="https://user-images.githubusercontent.com/51318860/162444785-39603b82-736c-41c8-af40-efd9cc762b51.png">
<img width="423" alt="Screen Shot 2022-04-08 at 3 24 31 PM" src="https://user-images.githubusercontent.com/51318860/162444790-e2a9db1c-e1f4-4a00-b887-aa30892f18ec.png">
<img width="394" alt="Screen Shot 2022-04-08 at 3 24 24 PM" src="https://user-images.githubusercontent.com/51318860/162444792-9ddb0c37-1e64-4c7e-a839-0e8c2b503198.png">

Note:
Android: appcenter codepush release-react -a example.example.com/example -d Staging
iOS: appcenter codepush release-react -a example.example.com/example -d Staging

Work fine, and i can see the code push "releases" on the AppCenter Dashboard.

### Steps to Reproduce
1. yarn install
2. cd ios && pod install
3. cd .. yarn start
4. yarn ios

### Expected Behavior
I am expecting to get the Logs for the code-push in the terminal when the iOS Simulator is working alone?

### Actual Behavior
I do not get any logs in my terminal.

### Environment

* "react-native-code-push": "^7.0.4",
* "react-native": "0.64.2",

**Comment by feras-merwas** [comment]
@BranislavBrnjos  

did you find any solution

**Comment by BranislavBrnjos** [comment]
@feras-merwas I have not, I tried going threw the documentation again, and reading step by step, also changed the frequency and install mode, but had no luck... It's still acting the same..

**Comment by FadiAboMsalam** [comment]
@BranislavBrnjos @feras-merwas  I faced a similar issue the only thing that worked with me is to change the Scheme --> info --> build Configuration to **release** instead of debug it worked for me then
