### ISSUE TITLE
CodePush.checkForUpdate is failing/crashing

### ISSUE THREAD

**Issue by rohitdhall07** [microsoft/react-native-code-push#2245]
### Steps to Reproduce
1. Call CodePush.checkForUpdate from react-native-code-push
2. This had been working on live since last 4 months and suddenly starting causing this problem today.
3.   CodePush.checkForUpdate()
.then((update) => {
    console.log("At update", JSON.stringify(update));
})
.catch((e) => console.log("At error", e));

### Expected Behavior
Promise should resolve and it should return RemotePackage object or null.

### Actual Behavior
Giving error in catch block: [TypeError: Network request failed]

### Environment

* react-native-code-push version: 6.4.1
* react-native version: 0.67.0
* iOS/Android/Windows version: All versions
* Does this reproduce on a debug build or release build? -- Release build
* Does this reproduce on a simulator, or only on a physical device? -- All devices and simulators

**Comment by TheMechanical** [comment]
Same problem. Error: [TypeError: Network request failed]

**Comment by blueberry6401** [comment]
This may be the reason. Did they not notice their server?

<img width="805" alt="image" src="https://user-images.githubusercontent.com/7337535/162615709-4a36c4e5-8ad0-40b3-a1bd-98e5d9d5f3c3.png">

**Comment by AbdulZaid** [comment]
It's crashing our apps. Their website seems to be down as well. @alexnekrashevich

**Comment by efeakyuz** [comment]
Any updates?

**Comment by aqweider** [comment]
We have the same issue. 
Do we expect the service to back soon or you giving up this service?

**Comment by adsalihac** [comment]
Same issue , what the problem ?

**Comment by Victor-Daniel-M** [comment]
Same issue, been down for ~3hrs now, what's the problem.

**Comment by witalobenicio** [comment]
@Victor-Daniel-M Certificate of code.appcenter.ms has expired. We have to wait for them to fix it.

**Comment by dorota-uw** [comment]
Any updates on that one? Any ETA? Same issue here.

**Comment by efeakyuz** [comment]
@alexandergoncharov-zz Any updates?

**Comment by ahmedfarag1993** [comment]
Any updates ?

**Comment by rohitdhall07** [comment]
This issue has not been acknowledged yet by App Center at https://status.appcenter.ms/#.
I have written to App Center support as well, minimum reply time is 8 hours.

One of my friends has also tweeted this tagging VS App Center (link below).
The people experiencing this issue can help and raise this until someone responsible replies to this.

https://twitter.com/jerinjohnk/status/1513107279649771524?t=6gRvTOaWl028fyqZZwhPvA&s=08

**Comment by mediabc** [comment]
Certificate just was renewed.
Probably the issue is fixed

**Comment by goguda** [comment]
Yeah, this was bad. Left our app down in production for about 4-6 hours this morning as well.

Perhaps an (optional?) failsafe mechanism needs to be implemented in checkForUpdate, ex. After 3 seconds if there is no response, resolve the promise anyways and let the installed bundle launch.

**Comment by AbdulZaid** [comment]
Issue fixed from our end and our apps are back to normal. However, this needs to be handled properly and also we need clarity on whether this library will be deprecated or not.

**Comment by MichalCiesliczka** [comment]
Looks like it's fixed now

**Comment by ahsanparacha02** [comment]
facing same issue "network request failed", Any update

**Comment by rohitdhall07** [comment]
The certificate has been renewed and everything is working as expected.
