### ISSUE TITLE
Code push can't update new version

### ISSUE THREAD

**Issue by phamtruong010** [microsoft/react-native-code-push#2246]
It not work on android and ios.
![Capture](https://user-images.githubusercontent.com/51196083/162619720-8d95db8a-2ce5-4548-93f3-3c9b20277496.PNG)
![image](https://user-images.githubusercontent.com/51196083/162619747-8074a684-5e50-48cb-883b-e0552b11abb0.png)

**Comment by efeakyuz** [comment]
#2245 same issue

**Comment by ShaunLWM** [comment]
@phamtruong010 offtopic, but what app is that in the first screenshot?

**Comment by phamtruong010** [comment]
> @phamtruong010 offtopic, but what app/library is that in the first screenshot?

I use reactotron.
