### ISSUE TITLE
Error: Deployment "Staging" does not exist.

### ISSUE THREAD

**Issue by feras-merwas** [microsoft/react-native-code-push#2247]
I ran following command

```
appcenter codepush release-react -a email/appname -d Staging
```
then i got following error

```
Error: Deployment "Staging" does not exist.
```

i added these to strings.xml and follow all the instruction so what is the problem

```
  
    <string moduleConfig="true" name="CodePushDeploymentKey">********</string>

```

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.67.2
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? release 
* Does this reproduce on a simulator, or only on a physical device? physical device

**Comment by mujehoxe** [comment]
Did you find a solution?
