### ISSUE TITLE
Getting "Rate limit is exceeded" error all the time.

### ISSUE THREAD

**Issue by rohitdhall07** [microsoft/react-native-code-push#2250]
After #2245 was fixed, we are getting below error very frequently. Our user base has not increased overnight but started receiving "Rate limit exceeded" error suddenly.

From https://docs.microsoft.com/en-us/appcenter/distribution/codepush:
"CodePush API usage has a rate limitation of 70 requests per second applied. Those are counted per combination of the following: Requested endpoint, IP request is coming from, deployment key, and client unique id. If the limit is reached, response with a status code 429 would be returned"

Tested this with Dev deployment key as well, where the number of users has never been more than 5.

Also, even once the checkForCodepush works fine, the sync method fails and downloading never starts.

### Steps to Reproduce
1. Call CodePush.checkForUpdate from react-native-code-push

### Expected Behavior
Promise should resolve and it should return RemotePackage object or null.

### Actual Behavior
What actually happens?
Response received in catch block:
```
{ "statusCode": 429, "message": "Rate limit is exceeded. Try again in 233 seconds." }
```

### Environment

* react-native-code-push version: 6.4.1
* react-native version: 0.67.0
* iOS/Android/Windows version: All versions
* Does this reproduce on a debug build or release build? -- Release build
* Does this reproduce on a simulator, or only on a physical device? -- All devices and simulators

Please help with this, it is causing serious issues in production.

**Comment by VrajSolanki** [comment]
Yes it is always failing with rate limiting even without 70 requests from these parameters : 
`counted per combination of the following: Requested endpoint, IP request is coming from, deployment key, and client unique id. `

**Comment by VrajSolanki** [comment]
@alexandergoncharov-zz can you check this ?

**Comment by AustinZuniga** [comment]
+1

**Comment by ahsanparacha02** [comment]
Facing same issue. Any update ?

**Comment by swathipriyap** [comment]
+1

**Comment by ahsanparacha02** [comment]
@[rohitdhall07](https://github.com/rohitdhall07) "Rate limit is exceeded" issue has been fixed.

**Comment by rohitdhall07** [comment]
Looks fine as of now. Closing the issue.
