### ISSUE TITLE
Not able to override the deployment key using CodePush.sync

### ISSUE THREAD

**Issue by antonyrajr** [microsoft/react-native-code-push#2251]
Hi I am facing an issue while overriding the **deployment key**

I added the code below inside the useEffect

```
CodePush.sync({
        deploymentKey: Config.CODE_PUSH_DEPLOYMENT_KEY,
        installMode: CodePush.InstallMode.IMMEDIATE,
 });
```
 The above code is not overriding the deployment key present in the string.xml and it is always taking the deployment key from the string.xml.

**Version:**
```
"react": "17.0.2"
"react-native": "0.67.4"
"react-native-code-push": "^7.0.4"
```

**Comment by ferasabufares** [comment]
@antonyrajr  did you manag to fix it ???

**Comment by antonyrajr** [comment]
Yes I did 😊

**Comment by ferasabufares** [comment]
@antonyrajr  can you post your solution
