### ISSUE TITLE
ReactNative windows CodePush is not updating latest build.

### ISSUE THREAD

**Issue by VarunTwri** [microsoft/react-native-code-push#2256]
Referenced link:https://microsoft.github.io/react-native-windows/blog/2021/05/17/codepush
We are able to push latest update to appcenter, but as mentioned tried to restart the application is not updating the app.
![image](https://user-images.githubusercontent.com/102298041/163814213-cfd625b3-0983-4879-910f-67d70c0ed54a.png)

![image](https://user-images.githubusercontent.com/102298041/163813897-43e16913-ce40-41a6-a971-4ee0f0f33b25.png)

App.js:
![image](https://user-images.githubusercontent.com/102298041/163814016-b263b72f-f6f1-4c60-ba96-5c7e0b3f9df7.png)

![image](https://user-images.githubusercontent.com/102298041/163814052-4d41e504-f0b1-4078-b1e2-5fd726b1c6ac.png)

![image](https://user-images.githubusercontent.com/102298041/163814132-374ca8ba-f1f2-47af-b94a-0ba92c565282.png)

**Comment by akhilsanker** [comment]
Hi @VarunTwri , 
Did your code get updated in build?

I am facing the same, pushed new code to code push and its not getting updated in build.

Thanks

**Comment by Narenthran-Manokaran** [comment]
Stills this issue not fixed in the windows platform
