### ISSUE TITLE
Rate Limiting [PSA]

### ISSUE THREAD

**Issue by ball-hayden** [microsoft/react-native-code-push#2257]
In the absence of any public announcement from Microsoft, I've been told by AppCenter support that CodePush is (as of 12 April 2022) now enforcing a rate limit of one "request" every 5 minutes (per device ID and deployment key).

Checking for updates more frequently (e.g. a user closing and re-opening your app within 5 minutes) will result in a 429 error response.

Please could someone from the app center team:
- Provide further information about the actual rate-limiting logic being applied (whether it is actually 1 request every 5 minutes, or whether the support agent has misunderstood)
- Update the documentation at https://docs.microsoft.com/en-us/appcenter/distribution/codepush/, which clearly says 70 requests per second

**Comment by gupta-ji6** [comment]
I've also started experiencing the same error recently in both the development & production environment. Has the rate limit really changed & has not been communicated?

**Comment by ball-hayden** [comment]
@gupta-ji6 I'd strongly recommend moving to Expo Updates if you can.

The current form works largely like CodePush, and we've had none of the issues that we had with Microsoft randomly breaking things.

It is a paid service, but you get what you pay for (and it isn't particularly expensive).

**Comment by gupta-ji6** [comment]
thanks for the suggestion, @ball-hayden 

So that you know, our app isn't built with Expo but with RN CLI.
Did you also set up Expo Updates in a bare RN app? If yes, how easy/complex was the setup for it & what cons it has if any from your experience?

**Comment by ball-hayden** [comment]
We have a "bare" React Native app as well, but are starting to slowly adopt more of the Expo ecosystem.

Expo Updates works very well with a bare React Native app.

The setup wasn't massively challenging - I wouldn't say any more difficult than setting up CodePush was initially.

Pros:
* Active maintenance and improvements
* Significantly faster server response times

Cons:
* Paid for (although not massively expensive - our last few bills have been $30/month for ~6000 updated users/month)
* Challenges uploading source maps to Sentry (although I think this may have been fixed in the latest release - we haven't been able to investigate yet)

**Comment by yasirtrimulabs** [comment]
I am facing the same problem did you find any solution?

**Comment by pavlobu** [comment]
@lucen-ms Hi thanks for the update,
Do you happen to know what is a client unique id in such case ? Is client counting here as one specific user device where app runs with codepush, and  one development account doesn't count as one client ?
Thanks!
