### ISSUE TITLE
Codepush doesn't work on iOS in release mode

### ISSUE THREAD

**Issue by samouds** [microsoft/react-native-code-push#2259]
Hello,

i am using 7.0.4 version and it works on android. I have followed all the steps but I have some issue on iOS (tvos) : 
- When I run the app in release mode on Xcode, I see the update dialog and the bundle is updated.
- When I push the app to TestFlight, I get the update dialog too but the bundle isn't update. 

How can I get logs to see what's going on in release mode on TestFlight ?

**Comment by samouds** [comment]
Hello,

I got more details about the error 

```
[javascript] [CodePush] Downloading package.
[javascript] [CodePush] An unknown error occurred.
[javascript] [CodePush] You don’t have permission to save the file “CodePush” in the folder “Application Support”.

```

**Comment by rkaartikeyan** [comment]
In Simulator it's not working, can you try on real device?

**Comment by samouds** [comment]
@rkaartikeyan it's working in the simulator but not on real device.

**Comment by rkaartikeyan** [comment]
seems it's expecting permission for write file on device.

**Comment by yz1311** [comment]
Same to me.Android real device and ios simulator works fine except ios real device.

**Comment by yz1311** [comment]
> Same to me.Android real device and ios simulator works fine except ios real device.

ok, enable ios hermes,work fine now.

**Comment by josephk96** [comment]
> > Same to me.Android real device and ios simulator works fine except ios real device.
> 
> ok, enable ios hermes,work fine now.

Thanks @yz1311 ! Your solution worked. I'm not sure why though, before upgrading to RN 0.68.2 from 0.63.3, it was working properly even without Hermes, but after upgrading my release iOS app stopped downloading CodePush bundles.

https://github.com/microsoft/appcenter-cli/blob/6dad658ce6b97d2e8f5c382914d673983ee81618/src/commands/codepush/release-react.ts#L233 appcenter-cli also seems to be converting js bundles to hermes if hermes is enabled, https://github.com/microsoft/appcenter-cli/blob/6dad658ce6b97d2e8f5c382914d673983ee81618/src/commands/codepush/lib/react-native-utils.ts#L490 so I'm really confused as to why we have to enable hermes on iOS for it to work

**Comment by crewtaylorfd** [comment]
I am trying to run on tvOS and it is not working on a real device with hermes enabled. I get the following logs. 
```
[CodePush] Downloading package.
[CodePush] An unknown error occurred.
[CodePush] You don’t have permission to save the file “CodePush” in the folder “Application Support”.
