### ISSUE TITLE
Execution failed for task ':react-native-code-push:generateDebugRFile'.

### ISSUE THREAD

**Issue by iqbalsafeip** [microsoft/react-native-code-push#2263]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
react-native run-android

### Actual Behavior
Execution failed for task ':react-native-code-push:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-code-push:debugCompileClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by LeeKyungJoon2** [comment]
The same problem occurred to me.
It worked well until last Wednesday
It suddenly doesn't work from today.
What should I do?

**Comment by daonham** [comment]
Same error.
Any solution?

**Comment by huynv3** [comment]
I have the same error. is there any solution for it?

**Comment by hoanglam10499** [comment]
temporary solution

in `android/build.gradle`
![image](https://user-images.githubusercontent.com/37326429/167333661-5c69cbb0-3591-496c-af47-763cf33b06b8.png)

**Comment by LeeKyungJoon2** [comment]
> 

`Could not find com.facebook.fresco:fbcore:2.2.0.`

Changing jcenter() to mavenCentral() results in the following error:
A temporary solution is no use either.

**Comment by thp96** [comment]
Same error. @hoanglam10499 the temporary solution did not work for me :(

**Comment by 0xzight** [comment]
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :app > project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)

**Comment by edohartono** [comment]
Same error. Any solution?

**Comment by edohartono** [comment]
Same error.
The temporary solution give me the following error:

![Screen Shot 2022-05-09 at 11 51 45](https://user-images.githubusercontent.com/43302789/167342800-83ab991a-3e9c-455e-b4f4-6273442a7e04.png)

**Comment by cam-shaw** [comment]
https://status.bintray.com/ Giving a 502 bad gateway 😅 .
Think we might not have a quick fix for this unless you are able to swap to mavenCentral

**Comment by pjc0247** [comment]
seems like `jcenter` is deprecated. (see https://blog.gradle.org/jcenter-shutdown)

just migrate all your 3rd party libraries (by modifying `build.gradle` file inside each modules)

**Comment by edohartono** [comment]
Add mavenCentral inside buildscript repositories and allprojects repositories is working for me.

`android/build.gradle`

![Screen Shot 2022-05-09 at 13 08 15](https://user-images.githubusercontent.com/43302789/167350206-a50724c1-f4d9-4d19-9da1-48089df1ec68.png)

**Comment by cctipgit** [comment]
> Add mavenCentral inside buildscript repositories and allprojects repositories is working for me.
> 
> `android/build.gradle`
> 
> ![Screen Shot 2022-05-09 at 13 08 15](https://user-images.githubusercontent.com/43302789/167350206-a50724c1-f4d9-4d19-9da1-48089df1ec68.png)
thanks

**Comment by LeeKyungJoon2** [comment]
> Add mavenCentral inside buildscript repositories and allprojects repositories is working for me.
> 
> `android/build.gradle`
> 
> ![Screen Shot 2022-05-09 at 13 08 15](https://user-images.githubusercontent.com/43302789/167350206-a50724c1-f4d9-4d19-9da1-48089df1ec68.png)

@edohartono 
You made a very wise choice.
Thank you very much.
I had a headache at the thought of migrating, but I don't have to.

**Comment by Fred0218** [comment]
I have the same error. is there any solution for it?

**Comment by LeeKyungJoon2** [comment]
@Fred0218 
./gradlew clean and cache clear and try again.

**Comment by Fred0218** [comment]
> 
I have clean and tried again, still now work.

Could not determine the dependencies of task ':react-native-code-push:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-code-push:debugCompileClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by LeeKyungJoon2** [comment]
@Fred0218 
I'm sorry.
I don't know any more.

**Comment by 0xzight** [comment]
@edohartono thanks +1

**Comment by nvtai123** [comment]
for me, I have to add mavenCentral to buildscript repositories and maven url "https://plugins.gradle.org/m2/" to allprojects repositories
![image](https://user-images.githubusercontent.com/41268889/167359415-5e9370d4-a6ad-4518-8c98-9328b40c37c0.png)

![image](https://user-images.githubusercontent.com/41268889/167359213-6332f06a-8363-4b2a-acc4-343b2c5bbd0f.png)

**Comment by hrupesh** [comment]
We solved this by adding maven central to our project repository and for all the dependencies in our project

In the project's `build.gradle`
 * Add maven to project repositories 
    
![Screenshot 2022-05-09 at 13 48 46](https://user-images.githubusercontent.com/30570616/167370473-ef0ac2a9-9e56-4210-9cd5-1fd1d8ee5524.png)


* Add maven to `allprojects` repositories and exclude react native as older versions can be present there.
 
![Screenshot 2022-05-09 at 13 49 31](https://user-images.githubusercontent.com/30570616/167370497-3b693a4b-3b4e-4490-b023-a2c74b252102.png)

Hope it helps someone, Thanks!

**Comment by LeonArantes** [comment]
> for me, I have to add mavenCentral to buildscript repositories and maven url "https://plugins.gradle.org/m2/" to allprojects repositories ![image](https://user-images.githubusercontent.com/41268889/167359415-5e9370d4-a6ad-4518-8c98-9328b40c37c0.png)
> 
> ![image](https://user-images.githubusercontent.com/41268889/167359213-6332f06a-8363-4b2a-acc4-343b2c5bbd0f.png)

thanks +1

**Comment by angel-urena** [comment]
I followed some of the suggestions here and while they helped to get the build to complete I eventually ran into app crashes when the app attempted to apply updates published through CodePush. After some additional search I stumbled upon a suggestion to downgrade `com.google.gms:google-services` from `4.2.0` to `4.1.0`. That created a different problem and eventually I decided to upgrade it to `4.3.10` since I saw that version in other documentation and now everything works 👍🏻 I hope this helps someone.

<img width="614" alt="CleanShot 2022-05-11 at 21 28 44@2x" src="https://user-images.githubusercontent.com/17153928/167974364-38d6e2ff-f1a7-4c36-9c8a-48d63078e54e.png">

**Comment by MrGautamojha** [comment]
<img width="480" alt="Screenshot 2022-05-15 at 6 18 02 PM" src="https://user-images.githubusercontent.com/47115026/168473685-cf649a4d-9e9f-427
<img width="496" alt="Screenshot 2022-05-15 at 6 18 15 PM" src="https://user-images.githubusercontent.com/47115026/168473698-f2219369-b7e5-483d-8315-4f22a7b5725d.png">
3-84ea-6086baa8ba99.png">
<img width="552" alt="Screenshot 2022-05-15 at 6 19 52 PM" src="https://user-images.githubusercontent.com/47115026/168473764-6f72f528-b277-4439-b5ed-bfba40c9286e.png">



<img width="579" alt="Screenshot 2022-05-15 at 6 20 05 PM" src="https://user-images.githubusercontent.com/47115026/168473777-ba618d8f-4210-437e-95cd-170ccf9845e6.png">

I tried with multiple solution mentioned above but .
getting error 👎 
 startup failed:
  General error during semantic analysis: Unsupported class file major version 62
  
  java.lang.IllegalArgumentException: Unsupported class file major version 62
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:8
