### ISSUE TITLE
project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1

### ISSUE THREAD

**Issue by sam9010** [microsoft/react-native-code-push#2264]
"react-native-code-push": "^7.0.4",
    "react": "16.9.0",
    "react-native": "0.61.5",

classpath 'com.android.tools.build:gradle:3.5.1'
classpath 'com.google.gms:google-services:4.3.2'

but did not build
this error

rror: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-code-push:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-code-push:debugCompileClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)

I test with -> classpath 'com.google.gms:google-services:4.2.0'  and
classpath 'com.google.gms:google-services:4.1.0'  but not fix

plz help me... my app was ok 2 days ago, but now no

**Comment by LeeKyungJoon2** [comment]
It's the same issue as that one.
[https://github.com/microsoft/react-native-code-push/issues/2263](https://github.com/microsoft/react-native-code-push/issues/2263)

**Comment by mohity777** [comment]
I am also facing it.

**Comment by hupptechnologies** [comment]
Also facing same issue

> Could not resolve net.minidev:json-smart:[1.3.1,2.3].
>      Required by:
>          project :app > project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1
>       > Failed to list versions for net.minidev:json-smart.
>          > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
>             > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
>                > org.apache.http.client.ClientProtocolException (no error message)

**Comment by pallavAtRelevel** [comment]
+1

**Comment by sizhe-eb** [comment]
My app also works two days ago then face the issue today

**Comment by LeeKyungJoon2** [comment]
[https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120681062](https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120681062)

It works when both are applied simultaneously.
I think this is the best way at the moment.

**Comment by LeeKyungJoon2** [comment]
[https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120668969](https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120668969)

It is a problem caused by the shutdown of jcenter.
Eventually, it needs to be migrated later.

**Comment by hupptechnologies** [comment]
https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120687289

This one worked for me

**Comment by sam9010** [comment]
android/build.gradle
![167350206-a50724c1-f4d9-4d19-9da1-48089df1ec68](https://user-images.githubusercontent.com/41944885/167352502-144cb1aa-14d9-46ba-ad30-b792a72ec593.png)

**Comment by sizhe-eb** [comment]
> [#2263 (comment)](https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120668969)
> 
> It is a problem caused by the shutdown of jcenter. Eventually, it needs to be migrated later.

Does that mean the `mavenCentral()` just a temporary solution, we still need to remove it after the migration?

**Comment by lnk1729** [comment]
> > [#2263 (comment)](https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120668969)
> > It is a problem caused by the shutdown of jcenter. Eventually, it needs to be migrated later.
> 
> Does that mean the `mavenCentral()` just a temporary solution, we still need to remove it after the migration?

It is. 
For now, we're at the mercy of the jcenter folks to get their server up running, since they've promised readonly access to all artifacts hosted.
