### ISSUE TITLE
react-native-code-push >> net.minidev:json-smart maven meta data issues

### ISSUE THREAD

**Issue by evolvingkid** [microsoft/react-native-code-push#2265]
create a new project and then run two command
"yarn add react-native-code-push"
"react-native link react-native-code-push"

and then i run in android with "react-native run-android"

after that i run the program, i get the following error.

Error:A problem occurred configuring project ':app'.

    Could not resolve all dependencies for configuration ':app:_debugApk'.
    A problem occurred configuring project ':react-native-code-push'.
    > Could not resolve all dependencies for configuration ':react-native-code-push:_debugPublishCopy'.
    > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
    Required by:
    testCodePush:react-native-code-push:unspecified > com.nimbusds:nimbus-jose-jwt:5.1
    > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
    > Failed to list versions for net.minidev:json-smart.
    > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
    > Could not GET 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
    > jcenter.bintray.com

Anyone have solution for solving these error??

This is the same issues as #1279

**Comment by Harikarthyk** [comment]
I encountered the same error while building my APK. 

Any solution to solve this

**Comment by harisshk** [comment]
I too have the same issue

**Comment by gurbela** [comment]
https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120681062

**Comment by Harikarthyk** [comment]
That works 

@gurbela  thank you

**Comment by harisshk** [comment]
This works, thank you for your work @gurbela

**Comment by raushanji** [comment]
I was also getting this issue

I used this, it's working fine

```
repositories {
        mavenLocal()
        mavenCentral()   <- Add this
        google()
        jcenter()
    }
```

**Comment by evolvingkid** [comment]
using mavenCenteral fix the error but i'm not closing the issues since this is just a work around.

**Comment by Fernando922** [comment]
> mavenCentral()

i love you man

**Comment by samuel-io** [comment]
> Eu também estava recebendo esse problema
> 
> Eu usei isso, está funcionando bem
> 
> ```
> repositories {
>         mavenLocal()
>         mavenCentral()   <- Add this
>         google()
>         jcenter()
>     }
> ```

For now this solved it for me

**Comment by cdunkel** [comment]
Just as a note, you have to add `mavenCentral()` to both the `allprojects` and `buildscript` repository sections.

**Comment by risardi123** [comment]
> mavenLocal()
>         mavenCentral()

Thanks it work (android/build.gradle)
<img width="169" alt="image" src="https://user-images.githubusercontent.com/29408156/167575505-6474458d-c764-45df-af69-c2e6ab39f9ac.png">
and
<img width="184" alt="image" src="https://user-images.githubusercontent.com/29408156/167575582-e8655521-7b23-46c1-a05b-b82571ff205a.png">
