### ISSUE TITLE
Could not determine the dependencies of task ':app:mergeDebugAssets'. > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.

### ISSUE THREAD

**Issue by MrGautamojha** [microsoft/react-native-code-push#2267]
* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :app > project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               > org.apache.http.client.ClientProtocolException (no error message)

### Environment

* react-native-code-push version:7.0.4
**        classpath 'com.google.gms:google-services:4.3.4'**

(The more info the faster we will be able to address it!)

**Comment by aajahid** [comment]
Duplicate #2263 

Solution - https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120588185
