### ISSUE TITLE
Task :react-native-code-push:generateReleaseRFile FAILED

### ISSUE THREAD

**Issue by Yandamuri** [microsoft/react-native-code-push#2270]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.Try building .aab by running ./gradlew bundleRelease
2. Then you will encounter with mentioned error

### Expected Behavior
app bundle should be created with out any errors

### Actual Behavior

      Execution failed for task ':react-native-code-push:generateReleaseRFile'.
     Could not resolve all files for configuration ':react-native-code-push:releaseCompileClasspath'.
     Could not resolve net.minidev:json-smart:[1.3.1,2.3].
     Required by:
         project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1
         Failed to list versions for net.minidev:json-smart.
         Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
             Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'.
               org.apache.http.client.ClientProtocolException (no error message)

### Reproducible Demo

Unable to share the reproducible demo as my project is huge.

### Environment

* react-native-code-push version: "6.3.0",
* react-native version: "0.63.2",
* iOS/Android/Windows version: Android 9
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? con't answer. because I was trying to create app bundle

**Comment by aajahid** [comment]
Duplicate.

temp solution - https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120800868

**Comment by Yandamuri** [comment]
> Duplicate.
> 
> temp solution - [#2263 (comment)](https://github.com/microsoft/react-native-code-push/issues/2263#issuecomment-1120800868)

@aajahid This solution worked for me. Thank you.May I know the root cause of the issue?

**Comment by PankajChandel1997** [comment]
Task :react-native-push-notification:generateReleaseRFile FAILED

i have face this issue but above solution not work for me.

**Comment by MikhailSuendukov** [comment]
Hello @PankajChandel1997, and thank you for reaching out! Could you please share additional details about your project and environment? Specifically:

- react-native-code-push version
- react-native version
- Operating system version (iOS/Android/Windows)
- Build type: Does this issue occur in debug or release builds?
- Device type: Does this issue reproduce on a simulator or only on a physical device?

Additionally, it would be extremely helpful if you could provide app logs and, if feasible, a small demo app that reproduces the issue. Thank you!
