### ISSUE TITLE
Request specific version of a bundle to be downloaded

### ISSUE THREAD

**Issue by flaviostutz** [microsoft/react-native-code-push#2271]
We use a feature flag mechanism for enabling features in our App. Sometimes we would like to target just a few users to a specific bundle version for a more controlled rollout by using the same feature flag mechanism also.

For this to be possible, we would like to send something like this in code push options:
  - bundleVersion: "v18"

Would this be possible?

* This is similar to #1361

**Comment by Spencer-Yoder** [comment]
Bump, this would be much cleaner then making a bunch of deployments and then switching between them

**Comment by savv** [comment]
This would be an incredibly cool feature to have - we would like to have a version selector in our app that would allow our internal users to test their git branches, by selecting that version, after it has been code pushed by our CI.

This would make debugging and testing much easier for us.
