### ISSUE TITLE
codePush.sync with installMode IMMEDIATE is not updating.

### ISSUE THREAD

**Issue by fragilehm** [microsoft/react-native-code-push#2272]
My App component is wrapped into:
```
codePush({
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
})(App);
```
And this part is working as expected Downloading and Installing the available update on the app resume. 
But in our application, there is also a button to manually check for the available update.

Say the app is active and in v1 and there is v2 available  after the app goes to background mode and comes back active the v2 update is downloaded and installed:
![image](https://user-images.githubusercontent.com/20160573/169835881-2d21b465-996b-4c20-819a-3aa9c39c581d.png)

but not yet updated to v2, so when checking for an update manually, there is PENDING update available so the following code is executed to apply the installed update:
```
codePush.sync({
        updateDialog: undefined,
        installMode: codePush.InstallMode.IMMEDIATE,
})
```
Which just gives back status 1 (UPDATE_INSTALLED) but does not actually restart the app and apply the installed update even with `codePush.InstallMode.IMMEDIATE`

### Expected Behavior

the app should be restarted and apply the installed update.

### Actual Behavior

the app is not restarting to apply the installed update.

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.67.4
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

(The more info the faster we will be able to address it!)

**Comment by tkyr-mse** [comment]
Having the same issue

**Comment by samstoppani-tred** [comment]
also having the same problem

**Comment by abadrangui** [comment]
Still having the problem
