### ISSUE TITLE
Node_Modules Changes

### ISSUE THREAD

**Issue by sonivaibhav27** [microsoft/react-native-code-push#2276]
I have made changes to third party node_modules library JS file. Can i codepush the changes or do i need to upload new .aab to play store?

**Comment by swizes** [comment]
If it has native module in it, you need to upload a new version to store, if not the codepush should also send the updated package. You can try it, if you have a dev environment. Or just create an upper version to test it and disable the codepush update if it didnt work

**Comment by sonivaibhav27** [comment]
I have uploaded the changes through codepush , and it was in JS File . It was reflected without any errors.

**Comment by bang88** [comment]
Use `patch-package` instead.
