### ISSUE TITLE
Update did not finish loading the last time, rolling back to a previous version

### ISSUE THREAD

**Issue by atifaziz1** [microsoft/react-native-code-push#2286]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
Updates should be install

### Actual Behavior
Rollback to previous version
`Update did not finish loading the last time, rolling back to a previous version`

### Environment

* react-native-code-push version: ^6.4.1
* react-native version: 0.64.2
* iOS/Android/Windows version: Android O
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? Physical device

(The more info the faster we will be able to address it!)

**Comment by cmdparkour** [comment]
meet the same question, but don't know how to fix it
