### ISSUE TITLE
react-native 0.68 the later version

### ISSUE THREAD

**Issue by ShaoGongBra** [microsoft/react-native-code-push#2287]
react-native 0.68, the later version, has opened a new architecture, the packaged code is binary, and after the download of the hot update code is completed, it crashes directly. Does anyone successfully run codepush in the new architecture of 0.68?

**Comment by majugurci** [comment]
Also now that RN 0.69 is out it is released with react 18. Is there any estimation when this would be supported?

**Comment by joaodematejr** [comment]
Same problem here

**Comment by rarenatoe** [comment]
Help

**Comment by linxianxi** [comment]
can used in 0.68?

**Comment by Fagner3g** [comment]
problem persists in 0.69.1 :/

**Comment by jzxchiang1** [comment]
Is this project still maintained?

**Comment by hegnn** [comment]
I didn't have this problem with 0.68.2 version but it appeared with 0.69 version

**Comment by octobus55** [comment]
Is there any update plan for this issue? Is it still maintained?

**Comment by afrakhan123** [comment]
+1

**Comment by ShaoGongBra** [comment]
still not resolved

**Comment by ShaoGongBra** [comment]
still not resolved

**Comment by octobus55** [comment]
Currently, our project uses react-native: 0.68.3, and codepush works

**Comment by ShaoGongBra** [comment]
Is the packed code binary？

**Comment by RP-alissonpaschoal** [comment]
I was able to use CodePush with react native 0.70 and the new architecture enabled (Fabric components and turbo modules)
