### ISSUE TITLE
IOS code push fails

### ISSUE THREAD

**Issue by LucasWili** [microsoft/react-native-code-push#2294]
When trying code push for IOS its gets fails.
`[Error: ENOENT: no such file or directory, copyfile '/var/folders/vd/5cvyc22x38bbwh2ztkdkc_pc0000gn/T/code-push2022527-34436-1ilax9q.iuz/CodePush/main.jsbundle.hbc' -> '/var/folders/vd/5cvyc22x38bbwh2ztkdkc_pc0000gn/T/code-push2022527-34436-1ilax9q.iuz/CodePush/main.jsbundle'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: '/var/folders/vd/5cvyc22x38bbwh2ztkdkc_pc0000gn/T/code-push2022527-34436-1ilax9q.iuz/CodePush/main.jsbundle.hbc',
  dest: '/var/folders/vd/5cvyc22x38bbwh2ztkdkc_pc0000gn/T/code-push2022527-34436-1ilax9q.iuz/CodePush/main.jsbundle'
}`

`[Error: ENOENT: no such file or directory, unlink '/var/folders/vd/5cvyc22x38bbwh2ztkdkc_pc0000gn/T/code-push2022527-34436-1ilax9q.iuz/CodePush/main.jsbundle.hbc'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/var/folders/vd/5cvyc22x38bbwh2ztkdkc_pc0000gn/T/code-push2022527-34436-1ilax9q.iuz/CodePush/main.jsbundle.hbc'
}`

**Comment by raccoon-classum** [comment]
@LucasWili Did you solve this?
