### ISSUE TITLE
[Feature Request] Possibility to cancel download in case codepush server is slow to download

### ISSUE THREAD

**Issue by zxccvvv** [microsoft/react-native-code-push#2299]
Hi Code Push Team,

currently we had a lot of bad review of our apps in store that user complaining about loading forever when downloading bundle update 

I've tried to find any similar issue like:
https://github.com/microsoft/react-native-code-push/issues/2206
https://github.com/microsoft/react-native-code-push/issues/1942

but none of them provide a solution about slow download

so i think it would be good if there is some feature like `cancel download` in case codepush server is busy or response time is high

of course IMO canceling download is better than rollback in case download progress is interrupted (user kill apps or no connection).

last time i've an idea to check ping of hosting where bundle stored before let user download it, but i don't see any react native package to handle this

**Comment by zeusstl** [comment]
I understand that this is a feature request and those are still on hold, but this feature request is actually resolving a bug that is constantly cropping up in the react-native-code-push github issues. The issue of the slowness is a really serious issue for anyone trying to use codepush in a real app. This feature is more a solution to a bug than an actual feature request. If the team would resolve this slowness, codepush would be used on a lot more apps.
