### ISSUE TITLE
syncPromise...done(...) is not a function

### ISSUE THREAD

**Issue by mudetroit** [Microsoft/react-native-code-push#230]
I started getting this error when I began integrating codepush into my project It seems to be related to:
https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L222

I am not sure what the `done()` call is doing here. As far as I am aware it is not part of the Promises/A+ spec, and it is empty anyhow. Just wondering if I am missing something.

**Comment by dtivel** [comment]
#229 fixes this.

**Comment by lostintangent** [comment]
@mudetroit We had this issue reported over the weekend and we're about to merge in the fix. As you mentioned, we didn't need the `done` call at all, so it's a simple fix to ensure compatibility with any spec-compliant `Promise` implementation.

**Comment by lostintangent** [comment]
We just merged in this fix and will publish it to NPM this afternoon. Thanks for reporting it!
