### ISSUE TITLE
[IOS] AppCenterReactNative.h not found 

### ISSUE THREAD

**Issue by ahmadzraiq** [microsoft/react-native-code-push#2306]
After adding 
`#import <AppCenterReactNative.h>
#import <AppCenterReactNativeAnalytics.h>
#import <AppCenterReactNativeCrashes.h>` in AppDelegate.mm

I got an error  **<AppCenterReactNative.h> not found** 

Steps to reproduce: 
1- create new app 
2-  install `    
    "react-native-code-push": "^7.0.4",
     "appcenter": "4.4.4",
    "appcenter-analytics": "4.4.4",
    "appcenter-crashes": "4.4.4",`

3- add `#import <AppCenterReactNative.h>
#import <AppCenterReactNativeAnalytics.h>
#import <AppCenterReactNativeCrashes.h>` in AppDelegate.mm

4- pod install
5- npm run ios

**Comment by lucasftcruz** [comment]
@ahmadzraiq I'm updating react-native to 0.70.3 and encountered the same issue, how did you fix it?

**Comment by feedthedevil** [comment]
The same issue
