### ISSUE TITLE
[IOS][Android] App crashes each time with new codepush update (react native 0.69.2)

### ISSUE THREAD

**Issue by ahmadzraiq** [microsoft/react-native-code-push#2307]
App crashes each time with new release after upgraded react native from 0.68.2 to 0.69.2 in release mode (testflight, firebase distribution) 

**Error**:
`
Fatal Exception: com.facebook.jni.CppException: Compiling JS failed: Wrong bytecode version. Expected 85 but got 84 Buffer size 9790868 starts with: c61fbc03c103191f5400000090bf9853 and has protection mode(s): r--p
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:201)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:764)
`

### Steps to Reproduce
Do a codepush on release build with react native 0.69.2

### Expected Behavior
 Update the app without crash

### Actual Behavior
```
App crashes after downloading the release
```

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.69.2
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? physical device

**Comment by geekyoperand** [comment]
Will code push work fine for react native version 0.68.1 ?

**Comment by geekyoperand** [comment]
Hi @ahmadzraiq, Does code push supports react native version 0.68.1. Because as per the documentation only these versions are mentioned

![image](https://user-images.githubusercontent.com/52500177/181120977-a8642b3a-0ebb-4954-afc1-af75a2df5934.png)

**Comment by ahmadzraiq** [comment]
@geekyoperand Hello, code push is working with me react native 0.68.2

**Comment by edritech93** [comment]
same issue for me, I use reacct-native 0.69.5

**Comment by ahmadzraiq** [comment]
@edritech93 you need to upgrade appcenter-cli to latest version

**Comment by chellongCoder** [comment]
> @edritech93 you need to upgrade appcenter-cli to the latest version

I have still got this error :( it's crashed when update 100% pakage
