### ISSUE TITLE
CodePush does not work if CODE_PUSH_APK_BUILD_TIME is inside a DFM

### ISSUE THREAD

**Issue by saihemanth121** [microsoft/react-native-code-push#2308]
Platform: Android

I have an Android Project where react-native components are part of a Dynamic Feature Module (DFM). CodePush works if CODE_PUSH_APK_BUILD_TIME is added as resValue to defaultConfig in base module. But it affects incremental builds and build caching since it changes every build, so I tried moving it to the DFM where all other react-native components are along with codepush dependency. This breaks codepush as CodePush.java is using base package name (instead of DFM package name) to get the resource identifier for CODE_PUSH_APK_BUILD_TIME.

Is there any other way to keep CODE_PUSH_APK_BUILD_TIME out of base module?

**Comment by geekyoperand** [comment]
Hi @saihemanth121, Does code push supports react native version 0.68.1. Because as per the documentation only these versions are mentioned

![image](https://user-images.githubusercontent.com/52500177/181120977-a8642b3a-0ebb-4954-afc1-af75a2df5934.png)
