### ISSUE TITLE
Codepush not working for RN version 0.69.2

### ISSUE THREAD

**Issue by afrakhan123** [microsoft/react-native-code-push#2314]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by krunalbad** [comment]
Yes same for me. I was about to open this issue 2 weeks ago lol. @afrakhan123 

Can you try adding this in `defaultConfig`?
`resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())`

Didn't work for me but you can try this to see if it's working for you or not

**Comment by eshantbist** [comment]
@afrakhan123 

Have you found any fix for this?
I am also facing same issue after I upgraded to 0.69.3

@krunalbad I tried you solution but it didn't work.

**Comment by bachngocnhat** [comment]
> Yes same for me. I was about to open this issue 2 weeks ago lol. @afrakhan123
> 
> Can you try adding this in `defaultConfig`? `resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())`
> 
> Didn't work for me but you can try this to see if it's working for you or not

it worked for me

**Comment by chamaldesilva** [comment]
> Yes same for me. I was about to open this issue 2 weeks ago lol. @afrakhan123
> 
> Can you try adding this in `defaultConfig`? `resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())`
> 
> Didn't work for me but you can try this to see if it's working for you or not

works for me! thanks @eshantbist
