### ISSUE TITLE
Installation guide for Android is outdated

### ISSUE THREAD

**Issue by andrefangeloni** [microsoft/react-native-code-push#2325]
On step 3, the orientation is update the method `getJSBundleFile()` on `MainApplication.java`:

```java
public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        ...

        // Override the getJSBundleFile method in order to let
        // the CodePush runtime determine where to get the JS
        // bundle location from on each app start
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
    };
}
```

But on version 0.69 there is no `getJSBundleFile()`, it was replaced by `getJSMainModuleName()`

```java
@Override
protected String getJSMainModuleName() {
   return "index";
}
```

How can I proceed with the configuration?
Thanks in advance

### Environment

* react-native-code-push version: 7.0.5
* react-native version: 0.69.1

**Comment by pnthach95** [comment]
I add that `getJSBundleFile` function and it works

**Comment by andrefangeloni** [comment]
> I add that `getJSBundleFile` function and it works

Thanks @pnthach95, now it's working!
