### ISSUE TITLE
"ANDROID_ID " not compliant with Huawei App market Policies

### ISSUE THREAD

**Issue by zhuminjunivan** [microsoft/react-native-code-push#2327]
I found that there is a way to get ANDROID_ID in the CodePushNativeModule method, CodePushNativeModule will be called when it is initialized. It is against the user's privacy policy to obtain ANDROID_ID without the user's consent when the app is opened.
![image](https://user-images.githubusercontent.com/16554031/187586921-165d3139-a78a-4a8d-8a25-d44b255de8e5.png)
(https://github.com/microsoft/react-native-code-push/blob/88ee6d14e96ca4890f86c1791bd8866d3a7f1478/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L63)

And mClientUniqueId is only used in the getConfiguration method, so I recommend getting ANDROID_ID when using it.
![image](https://user-images.githubusercontent.com/16554031/187587203-b78f6947-3173-4299-9e88-e87127d71e2a.png)
https://github.com/microsoft/react-native-code-push/blob/88ee6d14e96ca4890f86c1791bd8866d3a7f1478/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L359

**Comment by antoinedelp** [comment]
Hi, we had the same problem. We circumvented it by modifying the code in the package, and passing an hard-coded string instead of the mClientUniqueId. We then fixed the package with react-native-fix-package. This does not fix the issue but will help you pass the validation process.

**Comment by KURTGODEL** [comment]
This issue should still be open. I just got a message from Google stating the following:

"
Issue found: Invalid Data safety form
...
•	SPLIT_BUNDLE [VERSION_CODE]: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address)
"

We need someone to review it and update the README.
