### ISSUE TITLE
Deep links are ignored when CodePush update is mandatory

### ISSUE THREAD

**Issue by SMJ93** [microsoft/react-native-code-push#2328]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Deploy a mandatory CodePush release
2. Open the app via a deep link or universal link
3. App will initially open deep link screen
4. Once mandatory CodePush has downloaded
5. App will restart and load home screen (initial app screen)

### Expected Behavior
What you expected to happen?

After the restart I would expect it to load the deep link screen again

### Actual Behavior
What actually happens?

It loads the home screen (initial app screen)

### Reproducible Demo

Any CodePush project with deep links will have this issue

### Environment

* react-native-code-push version: **7.0.5**
* react-native version: **0.69.3**
* iOS/Android/Windows version: **iOS and Android**
* Does this reproduce on a debug build or release build? **Release**
* Does this reproduce on a simulator, or only on a physical device? **Both**

(The more info the faster we will be able to address it!)

**Comment by SMJ93** [comment]
@ricardobeat will give that a go. Do you know of any examples?

**Comment by doddannad** [comment]
same issue here looking from long time any update on it

**Comment by wavesandwaves** [comment]
The issue I am having is that the bundle sometimes reloads before the deep link is successfully put into state.
