### ISSUE TITLE
Question : google in app update and code push  

### ISSUE THREAD

**Issue by yakir1986** [microsoft/react-native-code-push#2330]
It's not a issue, but I have a question:

I implemented a mechanism for automatic updates through Google (In-app updates)
like this : https://developer.android.com/guide/playcore/in-app-updates.

**Every time the application starts, the function check if there is a binary update (not code push / js files) for the application via google play.**
And if yes it will popup a message and ask the user if he wants to download the app update.

**Now I also have a function that checks if there are updates through Code Push, and install them ON_NEXT_RESUME
like this :** 

checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME,
installMode: CodePush.InstallMode.ON_NEXT_RESUME,

So my question is this: 

What happens if **Code Push** downloaded an update and is waiting for the next restart / next resume of the application, and at the same time **In-app updates (through Google)** just download and update and then restart the app.

Will this cause some issue to the app on start? because after all,  **Code Push** waiting for the next restart in order to install the update.

I would appreciate it if someone could clarify this.
Thanks

**Comment by ginccc** [comment]
+1
