### ISSUE TITLE
VM2 security vulnurability issue [ https://security.snyk.io/package/npm/vm2](url)

### ISSUE THREAD

**Issue by uday5162** [microsoft/react-native-code-push#2338]

**Comment by cam-shaw** [comment]
@uday5162 as a temporary solution, you can add a package resolution if you use yarn.
 From looking at the changes, they don't see too major from from version 3.9.8 (or 3.9.9) to 3.9.11

```
"resolutions": {
    "vm2": "^3.9.11"
  },
```
