### ISSUE TITLE
Paid service or possibility to open source codepush server - Download SLOW

### ISSUE THREAD

**Issue by witalobenicio** [microsoft/react-native-code-push#2339]
It's been a while since CodePush bundle download is extremely slow.
Trying to download a 18Mb bundle, takes more than 5 minutes in 500Mbps connection.

It's possible to have paid service with improved conditions?
Or maybe open sourcing the server code so we can push our own server with better configs.

### Steps to Reproduce
1. Try to download

### Expected Behavior
Download bundle in an acceptable time

### Actual Behavior
It's extremely slow

### Reproducible Demo

* Just try with any project (at least here in Brazil)

### Environment

* react-native-code-push version: 7.0.5
* react-native version: 0.66.1
* iOS/Android/Windows version: ios 15.6.1
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by shawarmaz** [comment]
+1 prohibitively slow on my end as well, 4.5MB taking 6 minutes, every time, for the past 48 hours
