### ISSUE TITLE
Building project fail with codepush.gradle

### ISSUE THREAD

**Issue by avishayil** [Microsoft/react-native-code-push#234]
React Native build fail immediately after adding the codepush.gradle line to app/build.gradle.

Stack trace:
````
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:app:bundleDebugJsAndAssets
+--- :app:mergeDebugResources
|    \--- :app:generateDebugResources
|         \--- :app:fabricGenerateResourcesDebug
|              \--- :app:processDebugManifest
|                   \--- :app:generateBundledResourcesHashDebug
|                        \--- :app:bundleDebugJsAndAssets (*)
\--- :app:recordFilesBeforeBundleCommandDebug
     \--- :app:mergeDebugResources (*)

(*) - details omitted (listed previously)
````

**Comment by geof90** [comment]
Hi @avishayil, could you remove [this line](https://github.com/Microsoft/react-native-code-push/blob/master/android/codepush.gradle#L62) from the codepush.gradle file and verify that the build succeeds?

**Comment by avishayil** [comment]
Yeah, it does.
I have a problem now with the CI of CodePush, any chance for a hotfix?

**Comment by geof90** [comment]
@avishayil great! We have already merged this fix: https://github.com/Microsoft/react-native-code-push/pull/235

We will be uploading the latest bits to NPM soon, but for now if you want CI to work, you could specify `github:Microsoft/react-native-code-push` as your dependency in package.json to depend directly on the code on the master branch. We will let you know the moment we publish. 

I'll close this issue for now! Feel free to open it again if you run into more problems.
