### ISSUE TITLE
App up to date after update, rollout 100%, 0/0 Active Installs

### ISSUE THREAD

**Issue by Dev-Tester-Test** [microsoft/react-native-code-push#2342]
### Steps to Reproduce
1. Create code changes
2. Push Codepush update (from instructions on appcenter)
3. App does not update

### Expected Behavior / Description

On Android, I have set up Codepush following the Appcenter guide. When the app foregrounds I can see in the logs that Codepush is saying the app is up to date. After pushing out an update, I can see that update on Appcenter's Codepush section but it says 100% rollout, 0/0 Active installs. I am running the app on a staging buildType (note - adding the key string under buildType caused the app to not compile so I have it in strings.xml under the staging res/values folder... same issue as here https://github.com/microsoft/react-native-code-push/issues/1686). The way I test it is I compile the app onto a physical device that is plugged into my computer, then I unplug it so it doesn't hot-reload with the changes (I just change some text on the login page). Then I run the update command, but the app doe not seem to get it. Any help would be appreciated, thank you.

### Environment

* react-native-code-push version: 7.0.5
* react-native version: 70.1
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? Staging build (using release creds)
* Does this reproduce on a simulator, or only on a physical device? (physical device)

**Comment by ramadhanoo** [comment]
the same problem in RN 70.1

**Comment by YousufMansoor** [comment]
same issue

**Comment by ngocdv-namitrade** [comment]
same issue on iOS production

**Comment by KimJeonghun91** [comment]
same issue

**Comment by kvngcheerio** [comment]
same issue

**Comment by vinodsonu** [comment]
Same issue
