### ISSUE TITLE
iOS app doesn't update in all the devices.

### ISSUE THREAD

**Issue by mariogarciat** [microsoft/react-native-code-push#2346]
Our iOS app is not updating with codepush in all the devices. After completing the release, not all the devices with the previous version get the new one uploaded to the code push server. This happens in all our environments, prod and nonprod. The described unexpected behavior occurs only with iOS devices, Android works correctly.

### Steps to Reproduce
1. Release a new version (with JS changes) to the code push server.
2. Follow the steps we set in the code push decorator config to get the changes (`checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME` and `installMode: CodePush.InstallMode.ON_NEXT_SUSPEND`).
3. From 10 devices, 4 to 6 don't download the new version.

### Expected Behavior
All devices with previous version should install the new one released to the code push server.

### Actual Behavior
Almost 50% of devices don't get the new version by following the configuration steps, we need to do other steps and even so, some of them never get the update.
Tests were run in different devices: iPhone X, Xr, 11, 12, 13 as well as with different iOS versions. Every time we changed the environment, the results changed. For example, if a specific device failed to update in Staging, it updated successfully in Prod.
We even changed the `mandatory` flag to `true` but the results were the same. Working devices get the update immediately, but not working ones still don't get the update
We ran out of ideas about what the root cause of this behavior could be.

### Environment

* react-native-code-push version: 5.7.0
* react-native version: 0.61.5
* iOS: 14.4, 15.3.1, 15.4.4, 16.0
* Does this reproduce on a debug build or release build?
This reproduce on both release and debug builds
* Does this reproduce on a simulator, or only on a physical device?
*Physical devices, we don't use code push with simulators.

**Comment by bonnmh** [comment]
the same problem

**Comment by hoanglam10499** [comment]
same problem :(

**Comment by felipegmg** [comment]
Do you use any bridge libraries? I ran into this problem due to the webengage bridge. It overrides the default code 
`return [CodePush bundleURL]`
and does not update the code via codepush

**Comment by knro** [comment]
Same issue here! Any updates on a workaround? Does the appcenter-cli issue above fixes the issue?

**Comment by bentburton** [comment]
Experiencing same issue. Please help

**Comment by renopp** [comment]
same problem, it's happened on android & iOS

**Comment by knro** [comment]
This should be treated as a show-stopper. Any workarounds?

**Comment by SravanthiGujjula** [comment]
Facing same issue. Codepush updating only few iOS devices. Android is working fine. Please help.

**Comment by knro** [comment]
RIght, just confirmed this here again as well with latest releases of all components. Codepush works fine on iPad (iOS v16.3), but apparently loads and then immediately rolls back on iPhone (iOS v16.1)

**Comment by SravanthiGujjula** [comment]
Facing same issue. Codepush updating only few iOS devices. Please help

**Comment by thespacemanatee** [comment]
Same issue with our production application

**Comment by vxm5091** [comment]
Having the same issue and what's worked for me is pushing out another incremental release, however small, just to pass the diff check. 

I'm new to Codepush so I've only had to do it a handful of times but so far that's worked.

**Comment by carloslibardo** [comment]
I'm facing the same issue

**Comment by Yangeok** [comment]
Anyone solved this problem?

**Comment by knro** [comment]
No unfortunately, it's still there. Giving that Microsoft is going to abandon code push, I don't see anywhere this would be resolved anytime soon.

**Comment by IlyaBausovAkvelon** [comment]
@Yangeok @knro and everybody else who is experiencing this,
Could you please share device logs with us so we can check the codepush logs?
