### ISSUE TITLE
CodePush 400: {"status":400,"name":"Error","message":"Missing required query parameter \"deployment_key\""}

### ISSUE THREAD

**Issue by emclab** [microsoft/react-native-code-push#2352]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. start IOS emulator
2. In terminal, `npx react-native run-ios`
3.

### Expected Behavior
No CodePush error

### Actual Behavior
What actually happens?
```
   LOG  [CodePush] An unknown error occurred.
  LOG  [CodePush] 400: {"status":400,"name":"Error","message":"Missing required query parameter \"deployment_key\""}
```

Then I create a new app in MS appcenter for IOS and replaced the app secret with the new one just created in AppCenter-Config.plist in Xcode 14. But the error is the same. 

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 7.0.5
* react-native version: 0.70.1
* iOS/Android/Windows version:Montenery
* Does this reproduce on a debug build or release build? dev build (npx react-native run-ios)
* Does this reproduce on a simulator, or only on a physical device? IOS simulator

Here is the output of `react-native info`

```
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 116.89 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.1 => 0.70.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
(The more info the faster we will be able to address it!)

Many thanks.
```

**Comment by esbenvb** [comment]
I'm not sure if you have the same problem, but In my case, I got this error because I forgot to set the `CodePushDeploymentKey` in`Info.plist` :) 

Now that I have a configuration-specific `CODEPUSH_KEY` and have set the `CodePushDeploymentKey` to `$(CODEPUSH_KEY)`, it works!
