### ISSUE TITLE
An unknown error occurred. Error in getting binary resources modified time

### ISSUE THREAD

**Issue by omerkok** [microsoft/react-native-code-push#2354]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/48768206/196193591-3222d842-a10d-4c59-86e8-3bed5b71b342.png)
![image](https://user-images.githubusercontent.com/48768206/196193687-c3ebcb1d-abbf-47ea-99a1-dd73e585a956.png)
![image](https://user-images.githubusercontent.com/48768206/196193778-c067811a-fd4a-4e78-9556-ff595278af6f.png)

### Expected Behavior
After performing the installation steps. The update sent to Appcenter with codepush is downloaded to the devices without any problems.

### Actual Behavior
I have completed the necessary steps for installing codepush on Android. Then I submitted a version to test. ' An unknown error occurred while the version I sent was downloaded to the app. I got two warnings as Error in getting binary resources modified time ' and there is no detail in the error. Any way the app can't download the update.

Is this issue caused by react-native version?

### Environment

* react-native-code-push version:  7.0.5
* react-native version: 0.70.3
* iOS/Android/Windows version: all android
* Does this reproduce on a debug build or release build? debug and release
* Does this reproduce on a simulator, or only on a physical device? similator and physical

(The more info the faster we will be able to address it!)

**Comment by omerkok** [comment]
![image](https://user-images.githubusercontent.com/48768206/196194311-ed49740c-facd-4f10-9569-f3fc3bcc3c0b.png)

**Comment by omerkok** [comment]
When there was a problem in the project I was developing, I created a new project to be sure of the problem and tried it, but the same problem continues.

**Comment by Pashkagreen** [comment]
+1

**Comment by sagarv1997** [comment]
> I have a fix pushed up in #2337

Worked! Thank you very much!

**Comment by SoohyungJung** [comment]
@Abbondanzo 
You saved my life!!!
Thank you so much 👍👍👍

**Comment by DmitriyKirakosyan** [comment]
The fix has been released. Closing.
