### ISSUE TITLE
ON_NEXT_SUSPEND does not work on iOS

### ISSUE THREAD

**Issue by abhiin1947** [microsoft/react-native-code-push#2359]
### Steps to Reproduce
1. Set `ON_NEXT_SUSPEND` as the install mode. I used `minimumBackgroundDuration` as 30.
2. Create a non mandatory codepush
3. Install a codepush
4. App restarts immediately.

### Expected Behavior
What you expected to happen?
- App doesn't install the codepush until it's in the background for 30seconds.

### Actual Behavior
What actually happens?
The App immediately installs.

### Reproducible Demo
I don't have one yet.. Will try to get a reproducible build and update the issue

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.66.4
* iOS/Android/Windows version: iOS 15 & 16
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? I only tested it on a physical device

**Comment by abhiin1947** [comment]
Did not realize the Mandatory flag bubbles up if there are multiple bundles targeting the same binary version and one of them is mandatory. My bad 😅

**Comment by ajitaro** [comment]
> Did not realize the Mandatory flag bubbles up if there are multiple bundles targeting the same binary version and one of them is mandatory. My bad 😅

omg it happens to me also. i just realize the mandatory flag in true
