### ISSUE TITLE
Getting infrequent iOS crashes RCTFatalException: Error opening bundle /var/mobile/Containers/Data/Application/.....

### ISSUE THREAD

**Issue by KennyKYLam** [microsoft/react-native-code-push#2360]
### Steps to Reproduce
1. I deployed the Codepush app using the standard CLI, and client-side is the typical sync() method
2. I am getting seldom crashes on Sentry `RCTFatalException: Error opening bundle` only on iOS.

### Expected Behavior
I expect no codepush-related crashes on iOS release.

### Actual Behavior
The crash rate is low at around 1% per 100 installs for initial testing but I am trying to figure out the solution before the full rollout. Wondering if other codepush apps are facing similar crashes and what causes this? The numbers is close to rollback numbers but not sure if they are correlated. I have rollback retry config off currently.

Getting crashes on Sentry like this:
```
RCTFatalException: Error opening bundle  /var/mobile/Containers/Data/Application/.....
```
![Screen Shot 2022-10-27 at 3 23 10 PM](https://user-images.githubusercontent.com/6352869/198380314-c460cdec-106a-4833-a373-a199086d9d06.png)

### Environment

* react-native-code-push version: `7.0.5`
* react-native version: `0.64.2`
* iOS/Android/Windows version: iOS `7.0.5`
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

**Comment by shahnewaz469** [comment]
@KennyKYLam Did you able to resolve this issue?

**Comment by moniquealtero** [comment]
I'm facing this issue using NX, any news?
