### ISSUE TITLE
App built from new version automatic rollback to the previous version

### ISSUE THREAD

**Issue by QuangBinhDinh** [microsoft/react-native-code-push#2362]
### Steps to Reproduce
1. I already have version `1.0.5` of my IOS app in App Center's Code Push
2. I built a new version of my app (version `1.0.7`) and publish it through DeployGate to start testing
3. Uninstall version `1.0.5` on my iPhone and download version `1.0.7` to my phone
4. After a few times reopen, version `1.0.7` automatically roll back to version `1.0.5`, even I didn't push any new code for this version

### Expected Behavior
Version `1.0.7` stay the same after reopen app.

### Actual Behavior
Version `1.0.7` roll back to `1.0.5`

Here is screenshot of recently code pushed. 
<img width="707" alt="Untitled" src="https://user-images.githubusercontent.com/43164997/198965629-b56879cb-4e56-4b51-ad5f-ff12257423b5.png">

### Environment
* react-native-code-push version: 7.0.5
* react-native version: 0.66.4
* iOS/Android/Windows version: iOS 14.7.1
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? Physical device, iPhone 7

**Comment by QuangBinhDinh** [comment]
Hello any updates in here ???

**Comment by Mass812** [comment]
We appear to be having the same issue as well!

**Comment by sundaramLwt** [comment]
I am having the same issue also happening in android.
