### ISSUE TITLE
Could not resolve net.minidev:json-smart:[1.3.1,2.3].

### ISSUE THREAD

**Issue by Yandamuri** [microsoft/react-native-code-push#2363]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.Just run the app form Android Studio
2. Then you will encounter the following error 

### Expected Behavior
App should run without any errors

### Actual Behavior
What actually happens?
```
  > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve net.minidev:json-smart:{require [1.3.1,2.3]; prefer 2.3}.
     Required by:
         project :app > project :react-native-code-push > com.nimbusds:nimbus-jose-jwt:5.1
      > Failed to list versions for net.minidev:json-smart.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

```

### Reproducible Demo

I am unable to provide any reproducible demo as my project is huge.

### Environment

* react-native-code-push version: I tired in both 6.3.0 & 7.0.5
* react-native version: 0.64.3
* iOS/Android/Windows version: Android 12
* Does this reproduce on a debug build or release build? : debug
* Does this reproduce on a simulator, or only on a physical device? Simulator

I have gone through many similar issues and applied some solutions like,

1. adding this to "app/build.gradle" dependencies :
```
dependencies {
  components.all {
    allVariants {
      withDependencies { deps ->
        deps.each { dep ->
          if (dep.group == 'net.minidev' && dep.name =='json-smart') {
            dep.version {
                prefer "2.3"
            }
            dep.because "resolving dependencies issue"
          }
        }
      }
    }
  }
```

2. adding `mavenCentral ()` to both `allprojects` and buildscript's `repositories` in `android/buid.gradle`.

3. adding `maven { url 'https://plugins.gralde.org/m2/'}` to `allprojects` in `android/buid.gradle`.

But none of these solutions worked for me.

Note: My app is working fine till yesterday. I just ran the app from `Android Studio` today morning, Then I faced this issue. 
(The more info the faster we will be able to address it!)

**Comment by renansoaress** [comment]
I have the same problem. :(

**Comment by renansoaress** [comment]
Apparently the problem is with https://jcenter.bintray.com/net/minidev/json-smart/maven-metadata.xml (https://jcenter.bintray.com) is down.
Here we can see the status https://status.gradle.com/

**Comment by alexandreerick** [comment]
Same problem here

**Comment by Yandamuri** [comment]
@renansoaress Yes, You are right. Now the app is running successfully without doing any changes. Thanks for your help.

**Comment by srk-stack** [comment]
I am facing the same issue today. Seems like [https://jcenter.bintray.com/](jcenter.bintray.com) is down. However, [https://status.gradle.com/](gradle Status) is showing as Operational
