### ISSUE TITLE
ReactNative windows CodePush is not updating latest build

### ISSUE THREAD

**Issue by Narenthran-Manokaran** [microsoft/react-native-code-push#2365]
#2256 
Referenced link:https://microsoft.github.io/react-native-windows/blog/2021/05/17/codepush
We can push the latest update to the app center, but as mentioned, trying to restart the application is not updating the app.

![163814213-cfd625b3-0983-4879-910f-67d70c0ed54a](https://user-images.githubusercontent.com/6009549/199428626-2a2fb658-6ee9-4fb6-b252-81efaa2546e2.png)

![163813897-43e16913-ce40-41a6-a971-4ee0f0f33b25](https://user-images.githubusercontent.com/6009549/199428643-393a3500-a7e5-45dd-9d9d-287fec20e5af.png)

![163814016-b263b72f-f6f1-4c60-ba96-5c7e0b3f9df7](https://user-images.githubusercontent.com/6009549/199429037-a042978d-64d5-4f41-9fe0-220ecd75a056.png)

![163814052-4d41e504-f0b1-4078-b1e2-5fd726b1c6ac](https://user-images.githubusercontent.com/6009549/199429070-aeb74cce-9793-4e93-8142-f6efe55fdaae.png)

![163814132-374ca8ba-f1f2-47af-b94a-0ba92c565282](https://user-images.githubusercontent.com/6009549/199429091-f6ca5a72-e184-43d3-8c83-3cd81ea7224e.png)

@qmatteoq @msftgits

**Comment by safaaroua** [comment]
Hello did you manage to fix this issue?
