### ISSUE TITLE
[Question] Ignore image from CodePush bundle

### ISSUE THREAD

**Issue by blueberry6401** [microsoft/react-native-code-push#2367]
My bundle size is growing in size, and mostly because of images, which is rarely needed to update. 
So is there any way to ignore those images from bundle in?
Thanks.

**Comment by swizes** [comment]
One tideous option is to add images on android and ios native side instead of including into the js bundle. I recommend to do it for large images and keep icons svgs etc in js bundle

**Comment by blueberry6401** [comment]
> One tideous option is to add images on android and ios native side instead of including into the js bundle. I recommend to do it for large images and keep icons svgs etc in js bundle

Thanks for your reply. How do I refer to images put in native? @swizes
