### ISSUE TITLE
Error: spawn node_modules\hermesvm\win64-bin\hermes ENOENT

### ISSUE THREAD

**Issue by abdullahIsa** [microsoft/react-native-code-push#2368]
Hello i am having this issue after upgrading to react native 0.70.4 and appcenter 4.4.5 and react-native-code-push ^7.0.5

### Log

```
PS C:\Users\Abdullah\Desktop\Programming\company\apps\Chappie\Chappie-0.70.4> npm run codePushStagingAndroid

> chappie@0.0.9 codePushStagingAndroid
> appcenter codepush release-react -a EnTechCS/Chappie -d Staging

Detecting android app version:

Using the target binary version value "0.0.9" from "android\app\build.gradle".

Running "react-native bundle" command:

node node_modules\react-native\local-cli\cli.js bundle --assets-dest C:\Users\Abdullah\AppData\Local\Temp\code-push2022106-20196-109374m.ias9\CodePush --bundle-output C:\Users\Abdullah\AppData\Local\Temp\code-push2022106-20196-109374m.ias9\CodePush\index.android.bundle --dev false --entry-file index.js --platform android
Welcome to Metro v0.72.3
              Fast - Scalable - Integrated

info Writing bundle output to:, C:\Users\Abdullah\AppData\Local\Temp\code-push2022106-20196-109374m.ias9\CodePush\index.android.bundle
info Done writing bundle output
info Copying 113 asset files
info Done copying assets
Converting JS bundle to byte code via Hermes, running command:

node_modules\hermesvm\win64-bin\hermes -emit-binary -out C:\Users\Abdullah\AppData\Local\Temp\code-push2022106-20196-109374m.ias9\CodePush\index.android.bundle.hbc C:\Users\Abdullah\AppData\Local\Temp\code-push2022106-20196-109374m.ias9\CodePush\index.android.bundle -w
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\hermesvm\win64-bin\hermes ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn node_modules\\hermesvm\\win64-bin\\hermes',
  path: 'node_modules\\hermesvm\\win64-bin\\hermes',
  spawnargs: [
    '-emit-binary',
    '-out',
    'C:\\Users\\Abdullah\\AppData\\Local\\Temp\\code-push2022106-20196-109374m.ias9\\CodePush\\index.android.bundle.hbc',
    'C:\\Users\\Abdullah\\AppData\\Local\\Temp\\code-push2022106-20196-109374m.ias9\\CodePush\\index.android.bundle',
    '-w'
  ]
}
```

**Comment by abdullahIsa** [comment]
@andreidubov @alexandergoncharov-zz

**Comment by markl-vesper** [comment]
+1 same issue here

react-native 0.70.2
react-native-code-push 7.0.1
appcenter-cli 2.11.0

Will check other comments in other threads to see what I can find but this was working fine a week ago and no react-native upgrade apart from some minor packages

**Comment by markl-vesper** [comment]
I guess one way to fix this is to disable hermes but I dont know the knock on effect of disabling

**Comment by abdullahIsa** [comment]
> I guess one way to fix this is to disable hermes but I dont know the knock on effect of disabling

I think you might be right but I don't really want to turn it off, I can make normal builds but only code push not working, disabling Hermes will lead to certain low performance. wish someone from the team replies.

**Comment by ajiehatajie** [comment]
same issue 

react-native 0.70.5
react-native-code-push 7.0.5
appcenter-cli 2.11.0

```
node_modules/hermesvm/osx-bin/hermes -emit-binary -out /var/folders/ds/g6jgv1651rl3_sdrxg24fdtm0000gn/T/code-push20221016-42833-ry34g3.hokah/CodePush/index.android.bundle.hbc /var/folders/ds/g6jgv1651rl3_sdrxg24fdtm0000gn/T/code-push20221016-42833-ry34g3.hokah/CodePush/index.android.bundle -w
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/hermesvm/osx-bin/hermes ENOENT
```

**Comment by alz10** [comment]
Same Issue here. Any fix???
```
"react": "18.1.0",
"react-native": "0.70.5",
"react-native-code-push": "^7.0.5",
appcenter version 2.7.4
```
<img width="1121" alt="Screen Shot 2022-11-17 at 11 23 34 AM" src="https://user-images.githubusercontent.com/38030623/202347135-586850fd-226f-435c-8d7a-10df3e32d0d7.png">

**Comment by elliotdickison** [comment]
You need to update appcenter-cli to 2.11.0 or greater. See: https://github.com/microsoft/appcenter-cli/issues/1987

**Comment by markl-vesper** [comment]
@elliotdickison 2.11.0 made zero difference for us

hermes: false for better or for worse got us past the error till it gets properly resolved

**Comment by abdullahIsa** [comment]
> @elliotdickison 2.11.0 made zero difference for us
> 
> hermes: false for better or for worse got us past the error till it gets properly resolved

Same true, even worse build failing if i use Hermes false, anyone has a solution???? cause this really slows down updates.

**Comment by elliotdickison** [comment]
I'm confident that appcenter-cli@2.11.0 fixes the error described by this particular issue (the error caused by appcenter looking for hermes in the wrong location: `Error: spawn node_modules\hermesvm\win64-bin\hermes ENOENT`). If you are still experiencing that error after upgrading appcenter-cli I'd try cleaning, cleaning, cleaning, and rebuilding. There's a lot at play though and it's definitely possible that you're facing other unrelated issues.

**Comment by abdullahIsa** [comment]
@elliotdickison i have cleaned and gradlew clean and reinstalled node_modules many times still the same error, no idea what to do anymore as i can create a build normally without error but code push is the only error i am facing.

"react": "18.1.0",
"react-native": "^0.70.6"
"react-native-code-push": "^7.0.5"

appcenter-cli 2.12.0

**Comment by elliotdickison** [comment]
@abdullahIsa If you dig into appcenter-cli, here's the bit of code used to call hermes:

https://github.com/microsoft/appcenter-cli/blob/c272be7a342129cb34dd55f389d97bca9347f7ec/src/commands/codepush/lib/react-native-utils.ts#L535-L560

I poke through that logic to determine why it's falling through to line 558 and attempting to call the binary in the non-existent hermesvm folder (e.g. does hermes not exist in the location from line 544). Also, it looks like per line 549 you might actually be able to specify `hermesCommand` in your gradle file and override the broken automatic lookup code.

**Comment by rizalthewebdev** [comment]
@elliotdickison thanks it works, i add this into android/app/build.gradle
`project.ext.react = [
    entryFile: "index.js",
    hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes", // Or whatever path you need
    enableHermes: true, // clean and rebuild if changing,
]`

**Comment by abdullahIsa** [comment]
> @elliotdickison thanks it works, i add this into android/app/build.gradle `project.ext.react = [ entryFile: "index.js", hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes", // Or whatever path you need enableHermes: true, // clean and rebuild if changing, ]`

hmm i did same

```
project.ext.react = [
    enableHermes: true,  // clean and rebuild if changing
    hermesCommand: "../../node_modules/hermes-engine/%OS-BIN%/hermes",
]
```

i went into android dir and also ran ` ./gradlew clean`

still same error 🙁

**Comment by abdullahIsa** [comment]
I just want to update that issue has been resolved, did many uninstall and cleaning and eventually worked, thanks.
