### ISSUE TITLE
CodePush release doesn't install on devices

### ISSUE THREAD

**Issue by efeakyuz** [microsoft/react-native-code-push#2376]
When I release a new release with CodePush, the contents are downloaded but not installed on the device. When I check from Appcenter CLI I see `Installed: 0 (200 pending)`. I've been observing such a problem since we updated the React native version of our app to the latest version. Is there something I missed in the config? When using the `RN 0.63.3` version, we use whatever config exists. In the old version, codepush release was installed on the devices without any problem. We have migrated to RN `0.70.5` and are facing this now.

### Steps to Reproduce
- There is no reproduce steps

### Expected Behavior
What you expected to happen?
- It should download and install the newly created CodePush release without any problems.

### Actual Behavior
What actually happens?
The newly created CodePush version downloads to the device but is not installed.
```
Installed: 0 (200 pending)
```

### Environment

* react-native-code-push version: `7.0.5`
* react-native version: `0.70.5`
* iOS/Android/Windows version: `any iOS version`
* Does this reproduce on a debug build or release build? `Release`
* Does this reproduce on a simulator, or only on a physical device? `physical`
(The more info the faster we will be able to address it!)

### AppDelegate.m

```js
#import <CodePush/CodePush.h>
...

{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [CodePush bundleURL];
#endif
}
```

### Info.plist

```js
<key>CodePushDeploymentKey</key>
<string>{CodePushDeploymentKey}</string>
```

### Codepush Sync on App start

```js

syncFunction = async ()  => {
await CodePush.sync(
            { installMode: CodePush.InstallMode.ON_NEXT_RESTART },
            async (status) => {
...
...
...
..
}

let codePushOptions = {
  checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME,
};
```

**Comment by teckbeng-payboy** [comment]
i also cant get the update to download on my app.

i can get the update dialog to show, but after i click accept, there is nothing happen on the app

**Comment by Arun-paramasivam** [comment]
+1 happens the same in android(haven't tested on iOS). i have migrated the project from 0.63.4 to 0.70.5. 
"react-native-code-push": "^7.0.5"
appcenter cli version: 2.12.0

**Comment by efeakyuz** [comment]
I'm not entirely sure yet, but it seems to me that CodePush.sync is not working. I added the `installMode` that I made in CodePush.sync function to `codePushOptions` and got a new tesflight build. When I checked from Appcenter CLI, I can say that the install works. but as I said, I haven't been released to prod yet, so I don't know if the problem is just related to this.

**Comment by Alaa-Ben** [comment]
Same issue on android, update cannot be installed on react native 0.70 + :'(

**Comment by tischenkoa** [comment]
we also have this problem

**Comment by tischenkoa** [comment]
problem solution here https://github.com/microsoft/react-native-code-push/issues/1961#issuecomment-710698621

**Comment by BalogunofAfrica** [comment]
Facing this issue, running react-native `0.70.5`, react-native-code-push version is `7.0.5`. It works for iOS but it doesn't download for Android

**Comment by efeakyuz** [comment]
In my case, my bundles for iOS and Android are outdated. I also changed the codepush bundle folder and did all the jobs again. and voila worked like a charm.

- iOS bundle: `react-native bundle --platform ios --entry-file index.js --bundle-output ./CodePush/main.jsbundle --assets-dest ./CodePush --dev false`

- Android bundle: `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/`
  - if you are getting `Duplicate Resource` try:
  - `rm -rf ./android/app/src/main/res/drawable-*`
  - `rm -rf ./android/app/src/main/res/raw`

End do not forget to change new codepush bundle file in your appcenter script:
- `appcenter codepush release-react -a <appName> -d <env> --sourcemap-output --output-dir ./CodePush`

**Comment by BalogunofAfrica** [comment]
@tischenkoa's suggestion worked!!!!
