### ISSUE TITLE
A JS bundle file named "null" 

### ISSUE THREAD

**Issue by NoelMiranda1** [microsoft/react-native-code-push#2389]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Release bercion to dev environment with minimal update
2. start the application and wait for the available update dialog
3.Press Install option and cannot install the version returning this error: Update is invalid - A JS bundle file named "null" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.

### Expected Behavior
What you expected to happen?
That the update is installed correctly

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
![Captura de pantalla 2022-12-09 a la(s) 10 52 23](https://user-images.githubusercontent.com/55200516/206752082-cd1a7352-bcba-491c-ae18-70b4c15f434e.png)

<img width="429" alt="Captura de pantalla 2022-12-09 a la(s) 10 52 43" src="https://user-images.githubusercontent.com/55200516/206752115-cee6d84b-05dc-4ed6-8818-2f408e9f3215.png">

<img width="1214" alt="Captura de pantalla 2022-12-09 a la(s) 10 52 51" src="https://user-images.githubusercontent.com/55200516/206752151-67943ccf-9d86-4139-8b50-55ea5fd33965.png">

### Environment

* react-native-code-push version:  7.0.4
* react-native version: 0.62.2 
* iOS/Android/Windows version: Android 10
* Does this reproduce on a debug build or release build?
All
* Does this reproduce on a simulator, or only on a physical device?
 simulator and physical

**Comment by Dooqp** [comment]
**-----FIX-----**

@NoelMiranda1 

I've faced with the same issue and fixed it by overriding getJSBundleFile method inside MainApplicationReactNativeHost class. The problem was I was using new architecture for android but documentation only talks about overriding getJSBundleFile method inside ReactNativeHost (which is used if newarchitecture is disabled)

```java
...
// 1. Import the plugin class.
import com.microsoft.codepush.react.CodePush;

public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        ...

        // 2. Override the getJSBundleFile method in order to let
        // the CodePush runtime determine where to get the JS
        // bundle location from on each app start
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
    };
}
```

but if the new architecture is enabled react-native uses MainApplicationReactNativeHost which is inside  "newarchitecture" folder of your project. So just override this method there as well and it will work. (It did work on my case at least).

I think it should have been pointed out on [Android Setup](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md) docs as well

**Comment by NoelMiranda1** [comment]
> **-----FIX-----**
> 
> @NoelMiranda1
> 
> I've faced with the same issue and fixed it by overriding getJSBundleFile method inside MainApplicationReactNativeHost class. The problem was I was using new architecture for android but documentation only talks about overriding getJSBundleFile method inside ReactNativeHost (which is used if newarchitecture is disabled)
> 
> ```java
> ...
> // 1. Import the plugin class.
> import com.microsoft.codepush.react.CodePush;
> 
> public class MainApplication extends Application implements ReactApplication {
> 
>     private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
>         ...
> 
>         // 2. Override the getJSBundleFile method in order to let
>         // the CodePush runtime determine where to get the JS
>         // bundle location from on each app start
>         @Override
>         protected String getJSBundleFile() {
>             return CodePush.getJSBundleFile();
>         }
>     };
> }
> ```
> 
> but if the new architecture is enabled react-native uses MainApplicationReactNativeHost which is inside "newarchitecture" folder of your project. So just override this method there as well and it will work. (It did work on my case at least).
> 
> I think it should have been pointed out on [Android Setup](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md) docs as well

This does not accompany my problem since I do not have the new RN architecture, in the same way I have tried it without success
