### ISSUE TITLE
Installupdate expected 4 arguments, got 5

### ISSUE THREAD

**Issue by avishayil** [Microsoft/react-native-code-push#239]
Latest version, Android.
````
Fatal Exception: com.facebook.react.bridge.NativeArgumentsParseException
CodePush.installUpdate got 5 arguments, expected 4
 raw
com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke (BaseJavaModule.java:227)
com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call (NativeModuleRegistry.java:158)
com.facebook.react.bridge.NativeModuleRegistry.call (NativeModuleRegistry.java:58)
com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call (CatalystInstanceImpl.java:428)
com.facebook.react.bridge.queue.NativeRunnableDeprecated.run (NativeRunnableDeprecated.java)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:31)
android.os.Looper.loop (Looper.java:145)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (M
````

**Comment by avishayil** [comment]
Also:
CodePush.m:549:42: Use of undeclared identifier 'minimumBackgroundDuration'

**Comment by lostintangent** [comment]
I just checked-in a fix for the second issue, but I can't repro the first one. If you re-pull from GitHub, and  make sure you restart the packager after updating the CodePush plugin, you should be good to go. If you continue to see this problem, could you let us know how you're running if you're running your app in debug or release mode, and against the emulator or a device? Thanks!

**Comment by lostintangent** [comment]
@avishayil If you pull the latest from GitHub, this issue should be resolved. I'll close this bug for now but please re-open it if the problems persists for you. Thanks! And don't forget to kill any packager processes after the upgrade :)
