### ISSUE TITLE
Supported platform version confusion 

### ISSUE THREAD

**Issue by wlai-wavefin** [microsoft/react-native-code-push#2395]
We are checking the supported reactive native version and its corresponding CP versions, where the latest version is:  

v0.65-v0.69 | v7.2+ (RN updated iPhone-target-version)

We're confused that 
1. The doc said v7.2+ but the latest CodePush ver is v7.0.5 (so is it supported or not? ) 
2. The latest RN version is v0.7 which is not on the list (so is it supported or not?) 

Thanks for helping us to clarify theses.

**Comment by MCervenka** [comment]
my exact thought
