### ISSUE TITLE
Bad Documentation Installation Error Not Working yarn add appcenter appcenter-analytics appcenter-crashes --exact

### ISSUE THREAD

**Issue by putuoka** [microsoft/react-native-code-push#2396]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. npx react-native init codepushTest --template react-native-template-typescript
2. yarn add appcenter appcenter-analytics appcenter-crashes --exact --> from this documentation https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/react-native
3. yarn android --> and error can't run anything

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by vozaldi** [comment]
React Native CodePush doesn't require these command 

~~`yarn add appcenter appcenter-analytics appcenter-crashes --exact`~~

You can follow this documentation instead

1. Install the App Center CLI [https://learn.microsoft.com/en-us/appcenter/distribution/codepush/](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/)
2. CodePush-ify your app [https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started](https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started)
