### ISSUE TITLE
 [CodePush] An unknown error occurred.  Error in getting binary resources modified time

### ISSUE THREAD

**Issue by putuoka** [microsoft/react-native-code-push#2397]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Create account on https://appcenter.ms/
2. npx react-native init codepushTest --template react-native-template-typescript
3. Follow step here https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md only on section "Plugin Installation and Configuration for React Native 0.60 version and above (Android)"
4. add appcenter-config.json file like instruction here https://appcenter.ms/users/putu.oka-karmagroup.com/apps/pitchbook
5. import codePush from 'react-native-code-push'; & add export default codePush(App);

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS


```
![image](https://user-images.githubusercontent.com/20880839/207267653-c6456915-8008-47ab-bff3-94a680f99fc3.png)

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by lchenfox** [comment]
It works. Thank u so much.

**Comment by Abbondanzo** [comment]
This bug has been fixed for [Version 7.1.0](https://github.com/microsoft/react-native-code-push/releases/tag/v7.1.0)
