### ISSUE TITLE
Crashlytics detects codepush as a crash in Android devices

### ISSUE THREAD

**Issue by octobus55** [microsoft/react-native-code-push#2400]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Distribute a codepush from appcenter as mandatory
2. Open the application in an android device
3. Application doesn't crash but there is a log in crashlytics

### Expected Behavior
There shouldn't be a crash log in crashlytics

### Actual Behavior
What actually happens?
It causes a crash log in crashlytics.
```
 libsc.so
Crashed: Thread: SIGABRT  0x0000000000000000
#00 pc 0x62b20 libc.so 
#01 pc 0x4fb4ae libart.so 
#02 pc 0xa9702 ld-android.so 
#03 pc 0x4fc956 libart.so 
#04 pc 0x4fcffa libart.so 
#05 pc 0x3fe66f libart.so 
#06 pc 0xabbb7 libart.so 
#07 pc 0xa9ce2 libart.so 
#08 pc 0xb70c2 libart.so 
#09 pc 0x4fcffa libart.so 
#10 pc 0x4fb4f6 libart.so 
#11 pc 0x4fcff2 libart.so 
#12 pc 0xa6b50 libart.so 
#13 pc 0xba2b2 libc.so 
#14 pc 0x2b526 libbase.so 
#15 pc 0xba2b2 libc.so 
#16 pc 0x4fcffa libart.so 
#17 pc 0xba2b2 libc.so 
#18 pc 0xd97f libbase.so 
#19 pc 0x2b4de libbase.so 
#20 pc 0xd2b3 libbase.so 
#21 pc 0xa9702 ld-android.so 
#22 pc 0xa9702 ld-android.so 
#23 pc 0xba2b2 libc.so 
#24 pc 0x226cc5 libart.so 
#25 pc 0xabbb7 libart.so 
#26 pc 0x298967 libart.so 
#27 pc 0xba2b2 libc.so 
#28 pc 0xabbb7 libart.so 
#29 pc 0x4fcffa libart.so 
#30 pc 0xba2b2 libc.so 
#31 pc 0x4449c3 libart.so 
#32 pc 0xba2b2 libc.so 
#33 pc 0x2c441 libc.so 
#34 pc 0xba2b2 libc.so 
#35 pc 0x5e825 libc++_shared.so 
#36 pc 0x16e3f libhermes.so 
#37 pc 0xba2b2 libc.so 
#38 pc 0x16dc9 libhermes.so 
#39 pc 0x2afff libhermes.so 
#40 pc 0x7d31b libreanimated.so 
#41 pc 0xba2b2 libc.so 
#42 pc 0x140cd libhermes.so 
#43 pc 0xabbb7 libart.so 
#44 pc 0x4fcffa libart.so 
#45 pc 0xba2b2 libc.so 
#46 pc 0x2a5ac7 libart.so 
#47 pc 0x2c441 libc.so 
#48 pc 0xb70c2 libart.so 
#49 pc 0x5e825 libc++_shared.so 
#50 pc 0x14087 libhermes.so 
#51 pc 0x68e7e libreanimated.so 
#52 pc 0x14087 libhermes.so 
#53 pc 0x69f86 libreanimated.so 
#54 pc 0x70e02 libreanimated.so 
#55 pc 0x5f6de libreanimated.so 
#56 pc 0x70fd6 libreanimated.so 
#57 pc 0x70f5e libreanimated.so 
#58 pc 0x70f12 libreanimated.so 
#59 pc 0x70fa2 libreanimated.so 
#60 pc 0x7c2d44c7  
```

### Environment

* react-native-code-push version: 7.0.5
* react-native version: 0.68.3
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Physical device

(The more info the faster we will be able to address it!)

We tested this behavior, the release's crash free rate suddenly drops when the codepush is published

**Comment by ajiehatajie** [comment]
same issue

**Comment by ReactNativ** [comment]
When we do clear data(appInfo -> storage)
The update is done and does not crash
Is there a command to delete the CodePush before the previous update?

**Comment by Kariap** [comment]
+1

**Comment by Poojapandey89** [comment]
Facing same issue in version 7.0.5. Is it fixed in latest version 7.1.0?

**Comment by malikzype** [comment]
Same issue. Even Bugsnag report CodePush as Crash

**Comment by Miti063** [comment]
Facing same issue, do we have any update?

**Comment by octobus55** [comment]
@Miti063 Unfortunately not, still waiting for a proper solution

**Comment by cw-sanjeev** [comment]
Facing the same issue

**Comment by wuluru1002320** [comment]
Still Facing the same issue

**Comment by MikhailSuendukov** [comment]
Hello @wuluru1002320, and thank you for reaching out to us! Could you please provide more details about the error and clarify the following about your environment:

- What is the react-native-code-push version?
- What is the react-native version?
- Which version(s) of iOS, Android, or Windows are affected?
- Does the issue occur in a debug build, a release build, or both?
- Does the issue occur on a simulator/emulator, a physical device, or both?

Your answers will help us diagnose the problem more accurately. Thank you!
