### ISSUE TITLE
Changes are not reflecting on iPhone

### ISSUE THREAD

**Issue by hypesol** [microsoft/react-native-code-push#2414]
I am using below mentioned version

react-native: "0.70.6"
react-native-code-push: "^7.0.5"

Changes are not reflecting on iPhone. Code is being pushed on appcenter but not downloading and install on iPhone devices.

**Comment by ajaxjiang96** [comment]
same here. the app was able to trigger an update dialog but nothing happens after pressing continue

**Comment by pjc0247** [comment]
Did you get any messages from codepush?

for me, it prints:
`[CodePush] undefined is not a function`

**Comment by hypesol** [comment]
No i am not getting any message code push is working fine on Android but not on iOS

**Comment by pjc0247** [comment]
In my case, `fetch` api was broken for the entire app. (don't know why)
So I had to replace [fetch](https://github.com/microsoft/react-native-code-push/blob/master/request-fetch-adapter.js#L23) with `axios` using `yarn patch`.

**Comment by pjc0247** [comment]
You can also find out which line breaks the code-push by adding `console.log` line by line.

**Comment by ajaxjiang96** [comment]
> same here. the app was able to trigger an update dialog but nothing happens after pressing continue

Update: For me it was a different case. The network connection to App Center is a bit slow so wasn't able to tell if it's downloading or not. One way to debug this is to add a manual sync button, with update progress displayed somewhere. Also please check your `installMode`. The default behavior is installing the update on the next restart.

**Comment by hypesol** [comment]
I have checked all scenarios but still everything working on android but iOS not updating.

**Comment by vfmachado** [comment]
Hi folks, same problem here.

1. The app update is fine and changes reflect;
2. Close and open the app
3. Changes from the update do not persist

Is there a known work around to it?

Thanks

**Comment by SutharRohit** [comment]
Hi,

I am getting the same issue in iOS only, but for the android it is working fine.

i am using:
```
"react-native": "0.66.4",
"react-native-code-push": "^7.1.0",
```

anyone found solution for this issue ?

**Comment by viniciusRosa** [comment]
hi, same problem here, changes don't persist on IOS.

"react-native": "0.68.5",
"react-native-code-push": "^7.0.4"

if anyone found any update for this issue, please share us

thanks

**Comment by prateekuttreja2020** [comment]
Hi,

I am getting the same issue in iOS only, but for the android it is working fine.

i am using:

"react-native": "0.70.8",
"react-native-code-push": "^7.1.0",

Anyone found solution for this issue ?

**Comment by HSReact** [comment]
Same issue here, anyone listening please help.

**Comment by pjtcoco** [comment]
i am getting this error for both ios and android

**Comment by sosa-17** [comment]
Hi!

I am getting the same issue in iOS only, but for the android it is working fine.

**Comment by yosukapro** [comment]
Same here for iOS but work fine for Android. Did  you get new any solution for it?

**Comment by BILLXZY1215** [comment]
Same, any workaround?

**Comment by dkahdwk** [comment]
Same issue....

**Comment by AnatolyPristensky** [comment]
Closing due to the absence of activity.
