### ISSUE TITLE
CodePushDialog.showDialog show incorrect buttons order 

### ISSUE THREAD

**Issue by retyui** [microsoft/react-native-code-push#2420]
Why we need this `AlertAdapter`? 
https://github.com/microsoft/react-native-code-push/blob/67debe6c9f7e345f9bb10cf9f2e9cfcf7d4661ad/AlertAdapter.js#L16-L20

button order incorrect on Android

### Steps to Reproduce

```tsx
CodePush.sync({
  installMode: CodePush.InstallMode.IMMEDIATE,
  updateDialog: {
     // Ask mobile team member before install new version for custom deployment
  },
  // ...
});
```

### Expected Behavior

`"Install"` button should left align (as on iOS)

### Actual Behavior

| iOS | Android |
|---|---|
| <img width="379" alt="Screenshot 2023-01-15 at 23 29 38" src="https://user-images.githubusercontent.com/4661784/212570762-fb8db082-b68f-466b-81e2-797d6f212c19.png"> | <img width="379" alt="Screenshot 2023-01-15 at 23 29 38" src="https://user-images.githubusercontent.com/4661784/212570771-cb702525-e20b-40be-96a8-e8b6de90327b.png"> |

### Reproducible Demo

https://github.com/retyui/CodePushCiCd

### Environment

* react-native-code-push version: 7.0.5
* react-native version: all
* iOS/Android/Windows version: all

**Comment by ko-devHong** [comment]
You can solve this problem by branching according to the platform.

**Comment by retyui** [comment]
@ko-devHong reivew pls https://github.com/microsoft/react-native-code-push/pull/2438

**Comment by davydspotnana** [comment]
no please no

**Comment by davydspotnana** [comment]
no
