### ISSUE TITLE
CppException：Could not open file/data/user/0/com.fanggeek.shikamaru/files/CodePush/ffa7bf1448f4d2afcddefe871cdb886f233744009a78c9a3849085bf1d07c161/assets/index.android.bundle: No such file or directory

### ISSUE THREAD

**Issue by Felix8029** [microsoft/react-native-code-push#2421]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior

# create_react_context(2644)

com.facebook.jni.CppException

facebook::react::Recoverable: Could not open file/data/user/0/com.fanggeek.shikamaru/files/CodePush/ffa7bf1448f4d2afcddefe871cdb886f233744009a78c9a3849085bf1d07c161/assets/index.android.bundle: No such file or directory

com.facebook.react.bridge.CatalystInstanceImpl.jniLoadScriptFromFile(Native Method)

com.facebook.react.bridge.CatalystInstanceImpl.loadScriptFromFile(CatalystInstanceImpl.java:254)

com.facebook.react.bridge.JSBundleLoader$2.loadScript(JSBundleLoader.java:48)

com.facebook.react.bridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:277)

com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1422)

com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)

com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)

java.lang.Thread.run(Thread.java:930)

### Actual Behavior
download update package, then restart app, app is not start and throw this exception;

but i try to app setting and delete data, then restart app, its ok ? why ?

i received many our users report this exception !

### Environment

* react-native-code-push version: 7.0.5
* react-native version: 0.68.2
* iOS/Android/Windows version: Android 12
* Does this reproduce on a debug build or release build? : both
* Does this reproduce on a simulator, or only on a physical device?  on physical

**Comment by Felix8029** [comment]
Caused by multiple process， I solve it

**Comment by bhupali-sharechat** [comment]
@Felix8029 how did you solve it?

**Comment by Felix8029** [comment]
> multiple process

My problem here is that the App is multi-process, and when the Application initializes the RN-related logic, ReactNativeHost is repeatedly initialized, which also causes the code-push update logic and state to be repeatedly consumed and changed by the initialization of other processes. 

Workaround: Only initialize the associated RN logic in the main process

**Comment by Felix8029** [comment]
> @Felix8029 how did you solve it?

My problem here is that the App is multi-process, and when the Application initializes the RN-related logic, ReactNativeHost is repeatedly initialized, which also causes the code-push update logic and state to be repeatedly consumed and changed by the initialization of other processes. 

Workaround: Only initialize the associated RN logic in the main process
