### ISSUE TITLE
Codepush Trying To Sync On Startup Unnecessarily In Android

### ISSUE THREAD

**Issue by niftytyro** [microsoft/react-native-code-push#2422]
### Steps to Reproduce
1. Setup Codepush In React Native App.
2. In `strings.xml`, give a random deployment key, in my case - `'This is set in JS'`
3. Pass the deployment key in codepush options, and set `checkFrequency` to `MANUAL`.
4. Call `sync()` with the appropriate deployment key at a later stage in the app.
5. Run app and monitor network.

### Expected Behavior
It should make a network call to check for updates where `sync()` is called.

### Actual Behavior
It makes multiple network calls. One call is made at a later stage where `sync()` is defined and uses the correct deployment key. But initially, 2 extra network calls are made to `https://codepush.appcenter.ms/v0.1/public/codepush/report_status/deploy` with the wrong deployment key. They use the `'This is set in JS'` deployment key instead of the one set in codepush options in JS. This means that these calls are probably being made before even my RN activity boots up.
So I have 2 questions:
1. What is the purpose of these network calls? Are they really necessary?
2. And why are they being made in Android, while I see no such calls in iOS?

### Environment

* react-native-code-push version: 7.0.5
* react-native version: 0.65.2
* Android version: 11
* Does this reproduce on a debug build or release build? - debug build
* Does this reproduce on a simulator, or only on a physical device? - simulator

**Comment by ko-devHong** [comment]
why different use codepushKey ??
