### ISSUE TITLE
Codepush only works on android 12

### ISSUE THREAD

**Issue by khanhnn09** [microsoft/react-native-code-push#2423]
Please I need help with this problem.

### Expected Behavior

It can run directly on android studio, but when run apk or bundle only works on android 12, Another version gives an error "The update could not be verified because it was not signed by a trusted party."
### Build Grade
```
buildscript {
    ext {
        buildToolsVersion = "33.0.1"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        supportLibVersion   = "33.0.1"
        googlePlayServicesVersion      = "17.0.0"
        androidMapsUtilsVersion = "1.2.1"
        androidXCore = "1.6.0"
        ndkVersion = "22.1.7171670"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.5.3")
        classpath 'com.google.gms:google-services:4.3.5'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

```
### Environment
> 

* react-native-code-push version: 7.0.4
* react-native version: 0.64.0

(The more info the faster we will be able to address it!)

**Comment by ko-devHong** [comment]
duplicate : https://github.com/Microsoft/react-native-code-push/issues/1079
