### ISSUE TITLE
Android: Using react.gradle in your project is deprecated! (app instantly crashes with Hermes)

### ISSUE THREAD

**Issue by RnbWd** [microsoft/react-native-code-push#2428]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Upgrade to react-native ^0.70.1

### Expected Behavior
App launches normally

### Actual Behavior
App crashes immediately upon launch with this error message in the Android emulator:
```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
	SoSource 0: com.facebook.soloader.ApkSoSource
```
Also this warning appears while building the app for Android:
```
##############################

Using react.gradle in your project is deprecated! You should move to "apply plugin: com.facebook.react"
react.gradle is going to be removed in a future React Native project and your project will not build anymore.
You can use the template as a reference:
https://github.com/facebook/react-native/blob/main/template/android/app/build.gradle

##############################

```

However, the app launches normally when `hermesEnabled=false`, or if I comment out the react-native-codepush code in `src/build.gradle` and `main/MainApplication.java`

### Environment

* react-native-code-push version: 7.0.5
* react-native version:0.71.1
* iOS/Android/Windows version: Android Emulator API 33
* Does this reproduce on a debug build or release build? debug build
* Does this reproduce on a simulator, or only on a physical device? simulator (not sure about physical device)

(The more info the faster we will be able to address it!)

**Comment by ko-devHong** [comment]
duplicate issue : https://github.com/microsoft/react-native-code-push/issues/2418

**Comment by azharuddin1801734** [comment]
i am facing same issue durig runtime react native project

1.Using react.gradle in your project is deprecated! You should move to "apply plugin: com.facebook.react"
react.gradle is going to be removed in a future React Native project and your project will not build anymore.

2.The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=e26f7bff-1f80-47e2-91ac-d9016c8f3b00, currentDir=C:\Nodejs_Tricky\Freshser-Project\hikma-health-app\android}
Attempting to read last messages from the daemon log...
Daemon pid: 7520
  log file: C:\Users\atulk\.gradle\daemon\6.7.1\daemon-7520.out.log
----- Last  20 lines from daemon log file - daemon-7520.out.log -----

3.Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
----- End of the daemon log -----
4.Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=e26f7bff-1f80-47e2-91ac-d9016c8f3b00, currentDir=C:\Nodejs_Tricky\Freshser-Project\hikma-health-app\android}
Attempting to read last messages from the daemon log...
Daemon pid: 7520
  log file: C:\Users\atulk\.gradle\daemon\6.7.1\daemon-7520.out.log
----- Last  20 lines from daemon log file - daemon-7520.out.log -----
##############################

5.* Get more help at https://help.gradle.org

    at makeError (C:\Nodejs_Tricky\Freshser-Project\hikma-health-app\node_modules\execa\index.js:174:9)
    at C:\Nodejs_Tricky\Freshser-Project\hikma-health-app\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\Nodejs_Tricky\Freshser-Project\hikma-health-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:82:7)
    at async Command.handleAction (C:\Nodejs_Tricky\Freshser-Project\hikma-health-app\node_modules\@react-native-community\cli\build\index.js:111:9)

please tell me guys solutions of this issues i have mentioned all required module versions and jdk version
