### ISSUE TITLE
Code Push very slow on 0.70.6 (10s seconds for app launch)

### ISSUE THREAD

**Issue by walterholohan** [microsoft/react-native-code-push#2432]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Upgrade app from 0.69.x to 0.70.6
2. Open app from cold start on release mode
3. App takes more than 10 seconds to load JS bundle

### Expected Behavior
App should take 1-2 seconds to load app

### Actual Behavior
App takes more than 10 seconds before it starts to execute the Javascript in App.ts
```
  STACK TRACE AND/OR SCREENSHOTS
```
### Environment

* react-native-code-push version: 7.0.5
* react-native version: 0.70.6
* iOS/Android/Windows version: iOS 16
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by alihamza1729** [comment]
How did you resolve this ?
