### ISSUE TITLE
[iOS] App Rejection 2 Feb 2023

### ISSUE THREAD

**Issue by iMokhles** [microsoft/react-native-code-push#2434]
Hi all here's the rejection reason i received from apple's review team yesterrday

**Guideline 2.3.1 - Performance**

We discovered that your app contains hidden features.

Specifically, your app still contains CodePush-related remote code downloading/updating support in its main binary and main.jsbundle files. It would be appropriate to remove any and all remote package importing or hot updating functionality from this app, such as this app's [CodePushPackage downloadAndReplaceCurrentBundle:] method, before resubmitting for review.

The next submission of this app may require a longer review time.

**Next Steps**

- Review the Performance section of the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/).

- Ensure your app is compliant with all sections of the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/) and the [Terms & Conditions](https://developer.apple.com/terms/) of the Apple Developer Program.

- Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the [Terms & Conditions](https://developer.apple.com/terms/) of the Apple Developer Program to learn more about our policies regarding termination.

**Guideline 2.5.2 - Performance - Software Requirements**

Your app, extension, or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with [App Store Review Guideline 2.5.2](https://developer.apple.com/app-store/review/guidelines/#software-requirements) and section 3.3.2 of the [Apple Developer Program License Agreement](https://developer.apple.com/terms/).

This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior and/or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

The next submission of this app may require a longer review time.

**Next Steps**

- Review the Software Requirements section of the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/).

- Ensure your app is compliant with all sections of the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/) and the [Terms & Conditions](https://developer.apple.com/terms/) of the Apple Developer Program.

- Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the [Terms & Conditions](https://developer.apple.com/terms/) of the Apple Developer Program to learn more about our policies regarding termination.

 
**iOS App 1.1App Version**

**Rejection Reasons:**

2.3.1 Performance: Accurate Metadata

2.5.2 Performance: Software Requirements

Any updates or solution for this ? keep in mind they needs me to remove this ( [CodePushPackage downloadAndReplaceCurrentBundle:] method ) from the app
......

**Comment by kasterlod** [comment]
hello @iMokhles - quick question, how are you delivering updates? It was pushed before review of new version started or after?

**Comment by ajlee4** [comment]
@iMokhles have you solved this problem?

**Comment by iMokhles** [comment]
any updates ?
