### ISSUE TITLE
Question: How to load multiple JSBundles

### ISSUE THREAD

**Issue by mfbx9da4** [microsoft/react-native-code-push#2441]
I know this is not currently supported but I'm willing to get my hands dirty to make this work. My app has multiple RCTBridges and therefore multiple different `.jsbundle`s. Could a maintainer here point me in the right direction of how I might be able to use code-push to support a multiple bundle setup?

**Comment by zhonglikui** [comment]
I also want to know how to achieve this

**Comment by mfbx9da4** [comment]
Ping
