### ISSUE TITLE
Very slow codepush downloads in UAE resulting in UNKNOWN_ERROR

### ISSUE THREAD

**Issue by kyle-ssg** [microsoft/react-native-code-push#2444]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Attempt to download (9mb) https://codepush.blob.core.windows.net/storagev2/ID

### Expected Behavior
Downloads in a reasonable time 

### Actual Behavior
Takes 3-4 minutes on a 250mb line (in app it times out)

This is making CodePush unusable for people within this region.

I think could be a a general issue with Azure Blob storage, not sure where to raise though.

**Comment by zeusstl** [comment]
Experiencing slow updates everywhere. I am considering only running check updates once a week per user to avoid this. Would much prefer a proper solution than this hack, but haven't been able to find a solution to the slow updates and it really impacts the user's experience to wait 3-20 seconds each time they open their app.

**Comment by AbdulBsit** [comment]
Today I release the update, and experiencing very slow updates/or no updates at all, I tried debugging most of the times it says `Network request failed` even with the perfect internet
```
[CodePush] Network request failed
```
Also we can see on our network monitoring most of the request are failing with appcenter
<img width="924" alt="Screenshot 2023-03-15 at 9 53 33 PM" src="https://user-images.githubusercontent.com/32831612/225375045-a8b909de-dd68-4a30-b1f6-3e47733c534a.png">

**Comment by kyle-ssg** [comment]
In fairness, I've seen updates take <5 seconds in UK. But UAE is definitely very very slow - in our case, we had to fork / increase the download timeout.

https://github.com/SolidStateGroup/react-native-code-push/commit/53f9081301499414d0d1cd20d3079322b1b19663


Also it became clear that we needed to implement a progress handler (in fact thats how we diagnosed the download speed was so slow).

With an additional fork of [reac](https://github.com/zoontek/react-native-bootsplash) we were able to also get around the slow blank screen when it's refreshing.

```

function CodePushStatusDidChange(syncStatus) {
  switch (syncStatus) {
    default:
    case codePush.SyncStatus.DOWNLOADING_PACKAGE:
      updating = true
      rootPush(RouteUrls.AppUpdatingScreen, {}, 'AppUpdating')
      break
    case codePush.SyncStatus.INSTALLING_UPDATE:
      RNBootSplash.show()
      break
    case codePush.SyncStatus.UNKNOWN_ERROR:
      rootPop()
  }
}

function CodepushProgressUpdate: DownloadProgressCallback = (val) => {
    setCodepushProgress({
      percent: parseInt(
        `${((val.receivedBytes || 0) / (val.totalBytes || 1)) * 100}`,
      ),
      ...val,
    })
  }

```


Result: 


https://user-images.githubusercontent.com/8608314/225668907-235e6854-f4d5-412d-844f-4dd033c6a60d.mov

**Comment by AbdulBsit** [comment]
Related Issue
https://github.com/microsoft/react-native-code-push/issues/2456
