### ISSUE TITLE
Vulnerability issue ZipArchive - iOS - Codepush 7.1.0

### ISSUE THREAD

**Issue by ribamarsantos** [microsoft/react-native-code-push#2445]
### Steps to Reproduce
1. Setup React-native-codepush on latest version 7.1.0
2. Veracode / Snyk identified a vulnerability in one of the cocoapods dependecies 
See link
https://github.com/microsoft/react-native-code-push/blob/master/CodePush.podspec#L24
More details in the Lib issues:
https://github.com/ZipArchive/ZipArchive/issues/665

### Expected Behavior
What you expected to happen?
Vulnerability tool pass

### Actual Behavior
What actually happens?
```
Vulnerability tool find possible issues.

https://sca.analysiscenter.veracode.com/vulnerability-database/security/arbitrary-file-write/objective-c/sid-38804
```

### Environment

* react-native-code-push version: 7.1.0
* react-native version: 0.63.0
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by ribamarsantos** [comment]
I believe there is no action item from the Codepush team besides, subscribe or contribute to the dependency lib https://github.com/ZipArchive/ZipArchive/issues/665
Once it is fixed point to the latest version. 

Hope this is helpful.

**Comment by TheSolly** [comment]
This issue was solved according to this [post](https://github.com/ZipArchive/ZipArchive/issues/665#issuecomment-1440991564), could we please bump the version to 2.5.4?
