### ISSUE TITLE
On Android mandatoryInstallMode and minimumBackgroundDuration don't work

### ISSUE THREAD

**Issue by wanderson-ra** [microsoft/react-native-code-push#2446]
### Steps to Reproduce
1. Setup React-native-codepush on latest version 7.1.0
2. Add settings in root app:

```
export default CodePush({
  mandatoryInstallMode: CodePush.InstallMode.ON_NEXT_SUSPEND,
  minimumBackgroundDuration: 30,
  checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME,
})(App);
```

### Expected Behavior
Checking for updates should happen whenever the user goes back into the foreground and mandatory updates should be installed 30 seconds after the user has returned to the background.

### Actual Behavior
Checking for updates happens whenever the user goes back to foreground and stops and mandatory updates are being installed immediately.

![Captura de Tela 2023-02-17 às 16 54 12](https://user-images.githubusercontent.com/7583960/219781244-f37e0f71-c978-48f2-b047-d0cbf9d3eea0.png)

### Environment

* react-native-code-push version: 7.1.0
* react-native version: 0.64.2
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? physical device

Is there something wrong with my settings? On IOS works fine.

**Comment by ah584d** [comment]
Hi I have a similar issue, how did you manage to see the logs in release mode?

**Comment by ajitaro** [comment]
happened in my app too. minimumBackgroundDuration didn't work, app was restarted immediately. Working fine when deployed in appcenter (testing). But sometimes in productions it happens (immediate restart)

**Comment by MikhailSuendukov** [comment]
Hi @wanderson-ra @wanderson-ra 
Could you please confirm what this issue still persist on latest version (8.2.1)
