### ISSUE TITLE
On Android Code Push is Rolled Back on App Restart

### ISSUE THREAD

**Issue by malikzype** [microsoft/react-native-code-push#2449]
I have been using CodePush v7.1.0 with RN 0.70.6 in Android App. Currently, we are facing an issue with CodePush getting rolled back automatically on app restart and it asks the user for a new update every time.

On logging the response returned from CodePush, we observed that failedinstall is true every time we restart the app. Can't figure out why exactly this is been happening. We even tried calling CodePush.notifyAppReady() but no luck.

We are using     CodePush.checkForUpdate() to check if an update is available and then using custom dialog with sync we download and install the code push.

Can anyone guide me, please? Thank you

**Comment by npjoge** [comment]
Even I am facing same issue, please help.

**Comment by dusianandakumar** [comment]
I am getting the same issue on android.
Restarting app
[CodePush] Update did not finish loading the last time, rolling back to a previous version.
[CodePush] Loading JS bundle from "assets://index.android.bundle"
getting this error on android code push update install.

I am using these below versions: 

"react-native": "0.70.5"
"react-native-code-push": "^7.0.5"

**Comment by AlexeyPimenov** [comment]
Had the same issue 
"react-native": "0.65.3",
"react-native-code-push": "^7.1.0",

Solution for me:
Install react-native-restart

And where you call codePush.sync add the following:

`import RNRestart from "react-native-restart";`

`await codePush.sync(
        { installMode: codePush.InstallMode.IMMEDIATE },
        (status) => {
          switch (status) {
            case codePush.SyncStatus.UPDATE_INSTALLED:
              RNRestart.Restart();
              break;
            default:
              break;
          }
        },
        ({ receivedBytes, totalBytes }) => {
          //Something here if needed
        }
      );`

<img width="527" alt="Screenshot 2023-03-15 at 22 37 55" src="https://user-images.githubusercontent.com/101567572/225437062-7816bd6b-cdd6-420b-8b2a-fea128c79978.png">

**Comment by ali-soltanii** [comment]
> Had the same issue "react-native": "0.65.3", "react-native-code-push": "^7.1.0",
> 
> Solution for me: Install react-native-restart
> 
> And where you call codePush.sync add the following:
> 
> `import RNRestart from "react-native-restart";`
> 
> `await codePush.sync( { installMode: codePush.InstallMode.IMMEDIATE }, (status) => { switch (status) { case codePush.SyncStatus.UPDATE_INSTALLED: RNRestart.Restart(); break; default: break; } }, ({ receivedBytes, totalBytes }) => { //Something here if needed } );`
> 
> <img alt="Screenshot 2023-03-15 at 22 37 55" width="527" src="https://user-images.githubusercontent.com/101567572/225437062-7816bd6b-cdd6-420b-8b2a-fea128c79978.png">

this solution worked for me
