### ISSUE TITLE
iOS Linker issue

### ISSUE THREAD

**Issue by avishayil** [Microsoft/react-native-code-push#245]
I switched to the git repository rather than NPM, and now i'm encountering linking error:
````
  "_OBJC_CLASS_$_CodePushErrorUtils", referenced from:
      objc-class-ref in libCodePush.a(CodePushPackage.o)
      objc-class-ref in libCodePush.a(CodePush.o)
````

Probably because of one of the recent commits, issue not happening on 1.8.0-beta (but other issues does).

Any ideas?

**Comment by lostintangent** [comment]
We recently introduced a new file `CodePushErrorUtils.m` that wouldn't be included in the linked Xcode project after upgrading from NPM. You can resolve this by running the following steps:

1. Right-click the `Libraries/CodePush.xcodeproj` node in your project in Xcode, and select `Add Files to "CodePush.xcodeproj"...`
2. Select the `CodePush/CodePushErrorUtils.m` file.
3. Click the `Add` button
4. Re-build your app

Let me know if that works for you!

**Comment by avishayil** [comment]
Thanks, looks this solves the issue.
