### ISSUE TITLE
Multi deployment testing in android does not work when you build "releaseStaging"

### ISSUE THREAD

**Issue by ah584d** [microsoft/react-native-code-push#2450]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. deploy an update on Staging
2. in build.gradle file define a build type "releaseStaging" as shown in doc (https://github.com/microsoft/react-native-code-push/blob/master/docs/multi-deployment-testing-android.md)
3. no matter which update strategy you use, the update will never been downloaded by the application
4. if you build your application with "release" and use the Staging key value, them the app will download the update from Staging

### Expected Behavior
The app you be able to download the update when built with "releaseStaging"

### Actual Behavior
it works only with "release", no matter if we use Staging or Production key

### Environment

* react-native-code-push version: 7.1.0
* react-native version: 0.64.4
* iOS/Android/Windows version: Android 11
* Does this reproduce on a debug build or release build? releaseStaging
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)
these are my build types:

```
buildTypes {
        debug {
            signingConfig signingConfigs.debug
            resValue "string", "CodePushDeploymentKey", ""
        }
        releaseStaging {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            resValue "string", "CodePushDeploymentKey", '"my_staging_key"'
            matchingFallbacks = ['release']
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            resValue "string", "CodePushDeploymentKey", '"my_staging_key"'
        }
    }
```

**Comment by namhbnam** [comment]
same

**Comment by OHHAKO** [comment]
same. i got this error when react-native run-android --variant=staging. 
@ah584d  anything error in your local build?

```
Error: Command failed: ./gradlew app:installStaging -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installStaging' not found in project ':app'.
```

**Comment by OHHAKO** [comment]
@ah584d  i guess maybe you missed signingConfig in releaseStaging block. can you try it?

**Comment by ah584d** [comment]
No it is not related, I don't use 'signingConfig' for release and it works in release.
As you can see I use signingConfig for debug only.
My releaseStaging and release are 100% identical, only the key is different.
I feel that somewhere in codepush code they search for string "release" with exact match, that's why releaseStaging does not work.

```
signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            resValue "string", "CodePushDeploymentKey", ""
        }
      releaseStaging {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            resValue "string", "CodePushDeploymentKey", '************'
            matchingFallbacks = ['release']
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            resValue "string", "CodePushDeploymentKey", "********"
        }
```

**Comment by OHHAKO** [comment]
today I spent time all day to solve this problem.
just tested code below and now it works. 🎉 
- remove releaseStaging in buildTypes block
- just use flavorDimensions & productFlavors

app/build.gradle:
```
    ...
 
    // 1. i have 2 build types (debug, release)
    buildTypes {
        debug {
            ...
        }

        release {
          ...
        }
    }

    // 2. add flavorDimensions
    flavorDimensions "version"

    // 3. add each resValue you need to in productFlavors block.
    productFlavors {

        // 3-1. debug with no key
        development {
            resValue "string", "CodePushDeploymentKey", ""
        }

        // 3-2 . release with codepush production key
        production {
            resValue "string", "CodePushDeploymentKey", '"<CODE_PUSH_PRODUCTION_TRACK_KEY>"'
        }

        // 3-3 . release with codepush staging key
        staging {
            resValue "string", "CodePushDeploymentKey", '"<CODE_PUSH_STAGING_TRACK_KEY>"'
        }
    }
```

4. you can use three commands options
```vim
$ npx react-native run-android --variant=developmentDebug  // match with 3-1
$ npx react-native run-android --variant=productionRelease // match with 3-2
$ npx react-native run-android --variant=stagingRelease // match with 3-3
```

**Comment by OHHAKO** [comment]
I don't know why your update will never been downloaded by the application.

i had problem that additional build type didn't work. maybe it's different problem with yours.
today I spent time all day solving this problem.
just tested code below and now it works. I hope it helps you.

- remove releaseStaging in buildTypes block
- just use flavorDimensions & productFlavors

app/build.gradle:
```
    ...
 
    // 1. i have 2 build types (debug, release)
    buildTypes {
        debug {
            ...
        }

        release {
          ...
        }
    }

    // 2. add flavorDimensions
    flavorDimensions "version"

    // 3. add each resValue you need to in productFlavors block.
    productFlavors {

        // 3-1. debug with no key
        development {
            resValue "string", "CodePushDeploymentKey", ""
        }

        // 3-2 . release with codepush production key
        production {
            resValue "string", "CodePushDeploymentKey", '"<CODE_PUSH_PRODUCTION_TRACK_KEY>"'
        }

        // 3-3 . release with codepush staging key
        staging {
            resValue "string", "CodePushDeploymentKey", '"<CODE_PUSH_STAGING_TRACK_KEY>"'
        }
    }
```

4. you can use three commands options
```vim
$ npx react-native run-android --variant=developmentDebug  // match with 3-1
$ npx react-native run-android --variant=productionRelease // match with 3-2
$ npx react-native run-android --variant=stagingRelease // match with 3-3
```

**Comment by ah584d** [comment]
@OHHAKO thanks. - it did the job :-)
now when I build a signed apk through android studio it generates me an apk for each flavor - 
G. Bless You 💯

**Comment by Ayan4** [comment]
@OHHAKO Thank you so much ! it works like charm.
