### ISSUE TITLE
App fails to open with react native 0.71.3 version with code push

### ISSUE THREAD

**Issue by vineelk8** [Microsoft/react-native-code-push#2454]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Create a react-native latest version base project with version 0.71.3
2. Add react-native-code-push package with version 7.1.0 and follow the steps provided in the docs
3. Run the app, and build successfully but failed to open the app

### Expected Behavior
The app should work fine without any issue

### Actual Behavior
After running the app, build successfully but failed to open the app

If I remove the below code from android/app/build.gradle, the app works fine but code push will not work
```
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
```

And if I make hermes false in gradle.properties then the app works fine and code push also works fine
```
hermesEnabled=false
```

Please provide a fix for this and also update the example folder with the latest react native version working project

### Environment

* react-native-code-push version: 7.1.0
* react-native version: 0.71.3
* Reproducible on both debug build or release build
* Reproducible on a simulator and on a physical device as well

**Comment by NSShentu** [comment]
Facing the same issue.

**Comment by eumaninho54** [comment]
Here it's same error, something to fix?

**Comment by huuthanit** [comment]
Any update? I have the same issue

**Comment by vjerryv** [comment]
same

**Comment by blwinters** [comment]
I believe I'm seeing the same issue, though my project is using RN 0.69.5.

**Comment by NguyenHoangMinhkkkk** [comment]
- i created a project for reproducing this crash of *java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so*
-  hope it help here to debug this crash.

**Step reproduce:

- Init project: npx react-native init Test0714

- android/gradle.properties ->  newArchEnabled true

- add @react-native-firebase/app

- register firebase console -> add google-services.json (packageName: "com.test0714") to dir: /android/app

- rnfirebase docs: => cd android && ./gradlew signingReport

- add "classpath 'com.google.gms:google-services:4.3.15'" into dir: /android/build.gradle

- Lastly, execute the plugin by adding the following to your /android/app/build.gradle file:
      ->apply plugin: 'com.google.gms.google-services' // <- Add this line

- In File: /android/app/build.gradle 
    => add these lines: "multiDexEnabled true" and "implementation 'androidx.multidex:multidex:2.0.1'"

- yarn add @react-native-firebase/messaging

- yarn add @react-native-firebase/crashlytics
  - android/build.gradle add line: "classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.4'"
  - android/app/build.gradle add line:  "apply plugin: 'com.google.firebase.crashlytics'"

// run-android here working fine.

\/ \/ \/ \/ \/ \/ \/ \/
// Crash after do these things with react-native-code-push
// adb logcat ==> java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so

- yarn add react-native-code-push
  - android/setting.gradle:
      include ':app', ':react-native-code-push'
      project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
  - android/app/build.gradle
      apply from: "../../node_modules/react-native/react.gradle"
      apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
  - update MainApplication.java
      // 1. Import the plugin class.
      import com.microsoft.codepush.react.CodePush;

      //
      @Override
      protected String getJSBundleFile() {
          return CodePush.getJSBundleFile();
      }

- Run build: npx react-native run-android**

https://github.com/NguyenHoangMinhkkkk/reproduce-0714-crash

**Comment by rlopeslameira** [comment]
vejam https://github.com/microsoft/react-native-code-push/issues/2418#issuecomment-1436132060
