### ISSUE TITLE
Sync slows down at certain times every day these days.

### ISSUE THREAD

**Issue by minyoung-jun** [microsoft/react-native-code-push#2456]
### Steps to Reproduce
1. UTC 13:00 ~ 15:00 Occurs
2. CodePush.sync slow down (Synchronization takes more than a minute)
3. At that time, many users suffer.

### Expected Behavior
Fast sync (less than 3 seconds)

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.64.4
* iOS/Android/Windows version: iOS/Android
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Physical Device

**Comment by alexdr00** [comment]
+1 I can confirm. This has happened to me as well.

**Comment by HwangYoonSeong** [comment]
me too

**Comment by wkdgudcjf** [comment]
Me too.
The app was running very slowly because the checkForUpdate method was unresponsive.
Can't we timeout the checkForUpdate method?

**Comment by zereight** [comment]
Me too, same problem happening around the same time

**Comment by zeusstl** [comment]
I would recommend to everyone to please leave a comment here

And also...

To please log into appcenter codepush and let them know that this is an ongoing issue that has gotten worse and worse.

**Comment by kyle-ssg** [comment]
Hmm this is really worrying to see. Starting to wonder forking CodePush to upload/download to a different CDN might be an idea.

**Comment by SoohyungJung** [comment]
I'm also facing the same issue 🥲

**Comment by goguda** [comment]
Just started getting a full on 500 Internal Server Error here...

**Comment by alexdr00** [comment]
It seems it's working smoothly now. However, considering the instability CodePush servers might suffer from time to time, we created a workaround so we don't leave the users waiting for too long in case this happens again. The tradeoff is that the user will not see the update applied right away, but at least we won't leave it waiting in the loading screen.

The workaround is basically this: Check for update, install update immediately. If it takes too long (more than 4 seconds), go beyond loading screen and install update silently in the background.

This workaround implements the timeout solution mentioned in the [comment above](https://github.com/microsoft/react-native-code-push/issues/2456#issuecomment-1472251986) and it also combines it with a silent update.

I created a [gist](https://gist.github.com/alexdr00/5599f9e1cca423027804f7a21e4cdd1d) for this workaround if you are interested.

I put all the update logic inside a hook called "useCodePushSetup". The most important part to see here is the function "checkUpdates". It first executes CodePush.checkForUpdate with a timeout of 4 seconds; If it takes longer than 4 seconds then it throws the "timeout" error. Inside the catch, it updates the state and marks the app as ready (allowing the user to go beyond the loading screen) and it also executes CodePush.sync with installMode set to ON_NEXT_RESUME which starts a silent update. Thanks to the silent update the user won't notice any delay in the CodePush servers.

**Comment by mym0404** [comment]
The same issue, we suffer almost 10k 500 check_update error responses in a day.
There are possible options to resolve this.

1. Official Self hosted bundle server
2. Paid plan for stable service

**Comment by MasonLe2497** [comment]
same +1

**Comment by gourav-singhal** [comment]
+1

**Comment by minyoung-jun** [comment]
Fortunately, it doesn't seem to happen in recent days.
Has anyone experienced this in the last 2 days?

**Comment by luzhanyi** [comment]
+1

**Comment by minyoung-jun** [comment]
Currently, this issue appears to be resolved.
The cause was unknown.
I'll close the issue for now, and open it when it happens again.

**Comment by minyoung-jun** [comment]
@luzhanyi 
Has this problem happened to you again?

**Comment by zeusstl** [comment]
The issue is back. Stuck in check updating to the point where the app doesn't even load

Please see my comment from earlier to let them know that the issue is back.

> I would recommend to everyone to please leave a comment here
> 
> And also...
> 
> To please log into appcenter codepush and let them know that this is an ongoing issue that has gotten worse and worse.
> 
> There is a "?" on the top right of the codepush dashboard, where you can send a support request.

**Comment by goguda** [comment]
Yup, happening again...

**Comment by minyoung-jun** [comment]
The issue reopened😢

**Comment by zeusstl** [comment]
This issue should not be closed.

Extreme latency on a service that is the first thing a user sees is a nightmare.

The fact that in the US user this morning had to wait upwards of 2 minutes for codepush to finish loading and outside the US is was dramatically worse - not even loading in some cases - is a gigantic problem.

Somehow, this dramatic event is not even noted on the status page:
https://status.appcenter.ms/

**Comment by zeusstl** [comment]
Good point. Good to know that they are actively monitoring it. I'm guessing that the fix yesterday did not work, but it's good to know there is activity towards a resolution.

**Comment by mym0404** [comment]
I wouldn' t run my service with unstable server. So I did customized all package related codepush(even app center cli) and upload bundle to my backend. It works

**Comment by zeusstl** [comment]
Codepush is completely dead right now. Nothing loads!

**Comment by mym0404** [comment]
I implemented self hosted and it works. super fast (30mb/sec)

**Comment by goguda** [comment]
> I implemented self hosted and it works. super fast (30mb/sec)

How did you implement self-hosted? Did you have to manually reverse-engineer the node endpoints or is the source available somewhere I'm not aware of?

**Comment by goguda** [comment]
Intermittent 500 errors again preventing full load. Got to do something on our end for now, this isn't fair to our userbase...

**Comment by goguda** [comment]
So, I've been observing the times of this behaviour, and it does seem to be the worst around the times OP states (13:00 ~ 15:00 UTC). In my observations I'd almost say 11:00 ~ 15:00 UTC, but time of day does definitely seem to be an important factor in causing the issue.

After 15:00 the service seems to operate normally. Very strange issue.

**Comment by Ahmadin29** [comment]
+1

**Comment by pierroo** [comment]
Random question but, would all of this happen if we use the default CodePush configurations where it:
- check if there is an update (in background by default I think)
- launch the app regardless
- if there is an update, download it in background (no loading screen etc)
- only install it upon next launch, which should take almost time and no longer relies on remote fetching

I may be wrong but I feel like all the above is happening because you force a download & install right away when it detects an update, and force a checking screen while it searches for said update?

(asking these since i am considering using codepush from now on but this scares me)

**Comment by goguda** [comment]
> 

You should be fine if you're using it this way, it's checking for an update before the app loads that it causing the issue for people.

**Comment by goguda** [comment]
> Random question but, would all of this happen if we use the default CodePush configurations where it:
> 
>     * check if there is an update (in background by default I think)
> 
>     * launch the app regardless
> 
>     * if there is an update, download it in background (no loading screen etc)
> 
>     * only install it upon next launch, which should take almost time and no longer relies on remote fetching
> 
> 
> I may be wrong but I feel like all the above is happening because you force a download & install right away when it detects an update, and force a checking screen while it searches for said update?
> 
> (asking these since i am considering using codepush from now on but this scares me)

You should be fine if you're using it this way, it's checking for an update before the app loads that it causing the issue for people.

**Comment by goguda** [comment]
> thank you so much @goguda .
> 
> So that confirms that by default codepush will NOT block the app while checking for an update? (nor slow it down while waiting for a response if it ever takes too long as mentioned above?)

Correct
