### ISSUE TITLE
CodePush server downed and can not get clear code

### ISSUE THREAD

**Issue by hanzoow** [microsoft/react-native-code-push#2461]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

Currently my application using sync function to check and load code push. I catch status return by syncStatusChangedCallback then if it returned `CodePush.SyncStatus.UNKNOWN_ERROR:` i will alert to force user reload app to install code push (because sometimes user switch to another app and then back to my app, if i'm not implement that checking, it will rollback to old version).

But lately i saw that Code-Push server down several times and by my check it will alert and users could not use app anymore, that annoy!.

I want to know that if your server is down, like return code 500, can you gimme some solution to catch that code to skip alert to force user reload app in my case ?

### Steps to Reproduce
1. Fully installed code push
2. Code push version downed with error code 500

### Expected Behavior
What you expected to happen?
Need to now your model return if your server downed

### Actual Behavior
What actually happens?
it runs on `CodePush.SyncStatus.UNKNOWN_ERROR:` without any clear model
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Your server is down

### Environment

* react-native-code-push version: ^6.2.1
* react-native version: "0.63.2",
* iOS/Android/Windows version: any version
* Does this reproduce on a debug build or release build? bold debug and release
* Does this reproduce on a simulator, or only on a physical device? bold real device and simulator devices

(The more info the faster we will be able to address it!)

**Comment by minyoung-jun** [comment]
#2456 
This appears to be a similar situation to this issue.
