### ISSUE TITLE
8.0.0 is not yet published on npm

### ISSUE THREAD

**Issue by thespacemanatee** [microsoft/react-native-code-push#2468]
### Steps to Reproduce
1. `yarn add react-native-code-push`
2. `"react-native-code-push": "^7.1.0"` in `package.json`

### Expected Behavior

`yarn add react-native-code-push` installs `v8.0.0`

### Actual Behavior

`yarn add react-native-code-push` installs `v7.1.0`

### Reproducible Demo

`yarn add react-native-code-push`

### Environment

* react-native-code-push version: 8.0.0
* react-native version: 0.71.4

**Comment by Natanaelvich** [comment]
+1

**Comment by hengkx** [comment]
+1

**Comment by ducpt-bili** [comment]
+1

**Comment by thespacemanatee** [comment]
It's out!
