### ISSUE TITLE
No signature of method: java.util.ArrayList.get() is applicable for argument types: () values: []

### ISSUE THREAD

**Issue by jvgeee** [microsoft/react-native-code-push#2470]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

Getting this error when running Android build (in Android Studio) on the latest version of RN Codepush (8.0.0)

```
Script './node_modules/react-native-code-push/android/codepush.gradle' line: 6

* What went wrong:
A problem occurred evaluating script.
> No signature of method: java.util.ArrayList.get() is applicable for argument types: () values: []
  Possible solutions: get(int), get(int), set(int, java.lang.Object), set(int, java.lang.Object), grep(), grep()

```

Works fine on V7, assume that either the docs need to be upgraded for v8 or there's a bug somewhere

**Comment by anhquan291** [comment]
I'm facing the same issue !

**Comment by purevsurena** [comment]
This error occurred on the react-native v0.70.4. Problem was here this line. `apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"`

**Comment by bmaluff** [comment]
> Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
> 
> Getting this error when running Android build (in Android Studio) on the latest version of RN Codepush (8.0.0)
> 
> ```
> Script './node_modules/react-native-code-push/android/codepush.gradle' line: 6
> 
> * What went wrong:
> A problem occurred evaluating script.
> > No signature of method: java.util.ArrayList.get() is applicable for argument types: () values: []
>   Possible solutions: get(int), get(int), set(int, java.lang.Object), set(int, java.lang.Object), grep(), grep()
> ```
> 
> Works fine on V7, assume that either the docs need to be upgraded for v8 or there's a bug somewhere

The line 6 in codepush.gradle should return a map, and is returning an ArrayList which doesn't support **get()** method

**Comment by malikzype** [comment]
Facing same issue

**Comment by Omaressam9500** [comment]
I am facing same error

**Comment by malikzype** [comment]
@vlack-coder  Yes downgrading to v7 works fine

**Comment by blueberry6401** [comment]
v8 only works with react-native 0.71. Nothing is mentioned in the docs.

**Comment by AnYuku** [comment]
i work on react native version 0.66, codepush version 8.0.0 and got this issue too.

**Comment by RoyalBosS-Ayush** [comment]
Any update? Facing same on rn 0.68.0

**Comment by shahanshah-cutshort** [comment]
Downgrading to 7..0.0 with RN 0.70.5 is working.

**Comment by nassimmiled** [comment]
same

**Comment by AnYuku** [comment]
Hello. I have solved this issue by doing the following:
![image](https://user-images.githubusercontent.com/91923556/231347206-960d1841-3fe7-4129-ae10-a165dd41e2e9.png)
In this step,  find the first line then insert the second line. The first line is already there. I copied 2 line so first line is already there so cause error
![image](https://user-images.githubusercontent.com/91923556/231347435-93786ad0-958a-44dd-9e6a-ac78915a92d3.png)
In this step, delete include ':app' then copy paste this code to there.
![image](https://user-images.githubusercontent.com/91923556/231347640-3d12dbba-4099-469e-82cd-ae9049b139f5.png)
This step insert library then find ReactNativeHost  then insert this code:

@Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
 
 
![image](https://user-images.githubusercontent.com/91923556/231347795-f77020a5-6418-4712-a946-61d3945783f6.png)
In this step, DeploymentKey can be get on web appcenter or use command appcenter codepush deployment list -a <ownerName>/<appName> -k

so i have ownerName like nguyenquocan and app name like testApp
i will have this command:
appcenter codepush deployment list -a nguyenquuocan/testApp -k
if you have @gmail.com at the end owner name
-> appcenter codepush deployment list -a nguyenquocan-gmail.com/testApp -k
I hope this will be useful.

**Comment by RyanPliske** [comment]
same with RN 0.70.5

**Comment by taongocsontam** [comment]
I'm find resolve here: #2471

**Comment by prashantsoni-ai** [comment]
For anyone who is still facing the issue. follow these steps with library "react-native-code-push": "^7.0.1" , "react-native": "0.70.5" 
Codepush - appcenter - OTA - Autoupdate
Install library - react-native-code-push


Install appcenter CLI - npm install -g appcenter-cli


`Login to app center - appcenter login`


Create a new app - `appcenter apps create -d <AppName> -o <OS> -p React-Native`

 PS: Replace app name and os to your requirements.


Create Production and Staging keys using -

 ```
appcenter codepush deployment add -a <ownerName>/<appName> Production

 appcenter codepush deployment add -a <ownerName>/<appName> Staging

```
 PS: Replace ownerName and appName to your ownerName and appName


Once the app is set up, verify it with the appcenter.


Changes in React Native codebase.
//Add this code to MainApplication.java
```
import com.microsoft.codepush.react.CodePush;  //import this library
@Override //Add this code to the ReactNativeHost function. 
protected String getJSBundleFile() {
	return CodePush.getJSBundleFile();
}
```


`<string moduleConfig="true" name="CodePushDeploymentKey">ProductionKey</string>`
PS: Replace the production key to you production/staging keys obtained in step 5


`apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"`


```
include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app') 
```
PS: Dont enter the above code in the If block. 


PS: this code creates a codepush wrapper class and we wrap the App component in this class

```
import codePush from "react-native-code-push"; 
const codePushOptions = { 
checkFrequency: codePush.CheckFrequency.ON_APP_RESUME, 
installMode: codePush.InstallMode.IMMEDIATE,
};


export default App = codePush(codePushOptions)(App);
```

Once all of the above steps are completed, run the following command to create the deployment.
`appcenter codepush deployment create -a <app_name> -d <deployment_name>`

And run the following command to update your deployment.

`appcenter codepush release-react -a <app_name> -d <deployment_name>`

PS: Replace the app_name and deployment_name to your app’s name and Staging/Production respectively.


Note: Codepush might have some issues with some versions of ReactNative So make sure you have “react-native-code-push” → “7.0.1” if using “react-native" → “^0.70.0”
References → [Auto Update](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-android.md)``

**Comment by Azhar456** [comment]
i solved this solved issue 

"react-native": "0.68.2",
"react-native-code-push": "8.0.1",

I didn't import the import com.microsoft.codepush.react.CodePush;
in MainApplication.java

Note! You might have the following error.

Cannot add task 'bundleDebugJsAndAssets' as a task with that name already exists.
Please double-check whether you have a duplicate code in root/android/app/build.gradle .

**Comment by savaskalkan** [comment]
I solved this guys.
I just downgrade codepush version from 8.0.1 to 7.0.4
There is an issue that needs to be fixed by codepush team

**Comment by harish92** [comment]
+1 I'm also facing same issue.

**Comment by Azhar456** [comment]
> +1 I'm also facing same issue.

please recheck the if you follow all the steps correctly or not

**Comment by harish92** [comment]
yes followed all the steps still facing same issue.

**Comment by Azhar456** [comment]
> yes followed all the steps still facing same issue.

show your code or

**Comment by FrontendTerminator** [comment]
Just got the same error. But I solved it by downgrading from 8.0.1 to 7.0.1 code push version.
My react native version 0.64.4

**Comment by jvgeee** [comment]
Upgraded React Native to 0.71.4 and V8 of rn-code-push no longer causes this error in Android. 

If you're on an earlier version of React Native, the solution is to use v7 of this plugin, e.g. `yarn add react-native-code-push@7`.

**Comment by locht** [comment]
downgrade v7.0.4 working for me

**Comment by MateusAndrade** [comment]
Same issue with: 

```
        "react-native": "^0.72.0",
        "react-native-code-push": "^8.0.2",
```

**Comment by jesus-castro3** [comment]
For anyone reading this, fyi `react-native-code-push` v8.0.0+ is **incompatible with versions 0.65-0.70+** , took me a while to figure that out. Either you upgrade to RN 71 to use codepush v8 or you still with v7 for now.

**Comment by kigh143** [comment]
Downgrading helped me  but then faced this error :  The CodePush module doesn't appear to be properly installed.

**Comment by vanqui123** [comment]
use patch package and change codepush.gradle
diff --git a/node_modules/react-native-code-push/android/codepush.gradle b/node_modules/react-native-code-push/android/codepush.gradle
index 4faf49f..72df030 100644
--- a/node_modules/react-native-code-push/android/codepush.gradle
+++ b/node_modules/react-native-code-push/android/codepush.gradle
@@ -3,7 +3,7 @@
 import java.nio.file.Paths;
 
 def config = project.extensions.findByName("react") ?: []
-def bundleAssetName = config.bundleAssetName.get() ?: "index.android.bundle"
+def bundleAssetName = config.bundleAssetName ? config.bundleAssetName.get(): "index.android.bundle"
 
 // because elvis operator
 def elvisFile(thing) {
@@ -24,7 +24,7 @@ android.buildTypes.each { buildType ->
 }
 
 gradle.projectsEvaluated {
-    def debuggableVariants = config.debuggableVariants.get() ?: ['debug']
+    def debuggableVariants = config.debuggableVariants ?config.debuggableVariants.get(): ['debug']
 
     android.applicationVariants.all { variant ->
         // No code push for debuggable variants
@@ -49,8 +49,8 @@ gradle.projectsEvaluated {
         def jsBundleFile;
 
         // Additional node commandline arguments
-        def nodeExecutableAndArgs = config.nodeExecutableAndArgs.get() ?: ["node"]
-        def extraPackagerArgs = config.extraPackagerArgs.get() ?: []
+        def nodeExecutableAndArgs = config.nodeExecutableAndArg?  config.nodeExecutableAndArgs.get(): ["node"]
+        def extraPackagerArgs = config.extraPackagerArgs ?config.extraPackagerArgs.get(): []
 
         // Make this task run right after the bundle task
         def generateBundledResourcesHash;
@@ -60,9 +60,8 @@ gradle.projectsEvaluated {
             jsBundleDir = reactBundleTask.property('jsBundleDir').asFile.get()
             resourcesDir = reactBundleTask.property('resourcesDir').asFile.get()
             
-            jsBundleDir.mkdirs()
+             jsBundleDir.mkdirs()
             resourcesDir.mkdirs()
-
             jsBundleFile = file("$jsBundleDir/$bundleAssetName")
 
             generateBundledResourcesHash = tasks.create(
@@ -77,18 +76,18 @@ gradle.projectsEvaluated {
             runBefore("merge${targetName}Assets", generateBundledResourcesHash)
         } else {
             def jsBundleDirConfigName = "jsBundleDir${targetName}"
-            jsBundleDir = elvisFile(config."$jsBundleDirConfigName").get() ?:
+            jsBundleDir = elvisFile(config."$jsBundleDirConfigName") ?elvisFile(config."$jsBundleDirConfigName").get():
                     file("$buildDir/intermediates/assets/${targetPath}")
 
             def resourcesDirConfigName = "resourcesDir${targetName}"
-            resourcesDir = elvisFile(config."${resourcesDirConfigName}").get() ?:
+            resourcesDir = elvisFile(config."${resourcesDirConfigName}") ?: elvisFile(config."${resourcesDirConfigName}").get()
                     file("$buildDir/intermediates/res/merged/${targetPath}")
 
             // In case version of 'Android Plugin for Gradle'' is lower than 1.3.0
             // '$buildDir' has slightly different structure - 'merged' folder
             // does not exists so '${targetPath}' folder contains directly in 'res' folder.
             if (!resourcesDir.exists() && file("$buildDir/intermediates/res/${targetPath}").exists()) {
-                resourcesDir = file("$buildDir/intermediates/res/${targetPath}")
+resourcesDir = file("$buildDir/intermediates/res/${targetPath}")
             }
 
             jsBundleFile = file("$jsBundleDir/$bundleAssetName")

**Comment by vanqui123** [comment]
use patch package and change codepush.gradle

[react-native-code-push+8.2.2.patch](https://github.com/microsoft/react-native-code-push/files/15399211/react-native-code-push%2B8.2.2.patch)
