### ISSUE TITLE
Failed to release a CodePush update.

### ISSUE THREAD

**Issue by jaiprakashPal** [microsoft/react-native-code-push#2473]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

**Steps to Reproduce**
In terminal, i exec appcenter codepush release-react -a xxxxxxxx/xxxxxxxx-Android -d Staging

**Expected Behavior**
What you expected to happen?
Success in generating the release

**Actual Behavior**
info Done writing bundle output
info Copying 220 asset files
info Done copying assets
Error: Failed to release a CodePush update.

**Environment**

- react-native-code-push version: ^8.0.0
- react-native version: 0.71.3
- iOS/Android/Windows version: Android v11 and v12
- Does this reproduce on a debug build or release build? Both
- Does this reproduce on a simulator, or only on a physical device? simulator, but maybe this is not the case

 (The more info the faster we will be able to address it!)

**Comment by psyrenpark** [comment]
me too.

**Comment by Phong-TH** [comment]
Same here! The error occurred when checking the new version. Always receive 500 or 404 status code in the appcenter distribute list.

**Comment by numandev1** [comment]
@bruscantini getting same issue, how did you solve it?

**Comment by sabihaDrmz** [comment]
I'm having this problem. How did you solve it? @bruscantini

**Comment by bruscantini** [comment]
@numandev1 @sabihaDrmz  I can't remember. But I've since moved on to using EAS Update, instead. CodePush is getting sunset soon.
