### ISSUE TITLE
Code push for iOS works fine but not Android

### ISSUE THREAD

**Issue by vunguyendhSTS** [microsoft/react-native-code-push#2476]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. This morning try to deploy new code push version
2. run both script for iOS and Android deployment
3. iOS passed but Android throw internal server error or some SSL connection error

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: ^6.2.1
* react-native version: 0.63.2
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by maman** [comment]
seeing similiar errors on our build too. The stacktrace is something like this:

```sh
Error: Error: write EPROTO 139978279597952:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1563:SSL alert number 80
```

but in our case, the issue is on the ios bundle upload. Android is fine.

Our team also found that [appcenter is now still had some issues](https://status.appcenter.ms), could this be related? 

<small>(screenshot for history purpose)</small>
<img width="917" alt="image" src="https://user-images.githubusercontent.com/491458/229741826-fdc52a13-3d6f-477b-8de4-5dc296454d25.png">

**Comment by Garguy** [comment]
Having similar issue. Working fine on iOS but Android is failing. Device tries to download the update and just rollback on its own then CodePush is crashing app on restart.

`FATAL EXCEPTION: main
                                                                                                    Process: com.chrobinson.navispherecarrier.dev, PID: 30865
                                                                                                    java.lang.AssertionError: recreateReactContextInBackground should only be called after the initial createReactContextInBackground call.
                                                                                                    	at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:88)
                                                                                                    	at com.facebook.react.ReactInstanceManager.recreateReactContextInBackground(ReactInstanceManager.java:436)
                                                                                                    	at com.microsoft.codepush.react.CodePushNativeModule$2.run(CodePushNativeModule.java:156)`

**Comment by Garguy** [comment]
Any luck from anyone on this? Still having issues where the push goes out and Android just auto rolls back after trying to update.

**Comment by grid-dres** [comment]
Having this issue now but with android working fine but not ios.

**Comment by pierroo** [comment]
That issue is kinda scary; does that mean CodePush can actually crashes the app when they are down or something?

**Comment by jignesh-joshi** [comment]
I am facing the same issue is there any solution for it?
