### ISSUE TITLE
CodePush.sync() always returns status UP_TO_DATE when download_url is https://codepush-secondary.blob.core.windows.net

### ISSUE THREAD

**Issue by blueberry6401** [microsoft/react-native-code-push#2480]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
It happens 3 out of 5 times when pushing a new code push update.
Sometimes CodePush check for update response the `download_url` from `https://codepush-secondary.blob.core.windows.net`, the issue happens. if the download_url returns `https://codepush.blob.core.windows.net/`, it works fine.

1. Upon inspect, I see there is an API that checks for update being called:
`https://codepush.appcenter.ms/v0.1/public/codepush/update_check`

Response
```json
{
  "update_info": {
    "download_url": "https://codepush-secondary.blob.core.windows.net/storagev2/.....", // Pay attention to this one
    "description": "super secret description",
    "is_available": true,
    "is_disabled": false,
    "target_binary_range": "2.11.0",
    "package_hash": "xxxxxxxxxx",
    "label": "v1638",
    "package_size": 13173559,
    "update_app_version": false,
    "should_run_binary_version": false,
    "is_mandatory": false
  }
}
```

2. Status returned from CodePush.sync is wrong
```js
CodePush.sync({}, status => console.log(status));
```
If the `download_url` is from `https://codepush.blob.core.windows.net`, status is correct (DOWNLOADING_PACKAGE and so on). But when the url is `https://codepush-secondary.blob.core.windows.net`, status is UP_TO_DATE immediately while there is a newer version (there is actually a newer version and the `update_check` API said that too).

### Actual Behavior
Yeah it should update.

### Reproducible Demo
No

### Environment

* react-native-code-push version: 7.x; I don't use 8 beacause of this https://github.com/microsoft/react-native-code-push/issues/2470
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by blueberry6401** [comment]
UPDATE: it's not because of the url. Seems like the reason is update is rolled back. But no idea why this happens.
I constantly see that my rollback rate is about 10-15%, why don't have any app crash. I'll dig into this deeper.

**Comment by blueberry6401** [comment]
I have no idea why this happens. My app check for update when app start. When I build & push new update, I swipe out the app and open it again to let it check for update. And this happens, tell me there's rollback issue, which is not even happen.
In the meantime I will patch the shouldUpdateBeIgnored to return false when latestRollbackInfo is null. But still don't know I'm doing, and I don't need I should spend more time on this case. It's great if someone from the team can tell me what this is.

**Comment by blueberry6401** [comment]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/7337535/230399025-9801c4fc-0631-4cc6-a261-b9890fbdb5cb.png">

The bundle is 404 and only available after some minutes.

**Comment by 592da** [comment]
Happens for me too on production with customers after updating to version 8...
someone found a solution?

**Comment by judeProground** [comment]
+1 

Getting related error from `checkForUpdate()`. 
Thrown error has nothing but `https://codepush-secondary.blob.core.windows.net/storagev2/<...bundle_identifier>` message.

**Comment by BalochPalwisha** [comment]
I am also facing the same issue. Did someone find a solution?

**Comment by anhnguyen123** [comment]
me too

**Comment by renopp** [comment]
Also facing the same issue +1
