### ISSUE TITLE
iOS App update fails when user puts app in background

### ISSUE THREAD

**Issue by floriniordache12** [microsoft/react-native-code-push#2486]
### Steps to Reproduce
1. Create codepush update for ios app
2. Open iOS app and receive codepush dialog
3. Click install button 
4. **While codepush download is in progress, move app into background (not close it, just put it in background)**
5. When coming back to the app, it is in same state and when re-opening app the update dialog appears again

### Expected Behavior
App update continues while iOS app is in background.

### Actual Behavior

**App update fails when iOS app is in background.**

After some digging into codepush state, it seems like codepush reaches the `CodePush.SyncStatus.UNKNOWN_ERROR` state. The error is thrown by native ios code and its message is 'The network connection was lost.'
Stacktrace is:

```
  message: 'The network connection was lost.',
  domain: 'NSURLErrorDomain',
  userInfo: {
    NSUnderlyingError: {
      code: '-1005',
      message: 'underlying error',
      domain: 'kCFErrorDomainCFNetwork',
      userInfo: {
        NSLocalizedDescription: 'The network connection was lost.',
        NSErrorFailingURLStringKey:
          '<codepush_blob_link>',
        _kCFStreamErrorCodeKey: 53,
        NSErrorPeerAddressKey: null,
        NSErrorFailingURLKey: null,
        _kCFStreamErrorDomainKey: 1,
      },
      nativeStackIOS: [
       ...
        '3   AppName                             0x00000001048bd1fc __60-[CodePush downloadUpdate:notifyProgress:resolver:rejecter:]_block_invoke.97 + 272',
        '4   AppName                             0x00000001048c012c -[CodePushDownloadHandler connection:didFailWithError:] + 152',
        '5   CFNetwork                           0x00000001a0d9ab10 __CFTubeSetTubeTypeNotifier + 71768',
        ... 
      ],
    }
```

Because it gets into error state, the update does not finish successfully and when restarting the app the process starts again.
Another note: while app is in background, the download stops and nothing is downloaded anymore.

### Environment

* react-native-code-push version:8.0.0 (but also happens on all 7.* versions)
* react-native version: 0.69.7 (but also happens on 0.68)
* iOS/Android/Windows version: ios 16.2 (but also happend on 15). Did not have this issue on Android.
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

Let me know what other info I should provide. Thank you!

**Comment by from74** [comment]
+1 Same issue

**Comment by virgilcarcu** [comment]
it's still on

**Comment by nl-danish** [comment]
Still happening; It raises a get request with a fetch call, and whenever it loses the connection, my app prompts up with "TypeError
<global>(whatwg-fetch/dist/fetch.umd)
Network request failed"

Is there any fix to this? I'm yet to test the application with commenting out the implementation of code-push and see if the issue persists.

**Comment by VirgilCarcu** [comment]
🔛

**Comment by DmitriyKirakosyan** [comment]
The CodePush SDK does not handle or extend your app's ability to work in the background. You will need to configure your app to allow internet access while running in the background for CodePush to operate effectively in this mode.
