### ISSUE TITLE
DOCTYPE html PUBLIC

### ISSUE THREAD

**Issue by David-Nguyen17** [microsoft/react-native-code-push#2488]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Run command to push new version code
2. I got an error

### Expected Behavior
Code update new version successfully

### Actual Behavior

!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span></span></div></div></body></html>

* react-native-code-push version: 7.0.5
* react-native version: 0.70.6

(The more info the faster we will be able to address it!)

**Comment by Garguy** [comment]
Having the same issue
`Error: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
  <meta content='text/html; charset=utf-8' http-equiv='content-type'/>
  <style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style>
  <title>Service unavailable</title>
</head>
<body>
  <div id='content'>
    <div id='message'>
      <h2>Our services aren't available right now</h2>
      <p>We're working to restore all services as soon as possible. Please check back soon.</p>
    </div>
    <div id='errorref'><span>20230411T202749Z-mda97uc3cp5ax0d25k3kqvad9800000006kg00000002fyr5</span>
    </div>
  </div>
</body>
</html>`

**Comment by zeusstl** [comment]
I'm having the same issue as the original message when I try to build and submit except that my message says: "The request is blocked." in the html after "Microsoft".

IMPORTANT: Please log into your account center, and submit a request. They don't check the issues here, so it is important to let them feel how many people are being affected.

**Comment by zeusstl** [comment]
Related to issue #2456

**Comment by guilherme-luccas** [comment]
Same here, request blocked

**Comment by STO11** [comment]
Same error here =/

**Comment by LucasBarrosAL** [comment]
Same error here =/

**Comment by weinixuehao** [comment]
Same here =(

**Comment by doyunnn** [comment]
Same here

**Comment by chudaotrucnhan** [comment]
Same here

**Comment by DisciplineBK** [comment]
same here

**Comment by y1jay** [comment]
same here

**Comment by RahulRijhwani** [comment]
Facing same issue.
any update ?

**Comment by nan8420** [comment]
same ....

**Comment by Joshuaasare** [comment]
Facing the same issue as well

**Comment by bonnmh** [comment]
I just want to know for sure, everyone is having this problem

Error: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span>0Xi02ZAAAAABRodBdM6aFTr3eaoOLFzXNU0lOMzBFREdFMDIxMwBmZGMzYmE0Ny0zODk2LTQyNjAtYjFlNC02MDJmM2I2YzQwYmI=</span></div></div></body></html>

**Comment by choejoonkyung** [comment]
Is this code push CI feature error currently occurring for all users?

**Comment by efrilm** [comment]
Facing same issue

**Comment by swlkkk** [comment]
Facing same issue

**Comment by swlkkk** [comment]
Having the same issue
`<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span>0vkc2ZAAAAAAXcuv0KVrxSZOIp7sWL0vNSEtCRURHRTA5MTAAZmRjM2JhNDctMzg5Ni00MjYwLWIxZTQtNjAyZjNiNmM0MGJi</span></div></div></body></html>`🥺

**Comment by ShaoGongBra** [comment]
俺也一样

**Comment by martan-fitsense** [comment]
Facing the same error.

**Comment by herarya** [comment]
just now still facing same error

**Comment by weinixuehao** [comment]
Haven't solved it?

**Comment by vutuananh** [comment]
update codepush still error

**Comment by Aboa123** [comment]
please... somebody help me

**Comment by SwikarBhattarai** [comment]
> Hot updates can be posted using code-push(version:2.1.9)
> 
> I changed from Appcenter to code-push and it works fine (version: 2.1.9)

what do you mean? could be elaborate?

**Comment by liuhaiqing12** [comment]
> update codepush still error

Check your version number, I use 2.1.9 and it works fine

**Comment by SwikarBhattarai** [comment]
> > update codepush still error
> 
> Check your version number, I use 2.1.9 and it works fine

are you taking about react-native-code-push version ?

**Comment by liuhaiqing12** [comment]
> > Hot updates can be posted using code-push(version:2.1.9)
> > I changed from Appcenter to code-push and it works fine (version: 2.1.9)
> 
> what do you mean? could you elaborate?

I have the same problem with the appcenter command, replacing to code-push command works fine

**Comment by liuhaiqing12** [comment]
> > > update codepush still error
> > 
> > 
> > Check your version number, I use 2.1.9 and it works fine
> 
> are you taking about react-native-code-push version ?

code-push version 2.1.9

**Comment by vutuananh** [comment]
Error still when update app with appcenter codepush
I use:
appcenter version 2.13.4
react-native-code-push 8.0.0
"react-native": "0.71.3"
I will try with codepush command

**Comment by Joshuaasare** [comment]
> > > > update codepush still error
> > > 
> > > 
> > > Check your version number, I use 2.1.9 and it works fine
> > 
> > 
> > are you taking about react-native-code-push version ?
> 
> code-push version 2.1.9

can you elaborate? Preferably with the command you run and other details

**Comment by trinhkhukho** [comment]
> > > > update codepush still error
> > > 
> > > 
> > > Check your version number, I use 2.1.9 and it works fine
> > 
> > 
> > are you taking about react-native-code-push version ?
> 
> code-push version 2.1.9

thank you! code-push command works fine

**Comment by vutuananh** [comment]
I try with code-push 3.0.0 command
Error:
Upload progress:[==================================================] 100% 0.0s
[Error]  Forbidden

**Comment by The9-Kim** [comment]
use [this version](https://www.npmjs.com/package/code-push-cli/v/2.1.9)

**Comment by vutuananh** [comment]
Oh my god, I downgrade code-push to 2.1.9 and it's work fine
Thanks!

**Comment by xyunsh** [comment]
the same error

**Comment by 452MJ** [comment]
+1

**Comment by talha-mts** [comment]
still getting
Error: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body { font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px 0px }#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Microsoft</title></head><body><div id='content'><div id='message'><h2>The request is blocked.</h2></div><div id='errorref'><span>024U2ZAAAAACRnOiyc5IES5YGK2GZc2peRFhCMzBFREdFMDIxNgBmZGMzYmE0Ny0zODk2LTQyNjAtYjFlNC02MDJmM2I2YzQwYmI=</span></div></div></body></html>

**Comment by HuriHuchi** [comment]
https://status.appcenter.ms/

Now they are working on it.

**Comment by yooasd11** [comment]
seems like it's back again.

**Comment by Girum** [comment]
> seems like it's back again.

YES! It's back! It'a miracle! ;)

**Comment by Girum** [comment]
relase-react Android still with error

**Comment by David-Nguyen17** [comment]
I tested it three times and seems it working perfectly again!

**Comment by Aboa123** [comment]
Code push is a great feature and service, but in this case it's really hard... If possible, I think it would be good if it was provided as an open source later on 🥲
