### ISSUE TITLE
Changes are not reflecting on iPhone. 

### ISSUE THREAD

**Issue by prateekuttreja2020** [microsoft/react-native-code-push#2501]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
I am using below mentioned version

react-native: "0.70.8"
react-native-code-push: "^7.1.0"

Changes are not reflecting on iPhone. Code is being pushed on appcenter but not downloading and install on iPhone devices.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by HCSharma** [comment]
I have the same issue.

Any updates or a timeline for a fix would be helpful.

Thank you

**Comment by Hady207** [comment]
Also we face the same issue, and on android it downloads but rolls back.

**Comment by gunnartorfis** [comment]
This situation has been for at least 9 days. Their status page used to indicate an issue but now they state that all systems are operational. 

https://status.appcenter.ms/incidents/4vz96dxnj6jb

**Comment by hvlong** [comment]
I have the same today

**Comment by verochan** [comment]
During the last weeks, I've been adding Codepush support to the app I'm working on. I've been able to send the code changes (they appear on AppCenter Codepush section), log in the service both on Android and iOS (the sessions appear on Analytics, Overview section), but there's no way to achieve that the devices get the changes from Codepush.

I've also used `adb logcat` to track the logs from the Android staging build but there's no error log related with Codepush nor Appcenter.

Right now I don't know if it's related with the service not working correctly, according to this thread, or if there's something I'm doing wrong 🤷‍♀️

**Comment by FrontendTerminator** [comment]
I also faced it

**Comment by tindn** [comment]
I have been experiencing this issue for about 2 weeks, is there any updates on this? I'm only seeing this issue on iOS, working fine for Android.

"react-native": "0.71.6",
"react-native-code-push": "7.1.0"

**Comment by amyfang3** [comment]
Same issue here

**Comment by ThalesBMC** [comment]
Same issue here, just on IOS. It downloads from appcenter but does not install the update and does not give any error besides saying that a rollback occurred.

**Comment by knro** [comment]
Same issue here. Works perfectly fine on Android, but rollsback on iOS release. Tested with iPad + iPhone but none of them work.

```
"react-native": "0.71.8",
"react-native-code-push": "8.0.1",
```

**Comment by knro** [comment]
is there anything we can do to help trace this issue?

**Comment by emzet93** [comment]
I'm facing the same issue, but there is one thing I noticed.
If there is a codepush release already uploaded to the server and you install fresh app from app store after that, it works properly.
However, if the app is already installed on the device and then codepush released is pushed, the app will not install that.
Looks like it's iOS only.

**Comment by emzet93** [comment]
btw I was able to reproduce this behavior all the time on `7.1.0`. Right now I upgraded to `8.0.2` and all seems to work well. Will continue testing.

**Comment by gunnartorfis** [comment]
> btw I was able to reproduce this behavior all the time on `7.1.0`. Right now I upgraded to `8.0.2` and all seems to work well. Will continue testing.

It's broken on 8.0.1 for me. Deleting the app and installing it again works for me but not for already installed apps.

**Comment by emzet93** [comment]
@gunnartorfis can you please check with `8.0.2`? I'm wondering if it's really fixed in this version or it's just coincidence that it started working for me now.

**Comment by gunnartorfis** [comment]
@emzet93 No can do - I'm migrating over to Expo and EAS Update. CodePush has been broken/inconsistent for me for months and I can't justify spending more time on it.

**Comment by uncoolclub** [comment]
I was facing the same problem. 
While trying to figure out the solution, I inserted `-m` in the way it was posted on the [stackoverflow](https://stackoverflow.com/questions/57070138/react-native-javascript-changes-through-codepush-not-getting-reflected-on-iphone), and it was solved. Check the deployment command.

**Comment by emzet93** [comment]
I tried to narrow down the problem by playing with `checkForUpdate` and `getUpdateMetadata` and trying to achieve basically the same what `codePush` HOC does.

It worked well, but for some reason `checkForUpdate` function stopped working suddenly and the promise from this function is never resolved. I need to call it multiple times and it usually finally works after some time. But it feels really random.

I guess the same thing happen under the hood with codePush HOC or sync method.

It seems really weird, tbh I don't see any point in `checkForUpdate` source code which could cause such stuck/freeze. Could be because of some codepush service issues on the server? Would be actually really great to hear sth about that from the maintainers.

**Comment by emzet93** [comment]
> I was facing the same problem. While trying to figure out the solution, I inserted `-m` in the way it was posted on the [stackoverflow](https://stackoverflow.com/questions/57070138/react-native-javascript-changes-through-codepush-not-getting-reflected-on-iphone), and it was solved. Check the deployment command.

Thanks! However it is mandatory update which triggers app restart in front on the user. That's sth I wanted to avoid. Also I'm not 100% sure that it really solves the issue. It seems that problem with `checkForUpdate` is kind of random and it just might luckily work for some test cases for you?
