### ISSUE TITLE
Crash iOS after update via codepush

### ISSUE THREAD

**Issue by nguyenthanhtruongntt85** [microsoft/react-native-code-push#2505]
### Steps to Reproduce
1. appcenter codepush release-react -a MyProjectName -d Production -m
2. open app
3. Click update via code push

### Expected Behavior
No crash in iOS
### Actual Behavior
- Crash in iOS
- This is log from sentry
<img width="963" alt="Screen Shot 2023-04-23 at 19 42 00" src="https://user-images.githubusercontent.com/41815920/233840483-1081efd4-02f7-49ab-bd47-6c633bd135b0.png">

### Environment
* appcenter-cli version 2.13.6
* react-native-code-push version: 7.1.0
* react-native version: 0.70.1
* "react-native-iap": 12.10.5
* physical device

### Note
before there was no crash.

**Comment by gunnartorfis** [comment]
I'm experiencing the same. Happening on Android as well.

**Comment by DmitriyKirakosyan** [comment]
Hi @nguyenthanhtruongntt85 , can you reproduce it on a new app?

**Comment by nguyenthanhtruongntt85** [comment]
> 



> Hi @nguyenthanhtruongntt85 , can you reproduce it on a new app?

yes, reproduce the same new app.

**Comment by anthlasserre** [comment]
@nguyenthanhtruongntt85 The original issue is there I think 👇🏼 
https://github.com/microsoft/react-native-code-push/issues/2539

**Comment by anthlasserre** [comment]
@nguyenthanhtruongntt85 Do you have reanimated set for your project? If yes, which version?

**Comment by nguyenthanhtruongntt85** [comment]
> @nguyenthanhtruongntt85 Do you have `react-native-reanimated` set for your project? If yes, which version?

my project have react-native-reanimated.
 i only update macos and resolved issue.

**Comment by nguyenthanhtruongntt85** [comment]
> @nguyenthanhtruongntt85 The original issue is there I think 👇🏼 #2539

No, I only update macos and resolved issue.

**Comment by anthlasserre** [comment]
> No, I only update macos and resolved issue.
 Can you let us know which version you were and which version you are now ?

**Comment by nguyenthanhtruongntt85** [comment]
> an you let us know which version you were and which version you are now ?

I using MacOS 13.4.1 (22F82)

**Comment by anthlasserre** [comment]
> I using MacOS 13.4.1 (22F82)

Sorry, maybe we misunderstood. Can I get?
- Old MacOS version
- New MacOS version (which is fixing your crash)

**Comment by nguyenthanhtruongntt85** [comment]
> > I using MacOS 13.4.1 (22F82)
> 
> @nguyenthanhtruongntt85 Sorry, maybe we misunderstood. Can I get?
> 
> * Old MacOS version
> * New MacOS version (which is fixing your crash)

Old: 12
New: 13.4.1

**Comment by 18523237715** [comment]
The hot update failed on ios 14promax and iphone 15promoax. The other iphones were normal, with one iphone 14promax running at 16.2 and the other at 17.4. How?  help me

**Comment by 18523237715** [comment]
"react-native-code-push": "^7.0.1"

**Comment by DmitriyKirakosyan** [comment]
Hello @18523237715, it's challenging to troubleshoot the problem based on the information you've shared. Could you please create a demo application that replicates the issue?

**Comment by anthlasserre** [comment]
There is an activity mate. It's still not working.

Please guys move to EAS Updates as CodePush will be soon deprecated
