### ISSUE TITLE
Sending `CodePushDownloadProgress` with no listeners registered.

### ISSUE THREAD

**Issue by David-Nguyen17** [microsoft/react-native-code-push#2508]
### Steps to Reproduce
1. Implement Codepush.sync
2. Call function codePushDownloadDidProgress

### Expected Behavior
codePushDownloadDidProgress it will be called.
### Actual Behavior
The function does not call and shows a warning in the terminal is Sending `CodePushDownloadProgress` with no listeners registered.
### Environment

* react-native-code-push version:7.0.5
* react-native version:0.70.6
* iOS/Android/Windows version:16.4

**Comment by sagardeveloper** [comment]
This issue still exists, I am getting it for an IOS device.
