### ISSUE TITLE
Too many downloads and few installs

### ISSUE THREAD

**Issue by elabayoub** [microsoft/react-native-code-push#2509]
I have noticed after releasing a new version that i've got too many downloads and few installs, even with the rollbacks numbers doesn't make any sense, i had a crush on app launch, which doesn't occur on second app opening (which explains the rollbacks) but still i can't understand why there are too many downloads and fewer installs.

### Steps to Reproduce
1. New release pushed by CLI
2. Thats it!

### Expected Behavior
Equal downloads and installs or at least not a big gap

### Actual Behavior
What actually happens?
```
  Too many downloads and few installs, even with the rollbacks, that doesn't make any sense

```
<img width="650" alt="image" src="https://user-images.githubusercontent.com/15203856/235110912-2da2c390-d122-493e-9b8d-de6c5ad3409b.png">

### Environment

* react-native-code-push version: ^7.0.5
* react-native version: 0.67.5
* iOS/Android version: Android 10, 11, 12.. iOS 14,15,16..

**Comment by scrungrth** [comment]
did you remember to let codePush know the update was successful?
```tsx
  useEffect(() => {
    CodePush.notifyAppReady();
  }, []);
```
