### ISSUE TITLE
"No signature of method: java.util.ArrayList.get()" after upgrading react-native-code-push from 7.0.5 to 8.0.1

### ISSUE THREAD

**Issue by emclab** [microsoft/react-native-code-push#2510]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.upgrade react-native-code-push from 7.0.5 to 8.0.1
2. 
3.

### Expected Behavior
What you expected to happen?
npx react-native run-android launches without error after upgrade

### Actual Behavior
What actually happens?
```
  1: Task failed with an exception.
-----------
* Where:
Script '/Users/macair/Documents/code/js/xyz_app6/node_modules/react-native-code-push/android/codepush.gradle' line: 6

* What went wrong:
A problem occurred evaluating script.
> No signature of method: java.util.ArrayList.get() is applicable for argument types: () values: []
  Possible solutions: get(int), get(int), set(int, java.lang.Object), set(int, java.lang.Object), grep(), grep()


```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 8.0.1
* react-native version: 0.70
* iOS/Android/Windows version: MacOS Monterey
* Does this reproduce on a debug build or release build? NO
* Does this reproduce on a simulator, or only on a physical device? simulator

(The more info the faster we will be able to address it!)

**Comment by tommycp96** [comment]
Up, I'm facing the same issue even though I already follow the exact setup from this documentation
https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started

**Comment by gremech** [comment]
I had the same issue. Your versions of react-native and the library seem to be incompatible.
Try `react-native-code-push` v7.0+ for react native v0.65-v0.70
https://github.com/microsoft/react-native-code-push#supported-react-native-platforms

**Comment by ahmedrowaihi** [comment]
same issue here
```
System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900KF
    Memory: 5.58 GB / 31.82 GB
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\nvs\node\16.14.0\x64\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.3.1 - ~\AppData\Local\nvs\node\16.14.0\x64\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 29.0.2, 29.0.3, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google Play Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: AI-221.6008.13.2211.9619390
    Visual Studio: 17.5.33516.290 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.16.1 - C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.7 => 0.69.7
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    ```

**Comment by ahmedrowaihi** [comment]
## Update:
I have solved the issue.
## Solution: 
remove the get() method when accessing the arraylist, since get() expects an index

I created this a patch file anyone can use it with [patch-package](https://www.npmjs.com/package/patch-package)

@emclab @gremech @tommycp96 

filename: ```react-native-code-push+8.0.1```

```
diff --git a/node_modules/react-native-code-push/android/codepush.gradle b/node_modules/react-native-code-push/android/codepush.gradle
index a0f9d27..d5cc650 100644
--- a/node_modules/react-native-code-push/android/codepush.gradle
+++ b/node_modules/react-native-code-push/android/codepush.gradle
@@ -1,9 +1,12 @@
 // Adapted from https://raw.githubusercontent.com/facebook/react-native/d16ff3bd8b92fa84a9007bf5ebedd8153e4c089d/react.gradle
 
+// @ahmedrowaihi | Problem: No signature of method: java.util.ArrayList.get()
+// solution: remove the get() method when accessing the arraylist, since get() expects an index
+
 import java.nio.file.Paths;
 
 def config = project.extensions.findByName("react") ?: []
-def bundleAssetName = config.bundleAssetName.get() ?: "index.android.bundle"
+def bundleAssetName = config.bundleAssetName ?: "index.android.bundle"
 
 // because elvis operator
 def elvisFile(thing) {
@@ -24,7 +27,7 @@ android.buildTypes.each { buildType ->
 }
 
 gradle.projectsEvaluated {
-    def debuggableVariants = config.debuggableVariants.get() ?: ['debug']
+    def debuggableVariants = config.debuggableVariants ?: ['debug']
 
     android.applicationVariants.all { variant ->
         // No code push for debuggable variants
@@ -34,7 +37,7 @@ gradle.projectsEvaluated {
 
         def nodeModulesPath;
         if (config.root) {
-            nodeModulesPath = Paths.get(config.root.asFile.get().absolutePath, "/node_modules");
+            nodeModulesPath = Paths.get(config.root.asFile.absolutePath, "/node_modules");
         } else if (project.hasProperty('nodeModulesPath')) {
             nodeModulesPath = project.nodeModulesPath
         } else {
@@ -49,8 +52,8 @@ gradle.projectsEvaluated {
         def jsBundleFile;
 
         // Additional node commandline arguments
-        def nodeExecutableAndArgs = config.nodeExecutableAndArgs.get() ?: ["node"]
-        def extraPackagerArgs = config.extraPackagerArgs.get() ?: []
+        def nodeExecutableAndArgs = config.nodeExecutableAndArgs ?: ["node"]
+        def extraPackagerArgs = config.extraPackagerArgs ?: []
 
         // Make this task run right after the bundle task
         def generateBundledResourcesHash;
@@ -73,11 +76,11 @@ gradle.projectsEvaluated {
             runBefore("merge${targetName}Assets", generateBundledResourcesHash)
         } else {
             def jsBundleDirConfigName = "jsBundleDir${targetName}"
-            jsBundleDir = elvisFile(config."$jsBundleDirConfigName").get() ?:
+            jsBundleDir = elvisFile(config."$jsBundleDirConfigName") ?:
                     file("$buildDir/intermediates/assets/${targetPath}")
 
             def resourcesDirConfigName = "resourcesDir${targetName}"
-            resourcesDir = elvisFile(config."${resourcesDirConfigName}").get() ?:
+            resourcesDir = elvisFile(config."${resourcesDirConfigName}") ?:
                     file("$buildDir/intermediates/res/merged/${targetPath}")
 
             // In case version of 'Android Plugin for Gradle'' is lower than 1.3.0
```

**Comment by DmitriyKirakosyan** [comment]
Might be related to https://github.com/microsoft/react-native-code-push/issues/2521.

@emclab , @tommycp96 , would it be possible for you to upgrade RN to 0.71?

**Comment by tommycp96** [comment]
Hi @DmitriyKirakosyan thanks for coming back, we will try to upgrade and let you know if we still facing this issue.

**Comment by Eyad911** [comment]
I'm facing the same issue !
![Screenshot 1444-12-02 at 1 59 51 PM](https://github.com/microsoft/react-native-code-push/assets/92247966/06de3d0e-3f5c-453e-926f-59cae0bbcfeb)

**Comment by tommycp96** [comment]
> @tommycp96 , have you tried to upgrade yet? Just a gentle ping.

Hi @DmitriyKirakosyan we still in progress and found an issue for our android app, will keep you posted if we find any issue related to CodePush library. Thanks for checking btw, appreciate it.

**Comment by Eyad911** [comment]
> I'm facing the same issue ! ![Screenshot 1444-12-02 at 1 59 51 PM](https://user-images.githubusercontent.com/92247966/247094883-06de3d0e-3f5c-453e-926f-59cae0bbcfeb.png)

i just downgrade codePush to 7.0.4 and its work fine

**Comment by markosrx** [comment]
I am still having a same issue...Any solution?

**Comment by itsabk** [comment]
Facing the same issue

**Comment by rodrigodiasf1984** [comment]
same issue, any solution yet?

**Comment by bonesyblue** [comment]
Hi all 👋 

I solved this issue by making the following change in the `node_modules/react-native-code-push/android/codepush.gradle` file:

```groovy
// Broken 💥 
def debuggableVariants = config.debuggableVariants.get() ?: ['debug']

// Fixed ✅ 
def debuggableVariants = config.debuggableVariants ?: ['debug']
```

For managing alterations to npm dependencies that I make locally, I rely on [patch-package](https://www.npmjs.com/package/patch-package). Hope this helps! 🚀

**Comment by MikhailSuendukov** [comment]
@itsabk @rodrigodiasf1984 @bonesyblue 
Could you please check if this [fix](https://github.com/microsoft/react-native-code-push/pull/2471) works for you?

**Comment by pierroo** [comment]
FYI the info still persists on v8.2.1 @MikhailSuendukov ;
as a matter of fact I just created an issue on it (which I will close now that I found this one)

**Comment by benycodes** [comment]
If you're using expo make sure 
```gradle
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
```
is in the gradle file at `/android/app/build.gradle` (not the `/android/build.gradle` file)

**Comment by pnogier** [comment]
Hi guys,
Facing the same issue on `8.2.1`, RN `0.73.2`, could anyone fix this temporarily using a patch ?

**Comment by DrunkenNeoguri** [comment]
hello
I'm trying to use Code Push v8.2.2 with React Native v0.74.1, which was recently updated, but the same issue is occurring.
This issue is already closed, but I don't see a clear solution, so I'm writing a comment like this.🥲
