### ISSUE TITLE
Problem with codepush after upgrading packages

### ISSUE THREAD

**Issue by Darex1991** [microsoft/react-native-code-push#2520]
Hi, after upgrading from RN 0.64 to 0.67.5 I have problems with using code-push. I checked on two different Macs, any ideas on how to fix or debug this? To be honest, no idea what is going on. My diff changes https://diffy.org/diff/b87b956eeec64 (please do not delete it :))

```
Converting JS bundle to byte code via Hermes, running command:

node_modules/hermes-engine/osx-bin/hermesc -emit-binary -out source_maps/5.0.7v2/android/CodePush/index.android.bundle.hbc source_maps/5.0.7v2/android/CodePush/index.android.bundle -output-source-map -w
source_maps/5.0.7v2/android/CodePush/index.android.bundle:2563:123: error: ';' expected
__d(function(g,r,i,a,m,e,d){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var t=r(d[0])(r(d[1])),n=0,t.default`
                                                                                                                          ^
Error: Failed to release a CodePush update.
```

<img width="1439" alt="Screenshot 2023-05-17 at 20 12 37" src="https://github.com/microsoft/react-native-code-push/assets/5881611/d7e1b87d-1d0e-47ce-84ea-7d846193a66c">

### Environment

* react-native-code-push version: 7.0.4
* react-native version: 0.67.5
* hermes-engine: checked 0.9, 0.10 nad 0.11

**Comment by DmitriyKirakosyan** [comment]
Hi @Darex1991 , RN versions < 0.69 are out of support. I recommend you to upgrade RN to a supported version.
As for this issue, it is hard to tell what is going wrong. Have you tried to reproduce the problem on a fresh RN 0.67.5 app?

**Comment by Darex1991** [comment]
No, I need to upgrade my RN in next task so I'll check :) Thanks for the response. I'll ping you later

**Comment by Darex1991** [comment]
Sorry for late response :) I checked a week ago and it works :) Thanks, @DmitriyKirakosyan
