### ISSUE TITLE
Question: Multi deployments with different js bundle

### ISSUE THREAD

**Issue by Spejbl** [microsoft/react-native-code-push#2524]
In our setup we have different environment variables for staging and production builds. For which we have a simple bash script to swap them during the bundle phase.
```
# env-switch.sh
ENV=$1
cp env.$ENV.json env.json
```

```
"ios:bundle:staging": "sh ./scripts/env-switch.sh staging && react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'",
"ios:bundle:prod": "sh ./scripts/env-switch.sh production && react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'",
``` 

However, due to this approach, the resulting JavaScript bundle will differ between staging and production. This becomes particularly problematic when promoting a deployment from staging to production via CodePush since the bundled code still references the staging environment variables.

Did anyone encounter a similar issue? If so how did you manage to solve it? Thank you

**Comment by BANG88** [comment]
Try to use a different deployment key.

https://github.com/microsoft/react-native-code-push/blob/master/docs/api-js.md#CodePushOptions

**Comment by Spejbl** [comment]
We do have the setup with different deployment keys for staging and prod. The problem is when promoting from Staging to Production through CodePush. The Production build is going to point to the Staging js bundle.

Only solution I could think of is to ditch the CodePush environments and have a separate app for each instead. But that feels a bit hacky.
