### ISSUE TITLE
Bump SSZipArchive from 2.2.2 to 2.5.4, resolving Arbitrary File Write via Archive Extraction

### ISSUE THREAD

**Issue by TheSolly** [microsoft/react-native-code-push#2528]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-code-push@8.0.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-code-push/CodePush.podspec b/node_modules/react-native-code-push/CodePush.podspec
index d20c4f4..30d9ff2 100644
--- a/node_modules/react-native-code-push/CodePush.podspec
+++ b/node_modules/react-native-code-push/CodePush.podspec
@@ -21,7 +21,7 @@ Pod::Spec.new do |s|
   # we explicitly let CocoaPods pull in the versions below so all dependencies are resolved and 
   # linked properly at a parent workspace level.
   s.dependency 'React-Core'
-  s.dependency 'SSZipArchive', '~> 2.2.2'
+  s.dependency 'SSZipArchive', '~> 2.5.4'
   s.dependency 'JWT', '~> 3.0.0-beta.12'
   s.dependency 'Base64', '~> 1.1'
 end
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by kg-currenxie** [comment]
Same issue here. 6 months later...
![image](https://github.com/microsoft/react-native-code-push/assets/48229166/20187d3e-2691-480a-b816-a7c0dc04095c)
