### ISSUE TITLE
Codepush failed exception and Changes are not reflect to android app after release update to Staging and Production

### ISSUE THREAD

**Issue by BalochPalwisha** [microsoft/react-native-code-push#2538]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Install code push to the project
2.  implement default code push behaviour  as
 class MyApp extends Component {
// lines of code
}
MyApp = codePush(MyApp);

### Expected Behavior
code push should be successfully implemented in the project

### Actual Behavior
getting error on build "No signature of method: java.util.ArrayList.get() is applicable for argument types: () values: []" 

  1: Task failed with an exception.
-----------
* Where:
Script '/Users/macair/Documents/code/js/xyz_app6/node_modules/react-native-code-push/android/codepush.gradle' line: 6

* What went wrong:
A problem occurred evaluating script.
> No signature of method: java.util.ArrayList.get() is applicable for argument types: () values: []
  Possible solutions: get(int), get(int), set(int, java.lang.Object), set(int, java.lang.Object), grep(), grep()

### Environment

* react-native-code-push version:  8.0.2
* react-native version: 0.70.1
* iOS/Android/Windows version: 
* Does this reproduce on a debug build or release build?  release build
* Does this reproduce on a simulator, or only on a physical device? physical device

I have spent many hours searching for a solution but did not find any reliable fix. I also downgrade the code push version to 7.0.4
after downgrade, I am not getting the above error but my code push change does not reflect on the app.
Please help me in this situation.

**Comment by adsalihac** [comment]
i got same issue

**Comment by markosrx** [comment]
same for me

**Comment by DmitriyKirakosyan** [comment]
Seems similar to https://github.com/microsoft/react-native-code-push/issues/2510. Let's continue the discussion there.

Currently, this issue seems to arise after a react-native version upgrade. If anyone can replicate this in a sample app, please share with us.

Closing as duplicate.
