### ISSUE TITLE
[iOS] CodePush.restartApp() crash

### ISSUE THREAD

**Issue by kr-yeon** [microsoft/react-native-code-push#2539]
### Steps to Reproduce
1. build on testflight
2. start app
3. request CodePush.restartApp()

### Expected Behavior
What you expected to happen?
Restart Application

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
Shutdown app

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 8.0.0
* react-native version: 0.71.6
* iOS/Android/Windows version: iOS 16
* Does this reproduce on a debug build or release build? yes. it is release build.
* Does this reproduce on a simulator, or only on a physical device? physical device!

(The more info the faster we will be able to address it!)

**Comment by kr-yeon** [comment]
[super. bridge reload]; Occurs when running code

**Comment by sudokatsu** [comment]
I have this same issue. I've found that the CodePush gets applied most of the time, but requires the user to re-open the app after it crashes. Happens more on Android than iOS for me, but still occasionally on iOS.

**Comment by peytonwupeixin** [comment]
I use react-native-code-push version: 8.0.2. I have the same issue, iOS happens more than Android.  Is it because Code push currently only supports 0.71 and not yet 0.71.6?

**Comment by kr-yeon** [comment]
> I use react-native-code-push version: 8.0.2. I have the same issue, iOS happens more than Android. Is it because Code push currently only supports 0.71 and not yet 0.71.6?

I am currently using rn 0.71.11 I updated once but still have the same problem

**Comment by ludwig-pro** [comment]
I have exactly the same problem. at first i suspected reanimated, but after patching it, i still get the bug.

Only in "release", according to sentry tracking, it's a RAM problem: 
> WatchdogTermination: The OS watchdog terminated your app, possibly because it overused RAM.

I try to replace code-push with react-native-restart and [I have the same issue, also reported by other here](https://github.com/avishayil/react-native-restart/issues/239)

reanimated patch  for `react-native-reanimated 3.1.0` => 
```
diff --git a/node_modules/react-native-reanimated/ios/LayoutReanimation/REAAnimationsManager.m b/node_modules/react-native-reanimated/ios/LayoutReanimation/REAAnimationsManager.m
index 365ae4f..6290823 100644
--- a/node_modules/react-native-reanimated/ios/LayoutReanimation/REAAnimationsManager.m
+++ b/node_modules/react-native-reanimated/ios/LayoutReanimation/REAAnimationsManager.m
@@ -396,7 +396,7 @@ BOOL REANodeFind(id<RCTComponent> view, int (^block)(id<RCTComponent>))
     return NO;
   }
 
-  BOOL hasExitAnimation = _hasAnimationForTag(view.reactTag, EXITING) || [_exitingViews objectForKey:view.reactTag];
+  BOOL hasExitAnimation = [self hasAnimationForTag:view.reactTag type:EXITING] || [_exitingViews objectForKey:view.reactTag];
   BOOL hasAnimatedChildren = NO;
   shouldRemoveSubviewsWithoutAnimations = shouldRemoveSubviewsWithoutAnimations && !hasExitAnimation;
   NSMutableArray *toBeRemoved = [[NSMutableArray alloc] init];
@@ -521,7 +521,7 @@ BOOL REANodeFind(id<RCTComponent> view, int (^block)(id<RCTComponent>))
 {
   LayoutAnimationType type = before == nil ? ENTERING : LAYOUT;
   NSNumber *viewTag = view.reactTag;
-  if (_hasAnimationForTag(viewTag, type)) {
+  if ([self hasAnimationForTag:viewTag type:type]) {
     REASnapshot *after = [[REASnapshot alloc] init:view];
     if (before == nil) {
       [self onViewCreate:view after:after];
@@ -533,7 +533,7 @@ BOOL REANodeFind(id<RCTComponent> view, int (^block)(id<RCTComponent>))
     [self setNewProps:before.values forView:view];
   }
 
-  if (_hasAnimationForTag(viewTag, SHARED_ELEMENT_TRANSITION)) {
+  if ([self hasAnimationForTag:viewTag type:SHARED_ELEMENT_TRANSITION]) {
     if (type == ENTERING) {
       [_sharedTransitionManager notifyAboutNewView:view];
     } else {
diff --git a/node_modules/react-native-reanimated/src/reanimated2/mappers.ts b/node_modules/react-native-reanimated/src/reanimated2/mappers.ts
index 4e66106..bc8712f 100644
--- a/node_modules/react-native-reanimated/src/reanimated2/mappers.ts
+++ b/node_modules/react-native-reanimated/src/reanimated2/mappers.ts
@@ -80,8 +80,11 @@ export function createMapperRegistry() {
   }
 
   function mapperRun() {
-    processingMappers = true;
     runRequested = false;
+    if (processingMappers) {
+      return;
+    }
+    processingMappers = true;
     if (mappers.size !== sortedMappers.length) {
       updateMappersOrder();
     }
```

**Comment by ludwig-pro** [comment]
BTW I use Xcode_14.3.1.app to build the app

**Comment by anthlasserre** [comment]
@kr-yeon Does this crash happen through your local XCode with a release build?

**Comment by kr-yeon** [comment]
yeah

2023년 8월 19일 (토) 오전 12:21, Anthony LASSERRE ***@***.***>님이 작성:

**Comment by anthlasserre** [comment]
@kr-yeon Which MacOS version are you using ?

**Comment by kr-yeon** [comment]
Ventura 13.4
XCodeVersion is 14.3

2023년 8월 19일 (토) 오전 12:25, Anthony LASSERRE ***@***.***>님이 작성:

**Comment by ludwig-pro** [comment]
Should we consider react-native-code-push as deprecated?

**Comment by kr-yeon** [comment]
In fact, I excluded CodePush from the project. I don't know if I'm stupid, but I couldn't find the answer.

**Comment by iita71737** [comment]
I face the issue on Android , but work on iOS.
Anyone face it on Android too?

**Comment by kr-yeon** [comment]
I'm also experiencing that issue only on Android. I thought it might be a
problem with the built bundle's asset path, but I removed Codepush first.

2024년 1월 20일 (토) 오후 11:54, DanLin ***@***.***>님이 작성:

**Comment by MikhailSuendukov** [comment]
Hi everyone! Could you please confirm what this issue still persist on latest version (8.2.1)?

**Comment by krunal-cmyk** [comment]
Any solutions, I am facing with iOS on release app. It crashes after restart

**Comment by ludwig-pro** [comment]
The best solution is to drop codepush and use expo

**Comment by vlimag** [comment]
Im facing this same issue with expo-updates as well.
- "react-native-reanimated": "3.6.2",
- "react-native": "0.73.4",
- "expo": "~50.0.11",
- "expo-updates": "~0.24.11",

**Comment by Logan-FE** [comment]
any changes for this?

**Comment by DordeDimitrijev** [comment]
Hi @Logan-FE  thank you for reaching out. Does this issue still reproduce on latest 8.3.1 version?

**Comment by nihal-37-37** [comment]
> Im facing this same issue with expo-updates as well.
> 
> * "react-native-reanimated": "3.6.2",
> * "react-native": "0.73.4",
> * "expo": "~50.0.11",
> * "expo-updates": "~0.24.11",


[vlimag](https://github.com/vlimag) you found any alternative or solution with this?

**Comment by nihal-37-37** [comment]
> Im facing this same issue with expo-updates as well.
> 
> * "react-native-reanimated": "3.6.2",
> * "react-native": "0.73.4",
> * "expo": "~50.0.11",
> * "expo-updates": "~0.24.11",


@vlimag  [vlimag](https://github.com/vlimag) you found any alternative or solution with this?

**Comment by nihal-37-37** [comment]
@DordeDimitrijev I'm facing same problem, distribution is fine but to effect on android application

    "react-native-code-push": "^8.3.1",
       "react-native": "0.73.4",

**Comment by DmitriyKirakosyan** [comment]
@nihal-37-37 , are you using `react-native-reanimated` in direct or transitive dependencies? Could you share your crash log?

**Comment by nainglynndw** [comment]
if you are using `react-native-screenshot-prevent` , remove `enableSecureView` and `disableSecureView`.

Problem happens when we reload jsbundle. 

codepush.restart() also reload jsbundle. 

These make crash for me. 

After remove, it works
