### ISSUE TITLE
[android] release apk does't work. 

### ISSUE THREAD

**Issue by Sean-Snow** [Microsoft/react-native-code-push#254]
the log
<img width="976" alt="2016-03-18 19 38 21" src="https://cloud.githubusercontent.com/assets/4498796/13876705/0ad0ccd8-ed41-11e5-8aa4-eca6e91a320f.png">

**Comment by lostintangent** [comment]
@Sean-Snow Are the error logs appearing after you background/resume the app to force the install? Or are you getting these after the update installation completes? Could you let us know what command you ran to generate the update that you released to CodePush? It seems like the update contents might have also be invalid.

**Comment by Sean-Snow** [comment]
i cleanr my app,then install release app .it's work.I can not reproduce this error。 @lostintangent

**Comment by lostintangent** [comment]
@Sean-Snow OK thanks for letting us know. Should we close this issue then?

**Comment by Sean-Snow** [comment]
thank you. close it

**Comment by lostintangent** [comment]
Let us know if you run into any other issues! Thanks again.
