### ISSUE TITLE
Privacy - Inquiry Regarding Use of Cookies

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [microsoft/react-native-code-push#2541]
I'm currently using your valuable react-native-code-push library in one of my projects, and I find it highly beneficial and easy to use. I commend your team on the effort and skill you've put into this development.

As my application uses your library, I need to provide detailed and accurate information to my users regarding their data usage and privacy, particularly concerning cookies.

I was not able to find a clear specification in your documentation regarding the usage of cookies within the react-native-code-push client. Could you please provide some clarification about this matter? More specifically, I would like to understand:

- Does the react-native-code-push client use any cookies?
- If so, what specific data are these cookies collecting, and for what purpose?

I believe this information is essential for ensuring the transparency of data usage within our applications, and it would be very much appreciated if you could provide this detail.

Thank you in advance for your time and assistance in this matter. Looking forward to your response.

**Comment by MikhailSuendukov** [comment]
Hello and sorry for the long delay. Code Push does not store any cookies. If you still have any questions, feel free to contact us!
