### ISSUE TITLE
[Android] after codepush, svg image is not shown

### ISSUE THREAD

**Issue by kr-yeon** [microsoft/react-native-code-push#2544]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. init project and install react-native-svg and react-native-code-push package
2. use WithLocalSvg component and set props `asset={require(ur_svg_path)}`
3. code-push release

### Expected Behavior
What you expected to happen?
![KakaoTalk_Photo_2023-07-07-16-00-01](https://github.com/microsoft/react-native-code-push/assets/65217664/114478cb-ab39-4d3c-8e11-25fa3f74b7a7)

shown all svg image

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
![Screenshot_20230707_160149_TABLE](https://github.com/microsoft/react-native-code-push/assets/65217664/e32927f7-8fb1-419f-a327-4000ac4392db)

not shown all svg image

### Environment

* react-native-code-push version: 8.0.0
* react-native version: 0.71.11
* iOS/Android/Windows version: 13
* appcenter version: 2.13.4
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? physical device

I used this command.
```
appcenter codepush release-react -a {Project Name} -d Production —sourcemap-output —output-dir ./bundles
```

There is an svg file in bundles/CodePush/raw, but it doesn't show up. ToT

**Comment by AZbang** [comment]
Same problem

**Comment by enfp-dev-studio** [comment]
Same problem

**Comment by cristea2017** [comment]
> Hi @kr-yeon
> 
> Could you please confirm what this issue still persist on latest version (8.2.1)?

yep 100%

**Comment by cristea2017** [comment]
@kr-yeon https://github.com/microsoft/react-native-code-push/issues/2684#issuecomment-2026917475
