### ISSUE TITLE
target-binary-version *

### ISSUE THREAD

**Issue by asapMaki** [microsoft/react-native-code-push#2561]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Implement code push
2. Install release on Android with version `2.5.2` (or any other), sometimes version can be in this format `2.5.2-1964`
3. Deploy codepush update with command `appcenter codepush release-react -a owner/app -d Staging --target-binary-version "*"`

### Expected Behavior
What you expected to happen?
I expect that my target binary version is applied to all versions in this case

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
  Nothing happens, even codepush returns 404.
 LOG  [CodePush] Report status failed: {"appVersion":"2.5.2"}
 LOG  [CodePush] An unknown error occurred.
 LOG  [CodePush] 404: No deployment found.
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 7.1.0
* react-native version: 0.69.10
* iOS/Android/Windows version: MIUI 13
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device?
Only tried real device

(The more info the faster we will be able to address it!)

**Comment by quimvinals** [comment]
Same here. For staging build we have a nomenclature like `X.Y.Z-rc1` where only rc1, rc2, rc3... Changes.
When the app version has the final part of `-rcX` the `*` to the target version does not work.
Only works when the target version explicitly says the desired app to update, like `2.7.1-rc1`
It would be helpful if they would use binary version to target or that the `*` a the universal update actually worked
