### ISSUE TITLE
CodePushMetadata returning `undefined` instead of `null` type

### ISSUE THREAD

**Issue by HarryHighPants** [microsoft/react-native-code-push#2563]
`getUpdateMetadata` return type is shown as `LocalPackage | null` in the [Typescript types](https://github.com/microsoft/react-native-code-push/blob/master/typings/react-native-code-push.d.ts#L270) and [Docs](https://github.com/microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushgetupdatemetadata)
### Steps to Reproduce
Call getUpdateMetadata() while the app doesn't have a CodePush update installed
```
const codePushMetadata = await codePush.getUpdateMetadata()
if(codePushMetadata === null){
  console.log('We dont have an installed CodePush update')
} else {
  console.log('We have an installed CodePush update')
  console.log(codePushMetadata.label)
}
```

### Expected Behavior
I expect to get the console log "We don't have an installed CodePush update"

### Actual Behavior
`getUpdateMetadata` is actually returning `undefined` instead of `null` so the code tries to read it's data and gets an error:
`TypeError: Cannot read properties of undefined (reading 'label')`
![image](https://github.com/microsoft/react-native-code-push/assets/38173749/a3278f23-c6a4-497d-9192-a41320862a5b)

### Workaround
Use loose equality (double equals) instead of strict equality (triple equals)
`if(codePushMetadata == null)`
`if(!!codePushMetadata)`

### Environment
* react-native-code-push version: 8.0.2
* react-native version: 0.72.3
* iOS/Android/Windows version: -
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by DmitriyKirakosyan** [comment]
Hi @HarryHighPants, could you please specify which version of react-native-code-push you're using and direct me to the specific lines of code you referenced in your description?
