### ISSUE TITLE
Using ANDROID_ID violates google families policy

### ISSUE THREAD

**Issue by biomancer** [microsoft/react-native-code-push#2575]
Hi! 
Our app's audience includes kids and the app cannot send any unique identifiers according to Google Play Families Policy. 

react-native-code-push on the other hand uses ANDROID_ID in it's code https://github.com/microsoft/react-native-code-push/blob/777e2024c3420d58dfaad37fe580ab8fb140cc4f/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L63 and that triggers Google's static code analysis warning looking like that:

> SPLIT_BUNDLE [VERSION_CODE]: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address)

which leads to automatic build rejection.

Why is ANDROID_ID used? Is it possible to replace with something else or make it optional? 
What would happen if we replace it with static string like "no-android-id" via patch-package — would it break any functionality? 

### Environment

* react-native-code-push version: ours is 7.0.4, but that code is still the same in master, it will trigger the same warning.
* react-native version: 0.68.5
* iOS/Android/Windows version: N/A
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? N/A

Related issues are https://github.com/microsoft/react-native-code-push/issues/2327 and https://github.com/microsoft/react-native-code-push/issues/2297, but they are closed while the issue is still active.

**Comment by saoudnazir** [comment]
Same Issue.

**Comment by MikhailSuendukov** [comment]
We have implemented a fix and it will be available in the next SDK release. Therefore, I am closing this issue, but if you have any questions, you can freely re-open this issue.

**Comment by nguyenduythuc** [comment]
![image](https://github.com/microsoft/react-native-code-push/assets/6987808/498f12a0-c683-438f-a4ca-40da8ea37db9)

At react-native-code-push: 8.1.0. I am being rejected by Play Store about "Policy Declaration - Data Safety Section". I never met this issue before. Pls, help! :(

**Comment by nguyenduythuc** [comment]
@MikhailSuendukov did you release this pull request https://github.com/microsoft/react-native-code-push/pull/2592 on npm?

**Comment by AnatolyPristensky** [comment]
@nguyenduythuc, these changes are available in 8.1.1 version. It has been released today: https://www.npmjs.com/package/react-native-code-push

**Comment by nguyenduythuc** [comment]
> @nguyenduythuc, these changes are available in 8.1.1 version. It has been released today: https://www.npmjs.com/package/react-native-code-push

This is so meaningful to us, thanks for your support!
