### ISSUE TITLE
undefined is not an object (evaluating 'e.packageHash')

### ISSUE THREAD

**Issue by GoldenForest** [Microsoft/react-native-code-push#258]
[CodePush] Checking for update.
[CodePush] An unknown error occurred.
[CodePush] undefined is not an object (evaluating 'e.packageHash')

**Comment by geof90** [comment]
Hi @GoldenForest, for which version of the plugin are you seeing this error?

**Comment by lostintangent** [comment]
@GoldenHash We're having trouble reproing this issue. In addition to the version of the CodePush plugin you're using, could you also let us know if this is this is happening on iOS or Android, on the emulator or device, with Chrome debugging enabled or disabled, and in a debug or release build? Thanks!

**Comment by lostintangent** [comment]
@GoldenForest We haven't been able to repro this issue unfortunately, so I'm going to close it for now. If you are still hitting this, could you please re-open this and let us know what type of platform and configuration you were testing against? Thanks!
