### ISSUE TITLE
Does code push work with Xcode 15-Beta

### ISSUE THREAD

**Issue by muzzamilshaikh** [microsoft/react-native-code-push#2581]
I recently upgraded my Mac from macOS 13 (Ventura) to macOS 14 (Sonoma), which also resulted in an update to Xcode, now running Xcode 15-Beta. However, upon attempting to push new changes to TestFlight and test the code, I encountered issues, and I'm wondering if there might be stability issues with Xcode 15-Beta. Thank you for your assistance.

**Comment by DmitriyKirakosyan** [comment]
Hello @muzzamilshaikh,

Since Xcode 15 is still in beta, there may be some issues, particularly with the linker. Could you please specify the exact issues you are encountering?

**Comment by DmitriyKirakosyan** [comment]
I'm closing this. Please reopen if you're still facing the issue.
