### ISSUE TITLE
Codepush update not getting received for android. Working for iOS though.

### ISSUE THREAD

**Issue by prateekraj** [microsoft/react-native-code-push#2583]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Expected Behavior
When I Push copdepush update I should receive it on my phone. Happening for iOS but not for android. 

### Actual Behavior
Updates are getting pushed and they are visible on appcenter console. But my android app is not receiving it. It used to work but after upgrading gradle, react native and codepush library I started getting these isuues.
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 8.1.0
* react-native version:0.72.4
* com.android.tools.build:gradle :7.3.1
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? Both
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

**Comment by DmitriyKirakosyan** [comment]
Hi @prateekraj, have you tried creating a new React Native app using version 0.72.4 and integrating CodePush? Upon initial inspection, it seems like something might have been overlooked during the app upgrade, potentially leading to the issue you're experiencing.

**Comment by prateekraj** [comment]
> Hi @prateekraj, have you tried creating a new React Native app using version 0.72.4 and integrating CodePush? Upon initial inspection, it seems like something might have been overlooked during the app upgrade, potentially leading to the issue you're experiencing.

react-native-code-push version: 8.1.0
react-native version:0.72.4
com.android.tools.build:gradle :7.3.1

Could you be more specific please? @DmitriyKirakosyan

**Comment by prateekraj** [comment]
> Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
> 
> ### Expected Behavior
> When I Push copdepush update I should receive it on my phone. Happening for iOS but not for android.
> 
> ### Actual Behavior
> Updates are getting pushed and they are visible on appcenter console. But my android app is not receiving it. It used to work but after upgrading gradle, react native and codepush library I started getting these isuues.
> 
> ```
>   STACK TRACE AND/OR SCREENSHOTS
> ```
> 
> ### Reproducible Demo
> * Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
> * If you can't reproduce the bug on it, provide us as much info as possible about your project
> 
> ### Environment
> * react-native-code-push version: 8.1.0
> * react-native version:0.72.4
> * com.android.tools.build:gradle :7.3.1
> * iOS/Android/Windows version:
> * Does this reproduce on a debug build or release build? Both
> * Does this reproduce on a simulator, or only on a physical device? Both
> 
> (The more info the faster we will be able to address it!)

This is resolved. I had to disable hermes 
project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]
and add  this inside my 
buildType{
internal{
.....
resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())
}
release{
.....
resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())
}
}
