### ISSUE TITLE
Error: Deployment "Staging" does not exist.

### ISSUE THREAD

**Issue by mujehoxe** [microsoft/react-native-code-push#2584]
### Steps to Reproduce
1. Run `appcenter codepush release-react -a <ownerName>/<appName>`

### Expected Behavior
What you expected to happen?
Shouldn't face this error

### Environment

* react-native-code-push version: ^8.1.0
* react-native version: ^0.72.3
* iOS/Android/Windows version: Targeting android
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? N/A

(The more info the faster we will be able to address it!)
Also tried
`appcenter codepush release-react -a <ownerName>/<appName>  -m --description "alpha-0.1.0" -d "Staging" --use-hermes `
`appcenter codepush release-react -a <ownerName>/<appName>  -m --description "alpha-0.1.0" -d "Production" --use-hermes
Error: Deployment "Production" does not exist. `

**Comment by DmitriyKirakosyan** [comment]
Hi @mujehoxe , make sure the deployment exists on App Center, the user you log in with has required permissions. Try using full argument name --deployment-name.

**Comment by mujehoxe** [comment]
Didn't work, also i tried to build the app in the app center web ui from github repo, yet it didn't detect the package.json file.

**Comment by ZaharGusyatin** [comment]
in terminal
`

> appcenter login

`

**Comment by mujehoxe** [comment]
Man it's done

**Comment by mujehoxe** [comment]
yeah, getting an empty table with only the header.

Note: To display deployment keys add -k|--displayKeys option
┌──────┬─────────────────┬─────────────────┐
│ Name │ Update Metadata │ Install Metrics │
└──────┴─────────────────┴─────────────────┘

**Comment by mujehoxe** [comment]
Here is what i am getting when trying to build the app on the appcenterUI
![Screenshot from 2023-09-21 08-47-10](https://github.com/microsoft/react-native-code-push/assets/52047683/003cc1dc-806f-40c7-9748-59d96db3eb3b)

**Comment by mujehoxe** [comment]
![Screenshot from 2023-09-24 16-37-22](https://github.com/microsoft/react-native-code-push/assets/52047683/015fd784-d1c5-4214-81a3-cf3337de458e)

@DmitriyKirakosyan do you have any idea about how to solve this?

**Comment by DmitriyKirakosyan** [comment]
@mujehoxe , according to your picture, you are looking at build branches. What you need is CodePush deployments. It is located under Distribute -> CodePush.

**Comment by DmitriyKirakosyan** [comment]
Closing. Please let me know if the issue persists.
