### ISSUE TITLE
The update returns 404 response.

### ISSUE THREAD

**Issue by dkahdwk** [microsoft/react-native-code-push#2585]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Update code push.
2. The user checks for new updates through `checkForUpdate` and acts on the update.
3. But it returns `Received 404 response from https://codepush-secondary.blob.core.windows.net/storagev2/.....`
 - <img width="875" alt="스크린샷 2023-09-19 오후 5 09 48" src="https://github.com/microsoft/react-native-code-push/assets/56759331/bbf3ece0-a9f1-4896-9800-ac172c4e9290">
4. And on the device, this version continues unacceptable. (Until the app is reinstalled or a new code push version is released)

This problem is a very big problem! I wonder why it's still unresolved.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version: 0.71.12
* iOS/Android/Windows version: iOS 16.1.1
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? physical device

(The more info the faster we will be able to address it!)

**Comment by DmitriyKirakosyan** [comment]
@dkahdwk , thank you for reaching out! I believe this is a duplicate of https://github.com/microsoft/react-native-code-push/issues/2527/.

Can you confirm that the update is installed successfully if you postpone the `checkForUpdate` call for one minute or so after you released a new version?

**Comment by dkahdwk** [comment]
> @dkahdwk , thank you for reaching out! I believe this is a duplicate of #2527.
> 
> Can you confirm that the update is installed successfully if you postpone the `checkForUpdate` call for one minute or so after you released a new version?

Yes, it's the same as the issue.
If the update fails, it will not function properly after 1 minute. Until reinstall the app.

**Comment by skam22** [comment]
I was able to work around this issue by pushing the appcenter codepush release with the ```-x``` flag (update disabled).

It will upload but not be made available for users to download it immediately.

Wait a few minutes, and then enable the update after it has time to propagate across Microsoft's codepush servers, and you'll avoid the 404 error.

The problem is that if your users's device receives the 404 error, that specific update will not be attempted again because the SDK thinks that the release was rolled back.  By uploading with ```disabled``` status you'll avoid that situation.

**Comment by hotaryuzaki** [comment]
> I was able to work around this issue by pushing the appcenter codepush release with the `-x` flag (update disabled).
> 
> It will upload but **NOT** be made available for users to download immediately.
> 
> Wait a few minutes, and then enable the update after it has time to propagate across Microsoft's codepush servers, and you'll avoid the 404 error.
> 
> The problem is that if your users's device receives the 404 error, that specific update will not be attempted again because the SDK thinks that the release was rolled back. By uploading with `disabled` status you'll avoid that situation.

after that, can we enable it from CLI?

**Comment by hotaryuzaki** [comment]
the CLI docs is really bad, when we access it from the link in the Read me here, they redirect to CLI version 3.1.0 but actually Appcenter CLI still version 2.14.0 and they have different commands.
i know we need to use Patch command but i cannot find it anywhere in the docs how to set enable.
then i found it from an issue report that the parameter is "-x false"
and here the Patch command in Appcenter CLI version 2.14.0
```
appcenter codepush patch -a <ownerName>/<app_name> <deploymentName> -l <releaseLabel> -x false
```

**Comment by jamesholcomb** [comment]
@dkahdwk Why was the closed as completed?  Please let us know what changed.

**Comment by MikhailSuendukov** [comment]
Since this issue is already closed, let's continue the discussion in an open duplicate with high activity - in this https://github.com/microsoft/react-native-code-push/issues/2527.
