### ISSUE TITLE
How to configure updates with DeviceCheck and App Attest?

### ISSUE THREAD

**Issue by skam22** [microsoft/react-native-code-push#2593]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Archive and distribute app on TestFlight
2. Install app, App Attestation succeeds
3. From command line push appcenter codepush update
4. Install update on device
5. Update installs successfully, App Attestation fails.

### Expected Behavior
Expect App Attestation to remain valid.

### Actual Behavior
App attestation fails, resources are blocked.

### Environment

* react-native-code-push version:  8.1.0
* react-native version: 0.72.5
* iOS/Android/Windows version: latest
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? both

Our backend is protected using Firebase App Check.  Under the hood it uses DeviceCheck and App Attest for iOS applications.

Firebase has been set up correctly, the .p8 key is uploaded to firebase and AppCheck loads correctly on the initial load.

After TestFlight installation the AppCheck attestation passes and we are able to access our backend resources.

CodePush updates are signed with a private key, the affiliated public key is provided in the app's Info.plist.  The validity of the code signature is verified correctly when the update is downloaded.

After applying a code-push update, however, the App Check attestation fails and we are no longer able to access backend resources.

```shell
[FirebaseAuth][I-AUT000018] Error getting App Check token; using placeholder token instead. Error: Error Domain=com.apple.devicecheck.error Code=4 "(null)"
AppCheck failed: 'The operation couldn’t be completed. (com.apple.devicecheck.error error 4.)'

[FirebaseFirestore][I-FST000001] AppCheck failed: 'The operation couldn’t be completed. (com.apple.devicecheck.error error 4.)'
```
How should we configure react-native-code-push to push valid remote updates?

**Comment by MikhailSuendukov** [comment]
Hi @skam22, and thanks for reaching out to us. Judging by the logs you provided, you were unable to obtain a token after attestation. Could you please verify what kind of response you are receiving from the attestation request?

**Comment by skam22** [comment]
Strangely, after trying another archive / upload to testflight / and pushing an update via code-push the new build seems to be working with the AppCheck servers.  I'll wait for the token to expire before moving on.

With regards to the attestation response - that's handled automatically by the firebase SDK and the token is attached as a header to each subsequent request.  Since we're not calling it manually there's no response for me to see there.

The fact that we were receiving device check errors, however, tells me that the App Attest failed first, since DeviceCheck is a fallback option.  I'll keep my fingers crossed that it continues to work as expected with this new build.
