### ISSUE TITLE
Rollback after closing and re-opening the app

### ISSUE THREAD

**Issue by mhatami-ecotrak** [microsoft/react-native-code-push#2594]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
I use the snippet below behind a button to update the app
```
const status = await CodePush.sync({
        deploymentKey: CODE_PUSH_DEP_KEY,
        installMode: CodePush.InstallMode.IMMEDIATE,
        rollbackRetryOptions: {
          maxRetryAttempts: 5,
        }
      });
```
The app gets updated after a restart we can see the changes.
But as soon as we kill the app (iOS/ Android) and re-open the app, the changes are gone. And we cannot update again until we push a new update.
Sometimes the iOS app crashes after the re-open.

### Expected Behavior
We expect the changes be available after killing and re-opening the apps

### Actual Behavior
Changes go after re-opening the app.
<img width="597" alt="image" src="https://github.com/microsoft/react-native-code-push/assets/97941272/0f99f88a-904c-43dc-923a-c5a85e33255d">
<img width="485" alt="image" src="https://github.com/microsoft/react-native-code-push/assets/97941272/3f2043bd-0969-40f0-b979-55a30c9706cd">

- Although the changes are visible at least before closing the app, we can see the rollbacks are 1 and download is 1 but install is 0.

- Sometimes, after many tries the rollback doesn't happen. But it's not reliable.

- I also tried turning hermes on and off received the same results.

Do warnings cause rollbacks?

These are the logs after I run the sync function (But I don't kill the app)
After the internal restart by codepush I can literally see the changes.
The `checkCodePushUpdate` log is by me after the `sync` function is successfully ran I print its response. In this case it's `1` which means `UPDATE_INSTALLED`
```
[CodePush] Downloading package.
D  [CodePush] Applying full update.
I  [CodePush] Installing update.
D  [CodePush] Loading JS bundle from 
D  [CodePush] Restarting app
I  'checkCodePushUpdate', 1
```
After I kill & reopen the app I get these logs
```
D  [CodePush] Update did not finish loading the last time, rolling back to a previous version.
D  [CodePush] Loading JS bundle from "assets://index.android.bundle"
```
Note above logs are caught on android.

### Environment

* react-native-code-push version:  8.1.0
* react-native version: 0.72.5
* iOS/Android/Windows version: Latest
* Does this reproduce on a debug build or release build? Release (Couldn't reproduce on debug as it re-loads the bundles every time we open the app anyway)
* Does this reproduce on a simulator, or only on a physical device? Physical

(The more info the faster we will be able to address it!)

**Comment by mhatami-ecotrak** [comment]
This issue fixed by using `CodePush.notifyAppReady()`when the app starts to confirm the installation.
I didn't know that I have to call this piece of code.
Now my problem is resolved.

**Comment by vunl2000** [comment]
> This issue fixed by using `CodePush.notifyAppReady()`when the app starts to confirm the installation. I didn't know that I have to call this piece of code. Now my problem is resolved.

Hello. Can you tell me where to add? I tried in case DOWNLOADING_PACKAGE but still failed.

**Comment by xclidongbo** [comment]
> > This issue fixed by using `CodePush.notifyAppReady()`when the app starts to confirm the installation. I didn't know that I have to call this piece of code. Now my problem is resolved.
> 
> Hello. Can you tell me where to add? I tried in case DOWNLOADING_PACKAGE but still failed.

resolved it?
