### ISSUE TITLE
ReactNative with code-push AOS build [Error : Duplicate resources]

### ISSUE THREAD

**Issue by jihoon8730** [microsoft/react-native-code-push#2596]
I'm applying CodePush to React Native
I'm getting a build error on the Android side when finalizing the application.
I would appreciate it if you could take a look

**Error Message**
```
> Task :app:mergeReleaseResources FAILED
ERROR:[string/CodePushDeploymentKey] /Users/up/Desktop/project/coinpickle-app/android/app/src/main/res/values/strings.xml [string/CodePushDeploymentKey] /Users/up/Desktop/project/coinpickle-app/android/app/build/generated/res/resValues/release/values/gradleResValues.xml: Resource and asset merger: Duplicate resources

```

**Probable Cause**
I have code overlap in my CodePush setup

**Mycode**
```
1. strings.xml

<resources>
    <string name="app_name">XXXXXX</string>
    <string moduleConfig="true" name="CodePushDeploymentKey">XXXXXX</string> // Duplicate code here 
</resources>

2. gradleResValues.xml

<?xml version="1.0" encoding="utf-8"?>
<resources>

    <!-- Automatically generated file. DO NOT MODIFY -->

    <!-- Value from build type: debug -->
    <string name="CODE_PUSH_APK_BUILD_TIME" translatable="false">"1697169479092"</string>
    <!-- Value from build type: debug -->
    <string name="CodePushDeploymentKey" translatable="false"></string> // Duplicate code here 
    <!-- Value from default config. -->
    <integer name="react_native_dev_server_port">8081</integer>
    <!-- Value from default config. -->
    <integer name="react_native_inspector_proxy_port">8081</integer>

</resources>

```

```
app/build.gradle

 buildTypes {
        debug {
            signingConfig signingConfigs.debug
            resValue "string", "CodePushDeploymentKey", CODEPUSH_DEPLOYMENT_KEY_DEBUG
        }
        releaseStaging {
            initWith release
            resValue "string", "CodePushDeploymentKey", CODEPUSH_DEPLOYMENT_KEY_STAGING
            matchingFallbacks = ['release']
        }
        release {
            resValue "string", "CodePushDeploymentKey", CODEPUSH_DEPLOYMENT_KEY_PRODUCTION
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
```

**Tried**
1. Modify the configuration file
2. Delete duplicate code from sgrings.xml (another error occurs when deleting: R does not exit)
3. rebuild and build clean all

**Version**

"react-native-code-push": "^8.1.0",
"react-native": "0.71.10",
"appcenter": "^5.0.0",

```
    dependencies {
        classpath('com.android.tools.build:gradle:7.3.1')
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
```

**Desired**
Why duplicate code happens and how to fix it safely

I need help from experts and those who have encountered the error, please. ㅠ-ㅠ

**Comment by account-mhj** [comment]
check https://github.com/microsoft/react-native-code-push/issues/2497

**Comment by DmitriyKirakosyan** [comment]
Hi @jihoon8730, could you please test [this patch](https://github.com/microsoft/react-native-code-push/pull/2574) and let us know if it resolves the issue for you?

@account-mhj, thank you for pointing out the duplicate item.

**Comment by jihoon8730** [comment]
@DmitriyKirakosyan 
@account-mhj 

Thanks so much for the answer! 
In the issue you pointed out Clean build seems to be the main goal.
In fact, I tried it from the first GitHub issue you pointed me to, but it didn't work for me at all.
I'm still experiencing the same thing.

**Comment by haddad-yacine** [comment]
cd android
./gradlew clean

**Comment by sanduluca** [comment]
> Hi @jihoon8730, could you please test [this patch](https://github.com/microsoft/react-native-code-push/pull/2574) and let us know if it resolves the issue for you?
> 
> @account-mhj, thank you for pointing out the duplicate item.

This patch aims to solve other duplicate resource issue.

@jihoon8730 You have to either add the `CodePushDeploymentKey` in string (witch is global) or per build type. If you need it per build type just remove it from `strings.xml`

**Comment by jihoon8730** [comment]
Thank you all so much for your replies, I fixed the duplicate resource issue, but it was my mistake.
It was a duplicate issue with a completely different package from codepush. I fixed it and the build worked. Thank you so much!

**Comment by DmitriyKirakosyan** [comment]
@jihoon8730, it's awesome that you fixed the problem! Please share some details about what the issue was and how you solved it. This could be really helpful for others facing a similar problem. Thanks!

**Comment by jihoon8730** [comment]
@DmitriyKirakosyan 
In my case, a package called ImagePicker already existed, and the codepush related to ImagePicker also existed in the package bundler.
I deleted the part that declares the package related to the existing ImagePicker, and it was solved. I hope other people can check the case of conflicts with other packages, not just ImagePicker. Please understand if the translation is not smooth..^^)

**Comment by Guilherme03** [comment]
> @DmitriyKirakosyan In my case, a package called ImagePicker already existed, and the codepush related to ImagePicker also existed in the package bundler. I deleted the part that declares the package related to the existing ImagePicker, and it was solved. I hope other people can check the case of conflicts with other packages, not just ImagePicker. Please understand if the translation is not smooth..^^)

I have the same message error ( [string/CodePushDeploymentKey] ). Have tips to how to find possibles locations/package where has duplicates values ? Only reads the message error isn't enough to me.
