### ISSUE TITLE
Security Upgrade 

### ISSUE THREAD

**Issue by chirag-rakholiya** [microsoft/react-native-code-push#2597]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
We are waiting for this fix , is there any updates on the merge this security issue , 
[@sideway/formula from 3.0.0 to 3.0.1 ](https://github.com/microsoft/react-native-code-push/pull/2463)

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by chirag-rakholiya** [comment]
We are waiting for this fix , is there any updates on the merge this security issue ,
https://github.com/microsoft/react-native-code-push/pull/2463

**Comment by chirag-rakholiya** [comment]
@johnf @retyui

**Comment by johnf** [comment]
@chirag-rakholiya What's the issue and urgency here?
* This doesn't look like a security issue
* It's in the example code, not the library
* It's actually a sub-dependency, so if you `yarn upgrade` on your side it will get an update

**Comment by chirag-rakholiya** [comment]
@johnf thank you for the quick response, is it compatible with  react-native-codepush@7.1.0 ?

**Comment by DmitriyKirakosyan** [comment]
This PR is not relevant anymore, bot closed it. The package `@sideway/formula` has been already updated to 3.0.1.
