### ISSUE TITLE
The receivedBytes of DownloadProgress sometimes increases properly, but sometimes the value is smaller than the previous receivedBytes.

### ISSUE THREAD

**Issue by yunansworld** [microsoft/react-native-code-push#2611]
### Reproduction steps
1. Push the code to Mandatory.
2. Receive a code push from iOS. This doesn't happen on Android.
3. The receivedBytes of DownloadProgress sometimes increases properly, but sometimes the value is smaller than the previous receivedBytes.

### Expected behavior
What did you expect to happen? A value cannot be less than the previous receivedBytes.

### Actual Action
What actually happens? Sometimes receivedBytes is smaller than the previous receivedBytes, messing up the progress bar in the UI.

### environment
* React Native Code Push version: "react-native-code-push": "^7.1.0",
* React Native version: "react-native": "0.70.6",
* iOS/Android/Windows version: Reproduced only on iOS.
* Will this be reproduced in a debug or release build? yes
* Will it be reproduced in a simulator or only on a real device? It is also reproduced in the simulator.

**Comment by AnatolyPristensky** [comment]
Hello @yunansworld, could you please tell, how often it happens?

Sometimes fluctuating network conditions could cause this behavior. For instance, if the connection is lost and then re-established, the download might restart or continue from a previous point, causing the receivedBytes to decrease, also iOS may be caching responses or data in a way that doesn't happen on Android.

**Comment by AnatolyPristensky** [comment]
Closing due to the absence of activity.
