### ISSUE TITLE
ld: library not found for -lCodePush

### ISSUE THREAD

**Issue by vksgautam1986** [microsoft/react-native-code-push#2620]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
ld: library not found for -lCodePush
clang: error: linker command failed with exit code 1 (use -v to see invocation)
  STACK TRACE AND/OR SCREENSHOTS
![Screenshot 2023-11-20 at 12 59 59 PM](https://github.com/microsoft/react-native-code-push/assets/133006606/749f5c23-4419-49d9-9f09-7b59fea82f00)

```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment
System:
  OS: macOS 13.6
  CPU: (8) arm64 Apple M1
  Memory: 124.53 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.14.1
    path: ~/.nvm/versions/node/v16.14.1/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.5.0
    path: ~/Desktop/Caresmartz/AgencyMobileApplication/node_modules/.bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/netsmartz/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.4
    path: /Users/netsmartz/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.7
    wanted: 0.72.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

* react-native-code-push version: 8.1.0
* react-native version: 0.72.7
* iOS/Android/Windows version: MAC OS
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by vksgautam1986** [comment]
https://github.com/vksgautam1986/CodePushIssue
here is repro to reproduce this
git clone
yarn install
pod install and when you run this then we get this issue

**Comment by robbeman** [comment]
Maybe related: I am getting this error with Base64
> Library not found for -lBase64

Which is a dependency of codepush. So far no luck in solving this issue.

**Comment by vksgautam1986** [comment]
> Maybe related: I am getting this error with Base64
> 
> > Library not found for -lBase64
> 
> Which is a dependency of codepush. So far no luck in solving this issue.
> 
> EDIT: I may have made progress doing the following:
> 
> ```shell
> cd ios
> pod deintegrate
> rm -rf ./Pods
> rm -rf ./build
> rm -rf ./DerivedData
> 
> # important to do this AFTER removing all build cache and stuffs, sometimes it drags stuff along
> pod install
> ```

thanks , i forget to close this issue, the steps given you are working good to resolve these kind of issue

**Comment by robbeman** [comment]
FWIW, the steps above still failed in some cases for me.

I ended up locating the libBase64.a file in the build intermediates and manually copied them to `./ios/Libraries/libBase64.a` (and link them in xCode).

![image](https://github.com/microsoft/react-native-code-push/assets/3245659/070f1c4d-1b9c-4b98-8cd7-0c64f3d720e2)

This one 👇 
```
./ios/Build/Intermediates.noindex/ArchiveIntermediates/beta/BuildProductsPath/Release-iphoneos/Base64/libBase64.a
```
