### ISSUE TITLE
Delay in loading JS Bundle

### ISSUE THREAD

**Issue by alihamza1729** [microsoft/react-native-code-push#2623]
After a CodePush update, my app's JavaScript bundle is taking approximately 10 seconds to load, leading to a delay in the splash screen transition.

### Steps to Reproduce
1. Upgrade app from 0.71.1.x to 0.72.7
2. Open app from cold start on release mode
3. App takes more than 10 seconds to load JS bundle

### Expected Behavior
App should take 1-2 seconds to load app

### Actual Behavior
App takes more than 10 seconds before it starts to execute the Javascript in App.ts

```
  STACK TRACE AND/OR SCREENSHOTS
```

### Environment

* react-native-code-push:8.1.0
* react-native:0.72.7
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? Physical

**Comment by bilal-chaudhry** [comment]
@alihamza1729 
Examine your app/build.gradle file. In React Native version 0.72.7, the Hermes configuration has been eliminated. Consequently, your code push command cannot convert the JS bundle to bytecode through Hermes. 

To address this, insert the following code in the Gradle file and proceed to build again using the CodePush CLI or command:

project.ext.react = [
      enableHermes  :   true
]

**Comment by alihamza1729** [comment]
> @alihamza1729 Examine your app/build.gradle file. In React Native version 0.72.7, the Hermes configuration has been eliminated. Consequently, your code push command cannot convert the JS bundle to bytecode through Hermes.
> 
> To address this, insert the following code in the Gradle file and proceed to build again using the CodePush CLI or command:
> 
> project.ext.react = [ enableHermes : true ]

Thanks a lot, It worked for me, hero of the day

**Comment by Abdullah273** [comment]
> @alihamza1729 Examine your app/build.gradle file. In React Native version 0.72.7, the Hermes configuration has been eliminated. Consequently, your code push command cannot convert the JS bundle to bytecode through Hermes.
> 
> To address this, insert the following code in the Gradle file and proceed to build again using the CodePush CLI or command:
> 
> project.ext.react = [ enableHermes : true ]

Thanks!!!!! it works like a charm.

**Comment by AnatolyPristensky** [comment]
As solution has been found - I'm closing this issue.
