### ISSUE TITLE
RN 0.73 issue with 8.1.0 code push

### ISSUE THREAD

**Issue by vksgautam1986** [microsoft/react-native-code-push#2626]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
Android 
Error--- DevInternalSettings is not public in com.facebook.react.devsupport; cannot be accessed from outside package
import com.facebook.react.devsupport.DevInternalSettings;

 /Users/netsmartz/Desktop/0.72/MobileApplication/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java 

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:8.1.0
* react-native version:0.73.0-rc.6
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device? Simulator

(The more info the faster we will be able to address it!)
![Uploading Screenshot 2023-12-04 at 1.28.58 PM.png…]()

**Comment by domhacking** [comment]
I am facing the same issue as I have just upgraded to the same react-native version listed.

**Comment by recallwei** [comment]
Facing the same issue.

**Comment by VMagination** [comment]
temp package-patch should help till they release a patch for this

```
diff --git a/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java b/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java
index 923dd15..8394acb 100644
--- a/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java
+++ b/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java
@@ -10,7 +10,6 @@ import com.facebook.react.ReactPackage;
 import com.facebook.react.bridge.JavaScriptModule;
 import com.facebook.react.bridge.NativeModule;
 import com.facebook.react.bridge.ReactApplicationContext;
-import com.facebook.react.devsupport.DevInternalSettings;
 import com.facebook.react.devsupport.interfaces.DevSupportManager;
 import com.facebook.react.uimanager.ViewManager;
 
@@ -152,12 +151,11 @@ public class CodePush implements ReactPackage {
         if (instanceManager != null) {
             DevSupportManager devSupportManager = instanceManager.getDevSupportManager();
             if (devSupportManager != null) {
-                DevInternalSettings devInternalSettings = (DevInternalSettings)devSupportManager.getDevSettings();
-                Method[] methods = devInternalSettings.getClass().getMethods();
+                Method[] methods = devSupportManager.getDevSettings().getClass().getMethods();
                 for (Method m : methods) {
                     if (m.getName().equals("isReloadOnJSChangeEnabled")) {
                         try {
-                            return (boolean) m.invoke(devInternalSettings);
+                            return (boolean) m.invoke(devSupportManager.getDevSettings());
                         } catch (Exception x) {
                             return false;
                         }
```

**Comment by agusvazquez** [comment]
@VMagination solution worked for me! Thank you!

**Comment by vigneshwaran9494** [comment]
Same issue in with 8.1.1 code push too

**Comment by Kotpes** [comment]
This works great!
In case anyone's wondering how to apply patch: https://github.com/ds300/patch-package#readme

> temp patch-package should help till they release a patch for this
> 
> ```
> diff --git a/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java b/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java
> index 923dd15..8394acb 100644
> --- a/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java
> +++ b/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java
> @@ -10,7 +10,6 @@ import com.facebook.react.ReactPackage;
>  import com.facebook.react.bridge.JavaScriptModule;
>  import com.facebook.react.bridge.NativeModule;
>  import com.facebook.react.bridge.ReactApplicationContext;
> -import com.facebook.react.devsupport.DevInternalSettings;
>  import com.facebook.react.devsupport.interfaces.DevSupportManager;
>  import com.facebook.react.uimanager.ViewManager;
>  
> @@ -152,12 +151,11 @@ public class CodePush implements ReactPackage {
>          if (instanceManager != null) {
>              DevSupportManager devSupportManager = instanceManager.getDevSupportManager();
>              if (devSupportManager != null) {
> -                DevInternalSettings devInternalSettings = (DevInternalSettings)devSupportManager.getDevSettings();
> -                Method[] methods = devInternalSettings.getClass().getMethods();
> +                Method[] methods = devSupportManager.getDevSettings().getClass().getMethods();
>                  for (Method m : methods) {
>                      if (m.getName().equals("isReloadOnJSChangeEnabled")) {
>                          try {
> -                            return (boolean) m.invoke(devInternalSettings);
> +                            return (boolean) m.invoke(devSupportManager.getDevSettings());
>                          } catch (Exception x) {
>                              return false;
>                          }
> ```

**Comment by Dallas62** [comment]
#2617

**Comment by caiodeambrosio** [comment]
Same here =(

**Comment by nikolal** [comment]
Patch is working fine.

But it would be nice to merge this.

**Comment by MikhailSuendukov** [comment]
Hi everyone. Could you please confirm what this issue was resolved on latest version (8.2.1)?

**Comment by smithmallick149** [comment]
this issue still persists with react-native 0.73.7

**Comment by rafaelcorreiapoli** [comment]
Any solutions?

**Comment by DmitriyKirakosyan** [comment]
@smithmallick149 , @rafaelcorreiapoli , are you facing this error?

> Error--- DevInternalSettings is not public in com.facebook.react.devsupport; cannot be accessed from outside package
> import com.facebook.react.devsupport.DevInternalSettings;

What `react-native-code-push` version are you using?

**Comment by Ziad-Hossameldin** [comment]
I have the issue using RN 74.5 and latest code push
