### ISSUE TITLE
Unable to receive update on Release Mode 

### ISSUE THREAD

**Issue by rabindrachhachan** [microsoft/react-native-code-push#2627]
### Steps to Reproduce
Codepush  was working fine but after I integrated to below two libraries and making changes to build script . It is not working in release mode.  Below are current configurations.

1. "react-native-embrace": "3.14.0"
2. "@okta/okta-react-native": "2.2.0",

buildscript {
      ext {
          googlePlayServicesVersion = "17.0.0" // default: "+"
          firebaseMessagingVersion = "+" // default: "+"
          buildToolsVersion = "29.0.3"
          minSdkVersion = 21
          compileSdkVersion = 30 // was  29
          targetSdkVersion = 30 // was  29
          ndkVersion = "20.1.5948944"
      }
      repositories {
          mavenCentral()
          google()
          jcenter()
      }
      dependencies {
          classpath("com.android.tools.build:gradle:4.1.0")
          classpath 'com.google.gms:google-services:4.3.12'
          classpath 'com.google.firebase:perf-plugin:1.4.1'
          classpath "io.embrace:embrace-swazzler:${findProject(':react-native-embrace').properties['emb_android_sdk']}"
          // NOTE: Do not place your application dependencies here; they belong
          // in the individual module build.gradle files
      }
}

distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

I went through the embrace documentation and react native sdk changes log. They have  mentioned that they have fixed an issue related to codepush in version 2.0.1. I am using the higher version and updated SDK .  
2.0.1
December 24, 2019
Added a fix for CodePush integration on Android. This was addressed in the native Android SDK 4.0.0-beta7 and Swazzler 4.0.0-beta7. Please update your native SDK on Android . I have check deployment key and target  all are correct as it is working in debug mode. 

ReactNativeJS 'codepush update', 5
ReactNativeJS [CodePush] Reporting binary update (2.0.9)
ReactNativeJS[CodePush] Report status failed: {"appVersion":"2.0.9"}
ReactNativeJS 'codepush update', 3
ReactNativeJS [CodePush] false is not a function

### Expected Behavior
What you expected to happen?
It should work with any third party integration.

### Actual Behavior
What actually happens?
```
<img width="1016" alt="image" src="https://github.com/microsoft/react-native-code-push/assets/25128694/8b9a7817-037d-42bf-b60e-cbcdb0e34cbd">
```

### Reproducible Demo

* You can try with any example project with above integration.

### Environment

* react-native-code-push version: ^7.0.1
* react-native version:0.64.0
* iOS/Android/Windows version:  All platform and version
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device?  Both

(The more info the faster we will be able to address it!)

**Comment by MikhailSuendukov** [comment]
Hi @rabindrachhachan
Could you please confirm what this issue still persist on latest version (8.2.1)?

**Comment by AnatolyPristensky** [comment]
Hello @rabindrachhachan, we haven't heard from you for a while, so I'm closing this issue. Please, feel free to reopen it in case of new information.
