### ISSUE TITLE
Code Push not working

### ISSUE THREAD

**Issue by Vaib215** [microsoft/react-native-code-push#2628]
Any codepush update is not installed/downloaded on any device

### Steps to Reproduce
1. Make changes in code
2. Send codepush update on production
3. Check codepush install on dashboard

### Expected Behavior
The app should get updated for all the users

### Actual Behavior
No update gets pushed to user

![image](https://github.com/microsoft/react-native-code-push/assets/91018916/2d63c260-6fd4-4d29-a408-8d2816118cbd)

**Comment by SohaibKtb** [comment]
+1, updates are not showing on devices

**Comment by santiagogarzon** [comment]
+1. I'm seeing the same

**Comment by TheMakerOleguch** [comment]
Just to clarify, is react-native 0.72.x supported on Android?
On iOS all good

**Comment by velimir-jankovic** [comment]
We're currently looking into this.
Can you please tell me when did this exactly start to happen, and did you make any changes on your side?

Also let me know what version of react-native-code-push and react-native you are using, including the platform.

**Comment by Vaib215** [comment]
```
    "react-native-code-push": "^8.1.0",
    "react-native": "^0.72.3",
```

I don't remember when did it start to happen. I guess it was random

**Comment by velimir-jankovic** [comment]
Can you please contact our support: https://learn.microsoft.com/en-us/appcenter/help#accessing-app-center-free-support and share more information there? Please include your app name and deployment key that you are using.

**Comment by pratt3351** [comment]
i have error two.

when i called checkForUpdate function, codepush library gives me error message like this
"reader.readAsText is not a function (it is undefined)"

any updates..?

**Comment by MoamberRaza** [comment]
try to switch 0.73.1 react native and then try.

**Comment by hoangtrunnam** [comment]
i'm using react native: 0.72.5, 
react-native-code-push: 8.1.1

i downgrade react-native-code-push to 7.0.4 and it worked

**Comment by mununki** [comment]
@hoangtrunnam Did you downgrade it for Android too? I tried but it makes the compilation error on Android.

**Comment by hoangtrunnam** [comment]
@mununki mun
sorry. when I downgraded react-native-code-push to 7.0.4 and it just worked on IOS. android gets the error same as you.
then i upgraded to **"react-native-code-push": "8.0.0",** . and it really work both on IOS and Android.

"react-native-code-push": "8.0.0",
 "react-native": "0.72.5",

**Comment by mununki** [comment]
> @mununki mun sorry. when I downgraded react-native-code-push to 7.0.4 and it just worked on IOS. android gets the error same as you. then i upgraded to **"react-native-code-push": "8.0.0",** . and it really work both on IOS and Android.
> 
> can you test it? if it worked, pls let me know by reply this message
> 
> "react-native-code-push": "8.0.0", "react-native": "0.72.5",

Still having an issue. I opened new issue #2639

**Comment by AnatolyPristensky** [comment]
Hello, @mununki, I see that you resolved this issue with fix in https://github.com/microsoft/react-native-code-push/issues/2639#issuecomment-1893800684.

Also, I see reports that issue is gone in react-native-code-push 8.0.0, so closing this issue. Please, feel free to reopen it in case of new information.

**Comment by amanthegreatone** [comment]
pls check this i had this issue which was solved. https://github.com/microsoft/react-native-code-push/issues/2529#issuecomment-1968788585
