### ISSUE TITLE
App crashes after integrating code push in production build Android with TypeError: null is not an object (evaluating 'c.setTimeout')

### ISSUE THREAD

**Issue by MaratowKyryl** [microsoft/react-native-code-push#2629]
I'm trying to integrade CodePush in application. I've done implementation from official documentation from AppCenter (https://learn.microsoft.com/en-us/appcenter/distribution/codepush/rn-get-started#android-setup) as follow:

1. Added next lines in my android/settings.gradle at the end of a file:
```
include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
```
2. Added next line in `android/app/build.gradle` right after `react.gradle `task:
`apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"`
3. Added method to MainApplication.java:
```
@Override
      protected String getJSBundleFile() {
          return CodePush.getJSBundleFile();
      }
```
4. In android/app/src/main/res/values/strings.xml:
` <string moduleConfig="true" name="CodePushDeploymentKey">DeploymentKey</string>`
(Of course with my deployment key from AppCenter).

Application builds succesfuly in AppCenter. Downloaded build installs on device but crashes on attempt to open after SlashScreen.

### Steps to Reproduce
1. Integrate code push from documentation
2. Build release build
3. Download and install apk
4. Try to open 

### Expected Behavior
Application to work.

### Actual Behavior  
Application crach.

### Environment

* react-native-code-push version: 7.0.5
* react-native version: 0.67.5
* iOS/Android/Windows version: Android tested 13 and 11
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

There is some logged critical errors:
[logs.txt](https://github.com/microsoft/react-native-code-push/files/13612231/logs.txt)

(The more info the faster we will be able to address it!)

**Comment by pnthach95** [comment]
I read your log file
```
--------- beginning of crash
12-07 15:47:12.132 21785 21885 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
12-07 15:47:12.132 21785 21885 E AndroidRuntime: Process: com.shkolo.mobileapp, PID: 21785
12-07 15:47:12.132 21785 21885 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: null is not an object (evaluating 'c.setTimeout'), stack:
12-07 15:47:12.132 21785 21885 E AndroidRuntime: value@603:1388
12-07 15:47:12.132 21785 21885 E AndroidRuntime: <unknown>@602:2659
12-07 15:47:12.132 21785 21885 E AndroidRuntime: <unknown>@827:33937
12-07 15:47:12.132 21785 21885 E AndroidRuntime: <unknown>@827:126
12-07 15:47:12.132 21785 21885 E AndroidRuntime: <unknown>@827:239
12-07 15:47:12.132 21785 21885 E AndroidRuntime: h@2:1585
12-07 15:47:12.132 21785 21885 E AndroidRuntime: <unknown>@810:230
12-07 15:47:12.132 21785 21885 E AndroidRuntime: <unknown>@810:250
12-07 15:47:12.132 21785 21885 E AndroidRuntime: h@2:1585
12-07 15:47:12.132 21785 21885 E AndroidRuntime: <unknown>@799:940
12-07 15:47:12.132 21785 21885 E AndroidRuntime: <unknown>@803:44391
12-07 15:47:12.132 21785 21885 E AndroidRuntime: <unknown>@7:1525
12-07 15:47:12.132 21785 21885 E AndroidRuntime: h@2:1585
12-07 15:47:12.132 21785 21885 E AndroidRuntime: <unknown>@6:29
12-07 15:47:12.132 21785 21885 E AndroidRuntime: h@2:1585
12-07 15:47:12.132 21785 21885 E AndroidRuntime: d@2:958
12-07 15:47:12.132 21785 21885 E AndroidRuntime: global code@2824:3
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:211)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:300)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
12-07 15:47:12.132 21785 21885 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

You got `TypeError: null is not an object (evaluating 'c.setTimeout')`, it isn't CodePush error

**Comment by MaratowKyryl** [comment]
@pnthach95 Even so, there is another error related to SQLite before it. The problem is that I didn't changed anything else in project except those lines from description. All I did is follow the documentation to integrate CodePush. Before it worked correctly, that's definitely something in code push.

**Comment by pnthach95** [comment]
You use old version. Have you tried latest version? I don't have any problems with the latest

**Comment by MaratowKyryl** [comment]
@pnthach95 according to the documentation, 7.0.5 is the latest version that supports React Native 0.6. Although, there is a patch for version 8 of code push to work with RN 0.6 somewhere in opened issues (I'll find it if you're interested). I tried this case too,  the result is the same.

**Comment by MaratowKyryl** [comment]
@pnthach95 Just did so, there is almost the same set of errors in logs (SQLite, ENOENT etc) except for the last one `setTimeout` that cause crash.
