### ISSUE TITLE
【Android】Does the update process necessarily require the current activity to be in the onResume state?

### ISSUE THREAD

**Issue by H-Yongzi** [microsoft/react-native-code-push#2635]
### My Question

When the Android activity is in the onPause state, restartApp in the CodePushNativeModule class is called and finally enters the loadBundle. Will this cause some exceptions?
Or is it necessary that when entering restartApp, the current activity must be in the onResume state?

### Steps to Reproduce
1. open app；
2. check  update & download update
3. Call the restartApp function in the CodePushNativeModule class
4. At this time, the system permission request pop-up window will be displayed. and the Activity enters the onPause state.
5. At this point Android displays a white screen and remains in this state

STACK TRACE AND/OR SCREENSHOTS

![image](https://github.com/microsoft/react-native-code-push/assets/3264851/b16aad7c-98b9-4451-b2d9-a1056d9c3091)

**Comment by DmitriyKirakosyan** [comment]
@H-Yongzi, try checking the [CodePush logs](https://github.com/microsoft/react-native-code-push?tab=readme-ov-file#debugging--troubleshooting). If it downloads the update but fails to restart the app, try calling restartApp manually after dismissing the system alerts.
