### ISSUE TITLE
React Native Windows Images Disappear After Codepush

### ISSUE THREAD

**Issue by WilliamWelsh** [microsoft/react-native-code-push#2636]
## Steps to Reproduce
1. Create a C# React Native Windows app
2. Set up CodePush
3. Create an iOS app on AppCenter to use as project push

### Expected Behavior
Nothing to happen to my images

### Actual Behavior
All of my images disappear. I use `require("./assets/background.png")` for example

### Environment

* react-native-code-push version: 8.1.1
* react-native version: 0.72.4
* iOS/Android/Windows version: 0.72.10

I was using the guide below, which is the only link I've found to actually show start to finish for Windows. Even official Microsoft docs leave out setting up Windows on AppCenter, pushing Windows via the cli, and only showing the FULL steps for iOS/Android

https://devblogs.microsoft.com/react-native/rnw-codepush/

Here are my commands for pushing:

```
mkdir Bundle

npx --no-install react-native bundle --platform windows --entry-file index.js --bundle-output ./Bundle/index.windows.bundle --assets-dest ./Bundle --dev false --reset-cache

appcenter codepush release -a my/app -c .\Bundle -t 3.0.10 --mandatory true -d Production
```

**Comment by MikhailSuendukov** [comment]
HI @WilliamWelsh could you please confirm what this issue still persist on latest version (8.2.1)?

**Comment by projay11** [comment]
Hi this issue is happening for me as well using 8.2.1
