### ISSUE TITLE
App crashes after installing the new update on Android

### ISSUE THREAD

**Issue by abanoubamin** [microsoft/react-native-code-push#2641]
### Steps to Reproduce
1. Build and deploy a new code-push using this script `export version=$npm_package_version && appcenter codepush release-react -a App/app-android -t $version --description 'enhance' -d Production -m -x`
2. The app detects that there's a new build
3. Codepush installs the new update, then crashes

### Expected Behavior
The latest code-push update for Android should not cause the app to crash after installation.

### Actual Behavior
What actually happens?
```
The app crashes after installing a new code-push update on Android, which is unusual because previously, the app had restarted without crashing Android.
```

### Environment

* react-native-code-push version: `^8.1.0`
* react-native version: `0.71.14`
* iOS/Android/Windows version: `Android 13`
* Does this reproduce on a debug build or release build? release build

### Code snippets

```
const codePushOptions = { checkFrequency: codePush.CheckFrequency.MANUAL };
export default codePush(codePushOptions)(App);
```
![code](https://github.com/microsoft/react-native-code-push/assets/40027608/1d6d21e9-0207-4e12-b28a-9488f8f20246)

**Comment by abanoubamin** [comment]
My issue was related to Sentry and solved after upgrading `@sentry/react-native` to the latest version `5.15.2`

**Comment by krabbycrab** [comment]
does your solution work for react-native-cli too ?

**Comment by abanoubamin** [comment]
> react-native-cli

My project is already react-native-cli
