### ISSUE TITLE
No matching configuration of project :react-native-code-push was found.

### ISSUE THREAD

**Issue by ko-devHong** [microsoft/react-native-code-push#2642]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. https://reactnative.dev/docs/0.72/integration-with-existing-apps?language=kotlin
2. yarn add react-native-code-push
3. android set-up

### Expected Behavior
What you expected to happen?

Build successfully

### Actual Behavior
What actually happens?
```trace
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-code-push.
     Required by:
         project :app
      > No matching configuration of project :react-native-code-push was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.4.2', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - None of the consumable configurations have attributes.
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 8.1.1
* react-native version: 0.72.8
* iOS/Android/Windows version: 
* Does this reproduce on a debug build or release build? debug build 
* Does this reproduce on a simulator, or only on a physical device? simulator

(The more info the faster we will be able to address it!)

**Comment by uqmessias** [comment]
This is duplicated, please look at #2336

**Comment by uqmessias** [comment]
Also check to this issue with more info: #1873

**Comment by ko-devHong** [comment]
> This is duplicated, please look at #2336

I'm already set up. This error is different from me.

**Comment by ko-devHong** [comment]
> Also check to this issue with more info: #1873

It was same

**Comment by AnatolyPristensky** [comment]
Closing as duplicate https://github.com/microsoft/react-native-code-push/issues/1873.
