### ISSUE TITLE
Code push suddenly repeats "Network Request Failed"

### ISSUE THREAD

**Issue by ori9998** [microsoft/react-native-code-push#2645]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Start the app
2. When checking for update, it says "An unknown error occurred.
3. Emits [CodePush] Network request failed

### Expected Behavior
What you expected to happen?
It should check for update and start the app
This started an hour ago

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```
 LOG  [CodePush] Checking for update.
 LOG  [CodePush] An unknown error occurred.
 LOG  [CodePush] Network request failed

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 8.1.0
* react-native version: 0.71.6
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by ori9998** [comment]
Is anyone experiencing the same issue? My application is down and my customers are suffering. 
https://status.appcenter.ms/
appcenter status shows that it is operational...

**Comment by cwkeam** [comment]
Hi @ori9998 we are experiencing the same issue. We are seeing an SSL error in the AppCenter side.

**Comment by cwkeam** [comment]
@lucen-ms @DmitriyKirakosyan @Priskorn Apoloigies for the abrupt ping, but our whole service is down due to this issue.

**Comment by facucaramelpoint** [comment]
Same here ,IOS and Android on react native are not working. 

`"react-native-code-push": "^8.1.1"`
`"react-native": "0.71.8"`

**Comment by hubciorz** [comment]
Guys, they just didn't renew the TLS/SSL certificate 🫡

**Comment by angusryer** [comment]
Yep. Cert expired:

![image](https://github.com/microsoft/react-native-code-push/assets/46163463/b17d4c24-25ad-4fa1-99c2-86391132c264)

**Comment by kenithts** [comment]
Same here! Can we get more visibility to this issue?

**Comment by keijionga** [comment]
Same here
<img width="216" alt="image" src="https://github.com/microsoft/react-native-code-push/assets/22991823/ae63d8f7-2e43-419b-98dd-1ee4d94eb6e9">

**Comment by jeffinhk** [comment]
press likes on this post then more people should act upon this issue

**Comment by hubciorz** [comment]
> Same here! Can we get more visibility to this issue?

@kenithts Try to reach the support team:
<img width="327" alt="image" src="https://github.com/microsoft/react-native-code-push/assets/6502822/103f2a59-9adc-4e08-ab41-1d8a818cfa06">

**Comment by yunusemreayar** [comment]
any solution here?

**Comment by hubciorz** [comment]
> any solution here?

They need to renew the cert.

**Comment by hubciorz** [comment]
> Has anyone experienced a similar problem before? How long does it take to renew SSL certificates?

About a minute but they need to know about the problem first. Perhaps they didn't even get any notification on that since https://status.appcenter.ms/ shows that everything is fine...

**Comment by angusryer** [comment]
> > Has anyone experienced a similar problem before? How long does it take to renew SSL certificates?
> 
> About a minute but they need to know about the problem first. Perhaps they didn't even get any notification on that since https://status.appcenter.ms/ shows that everything is fine...

Maybe we should open an issue in a different repo and link this issue to it as well?

**Comment by hubciorz** [comment]
<img width="1061" alt="image" src="https://github.com/microsoft/react-native-code-push/assets/6502822/41c22ba2-587c-4927-b14c-6524d7453479">

**Comment by esthefanielanza** [comment]
I'm experiencing the same issue here, will contact support as well.

**Comment by burakgenc10** [comment]
I contacted support and they stated that they were having problems with the CodePush services. it will be resolved soon.

**Comment by hubciorz** [comment]
Yeah, but they started working on that only 2 minutes ago :/ 
<img width="706" alt="image" src="https://github.com/microsoft/react-native-code-push/assets/6502822/49f37b9c-2f10-4db0-babd-80cb20590b4c">

**Comment by lucen-ms** [comment]
We have rotated the expired certificate; we are sorry for any inconvenience.

**Comment by megabeehothanhminh** [comment]
@all should also check the code logic in that part. Because I also use codepush but I don't see this problem happening to me. I just give my opinion

**Comment by yunusemreayar** [comment]
> @ALL should also check the code logic in that part. Because I also use codepush but I don't see this problem happening to me. I just give my opinion

are you Friedrich Nietzsche ?

**Comment by hubciorz** [comment]
> @ALL should also check the code logic in that part. Because I also use codepush but I don't see this problem happening to me. I just give my opinion

Because it was fixed yesterday. That was a matter of an expired certificate and was not related to the code at all.

**Comment by songzuyun** [comment]
now, Same is happening to me
