### ISSUE TITLE
Android Crashing on Codepush for react native version 71.0 and codepush 8.0.2 for hermes build

### ISSUE THREAD

**Issue by Gautham495** [microsoft/react-native-code-push#2661]
Getting this error:

Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libhermes.so caused by: couldn't find DSO to load: libjsi.so caused by: couldn't find DSO to load: libfolly_runtime.so caused by: couldn't find DSO to load: libglog.so caused by: couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.app/lib-3/libc++_shared.so" is for EM_AARCH64 (183) instead of EM_X86_64 (62) result: 0 result: 0 result: 0 result: 0 result: 0 

### Steps to Reproduce
1. Create react native project version 71.0 and codepush 8.0.2
2. Hermes is enabled
3. New arch is disabled

### Expected Behavior
Once codepushed, the android app should receive the update and then update the app and restart.

### Actual Behavior
Once the update get received and the app updated the app crashes with the libhermes.so error.

### Environment

* react-native-code-push version: 8.0.2
* react-native version: 71.0
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? - In both
* Does this reproduce on a simulator, or only on a physical device? - In both

I searched around the internet but did not get an answer - also applied this but to no use

 implementation 'com.facebook.soloader:soloader:0.10.4+'

But iOS is working perfectly for same hermes build and disabled new arch.

Please provide a solution.

**Comment by basit-rayn** [comment]
Was it working fine before `8.0.2`? I mean is it working fine if we dont upgrade it to `8.0.2` from `8.0.1`?

**Comment by DmitriyKirakosyan** [comment]
@Gautham495, did it work for you previously? Have you recently updated React Native to version 0.71? Could you create a sample project to reproduce this issue?

**Comment by Gautham495** [comment]
It was working on version 8.0.2. It says libhermes.so and the 'lib' libraries not found and crashes.

**Comment by DmitriyKirakosyan** [comment]
If it was functioning correctly in version 8.0.2 before, could you detail any modifications made to your app that might have caused this issue to emerge? Have you updated React Native or any associated libraries?
