### ISSUE TITLE
was it tested and confirmed to work on RN0.73+?

### ISSUE THREAD

**Issue by pierroo** [microsoft/react-native-code-push#2669]
Used to work, no longer does since upgrading RN to 0.73+

### Steps to Reproduce
1. upgrade to RN0.73.4
2. no longer working for android

### Expected Behavior
to work

### Actual Behavior
doesn't work
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 8.2.1
* react-native version: 0.73.4
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? physical

Basically it was always working, now it no longer works since I upgraded to RN0.73
And yes I adjusted my MainActivity.kt file according to the new doc
I am using the multi deployment testing

also just to clarify the step 2 that says:

In your android/app/build.gradle file, add the codepush.gradle file as an additional build task definition to the end of the file:

...
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
...

should it literally be at the very end of the file?
I never had to put it at the very end before, but perhaps now it has to?

I see that the codepush is downloaded by users, but none is actually installed.
I have no clue why.

Is there any way to check on a release apk if something is going wrong?

I tried with adb logcat | find "codepush" 
but it gives nothing upon starting the app

**Comment by matthewadel** [comment]
yes it works pretty well with me

**Comment by djindal61** [comment]
We migrated the RN from 0.70.7bto 0.72.7

This is old version:
"react-native-code-push": "^7.0.4",
"react-native": "0.70.7",

This is new version:
"react-native": "0.72.4",
"react-native-code-push": "^8.2.0",

We are not able to push the code changes . New changes are not reflected ion android & iOS.

Please help us to clear out

Error: The uploaded package was not released because it is identical to the contents of the specified deployment's current release.

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue. Please let me know if anyone encounters any issues with RN 0.73.
