### ISSUE TITLE
Android plugin configuration README out of date

### ISSUE THREAD

**Issue by HenryStevens** [Microsoft/react-native-code-push#267]
import com.microsoft.codepush.react.CodePush;
    ....
    new CodePush("deployment-key-here", this, BuildConfig.DEBUG)

Should now be:

    import com.microsoft.codepush.react.CodePushReactPackage;
    ....
    new CodePushReactPackage("deployment-key-here", this, BuildConfig.DEBUG)

**Comment by HenryStevens** [comment]
Duplicate of #247

**Comment by lostintangent** [comment]
Which version of the CodePush plugin are you using? We actually just refactored our Java API to be more compatible with RNPM, which is why the docs updated. The `CodePushReactPackage` class no longer exists as of CodePush `v1.10.0-beta`.

**Comment by lostintangent** [comment]
If you upgrade to `v1.10.0-beta` of the CodePush plugin, it should be much more compatible with RNPM-based installations, and the README will reflect your setup experience.
