### ISSUE TITLE
Android app is crashing on taking mandatory codepush com.facebook.react.modules.core.ExceptionsManagerModule.reportException

### ISSUE THREAD

**Issue by vinayak-bm-ai** [microsoft/react-native-code-push#2670]
### Steps to Reproduce
1. Distribute a code push from the app center as mandatory for Android
2. Open the application on an Android device
3. App crash triggered

### Expected Behavior
App does not crash when we make code push mandatory.

### Actual Behavior
The Android app crashes when attempting to take codepush, but only if it's set to be mandatory. This started to happen when we upgraded to react-native-code-push 8.1.0 previously there were no crashes related to this.

## Crash Details
```
ExceptionsManagerModule.java line 72
com.facebook.react.modules.core.ExceptionsManagerModule.reportException

Fatal Exception: com.facebook.react.common.JavascriptException
Invariant Violation: This can happen if: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project. * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes, stack: anonymous@29:290 runApplication@132:1613 value@36:3866 anonymous@36:675 value@36:2510 value@36:646
```
<img width="1477" alt="Screenshot 2024-02-27 at 2 31 17 PM" src="https://github.com/microsoft/react-native-code-push/assets/130440988/115712fd-d0a7-4504-a261-e2ed6abc9ccd">

### Environment

* react-native-code-push version: 8.1.0
* react-native version: 0.71.13
* Android version: 10/11/12/13 
* Hermes Enabled
* New Arch: No

We tested this behavior, the release's crash-free rate suddenly drops when the code push is set to mandatory.

**Comment by jibinbajuMTN** [comment]
I am also facing the same issue with the version 8.1.1. app crashing after we download and install the latest air push updates.any updates on this?

**Comment by pierroo** [comment]
same here, if that matters

**Comment by 100sarthak100** [comment]
I'm getting same issue here, on "react native" : "^0.73.4" & "react-native-code-push": "^8.1.1"

**Comment by maqeelqureshi** [comment]
Same issue. Mandatory codepush is also not working.

react-native         0.73.4
react-native-code-push     8.2.1
node                                    21.6.2
appcenter-cli                         3.0.0
eas-cli                               7.3.0       
expo-cli                              6.3.10
npm                                   10.2.4
java               17.0.8

**Comment by DmitriyKirakosyan** [comment]
Thanks for bringing this to our attention. Unfortunately, I haven't been able to reproduce the issue on my end. Could you please provide a demo application that showcases the problem? This would greatly help in diagnosing and addressing the issue more effectively.

**Comment by jsh7195** [comment]
I was fine with version 8.1.0 but after I recently upgraded to 8.2.2, I get an error when installing it and it becomes a rollback.
"com.facebook.react.modules.core.ExceptionsManagerModule.reportException
ExceptionsManagerModule.java, line 65
com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: expected 0 arguments, got 1, js engine: hermes"

I changed it to 8.1.0 so it's okay, but it's an optional code push and as soon as I download it, I proceed with the installation...

**Comment by DmitriyKirakosyan** [comment]
@jsh7195, was the issue occurring only with mandatory updates, or could any update fail? Was it consistently crashing with every update, or was it happening only on specific Android devices?

**Comment by jlo1** [comment]
Hello, we're seeing the same error, when updating from v8.0 -> v8.3. @DmitriyKirakosyan , can we reopen?

```
com.facebook.react.common.JavascriptException: Error: Exception in HostFunction: java.lang.NullPointerException, js engine: hermes
```

**Comment by DhaivatKhanparaPanamax** [comment]
i am facing the same issue.

**Comment by DmitriyKirakosyan** [comment]
@DhaivatKhanparaPanamax , thanks for reaching out! Please answer to [these](https://github.com/microsoft/react-native-code-push/issues/2670/#issuecomment-2144565221) questions and provide more info about your project, including react-native and codepush versions you use.
Also please attach your crash log.

**Comment by DhaivatKhanparaPanamax** [comment]
It is occurring with both the updates. no update fails. yes  it consistently crashing with every update. In any android device it is crashing.

**Comment by DmitriyKirakosyan** [comment]
@DhaivatKhanparaPanamax , Thanks for your answers. Please share your crash log and codepush logs.

**Comment by jsh7195** [comment]
> @jsh7195, was the issue occurring only with mandatory updates, or could any update fail? Was it consistently crashing with every update, or was it happening only on specific Android devices?

I am so sorry for the late response.
It was not a required update. (no mandatory)
It only happens on Android( Galaxy flip, folder, etc.. and LG V40 model.).
