### ISSUE TITLE
Android Build Crashes 

### ISSUE THREAD

**Issue by rohit4812** [microsoft/react-native-code-push#2673]
We recently performed a code push build to address a JavaScript URL change. Surprisingly, the iOS version worked flawlessly, but the Android version consistently crashed. We attempted another code push for Android, which succeeded this time. However, some users are still experiencing crashes. As a next step, we did  a new app store build

Here are our questions: Would like to get more context on it

Code Push Availability: When a code push build is promoted to production, does it automatically become available to all users? We selected the option to install immediately. Still seeing crash reports from users on that build what could be the reason ?

Debugging Crashes: How can we effectively debug the code push build to identify the root cause of the crashes? Are there specific debugging methods we can leverage?"

<img width="1334" alt="Screenshot 2024-03-10 at 10 02 08 PM" src="https://github.com/microsoft/react-native-code-push/assets/13380530/f42970a1-6d66-444b-8db1-6ff7fa44a3de">

**Comment by DmitriyKirakosyan** [comment]
@rohit4812 , sorry for the late reply.

You can find the debug instructions in [Readme](https://github.com/microsoft/react-native-code-push?tab=readme-ov-file#debugging--troubleshooting).

> Code Push Availability: When a code push build is promoted to production, does it automatically become available to all users? We selected the option to install immediately. Still seeing crash reports from users on that build what could be the reason ?

Yes, it will be available for users. However, there is a known issue https://github.com/microsoft/react-native-code-push/issues/2527.
