### ISSUE TITLE
[Discussion] - Visual Studio App Center Retirement

### ISSUE THREAD

**Issue by flixyudh** [microsoft/react-native-code-push#2675]
Hi Code Push Team, I'm creating this because of AppCenter state the retirement of AppCenter services.
<img width="300" alt="Screen Shot 2024-03-15 at 10 28 01" src="https://github.com/microsoft/react-native-code-push/assets/19633881/b0d01bb6-d821-4d81-a7b6-805512afcbba">

Currently I'm using two services of AppCenter (Distributions and codepush). after reading the alternative solutions provided on [AppCenter site](https://learn.microsoft.com/en-us/appcenter/retirement#alternative-solutions). I've some questions mainly of `Distributions` and `codepush` section.

1. is there any other alternative rather than using [Apple’s TestFlight](https://developer.apple.com/testflight/)? quick search on google and found [diawi](https://www.diawi.com/), but I don't know if it's suitable as a Distribution services or not.

2. > We have prepared a special version of CodePush to integrate into your app and run independently from App Center. If you’d like to get access to the codebase of this CodePush standalone version, please reach out to our support team at [support@appcenter.ms](mailto:support@appcenter.ms) for more information.

What does the meaning of this statement? does App Center still accessible after retirement?
> _run independently **from**_ App Center

**Comment by minhnndev** [comment]
![img_v3_0290_2954e43d-9d04-4f59-8113-6fc4a41e83hu](https://github.com/microsoft/react-native-code-push/assets/45934641/5f6cb72a-5b21-4175-a2f6-90e49b7768b8)

I think and hope there will be another alternative version, AppCenter's retirement may be a move to separate AppCenter into a standalone application.

**Comment by huiqun922** [comment]
Write to app center team.
<img width="1291" alt="image" src="https://github.com/microsoft/react-native-code-push/assets/4495165/f54b5eaf-704d-4ca3-b253-2c9eb3940dff">

**Comment by glncy** [comment]
Hopefully they gonna release some timeline as soon as possible. We already chose codepush over expo update then I heard this news. Panics. Lol

**Comment by vagnerlandio** [comment]
Can we have our own server to store builds and continue using codepush to search for new updates on a new server instead of the Microsoft server?

I saw something about this in the codepush android api documentation -> https://github.com/microsoft/react-native-code-push/blob/master/docs/api-android.md#api-for-react-native-060-version-and-above

**Comment by flixyudh** [comment]
@vagnerlandio I've tried using this package https://github.com/lisong/code-push-server long time ago, I forgot why I stop research it, as I remember, their bundle isn't obfucasted yet (only minified).

**Comment by lucen-ms** [comment]
1. All our recommendations are described in the announcement (https://aka.ms/appcenter/retire) but of course it's up to you to check other alternatives.
2. Please see @huiqun922 message.

**Comment by flixyudh** [comment]
for `CodePush` service, I prefer to get an estimate time when `special version of CodePush` will be available if possible rather than spamming the email to [support@appcenter.ms](mailto:support@appcenter.ms). would you consider it @lucen-ms ?

**Comment by glncy** [comment]
Because of retirement, I just developed a package for custom server and cli. 

https://www.npmjs.com/package/expo-up
https://www.npmjs.com/package/expo-up-server

This uses expo updates package from expo.

**Comment by cbjs** [comment]
any update?

**Comment by htdcx** [comment]
Can try the server I just developed ,client use react-native-code-push
No need for expo
cli
https://github.com/htdcx/code-push-go

server
https://github.com/htdcx/code-push-server-go

**Comment by IgorPRibeiro** [comment]
Do I really need to use Expo-Update instead of CodePush? 
I have a super app built on an older version of React Native. Is there a way to use Expo-Update with that old version, or do I need to update the project to use Expo-Update?

**Comment by viper4595** [comment]
Does anyone try this?
- CLI: https://github.com/shm-open/code-push-cli
- Server: https://github.com/shm-open/code-push-server

**Comment by amdrade** [comment]
Any feedback on the alternative version of codePush?

**Comment by EavOutDom** [comment]
> Has anyone tried this?
> 
> * CLI: https://github.com/shm-open/code-push-cli
> * Server: https://github.com/shm-open/code-push-server

I tried but poor docs

**Comment by ferasabufares** [comment]
any update for  alternative of codePush 

any recommendation ?

**Comment by amdrade** [comment]
everyone waiting for the codePush team

**Comment by sauravBalodi1** [comment]
instead of codePush can we use Azure pipelines?
will it push the build automatically to app store or play store ?
@cbjs @huiqun922 @amdrade @vagnerlandio @flixyudh

**Comment by highRPM** [comment]
They say they have an independent code push ready, but when I email them, they say there's no progress yet. When are you going to provide an independent code push?

**Comment by GSFZamai** [comment]
> instead of codePush can we use Azure pipelines? will it push the build automatically to app store or play store ? @cbjs @huiqun922 @amdrade @vagnerlandio @flixyudh

Yes, it does.
But Code push don't send the code to AppStore ora PlayStore. 
The idea is to send codes updates (smal updates, hotfix, bugfix) without the need to send a new build to the store.
The updates can be done on background too while the user is using the app.

**Comment by vksgautam1** [comment]
> They say they have an independent code push ready, but when I email them, they say there's no progress yet. When are you going to provide an independent code push?

story of microsoft

**Comment by saransh-malik** [comment]
The last update I got from their team, is that the new version is almost ready and will soon be in testing, and should hopefully be available very soon.

**Comment by laumair** [comment]
> The last update I got from their team, is that the new version is almost ready and will soon be in testing, and should hopefully be available very soon.

When was this?

**Comment by jcgz100** [comment]
The Github repository is ready: https://github.com/microsoft/code-push-server

**Comment by gronxb** [comment]
If you’re looking for an alternative, check out: https://github.com/gronxb/hot-updater

It also supports the new architecture.

**Comment by joshuapinter** [comment]
For what it's worth we just switched from App Center to [revopush.org](https://revopush.org/). Took me about half a day to complete the migration and that's with our atypical app that started off life as a native Android app and has React Native added onto it afterwards.

We initially looked at hosting our own Code Push Server on Azure and were turned off by not the price but the complexity and nastiness of Azure's UI. It was painful.

Luckily we found revopush and were also considering [appzung.com](http://appzung.com/), which is mentioned as one of the comments. We tried out revopush first since it had a free tier and a lower price for our needs and it worked for us. I'd say check out both and go with what you think is the best fit.

Also, we had some questions and emailed support and they got back to us right away.

Thanks for making this change painless!

**Comment by gani-lw** [comment]
If you’re exploring a reliable CodePush alternative after App Center’s shutdown, AppsOnAir offers a seamless transition with a plug-and-play experience.

AppsOnAir is a drop-in replacement for CodePush, supporting the same SDK without requiring any workflow changes. Migration takes just a few minutes, simply switch the endpoint, and you’re ready to push real-time app updates, just like before.

Why AppsOnAir? It has no learning curve since it works exactly like CodePush, eliminating unnecessary rework.

You can push instant updates without app store approvals, ensuring a smooth update process.

AppsOnAir also provides full control and insights, allowing you to track deployments, rollbacks, and performance from a single dashboard.

Plus, it’s built for developers with a lightweight SDK and open-source flexibility, making integration effortless.

Whether you're a startup or an enterprise, AppsOnAir ensures your OTA updates continue without disruption.

Want to know more about our CodePush alternative? Visit: https://appsonair.com/codepush-alternative

**Comment by gani-lw** [comment]
> For what it's worth we just switched from App Center to [revopush.org](https://revopush.org/). Took me about half a day to complete the migration and that's with our atypical app that started off life as a native Android app and has React Native added onto it afterwards.
> 
> We initially looked at hosting our own Code Push Server on Azure and were turned off by not the price but the complexity and nastiness of Azure's UI. It was painful.
> 
> Luckily we found revopush and were also considering [appzung.com](http://appzung.com/), which is mentioned as one of the comments. We tried out revopush first since it had a free tier and a lower price for our needs and it worked for us. I'd say check out both and go with what you think is the best fit.
> 
> Also, we had some questions and emailed support and they got back to us right away.
> 
> Thanks for making this change painless!

@joshuapinter Please try AppsOnAir as well - https://appsonair.com/codepush-alternative

**Comment by Thor963** [comment]
With CodePush shutting down, it’s time to move to something better. Stallion isn’t just a replacement—it’s a next-gen OTA update solution built from scratch with modern React Native teams in mind. Check it out: https://stalliontech.io/

Why Stallion?
✔ Fully managed – No hosting/setup hassle
✔ Built-in testing – Switch between versions without new native builds (https://learn.stalliontech.io/docs/sdk/stallion-testing)
✔ Granular rollbacks – Supports both auto & manual rollbacks (with insights)
✔ Advanced analytics – Track adoption trends in real time
✔ Affordable – Extensive free plan & affordable pricing (https://stalliontech.io/pricing)

🚀 Migrating is easy – Follow our guide:
🔗 https://learn.stalliontech.io/blogs/react-native-ota-migration-codepush-appcenter-stallion

Future-proof your OTA workflow with Stallion!

**Comment by kit2o** [comment]
🚨 App center CodePush servers have officially been shut down.
This means you can no longer update your apps through CodePush.

To ensure uninterrupted app updates, migrate to Revopush today!

Here's a quick snapshot of Revopush's activity just for April:

✅ 800+ apps 
✅ 20K updates 
✅ 40M monthly active users 
✅ 100TB of bundle data

## 💈 Features

- Fully compatible with the existing CodePush SDK
- Supports the latest React Native versions and the New Architecture
- Multi-cloud architecture with a CDN for optimal delivery speed ([read our article](https://revopush.org/revopush-speeds-up-react-native-ota))
- A modern administration panel with team collaboration capabilities.
- Affordable [pricing](https://revopush.org/pricing) starting at just **$15**
- Seamless integration with popular CI/CD platforms
- Enhanced security and advanced analytics

## ☁️ Migration 

- Create your free account at [revopush.org](https://app.revopush.org/register)
- Read our [comprehensive guide](https://revopush.org/full-migration-guide-from-appcenter-codepush-to-revopush) on migrating your App Center applications
- Try the [Revopush SDK](https://github.com/revopush/react-native-code-push) for full support of the New Architecture
- Follow our CI/CD integration guide for [GitHub Actions](https://revopush.org/ci-cd-automation-with-codepush-and-github-actions), [Bitrise](https://revopush.org/ci-cd-automation-with-bitrise-codepush), or [CircleCI](https://revopush.org/ci-cd-automation-with-circleci-codepush)
