### ISSUE TITLE
CodePush rolling back the changes after app restarts even after successful update.

### ISSUE THREAD

**Issue by BilalBudhani** [Microsoft/react-native-code-push#269]
I'm facing an odd behaviour with CodePush. My app is distributed via TestFlight to our test users. I send them bug fixes and changes via CodePush. When the release is send via `code-push` command line, App clients receives the release, It also installs the release in the app successfully and everything is normal after this. But, Once the user removes the app from background, reopens it than the app version is back to the original test flight build. All the updates are gone. 

Also, There's no rollback metrics displayed on command line. The update is handled by `sync` method. Here's the code which is place in the root component of the app. 

```javascript
class Cgrn extends Component {
  componentDidMount() {
    codePush.sync({
      deploymentKey: CONSTANTS.DEPLOYMENT_KEY,
       updateDialog: {
        appendReleaseDescription: true,
        descriptionPrefix: "\n\nChange log:\n"
       },
       installMode: codePush.InstallMode.IMMEDIATE
    });
  }

  render() {
    return(<App />);
  }
};
```

**Comment by geof90** [comment]
@BilalBudhani Can I confirm that while releasing updates to CodePush, you did not also release a corresponding binary update to TestFlight? If a new version of the binary is downloaded from TestFlight, the jsbundle shipped with that binary would take precedence over any CodePush updates downloaded under the old binary version.

**Comment by BilalBudhani** [comment]
@geof90 I can confirm that no release to TestFlight was sent. All the updates were being sent via CodePush only.

**Comment by geof90** [comment]
@BilalBudhani Can you also confirm that you did steps 2 and 3 of https://github.com/Microsoft/react-native-code-push#plugin-configuration-ios? If that is not done, then the CodePush would install and run updates as they are downloaded but once the app process gets killed and restarted it would revert to loading `[[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"]` which is the version shipped in the binary.

**Comment by BilalBudhani** [comment]
@geof90 Yes, I've done that step as well. My `AppDelegate.m` file looks like this 
```objective-c
NSURL *jsCodeLocation;

#ifdef DEBUG
    jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif
```

**Comment by geof90** [comment]
@BilalBudhani That looks right. Do you ever see this issue show up when testing a "Release" build on the simulator? Or does it only ever happen when your binary is distributed via TestFlight?

Do you know of any other plugin/code your app is using that would be clearing away the files in [Application Support directory](https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/CodePush.m#L129)? That's where downloaded CodePush updates are stored.

The only place in our plugin code where we ever clear away old updates is https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/CodePush.m#L123, which theoretically will only ever get hit if a new version of the binary is installed causing the modified date of the binary's jsbundle to be different.

**Comment by BilalBudhani** [comment]
@geof90 I'm don't experience this while testing a "Release" build on simulator. This is something I've experienced on TestFlight only as of now. 

I don't have any code which is clearing away "Application Support Directory". Also, I don't think any of the plugins I'm using would be causing this. Here's is the list of plugins I'm using

```json
  "dependencies": {
    "react": "^0.14.7",
    "react-native": "^0.22.2",
    "react-native-code-push": "^1.9.0-beta",
    "react-native-device-info": "^0.9.0",
    "react-native-image-picker": "^0.18.3",
    "react-native-refreshable-listview": "git+https://github.com/jsdf/react-native-refreshable-listview.git",
    "react-native-vector-icons": "^1.3.0",
    "tcomb-form-native": "^0.4"
}
```

**Comment by BilalBudhani** [comment]
@geof90 I found the problem. Issue was from our side. There was a miscommunication between me and the other developer who releases the TestFlight builds. Turns out he was still uncommenting react native jsbundle part which was not needed before sending the build. I got that sorted with him and now everything is working as expected. 

Sorry for the inconvenience caused by me. I apologies for it. Closing the issue.

**Comment by lostintangent** [comment]
@BilalBudhani So happy to hear that you got it working correctly. Thanks for letting us know.

**Comment by avishayil** [comment]
Hi, sorry to open the issue again, but same happens here. Happens on Android on Production build, haven't tested on iOS production build yet.
Installing updates is going through, but after killing the task from the recent apps menu updates are gone.

**Comment by avishayil** [comment]
Hi, seems that I missed the part that says to wrap the root component with `MyApp = CodePush(MyApp);`
Everything seems to work correctly after this.
Hope it would help more fellows encountering this issue.

**Comment by silhouettes** [comment]
Thanks for updating with the fix @avishayil!

**Comment by krishlahoti1** [comment]
@avishayil  can u pls tell where did you place the content `MyApp = CodePush(MyApp);` in your application.
And after that, did u check that the app sticks to latest update and doesn't roll back to previous version?

**Comment by sujitpk-perennial** [comment]
@krishlahoti1  You can add this code to the root component as 

const codePushOptions = {
  checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.ON_NEXT_RESTART
}

AppName = codePush(codePushOptions)(AppName);
module.exports = AppName

**Comment by neildevas** [comment]
I'm facing a similar issue. I have an app downloaded on iOS from TestFlight, and I see that updates are installed successfully on the app. However, once I kill the app, the new changes no longer exist. This seems like intended behavior, but I'm not entirely sure why it's happening.

**Comment by jiaxiangcheng** [comment]
> [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"]

I am having the same issue. The codepush updates only survive one time. If I restart the app, the app is back to the testflight  version. Did you find the solution?
