### ISSUE TITLE
Js bundle null 

### ISSUE THREAD

**Issue by pranitabhurse** [microsoft/react-native-code-push#2692]
Error occurred: Error: Update is invalid - A JS bundle file named "null" could not be found within the downloaded contents. Please check that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.

**Comment by DmitriyKirakosyan** [comment]
Closing as duplicate of https://github.com/microsoft/react-native-code-push/issues/2083.
Please try this https://github.com/microsoft/react-native-code-push/issues/2083#issuecomment-1411745157
