### ISSUE TITLE
CodePush getBundleUrl is null

### ISSUE THREAD

**Issue by qingfeng** [Microsoft/react-native-code-push#27]
1. CodePushDeploymentKey set Staging key
2. code-push release gofire main.jsbundle 0.9.0

but `jsCodeLocation = [CodePush getBundleUrl];` is null

**Comment by lostintangent** [comment]
Hey qingfeng, did you make sure to add the #import statement for the CodePush headers at the top of your AppDelegate.m file? That would be unexpected for getBundleUrl to return nil, so I just want to double check what your setup looks like. Thanks so much for trying out the service and helping us find some bugs!

**Comment by qingfeng** [comment]
yes, #import "CodePush.h" to AppDelegate.m

**Comment by qingfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/18495/10888720/cd2062a6-81c8-11e5-80df-4fdc1eda585d.png)

**Comment by lostintangent** [comment]
When you added the `CodePushDeploymentKey` key to your `Info.plist` file, did you set its value to `Staging` or to the actual key value for the Staging deployment? (which you can collect by running `code-push deployment ls gofire`)

**Comment by qingfeng** [comment]
yes CodePushDeploymentKey into Info.plist

![image](https://cloud.githubusercontent.com/assets/18495/10888957/0293d750-81ca-11e5-9d28-8bc3b79f5ae4.png)

**Comment by lostintangent** [comment]
Hmm, interesting. Are you running this on the simulator or device? And which version of iOS? 9.1? Sorry for the hundred questions, I'm just trying to narrow this down, since we haven't seen it before.

**Comment by qingfeng** [comment]
simulator or device will not work, and iOS 8

**Comment by qingfeng** [comment]
```
(*'-') < code-push deployment ls gofire                                                                                            15-11-03 1:17
┌────────────┬──────────────────────────────────────┐
│ Name       │ Deployment Key                       │
├────────────┼──────────────────────────────────────┤
│ Production │ a4ec189d-xxxxxx │
├────────────┼──────────────────────────────────────┤
│ Staging    │ 85181c72-xxxxxxxxx │
└────────────┴──────────────────────────────────────┘
``

**Comment by lostintangent** [comment]
Is the JS bundle that you generated and packaged with the binary named `main.jsbundle`? We currently hardcode that expectation (soon to change), so that would explain the nil if you had named the bundle file differently.

**Comment by qingfeng** [comment]
I run command:
```
react-native bundle --minify --out main.jsbundle
code-push release gofire main.jsbundle 0.9.0 
```

**Comment by lostintangent** [comment]
Hmm, interesting. I'm downloading an iOS 8 simulator image to see if that is related, since I'm not able to repro this issue. While I'm doing that, could you confirm two more things:

1. Have you actually applied an update to the app locally? I see that you released one via the CLI, but has your app detected it and applied it?

2. If you change your jsLocation statement in your AppDelegate.m back to the standard production one, does that work? I'm assuming it does, but I just want to double check.

Finally, could you update the plugin? We released a new version on Friday that contain some bug fixes that may be related to this (`npm install react-native-code-push`). If you already have the latest (1.1.0-beta) then disregard this comment :)

**Comment by qingfeng** [comment]
I put into the project main.jsbundle on ok, Up and running
![image](https://cloud.githubusercontent.com/assets/18495/10890237/d0e93918-81d1-11e5-9f5f-68e38bce7aea.png)

NSLog(@"[CodePush getBundleUrl] %@", [CodePush getBundleUrl]);
`2015-11-03 02:22:32.369 gouhuo-native[2115:712575] [CodePush getBundleUrl] file:///private/var/mobile/Containers/Bundle/Application/0BCA7B0F-7011-41A0-B848-6D792EF9027F/gouhuo-native.app/main.jsbundle`

is OK?

**Comment by lostintangent** [comment]
That looks correct! Yeah apologies, the app expects for your initial bundle file to be included in the project. We should update the docs to be more clear here.

**Comment by qingfeng** [comment]
CodePush.sync() reason:

```
2015-11-03 02:35:11.560 [info][tid:com.facebook.React.JavaScript] 'reason', [Error: 400: An update check must include a deployment key, and provide a semver compliant app version]
```

**Comment by lostintangent** [comment]
Is the `CFBundleShortVersionString` key in your `Info.plist` set to a valid semver string? (e.g. 0.9.0) Right now, we require that in order to work, so if your `Info.plist` file sets this to just a major or a major and a minor, you'll get that error. We're going to relax it, but that it the current behavior. Your `code-push release` example showed the use of `0.9.0`, so just make sure your iOS app is consistent with that.

We recently added this requirement to the docs, but I agree its somewhat confusing.

**Comment by qingfeng** [comment]
sorry, i change CFBundleShortVersionString to 0.9.0 is work

but, click install
![image](https://cloud.githubusercontent.com/assets/18495/10891244/bf583162-81d7-11e5-9605-e230f39825ca.png)

after error
![slack for ios upload](https://cloud.githubusercontent.com/assets/18495/10891332/530d45a0-81d8-11e5-9b17-cadf89a3fb17.png)

It may be "篝火" These two Chinese characters sake?

**Comment by lostintangent** [comment]
No reason to be sorry! I want us to relax this requirement so it just works without needing to use a patch version in your semver string.

Hmm, is "篝火" the name of the app? What is the component name you pass to the AppRegistry call?

**Comment by qingfeng** [comment]
https://github.com/Microsoft/react-native-code-push/blob/a208afe7a1f96cc5852e2481ae00a725eac7a668/CodePushConfig.m#L18

`NSString *rootComponent = [infoDictionary objectForKey:@"CFBundleName"];`
my app `CFBundleName` is `篝火`, My local modify `gouhuo-native` is run

**Comment by geof90** [comment]
Hi @qingfeng, the error looks like React Native is expecting the "篝火" root component to be registered, but it wasn't. Specifically, if in your ```AppDelegate.m```, the ```RCTRootView``` is initialized with that module name,

```objectivec
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"篝火"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
```

Then in the javascript bundle, that same module name has to be registered. In other words, it has to contain this matching line:

```javascript
AppRegistry.registerComponent("篝火", () => CodePushDemoApp);
```

Could we just double confirm with you that this is indeed the case and it is done correctly?

**Comment by qingfeng** [comment]
So, I try! thanks @geof90 
the service is cool :beer:

**Comment by geof90** [comment]
Thanks @qingfeng! I guess it all worked out for you? If so I will close the issue. Thanks nonetheless for your feedback!

**Comment by qingfeng** [comment]
thanks :beer:

**Comment by lostintangent** [comment]
We fixed the issue where CodePush assumes your root component is named the same as the CFBundleName key in your Info.plist, so in the future, this issue should be less prevalent. Thanks qingfeng!

**Comment by qingfeng** [comment]
@lostintangent :beers:
