### ISSUE TITLE
 ERROR  Warning: Component "CodePushComponent" contains the string ref "rootComponent"

### ISSUE THREAD

**Issue by indobenua** [microsoft/react-native-code-push#2701]
ERROR  Warning: Component "CodePushComponent" contains the string ref "rootComponent". Support for string refs will be removed in a future major release. We recommend using useRef() or createRef() instead. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-string-ref
    in CodePushComponent
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer

My app
react-native info
installed: 0.74.1

node -v
v20.12.2

npm -v
10.5.0

code-push -v
3.0.0

**Comment by fmedinaUtoppia** [comment]
<img width="662" alt="Screenshot 2024-06-05 at 3 53 07 PM" src="https://github.com/microsoft/react-native-code-push/assets/159460105/2d4e0d73-6597-4c98-acaa-fe99805d61f0">

I guess this the reference. This is in CodePush.js from react-native-code-push from node_modules

**Comment by MikhailSuendukov** [comment]
Hi, could you please clarify how I can reproduce the output of this warning in the console?

**Comment by DmitriyKirakosyan** [comment]
The fix has been released.
