### ISSUE TITLE
[iOS] Code push back initial release after update ios version

### ISSUE THREAD

**Issue by amdrade** [microsoft/react-native-code-push#2702]
The app was working correctly with codepush, after updating the iOS version 16.7.7 to 16.7.8, the app returns to the initial version from when it was published in the apple store. 
When generating a new release, the app updates normally.

**Steps to Reproduce**
Release an update
Close / reopen the app
Update iOS version

**Expected Behavior**
App should load the updated bundle

**Actual Behavior**
What actually happens?
The app returns to the initial version from when it was published in the apple store and load the binary bundle.

**Environment**
react-native-code-push version: 7.0.1
react-native version: 0.65.3
iOS/Android/Windows version: iOS 16.8
Does this reproduce on a debug build or release build? release
Does this reproduce on a simulator, or only on a physical device? physical device

**Comment by tiendnvietis** [comment]
Ensure that you configure your release scheme with the correct values. To verify this, navigate to Build Settings and locate Apple Clang - Preprocessing. Check the Preprocessor Macros section. Confirm that the DEBUG=1 macro is not set for your release scheme (typically the default 'Release' scheme or any custom scheme you have created).
![Screenshot 2024-05-30 at 11 09 46](https://github.com/microsoft/react-native-code-push/assets/162114329/d126b5d5-1d0e-4c59-a019-fa31765e960e).

**Comment by amdrade** [comment]
Configuration is OK

![image](https://github.com/microsoft/react-native-code-push/assets/5581309/2cc7bdc3-8f7b-4741-a22f-f3dfef9a353c)

**Comment by DordeDimitrijev** [comment]
Hi [@amdrade](https://github.com/amdrade) thank you for reaching out. Please make sure your Appdelage.m implementation is as stated in the [docs](https://github.com/microsoft/react-native-code-push/blob/master/docs/setup-ios.md#ios-setup)

```
- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [CodePush bundleURL];
#endif
}
```
If everything is set according to the docs it'd be great if you could share a small demo app which can be used to reproduce this issue.

Could you confirm whether the rollbacks are occurring exclusively on iOS updates, if so does it only happen for updates from 16.7.7 to 16.7.8 or for all IOS device updates?

**Comment by DordeDimitrijev** [comment]
Closing due inactivity.

**Comment by amdrade** [comment]
Appdelage.m its OK

**Comment by DordeDimitrijev** [comment]
Could you please share a demo app  since I am unable to reproduce this issue, if not could you share [logs]?(https://github.com/microsoft/react-native-code-push?tab=readme-ov-file#debugging--troubleshooting)

**Comment by nguyenductoan1995** [comment]
@amdrade  Have you fixed this problem, can you share how to fix it I am having the same problem
