### ISSUE TITLE
babelHelpers.asyncToGenerator is not a function

### ISSUE THREAD

**Issue by niftylettuce** [Microsoft/react-native-code-push#271]
Hey — I'm on RN v0.21.0 using Code Push v1.10.0-beta, and as soon as I add the line `import codePush from 'react-native-code-push';` into my project, I receive the error `babelHelpers.asyncToGenerator is not a function`.  I found this issue which makes me think @brentvatne might know the solution per https://github.com/facebook/react-native/issues/4844.  The contents of my `.babelrc` are as follows:

```
{
  "presets": [ "react-native", "stage-0" ],
  "plugins": [
    "transform-decorators-legacy",
    "transform-async-to-generator"
  ]
}
```

**Comment by niftylettuce** [comment]
![screen shot 2016-03-31 at 11 12 03 am](https://cloud.githubusercontent.com/assets/523141/14182585/dde7bf62-f739-11e5-8bd4-b82673d7c548.png)

**Comment by lostintangent** [comment]
@niftylettuce This isn't a bug with CodePush, but rather, an issue with the packager when you use a custom Babelrc file. CodePush uses async/await and unfortunately this ends up causing issues, as you've seen with the linked bug. You would hit this issue if using any other library that uses async/await. The only solution that we've found it to either remove your custom babelrc or update the packager's Babel helpers file as mentioned in the RN bug you mentioned.

**Comment by niftylettuce** [comment]
I resolved, here was my new `.babelrc` file:

```
{
  "presets": [ "react-native" ],
  "plugins": [
    "transform-decorators-legacy",
    "transform-do-expressions",
    "transform-function-bind",
    "transform-class-constructor-call",
    "transform-export-extensions",
    "syntax-trailing-function-commas",
    "transform-exponentiation-operator"
  ]
}
```

I also ran the packager with `--reset-cache` to work: `node_modules/react-native/packager/packager.sh --reset-cache`.

Thank you and also thanks to @skevy for help over Slack in [ExponentJS](https://slack.exponentjs.com/).

**Comment by skevy** [comment]
For further information, see here: https://github.com/facebook/react-native/issues/4844#issuecomment-204035720

**Comment by dayudodo** [comment]
I found maybe is the watchman problem, I use the react 0.41.2, it occured this issue, because I install the stage-0, error, so uninstall it, but still. finally, I delete all the project and git clone again, error still their! but same project is good at my PC! so, watchman watch-del-all, rebuild, everything OK!
ultimate solution 
```
brew uninstall watchman
```

**Comment by htxiong** [comment]
@niftylettuce thanks, your solution works for me.
