### ISSUE TITLE
Looks like the Security vulnerability due to using com.nimbusds:nimbus-jose-jwt still exists

### ISSUE THREAD

**Issue by sizhe-eb** [microsoft/react-native-code-push#2714]
### Steps to Reproduce
We are using the MobSF platform to do a static analysis and got "The App uses the encryption mode CBC with PKCS5/PKCS7 padding. This configuration is vulnerable to padding oracle attacks." warning. And it's related to these two files:
- com/nimbusds/jose/crypto/impl/AESCBC.java
- com/nimbusds/jose/jca/JCASupport.java

Upgrade the react-naive-code-push to the latest version 8.2.2, this warning is still exist. But disappear after removing it form the project.

### Expected Behavior
The warning should disappear with the latest version 8.2.2

### Reproducible Demo
![image](https://github.com/microsoft/react-native-code-push/assets/62536400/d77eab85-1e1c-4a20-80cc-a1e19aa18ac0)

### Environment

* react-native-code-push version: v8.2.2
* react-native version: 0.74.1
* iOS/Android/Windows version: SDK34
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device?

**Comment by DordeDimitrijev** [comment]
Hello @sizhe-eb thank you for reaching out. I tried to use mobSF tool but wasn't able to set it up on my demo app. On the other hand I saw there were some vulnerabilities with dependencies of  _com.nimbusds:nimbus-jose-jwt_  library so I bumped it to latest version. Here is the [link](https://github.com/microsoft/react-native-code-push/tree/fix-vulnerability) to the changes, please let me know if it resolves the issue for you so we can create a PR for this.

**Comment by sizhe-eb** [comment]
Hi @DordeDimitrijev, thanks for your reply!
I just followed your commit and changed to `com.nimbusds:nimbus-jose-jwt:9.40`, but the vulnerability still exists.
I think it's still related to the `com.nimbusds:nimbus-jose-jwt` library. 

https://github.com/felx/nimbus-jose-jwt/blob/master/src/main/java/com/nimbusds/jose/jca/JCASupport.java
https://github.com/felx/nimbus-jose-jwt/blob/master/src/main/java/com/nimbusds/jose/crypto/AESCBC.java
```
// JCASupport.java
...
public static boolean isSupported(final EncryptionMethod enc, final Provider provider) {

		if (EncryptionMethod.Family.AES_CBC_HMAC_SHA.contains(enc)) {
			...
			try {
				Cipher.getInstance("AES/CBC/PKCS5Padding", provider);  // <----- this line
			}
                         ...
		}
...
```
```
// AESCBC.java
...
private static Cipher createAESCBCCipher(final SecretKey secretKey,
		                                 final boolean forEncryption,
		                                 final byte[] iv,
		                                 final Provider provider)
		throws JOSEException {

		Cipher cipher;

		try {
                         // This line
			cipher = CipherHelper.getInstance("AES/CBC/PKCS5Padding", provider);
			...

		} catch (Exception e) {

			throw new JOSEException(e.getMessage(), e);
		}

		return cipher;
	}
...
```
https://docs.oracle.com/javase/8/docs/api/javax/crypto/Cipher.html

CBC mode has no integrity and authentication, I think it's better to use AES-GCM which is in TLS 1.3 has an authenticated encryption scheme that provides both integrity and authentication.

Replacing `AES/CBC/PKCS5Padding` with `AES/GCM/NoPadding` may resolve this vulnerability.

**Comment by DordeDimitrijev** [comment]
Hello @sizhe-eb  thank you for reaching out. In our codebase we don't use any of those classes so I propose that you open an issue on the official [repo](https://bitbucket.org/connect2id/nimbus-jose-jwt/issues?status=new&status=open&status=submitted) of nimbus-jose-wt so they can fix the vulnerability on their side. Let us know when they do and we'll gladly update the library to the latest version to fix the vulnerability.

**Comment by sizhe-eb** [comment]
Hi @DordeDimitrijev,
I created an issue on the `nimbus-jose-jwt` repo, and will continue to follow up on this issue.
You can refer to https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/556/the-encryption-mode-cbc-with-pkcs5-pkcs7
