### ISSUE TITLE
Android crashes as soon as app opened (production bundle build)

### ISSUE THREAD

**Issue by niftylettuce** [Microsoft/react-native-code-push#272]

**Comment by lostintangent** [comment]
How are you running the app? "react-native run-android"? When you say that it's a production bundle build, do you mean that you actually did a release build of the APK or that you explicitly disabled developer support in your MainActivity? If the latter, then the RN build scripts don't generate the binary bundle by default in a debug build, and so your app will crash because it can't find the JS bundle. 

If that is in fact the problem, you should be able to remove the "getJSBundleFile" method entirely from your MainActivity (to remove the use of CodePush), and still see the same issue,.

**Comment by niftylettuce** [comment]
So I need to release one version to Code Push first in order for my app to stop crashing since it can't find a JS Bundle or something?

**Comment by lostintangent** [comment]
Nope, but your APK needs to contain a JS bundle. As I mentioned, by default, RN doesn't generate the JS bundle in the APK when doing a debug build (it assumes you're using the packager), so if you're running `react-native run-android`, you are doing a debug build and your APK won't actually include a JS bundle file to run. That isn't a CodePush issue, and would manifest itself if you removed CodePush entirely as well.

There are two solutions:

1. Do an actual release build
2. Modify the `android\app\react.gradle` file to enable generating the APK-bundled JS bundle file even in debug builds. Simply changing [this line](https://github.com/facebook/react-native/blob/a7cde8045ba10d67896cc5b203d397eaf4f395d6/react.gradle#L82) to `enabled true` would do the trick.

Let me know if either of those work for you. If not, it would be helpful if you could remove the `getJSBundleFile` method from your `MainActivity` file and see if the issue still occurs.

**Comment by niftylettuce** [comment]
What does the JS Bundle compare itself to when you check for updates?  Let's say I haven't released a version to Code Push yet -- I run gradle commands here, sign the app, and install it on a device.  https://gist.github.com/marty-wang/5a71e9d0a6a2c6d6263c.  Do I need to explicitly say the version I have on the device through JS or something?

**Comment by lostintangent** [comment]
As long as you did step 3 [here](https://github.com/facebook/react-native/blob/a7cde8045ba10d67896cc5b203d397eaf4f395d6/react.gradle#L82), the CodePush plugin will compare the contents of the binary against the latest update on the server. If you don't do this step, then the client will simply assume any update that is available in the configured CodePush deployment, and is eligible for the requesting client (e.g. the `targetBinaryVersion` matches, and the release isn't marked as disabled) is available.

**Comment by niftylettuce** [comment]
I used `rnpm` to install it, so I'm assuming it worked.  I also edited my app's `MainActivity.java` file to add/replace the line with `CodePush` being added under list package (and added my deployment key in there in quotes).

**Comment by niftylettuce** [comment]
Here's adb logcat, the bug persists with bundled builds somehow, is the packager cache not cleared for bundler?  This is incredibly frustrating.

```log
03-31 14:19:16.527 21131 21152 E ReactNativeJS: undefined is not a function (evaluating 'babelHelpers.asyncToGenerator')
03-31 14:19:16.534 21131 21153 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-31 14:19:16.534 21131 21153 E AndroidRuntime: Process: com.myapp, PID: 21131
03-31 14:19:16.534 21131 21153 E AndroidRuntime: Theme: themes:{}
03-31 14:19:16.534 21131 21153 E AndroidRuntime: com.facebook.react.modules.core.JavascriptException: undefined is not a function (evaluating 'babelHelpers.asyncToGenerator'), stack:
```

**Comment by niftylettuce** [comment]
See https://github.com/Microsoft/react-native-code-push/issues/271 for how I resolved it in debug/developer mode - but for some reason it still persists with these bundled releases.

**Comment by lostintangent** [comment]
I just updated our README to mention the custom gradle as part of the RNPM installation path. I didn't realize that was missing. Apologies!

**Comment by niftylettuce** [comment]
@lostintangent Still same issue after modifying/updating readme.

**Comment by niftylettuce** [comment]
Is this using its own version of `.babelrc` or something? https://github.com/Microsoft/react-native-code-push/blob/master/android/codepush.gradle#L54

**Comment by lostintangent** [comment]
Yeah sorry, my readme comment was about the gradle file step missing from the RNPM installation steps.

And no, we don't have our own babelrc file. I'll have to investigate why you're still hitting this issue, but I don't suspect that it's a CodePush issue, as opposed to an RN issue with your custom babelrc.

**Comment by niftylettuce** [comment]
@lostintangent Is it because the `code-push` dependency of `react-native-code-push@v1.10.0-beta` is `1.8.0-beta` instead of `1.9+`?

**Comment by geof90** [comment]
@niftylettuce The [code-push dependency is correct](http://npmjs.com/package/code-push), its the latest on NPM.

Have you tried @skevy's other recommendation of using `babel-preset-react-native-stage-0`?

> I've gone ahead and packaged this up into ANOTHER, unofficial babel-preset, called babel-preset-react-native-stage-0.
> 
> To use, simply npm install babel-preset-react-native-stage-0 --save and put
> 
> { presets: ['react-native-stage-0'] }

**Comment by niftylettuce** [comment]
yeah, I've used that.  Thing is I don't know how to clear the release/bundle cache.  I tried on a fresh `react-native init` and added code push and it worked fine.

**Comment by niftylettuce** [comment]
Could it  be because contents of my `index.android.js are `require('./src');`?

**Comment by geof90** [comment]
@niftylettuce have you tried deleting the entire contents of the android/build folder?

**Comment by niftylettuce** [comment]
@geof90 yeah

**Comment by niftylettuce** [comment]
Not sure if it makes a difference, but the clean/fresh `react native init` was v0.22.2 and the version I'm working with and running into this error with is v0.21.0

**Comment by geof90** [comment]
How about doing `rm -fr $TMPDIR/react-*`?

**Comment by niftylettuce** [comment]
Tried that too, and `watchman del all` thing -- and killed all processes with node/watchman

**Comment by geof90** [comment]
Just to help me understand the problem, what do u mean by a "production bundle build"? Are u following these steps https://facebook.github.io/react-native/docs/signed-apk-android.html#content to generate and run a release APK?

**Comment by niftylettuce** [comment]
I'm following this https://gist.github.com/marty-wang/5a71e9d0a6a2c6d6263c - same thing pretty much @geof90

**Comment by niftylettuce** [comment]
(I skip step 1)

**Comment by niftylettuce** [comment]
OK got it working.  I upgraded to latest RN v0.22.2, cleared node_modules, killed watchman and node, cleared watchman with `watchman watch-del-all`, `rm -rf ~/.npm` and then from scratch re-installed code push (w/o using rnpm).  I also removed the `android/app/build` folder and `android/build` folder (I only had removed app's build folder in the past, which may have been the actual issue).  Regardless, closing, as this is fixed.

**Comment by geof90** [comment]
@niftylettuce Glad it worked out!

**Comment by altruio** [comment]
> Let me know if either of those work for you. If not, it would be helpful if you could remove the getJSBundleFile method from your MainActivity file and see if the issue still occurs.

@lostintangent Was experiencing the same, and I removed the getJSBundleFile per your advice and the problem indeed did stop occurring. I don't suppose this is a good solution if I want CodePush to still work in production though, so would you have any other advice? ;)

**Comment by sergey-akhalkov** [comment]
Hi @altruio, could you please create [new issue using this template](https://github.com/Microsoft/react-native-code-push/issues/new), so we would able to help you?
