### ISSUE TITLE
The installation package has been updated, but some of the updated content has not taken effect

### ISSUE THREAD

**Issue by Rammst3** [microsoft/react-native-code-push#2724]
![1720145521478](https://github.com/microsoft/code-push/assets/66708014/e00d6f40-9756-465b-a75f-268e4691affb)
![image](https://github.com/microsoft/code-push/assets/66708014/9f30397b-8538-4360-b941-114819e3a99e)
![image](https://github.com/microsoft/code-push/assets/66708014/4c8957b4-7793-44e4-985b-5de33b12ca21)

当我添加react-native-compressor这个插件，使用code-push进行更新后，提示安装包已更新，但是图3这里的代码却没有生效

**Comment by DmitriyKirakosyan** [comment]
@Rammst3 , you are using old versions of `react-native` and `react-native-code-push`. Is it possible for you to upgrade these versions, RN v0.71+ and react-native-code-push to v8.3.0?

Additionally, make sure the added packages do not use native components. CodePush will not update native part.
