### ISSUE TITLE
 CodePush.checkForUpdate().then.catch ****   error = {}

### ISSUE THREAD

**Issue by Emperorywh** [microsoft/react-native-code-push#2738]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. CodePush .checkForUpdate().then.catch(error => console.log(error))
2.  console  =>>>>>  {}
3.

### Expected Behavior
What you expected to happen?
Check for updates and get the latest code

### Actual Behavior
What actually happens?
error:{}
```
  STACK TRACE AND/OR SCREENSHOTS
```

![image](https://github.com/user-attachments/assets/2960249a-d435-4d04-8e79-90564fb70764)

### Reproducible Demo

`
import { Button, Toast } from "@ant-design/react-native";
import { View } from "react-native";
import CodePush from 'react-native-code-push';

/**
 * 我的
 * @returns 
 */
function Mine() {
    const onCheck = () => {
        const key = Toast.loading({
            content: '正在检查更新....'
        });
        CodePush
            .checkForUpdate()
            .then(update => {
                Toast.remove(key);
                if (update) {
                    CodePush.sync(
                        {
                            updateDialog: {
                                mandatoryUpdateMessage: '必须安装的可用更新',
                                mandatoryContinueButtonLabel: '立即更新',
                                optionalIgnoreButtonLabel: '稍后再说',
                                optionalInstallButtonLabel: '立即更新',
                                optionalUpdateMessage: '发现新版本了，是否更新？',
                                title: '更新提示',
                            },
                            installMode: CodePush.InstallMode.ON_NEXT_RESTART,
                        },
                        status => {
                            switch (status) {
                                case CodePush.SyncStatus.UP_TO_DATE:
                                    Toast.info('当前已是最新版本!：' + status);
                                    break;
                                case CodePush.SyncStatus.SYNC_IN_PROGRESS:
                                    Toast.info('后台正在下载，请耐心等待!：' + status);
                                    break;
                                case CodePush.SyncStatus.CHECKING_FOR_UPDATE:
                                    Toast.info('正在检查更新，请稍后再试!：' + status);
                                    break;
                                case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
                                    Toast.info('正在下载中……：' + status);
                                    break;
                                case CodePush.SyncStatus.INSTALLING_UPDATE:
                                    Toast.info('已安装更新内容，请重启应用！：' + status, 5);
                                    break;
                                case CodePush.SyncStatus.UNKNOWN_ERROR:
                                    Toast.info('更新遇到错误，请稍后再试!：' + status);
                                    break;
                                default:
                                    break;
                            }
                        },
                        progress => {
                            console.log(
                                'codepush-sync:' +
                                progress.receivedBytes +
                                ' of ' +
                                progress.totalBytes +
                                ' received.',
                            );
                        },
                    );
                } else {
                    Toast.info('update：' + update);
                }
            })
            .catch(err => {
                console.log('出错：' + JSON.stringify(err))
                Toast.info('出错：' + JSON.stringify(err));
            });
    }
    return (
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
            <Button style={{ marginVertical: 10 }} onPress={onCheck}>
                检查更新
            </Button>
        </View>
    );
}

export default Mine;
`

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: ^8.3.1
* react-native version:0.74.3
* iOS/Android/Windows version: Android 13
* Does this reproduce on a debug build or release build?
* yes
* Does this reproduce on a simulator, or only on a physical device?
all

(The more info the faster we will be able to address it!)

![image](https://github.com/user-attachments/assets/c0a178e4-fa5d-4b7c-a13a-d0b407dd2d36)

My codepush was able to upload, check for updates and download normally before, so there is no doubt that there is something wrong with my configuration

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by chengxiaofeng123** [comment]
The device cannot detect the update and must scientifically go online to receive it

**Comment by Emperorywh** [comment]
![image](https://github.com/user-attachments/assets/c9c76d77-b437-482d-be09-aa31acf32289)

打包之前，将  private static String mServerUrl = “https://codepush.appcenter.ms”  替换为 https://api.appcenter.ms/ 也可以

**Comment by IlyaBausovAkvelon** [comment]
Hi @Emperorywh,
Thank you for reporting this issue. Could you please clarify when this issue is started to happen? Did this appear after react-native update? Does the device is being online when the update is happening?

**Comment by Emperorywh** [comment]
> Hi @Emperorywh, Thank you for reporting this issue. Could you please clarify when this issue is started to happen? Did this appear after react-native update? Does the device is being online when the update is happening?

I discovered this problem on August 16, 2024. The react-native version 0.71.3 also has this problem. The device is connected to the Internet when checking for updates. I turned on VPN and the update check worked properly.
