### ISSUE TITLE
https://codepush.appcenter.ms is down, can't get update now

### ISSUE THREAD

**Issue by glacjay** [microsoft/react-native-code-push#2740]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.61.5 react-native-code-push@6.0.0` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by usedlife** [comment]
Same error.
The response error code by `codepush.appcenter.ms`  is `999`

**Comment by IlyaBausovAkvelon** [comment]
Hi @glacjay, @usedlife,
Thank you for reporting this issue. Are you still experiencing this issue?

**Comment by cuantmac** [comment]
> Hi @glacjay, @usedlife, Thank you for reporting this issue. Are you still experiencing this issue?

Yes, I still experiencing this, and don't know the reason.

**Comment by glacjay** [comment]
@IlyaBausovAkvelon Yes

![图片](https://github.com/user-attachments/assets/46ae0593-a352-4ff1-bc8f-f590d3123f5c)
![图片](https://github.com/user-attachments/assets/4aaee720-400b-45cc-9114-1a4dcdfe854c)

**Comment by DmitriyKirakosyan** [comment]
Hi everyone, please use https://codepush.appcenter.ms/v0.1/status to check the codepush server status.

Anyone facing issues with codepush sdk, please share your application/codepush logs.

**Comment by ra1nj** [comment]
It looks like the codepush server is blocked by Great FireWall , can't access this [link](https://codepush.appcenter.ms/v0.1/status) in China unless using a VPN

**Comment by glacjay** [comment]
Switched to code-push-server-go.

**Comment by summer88123** [comment]
serverUrl `api.appcenter.ms` works fine

**Comment by jianxinzhoutiti** [comment]
It looks like the codepush server is blocked by Great FireWall , can't access this [link](https://codepush.appcenter.ms/v0.1/status) in China unless using a VPN

**Comment by nolife08021** [comment]
@jianxinzhoutiti  hi, do you have any solution for this?

**Comment by jianxinzhoutiti** [comment]
> @jianxinzhoutiti 你好，你们那边还遇到这个问题吗？我现在也遇到同样的问题，codepush 在中国失败了，有解决办法吗？

No, wait for resolution or build your own service

**Comment by summer88123** [comment]
> @jianxinzhoutiti hi, do your side still facing this issue? i facing same issue now, codepush fail in China, any solution for this?

try change serverUrl to `api.appcenter.ms` like this:
```
#ios add to Info.plist
<key>CodePushServerURL</key>
<string>${CODE_PUSH_SERVER_URL}</string>

#android add to res/value/strings.xml
<string moduleConfig="true" name="CodePushServerUrl">${CODE_PUSH_SERVER_URL}</string>
```
