### ISSUE TITLE
New Architecture (Bridgeless) support?

### ISSUE THREAD

**Issue by FightFarewellFearless** [microsoft/react-native-code-push#2742]
Any plan to support New Architecture?

**Comment by DmitriyKirakosyan** [comment]
Duplicate of https://github.com/microsoft/react-native-code-push/issues/2696 - we are not going to support new architecture.

**Comment by DordeDimitrijev** [comment]
RNCP won't support NA please check https://github.com/microsoft/react-native-code-push/issues/2774#issuecomment-2507636494 for reference.

**Comment by DordeDimitrijev** [comment]
@esbenvb  You can try the approach mentioned in this comment to use the new architecture https://github.com/microsoft/react-native-code-push/issues/2781#issuecomment-2519480160
