### ISSUE TITLE
Code push suddenly repeats "UNKNOWN_ERROR."

### ISSUE THREAD

**Issue by burakgenc10** [microsoft/react-native-code-push#2756]
Is anyone experiencing the same issue? My application is down.
https://status.appcenter.ms/
appcenter status shows that it is operational...

**Comment by joseviniciusnunes** [comment]
the url that the applications call has no configured IP, and there is a DNS problem
https://codepush.appcenter.ms/

Error: DNS_PROBE_FINISHED_NXDOMAIN

![Captura de Tela 2024-09-12 às 11 57 00](https://github.com/user-attachments/assets/bb22194b-d482-42e5-b4c0-4baefb92cc69)

**Comment by dw-l-e-e** [comment]
When can this issue be resolved? Every time I try CodePush, it keeps returning an UNKNOWN_ERROR.

**Comment by abhinavnimbuslearning** [comment]
Hello, we are also experiencing this issue.

**Comment by mahendra-bm-ai** [comment]
+1

**Comment by johnpwrs** [comment]
same issue

**Comment by streamize** [comment]
error!!!!!! what the fxck

**Comment by dmtuan97** [comment]
Same issue.

**Comment by stratus1011** [comment]
Same

**Comment by daviseares** [comment]
the same issue here. +1

**Comment by maxb94** [comment]
is there somebody at App Center that the issue can be reported to?

**Comment by dw-l-e-e** [comment]
The quickest way to contact, as far as I know, is for all of us to log into App Center, click the question mark button at the top right of the screen, and report the issue through 'Contact'.

**Comment by maxb94** [comment]
> The quickest way to contact, as far as I know, is for all of us to log into App Center, click the question mark button at the top right of the screen, and report the issue through 'Contact'.

Thanks, I've reported the issue.

Please could others do the same so they prioritise

**Comment by dmtuan97** [comment]
> > The quickest way to contact, as far as I know, is for all of us to log into App Center, click the question mark button at the top right of the screen, and report the issue through 'Contact'.
> 
> Thanks, I've reported the issue.
> 
> Please could others do the same so they prioritise

I did too

**Comment by dmtuan97** [comment]
They replied
![Uploading Screenshot 2024-09-12 at 23.50.47.png…]()

**Comment by stratus1011** [comment]
I got the the same response too. Jorge is super responsive from that team. I've reached out in the past and Jorge always responds extremely fast! Glad they're on it.

**Comment by podger** [comment]
+1

**Comment by cotovanugabi** [comment]
+1

**Comment by reactnv** [comment]
Our app checks for CodePush updates on startup and we didn't try-catch that.. huge mistake. now the app just doesn't work :(

**Comment by deggertsen** [comment]
> +1 - breaking our entire application, anyone know how to fallback on just App's preloaded JS if something like this happens again?

Yeah, we just implemented a catch, where if we get a network error back it will bypass codepush and just run the app on the current version.

**Comment by reactnv** [comment]
> > +1 - breaking our entire application, anyone know how to fallback on just App's preloaded JS if something like this happens again?
> 
> Yeah, we just implemented a catch, where if we get a network error back it will bypass codepush and just run the app on the current version.

Did you send an update right now with CodePush and it worked?

**Comment by deggertsen** [comment]
> > > +1 - breaking our entire application, anyone know how to fallback on just App's preloaded JS if something like this happens again?
> > 
> > 
> > Yeah, we just implemented a catch, where if we get a network error back it will bypass codepush and just run the app on the current version.
> 
> Did you send an update right now with CodePush and it worked?

I'm able to send codepush updates. But nobody can download them.

**Comment by reactnv** [comment]
> > > > +1 - breaking our entire application, anyone know how to fallback on just App's preloaded JS if something like this happens again?
> > > 
> > > 
> > > Yeah, we just implemented a catch, where if we get a network error back it will bypass codepush and just run the app on the current version.
> > 
> > 
> > Did you send an update right now with CodePush and it worked?
> 
> I'm able to send codepush updates. But nobody can download them. If you didn't already have a catch in place before this crash I think the only option is a new app store release.

![image](https://github.com/user-attachments/assets/66b70b90-4f2c-4c86-9451-2eb5f779884d)

**Comment by dw-l-e-e** [comment]
Is there any progress in resolving the issue currently happening?

**Comment by sd** [comment]
It seems to be back online

**Comment by deggertsen** [comment]
It's still intermittent for us. Lots of calls are still failing, but at least most seem to be working now.

**Comment by dmtuan97** [comment]
It is fixed for me

**Comment by burakgenc10** [comment]
yes, issue fixed for all of us. closed 💯
