### ISSUE TITLE
[question] [9.0.0] Why is iOS >=15.5 the minimum target

### ISSUE THREAD

**Issue by FrederickEngelhardt** [microsoft/react-native-code-push#2757]
Hello, reaching out regarding release [9.0.0](https://github.com/microsoft/react-native-code-push/releases/tag/v9.0.0) which sets the minimum supported iOS version to `15.5`. Change [here](https://github.com/microsoft/react-native-code-push/compare/v8.3.1...v9.0.0#diff-8349a8d6617f0705c9dfa3a79195187b639e4afd17e424301590b3d405f4dd99R13-R14)

1. Is there reason to drop iOS 13 & 14? RN support iOS 13 and 13.4 for versions which match react-native `~0.74.x - ~0.75`? These versions also need AGP >=8.x.x support but may need to also target iOS 13 and 14 devices.
  - 0.75 [requirement docs](https://reactnative.dev/blog/2024/08/12/release-0.75#last-version-supporting-minsdk-23-and-miniosversion-134)
  - 0.74 is 13.0, can't find docs but it's in the podspec.

2. Is there features that would not work with iOS 13 or 14 targets?

Locally for AGP >= 8.x.x we've been running a manifest namespace and xml patcher script, but curious if `react-native-code-push` >=[9.x.x](https://github.com/microsoft/react-native-code-push/releases/tag/v9.0.0) should be avoided until projects target ReactNatuve76 which targets > iOS 15 and/or companies want to drop support for iOS 13 & 14.

**Comment by huextrat** [comment]
Latest versions of `SSZipArchive` works on iOS 15.5+ https://github.com/ZipArchive/ZipArchive?tab=readme-ov-file#version-250-updates-minimum-os-versions

And the bump on codepush has been done here https://github.com/microsoft/react-native-code-push/pull/2709

**Comment by DmitriyKirakosyan** [comment]
@FrederickEngelhardt  We've updated `SSZipArchive` to version `2.5.5` to fix two critical vulnerabilities, and it set the minimum iOS version to 15.5.
Also, iOS 14 is no longer officially supported. See https://endoflife.date/ios.
Please use previous version until you can bump iOS version in your project.
