### ISSUE TITLE
App Shows White Screen After CodePush Updates in Release Mode

### ISSUE THREAD

**Issue by Ayush8923** [microsoft/react-native-code-push#2758]
Hello Team, reaching out regarding the weird issue in the Codepush version `8.1.0` with latest react native version, describe the issue below here

### Description
In our application, when all the CodePush changes are downloaded, the app is expected to refresh automatically. However, instead of refreshing, the application is showing a white screen after all the CodePush changes are downloaded. When we run the app in debug mode, it works correctly, but when we run the application in release mode and create the APK, this issue occurs. This problem only happens when the app is downloading the latest CodePush changes.

### Expected Behavior
- After all CodePush changes are downloaded, the app should refresh automatically without showing a white screen.

### Environment

* `react-native-code-push` version:- `8.1.0`
* `react-native` version: `0.74.0`
*  **Occurrence**: This issue only happens in the release build, not in debug mode.

**Comment by MikhailSuendukov** [comment]
Hello, and thank you for reaching out! Could you please confirm if the issue persists on the latest version of react-native-code-push (9.0.0)? If the error still occurs, could you please provide us with a simple demo application where the issue can be reproduced, along with detailed steps to reproduce the problem?

**Comment by Ayush8923** [comment]
Hi @MikhailSuendukov,
Thanks for your response, and I apologize for the late reply. Let me check with the latest version of CodePush, and if the issue persists with the latest version, I will let you know and share all the necessary information along with a simple demo of the application.

**Comment by Ayush8923** [comment]
Hi @MikhailSuendukov,
I tried checking the issue again and attempted to reproduce it, but I was unable to do so. I upgraded the `react-native-code-push` to the latest version, and things are working fine. Thanks @MikhailSuendukov

**Comment by Ayush8923** [comment]
We can close this issue ticket. If I encounter a similar issue again, I can open another issue ticket.

**Comment by MikhailSuendukov** [comment]
Thank you for the information, if you will have any questions, please feel free to contact us in the future.
