### ISSUE TITLE
Specs satisfying the CodePush  dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by trickyc0d3r** [microsoft/react-native-code-push#2768]
Hi everyone! Got this issue on RN 0.75.4 and react-native-code-push version is 9.0.0. Can anyone help to fix it?
Here my Podfile=>
`# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BrainBlow' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'BrainBlowTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
`

**Comment by huextrat** [comment]
@trickyc0d3r `platform :ios, '15.0'` -> `platform :ios, '15.5'`

Version 9.0.0 is compatible with iOS 15.5+: https://github.com/microsoft/react-native-code-push/releases/tag/v9.0.0

Bump your minimal supported iOS version or downgrade CodePush to v8.3.1

**Comment by trickyc0d3r** [comment]
THX !!! yeap, its working now.

**Comment by DordeDimitrijev** [comment]
Hello @trickyc0d3r  as @huextrat  mentioned in the latest version 9.0.0 we've raised min ios version.  I'll be closing this issue since it seems to be resolved, if you have any additional questions feel free to re-open it.
