### ISSUE TITLE
Visual Studio App Center is scheduled for retirement on March 31, 2025.

### ISSUE THREAD

**Issue by sejr1996** [microsoft/react-native-code-push#2772]
What does it mean?

![Image](https://github.com/user-attachments/assets/4be19551-2efc-4737-9697-a6ace238c740)

I will not be able to deploy my application using this library?

**Comment by krzysztofzaluski** [comment]
@DordeDimitrijev can I still use this library in my RN project but host my updates on my own server instance?
How can I do that and change the server url?

**Comment by DordeDimitrijev** [comment]
Yes you can add your custom server url to RNCP project.
```
#ios add to Info.plist
<key>CodePushServerURL</key>
<string>${CODE_PUSH_SERVER_URL}</string>

#android add to res/value/strings.xml
<string moduleConfig="true" name="CodePushServerUrl">${CODE_PUSH_SERVER_URL}</string>
```

**Comment by krzysztofzaluski** [comment]
@DordeDimitrijev thank you, any additional changes required on mobile side with it or just change server address?

Also, will this library `react-native-code-push` continue to be updated and maintained?

**Comment by DordeDimitrijev** [comment]
No additional changes are needed. React Native code-push will also be retired from 31st March. I believe there are forks from the repo already out there so you can take a look at those or create your own fork.

**Comment by hcrnln** [comment]
Can we continue using it without forking? Because we were using this package without forking in our project

**Comment by DordeDimitrijev** [comment]
Hello @hcrnln you can still use it, but if you plan to make some changes better to use a fork.

**Comment by 7ictor** [comment]
@DordeDimitrijev thanks for the custom server url explanation, obviously this means that old versions of MyApp without a custom url will not receive updates?

**Comment by DordeDimitrijev** [comment]
That's correct you'd need a new release of your application to app/play store with this configuration in order to keep using codepush with your custom codepush server.
