### ISSUE TITLE
io.invertase.firebase.crashlytics.JavaScriptError - Object is not a function

### ISSUE THREAD

**Issue by Nader-CS** [microsoft/react-native-code-push#2777]
![Image](https://github.com/user-attachments/assets/86cd2871-9d55-4a62-9de5-322ba4bba258)
![Image](https://github.com/user-attachments/assets/d7dcdb80-3008-453c-a99f-8ad8381adc8f)
 it happens in the first 5 seconds

`react native version : 0.75.4`
`code push version : ^8.3.1`
`@react-native-masked-view/masked-view: ^0.2.8`

**Comment by Nader-CS** [comment]
same issue in ios
![Image](https://github.com/user-attachments/assets/b1e014f4-52e4-4722-a326-0c4212eddc35)
![Image](https://github.com/user-attachments/assets/6e1dd50f-7895-47e6-8cb2-5b5dcfcc319d)
it happens when i release code push

**Comment by MikhailSuendukov** [comment]
Hello, and thank you for reaching out! Could you please clarify why you believe react-native-code-push might be causing this error? To help us investigate further, it would be very helpful if you could provide a decrypted stack trace of the error, along with application logs from both startup and the moment the error occurred.

**Comment by Nader-CS** [comment]
this issue does not caused by code push, thanks.
