### ISSUE TITLE
Where can get e.g. which about DownloadProgressCallback

### ISSUE THREAD

**Issue by xhacker5000** [Microsoft/react-native-code-push#278]
I wanna use DownloadProgressCallback make a download dialog whit progress , is there any e.g for learn ?

**Comment by dtivel** [comment]
Here is the `sync(...)` API signature:

    codePush.sync(options: Object, syncStatusChangeCallback: function(syncStatus: Number), downloadProgressCallback: function(progress: DownloadProgress)): Promise<Number>;

The DownloadProgressCallback callback is described in [sync(...)'s documentation](https://github.com/Microsoft/react-native-code-push#codepushsync).  Here's a documentation excerpt:

* __downloadProgressCallback__ *((progress: DownloadProgress) => void)* - Called periodically when an available update is being downloaded from the CodePush server. The method is called with a `DownloadProgress` object, which contains the following two properties:
    * __totalBytes__ *(Number)* - The total number of bytes expected to be received for this update package
    * __receivedBytes__ *(Number)* - The number of bytes downloaded thus far.

Here is your `sync(...)` call with a DownloadProgressCallback callback:

    var options = {
        installMode: codePush.InstallMode.IMMEDIATE,
        updateDialog: { appendReleaseDescription: true, descriptionPrefix: "\n\更新信息:\n" }
    };
    var downloadProgressCallback = function(progress) {
        console.log("Received " + progress.receivedBytes + " of " + progress.totalBytes + " total bytes.");
    };

    codePush.sync(options, /*syncStatusChangeCallback*/ null, downloadProgressCallback);

**Comment by xhacker5000** [comment]
thank you 
BTW , are you from China , I found you using Chinese '更新信息'

**Comment by dtivel** [comment]
No problem.  Did it work?  Let us know if you run into any issues.

I just copied code from [your now-deleted post under a different issue](https://github.com/Microsoft/react-native-code-push/issues/277#issuecomment-205875590). :)

**Comment by xhacker5000** [comment]
Still trying ...

**Comment by lostintangent** [comment]
@xhacker5000 Any luck? :) The CodePush sample app actually shows how to use the download progress callback as well, if you'd like to see a sample: https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/crossplatformdemo.js#L73

**Comment by lostintangent** [comment]
@xhacker5000 I'm going to close this issue since we support download progress and there doesn't appear to be a bug with it. Please re-open this if you run into any problems and/or have a question about how to use it. Thanks!
