### ISSUE TITLE
iOS CodePushServerURL plist doesn't like //

### ISSUE THREAD

**Issue by kmcrawford** [microsoft/react-native-code-push#2782]
Example:
```
<key>CodePushServerURL</key>
<string>https://mycode-push.server.com</string>
```
You get this error: (masked)

`error: unable to read property list from file: /Users/****/Library/Developer/Xcode/DerivedData/**_mobile-**/Build/Intermediates.noindex/**_mobile.build/Debug-iphonesimulator/**_mobile.build/Preprocessed-Info.plist: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 2.) (in target '**_mobile' from project '**_mobile')`
If I look at the `Preprocessed-Info.plist`  I see the following:
```
<key>CodePushServerURL</key>
 <string>https:
 <key>UIViewControllerBasedStatusBarAppearance</key>
 <false/>
```
The end of the string is missing, I'm not sure it likes the //.

I was able to get around this issue by setting the plist to:
```
<key>CodePushServerURL</key>
<string>$(CODE_PUSH_SERVER_URL)</string>
```
Then:
1. Open Xcode and go to your project’s Build Settings.
2. Add a new User-Defined Setting. Name it `CODE_PUSH_SERVER_URL` and set its value t

**Comment by DordeDimitrijev** [comment]
Hello @kmcrawford thank you for reaching out! Are you still experinecing this issue, I've tried to generate the preprocessed plist and i get the same output as in info.plist. Could you please share a demo app or steps so i can reproduce this issue?

**Comment by kmcrawford** [comment]
I am using the work around above..  If others aren't having this issue, then I am fine closing this and leaving it for others to find if they run into the same issue as me.
