### ISSUE TITLE
iOS: expectedContentLength returns -1 and codepush crashd

### ISSUE THREAD

**Issue by rikuayanokozy** [Microsoft/react-native-code-push#290]
In some case NSURLResponse.expectedContentLength returns -1. For example, if a response compress with gzip, NSURLResponse cannot know the actual length at didReceiveResponse phase(https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/CodePushDownloadHandler.m#L43).
And it caused the length assertion(https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/CodePushDownloadHandler.m#L94) failed.
The assertion is not necessary because we've packageHash.

BTW. If I made an open-source code push server, will it incompatible with code-push license?

**Comment by lostintangent** [comment]
@rikuayanokozy Are you hitting an issue with this using the CodePush server, or are you only experiencing a problem when using our client plugin with your own server?

**Comment by geof90** [comment]
The CodePush server does not gzip responses as far as I know. That being said, maybe it makes sense to remove a superfluous assertion would crash the app especially since like mentioned, we verify the package hash anyway.

**Comment by rikuayanokozy** [comment]
Yes, I only reach this problem when using my own server, that compress response with gzip. Because we wire deploy jsbundle directly(without zip), enable gzip can reduce about 30% transfer.
NSURLConnection handle gzip compression transparently, and as you mentioned we'll check package hash after download, I think the assertion can be removed safely.

**Comment by rikuayanokozy** [comment]
I opened a PR for this, please review.
https://github.com/Microsoft/react-native-code-push/pull/292

**Comment by lostintangent** [comment]
Thanks for the PR! I just merged your change.
