### ISSUE TITLE
iOS: expectedContentLength returns -1 and codepush crashd

### ISSUE THREAD

**Issue by rikuayanokozy** [Microsoft/react-native-code-push#291]
In some case NSURLResponse.expectedContentLength returns -1. For example, if a response compress with gzip, NSURLResponse cannot know the actual length at didReceiveResponse phase([CodePushDownloadHandler.m#L43](https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/CodePushDownloadHandler.m#L43)).
And it caused the length assertion([CodePushDownloadHandler.m#L94](https://github.com/Microsoft/react-native-code-push/blob/master/ios/CodePush/CodePushDownloadHandler.m#L94)) failed.
The assertion is not necessary because we've packageHash.

BTW. If I made an open-source code push server, will it incompatible with code-push license?

**Comment by lostintangent** [comment]
I'm assuming that #290 is sufficiently tracking this issue, so I'm closing this one so we can consolidate the debug. Please re-open if that isn't true.
