### ISSUE TITLE
How to refer an android project that not in the same directory with the react native code

### ISSUE THREAD

**Issue by ghalong** [Microsoft/react-native-code-push#296]
Hi, my react native code is in ~/react_native,my android project is in ~/android-app/app,when I exexute \<code-push release-react android-app android -m --description "Modified the login 111"\>,the cli give the info <[Error]  Unable to find or read "build.gradle" in the "android/app" folder.>.thank you.

**Comment by silhouettes** [comment]
Hi @ghalong, this is certainly unusual - is the reason they are in separate directories because you own a native app that embeds react-native code?

We can look into possibly adding an option that allows you to specify the location of your gradle file, but in the mean-time a good workaround would be to just specify the `--targetBinaryVersion` flag, which will skip that step.

**Comment by ghalong** [comment]
Hi @silhouettes ,thank you!Our App have android and iOS version,and they are independent project.A few days ago,we introduced React Native to our project in order to improve the work efficient,we want the RN code keep away from our former iOS or Android code,so make the RN code be a independent project and managed by git.I have check the --targetBinaryVersion,it seems just change the version of the apk? I am not good at English,I hope you can understand me. : )

**Comment by geof90** [comment]
@ghalong yup you are right, it just changes the version of the APK. If you explicitly specify the --targetBinaryVersion, it should skip trying to look at the build.gradle file. Let me know if it works. Thanks!

**Comment by ghalong** [comment]
Hi,@geof90 thank you,I have tried specify the --targetBinaryVersion and it does work well! There's also something would be pay attention when the RN code directory does't same with android code, when import the code-push gradle file,like `apply from: "../../../AwesomeProject/node_modules/react-native-code-push/android/codepush.gradle"
`,we would modify the gradle code `def recordFilesBeforeBundleCommand = tasks.create(
                    name: "recordFilesBeforeBundleCommand${targetName}",
                    type: Exec) {
                commandLine "node", "../../../AwesomeProject/node_modules/react-native-code-push/scripts/recordFilesBeforeBundleCommand.js", resourcesDir
            }` and `def generateBundledResourcesHash = tasks.create(
                    name: "generateBundledResourcesHash${targetName}",
                    type: Exec) {
                commandLine "node", "../../../AwesomeProject/node_modules/react-native-code-push/scripts/generateBundledResourcesHash.js", resourcesDir, "$jsBundleDir/$bundleAssetName", assetsDir
            }` to the real path of the RNCode directory,otherwise it would appear like "can't find recordFilesBeforeBundleCommand" and so on. : )

**Comment by geof90** [comment]
I see. That makes sense. Perhaps there could be a better way to reference the path to the node_modules directory without assuming that there is a fixed folder depth. I will try to investigate this, but in the meantime if you can think of a better workaround, feel free to send a PR. It seems that your original issue has been resolved so I will close this for now, feel free to reopen otherwise.

**Comment by Krupen** [comment]
I have a similar problem.
I am getting `Error: Cannot find module '/Users/krupenghetiya/AndroidStudioProjects/node_modules/react-native-code-push/scripts/recordFilesBeforeBundleCommand.js'`

I have applid plugin as below: 
`apply from: "../../android-v2/react-native-consumer-app/node_modules/react-native/react.gradle"
`
`apply from: "../../android-v2/react-native-consumer-app/node_modules/react-native-code-push/android/codepush.gradle"`
and it doesn't give any error, it gradle syncs and complies well.

I have a submodule for React-Native code as I have both Android and iOS app and code management becomes easy.
My `recordFilesBeforeBundleCommand.js` would be at path `/Users/krupenghetiya/AndroidStudioProjects/android-v2/react-native-consumer-app/node_modules/react-native-code-push/scripts/recordFilesBeforeBundleCommand.js'`
So how do I specify it?
