### ISSUE TITLE
Confusing documentation on getUpdateMetadata()

### ISSUE THREAD

**Issue by chetstone** [Microsoft/react-native-code-push#299]
I'm just trying to get started with codepush. Installed a couple of days ago. sync() works OK but getUpdateMetadata() is undefined. [This page](https://github.com/Microsoft/react-native-code-push#javascript-api-reference) documents that function but [this page](http://microsoft.github.io/code-push/docs/react-native.html#codepushgetcurrentpackage) doesn't mention it. Instead it talks about getCurrentPackage(). I see a recent commit about clarifying getcurrentpackage. What is the real story here?

Also, something is very strange about the installation. npm ls will not show me the version of the installed package:

```
npm ls react-native-code-push
Sadhana@0.0.2 /Users/chet/prj/malas/firebase
└── (empty)

npm ERR! code 1
```
but I know it's there:
```
ls node_modules/react-native-code-push
AlertAdapter.js			ios
CodePush.js			package-mixins.js
CodePush.podspec		package.json
LICENSE.md			react-native-code-push.d.ts
README.md			request-fetch-adapter.js
android				scripts
```

**Comment by lostintangent** [comment]
@chetstone Apologies for the confusion here! The GitHub readme always reflects the state of master, which is periodically ahead of the bits on NPM. The website docs always reflect the public bits on NPM.  

Regarding the disparity you're seeing, we recently deprecated the `getCurrentPackage` method in favor of `getUpdateMetadata`, but we haven't released it to NPM yet (I'll be doing that today). The `getCurrentPackage` method is still available, but you won't see `getUpdateMetadata` unless you install the CodePush SDK from GitHub or after upgrading to the release we'll publish this afternoon. We ran into a bug that we're trying to fix which is delaying the NPM release, so I apologize about the doc disparity.

Regarding the NPM installation question, I believe that you need to specify the version number when running `npm ls`. If you run `npm ls react-native` do you get similar output? For me, the behavior you listed for CodePush is the same as trying to list any other NPM module if I omit the version. However, if I run `npm ls react-native-code-push@1.10.1-beta`, that should work. I believe that is just a behavior of the `npm ls` command, and isn't related to the CodePush package itself. I could be wrong though, so let me know what you see.

Thanks!

**Comment by lostintangent** [comment]
FYI, I just added the docs for `getCurrentPackage` to our GitHub readme, and simply marked is as deprecated in >=1.10.3-beta (which we'll release this afternoon). Sorry again for the confusion.

**Comment by chetstone** [comment]
Thanks for the explanation. I'll want to use the new API.

I've always used `npm ls` to find out what version I have installed. What's
the point if you already know the version?
This is the first time I've seen it not work. Maybe there's something wrong
with your package.json?

$ npm ls react-native

Sadhana@0.0.2 /Users/chet/prj/malas/firebase

└── react-native@0.22.2

**Comment by lostintangent** [comment]
Ah I think there may be a bug with `npm ls` if the specified package's version has a pre-release tag. Since CodePush includes a `-beta` suffix, and in my case, I'm using an `-rc` version of React Native, neither one work correctly with `npm ls`. If I run `npm ls` on a non-RC version of React Native, or any other package, it works fine.

**Comment by lostintangent** [comment]
@chetstone The new SDK release has been published to NPM and includes the `getUpdateMetadata` method. As I mentioned, I believe the `npm ls` issue is related to package's whose version includes a pre-release tag, but please re-open this issue if you see any other issues. Thanks!
