### ISSUE TITLE
Release uploads then [Error] Not Found

### ISSUE THREAD

**Issue by Jered** [Microsoft/react-native-code-push#301]
I can't seem to figure out what's happening with this fairly cryptic error on one of my projects. I've done new projects that work just fine but this one always errors out. Is there any way to get more info on what is happening?

```
code-push release-react MyApp ios -m --description "v1.0.18 code push test"
Running "react-native bundle" command:

node node_modules/react-native/local-cli/cli.js bundle --assets-dest /var/folders/s3/g96v8wcs16z59qpmglftjtrc0000gn/T/CodePush --bundle-output /var/folders/s3/g96v8wcs16z59qpmglftjtrc0000gn/T/CodePush/main.jsbundle --dev false --entry-file index.ios.js --platform ios
bundle: Created ReactPackager
bundle: start
[10:41:36 AM] <START> Whole Program Optimisations
[10:41:44 AM] <END>   Whole Program Optimisations (8325ms)
[10:41:44 AM] <START> minify
[10:41:48 AM] <END>   minify (4089ms)
bundle: finish
bundle: Writing bundle output to: /var/folders/s3/g96v8wcs16z59qpmglftjtrc0000gn/T/CodePush/main.jsbundle
bundle: Closing client
bundle: Copying 273 asset files
bundle: Done writing bundle output
bundle: Done copying assets

Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
[Error]  Not Found
```

**Comment by geof90** [comment]
That definitely looks strange, it seems to be a server issue, we'll look into it.

**Comment by geof90** [comment]
Hi @Jered, do you have any idea whats the file size of your upload?

**Comment by Jered** [comment]
153.4MB fairly hefty but there are a lot of included images since this is a prototype without a CDN or backend.

**Comment by geof90** [comment]
We currently impose a limit of 100mb, which should be the error you're seeing. I agree 100% the message needs to be improved. That said, we will increase the limit to unblock you. We have a server deployment scheduled today following which u should no longer see the error. I will keep you updated.

**Comment by Jered** [comment]
awesome! Thank you so much.

**Comment by geof90** [comment]
Hi @Jered, if you go ahead and do a release now, the server should accept it. Let me know if you are still hitting this issue.

**Comment by Jered** [comment]
Worked perfectly! Thank you.
