### ISSUE TITLE
My code-push is not updating my app 

### ISSUE THREAD

**Issue by gmchaturvedi1** [Microsoft/react-native-code-push#304]
i am new to code-push react native i have setup all things  as per the suggested in android setup .

but my update is not working when i am release the it show successful update but in app side nothing happen.

**Comment by lostintangent** [comment]
@gmchaturvedi1 Could you take a look at the Chroome console or ADB logcat output when you call sync in your app? That should help shed some light on what may be happening. Also, our [troubleshootinf](https://github.com/Microsoft/react-native-code-push/blob/master/README.md#debugging--troubleshooting) docs have some common issues and workarounds that could be worth double checking.

**Comment by gmchaturvedi1** [comment]
when i am using react-native run-android and start chrome console showing
code-push update then showing network error.

kindly find the scrreenshot
[image: Inline image 1]


kindly suggest what to check to resolve the same

reagrds
G M Chaturvedi

**Comment by lostintangent** [comment]
Could you try restarting the emulator? Sometimes, when you switch networks there can be connectivity issues. Restarting the emulator will resolve that, if that is in fact the issue.

**Comment by gmchaturvedi1** [comment]
Now updaye is giving popup but nothing changed .ia it take more time to be
in effect

**Comment by lostintangent** [comment]
What does the console output show after you try to install the update? Also, can you share how you're calling `sync`?

**Comment by gmchaturvedi1** [comment]
I am just calling sync woth root component componentdidmount lifecycle and
call codePush.sync() as suggested in documents

**Comment by lostintangent** [comment]
OK cool. After you install the update, and then kill and restart the app, you're not seeing the changes take affect? Could you try looking at the Chrome logs to see what may be going on?

**Comment by gmchaturvedi1** [comment]
in localhost update is working but in googleplay pop up update is coming
but changes is not done.

**Comment by geof90** [comment]
From what I am understanding, you are calling `codePush.sync()` without any additional options, so the installMode will default to `ON_NEXT_RESTART`. Therefore, the changes will only show up when you kill the app. This can appear to behave different sometimes for certain emulators from my experience, where if the system resources allocated are not enough, sometimes backgrounding the app will immediately cause the process to get killed, in which case simply returning to the app will cause it to pick up the updates.

So, I would suggest for the googleplay version, to either try forcibly killing the app after the update is installed, or changing the call to `codePush.sync()` to use InstallMode.ON_NEXT_RESUME or InstallMode.IMMEDIATE, and see if it solves your problem. Let us know if otherwise!

**Comment by gmchaturvedi1** [comment]
i did the same as you have suggested in your trail mail.But still not
updating. i set InstallMode.IMMEDIATE .Update dialogue box show
immediateley after release update but when we continue nothing chnaged as
per the release(whilein locl system it is working).Is their anything so it
is not updating in app install through google play.

Regards
G m chaturvedi

**Comment by lostintangent** [comment]
Can you share what your MainActivity looks like? And also, can you try copying and pasting the logs of the app when trying to sync an update in the Google Play version? That should help us figure out what might be going on. You can't use Chrome with the release build, but you can use ADB via "adb logcat *:S ReactNative:V ReactNativeJS:V".

**Comment by gmchaturvedi1** [comment]
i see a weired thing that when update is available the update window is
showing only continue button. but as i am watching one screecast of mr
purushottam ,on update two button will rise install and ignor.

MainActivty


package com.go4skillcom;

import com.facebook.react.ReactActivity;
import io.realm.react.RealmReactPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.microsoft.codepush.react.CodePush;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "go4skillcom";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new RealmReactPackage(),
            new VectorIconsPackage(),
            new CodePush("6fmr8pcJ2Ov51fm3at9_ioOn5TXEVy9szxs6g", this,
BuildConfig.DEBUG)
        );
    }
}

regards
G M chaturvedi

**Comment by gmchaturvedi1** [comment]
Sorry for the delayed response from my side asbibm not access vthe
network.kindly help me out on yhis

**Comment by lostintangent** [comment]
@gmchaturvedi1 Your `MainActivity` class needs to override the `getJSBundleFile` file in order for the React Native runtime to ask CodePush where to get the JS bundle from when the app starts. Refer to step #2 in the [Android configuration docs](https://github.com/Microsoft/react-native-code-push#plugin-configuration-android).

```java
@Override
protected String getJSBundleFile() {
   return CodePush.getBundleUrl();
}
```

This was likely working for you during development because the changes you were deploying to CodePush were also available locally, so when the app would restart, the packager would pick them up.

**Comment by gmchaturvedi1** [comment]
so shall i need to add these as suggested in mainActivity. Kindly tell me
the location .

so i can try and get back with update.


thanks & Regards
G M Chaturvedi

**Comment by lostintangent** [comment]
Update your `MainActivity` file like so. Note that I simply added the `getJSBundleFile` override to the code that you pasted above. As I mentioned in my previous comment, you should be able to follow our conjuration steps and ensure that you've setup everything correctly.

```java
public class MainActivity extends ReactActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "go4skillcom";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

   @Override
   protected String getJSBundleFile() {
      return CodePush.getBundleUrl();
   }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new RealmReactPackage(),
            new VectorIconsPackage(),
            new CodePush("6fmr8pcJ2Ov51fm3at9_ioOn5TXEVy9szxs6g", this,
BuildConfig.DEBUG)
        );
    }
}
```

**Comment by gmchaturvedi1** [comment]
after adding these lines in mainactivity file when i assemble and install
locally then this is going corrupt

**Comment by lostintangent** [comment]
What do you mean it is getting corrupted? Maybe try uninstalling the app from the device/emulator, running `./android/gradlew cleanDebug` to ensure you do a fresh build, and then re-trying?

**Comment by gmchaturvedi1** [comment]
its done and now chnaging. thanks for your valuable support to resolve
this. i just have one doubt when i will install any module then code-push
release will change this or i have generate apk and upload in google play.

thanks & Regards
G M Chaturvedi

**Comment by lostintangent** [comment]
We're more than happy to help! Thank you for spending the time to give CodePush a try :)

As you mentioned, when you update your React Native version, or add/update a module, you will need to upload a new APK to the App Store. CodePush can only be used for changes that touch JS and/or images, Java code.

BTW, would you be able to share any details about your app? Is it live in the Google Play store already? I'd love to check it out. Thanks!

**Comment by lostintangent** [comment]
I'm going to close this for now since your issue has been resolved. Please let us know if you run into any other issues. Thanks again!

**Comment by gmchaturvedi1** [comment]
our app in alpha stage .We are working on education app for training and
assessment for diffenet competative examination and boards exam in india
and we will be live by next week. Once we will live ,we will share you our
app details. Again thanks because it will ease  our life continuous
integration.

Thanks & Regards
G M Chaturvedi
