### ISSUE TITLE
Re-setting RootView initialProperties after update

### ISSUE THREAD

**Issue by jevakallio** [Microsoft/react-native-code-push#31]
I am passing some configuration variables to my root level React Native component using the `RCTRootView.initialProperties` object. This object becomes the `props` of the root level component.

When the application is updated and reloaded by calling `CodePush.sync()`, the initial properties are empty.

It is possible to work around this using local persistent storage to detect for situations when the app was updated, but it would be more convenient, if `CodePush.sync` could either

a) Automatically pass the original `initialProperties` to the root view, or
b) Accept an argument of `initialProperties` to be passed when the application reloads.

**Comment by jevakallio** [comment]
Closing this, as it looks like https://github.com/Microsoft/react-native-code-push/commit/0eb8eab264d083ed99ab2ab3493ce2b54acb2ad0, landed in master yesterday, already solves this issue by using `RCTBridge.reload`. 

Thanks for fixing my issue proactively :)

**Comment by lostintangent** [comment]
Thanks for reporting this! We're going to release an update to NPM in the morning that includes this fix.
