### ISSUE TITLE
Is there a way to embed sourceMap into the bundle?

### ISSUE THREAD

**Issue by eugenehp** [Microsoft/react-native-code-push#312]
At the moment I do this
```
./node_modules/react-native-cli/index.js  bundle --platform ios --entry-file index.ios.js --bundle-output ./CodePush/main.jsbundle --assets-dest ./CodePush --sourcemap-output ./sourcemap.js --dev false
```

The question is how can I make sure I include `sourceMap` inside the zipped bundle itself?

**Comment by eugenehp** [comment]
It would be awesome to overwrite this option `inlineSourceMap ` in here https://github.com/facebook/react-native/tree/master/packager#pathtomodulenamemapbundle-query-params

**Comment by lostintangent** [comment]
If you're using the React Native CLI directly, couldn't you set the `inlineSourceMap` parameter already? And then call the `code-push release` command as on your `CodePush` directory? Or were you thinking about adding the `inlineSourceMap` parameter to the `code-push release-react` command?

**Comment by lostintangent** [comment]
If you set the `--sourcemap-output` parameter to save your file inside of the `./CodePush` folder (e.g. --sourcemap-output ./CodePush/sourcemap.map`), then it would be included in the zipped update that is deployed to CodePush. That would also mean that your end users would download this file though. Is that the desired behavior?

**Comment by eugenehp** [comment]
Hey Jonathan,

Thanks for helping on this. Yeah, it will be bundled, but how can I access it within the application, as an asset? Cause it's just plain `JSON` format in there. Just wondering if you had similar ideas.

![Example](https://cloud.githubusercontent.com/assets/1857263/14803057/322393be-0b0b-11e6-9970-3fd392222f28.jpg)

**Comment by eugenehp** [comment]
@lostintangent and whenever you reference it back inside the system, it creates a circular dependency, where it just crashes the packager with `Unable to find this module in its module map or any of the node_modules directories under ...`

**Comment by lostintangent** [comment]
I'm not actually sure if React Native's debugging support allows a source map to be located on disk, as opposed to being served by the packager. This kind of makes sense considering they only enable red/yellow box in dev mode, and they expect you to be using the packager in debug mode. 

Could you elaborate on the scenario you're trying to achieve? Are you wanting to release debug builds via CodePush and have yellow box display source mapped stacks?

**Comment by lostintangent** [comment]
@eugenehp I'm going to close this issue for now, since I'm not sure if it's actionable for us. I briefly looked into enabling inline sourcemaps from the `release-react` command, but it doesn't currently seem possible. If you had a scenario in mind that we could help address, please re-open this. Thanks again!

**Comment by eugenehp** [comment]
Thanks @lostintangent 
I found a way to get that data in a standalone builds, I wouldn't call it a nice way.
I'll release the open source version of it soon, so you'll be able to advise me on it 😉

Thanks!

**Comment by lostintangent** [comment]
@eugenehp Sounds good. I look forward to seeing what you came up with :)
