### ISSUE TITLE
Can't download update, seems blocked at China

### ISSUE THREAD

**Issue by kiliwalk** [Microsoft/react-native-code-push#318]
Though it's not your service problem, I'm just sad with this.
Any plan for the poor man, me and us?

**Comment by lostintangent** [comment]
@kiliwalk Could you elaborate a little bit on this issue? Are you saying that CodePhsh has been working for you but now.access to it is being blocked in China?

**Comment by kiliwalk** [comment]
Yes, the download url domain `https://codepush.blob.core.windows.net/` is blocked, I can visit it by using proxy. But `checkForUpdate` and cli is still working

**Comment by lostintangent** [comment]
Interesting. If I check the connectivity from China, it seems to work, but maybe the tests I'm running aren't reflective of reality. We'll investigate this ASAP!

**Comment by kiliwalk** [comment]
@lostintangent , It's working now. Just blocked in two days.

**Comment by lostintangent** [comment]
It will be blocked in two days? I'd love to know how you know that :)

**Comment by kiliwalk** [comment]
sorry, not the future, just the past two days:)
Anyway, it's ok now, and if blocked again, I will reopen this and make you guys know that.
Thanks.

**Comment by lostintangent** [comment]
Phew! You had me worried man :) Thanks for the heads up. I really appreciate it.
