### ISSUE TITLE
Release build fails: RCTBridgeModule.h not found

### ISSUE THREAD

**Issue by jevakallio** [Microsoft/react-native-code-push#32]
Applications using this library cannot be Archived due to build error `'RCTBridgeModule.h' file not found`.

<img width="305" alt="screen shot 2015-11-04 at 00 25 24" src="https://cloud.githubusercontent.com/assets/1203949/10925957/a9bc5488-828a-11e5-9997-8b6ca95568c4.png">

This is because the Release configuration search paths do not include the correct relative paths to find the React Native headers.

**Comment by lostintangent** [comment]
Thanks for taking care of this fix! I just merged your change and will release it along with our NPM update this afternoon.
