### ISSUE TITLE
App Store rejection due to downloaded JavaScript bundle

### ISSUE THREAD

**Issue by justim** [Microsoft/react-native-code-push#320]
When we try to release our React Native iOS app in the App Store it's being rejected in the review phase, with the following message:

> **2.23** - Apps must follow the iOS Data Storage Guidelines or they will be rejected
>
> On launch and content download, your app stores 8.14MB on the user's iCloud, which does not comply with the iOS Data Storage Guidelines.

_See complete feedback reply in this [gist](https://gist.github.com/justim/520d104a4d0f9acfe166671f7230a83d)._

The 8.14MB mentioned above is the size of the JavaScript bundle.

I can't seem to find any solution for this problem or even other people mentioning it in the issues/pull requests of the relative projects (the code push ones and the react native one).

Am I missing something here?

Versions used:
- `react-native`: `0.24.0`
- `react-native-code-push`: `1.10.0-beta` (the release notes don't mention a change for this)
- The functionality itself works perfectly in TestFlight

**Comment by lostintangent** [comment]
@justim Interesting, we haven't seen an app be rejected for this purpose before. Is your app silently downloading the update and restarting on app start? If their issue is strictly that the content is synced with iCloud, we can definitely update the plugin to prevent this from happening.

**Comment by justim** [comment]
It's the very basic implementation of Code Push with just an `codePush.sync()` call in the `componentDidMount`, nothing fancy.

It seems from their feedback that it's just about the location of the bundle, which is synced to iCloud.

**Comment by lostintangent** [comment]
@justim Yep that makes sense. It's odd that we haven't seen this rejection before, and I really apologize for the issue. We'll make a change to the plugin to prevent iCloud syncing right now and will get that out ASAP. Stay tuned!

**Comment by justim** [comment]
Great! Thanks.

**Comment by lostintangent** [comment]
@justim This has been resolved via #321. If you want, you can pull the update from GitHub directly. Otherwise, we'll be releasing to NPM shortly. Let us know if you run into any other issues, and once again, apologies for this inconvenience!

**Comment by lostintangent** [comment]
@justim We just release `v1.10.6-beta` to NPM which includes this fix, along with some perf improvements to the update download process. Let us know how that works out for you. Thanks!

**Comment by justim** [comment]
Thanks! I just pushed a new version to iTunes Connect for review with the new version.

**Comment by justim** [comment]
Yay! Our app was successfully released. Thanks for the quick response! 👍

**Comment by lostintangent** [comment]
Yay!! Thanks for confirming the fix worked for you. 

Any chance you could share details about the app? It's always exciting to see what folks are using CodePush for.

**Comment by justim** [comment]
Yes, sure :)
We're currently in the progress of rebuilding our old app in React Native. We released a pretty basic version and want to use CodePush to quickly iterate with new features. It's exciting for us as well!

App store: [Dutch home rentals](https://itunes.apple.com/us/app/dutch-home-rentals/id540376128?ls=1&mt=8)

**Comment by lostintangent** [comment]
Awesome! Let me know if you guys are interested in having the app added to our [showcase](http://microsoft.github.io/code-push/community/friends.html). Your feedback on this was extremely helpful to identity a key bug with the product, so I'd love to advertise your awesome work if you're interested.

**Comment by justim** [comment]
Sweet, I created an issue for this, thanks! Microsoft/code-push#218
