### ISSUE TITLE
Expected receiver of type com.facebook.react.ReactActivity, but got 

### ISSUE THREAD

**Issue by ghalong** [Microsoft/react-native-code-push#328]
Hi, in my code,my React related Activity,like MyReactActivity did not extend the ReactActivity,but extend my own BaseActivity and implement the interface DefaultHardwareBackBtnHandler.The main code is 
` @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new CodePush(CODE_PUSH_KEY, this, BuildConfig.DEBUG))
                .setJSBundleFile(CodePush.getBundleUrl())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        mReactRootView.startReactApplication(mReactInstanceManager, "testApp", null);

        setContentView(mReactRootView);
    }`
when I use code-push release some update by cli,then I restart the MyReactActivity,I got a crash and the bellow error info
`java.lang.IllegalArgumentException: Expected receiver of type com.facebook.react.ReactActivity, but got com.meicai.mall.activity.MyReactActivity_
                                                  at java.lang.reflect.Field.get(Native Method)
                                                  at com.microsoft.codepush.react.CodePush$CodePushNativeModule.loadBundle(CodePush.java:400)
                                                  at com.microsoft.codepush.react.CodePush$CodePushNativeModule.restartApp(CodePush.java:648)`
then I checked the CodePush.java and located where the error was thrown,the code is 
`Field instanceManagerField = ReactActivity.class.getDeclaredField("mReactInstanceManager");
                instanceManagerField.setAccessible(true); // Make a private field accessible
                final Object instanceManager = instanceManagerField.get(mainActivity);`.
In there, expected mainActivity type is ReactActivity,but in my code，it is not.I also found the above code is wrapped by try-catch,but the expect error type is ReflectiveOperationException,it is not extend the IllegalArgumentException,so the APP crashed at last.By the way,after the crash happened,I reopen the App and found the released update have been deployed my device.

**Comment by lostintangent** [comment]
@ghalong Thanks for reporting this, and apologies for the issue. If you upgrade to the latest version of the plugin, the error handling will appropriately catch this issue, and will prevent your app from crashing.

That said, we'll definitely fix this bug, since our reload logic should be resilient to apps which aren't inheriting from ReactActivity, since that is a convention not a requirement.

Just for our own understanding, could you share why you aren't using ReactActivity? The code in your onCreate method seems to duplicate exactly what ReactActivity does for you, so I'd be curious to know what your use case is. Thanks!

**Comment by lostintangent** [comment]
@ghalong We just submitted a fix for this and will release it to NPM in the next day or so. You can either upgrade your bits from GitHub, or as I mentioned above, if you upgrade to the latest version on NPM, it will already include the improved error handling that will prevent this crash from happening. Thanks again for reporting this!

**Comment by ghalong** [comment]
@lostintangent Hi,thanks for your answer,because our BaseActivity have something that we have implemented previously，I want use them.I just the beginner of the RN and code-push,thanks for you asked  why me aren't using ReactActivity,now I realized it is not necessary using BaseActivity if I use the RN,using ReactActivity will be a better choice.

**Comment by lostintangent** [comment]
@ghalong Awesome, thanks for confirming. We made this fix anyways, but I would definitely recommend using ReactActivity if possible.
