### ISSUE TITLE
Travis support? code-push release-react

### ISSUE THREAD

**Issue by morgondag** [Microsoft/react-native-code-push#329]
Trigger to trigger stage deployment with travis build.

I can successfully login with a ```--accessKey```

```travis
Successfully logged-in. Your session file was written to /home/travis/.code-push.config. You can run the code-push logout command at any time to delete this file and terminate your session.
```

But the actually release always fails.

```travis
> code-push release-react myApp --entryFile ./index.ios.js ios -d Staging --mandatory
[Error]  Unable to find or read "Info.plist" in the "iOS/app" or "iOS" folders.
```
Tried without entryFile with the same result.
there is no ```iOS/app``` folder in a standard react-native build but there is a ```ios/app/``` folder.
Is there a config/fix for this?

**Comment by lostintangent** [comment]
@morgondag Thanks for reporting this! We definitely need to make this work on environments with case-sensitive file systems. We can get a fix for that out quick. In the meantime, you can work around this issue by explicitly passing the "--targetBinaryVersion" parameter to the release-react command. The CLI reads your app version from the plist file automatically, so if you give it an explicit version, then it won't try to read that file.

**Comment by lostintangent** [comment]
@morgondag We just submitted a fix for this and will release it to NPM this afternoon. In the meantime, the workaround that I mentioned should get you unblocked. Please re-open this issue if you are still running into issues. Thanks!

**Comment by morgondag** [comment]
@lostintangent 


```$code-push release-react myApp--entryFile ./index.ios.js ios -d Staging --mandatory --targetBinaryVersion```

Still gives this:
```
[Error]  Unable to find or read "Info.plist" in the "iOS/app" or "iOS" folders.
```

Seams to not be fixed in code-push-li either or there is no released version?
```
npm install -g code-push-cli@latest
```

```
1.10.0-beta
```

**Comment by lostintangent** [comment]
Apologies! We haven't released this fix to NPM yet. We'll be doing that today. In the meantime, if you set the "targetBinaryVersion" flag to bundle short string value in your Info.plist (e.g. 1.2.2), you won't get this error.

**Comment by morgondag** [comment]
@lostintangent not sure what you mean by targetBinaryVersion. 
adding a version to info.plist dosen't do anything.

**Comment by lostintangent** [comment]
In the CLI example you posted in your previous comment, you passed the "--targetBinaryVersion" flag to the release-react command, but you didn't specify the value (e.g. '--targetBinaryVersion "1.0.0"'. If you change that to pass the version number from your Info.plist file, it will work. This is because the release-react command only attempts to read your Info.plist file in order to infer your target binary version, and therefore, if you explicitly set it, then it doesn't need to read the Info.plist file at all.

**Comment by morgondag** [comment]
@lostintangent thank you for taking the time and explain. 
Passing ```--targetBinaryVersion '0.1.0'``` works!
