### ISSUE TITLE
I really need help

### ISSUE THREAD

**Issue by xhacker5000** [Microsoft/react-native-code-push#333]
My product sale on apple store.
and there are some bugs need using code-push update

but we release success on code-push  , the AppStore version never show the update dialog 

Could you please help us to check the code-push back-end server log ?

the App name is : ArtGallery

and AppStore name is :点影

**Comment by xhacker5000** [comment]
and the debug version can update by code-push .
any of AppStore version can not use code-push. I  don't know why :(

**Comment by xhacker5000** [comment]
I checked everything , CodePushDeploymentKey , and step debug code-push project;
every time code-push  return status = 4

that's meaning code-push up-to-date

but in fact it's not the newest version .


┌────────────┬──────────────────────────────────┬────────────────────────────┐
│ Name       │ Update Metadata                  │ Install Metrics            │
├────────────┼──────────────────────────────────┼────────────────────────────┤
│ Production │ Label: v13                       │ Active: 1.2% (2 of 164)    │
│            │ App Version: 2.0.4               │ Total: 3                   │
│            │ Mandatory: Yes                   │                            │
│            │ Release Time: 37 minutes ago     │                            │
│            │ Released By: project@loocall.com │                            │
│            │ Description: 点影更新                │                            │
├────────────┼──────────────────────────────────┼────────────────────────────┤
│ Staging    │ Label: v3                        │ Active: 1.0e+2% (23 of 22) │
│            │ App Version: 1.0.0               │ Total: 23                  │
│            │ Mandatory: Yes                   │                            │
│            │ Release Time: Mar 23             │                            │
│            │ Released By: project@loocall.com │                            │
│            │ Description: firstcommit         │                            │
└────────────┴──────────────────────────────────┴────────────────────────────┘


Please help

**Comment by geof90** [comment]
Hi @xhacker5000, your latest `Production` update targets appVersion **2.0.4**, but your latest app https://itunes.apple.com/us/app/dian-ying/id992080593?mt=8 is on **2.0.5**.

If you are sure that the latest update can apply to the **2.0.5** version, you can use the following command: 
```
code-push patch ArtGallery Production --targetBinaryVersion 2.0.5
```

**Comment by xhacker5000** [comment]
Oh , thanks very much  , I am very appreciate 👍 👍 👍 👍

**Comment by geof90** [comment]
@xhacker5000 awesome!
