### ISSUE TITLE
CodePush only update once

### ISSUE THREAD

**Issue by CoderZZheng** [Microsoft/react-native-code-push#336]
Development environment：Xcode7.3.1, RN： 0.25.1，code-push：1.7.3-beat

CodePush only update once，After that，an error occurred after new release updates (iOS) 。

[CodePush] An unknown error occurred.
[CodePush] R.getUpdateMetadata is not a function. (In 'R.getUpdateMetadata(e||E.UpdateState.RUNNING)', 'R.getUpdateMetadata' is undefined)

**Comment by geof90** [comment]
What version of `react-native-code-push` are you using? At first glace, it looks like the version of `react-native-code-push` JS code in your update contents is not in sync with your app's Obj-C code. [The getUpdateMetadata change was only introduced in react-native-code-push@1.10.3-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v1.10.3-beta), therefore if you released a JS update which bundles up a newer version of the plugin and it gets downloaded by an app using an older version of the plugin, that error can occur. 

If you upgraded our plugin, make sure you redeploy a new binary / release a new binary to the app store, to prevent this issue.

**Comment by CoderZZheng** [comment]
Thank you, you may be right, I'm testing now

**Comment by lostintangent** [comment]
@CoderZZheng Did this resolve your issue? We aren't able to repro it on our end, so it would be great to make sure you're unblocked.

**Comment by lostintangent** [comment]
I'm going to close this issue since as @geof90 mentioned, this appears to be a result of your native code being out of sync with the JS code in your app. Please reopen this if the problem persists. Thanks!
