### ISSUE TITLE
Working with ZipArchive

### ISSUE THREAD

**Issue by wrlqwe** [Microsoft/react-native-code-push#337]
CodePush and ZipArchive are used in my project with CocoaPods, they both import the "aes" and "minizip" libs which made conflicts, so how could I do to make them work well?

**Comment by geof90** [comment]
@wrlqwe I believe https://github.com/Microsoft/react-native-code-push/issues/241 is a similar issue, let me know if the solution steps in that issue work for you.

**Comment by wrlqwe** [comment]
@geof90 sorry for the late reply, I haven't use this solution because each developers in our team have to configure this, I fix this by wrote an script to remove the minizip and aes libs refs in CodePush's podspec and link it to npm's post-install script, everyone's 'pod install' will install CodePush without these 2 libs, so everyone would be happy. 😁

**Comment by lostintangent** [comment]
@wrlqwe Would it be helpful if we updated our podspec to include a subspec that exclude these? That way, you wouldn't need the post-install script. You would simply need to update your pod file to depend on the "no-SSZipArchive" version of CodePush.

**Comment by lostintangent** [comment]
@wrlqwe Regardless if you keep your private script, I wanted to take this opportunity to improve this situation for future users. Could you take a quick look at #348 and see if that looks reasonable? Thanks!

**Comment by wrlqwe** [comment]
@lostintangent may be you could use spec.dependency to manage SSZipArchive. but this problem is conflicts between ZipArchive and SSZipArchive after all, because they both using minizip and aes by containing them in their pods, not CodePush's problem...

may be our team should not use mattconnolly/ZipArchive any more, it's inactive for a long time.

**Comment by lostintangent** [comment]
@wrlqwe The reason we aren't using CocoaPods to manage our `SSZipArchive` dependency is so that React Native users who aren't using CocoaPods don't need to run `pod install`. I like that CodePush is fully self-contained for most of our users. That said, if someone is directly using CocoaPods, then it definitely makes sense that we allow linking with CodePush without `SSZipArchive` included.

**Comment by lostintangent** [comment]
I'm going to close this via #348. It sounds like you're unblocked via your own scripts, but let us know if you run into any other problems or if the pod spec change doesn't suit your needs. Thanks!

**Comment by chirag04** [comment]
@lostintangent can we do something for those who are not using CocoaPods ?

**Comment by sidferreira** [comment]
It should be reopened...
