### ISSUE TITLE
Binary hashing doesn't appear to be working on iOS

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/react-native-code-push#345]
I may be misinterpreting these results, but I would expect the following to work:

1. Run `react-native run-ios` to deploy an app to the iOS simulator
2. Run `code-push release-react [APP] ios --dev` to deploy the exact same bits as #1 to the CodePush server
3. From the running app, check for an update

**Expected:** No update to be available since the app is already running the latest update
**Actual:** An update is available

Is this expectation accurate? I tried to get this to work a handful of different times and couldn't. I also didn't try Android, so I'm not sure how that currently behaves.

I recently spoke with someone on Discord about them noticing this behavior, but they thought it could have been their fault. After doing some quick dogfooding, it seems like it isn't working correctly, and therefore, more be a regression on our end, or a change in the RN bundle that is making these contents appear different.

**Comment by geof90** [comment]
Looking into this now

**Comment by geof90** [comment]
It seems RN broke this feature. The generated bundle when you run `react-native bundle` and the one generated in the app is different. This repros in 0.27.0-rc, it does not repro in 0.19. I'm not sure if 0.26.1 has the same issue.

**Comment by geof90** [comment]
Additionally, in 0.27.0-rc, everytime u run `react-native bundle` with the `--reset-cache` flag, it generates a slightly different jsbundle.

**Comment by lostintangent** [comment]
If you remove that flag from the Xcode build script does this feature suddenly work?

**Comment by geof90** [comment]
Well.. It looks like module IDs attached to each module in the JS bundle gets randomized each time.
![image](https://cloud.githubusercontent.com/assets/8598682/15492848/768377ec-2134-11e6-8e77-ce8f19cf660d.png)

@lostintangent all `--reset-cache` does is basically the same as `rm-rf $TMPDIR/react*` right? It wouldn't suddenly work because our CLI clears the cache too in `release-react`.

**Comment by lostintangent** [comment]
I'm marking this as external now that we now it's an issue with React Native/node-haste. It looks like they may fix it, so we can use this bug to track it.

**Comment by lostintangent** [comment]
Closing this is a dupe of #352, since we'll track both scenarios via the same root problem.
