### ISSUE TITLE
question about update download

### ISSUE THREAD

**Issue by hanleirx** [Microsoft/react-native-code-push#351]
When I update my project ,I need to download the bundle file .I want to know the bundle file is total file or the changed part file.I looked the introduction and I didn't find the answer.
Thank you!

**Comment by lostintangent** [comment]
The client will only download files which have changed, but we don't currently support syncing just a subset of a single file. So if you release an update that only changed JS and not images, then the next time your app syncs with the server, it would download the entire JS bundle file but not the images.

**Comment by hanleirx** [comment]
Sorry,I don't understand.You mean react-native-code-push can't only renew the changed file,right?
For example,
first version:
<Text style={styles.welcome}>
          Just try it！
        </Text>
second version:
<Text style={styles.welcome}>
          Just try it again!
        </Text>
so every time I will download the the same part,is it?

**Comment by lostintangent** [comment]
If you release an update that changed th JS bundle, then your users will re-download the entire JS bundle. But they won't download any files which didn't change (like images).

**Comment by hanleirx** [comment]
Ok ,thank you .I got it.

**Comment by lostintangent** [comment]
OK cool, I'll close this issue for now then.
