### ISSUE TITLE
gradle.properties doesn't appear to be used when build.gradle is run

### ISSUE THREAD

**Issue by nicinabox** [Microsoft/react-native-code-push#353]
When I run `release-react` for android I get the following error:

> [Error]  The "android.defaultConfig.versionName" property in "android/app/build.gradle" needs to have at least a major and minor version, for example "2.0" or "1.0.3".

I have an `android/gradle.properties` in my project with version and build number that updates from our build system:

```
VERSION_NAME=2.8.4
VERSION_CODE=166
```

And these are referenced in `android/app/build.gradle`:

```
// snip from android/app/build.gradle
defaultConfig {
        applicationId "com.advisory.crimsonconnect"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode project.VERSION_CODE.toInteger()
        versionName project.VERSION_NAME
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```

I'm pretty new to gradle, but should code-push be picking up configuration from `gradle.properties`?

**Comment by lostintangent** [comment]
@nicinabox Ah, yeah our logic that tries to infer the app version isn't currently smart enough to parse this. One way to work around it in the meantime is to explicitly pass the `-t "2.8.4"` flag to your call to `release-react`. That will prevent the `release-react` command from trying to parse the Gradle file in the first place.

**Comment by nicinabox** [comment]
Works for me. Thanks for the tip!

**Comment by lostintangent** [comment]
Awesome :) I'm going to leave this bug open to track us adding support for reading the `gradle.properties` file in the event that a `build.gradle` is referencing a project property as its `versionName`. My previous comment will help unblock you in the meantime, but I want this scenario to just work. Thanks for the feedback!

**Comment by lostintangent** [comment]
@nicinabox FYI, I just sent out a PR that addresses this scenario and will allow you to start releasing Android updates to CodePush without needing to explicitly set the target binary version.

**Comment by nicinabox** [comment]
![excited birthday](https://cloud.githubusercontent.com/assets/246280/16200328/7edb8bb0-36d2-11e6-9cd3-dc2909c74dc2.gif)

**Comment by lostintangent** [comment]
This has been resolved and will be included in our next CLI release tomorrow. Thanks again for the feedback!

**Comment by lostintangent** [comment]
This has been released to NPM, so once you upgrade, you should be good to go :)
