### ISSUE TITLE
I want to know the principle

### ISSUE THREAD

**Issue by hanleirx** [Microsoft/react-native-code-push#354]
Hello, I want to know why when I run 'code-push release-react <appName> <platform>',it can package the js file. How did it work? Which part of code does it use?

**Comment by dtivel** [comment]
The implementation for `code-push release-react` starts [here](https://github.com/Microsoft/code-push/blob/master/cli/script/command-executor.ts#L1133), and the code that packages the JavaScript file is the [part](https://github.com/Microsoft/code-push/blob/master/cli/script/command-executor.ts#L1251) that runs the react-native CLI.  The CodePush CLI releases the bundle [here](https://github.com/Microsoft/code-push/blob/master/cli/script/command-executor.ts#L974).

**Comment by hanleirx** [comment]
OK，thank you!

**Comment by lostintangent** [comment]
I'm going to close this issue for now since I think your question was answered. Let us know if you have any other questions or run into other issues. Thanks!
