### ISSUE TITLE
Error restartApp in Android

### ISSUE THREAD

**Issue by jerson** [Microsoft/react-native-code-push#356]
im using restartApp in android 

```
 codePush.restartApp(false);
```
and I returns this error and closes the application
```
05-27 15:55:17.862 28557 28595 W System.err: 	at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:420)
05-27 15:55:23.104 28557 28595 D ReactNative: [CodePush] Loading JS bundle from "assets://null"
```

**Comment by geof90** [comment]
Hi @jerson, right now, our CodePush runtime has no ability to know what the file name of your bundled JS file is if `CodePush.getBundleUrl()` is not called previously. Did you follow all of the [plugin configuration](https://github.com/Microsoft/react-native-code-push#plugin-configuration-android) steps listed here, in particular, the overriding of the `getJSBundleFile()` method?

**Comment by jerson** [comment]
Sorry was my mistake


I had forgotten to add this
```
 @Override
    protected String getJSBundleFile() {
        return CodePush.getBundleUrl();
    }
```

now it works. thank you very much
