### ISSUE TITLE
R.strings should be R.string

### ISSUE THREAD

**Issue by niksinfinite10** [Microsoft/react-native-code-push#358]
react-native-cli is generating code with R.strings in MainActivity.java which should be R.string

**Comment by lostintangent** [comment]
@niksinfinite10 Did you use RNPM to install the CodePush plugin? We don't generate any code in your MainActivity.java file that references the R class, so this typo sounds like a bug with rnpm-plugin-link. I can take a look into this and potentially file a bug with them.

**Comment by lostintangent** [comment]
I confirmed that this behavior is coming from RNPM, and I logged a [bug](https://github.com/rnpm/rnpm-plugin-link/issues/86) to track it. Thanks for letting us know!

**Comment by lostintangent** [comment]
This was just resolved by the RNPM team, so I'm going to resolve this.
