### ISSUE TITLE
iOS folder name

### ISSUE THREAD

**Issue by AwesomeJerry** [Microsoft/react-native-code-push#361]
The default project folder generated by "react-native init AwesomeProject" contains "ios" folder not "iOS" on Linux.
 It should support "ios" folder name when releasing by "code-push release-react appName ios".
![screenshot from 2016-06-01 11 40 33](https://cloud.githubusercontent.com/assets/6601073/15697539/aff7e3f4-27ed-11e6-883b-b574eeb1d119.png)
![screenshot from 2016-06-01 11 41 34](https://cloud.githubusercontent.com/assets/6601073/15697554/d5e04ae8-27ed-11e6-8d5a-3974e2ba896e.png)

**Comment by lostintangent** [comment]
@AwesomeJerry We actually fixed this issue in v1.11.0 of the CodePush CLI. Could you check if you're already running that version? If not, you should be able to update to the latest on NPM and be good to go. Otherwise, we can investigate why you're still hitting this problem.

**Comment by AwesomeJerry** [comment]
I was in v1.7.0-beta. Thanks for the information. Closing the issue :D

**Comment by lostintangent** [comment]
Awesome! Thanks for confirming this.
