### ISSUE TITLE
Idea: codePush.InstallMode.ON_NEXT_SUSPEND

### ISSUE THREAD

**Issue by nevir** [Microsoft/react-native-code-push#366]
Another mode, similar to `codePush.InstallMode.ON_NEXT_RESUME`, except that it applies the update in the background (after some delay).  

This would be a potential speed up when resuming the app (e.g. when brought back from suspension) - I'm not sure if the added complexity is worth it (for `sync()`), though 

---

On the iOS side, this would require some extra work via a background task (and some API exposed for it), I think.  Similar setup for (newer) Android, too, I think.

**Comment by nevir** [comment]
(or, it might be worth waiting for react native to provide an abstraction for background tasks)

**Comment by lostintangent** [comment]
@nevir That's an awesome idea :) We'll definitely have to do an investigation into what this would look like. In lieu on RN improving their background task story, we also have quite a few users embedding RN into existing native apps, and have asked to be able to do the install in the background so as to mitigate the restart flash.

**Comment by nevir** [comment]
> and have asked to be able to do the install in the background so as to mitigate the restart flash.

The way we're mitigating that is to expose a hook to show/hide our splash screen (which is handy for masking any view screwups on app launch, too).  We hide the splash screen once everything has spun up (around the same time we call `notifyAppReady`).  Not sure _that_ is easily to abstract, though

**Comment by lostintangent** [comment]
@nevir I threw together prototype of this feature to test it out, which in addition to adding the new install mode, also supports the existing `minimumBackgroundDuration`, that way you can do either of the following:

```javascript
// Restart the app as soon as the app is put into the background,
// instead of waiting for it to be resumed to the foreground
codePush.sync({ installMode: codePush.InstallMode.ON_NEXT_SUSPEND });

// Restart the app _while_ it is in the background, but only after it has
// been in the background for 2 minutes, so that user context isn't
// lost unless the app suspension is long enough to not matter
codePush.sync({ 
    installMode: codePush.InstallMode.ON_NEXT_SUSPEND,
    minimumBackgroundDuration: 2 * 60
});
```

Does that match the use cases you had in mind? It definitely is a pretty awesome experience.

**Comment by nevir** [comment]
Yeah!  That's perfect!  We'd want to use the `minimumBackgroundDuration` approach

(also, just to make sure: I'm assuming this works via `localPackage.install()` as well)

**Comment by lostintangent** [comment]
@nevir Yep this would work with LocalPackage.install as well!

**Comment by tomauty** [comment]
I would love this! Sorry for a useless comment, but I hope this makes it in soon.

**Comment by panarasi** [comment]
@lostintangent Do you still have that prototype ? We are thinking of move all update logic to the native land - that would help with background updates. However, if you were able to solve it in a different way, I think we should look at that too.

**Comment by panarasi** [comment]
@sergey-akhalkov Can you investigate this issue ? This may be possible once we move all our logic to native code.

**Comment by sergey-akhalkov** [comment]
Hi @nevir, @tomauty, I've just created the [PR ](https://github.com/Microsoft/react-native-code-push/pull/770) that implements this feature, would you have a chance to look at it and verify if it works as expected?

**Comment by sergey-akhalkov** [comment]
Closing this due to #770 has been merged
