### ISSUE TITLE
Dev, staging and production environments

### ISSUE THREAD

**Issue by wrousseau** [Microsoft/react-native-code-push#374]
Hi there,

Thanks for this and the documentation which looks really exhaustive. I'm not sure if this is the right place but I feel like the following code

```
NSURL *jsCodeLocation;

#ifdef DEBUG
    jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif
```

used to work in dev mode is not compatible with the multi-environment part of the tutorial. From what I understand, the "DEBUG" is then used for the staging environment and must also use `jsCodeLocation = [CodePush bundleURL];`. Is it possible to have a dev environment (using the `NSURL`), a staging environment and a prod environment ?

Thanks in advance, if it is not clear, I'd be happy to provide more details !

Woody

**Comment by lostintangent** [comment]
Yeah you're totally right. To keep things simple, I wrote the multi-deployment doc using the standard debug and release configurations within the Xcode project, but in practice, you would likely want to create a new configuration called "Staging" (or similar) that would allow you to configure it seperately from your actual local debugging environment. 

Apologies for the confusion. I'll update the docs later this morning to call this out. The AppDelegate.m code sample will remain the same, but the multi-deployment setup will just include a few more steps to create the staging configuration, and then instructions on how to build the app using the newly created staging configuration.

Thanks so much for the feedback!

**Comment by wrousseau** [comment]
Thank you for answering so quickly ! This is something I will likely need in the following few days so if you need some extra feedback or even some help, I'd be more than happy to provide some (even though I'm just getting started with react native, coming from Ionic).

**Comment by lostintangent** [comment]
Perfect. I'll send out the PR with the changes this afternoon and will CC you on it to get feedback before we merge it in.

**Comment by lostintangent** [comment]
Just updated the docs to include mention of how to create a new `Staging` configuration. Let me know what you think.

**Comment by lostintangent** [comment]
I'm going to close this for now, but please re-open it or comment if you feel like we need to add more detail to the docs. Thanks again for the feedback and sorry for the confusion!

**Comment by huseyin39** [comment]
Hi,
When changing the scheme configuration to Staging, Metro bundler is still needed to run the app (on React Native). 
I expected to run it like an actual release.
