### ISSUE TITLE
Can get stuck in an infinite update loop

### ISSUE THREAD

**Issue by nevir** [Microsoft/react-native-code-push#378]
(advanced-mode only)

If you call `LocalPackage#install()`  before calling `codePush.notifyAppReady()`, your application will restart forever, even if the package being loaded is the one that was asked to install.

It appears a bit difficult to detect, at least in Obj-C land, as the update isn't marked with "IsLoading" until some time later (next full launch).  Should that flag be set whenever reloading the bundle, too?

---

rough repro steps are just to have a bundle that does:

```
const remote = await codePush.checkForUpdate();
const pending = await remote.download();
await pending.install(codePush.InstallMode.IMMEDIATELY);
```

**Comment by nevir** [comment]
So, this is actually a bit of an issue for us:

* We'd like to be able to check for updates _before_ the app fully loads
  * Intention: ensure that first launch after downloading a new native app has the most recent bundle (transparently to the user)
  * We'll also time it out after a few seconds and just update in the background (in case of bad connectivity)
* But at the same time, we don't want to mark the app as ready before that (since we're not likely to encounter errors on boot until after checking for updates on boot)

**Comment by lostintangent** [comment]
We can look into this ASAP to make sure you're unblocked. Just to make sure we can repro this, can you share where in your app you're calling the code snippet you previously posted, and where you're calling notifyApplicationReady? Or does it matter?

**Comment by nevir** [comment]
Thanks!  Really appreciate how response you guys are

Doesn't seem to matter (since the currently-applying package stays pending until we call `notifyAppReady`) - but we do call `notifyAppReady` asynchronously later (if there is no update to install), often 250ms+ later

Here's a slightly cleaned up copy of what we've got atm:

```
function handleAppLaunch() {
  return new Promise((resolve, reject) => {
    let completed = false;

    setTimeout(() => {
      if (completed) return;
      completed = true;
      resolve();
    }, 5000);

    codePush.sync({installMode: codePush.InstallMode.ON_NEXT_RESUME})
      .then(() => {
        // We didn't make it in time; nothing more to do.
        if (completed) return;
        completed = true; // Don't allow the timer to fire.
        const pendingPackage = await codePush.getUpdateMetadata(codePush.UpdateState.PENDING);
        pendingPackage.install(codePush.InstallMode.IMMEDIATE).then(resolve, reject);
      })
      .catch(error => {
        if (completed) {
          console.error(`handleAppLaunch failed after timeout:`, error);
        } else {
          completed = true;
          reject(error);
        }
      });
  });
}
```

**Comment by lostintangent** [comment]
OK perfect, thanks so much for providing this snippet. I'll try to repro this, but in parallel, I wonder whether you couldn't replace the call to getUpdateMetadata and LocalPackage.install with codePush.restartApp(true). I believe that would achieve the experience you want (force an immediate restart if the update was downloaded within a certain threshold), and may workaround a bug we have with the LocalPackage.install method.

**Comment by nevir** [comment]
Sorry, just updated that snippet too - not actually calling `sync()` :P

**Comment by lostintangent** [comment]
My same comment applies to your new snippet :) I think you could simplify your then callback via the suggestion I mentioned previously, and that _may_ also resolve this issue.

**Comment by nevir** [comment]
Yup, tweaking my code to see how it goes!

Also, huh, it does happen when calling `sync()` too - that's not what I expected (because sync calls `notifyAppReady`)!

**Comment by nevir** [comment]
...it also isn't updating the bundle URL (still pointing to the baked in bundle)

**Comment by nevir** [comment]
Ha, perfect, the `restartApp(true)` workaround works like a charm thus far!  Testing a little bit more

**Comment by lostintangent** [comment]
Yay! That is the solution I would actually recommend, so if you're cool with that code, then that should unblock you, and we can investigate this bug in parallel.

**Comment by nevir** [comment]
Yeah, that seems like a pretty straightforward approach to me!  If it's the recommended approach, all the better :)

**Comment by nevir** [comment]
you know, it might actually be good to just throw if someone calls `install` when there's an update being loaded?  Or maybe just silently ignore it if it's the same update that's currently being loaded?

**Comment by lostintangent** [comment]
Yeah that solution would make sense. I think that's how we'll actually resolve this.
