### ISSUE TITLE
Add UpdateState.DOWNLOAD

### ISSUE THREAD

**Issue by cameronbourke** [Microsoft/react-native-code-push#383]
There is a situation where the `remotePackage` has been downloaded, however the `localPackage` has yet to be installed. I would like to be able to check for this and have the `localPackage` returned using `getUpdateMetadata`. That would mean that `UpdateState.DOWNLOAD` would indicate the following: 

> Indicates than an update has been downloaded, but it has yet to be installed. This can be useful for determining whether there is a downloaded update, which you may want to programmatically install, whether it be at a later date or in response to an action by a user.

Love to hear your thoughts! (note this simply an enhancement, not a bug)

**Comment by lostintangent** [comment]
Would calling `getUpdateMetadata(UpdateState.PENDING)` satisfy your requirements? A "pending" update is one that has been downloaded but not yet installed. It's possible that our docs explain `UpdatetState.PENDING` poorly, so either we can improve them if this fits your needs, or we can definitely make sure to add the necessary new state for this scenario. Thanks!

**Comment by cameronbourke** [comment]
@lostintangent That was my assumption as well! But I think the docs detail a similar but different scenario. The `UpdateState.PENDING` in the DOCS reads as:

> Indicates than an update has been installed, but the app hasn't been restarted yet in order to apply it. This can be useful for determining whether there is a pending update, which you may want to force a programmatic restart (via restartApp) in order to apply.

In my case, the update has not been installed yet, only downloaded.

**Comment by lostintangent** [comment]
@cameronbourke Are you explicitly calling `remotePackage.download` and not installing the update until some later point, or are you calling `sync`? If the later, then the update is always being "installed", but the restart won't happen until the point that you specify via the `InstallMode` (e.g. resume).

**Comment by cameronbourke** [comment]
@lostintangent Thanks for the quick reply! I am doing the earlier: 
> calling `remotePackage.download` and not installing the update until some later point

**Comment by lostintangent** [comment]
We actually add an isPending property to the localPackage after it's installed, so assuming that you have a reference to the package so that you can install it, you could potentially use the localPackage.isPending property to check whether the local package that you've downloaded is pending (install was called on it) or not. Would that work?

**Comment by lostintangent** [comment]
BTW, is this to support your react-native-cp-update-button component? As an aside, we should figure out how to incorporate that into our docs so that it gets the deserved visibility.

**Comment by cameronbourke** [comment]
My use case the moment is to be able to do the following:
```
getUpdateMetadata(UpdateState.DOWNLOADED)
```
So that returns to the localPackage downloaded as opposed to what I am doing currently to cache that version @ https://github.com/cameronbourke/react-native-cp-update-button/blob/master/src/lib/downloadNewVersion.js#L7

**Comment by cameronbourke** [comment]
@lostintangent Haha yeah it is! That would be awesome, more than welcome to get some feedback from you guys on how it can be improved as well!

**Comment by panarasi** [comment]
@cameronbourke Do you still need this functionality ?

**Comment by panarasi** [comment]
@cameronbourke Thanks for the info. In that case, let me close this issue for now, and copy this over to our backlog.
