### ISSUE TITLE
[Android] buildConfigField saved in BuildConfig.java is not enclosed in quotes

### ISSUE THREAD

**Issue by imalbert** [Microsoft/react-native-code-push#390]
I followed https://github.com/Microsoft/react-native-code-push#android;

It appears that the line 
`buildConfigField "String", "CODEPUSH_KEY", "EXAMPLE_STAGING_KEY"` generates
`public static final String CODEPUSH_KEY = EXAMPLE_STAGING_KEY` in BuildConfig.java

When I run `react-native run-android` it gives an error pertaining to it (';' expected and <identifier> expected)

react-native 0.24.0
react-native-code-push 1.12.2-beta

**Comment by lostintangent** [comment]
@imalbert What version of RNPM are you running? That code you mentioned is actually generated by RNPM, not our plugin, so if there's a bug in it, I can follow up with them to get it looked at.

**Comment by imalbert** [comment]
I'm using rnpm 1.9.0

**Comment by ashleydw** [comment]
Got the same, the docs should state:

`buildConfigField "String", "CODEPUSH_KEY", '"<INSERT_STAGING_KEY>"'`

Note the single quotes outside the double. More info: http://stackoverflow.com/questions/30796533/how-to-generate-buildconfigfield-with-string-type

**Comment by lostintangent** [comment]
Ah right, my bad. I just fixed this. Thanks so much for the feedback here!

**Comment by imalbert** [comment]
This is awesome. Thanks guys!

**Comment by pavelyevchenko** [comment]
why then applicationId "some string" - goes without double quotation ?
