### ISSUE TITLE
[RN 0.29.0] Rationalize RCTBundleURLProvider

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/react-native-code-push#393]
As of React Native 0.29, the generated `AppDelegate.m` file includes the following code to determine the JS bundle's location:

``` objective-c
NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
```

The nice thing about this new solution, is that it handles using the packager in debug-mode and the bundled JS file in release mode (kind of like how Android already works). Therefore, devs don't need to use an `#if DEBUG` statement to toggle between the two.

We should think about how we expect devs to use CodePush in conjunction with this new API and/or if we need to expose a new API that effectively uses the `RCTBundleURLProvider` under the hood (e.g. `[CodePush jsBundleURLForBundleRoot]`).

I validated that CodePush works great on iOS in RN 0.29, but we need to update our docs and potentially our API in order to fully embrace the new `AppDelegate.m` code.

**Comment by lostintangent** [comment]
After thinking about this again, I wonder whether the simplest thing to do here is to simply update our docs to call out the following for RN v0.29.0+ apps:

```javascript
NSURL *jsCodeLocation;

#ifdef DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif

The only thing that is "odd" about that, is that the `RCTBundleURLProvider` will also return the path to the binary if the packager isn't running. So if the app was in debug-mode, but the dev had for some reason stopped the packager, the app would use the binary-bundled bits, which isn't necessarily obvious. I think it's fine for now though.

**Comment by stovmascript** [comment]
My DEBUG build is acting strangely with this configuration, which I've made myself and thought would work. It will try to load the offline bundle - the dev menu also looks like the offline bundle should be loaded, since half of the options (live reload, etc.) are missing. But after reloading, I get a redbox error complaining that the packager server isn't running.
