### ISSUE TITLE
[RN 0.29.0] Android Native Module

### ISSUE THREAD

**Issue by janicduplessis** [Microsoft/react-native-code-push#394]
Native module creation has been moved to ReactNativeHost and is created in the android Application instead of Activity by default. It would be nice to remove the need to pass the activity to the native module (no idea if it is actually possible) or add instructions to move the ReactNativeHost back to the Activity.

**Comment by geof90** [comment]
@janicduplessis working on it!

**Comment by lostintangent** [comment]
The fix for this has been merged into master, so if anyone wants, you can install the bits from there. Additionally, we'll release this to NPM later this afternoon. Thanks!
