### ISSUE TITLE
About CodePush.SyncStatus.UPDATE_APPLIED Event

### ISSUE THREAD

**Issue by TanTan-TT** [Microsoft/react-native-code-push#40]
Hi
    As your code  in sync() method

       remotePackage.download()
                  .then((localPackage) => {
                    resolve(CodePush.SyncStatus.UPDATE_APPLIED)
                    return localPackage.apply(syncOptions.rollbackTimeout);
                   })

   I believe it is a little usage to call UPDATE_APPLIED event after download finished. Because after reload js package, view will be refreshed and reload new package. This reload action can not be controled by developers. So I wish you apply UPDATE_APPLIED event before download.
I am in China so download package for your API is slow, so I have to add a spinner in my App when download started.

**Comment by TanTan-TT** [comment]
@geof90 I want to propose another enhancement for download new js package. Is there possible to get progress when downloading js package?

**Comment by lostintangent** [comment]
@TanTan-TT We plan on adding support for this very soon. Thanks for giving us the additional feedback!

**Comment by TanTan-TT** [comment]
@lostintangent Thanks. I will try it first when you release this.

**Comment by TanTan-TT** [comment]
@lostintangent I have upgraded the lastest version. All new features are great!

**Comment by lostintangent** [comment]
Awesome! I'm happy to hear that :)
