### ISSUE TITLE
how should I custom updateDialog?

### ISSUE THREAD

**Issue by L-Jovi** [Microsoft/react-native-code-push#402]
when I called `codePush.sync({ updateDialog: {...} });`

I want to custom textAlign of `Alert`, like `textAlign: left`, how could I implement that?

thanks for your time.

**Comment by lostintangent** [comment]
@L-Jovi We use the standard React Native `Alert` module to display the update dialog, which as far as I can tell, doesn't expose any way to control the text alignment. Under the covers, this module is using the system dialog for iOS and Android, including the default styling, which I believe provides the most consistent looking experience for end users.

If you needed to control the text alignment of the message, I think you'd have to use a custom 3rd party dialog module that supported it. You can then use your own custom dialog when calling `sync` by not enabling the `updateDialog` property, and showing your own dialog in the sync status callback.

**Comment by L-Jovi** [comment]
@lostintangent  thanks for your patient reply :)

**Comment by lostintangent** [comment]
@L-Jovi Absolutely! Let us know if you'd like us to investigate this more. In theory, I think we could support changing the text alignment, but it might require tweaking the runtime UI tree in a way that could break across OS versions. Thanks again for the feedback!
