### ISSUE TITLE
Prerelease deployments ending up in Production

### ISSUE THREAD

**Issue by nicinabox** [Microsoft/react-native-code-push#403]
Hey guys, we're seeing some weird issues that don't make any sense to us, but might to you.

We're using 2 deployments: Prerelease and Production in conjunction with HockeyApp and the App Store. Prerelease code pushes target HockeyApp binaries, and Production code pushes target App Store binaries. These releases use separate Info.plist files with different code push keys.

10 days ago I released a code push to Prerelease (2.9.7 targeting the 2.8.11 binary). A couple days later I promoted it to Production targeting the 2.8.4 App Store binary.

We already had a newer binary in the App Store by this time (2.8.11) and realizing my mistake, promoted 2.9.7 to Production targeting the newest binary (2.8.11).

All's well I think and I continue on with normal development and 3 more releases to Prerelease. Cool.

Today I get a report of a user having 2.9.10 installed. No way I claim, not possible. That's a Prerelease version and the newest Production version is 2.9.7. But then I saw screenshots, and it was true.

I checked the deployment history for both deployments and this is where things get weird. We have less than 10 people provisioned to receive prereleases, but see Prerelease installs like we should for Production.

Right around the time we had 2.8.11 in Production, our 2.8.11 Prereleases appear to start leaking out and the 2.9.7 promotion (targeting 2.8.11 in Production) never got any installs. They all seem to be on the Prerelease.

Prerelease deployment for the last month:
![screen shot 2016-06-27 at 3 24 00 pm](https://cloud.githubusercontent.com/assets/246280/16395234/7dbf8eb4-3c7e-11e6-93cf-754902159e4f.png)

Production deployment:
![screen shot 2016-06-27 at 3 26 16 pm](https://cloud.githubusercontent.com/assets/246280/16395241/83f5bf42-3c7e-11e6-80a1-f8a1eec8d07b.png)

Sample command when releasing:
```bash
$ code-push release-react CrimsonConnect ios -t 2.8.11 --description 2.9.10+284 --deploymentName Prerelease
```

App Store versions | Date
---|---
2.8.11 | June 7
2.8.4 | May 27

**Comment by nicinabox** [comment]
I guess sometimes you just need to tell someone your problem so you can connect the dots in your head.

I'm pretty sure I know what happened. This isn't an issue in code push. 

When I submitted 2.8.11 I remember having trouble with xcode not opening, so I submitted the existing binary using Application Loader. I'm almost positive that I uploaded the same binary used for HockeyApp to the App Store. This would explain why the Production release isn't working and users are getting updates from Prerelease.

Sorry to trouble you all, you're doing great <3

**Comment by lostintangent** [comment]
@nicinabox When I read your first post, my initial thought was that it seemed too coincidental that you started seeing production users getting pre-release CodePush updates after you did an App Store update :) Let us know if you run into any other issues here!

**Comment by nicinabox** [comment]
Totally. Thanks for being my rubber ducky :)
