### ISSUE TITLE
No installs recorded

### ISSUE THREAD

**Issue by mumuda** [Microsoft/react-native-code-push#412]
when I  use code-push, it is alway show this  "No installs recorded",    who can help me 
,┌───────┬────────────────┬─────────────┬───────────┬─────────────┬──────────────────────┐
│ Label │ Release Time   │ App Version │ Mandatory │ Description │ Install Metrics      │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v1    │ 23 minutes ago │ 1.0.1       │ No        │             │ No installs recorded │
├───────┼────────────────┼─────────────┼───────────┼─────────────┼──────────────────────┤
│ v2    │ 16 minutes ago │ 1.0.1       │ No        │             │ No installs recorded │

**Comment by geof90** [comment]
Have you configured an app to download and install the update? Are you seeing the install happen successfully?

**Comment by mumuda** [comment]
when i update  ， code-push release XXXX， it is successful， i open app again，it show message To install， but  It didn't update，I do this :code-push deployment history LU9 Staging，this show   No installs recorded。in Xcode  info.plst  ,I add CodePushDeploymentKey with  Staging key
