### ISSUE TITLE
[ANDROID] - unchecked call to getMethod(String,Class<?>...) as a member of the raw type Class

### ISSUE THREAD

**Issue by mtunique** [Microsoft/react-native-code-push#417]
\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:115: warning: [unchecked] unchecked call to getMethod(String,Class<?>...) as a member of the raw type Class
                    Method getReactNativeHostMethod = reactApplicationClass.getMethod("getReactNativeHost");
                                                                                     ^
\node_modules\react-native-code-push\android\app\src\main\java\com\microsoft\codepush\react\CodePushNativeModule.java:118: warning: [unchecked] unchecked call to getMethod(String,Class<?>...) as a member of the raw type Class
                    Method getReactInstanceManagerMethod = reactNativeHostClass.getMethod("getReactInstanceManager");
                                                                                         ^
error: warnings found and -Werror specified
1 error
2 warnings

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-code-push:compileReleaseJavaWithJavac'.

**Comment by mtunique** [comment]
Find another way to implement it or disable Werror in subprojects.

**Comment by lostintangent** [comment]
@mtunique If you pull the latest bits from this repo instead of NPM, does that resolve the issue? We recently disabled lint warnings from failing the build, so you hopefully shouldn't be running into this. We should fix the lint warnings in general, but you should be able to get unblocked with the bits from master.

**Comment by mtunique** [comment]
Thanks.But the latest bits from this repo can't resolve the issue.

**Comment by silhouettes** [comment]
Hey @mtunique, sorry about this! I'll be looking into this tomorrow.

**Comment by silhouettes** [comment]
#421 should fix this :)

**Comment by geof90** [comment]
@mtunique #421 has been merged, if you pull down the latest bits from master, do you still hit this issue?

**Comment by mtunique** [comment]
@geof90  Thanks. It is fixed.

**Comment by geof90** [comment]
We've published react-native-code-push@1.13.3 to NPM that includes this fix.
