### ISSUE TITLE
HMR support for updating jsbundle?

### ISSUE THREAD

**Issue by LeBlaaanc** [Microsoft/react-native-code-push#419]
It'd be super duper awesome to explore if hot module reloading could be used to update the jsbundle removing the need for enduser to relaunch app for update to occur. This was asked in Reactiflux Q&A to @geof90 and @lostintangent.

**Comment by senthilsivanath** [comment]
Would take code push to next level. Must have. Eagerly waiting.

**Comment by pniko** [comment]
Closing this issue out for now. It is on our backlog for execution in the future.
