### ISSUE TITLE
Intermittent Rollbacks

### ISSUE THREAD

**Issue by tomauty** [Microsoft/react-native-code-push#420]
Hey all. Posted this in the Q&A, wanted to get some ideas. Below is a chunk of my deployment history (ignore the low adoption. I may have been pushing multiple per day at this time ;))
<img width="218" alt="screen shot 2016-07-07 at 3 07 21 pm" src="https://cloud.githubusercontent.com/assets/1112872/16666226/b3fe6a8a-4454-11e6-9385-0c1198bd6fe9.png">

Both of my codepush calls are using the `sync()` method, so it shouldn't be a consequence of not calling `notifyAppReady()`. These are pretty much consistently sprinkled throughout each release. Any ideas?

**Comment by geof90** [comment]
Hi @tomauty, what version of the plugin are you using? We recently shipped a bug fix https://github.com/Microsoft/react-native-code-push/pull/387 that involves a rollback triggered by restarting the app twice. Since you are calling sync on both app start and another component, perhaps this could be a cause?

**Comment by tomauty** [comment]
I'm on `1.10.3-beta` so...quite a bit behind. Didn't realize. Any risk with updating to latest if I'm on RN 0.24.1?

**Comment by geof90** [comment]
@tomauty We tested backwards compatibility to RN 0.19. I think RN 0.24.1 should be working fine.

**Comment by iniestano8** [comment]
The same as you. I install a new app and there are multi-updated labels(v1,v2), it crashes when i start it. But it is fine when i update from v1 to v2. I use codePush.sync() in method 'componentDidMount' of main js, here is the error log:
`java.lang.RuntimeException: Couldn't call JS module 0, method 0: bridge configuration isn't available. This probably means you're calling a JS module method before bridge setup has completed or without a JS bundle loaded.
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:136)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
	at java.lang.Thread.run(Thread.java:841)`

**Comment by geof90** [comment]
Interesting, I've never seen this error before. Could you clarify what you mean by "multi-updated labels"?

**Comment by silhouettes** [comment]
@tomauty, @iniestano8, are you still seeing your issues?

**Comment by iniestano8** [comment]
@silhouettes it's fine with me, and I have resolved my problem. thanks
