### ISSUE TITLE
CodePush does not support a bundle resource not at the root of the main bundle

### ISSUE THREAD

**Issue by joshuafeldman** [Microsoft/react-native-code-push#427]
On iOS code push currently only supports `bundleURLForResource:withExtension:` which prevents the ability to contain all of the react resources inside of a parent folder at the root of the main bundle. `NSBundle` supports `URLForResource:withExtension:subdirectory:` which would allow us to specify the directory in the bundle the react resources live in and the directory code push should download to. If I have some time I will try and issue a pull request but it would be great to know if there is a plan to add this and if it was added will it be supported and function correctly. Thanks!

**Comment by joshuafeldman** [comment]
Pull request https://github.com/Microsoft/react-native-code-push/pull/428

**Comment by geof90** [comment]
Closed via #428

**Comment by joshuafeldman** [comment]
@geof90 after using it for a while it looks like this doesn't actually work and is causing a rollback on second launch. Looks like some of the other code push classes make assumptions about the directory structure. In `CodePushPackage.m` there is a method called `-getBinaryAssetsPath` which is assuming that `assets` exists at the root of the bundle. I believe this assumption is breaking this. I advise we fix these assumptions (not sure if there are more yet) or rollback the change in your master branch since it will break for people. This ticket should be reopened.

**Comment by joshuafeldman** [comment]
I see this in the console
```
[info][tid:com.facebook.react.JavaScript] [CodePush] Checking for update.
[info][tid:com.facebook.react.JavaScript] [CodePush] An unknown error occurred.
[info][tid:com.facebook.react.JavaScript] [CodePush] g.getCurrentPackage is not a function. (In 'g.getCurrentPackage()', 'g.getCurrentPackage' is undefined)
```
