### ISSUE TITLE
App restarts during payments on Android

### ISSUE THREAD

**Issue by mcrowe** [Microsoft/react-native-code-push#430]
If you are using install mode `ON_NEXT_RESUME`, and there is an update downloaded, then immediately after you complete a payment on Android, the app is restarted in order to install the next version. This does *not* occur on iOS.

This occurs because the Google Play payment dialogs that appear when making a payment cause the app to go into the background, and _resume_ when they close. So, if there is an update pending then CodePush decides that is now the time to restart the app and install the update. Of course, this is probably the _worst_ time to install an update!

Of course, you could just use a different install mode, or manually control the installs. But this makes `ON_NEXT_RESUME` problematic for many apps.

I'm not sure if there is a good way to fix this. Perhaps the best solution is for apps to simply use `disallowRestart` any time payments occur? In any case, it may be worth mentioning this gotcha in the docs.

**Comment by geof90** [comment]
Thanks for the feedback. The fact that React native plugins in general can navigate the app away from and back to the main ReactActivity was a scenario we didnt consider. And I agree maybe the solution is to call this out more explicitly in the docs, or perhaps add some extra console logging if we detect a few known plugins in the project that does this?

**Comment by mcrowe** [comment]
Yeah. That caught me off-guard, too. Especially considering the behaviour is platform specific. Overall, CodePush has been a ridiculously amazing tool to use. Seriously awesome open-source contribution!

 `disallowRestarts` solves the issue for me just fine. To be honest, I didn't think of that solution until I wrote up my issue above.
