### ISSUE TITLE
RN 0.29.1 with rnpm android evaluating '_reactNativeCodePush2.default.sync'

### ISSUE THREAD

**Issue by greenteamer** [Microsoft/react-native-code-push#432]
Hi!
thank you for your help,
the actual question in the title, and I can not run react native 0.29.1 on Android

`undefined is not an object (evaluating '_reactNativeCodePush2.default.sync')`
if i use
`codePush.sync();`

or 
'undefined is not an object (evaluating '_reactNativeCodePush2.default.getCurrentPackage')'
if 
`codePush.getCurrentPackage()`

**Comment by greenteamer** [comment]
MainActivity.java

`package com.startmobile;

import com.facebook.react.ReactActivity;
import com.airbnb.android.react.maps.MapsPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.airbnb.android.react.maps.MapsPackage;
import com.BV.LinearGradient.LinearGradientPackage;
import com.microsoft.codepush.react.CodePush;
import io.realm.react.RealmReactPackage;


public class MainActivity extends ReactActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */

    @Override
    protected String getMainComponentName() {
        return "StartMobile";
    }
}
`

**Comment by greenteamer** [comment]
MainActivity.java

`
package com.startmobile;

import com.facebook.react.ReactActivity;
import com.airbnb.android.react.maps.MapsPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.airbnb.android.react.maps.MapsPackage;
import com.BV.LinearGradient.LinearGradientPackage;
import com.microsoft.codepush.react.CodePush;
import io.realm.react.RealmReactPackage;


public class MainActivity extends ReactActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */

    @Override
    protected String getMainComponentName() {
        return "StartMobile";
    }
}
`

**Comment by geof90** [comment]
@greenteamer Running `rnpm link` from the RNPM CLI will no longer work in 0.29 for android. 

RNPM has been merged into React Native CLI, so you can try running `react-native link` instead. 

If that doesn't work try instead performing the [manual installation steps](https://github.com/Microsoft/react-native-code-push#plugin-installation-android---manual).

Let me know if `react-native link` works for you, and I will update the docs.

**Comment by greenteamer** [comment]
@geof90 actualy react-native link does not work

**Comment by geof90** [comment]
Ah I see, [the fix for `react-native link` will only go out in RN 0.29.2](https://github.com/facebook/react-native/pull/8807).

For now, could you use the manual installation steps?

**Comment by greenteamer** [comment]
@geof90 yes, thank you, i don't use manual correctly in first time, but now everything allright!

**Comment by ps-swaroop** [comment]
Hi,

I am still getting the same issue. Can someone please help?

code-push version : 1.12.1-beta
react-native version : 0.30.0
