### ISSUE TITLE
Install docs leak deployment keys

### ISSUE THREAD

**Issue by jhabdas** [Microsoft/react-native-code-push#437]
https://github.com/search?l=java&q=new+CodePush&ref=searchresults&type=Code

Install docs are encouraging release of deployment keys into the public domain. Am I missing something here? That can't be good.

**Comment by jhabdas** [comment]
Closing to decrease visibility.

**Comment by silhouettes** [comment]
@jhabdas: The deployment key is only as secret as the source code of the app, and it only gives access to the latest version of that source on that deployment. For apps that are publicly released, as React Native uses client-side HTML/JS, it is easy for end users to crack open the app and view the source anyway. As the app would be pulling the latest on that deployment, getting the deployment key doesn't give you any more information than you would have gotten just by running the app and inspecting it after it updates to the latest version. For apps that are not publicly released (in beta testing, for example), the repository/source would not be public, and hence the deployment key would not be visible.

We can certainly change the install docs to encourage loading it from a config file or the like, but my intuition is that it doesn't matter too much. I'm happy to hear your thoughts though - does this make sense to you?

**Comment by jhabdas** [comment]
@silhouettes Native apps have the benefit of security through obscurity. While it may be possible to access the source code of an RN app by snooping, it seems to me it'd be much harder than, say, a web application. But access to the source is not my primary concern, it's the possibility of overwriting someone's app once you know their key. If that's possible, even in a beta stage, I'd strongly suggest updating the docs to warn users and provide a method for abstracting secrets away into an environment variable or config outside the application. What do you think?

**Comment by silhouettes** [comment]
Ah, I see where your concern is. No, a deployment key doesn't give you any kind of ability to write to the deployment, it only gives you the ability to download from it. In some of our early mockups, you'd even email the deployment key to beta testers who you wanted to install your app. In other words, a deployment key is exactly as sensitive as the source is (if you have access to view the source, you already have access to everything the deployment key would give you).

Being able to write to the app requires you to have access to the developer's account on CodePush, which requires either OAuth credentials or a separate 'access key' credential for the CLI that is never used anywhere in our SDK's.

Does that make sense to you?

**Comment by silhouettes** [comment]
I realized my initial comment was kind of confusing/misleading, so I tidied it up a bit! If you still have concerns, please let me know.

**Comment by jhabdas** [comment]
@silhouettes yes, and thanks for helping me get past that concern!
