### ISSUE TITLE
Android and version 0.30

### ISSUE THREAD

**Issue by Sciandra-Leva** [Microsoft/react-native-code-push#438]
I followed the getting started and React-Native guidelines, and also watched the two videos suggested in the description.
With iOS I managed to get the app to download the updates from the codepush releases, but with Android, when using the command

`react-native run-android`

to deploy it on a physical device it still gets the updates directly from localhost.
I am running the newest react-native `0.30` implementation, anyone having the same issue?

My hypothesis is that the second step of the plugin configuration
`
        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
`

isn't working, seems to be ignored.

**Comment by silhouettes** [comment]
Hi @Sciandra-Leva, please check out #153, which might give you more information about this specific problem. Does that help?

As we've gotten this multiple times, I'll leave this issue open to track adding more documentation (and, if feasible, devising some kind of fix or workaround). We are definitely open to ideas here!

**Comment by geof90** [comment]
If you replaced this line in your react.gradle file in node_modules https://github.com/facebook/react-native/blob/master/react.gradle#L90 with `true`, then when you run `react-native run-android`, immediately close the dev server, it should get forced to pick up the version bundled in the binary contents.

**Comment by Sciandra-Leva** [comment]
Hi guys.
I tried @geof90 workaround but it didn't work for me: moreover, I'm not entirely sure why modifying Line 90 should have any effect on forcing the app to get the "codepush staging in remote" version (but I'm 99% sure it's simply because I can't understand properly how it all works).

In the [Deepak Sisodiya](https://www.youtube.com/watch?v=f6I9y7V-Ibk) video a similar workaround for the `iOS Simulator` is to:

1. Modify the `AppDelegate.m` to force the JSCode location to be "remote":
```
jsCodeLocation = [CodePush bundleURL];

//#ifdef DEBUG
////  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
//  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios"fallbackResource:nil];
//#else
//  jsCodeLocation = [CodePush bundleURL];
//#endif
//
```

2. Commenting around lines 18-19 in `node_modules/react-native/packager/react-native-code.sh` the lines:

```
    if [[ "$PLATFORM_NAME" = "iphonesimulator" ]]; then
      echo "Skipping bundling for Simulator platform"
      # I have to comment this in order to make CodePush work in iOS simulator
      # exit 0;
    fi
 ```

(I'm writing it here since. as @silhouettes wrote, we'll use this issue for documentation)

That said, the #153 issue give a good explanation of why this issue happen:

> On Android, React Native forces the JS bundle to be loaded from the packager, and therefore, doesn't consult the CodePush plugin where to get it from.

But still I don't know how to get to my objective, which is to have an Android device running my react-native application "pointing" to my staging deployment instead of localhost. Is [Generating Signed APK](http://facebook.github.io/react-native/docs/signed-apk-android.html#generating-signed-apk) the only way?

**Comment by geof90** [comment]
I have verified that our plugin is working on a RN 0.30 app. ` @Override protected String getJSBundleFile() { return CodePush.getJSBundleFile(); } ` is not ignored.

@Sciandra-Leva, Line 90 of https://github.com/facebook/react-native/blob/master/react.gradle#L90 tells gradle to only create an offline bundle in the app binary only if its a "release" build. Changing it to a hard coded "true" value tells it to always create the offline bundle even in a "debug" build. Therefore, it needs to be done if you want to see it load the local bundle in debug, otherwise there wouldn't even be one.

The second thing you need to do is to close the dev server, the new terminal that pops up, when you do `react-native run-android`. React Native has it hardcoded that in debug, it always first consults the dev server, and only if the dev server is not running, then does it go to the offline bundle.

I will close this issue for now, feel free to reopen if you are still hitting this.

**Comment by deepaksisodiya** [comment]
@Sciandra-Leva 
Hi, In my video I told to change file AppDelegate.m and node_modules/react-native/packager/react-native-code.sh for testing purpose only (only for IOS simulator). after testing you should revert your changes as it was.

Here is the project for i made while making the video. https://github.com/deepaksisodiya/reactnative-codepush/blob/master/package.json

**Comment by deepaksisodiya** [comment]
@Sciandra-Leva 
Hey, For getting data from codepush in android. You need to make a release build and run in device then only it will get data from codepush.

`react-native run-android` make debug build not the release build.
Here is the link for making release build. https://facebook.github.io/react-native/docs/signed-apk-android.html

**Comment by Sciandra-Leva** [comment]
> For getting data from codepush in android. You need to make a release build and run in device then only it will get data from codepush. 

Yes, I understand better know.
Thanks all.
