### ISSUE TITLE
CocoaPods configuration

### ISSUE THREAD

**Issue by nevir** [Microsoft/react-native-code-push#44]
It'd be handy to also package this as a CocoaPods project for even easier setup

**Comment by lostintangent** [comment]
This is definitely something we need to do! Thanks for bringing it up @nevir. We'll likely address this in the next week or so, as we light up a few other enhancements.

**Comment by nevir** [comment]
:+1:

**Comment by lostintangent** [comment]
We're going to evaluate using RNPM for making the setup of our plugin easier for both platforms, since the CocoaPods solution would only help iOS. Reopen this issue if you think CocoaPods support specifically would be valuable. Thanks!
