### ISSUE TITLE
RN 0.30 Support

### ISSUE THREAD

**Issue by DVassilev** [Microsoft/react-native-code-push#444]
What's the current state of support for 0.30? Any critical issues?

**Comment by silhouettes** [comment]
We have tested it and have not found any critical issues. #442 is still being investigated, but it's not clear that it is specifically linked to RN 0.30. We'll do more rigorous checking and update our documentation on Monday (PST).

**Comment by geof90** [comment]
I've tested 0.30 on both iOS and Android and have not found any issues, so I will close this.
