### ISSUE TITLE
Not updating my app 

### ISSUE THREAD

**Issue by KGALLET** [Microsoft/react-native-code-push#452]
Hi everyone, 

I got an App published in the Play Store (version : 1.3) and I didn't manage to push new updates.
Here is my app/build.gradle : 
```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.lacnative"
        minSdkVersion 18
        targetSdkVersion 22
        versionCode 3
        versionName "1.3"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
     signingConfigs {
        release {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        debug {
            buildConfigField "String", "CODEPUSH_KEY", '<my-staging-key>'
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            buildConfigField "String", "CODEPUSH_KEY", '<my-production-key>'
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
``` 
And here in my MainApplication : 

```

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new CodePush("<my-staging-key>", MainApplication.this, BuildConfig.DEBUG)
      );
```

I call the `codePush.sync()` function when my app load.

Here is the steps I'm making to push update.
```
code-push release-react "<my-app-name>" android         
code-push promote "<my-app-name>" Staging Production
```

But I can't see my changes.

Is that the good way to use Code-push? 

Thx

**Comment by geof90** [comment]
Did you add the getJSBundleFile override to your MainApplication? https://github.com/Microsoft/react-native-code-push#plugin-configuration-android

**Comment by KGALLET** [comment]
Yes, I have it in my MainApplication. The setup of the plugin is nice, but I think this is the way I use to update my app that isn't..

**Comment by silhouettes** [comment]
A few things:
1. What do the CodePush logs say when you test it locally if you substitute in the production key? You can use any log viewer or the `code-push debug` command to see them.
2. Just as a sanity check, you've double checked that the deploymentKey is configured correctly in your app?

**Comment by KGALLET** [comment]
I reupload a new binary version of my app on Play Store. Now it seems to be ok. 

Closed. :)

Thx
