### ISSUE TITLE
React Native iOS app not applying update (but says it has)

### ISSUE THREAD

**Issue by greena13** [Microsoft/react-native-code-push#463]
**Steps:**

I added the code to view debugging information in release builds

AppDelegate.m file:

    #import "RCTLog.h"

At the top of your `application:didFinishLaunchingWithOptions` method:

    RCTSetLogThreshold(RCTLogLevelInfo);

- I tail the logs using

    `code-push debug ios`

- I built an iOS staging build (a copy of release with a different deployment key) through Xcode and installed it on the simulator
- I then add a `<Text>` component to the homescreen of my app and I run 

    `code-push react-release <appName> ios`

- I check the release has been received using

   `code-push deployment ls <appName>`

- Now that I know the bundle contains an extra `<Text>` component and that it is on CodePush's servers, I expect the iOS app to *detect* this bundle the next time I open the app, then *apply* it the following time I open it (and the `<Text>` component to appear on the homescreen). So, I open the app on the simulator and I close it again, and then open it and I see the following log output

    [11:07:28] Checking for update.
    [11:07:29] Downloading package.
    [11:07:31] Installing update.
    [11:07:31] Update is installed and will be run on the next app restart.
    [11:07:41] Checking for update.
    [11:07:41] Reporting CodePush update success (v5)
    [11:07:42] App is up to date.

But I *do not see the `<Text>` on my home screen*. I have also tried this with changing background colours of a `<View>` component with the same result - the logs said it applied, but it didn't. 

These same changes were successfully applied on the Android version of the app following a similar procedure.

This also happens for the production build.
This also happens using a physical device.

**Configuration:**

I have followed the installation instructions on the Readme and my MainActivity.java looks like this:

    package com.mypackage;
    
    import android.app.Application;
    
    import com.facebook.react.ReactApplication;
    import com.microsoft.codepush.react.CodePush;
    import com.facebook.react.ReactNativeHost;
    import com.facebook.react.ReactPackage;
    import com.facebook.react.shell.MainReactPackage;
    
    
    import java.util.Arrays;
    import java.util.List;
    
    public class MainApplication extends Application implements ReactApplication {
      private CodePush _codePush;
    
      private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    
        @Override
        protected boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }
    
        @Override
        protected String getJSBundleFile() {
          return _codePush.getJSBundleFile("index.android.bundle");
        }
    
        @Override
        protected List<ReactPackage> getPackages() {
          _codePush = new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG);
    
          return Arrays.<ReactPackage>asList(
              new MainReactPackage(),
              _codePush
          );
        }
      };
    
      @Override
      public ReactNativeHost getReactNativeHost() {
          return mReactNativeHost;
      }
    }

I am using:

code push CLI 1.12.3-beta
code push 1.8.0-beta
react-native-code-push 1.14.1-beta
react-native 0.29.2

**Comment by greena13** [comment]
This ended up being because the version of react-native I was using (0.29.2) failed to complete the steps listed in https://github.com/Microsoft/react-native-code-push#plugin-configuration-ios automatically when I ran the link command. 

I had to perform them manually and I think the issue has now been resolved.

**Comment by silhouettes** [comment]
Thanks for diagnosing this @greena13! We will have `react-native link` working properly for our plugin in our upcoming release today.
