### ISSUE TITLE
[Android] custom ReactInstanceManager

### ISSUE THREAD

**Issue by mtunique** [Microsoft/react-native-code-push#465]
Sometime developers don't inherit `ReactActivity`. When the app(react native app) restart, the activity will recreate.  The experience is very poor.
Maybe we can set the ReactInstanceManager by ourselves.

**Comment by geof90** [comment]
@mtunique Are you linking the plugin via this way: https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#add-native-code?

The main difficulty is your `ReactInstanceManager` would be initialized as such:
```
mReactInstanceManager = ReactInstanceManager.builder()
                ...
                .addPackage(new CodePush(...))
                .build();
```

So, we can't pass in the `mReactInstanceManager` instance to CodePush during construction, perhaps it could be a separate method call?

If you find an elegant way to implement this, feel free to send out a pull request!

**Comment by geof90** [comment]
What if we let you pass in a custom `ReactInstanceManagerHolder` interface, that you would need to implement? The interface would expose a method `ReactInstanceManager getReactInstanceManager() { ... }` to us.

**Comment by mtunique** [comment]
Maybe it is better than a separate method to set the `ReactInstanceManager`.

**Comment by geof90** [comment]
@mtunique I just sent out https://github.com/Microsoft/react-native-code-push/pull/470, which should unblock you, feel free to take a look if you are interested.

**Comment by geof90** [comment]
I published #470 to NPM as v1.14.4-beta so it should work if you pull the latest bits!

**Comment by igrayson** [comment]
We have a related use-case of running our react instance entirely without an activity. I've created a PR, exposing the change we're already using, which happens to take the approach initially discussed here.

https://github.com/Microsoft/react-native-code-push/pull/491

**Comment by mtunique** [comment]
It work in react native 0.29. Thanks.
