### ISSUE TITLE
does it necessary to build two apps to make a difference in different platform?

### ISSUE THREAD

**Issue by iniestano8** [Microsoft/react-native-code-push#466]
Does it necessary to build two apps to make a difference in different platform, because I found the ios app can recieve the update of android ( I use the commond 'code-push release-react <appName> android' ), I'm using the same codePushKey in both of my ios and android app.

**Comment by geof90** [comment]
I guess its possible that the iOS and Android bundles generated by React Native could be similar if your app doesn't contain any platform specific components (e.g. TabBarIOS, ViewPagerAndroid), however we don't recommend it.

**Comment by iniestano8** [comment]
Is it normal that ios app received the update when i push update to android ? (code-push release-react <appname> android)

**Comment by iniestano8** [comment]
@silhouettes could you answer me the question please?  If I push an update to android (use commend 'code-push release-react android'), both iphone and android phone will receive the update tips? but the update content will be shown on iphone after installing.

**Comment by geof90** [comment]
Both will receive it if you used the same deployment key. CodePush doesn't send platform information when you query for updates, so it will just download the update as long as the binary's version is within the targeted range.

**Comment by iniestano8** [comment]
Ok,I see. Thanks.
