### ISSUE TITLE
EXC_BAD_INSTRUCTION error after start RN app

### ISSUE THREAD

**Issue by cbcye** [Microsoft/react-native-code-push#467]
![image](https://cloud.githubusercontent.com/assets/869074/17704820/c5eda278-6408-11e6-814f-e5eb740a7a27.png)
EXC_BAD_INSTRUCTION error after start RN app if i remove the jsCodeLocation = [CodePush bundleURL]; use the local bundle. then it is working.

**Comment by geof90** [comment]
Sorry just to clarify your question. You see the error AFTER you removed the line?

**Comment by cbcye** [comment]
I mean if i use jsCodeLocation = [CodePush bundleURL]; it will occure error ,then remove and use local bundle it is working.

**Comment by geof90** [comment]
It's hard to diagnose this without more information. Could you show us the console logs, or step through the code to see which instruction is failing?

Are you running in the debug or release scheme?

**Comment by cbcye** [comment]
Thank you, Below is the debug output info

2016-08-17 09:18:25.608 [fatal][tid:main] React Native doesn't generate your app's JS bundle by default when deploying to the simulator. If you'd like to test CodePush using the simulator, you can do one of three things depending on your React Native version and/or preferred workflow:

1. Update your AppDelegate.m file to load the JS bundle from the packager instead of from CodePush. You can still test your CodePush update experience using this workflow (debug builds only).

2. Force the JS bundle to be generated in simulator builds by removing the if block that echoes "Skipping bundling for Simulator platform" in the "node_modules/react-native/packager/react-native-xcode.sh" file.

3. Deploy a release build to the simulator, which unlike debug builds, will generate the JS bundle (React Native >=0.22.0 only).
2016-08-17 09:18:25.613 Huola[1736:56887] Loading JS bundle from (null)
2016-08-17 09:18:25.613 Huola[1736:56887] *** Assertion failure in -[RCTBatchedBridge loadSource:](), /work/app/reactnative/Huola/node_modules/react-native/React/Base/RCTBatchedBridge.m:180
2016-08-17 09:18:25.615 Huola[1736:56887] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'bundleURL must be non-nil when not implementing loadSourceForBridge'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001051c2d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001043b7deb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001051c2bea +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x0000000104001e1e -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 169
	4   Huola                               0x0000000103874c8a -[RCTBatchedBridge loadSource:] + 746
	5   Huola  libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by geof90** [comment]
I see. The error message is pretty informative. For example, could you try doing Suggestion number 2 that suggests to remove [lines 17-20 of node_modules/react-native/packager/react-native-xcode.sh](https://github.com/facebook/react-native/blob/master/packager/react-native-xcode.sh#L17), and see if the error still occurs?

**Comment by cbcye** [comment]
Thank you very much, it is working after i remove the following code in node_modules/react-native/packager/react-native-xcode.sh

 # if [[ "$PLATFORM_NAME" = "iphonesimulator" ]]; then
    #   echo "Skipping bundling for Simulator platform"
    #   exit 0;
    # fi

**Comment by cbcye** [comment]
Sorry , after i remove the code the application can start , but load local bundle file , is it correct ?
Loading JS bundle from file:///Users/Gary/Library/Developer/CoreSimulator/Devices/9F01B196-EE1E-4119-96B6-D64CEAD677C7/data/Containers/Bundle/Application/F3171D3C-6347-45BB-B34A-A8EAB260547B/Huola.app/main.jsbundle

**Comment by geof90** [comment]
It will load the bundle file that is compiled into disk during the "Bundle React Native JS Code and Images" build step. You only really want to do this when you are testing CodePush, since removing the line from node_modules/react-native/packager/react-native-xcode.sh causes the build to become slower. Otherwise, during development, I presume you'd prefer to use the dev server. The [iOS configuration section in our README](https://github.com/Microsoft/react-native-code-push#plugin-configuration-ios) explains all of this, and suggests you do something like this:

```objectivec
NSURL *jsCodeLocation;

#ifdef DEBUG
    jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif
```
so that CodePush is only used in release builds.
