### ISSUE TITLE
Option to specify bundle other than mainBundle

### ISSUE THREAD

**Issue by kenwheeler** [Microsoft/react-native-code-push#468]
I'm using CodePush on a RN app that is inside the Walmart iOS app and it lives in its own framework. Is there an out of the box way to do something like this:

```
    NSURL* url = [CodePush bundleURLWithNSBundle:[NSBundle bundleWithIdentifier: kWMReactNativeFrameworkIdentifier]];
```

**Comment by geof90** [comment]
@kenwheeler not right now. I'll try to add support for this ASAP!
