### ISSUE TITLE
Documentation clarification: jsCodeLocation

### ISSUE THREAD

**Issue by ashleydw** [Microsoft/react-native-code-push#47]
I am just starting to get set up, and following the guide in the readme file. I have read: 

> Find the following line of code, which loads your JS Bundle from the packager's dev server:
> 
> jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];

Which I understand fine, however this is the development JS bundle file. Shouldn't the actual replacement with `jsCodeLocation = [CodePush getBundleUrl];` be on the production file (or both)?

I.e. shouldn't that documentation line state that the below line should be replaced:

> jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

OR, on second thought, are you stating that we should leave the secondary `jsCodeLocation` commented out (as per react-native original AppDelegate.m file)? I am updating an existing application with codepush so have this enabled for releases; perhaps this is where my confusion is.

Edit: I see in the example app it is the second `jsCodeLocation` https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/iOS/AppDelegate.m#L48

**Comment by lostintangent** [comment]
You are absolutely right! Thank you for his feedback. I'll send a PR later this morning that clarifies that you should replace the production URL location solution and not the development time URL loading solution.

**Comment by lostintangent** [comment]
The docs have been updated to remove this ambiguity. Let me know if we should change it further. Thanks!
