### ISSUE TITLE
binding errors

### ISSUE THREAD

**Issue by eladgel** [Microsoft/react-native-code-push#473]
We define our root class like this

```
var Root = React.createClass({
....
...
...});
module.exports = CodePush(CodePushOptions)(Root);
```

When running the app we get warning messages because of our bindings in the next two calls

`            syncStatusCallback = rootComponentInstance.codePushStatusDidChange.bind(rootComponentInstance);
            downloadProgressCallback = rootComponentInstance.codePushDownloadDidProgress.bind(rootComponentInstance);
`

When moving on to class definition like so
`class Root extends React.Component`
All of the warnings disappear

Is there a way to avoid these warnings other then forking the repo?
Thanks

**Comment by geof90** [comment]
I see. We'll see if we can get this fixed today.
