### ISSUE TITLE
[CodePush] 400，An update check must include a valid deployment key - please check that your app has been configured correctly. To view available deployment keys, run 'code-push deployment ls <appName> -k'.

### ISSUE THREAD

**Issue by fanyuRN** [Microsoft/react-native-code-push#474]
I have setted codepushdeployment key within my infolist  ,how to solve it?

**Comment by geof90** [comment]
Could you show us your info.plist and mask out the key?

**Comment by fanyuRN** [comment]
sure,
![4cb6b747-3e34-453b-bd06-0c62e16feefc](https://cloud.githubusercontent.com/assets/20810414/17796430/f80df208-65f2-11e6-98e0-171ab6593369.png)

![d959e334-39ce-46cb-98f3-45263442f4bb](https://cloud.githubusercontent.com/assets/20810414/17796420/e9998566-65f2-11e6-978b-c05bd70e8d5b.png)

**Comment by geof90** [comment]
Are you running the debug scheme? From your screenshots CODEPUSH_KEY is not defined in debug.

**Comment by fanyuRN** [comment]
yeah, I don't set the  debug key ,I am running app in the simulator ,

**Comment by geof90** [comment]
Since CODEPUSH_KEY is not defined in debug, the 400 is expected behavior because you are not sending a deployment key from which to get updates from.

**Comment by fanyuRN** [comment]
I have defined CODEPUSH_KEY in debug ,it seem to no effect ;and I use CodePush.sync(); I dont't know Staging and production is how to map app's development environmeng ,is Provisioning Profile? thank you!

**Comment by geof90** [comment]
I assume you followed the [Multi-Deployment Testing](https://github.com/Microsoft/react-native-code-push#ios) section of our docs.

The deployment key is used to query updates with a particular deployment. If you release to Staging, then any app configured with the Staging key will get the update. That section of the docs assumes that you won't want to use CodePush during development/Debug, and you will want to prepare a Staging build for your internal testers, then a Release build for publishing to the app store. So, the staging build should be configured with the Staging key, and the Release build will be conifgured with the Production key. You would then make CodePush releases to Staging first, so that once testers have signed off, you can promote the release to Production so that production users can see it.

To do a Staging/Release build, you can click on your target > Edit Scheme and change the run configuration to Staging/Release.

![image](https://cloud.githubusercontent.com/assets/8598682/17877161/c32245b2-6895-11e6-96c0-6258f24acf81.png)

**Comment by zaach** [comment]
I'm running into this problem as well. I hardcoded `CodePushDeploymentKey` to one of my deployment keys just to be sure, but it's still giving this error. Any other ways to debug it? Probably unrelated but `code-push debug ios` doesn't output anything.

**Comment by geof90** [comment]
`code-push debug ios` might not output anything if your app is running in a release build. Could you try running it in debug mode, and if `code-push debug ios` still doesn't work, try running it from xcode to see the debug logs?

**Comment by zaach** [comment]
I didn't see any output for the debug build unless I use `jsCodeLocation = [CodePush bundleURL];`, which results in this being logged: `[03:38:56] Loading JS bundle from (null)`, and the app not launching.

**Comment by fanyuRN** [comment]
thank you ,I hava got it

**Comment by RomanVanso** [comment]
I have the same problem. What ever I do, nothing helps. I have also set multi-deployment but still getting this error. Can anyone help please?
react-native 0.47.2,
react-native-cli 2.0.1

**Comment by PizzaLiu** [comment]
What I have found is that if you just add the [Multi-Deployment Testing](https://github.com/Microsoft/react-native-code-push#ios) , you'd better clean the project and rebuild it in Xcode (`Project / Clean`). Hope this help guys!

**Comment by rob-keepsafe** [comment]
We ran into this situation as well. It'd be nice if you all logged the error or rethrow it instead of swallowing it.

For now, you can dump it by modifying `react-native-code-push/CodePush.js` to add:

```js
log(`Error is ` + e);
// above this line
log(`Report status failed: ${JSON.stringify(statusReport)}`);
```

**Comment by saravanannnallasamy** [comment]
I am having the same issue,
previously i have used `react-native 0.34`
i have changed the version to 0.40 and run `npm install`
the app is build successfully, but in the login page `native-base` input component is not visible.
In the background i have above issue

> [CodePush] 400，An update check must include a valid deployment key - please check that your app has been configured correctly. To view available deployment keys, run 'code-push deployment ls <appName> -k

  i have clean and rebuild the project but it is not working.

**Comment by rob-keepsafe** [comment]
Also, this relates to https://github.com/Microsoft/code-push/issues/290#issuecomment-236392414

>To ensure compatibility between the native binary interface and the dynamically updated JS, CodePush versions your binary code using the App Store version of your app. We expect this version to follow semver (e.g. 1.0.0), so it's likely that you just need to change it to conform to the format.

**Comment by mattcolman** [comment]
Hi, I'm experiencing this issue after updating packages from:
`"react-native": "0.42.3",
    "react-native-code-push": "1.17.4-beta",`
to
`
"react-native": "^0.56.0",
    "react-native-code-push": "^5.4.1",
`
I followed the "Multi-Deployment Testing" link so I have no defined a deployment key for DEBUG.
I also have this code to read the jsCodeLocation from the local bundle and not codepush.
`#ifdef DEBUG
    jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif`

So why is codepush still trying to do an update??

The error again is:
`400: An update check must include a valid deployment key - please check that your app has been configured correctly.`
