### ISSUE TITLE
版本号不合规则

### ISSUE THREAD

**Issue by zhuchuanwu** [Microsoft/react-native-code-push#475]
我发版的时候版本号用了2.00.7，现在发现无法使用codepush，有办法解决吗

**Comment by geof90** [comment]
抱歉，暂时唯一的办法是再发新的版本号到 app store 把版本号改成 2.0.7 (遵守 semver 的版本号)，发了过后就可以应用 CodePush。

**Comment by geof90** [comment]
我们暂时无法在后端允许不守semver 的版本号 (如 `2.00.7`)。唯一方法是把版本号改成守semver(如 `2.0.7`)，或应用[`overrideAppVersion()`](https://github.com/Microsoft/react-native-code-push#methods-2)，然后把新版本发布到app store，以后就可以用CodePush 更新那个新的版本。
