### ISSUE TITLE
App can't load pushed update.

### ISSUE THREAD

**Issue by ps-swaroop** [Microsoft/react-native-code-push#481]
Hey,

I am trying to use react native and code push to populate a screen in my existing app. My app can detect an update, fetch the update but could not load the updated bundle.

Logs while trying to update:

```
Loading JS bundle from "/data/user/0/com.tute.codepushdemo/files/CodePush/751e34384d3a9b72bab7093cb6ae784370f081060d2cc5d4fb6664f69f4ce2b5/CodePush/index.android.bundle".
Restarting app. 
Update did not finish loading the last time, rolling back to a previous version.
```

Unfortunately same code works like a charm if I create a new project using "react-native init <project-name>"

Can someone please help me.

**Comment by ps-swaroop** [comment]
I was not configuring well. Issue is fixed

**Comment by mobohua** [comment]
i had same issue,can you tell me hot to fix it?
