### ISSUE TITLE
Add notifications for JS bundle operations

### ISSUE THREAD

**Issue by daniel-beard** [microsoft/react-native-code-push#489]
- Would be nice to listen for notifications for JS bundle operations such as:
  - Bundle downloaded succesfully
  - Bundle failed to download
  - Bundle was applied successfully
  - Bundle failed to apply
  - etc.

**Comment by piyushjo** [comment]
Have you tried the debug command described here - https://microsoft.github.io/code-push/docs/cli.html#link-5. Would this work?

**Comment by daniel-beard** [comment]
Sorry, I should have been more clear, I'd like to see this from the iOS / Android SDKs and available in Release builds.

**Comment by daniel-beard** [comment]
Following up here, I would ideally like a native (Objective-C) approach to listening to successful / failed updates. My vision for this would be NSNotification based. Would the team be open to an approach like this? I don't mind implementing this.

**Comment by panarasi** [comment]
@daniel-beard We are looking at moving all the download logic to native land to serve this use case. cc @sergey-akhalkov - If we have this issue capture else where, can you add it here ?

**Comment by sergey-akhalkov** [comment]
@panarasi, got it, will do.
