### ISSUE TITLE
Any setup suggestions on how to use staging and production environments for Android Play store's open beta and prod releases

### ISSUE THREAD

**Issue by prithsharma** [Microsoft/react-native-code-push#494]
The mechanism suggested in the documentation can ensure that my debug builds use staging deployment key and release build use production key. But as far as I can understand(please correct me if I am wrong in this understanding), the debug builds would need the packager running and thus can't be shared to potential testers. 
The purpose is for users in the app's beta program on Play Store to get pre-production updates from staging and other users get updates from production. But since the same release build is promoted to prod from open beta in Play Store, they would both ideally have the production deployment key.

The reason _Dynamic Deployment Assignment_ wouldn't work is because I can't get a handle to which user has joined the app's beta program on Play Store. Or do I?

**Comment by prithsharma** [comment]
One method I can think of is to target releases with versions(which I can adjust according to my knowledge of the version in Play Store's open beta and prod) in addition to environments.
But it would be really elegant if I could leverage the environments for this.
The reason _Dynamic Deployment Assignment_ wouldn't work is because I can't get a handle to which user has joined the app's beta program on Play Store. Or do I?

**Comment by prithsharma** [comment]
Sorry for posting this as an issue, I'll better ask on StackOverflow.

**Comment by prithsharma** [comment]
Couldn't get an answer on SO still, reopening the issue.

**Comment by goldylucks** [comment]
@prithsharma I'm facing the same problem
>One method I can think of is to target releases with versions(which I can adjust according to my knowledge of the version in Play Store's open beta and prod) in addition to environments.

can u describe your current flow for achieving this?

**Comment by prithsharma** [comment]
I don't think I found a neat solution to this problem.

But this is what I am following right now -
1. My debug builds(both in Android and iOS) are subscribed to CodePush's staging releases.
1. For testing whether a CodePush release would work as expected, I make the staging release and test it in the debug build(mostly in a simulator in my case). 
1. After this, I promote the release to production.

Ideally, after the second step, I should be able to make the release to a smaller set of users(QA or beta testers etc.) before promoting it to production in the third step.
Something like that could be achieved by checking the app version in your JS and deciding which deployment name to check updates from on the basis of the app version. That would require maintaining a map of the version numbers to deployment names somewhere on the web server so it can be served via an API to the app.
I haven't done something like this yet since it would get too coupled with the web server(where I would maintain the mapping I talked about).

**Comment by sergey-akhalkov** [comment]
@prithsharma, could you please look at https://github.com/Microsoft/react-native-code-push#android?
I've updated the documentation so for now there is an additional buildType - `releaseStaging`, so you could store your staging deployment key there. `releaseStaging` buildType works exactly like `release` buildType and it uses offline js bundle instead of packager.
The same for iOS - https://github.com/Microsoft/react-native-code-push#ios. You could create Staging configuration and store staging deployment key there. 
Please let me know it helps or if you have any questions.

**Comment by valetarton** [comment]
^^ @sergey-akhalkov found the solution in the recently updated documentation for Android worked like a charm.

Now just having issues with iOS app downloading update. But that's not your problem :)

**Comment by sergey-akhalkov** [comment]
@valetarton, please feel free to create new issue if you need any help.

**Comment by sergey-akhalkov** [comment]
@prithsharma, just a friendly ping, please let me know if docs update helps or if you have any questions.

**Comment by sergey-akhalkov** [comment]
Closing this, please feel free to reopen if needed.

**Comment by prithsharma** [comment]
@sergey-akhalkov really sorry for the late reply. 
My [comment above](https://github.com/Microsoft/react-native-code-push/issues/494#issuecomment-273820526) suggests the same thing as the update in the docs(correct me if I am wrong). 

While I had figured it out for Android, I still have to do it for iOS - the iOS staging env docs will be helpful. Thank you.
