### ISSUE TITLE
400: An update check must include a binary version that conforms to the semver standard (e.g. '1.0.0'). 

### ISSUE THREAD

**Issue by huiyangs** [Microsoft/react-native-code-push#502]
Hi guys,

We found the issue as following while react-native-code-push checked update.

08-31 17:05:45.543 I/ReactNativeJS: ----- codepush sync!
08-31 17:05:45.546 I/ReactNativeJS: [CodePush] Checking for update.
08-31 17:05:45.957 I/ReactNativeJS: [CodePush] An unknown error occurred.
08-31 17:05:45.957 I/ReactNativeJS: [CodePush] 400: An update check must include a binary version that conforms to the semver standard (e.g. '1.0.0'). The binary version is normally inferred from the App Store/Play Store version configured with your app.

Since we are going to integrate ReactNative to a published Android product, we cannot change our version name pattern (something like 1.2.3.456, longer than 1.0.0). Is there any workaround for this issue? Is there any interface for Android client to customize the app version which code-push could use while it is goint to check for update?

Thanks

**Comment by geof90** [comment]
Hi @huiyangs, yes indeed there is a workaround via the `overrideAppVersion` method of the Java API.
https://github.com/Microsoft/react-native-code-push#static-methods

**Comment by huiyangs** [comment]
Great, thanks!

**Comment by oussaki** [comment]
@geof90  i tried using overrideAppVersion and still getting the same error.

**Comment by kinanahirani** [comment]
@geof90 Thanks. It worked. You can use `overrideAppVersion `method in both android and iOS as mentioned below.

**For Android:**
Define this method in MainApplication.java where you are doing setup for react-native-code-push: 

```
protected String getJSBundleFile() {
    CodePush.overrideAppVersion("1.0.0")  //App version which you want to choose for code push
    return CodePush.getJSBundleFile();
}
```

**For iOS:** 
Add this line in AppDelegate.mm file.

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    // Override the CodePush version before setting up the bridge
    [CodePush overrideAppVersion:@"1.0.0"];
    // ... the rest of your code ...
}
```
And when you push the code into appcenter, make sure to define the version at the end of the command like : <command> --target-binary-version "1.0.0"

**Comment by tahahaz1374** [comment]
In my case, I currently have '2.07' as the version for my iOS app, which seems to be causing this error. Would it be advisable to switch to the standard semantic versioning format, such as '2.7'.
