### ISSUE TITLE
Unable to use CodePush with rnpm link

### ISSUE THREAD

**Issue by chadwilken** [Microsoft/react-native-code-push#503]
We previously were using CodePush with CocoaPods but I wanted to have everything run through `rnpm` for the ease of use. When I attempted to use `rnpm` to set up CodePush it would set everything up or confirm that it was correctly set up. It always gave me issues like in the photo below. I totally wiped out everything related to CodePush in the cocoapods, I also deleted the pods project, node_modules, cleared all caches etc and it still did this. It would always throw an error about `#import "CodePush.h"` saying that it couldn't be found. I was able to verify the _CodePush.xcodeproj_ located in the _Libraries_ directory.

Using rnpm 1.9.0
react-native-code-push 1.14.5-beta

![Screenshot](https://dl.dropboxusercontent.com/u/13238118/Screen%20Shot%202016-08-31%20at%204.44.52%20PM.png)

**Comment by geof90** [comment]
Just to clarify, are you using `rnpm` or `react-native link`? The former seems to be no longer maintained.

**Comment by chadwilken** [comment]
I'm using rnpm

**Comment by geof90** [comment]
If you go to the Pods project from XCode, and expand the Headers folder, do you see those file references there? It looks like there are dangling file references that need to be removed.

**Comment by chadwilken** [comment]
No there aren't any. I also completely deleted the pods folder and
reinstalled

**Comment by chadwilken** [comment]
I ended up just using CocoaPods to handle the install because it was holding up my development.

**Comment by panarasi** [comment]
This is likely to be fixed, since there have been a lot of changes in the header. Closing this issue. If you still have a bug, please reopen this and we can look at this.
