### ISSUE TITLE
Can't build from command line

### ISSUE THREAD

**Issue by bsiddiqui** [Microsoft/react-native-code-push#505]
If I build from the command line `react-native run-ios --scheme "AppStaging"` I get a `undefined is not an object (evaluating '_reactNativeCodePush2.default.CheckFrequency')`

It works fine if I select the scheme from xcode and build

**Comment by geof90** [comment]
I am unable to reproduce this. Could you provide more information? How did you create the AppStaging scheme, did you duplicate an existing one?

**Comment by bsiddiqui** [comment]
@geof90 I figured it out - I had to clear watchman
