### ISSUE TITLE
Error restart app: Didn't expect to set up twice

### ISSUE THREAD

**Issue by jerson** [Microsoft/react-native-code-push#509]
Im using *restartApp* method and sometimes crash

```javascript
codePush.restartApp(false);
```
im using this versions

```json
    "react-native-code-push": "^1.14.6-beta",
    "react": "^15.3.1",
    "react-native": "^0.32.0",
```

```
2016-09-02 10:50:42.318788 Setbeat[3744:1193576] *** Assertion failure in __23-[RCTJSCExecutor setUp]_block_invoke(), /Users/gerson/Setbeat/node_modules/react-native/React/Executors/RCTJSCExecutor.mm:419
2016-09-02 10:50:42.335309 Setbeat[3744:1193576] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Didn't expect to set up twice'
*** First throw call stack:
(0x1922c01c0 0x190cf855c 0x1922c0094 0x192d49898 0x100382658 0x10038760c 0x192da56ec 0x19226e278 0x19226dbc0 0x19226b7c0 0x19219a048 0x10037fb24 0x192da550c 0x191353860 0x191353770 0x191350dbc)
libc++abi.dylib: terminating with uncaught exception of type NSException
warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available.

```

```
#0	0x000000019128e014 in __pthread_kill ()
#1	0x0000000191355460 in pthread_kill ()
#2	0x00000001912023f4 in abort ()
#3	0x0000000190ccd2d4 in abort_message ()
#4	0x0000000190ceacc0 in default_terminate_handler() ()
#5	0x0000000190cf8844 in _objc_terminate() ()
#6	0x0000000190ce766c in std::__terminate(void (*)()) ()
#7	0x0000000190ce7234 in __cxa_rethrow ()
#8	0x0000000190cf871c in objc_exception_rethrow ()
#9	0x000000019219a0bc in CFRunLoopRunSpecific ()
#10	0x000000010037fb24 in ::+[RCTJSCExecutor runRunLoopThread]() at /Users/gerson/Setbeat/node_modules/react-native/React/Executors/RCTJSCExecutor.mm:280
#11	0x0000000192da550c in __NSThread__start__ ()
#12	0x0000000191353860 in _pthread_body ()
#13	0x0000000191353770 in _pthread_start ()
#14	0x0000000191350dbc in thread_start ()

```

**Comment by geof90** [comment]
Hi @jerson Can you provide more information about when you are calling `restartApp`? Is it after the `sync` promise resolves?

**Comment by jerson** [comment]
@geof90  I'm playing music in the background and updating the time of the song, maybe these actions are likely to generate the error.

**Comment by jerson** [comment]
but if it worked well before with the previous version

```json
    "react-native-code-push": "^1.13.5-beta",
    "react-native": "^0.30.0",
```

**Comment by geof90** [comment]
Are you using a plugin to play the music? `react-native-music-control` or `react-native-audioplayer`? I am trying to set up a repro.

**Comment by jerson** [comment]
No, I've created my own native module react, but it is a bit similar to this https://github.com/tlenclos/react-native-audio-streaming

**Comment by geof90** [comment]
Hi @jerson, our `restartApp()` logic did not change over the two versions you mentioned, this crash you are seeing is a result of [this change](https://github.com/facebook/react-native/commit/1ebd9c5deaa453a56e73f4fc34165f08de18bd79#diff-24171be54ca5e6987e6e9b2f870fe8a3R316). We need more time to dig into the internals about what we/the audio player is doing such that the jscWrapper is dereferenced but the jsContext isn't. However, as a workaround, could you try stopping the music player before calling `restartApp()` and see if the problem persists?

**Comment by jerson** [comment]
@geof90  The problem was related to Realm instance but now is fixed :) , closed 👍

**Comment by jaisonveneri** [comment]
I'd like to know too. You could share @jerson.

**Comment by jerson** [comment]
check this repo, was an old error but now is solved

https://github.com/jerson/realm-example-error

**Comment by jaisonveneri** [comment]
Thanks @jerson
