### ISSUE TITLE
Improve download speeds in China

### ISSUE THREAD

**Issue by sopaco** [Microsoft/react-native-code-push#514]
I have found sometimes this code would block all `await` operations,why?
```js
import codePush from "react-native-code-push";
let CodePushOptions = {
    checkFrequency: codePush.CheckFrequency.ON_APP_START,
    installMode: codePush.InstallMode.ON_NEXT_RESUME
}
let CodePushWrapOnMainGuiPage = codePush(CodePushOptions)(MainGuiPage);
module.exports = CodePushWrapOnMainGuiPage
```

**Comment by silhouettes** [comment]
Hi @sopaco, I'm not sure I follow - so you're saying every asynchronous operation in your app is blocked by CodePush? I'm not sure that makes sense to me - how did you verify that CodePush is the cause of this?

**Comment by sopaco** [comment]
@silhouettes because when i remove these code, it works :}

**Comment by geof90** [comment]
@sopaco I can't reproduce this problem. Can you show us where are you making the await operations? I tested those on `async componentDidMount()` and did not see any failures.





```javascript
function alertAfterTimeout() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      Alert.alert("Boo!");
      resolve("resolved");
    }, 5000);
  });
}

class CodePushDemoApp extends Component {
  async componentDidMount() {
    var str = await alertAfterTimeout();
    Alert.alert(str);
  }
  ...
}

CodePushDemoApp = CodePush({
  checkFrequency: CodePush.CheckFrequency.ON_APP_START,
  installMode: CodePush.InstallMode.ON_NEXT_RESUME
})(CodePushDemoApp);
```

**Comment by silhouettes** [comment]
Hi @sopaco, did you still want to follow up on this issue?

**Comment by sopaco** [comment]
Consider if network is too slowly, the long times cost operation of `await xxx` will block other await operation?

**Comment by silhouettes** [comment]
Are you blocked on other network calls while an update is downloading? That could be a possible explanation. (I doubt an update check would use much network at all, so it would purely be the cost of downloading the update when there is one).

How long are your operations blocked for, and does that time period correspond to any CodePush activity? Can you show us where you are making the await operations?

**Comment by sopaco** [comment]
@silhouettes it seems cost much time to download the update file(more than 1 minute), and in this duration any other await operation was blocked. Does all these await operation run on a single thread in react-native?

**Comment by silhouettes** [comment]
@sopaco - The download should happen asynchronously, so that other activities are not blocked, however it may be competing for network resources.

How big is your update, and how fast is your connection? I am also assuming that you're located in China - we will be rolling out a CDN with our next update which will improve the download speed.

**Comment by sopaco** [comment]
@silhouettes Right! In China our update file is almost about 3MB, duration the code-push-upgrading, any other operations based `await fetch` was blocked. Looking forward to the CDN you mentioned.
