### ISSUE TITLE
iOS 7 - Code push reports status 0 and crashes

### ISSUE THREAD

**Issue by joshuafeldman** [Microsoft/react-native-code-push#518]
I think this crash might be related to some other tickets but I decided to start a new thread in case I am wrong.

Basically we are seeing a crash intermittently. Reproducing it has been difficult but the last item in our log before the crash is 
`2016-09-16 11:48:21.953 [info][tid:com.facebook.react.JavaScript] [CodePush] App is up to date.
2016-09-16 11:48:21.956 [info][tid:com.facebook.react.JavaScript] CODEPUSH STATUS: 0`

[Crash.txt](https://github.com/Microsoft/react-native-code-push/files/477607/Crash.txt)

**Comment by silhouettes** [comment]
What version of RN/CodePush is running in your app? We will try to look at this over the next two days, although it may be difficult.

**Comment by silhouettes** [comment]
@joshuafeldman just a friendly ping!

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen it if needed!
