### ISSUE TITLE
iOS ipa size increases a lot after using this library

### ISSUE THREAD

**Issue by inetfuture** [Microsoft/react-native-code-push#519]
Jump from 8.3M to 33.9M.

Although I'm not sure if it is related to this library, but it happens right after the integrating, so I think I might ask here for any potential tips, is there any?

react-native version is 0.29, react-native-code-push version is 1.14.6-beta

Thanks.

**Comment by hilkeheremans** [comment]
Seems we are having this as well.

**Comment by frantic** [comment]
I think I found the issue – the npm module published contains Android build artifacts[1]. @silhouettes could you please check the `.npmignore` file and make sure it matches `.gitignore`?

1. To repro, `npm install react-native-code-push` and check out `node_modules/react-native-code-push/android/app/build`. The folder is > 30MB in size.

**Comment by vladimir-kotikov** [comment]
@frantic, I confirm that the issue with released packages exists, but does it really affects the size of iOS archives? I just checked and in my case archive size with code-push installed is 6Mb vs. 5.3 Mb without it.

**Comment by frantic** [comment]
@vladimir-kotikov you are right, just checked on a different project and it doesn't seem to affect the IPA size.

**Comment by sergey-akhalkov** [comment]
Seems to be fixed by #652, please feel free to reopen it if needed.
