### ISSUE TITLE
Failure in :app:recordFilesBeforeBundleCommandDebug when linking with Android

### ISSUE THREAD

**Issue by chetstone** [Microsoft/react-native-code-push#523]
I'm trying to get my iOS app (which works fine with codepush) running on Android.
I was able to get Android built and running successfully but the debugger had a message something like: `CodePush is not installed properly`

Oops, I hadn't linked it. Following the manual linking steps in the README, the build now fails with:

```
:app:recordFilesBeforeBundleCommandDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:recordFilesBeforeBundleCommandDebug'.
> A problem occurred starting process 'command 'node''
```

I decided to undo that and try `react-native link react-native-code-push`. The build then failed with:

```
Build file '/Users/chet/prj/malas/firebase/android/app/build.gradle' line: 145

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':react-native-code-push' could not be found in project ':app'.
```

It seems the automatic link didn't make the required changes in `settings.gradle`.
Adding those back in from the manual link instructions, I'm back at the same `:app:recordFilesBeforeBundleCommandDebug FAILED` error.

Any suggestions?

thanks

UPDATE: I'm using react-native 0.32.1 and react-native-code-push 1.14.6-beta

**Comment by geof90** [comment]
Does the recordFilesBeforeBundleCommand script fail with an exception? It would help us to diagnoSe the issue.

**Comment by chetstone** [comment]
Thanks for the response. It seems to be working now. I temporarily took out all the code-push stuff and was working on other things which involved changing the android build, trying to straighten out the name of the app, etc. Probably something I changed there (which involved a couple `clean` builds) fixed this.

Now to test to see if code-push actually works. I have a question after reading your notes on [multi-deployment testing](https://github.com/Microsoft/react-native-code-push#multi-deployment-testing). Those notes seem to focus on changing the deployment key. But the default build of Android seems to always use the packager server to download the bundle, so you wouldn't be able to use code-push because the installed bundle isn't being used. It seems you need three configurations: 

1. Development, uses packager
2. Staging, builds an APK with staging deployment key
3. Release, builds APK with release deployment key.

Or is there a clever way to use the same `debug` build for 1 and 2?

**Comment by panarasi** [comment]
@sergey-akhalkov Related to https://github.com/Microsoft/react-native-code-push/issues/614 ? 

If it is related, lets close this issue since we are working on the other issue.

**Comment by sergey-akhalkov** [comment]
Closing this, due to #614
