### ISSUE TITLE
Cannot upload release bundle, "502 - Web server received an invalid response while acting as a gateway or proxy server."

### ISSUE THREAD

**Issue by Ranatchai** [Microsoft/react-native-code-push#528]
![screen shot 2559-09-25 at 10 03 06 pm](https://cloud.githubusercontent.com/assets/5508501/18816091/130af7f4-836c-11e6-9d76-20e7902c99c9.jpg)
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version: 1.14.6-beta
* react-native version: 0.32.0
* iOS/Android version: iOS10
* bundle size after zip: 25 MB
* Repro steps:

1. run `code-push release-react [appName] ios -d Production`
2. finish bundle and start upload
3. stuck at 9% (sometime at 10%)

**Comment by silhouettes** [comment]
Thanks for filing this! As this is an issue on the CodePush CLI, I've moved this to https://github.com/Microsoft/code-push/issues/326 and will follow up there.
