### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by JAStanton** [Microsoft/react-native-code-push#53]
I'm trying to hit updateCheck when I've switched to using XHR in chrome rather than the fetch polyfill (https://github.com/facebook/react-native/blob/478a712d20fc03c6bea03ba888c7a4f93e01fd5f/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js#L51)

and I hit this CORS issue:

```
XMLHttpRequest cannot load https://codepush.azurewebsites.net/updateCheck?deploymentKey=REDACTED&appVersion=1.0.1&packageHash=&isCompanion=. Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://codepush-ui.azurewebsites.net' that is not equal to the supplied origin. Origin 'http://localhost:8081' is therefore not allowed access.
```

**Comment by lostintangent** [comment]
That's a great catch, we can add the right heads in the response to accommodate this scenario. We hadn't tested this workflow with replacing fetch and running the network calls in Chrome itself :)

**Comment by lostintangent** [comment]
We're going to look into this, but in the meantime, would this workaround help you to be unblocked? http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by lostintangent** [comment]
I'm going to close this issue based on the Chrome workaround of disabling CORS during your debugging session. Please re-open it if this isn't a good solution for you and we would be more than happy to discuss how to unblock you. Thanks!

**Comment by silhouettes** [comment]
So we just discussed this and we probably shouldn't have CORS turned on at all. Having CORS turned on in the server is a legacy thing that should have been removed a long time ago. Re-opening this so that we can track its removal!

**Comment by lostintangent** [comment]
I'm going to close this and we'll track it as a server bug. Let us know if there is another fix that we should investigate to satisfy this scenario. Thanks!
