### ISSUE TITLE
InstallMode.ON_NEXT_RESUME triggering infinite loop - trying to recreate activity

### ISSUE THREAD

**Issue by stewart42** [Microsoft/react-native-code-push#540]
* react-native-code-push version: 1.14.6-beta
* react-native version: 0.34
* iOS/Android version: Android 7.0
* Does this reproduce on a simulator, or only on a physical device? physical device (Nexus 5x)
* Repro steps and/or stack trace:

```
const codePushOptions = {
    checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
    installMode: codePush.InstallMode.ON_NEXT_RESUME,
    mandatoryInstallMode: codePush.InstallMode.IMMEDIATE,
};
 ```

- upload a new bundle to code-push servers
- pause the activity 
- resume the activity
- codepush downloads new bundle
- pause the activity
- resume the activity and then below happens

  1. The exception `java.lang.NoSuchMethodException: createFileLoader [class android.content.Context, class java.lang.String]` occurs at [L116](https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L116)
  2. then an exception `java.lang.NoSuchFieldException: No field mJSBundleFile in class Lcom/facebook/react/XReactInstanceManagerImpl; (declaration of 'com.facebook.react.XReactInstanceManagerImpl' appears in /data/app/com.xxxxxxxx.android.debug-1/base.apk)` is raised at [L122] (https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L122)
  3. the outer catch then triggers `loadBundleLegacy()` which attempts to recreate the activity
  4. once the activity is recreated the onHostResume event fires [L434](https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L434) and `loadBundle` is called looping back to the first excpetion above

We are imbedding this in an existing app that does have `multiDexEnabled` set to `true`, not sure if this is relevant?

Any ideas what I am doing wrong?

**Comment by silhouettes** [comment]
Thanks so much for your detailed investigation of this! As I'm fairly sure this is an issue related to RN 0.34 support, I'm going to close this so that we can use #536 to track it.
