### ISSUE TITLE
Release-react for the same app on iOS and Android?

### ISSUE THREAD

**Issue by afilp** [Microsoft/react-native-code-push#542]
I cannot update an app that is created for both iOS and Android, and using the *same* Deployment Key for the production.

Is this a mistake? Should we have 2 different applications? Like: myApp-iOS and myApp-Android, with 2 different Deployment Keys? And then run **release-react** twice? (even though the changes are simple changes on the JavaScript?

Thank you, please let us know, this is not well clarified on the README.

**Comment by silhouettes** [comment]
Yes - the recommendation is to use separate CodePush apps. Apologies for the confusion! We will clarify it in the README, and we also have future plans to improve the way we handle different platforms of the same app.

I'm going to close this for now, but please let me know if you have any other questions!

**Comment by afilp** [comment]
@silhouettes Thank you for your prompt reply!

So, now that I did a *react-release* for iOS do I cause "harm" to the Android app? They use the same Deployment Key, so it will get the "iOS-related" JS code?! Should I hurry up and change this ASAP? Thanks!

**Comment by silhouettes** [comment]
Hi @afilp - in this specific case, the CodePush SDK is smart enough to detect that the structure of the update does not match what is expected for the platform, and reject the update without disturbing the user (assuming silent mode).

Sorry for any concern this may have caused you! In future, we recommend creating a Staging version of your app pointing to your Staging deployment, and validating CodePush updates there first before running `code-push promote` to promote them to your Release deployment. As a last resort, we also have an automatic rollback feature that can sometimes save you if you push a bad update. Remember, with great power comes great responsibility!

**Comment by afilp** [comment]
Ok, thanks! Keep up the **very** good work and support.
