### ISSUE TITLE
Deploying Error

### ISSUE THREAD

**Issue by scerelli** [Microsoft/react-native-code-push#555]
I just installed `react-native-code-push`i linked everything using rnpm, everything it's fine inside the Android/iOS projects but if i type  

`code-push release-react "appName-android" android`

I get this error:
```
[Error]  Unable to find or read "package.json" in the CWD. The "release-react" command must be executed in a React Native project folder.
```

even if i'm inside the project folder that is structured like this:

- Project
 - android
 - App
 - Tests
 - index.ios.js
 - index.android.js
 - package.json

**Comment by silhouettes** [comment]
Hi @scerelli, is `react-native` a dependency in your `package.json`?

**Comment by scerelli** [comment]
No, moving it to dependencies fix the problem. 
Usually, I put all dependencies into `dev-dependencies` because none are required for production since `react-native` will bundle what it's needed from imports.

**Comment by silhouettes** [comment]
Ah - that's a great point! I've filed this request on the `code-push` repo (https://github.com/Microsoft/code-push/issues/331) so that we can follow up on this at some point. As you seem to have resolved it with a workaround, I'm going to close this one for now. Thanks for filing this!
