### ISSUE TITLE
Improve resilience to breaking RN changes

### ISSUE THREAD

**Issue by silhouettes** [Microsoft/react-native-code-push#556]
- react-native-code-push version: <= 1.15.*
- react-native version: <= 0.34.*

CodePush uses reflection to find the `ReactInstanceManager` and then to find the right fields on it to set the location of the JSBundle to load. This is somewhat brittle to breaking changes in React Native (see #536) and requires custom legacy code to support multiple RN versions.

We could consider submitting a PR to react-native to encapsulate this logic and expose a public interface, such that we can detect breaking changes at compilation time, and such that it will be updated within RN itself whenever a breaking change happens.

**Comment by silhouettes** [comment]
Note that we can't resolve these fields statically unless we pin our minimum dependency version of `react-native` on the version where the public interface is introduced. As this would be a breaking change (older versions would then no longer be supported), we could potentially continue using reflection as a stop-gap for a few versions before pinning the minimum version.

Another option is to simply leave a comment in the RN codebase that will dissuade changes, or encourage them to tag us in the relevant PR's.

**Comment by panarasi** [comment]
Closing this issue, issue moved to service repo.

**Comment by fadookie** [comment]
@panarasi Where is the service repo? We are using a similar hack for doing runtime bundle loading and would be interested in following an issue/PR if one exists, and potentially making one if it doesn't yet.
