### ISSUE TITLE
rootProject.name overrides application's own name

### ISSUE THREAD

**Issue by zvona** [Microsoft/react-native-code-push#558]
`rootProject.name = 'ReactNativeCodePush'` overrides the application's own name in `settings.gradle` and sets it as _ReactNativeCodePush_ for Android. This probably isn't intentional. Is there a way to fix it or should this line be removed: https://github.com/Microsoft/react-native-code-push/blob/master/android/settings.gradle#L1

**Comment by silhouettes** [comment]
Hi @zvona, thanks so much for filing this and apologies for the slow response! That line has been removed and this has been merged into master.

**Comment by silhouettes** [comment]
(This was released in `1.15.1-beta` ([release notes](https://github.com/Microsoft/react-native-code-push/releases/tag/1.15.1-beta)))
