### ISSUE TITLE
How to change deployment-key

### ISSUE THREAD

**Issue by sharingjingang050241** [Microsoft/react-native-code-push#570]
In my project ,it used old deployment-key,and the app on Code-Push was deleted.so it does not to work.Now ,i have new a app on Code-Push ,and have a new deployment-key.how can i change deployment in my project.Thanks

**Comment by silhouettes** [comment]
@sharingjingang050241 - so I gather you specifically want to change the deployment key on your new app to what it was on your old one? There is no way to do this as an end user, but if you'd like we can change it back for you. Please email codepush@microsoft.com with the following details:

1. What is your current deployment key, and what would you like to change it to?
2. Approximately when did you delete your old app? (We need to verify that the deployment key you are requesting actually belonged to you)
3. What was the reason you deleted your old app? (This is purely for our own product improvement purposes)

I'm going to close this issue for now, but I look forward to your email!

**Comment by silhouettes** [comment]
For anyone else reading this issue in the future, please note that we can no longer service individual requests to restore deployment keys. If you have removed your deployment by accident, please create a new deployment and ship an app store update with your new deployment key.

**Comment by naltimari** [comment]
Ok, so the CLI might show an warning, but I removed the app in Mobile Center without releasing it was connected to the deployment key I was already using... it's a shame

**Comment by adambene** [comment]
There should be a feature to transfer deployment keys between apps.

**Comment by sergey-akhalkov** [comment]
Hi @adambene, thanks for reaching us, could you please clarify what do you mean by transferring deployment keys between apps, could you please provide a real use case/usage scenario?

**Comment by adambene** [comment]
Hi @sergey-akhalkov, sure. We accidentally deleted an app from the web UI of the App Center and it contained the Code Push deployments also. There was no warning whatsoever that says it will happen.
We'd like to create a new app with the old deployment keys because we want to restore the original state to fix all the apps out there in a backward compatible way.
Another option would be to restore the old app with all its codepush releases in the App Center.

**Comment by sergey-akhalkov** [comment]
@adambene, thanks for the clarification, we are going to discuss what mechanics we can provide to avoid such kind of situations. I'll let you know if I have any updates regarding this.

**Comment by adambene** [comment]
@sergey-akhalkov really nice! thanks :)

**Comment by suretarget** [comment]
@sergey-akhalkov any update regarding to the issue? 
In appcenter, I can add new deployment key but cannot use the old key I added to the release app. Thanks.
