### ISSUE TITLE
RNPM link iOs breaks build

### ISSUE THREAD

**Issue by DeDuckProject** [Microsoft/react-native-code-push#572]
- react-native-code-push version: 1.15.0 beta
- react-native version: 0.30.0
- Does this reproduce on a debug build or release build? both
- Repro steps and/or stack trace:

once building after RNPM link I get these errors:

ld: warning: directory not found for option '-L/Users/iftachyakar/Developer/Fetchy/Source/react_clients/ios/Libraries'
Undefined symbols for architecture x86_64:
  "_crc32", referenced from:
      _unzReadCurrentFile in libCodePush.a(unzip.o)
      _zipWriteInFileInZip in libCodePush.a(zip.o)
  "_deflate", referenced from:
      _zipWriteInFileInZip in libCodePush.a(zip.o)
      _zipCloseFileInZipRaw64 in libCodePush.a(zip.o)
  "_deflateEnd", referenced from:
      _zipCloseFileInZipRaw64 in libCodePush.a(zip.o)
  "_deflateInit2_", referenced from:
      _zipOpenNewFileInZip4_64 in libCodePush.a(zip.o)
  "_get_crc_table", referenced from:
      _unzOpenCurrentFile3 in libCodePush.a(unzip.o)
      _zipOpenNewFileInZip4_64 in libCodePush.a(zip.o)
  "_inflate", referenced from:
      _unzReadCurrentFile in libCodePush.a(unzip.o)
  "_inflateEnd", referenced from:
      _unzCloseCurrentFile in libCodePush.a(unzip.o)
  "_inflateInit2_", referenced from:
      _unzOpenCurrentFile3 in libCodePush.a(unzip.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by calflegal** [comment]
I believe this step fixed this issue for me: http://stackoverflow.com/questions/289274/error-when-import-zlib-in-iphone-sdk#answer-289294

**Comment by calflegal** [comment]
Actually, I think since I've upgraded to react-native 0.36.0 I no longer needed those flags?

**Comment by vladimir-kotikov** [comment]
Just checked and helloworld app with `react-native link`'ed code-push is being compiled properly (react-native@0.39.2). @silhouettes, are we interested in fixing this issue for previous RN versions?

**Comment by panarasi** [comment]
@vladimir-kotikov What would be the proposed fix here ?

**Comment by vladimir-kotikov** [comment]
@panarasi, I was thinking that we might want to add a logic to postlink script that would add required linker option to Xcode project so the project would compile with older React-native versions (they don't seem to have this flags added by default)

**Comment by max-mironov** [comment]
@panarasi, @iageoghe - what do you think, do we need to proceed with this?
IMO this issue should be closed as far as we do not see anyone who claims about this for last several month (I believe it was fixed in RN 0.36+). Your insight here is much appreciated.

**Comment by iageoghe** [comment]
@max-mironov I think your instinct is good here. RN has moved along past the issue.
