### ISSUE TITLE
Updates working for debug config but not release

### ISSUE THREAD

**Issue by wafisher** [Microsoft/react-native-code-push#573]
I'm finding that on the debug configuration, CodePush runs and logs to console:

```
2016-10-19 13:15:42.918 [info][tid:com.facebook.react.JavaScript] [CodePush] Checking for update.
[other log messages]
2016-10-19 13:15:43.296 [info][tid:com.facebook.react.JavaScript] [CodePush] Downloading package.
```

But when I run the app in the release configuration in the simulator, all I get is this:

```
[CodePush] Loading JS bundle from file:///Users/myname/Library/Developer/CoreSimulator/Devices/83B598CF-4F70-4EB2-99EC-B44CA696A8DC/data/Containers/Bundle/Application/59C210B2-47A0-46F0-AAB0-37B90023EF05/MyApp.app/main.jsbundle
```

When the app runs in debug mode, it registers with the server which I can see  `code-push deployment ls` and when it runs in release mode, nothing. I'm also confused how it even replaces the JS code if the startup hook doesn't run in debug mode, which it definitely doesn't since it's hitting the packager.
- react-native-code-push version: 1.15.0-beta
- react-native version: 0.35.0
- iOS/Android/Windows version: 10.0

**Comment by mrkhan2** [comment]
Im having the same problem in #575

**Comment by matrosov-nikita** [comment]
Hi @wafisher 

It's specific implementation of logging in react-native. This condition(https://github.com/facebook/react-native/blob/master/React/Base/RCTLog.mm#L272) is never satisfied in release configuration. There is great answer which explains a reason and suggests workaround for release configuration to show logs in console: http://stackoverflow.com/questions/39089772/release-mode-diagnostics-in-react-native/39091109.

**Comment by marcpechaitis** [comment]
I too am seeing this happen to my newly deployed iOS app.  When running in DEV mode (either via Simulator or on my device), I see the app showing up in the deployment list.  I am not seeing any users/installs show up when running the version from the app store (including my own device)

I checked the logs from the App Store version and found this:

```
Jan  5 12:46:08 myphone myapp(CFNetwork)[713] <Notice>: TIC TCP Conn Cancel [2:0x1743822f0]
Jan  5 12:46:08 myphone myapp(libsystem_network.dylib)[713] <Info>: nw_endpoint_handler_cancel [2 codepush.azurewebsites.net:443 ready resolver (satisfied)]
Jan  5 12:46:08 myphone myapp(libsystem_network.dylib)[713] <Info>: nw_endpoint_handler_cancel [2.1 23.101.203.117:443 ready socket-flow (satisfied)]
Jan  5 12:46:08 myphone myapp(libsystem_network.dylib)[713] <Notice>: __nw_socket_service_writes_block_invoke sendmsg(fd 15, 85 bytes): socket has been closed
Jan  5 12:46:08 myphone myapp(libsystem_network.dylib)[713] <Info>: nw_endpoint_flow_protocol_disconnected [2.1 23.101.203.117:443 cancelled socket-flow (null)] Output protocol disconnected

```
(I am not sure if that is a red herring or not...but its the only reference to "codepush" I found in the logs.)

Here is my code that performs the sync:
```
componentDidMount() {
    CodePush.sync({ deploymentKey: this.getCodePushDeploymentKey(),
                    updateDialog: false,
                    installMode: CodePush.InstallMode.ON_APP_RESUME })
  }

```

- react-native-code-push version: 1.16.0-beta
- react-native version: 0.35.0
- iOS version: 10.0

Codepush is working perfectly fine on the Android deployment.

One other thing to note that might be a factor -- I do not have my codepush deployment key stored in my Info.plist file.  I do not want the key posted publicly in my git repo, so instead I am using [react-native-config](https://github.com/luggit/react-native-config) to hide the key in .env file.  But again, this works fine for android and via simulator so I do not think its the problem?

**Comment by panarasi** [comment]
@marcpechaitis Was this issue resolved ?

**Comment by marcpechaitis** [comment]
I suppose it was?  I ended up just adding the deployment key to my plist (I stopped hiding it via react-native-config) and now it is working.

I will close the issue.

**Comment by panarasi** [comment]
@marcpechaitis Thanks. Closing this issue. Please re-open it if you still have a problem.

**Comment by marcpechaitis** [comment]
@panarasi, but be advised this is not my issue originally...is @wafisher satisfied?

**Comment by panarasi** [comment]
@wafisher Ping.

**Comment by wafisher** [comment]
This was resolved with the answer from @matrosov-nikita. Thanks!
