### ISSUE TITLE
AsyncStorage(get/set...) operation will be blocked while downloading the bundle

### ISSUE THREAD

**Issue by dentalulcer** [Microsoft/react-native-code-push#574]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
- react-native-code-push version: 1.12.1-beta
- react-native version: 0.25.1
- iOS/Android/Windows version: android 5.0.2(SAMSUNG Galaxy A3), android 6.0.1 MMB29M(MI MAX) 
- Does this reproduce on a debug build or release build? both
- Does this reproduce on a simulator, or only on a physical device? both
- Repro steps and/or stack trace: 

I store my login info locally using AsyncStorage, when I start my app and submit login info, the storage operation will be blocked while downloading the new codepush bundle, it happens on android. Is it normal?

Thanks for the amazing project!

**Comment by dentalulcer** [comment]
help

**Comment by jerson** [comment]
same here im using react-native-fs and block when download

**Comment by sopaco** [comment]
@dentalulcer @jerson 
I also have some such problem only in Android.
see https://github.com/facebook/react-native/issues/10203

**Comment by dentalulcer** [comment]
it works for me 
`
/** CodePushNativeModule.java->downloadUpdate() */
asyncTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR);
`

**Comment by panarasi** [comment]
@sergey-akhalkov I think we should investigate this issue.

**Comment by jonrh** [comment]
I've been trying to diagnose a problem on an iOS app that may suffer from a similar trait. I'm using [react-native-keychain](https://github.com/oblador/react-native-keychain) to save/load passwords securely. I'm not entirely sure how it works but I think it's done asynchronously. Could there be a similar block/issue?

@buptkang: The v1.17.1-beta release notes states in Bug Fixes: "2. (**Both iOS** and Android) Fixed the issue #574". The [pull request #693](https://github.com/Microsoft/react-native-code-push/pull/693) only changed some Java files, were similar iOS changes made in a different PR/commit or was this perhaps never an issue on iOS?

**Comment by sergey-akhalkov** [comment]
@jonrh,
>was this perhaps never an issue on iOS?

We've not reported before that the issue reproduces for iOS too, also @sopaco said:
>I also have some such problem only in Android.

For the matter of that:
>Could there be a similar block/issue?

I don't sure about it, so we need some investigation - could you please verify if the issue reproduces or not in case of using `AsyncStorage` (instead of using `Keychain`)? If so, please create [new issue](https://github.com/Microsoft/react-native-code-push/issues/new) so we would able to start investigation and fixing.

**Comment by jonrh** [comment]
@sergey-akhalkov Thanks! I will try my best. It's been very hard though to produce code that reliably replicates this. I'll submit an issue if I'm able to. Thanks again for your hard work!

**Comment by sergey-akhalkov** [comment]
@jonrh, no problem, thank you!
