### ISSUE TITLE
Running a Local Debug Build [Android]

### ISSUE THREAD

**Issue by ninjz** [Microsoft/react-native-code-push#576]
I would like to be able to create a local debug build (loading the JS package from my machine), but with the current instructions I am only able to create a Staging and Production build that loads the JS bundle from CodePush. I think my confusion mostly lies in the fact that we have explicitly overrode the getJSBundleFile Method in MainApplication.java, and I can't seem to figure out how to conditionally override it based on the set buildType

* react-native-code-push version: v1.15-beta
* react-native version: 0.34.1
* iOS/Android/Windows version: Android

**Comment by ippa** [comment]
You need something like this in AppDelegate.m:

```
#ifdef DEBUG
   jsCodeLocation = [NSURL URLWithString:@"http://YOUR_IP:8081/index.ios.bundle?platform=ios&dev=true"];
#else
    jsCodeLocation = [CodePush bundleURL];
#endif
```

**Comment by silhouettes** [comment]
Hi @ninjz, I believe that when running in `debug` mode, React Native will force your app to load from the packager, regardless of what you have instrumented in code. More information here: https://github.com/Microsoft/react-native-code-push/issues/153

Does this resolve the problem for you?

**Comment by ninjz** [comment]
Hi @silhouettes I think that solves my issue, but now I am confused as to how to have a staging environment for my application. According to the instructions we are to put our staging environment configs in the `debug` buildType, but since that loads up the app from the packager then it technically is not getting my staging build either

**Comment by ippa** [comment]
@ninjz: from my build.gradle, maybe it helps:

```
buildTypes {
        debug {
            buildConfigField "String", "CODEPUSH_KEY", '""'
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            buildConfigField "String", "CODEPUSH_KEY", '"keyz"'
        }

        // HACK: Name it "stagingrelease" so react-native (via react.gradle) will build it as a release
        stagingrelease.initWith(buildTypes.release)
        stagingrelease {
            buildConfigField "String", "CODEPUSH_KEY", '"keyz"'
        }
    }
```
This setup works well for me for now.

**Comment by ninjz** [comment]
Ok that actually makes a lot of sense now. Thanks @ippa !
