### ISSUE TITLE
[Android] CodePushHash.json is not JSON

### ISSUE THREAD

**Issue by insaindesign** [Microsoft/react-native-code-push#577]
`CodePushHash.json` is just storing a string, and not JSON, so the file type should **NOT** be JSON. This breaks flow type checking, and generally just seems confusing.

The file is read as a string from https://github.com/Microsoft/react-native-code-push/blob/3dce59f36e0f780f1773342e20c56fe870ba019a/android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateUtils.java#L110 and written to as a crypto hex string in https://github.com/Microsoft/react-native-code-push/blob/bb04535fbef4cb580da4c29ae628452cc0774fc8/scripts/generateBundledResourcesHash.js#L74. At no point is it encoded or needing to be decoded as JSON.

**Comment by panarasi** [comment]
@insaindesign I think this is a good point. However, if we change the name now, it would break existing apps. Is there a way you could ignore it in the flow type checking ?

**Comment by hawkrives** [comment]
@panarasi In my project, I have flow configured to ignore all .json files, which it does – it will error on other JSON files if I don't – but it still errors on the `CodePushHash.json`.

We discovered that adding `.*/CodePushHash.json`, with the leading `.*/`, will force flow to ignore the file and not error.

**Comment by panarasi** [comment]
@sergey-akhalkov Can we investigate this ? We would need a backward compatible change.

**Comment by sergey-akhalkov** [comment]
Closing this due to #763 has been merged, please feel free to reopen if needed.
