### ISSUE TITLE
Flag to ignore: [Error]  The uploaded package was not released because it is identical to the contents of the speci fied deployment's current release.      

### ISSUE THREAD

**Issue by StevePotter** [Microsoft/react-native-code-push#578]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version: 1.14.6-beta
* react-native version:0.35
* iOS/Android/Windows version: latest ios
* Does this reproduce on a debug build or release build? debug (didn't try releases)
* Does this reproduce on a simulator, or only on a physical device?
* Repro steps and/or stack trace:

code-push runs in our ci system (bitrise.io).  Sometimes we make a change that doesn't affect the RN portion.  When this happens, code-push fails with error: [Error]  The uploaded package was not released because it is identical to the contents of the speci
fied deployment's current release.      

This results in a broken build report.  It would be nice if this error could be ignored via command line flag.  Even a different exit code would be helpful

**Comment by silhouettes** [comment]
Hi @StevePotter - we have actually gotten the same request and implemented this flag already! Please see: https://github.com/Microsoft/code-push/issues/255.

I'm going to close this for now, but please let me know if that works for you!

**Comment by iTOYS** [comment]
Hi @luongs3 
Flag works properly, we don't publish the same packages.
This flag useful for CI and doesn't work like `git --amend`

Thanks!

**Comment by jsshizhan** [comment]
i have the same problem and --noDuplicateReleaseError not work.when i clean history,the problem disappear

**Comment by karltaylor** [comment]
Sorry for hijacking but it's the same problem - when I try and do `appcenter codepush deployment clear Staging`

I get an error:

```
Error: {"message":"Forbidden","code":"Forbidden"}
```
