### ISSUE TITLE
Is Apple store support for this? i need help

### ISSUE THREAD

**Issue by luyuan11233** [Microsoft/react-native-code-push#579]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?
* Repro steps and/or stack trace:

(The more info the faster we will be able to address it!)

**Comment by silhouettes** [comment]
Please see: http://microsoft.github.io/code-push/faq/index.html
