### ISSUE TITLE
Update fail since yesterday 

### ISSUE THREAD

**Issue by seph14** [Microsoft/react-native-code-push#580]
I keep getting 500 response from server since yesterday night (GMT+9)

![screen shot 2016-10-25 at 13 40 44](https://cloud.githubusercontent.com/assets/6417336/19674174/bcc5ce82-9ab8-11e6-81d7-c430a8d3e2c5.png)
Does anyone else experiencing the same?

**Comment by silhouettes** [comment]
Hi @seph14, could you upgrade to the latest CLI and try again? (`npm install -g code-push-cli@latest`). I suspect that your access key has expired, and if that is the case, the latest CLI will display a much better error message.

Sorry for the confusion, and please let me know if that resolves it for you!

**Comment by silhouettes** [comment]
@seph14 - I'm going to close this for now, but please let me know if you run into any more issues!
