### ISSUE TITLE
1.15.0 on ios using swift and cocoapods - RCTEventEmitter not found

### ISSUE THREAD

**Issue by stewart42** [Microsoft/react-native-code-push#583]
- react-native-code-push version: 1.15.0-beta
- react-native version: 0.34.0
- iOS/Android/Windows version: ios
- Does this reproduce on a debug build or release build? na
- Does this reproduce on a simulator, or only on a physical device? na
- Repro steps and/or stack trace:

ios project using cocoapods and swift, code-push 1.14.6-beta - no issues.
upgrade to 1.15.0-beta 
pod install
build project - `node_modules/react-native-code-push/ios/CodePush/CodePush.h:1:9: 'RCTEventEmitter.h' file not found`

change line 1 of `CodePush.h` to `#import "React/RCTEventEmitter.h"`
build succeeds 

A while back react-native had issues with cocoapods see https://github.com/facebook/react-native/issues/9014 as an example, it may help.

**Comment by stewart42** [comment]
@silhouettes have you guys made any progress on this? Can I help in anyway?

**Comment by quinnliu** [comment]
I am having the same issue with versions:
```
    "react-native": "0.35.0",
    "react-native-code-push": "^1.15.0-beta",
```
and Xcode 7.3.1 for my iOS project: https://github.com/Laybium/laybium

When I tried change line 1 of CodePush.h to #import "React/RCTEventEmitter.h"
I still get the same error. 

@silhouettes Is there a earlier version of `react-native-code-push` I should try? Thanks

**Comment by stewart42** [comment]
@quinnliu you could try [v1.14.6-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v1.14.6-beta)

**Comment by silhouettes** [comment]
@stewart42, sorry about the slow response. Does @quinnliu's fix work for you by any chance?

**Comment by shrutic** [comment]
@silhouettes I had the same issue as @stewart42 and I followed the work around as mentioned by @quinnliu  . It unfortunately didnt work for me. I still get the error "RCTEventEmitter.h" file not found. For me "React/RCTEventEmitter.h" also didnt work. I am trying to setup CodePush for an iMessage Extension using React native. My react native version is 0.34.0 and code push version is the latest as installed today via npm and pod install on Nov 7 2016.(not sure how to get code push version from npm module)

**Comment by stewart42** [comment]
@silhouettes I tried the suggestion above and I am still getting the issue unfortunately.

**Comment by bendellarocco** [comment]
I am seeing this on "react-native-code-push": "^1.15.1-beta" using react 25

**Comment by bendellarocco** [comment]
I also tried the above steps and had the same results.  I installed using rnpm link as well as the manual process

**Comment by silhouettes** [comment]
Thank you for the details - I suspect the issue is either with our compatibility with CocoaPods, or with RN 34. @bendellarocco, are you using CocoaPods? Also when you say 'react 25', do you mean `react-native@0.25.0`?

**Comment by bendellarocco** [comment]
@silhouettes `"react-native": "^0.25.1",`.  I am not using Cocao Pods for this package.  I am used rnpm link.  And I also tried installing using the manual process.  When I switched to v1.14.6-beta I no longer had this issue.

**Comment by silhouettes** [comment]
I tried a simple barebones app with `react-native@0.34.0`, `react-native-code-push@1.15.0-beta`, and installation using `react-native link`, and was not able to reproduce.

I will follow up by trying the same thing with CocoaPods, and then the same thing with `react-native@0.25.1` (it is possible they are two separate issues).

**Comment by stewart42** [comment]
FWIW, @silhouettes I am referencing codepush the pod file 
`pod 'CodePush', :path => './node_modules/react-native-code-push'`

**Comment by silhouettes** [comment]
I am still unable to reproduce with `react-native@0.34.0`, `react-native-code-push@1.15.0-beta`, and CocoaPods this time. @stewart42, @shrutic - are you able to show me your repo somehow? If not, would you like to do a Skype session sometime?

**Comment by silhouettes** [comment]
Are you all using swift?

**Comment by stewart42** [comment]
Yes I am using swift. 
I have a few items I need to get done today, but I will try to get a sample app with the issue as soon as I can.

**Comment by shrutic** [comment]
Yes I am using Swift as well. I might be able to get a sample app next
week. Which version of Cocoapods are you using? I am using 1.0.1. Beyond
1.0.1, React native has issues for me and so until react native fixes this,
I am stuck at cocoapods 1.0.1

**Comment by silhouettes** [comment]
Okay, so I've set up a project from scratch using Swift and I've reproduced the issue! Thanks for your patience, fix will be coming shortly.

**Comment by stewart42** [comment]
Oh awesome @silhouettes, thanks so much.

**Comment by dcvz** [comment]
I'm also experiencing this issue. Is there a temporary workaround?

**Comment by stewart42** [comment]
@dcvz either revert to `1.14.6-beta` or change line 1 of `CodePush.h` to `#import "React/RCTEventEmitter.h"`

**Comment by stewart42** [comment]
@silhouettes any ETA on this fix? Sorry to push, just planning some deployments.

**Comment by silhouettes** [comment]
I'm going to estimate 3 days on this, apologies for the wait!

**Comment by silhouettes** [comment]
The fix has been tested and published in `react-native-code-push@1.16.1-beta` ([release notes](https://github.com/Microsoft/react-native-code-push/releases)). Thank you so much for your patience, and feel free to come back if you run into any other issues!

@stewart42 @quinnliu @shrutic @bendellarocco @dcvz

**Comment by mikberg** [comment]
To anyone this might benefit: I could not get this to work using cocoapods. I fixed it by installing codepush manually for iOS.

I might have an odd configuration, I don't know.

**Comment by IrvingAxelB** [comment]
I am also running into this error using "react-native-code-push": "^1.16.1-beta" and "react-native": "0.35.0"

**Comment by sergey-akhalkov** [comment]
@IrvingAxelB - hi!
To avoid unexpected issues make sure you are using compatible version of `react-native` and `react-native-code-push` ([Supported React Native platforms](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms)).
I've also faced with this issue and fixed it by adding `React` to my `Podfile`:
```
  pod 'React', :path => '../node_modules/react-native'
  pod 'React/RCTGeolocation', :path => '../node_modules/react-native'
  pod 'React/RCTImage', :path => '../node_modules/react-native'
  pod 'React/RCTNetwork', :path => '../node_modules/react-native'
  pod 'React/RCTText', :path => '../node_modules/react-native'
  pod 'React/RCTWebSocket', :path => '../node_modules/react-native'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
```

**Comment by rafaelcorreiapoli** [comment]
I'm still facing this issue

**Comment by sergey-akhalkov** [comment]
Hi @rafaelcorreiapoli, please feel free to create new issue and fill out the [issue's template](https://github.com/Microsoft/react-native-code-push/issues/new) - we'll glad to help you.
