### ISSUE TITLE
Is it possible to use code-push in the ios simulator?

### ISSUE THREAD

**Issue by sulliwane** [Microsoft/react-native-code-push#59]
Hello, me again.

Short question: Is it possible to use code-push in the ios simulator?

It seems not working for me, only on the device.

Thanks!

**Comment by lostintangent** [comment]
Yep it definitely works in the simulator. We test it in that environment heavily. Could you elaborate a little on what isn't working? Thanks!

**Comment by sulliwane** [comment]
One more false positive, indeed it's possible. It was downloading very slowly the bundle (china), so it just took time to see the changes. Thanks!

**Comment by lostintangent** [comment]
Yeah, the silent mode behavior definitely might mask this :) when you're debugging your app, check out the console in either. Xcode or Chrome and you'll see logs with the status of the download process. That way you can track its status and ensure its working :)

**Comment by sulliwane** [comment]
I was killing the app to "start" the update, and so killing the chrome debugging sessions at the same time. So using ``` sync({ updateDialog: true, installMode: CodePush.InstallMode.IMMEDIATE })``` was very helpful for debugging :+1:
