### ISSUE TITLE
how could I build my private code-push server

### ISSUE THREAD

**Issue by L-Jovi** [Microsoft/react-native-code-push#591]
hi, it's actually not a issue, thanks for your smart `react-native-code-push`, it's cool and convenient

and my question is that how could I build my own code-push-server, I mean it's similar to docker registry and I could manage own service from my VPS and so on ..

 I don't find any server building info from [code push official website](https://microsoft.github.io/code-push/), maybe I miss something :(

thanks for your time,

regards.

**Comment by johnwook** [comment]
Although it's not official, I know there is a [code-push-server](https://github.com/lisong/code-push-server)

**Comment by silhouettes** [comment]
Hi @L-Jovi, unfortunately we don't currently have an on-premise solution. For now, we recommend just using the official CodePush server - you are welcome to build your own, but keep in mind that we cannot guarantee compatibility with any unofficial servers, especially as new features come out in the future. I hope this helps, feel free to ask any additional questions!

**Comment by L-Jovi** [comment]
thanks for reply :)
