### ISSUE TITLE
TransformError

### ISSUE THREAD

**Issue by sopaco** [Microsoft/react-native-code-push#594]
when I execute the command `code-push release-react yitech_ios ios -d Production -t '*'`, it report an error below(I could run the app successful with react-native start ):
`TransformError: /Users/MacHewleet/Workspace/SAW/generic_reactapp/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/ExceptionsManager.js: /Users/MacHewleet/Workspace/SAW/generic_reactapp/node_modules/react-native/Libraries/JavaScriptAppEngine/Initialization/ExceptionsManager.js: Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null`
What's wrong!
( cli-version: '1.11.1-beta', "react-native-code-push": "^1.15.0-beta", react-native: 0.35.0)

**Comment by mankins** [comment]
What was this caused by, @sopaco ?

**Comment by lengocgiang** [comment]
@sopaco : I also had this problem?

**Comment by mankins** [comment]
@lengocgiang Mine was caused by a babelrc problem. I was using a plugin to remove console.log statements. When I removed it / reverted to the standard .babelrc it worked.
