### ISSUE TITLE
fatal error: 'CodePush.h' file not found

### ISSUE THREAD

**Issue by devhyunjae** [Microsoft/react-native-code-push#595]
* react-native-code-push version: @1.15.1-beta
* react-native version: 0.36.0
* iOS/Android/Windows version: iOS
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both
* Repro steps and/or stack trace:

build fails

```
fatal error: 'CodePush.h' file not

      found
#import "CodePush.h"
        ^
1 error generated.

** BUILD FAILED **
```

(The more info the faster we will be able to address it!)

after,

`react-native link react-native-code-push`

`react-native run-ios`

builds fail with this error

```
fatal error: 'CodePush.h' file not

      found
#import "CodePush.h"
        ^
1 error generated.

** BUILD FAILED **
```

I don't know why, but `react-native link` does not perfectly do the linking job. It inserted the code, but didn't do linking. So i have done as mentioned in the manual installation flow.

![screen shot 2016-11-08 at 2 52 22 pm](https://cloud.githubusercontent.com/assets/12890257/20088478/96d9f156-a5c3-11e6-946e-950db1f77fa3.png)

![screen shot 2016-11-08 at 2 54 13 pm](https://cloud.githubusercontent.com/assets/12890257/20088479/999ca5e6-a5c3-11e6-9002-82bf2dbcad51.png)

but still, having this error

**Comment by devhyunjae** [comment]
never mind, i added in the test path :(

**Comment by adeelraza** [comment]
@devhyunjae I'm getting this error. How did you resolve it?
