### ISSUE TITLE
app not update

### ISSUE THREAD

**Issue by wzy535** [Microsoft/react-native-code-push#596]
Hi,
when I use this ,It can download ,but the app not update. restart the app and it's not update too.
when touch sync again it display "app is up to date"

* react-native-code-push version: 1.15.1-beta
* react-native version: 0.35
* iOS/Android/Windows version: Android 6
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? simulator
* Repro steps and/or stack trace: 

`11-08 01:08:22.930  6545  6567 I ReactNativeJS: [CodePush] Reporting binary update (1.0.17)
11-08 01:08:22.939  6545  6596 V WebViewFactory: webViewPackageName: com.android.webview
11-08 01:08:22.940  6545  6596 I WebViewFactory: Loading com.android.webview version 44.0.2403.119 (code 246011910)
11-08 01:08:22.955  6545  6596 W System  : ClassLoader referenced unknown path: /system/app/webview/lib/x86
11-08 01:08:22.958  6545  6596 I LibraryLoader: Time to load native libraries: 1 ms (timestamps 6957-6958)
11-08 01:08:22.958  6545  6596 I LibraryLoader: Expected native library version number "",actual native library version
number ""
11-08 01:08:28.000   782  1675 D NetlinkSocketObserver: NeighborEvent{elapsedMs=18122000, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_REACHABLE}
11-08 01:08:43.760   782  1675 D NetlinkSocketObserver: NeighborEvent{elapsedMs=18137760, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_STALE}
11-08 01:08:47.430   782   921 I ActivityManager: START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10016 on display 0
11-08 01:08:47.466   814   814 E EGL_emulation: tid 814: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)
11-08 01:08:47.545  6545  6545 D FirebaseApp: Notifying background state change listeners.
11-08 01:08:47.585  6545  6564 E Surface : getSlotFromBufferLocked: unknown buffer: 0xe05db5b0
11-08 01:08:47.608   903  1238 W EGL_emulation: eglSurfaceAttrib not implemented
11-08 01:08:47.608   903  1238 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xde1fe3c0, error=EGL_SUCCESS
11-08 01:08:50.702   782  1212 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.android.launcher3/.Launcher} from uid 10016 on display 0
11-08 01:08:50.706   782  1204 I ActivityManager: Killing 6545:com.saitio/u0a82 (adj 9): remove task
11-08 01:08:50.724   782   842 W InputDispatcher: channel 'e03a988 com.saitio/com.saitio.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-08 01:08:50.724   782   842 E InputDispatcher: channel 'e03a988 com.saitio/com.saitio.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-08 01:08:50.725   782   921 D GraphicsStats: Buffer count: 5
11-08 01:08:50.725   782   794 I WindowState: WIN DEATH: Window{e03a988 u0 com.saitio/com.saitio.MainActivity}
11-08 01:08:50.725   782   794 W InputDispatcher: Attempted to unregister already unregistered input channel 'e03a988 com.saitio/com.saitio.MainActivity (server)'
11-08 01:08:50.789   903  1238 E Surface : getSlotFromBufferLocked: unknown buffer: 0xe05f9140
11-08 01:08:50.820   903  1238 D OpenGLRenderer: endAllStagingAnimators on 0xde65bc00 (RippleDrawable) with handle 0xde16dbf0
11-08 01:08:50.866  1167  1299 W EGL_emulation: eglSurfaceAttrib not implemented
11-08 01:08:50.866  1167  1299 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xddfb4920, error=EGL_SUCCESS
11-08 01:08:51.483  1167  1299 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
11-08 01:08:51.483  1167  1299 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
11-08 01:08:53.833   782  1190 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.saitio/.MainActivity (has extras)} from uid 10008 on display 0
11-08 01:08:53.852   782   793 I ActivityManager: Start proc 6612:com.saitio/u0a82 for activity com.saitio/.MainActivity
11-08 01:08:53.875  6612  6612 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
11-08 01:08:53.877  6612  6612 D FirebaseApp: Initialized class com.google.firebase.iid.FirebaseInstanceId.
11-08 01:08:53.877  6612  6612 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
11-08 01:08:53.881  6612  6612 I FA      : App measurement is starting up, version: 9080
11-08 01:08:53.881  6612  6612 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
11-08 01:08:53.890  6612  6612 D FirebaseApp: Initialized class com.google.android.gms.measurement.AppMeasurement.
11-08 01:08:53.890  6612  6612 I FirebaseInitProvider: FirebaseApp initialization successful
11-08 01:08:53.890   476   864 D AudioFlinger: mixer(0xf1e40000) throttle end: throttle time(11)
11-08 01:08:53.904  6612  6612 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.saitio/files/CodePush/a45ca47a256787dd7dde34a5a503c25d5a2ebbc06f0ba995bab040b83e5f0d12/CodePush/index.android.bundle"
11-08 01:08:53.905  6612  6612 V fb-UnpackingSoSource: locked dso store /data/user/0/com.saitio/lib-main
11-08 01:08:53.905  6612  6612 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.saitio/lib-main
11-08 01:08:53.905  6612  6612 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.saitio/lib-main
11-08 01:08:53.917  6612  6612 I art     : Thread[1,tid=6612,Native,Thread*=0xf3df4a00,peer=0x73965258,"main"] recursive attempt to load library "/data/app/com.saitio-1/lib/x86/libfb.so"
11-08 01:08:53.947   782   842 I InputDispatcher: Dropping event because there is no touchable window at (920, 1905).
11-08 01:08:53.983  6612  6630 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
11-08 01:08:54.028  6612  6622 I art     : Background sticky concurrent mark sweep GC freed 3211(400KB) AllocSpace objects, 8(160KB) LOS objects, 33% free, 1307KB/1954KB, paused 185us total 100.801ms
11-08 01:08:54.052  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
11-08 01:08:54.055  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
11-08 01:08:54.058  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
11-08 01:08:54.059  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
11-08 01:08:54.060  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
11-08 01:08:54.062  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
11-08 01:08:54.062  6612  6612 D         : HostConnection::get() New Host Connection established 0xe8c3fe20, tid 6612
11-08 01:08:54.064  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
11-08 01:08:54.065  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
11-08 01:08:54.066  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
11-08 01:08:54.070  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
11-08 01:08:54.071  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
11-08 01:08:54.075  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
11-08 01:08:54.092  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
11-08 01:08:54.093  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
11-08 01:08:54.093  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
11-08 01:08:54.093  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
11-08 01:08:54.093  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
11-08 01:08:54.094  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
11-08 01:08:54.095  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
11-08 01:08:54.095  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
11-08 01:08:54.096  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
11-08 01:08:54.096  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
11-08 01:08:54.097  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
11-08 01:08:54.097  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
11-08 01:08:54.097  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
11-08 01:08:54.097  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
11-08 01:08:54.098  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
11-08 01:08:54.100  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
11-08 01:08:54.100  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
11-08 01:08:54.102  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
11-08 01:08:54.103  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
11-08 01:08:54.103  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
11-08 01:08:54.103  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
11-08 01:08:54.104  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
11-08 01:08:54.105  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
11-08 01:08:54.105  6612  6629 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.github.alinz.reactnativewebviewbridge.WebViewBridgeManager
11-08 01:08:54.121  1167  1299 E Surface : getSlotFromBufferLocked: unknown buffer: 0xe0e04290
11-08 01:08:54.157  6612  6630 D libEGL  : loaded /system/lib/egl/libEGL_emulation.so
11-08 01:08:54.160  6612  6630 D libEGL  : loaded /system/lib/egl/libGLESv1_CM_emulation.so
11-08 01:08:54.167  6612  6630 D libEGL  : loaded /system/lib/egl/libGLESv2_emulation.so
11-08 01:08:54.192  6612  6630 D         : HostConnection::get() New Host Connection established 0xdeb4cd70, tid 6630
11-08 01:08:54.212  6612  6630 I OpenGLRenderer: Initialized EGL, version 1.4
11-08 01:08:54.335  6612  6630 W EGL_emulation: eglSurfaceAttrib not implemented
11-08 01:08:54.335  6612  6630 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdeb593e0, error=EGL_SUCCESS
11-08 01:08:54.368  6612  6638 W InstanceID/Rpc: Failed to resolve REGISTER intent, falling back
11-08 01:08:54.368  6612  6627 I FA      : This instance being marked as an uploader
11-08 01:08:54.369  6612  6638 W InstanceID/Rpc: Both Google Play Services and legacy GSF package are missing
11-08 01:08:54.369  6612  6638 D FirebaseInstanceId: background sync failed: MISSING_INSTANCEID_SERVICE, retry in 10s
11-08 01:08:54.393  6612  6633 I ReactNativeJS: Running application "saitio" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
11-08 01:08:54.470   782   801 I ActivityManager: Displayed com.saitio/.MainActivity: +628ms
11-08 01:08:55.740   782  1675 D NetlinkSocketObserver: NeighborEvent{elapsedMs=18149740, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_REACHABLE}
11-08 01:09:00.003   782   796 I ProcessStatsService: Prepared write state in 0ms
11-08 01:09:04.377  6612  6642 D FirebaseInstanceId: background sync failed: MISSING_INSTANCEID_SERVICE, retry in 20s
11-08 01:09:09.292   782  1675 D NetlinkSocketObserver: NeighborEvent{elapsedMs=18163292, 10.0.3.2, [525400123502], RTM_NEWNEIGH, NUD_STALE}
11-08 01:09:24.381  6612  6644 D FirebaseInstanceId: background sync failed: MISSING_INSTANCEID_SERVICE, retry in 40s`

Thanks in advance!

**Comment by silhouettes** [comment]
This is a tricky one... could you perhaps show me the output of `code-push deployment history <AppName> <DeploymentName>`?

**Comment by vladimir-kotikov** [comment]
@wzy535, are you still seeng this? If so, could you please also paste output of `code-push debug android` (in addition to `code-push deployment history`)

**Comment by caoyang819** [comment]
Sorry, I have already upgrade react native's version(now react native is using 0.39.2).  And it's ok now!
Thank you very much!
