### ISSUE TITLE
Issue using codePushDidChange

### ISSUE THREAD

**Issue by bendellarocco** [Microsoft/react-native-code-push#597]
* react-native-code-push version: 1.14.6-beta
* react-native version: 25
* iOS/Android/Windows version: 10
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? simulator

codePushDidChange seems to never get called for me.  It may be my error but I would appreciate if anyone knew my issue here.  An update will install but the codePushStatusDidChange never recieves a callback. 

Code Example:
<img width="670" alt="screen shot 2016-11-08 at 12 14 49 pm" src="https://cloud.githubusercontent.com/assets/9866222/20109200/fd38ed42-a5ac-11e6-82e2-71e1b126f675.png">

**Comment by silhouettes** [comment]
I can't see what `codePushOptions` is from your screenshot, but is it possible that the `this` pointer is not binded correctly for `codePushStatusDidChange`?

Also, here is a working example: https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/demo.js

**Comment by bendellarocco** [comment]
Code Push Options - 
`var codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_RESUME, installMode: codePush.InstallMode.ON_NEXT_RESUME, rollbackTimeout: 10000, }`

**Comment by bendellarocco** [comment]
Using your example I was able to solve the issue.  Thank you!

**Comment by silhouettes** [comment]
Glad you were able to solve it!
