### ISSUE TITLE
"react-native link" command assumes existence of ios app in repository

### ISSUE THREAD

**Issue by artdent** [Microsoft/react-native-code-push#598]
I'm embedding react-native in an existing Android app, with no iOS code in the repository. Because of this, `react-native link react-native-code-push` fails when it runs scripts/postlink/ios/postlink.js, which expects to find e.g. AppDelegate.m. I was able to work around this by commenting out that script, but it would be good for the script to handle this scenario by gracefully doing nothing.

* react-native-code-push version: 1.15.1-beta
* react-native version: 0.36.1
* Repro steps and/or stack trace:
```
$ npm install --save react-native-code-push
$ react-native link react-native-code-push
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at Object.<anonymous> (/Users/.../node_modules/react-native-code-push/scripts/postlink/ios/postlink.js:18:42)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
/Users/.../node_modules/react-native/local-cli/core/makeCommand.js:19
        throw new Error(`Error occured during executing "${ command }" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (/Users/.../node_modules/react-native/local-cli/core/makeCommand.js:19:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by artdent** [comment]
On a side note, the Android script didn't work either for a variety of reasons:
- my app is in the root directory, not the "android" subdirectory
- my app/build.gradle uses single quotes, breaking the regex that looks for 'apply from: [...]react.gradle'
- my ReactNativeHost is in its own file, not within the ReactApp class.

But, honestly, the manual integration is super easy (edit three files in the standard manner), so I imagine it's probably not worth making the postlink script handle anything more complicated than what's generated by `react-native init`.

**Comment by silhouettes** [comment]
Ah - thank you!! We've been trying to figure out all of the issues with the linking script but it's been difficult to know what is different on people's machines. This is extremely helpful!!

**Comment by yangjinsong** [comment]
I have also encountered this problem， how to Solve the problem

**Comment by matrosov-nikita** [comment]
Hi @artdent, @yangjinsong 

I've sent PR(https://github.com/Microsoft/react-native-code-push/pull/639) which prevents crash if any platform is missing in project.
As for other cases, it's really difficult to identify all user's changes. Now, we can only mitigate regex expression to resolve your second problem.

**Comment by vladimir-kotikov** [comment]
Closing this as many of edge cases above has been fixed in in https://github.com/Microsoft/react-native-code-push/pull/639
