### ISSUE TITLE
Not possible to install an update after it's been rolled back?

### ISSUE THREAD

**Issue by cooperka** [Microsoft/react-native-code-push#600]
### Current behavior

1. I run `release-react` and a new version is released to Staging
2. I check for updates in my simulator, and the new version is installed
3. I refresh the simulator with `Cmd+R`
4. The app errors out because it can't connect to the remote debugger (this seems to happen when installing CodePush updates, but it's fine)
5. CodePush assumes that it was at fault for the error, and rolls back the release
6. I have no way of ever updating to that version again
  * Message: `An update is available, but it is being ignored due to having been previously rolled back.`
7. I have to make an arbitrary change in the code so I'm allowed to re-publish a new build and start from step 1 (with remote debugging turned off this time)

### Expected behavior

The same as 1-5, but there should be an option of either resetting all rollbacks for a release or disabling auto-rollback for dev builds. In this case there was nothing wrong with the CodePush update, but once it thinks there was a problem, there's nothing I can do to reset it.

### Version info

* react-native-code-push v1.15.1-beta
* react-native v0.37.0

**Comment by silhouettes** [comment]
HI @cooperka, this may be very problem-specific, but if you wipe the data on the simulator (it should be available as a menu option) and re-deploy the app, it should behave as if it was a fresh install and apply the original version you intended. Does that solve the problem for you?

**Comment by cooperka** [comment]
Even easier, I uninstalled the app and reinstalled it, and that works. That's definitely easier than publishing a new update!

It would still be nice if there were a way to disable rollbacks, at least on Staging, but this workaround is fine for now.

**Comment by silhouettes** [comment]
I'm going to close this for now seeing as there is a workaround, but if there are more requests to disable rollbacks we can re-visit it!

**Comment by tlcheah2** [comment]
Is that means if rollback happened, there would be no way for the user that was roll backed to install the latest update through codePush ? 
Rather, the user would need to uninstall the whole application and reinstall it as fresh app.

**Comment by cooperka** [comment]
@tlcheah2 correct, to install the **same exact** version that was automatically rolled back, you need to either clear the app's data (so it forgets it rolled back the update) or just push a new version.
