### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by kiranruth** [Microsoft/react-native-code-push#604]
While installing  code push using the command 

> npm install --save react-native-code-push@latest

I get the error 

> npm ERR! cb() never called!

How do i proceed ?

**Comment by silhouettes** [comment]
Hi @kiranruth, which version of npm are you using? I'm assuming that you ran this from the root of your project, which already has a `package.json` set up?

**Comment by kiranruth** [comment]
@silhouettes i'm using npm 3.10.9 and node 7.1.0. Yes i ran this from the root of my project which has a package.json

**Comment by silhouettes** [comment]
Do you mind showing me the contents of your `package.json`?

**Comment by silhouettes** [comment]
Closing this for now, but feel free to reopen!

**Comment by edem** [comment]
I got the same error .....

**Comment by edem** [comment]
D:\??????>npm install
npm WARN tar zlib error: unexpected end of file
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2018-05-31T07_25_15_835Z-debug.log
