### ISSUE TITLE
Is the service up and running at the moment?

### ISSUE THREAD

**Issue by kkgelu** [Microsoft/react-native-code-push#605]
I keep getting this when releasing my apps to production today:

> bundle: Done writing bundle output
bundle: Copying 13 asset files
bundle: Done copying assets

Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
[Error]  <html><head><title>500 - The request timed out.</title></head><body>  <font color ="#aa0000">         <h2>500 - The request timed out.</h2></font>  The web server failed to respond within the specified time.</body></html>
15:

Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version: 1.15.0-beta
* react-native version: 0.35.0

**Comment by kkgelu** [comment]
Okay, I need to re-login again. Hope we get a better error message in future.

**Comment by silhouettes** [comment]
Yes, sorry about that! If you upgrade to the latest CLI (`npm install -g code-push-cli@latest`), we will have fixed that error message.
