### ISSUE TITLE
never work when add 'codepush' 's tag

### ISSUE THREAD

**Issue by aqnaruto** [Microsoft/react-native-code-push#608]
i followed the readme document ,and rebuiled again and again.
it still not work.
whether  add `async` or `codePush(MyApp)` or add`@codepush`with es7
![image](https://cloud.githubusercontent.com/assets/9067159/20349943/a063390a-ac47-11e6-8ffa-7ba073b03939.png)
`

seems the environment do'nt recognize it 

rn 3.6 , android ,windows.

**Comment by aqnaruto** [comment]
sorry i am fogot to rebuild it

**Comment by silhouettes** [comment]
Hi @aqnaruto, I'm not sure if your problem is solved now, but if not, can you show me the contents of `Main.js`?

**Comment by aqnaruto** [comment]
close

**Comment by aqnaruto** [comment]
sorry i am fogot to rebuild android ,it is a basic opretion.  thank your excellent work @silhouettes
