### ISSUE TITLE
Updates always rolled-backed

### ISSUE THREAD

**Issue by tobiaskiel** [Microsoft/react-native-code-push#610]
Hi!
Im trying to update my app using codepush
In my component I have:
`componentDidMount() {
    codePush.sync({ updateDialog: true});
}
`

Running command
`code-push release-react DTS-Android android -m` renders a new release in Staging

Then when i refresh my app in emulator i get the prompt telling me that an update is required when i press continue the restarts but no updates are visible

According to log it did says Update Installed but then after restart -> Update did not finish

MainApplication.java:
`protected List<ReactPackage> getPackages() {'
 return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new CodePush(BuildConfig.CODEPUSH_KEY,MainApplication.this, BuildConfig.DEBUG),
            new MapsPackage(),
            new VectorIconsPackage()
      );
    }`
build.gradle (keys replaced of course :)
`buildTypes {
        buildTypes {
            debug {
                buildConfigField "String", "CODEPUSH_KEY", '"myStagingKey"'
            }
            release {
                buildConfigField "String", "CODEPUSH_KEY", '"myProductionKey"'
                minifyEnabled enableProguardInReleaseBuilds
                proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
                signingConfig signingConfigs.release
            }
        }
    }`
* react-native-code-push version: 1.15.1-beta
* react-native version: 0.36.0
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? simulator
* Repro steps and/or stack trace:

11-16 19:38:27.035  2711  2991 I ReactNativeJS: Checking for updates.
11-16 19:38:30.926  2711  2991 I ReactNativeJS: Downloading package.
11-16 19:38:32.215  2711  2991 I ReactNativeJS: Installing update.
11-16 19:38:32.259  2711  2991 I ReactNativeJS: Update installed.
11-16 19:38:32.264  2711  2992 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.ericsson.dts/files/CodePush/91092a38511a708a786560002bb61d52144a526a655540afa1f56868cfc4c946/CodePush/index.android.bundle"
11-16 19:38:32.264  2711  2711 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.ericsson.dts/files/CodePush/91092a38511a708a786560002bb61d52144a526a655540afa1f56868cfc4c946/CodePush/index.android.bundle"
11-16 19:38:32.267  2711  2991 I ReactNativeJS: [CodePush] Restarting app
11-16 19:38:32.311  2711  2711 D ReactNative: [CodePush] Update did not finish loading the last time, rolling back to a previous version.
11-16 19:38:33.924  2711  3002 I ReactNativeJS: Running application "DTS" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
11-16 19:38:34.139  2711  3002 I ReactNativeJS: Checking for updates.
11-16 19:38:34.146  2711  3002 I ReactNativeJS: [CodePush] Reporting CodePush update rollback (v22)
11-16 19:38:35.115  2711  3002 I ReactNativeJS: [CodePush] An update is available, but it is being ignored due to having been previously rolled back.
11-16 19:38:35.115  2711  3002 I ReactNativeJS: Installing update.

**Comment by tobiaskiel** [comment]
Installed the relese apk on the emulator now the logfile looks a bit different and the app crashes after update being installed and app restarted 

11-16 20:08:43.787  3391  3391 D ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
11-16 20:08:44.990  3391  3408 I ReactNativeJS: Running application "DTS" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
11-16 20:08:45.564  3391  3408 I ReactNativeJS: [CodePush] Checking for update.
11-16 20:08:45.567  3391  3408 I ReactNativeJS: [CodePush] Reporting binary update (2.0.2)
11-16 20:08:47.389  3391  3408 I ReactNativeJS: [CodePush] Awaiting user action.
11-16 20:08:50.653  3391  3408 I ReactNativeJS: [CodePush] Downloading package.
11-16 20:08:51.829  3391  3408 I ReactNativeJS: [CodePush] Installing update.
11-16 20:08:51.868  3391  3391 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.ericsson.dts/files/CodePush/97025bd727fede3db3cdbefbea41cee5315cd77d463ac9cd6e467315dc45614e/CodePush/index.android.bundle"
11-16 20:08:51.872  3391  3409 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.ericsson.dts/files/CodePush/97025bd727fede3db3cdbefbea41cee5315cd77d463ac9cd6e467315dc45614e/CodePush/index.android.bundle"
11-16 20:08:51.872  3391  3408 I ReactNativeJS: [CodePush] Restarting app
11-16 20:08:51.953  3391  3391 D ReactNative: [CodePush] Update did not finish loading the last time, rolling back to a previous version.
--------- beginning of crash
11-16 20:09:11.213  3449  3449 D ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
11-16 20:09:12.108  3449  3466 I ReactNativeJS: Running application "DTS" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
11-16 20:09:12.341  3449  3466 I ReactNativeJS: [CodePush] Checking for update.
11-16 20:09:13.430  3449  3466 I ReactNativeJS: [CodePush] An update is available, but it is being ignored due to having been previously rolled back.
11-16 20:09:13.430  3449  3466 I ReactNativeJS: [CodePush] App is up to date.
11-16 20:10:01.053  3491  3491 D ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"

**Comment by silhouettes** [comment]
Hi @tobiaskiel, thanks for this detailed issue. `react-native-code-push@1.15.1-beta` is not actually compatible with `react-native@0.36.0` - we recommend upgrading to `react-native-code-push@1.16.0-beta` ([release notes](https://github.com/Microsoft/react-native-code-push/releases/tag/v1.16.0-beta)), which was recently released.

We try and keep our compatibility list up-to-date on our [README](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms), but I understand that it's not always obvious where to look. In future we will try to solve breaking issues earlier so that we can guarantee that the latest CodePush release is always compatible with the latest React Native release.

As a side note, I'm also assuming that you've wrapped your root component as described in the [Plugin Usage](https://github.com/Microsoft/react-native-code-push#plugin-usage), with a `checkFrequency` of `MANUAL`. If this step is skipped, it would also cause rollbacks.

Does this solve the problem for you?

**Comment by tobiaskiel** [comment]
Thank you for a very quick response. I will try your suggestion//changes first thing tomorrow!

**Comment by tobiaskiel** [comment]
Hi @silhouettes ! I can confirm that updating to `react-native-code-push@1.16.0-beta` for `react-native@0.36.0`  did solve my problem! 

11-17 07:04:29.350  3586  3615 I ReactNativeJS: [CodePush] Checking for update.
11-17 07:04:29.353  3586  3615 I ReactNativeJS: [CodePush] Reporting binary update (2.0.2)
11-17 07:04:30.557  3586  3615 I ReactNativeJS: [CodePush] Awaiting user action.
11-17 07:04:32.928  3586  3615 I ReactNativeJS: [CodePush] Downloading package.
11-17 07:04:33.874  3586  3615 I ReactNativeJS: [CodePush] Installing update.
11-17 07:04:33.943  3586  3616 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/com.ericsson.dts/files/CodePush/8a163b53f4694818a8cc724310cb06dece37c06cd0c8986614c74fea725a1f31/CodePush/index.android.bundle"
11-17 07:04:33.947  3586  3615 I ReactNativeJS: [CodePush] Restarting app
11-17 07:04:34.580  3586  3638 I ReactNativeJS: Running application "DTS" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
11-17 07:04:34.760  3586  3638 I ReactNativeJS: [CodePush] Checking for update.
11-17 07:04:34.764  3586  3638 I ReactNativeJS: [CodePush] Reporting CodePush update success (v25)
11-17 07:04:35.088  3586  3638 I ReactNativeJS: [CodePush] App is up to date.

**Comment by silhouettes** [comment]
I am glad that helped! Going to close this issue now, but feel free to come back if you have any other issues!
