### ISSUE TITLE
Android app crashes after downloading update

### ISSUE THREAD

**Issue by chetstone** [Microsoft/react-native-code-push#612]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version: 1.14.6-beta
* react-native version: 0.32.1
* iOS/Android/Windows version: Samsung Galaxy S5 SM-G900T - 6.0.1
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? physical
* Repro steps and/or stack trace:

Logging output:
```
11-17 11:26:38.811 17539 17539 D ReactNative: [CodePush] Loading JS bundle from "assets://index.android.bundle"
11-17 11:26:39.931 17539 17576 I ReactNativeJS: Running application "MalaMode" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
11-17 11:26:40.401 17539 17576 I ReactNativeJS: [CodePush] Checking for update.
11-17 11:26:40.401 17539 17576 I ReactNativeJS: [CodePush] Reporting binary update (1.5.7)
11-17 11:26:40.951 17539 17576 I ReactNativeJS: [CodePush] Downloading package.
11-17 11:26:41.771 17539 17576 I ReactNativeJS: [CodePush] Installing update.
11-17 11:26:41.801 17539 17576 I ReactNativeJS: [CodePush] Update is installed and will be run on the next app restart.
```
Then the app crashes. The update runs fine when the app is restarted.

Note that I'm using the legacy method of starting codepush. Could this be the problem? In my index.android.js file I have:
```
  componentDidMount: function() {
    lifecycle("MalaMode componentDidMount");
    if (!__DEV__) {
      codePush.sync().then((status) => {
        //get version
        codePush.getUpdateMetadata().then((update) => {
          MiscActions.codePushRelease(update);
        });

        // Check to see if there is still an update pending.
        codePush.getUpdateMetadata(codePush.UpdateState.PENDING).then((update) => {
          MiscActions.codePushPending(update);
        });

      });
    }
  },

```
(The more info the faster we will be able to address it!)

**Comment by chetstone** [comment]
Just tried taking out the `!__DEV__` in the above code so codepush would run in the debug build. It also crashes after downloading the update. Then, weirdly, on restart it claims it is using the update bundle but it is not.
```
11-17 11:51:09.761 22582 22582 D ReactNative: [CodePush] Loading JS bundle from "/data/user/0/io.malamode.debug/files/CodePush/5b0bc4dfaeb43a8ed77cd0c98c98861f49536fef992ab38eada7b7e0fd578218/CodePush/index.android.bundle"
11-17 11:51:11.181 22582 22624 I ReactNativeJS: Running application "MalaMode" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
11-17 11:51:12.601 22582 22624 I ReactNativeJS: [CodePush] Checking for update.
11-17 11:51:13.401 22582 22624 I ReactNativeJS: [CodePush] App is up to date.
```
I know it's using not using the update bundle because `__DEV__` is `false` in the update bundle, and  the update's features are not there.

**Comment by silhouettes** [comment]
@chetstone For the behavior in the debug build, I wouldn't worry as your app is likely still loading from the packager (React Native coerces it into doing so). A lot of our users don't test CodePush in debug, but if you'd like to do so there are some more details in #153 and a workaround in #438.

I believe that the crash that you're seeing happens when `codePush.getUpdateMetadata()` is called in a specific situation, and can be fixed by upgrading to the latest `react-native-code-push` (`1.16.0-beta`). If you'd like more details, the bug is #515, which was fixed in `react-native-code-push@1.15.0-beta` ([release notes](https://github.com/Microsoft/react-native-code-push/releases/tag/v1.15.0-beta)).

Please let me know if that solves the problem for you!

**Comment by chetstone** [comment]
Thanks! I'm on react-native 0.32.1. Do I have to upgrade react-native to
use newer versions of RN code-push?

**Comment by chetstone** [comment]
Oh and by the way, I agree with most of your users who don't test CodePush in debug, because it seems like a very tricky thing to do. But your instructions on [Multi-Deployment Testing](https://github.com/Microsoft/react-native-code-push#android) seem to suggest that that's the way to do it. I think it would be better to have separate Debug, Staging and Release builds the way you have described the setup for iOS. Do you agree?

**Comment by silhouettes** [comment]
@chetstone - You shouldn't need to upgrade React Native, it should just work. To keep your mind at ease, we try to keep our compatibility table up to date [here](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms). Please let me know how that goes!

And yes, thank you for the feedback about debug builds. We'll try and go through everything again and figure out the setup that makes the most sense, although it might be a week or two.

**Comment by chetstone** [comment]
@silhouettes Thanks a lot. Upgrading to 1.16.0-beta fixed the crashing problem.

Looking forward to updates on android configuration.

**Comment by ssomnoremac** [comment]
I'm on 1.16.1-beta. Still crashing on reboot on Release Android build. Got some error on Android when debugging that was `undefined is not a function t.something` but didn't keep it because i read this thread. Should I dig that error up?
