### ISSUE TITLE
Question for InstallMode

### ISSUE THREAD

**Issue by brettpappas** [Microsoft/react-native-code-push#613]
Is there a way to use both InstallMode.ON_NEXT_RESUME and InstallMode.ON_NEXT_RESTART?

We would like to get updates out to users quicker without interrupting their use of the app like IMMEDIATE does.

The problem I see with ON_NEXT_RESUME is that if someone only uses the app once in a while, then the app could potentially never "resume" if the OS is always removing it from memory between each time it gets launched (and therefore triggering the ON_NEXT_RESTART instead).

Ideally we could specify both InstallModes or make it so ON_NEXT_RESUME fires for both events.

**Comment by vonovak** [comment]
quoting the docs:

1) *Silent sync on app start (the simplest, default behavior)*. Your app will automatically download available updates, and apply them the next time the app *restarts*

2) Silent sync every time the app resumes. *Same as 1*, except we check for updates, or apply an update if one exists every time the app returns to the foreground after being "backgrounded".

therefore ON_NEXT_RESUME fires both events and you're good to use it ;)

**Comment by brettpappas** [comment]
This is actually not what I have found to be true. The docs you referenced are not for InstallMode, they refer to the sync process that checks for updates.

My testing seemed to show that the "sync" option for ON_NEXT_RESUME only checked when the app "returned" from background to foreground NOT when the app started initially. This scenario is only triggered when ON_NEXT_RESTART is set.

**Comment by vladimir-kotikov** [comment]
> My testing seemed to show that the "sync" option for ON_NEXT_RESUME only checked when the app "returned" from background to foreground NOT when the app started initially

That's true, the check is performed only in resume handler, but this doesn't cancel the fact that at next startup app will read bundle url and start with the bundle from last update even if you have specified `InstallMode.ON_NEXT_RESUME` previously.

**Comment by panarasi** [comment]
@brettpappas Was your question answered ? Closing the issue since there is no other action item. Please re-open the issue if you still have the question and we can help you.
