### ISSUE TITLE
my android app is not updating

### ISSUE THREAD

**Issue by gmchaturvedi1** [Microsoft/react-native-code-push#616]
I had followed the steps of react-native-code-push steps but my react-native app is not updating.

when i run the command  codepush release-react go4edu android ,its successfully showed that updates is uploaded but in my it not coming i have put this in my root component likethe following:

componentDidMount(){
    codePush.sync({ updateDialog: true, installMode: codePush.InstallMode.IMMEDIATE})
  }

**Comment by buptkang** [comment]
@gmchaturvedi1 could you share your main js file or give me more in detailed information?

**Comment by gmchaturvedi1** [comment]
sorry i am late replying. it is solved .
