### ISSUE TITLE
The UI freeze after releasing a new version via codepush.

### ISSUE THREAD

**Issue by skeie** [Microsoft/react-native-code-push#621]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

Hi, I've just integrated codepush to my project. When I release a new version through code push and the new version is loaded, the whole app freezes. And I get this error in the console: 

W/unknown:React: Calling JS function after bridge has been destroyed.

If I restart the app, everything works. 

* react-native-code-push version: 1.12.6-beta
* react-native version: 0.27.2
* iOS/Android/Windows version: Android 6.01
* Does this reproduce on a debug build or release build?  Both debug build and release build
* Does this reproduce on a simulator, or only on a physical device?  physical device
* Repro steps and/or stack trace:
I can provide a repo if necessary for you guys. Since its quite and old react-native version it will take some time to set it up.

(The more info the faster we will be able to address it!)

**Comment by vonovak** [comment]
check out supported versions

v0.19-v0.28	v1.7.0+ (introduced Android asset support)

**Comment by skeie** [comment]
Aha, sorry! Thanks 👍
