### ISSUE TITLE
[Windows] Unable to build with code-push

### ISSUE THREAD

**Issue by Milkdog** [Microsoft/react-native-code-push#625]
I've followed the React Native Windows/UWP directions closely, and started from scratch multiple times to make sure I was following them properly. I even tried re-installing Visual Studio and the Windows 10 SDK v10.0.10586.212. When trying to build my solution in Visual Studio 2015 (and 2017 RC), I get the following error. If I continue past the error, it just closes my app out.

* react-native-code-push version: 1.16.0-beta
* react-native version: 0.38.0
* iOS/Android/Windows version: 0.38.0
* Does this reproduce on a debug build or release build? Debug. There was a similar, but different error with release
* Does this reproduce on a simulator, or only on a physical device? UWP Native App on Desktop
* Repro steps and/or stack trace: Build with Debug x86

![Imgur](http://i.imgur.com/ZrrzRxb.png)

**Comment by Milkdog** [comment]
I tried hacking things to much. Eventually I got to the root of my problem, and it was that I need to use DebugBundle/ReleaseBundle to use code-push. And even more importantly, I need to build a bundle file before building the app using the commands in `ReactAssests/index.windows.bundle`

**Comment by silhouettes** [comment]
Thanks so much for the update @Milkdog, this is helpful!
