### ISSUE TITLE
Text files diff

### ISSUE THREAD

**Issue by lisong** [Microsoft/react-native-code-push#626]
Do you have plan to use `google-diff-match-patch`  calculate Text file diff and merge ?

**Comment by silhouettes** [comment]
Hi @lisong, not currently. We currently do a file-based diff (replace each file that has changed, but keep the files that have not changed). This makes sense to me, because most of the size of an app is likely to come from assets, like images and video. Is there any reason you think we should do a text-based diff?

**Comment by lisong** [comment]
thanks for reply! sometimes you just fix a bug. maybe just a condition and react-native-cli has not split js bundles files, when app contains many business. jsbundles is really very big. it a expensive network. maybe google-diff-match-patch is a choices.

**Comment by panarasi** [comment]
@lisong Thanks for the input. We have added this idea as something we would explore for the next version of Code Push. I am closing this issue here since it has been copied to our backlog.

**Comment by thecachedbyte** [comment]
Any update on this? It will be awesome if we can achieve text-based diff patching. Downloading jsbundle of 1 or 2 mb on 2g or 3g network in country like India is a costly affair.

**Comment by karthikmit** [comment]
I second @thecachedbyte, as it is a very important requirement for lite apps designed for low bandwidth constraints.

**Comment by zjx** [comment]
agree with @thecachedbyte, using google-diff-match-patch will significantly reduce the potential expensive costs may charge to end users.
