### ISSUE TITLE
update fail with rollback

### ISSUE THREAD

**Issue by mobohua** [Microsoft/react-native-code-push#628]
i have success deployed to the server,but it is always rollback when i update version,
i write my code and error log in following
(android platform)

react version:
"react": "15.4.0",
"react-native": "0.38.0",
"react-native-code-push": "1.16.0-beta"

js code:
componentDidMount() {
                CodePush.sync({
                    deploymentKey: this.props.code_push_key,
                    updateDialog: {
                        appendReleaseDescription:true,
                        title: 'update'
                    },
                    installMode: CodePush.InstallMode.IMMEDIATE
                });
    }

log:
 [CodePush] Checking for update.
 [CodePush] Awaiting user action.
 [CodePush] Downloading package.
 [CodePush] Installing update.
 [CodePush] Loading JS bundle from "/data/data/com.boowa.codepushtest/files/CodePush/a548397ec2b523cb9b7d31c261a76d169b83f9a47c1150551888afe7cd94fbb6/bundles/index.android.bundle"
[CodePush] Loading JS bundle from "/data/data/com.boowa.codepushtest/files/CodePush/a548397ec2b523cb9b7d31c261a76d169b83f9a47c1150551888afe7cd94fbb6/bundles/index.android.bundle"
 [CodePush] Update did not finish loading the last time, rolling back to a previous version.
 [CodePush] Restarting app
[CodePush] Loading JS bundle from "assets://index.android.bundle"

please,can anyone help me how to fix it?

**Comment by silhouettes** [comment]
Hi @mobohua, can you show us your `MainApplication.java` file?

**Comment by mobohua** [comment]
thank you for your answer @silhouettes ,i had found my fault,in activity,i forget to add a part of code as follow:
 CodePush.setReactInstanceHolder(new ReactInstanceHolder() {
            @Override
            public ReactInstanceManager getReactInstanceManager() {
                return mReactInstanceManager;
            }
        });

**Comment by silhouettes** [comment]
Thanks so much for the update @mobohua, as your problem is solved I'm going to close this now but feel free to come back with any other issues!
