### ISSUE TITLE
Android can't assign build.gradle path

### ISSUE THREAD

**Issue by kevinTutu** [Microsoft/react-native-code-push#641]
I encount a problem , when I assign the Android build.gradle path ,but he tell me 'no such file or directory',but I confim the build.gradle path is correct .The IOS can run normally . The logcat as follow:
![](http://oi3r347z2.bkt.clouddn.com/QQ20161213-1@2x.png)

**Comment by matrosov-nikita** [comment]
Hi @kevinTutu 

Option `-p` is for `.plist` files. You probably need a `-g` option:

`code-push release-react XhcClient-android android -g ~xhc_android/redlips/build.gradle`

Please see `code-push release-react --help` for more details

**Comment by kevinTutu** [comment]
Thank you , you are correct. But in the CLI docs shows -p,as follow:
Later,I find the answer in the command-parser file . Thank you anyway!

原始邮件
发件人:Nikita Matrosovnotifications@github.com
收件人:Microsoft/react-native-code-pushreact-native-code-push@noreply.github.com
抄送:kevinTutuwangzihang@xiaohongchun.com; Mentionmention@noreply.github.com
发送时间:2016年12月14日(周三) 17:04
主题:Re: [Microsoft/react-native-code-push] Android can't assignbuild.gradle path (#641)


Hi @kevinTutu
Option -p is for .plist files. You probably need a -g option:
code-push release-react XhcClient-android android -g ~xhc_android/redlips/build.gradle
Please see code-push release-react --help for more details

**Comment by kevinTutu** [comment]
Thank you !  The CLI docs example is wrong, I found the answer in the command-parser file .Thanks !
