### ISSUE TITLE
The CodePush module doesn't appear to be properly installed

### ISSUE THREAD

**Issue by MyGuySi** [Microsoft/react-native-code-push#642]
* react-native-code-push version: 1.16.1-beta
* react-native version: 0.39.2
* iOS version: 10.1

Hi, I'm trying to integrate CodePush but having some trouble with the above error message when logging iOS. I'm running in the simulator, the iOS app builds fine with no errors.

I first noticed it when trying the usage code like this:

```
import React, { Component } from 'react';
const codePush = require('react-native-code-push');

import ContractorNavigator from './navigation/ContractorNavigator';

class App extends Component {
  render() {
    return (
      <ContractorNavigator />
    );
  }
}

export default codePush(App);
```

but I was getting:

`codePush is not a function. (In 'codePush(App)', 'codePush' is undefined)`

I followed the Getting Started guide and used `react-native link`. I've since gone through the manual instructions to verify that everything was linked as it should have been and it looks fine to me.

Any help would be appreciated, thanks.

**Comment by vladimir-kotikov** [comment]
@MyGuySi, where are you seeing this error? Could you please also check if there is anything suspicious is logged to console, as explained here: [Accessing console logs](https://facebook.github.io/react-native/docs/debugging.html#accessing-console-logs)

Have you tried to debug the app using [Chrome debugger](https://facebook.github.io/react-native/docs/debugging.html#debugging-on-a-device-with-chrome-developer-tools)?

**Comment by MyGuySi** [comment]
@vladimir-kotikov I'm really sorry, it appears to be working correctly now. I simply removed the code while I was working on something else now that I've come back and tried it again, its working fine.

My apologies, it must have been some caching issue, though I cleaned the iOS project, reset the React Native Packager cache and rebuilt everything. Weird..

**Comment by vladimir-kotikov** [comment]
Okay, thanks for letting us know
