### ISSUE TITLE
Android permissions - READ_PHONE_STATE

### ISSUE THREAD

**Issue by giladartzi** [Microsoft/react-native-code-push#649]
Hello,

In the `react-native-code-push` project's AndroidManifest.xml file, the required permissions are:
```
<android:uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<android:uses-permission android:name="android.permission.READ_PHONE_STATE" />
<android:uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

The `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` are probably needed in order to read and write the JavaScript bundle, which is understandable.

My question is, why is `READ_PHONE_STATE` required? This permission is quite scary for end users, especially on applications which do not have anything to do with phones calls.

In case it's not needed, can it be removed?

Thanks

**Comment by vladimir-kotikov** [comment]
@giladartzi, I'm not sure if these permissions come from react-native-code-push? A [quick search](https://github.com/Microsoft/react-native-code-push/search?q=READ_PHONE_STATE+WRITE_EXTERNAL_STORAGE+READ_EXTERNAL_STORAGE&type=Code&utf8=%E2%9C%93) in codebase shows no matches. Is it possible that you have another RN package that  adds these permissions?

**Comment by goldylucks** [comment]
@giladartzi those permissions are (wrongfully) built into react-native at the moment. Maybe that's y u r seeing them?

refer to [this](https://github.com/facebook/react-native/issues/5886) issue on the react-native repo.

the quick fix is adding the following to `AndroidManifest.xml`
```xml
    <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" tools:node="remove" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove" />
```

**Comment by vladimir-kotikov** [comment]
@goldylucks, thanks for the info and workaround! Closing this
