### ISSUE TITLE
getBinaryResourcesModifiedTime always returns the same time on Android

### ISSUE THREAD

**Issue by jacob-meacham** [Microsoft/react-native-code-push#650]
* react-native-code-push version: 1.16.0-beta
* react-native version: 0.36.0
* iOS/Android/Windows version: Android 6.0.1, API 23, gradle 2.14.1

The timestamp returned in getBinaryResourcesModifiedTime() always returns 312796800000 (11/30/1979, 12:00:00 AM). This is expected as per https://code.google.com/p/android/issues/detail?id=220039. The workaround to set android.keepTimestampsInApk = true is an ok one, but in a default project, the binary version is never loaded once a codepush bundle has been installed.

I'm happy to cook up a PR to fix this issue, but I am not primarily an android dev and wanted to get some feedback on an appropriate fix. My initial proposal is to set a buildConfigField in codepush.gradle, and then check that at runtime.

Thanks!

**Comment by vladimir-kotikov** [comment]
Looks like this is exactly the same problem as with cordova plugin here: https://github.com/Microsoft/cordova-plugin-code-push/issues/196

**Comment by matrosov-nikita** [comment]
Hi @jacob-meacham 

Yeah, I see the timestamp within update and built apk time are equal, but there is [additional check](https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePush.java#L187) for binary versions equality. Even though the timestamps are the same, after build step plugin cleans out current local package (if you bump version) and anyway downloads new updates. Could you provide specific case which demonstrates your problem?

**Comment by jacob-meacham** [comment]
@matrosov-nikita yeah, on debug builds right now we're not bumping version appropriately. We should definitely fix that on our side, but it's why I noticed this issue. If the code is just dead, maybe the better solution is just to remove it?

**Comment by matrosov-nikita** [comment]
@jacob-meacham, I've sent the PR. It uses `buildConfigField` to get correct apk built time as you've already suggested. Could you pls check whether it works for you?

**Comment by jacob-meacham** [comment]
This is similar to the hacked fix I had been using and works for me. Thanks!
