### ISSUE TITLE
Can multiple lib project use code-push in one app？

### ISSUE THREAD

**Issue by JuanbingTeam** [Microsoft/react-native-code-push#653]
My app project includes several library projects, for example, UserCenterLib\AdLib.
For now, just use RN in UserCenterLib, but I'd like to use RN in both library in future.
(Both UserCenter and Ad contain a different react project submodule).
Will CodePush generate CodePushHash.json in both library?
If so, how to deal with the resource file conflict?

**Comment by panarasi** [comment]
@JuanbingTeam Could you help us understand the use case better please ? Is your project a native project where you try to include React Native twice ? Is there a sample repo that you could share to help us understand this case better ?

**Comment by panarasi** [comment]
@JuanbingTeam Wanted to ping you see if you have more information on this.

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen if you have any questions.

**Comment by JuanbingTeam** [comment]
@panarasi  Sorry for the late late late response...

In short, I have multiple modules in my app. I 'd like to generate one bundle file for each module.
For example:  module1.android.bundle, module2.android.bundle, module3.android.bundle...

Now, in my res folder , I have multiple .bundle and .meta files but only one CodePushHash file.
module1.android.bundle
module1.android.bundle.meta
module2.android.bundle
module2.android.bundle.meta
module3.android.bundle
module3.android.bundle.meta
...
CodePushHash (CodePushHash.json for old version)

So, My conclusion is CodePush can ONLY manage one JS bundle...
Unless adding a new API  to config hash file for each bundle...

**Comment by JuanbingTeam** [comment]
My project is a huge project. There are several RN entrance. 
Each entrance can config its own ReackPackages (CodePush).

**Comment by yellowChao** [comment]
@JuanbingTeam  无fuck说

**Comment by ooyo-tech** [comment]
@JuanbingTeam  any updates on this?

**Comment by The-Pascal** [comment]
I faced the same problem with CodePush, that it is able to manage one js bundle only, so I dug out and made some changes to the native Android code of CodePush.

So, now with these changes, CodePush can manage multiple JS bundles in the same application.

I have published an article on the same - https://medium.com/@chaharchandresh/multiple-codepush-in-same-application-5e3f57a9ae0b

And also published an npm library for it- https://www.npmjs.com/package/@the-pascal/react-native-code-push

Please feel free to use it and provide any suggestions you might have.
