### ISSUE TITLE
codePush.checkoutUpdate() return onRejected

### ISSUE THREAD

**Issue by YongHuiLuo** [Microsoft/react-native-code-push#655]
* react-native-code-push version: 1.12.6-beta
* react-native version: 0.37.0
* iOS/Android/Windows version:  Android
* Does this reproduce on a debug build or release build :  release build
* Does this reproduce on a simulator, or only on a physical device :  only on a physical device

```
componentDidMount() {
            console.log("tiny componentDidMount");
            codePush.checkForUpdate().then((update) => {
                    if (!update) {
                        console.log("tiny app是最新版本");
                    } else {
                        console.log("tiny 有更新哦");
                        codePush.sync();
                    }
                },() => {
                   console.log("tiny  checkoutFor Update error");
                }
            );
        }
```

Console output “ tiny  checkoutFor Update error” ，So checkForUpdate onRejected implementation of the method, what will lead to this situation?

thanks

**Comment by vladimir-kotikov** [comment]
@YongHuiLuo, it's really hard to say what exactly caused the error in your case. You might want to try logging an error in rejection handler to get more details:

```js
codePush.checkForUpdate().then((update) => {
      ...
    },(error) => {
       console.log("tiny  checkoutFor Update error");
       console.error(error, error.message && error.message)
    }
);``

**Comment by YongHuiLuo** [comment]
@vladimir-kotikov   thank you very much，I did not do any code changes, but the problem did not reoccurrence, I guess is a network problem, due to the instability of the network environment.

**Comment by vladimir-kotikov** [comment]
Thanks for update. I'll close this - feel free to reopen if necessary.

**Comment by marlti7** [comment]
same problem
