### ISSUE TITLE
Variable spelling mistakes

### ISSUE THREAD

**Issue by EngsShi** [Microsoft/react-native-code-push#657]
[CodePushConfig.m](https://github.com/Microsoft/react-native-code-push/blob/bb04535fbef4cb580da4c29ae628452cc0774fc8/ios/CodePush/CodePushConfig.m#L11)  have a spelling mistakes. "BuildV**d**ersionConfigKey" => "BuildVersionConfigKey"

* react-native-code-push version: 1.16.1-beta

**Comment by vladimir-kotikov** [comment]
@EngsShi, thanks, updated this in #659
