### ISSUE TITLE
code-push [error] permission denied, mkdir '/Users'

### ISSUE THREAD

**Issue by kevinTutu** [Microsoft/react-native-code-push#658]
when I plan to code-push , I use the command like this:
![](http://image.xiaohongchun.com.cn/QQ20161228-0@2x.png)

But I get the reply like this:

![](http://image.xiaohongchun.com.cn/QQ20161228-1@2x.png)

I don't know the reason about this,who has the same problem?

**Comment by vladimir-kotikov** [comment]
@kevinTutu, thanks for reporting this!

The error message is pretty uninformative and it's hard to determine, where the error occured. Could you please add a `console.log(error.stack)` line right after `console.error(chalk.red("[Error]  " + error.message));` in `code-push` main module - you can locate it by running `which code-push` - and then run command again. This would show where the error comes from.

**Comment by kevinTutu** [comment]
I do as you tell me ,but I didn't get the effective information，just print --  'undefined',like this:
![](http://oi3r347z2.bkt.clouddn.com/QQ20161229-0.png)
and I add the console.log in command-executor file,like this:
![](http://oi3r347z2.bkt.clouddn.com/QQ20161229-0@2x.png)
I get the information like this:
![](http://oi3r347z2.bkt.clouddn.com/QQ20161229-1.png)

**Comment by vladimir-kotikov** [comment]
@kevinTutu, were you able to find the cause of this error?

**Comment by kevinTutu** [comment]
yes，we have use our code-push server ， the reason is out server problem，so sorry，I have thought code-push-cli problem，but is our problem


原始邮件
发件人:Vladimir Kotikovnotifications@github.com
收件人:Microsoft/react-native-code-pushreact-native-code-push@noreply.github.com
抄送:kevinTutuwangzihang@xiaohongchun.com; Mentionmention@noreply.github.com
发送时间:2017年1月5日(周四) 15:55
主题:Re: [Microsoft/react-native-code-push] code-push [error] permissiondenied, mkdir '/Users' (#658)


@kevinTutu, were you able to find the cause of this error?
