### ISSUE TITLE
CodePushDeploymentKey react-native link bug when using firebase

### ISSUE THREAD

**Issue by Yox2l** [Microsoft/react-native-code-push#661]
* react-native-code-push version:  1.16.1-beta
* react-native version: 0.39.2

I'm using firebase in my react-native app and therefore I have a **GoogleService-Info.plis**t in my project now when I run the "react-native link" command the **CodePushDeploymentKey** added to  **GoogleService-Info.plist** instead of the **Info.plist** file.

**Comment by axemclion** [comment]
Looks like it is due to this line - https://github.com/Microsoft/react-native-code-push/blob/master/scripts/postlink/ios/postlink.js#L52

We need to look for Info.plist, not *Info.plist. 


cc @vladimir-kotikov

**Comment by max-mironov** [comment]
Closed it for now as a pull request with fixes has been already merged.

**Comment by jordanmkoncz** [comment]
Has this fix made it into a release yet? I've just followed the CodePush setup instructions from scratch, with `"react-native-code-push": "^1.17.3-beta"` being installed, and I had this same issue happen.

**Comment by max-mironov** [comment]
@jordanmkoncz hello - yes, that fix should be present in recent [1.17.3 beta](url) version. 
If you still see the issue is it possible for you to open another ticket and fill as much details as possible [here](https://github.com/Microsoft/react-native-code-push/issues/new) and we will look at?

**Comment by jordanmkoncz** [comment]
@max-mironov Done :)
