### ISSUE TITLE
'CodePush.h' file not found

### ISSUE THREAD

**Issue by sergey-akhalkov** [Microsoft/react-native-code-push#662]
* react-native-code-push version: v1.16.1-beta
* react-native version: v0.40.0
* iOS/Android/Windows version: iOS
* Does this reproduce on a debug build or release build? all
* Does this reproduce on a simulator, or only on a physical device? all
* Repro steps and/or stack trace:
1. Execute `react-native init myapp`
2. Execute `cd myapp` then `npm install --save react-native-code-push@1.16.1-beta`
3. Execute `react-native link react-native-code-push`
4. Then after build and run `myapp` using xcode I've got following error:
![image](https://cloud.githubusercontent.com/assets/4928157/21715111/bca0ef60-d413-11e6-83af-d169ea9f37a0.png)

Seems like `react-native link react-native-code-push` command works wrong.
Created issue in react-native repo: https://github.com/facebook/react-native/issues/11747

**Comment by SamMatthewsIsACommonName** [comment]
@sergey-akhalkov I'm having the same issue, have you been able to fix it?

**Comment by sergey-akhalkov** [comment]
@SamMatthewsIsACommonName, hi! You could fix it by [installing CodePush plugin manually](https://github.com/Microsoft/react-native-code-push#plugin-installation-ios---manual) (look at pt.6).
I assume the issue will be fixed soon by React Native team so we wouldn't have to fix it manually.

**Comment by SamMatthewsIsACommonName** [comment]
Hi @sergey-akhalkov I ended up using an earlier version of React Native and worked fine. Cheers!

**Comment by anhtuank7c** [comment]
I have same problem with RN 0.40.0, RN-cli 2.0.1
```

/Users/anhtuank7c/Projects/reactnative/Clock/ios/Clock/AppDelegate.m:11:9: fatal error: 'CodePush.h' file not found
#import "CodePush.h"
        ^
1 error generated.


** BUILD FAILED **
```

**Comment by 2ducanhpham** [comment]
Thanks @anhtuank7c

**Comment by fabriziogiordano** [comment]
I am having the same issue.

```
  "dependencies": {
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.4",
    "react-native-code-push": "^4.1.0-beta"
  },
```

![screenshot 2017-07-21 10 29 06](https://user-images.githubusercontent.com/109390/28467995-a71af6e6-6dff-11e7-9930-44a3f6f8f3c8.png)

It was working then all of the sudden.. stop working. It is frustrating. Is there something I should do?

**Comment by ujwal-setlur** [comment]
Check the Header Search Paths under each target. For me, it was 
```
$(SRCROOT)/../node_modules/react-native-code-push/ios/CodePush
```

It should have been
```
$(SRCROOT)/../node_modules/react-native-code-push/ios
```

**Comment by mcrowe** [comment]
Running `react-native link react-native-code-push` currently adds an incorrect header search path as @ujwal-setlur witnessed. If you have run that command, you will need to:

1) Follow the instructions under [Manual Plugin Installation](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---manual)

2) Change the Header Search Paths entry for code-push to `$(SRCROOT)/../node_modules/react-native-code-push/ios`

**Comment by SamiChab** [comment]
For me `react-native link` solved it

**Comment by jackmead515** [comment]
This was the output I got related to CodePush when I did `react-native link`:

`rnpm-install info Android module react-native-code-push is already linked 
rnpm-install info iOS module react-native-code-push is already linked 
"CodePush.h" header already imported.
"jsCodeLocation" already pointing to "[CodePush bundleURL]".
Could not determine correct xcode proj path to retrieve related plist file, there are multiple xcodeproj under the solution.
"CodePushDeploymentKey" already specified in the plist file.
"getJSBundleFile" is already overridden
"codepush.gradle" is already linked in the build definition`

**Comment by dzotos** [comment]
Manual configuration worked for me.

**Comment by baskan** [comment]
correct header search path is now: 
`$(SRCROOT)/../node_modules/react-native-code-push/ios/CodePush`

**Comment by rdewolff** [comment]
Had to do what you advised @mcrowe to get it running. Thanks for sharing the solution!

**Comment by basha777** [comment]
After `npm install react-native-code-push` running` pod install `inside ios directory fixed my issue.

**Comment by vitozyf** [comment]
> Check the Header Search Paths under each target. For me, it was
> 
> ```
> $(SRCROOT)/../node_modules/react-native-code-push/ios/CodePush
> ```
> 
> It should have been
> 
> ```
> $(SRCROOT)/../node_modules/react-native-code-push/ios
> ```

It works for me

**Comment by PritchardAlexander** [comment]
Happened to me today with a fresh install of NPM v12.6.0 via NVM and following the instructions using react-native-link here: https://docs.microsoft.com/en-us/appcenter/distribution/codepush/react-native#getting-started

The Library import of CodePush and library binary libz.tbd linking had not been done, but the code transform of return [CodePush bundleURL]; had been done, as well as the Info.plist updates.

**Comment by plaporte** [comment]
@vitozyf Could you give a quick run down on how exactly you update this? I'm not sure what to do.

**Comment by mhsfh** [comment]
i faced a similar issue, and fortunately, i could fix it 

```json
"react-native": "0.72.4",
"react-native-code-push": "^8.2.1"
```

you need just to add `  pod 'CodePush', :path => '../node_modules/react-native-code-push'` as follow in `ios/Podfile`

```
target 'YourApp' do
  config = use_native_modules!
 pod 'FirebaseCore', :modular_headers => true
 pod 'CodePush', :path => '../node_modules/react-native-code-push'
 ...
```
