### ISSUE TITLE
Better docs for staging usage

### ISSUE THREAD

**Issue by goldylucks** [Microsoft/react-native-code-push#667]
I'm trying to figure out what use there is for the staging release. According to the docs, it's default to the debug build.

but the debug build only works if there's an active package manager in the background, and if I'm doing that, I already have the changes on my device since I'm actively developing on it.

I was thinking that I should publish a second app to the stores, called something like "My App (staging)" and it will be unlisted.

Then I download that app on my phone, and code-pushify changes to staging, test it on the staging version, and only then promote the changes to production version.

Am I missing something?
and if not, I could prepare a PR with better docs about that matter :)

**Comment by vonovak** [comment]
related #614

**Comment by sergey-akhalkov** [comment]
@goldylucks - hi! I suppose you are right, I've added https://github.com/Microsoft/react-native-code-push/issues/614#issuecomment-274051514 describing the same things...
>and if not, I could prepare a PR with better docs about that matter :)
I would be very grateful if you could update the docs, thank you!

**Comment by panarasi** [comment]
I think we should close this since #614 already captures the issue. 

@goldylucks If you think #614 does not cover your concern, please let us know and we can reopen the bug.
