### ISSUE TITLE
RN 40 support

### ISSUE THREAD

**Issue by chirag04** [Microsoft/react-native-code-push#668]
RN version .40 is already published with a major breaking change. Can we update the example app and docs to support RN 40.

**Comment by sergey-akhalkov** [comment]
@chirag04 - hi!
There are two PRs, #665 and #638 are waiting to be merged and released. Hoping this will happen soon.

**Comment by grabbou** [comment]
As already noted in the react-native repo, from the `link` perspective, it doesn't really matter. Just to say that #665 is not currently supported by the `react-native link` and so, using it will add headers to search paths anyway. If we decide to merge it, we need to release support for that with react-native at the same time.

Happy to consider, just need to release the fix in first place.

**Comment by JusticeLai** [comment]
![image](https://cloud.githubusercontent.com/assets/13083749/21881738/806bda40-d8e2-11e6-85b9-ffb3f3f18cb8.png)

iPhone 6s Plus  Release  Error
iPhone 6s Plus  Debug  is ok

**Comment by sergey-akhalkov** [comment]
@grabbou, got it, thanks!
It would be great to support #665 due to benefits you've described in  https://github.com/facebook/react-native/issues/11747#issuecomment-271989016.
> That approach seems better as it doesn't pollute global namespace and reduces one more step when user links "manually".

So after releasing `react-native link ...` updates we would merge #655 and update the `react-native-code-push` documentation.

**Comment by sergey-akhalkov** [comment]
@JusticeLai - hi!
I've got the same issue using initial `react-native` app, so I've created https://github.com/facebook/react-native/issues/11861

**Comment by grabbou** [comment]
I'll then ship two things now, 1) the fix 2) that new features. Will update this issue accordingly.

**Comment by grabbou** [comment]
Fix has shipped here https://github.com/facebook/react-native/commit/545072b02d94e264a66987a5cebc15629a16f188. Watch out for a new release to land today or tomorrow

**Comment by sergey-akhalkov** [comment]
@grabbou, got it, thanks!

**Comment by JusticeLai** [comment]
@sergey-akhalkov 
![image](https://cloud.githubusercontent.com/assets/13083749/21954882/1d15e2a2-da99-11e6-9c6e-f80716a16d82.png) still  same error,

Have you solved it?

**Comment by stirman** [comment]
@grabbou any update on the next release with .40 support? Thx!

**Comment by sergey-akhalkov** [comment]
@JusticeLai, I've applied this https://github.com/facebook/react-native/pull/11889/files changes and got `build success` in `release` mode.

**Comment by ezyone123** [comment]
I have tried all the above suggestions and have been able to building in release and debug mode. My issue is my staging build config in Xcode, it still complains about React/RCTBridge.h not found. My staging build configuration is a copy of production. I am not sure if this is a code push issue or a react native/my setup issue. I am just confused as to why release mode works but not staging when its just a copy of release. Any thoughts would be much appreciated. P.S. Staging build config worked before updating to react 0.40 from 0.38

**Comment by JusticeLai** [comment]
@sergey-akhalkov thanks ,build success...

**Comment by slicejunk** [comment]
@ezyone123 
in case it may help for build process:
add 
```$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)/include ```
to Xcode Build Settings / HEADER_SEARCH_PATHS

**Comment by buptkang** [comment]
@chirag04 @stirman @JusticeLai @ezyone123 
We've merged all of the required fixes and verified everything. react-native-code-push@1.17.0-beta has been published to npm with support for react-native@0.40.0. Thanks for your patience.

**Comment by stirman** [comment]
Woot! Thx :)

**Comment by panarasi** [comment]
Closing this issue since RN 0.40 is now supported.
