### ISSUE TITLE
Android infinite loop of pause / resume

### ISSUE THREAD

**Issue by ewindso** [Microsoft/react-native-code-push#669]
I have RN running in a Fragment...  when it gets an update, it seems to do onPause / onResume repeatedly, never ending...  it does this for both `InstallMode.IMMEDIATE` and `ON_NEXT_RESUME`.

My Fragment also has onPause / onResume:

```
    protected void onPause(Activity activity) {
        ReactInstanceManager mReactInstanceManager = mReactNativeHost.getReactInstanceManager();

        mReactInstanceManager.onHostPause(activity);
```

and 

```
    protected void onResume(Activity activity) {
        ReactInstanceManager mReactInstanceManager = mReactNativeHost.getReactInstanceManager();

        mReactInstanceManager.onHostResume(activity, null);
```

I wonder if these could be conflicting?  Any help would be great.

**Comment by ewindso** [comment]
Here's the log:

```
I/ReactNativeJS: [CodePush] Downloading package.
I/ReactNativeJS: [CodePush] Installing update.
D/Fragment: Pause
I/ReactNativeJS: [CodePush] Restarting app
D/Fragment: Resume
D/ReactNative: [CodePush] Loading bundle on resume
D/Fragment: Pause
D/Fragment: Resume
D/ReactNative: [CodePush] Loading bundle on resume
D/Fragment: Pause
D/Fragment: Resume
D/ReactNative: [CodePush] Loading bundle on resume
...
```

It continues to Pause / Resume forever...

**Comment by max-mironov** [comment]
Hello @ewindso, thank you for filling the issue. Right now it is not very clear how you are integrating RN  into the Fragment, so it would be very helpful if you could provide a minimum working example of the app integration or may be a minimum app. So we can repro your case and try to identify how this can be fixed.

**Comment by ewindso** [comment]
Thanks @max-mironov -- I got this fixed by implementing `ReactInstanceHolder` and using `CodePush.setReactInstanceHolder`.  

Seems to work like magic after that :)  No more infinite loops.
