### ISSUE TITLE
Update dialog isn't shown (but app is updated)

### ISSUE THREAD

**Issue by jonaswindey** [Microsoft/react-native-code-push#67]
I'm using react-native 0.14 with code-push 1.2.2-beta

When I do a "Staging" deployment and re-open the app, there is no update dialog. When I close my app and re-open, the update is installed and my code is updated. Is this expected behaviour because I'm in staging? Do I need to change my release config for the update dialog to show?

The commands I use are:

```react-native bundle --entry-file index.ios.js --platform ios --bundle-output ./ios/main.jsbundle```

```code-push release myabi ./ios/main.jsbundle 1.0.0```

Let me know if you need help debugging this, and keep up the great work on this service!

`code-push deployment ls myabi`

```
│ Staging    │ xxx│ Label: v11                                                             
│            │                                      │ App Version: 1.0.0                                                     │
│            │                                      │ Mandatory: No                                                          │
│            │                                      │ Hash: 11e252cb25de4207ea417df2d5bd8a0c7b793dd7af6e98ab45cd66830ecd2215 │
│            │                                      │ Release Time: 5 minutes ago                                            │

```

**Comment by lostintangent** [comment]
Hey @jonaswindey. In v1.2.2-beta, we actually changed the default behavior of sync to be "silent" by default, and to install the update  on the next app restart. This was based on a bunch of user feedback. 

If you want to display the dialog again, and install it immediately, you can simply call `CodePush.sync({ updateDialog: true, installMode: CodePush.InstallMode.IMMEDIATE })`, which effectively gives you the old default behavior. We just updated the docs with this change, but I apologize for any confusion!

Let me know if that works for you and/or if you have any feedback about it. Thanks!

P.S. If you decide to show the dialog in your app, keep in mind that we also added support to `sync` for tracking the download progress, which allows you to show/update a "loading UI" after the user chooses to accept the download.

**Comment by jonaswindey** [comment]
Ok sorry, but I didn't see that in the docs? Are there different docs for the beta branch?

Another question, you mention that the update will be installed on the next app restart. Is this only happening when a user manually closes the app (by double-pressing home and swiping the app away)? Or does an app restart regularly/scheduled when it's running in the background too?

Thanks

**Comment by lostintangent** [comment]
Hmm, I'm sorry. I just noticed that we updated the getting started section of the docs to mention the silent update behavior, but the API reference section isn't quite as clear when it mentions the sync method. I'll fix this in the morning. Apologies for the confusion!

Regarding the restart behavior, yep that will account for both manual restarts by the end-user as well as when the OS kills the app when it is in the background. This option is non-deterministic in terms of when the update will actually be applied, but it's also the least invasive to he end-user. The sync method also allows you to specify to install an update on the next resume or immediately after downloading it.

**Comment by jonaswindey** [comment]
Allright, thanks for the feedback.

**Comment by lostintangent** [comment]
Oh right, we need to update the docs on the website, since they're a little out of the date with the readme. Thanks for the reminder!

**Comment by jonaswindey** [comment]
Just a small question, any reason why the default sync install mode is CodePush.InstallMode.ON_NEXT_RESTART and not CodePush.InstallMode.ON_NEXT_RESUME?
