### ISSUE TITLE
Latest mandatory release isn't being deployed

### ISSUE THREAD

**Issue by patrickomeara** [Microsoft/react-native-code-push#671]
I have released to Staging and promoted to Production a few times without issue. However, the latest mandatory release won't go out to any users. I have killed and restarted the app numerous times, but I'm still not getting the update.

Am I missing something? How can I debug this further?

I am using `1.12.6-beta` as I am on RN `0.28.0` and updating breaks my app quite a bit. The release in question is a small but important API change.

![untitled-1](https://cloud.githubusercontent.com/assets/571773/21918001/937e946a-d9a0-11e6-8516-edf93410573d.jpg)

* react-native-code-push version: 1.12.6-beta
* react-native version: 0.28.0
* iOS/Android/Windows version: ios 10

**Comment by max-mironov** [comment]
Hello @patrickomeara, do you have a chance to verify that you can successfully get updates from your Staging deployment (which was promoted to v3 Prod)? If yes - please verify once again that your are running the app which is of version 0.4.0  and the Deployment key in plist file is correct. 
You can also try to debug the app on iOS simulator which is configured with your prod release key to view the diagnostic logs produced by the CodePush plugin within your app (should be built with debug configuration), please see https://microsoft.github.io/code-push/docs/cli.html#link-5 for details.

**Comment by panarasi** [comment]
@patrickomeara I was wondering if this bug is fixed ? Please let us know if there is any way we could help.

**Comment by patrickomeara** [comment]
@panarasi @max-mironov thanks for your help, I was bumping the version number in `Info.plist` and `build.gradle` to `0.3.1` which was changing the target version. I have left them at `0.3.0` now and updates are pushing out again.

**Comment by silhouettes** [comment]
By the way, please note that when you perform releases, there are flags that allow you to set a range of versions to target, e.g. `>= 0.4.0 < 0.5.0`.

Just be aware of any binary compatibility issues if you do this though, and be aware that this package will be applied on top of any future app store updates in that range unless those updates are also published to CodePush!
