### ISSUE TITLE
Android crashes after update from Play store

### ISSUE THREAD

**Issue by mongolgamestudio** [Microsoft/react-native-code-push#674]
* react-native-code-push version: 1.16.0-beta
* react-native version: 0.38.0
* iOS/Android/Windows version: Android 4, 5, 6, 7 (Specially Samsung)
* Does this reproduce on a debug build or release build? : Release
* Does this reproduce on a simulator, or only on a physical device? : Physical
* Repro steps and/or stack trace: 
Deployed new update in Play store then pushes CodePush update to tell new version is available in Play store. (Only build number changes 1.0.10 -> 1.0.11)
End user behaviour: 
1. Download code-push update and apply changes.
2. App blocks and tells get new update in Play store.
3. User updates app from Play store. (delta changes are applied)
4. Application doesn't have latest code-push update which downloaded from 1. step. It has previous code-push data and crashes.
5. Uninstall app and installs from Play store. In Samsung devices old data still remains then crashes. In Nexus devices works as expected.
6. In application manager Delete app data and uninstall app. Then installs from Play store. Success.

> Fatal Exception: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'i.Aspect'), 

in Play store 1k reports. Is there any idea to fix this problem or am I missing something?

```
componentDidMount(){
       if( outDated() ){
              CodePush.sync();
              Alert.alert('Update',  'New update is available!', [{text: 'Update', onPress: this.jumpToStore}] );
       }else{
              CodePush.sync(
                  {installMode: CodePush.InstallMode.IMMEDIATE},
                  this.codePushStatusDidChange.bind(this),
                  this.codePushDownloadDidProgress.bind(this)
              );
       }
 }
```

**Comment by sergey-akhalkov** [comment]
@mongolgamestudio - hi!
Seems like you have faced with this issues: https://github.com/Microsoft/cordova-plugin-code-push/issues/196, https://github.com/Microsoft/react-native-code-push/issues/650
Could you please try this PR https://github.com/Microsoft/react-native-code-push/pull/654 and let me know if it helps?

**Comment by mongolgamestudio** [comment]
Thanks for comment.
I've resolved by clearing cache and data after store update. On first run in MainApplication onCreate :

```
SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
    if(prefs.contains(lastKnownVersion)){
      //Exists.
      int lastKnownVersionNumber = prefs.getInt(lastKnownVersion, 0);
      if(lastKnownVersionNumber < BuildConfig.VERSION_CODE) {
        // App has been upgrade
        deleteAppDirectory();
        Log.i("com.xxx.yyy", "App is upgraded: "+ BuildConfig.VERSION_CODE);
        SharedPreferences.Editor editor = prefs.edit();
        editor.putInt(lastKnownVersion, BuildConfig.VERSION_CODE);
        editor.commit();
      }
      else{
        Log.i("com.xxx.yyy", "App is ok: " + BuildConfig.VERSION_CODE + ": " + lastKnownVersionNumber);
      }
    }
    else{
      //Doesn't exists === First run or old version
      Log.i("com.xxx.yyy", "First run: "+ BuildConfig.VERSION_CODE);
      deleteAppDirectory();
      SharedPreferences.Editor editor = prefs.edit();
      editor.putInt(lastKnownVersion, BuildConfig.VERSION_CODE);
      editor.commit();
    }
```
