### ISSUE TITLE
Is it possible to use own server instead of CodePush server?

### ISSUE THREAD

**Issue by petromoldovan** [Microsoft/react-native-code-push#675]
Guys, thank you for the awesome work!

quick question though: is there a way how i can avoid using CodePush server and use my own server and maintain the functionality?

**Comment by silhouettes** [comment]
Not at the moment, unfortunately :(

Closing this for now, but feel free to ask any additional questions!

**Comment by petromoldovan** [comment]
@silhouettes thank you!!!
