### ISSUE TITLE
Android app crash when using installMode IMMEDIATE, and ON_NEXT_RESTART working as expected.

### ISSUE THREAD

**Issue by jaggerwang** [Microsoft/react-native-code-push#676]
* react-native-code-push version: pull #670 
* react-native version: 0.40
* wix/react-native-navigation#pull/652/head
* iOS/Android/Windows version: Android 6.0.1
* Does this reproduce on a debug build or release build? only on release build
* Does this reproduce on a simulator, or only on a physical device? on device, simulator not test
* Repro steps and/or stack trace:

Call `codePush.sync` to download and install update, with installMode IMMEDIATE, then the app will crash with the following error. If in default silent mode, update ok.

![image](https://cloud.githubusercontent.com/assets/1255011/22155762/9a86469c-df6b-11e6-932a-6bdf0ae517bf.png)

**Comment by sergey-akhalkov** [comment]
@jaggerwang - hi! 
I've tried to reproduce the issue using react-native@0.40.0, but with no luck. Also I've noticed that you are using `wix/react-native-navigation#pull/652/head`. From [this article](https://github.com/wix/react-native-navigation/wiki/Installation---Android#important) we could see that this library supports React Native 0.37.0 only. So could you please try to test `IMMEDIATE` installation mode with `react-native@0.37.0` and let me know if the issue still reproduces?

**Comment by panarasi** [comment]
@jaggerwang Thanks for the issue. Wanted to ping you again to see if this is still an issue. Could this be an issue with react native navigation as mentioned in @sergey-akhalkov 's comment above ?

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen if needed.
