### ISSUE TITLE
Circular dependency during Android build

### ISSUE THREAD

**Issue by ConnorJWilliams** [Microsoft/react-native-code-push#679]
* react-native-code-push version: 1.16.1-beta (latest)
* react-native version: 0.37.0
* iOS/Android/Windows version: Android 5.1
* Gradle Version: 2.14.1
* Android Plugin Version: 2.2.3

Building Android via Gradle produces a Circular dependency error occurring since the integration of Code Push. 

Error:

````
Circular dependency between the following tasks:
:app:bundleDebugJsAndAssets
\--- :app:recordFilesBeforeBundleCommandDebug
     +--- :app:mergeDebugAssets
     |    \--- :app:bundleDebugJsAndAssets (*)
     \--- :app:mergeDebugResources
          +--- :app:bundleDebugJsAndAssets (*)
          \--- :app:generateDebugResources
               \--- :app:fabricGenerateResourcesDebug
                    \--- :app:mergeDebugAssets (*)

(*) - details omitted (listed previously)

````
This is using the newest version @latest of the npm library. The steps indicated in https://github.com/Microsoft/react-native-code-push/issues/584 did not work, as I'm guessing this line within codepush.gradle has since been removed?

Thanks! :)

**Comment by ConnorJWilliams** [comment]
Issue related to our gradle dependency structure in react.gradle. Will mark as resolved.

**Comment by silhouettes** [comment]
Thanks for the update @ConnorJWilliams!
