### ISSUE TITLE
[docs] CodePush updates should be tested in modes other than debug

### ISSUE THREAD

**Issue by sergey-akhalkov** [Microsoft/react-native-code-push#682]
The fact, that JS bundle is still loaded via React Native packager (due to jsCodeLocation variable is configured to use React Native packager for each app restart in debug mode) after CodePush updates were installed, is confusing: there are two questions about testing CodePush updates in Debug mode: #672 and Microsoft/code-push#364.
I suppose documentation should be updated to specify that only release mode should be used to test CodePush updates.

**Comment by vonovak** [comment]
> I suppose documentation should be updated to specify that only release mode should be used to test CodePush updates.

I would rather say that only modes **other than debug** should be used with code push. 

[This](https://github.com/Microsoft/react-native-code-push#android) paragraph, more specifically

```
 debug {
            ...
            buildConfigField "String", "CODEPUSH_KEY", '"<INSERT_STAGING_KEY>"'
            ...
        }
```

should imo be updated, because it makes no sense to me to use code push in debug buildConfig. Rather I'd create a new buildConfig called `staging` and put this content into it.

**Comment by sergey-akhalkov** [comment]
@vonovak, I've found another way we could add staging build variant - we have to use `releaseStaging` naming instead of `staging` as workaround. For more details please look at https://github.com/Microsoft/react-native-code-push/pull/694

**Comment by kodemi** [comment]
Hi! "Multi-Deployment Testing" section for Android has this line for MainApplication.java:
`new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG)`. But if we not configure CodePush in debug mode this line cause error when `react-native run-android`: `cannot find symbol ... variable CODEPUSH_KEY`. So, how to prevent CodePush to run in debug mode?

**Comment by sergey-akhalkov** [comment]
@kodemi, as workaround you could add 
```gradle
buildConfigField "String", "CODEPUSH_KEY", '""'
``` 
line [here](https://github.com/Microsoft/react-native-code-push/pull/694/files#diff-04c6e90faac2675aa89e2176d2eec7d8R623). It will prevent CodePush from installing updates due to empty deployment key.
Please let me know if you have any questions or see any issues.
