### ISSUE TITLE
Getting lots of 502s from client apps

### ISSUE THREAD

**Issue by mikelambert** [Microsoft/react-native-code-push#685]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The underlying react-native-code-push libraries seem to be getting 502s from the server, which are showing up in the console log (and then being reported to via TrackJS to the trackjs server):

In the last few weeks, 258 instances:
```
502 undefined: POST https://codepush.azurewebsites.net/reportStatus/deploy
 Console -  [CodePush] An unknown error occurred.
 Console -  [CodePush] 502: 502 Bad Gateway
```

And 148 instances of:
```
[CodePush] Report status failed: {"appVersion":"2.2.1"}
502 undefined: GET https://codepush.azurewebsites.net/updateCheck?deploymentKey=XXXX&appVersion=2.2.1&packageHash=&isCompanion=&label=&clientUniqueId=YYYY
```

Seems that there are 
* react-native-code-push version: 1.16 and 1.17
* react-native version: 0.39.2 and a few earlier ones
* iOS/Android/Windows version: Android 19 (all I've seen so far, not sure if it's limited to that though)
* Does this reproduce on a debug build or release build? release build (dunno about debug, it's not consistent though)
* Does this reproduce on a simulator, or only on a physical device? physical device (dunno about simulators)
* Repro steps and/or stack trace:

Are these errors normal/expected? Should I be trying to ignore them from within the StackJS client library? Or does this mean something is broken in my react-native-code-push setup and querying?

**Comment by mikelambert** [comment]
Graph of errors over two weeks:
<img width="1653" alt="2017-02-02 12 17 09" src="https://cloud.githubusercontent.com/assets/7953259/22535959/c4b7773a-e941-11e6-8d54-983d43c765ef.png">

**Comment by mikelambert** [comment]
Ahhh, a big clue. I get multiple client ids from the same IP addresses, and these IP addresses are of the form 66.249.69.242 and 66.249.69.246, which are based in Mountain View, CA.

My best guess is that this might be the Calypso AppCrawler, crawling my app. It's hard to find too much info out there, but I saw this triggering usage stats on my MixPanel dashboard as well. I *think* but am unsure that the Calypso crawler might be related to https://firebase.google.com/docs/app-indexing/?hl=en , but there's not much info out there on this...

**Comment by silhouettes** [comment]
@mikelambert Thanks for the very detailed report! One of our vendors will look at this sometime over the next week or so. There are two possible explanations for the error as far as I can see:

- The 'Bad Gateway' originates between the client and our server, e.g. a network/proxy issue
- The 'Bad Gateway' originates from our server itself

They should be able to figure out which it is by looking at our server logs, and to tell you whether it is expected or not.

Note that either way, the effect shouldn't be too bad - a failure on the `reportStatus` route for a given client will mean that CodePush metrics for your app will be slightly off, and a failure on the `updateCheck` route (assuming it's not persistent) will mean that client won't be able to update until the next check. I'm assuming that the numbers you report are a small percentage of your overall traffic, but if not then please let me know.

**Comment by silhouettes** [comment]
Ahh, nice observation! If they are all geographically in the same location then it definitely gives more credence to the idea that the 502's are coming from some kind of proxy.

**Comment by panarasi** [comment]
@silhouettes Since this is resolved, can we close this issue ?

**Comment by silhouettes** [comment]
Based on the information given, I think a reasonable conclusion is that the app is being run from inside a firewall. I'll close this issue for now, but if you think it deserves more investigation @mikelambert, or if you think the way we handle this use-case needs to be improved, please let us know!
