### ISSUE TITLE
why my codepush cli active and total always is 0

### ISSUE THREAD

**Issue by jameslcj** [Microsoft/react-native-code-push#689]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version:16.1-beta
* react-native version:0.37
* iOS/Android/Windows version:10.0
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? both
* Repro steps and/or stack trace:

I released my new version by code-push, then my app has installed new version successfully. When I use shell command "code-push deployment h myappname Staging" to checkout installation information about new version, the active and total still is 0, and 2 devices is pending(actually, they has installed successfully),situation likes picture
<img width="661" alt="m7phh" src="https://cloud.githubusercontent.com/assets/11494059/22635988/f5f14c02-ec72-11e6-8150-7844069f5f8b.png">
. Do you know why? Could you help me. Waiting for you answer. Thank you very much.

(The more info the faster we will be able to address it!)

**Comment by jameslcj** [comment]
I'm sorry... I have known... because I forgot to invoke the `CodePush.notifyAppReady();` when I start  new version first time... 
thank you!

**Comment by sergey-akhalkov** [comment]
@jameslcj, got it, closing this for now, please feel free to reopen if needed!
