### ISSUE TITLE
Update Available problem

### ISSUE THREAD

**Issue by Fantasim** [Microsoft/react-native-code-push#691]
Hi,

3 weeks ago I sent code-push the latest version of my app.
Today I prepare a new update, but whenever I run the simulator or test my application on device, this message appears every time, specifying that a new version is now available and does not take Account my changes, how can I fix the problem? (Knowing that for this update, I have to go through Itunes Connect and there will be no update on codepush)

[picture problem](http://www.yagoshack.fr/?v=capturese.png)

my code in index.ios.js

```
  codePushInit(){
    CodePush.sync({ updateDialog: true, installMode: CodePush.InstallMode.IMMEDIATE },
      (status) => {
        switch (status) {
          
          case CodePush.SyncStatus.DOWNLOADING_PACKAGE:
            this.setState({ showDownloading: true });
            break;
          
          case CodePush.SyncStatus.INSTALLING_UPDATE:
            this.setState({ showInstalling: true });
            break;

          case CodePush.SyncStatus.UPDATE_INSTALLED:
            this.setState({ showDownloading: false });
            break;

          default:
            break;
        }
      },
      ({ receivedBytes, totalBytes }) => {
        this.setState({ downloadProgress: (receivedBytes / totalBytes) * 100 });
      }
    )
  }

  componentDidMount(){
    this.codePushInit()
  }

```
Thanks :)

* react-native-code-push version: 1.16.1-beta
* react-native version: 0.37.0
* iOS/Android/Windows version: iOS
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by sergey-akhalkov** [comment]
@Fantasim, do I understand correctly that you've received an update message which points to code-push deployment released 3 weeks ago? If so, this message probably means that the app does not have any installed updates. To check it you could try to call `CodePush.getUpdateMetadata(CodePush.UpdateState.RUNNING)` method. In my case it returns some metadata, which means that the app have successfully installed update, so I have no update messages anymore.

To test your changes you could try to 
1. prepare release/staging build which does not contain new changes and changes made 3 weeks ago.
2. then you need to install changes made 3 weeks ago
3. release new CodePush deployment and install it. 

In case if you've already released new changes the last CodePush deployment will be applied on step 2.
We've also discussed best approach to test CodePush updates: https://github.com/Microsoft/react-native-code-push/issues/614
Please also note that CodePush updates should not be tested in debug mode: https://github.com/Microsoft/react-native-code-push/issues/682

**Comment by sergey-akhalkov** [comment]
@Fantasim, are you still experiencing the issue? Please let me know if I could help you.

**Comment by Fantasim** [comment]
Yes sorry for late answer, i've fixed problem with you help, thanks
