### ISSUE TITLE
Update is invalid?

### ISSUE THREAD

**Issue by LiuC520** [Microsoft/react-native-code-push#695]
there is a new problem:

[CodePush] An unknown error occurred.
[CodePush] Update is invalid - A JS bundle file named "main.jsbundle" could not be found within the downloaded contents. Please ensure that your app is syncing with the correct deployment and that you are releasing your CodePush updates using the exact same JS bundle file name that was shipped with your app's binary.

**Comment by sergey-akhalkov** [comment]
@LiuC520, are  you using the same deployment key both for Android and iOS?
It feels like you've released an update for android using `code-push release-react myapp android` command and tried to install produced update for iOS, but there are different bundle names for iOS and Android:
*Android: "index.android.bundle"
*iOS: "main.jsbundle"
So could you please try to execute `code-push release-react myapp iOS` command and install an update again? Please let me know if it helps.

**Comment by LiuC520** [comment]
Thank you !
I use the command:

> 1、react-native bundle --platform android --entry-file index.android.js --bundle-output ./bundles/index.android.bundle --assets-dest ./bundles/ --dev false
> 2、react-native bundle --platform ios --entry-file index.ios.js --bundle-output ./bundles/index.ios.bundle --assets-dest ./bundles/ --dev false
> 3、code-push release <AppName> ./bundles/  1.0.0 —-deploymentName Production  —-mandatory true
