### ISSUE TITLE
How to promote app version after code push

### ISSUE THREAD

**Issue by leonardgithub** [Microsoft/react-native-code-push#698]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

* react-native-code-push version: 1.16.1-beta
* react-native version: 0.39
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?
* Repro steps and/or stack trace:

(The more info the faster we will be able to address it!)
How to promote app version after code push? e.g. The app version is now 1.1.0, I want to change the app version to 1.2.0 after code push

**Comment by max-mironov** [comment]
Hello @leonardgithub, do I get it right that you would like to bump app version via code-push release command? If so than unfortunately it is impossible to do via code-push release due to React Native plugin will sync your JS bundle file and any image assets only. 
Also please note that you can specify target binary version for any release like so:
`code-push release-react MyApp-Android android --targetBinaryVersion "~1.1.0`
so you can manage which version of the app your code-push release will be applied.

**Comment by leonardgithub** [comment]
@max-mironov yes, you are right. I am lazy to release my app of new version to the app market stores, and I want code push help me promote the app version, which can save my time. Thanks

**Comment by buptkang** [comment]
Hey @leonardgithub, based on your comment, we can further improve the tool to automatically promote the bump version if developers do not specify it.

**Comment by sergey-akhalkov** [comment]
@leonardgithub, to promote app version you have to change `android:versionName` property value in `AndroidManifest.xml` file, but it cannot be changed at runtime. This is how Android designed. To promote app version you need to perform a release to the app market store.

Closing this for now, please feel free to reopen if you have any questions or if you have ideas how we could change app version at run-time (programmatically). Thank you!

**Comment by leonardgithub** [comment]
Thank you, sergey-akhalkov

**Comment by ribamarsantos** [comment]
Would that solve this https://gist.github.com/wynch/97b4adcb78af55ba7402222f56838b6f ?

**Comment by vorlovsky** [comment]
> Would that solve this https://gist.github.com/wynch/97b4adcb78af55ba7402222f56838b6f ?

Nope, as those scripts just take and parse version string from package.json and update platform-specific _native_ build settings. And native part is not to be updated using CodePush.
