### ISSUE TITLE
breaking change on rn master breaks code push

### ISSUE THREAD

**Issue by chirag04** [Microsoft/react-native-code-push#703]
latest version of code push is not compatible with master branch of RN as of today.

Refer:
https://github.com/facebook/react-native/commit/ea6845ca2275e0420761a087e6c8844ebaae343e

Fix is simple:
change import to `import com.facebook.react.modules.core.ReactChoreographer;` in Codepush.java and CodepushNativemodule.java.
add missing import `import com.facebook.react.uimanager.ViewManager;` in codepush.java

**Comment by sergey-akhalkov** [comment]
@chirag04, got it, thanks!

**Comment by sergey-akhalkov** [comment]
Closing this due to https://github.com/Microsoft/react-native-code-push/pull/735 has been merged. Please feel free to reopen if need.
