### ISSUE TITLE
Breaking changes break everything

### ISSUE THREAD

**Issue by dbof10** [Microsoft/react-native-code-push#705]
In previous version of CodePush, I used `TikiHome = codePush(optionsProd)(TikiHome);`. After upgrading to `0.17`, codePush does not work anymore. Log message `Object is not a function (evaluating '(0,_reactNativeCodePush2.default)(optionsProd))')`. I noticed that `codePushify` function was removed!!! ĐM. Thanks :)

**Comment by sergey-akhalkov** [comment]
@dbof10, please try to import CodePush like this `var CodePush = require("react-native-code-push")` and let me know if any changes.
