### ISSUE TITLE
Check for app exist before uploading build

### ISSUE THREAD

**Issue by passabilities** [Microsoft/react-native-code-push#706]
* react-native-code-push version: 1.12.6-beta

Not really a big deal and not sure if this has been addressed already since this isnt the newest version im using (Working with react native v 0.24.1) but when pushing a new build it waits till the end of the `release` command to say I typed the wrong name of the app.

<img width="1507" alt="screen shot 2017-02-18 at 21 17 57" src="https://cloud.githubusercontent.com/assets/6958300/23098591/11df3788-f620-11e6-81e1-2f24681f9b57.png">

**Comment by sergey-akhalkov** [comment]
@passabilities, thanks for the feedback. I've added PR implements this functionality [here](https://github.com/Microsoft/code-push/pull/399). In case you want to test it you could use [my code-push fork](https://github.com/sergey-akhalkov/code-push/tree/issue706).

**Comment by sergey-akhalkov** [comment]
Closing this due to #399 has been merged.
