### ISSUE TITLE
[Android] - CodePush mAssetsBundleFileName can not be configured

### ISSUE THREAD

**Issue by MrBr** [Microsoft/react-native-code-push#707]
I have scenario where CodePush is not used for loading bundle until new bundle from CodePush is actually downloaded, therefore the current Android implementation leaves `mAssetsBundleFileName` with `null` value which prevents proper CodePush synchronization. It fails when checking if there is proper entry file in the bundle because it is looking for the `null`.

I am interested is there any reason behind it?

In short term, my proposal is to add public method `setAssestsBundleFileName` which will provide more control over `mAssetsBundleFileName` attribute. Further more I would remove part where `mAssetsBundleFileName` is set while getting JS bundle with `getJSBundleFileInternal` method, this doesn't seem right, I prefer, if there is no `mAssetsBundleFileName` then just use default fallback, or define default value for `mAssetsBundleFileName`. Things are too coupled atm.

If you like this idea, I can create PR.

In long term, if sync is already checking entry bundle file, then I would allow JS part to change it for the new bundle.

**Comment by sergey-akhalkov** [comment]
Hi @MrBr, thanks for reaching us and sorry for such late reply.

>the current Android implementation leaves mAssetsBundleFileName with null value which prevents proper CodePush synchronization. It fails when checking if there is proper entry file in the bundle because it is looking for the null

I don't sure if I get it right, but I've not heard about such kind of issue before. Could you please provide us with more info or repro steps, stack trace to get better understanding what actually goes wrong?

Could you also please clarify what do you mean by `"In long term, if sync is already checking entry bundle file, then I would allow JS part to change it for the new bundle."`  and also clarify (provide pseudo code if possible) which way you are planning to use `setAssestsBundleFileName` method?

Please also let me know if you see any issues.

**Comment by sergey-akhalkov** [comment]
@MrBr, just a friendly ping.

**Comment by MrBr** [comment]
Hey @sergey-akhalkov, sorry I've missed the reply. 

It's been a while since I've faced the problem, so I'll need to dig in if I do not provide enough info.

As much as I remember, the problem is that the Android Code Push implementation doesn't know how to load later downloaded JS bundle if the default bundle (the one bundled in the app binary) is not loaded with Code Push as well.

When you do not use Code Push to load default bundle (you leave it to the RN), but only to load the updates sent to the Code Push server, Code Push native part doesn't have defined `mAssetsBundleFileName` and when an update comes it doesn't know what is the bundle file name, it has `null` value.

I have a case where I use 2 RN instances (Views). One instance always has the same bundle and the other loads bundle dynamically with the Code Push. Problem is that Code Push always looks into the same `setAssestsBundleFileName` and as I do not use Code Push to load the bundle on the start `setAssestsBundleFileName` stays undefined (`null`).

What I wanted to say is that if `sync` method (native Android implementation) is checking for the `setAssestsBundleFileName` in the update, it would be all right if it could also change the it. It makes sense that new bundles can have different main module names.

For example, maybe new bundle (update) will not have both `index.ios` and `index.android` but only `index.js` and current implementation doesn't allow it. Or as in my case, I use Code Push to dynamically load independent bundle afterward for specific RN instance and I can not easily define `setAssestsBundleFileName`.

If you look how `setAssestsBundleFileName` is defined you will see that there is no setter but it is integrated into `getJSBundleFileInternal` and this implementation makes it hard to change it.

Does it help?

Didn't catch the time to write any code but if it is needed I will find some time.

**Comment by sergey-akhalkov** [comment]
Hi @MrBr, sorry for such delayed response. I've reviewed your post ones again and I've got your idea here. To set `mAssetsBundleFileName` private var value you could use `CodePush.getJSBundleFile("index.android.bundle");` method to set custom JS bundle name. Please pay attention to CodePush setup for react native activity:
```js
@Override
    protected void onCreate ( Bundle savedInstanceState ) {
 
        super.onCreate( savedInstanceState );
 
        if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.M ) {
            if ( !Settings.canDrawOverlays( this ) ) {
                Intent intent = new Intent( Settings.ACTION_MANAGE_OVERLAY_PERMISSION,
                        Uri.parse( "package:" + getPackageName() ) );
                startActivityForResult( intent, OVERLAY_PERMISSION_REQ_CODE );
            }
        }
 
        mReactRootView = new ReactRootView( this );
        mReactInstanceManager = ReactInstanceManager.builder()
                                                    .setApplication( getApplication() )
                                                    .addPackage( new MainReactPackage() )
                                                    .addPackage( new TrakBridgeModulePackage() )
                                                    .addPackage( new RCTCameraPackage() )
                                                    .addPackage( new SvgPackage() )
                                                    .addPackage( new RNFSPackage() )
                                                    .addPackage(new CodePush(BuildConfig.CODEPUSH_KEY, getApplicationContext(), BuildConfig.DEBUG))
//                                                    .addPackage( new MapsPackage() )
                                                    .addPackage( new ReactNativeMapboxGLPackage() )
                                                    .addPackage( new RCTBluetoothSerialPackage() )
                                                    .setUseDeveloperSupport( BuildConfig.DEBUG )
                                                    .setInitialLifecycleState( LifecycleState.RESUMED )
                .setJSBundleFile(CodePush.getJSBundleFile("index.android.bundle"))
                                                    .build();
 
        // Get passed extras and pass to React Native as initial props.
 
        String facilityUid  = getIntent().getStringExtra( this.getPackageName() + ".facilityUid" );
        String initialRoute = getIntent().getStringExtra( this.getPackageName() + ".initialRoute" );
 
        Bundle initialProps = new Bundle();
 
        initialProps.putString("facilityUid", facilityUid);
        initialProps.putString("initialRoute", initialRoute);
 
        mReactRootView.startReactApplication( mReactInstanceManager, "Trak", initialProps );
 
        setContentView( mReactRootView );
    }
```

Closing this for now, please feel free to reopen in case of any concerns or questions.
