### ISSUE TITLE
How is CodePush secured?

### ISSUE THREAD

**Issue by eladmoshe** [Microsoft/react-native-code-push#708]
I was not able to find any resources about the security model of CodePush. I am especially referring to the prevention of application code hijacking; i.e. pushing malicious code to users. 
I think this is important as this is a prerequisite for enterprise applications.

**Comment by sergey-akhalkov** [comment]
@eladmoshe, thanks for the question. The source code uploaded to the Code Push Servers can only be accessed using your access key. Once uploaded, only meta data about the source code can change, not the code itself. We are also working on adding the ability to sign the code and verify its validity, but this is something for the future.
Also, all communications are via HTTPS protocol. CodePush CLI and React Native SDK do verify that CodePush Web Server SSL certificate is valid.

**Comment by eladmoshe** [comment]
Thank you @sergey-akhalkov!
Having the ability to sign the code and have the client SDK decline any unsigned update is crucial IMHO for this type of service. I believe that otherwise any enterprise security audit will automatically fail.

**Comment by merlinpatt** [comment]
@sergey-akhalkov, I know this is old but I can't much else on React Native code push security concerns so I'll ask here.

What's to prevent a malicious developer from creating a boring app and then later pushing out code that mirrors a bank app or another valuable app?

**Comment by max-mironov** [comment]
@merlinpatt - hi. So - yes, in fact it is possible to push such changes that will try to mirror another app. 
But remember that usually  bank apps (or other valuable apps) uses two factor authentication, so even if someone stole a password that would be not enough. 
Also as far as it is not possible to push native changes - that will make more difficult to potentially harm user.
Finally most likely that the app will be banned by Apple or GooglePlay very soon as it will violate Apple's [developer agreement](https://developer.apple.com/programs/ios/information/iOS_Program_Information_4_3_15.pdf) or [GooglePlay policies](https://play.google.com/about/ip-deception-spam/deceptive-behavior/).

**Comment by mayurssoni2456** [comment]
@sergey-akhalkov/All 

Could you please shed some light on the security aspects

As mentioned in the above comments, 
> The bundle is stored on CP server
> Only accessible via key provided to the client

Is there any other security updates introduced after 2017.

The main concern is still
> Uploading JS bundle 
> Data usage policies 


I am not able to find the info which provides detail security details about Code Push. 
Would be really great if you could share some link 

Thank you. 
Mayur SSoni
