### ISSUE TITLE
NullReferenceException due to missing ProcessorId key

### ISSUE THREAD

**Issue by gabergg** [Microsoft/react-native-code-push#713]
* react-native-code-push version: master
* react-native version: 0.42.0-rc.2
* iOS/Android/Windows version: Windows 10
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? Windows 10 Desktop VM
* Repro steps and/or stack trace: Crashes on startup

<img width="1002" alt="screen shot 2017-02-21 at 2 14 31 pm" src="https://cloud.githubusercontent.com/assets/3479242/23187748/daad969c-f840-11e6-9149-b48868766ab1.png">

**Comment by sergey-akhalkov** [comment]
Hello @gabergg, sorry for slow response, do you still experiencing the issue? Were you able to resolve it?

**Comment by sergey-akhalkov** [comment]
Closing this due to #743 has been merged. Please feel free to reopen if needed.
