### ISSUE TITLE
ld: 5 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by byk04712** [Microsoft/react-native-code-push#714]
* react-native-code-push version:1.17.0-beta
* react-native version:0.41.2
* Xcode:8.2
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device? run on simulator
* Repro steps and/or stack trace:

I integration react-native-code-push to my  cocoapods project. When i added `CodePush.xcodeproj` and `libCodePush.a`. I got this error.
-------
<img width="1216" alt="wx20170222-130731 2x" src="https://cloud.githubusercontent.com/assets/6211302/23198078/e8794cde-f8ff-11e6-9bab-e77805f7796c.png">

See my Podfile content below

-----
<img width="403" alt="pod" src="https://cloud.githubusercontent.com/assets/6211302/23198116/1afe9d76-f900-11e6-864a-dd8c7a268ab9.png">

-----

But when I remove `CodePush.xcodeproj` reference.  It works!

How do I fix it?

**Comment by byk04712** [comment]
I solved this problem. react-native-code-push has SSZipArchive library.  so I removed `pod 'SSZipArchive', '~>1.2'` from Podfile. and added `$(SRCROOT)/../node_modules/react-native-code-push/ios/CodePush/SSZipArchive` (set to recuirsive)  to `Build Setting -> Header Search Paths`. them clear & build. It's works

**Comment by sergey-akhalkov** [comment]
@byk04712, thanks for response. Closing this for now, please feel free to reopen if needed.

**Comment by adalvi13** [comment]
I am still facing same issue, any other solution?

**Comment by NickToropov** [comment]
Hi @adalvi13, please check if you `Podfile` is similar to [this one](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---cocoapods)
