### ISSUE TITLE
HELP!!!!!! Accidentally remove my deployment!!!

### ISSUE THREAD

**Issue by dannyyaou** [Microsoft/react-native-code-push#715]
* react-native version: 40
* iOS/Android/Windows version: ios android

Dear ALL:

Thanks a lot for your CodePush Project! That helps a lot!

But today there's a issue happened on IOS! I can't get my app updated!
And my app will stuck on the update page.
That's a big problem! 
So I try to remove new deployment as soon as posible

THEN I REMOVED MY "PRODUCTION" DEPLOYMENT ACCIDENTALLY!!!

That means all al the users can't get updated unless I upload new version to App Store and Play with new deployment key, and they go to app store or play store updating their app...

Can I have my PRODUCTION" DEPLOYMENT back please!!!

Please! Please Let me know if this possible!!

Thanks a lot!
Sincerely Yours

**Comment by silhouettes** [comment]
@dannyyaou: We can look into this for you, but please note that we won't be able to do this again. Please email codepush@microsoft.com using the email address that your account is registered with (we have received some emails, but they are not from the email address originally associated with your GitHub account). In the email, please include the deploymentKey you'd like to change, and the original deploymentKey you previously owned, and we will change it for you once we verify you owned the original deploymentKey.

@max-mironov @sergey-akhalkov - When you are back, can you make sure the confirmation prompt on the `app rm` and `deployment rm` commands on the CLI default to 'no', and make the message more severe than they currently are (e.g. `Are you sure? Any deployment keys associated with this deployment will be lost FOREVER.`)

**Comment by dannyyaou** [comment]
Dear Codepush Team and Richard Hua:

Thanks a lot for helping me out, I promise this wont happened again!

My original Deployment-Key is: A7Nju32c9lfHYQu6pOtMcjUXvGg_VyBlucLtBQg
My new Deployment-Key is: H5huJ0l6op17ytdGYHzystfl-7yrVyBlucLtBQg

Please make my new Deployment-Key back to my original Deployment-Key,
Thanks you very much!!!

Sincerely Yours
Danny Yao

2017-02-23 17:12 GMT+08:00 Richard Hua <notifications@github.com>:

**Comment by silhouettes** [comment]
Please don't post your deployment key publicly! I have deleted your message. In the meantime, can you please email us using the email that was originally associated with your GitHub account? I will verify that you own the key while you do that.

**Comment by max-mironov** [comment]
@silhouettes sure, we'll handle this

**Comment by silhouettes** [comment]
For anyone else reading this issue in the future, please note that we can no longer service individual requests to restore deployment keys. If you have removed your deployment by accident, please create a new deployment and ship an app store update with your new deployment key.
