### ISSUE TITLE
Tracking Codepush updates per version

### ISSUE THREAD

**Issue by ssomnoremac** [Microsoft/react-native-code-push#719]
v1.16.0+RN37* iOS/10.2.1
-------------------------

I'm having difficulty managing version changes in the app with codepush updates. I have two versions of my iOS app, 1.4.1 and 1.4.2.  It might be worth mentioning in the docs btw that codepush looks at the info.plist for this information when committing an update. I assumed that codepush was only dependent on the `src` folder of my app-- and that came back to bite me in production. 

My question is this however: If I did a codepush on 1.4.2 and then later on 1.4.1, are both codepushes still active?

If I have testflights on 1.4.2 ( iOS will not let you do a testflight for an earlier version, so I'm stuck at 1.4.2) and my production is on 1.4.1, it seems like both are receiving different codepushes. The latest codepush is for 1.4.1 but I made an earlier one on 1.4.2. Is this earlier one still active for builds on 1.4.2? It would seem so in my case.

** update:
Looking at the [cli](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter) docs I can see that you can set the range of versions. However, I am still curious about lingering updates.

**Comment by silhouettes** [comment]
Yes - the way we resolve updates is that we look for the latest CodePush release for which its appVersion range satisfies the version in your Info.plist. So, it is possible to support multiple app versions in the same deployment. Does this make sense to you, and do you have any further questions?

With the fact that the version is read from your Info.plist - that is a good point, and we will consider making doc changes.

**Comment by ssomnoremac** [comment]
Thanks. The cli docs are so good! These docs are great too 😀  That answers all my questions yes, and I know what to do going forward as well. It might be enough just to show examples that target version binaries using something like `-t >1.0.0`. Something like that would have saved me a lot of time. Great work though -- such a sold product!

**Comment by silhouettes** [comment]
No worries, and glad to hear :)

@sergey-akhalkov @max-mironov - I remember we had another issue asking to clarify the behavior for appVersion ranges that target pre-releases. Could we also address this issue at the same time when we are making those doc changes?
