### ISSUE TITLE
iOS App Updates even though binary version has been incremented

### ISSUE THREAD

**Issue by jamealg** [Microsoft/react-native-code-push#720]
I released an app with a binary version of 1.0.3 and later released a mandatory update over the air with the same binary version. That all worked fine. Later I made some updates and then updated the binary version to 1.0.6. I then re-released the app expecting it to ignore the over the air update (because it's binary version is 1.0.6 and the code push update was for 1.0.3) however it updates anyway and now my release build is back on 1.0.3.

I see Code Push logging `[CodePush] Reporting binary update (1.0.6)` and yet it still downloads the package`CodePush: Downloading package.`

I performed the same sequence of events with the corresponding Android version of our app and Code Push reported the app as `Up to date` which is the behavior I expected.

Here is the JSON the update check returns on iOS in case it's useful:
```
"updateInfo": {
"downloadURL": "[redacted]",
"description": "",
"isAvailable": true,
"isMandatory": true,
"appVersion": "1.0.6",
"packageHash": "[redacted]",
"label": "v1",
"packageSize": 5438387,
"updateAppVersion": false,
"shouldRunBinaryVersion": false
}
```

Other information:
* react-native-code-push version: 1.16.1-beta
* react-native version: 0.40.0
* iOS/Android/Windows version: iOS 10.0.2
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Physical Device

**Comment by silhouettes** [comment]
@jamealg Are you absolutely certain that the iOS version you published didn't target `1.0.6`? Could you check the output of `code-push deployment history <appName> <deploymentName>`?

**Comment by jamealg** [comment]
Sorry for the delayed response. Here's what I see. Is it the mandatory update that's forcing it? What's strange is that I'm almost certain I ran `deployment clear` fewer than 18 days ago so that release shouldn't even be in the history. 

```
┌───────┬──────────────┬─────────────┬───────────┬─────────────┬────────────────────────┐
│ Label │ Release Time │ App Version │ Mandatory │ Description │ Install Metrics        │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v1    │ 18 days ago  │ *           │ Yes       │             │ Active: 41% (21 of 51) │
│       │              │             │           │             │ Total: 38              │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v2    │ 12 days ago  │ 1.0.3       │ Yes       │             │ Active: 16% (8 of 51)  │
│       │              │             │           │             │ Total: 18              │
├───────┼──────────────┼─────────────┼───────────┼─────────────┼────────────────────────┤
│ v3    │ 6 days ago   │ 1.0.3       │ Yes       │             │ Active: 53% (27 of 51) │
│       │              │             │           │             │ Total: 27              │
└───────┴──────────────┴─────────────┴───────────┴─────────────┴────────────────────────┘
```

**Comment by jamealg** [comment]
Yes and thank you for the detailed and thorough response.

**Comment by bencollab** [comment]
I'm seeing similar behavior. All of my CodePush releases have targeted a specific binary version (see table below), yet when I build a new binary for my app (in this case, version 2.0.16) and distribute through TestFlight, the app (CodePush) is pulling down and applying v36, which is *not* what I expect. Am I doing something wrong, or could there be some kind of bug in the version comparison logic?

- react-native-code-push version: 3.0.1-beta
- react-native version: 0.44.2
- iOS/Android/Windows version: iOS 10.3.2
- Does this reproduce on a debug build or release build? Release
- Does this reproduce on a simulator, or only on a physical device? Physical Device
```
┌───────┬──────────────────────────────┬─────────────┬───────────┬────────────────────────┐
│ Label │ Release Time                 │ App Version │ Mandatory │ Install Metrics        │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v1    │ 14 days ago                  │ 2.0         │ No        │ No installs recorded   │
│       │ (Promoted v1 from "Staging") │             │           │                        │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v2    │ 14 days ago                  │ 2.0         │ No        │ Active: 1.5% (1 of 65) │
│       │ (Promoted v2 from "Staging") │             │           │ Total: 2               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v3    │ 14 days ago                  │ 2.0         │ No        │ Active: 0% (0 of 65)   │
│       │ (Promoted v3 from "Staging") │             │           │ Total: 1               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v4    │ 14 days ago                  │ 2.0         │ No        │ Active: 0% (0 of 65)   │
│       │ (Promoted v4 from "Staging") │             │           │ Total: 1 (1 pending)   │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v5    │ 14 days ago                  │ 2.0         │ No        │ Active: 0% (0 of 65)   │
│       │ (Promoted v5 from "Staging") │             │           │ Total: 3               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v6    │ 13 days ago                  │ 2.0         │ No        │ Active: 0% (0 of 65)   │
│       │ (Promoted v6 from "Staging") │             │           │ Total: 1               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v7    │ 13 days ago                  │ 2.0         │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 3 (1 pending)   │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v8    │ 13 days ago                  │ 2.0         │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 6               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v9    │ 13 days ago                  │ 2.0         │ No        │ No installs recorded   │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v10   │ 13 days ago                  │ 2.0         │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 6               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v11   │ 13 days ago                  │ 2.0         │ No        │ Active: 3.1% (2 of 65) │
│       │                              │             │           │ Total: 15 (1 pending)  │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v12   │ 12 days ago                  │ 2.0         │ No        │ Active: 32% (21 of 65) │
│       │                              │             │           │ Total: 34 (11 pending) │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v13   │ 11 days ago                  │ 2.0.5       │ No        │ No installs recorded   │
│       │                              │             │           │                        │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v14   │ 11 days ago                  │ 2.0.6       │ No        │ No installs recorded   │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v15   │ 11 days ago                  │ 2.0.9       │ No        │ Active: 3.1% (2 of 65) │
│       │                              │             │           │ Total: 4 (3 pending)   │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v16   │ 11 days ago                  │ 2.0.9       │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 4               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v17   │ 10 days ago                  │ 2.0.9       │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 2               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v18   │ 10 days ago                  │ 2.0.9       │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 3               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v19   │ 9 days ago                   │ 2.0.9       │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 2               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v20   │ 9 days ago                   │ 2.0.9       │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 3               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v21   │ 9 days ago                   │ 2.0.9       │ No        │ Active: 3.1% (2 of 65) │
│       │                              │             │           │ Total: 3 (1 pending)   │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v22   │ 7 days ago                   │ 2.0.10      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 2               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v23   │ 7 days ago                   │ 2.0.10      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 2               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v24   │ 7 days ago                   │ 2.0.10      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 3               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v25   │ 7 days ago                   │ 2.0.10      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 1               │
│       │                              │             │           │ Rollbacks: 1           │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v26   │ 6 days ago                   │ 2.0.10      │ No        │ Active: 3.1% (2 of 65) │
│       │                              │             │           │ Total: 4               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v27   │ 6 days ago                   │ 2.0.11      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 2 (3 pending)   │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v28   │ 5 days ago                   │ 2.0.11      │ No        │ Active: 3.1% (2 of 65) │
│       │                              │             │           │ Total: 3               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v29   │ 5 days ago                   │ 2.0.12      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 2 (2 pending)   │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v30   │ 4 days ago                   │ 2.0.12      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 4               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v31   │ 4 days ago                   │ 2.0.12      │ No        │ Active: 7.7% (5 of 65) │
│       │                              │             │           │ Total: 9               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v32   │ 4 days ago                   │ 2.0.13      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 1               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v33   │ 4 days ago                   │ 2.0.13      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 2               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v34   │ 4 days ago                   │ 2.0.13      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 2               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v35   │ 4 days ago                   │ 2.0.13      │ No        │ Active: 0% (0 of 65)   │
│       │                              │             │           │ Total: 2               │
├───────┼──────────────────────────────┼─────────────┼───────────┼────────────────────────┤
│ v36   │ 3 days ago                   │ 2.0.13      │ No        │ Active: 1.5% (1 of 65) │
│       │                              │             │           │ Total: 2               │
└───────┴──────────────────────────────┴─────────────┴───────────┴────────────────────────┘
```

**Comment by max-mironov** [comment]
Hey @bencollab, I have just tried to reproduce your issue but unfortunately with no luck. 
So I've used iPhone7 iOS 10.3.2 with RN 0.44.2 and react-native-code-push 3.0.1-beta.
I've produced version 2.0.13 of my app, released few updates, verified they are available and applied correctly. 
After that I've produced new version of the app (v. 2.0.16) and have verified that I do not see any updates now. 

Is it possible for you to verify the issue once again (could you also try to release it without Testflight to see if the issue could be reproducible this way either) and try to check once again if my repro steps are complete and if you have any other conditions that I have missed probably. 

Please let us know the results.

**Comment by bencollab** [comment]
@max-mironov Thank you for taking the time to try and reproduce the issue.

I double-checked (with and without TestFlight) with some new builds, and found something interesting: I was wrong about it applying v36; as best I can tell, *it's actually reverting back to v21*. If you look at the history table, you'll notice that v21 was the last version with a single digit in the patch version component. This is pure speculation, but I suspect this could be a result of CodePush comparing/ordering version string components using string comparison rather than a numeric comparison.

Is there any chance you could try to reproduce again, but with an app version 2.0.9 prior to version 2.0.16?

**Comment by max-mironov** [comment]
Hey @bencollab, thanks for quick reply. Sure thing, I can check tomorrow with version 2.0.9 but I don't believe that this could be the reason of the issue. AFAIK CodePush uses [semver ](https://www.npmjs.com/package/semver)for comparing versions so it should work correctly with v.2.0.9 in this case.
Anyway when you build new binary on the device old updates are removed and only those who are targeting your binray version would be downloaded. 
BTW you said 
> try to reproduce again, but with an app version 2.0.9

if I install version 2.0.9 of the app then it should be correct that release `v21 ` is applied because its target binary version is satisfied. So it looks like expected result, isn't it?

**Comment by bencollab** [comment]
> if I install version 2.0.9 of the app then it should be correct that release v21 is applied because its target binary version is satisfied. So it looks like expected result, isn't it?

Right, I should have been clearer: make sure you push a CodePush update *targeting* 2.0.9, followed by a binary build of version >= 2.0.10.

> when you build new binary on the device old updates are removed and only those who are targeting your binray version would be downloaded

I do understand that's the intended behavior, and when I first run the new build on a device, it obviously includes (bundled with the binary) the new JS codebase, but it's definitely downloading and later running (on a subsequent launch of the app) a CodePush version targeted for a lower binary version.

**Comment by bencollab** [comment]
One more thing to note: this only appears to happen (for me) if I *don't* release any CodePush updates targeting the newest binary (in other words, no CodePush update exists to satisfy the binary version). I've been assuming in that case, there should just be no CodePush update applied, but perhaps I'm mistaken.

If I build a new binary version and immediately follow it up with a CodePush update targeting the new version, then it does stay on the correct/newest CodePush versions as expected.

**Comment by bencollab** [comment]
@max-mironov I've been trying to reproduce the issue with a new react-native project, and so far I haven't been able to reproduce the issue with the steps I gave you, so there must be some other factor causing it. I'll keep digging and let you know if I can track it down. No need to try it on your end.

**Comment by max-mironov** [comment]
@bencollab - thanks for heads up! Let us know if you get more info regarding this or see any issues.

**Comment by bencollab** [comment]
OK, I just reproduced the issue with a new react-native project. These were my steps (this was tested only with iOS):

- Start with a new react-native project (and add CodePush support - I'm using all defaults except for `{ checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
  installMode: codePush.InstallMode.ON_NEXT_RESUME }`
- `code-push release-react APP_NAME ios -d Production -t 2.0`
- Make visible change in JS codebase
- Set app version (CFBundleShortVersionString) to `2.0.1`
- Build app for release and install on device
- Run the app on the device, background the app, and then resume

The app will have updated to the CodePush version that was targeted for `2.0`.

More speculation (please forgive me): If [semver](https://www.npmjs.com/package/semver) is being used for the version comparison, maybe the issue is related to the fact that `2.0` is not actually a valid semver version (though often treated the same as `2.0.0`.

**Comment by max-mironov** [comment]
@bencollab - good catch, so I've just recalled that we have the similar question previously, could you please take a look at the following:
https://github.com/Microsoft/code-push/issues/400#issuecomment-281279417

So probably we have to update our docs to make things much clearer, if you have any suggestions or could help us with PR for this - that would be much appreciated.

**Comment by bencollab** [comment]
@max-mironov Interesting. In the CLI README under "Target binary version parameter", it specifically states:
> NOTE: If the app store version in the metadata files are missing a patch version, e.g. 2.0, it will be treated as having a patch version of 0, i.e. 2.0 -> 2.0.0

Maybe I'm misreading that, but I had assumed that by leaving off the target binary version parameter when releasing a CodePush update, I'd essentially be locking the update to *only* the version specified by the app (e.g., in `Info.plist`), and that when my app was `2.0`, it would be treated the same as `2.0.0`. If that's not correct, I think it definitely deserves some correction/explanation in the docs as you say.

From the comment you linked to, it sounds like the target binary version parameter is actually *always* treated as a semver range (which was not expected).

**Comment by max-mironov** [comment]
@bencollab Yes, you are correct with your assumptions and adding patch version is referring to the app being requesting the update. 
As for `target binary version` : it is indeed treated as range and as for specifying separate option or flag - in my point of view that is probably not required because you could always narrow versions to match exact number (or [patch](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter-3) your release if you need to update previous one). 
Additional flag also could lead to increasing complexity for the API, which is also may not be desired. 
Anyway than you very much for pointing at this and we probably should at least update documentation to avoid confusion in future.

**Comment by bencollab** [comment]
> that is probably not required because you could always narrow versions to match exact number

@max-mironov Is there a way to do that with a version such as "2.0"? It doesn't sound like that's possible, and I believe it's fairly common for people to release versions without a patch number.

**Comment by max-mironov** [comment]
@bencollab I think that [patch ](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter-3)command is what you are looking for. You could update your target binary version for this release from `2.0` to `2.0.0`. I could look at this more tomorrow if needed.

**Comment by bencollab** [comment]
@max-mironov Hmmm, ok. Yes, I can (already did) use the patch command to retroactively fix that for past versions, but IMO that's just fixing symptoms of the problem rather than the problem itself. I have to say I'm a bit surprised that you consider this to be the intended behavior, but obviously it's not my product so it's your call.

**Comment by max-mironov** [comment]
@bencollab Thanks for providing with feedback. 
I understand your concerns and that all really make sense for me. But to be honest  for now we didn't get any requests for this yet, so for sure if it becomes something that gets more and more votes - we definitely should go ahead with this. 
From the other point of view I believe that some people could get used to expect current behavior at that moment and release updates with current logic in mind. So we should consider this scenario also.

**Comment by ou2s** [comment]
Sorry for complaining, we love codepush, but this is a very annoying issue. We had to run the `code-push patch` more than 100times  to change AppVersion from `5.0` to `5.0.0` for our different apps to make sure that `5.0.1` wont be targeted because we still fear that Apple would reject us for having a codepush installl on launch.

I think the version parsing in the Info.plist in the CP CLI should have a fix for that.

**Comment by sergey-akhalkov** [comment]
Hi @ou2s, thanks for reaching us. 
Could you please clarify - do I get it right if 
1. your `Info.plist` has version `5.0`
2. you have released several update for `5.0`
3. you have released new binary version of your app `5.0.1`
4. you want to avoid of installing updates that have been released for  `5.0` to `5.0.1`?

If so, CodePush automatically gets your app version from your `Info.plist` file and it works for most of the users. Also it's important to note that CodePush using `semver` [rules](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter) while making a desition to distribute the specific update for the current binary version of your app or not.

To avoid this issue you can use `major.minor.patch` version structure for your app or just release updates using [target-binary-version parameter](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter)

Please let me know if I've missed something or if you have any questions or considerations.

**Comment by ou2s** [comment]
Thanks for your answer @sergey-akhalkov 

Yes you got it right, when `5.0` was defined as `App Version` in codepush, it was also installing on binary with `5.0.1` version. And in my opnion, this is a bug. CodePush cli should convert `5.0` to `5.0.0`to avoid this error.  In order to avoid codepush installations on `5.0.1` we had to patch all previous codepush releases from `5.0`to `5.0.0`.

**Comment by sergey-akhalkov** [comment]
@ou2s, I got your concern here, thanks for the clarification. We are going to discuss if it would be more clear for users to convert app version from build.gradle or info.plist to the `major.minor.patch` format by default to avoid of unexpected installations. We'll let you know the results, thanks.

**Comment by ou2s** [comment]
Leaving just there for anyone having to patch multiple previous codepush releases. This shell script might help you.
```
 #!/bin/bash

 for i in {1..52};
 do code-push patch MyApp-ios Production -l v$i -t "5.0.0";
 done
```
