### ISSUE TITLE
The request timed out.

### ISSUE THREAD

**Issue by mike623** [Microsoft/react-native-code-push#722]
* react-native-code-push version: ^1.17.0-beta
* react-native version: ^0.41.2
* iOS/Android/Windows version: iOS 9.3
* Does this reproduce on a debug build or release build: no
* Does this reproduce on a simulator, or only on a physical device: both
* Repro steps and/or stack trace:

<img width="756" alt="screen shot 2017-02-25 at 4 58 19 pm" src="https://cloud.githubusercontent.com/assets/14008281/23329875/48a3ca16-fb7c-11e6-9910-af1959d25de8.png">

Update: Seem double release to make `[Error]  The uploaded package was not released because it is identical to the contents of the specified deployment's current release.`  to make download package success

**Comment by max-mironov** [comment]
Hello @mike623, thank you for filling the issue.
As for the second question - by default code push prohibit to release packages with identical contents, you can override this behavior if needed as it is described here - https://github.com/Microsoft/code-push/tree/master/cli#no-duplicate-release-error-parameter.

For the issue with request timeout can you please help us and answer some questions to clarify:
Does it reproduced on sample app? Which way do you release your code-push updates? Were the previous updates successful or this is the first package you were downloading to apply?

**Comment by max-mironov** [comment]
Hi @mike623, please let us know if you still face the issue.

**Comment by diegoperini** [comment]
I had the same issue. I logged out and logged in again to fix the issue. Just letting you know.

**Comment by max-mironov** [comment]
@diegoperini - thanks for the info! @mike623 - I'm closing the issue for now, please feel free to reopen or create a new one of you could still see this (also it would be great if you could try to login-logout from cli first as it was suggested by @diegoperini)
