### ISSUE TITLE
code-push release-react myapp android it shows an update on iOS and it breaks it (flags it as broken on iOS)

### ISSUE THREAD

**Issue by octohedron** [Microsoft/react-native-code-push#723]
Issuing `code-push release-react myapp android` shows an update on iOS and it breaks it (flags it as broken on iOS) so new app installs won't get the latest version because it's flagged as broken.

I guess this could be solved by having two different apps instead of one, for each platform, but the docs don't say that.

Same thing happens when doing `code-push release-react myapp ios -b main.jsbundle`, it shows an update available on Android, and then flags it as broken, so if you want to install the latest update it wont, it won't install any update unless you release another update for Android.

* react-native-code-push version:  `1.16.1-beta`
* react-native version: 0.41.2
* iOS/Android/Windows version: latest
* Does this reproduce on a debug build or release build? either
* Does this reproduce on a simulator, or only on a physical device? both
* Repro steps and/or stack trace: explained above

**Comment by silhouettes** [comment]
@octohedron - Thanks for the issue, and apologies for the confusion! We've already tried to mention the need for an app for each platform in the docs wherever we could, but of course there still might be gaps. Could you be more specific about where we should add this clarification?

@max-mironov - When he replies, could you add that clarification there?
