### ISSUE TITLE
checkForUpdate  方法返回  {line:184,column:'4004',sourceURL:'index.android.bundle'}

### ISSUE THREAD

**Issue by qinghantang** [Microsoft/react-native-code-push#726]
这个错是怎么回事啊

**Comment by max-mironov** [comment]
@qinghantang - hi, if possible could you please rephrase the problem in English and try to provide us with more info like it is described [here](https://github.com/Microsoft/react-native-code-push/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by max-mironov** [comment]
@qinghantang, I'm closing the issue for now because of lack of description, please reopen or create a new one with more detailed repro steps if needed,
