### ISSUE TITLE
Android SDK version mismatch

### ISSUE THREAD

**Issue by ryankask** [Microsoft/react-native-code-push#733]
React Native uses version 23 of the Android SDK: https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/android/app/build.gradle#L86. 

When trying to compile the project for Android I'm receiving the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-code-push'.
   > failed to find target with hash string 'android-25' in: /usr/local/opt/android-sdk
```

This version requirement was recently changed because of #725 but requiring the newer version seems out of step with React Native's version.

I'm not an Android developer so perhaps I'm misunderstanding something but should this change be rolled back?

**Comment by sergey-akhalkov** [comment]
@ryankask, thank you for reporting the issue.
>This version requirement was recently changed because of #725 but requiring the newer version seems out of step with React Native's version.

Agreed, seems like there is an inconsistency, but I could see that the PR fixes this issue https://github.com/Microsoft/react-native-code-push/issues/724.
>I'm not an Android developer so perhaps I'm misunderstanding something but should this change be rolled back?

I also think it would be better to have one common version of Android SDK: the same both for React Native and React Native Module for CodePush, so I'll investigate and discuss this approach. As for now, to fix the issue you could try to download and install the `android-25` SDK's version. Please let me know if it helps.

**Comment by buptkang** [comment]
Hello @ryankask, thanks for pointing us this incorrect update. Yep, the current react-native supports up to android API level as 23, the react-native-code-push repo will sync with their upgrade.  In other word, the current version does not support Android SDK 7.0 and upper.

**Comment by silhouettes** [comment]
@ryankask - Just to keep you updated, @sergey-akhalkov will change it back to `23.0.1`, and we will publish a release this week. Thank you for filing this!

**Comment by ryankask** [comment]
@silhouettes Great! Thanks for following up.

**Comment by sergey-akhalkov** [comment]
Closing this due to #747 has been merged.
