### ISSUE TITLE
Question - Can I use 0.42.0 on Android?

### ISSUE THREAD

**Issue by yaronlevi** [Microsoft/react-native-code-push#744]
I saw a breaking change in android which deprecates JSBundleLoader.getSourceUrl()
Will it affect CodePush with 0.42.0?

**Comment by sergey-akhalkov** [comment]
Hello @yaronlevi, thank you for the question. 
I've verified RN 0.42 support here: https://github.com/Microsoft/react-native-code-push/pull/742 and all seems to be ok, please let me know if you see any issues while using `react-native-code-push` with RN 0.42

**Comment by yaronlevi** [comment]
Great! thanks... will check and report back

**Comment by yaronlevi** [comment]
Works great!
