### ISSUE TITLE
Failed to build DependencyGraph: @providesModule naming collision

### ISSUE THREAD

**Issue by rouge3351** [Microsoft/react-native-code-push#745]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens. Also exact reproduction steps and stack trace will be much appreciated.]

### Reproduction

[FILL THIS OUT: If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp. If you can't reproduce the bug on it, provide us as much info as possible about your project.]

### Additional Information

* react-native-code-push version:^1.17.0-beta
* react-native version:0.41.1
* iOS/Android/Windows version: on cli command process not in app
* Does this reproduce on a debug build or release build? no
* Does this reproduce on a simulator, or only on a physical device? no

(The more info the faster we will be able to address it!)

i have a trouble at this cli command
code-push release-react project-ios ios 
when i call this command failt to build with this message

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /project_dir/node_modules/react-native/package.json collides with /project_dir/ios/Pods/React/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /project_dir/node_modules/react-native/package.json collides with /project_dir/ios/Pods/React/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/rouge/workspace/like-hero-client/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/rouge/workspace/like-hero-client/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
[Error]  "react-native bundle" command exited with code 1.

i'm pod install and in pod folder have React project.
i don't know how to do..
please help me!

**Comment by sergey-akhalkov** [comment]
Hi @rouge3351, seems like you've got this issue due to `React` folder in `/project_dir/ios/Pods` directory. I could not see that folder in my `Pods` folder, so the issue does not reproduce. Please try to remove `/project_dir/ios/Pods/React` folder and let me know if it helps.
Also please make sure your Podfile has been configured properly. Here is contents of my own version of `Podfile`:
```Podfile
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
]

pod 'CodePush', :path => '../node_modules/react-native-code-push'
```

**Comment by rouge3351** [comment]
yes thank you!!! :)

**Comment by skizzo** [comment]
I run into this very same error with RN 0.57.7 and have no clue how to fix it. The only thing that works is deleting all folders and files created by code-push, and then restarting the packager. 

Any ideas how I could tell the bundler to just ignore the data created by code-push? Blacklisting the folder in `rn-cli.config.js` doesn't help, which strikes me as a bit weird too.

Thanks for any suggestions.
