### ISSUE TITLE
[Android] Upload aar to bintray

### ISSUE THREAD

**Issue by desmond1121** [Microsoft/react-native-code-push#746]
As the fact that not every company use RN to write whole app, Android and JS code always place in different directory. I think there is a better approach to get Android SDK in their project: upload Android sdk to bintray and users can compile them with gradle.  

In this approach, older version users would not change anything, but newbee of RN code-push can use gradle compile 'com.microsoft.codepush:react-native-code-push:x.x.x' to integrate sdk into their project. (Decoupling dependency of npm which not need for Android project).

**Comment by sergey-akhalkov** [comment]
Hi @desmond1121, thanks for reaching us and sorry for late reply. 

Could you please clarify (add details) about workflow that will include bintray in build process and how we can help you with this (what should we implement / add support for)?

Please let me know if you have any questions or see any issues.

**Comment by sergey-akhalkov** [comment]
Hi @desmond1121, I'm closing this for now, please feel free to reopen if any updates.
