### ISSUE TITLE
Warning from Apple

### ISSUE THREAD

**Issue by quentinyang** [Microsoft/react-native-code-push#748]
I received a warning from Apple this morning , it seems that, App Store doesn't allow developers to use the updates, how to solve it?

> 
> Dear Developer,
> 
> Your app, extension, and/or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with section 3.3.2 of the Apple Developer Program License Agreement and App Store Review Guideline 2.5.2. This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes.
> 
> This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.
> 
> Please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above before submitting the next update for your app for review.
> 
> Best regards,

**Comment by BretJohnson** [comment]
Does your app use Rollout.io or any other code update technologies beyond CodePush itself?

**Comment by ajwhite** [comment]
I'm a bit speculative that this response from Apple is particular to CodePush.

For clarity, as I'm sure there will be developers verifying the effect on CodePush, the current guidelines from Apple are:

>Apple’s guidelines explicitly permit you to push executable code directly to your app, bypassing the App Store, **under these two conditions:**
> 1. The code is run by Apple’s built-in WebKit framework or **JavascriptCore**
> 2. The code **does not provide**, unlock or enable **additional features or functionality**

CodePush adheres to these guidelines. Rollout and JSPatch provide a framework for Javascript to execute any arbitrary native code. CodePush does not operate under these conditions.

**Comment by BretJohnson** [comment]
@quentinyang We suspect your app is using JSPatch. Can you confirm that. Thanks.

**Comment by TyrealGray** [comment]
https://github.com/facebook/react-native/issues/12778

**Comment by sriraman** [comment]
I'm using only CodePush. We didn't use anything frameworks like Rollout.io or JSPathc. Still, My app got rejected by apple with the same warning from Apple today.

**Comment by silhouettes** [comment]
For others looking at this issue, I am linking it to an equivalent issue in the RN repo which is more up-to-date: https://github.com/facebook/react-native/issues/13011. It seems unlikely that CodePush is the issue here.

**Comment by quentinyang** [comment]
I use codepush and others SDK, but no JSPatch.

**Comment by silhouettes** [comment]
@quentinyang could you list the iOS packages that you are currently using? This may also help the investigation in the linked issue.

**Comment by imWildCat** [comment]
@quentinyang Chinese SDK? https://github.com/bang590/JSPatch/issues/751
These fuxxing SDKs contained JSPatch. They played the evil.

**Comment by sergey-akhalkov** [comment]
I'm closing the issue now as it turns out that code-push is valid for using with app store. Will reopen this one if any changes.
