### ISSUE TITLE
Feature Request - Signing bundles

### ISSUE THREAD

**Issue by ajwhite** [Microsoft/react-native-code-push#749]
Security is an important concern for our b2b application, and as such, we had performed some research in how CodePush enforces security with HTTPS and requiring access keys (https://github.com/Microsoft/react-native-code-push/issues/708) to publish and receive updates.

These are good measures in ensuring secure transmission of content, but I'd like to propose an optional step that applications can take in additional security: **Signing application bundles**.

### Goal

Increase security by signing application bundles before they are transmitted to Code Push, and verifying the bundle within the application upon receipt.

### Process

The process, as I see it, would be relatively straight forward in theory for how applications are traditionally signed. We'd take this approach to the Javascript bundles as well.

A key pair would be created by the developer, where a public key is shared with CodePush's service, and a private key is shared with the CodePush SDK within the application.

1. A developer creates a key pair, and registers it with CodePush.
  `code-push app add-key <private key path> <public key path>`
  The local cli registers the location of the private key for creating releases, and uploads the public key to the CodePush services. 
2. The public key is added to the project and configured with the `CodePush` SDK.
3. When uploading a release, the bundle is signed with the private key registered with the local CLI.
4. When CodePush receives a release, the bundle is verified by the public key.
5. When the application receives the release, the application can verify the bundle with the public key.

**Comment by silhouettes** [comment]
Hey @ajwhite, we've recently begun reviving our investigation into a code signing feature. Our original plan is something like this: https://github.com/Microsoft/code-push/issues/307#issuecomment-242824845. Do you have any thoughts on that approach as compared to yours? My thoughts at the time were that we didn't need to store anything on the server at all, that way in the unlikely event that the server was compromised there would still be nothing that could be done to forge a release.

**Comment by ajwhite** [comment]
> My thoughts at the time were that we didn't need to store anything on the server at all, that way in the unlikely event that the server was compromised there would still be nothing that could be done to forge a release.

Great point, the real value is in the process of signing the bundle, and verifying the bundle within the application. If it gets an untrusted bundle, it will simply reject it. The server-side validation really doesn't play a critical role here, and as you mention, opens up its own vector.

Agreed on this point 👍

**Comment by sergey-akhalkov** [comment]
Closing this for now due to discussion have place in https://github.com/Microsoft/code-push/issues/307.
Please feel free to reopen if needed.
