### ISSUE TITLE
release-react【Error】Not Found

### ISSUE THREAD

**Issue by 438198602** [Microsoft/react-native-code-push#753]
Hi, guys!
I have a problem，when I run “code-push release-react MyApp android -d Production”，it throw 【Error】Not Found。Who can save me？thanks……

**Comment by max-mironov** [comment]
Hello @438198602 thanks for posting an issue, a couple of questions:
a) What version of code-push cli/react-native you are on? Do you see any issues with other commands (like code-push app ls/ code-push deployment history MyApp Production etc?
b) Are you able to reproduce this on our [Sample ](https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp)app, or it is not working there either?

**Comment by 438198602** [comment]
@max-mironov  
a)：My code-push is 1.12.8-beta， react-native 0.41.2，code-push app ls/code-push deployment history MyApp Production is work。
b)：Someone else to build the server, he can be successful, my error。

**Comment by max-mironov** [comment]
@438198602 is it possible for you to ping me via skype so it would be easier to determine the issue? (my skype id is max.mironov89)

**Comment by max-mironov** [comment]
@438198602 btw just a guess - may your issue be related to something like this?
- http://stackoverflow.com/questions/37189081/react-native-command-not-found
- http://stackoverflow.com/questions/32253981/path-error-while-installing-react-native-command-not-found-error 
Have you tried to uninstall and re-install node-npm and reinstall  react-native-cli?

**Comment by 438198602** [comment]
Thank you, but now I have encountered other problems with the React Native, I need to solve this problem。after that, I will try what you say for code-push.Thank you very much！

**Comment by 438198602** [comment]
@max-mironov 
Thank you, but now I have encountered other problems with the React Native, I need to solve this problem。after that, I will try what you say for code-push.Thank you very much！

**Comment by 438198602** [comment]
@max-mironov  OK，you can close this issue for now.
