### ISSUE TITLE
typo in code snippet 

### ISSUE THREAD

**Issue by palaniraja** [Microsoft/react-native-code-push#756]
### Description

Typo in code snippet, for some reason copy paste to deploy to ios seems to work, where as it caught me when I try the same for android.

URL: https://microsoft.github.io/code-push/docs/tutorials.html
Section: UPDATE DIALOG CUSTOMIZATION

Code:
   ` codePush.sync({ updateDialog: updateDialogOptions};`

Corrected:
    `codePush.sync({ updateDialog: updateDialogOptions});`

### Reproduction

N/A

### Additional Information

* react-native-code-push version: N/A
* react-native version:N/A
* iOS/Android/Windows version:N/A
* Does this reproduce on a debug build or release build?N/A
* Does this reproduce on a simulator, or only on a physical device?N/A

**Comment by max-mironov** [comment]
@palaniraja thanks for pointing at this, we've fixed typo.
