### ISSUE TITLE
[iOS] - Crash on initial launch during first sync only

### ISSUE THREAD

**Issue by kevinhylant** [Microsoft/react-native-code-push#757]
### Description
A.)  After upgrading from an older version of CodePush to 1.17.2-beta to maintain compatibility with a required react-native upgrade (see deps below), we began to experience crashes on the first launch of the app when syncing CodePush (stack trace below) 

![pasted_image_at_2017_03_14_03_18_pm_480](https://cloud.githubusercontent.com/assets/7389576/23919426/2d88be22-08cd-11e7-8458-9c01dba1f818.png)

B.) I then went back to your GettingStarted on iOS instructions for a brownfield app wherein react-native link doesn't work & followed the manual installation instructions.
1.) Added Code-push xcode prject file into Libraries
2.) Added libCodePush.a to Link Binary with Libraries in Build Phases

Attempted to rebuild (after cleaning build & deleting derived data) and got a build error about some codePushLib.h (sp*( header missing. The header import linked was formatted with the "codePushLib.h" styling, not <codePush...h>

C.) I then updated our header search paths to include each our `Libraries` recursively & `node_modules/react-native-code-push` recursively.

Rebuilt - failed with the following:
![image](https://cloud.githubusercontent.com/assets/7389576/23919790/a3a14c86-08ce-11e7-80f6-3e94bd499b2f.png)

D.) Then added `node_modules/react-native` (recursive) to our header search paths

Rebuilt with the same error.

**Thanks in advance for the debugging help!!**

### Reproduction

[FILL THIS OUT: If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp. If you can't reproduce the bug on it, provide us as much info as possible about your project.]

### Additional Information

package.json dependencies:
```
"dependencies": {
    "json-server": "0.9.4",
    "react": "15.4.2",
    "react-native": "0.42.0",
    "react-native-code-push": "1.17.2-beta",
    "react-native-i18n": "1.0.0",
    "uglify-js": "2.8.9"
  },
  "devDependencies": {
    "code-push-cli": "1.12.9-beta",
    "yarn": "0.20.4"
  }
```
* iOS version: 10.1
* Does this reproduce on a debug build or release build? **both** - but only on first app launch 
* Does this reproduce on a simulator, or only on a physical device? **both**

**Comment by silhouettes** [comment]
@max-mironov Please investigate this one as soon as you are able!

**Comment by max-mironov** [comment]
Hello @kevinhylant can you please clarify - you are unable to build the app with xCode and got an error with 

> React/RCTBridge.h not found

 (make sure that all steps from [here ](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---manual)are completed)?
Or you can build the app with xCode and deploy to the device but it crashes when you call `sync` method for update? But only first time, so subsequent `sync` calls will work?

**Comment by kevinhylant** [comment]
@max-mironov  I can confirm that I completed all of those steps. 

Originally (see **A.)**, Xcode was able to build the project successfully, but once distributed to devices the build crashes on `sync`

Then after completing steps, B -> D, Xcode builds failed with `React/RCTBridge.h not found` as the reason

**Comment by max-mironov** [comment]
@kevinhylant just to double check that on step B-1 you are adding correct node_modules/react-native-code-push/ios version of react-native-code-push (so you have removed the previous one and installed the latest with `npm install` command). Seems that something goes wrong after step B-2 and I've tried to repro this by manually removing - installing react-native code-push and updating react-native with npm install and seems it works fine,

**Comment by kevinhylant** [comment]
Yes. I am using yarn@0.20.3 and have removed the old version entirely

**Comment by max-mironov** [comment]
@kevinhylant got it, thanks. I've googled about this problem, what I've found so far and you can possibly try do look at:
http://stackoverflow.com/a/41488258
https://github.com/facebook/react-native/issues/12042#issuecomment-275025960

Also I believe that adding references to header search paths is not really needed, so may be it make sense to try to reinstall code push plugin and see if it helps. If it is possible for you to share (or reproduce this on small example) the app so we can try to build on our side - it would be great.

**Comment by max-mironov** [comment]
@kevinhylant, do you have a chance to look at this? Please let us know if you still face the issue.

**Comment by max-mironov** [comment]
@kevinhylant  - I'm closing the issue for now, please reopen or create a new one if you still have this problem.

**Comment by kevinhylant** [comment]
Thank you for being so diligent with your responses on this issue - sorry for my very slow response - I had been on vacation. I will review your links and let you know if I need any further assistance / provide additional information if relevant.
