### ISSUE TITLE
Is there a way to get the deployment name (Staging/Production/etc)?

### ISSUE THREAD

**Issue by j2kun** [Microsoft/react-native-code-push#764]
### Description

After calling `codePush.getUpdateMetadata(codePush.UpdateState.RUNNING)` I want to display (for debugging purposes) the name of the deployment that codepush is pulling from. Is this possible without a new feature? (You provide the deployment key, but I'd prefer not to do the reverse lookup because that would require hard-coding the deployment keys in my JS)

**Comment by silhouettes** [comment]
@j2kun - not without additional work, unfortunately. You could possibly put the name of the deployment as a property in your Info.plist, immediately below where the deployment key is specified.

**Comment by j2kun** [comment]
@silhouettes I see. My use case is in dynamically changing the deployment, so this won't work. I'd be happy to contribute a PR, but it seems the server side is private?

**Comment by silhouettes** [comment]
Yes, it is private unfortunately :( Could you maybe use whatever mechanism you are using to dynamically get new deployment keys, to also feed the new deployment name?

**Comment by j2kun** [comment]
@silhouettes It's not a huge deal. I was testing that mechanism, and it just taking extra steps to go through the `code-push-cli` deployment history to match up the version numbers with what is reported by `getUpdateMetadata`.

Anyway, consider the feature requested :) Hope it's an easy one :)

**Comment by silhouettes** [comment]
Thanks @j2kun, your feedback is appreciated! We'll keep an eye out for similar requests.
