### ISSUE TITLE
App not updating after update is avaliable and is resumed

### ISSUE THREAD

**Issue by nerdmed** [Microsoft/react-native-code-push#766]
### Description

The app is not switching to the downloaded JS bundle after several restarts. The download is working and calling the `getUpdateMetadata` function its telling me about the correct version.

```js
codePush.getUpdateMetadata(codePush.UpdateState.PENDING).then((localPackage) => {
    console.log('Current update', localPackage);
});
```
My main component is wrapped with the setting `ON_APP_RESUME`

```js
const codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_RESUME };
export default codePush(codePushOptions)(MyApp);
```

This is the logs i get on the first start:

```js
2017-03-24 19:50:57.087 [info] [CodePush] Downloading package.
2017-03-24 19:50:58.580 [warn][RCTEventEmitter.m:54] Sending `CodePushDownloadProgress` with no listeners registered.
2017-03-24 19:50:58.699 [info] [CodePush] Installing update.
2017-03-24 19:50:58.702 [info] [CodePush] Update is installed and will be run on the next app restart.
```

Restarting also after a coulpe of minutes will just log:
```
[CodePush] Checking for update.
[CodePush] App is up to date.
```

When i run `codePush.restartApp(true)` it updates. but as i have set the frequency to `ON_APP_RESUME` i expect the update to be applied on a resume or am i wrong?

Calling the sync with the immediate option is also not restarting immediatly:
```
codePush.sync({
    updateDialog: true,
    installMode: codePush.InstallMode.IMMEDIATE,
});
```

### Additional Information

* react-native-code-push version:
* react-native version: 0.42.0
* iOS/Android/Windows version: latest 
* Release-Build
* Happens on the simulator and the device

**Comment by max-mironov** [comment]
@nerdmed - hi again, do you have a chance to look at this?

**Comment by nerdmed** [comment]
@max-mironov sorry did not come to this as my workaround works for now. I will check it with my next release probably at the end of the week and try out your suggestions

**Comment by max-mironov** [comment]
@nerdmed - please let us know if you have any updates about this :)

**Comment by nerdmed** [comment]
@max-mironov thanks again for your support. Finally got it running but i had to change the code a little. For me it works with the following:

```
const codePushOptions = {
    checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
    installMode: codePush.InstallMode.ON_NEXT_RESUME,
};

export default codePush(codePushOptions)(MyApp);
```

Exporting first and then applying codePush does not work. Adding the installMode fixed the problem.

**Comment by max-mironov** [comment]
@nerdmed thanks for heads up, this will be useful for further reference if we get the same error. Thanks again, appreciate it!
