### ISSUE TITLE
How about native changes (need rnpm link)?

### ISSUE THREAD

**Issue by just4fun** [Microsoft/react-native-code-push#767]
I have an APP in App Store, and its version is `1.0.0`.

During these months, I pushed some changes (v1, v2) via `react-native-code-push` to fix some bugs.

In addition, I have also finished some new features, which contains some native changes (need rnpm link).

Now I want to submit new version `2.0.0` to App Store.

Here is question, if I push some changes (v3) via `react-native-code-push` to fix issues for `2.0.0` later, for the users who won't download `2.0.0` from App Store, I think they will also receive `v3` ? Then the APP in their devices will crash I think, b/c `v3` also includes JS changes from the new version `2.0.0`, but user can not receive the native changes.

Is that right, or is there anything I misunderstood?

**Comment by max-mironov** [comment]
Hi @just4fun, according to this https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter it is ok to release updates only to v.2.0.0 and users that are running earlier version will not be affected.

>This specifies the store/binary version of the application you are releasing the update for, so that only users running that version will receive the update, while users running an older and/or newer version of the app binary will not. This is useful for the following reasons:

> 1. If a user is running an older binary version, it's possible that there are breaking changes in the CodePush update that wouldn't be compatible with what they're running.

> 2. If a user is running a newer binary version, then it's presumed that what they are running is newer (and potentially incompatible) with the CodePush update.

**Comment by just4fun** [comment]
Thanks @max-mironov , it helps!

**Comment by just4fun** [comment]
Hey @max-mironov , I faced another issue when I want to release v2.0.0 which contains native changes as I mentioned above.

It is that the production release with code-push before has no `target-binary-version-parameter` set, that said if I release v2.0.0 to App Store, users with new app version will also receive the old updates.

I think there are two ways to resolve it.

- Release a new update with code-push and set `target-binary-version-parameter` to v2.0.0, then when users update to new app version, they will receive the update, but old version users will not.
- Clear release history for Production, then re-push an update for old version v1.0.0 with `target-binary-version-parameter`, then old version users will still receive updates, but new version users will not.

Please let me know if you have any thoughts or I misunderstood anything.

**Comment by max-mironov** [comment]
Hey @just4fun, if you use `code-push release-react` command than (more details [here](https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-react-native)) the following behavior will be performed:
TargetBinaryVersion of this release will be inferring by using the version name that is specified in your project's Info.plist (for iOS) and build.gradle (for Android) files. 

So there is no need to set up target binary version explicitly unless you want to change the default behavior. Also if you use [general](https://github.com/Microsoft/code-push/tree/master/cli#releasing-updates-general)  command to release updates it will not be allowed  to release unless you set up target binary version on your own.

You can always verify which version your release belong to by executing the following command:
`code-push deployment history AppNAme DeploymentName` -> App Version column.

Please let us know if it solves your question.

**Comment by just4fun** [comment]
@max-mironov thank you.
