### ISSUE TITLE
[Android]App of updated slower

### ISSUE THREAD

**Issue by coutliuxing** [Microsoft/react-native-code-push#772]
Similar to this guy I met problems https://github.com/Microsoft/react-native-code-push/issues/739, but his problems have been left out, so I submit once again.After you finish the update won't appear this kind of problem?After the update, as is in debug mode.

**Comment by sergey-akhalkov** [comment]
Hi @coutliuxing, if you don't mind, let's discuss the issue here https://github.com/Microsoft/react-native-code-push/issues/739, I just want to avoid duplication.

Closing this due to we already have the similar issue.
