### ISSUE TITLE
CodePushDeploymentKey added to GoogleService-Info.plist instead of Info.plist file

### ISSUE THREAD

**Issue by jordanmkoncz** [Microsoft/react-native-code-push#774]
### Description

I've just followed the CodePush setup instructions from scratch, with `"react-native-code-push": "^1.17.3-beta"` being installed, and after running `react-native link react-native-code-push`, `CodePushDeploymentKey` is added to `GoogleService-Info.plist` instead of the `Info.plist file`. This appears to be the same issue as https://github.com/Microsoft/react-native-code-push/issues/661#issuecomment-291060801.

I have a fairly standard React Native iOS app. I've added some Firebase services, which is why I have a `ios/MyApp/GoogleService-Info.plist` file alongside the usual `ios/MyApp/Info.plist` file. 

### Additional Information

* react-native-code-push version: 1.17.3-beta
* react-native version: 0.41.2

**Comment by max-mironov** [comment]
Hello @jordanmkoncz, thanks for filling the issue.
You can help us to determine the issue more quickly by doing the following:

All "magic" of searching correct plist path is done here: ./node_modules/react-native-code-push/scripts/postlink/ios/postlink.js.

So [here ](https://github.com/Microsoft/react-native-code-push/blob/master/scripts/postlink/ios/postlink.js#L54)we try to determine correct path for plist file.
Can you add right before [this](https://github.com/Microsoft/react-native-code-push/blob/master/scripts/postlink/ios/postlink.js#L137) line one more `console.log('Couldnt find xcode project, return the default value`) statement so we can be sure if we are not failing here when calling `react-native link react-native-code-push`.

I believe other cases will be caught by `console.log` statements, so we will be able to determine what is going wrong by looking for the output.

The next place where you may fail to get correct plist path is [here](https://github.com/Microsoft/react-native-code-push/blob/master/scripts/postlink/ios/postlink.js#L163).

This logic is pretty good described by the comment above, so you need to verify the following:
Open your project.pbxproj file in any text editors and find `INFOPLIST_FILE` occurrences. Check here what is plist path here (may be you could also share with us your project.pbxproj file so we can verify this on our side also).
Please let us know the results.

**Comment by max-mironov** [comment]
@jordanmkoncz please let us know if you have a chance to look at this.

**Comment by jordanmkoncz** [comment]
Hey @max-mironov, sorry I've been super busy and haven't had a chance to get back to about this. Should be able to get that extra info for you later this week.

**Comment by max-mironov** [comment]
@jordanmkoncz np, that's ok, thanks for heads up! Will wait for your response.

**Comment by max-mironov** [comment]
@jordanmkoncz, just gentle ping on this :)

**Comment by max-mironov** [comment]
@jordanmkoncz if you don't mind I'll close it for now, please reopen when you have a chance to revisit it.

**Comment by merryejik** [comment]
I have the same situation.
In console I get: 
'Could not determine correct xcode proj path to retrieve related plist file, there are multiple xcodeproj under the solution.'
Some paths from xcodeProjectPaths:
'ios/Pods/Pods.xcodeproj/project.pbxproj',
'ios/reactapp.xcodeproj/project.pbxproj'
So you are looking in subfolders too.

INFOPLIST_FILE in my project 'reactapp/Info.plist'

**Comment by ruslan-bikkinin** [comment]
Hi @merryejik and thanks for reaching us. Please fill new issue so we could help you.
