### ISSUE TITLE
Support for React Native Unbundle

### ISSUE THREAD

**Issue by panarasi** [Microsoft/react-native-code-push#778]
Just like the bundle command, React Native also has an `unbundle` command, using `$ react-native unbundle`. Code-Push should also be able to support unbundled files.

Today, `code-push release-react` calls `react-native bundle` under the covers. For unbundling, we could see if we can reuse the `code-push` release command that can take in the folder that a user may have created using `react-native unbundle` command. Since codepush already supports bundling multiple files and assets, this should technically work, and we may just want to document how this can be achieved. 

Note that this is low priority.

**Comment by pniko** [comment]
Currently not something we are planning to execute on. If there is more demand for it we will re-investigate.

**Comment by prateekkohli1989** [comment]
I think code push should start supporting React Native unbundle. In android, jsbundle took time for initialization, with unbundle it is quick and took less than 1s to load the app.

**Comment by skizzo** [comment]
Any updates on this?

**Comment by vivek-walecha-657** [comment]
any updates on this?
