### ISSUE TITLE
Apple Watch support

### ISSUE THREAD

**Issue by skleest** [Microsoft/react-native-code-push#789]
Hi Code Push team,

Following up on our email conversation--opening up an issue to support Watch extension apps on iOS. Thanks!

**Comment by sergey-akhalkov** [comment]
Hi @skleest, could you please confirm if the issue has been fixed to you by [this PR](https://github.com/Microsoft/react-native-code-push/pull/783)?

Please let me know if you have any questions or see any issues.

**Comment by skleest** [comment]
@sergey-akhalkov Thanks for the update--will check ASAP.

**Comment by sergey-akhalkov** [comment]
@skleest, I'm closing this for now, please feel free to reopen if needed.

**Comment by skleest** [comment]
Hi @sergey-akhalkov Thanks for the update--it is working well on production env.

I'm having trouble using this on staging environment, getting the following error:
"/Users/SLEE/Library/Developer/Xcode/DerivedData/Aura-drnguqqakspmosfmqlphgdyhukcr/Build/Products/Staging-watchos/AuraWatch.app: No such file or directory"

Seems like Staging-watchos part is the problem, I'm guessing I have to change build settings somewhere for the watch app. Looked around for a while but couldn't find anything, any ideas?

**Comment by sergey-akhalkov** [comment]
Hi @skleest, thanks for reaching out to me. It is difficult to say what goes wrong here without exact reproduction steps or app sample where the issue reproduces.
Have you configured your staging env using [this article](https://github.com/Microsoft/react-native-code-push#ios)? If not, please go thru it and check if everything has been configured cofigured correctly.

Please let me know if any updates or if you have any questions.

**Comment by skleest** [comment]
Thanks @sergey-akhalkov--yes, I overcome other errors (e.g. library not found), but this one seems specific to the watchos seeing that /Staging-watchos/ folder doesnt exist. Is there a way to change that path to Production?
