### ISSUE TITLE
[Android]: when the app version scheme is like "2.0.0-beta", can't find update

### ISSUE THREAD

**Issue by rahuljiresal** [Microsoft/react-native-code-push#791]
### Description

When the version of the Android app is something like 2.0.0-beta (we have that version scheme for internal versions), CodePush always returns `An update is available but it is not targeting the binary version of your app.`. This happens even if you specify `"*"` in `code-push release`.

### Reproduction

Just rename the version scheme to have some text like mentioned above and you got the bug.

**Comment by max-mironov** [comment]
Hello @rahuljiresal, code-push uses [semver](https://github.com/npm/node-semver) package internally as a semver parser, so for version `2.0.0-beta` this check `semver.satisfies('2.0.0-beta', '*')` returns `false`.

You should release an update with version `2.0.0-beta` if you are going to target prerelease tags in your updates.
Please let us know if it helps.

**Comment by max-mironov** [comment]
Also please see https://github.com/Microsoft/code-push/issues/335 for more info.

**Comment by max-mironov** [comment]
@rahuljiresal, I believe we can close the issue now, please let us know if any questions.
