### ISSUE TITLE
[Android] It seem to be case codePush.SyncStatus.DOWNLOADING_PACKAGE not run?

### ISSUE THREAD

**Issue by lelup** [Microsoft/react-native-code-push#797]
I used progress bar and codePush for my app, in iOS it worked fine but in ANDROID my Launch screen show nothing.  
How can I fix it? My code below:

![screen shot 2017-04-17 at 10 14 51](https://cloud.githubusercontent.com/assets/19283388/25077751/e927d46c-2356-11e7-9681-f1a4734801b2.png)
![screen shot 2017-04-17 at 10 15 16](https://cloud.githubusercontent.com/assets/19283388/25077753/eb4c56f0-2356-11e7-92f2-2ec2390c1950.png)

I log 2 state showDownloadingModal, showInstallingModal when run code-push release-react myApp android and it always false.

**Comment by sergey-akhalkov** [comment]
Hello @lelup, thank you for reaching us. I've just tried to reproduce the issue but with no luck. Could you please take a look at our [sample app](https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp) and verify if it works for you? You also could [find there](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/demo.js#L20) the way we are using to show current sync status.

**Comment by lelup** [comment]
@sergey-akhalkov Thanks for your support!
By the way, I would like to ask you :
Is there any way to change the language of Alert updated when I run code-push?

**Comment by sergey-akhalkov** [comment]
@lelup, [here is the dialog options](https://github.com/Microsoft/react-native-code-push/blob/master/typings/react-native-code-push.d.ts#L158) that you can customize, just like this:
```Json
{ "updateDialog": { "title": "My title",  } }
```
Please let me know if you have any questions or see any issues.

**Comment by lelup** [comment]
yep! many thanks @sergey-akhalkov

**Comment by sergey-akhalkov** [comment]
@lelup, no problem! I'm closing this for now, please feel free to reopen in case of any questions or issues.
