### ISSUE TITLE
Warnings and Additional Feedback

### ISSUE THREAD

**Issue by rhaker** [Microsoft/react-native-code-push#80]
Thanks for putting this together. I've been doing more testing and it seems that my understanding was correct in my comment last week at https://github.com/Microsoft/react-native-code-push/issues/54. You can probably close that issue.

As I mentioned, I would provide some additional color. Overall, it's really nice and I've been able to get up and running quickly.

Specs: Running React Native 0.14.2, ios (testing android next), Xcode 7.1, code push 1.2.1-beta

1) Npm warning when installing the cli asking for node version 0.X instead of Node 4.X (which is what React Native uses). Not a big deal, of course. Install works nevertheless.

2)  Implicit conversion warning during archive in CodePushDownloadHander.m for self.expectedContentLength. Again, not a big deal. Warning only during archive.

3) Website documentation (https://microsoft.github.io/code-push/docs/react-native.html) - has a few things that were confusing. The command: code-push release <appName> <deploymentName> ./ios/main.jsbundle <appVersion> doesn't have the --deploymentName tag (Not sure if it's needed). Again not a big deal. I'm still a little confused about Staging vs Deployment and what the exact difference is (e.g. what happens if you forget and keep your Staging Key in info.plist and submit to the App Store, can you still do Production level releases?)...

I'll stop here because it's already not a great idea to put all this in 1 issue and these aren't really issues (more like questions) and I don't want to waste your time. All the best.

**Comment by lostintangent** [comment]
Any feedback is hugely valuable, so always feel free to send as many comments/questions/etc. our way, and rest assured it will absolutely be worth our time :)

Regarding your questions:

1. Yes, we should absolutely update this. I'll use this issue to track the fix
2. Fully agreed. I've been seeing this a lot lately and it has annoyed the heck out of me :)
3. Good point. I'll add a mention of the --deploymentName parameter to the release section. The CLI docs call it out, and mention that it defaults to "Staging" if omitted, but I agree it would be helpful to mention a little bit about it in the RN docs as well.

Regarding your question about Staging vs. Production deployments, there is nothing functionally different about them. Their names are just arbitrary strings that we assigned to them, and in fact, you could rename Staging to "Foo" and Production to "Bar" and it wouldn't make any difference. The friendly names are just there to make it easier to release an update from the CLI to a specific "channel" that you intend to.

I'm in the process of writing up some docs that explain the various "strategies" that deployments can be used for a little more clearly. We basically recommend that you always test out the E2E update process before pushing it out to end-users, and to achieve that, doing a release to Staging, and then promoting from Staging to Production allows you a high degree of confidence that what you're sending out to customers will work as expected.

If you were to accidentally send out a binary to the public store that was configured to use your Staging deployment key, you could simply rename it to "Production" (or whatever you would like) and use that key for those purposes.

**Comment by rhaker** [comment]
Jonathan, thanks for the words. As I said above, CodePush is really well done (and the issues above are super low priority). I'm in the process of building on android, so I should have android-specific feedback for you in the next few weeks.

With respect to deployment v. staging, your response is really helpful. I was worried there were some sort of sandbox limits imposed on Staging that could cause an issue - because I'm constantly switching between emulator/device and dev/release. I need to figure out some way to automate better...

With respect to #54, the approach makes a lot of sense. I read on one of the other issues about rolling back a problematic release. Do you have any best practices on rollbacks? For example, if I do several patches (code-push releases) on a v0.1.10, is there any way to roll back to a specific one (since they are all named 0.1.10), or is it better just to push out a new release with a forced update?

**Comment by lostintangent** [comment]
Right now, we would just recommend pushing out a new release. That said, we're planning to add support for doing actual rollbacks via the CLI, which would have the effect of creating a new release that used the code/metadata of the specified update. For example, if you simply called `code-push rollback APP_NAME DEPOYMENT_NAME`, it would create a new release whose contents/metadata was equivalent to the previous, so it's effectively automating the process you could achieve today, but making it much less error prone. Additionally, you could call `code-push rollback APP_NAME DEPLOYMENT_NAME RELEASE_LABEL` to rollback to a specific release, if for some reason you wanted to "jump back" a few releases. The "label" value would come from the label property that we auto-gen for each release, which you can see by running `code-push deployment history APP_NAME DEPLOYMENT_NAME`.

Let me know what you think about that proposal. Our hope is that it would be a simple but nice feature to achieve what you could do manually (e.g. release a new version that uses the old code), but quicker :)

**Comment by rhaker** [comment]
That makes sense. 

To me, the value of rollbacks is during the firedrill period when you've realized there's a bug, but don't have the solution to push out a "forced update" new release. You don't want to think about creating a new release, you just want to quickly rollback and spend time finding the bug. In practice, rolling back to the previous version will probably cover 99 percent of the cases.

I haven't looked at the RELEASE_LABEL and don't know how human-readable it is. I was imagining some sort of message analogous to the git commit -m "This is the Release Label" message, where you could attach a human readable string on each CodePush release to distinguish one from another. But this may be overkill and it's always easy to say things and not have to implement them. A RELEASE_LABEL that shows the diffs or something might be more than sufficient. The main issue is if you've done 30 CodePushes for the latest App Store binary, will you be able to distinguish one from the other with the RELEASE_LABEL?

**Comment by lostintangent** [comment]
The release label is an incrementing integer that is unique to the deployment and increases monotonically each time you release to CodePush (including promotions as well as rollbacks). The first release's label is "v1", the second is "v2" and so on. The label is primarily meant to identify the release in your history (when running `code-push deployment history`), as well as an identifier for things like crash reporting/analytics so you know the CodePush version along with the app store version when looking at telemetry data. The label is auto-generated by CodePush whenever you release and you can't modify it.

The description on the other hand, is a customizable/arbitrary string that you can add to the release when you release, and you can view when you look at history.

Therefore, the label and the description would both allow you to distinguish each release to CodePush, as long as you use the description to represent a semantically meaningful string (e.g. a feature addition, a bug number, a Git commit SHA).

I'd be really interested in any feedback here.

**Comment by lostintangent** [comment]
BTW, here is screenshot example of calling the release history command. The label column is the release label I mentioned above, and the circled string represents a value I passed to the `description` parameter when calling the `release` command. I didn't specify a description with the other releases, which is why their description column is blank:

![screen](https://cloud.githubusercontent.com/assets/116461/11547493/3e93253e-9909-11e5-946f-3a8f2de14c28.PNG)

**Comment by rhaker** [comment]
Ah, that's beautiful. The description field is exactly what I was thinking about - and I need to start using it in my CodePushes because I didn't know about it (or didn't read the docs carefully enough). 

I can imagine some sort of future scenario where you can release a bunch of different versions and be able to do some sort of intelligent mapping based on the version (and the description would quickly tell you what's in the release for the mapping). For example, you could do geo-filtering based on IP, where you could push a North American version with a description "North America production release" to IP-filtered North American users and then you could rollback those users to a "Global production release" if there was some sort of bug. Basically, you could use the deployment history as a mini-dashboard for analytics and release planning (and targeted production rollback). [Note: I'm probably overlapping some of the Staging vs Deployment current functionality here.]

FYI, I know this isn't implemented and probably requires drastic technical manipulation. It's just a quick brainstorm.

All the best. Good luck with this.

**Comment by lostintangent** [comment]
I like how you're thinking! :) We are very interested in doing smarter deployment strategies like this once we've nailed the core scenarios (e.g. we need rollback, support RN assets).

**Comment by lostintangent** [comment]
Hey @rhaker, FYI the implicit conversion issue was fixed with #82.

**Comment by rhaker** [comment]
Nice. I'm going to close this issue - so it's one more thing off your plate.
