### ISSUE TITLE
Can't seem to get CodePush to work in iOS release or staging build (RN v0.43.3)

### ISSUE THREAD

**Issue by ndbroadbent** [Microsoft/react-native-code-push#802]
### Description

I followed all of the instructions to set up CodePush, and everything is working fine in Android. But it seems to be failing silently iOS, so I have no idea what I need to change. I am testing in the iOS Simulator, using the "Staging" configuration that I set up while following the [multi-deployment instructions](https://github.com/Microsoft/react-native-code-push/blob/master/README.md#multi-deployment-testing).

Logs from `code-push debug android`:

```
Listening for android debug logs (Press CTRL+C to exit)
[05:01:13] Loading JS bundle from "/data/user/0/com.ndbroadbent.myapp/files/CodePush/194f17abf7e68e43e25267b82e1af0ffbf7b81be5c3962f5cf4efc5af300d4ee/CodePush/index.android.bundle"
[05:01:14] Checking for update.
[05:01:16] App is up to date.
```

Logs from `code-push debug ios`:

```
Listening for ios debug logs (Press CTRL+C to exit)
[05:02:26] Loading JS bundle from file:///Users/ndbroadbent/Library/Developer/CoreSimulator/Devices/31A8CD96-6A3E-4082-92AD-180C5DD86CF1/data/Containers/Data/Application/F0A5E217-DC4C-4B5F-B157-AB628B32B75F/Library/Application%20Support/CodePush/e89fb5ef8de979b5bf615225f59103b36e790a9f088c4efea6cc986e813bbd71/CodePush/main.jsbundle
```

And that's all, there are no update messages. 

When I run `code-push deployment ls myapp-ios`, I was seeing `No installs recorded` for a very long time. But now I am seeing some activity:

```
├────────────┼───────────────────────────────────┼──────────────────────┤
│ Staging    │ Label: v6                         │ Active: 29% (2 of 7) │
│            │ App Version: 1.0.0                │ Total: 2 (1 pending) │
│            │ Mandatory: No                     │                      │
│            │ Release Time: 26 minutes ago      │                      │
│            │ Released By: myemail@example.com  │                      │
└────────────┴───────────────────────────────────┴──────────────────────┘
```

I guess that means something is going through, but I would like to know why `code-push debug ios` isn't displaying any log messages.

Is this just because I am running a release build on the simulator?

If I run the app with the Debug configuration, and I set my Staging key in Debug, then CodePush seems to be working:

```
[05:14:50] Checking for update.
[05:14:50] App is up to date.
```

Is the logging just disabled for release builds? Is it safe to assume that CodePush will be working for my Release build, even if I don't see any logging in `code-push debug ios`?

### Additional Information

* react-native-code-push version: 2.0.2-beta
* react-native version: 0.43.3
* iOS/Android/Windows version: iOS 10
* Xcode 8.3.1
* Does this reproduce on a debug build or release build? - I am testing a Release build
* Does this reproduce on a simulator, or only on a physical device? - I am testing on the iOS Simulator

### UPDATE

It seems to be working fine, but there is no logging. I pushed some builds where I changed the background color, and after closing and restarting the app, the color changed.

Is there any reason why the CodePush logs would not be showing up in the console or in Xcode? I see plenty of logging from other libraries, such as Fabric, Crashlytics, and Firebase/Analytics.

**Comment by sergey-akhalkov** [comment]
Hello @ndbroadbent, thank you for reaching us.
React Native disables logging in Release mode by default, to enable it, you could try the following: https://gist.github.com/huston007/61490dbc3269d89e4ac2e310fe21c554
Please let me know if it helps.

**Comment by sergey-akhalkov** [comment]
@ndbroadbent, closing this for now, please let me know if you have any questions or see any issues.
