### ISSUE TITLE
code-push release-react [both platform]

### ISSUE THREAD

**Issue by mike623** [Microsoft/react-native-code-push#805]
I am confusing about release flow becoz I cannot release both platform at the same time. Is there any reason to restrict that? For now. I have to `code-push release-react android` and `code-push release-react ios` for different platform but I have no idea to see which platform I release in `code-push deployment history`. As the screenshot below, I have duplicate message. but I forgot which `label` for which platform

<img width="741" alt="screen shot 2017-04-22 at 4 52 49 pm" src="https://cloud.githubusercontent.com/assets/14008281/25302940/2498f55c-277c-11e7-948b-484a20d21025.png">

**Comment by max-mironov** [comment]
Hey @mike623 we recommend to create separate CodePush applications for each platform to avoid issues when e.g. you have released an update for iOS but your Android app also shows an update and it breaks it. 

This will help to avoid such problems like were described e.g. here: https://github.com/Microsoft/react-native-code-push/issues/723
Please let us know if you have more questions.

**Comment by max-mironov** [comment]
@mike623 - please let us know if you need any further assistance with this.

**Comment by max-mironov** [comment]
Closing the issue, feel free to reopen if any Q's.
