### ISSUE TITLE
api suggestion

### ISSUE THREAD

**Issue by yellowChao** [Microsoft/react-native-code-push#807]
in iOS platform, can you add a class method ?  

CodePush.h file 
ex: - (void)specifyBundleUrl:(NSURL*)url;

on this way , i think it will be better that only one parameter

**Comment by sergey-akhalkov** [comment]
Hello @yellowChao, thanks for reaching us. To specify js bundle url you need to change `jsCodeLocation` [variable value](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/iOS/CodePushDemoApp/AppDelegate.m#L29). In case you want to change js bundle file name you need to use `bundleURLForResource` [method](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-ios.md#methods).
 
In case it does not fit for you, could you please clarify what you want achieve by adding `(void)specifyBundleUrl:(NSURL*)url;` method?

**Comment by yellowChao** [comment]
@sergey-akhalkov I tried configure CodePush by this way
`[CodePush bundleURLForResource:@"main" withExtension:@"jsbundle" subdirectory:@"Frameworks/User.framework/User.bundle"];`

it requires 3 args and not flexible, can you add a method like this:
`[CodePush specifyBundleResource:@"Frameworks/User.framework/User.bundle/main.jsbundle" ]`
so we can use it simpler.
☺️

**Comment by sergey-akhalkov** [comment]
@yellowChao, as of now, we are extremely backlogged and currently working on "Code signing" and "Support brownfield React Native apps" features, so we'll be very grateful if you could try to implement this enhancement (it does not look very difficult) and publish PR to deliver this method faster. 
As of now you can use `[CodePush bundleURLForResource:@"main" withExtension:@"jsbundle" subdirectory:@"Frameworks/User.framework/User.bundle"]` method, please let me know if this method does not work as expected.

**Comment by iageoghe** [comment]
@yellowChao Closing for now; please let us know if the method @sergey-akhalkov has detailed does not work as expected. Thanks.
