### ISSUE TITLE
CodePush Deployment key  is not valid on IOS

### ISSUE THREAD

**Issue by Temereru** [Microsoft/react-native-code-push#808]
Hi
I'm new in codePush, and I have a problem
i connected my reactNative app to codePush, in android it is working fine
but in ios..
I followed this instructions https://github.com/Microsoft/react-native-code-push#ios
but still I got this message on my xCode log
![image](https://cloud.githubusercontent.com/assets/17434097/25372343/b2e02164-299d-11e7-8069-8e0df76bac86.png)

I also added some logs in codePush.js and it looks like my deployment key is not valid

this is my deployment keys:
![image](https://cloud.githubusercontent.com/assets/17434097/25371754/f131eeaa-299a-11e7-8431-a886d7b0c1fe.png)

and some more imgs to let you know what I did 

configuration:
![image](https://cloud.githubusercontent.com/assets/17434097/25372371/c9b475c0-299d-11e7-92a9-c8ad5a281c53.png)

buildSettings
![image](https://cloud.githubusercontent.com/assets/17434097/25372394/e5468c42-299d-11e7-837a-07d017d3a958.png)

CODEPUSH_KEY:
![image](https://cloud.githubusercontent.com/assets/17434097/25372421/fe117f70-299d-11e7-9578-bfffa771a436.png)

info.plist:
![image](https://cloud.githubusercontent.com/assets/17434097/25372437/0d33323c-299e-11e7-8bb5-530930293d36.png)

and my appDelegate.m file: 
![image](https://cloud.githubusercontent.com/assets/17434097/25372459/2bc58c2c-299e-11e7-9e07-7e730250556c.png)

react-native-code-push version - 0.43.2
react-native version - ^2.0.2-beta

hope I gave all the info you need, 
Thanks alot!!
Sary

**Comment by sergey-akhalkov** [comment]
Hi @Temereru, thanks for reaching us. Could you please clarify - are you using the same deployment key both for Android and iOS? If so, you need to create new app in CodePush CLI and set new deployment key for iOS:
>Note, if you are targeting both platforms it is recommended to create separate CodePush applications for each platform.

Then you need to release CodePush update for iOS: `code-push release-react myapp-ios ios`. Please let me know if it helps.

**Comment by Temereru** [comment]
I have 2 different apps for android and ios
but now I added the deployment key in my index.js - hardcoded, and it is working fine
you can close this issue
thanks for helping :)

**Comment by sergey-akhalkov** [comment]
@Temereru, got it, thank you, so I'm closing this for now, please feel free to reopen if needed.
