### ISSUE TITLE
[Android] Users experiencing long application hangs on app opening.

### ISSUE THREAD

**Issue by matt33** [Microsoft/react-native-code-push#810]
### Description
Mostly Android users are experiencing long white screen hangs on app start after introducing the code push, app just freezes and nothing happens. iOS users experience this as well but less frequently - once per day. When I checked `code-push deployment history OurApp-Android Production` I can see that there is a lot of rollbacks for android platform.
```
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v12   │ 12 days ago                   │ 2.10.0      │ No        │             │ Active: 8.0% (44 of 547) │
│       │ (Promoted v36 from "Staging") │             │           │             │ Total: 207 (52 pending)  │
│       │                               │             │           │             │ Rollbacks: 21            │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v13   │ 6 days ago                    │ 2.10.0      │ No        │             │ Active: 8.0% (44 of 547) │
│       │ (Promoted v37 from "Staging") │             │           │             │ Total: 166 (27 pending)  │
│       │                               │             │           │             │ Rollbacks: 18            │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v14   │ 4 days ago                    │ 2.10.0      │ No        │             │ Active: 20% (112 of 547) │
│       │ (Promoted v38 from "Staging") │             │           │             │ Total: 195 (40 pending)  │
│       │                               │             │           │             │ Rollbacks: 14            │
├───────┼───────────────────────────────┼─────────────┼───────────┼─────────────┼──────────────────────────┤
│ v15   │ 17 hours ago                  │ 2.10.0      │ No        │             │ Active: 17% (95 of 547)  │
│       │ (Promoted v39 from "Staging") │             │           │             │ Total: 95 (51 pending)   │
│       │                               │             │           │             │ Rollbacks: 8             │
└───────┴───────────────────────────────┴─────────────┴───────────┴─────────────┴──────────────────────────┘
```
Our root container is wrapped inside codePush function `export default codePush(codePushOptions)(connect(mapStateToProps, mapDispatchToProps)(RootContainer))`
and codePushOptions are:
```
let codePushOptions = {
  checkFrequency:       codePush.CheckFrequency.ON_APP_RESUME,
  installMode:          codePush.InstallMode.ON_NEXT_RESUME,
  mandatoryInstallMode: codePush.InstallMode.IMMEDIATE
}
```
My questions are:
1. Is there any way to find out why these rollbacks happened? 
2. Also what could be the reason for the long white screen hangs from code push side (we are thinking slow internet connection)?
3. Are there any accessible logs from code-push server for us to see whether our app is really hanging while checking for code push updates? - something like CodePush check started, CodePush check finished etc.

Thanks a lot for the response.

### Additional Information

* react-native-code-push version: 1.17.2-beta
* react-native version: 0.40.0
* Does this reproduce on a debug build or release build? - only release build
* Does this reproduce on a simulator, or only on a physical device? - only on a physical device

**Comment by matt33** [comment]
Just simulated it - when I download the app from the play store, it runs well for the first time. But then when I launch it and update should be installed to the latest available the application hangs on white screen.
Is this because there was a lot of code-push releases since we made the app available in the play store? Is there any way to debug this or see what is happening?

**Comment by sergey-akhalkov** [comment]
Hello @matt33. thanks for reaching us. Please take a look at comments below:
>Is there any way to find out why these rollbacks happened?
>Is there any way to debug this or see what is happening?

To achieve it you need to use an exception reporter library, so it will allow you to track and report the exceptions both for native side and js code.

>Also what could be the reason for the long white screen hangs from code push side (we are thinking slow internet connection)?

It's hard to say what went wrong or reproduce it without any code samples. Does the issue reproduces for all releases you have uploaded or it have started to reproduce from specific one?

>Are there any accessible logs from code-push server for us to see whether our app is really hanging while checking for code push updates? - something like CodePush check started, CodePush check finished etc.

CodePush SDK reports to the CodePush Server (using `acquisition-sdk` module) that an update has been downloaded by the app user, then it reports to the server if an update has been installed successfully or not. To log things like `CodePush check started, CodePush check finished` you need to use [sync status change callback](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/demo.js#L83), then you need to save logs locally and report them using an logs reporter.

**Comment by matt33** [comment]
Thanks a lot for the response @sergey-akhalkov 
We'll try installing bugsnag and debug some more, will post the answer once we have some conclusion.

**Comment by sergey-akhalkov** [comment]
@matt33, no problem! Don't you mind if I close the issue for now, so we will reopen it in case you'll find out more info regarding to it?

**Comment by sergey-akhalkov** [comment]
@matt33, I'm closing this for now, please feel free to reopen.

**Comment by tiaanduplessis** [comment]
@matt33 I'm experiencing a similar issue on android. Were you able to resolve it?

**Comment by matt33** [comment]
@tiaanduplessis turned out to be different issue with the splash screen. We still have a couple of rollbacks for every version but did not have time to get to the bottom of it.

**Comment by solidstate-tech** [comment]
I'm having this issue on my splash screen on android and IOS, any idea why this happens?
