### ISSUE TITLE
ios debug killed rollback

### ISSUE THREAD

**Issue by huangdou0204** [Microsoft/react-native-code-push#814]
IOS in the debug mode to kill APP rollback,
1. After the update is complete, notifyAppReady was successfully called
2. The next startup shows the previous version, and the status of the detection is: SyncStatus.UP_TO_DATE

Look at my code: ⬇️⬇️⬇️⬇️

```JavaScript
updateCompelete(syncStatus) {
    const { CHECKING_FOR_UPDATE, UP_TO_DATE, DOWNLOADING_PACKAGE, INSTALLING_UPDATE, UPDATE_INSTALLED, UNKNOWN_ERROR } = CodePush.SyncStatus
    let statusText = this.state.versionState
    let isStart = false
    try {
      switch (syncStatus) {
        case CHECKING_FOR_UPDATE:
          break;
        case UP_TO_DATE:
          statusText = '当前为最新版本!';
          isStart = true;
          break;
        case DOWNLOADING_PACKAGE:
          statusText = '下载更新中...';
          break;
        case INSTALLING_UPDATE:
          statusText = '应用更新中...';
          break;
        case UPDATE_INSTALLED:
          statusText = '应用更新完成,重启中...';
          break;
        case UNKNOWN_ERROR:
          statusText = '应用更新出错,请检查设置!';
          break;
      }
    } catch (e) {
      statusText = '应用更新异常!'+e
    }
    this.setState({versionState: statusText})
    isStart ? this.isFirstRun() : false
  }
  isFirstRun() {
    let me = this
    CodePush.getCurrentPackage().then((update) => {
      if (update.isFirstRun) {
        me.setState({versionState: '版本更新成功!'})
        CodePush.notifyAppReady()
      }
      this.layzAutoLogin()
    })
  }
```

**Comment by max-mironov** [comment]
Hey @huangdou0204, sorry for the delay in response. 
Do you still experience the issue? Have you tried to put `NotifyAppReady` in `componentDidMount` event? It would be great if you share with us the minimum app example where the issue can be reproduced so we can see how you instantiate CodePush and apply update  check logic. 
Also have you tried default behavior if it works for you like it is done in [our basic sample](https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/demo.js)?

**Comment by neeboo** [comment]
Hi @max-mironov , I've came across the same problem after the install-restart process using the example you post up here. I think maybe the bundled JS is downloaded from server but not loaded after device rebooted.

**Comment by max-mironov** [comment]
hi @neeboo. Basically you should use `release` scheme configuration in order to allow bundles to be loaded and applied correctly after code-push update is applied (otherwise it will be always loaded from packager by default in `debug` configuration). You can change your configuration with Product -> Scheme -> Edit Scheme -> select Release configuration in xCode. 
Please let me know if it helps.

**Comment by neeboo** [comment]
Thanks,@max-mironov. Changing the "Product Scheme" is the right way to apply the update.
It would be good if we can put the instruction to "code-push-ios-guide" for those are not familiar to Xcode setting.

**Comment by max-mironov** [comment]
@neeboo thank you for your answer. 
We have some info about this in guides here: https://github.com/Microsoft/react-native-code-push#releasing-updates

> NOTE: CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply.

But I believe that we can improve this message a little bit. Please let us know what can be changed here so we can add this info in this section or may be in other place.

**Comment by max-mironov** [comment]
@huangdou0204 - do you still experience the issue? Please let us know if you have any updates about it.

**Comment by max-mironov** [comment]
Closing the issue for now, please feel free to reopen or create a new issue if any questions.

**Comment by huangdou0204** [comment]
@max-mironov 

> NOTE: CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply.

the above answer has solved my question, thank you very much! (unsupport debug!
> JS bundle downloaded by CodePush does not apply)
