### ISSUE TITLE
[CodePushPackage downloadPackage:expectedBundleFileName:operationQueue:progressCallback:doneCallback:failCallback:]

### ISSUE THREAD

**Issue by Amurmurmur** [Microsoft/react-native-code-push#815]
### Description
Rolled out an update as usual, update dialog pops up, clicking continue.
From the logs the package gets loaded completely, but at the point when it tries to install the update app crashes, and nothing gets installed. The pop up shows again on the next app boot and the whole thing just repeats.

I noticed this behavior after a recent code-push and react-native update. However on RN ^0.42 and code-push on ^0.17 the problem did not exist.

### Reproduction
Rollout an update on iOS.
When codepush finishes loading the update right after which, an app will crash with the following:
```
__116+[CodePushPackage downloadPackage:expectedBundleFileName:operationQueue:progressCallback:doneCallback:failCallback:]_block_invoke at ProjectName/node_modules/react-native-code-push/ios/CodePush/CodePushPackage.m:261
```

### Additional Information
* react-native-code-push version: 2.0.2-beta
* react-native version: 0.43.4
* iOS/Android/Windows version: 10.3
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hello @Amurmurmur, as you've mentioned earlier - probably your issue could relates to https://github.com/Microsoft/react-native-code-push/issues/816. Could you please verify this and check if suggested fixes can help you?

**Comment by Amurmurmur** [comment]
@max-mironov I just replied to the relevant #816 issue.

The suggested PR #809 fixes the issue!
Thank you very much for your help!
Cant wait to update via NPM.

Closing for now 👍
