### ISSUE TITLE
I was refused by appstore when using codepush

### ISSUE THREAD

**Issue by tigerohuang** [Microsoft/react-native-code-push#818]
I submitted a version to appstore, and was refused, and I removed codepush, was passed, how can I use codepush and can be passed.
   My codepush code is following:
  let CodePushOptions = { checkFrequency: CodePush.CheckFrequency.ON_APP_START,installMode: CodePush.InstallMode.ON_NEXT_RESTART };

export default CodePush(CodePushOptions)(App);

 The reason why I was refused is :

Guideline 2.5.2 - Performance

Thank you for your resubmission. After further review, we find the following issue(s) to be unresolved:

Your app, extension, or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with App Store Review Guideline 2.5.2 and section 3.3.2 of the Apple Developer Program License Agreement.

This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior and/or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

Next Steps

To resolve this issue, please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above and resubmit your app’s binary for review.

Guideline 5.1.5 - Legal

Your app uses background location services but does not clarify the purpose of its use in the location modal alert as required in the iOS Human Interface Guidelines.

Please see attached screenshots for details.

Next Steps

To resolve this issue, please revise the NSLocationAlwaysUsageDescription value in the Info.plist to specify the intended purpose of using the user's location while the app is in the background.

Resources

For additional information and instructions on configuring and presenting an alert, please review the Requesting Permission section of the iOS Human Interface Guidelines and the Information Property List Key Reference

**Comment by max-mironov** [comment]
Hello @tigerohuang, thanks for reaching us. Any chance that you have similar problem as it was discussed in the links below?
[Warning from Apple](https://github.com/Microsoft/react-native-code-push/issues/748)
https://github.com/Microsoft/code-push/issues/415

**Comment by max-mironov** [comment]
Close this for now as duplicate of https://github.com/Microsoft/react-native-code-push/issues/748, please update older thread if you have any thought/assumptions about this.
