### ISSUE TITLE
iOS crash when updating without debug server

### ISSUE THREAD

**Issue by yelkamel** [Microsoft/react-native-code-push#821]
Hello,

It's my second app using code push with react-native.

react-native-cli: 2.0.1
react-native: 0.41.2
react-native-code-push: 1.17.3-beta
iOS version: 10.3
Reproduce on simulator and device

When I try to update with CodePush with debugger it's work well but without I got this : 
![capture d ecran 2017-05-02 a 16 49 09](https://cloud.githubusercontent.com/assets/10924422/25624082/ab7e65d2-2f58-11e7-9737-12959117ee33.png)

I tried to:
- Unlink and re-link
- Use another codeDeploymentKey 
- Using the version `1.17.0-beta`
but I got the same issue...

If you have any idea to fix it, don't hesitate.

Regards,
Youcef

PS: it's work on Android

**Comment by max-mironov** [comment]
Hello @yelkamel, your issue looks similar to https://github.com/Microsoft/react-native-code-push/issues/816

The fix is on flight and new version will be available really soon. Thank you for your patience!

**Comment by yelkamel** [comment]
Oh sorry, I didn't see this issue.

It's similar when I adding this 
[mutableUpdatePackage removeObjectForKey:@"download"];

before that 
NSData *updateSerializedData = [NSJSONSerialization dataWithJSONObject:mutableUpdatePackage options:0 error:&error];

it's work perfectly thank you :)

**Comment by max-mironov** [comment]
@yelkamel no problem and sorry for inconvenience, this will be resolved ASAP.
