### ISSUE TITLE
Unable to resolve module 'react-native-code-push'

### ISSUE THREAD

**Issue by li-zhenyu** [Microsoft/react-native-code-push#826]
### Description

I installed `react-native-code-push@1.17.3-beta`,
but when I wrote `import codePush from 'react-native-code-push'` I got an error:
Unable to resolve module 'react-native-code-push', my react-native version is 0.42.0.
I rerun `react-native run-ios`, it build failed:

Undefined symbols for architecture x86_64:
  "_crc32", referenced from:
      _unzReadCurrentFile in libCodePush.a(unzip.o)
      _zipWriteInFileInZip in libCodePush.a(zip.o)
  "_deflate", referenced from:
      _zipWriteInFileInZip in libCodePush.a(zip.o)
      _zipCloseFileInZipRaw64 in libCodePush.a(zip.o)
  "_deflateEnd", referenced from:
      _zipCloseFileInZipRaw64 in libCodePush.a(zip.o)
  "_deflateInit2_", referenced from:
      _zipOpenNewFileInZip4_64 in libCodePush.a(zip.o)
  "_get_crc_table", referenced from:
      _unzOpenCurrentFile3 in libCodePush.a(unzip.o)
      _zipOpenNewFileInZip4_64 in libCodePush.a(zip.o)
  "_inflate", referenced from:
      _unzReadCurrentFile in libCodePush.a(unzip.o)
  "_inflateEnd", referenced from:
      _unzCloseCurrentFile in libCodePush.a(unzip.o)
  "_inflateInit2_", referenced from:
      _unzOpenCurrentFile3 in libCodePush.a(unzip.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:

	Ld build/Build/Products/Debug-iphonesimulator/bishe.app/bishe normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/bishe.app
An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/zhenyu/Library/Developer/CoreSimulator/Devices/D46CC213-153C-48FD-ABEF-3A85DD8DAB76/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/A15355E4-CE17-42CF-8B7B-2BD0B3C52DFF/bishe.app/bishe : No such file or directory
Launching org.reactjs.native.lzy.bishe

### Additional Information

* react-native-code-push version: 1.17.3-beta
* react-native version: 0.42.0
* iOS/Android/Windows version: iPhone 6
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? on a simulator

**Comment by max-mironov** [comment]
Hello @li-zhenyu, that looks odd. 
Can you please be more specific about how you install CodePush into your app?
Which plugin installation steps have you followed from [here](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md)?

**Comment by li-zhenyu** [comment]
hi @max-mironov 
I used `react-native link react-native-code-push`

**Comment by li-zhenyu** [comment]
@max-mironov 
Actually I got another warning:
warning: using 'ALWAYS_SEARCH_USER_PATHS = YES' while building targets which define modules ('DEFINES_MODULE = YES') may fail. Please migrate to using 'ALWAYS_SEARCH_USER_PATHS = NO'.
but I tried to set the value to 'No', this warning is still happen,
may that cause the failed?

**Comment by max-mironov** [comment]
@li-zhenyu
So to sum it up, when you say "Actually I got another warning" does it mean that you still have `Unable to resolve module 'react-native-code-push'` error or this error has gone away?
Have you tried to build project with xCode and what is the full build output there?

Ideally it would be great if you can share with us your app so we can quickly have a look at what is wrong with your configuration. 
Also it may looks reasonable to e.g. remove CodePush from your app and then reinstall it again and see if it helps to resolve the issue.

**Comment by li-zhenyu** [comment]
@max-mironov 
My app build failed so I can not see the `Unable to resolve module 'react-native-code-push'` error.
I have tried to build with XCode and the output is :
<img width="433" alt="qq20170504-164406 2x" src="https://cloud.githubusercontent.com/assets/21993802/25696225/f2cc1f6a-30e8-11e7-8a45-b2af1962bc79.png">
I think 'ALWAYS_SEARCH_USER_PATHS = YES' cause the build failed but I don't know how to fix it.

**Comment by max-mironov** [comment]
@li-zhenyu 
So after a quick search I found that usually Mach-O Linker Error means you have not included a header file for a function you are using in your code ([here](http://stackoverflow.com/questions/17414460/xcode-gives-apple-mach-o-linker-error) are some more details). 
As for `ALWAYS_SEARCH_USER_PATHS` - I don't think that this could be a reason of build failure because it is just warning, not an error.

In general I'd recommend firstly to remove CodePush temporary from your project and try to build the project. In this case if everything works fine we can be sure that the problem is somehow related to CodePush. After that (if it works well) try to add CodePush again to see if the issue still exists.

Please let us know the results.

**Comment by li-zhenyu** [comment]
@max-mironov 
I uninstalled everything about CodePush and installed again.
Then I installed it manually, it works fine now.
Thanks, I'm going to close this.
