### ISSUE TITLE
White/Blank screen after new app bundle is installed 

### ISSUE THREAD

**Issue by mobile-support93** [Microsoft/react-native-code-push#827]
Whenever there's a code push update, it restarts the application and  white screen flashes for a few seconds.
Is there a way to show the loader or  to avoid the white screen altogether ?

Thanks!

**Comment by max-mironov** [comment]
Hi @mobile-support93, as I get it right you have **InstallMode: Immediate** for installing updates.
Probably as a solution you can try to use [InstallMode:On_NEXT_SUSPEND](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L522), this was recently released in [v2.0.3-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v2.0.3-beta). So this should install the app in the background and this way can help you to avoid seeing white screen on applying new bundle. 
Please let us know if it helps.

**Comment by max-mironov** [comment]
@mobile-support93 - please let us know if the information from above help you to resolve the issue.

**Comment by max-mironov** [comment]
I'm closing the issue now as of no response, please feel free to reopen or create a new one if needed.

**Comment by mobile-support93** [comment]
Thanks, that helped me resolve the issue.

**Comment by gabrielmoncea** [comment]
@max-mironov is it possible to replace the white flash when using `InstallMode:IMMEDIATE`
