### ISSUE TITLE
CodePushNativeModule.java error cannot find symbol import com.facebook.react.modules.core.ChoreographerCompat

### ISSUE THREAD

**Issue by esutton** [Microsoft/react-native-code-push#829]
### Description

Building an Android version of my app results in multiple missing symbols from CodePushNativeModule.java.

CodePushNativeModule.java error cannot find symbol **com.facebook.react.modules.core.ChoreographerCompat**

### Reproduction

I followed Android setup "manual instructions":
- https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-android.md

`react-native run-android`

#### Build Output
```
/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java:22: error: cannot find symbol
import com.facebook.react.modules.core.ChoreographerCompat;
                                      ^
  symbol:   class ChoreographerCompat
  location: package com.facebook.react.modules.core
/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java:23: error: cannot find symbol
import com.facebook.react.modules.core.ReactChoreographer;
                                      ^
  symbol:   class ReactChoreographer
  location: package com.facebook.react.modules.core
/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java:258: error: package ReactChoreographer does not exist
                                    ReactChoreographer.getInstance().postFrameCallback(ReactChoreographer.CallbackType.TIMERS_EVENTS, new ChoreographerCompat.FrameCallback() {
                                                                                                         ^
/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java:258: error: package ChoreographerCompat does not exist
                                    ReactChoreographer.getInstance().postFrameCallback(ReactChoreographer.CallbackType.TIMERS_EVENTS, new ChoreographerCompat.FrameCallback() {
                                                                                                                                                             ^
/Users/edward3/Documents/projects/react-native/field-scout/source/node_modules/react-native-code-push/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java:258: error: cannot find symbol
                                    ReactChoreographer.getInstance().postFrameCallback(ReactChoreographer.CallbackType.TIMERS_EVENTS, new ChoreographerCompat.FrameCallback() {
                                    ^
  symbol: variable ReactChoreographer
5 errors
:react-native-code-push:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

### Additional Information

* react-native-code-push version: 2.0.3-beta
* react-native version: 0.42.3
* iOS/Android/Windows version: Android

Thanks in advance for any suggestions!

**Comment by esutton** [comment]
Looks like this may hold the answer: https://github.com/Microsoft/react-native-code-push/issues/792

**Comment by max-mironov** [comment]
@esutton thank you for reaching us. 
We try to do our best to maintain backwards compatibility of our plugin with previous versions of React Native, but due to the nature of the platform, and the existence of breaking changes between releases sometimes it is not possible to use specific version of the plugin with exact version of RN.

Please remember that you could use react-native-code-push 1.17.x versions with RN 0.40-0.42 versions in your case.

**Comment by esutton** [comment]
@max-mironov Thanks Max.  

I think CodePush is magic and really appreciate your work!

What will I be missing if I downgrade both iOS and Android to 1.17.x versions with RN  0.42.3?

Should downgrading "just work"?

**Comment by max-mironov** [comment]
Thank you for feedback @esutton, appreciate it!

As for using 1.17.x versions - you will have almost all functionality as code-push can provide for today, so there should be no problem with this.

You can check for details of what was added in latest 2.0.x releases here:
1) [v2.0.1-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v2.0.1-beta)
2) [v2.0.2-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v2.0.2-beta)
3) [v2.0.3-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v2.0.3-beta)

But again, using 1.17.x version will be ok and you can have all the functionality working as expected with this versions.

**Comment by esutton** [comment]
@max-mironov  Very good!

Upgrading packages for a single iOS platform can be problematic. 

I wish there was some easy way to have two package.json one for Android and one for iOS so I could lock down package versions for each target.  Maybe a Node.js expert might have ideas.

Two package.json folders? One for Android and one for iOS?

Thank you for the links!

**Comment by max-mironov** [comment]
@esutton From my point of view it is not a good idea having single code base but different package versions for different platforms, the differences between versions will turn out really hard to maintain at some point.
But at least you can always have two separate apps, one for iOS and one for Android if you really need to have latest version of the plugin for iOS platform.

There is a [similar question ](http://stackoverflow.com/questions/42586022/different-package-versions-for-android-and-ios) in StackOverflow, but I'm not sure if it can help you a lot.

**Comment by esutton** [comment]
@max-mironov thanks Max!
