### ISSUE TITLE
Released packages always flagged is "isAvailable:false"

### ISSUE THREAD

**Issue by ajwhite** [Microsoft/react-native-code-push#83]
I've deployed a few releases now but I haven't gotten the CodePush synchronizer to download them. After digging around, I discovered each one has this pretty empty looking response:

![screen shot 2015-12-03 at 11 54 14 am](https://cloud.githubusercontent.com/assets/656630/11567358/aee3ad62-99b4-11e5-964d-3fee215ae6d3.png)

**Comment by ajwhite** [comment]
Ah -- I mistakenly have been incrementing the "app version" thinking that's how I push releases. I see that the app version specifies which target should allow the update. Fantastic.

For anyone else confused -- make sure that when you perform a release that your version is targeting the version you want to sideload

**Comment by lostintangent** [comment]
The fact that the updateAppVersion property is true means that the server thinks you are running an older version of the app then the update is meant for.
