### ISSUE TITLE
Beta/other app configuration won't build

### ISSUE THREAD

**Issue by chrisjrex** [Microsoft/react-native-code-push#831]
### Description

Xcode / iOS bug

I have multiple configurations for my app: `Debug`, `Beta`, `Release`, `Beta Release`. However using code push as a library added to my project I am only able to build `Debug` & `Release`.

I had similar issues with the rest of the reactive-native modules/libraries but was able to solve it using this package: https://www.npmjs.com/package/react-native-schemes-manager

Is there something similar for code push?

### Additional Information

* react-native-code-push version: 2.0.2-beta
* react-native version: 0.43.3
* iOS/Android/Windows version: iOS 10
* Does this reproduce on a simulator, or only on a physical device? Both

**Comment by sergey-akhalkov** [comment]
Hi @chrisjrex, thanks for reaching us. I believe that [Multi-Deployment Testing for iOS](https://github.com/Microsoft/react-native-code-push/blob/master/README.md#ios) can help you to resolve it. Please pay attention on point 7: 
>Go to Build Location -> Per-configuration Build Products Path -> Staging and change Staging value from $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME) to $(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)

Please let me know if it helps.

**Comment by chrisjrex** [comment]
Thank you very much for the quick reply. Sorry that I missed that in the docs

**Comment by sergey-akhalkov** [comment]
@chrisjrex, just a friendly ping.

**Comment by chrisjrex** [comment]
@sergey-akhalkov Sorry i thought I had left my reply! I did manage to solve my problem via following your link and a few others.

Thanks that you were so quick getting back to me before

**Comment by sergey-akhalkov** [comment]
@chrisjrex, thanks for the response, so I'm closing this, please feel free to reopen if needed.
