### ISSUE TITLE
Archived bundles crash during update

### ISSUE THREAD

**Issue by julienvincent** [Microsoft/react-native-code-push#832]
### Description

Since updating to `V2 beta` (on `RN44`) code-push updates freeze-crash the app. When building (`debug` | `release`) I have no problems downloading and installing updates. This is only an issue for archived builds running on physical devices.

### Reproduction

+ Archive a react-native app and install to a physical device
+ Try code-push an update.

### Additional Information

* react-native-code-push version: **2.0.3-beta**
* react-native version: **0.44**
* iOS/Android/Windows version: **ios, 10.0.2**
* Does this reproduce on a debug build or release build? **no**
* Does this reproduce on a simulator, or only on a physical device? **only physical**

### Edit

This issue does not affect downloading. I am listening to download progress, which successfully completes. It's only when attempting to install the newly downloaded update that the app crashes.

I have since tested with version `2.0.2-beta` and everything worked as expected. Perhaps the regression has something to do with the `ON_NEXT_SUSPEND` feature added in `2.0.3-beta` (seeing as this deals with installation).

**Comment by sergey-akhalkov** [comment]
Hi @julienvincent, thanks for reaching us. I've just tried to reproduce your issue, but with no luck - it works well for me on physical device. Is it possible if you have the same issue as here https://github.com/Microsoft/react-native-code-push/issues/775#issuecomment-291534691?
If not, could you please then be more specific regarding to repro steps, source code and environment settings? You also could try to reproduce the issue using our sample app: https://github.com/Microsoft/react-native-code-push/tree/master/Examples

**Comment by julienvincent** [comment]
Hi @sergey-akhalkov - It is not related to that issue / comment, but it may be related to something going wrong while upgrading from `RN40` => `RN44`.

I will do some more testing with my repo as well as with your sample app using `2.0.3-beta` and see if I can reproduce it again.

Thanks for your fast reply

**Comment by julienvincent** [comment]
So, after re-installing `2.0.3-beta` and re-linking I am unable to reproduce this issue.

Closing 👍

**Comment by sergey-akhalkov** [comment]
@julienvincent, great, please feel free to reopen if needed.
