### ISSUE TITLE
Dimensions incorrect after CodePush update

### ISSUE THREAD

**Issue by peacechen** [Microsoft/react-native-code-push#833]
### Description

After a CodePush update and auto-restart, the result of a RN Dimensions call returns incorrect values.  This occurs when the JS is hot-reloaded by CodePush, as compared to a full app restart (double tap home button, swipe up on the app to kill it).  The results are correct after the app is fully restarted.

### Reproduction

Open app that calls 
```
import { Dimensions } from 'react-native';
    let dims = Dimensions.get('window');
```

The result is correct for the app until a CodePush update occurs.  After that, calls to `Dimensions.get('window')` return incorrect values.

### Additional Information

* react-native-code-push version: 1.17.4-beta
* react-native version: 0.34.1
* iOS/Android/Windows version: iOS 10.3
* Does this reproduce on a debug build or release build?  release
* Does this reproduce on a simulator, or only on a physical device?  device

**Comment by max-mironov** [comment]
Hi @peacechen - just have tried to reproduce your issue but with no luck. Probably I'm missing something within your repro steps? 
I've attached my little demo app here (dropped node_modules to reduce size) so can you have a look at this and see if you have an issue there? There are 3 buttons in it, one for immediate update, one for background update and one for showing dimensions. After every code push update dimensions are the same for me.
(Note: I'vent yet tried with iOS 10.3 on real device, was tested on simulator in Release Mode).
[testapp_rn34.zip](https://github.com/Microsoft/react-native-code-push/files/989437/testapp_rn34.zip)



Please let us know the results.

**Comment by peacechen** [comment]
@max-mironov  Thanks for the test project. Having a bit of trouble building it, seeing this error logged in the console:

> The CodePush module doesn't appear to be properly installed. Please double-check that everything is setup correctly.

I'll keep plugging at it, but in the meantime I've updated the OP to specify release & physical device.  I vaguely recall seeing it in the simulator but my memory could be wrong on this.  It definitely occurs on release builds + physical device.

**Comment by max-mironov** [comment]
@peacechen, ok I've tried this with real device on iOS 10.3.1 and release build with latest react and code-push but don't see any issues. (have tried to run both from xCode and command line)
Do you have a chance to verify if you still have issue with e.g react 0.44?

Also when you say

> Update: Runs properly from Xcode, but not the command line.

do you mean that dimensions are incorrect after code-push update when deployed via command line or you mean that my example runs from xCode but not command line?

**Comment by peacechen** [comment]
Sorry for the ambiguity.  Your test project builds and runs from Xcode but not the command line.  Dimensions are returned as expected in the test app.

**Comment by max-mironov** [comment]
@peacechen thanks for update. So do you have any idea how to reproduce it with test app or may be you have other conditions?

**Comment by peacechen** [comment]
For our app's internal code as well as a 3rd party library that uses Dimensions, the returned values are incorrect immediately after an update.  The symptom appears to be that it returns the landscape width & height values when the device is in portrait mode.  I've yet to see it do the opposite, though we primarily run our app in portrait mode.

I'll try to dig in more with the debugger.

**Comment by max-mironov** [comment]
@peacechen - hi again, do you have any updates about this item?

**Comment by peacechen** [comment]
This behavior appears to be due to React Native and not CodePush.  I've observed Dimensions returning incorrect results on app resume when no CodePush update has been applied.  Thanks for your help and apologies for taking up your time.

**Comment by max-mironov** [comment]
@peacechen - np, thanks for update!
