### ISSUE TITLE
how do you do versioning?

### ISSUE THREAD

**Issue by pvinis** [Microsoft/react-native-code-push#834]
### Description
i started using codepush and its great. one thing i havent figured out yet, is how to do versioning. more specifically, if i need to do a migration after an update, how do i know which version im on and which one im getting?
for the ios app, i have the appstore version, and i also have the build number, which i use to know when to do migrations. how do i do that for the codepush releases?

### Reproduction

-

### Additional Information

* react-native-code-push version: 2.0.0-beta
* react-native version: 0.41.0
* iOS/Android/Windows version: 10.3
* Does this reproduce on a debug build or release build? 
* Does this reproduce on a simulator, or only on a physical device?

**Comment by max-mironov** [comment]
Hey @pvinis - thank you for your question.

For iOS CodePush uses CFBundleShortVersionString key in the Info.plist file to verify if it satisfy your update's semver range. If yes - then update will be applied. 

Please have a look at [TargetBinaryVersion ](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter)section for detailed info about versioning. 
Please let us know if you have more questions regarding this.

**Comment by pvinis** [comment]
no, i understand that. i can tell it that from like appstore version 4.5, target that.
what im asking is this. i have version 4.5. then i have an update that i release to code push, and it happens to the users. lets call that codepush-version `X`. then later, i find out that i introduced a bug, and to fix it I made codepush-version `Y`. but to apply this fix, i need to migrate some state thing. so i would like to be able to tell which `X` and which `Y` im working with, so before teh update of after the update, i can apply some migration logic.

does that make sense?

**Comment by max-mironov** [comment]
@pvinis 
I don't really get what do you mean by "but to apply this fix, i need to migrate some state thing"?
You can always release [mandatory ](https://github.com/Microsoft/code-push/tree/master/cli#mandatory-parameter) update with all critical fixes and it will be applied to all users whether they are on code-push version `X` or already on code-push version `Y`. But I'm not sure if it is something you are asking for. Can you please clarify more if possible.

**Comment by pvinis** [comment]
so in the app we have some models. when we add a new feature, sometimes we add things to the models. when we do that, sometimes we need to run a migration, to make sure the old model is changed to the new model, before we act upon it and change it. one simple example is if we have like a person model with name and year of birth. then we change this model to have name and date of birth for better calculation of age. so now we need to run a migration that if we go from version 5 to version 6, it will change all the stored data on the app to have a year of birth instead of the full date of birth. and I want to run this one only if I'm going from a version <=5 to a version >=6.

but how do I know the version of the js bundle that is pushed to the phone?
I have the rest of the logic in the app for app store versions. but I need to know the js bundle version too. how do others do js bundle versioning. how can code push know which version I run and which one I will install.

is that clearer?

**Comment by max-mironov** [comment]
@pvinis  - thank you for explanation, hope I get it right now. 
So I believe in general we suppose that store versions should serve that purpose and when you perform breaking changes it may seems reasonable to bump app version of the app (and this way CodePush updates will be mostly for addressing bugs and/or adding small changes).

But in several cases you can probably use CodePush js api to inspect possible update and verify if you ever need to proceed with it.
You can use [checkForUpdate ](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushcheckforupdate) method  to see whether the configured app deployment has an update available. If it has an update you can inspect its props and decide if you would like to download it. 
You can also use [getUpdateMetadata ](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushgetupdatemetadata) method which retrieves the metadata for an installed update whose state matches the specified `updateState` parameter. This way you can get out what update you are running if any. 
Strictly speaking 'updates' doesn't have versions at all, they are distinguished by label property which is automatically given to the update by the CodePush server. Hope it helps.

Also would be great if someone else in the community will have a fresh look at this and share their thoughts if any.

**Comment by max-mironov** [comment]
Closing this for now, please reopen this or create new issue if you have further questions.
