### ISSUE TITLE
bundle generation TEMP_FILE_PATH sometimes breaks parallel react-native builds

### ISSUE THREAD

**Issue by webkodierer** [Microsoft/react-native-code-push#836]
### Description

During bundle creation a temp file is used in _TMPDIR_/CodePushResourcesMap.json 

For concurrent executions (for us this is the case on our continuous integration server) this allows race conditions resulting in unexpected build failures and _maybe_ to other unexpected results. 

Sequence: 

First in scripts/recordFilesBeforeBundleCommand.js the file is created and written: 
```
var TEMP_FILE_PATH = path.join(require("os").tmpdir(), "CodePushResourcesMap.json");
// [ ... ]
fs.writeFile(TEMP_FILE_PATH, JSON .... 
```

later in scripts/generateBundledResourcesHash.js the file is read and removed: 
```
var TEMP_FILE_PATH = path.join(require("os").tmpdir(), "CodePushResourcesMap.json");
// [ ... ]
var oldFileToModifiedTimeMap = require(TEMP_FILE_PATH);
// [ ... ]
fs.unlinkSync(TEMP_FILE_PATH);
```

For us it happens quite often that multiple jobs are running in parallel, breaking each other. 
This is the sample output from the affected jenkins job:

```
[ ... ]
bundle: Done copying assets
:app:generateBundledResourcesHashLocalReleasemodule.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/CodePushResourcesMap.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/jenkins_home/workspace/my-feature-branch-S7T3KVECBPSJLFN6HQNB4IPKGNWPRYTU3HWBIQIZ6YVEAAKS4E6Q/node_modules/react-native-code-push/scripts/generateBundledResourcesHash.js:32:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateBundledResourcesHashLocalRelease'.
> Process 'command 'node'' finished with non-zero exit value 1
```
### Reproduction

Use gradle to build two codepush enabled react-native projects at the same time (e.g. different feature branches)

### Additional Information

* react-native-code-push version: ^1.14.6-beta (but obviously affects versions up to latest)
* react-native version: ^0.36.1
* iOS/Android/Windows version: none as this is a compile time issue, but we used android build
* Does this reproduce on a debug build or release build? Release build
* this at least happens during android gradle builds

**Comment by sergey-akhalkov** [comment]
Hi @webkodierer, thanks for reporting the issue! As of now, we are extremely backlogged and currently working on frequently asked feature - [Code Signing](https://github.com/Microsoft/code-push/issues/307), so we'll implement this improvement later. If you have a time and ability you could try to help us to deliver this feature faster by publishing pull request - this feature does not look very difficult.

To fix the issue, I suggest to generate unique name for `CodePushResourcesMap.json` file in [codepush.gradle](https://github.com/Microsoft/react-native-code-push/blob/master/android/codepush.gradle#L56) script, then pass it as an argument both for [recordFilesBeforeBundleCommand](https://github.com/Microsoft/react-native-code-push/blob/master/android/codepush.gradle#L59) and [generateBundledResourcesHash](https://github.com/Microsoft/react-native-code-push/blob/master/android/codepush.gradle#L70) tasks. Then we will need to receive such unique filename in those tasks like this: `var TEMP_FILE_PATH = process.argv[3];` Please let me know what do you think.
