### ISSUE TITLE
Deployment strategies with code-push + native update

### ISSUE THREAD

**Issue by mike623** [Microsoft/react-native-code-push#837]
I have live application on both (ios, android) with installed code-push. But I faced a problem that: Fresh new user also need update immediately because they downloaded previous source code.

I am wonder if any "best practice" strategies for both situation: get update from `code-push` and download updated code from store

**Comment by sergey-akhalkov** [comment]
Hi @mike623, thanks for reaching us.

>Fresh new user also need update immediately because they downloaded previous source code.

Have you released updates after releasing new app version for store (you can check it by printing your deployment history)? In this case users will download the latest released CodePush update. To prevent it you could use [target binary version parameter](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter) and specify for which version of the app you want to release an update.

Please let me know if it helps or if you have any questions.

**Comment by sergey-akhalkov** [comment]
@mike623 just a friendly ping.

**Comment by sergey-akhalkov** [comment]
Hi @mike623, closing this for now, please feel free to reopen the issue or create new one if needed.
