### ISSUE TITLE
Application crashes after syncing new version

### ISSUE THREAD

**Issue by ajwhite** [Microsoft/react-native-code-push#84]
I've added the following to my `componentDidMount`

```js
CodePush.sync({
  updateDialog: true,
  installMode: CodePush.InstallMode.ON_NEXT_RESTART
});
```

The following behavior is experienced:

1. When the application loads, the update prompt is presented
2. The update prompt is confirmed
3. Manually restart application
4. Application loads with new version
5. Update prompt activates *again*
6. App continuously reloads in the background (without confirming the repeated dialog)
7. Manually restart application
8. Application crashes and cannot open with the following log message:

```
Dec  3 12:34:56 Atticuss-MacBook-Pro RobinRooms[21558]: Deriving mainBundle URL...
Dec  3 12:34:56 Atticuss-MacBook-Pro RobinRooms[21558]: file:///Users/ajwhite/Library/Developer/CoreSimulator/Devices/B1FAC6C9-136F-4027-ADC8-3F1EFDC6283A/data/Containers/Data/Application/F0E5D633-B97A-4677-A4E6-BBF8C9584FB1/Documents/CodePush/3b32e6b0b45734580c78111f704a611c41d0edb1b1211bf75970c73154982aa1/app.jsbundle
Dec  3 12:34:56 Atticuss-MacBook-Pro assertiond[4384]: assertion failed: 15B42 13B137: assertiond + 13207 [2F0DDEBE-B278-35C0-8523-3236DA94649E]: 0x1
Dec  3 12:34:56 --- last message repeated 2 times ---
Dec  3 12:34:56 Atticuss-MacBook-Pro RobinRooms[21558]: SyntaxError: Unexpected end of script
Dec  3 12:34:56 Atticuss-MacBook-Pro RobinRooms[21558]: *** Terminating app due to uncaught exception 'RCTFatalException', reason: 'Message: SyntaxError: Unexpected end of script'
	*** First throw call stack:
	(
		0   CoreFoundation                      0x01464a84 __exceptionPreprocess + 180
		1   libobjc.A.dylib                     0x006b0e02 objc_exception_throw + 50
		2   CoreFoundation                      0x014649ad +[NSException raise:format:] + 141
		3   RobinRooms                          0x0008a65b RCTFatal + 358
		4   RobinRooms                          0x000a5db2 -[RCTBatchedBridge stopLoadingWithError:] + 305
		5   RobinRooms                          0x000a5834 __38-[RCTBatchedBridge executeSourceCode:]_block_invoke_2 + 43
		6   libdispatch.dylib                   0x049159f3 _dispatch_call_block_and_release + 15
		7   libdispatch.dylib                   0x049336fd _dispatch_client_callout + 14
		8   libdispatch.dylib                   0x0491c296 _dispatch_main_queue_callback_4CF + 689
		9   CoreFoundation                      0x013b65fe __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
		10  CoreFoundation                      0x013742f4 __CFRunLoopRun + 2356
		11  CoreFoundation                      0x01373706 CFRunLoopRunSpecific + 470
		12  CoreFoundation                      0x0137351b CFRunLoopRunInMode + 123
		13  GraphicsServices                    0x050e6664 GSEventRunModal + 192
		14  GraphicsServices                    0x050e64a1 GSEventRun + 104
		15  UIKit                               0x02d451eb UIApplicationMain + 160
		16  RobinRooms                          0x0005e82c main + 94
		17  libdyld.dylib                       0x04958a21 start + 1
	)
Dec  3 12:34:56 Atticuss-MacBook-Pro SpringBoard[4380]: HW kbd: Failed to set (null) as keyboard focus
Dec  3 12:34:56 Atticuss-MacBook-Pro com.apple.CoreSimulator.SimDevice.B1FAC6C9-136F-4027-ADC8-3F1EFDC6283A.launchd_sim[4363] (UIKitApplication:com.robinpowered.rooms[0xa569][21558]): Service exited due to signal: Abort trap: 6
Dec  3 12:34:56 Atticuss-MacBook-Pro SpringBoard[4380]: Application 'UIKitApplication:com.robinpowered.rooms[0xa569]' crashed.
```

Example:
~~Example Removed~~

Version `1.3.1-beta`.
`jsCodeLocation = [CodePush bundleURL];` properly linked.

**Comment by ajwhite** [comment]
So a couple things are going on here.

One - A little user error on my part, the released version does an `IMMEDIATE` installation without an update dialog. 

However, it appears to continuously reload

**Comment by ajwhite** [comment]
I ended up having to do the following workaround to avoid it endlessly reinstalling the updated version (which did not appear to fail).

```js
CodePush.notifyApplicationReady();
Promise.all([
  CodePush.getCurrentPackage(),
  CodePush.checkForUpdate()
]).spread((current, update) => {
  if (!update) {
    return;
  }
  if (!current || current.packageHash !== update.packageHash) {
      CodePush.sync({
        updateDialog: false,
        rollbackTimeout: 10000,
        installMode: CodePush.InstallMode.IMMEDIATE
      });
    }
  }
});
```

Otherwise, `CodePush.sync` will continuously download, install, and restart the app

**Comment by lostintangent** [comment]
You should definitely not need to do all of that! Sorry for the invocenience. I just tried reproing this and I'm not sure what could be the issue.

`sync` uses `checkForUpdate` under the covers and will "short-circuit" if it resolves to `null`. If you remove the "if (!update)" block, as well as the "!current" expression in your second if statement, does this still work? I'm just wondering if there is something funky with the package hash comparison.

I'm looking into this right now. Thanks for the patience!

**Comment by ajwhite** [comment]
Exactly this -- If I don't wrap any conditions, and simply do `CodePush.sync`, it reinstalls. I compared the two hashes during this reinstallation period and they were the same

**Comment by ajwhite** [comment]
For privacy reasons, I'm going to remove the screen gif in 5 minutes, incase you need to save a copy.

**Comment by geof90** [comment]
Hi @ajwhite, can we verify that you indeed got back a package with the same package hash?
```
CodePush.notifyApplicationReady();
Promise.all([
  CodePush.getCurrentPackage(),
  CodePush.checkForUpdate()
]).spread((current, update) => {
  if (!update) {
    return;
  }
  if (!current || current.packageHash !== update.packageHash) {
    CodePush.sync({
      updateDialog: false,
      rollbackTimeout: 10000,
      installMode: CodePush.InstallMode.IMMEDIATE
    });
  } else if (current.packageHash == update.packageHash) {
    // Verify that this part of the code actually gets executed
  }
});
```

**Comment by ajwhite** [comment]
Since I'm running in production mode on the device using this, i can't console, so I threw in an `AlertIOS.alert('foo', 'bar')` in that equality check for the same package.

Confirmed that it fires repeatedly.

**Comment by geof90** [comment]
In https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L33, there is a queryPackage object that the SDK takes which is used to query the server for updates. The server is configured to check the package hash of the given query package and return an update if it exists. The server should not be returning an update with the same package hash if indeed it was supplied.

For example, https://codepush.azurewebsites.net/updateCheck?deploymentKey=YOUR_DEPLOYMENT_KEY&appVersion=1.0.0 may return an update, but https://codepush.azurewebsites.net/updateCheck?deploymentKey=YOUR_DEPLOYMENT_KEY&appVersion=1.0.0&packageHash=LATEST_PACKAGE_HASH will return no update.

What would be really helpful for us to debug this is if you could verify that this queryPackage object indeed has the packageHash object set. Also if you could obtain the URL query string of the call to the server here: https://github.com/Microsoft/code-push/blob/master/sdk/script/acquisition-sdk.ts#L89, that would also really help. Sorry for the trouble, we really just need more information as we have not been able to reproduce this issue.

**Comment by ajwhite** [comment]
Okay. I'll try to get back to you timely, but this may run into next week.

**Comment by lostintangent** [comment]
Hey @ajwhite, don't worry about it, we figured out the issue and I'm about to send our a PR that will let you remove all of that horrible workaround code you had to write :)

For the record, the issue was that you are putting a "v" in your app version when releasing from the CLI and so when our plugin would compare the running version, it did so as a dumb string comparison against the version associated with the latest update (e.g. does v2.0.0 === 2.0.0). We'll change this to use semver comparison (which is what the server already does) and everything will work perfectly for you.

I was also able to confirm that you are the only CodePush user that would have hit this issue, so fortunately you reported it and we can prevent anyone else from running into it :)

Thanks again for your patience and help with this!

**Comment by ajwhite** [comment]
OH man. It's been a long day.. Glad you guys narrowed that down! Fantastic, I'll keep my eyes out. We're very excited to use this tool :smile:

**Comment by lostintangent** [comment]
We're excited to have you use it! #85 was just submitted and we'll get that merged in soon and likely release it along to NPM with support for the new React Native asset system. I'm hoping that will land tomorrow and we'll snap the 1.4.0 release. Thanks again for reporting this error. I'm glad we caught this early :D

**Comment by ajwhite** [comment]
:+1: :100: :clap: 

> support for the new React Native asset system

Would this explain #4549? I just realized that build where my images were missing was likely synced from CodePush

**Comment by lostintangent** [comment]
Yeah that is our problem :( we'll get that PR merged by tomorrow and will publish to NPM. The new asset system landed while we were trying to finish Android support and so it got a little ahead of us.

**Comment by lostintangent** [comment]
Just merged in the fix for this via #85! Thanks again for helping us get to the better of this. Once the assets support gets merged in, I'll snap 1.4.0 and publish to NPM.

**Comment by ajwhite** [comment]
Fantastic, nice work :+1:

**Comment by kylezhang** [comment]
When I learn the first react-native demo,
use: react-native init Box
......
The next error

![snip20160124_1](https://cloud.githubusercontent.com/assets/3679798/12531926/b3bf0128-c241-11e5-8c44-9fbdcdfae2d4.png)

**Comment by lostintangent** [comment]
@kylezhang That error doesn't look like it has anything to do with CodePush. It would appear like there may be an issue with the sample you are running or Reacf Native. Maybe try checking the babelrc file that the red box references and see if it includes a setting that isn't valid?

**Comment by ajwhite** [comment]
@kylezhang in [0.16.0 of ReactNative](https://github.com/facebook/react-native/releases/tag/v0.16.0) they upgraded from Babel5 to Babel6. This is a large breaking change in how the `.bablerc` configuration files are structured. Many dependencies that are commonly found in React Native projects still use Babel5, while React Native compiles with Babel6. In your case, `react-deep-force-update` is using a Babel5 formatted `.babelrc`.

Discussion issue: https://github.com/facebook/react-native/issues/4062#issuecomment-162550776

Current workaround that I'm using: https://github.com/facebook/react-native/issues/4062#issuecomment-164598155

**Comment by kylezhang** [comment]
@lostintangent Thanks your answer, initializing and running the project

**Comment by kylezhang** [comment]
@ajwhite /(ㄒoㄒ)/~~
What can I do it？
Thanks！！！
