### ISSUE TITLE
[Android] App restart loop when using InstallMode.ON_NEXT_RESUME

### ISSUE THREAD

**Issue by AndrewJack** [Microsoft/react-native-code-push#841]
### Description

When `InstallMode.ON_NEXT_RESUME` is used on android the app will go into a restart loop and crash the app.

### Reproduction

1. Initialise with the following code push options
   ```
     {
          checkFrequency: CheckFrequency.ON_APP_RESUME,
          installMode: InstallMode.ON_NEXT_RESUME
      }
   ```
2. Run the app - wait for it to download the update
3. Press the home button
4. Resume the app from the multi task view
Observe: App will go black and into a loop of `onResume` -> `loadBundle`

I think the cause is around here - https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L470

### Additional Information

* react-native-code-push version: 2.0.3-beta
* react-native version: 0.44
* iOS/Android/Windows version: Android 7.1
* Does this reproduce on a debug build or release build? Release build
* Does this reproduce on a simulator, or only on a physical device? Reproduced on a device

**Comment by AndrewJack** [comment]
Trying to reproduce on the Example

**Comment by sergey-akhalkov** [comment]
Hi @AndrewJack, thanks for reaching us. 

>Trying to reproduce on the Example

Got it, this should be very useful for us, please let me know if any updates.

**Comment by AndrewJack** [comment]
@sergey-akhalkov I've figured it out.

- Enable proguard
- perform the same steps as above

Then this happens:
- `loadBundle` is called from `onResume`
- It then fails on this line (because proguard + reflection) https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L160
- This then is caught and `loadBundleLegacy ` is called - https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L84
- This then re-creates the activity
- Which calls `onHostResume` again - starting the infinite loop - https://github.com/Microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L473

Do we still need this legacy support in v2 of code push?

**Comment by AndrewJack** [comment]
I've fixed my code by adding `-keep class com.facebook.react.** { *; }` for now

**Comment by AndrewJack** [comment]
Things to fix:
1. Remove support for old react native versions that may not work anyway (and all the reflection)?
2. Fix loadBundleLegacy infinite loop if 1 isn't fixed.

**Comment by sergey-akhalkov** [comment]
@AndrewJack, thank you for such great investigation! I think we can remove support for old react native versions due to breaking changes that have been released in [v2.0.1-beta](https://github.com/Microsoft/react-native-code-push/releases/tag/v2.0.1-beta). We'll fix the issue asap, but if you have a time and ability you could help us to deliver this fix much faster by publishing pull request - we'll be very grateful. 

Please let us know if it works for you (if not, we'll start investigating and fixing it tomorrow) or if you have any questions.

**Comment by AndrewJack** [comment]
https://github.com/Microsoft/react-native-code-push/pull/845 - let me know if you need anything changed

**Comment by sergey-akhalkov** [comment]
@AndrewJack, thank you for the contribution! I'll review it and notify you if needed.

>I'm surprised code push doesn't have an supported react native api to setJSBundle yet.

I suppose that React Native module for CodePush have been implemented a long time ago and have supported big amount of react-native versions until v2.0.1-beta. As of now I think code-push could support react native api to setJSBundle. We'll investigate and implement it, thanks you for your advice. Please also let me know if you have any thoughts/advises that could help us to implement this better way.
