### ISSUE TITLE
addComponentAsRefTo(...): Only a ReactOwner can have refs.

### ISSUE THREAD

**Issue by Amurmurmur** [Microsoft/react-native-code-push#843]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens. Also exact reproduction steps and stack trace will be much appreciated.]
Without any additional libs in my app.js, it just keeps throwing an exception.
When using react-native-code-push for some weird reasons this gets thrown:
```
addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Object.addComponentAsRefTo
    ReactOwner.js:84:6
attachRef
    ReactRef.js:71:15
Object.ReactRef.attachRefs
    ReactRef.js:93:4
ReactCompositeComponentWrapper.attachRefs
    ReactReconciler.js:24:11
CallbackQueue.notifyAll
    CallbackQueue.js:75:21
ReactNativeReconcileTransaction.close
    ReactNativeReconcileTransaction.js:36:25
ReactNativeReconcileTransaction.closeAll
    Transaction.js:221:24
ReactNativeReconcileTransaction.perform
    Transaction.js:163:15
batchedMountComponentIntoNode
    ReactNativeMount.js:72:14

```

Here is my app.js
```
'use strict'
import codePush from "react-native-code-push";

import React, { Component } from 'react';
import { View, Text } from 'react-native';

class app extends Component {

  constructor(props){
    super(props)
  }

  componentDidMount() {
    if (!__DEV__)
      codePush.sync({
        updateDialog: true,
        installMode: codePush.InstallMode.IMMEDIATE
      });
  }

  render() {
    return (
        <View style={{flex: 1, backgroundColor: 'green'}}>
          <Text>TEST</Text>
        </View>
    );
  }
}

  app = codePush({ checkFrequency: codePush.CheckFrequency.MANUAL })(app);
  export default app;
```
Here is my index.ios.js
```
import { AppRegistry } from 'react-native'
import app from './src'

AppRegistry.registerComponent('app', () => app);
```

Though the code worked fine with react-native-navigation and react-native-router-flux.
Even though that I dont include anything in the app.js it for some weird reasons started that exception on me.

### Reproduction

[FILL THIS OUT: If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp. If you can't reproduce the bug on it, provide us as much info as possible about your project.]

react-native init projectname
yarn add react-native-code-push
yarn add react-navigation
react-native run-ios

### Additional Information

* react-native-code-push version: 2.0.3-beta
* react-native version: 0.44.0
* iOS/Android/Windows version: iOS
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device? Both

(The more info the faster we will be able to address it!)

Thank you very much in advance!

**Comment by max-mironov** [comment]
Hey @Amurmurmur, I have tried to reproduce your issue but with no luck. So basically I've done the following (as you have described):

```
react-native init RNIssue843
yarn add react-native-code-push
yarn add react-navigation
react-native run-ios
```

Also linked code-push with `react-native link react-native-code-push`.

My index.ios.js is as follows:
```import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import codePush from "react-native-code-push";

class RNIssue843 extends Component {

  constructor(props){
      super(props);
  }

  componentDidMount() {
    if (!__DEV__)
      codePush.sync({
        updateDialog: true,
        installMode: codePush.InstallMode.IMMEDIATE
      });
  }

  render() {
    return (
     <View style={{flex: 1}}>
          <Text>TEST</Text>
        </View>
    );
  }
}

RNIssue843 = codePush({ checkFrequency: codePush.CheckFrequency.MANUAL })(RNIssue843);

AppRegistry.registerComponent('RNIssue843', () => RNIssue843);

export default RNIssue843;
```

So could you please verify if my repro steps are correct or if you can reproduce the issue when starting from the scratch?

**Comment by Amurmurmur** [comment]
Omg I cant believe it,
react-native-router-flux was causing the problem, I completely uninstalled it, everything is smooth.

@max-mironov Thank you very much for testing it for me and for your time, so that I went into different direction and fixed the issue finally.
Nothing code-push related, AWESOME WORK and FAST response as usual.
👍 👍 👍 You are awesome guys, thank you. 👍 👍 👍

**Comment by max-mironov** [comment]
@Amurmurmur thank you for your kind words, you are always welcome!
