### ISSUE TITLE
Redefinition of enumerator

### ISSUE THREAD

**Issue by youngern** [Microsoft/react-native-code-push#849]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

[FILL THIS OUT: Explain what you did, what you expected to happen, and what actually happens. Also exact reproduction steps and stack trace will be much appreciated.]

### Reproduction

[FILL THIS OUT: If possible try to reproduce your bug on our basic sample: https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp. If you can't reproduce the bug on it, provide us as much info as possible about your project.]

### Additional Information

* react-native-code-push version: 1.17.0-beta
* react-native version: 0.35
* iOS/Android/Windows version: El Capitan 10.11.6
* Does this reproduce on a debug build or release build? Debug
* Does this reproduce on a simulator, or only on a physical device?
Simulator, haven't tested on a real device

(The more info the faster we will be able to address it!)

I included code push on the app,
It builds fine, but then when I include the line
#import <CodePush/CodePush.h>

I get these errors:

../node_modules/react-native/React/Base/RCTJavaScriptLoader.h:17:3: error: redefinition of enumerator 'RCTJavaScriptLoaderErrorNoScriptURL'
  RCTJavaScriptLoaderErrorNoScriptURL = 1,
  ^
...

I get about 20 errors like this.

I have included the info.pList key but since I'm just in debug it should just be using debug local source.. I haven't included the bundle import line yet. Only the CodePush import statement.

Is there something else I need to do?

**Comment by youngern** [comment]
I had to remove the derivedData folder..

**Comment by rzrobert** [comment]
Are you fix it? I have the same problem……

**Comment by youngern** [comment]
@rzrobert yes, I couldn't pinpoint the exact issue but it has something do with the way Xcode caches build data.

Delete the folder associated with your project in the DerivedData folder

`rm -rf ~/Library/Developer/Xcode/DerivedData/<your project folder>`

If your project name is your_project, it should be some folder called `your_project-[rand string]`

cheers

**Comment by rzrobert** [comment]
Mabey you can change the way for import like this(node_modules/react-native/React/Base):
#import <React/RCTDefines.h>
//#import "RCTDefines.h"

**Comment by rzrobert** [comment]
@youngern Mabey you can change the way for import like this(node_modules/react-native/React/Base):
#import <React/RCTDefines.h>
//#import "RCTDefines.h"
