### ISSUE TITLE
CodePush not in ApplicationSupport folder

### ISSUE THREAD

**Issue by rawpaw** [Microsoft/react-native-code-push#854]
I've integrated codepush into my project using cocaopods, as well as react stuff.
Everything builds and runs, on my device using "[CodePush bundleURL]". However, I noticed that it never shows "[CodePush] Checking for update."
I dug further and saw that it's looking for a folder ('CodePush') in the ApplicationSupport folder, but it's not there. The ApplicationSupport folder is not created.

**Comment by sergey-akhalkov** [comment]
Hi @rawpaw, thanks for reaching us. Could you please share with us content or your pod file and way you are using CodePush to check for updates (js code)?

**Comment by rawpaw** [comment]
Hi @sergey-akhalkov , thanks for responding. I have managed to get this working. I think it was because I didn't have "jsCodeLocation = [CodePush bundleURL];" in the AppDelegate.m file but had it in a separate file (for good reason).

**Comment by sergey-akhalkov** [comment]
@rawpaw, got it, thanks for the clarification, please feel free to reopen if needed.
