### ISSUE TITLE
Production app is not getting updated, giving error ReactNative: [CodePush] Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.

### ISSUE THREAD

**Issue by sudhanshu6247** [Microsoft/react-native-code-push#856]
It was working fine, but for last 10-15 days it's started giving following error
 
**ReactNative: [CodePush] Unable to get the hash of the binary's bundled resources - "codepush.gradle" may have not been added to the build definition.**

and no change is getting reflected on production app through code-push.

my android/app/build.gradle file is
    
       apply plugin: "com.android.application"
      buildscript {
          repositories {
              maven { url 'https://maven.fabric.io/public' }
          }
          dependencies {
              classpath 'io.fabric.tools:gradle:1.+'
          }
      }
      apply plugin: 'io.fabric'
      repositories {
          maven { url 'https://maven.fabric.io/public' }
          mavenCentral()
      }
      
      import com.android.build.OutputFile
      
      apply from: "../../node_modules/react-native/react.gradle"
      apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"
      
      def enableSeparateBuildPerCPUArchitecture = false
      
      def enableProguardInReleaseBuilds = false
      
      android {
          compileSdkVersion 23
          buildToolsVersion "25.0.0"
      
          defaultConfig {
              applicationId "com.healthmir.sympler"
              minSdkVersion 16
              targetSdkVersion 22
              versionCode 71
              versionName "7.1"
              ndk {
                  abiFilters "armeabi-v7a", "x86"
              }
          }
          splits {
              abi {
                  reset()
                  enable enableSeparateBuildPerCPUArchitecture
                  universalApk false  // If true, also generate a universal APK
                  include "armeabi-v7a", "x86"
              }
          }
          buildTypes {
              debug {
                  buildConfigField "String", "CODEPUSH_KEY", '""'
              }
        releaseStaging {
                  buildConfigField "String", "CODEPUSH_KEY", '"xxxxxxxxxxxxx"'
              }
              release {
                  minifyEnabled enableProguardInReleaseBuilds
                  proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
                  buildConfigField "String", "CODEPUSH_KEY", '"xxxxxxxxxxx"'
              }
          }
          applicationVariants.all { variant ->
              variant.outputs.each { output ->
                  def versionCodes = ["armeabi-v7a":1, "x86":2]
                  def abi = output.getFilter(OutputFile.ABI)
                  if (abi != null) {  // null for the universal-debug, universal-release variants
                      output.versionCodeOverride =
                              versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
                  }
              }
          }
      }
      
      dependencies {
          compile project(':react-native-photo-view')
          compile project(':react-native-tts')
          compile project(':react-native-device-info')
          compile project(':react-native-fbsdk')
          compile project(':react-native-share')
          compile project(':react-native-android-sms-listener')
          compile project(':react-native-code-push')
          compile project(':react-native-google-analytics-bridge')
          compile project(':react-native-fabric')
          compile(project(':react-native-google-signin')) {
              exclude group: "com.google.android.gms" // very important
          }
          // should be at least 9.0.0
          compile project(':react-native-facebook-login')
          compile project(':react-native-push-notification')
          compile 'com.google.android.gms:play-services-gcm:10.2.1'
          compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
              transitive = true;
          }
          //compile project(':rn-splash-screen')
          compile project(':react-native-razorpay')
          compile project(':react-native-splashscreen')
          compile project(':react-native-video')
          compile project(':react-native-image-picker')
          //    compile project(':react-native-sound')
          compile project(':react-native-simpledialog-android')
          // compile project(':rn-splash-screen')
          compile project(':react-native-vector-icons')
          compile project(':react-native-linear-gradient')
          compile 'com.google.android.gms:play-services-auth:10.2.1'
          compile 'com.google.android.gms:play-services-analytics:10.2.1'
          compile project(':react-native-material-kit')
          compile project(':react-native-i18n')
          compile project(':react-native-svg')
          compile project(':react-native-sound')
          compile project(':VoiceModule')
          compile fileTree(include: ['*.jar'], dir: 'libs')
          compile 'com.android.support:appcompat-v7:25.0.0'
          compile 'com.facebook.react:react-native:+'
          // From node_modules
          compile project(':react-native-shared-preferences')
          //    compile project(':RNSimpleAlertDialogModule')
      
          // If your app supports Android versions before Ice Cream Sandwich (API level 14)
          compile 'com.facebook.fresco:animated-base-support:0.11.0'
          // For animated GIF support
          compile 'com.facebook.fresco:animated-gif:0.11.0'
          // For WebP support, including animated WebP
          compile 'com.facebook.fresco:animated-webp:0.11.0'
          compile 'com.facebook.fresco:webpsupport:0.11.0'
          // For WebP support, without animations
          compile 'com.facebook.fresco:webpsupport:0.11.0'
          compile 'com.facebook.android:facebook-android-sdk:[4,5)'
          compile project(':OptimiseSdk_2.1.1')
      }
      
      task copyDownloadableDepsToLibs(type: Copy) {
        from configurations.compile
        into 'libs'
      }
      apply plugin: 'com.google.gms.google-services' // <--- this should be the last line
      
I am generating signed apk from android studio and inside apk there is no "CodePushHash.json" file.

versions:
"react-native": "^0.34.1",
"react-native-code-push": "^1.15.0-beta"

Please help.

**Comment by sergey-akhalkov** [comment]
Hello @sudhanshu6247, thanks for reaching us and sorry for late reply. 
Could you please clarify which way you are building your apk in release mode? Are  you running `gradlew assembleRelease` command?

**Comment by sergey-akhalkov** [comment]
@sudhanshu6247, I'm closing this for now, please feel free to reopen.

**Comment by sujitpk-perennial** [comment]
Hello @sergey-akhalkov I am also facing the same issue. My app is already live. I already did 4-5 times code-push to update the app functionality for Android. Now I have added auth, share functionality in the app. But currently I commented the code. But auth, share package is already there is node_modules. Is addition of new package giving me this issue ?

**Comment by rajatgalav** [comment]
Hii **@sergey-akhalkov**  I am also facing the same issue. It was working when i released app using `./gradlew assembleRelease`. But now i am using bundle to upload the app `./gradlew bundleRelease` it is not working now.

**Comment by kaushil111** [comment]
I have the same issue as @rajatgalav
