### ISSUE TITLE
Using forked version of react-native 0.43.3 with code-push 2.0.2-beta is causing errors

### ISSUE THREAD

**Issue by shrutic** [Microsoft/react-native-code-push#858]
### Description

I am using a forked version of react-native 0.43.3 with 2.0.2-beta with my  project. I have recently started developing on  Android and I have started seeing the errors reported in this issue https://github.com/Microsoft/react-native-code-push/issues/792 even though I am on RN 43 ( albiet a forked version)

### Additional Information

* react-native-code-push version: 2.0.2-beta
* react-native version: 0.43.3 ( with some custom fixes inside my fork) . Entry in my package.json 
    "react-native": "git://github.com/shrutic/react-native.git#AppExtensionSafe-ReactNative",
* iOS/Android/Windows version: Android 6.0 on emulator
* Does this reproduce on a debug build or release build? debug build
* Does this reproduce on a simulator, or only on a physical device? repros on emulator . 

(The more info the faster we will be able to address it!)

**Comment by chirag04** [comment]
in our RN fork, we publish the archives for android. It should work then. eg: https://github.com/facebook/react-native/compare/master...4Catalyzer:17_4_6

**Comment by shrutic** [comment]
Thanks for your response, Chirag. 

When I remove the /android/ entry from .gitignore, I don't get any other files added. Seems like I need to compile react-native somehow to generate the archives. Could you let me know how I can do that?

**Comment by sergey-akhalkov** [comment]
Hi @shrutic, thanks for reaching us. I've just tried to set up clean project that uses `react-native@0.43.3` and `react-native-code-push@2.0.2-beta` and it works well for me. So I don't sure about your fork, but official version of RN compiles well with CodePush and I can not see any issues. So could you please try to install official version of `react-native@0.43.3` and verify if the issue still reproduces?

**Comment by shrutic** [comment]
Code push works just fine upon pointing to 0.43.3 version directly but fails with my forked version.

Upon further investigation, I hit similar errors ( Unable to locate symbol ) even after removing codepush from my android project. 

Then I found out that as per the react-native documentation, there are additional steps to be followed for android when using a forked version of react-native here [Building React native from source for android](https://facebook.github.io/react-native/docs/android-building-from-source.html ). 

Upon following the above steps, all the "Unable to locate symbol" errors without codepush were resolved. But upon adding codepush, the react-native errors still showed up. So for now, I have removed codepush from our project. I will continue to investigate why these errors are still happening

**Comment by sergey-akhalkov** [comment]
@shrutic, got it, thanks for the clarification, please let me know if you have any questions.

**Comment by sergey-akhalkov** [comment]
@shrutic, closing this for now, please let me know if any changes.

**Comment by shrutic123** [comment]
@chirag04 could you help me with **_how to publish archives from React native fork_**. I could not find any instructions on how to do that in a fork. All the instructions I see are how to compile React native android from source.

Would really appreciate your help as this is blocking me from using many third party libraries in Android.

**Comment by shrutic** [comment]
@chirag04 could you help me with **how to publish archives from React native fork**. I could not find any instructions on how to do that in a fork. All the instructions I can find  are [how to compile React native android from source](https://facebook.github.io/react-native/docs/android-building-from-source.html#content).

Would really appreciate your help as this is blocking me from using many third party libraries in Android.

**Comment by shrutic** [comment]
Thanks for the quick response. I tried the command and was able to generate the jar files. I created a new branch in my fork with these jar files checked in and updated my package.json to point to my new file. After "npm install", I still get the "Unable to locate the symbol" errors. I looked at the publish-npm.js and I did not see any additional steps except npm publish. Do I have to do a npm publish against my fork? I am not sure how that would work. 

![image](https://user-images.githubusercontent.com/4141641/26849233-3e97c5f0-4ab8-11e7-9e85-c6c72ccd0167.png)

**Comment by chirag04** [comment]
@shrutic your fork looks good to me. make sure you are not building from source when switching to your fork. also double check you are install react native from your fork. No need to publish your fork to npm.

**Comment by shrutic** [comment]
@chirag04 I was indeed building from the source in my project where I was using my fork of react-native. 
I updated my project to no longer build react-native from source. I also made sure that the react-native installed in node_modules is indeed from my fork ( my iOS version of project does not compile if the code isnt from my fork). But I still get the errors I showed in my earlier message. 

Should I make sure that that generated android archive files are also downloaded correctly? Where would they be present in the node_modules?

**Comment by shrutic** [comment]
I could not find the android directory under react-native in node_modules. The relevant path that I did find is ... node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react. But I did not find the react-native directory under it where all the generated archives seemed to get placed when I created the PR https://github.com/shrutic/react-native/commit/b4b09493d4558a6aae2169253d7d490021a849f4. Does this mean the fork was not correctly downloaded?

I made sure I had the line you specified in my build.gradle.. :(  As I mentioned before, I dont get this problem if I point to the facebook's react-native version directly. It happens only when I switch to my fork. I will try to create a new project with my specific third party libraries against my fork and see if that gives any insights

**Comment by chirag04** [comment]
you should have files like these in your node_modules/react-native/android/com/facebook/react/react-native.

<img width="506" alt="screen shot 2017-06-06 at 5 14 12 pm" src="https://user-images.githubusercontent.com/954063/26852234-9b527b1e-4adb-11e7-9196-e5e73ef845e5.png">

**Comment by shrutic** [comment]
I do not have the directory android in my node_modules/react-native. 
This is how I reference my forked branch in my package.json

    "react-native": "git://github.com/shrutic/react-native.git#AndroidWorkingTrial",

Am I missing something? Maybe this mode of referencing forks does not download everything?
