### ISSUE TITLE
[CodePush] An unknown error occurred.

### ISSUE THREAD

**Issue by bogdantmm92** [Microsoft/react-native-code-push#86]
From my debugging I concluded that  "currentPackage" is empty for me.
"queryUpdateWithCurrentPackage" builds this link 
```https://codepush.azurewebsites.net/updateCheck?deploymentKey=Staging&appVersion=1.2.4&packageHash=&isCompanion= ```

I'm doing this in the first component: http://puu.sh/lIV4z/1bbc353fa3.png

**Comment by dtivel** [comment]
"Staging" is a deployment name, but updateCheck takes a deployment key.  You can see the deployment key for your Staging deployment by running the following command, where <AppName> is the name of your app.

    code-push deployment list <AppName>

For example, running it on my app "My App":

    code-push deployment list "My App"

...yields:

![deployments](https://cloud.githubusercontent.com/assets/12734758/11597238/83bf9662-9a6f-11e5-9dd4-f0a4dbe4b244.png)

**Comment by bogdantmm92** [comment]
Indeed, that was the problem. Maybe you guys could make it more clear by showing this image in the documentation.
Thanks a lot!

**Comment by dtivel** [comment]
Great, I'm glad that worked.

**Comment by lostintangent** [comment]
Hey @bogdantmm92, I just submitted PR #88. Could you let me know if you think that is enough detail or if we could help make this less confusing? Thanks so much!

**Comment by MrPluto** [comment]
what will throw  "An unknown error " ??  i got the error when i change the key in plist file

**Comment by lostintangent** [comment]
Two common causes are:

1. Your deployment key isn't valid. Make sure you're setting it to the key value (not the name like "Staging") of the intended app deployment
2. Your version number isn't server compliant in the plist file (e.g. It's 1.0 not 1.0.0)

Are you seeing this error as part of the update check? Or after downloading it/installing it?

**Comment by MrPluto** [comment]
just  when i open my simulator. and CodePush log Checking for update ,then log An unknown error.
something confused me, what does  [CodePush bundle] work?   seems my code doesn't work if i choose this line ?

**Comment by MrPluto** [comment]
forgive me, i cant remerber sync or checkForupdate method.

**Comment by sulliwane** [comment]
I have same problem on ios, **[CodePush] An unknown error occurred. **

I just checked my deployment key and my version number, both are valid. Spent 2 hours on this without success...any idea to isolate the problem?

thanks.

**Comment by sulliwane** [comment]
the problem was this issue: https://github.com/Microsoft/react-native-code-push/pull/94
Solved now with 1.4.1

**Comment by lostintangent** [comment]
Awesome! BTW, I just checked in a fix to log any error to the console when an "unknown error" occurs. That way it's more obvious in the future what the exact issue is.

**Comment by akshaysmurthy** [comment]
@lostintangent Where are you logging this error you mentioned above? I am asking this because we cannot really debug in Chrome to see the log when we are using CodePush to provide the JS bundle.

**Comment by lostintangent** [comment]
@akshaysmurthy You can view the logs in either the Xcode console or the ADB logcat output for React Native (depending on the platform you're running). When an unknown error happens during sync, we log the error message along with it, so hopefully you can see the issue.

Did this error just start for you or are you seeing it on a new project?

**Comment by akshaysmurthy** [comment]
@lostintangent Thanks I'll check the logs out tonight (I am indeed using Xcode). And yes, I started seeing the error message since yesterday.

**Comment by akshaysmurthy** [comment]
@lostintangent Interestingly enough I do not see it anymore -¯\_(ツ)_/¯ Thanks :)

**Comment by lostintangent** [comment]
Hmm, Ok :) Let us know if you hit any other issues!

**Comment by cxy200927099** [comment]
hi @lostintangent : 
   I also get a unknown error, and my deployment key and my version number both are valid.
When i open the link: [https://codepush.azurewebsites.net/updateCheck?deploymentKey=pw_ho269Dv5tqs8XxjSm7bvv0YraEyNXGfLOM&appVersion=1.0.2&packageHash=&isCompanion=](url)
i got:
`{
    "updateInfo": {
        "downloadURL": "https://codepush.blob.core.windows.net/storagev2/EH-s83BXWNqcgPeHv7SYL_qJ0LaNEyNXGfLOM",
        "description": "1.修改了背景颜色为白色；2.修改了顶部的间距",
        "isAvailable": true,
        "isMandatory": false,
        "appVersion": "1.0.2",
        "packageHash": "9493b3c803d3925ae4579c2c2930a0051cc7fafbecc286b455079c87222d9f9f",
        "label": "v3",
        "packageSize": 169750,
        "updateAppVersion": false,
        "shouldRunBinaryVersion": false
    }
}`

and the adb log as bellow:
`I/ReactNativeJS( 2462): Running application "helloworld" with appParams: {"initialProps":{},"rootTag":11}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
I/ReactNativeJS( 2462): [cxy] function (t, e) {"object"!=typeof t&&"function"!=typeof t&&null!=t?s("85"):void 0,this.updater.enqueueSetState(this,t),e&&this.updater.enqueueCallback(this,e,"setState");}
I/ReactNativeJS( 2462): [cxy] syncStatus=5
**I/ReactNativeJS( 2462): [CodePush] Report status failed: {"appVersion":"1.0.2"}**
I/ReactNativeJS( 2462): [cxy] function (t, e) {"object"!=typeof t&&"function"!=typeof t&&null!=t?s("85"):void 0,this.updater.enqueueSetState(this,t),e&&this.updater.enqueueCallback(this,e,"setState");}
I/ReactNativeJS( 2462): [cxy] syncStatus=3
**I/ReactNativeJS( 2462): [CodePush] Network request failed**`

could you help me ? thank you

**Comment by kaushikwavhal** [comment]
I was getting this error  since i had a non default bundle name and i was releasing code push with default bundle name. Adding bundle name to the release command with -b flag solved this issue.
