### ISSUE TITLE
getUpdateMetadata may return an empty string on android

### ISSUE THREAD

**Issue by jay1337** [Microsoft/react-native-code-push#862]
Hello,

On android in some case, I get an empty string instead of a null value when I call getUpdateMetadata with no arguments.
It seems normal since the native android code resolves getUpdateMetadata as an empty string in some cases.
But in the documentation it's written that getUpdateMetadata return a LocalPackage or null...

If I'm right, can you update the documentation or fix the code ?

Thanks.

**Comment by max-mironov** [comment]
@jay1337 - thank you so much for pointing at this. 
I've added [PR](https://github.com/max-mironov/react-native-code-push/commit/e122824a2c025ac77ca00363528c25d3d4a2bf67) to fix this inconsistency (have tried this on emulator and real device with Android 7 and RN 0.44 and CP 2.0.3-beta) - could you please also verify if it works for you on your side?

**Comment by max-mironov** [comment]
@jay1337 - hi, please let us know if you have a chance to look at this.

**Comment by jay1337** [comment]
@max-mironov I'm not able to test it but your PR seems ok

**Comment by sergey-akhalkov** [comment]
Closing this due to #864 has been merged.
