### ISSUE TITLE
compile project(':react-native-code-push') not added by auto link

### ISSUE THREAD

**Issue by yaronlevi** [Microsoft/react-native-code-push#863]
When running the react-native link command, it does not add the compile project(':react-native-code-push') line to android/app/build.gradlec file.

React Native@0.44.0

**Comment by max-mironov** [comment]
Hi @yaronlevi, thank you for reaching us.
I've tried to use `react-native link react-native-code-push` and looks like it adds `compile project(':react-native-code-push')` line to my android/app/build.gradle file (I'm on RN 0.44.2).
I've done the following:
1) `react-native init MyProjectName`
2) `npm install --save react-native-code-push@latest`
3) `react-native link react-native-code-push`.

So it looks like this dependency should be added at this [step](https://github.com/facebook/react-native/blob/master/local-cli/link/link.js#L56).

Could you please clarify if I'm missing something or your repro steps are different?

**Comment by max-mironov** [comment]
@yaronlevi - hi again, please let us know if you still experience the issue.

**Comment by max-mironov** [comment]
@yaronlevi
I believe we can close the issue currently, please reopen or create a new item if you have any issues with this going further.
