### ISSUE TITLE
codepush rollbacks after successful deploys when using wix/react-native-navigation 

### ISSUE THREAD

**Issue by grigored** [Microsoft/react-native-code-push#875]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

When using wix/react-native-navigation/ , code update works fine until restarting the app. Then it rollbacks to the previous version.

### Reproduction
1. clone the react-native-navigation example
`git clone https://github.com/JuneDomingo/movieapp`
1. install codepush
1. when modifying `src/app.ios.js` by adding @codePush decorator, the app gets stuck, so I tried #4 below
1. import codepush and add codepush in constructor
```
        constructor(props) {
		super(props);
		iconsLoaded.then(() => {
			this.startApp();
			codePush.sync({
	            installMode: codePush.InstallMode.IMMEDIATE
	        });
		});
	}
```
5. install on device

### Additional Information

* react-native-code-push version: 2.0.3-beta
* react-native version: 0.42.3
* iOS/Android/Windows version: 
* Does this reproduce on a debug build or release build? release build
* Does this reproduce on a simulator, or only on a physical device? both

(The more info the faster we will be able to address it!)

**Comment by grigored** [comment]
After spending several hours on this, i finally found a solution/workaround:
1. I wasn't able to make codePush.sync work, no matter where i put the sync/notifyAppReady functions.
1. I tried wrapping the startSingleScreenApp() in a React component, but for some reason that didn't work either. 
1. I tried wrapping the main screen component in @codePush, and that partially worked, but static methods were not copied by the codePush HOC. The answer to this is [in the react docs](https://facebook.github.io/react/docs/higher-order-components.html#static-methods-must-be-copied-over), was considering creating a pull request for this, but I don't have the time right now.
1. So what I did that finally solved the problem, is I created another react component:
```
import React from "react";
import codePush from "react-native-code-push";

@codePush({
    installMode: codePush.InstallMode.ON_NEXT_RESUME,
    checkFrequency: codePush.CheckFrequency.ON_APP_RESUME,
})
export class CodePushComponent extends React.Component {
    render() {
        return null;
    }
}
```
and then just rendered that component in the main screen. This way, I'm using the recommended decorator method. Not sure what kind of sorcery that decorator is doing that I couldn't replicate with sync/notifyAppReady.

**Comment by sergey-akhalkov** [comment]
Hi @grigored, got it, thank you for the information, please feel free to reopen if needed. Also let us know if you have any questions or see any issues.

**Comment by grigored** [comment]
An issue I definitely see is what I mentioned at 3: the codepush HOC doesn't copy static data. I had this problem elsewhere, and am using hoistNonReactStatic to solve it, as described in the [react docs](https://facebook.github.io/react/docs/higher-order-components.html#static-methods-must-be-copied-over).

**Comment by grigored** [comment]
And there's one more thing I had to do to make it work, that I didn't

**Comment by oliviachang29** [comment]
Thanks for the workaround 👍 
Worked in my app as well.

**Comment by tmaly1980** [comment]
@grigored That works for me, except I needed to add 'default' to the export since I had it in a separate file. I would LOVE to see this in the official docs.

**Comment by grigored** [comment]
@tmaly1980 The decorator is just syntactic sugar, you don't have to use it. It's equivalent to the code below
```
class CodePushComponent extends React.Component {
....
}

export default @codepush(options)(CodePushComponent)
```

**Comment by tuanphamanh91** [comment]
I did this way but my codepush get rollback a lot, about 33% got rollback. Does anyone get this problem?
