### ISSUE TITLE
React Native 0.45 support

### ISSUE THREAD

**Issue by sattaman** [Microsoft/react-native-code-push#878]
Is React Native 0.45 supported yet?

**Comment by sergey-akhalkov** [comment]
Hi @sattaman, thanks for reaching us, we will check for compatibility soon and will update [this table](https://github.com/Microsoft/react-native-code-push#supported-react-native-platforms). We also let you know if any updates.

**Comment by hose314** [comment]
I run 0.45 in production with code push. Currently everything is okay.

**Comment by sergey-akhalkov** [comment]
Hey guys, I would recommend you to avoid of using CodePush with RN 0.45 for now, due to new version of RN has some breaking changes that does not allow CodePush to reload js bundle, in another words `CodePush.restartApp` and the following install mods are not work with RN 0.45: `IMMEDIATE`, `ON_NEXT_RESUME`, `ON_NEXT_SUSPEND`.
I've also created new issue in RN: https://github.com/facebook/react-native/issues/14533

So I'll let you know if any updates.

**Comment by hose314** [comment]
@sergey-akhalkov thanks for the warning. Sorry for confusion on iOS is everything is okay. Can confirm that im also encountered with the same issue on Android described above.

**Comment by SudoPlz** [comment]
Ok so does that mean that if we use `ON_NEXT_RESTART` it's fine to still use RN 0.45 ?

**Comment by sergey-akhalkov** [comment]
Hi @SudoPlz, correct, `ON_NEXT_RESTART` install mode works well both for Android and iOS.

**Comment by SudoPlz** [comment]
Awesome, thanks Sergey!

**Comment by maximeaubaret** [comment]
I haven't been able to CodePush work on RN 0.45.1, even with `ON_NEXT_RESTART`. I tried using the HOC and calling sync directly with the same results.

When I force quit the app to force the CodePush install, the app crashes. I've tested this on iOS.

**Comment by nerdmed** [comment]
Same here, only works on restarts! But its really important to get `ON_NEXT_RESUME` running, seriously who is restarting his apps 💃 ?  Anyone tried to manually download and refresh the bundle on the app resume event? I had a workaround some time ago.

**Comment by yaronlevi** [comment]
Also note that if you used the **--mandatory** flag it forces a restart, which will cause a crash.

**Comment by sergey-akhalkov** [comment]
Hey guys, the issue I've created https://github.com/facebook/react-native/issues/14533 is probably stuck,  so I've investigated it deeper by myself and I believe that I've implemented solution that should work - https://github.com/Microsoft/react-native-code-push/issues/901.

Could you guys please try this PR and let me know if it works or if you see any issues?

**Comment by sergey-akhalkov** [comment]
Closing this due to https://github.com/Microsoft/react-native-code-push/releases/tag/v3.0.0-beta has been released.
