### ISSUE TITLE
[iOS] crash after finished downloading the update

### ISSUE THREAD

**Issue by tonylkc** [Microsoft/react-native-code-push#879]
### Description

After update my project from RN0.39 to RN0.44, the app will crash without a proper error during the update process.
<img width="1139" alt="screen shot 2017-06-09 at 10 55 13 pm" src="https://user-images.githubusercontent.com/12801030/26981287-42c963de-4d67-11e7-9462-62a01cbbdfe3.png">

### Additional Information

* react-native-code-push version: 2.1.0-beta
* react-native version: 0.44.0
* iOS version: 10
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

Thanks!

**Comment by tonylkc** [comment]
I have tried the create a new project and put my code back to this new project. However, its still has the same error.

**Comment by sergey-akhalkov** [comment]
Hi @tonylkc, thanks for reaching us. Could you please check if you have [the same issue as here](https://github.com/Microsoft/react-native-code-push/issues/775#issuecomment-291534691)? If not, please share with us the source code where you are calling sync function, so we could figure out your CodePush settings (checkFrequency, installMode, etc.)
As for me, I've successfully released and installed CodePush update using react-native version 0.44.0 and react-native-code-push version 2.1.0-beta with the following app source code: https://github.com/Microsoft/react-native-code-push/tree/master/Examples/CodePushDemoApp

**Comment by sergey-akhalkov** [comment]
@tonylkc, just a friendly ping.

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen if any updates.
