### ISSUE TITLE
The codepush HOC doesn't copy static data

### ISSUE THREAD

**Issue by sergey-akhalkov** [Microsoft/react-native-code-push#882]
Details in point 3 from https://github.com/Microsoft/react-native-code-push/issues/875#issuecomment-306776606

**Comment by pniko** [comment]
Prioritized for investigation later on. Please take a look @sergey-akhalkov when you have some bandwidth.

**Comment by max-mironov** [comment]
Closing the item since fix for it https://github.com/Microsoft/react-native-code-push/pull/1037 has been merged.
