### ISSUE TITLE
CodePush with Salesforce SDK

### ISSUE THREAD

**Issue by booker-laputa** [Microsoft/react-native-code-push#883]
### Description

I tried to install react-native-code-push for my Salesforce project, I expect it is the same as the normal react native project. However I found the iOS project resulted some crash, likeApple Mach-O Linker Error.

After that it result in error after code push imported.

### Reproduction

1. `npm i forceios` install forceios
2. `forceios create` to create react native project
3. `npm i react-native-code-push --save`
4. `react-native link react-native-code-push`

### Additional Information

* react-native-code-push version: @latest
* react-native version: 0.43.1
* iOS/Android/Windows version: iOS
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? simulator

**Comment by sergey-akhalkov** [comment]
Hi @booker-laputa, thanks for reaching us. Could you please take a look at [iOS Setup guide](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md) and verify if you have the same setup as yours?

Please let me know if it help or if you still experiencing the issue.

**Comment by booker-laputa** [comment]
@sergey-akhalkov Yes, I have tried `react-native link` method and the manually setup method.

I have checked that `forceios` create a different pattern of react native project and it breaks the auto link.

I have no idea how can I integrate CodePush with Salesforce SDK

**Comment by sergey-akhalkov** [comment]
@booker-laputa, I've figured out that Salesforce SDK uses [pod file](https://cocoapods.org/) for project dependencies, so [you need to add](https://github.com/Microsoft/react-native-code-push/blob/master/docs/setup-ios.md#plugin-installation-ios---cocoapods) `pod 'CodePush', :path => '../node_modules/react-native-code-push'` line into the `myapp/ios/Podfile`. Please try and let me know if any changes.

**Comment by booker-laputa** [comment]
@sergey-akhalkov Thanks! It's working now.
I added the `pod 'CodePush', :path=> '../node_modules/react-native-code-push'`, run `pod install`
Configure the project manually.

However `react-native link react-native-code-push` will damage the project, I don't know why.

Thanks for your help again!

**Comment by sergey-akhalkov** [comment]
Hi @booker-laputa, thanks for your response, closing this, please feel free to reopen if needed.
