### ISSUE TITLE
App crashes when close it while installing update

### ISSUE THREAD

**Issue by sergey-akhalkov** [Microsoft/react-native-code-push#885]
### Reproduction

1. Start update
2. immediately double tapping the home button and swiping up to remove the app from memory
3. relaunching the app

Actual: app crashes
Expected: update should be applied

* react-native-code-push version: 2.1.0-beta
* react-native version: 0.44.0
* iOS/Android/Windows version: iOS 10.3.2
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by iageoghe** [comment]
For me it crashes even if the update has been completed.

**Comment by sergey-akhalkov** [comment]
Hi @iageoghe, I've investigated the issue and tried to reproduce it - but with no luck, the app does not crash. 
The only issue I can see - update does not applied after successful installation. I've found the root cause of this issue - we need to [decorate our main component here](https://github.com/iageoghe/PreBuiltDemo/blob/master/app/index.js#L99) like this: 
```js
Pre_Built_Demo = CodePush({ checkFrequency: CodePush.CheckFrequency.MANUAL })(Pre_Built_Demo);

AppRegistry.registerComponent('Pre_Built_Demo', () => Pre_Built_Demo);
```
In case the update process has been interrupted by closing the app - the app asks to update again on next app start.
I'll try to reproduce the issue again and let you know if any changes, please also let me know if you have any ideas.

**Comment by iageoghe** [comment]
@sergey-akhalkov I added you a Pre_Built_Demo project that I built. Here are the repro steps to causing the issue on your iPhone:

1. Install update
2. Double click the home button; swipe up removing the app from memory
3. Restart the app

### Expectation
* App will still have update

### Bug
* The update will have been rolledback.
