### ISSUE TITLE
【android，reactnative】first install app and the first launch no update

### ISSUE THREAD

**Issue by dongbingbin77** [Microsoft/react-native-code-push#887]
I first install my app ，and first start it，no update，I set config 

class MyApp extends Component {}
MyApp = codePush({ updateDialog: false, installMode: codePush.InstallMode.IMMEDIATE })(MyApp);

**Comment by dongbingbin77** [comment]
but the second started ，app update

**Comment by dongbingbin77** [comment]
it is that a bug？

**Comment by sergey-akhalkov** [comment]
Hi @dongbingbin77, thanks for reaching us, please take a look at [issue template](https://github.com/Microsoft/react-native-code-push/issues/new) and fill it out - it would help us to investigate and reproduce the issue.

Please also let me know if you have any questions.

**Comment by sergey-akhalkov** [comment]
Closing this due to https://github.com/Microsoft/react-native-code-push/issues/890 has been created.
