### ISSUE TITLE
first install the app and the first time to start the app, can not be updated through the codepush

### ISSUE THREAD

**Issue by dongbingbin77** [Microsoft/react-native-code-push#890]
### Description

I first install the app and the first time to start the app, can not be updated through the codepush, after the second start to normal update, I set the update is updated immediately, the code is as follows

### Reproduction

```js
componentWillMount(){
        if (Platform.OS == 'android'){
            codePush.sync({
                updateDialog: false,
                installMode: codePush.InstallMode.IMMEDIATE
            });
        }
    }
```

### Additional Information

* react-native-code-push version:2.1.0-beta
* react-native version:0.44.0
* iOS/Android/Windows version:Android 7.1
* Does this reproduce on a debug build or release build?  yes
* Does this reproduce on a simulator, or only on a physical device? on a physical device

**Comment by sergey-akhalkov** [comment]
Hi @dongbingbin77, thanks for filling out issue template. Please try to more your `codePush.sync({` call into the `componentDidMount` method and let me know if any changes.

**Comment by dongbingbin77** [comment]
you mean I call the codePush.sync({  method again like this
    componentWillMount(){
        if (Platform.OS == 'android'){
            codePush.sync({
                updateDialog: false,
                installMode: codePush.InstallMode.IMMEDIATE
            });
            codePush.sync({
                updateDialog: false,
                installMode: codePush.InstallMode.IMMEDIATE
            });
        }
}

**Comment by sergey-akhalkov** [comment]
@dongbingbin77, no, I mean that you should move `codePush.sync` method into the componentDidMount method like this:
```js 
class rncp890 extends Component {
  constructor() {
    super();
    this.state = { restartAllowed: true };
  }

  componentDidMount() {
    CodePush.notifyAppReady();
    CodePush.sync({
        updateDialog: false,
        installMode: CodePush.InstallMode.IMMEDIATE
    });
  }
...
```

**Comment by dongbingbin77** [comment]
I tried it, still have to wait until the second start to see the update

componentDidMount(){
        if (Platform.OS == 'android'){
            codePush.notifyAppReady();
            codePush.sync({
                updateDialog: false,
                installMode: codePush.InstallMode.IMMEDIATE
            });
        }
    }

**Comment by sergey-akhalkov** [comment]
@dongbingbin77, hmm, everything works well for me, please take a look at my app sample
[rncp890.zip](https://github.com/Microsoft/react-native-code-push/files/1084527/rncp890.zip)
 and pay attention on `demo.js` file contents. To build an apk please use `gradlew assembleDebug` command.

**Comment by dongbingbin77** [comment]
I have found the problem, because I was on the home page to do the reasons for the cache, very grateful

**Comment by sergey-akhalkov** [comment]
@dongbingbin77, great! Closing this for now, please feel free to reopen if needed.
