### ISSUE TITLE
Remove override of createJSModules

### ISSUE THREAD

**Issue by ptomasroos** [Microsoft/react-native-code-push#894]
Since of recently in master the unused createJSModules has been removed and ReactPackage's no longer contain the definition of createJSModules. There for it must be removed in order to not yield a compile error. This is breaking change.

https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

**Comment by sergey-akhalkov** [comment]
Hi @ptomasroos, thank you very much for this info and for publishing PR https://github.com/Microsoft/react-native-code-push/pull/895

Please let me know if you have any question and see any issues.

**Comment by sergey-akhalkov** [comment]
Closing this due to v5.0.0-beta has been released, please feel free to reopen if needed.
