### ISSUE TITLE
Js bundle is not loaded when app is run for android 

### ISSUE THREAD

**Issue by arrayoutofbounds** [Microsoft/react-native-code-push#898]
### Description

While creating the react native android app, I saw that the changes made were not being shown at all. After a lot of debugging I did react-native log-android and was able to see that js bundle for android is not loading. 

![screenshot 2017-06-21 10 48 23](https://user-images.githubusercontent.com/8585118/27390418-2ea3b808-566f-11e7-9e74-3b405bf7d05a.png)

As seen, the js bundle does not load until I run the app again ( as seen by the time ). 

However, the issue is not there for ios. I have checked the compatibility table and made sure that code push was set up correctly ( it works for ios ).

### Additional Information

* react-native-code-push version: 1.17.1-beta
* react-native version: 0.41.2
* iOS/Android/Windows version: 7.1.1 android 
* Does this reproduce on a debug build or release build? both
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by sergey-akhalkov** [comment]
Hi @arrayoutofbounds, thanks for reaching us. I've tried to reproduce the issue but with no luck - could you please try to provide me exact reproduction steps - so I'll be able to reproduce it using our [sample app](https://github.com/Microsoft/react-native-code-push/tree/master/Examples)?

Please also note that CodePush updates should not be tested on debug build.

**Comment by sergey-akhalkov** [comment]
Closing this for now, please feel free to reopen.
