### ISSUE TITLE
Update did not finish loading the last time, rolling back to a previous version

### ISSUE THREAD

**Issue by kala888** [Microsoft/react-native-code-push#909]
### Description
When i integrate the code push to my RN App, i could update my App first time(UI changed), but when i forced exit（press the android physical back button）to exit the app, and then open the app, the UI rollback.
How can i handle this case?

### Reproduction
0. Install the app to android device (Mi 5) by 
```
$ react-native run-android
```
1. open the app, the app will check the Version and then open a dialog to ask the user to update its App.
2.User click update, then download the package
3.Package download successful, then reload 
4.the app check the Version, and then show the app is the latest one.
5.wait about 40s, then press the back button(physical back button, the app will forced exit)
6.open the app again, the version was roll back

![image](https://user-images.githubusercontent.com/1215976/27677129-23d58468-5ce3-11e7-8e20-75e6a284098b.png)

### Additional Information
```
"dependencies": {
    "axios": "^0.16.2",
    "color": "~0.11.1",
    "dva": "1.3.0-beta.4",
    "dva-loading": "^0.2.1",
    "jcore-react-native": "^1.1.0",
    "jpush-react-native": "1.6.0",
    "lodash": "^4.13.1",
    "mobile-center": "^0.6.0",
    "mobile-center-analytics": "^0.6.0",
    "mobile-center-crashes": "^0.6.0",
    "moment": "^2.18.1",
    "native-base": "^2.1.5",
    "path-to-regexp": "^1.7.0",
    "rc-form": "^1.3.4",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-code-push": "^3.0.0-beta",
    "react-native-datepicker": "^1.6.0",
    "react-native-eventemitter": "0.0.1",
    "react-native-i18n": "^2.0.1",
    "react-native-image-crop-picker": "^0.13.1",
    "react-native-looped-carousel": "^0.1.7",
    "react-native-picker": "^4.0.18",
    "react-native-splash-screen": "^2.1.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-timer-mixin": "^0.13.3",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.8.0"
  },
```
![image](https://user-images.githubusercontent.com/1215976/27677511-94082e60-5ce4-11e7-820b-2022a4674505.png)

* Android
* debug
* physical device Mi 5

**Comment by sergey-akhalkov** [comment]
Hi @kala888, thanks for reaching us. Please note, that CodePush updates should not be tested in debug mode, from official docs: 
>NOTE: CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply.

To test your updates in debug mode you should:
1. close React Native packager if exists
2. add the following lines to your `app/build.gradle` file:
```gradle
project.ext.react = [
        bundleInDebug: true
]
```
3. open `projectRoot/android` folder and perform there `./gradlew assembleDebug` command
4. close React Native packager if exists
5. install produces apk file and open your app.

**Comment by kala888** [comment]
@sergey-akhalkov 
Thanks your tips, but i my this issue not in debug model,  i used  the following code before
```
$ ./gradlew aR installRelease
```

**Comment by kala888** [comment]
Oh, my fault, 
add codePush to root component, it works fine now.
https://github.com/Microsoft/react-native-code-push#plugin-usage

![image](https://user-images.githubusercontent.com/1215976/27679262-bf0fbf3c-5cea-11e7-97ae-0396f7f63be6.png)
![image](https://user-images.githubusercontent.com/1215976/27679297-dfa709bc-5cea-11e7-8aff-bd9c246e2e05.png)

**Comment by kala888** [comment]
![image](https://user-images.githubusercontent.com/1215976/27679459-633fe780-5ceb-11e7-9ab4-225a27e2ea1c.png)

**Comment by kala888** [comment]
![image](https://user-images.githubusercontent.com/1215976/27679484-7657449e-5ceb-11e7-8701-47eef3722927.png)

**Comment by sergey-akhalkov** [comment]
@kala888, great! Thanks for the clarification)
