### ISSUE TITLE
[error][tid:com.facebook.react.CodePushQueue]

### ISSUE THREAD

**Issue by harsinyee** [Microsoft/react-native-code-push#914]
Below are the crash logs i got when i was trying to open my react native page with [CodePush bundleURLForResource:@"{{name}}"];

[error][tid:com.facebook.react.CodePushQueue][RCTModuleMethod.m:361] Unknown argument type 'CodePushUpdateState' in method -[CodePush getUpdateMetadata:resolver:rejecter:]. Extend RCTConvert to support this type.

* react-native-code-push version: 1.17.4-beta
* react-native version: 0.30.0
* iOS version: 10.2
* xcode version: 8.2.1
* scheme: Release and debug mode
* Able to reproduce the issue from simulator and device

**Comment by sergey-akhalkov** [comment]
Hi @harsinyee, thanks for reaching us. Could you please take a look at https://github.com/Microsoft/react-native-code-push/issues/516 and https://github.com/Microsoft/react-native-code-push/issues/782 and let me know if it helps? Please pay attention on https://github.com/Microsoft/react-native-code-push/issues/782#issuecomment-292941100

**Comment by max-mironov** [comment]
Hey @harsinyee, did you have a chance to look if links from above can help?

**Comment by harsinyee** [comment]
hi @sergey-akhalkov, i installed code push manually last time following the guides provided.. since the app crash.. i tried to reinstall code push via cocoa pods then it is working fine now.. @@ 

Anyway~~~Thanks for your help~~

**Comment by max-mironov** [comment]
Thanks for the update @harsinyee, closing the issue for now. Feel free to contact to us if any help is needed.
