### ISSUE TITLE
Created New RN Project with Facebook's CRNA -- Error: "Couldn't find AppDelegate"

### ISSUE THREAD

**Issue by MarcusHurney** [Microsoft/react-native-code-push#915]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

I created an app using Facebook's CRNA. I am following the Code Push docs for setting up an app to use code push. I am at the step where I need to install plugins for iOS. I run the command: "react-native link react-native-code-push" and I get an error saying "Couldn't find AppDelegate. You might need to update it manually."

Is this an issue with how I generated my app via CRNA? I don't see an AppDelegate file at all, so what do you suggest I do?

### Reproduction

To reproduce, run:

1. "create-react-native-app AwesomeProject"

2. "cd AwesomeProject"

3. "npm start"

4. "npm install --save react-native-code-push@latest"

5. "react-native link react-native-code-push"
### Additional Information

* react-native-code-push version: ^3.0.1-beta
* react-native version: ^0.45.1
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hi there @MarcusHurney, thank you for your question. 

So [the main limitation](https://github.com/react-community/create-react-native-app#what-are-the-limitations-of-create-react-native-app) of a Create React Native App project is that it must be written in pure JavaScript and not have any dependencies which rely on custom native code (i.e. ones which require running react-native link to work). 
That is the reason why you were unable to run `"react-native link react-native-code-push"` command.

As a solution of integrating code-push to your app you can always "eject" to your own build setup if you need to write custom native code or modify how your app is built. 

For this you should run `npm run eject` from your project working directory. 
Please refer to the [documentation](https://github.com/react-community/create-react-native-app#npm-run-eject) first and remember that running eject is a permanent action.
After that you should be able to continue integration of code-push plugin with `react-native link react-native-code-push`. 

Please let us know if it helps.

**Comment by max-mironov** [comment]
@MarcusHurney I'm going to close the issue for now, please reopen it if needed or let us know if you have any questions.
