### ISSUE TITLE
Android App got 'com.facebook.react.cxxbridge.CatalystInstanceImpl.jniLoadScriptFromFile' crash report on Fabric

### ISSUE THREAD

**Issue by youngcube** [Microsoft/react-native-code-push#918]
### Description

We've made an Android App using CodePush. But when I checked Fabric for some crash report, I saw many crashes in `'com.facebook.react.cxxbridge.CatalystInstanceImpl.jniLoadScriptFromFile'` method. Unfortunately I can't reproduce it.

In out project, we make `compileSdkVersion 25` and ` buildToolsVersion "25.0.0"` to make our app can be compile.It's not the CodePush's default SDK Version. I'm not sure if this can make this crash.

In this issue  #847 @hose314 said that he also changed `compileSdkVersion 25 buildToolsVersion '25.0.2' ` and face the same problem.

Here is the full crash report:
```

  | com.facebook.react.cxxbridge.CatalystInstanceImpl.jniLoadScriptFromFile (CatalystInstanceImpl.java)
-- | --
  | com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromFile (CatalystInstanceImpl.java:205)
  | com.facebook.react.cxxbridge.JSBundleLoader$2.loadScript (JSBundleLoader.java:53)
  | com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle (CatalystInstanceImpl.java:218)
  | com.facebook.react.ReactInstanceManager.createReactContext (ReactInstanceManager.java:1006)
  | com.facebook.react.ReactInstanceManager.access$600 (ReactInstanceManager.java:108)
  | com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground (ReactInstanceManager.java:225)
  | com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground (ReactInstanceManager.java:203)
  | android.os.AsyncTask$2.call (AsyncTask.java:292)
  | java.util.concurrent.FutureTask.run (FutureTask.java:237)
  | java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1115)
  | java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:590)
  | java.lang.Thread.run (Thread.java:818)


```

![image](https://user-images.githubusercontent.com/13709506/28169668-a94127f0-6815-11e7-820a-e95d5ab82430.png)

### Reproduction

I can only see it in Fabric's crash report. I can not reproduce this issue.

### Additional Information

* react-native-code-push version: 2.0.3-beta
* react-native version: 0.44.0
* iOS/Android/Windows version: Android 4/5/6/7
* Does this reproduce on a debug build or release build? Not on my devices.
* Does this reproduce on a simulator, or only on a physical device?  Not on my devices.

**Comment by max-mironov** [comment]
Hello @youngcube, thanks for sharing this. Could you please have a look at #919 regarding usage of SDK version 25.

**Comment by youngcube** [comment]
I am not Android developer so I could misunderstanding this SDK version's effort. Perhaps it's not related to the changing of  `compileSdkVersion 25` and `buildToolsVersion "25.0.0"` since RN is also  `compileSdkVersion 23` and `buildToolsVersion "23.0.1"`.

When I compile my Android project in first time,  CodePush is all 23.It can not be compile for this error log:

```
Error:The SDK Build Tools revision (23.0.1) is too low for project ':react-native-code-push'. Minimum required is 25.0.0

```

So I change CodePush's `buildToolsVersion "25.0.0"` but leave `compileSdkVersion` to `23`

It can compile. But App will crash in some I/O operations sometimes. so I also change CodePush's `compileSdkVersion` to `25`. Now App will not crash in all I/O operations.

Maybe my issue is not related to SDK problem but hope this clue may help.

**Comment by max-mironov** [comment]
@youngcube can you please have a look at this [comment](https://github.com/Microsoft/react-native-code-push/pull/725#issuecomment-284979977) and verify if dynamically changing `compileSdkVersion` and `buildToolsVersion` for your subprojects could help in your case.

**Comment by hose314** [comment]
@youngcube @max-mironov works for me!

**Comment by youngcube** [comment]
As for now we've changed our project all subprojects's `compileSdkVersion` and `buildToolsVersion` to 23 to fit CodePush & RN. We will release it ASAP and observe this crash report in Fabric. I'll let you know if this crash report dismiss.

**Comment by max-mironov** [comment]
@youngcube got it and thanks! Please let us know the results when ready.

**Comment by youngcube** [comment]
@max-mironov We've decided not to use CodePush & RN in our project anymore and transfer JavaScript code into native Java-Android since there are too many crash reports except this one in many Android devices according to the Fabric crash list and user feedback. I'm sorry I can't observe this issue anymore.

**Comment by max-mironov** [comment]
@youngcube understood, that's ok, thanks for the update. Anyway hope info from this thread could be useful if someone else face similar issues in future.
