### ISSUE TITLE
Android build tools to 25.0.2

### ISSUE THREAD

**Issue by tapz** [Microsoft/react-native-code-push#919]
### Description

Please update the Android build tools to 25.0.2 in build.gradle

### Additional Information

* react-native-code-push version: 4.0.0-beta
* react-native version: 0.46.2

**Comment by max-mironov** [comment]
Hi there @tapz, thanks for your question. We have discussed this issue previously so could you please take a look at the following links:

[update android SDK to version 25](https://github.com/Microsoft/react-native-code-push/pull/725) and [android SDK version mismatch](https://github.com/Microsoft/react-native-code-push/issues/733)

The latter [states that](https://github.com/Microsoft/react-native-code-push/issues/733#issuecomment-284057037) the [current react-native](https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/android/app/build.gradle#L93) supports android API up to level  23, the react-native-code-push repo will sync with their upgrade. 

So I believe we should keep build tools version in sync with react native to avoid SDK verison mismatch.
Please let us know if you have any questions or considerations regarding this.

**Comment by max-mironov** [comment]
@tapz - hi again. In accordance with the info from above I'm going to close this issue for now. Let us know if any concerns or have questions regarding this.
