### ISSUE TITLE
Control Code Push roll out only to some specific users

### ISSUE THREAD

**Issue by ashrithks** [Microsoft/react-native-code-push#925]
Hi all, 
Just A  Question,
How to control code push rollout to targeted users?
Example:-
Current code push version -1.0.0
found a bug , so rolled out to 1.0.1,
before releasing to all users or segmented users,
wanted to release for specific devices(targeted users).

**Comment by max-mironov** [comment]
Hi @ashrithks. Aside from [Rollout](https://github.com/Microsoft/code-push/tree/master/cli#rollout-parameter) parameter I think it make sense to use [different deployments](https://github.com/Microsoft/code-push/tree/master/cli#deployment-management) this way, so you can test e.g. `Staging` deployment for specific uses and later (after you have verified that this update is ok) you can [promote](https://github.com/Microsoft/code-push/tree/master/cli#promoting-updates) this release to all the rest ones.  

Please let us know if you have any questions.

**Comment by max-mironov** [comment]
Closing this for now, feel free to reach us if any further questions.
