### ISSUE TITLE
Please use a semver-compliant target binary version range, for example "1.0.0", "*" or "^1.2.3".

### ISSUE THREAD

**Issue by akaiz** [Microsoft/react-native-code-push#926]
Code push returns this error when ever I push and my ios app version number is 1.70 and my build no 1.4.4 . When I run command  "code-push release-react AppName ios -d Production"
[Error]  Please use a semver-compliant target binary version range, for example "1.0.0", "*" or "^1.2.3".

**Comment by disharmonized** [comment]
@akaiz thanks for reaching us. Error talks for itself - you need to use semantic versioning for your target binary builds. Your app version number is 1.70 which is not suits semver scheme. Please refer to http://semver.org/ for additional information about semantic versioning.

**Comment by akaiz** [comment]
Thanks, @disharmonized for your reply.
