### ISSUE TITLE
Please update the build.gradle file to use the latest SDK & Tools version

### ISSUE THREAD

**Issue by dkadlecek** [Microsoft/react-native-code-push#929]
See title. Current versions set are old and prevent compilation on android

**Comment by sergey-akhalkov** [comment]
Hi @dkadlecek, thanks for reaching us. Please take a look at https://github.com/Microsoft/react-native-code-push/issues/919#issuecomment-315303332 and let me know if you have any questions.

**Comment by sergey-akhalkov** [comment]
Closing this as duplicate, please feel free to reopen if needed.
