### ISSUE TITLE
CodePush/main.jsbundle is stale even when building app in release mode

### ISSUE THREAD

**Issue by blairvanderhoof** [Microsoft/react-native-code-push#931]
### Issue
* Did some code pushes, seems that CodePush/main.jsbundle is now changed.
* Made some more JS changes and debugged in "debug" mode instead of "release" mode.
* Now tried to do a release build and test in simulator
* It seems that the release build contains the code from the previous code-push, not the new bundle I was testing in the debug build.

### Question

* When deploying a new release build, how do i also include an update to date JS bundle? It seems in order for the user to get the new JS bundle after the app update, I need to do a code-push. Is this by design?

**Comment by sergey-akhalkov** [comment]
Hi @blairvanderhoof, thanks for reaching us. Please note, that you should not test CodePush updates in debug mode. From official docs:
>NOTE: CodePush updates should be tested in modes other than Debug mode. In Debug mode, React Native app always downloads JS bundle generated by packager, so JS bundle downloaded by CodePush does not apply.

In case you still want to test CodePush updates in debug mode, please make sure that react native packager has been disabled and that `myappRoot/android/app/build.gradle` contains the following code:
```gradle
project.ext.react = [
    bundleInDebug: true
]
```
Then you need to perform `.\gradlew assembleDebug` or `.\gradlew assembleRelease` command in 
 `myappRoot/android` folder.

Please let me know if you have any questions or see any issues.

**Comment by blairvanderhoof** [comment]
My question is actually when archive my app for App Store release, it doesn't generate any new
Bundle, I have to push the bundle to the user via code push. Is this normal? Can I regenerate the bundle on release build?

**Comment by max-mironov** [comment]
Hi @blairvanderhoof, so I think that when you archive the app for appStore release it should regenerate a new bundle. Anyway I don't see how the question is related to code-push. Is it possible that code push update was applied accidentally and thus override your latest changes?

Actually you can do the following to verify if the new bundle is generated on release:
1) Remove code-push  from the app (just to be sure that no updates can be applied accidentally)
2) Close all packagers before building  for archive
3) Archive your app to the app store release, verify the output

Please let us know the results.

**Comment by sergey-akhalkov** [comment]
Hi @blairvanderhoof, I'm closing this for now, please feel free to reopen if needed.

**Comment by sukhjindersingh** [comment]
@sergey-akhalkov I am having similar issue but little bit different. Here is the link https://github.com/microsoft/react-native-code-push/issues/1798
