### ISSUE TITLE
【iOS】Unable to find or read "package.json" in the CWD. The "release-react" command must be executed in a React Native project folder.

### ISSUE THREAD

**Issue by SunMichael** [Microsoft/react-native-code-push#932]
release ios package

### Description

use release-react update

code-push version 3.0.1-beta
react-native 0.42.3

**Comment by FSanguinetti** [comment]
Im also having this issue running the `appcenter codepush release-react -a ownerName/appName` from the root directory. What was your solution?

**Comment by mike-niemand** [comment]
Anyone figure this out? I'm suddenly having it on one solution.

**Comment by yuri-kulikov** [comment]
@mike-niemand, You should check:
- if the file `package.json` exists
- and if it has the `"name": "..."` parameter

**Comment by mike-niemand** [comment]
Thanks Yuri, it was missing the name value.
