### ISSUE TITLE
Codepush still use old bundle after app is reinstalled on Android

### ISSUE THREAD

**Issue by murmurwoodz** [Microsoft/react-native-code-push#933]
### Description

I installed a new version of app with new bundle by reinstalled with apk, and didn't uninstall the app before reinstalling, but codepush still loaded old bundle instead of using new version packed in the apk file.

### Reproduction

I call codePush.sync after connect to my server, since there are many branches of bundles.
the path looks like
file:///data/user/0/com.***.**/files/codepush/deploy/versions/b8ac7f60051da*************9f3335eb66d6fff4/www/index.html
To prevent codepush for using old bundle, I changed app version from 3.0.0 to 3.0.1, but It's useless.

### Additional Information
cordova-plugin-code-push ~1.9.2-beta
server: https://github.com/lisong/code-push-server, cause you know it's in China
Android version:miui 8.5 with android 7.0

**Comment by el-lsan** [comment]
@murmurwoodz Did you manage to solve it ?
I'm facing the same issue.
