### ISSUE TITLE
Equivalent of getUpdateMetadata in native API

### ISSUE THREAD

**Issue by jsierles** [Microsoft/react-native-code-push#934]
I found this in the Android code, called by Javascript: https://github.com/Microsoft/react-native-code-push/blob/9bc0770845cb1ed01344048ea5468dc89a2430e2/android/app/src/main/java/com/microsoft/codepush/react/CodePushNativeModule.java#L291

Is this method suitable for calling from the other native code?

My goal is to attach the current CodePush version to native exception reports on BugSnag.

Thanks for a great tool!

**Comment by sergey-akhalkov** [comment]
Hi @jsierles, thanks for reaching us. Yes, you could move this method implementation to `CodePush.java` but please note, that the native implementation does not return `failedInstall` and `isFirstRun` [props](https://github.com/Microsoft/react-native-code-push/blob/master/CodePush.js#L114).

Please also take a look at [this method implementation](https://github.com/sergey-akhalkov/react-native-code-push/blob/support_for_brownfield_apps_v2/android/app/src/main/java/com/microsoft/codepush/react/CodePushCore.java#L484) from "Support for Brownfield Apps" feature, it might help.

Please let me know if you have any questions.

**Comment by sergey-akhalkov** [comment]
Hi @jsierles, closing this for now, please feel free to reopen if needed.
