### ISSUE TITLE
react native code push increase rollout percentage 

### ISSUE THREAD

**Issue by BalaKrishnaJ27** [Microsoft/react-native-code-push#940]
I have created a production release with a rollout to 20% by using following command

code-push promote <App_name> Staging Production --rollout 20 --targetBinaryVersion 2.2.12

Now I want to increase the rollout to 100% for which I am able to find the proper command / documentation

* react-native-code-push version: ^1.16.1-beta
* react-native version: 0.40.0
* Does this reproduce on a debug build or release build? Release

**Comment by max-mironov** [comment]
Hi there @BalaKrishnaJ27, please take a look at https://github.com/Microsoft/code-push/tree/master/cli#patching-update-metadata command and let us know if it is something you are looking for.

**Comment by BalaKrishnaJ27** [comment]
@max-mironov  Thanks for the info

**Comment by max-mironov** [comment]
I believe we can close the issue now, please feel free to reach us if any questions.
