### ISSUE TITLE
Open the app again, and app crashes

### ISSUE THREAD

**Issue by wjm117** [Microsoft/react-native-code-push#942]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description

Production environment version, installed app, first open is normal, then turn off app open, appear flash retreat, and then open app again, version back to v1.No errors were reported while packing the app。and the version I used a few days ago was 1.13.

### Reproduction
Here is my code：
    componentDidMount: function () {
        AppState.addEventListener('change', this.handleAppStateChange);
        CodePush.sync({installMode: CodePush.InstallMode.ON_NEXT_RESUME});
    },
    componentWillUnmount: function () {
        AppState.removeEventListener('change', this.handleAppStateChange);
    },
handleAppStateChange: function (appState) {
        if (appState === 'active') {
            CodePush.sync({installMode: CodePush.InstallMode.ON_NEXT_RESUME});
        }
    }

### Additional Information

* react-native-code-push version:2.1.1-beta
* react-native version:0.43.4
* iOS/Android/Windows version:android:7.0,ios:10.1
* Does this reproduce on a debug build or release build?reproduce
* Does this reproduce on a simulator, or only on a physical device?reproduce

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hi @wjm117 thank you for your question.

Is it possible that your update was rolled back while applying?
Could you share with us the output of deployment history command for your application? 
Also can you verify if you see this issue with our basic sample app or maybe you can share with us the minimum example where we can see that issue?

**Comment by max-mironov** [comment]
@wjm117 just a friendly ping on this

**Comment by wjm117** [comment]
@max-mironov After a few days of testing, I would like to show that this problem is not the reason for the plug-in. Thank you very much

**Comment by sergey-akhalkov** [comment]
Hi @wjm117, just wondering - what the reason is? Is it somehow relates to other plugins?

**Comment by max-mironov** [comment]
@wjm117 - thanks for the update!
