### ISSUE TITLE
Add docs: "How to use CodePush and Notifications to do A / B testing"

### ISSUE THREAD

**Issue by esutton** [Microsoft/react-native-code-push#945]
### Description

Enhancement request.

The Microsoft Team in [React Native Monthly #2](http://facebook.github.io/react-native/blog/2017/07/28/react-native-monthly-2.html) stated:

> Mobile Center now supports Push Notifications for CodePush. We also showed how a combination of Notifications and CodePush could be used for A/B testing apps - something unique to the ReactNative architecture.

Do you send two opt-in notifications, one for A and one for B, and then the user can somehow toggle between CodePushA and CodePushB and use analytics to determine which one wins?

Documenting how to do A/B testing, either here, or on Mobile Center will be helpful to CodePush users.

Thank you for all the great libraries!

**Comment by pniko** [comment]
@panarasi recently demonstrated an approach to A/B testing utilizing Mobile Center's Push, Analytics and CodePush technologies. Using our Mobile Center Push SDK he was able to define two user segments and push a notification to each with a different deployment key specified in the payload. When one of the users clicked on the notification to launch his application it grabbed the deployment key specified in the notification and checked the CodePush services for an update against that key. After the users app was updated he relied on Mobile Center's Analytics to determine the solution with the best reception.

We're working to further enhance these types of capabilities and workflows today so expect more features, documentation and breakdowns in the not so distant future covering this and similar topics.

**Comment by esutton** [comment]
Thank you @pniko.  Is the @panarasi demo for A/B testing online someplace?

Very good.

This sounds like in addition to doing A / B testing,  I could make a user segment for **instructors**.

The use case is that our **instructors** need app functionality that should be hidden from normal users.  For example, resetting our Bluetooth devices to a clean state.

**Comment by pniko** [comment]
I believe this is what you are looking for @esutton. 

https://www.youtube.com/watch?v=f_-S0ZhVmvQ&list=PLFHvL21g9bk3RxJ1Ut5nR_uTZFVOxu522&index=11

The use case you are trying to achieve depends on how the devices are shared. You could theoretically identify a deployment key on login for that user and make sure their device gets updated to the instructor or service tech deployment if they aren't already on the correct one prior to use.

**Comment by esutton** [comment]
Thank you for the video link @pniko !

**Comment by max-mironov** [comment]
@esutton also please take a look at this @panarasi  blog post http://blog.nparashuram.com/2017/09/ab-testing-for-react-native-apps-with.html that might be interesting for you!

**Comment by esutton** [comment]
@max-mironov Great article by is @panarasi 

Thank you for letting me know!

**Comment by esutton** [comment]
I just got Google Analytics and firbase analytics working.

I may need to try out mobile-center-analytics

Question: Can mobile-center-analytics display user location to the city level like Google Analytics can?

**Comment by max-mironov** [comment]
@esutton AFAIK at that moment only County level information is supported. Please checkout https://docs.microsoft.com/en-us/mobile-center/analytics/overview ->` Country/Region and Languages` section for more information.
