### ISSUE TITLE
unable to resolve host "codepushupdates.azureedge.net": No address associated with hostname

### ISSUE THREAD

**Issue by larryranches** [Microsoft/react-native-code-push#948]
### Description

I am receiving an error when my app boots up now that code push is throwing an error when receving bundle updates. Is this a sign that the server is down? I'm using react-native-code-push 3.0.1 beta and react native 0.45.1. Do I need to upgrade or something?

```
[CodePush] Reporting binary update (1.0)
logging.js:3 [CodePush] Downloading package.
logging.js:3 [CodePush] An unknown error occurred.
logging.js:3 [CodePush] Unable to resolve host "codepushupdates.azureedge.net": No address associated with hostname
```

### Additional Information

* react-native-code-push version: 3.0.1 beta
* react-native version: 0.45.1
* iOS/Android/Windows version: Android
* Does this reproduce on a debug build or release build? debug
* Does this reproduce on a simulator, or only on a physical device? physical device

**Comment by larryranches** [comment]
nvm

**Comment by jaysig** [comment]
How did you manage to get this resolved because I am having a similar issue @larryranches

**Comment by larryranches** [comment]
@jaysig Make sure your connected to the internet
