### ISSUE TITLE
App Store rejected

### ISSUE THREAD

**Issue by gHashTag** [Microsoft/react-native-code-push#949]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Description
Publish the app in the App Store, but it rejected.
What am I doing wrong?
Before upgrade I have no update alerts.
` codePush.sync({ updateDialog: true, installMode: codePush.InstallMode.IMMEDIATE  });`
### Reproduction
Here is what they write:

Thank you for your resubmission and for addressing the issues with your app. Upon further review, we found the following:
Guideline 4.0 Design
Your app includes an update button or alerts the user to update the app. To avoid user confusion, app version updates must utilize the iOS built-in update mechanism.
Please see attached screenshots for details.

Steps
To resolve this issue, please remove the update feature from your app.To distribute a new version of your app, upload the new app binary version into the same iTunes 

Connect record you created for the app's previous version. Updated versions keep the same Apple ID, iTunes Connect ID (SKU), and bundle ID as the original version, and are available free to customers who purchased a previous version.
Resources
To create new versions of your app, please review the https://help.apple.com/itunes-connect/ developer/#/dev480217e79 
Create a new version section in iTunes Connect Developer Help.

### Additional Information

* react-native-code-push version: "^4.1.0-beta",
* react-native version: 0.46.4,
* iOS version: 10.3

![img_0395](https://user-images.githubusercontent.com/6774813/28940302-ef56b7a4-789c-11e7-8fba-7d3a3cfffd7e.PNG)

**Comment by max-mironov** [comment]
Hi @gHashTag, that probably could be related to the way you are informing users about your updates - that is update dialog. Could you please  remove it, try again and let us know the results.
Also please take a look at the following information regarding AppStore rejections: https://github.com/Microsoft/react-native-code-push#store-guideline-compliance

**Comment by gHashTag** [comment]
`updateDialog: false `
... and Ready for sale
