### ISSUE TITLE
Detecting Staging vs Release in same binary?

### ISSUE THREAD

**Issue by tmaly1980** [Microsoft/react-native-code-push#960]
I'm hoping to have a distinct Staging vs Release/Production track in CodePush for my react-native project, so I can have team members/management approve changes before the rest of the world sees them. I'm trying to follow:

https://microsoft.github.io/code-push/docs/react-native.html#link-8

Normally, I'd push a new release via TestFlight and this doesn't get deployed live immediately, so there can be a review process. Ultimately, once an app gets released and is live in the app store, this means we need distinct deployments. Unfortunately, having a Staging deployment in TestFlight doesn't make sense, because it'll never actually get released live, and it becomes hard to identify it as staging vs production.

It would be ideal to have one binary with code at the native level that can detect whether the app is in testflight/beta mode and use a different deployment key in each case. I've looked around for answers and found this, but it seems obsolete and won't work in XCode 8:

https://stackoverflow.com/questions/26081543/how-to-tell-at-runtime-whether-an-ios-app-is-running-through-a-testflight-beta-i?lq=1

There doesn't seem to be a solution for android.

Until I can get something figured out, CodePush really seems more useful for hotfixes rather than actual new major releases that often require a review process before approving public release. Or can it be used for both? 

It doesn't seem like there's a way to use the same binary for the 'staging' version and 'production' version, so how do I work with both? How would I manage versions so I know the difference between a production-ready binary and a staging-level one?

Or should I not be expecting to use CodePush for new major releases? Even as hotfixes, it would seem that there should be an intermediate 'review/approval' stage (where someone other than the developer gets to look at the changes) before deploying to the entire world.

**Comment by sergey-akhalkov** [comment]
Hi @tmaly1980, thanks for reaching us.

1. Do I get it right if you are searching for mechanics to determine if the app is in TestFlight or in the Prod? Then you would like to use that info to dynamically switch Staging and Prod deployment keys, right? 
If so, I've already investigated this problem and unfortunately, seems like there is no ability to determine if the app is in TestFlight or in the Prod via native side. That means you'll have to use different schemas in case you want to test your updates in Staging before promoting them to Prod.
The only workaround that I can see is described here https://stackoverflow.com/a/41557481
```Another solution is to make a build that points to real data by default, but has a hidden switch you can teach internal users to use to switch to test data.```
Here we could use [Dynamic Deployment Assignment](https://github.com/Microsoft/react-native-code-push#dynamic-deployment-assignment) feature. Please also take a look at this https://github.com/Microsoft/react-native-code-push/issues/786#issuecomment-319608461 for more details and let us know if you have any questions.
2. Could you please clarify - what do you mean by major releases? It is up to you in which way you want to use CodePush, but we would recommend you to use CodePush service to release bug fixes and improvements/features that maintain the app’s original/presented purpose (i.e. don’t CodePush a calculator into a first-person shooter), please take a look at http://microsoft.github.io/code-push/faq/index.html

Let me know if you have any other questions.

**Comment by max-mironov** [comment]
@tmaly1980 - hi, please let us know if you have a chance to look at this!

**Comment by max-mironov** [comment]
Closing the item for now, please feel free to reopen or ask additional questions when if any.

**Comment by kirlen** [comment]
One potential solution my team is contemplating: Whenever we create a native/app-store release, e.g. 1.5.0, we'll simultaneously create a "codepush-test-target" release that is identical except for a version bump (e.g. 1.5.1), which we'll only ever push to TestFlight. We'll use that to test all CodePush releases that are meant to target 1.5.0 -- by creating those releases with a target binary version set initially to 1.5.1. When verified successful/approved in the TestFlight-only release we'll drop the target binary version to 1.5.0 to allow apps in the wild to begin receiving the update. Any thoughts on this approach, @sergey-akhalkov or others? Curious to know what you wound up doing, too.

**Comment by msadura** [comment]
@kirlen does that solution work for you as expected? I am about to do the same, but I am wondering iff there is a better approach

**Comment by kirlen** [comment]
@msadura we wound up simplifying the idea a bit further:

- each time you release a new native build (i.e. not a CodePush) to the app store (e.g. xyzApp v1.5.0), release a companion CodePush "staging test" build (e.g. xyzApp-cp-test v1.5.0) to TestFlight (or restricted Google Play distribution) that is *identical* to the app store build other than pointing to your Staging CodePush deployment key.
- now, for as long as your CodePush'es target a given binary version (xyzApp v1.5.0) you can use the corresponding CodePush test build (xyzApp-cp-test v1.5.0) to test them before you promote from Staging to Production.

This has been working well!
