### ISSUE TITLE
Xcode unable to find libCodePush.a

### ISSUE THREAD

**Issue by jaysig** [Microsoft/react-native-code-push#961]
### Description

I am running into an issue with Archiving within Xcode that is caused by Xcode being unable to find /BuildProductsPath/Release-iphoneos/libCodePush.a'. I have tried to install CodePush manually and with react-native link with no success. Any suggestions would be appreciated.

### Additional Information

* react-native-code-push version: 2.1.1
* react-native version: 0.44.3

**Comment by max-mironov** [comment]
Hi @jaysig 
I've tried to reproduce your issue with the following steps:
1) `rninit init AppName react-native@0.44.3`
2) `cd AppName`
3) `npm install --save react-native-code-push@2.1.1-beta`
4) `react-native link react-native-code-push`
5) open project in xCode (mine version is 8.3.3) and verify it is building without any errors 
6) go to Product->Archive and was able to archive it without errors

Please let us know if your steps differ.

**Comment by jaysig** [comment]
Maybe it is something within my project, because it creates it at /Release-iphoneos/CodePush/libCodePush.a. I will keep playing around with it though, thanks

**Comment by max-mironov** [comment]
Thanks for the update @jaysig!

**Comment by shyaniv7** [comment]
@jaysig were you able to resolve this issue? We are seeing the same exact problem where it would randomly fail in the fastlane build app command
