### ISSUE TITLE
best practices for deployment strategies considering native changes

### ISSUE THREAD

**Issue by grigored** [Microsoft/react-native-code-push#963]
What's the recommended method to deploy changes? I estimate that >90% of future deployments won't have native changes. We might have an update once every few days. I noticed that a codepush release where i only change one line downloads ~1mb (don't understand why, the uncompressed bundle size is 1.5mb, and compressed is 300k). Does codepush compress the bundle before sending it? 

The strategy i think is best is:
a) when doing native changes, upload the app to app store, and use codePush.InstallMode.IMMEDIATE. This way, new installs will be forced to get the last js updates immediately. Users will have to wait a little, but they already waited for the app to download, and should have a decent network connection if they decided to download a new app. 

b) On all codepush deploys, change the codepush settings to codePush.InstallMode.ON_NEXT_RESUME. This way, small incremental updates (that aren't mandatory) will be downloaded in the background, and users will have the best update user experience.
 
The problem is new installs won't be able to start the app right away, but wait for codepush to finish. But the only option to solve this would be to submit the app to app store with every codepush deploy, but then people will have to update the app twice (once through codepush, and then through the app store). Maybe this isn't such a big deal?

Is there any recommended best practice? More documentation on possible strategies, and advantages and disadvantages of each would be much appreciated.

**Comment by max-mironov** [comment]
@grigored - hi, so yes, the bundle is always sent as a zip archive so its size should be smaller. 

Regarding the rest questions:
a) If you do native changes and upload new app to AppStore you should always increment app version and this way your previous updates would not be applied. This really make sense and also when you do native changes you always update js/css/assets part accordingly, so no need to users to apply code push updates
b) It make sense to use ON_NEXT_RESUME mode to install updates silently, also please take a look at our new feature for installing updates - [ON_NEXT_SUSPEND](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#installmode) - this can bring a great user experience to your app. 

The only notice here is to avoid using update dialog, you can see more details about why you should not use it in your code push updates [here](https://github.com/Microsoft/react-native-code-push#store-guideline-compliance).
Please feel free to ask if you have more questions.

**Comment by max-mironov** [comment]
@grigored I'm closing your questions for now, please let us know if you have more questions or need clarifications regarding this.
