### ISSUE TITLE
how I can get description in updateDialog?

### ISSUE THREAD

**Issue by wuyunqiang** [Microsoft/react-native-code-push#967]
I release version like that,
code-push release-react appname  ios  --t 1.0.0 --d Production --des “changesomething”  -m false.
and how I can get description in updateDialog and show this.
![update](https://user-images.githubusercontent.com/13480948/29260456-8d71ff86-80fc-11e7-802c-0b4375b39e5b.png)

```
    CodePush.sync({
            updateDialog: {
                mandatoryContinueButtonLabel:'更新',
                mandatoryUpdateMessage:'有新版本了，请您及时更新',
                optionalIgnoreButtonLabel: '稍后',
                optionalInstallButtonLabel: '后台更新',
                optionalUpdateMessage:'有新版本了，是否更新？',
                title: '更新提示'
            },
            installMode: CodePush.InstallMode.IMMEDIATE
        });
```

### Environment
* react-native-code-push version:^4.1.0-beta
* react-native version:0.46.4
* iOS/Android/Windows version: ios 10.3
* Does this reproduce on a debug build or release build? release
* Does this reproduce on a simulator, or only on a physical device? both

**Comment by max-mironov** [comment]
Hello @wuyunqiang,

You should use `appendReleaseDescription` option to enable this.
Please have a look at this from [CodePushOptions->UpdateDialog](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushoptions) section details from our documentation.

Please let me know if it helps.

**Comment by wuyunqiang** [comment]
oh it's good for me 
very thx.
