### ISSUE TITLE
Production install not work

### ISSUE THREAD

**Issue by zheng-liu-seattle** [Microsoft/react-native-code-push#972]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Followed the document to setup staging and production on iOS (https://microsoft.github.io/code-push/docs/react-native.html#link-7)
2. Built app on staging
3. code-push release-react
4. Saw the install on staging
5. Build the app on production
5. run code-push promote xxxxx Staging Production
6. production app not install

### Expected Behavior
What you expected to happen?
production app should install update

### Actual Behavior
What actually happens?
not install

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by joshuapinter** [comment]
@zheng-liu-seattle Did you solve this? If so, what was the issue? Thanks!

**Comment by joshuapinter** [comment]
@zheng-liu-seattle Did you solve this? If so, what was the issue? Thanks!
