### ISSUE TITLE
Unable to get Staging code push to work

### ISSUE THREAD

**Issue by atom-r** [Microsoft/react-native-code-push#976]
RN v. 0.44
React Native Code Push v. 5.0.0-beta
iOS 10.3

When I initiate a code push, TestFlight builds with the corresponding version number (1.1.1) do not download the Staging update. They will, however, download an update after it has been promoted to Production. This is despite changing my configuration setting in XCode from Release to Staging.

This is after following the instructions for multiple configurations seen here:
https://github.com/Microsoft/react-native-code-push#multi-deployment-testing

I've double checked that I'm using the correct key for a build configured for Staging. 

While debugging, I also set the Debug configuration to use the Staging key (running a react native app on the simulator uses the Debug configuration). I confirmed that the simulator was seeing Staging versions and downloaded them successfully.

It seems like when I create an archive in XCode, it thinks that it is building a Release configuration, no matter if I change the XCode setting from Release to Staging.

I'm considering trying a react native upgrade, as I'm wondering if it's related to 0.44. Hoping someone here might have some suggestions before I go down that path, though.

**Comment by RomanISWG** [comment]
Same or similar issues at my side with rn 0.47.2. I have followed multi-deployment-testing guide. However only Debug scheme (with Staging deployment key) does work. Release and Staging scheme do not download any updates. Any ideas to solve this?

**Comment by sergey-akhalkov** [comment]
Hey guys, thanks for getting in touch! 

Have you changed your `Build Configuration` to `Staging` here: **Product -> Scheme -> Edit Scheme -> Archive -> Build Configuration**

![screenshot 2017-08-28_13-20-59](https://user-images.githubusercontent.com/4928157/29769593-c3968706-8bf3-11e7-9fe8-8a1cde9d9d00.png)

?

**Comment by RomanISWG** [comment]
I have change this for Run as I'm not trying to get any ipa yet.

**Comment by sergey-akhalkov** [comment]
Hi @RomanISWG, please take a look at demo I've prepared - [rncp976 copy.zip](https://github.com/Microsoft/react-native-code-push/files/1259957/rncp976.copy.zip)

Please try to Run it with Release and Staging configurations and let me know if it works or if you see any issues.

**Comment by atom-r** [comment]
@sergey-akhalkov That seems to have been my problem -- i.e., not setting the Archive scheme to 'Staging'.

I suspect it will work if I can get a build to succeed. Currently troubleshooting getting a custom configuration to build successfully for a Cocoapods React-Native project, which is outside the scope of this issue.

Thank you for your help.

**Comment by sergey-akhalkov** [comment]
@atom-r, take a look at https://github.com/Microsoft/react-native-code-push/issues/893#issuecomment-317648454 - there you can find CodePushified react-native app that uses cocoapods.

I'm closing this issue, please feel free to ask questions or reopen if needed.

**Comment by sibelius** [comment]
@sergey-akhalkov tks for your help

I think it's better to have a different scheme/target on xcode to be easy to build for Staging

what do you think?

**Comment by sergey-akhalkov** [comment]
Hi @sibelius, it's totally up to you, but I think that it would be more convenient to have different schemes for Staging and Release.

Please let me know if you have any other questions.
