### ISSUE TITLE
Sending `CodePushDownloadProgress` with no listeners registered.

### ISSUE THREAD

**Issue by agersoncgps** [Microsoft/react-native-code-push#978]
### Steps to Reproduce
Just set up code push for the first time. Then I pushed out my first update. Everything is working fine, the app updates, but I am getting a warning:

![screenshot 2017-08-27 16 40 56](https://user-images.githubusercontent.com/336441/29753768-84961b78-8b46-11e7-92ff-9af11a24da17.png)

### Environment

* react-native-code-push version:
"react-native-code-push": "^5.0.0-beta",
* react-native version:
"react-native": "0.47.2",
* iOS/Android/Windows version:
iOS simulator

**Comment by max-mironov** [comment]
Hello @agersoncgps and thanks for asking.
Could you please share the code how you have integrated code-push?
Did you use [sync](https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-js.md#codepushsync) method for this?

**Comment by agersoncgps** [comment]
Did not use the sync method. I think I am pretty bare bones on my integration. The only three lines of CodePush code I have in my app are in my index.js:

```
console.ignoredYellowBox = ["Warning: BackAndroid", "Remote debugger", "Setting a timer"];

import React, { Component } from "react";
import { View, StatusBar } from "react-native";
import { MainNav } from "./config/router";
import { DrawerNavigator } from 'react-navigation';
import Icon from "react-native-vector-icons/MaterialIcons";

import { Client } from 'bugsnag-react-native';
const bugsnag = new Client();

import codePush from "react-native-code-push";
let codePushOptions = { checkFrequency: codePush.CheckFrequency.ON_APP_RESUME };

class App extends React.Component {
  static navigationOptions = {
   drawerLabel: 'Home',
   drawerIcon: ({ tintColor }) => (
     <Icon color="#fff" style={{ marginRight: 10 }} name={"settings"} size={26} />
   ),
 };
  constructor(props) {
    super(props);
  }
  render() {
    return <MainNav onNavigationStateChange={null} /> ;
  }
}

App = codePush(codePushOptions)(App);

export default App;

```

**Comment by max-mironov** [comment]
@agersoncgps thanks for update, I've tried your code with android and didn't see such warnings, probably that warnings are ios specific.
However I've found similar issue to yours, please take a look at [this comment](https://github.com/Microsoft/react-native-code-push/issues/516#issuecomment-275688344) and let us know if it helps.

**Comment by max-mironov** [comment]
@agersoncgps - I'm closing the issue for now as I believe the question was already answered in the issue linked above, please let us know if any questions or have any concerns.

**Comment by zmnv** [comment]
I have the same warning on iOS:

```
[CodePush] Checking for update.
[CodePush] Downloading package.
Sending `CodePushDownloadProgress` with no listeners registered.
[CodePush] Installing update.
[CodePush] Update is installed and will be run when the app next resumes.
```

but I don't use `CodePushDownloadProgress` at all.

`react-native-code-push-saga` also doesn't use it.

**Comment by zmnv** [comment]
@max-mironov 

I have the same warning on iOS:

```
[CodePush] Checking for update.
[CodePush] Downloading package.
Sending `CodePushDownloadProgress` with no listeners registered.
[CodePush] Installing update.
[CodePush] Update is installed and will be run when the app next resumes.
```

but I don't use `CodePushDownloadProgress` at all.

`react-native-code-push-saga` also doesn't use it.

**Comment by yasirtrimulabs** [comment]
How can I remove this warning if my main app is a functional component?
PS: I can't convert it to class component. Thanks

**Comment by williamgurzoni** [comment]
I'm facing the same warning.

checkFrequency: codePush.CheckFrequency.ON_APP_RESUME
installMode: codePush.InstallMode.ON_NEXT_RESUME

"react-native": "0.64.2"
"react-native-code-push": "6.4.1"
