### ISSUE TITLE
my code-push account published updates not work

### ISSUE THREAD

**Issue by wjm117** [Microsoft/react-native-code-push#981]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.My colleague added my code-push account to the collaborator;
![image](https://user-images.githubusercontent.com/20735485/29859360-4ddabc06-8d94-11e7-8c29-f146215bc691.png)

2.I add our app to my account like this:code-push app add <appName>
![image](https://user-images.githubusercontent.com/20735485/29859335-373d93a6-8d94-11e7-98b0-ae1368c1cd64.png)

3.I Perform updates,everything is ok,Prompt success。
![image](https://user-images.githubusercontent.com/20735485/29859296-051ba994-8d94-11e7-8774-ea46d690c16a.png)
### Expected Behavior
What you expected to happen?
App will be updated to the latest version of my release
### Actual Behavior
What actually happens?
App is still the original version;
If I use my colleague's account Release update，it is work;
What do I need to do to publish app correctly?
```
  STACK TRACE AND/OR SCREENSHOTS
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:^2.1.1-beta
* react-native version:^0.44.3
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?      release
* Does this reproduce on a simulator, or only on a physical device?  physical

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hello @wjm117,

I believe that you should not do step 2 at all:

> I add our app to my account like this:code-push app add 

In case you are a collaborator of the app you have shared access to it, so you should use you shared app (to which you was added as a collaborator with `code-push collaborator add <appName> <collaboratorEmail>` command) and do not create a new app this way.

Please let us know if any troubles or if you have more questions.

**Comment by wjm117** [comment]
Thank you for your answer @max-mironov 
it happened like this：he run code-push collaborator add <appName> <collaboratorEmail>to add my code-push to app,and then i run: code-push app ls,but nothing in list 
![image](https://user-images.githubusercontent.com/20735485/29863837-69a1fe72-8da3-11e7-9cc7-eb021e6e52ef.png),so he suggest me to do step 2;
before he run add collaborator,are there any other operations needed?
or he run add collaborator ,Will I receive tips?

**Comment by sergey-akhalkov** [comment]
Hi @wjm117, we've just tested collaborators functionality and it works as expected for us:
1. I've executed `code-push collaborator add rncp976-android v-maximi@microsoft.com` command
2. @max-mironov has received an email and accepted invitation
3. Max has executed `code-push app ls` command and from its output he can see my `rncp976-android` app that I've shared.

Could you please confirm if you've received an email and accepted the invitation?

**Comment by wjm117** [comment]
Thanks very much for your help, @sergey-akhalkov @max-mironov , the problem is solved.Yesterday I asked my colleagues to follow your steps，then i check my mailbox ，no invitation mailbox found,but the email  was received an hour later。I  check my mailbox again when I see your answer,then i found invitation mail。everything is ok now ,thanks very much again

**Comment by sergey-akhalkov** [comment]
@wjm117, great! Thanks for the response.
