### ISSUE TITLE
How to Check for App Version Before Showing code push update to the React Native App.

### ISSUE THREAD

**Issue by harshithpawar94** [Microsoft/react-native-code-push#985]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1.
2. 
3.

### Expected Behavior
What did you expect to happen?
It Has to check for App Version is App Version is different than the New App Version than code push Update Should Show.
### Actual Behavior
What actually happens?
It just shows update even if Bundle Versions are same.
```
  STACK TRACE AND/OR SCREENSHOTS

Is there any way to pass Bundle Version as a parameter like: -
code-push release-react [APP_NAME] ios -d CODE_PUSH_DEPLOYMENT_ID -bundleInfo BUNDLE_VERSION
```

### Reproducible Demo

* Download https://github.com/Microsoft/react-native-code-push/archive/master.zip and unzip. From `Examples` folder run `node create-app.js appName react-native@0.47.1 react-native-code-push@5.0.0-beta` command to generate plain CodePushified React Native app. Please see description on top of `create-app.js` file content if needed
* If you can't reproduce the bug on it, provide us as much info as possible about your project

### Environment

* react-native-code-push version:
* react-native version:
* iOS/Android/Windows version:
* Does this reproduce on a debug build or release build?
* Does this reproduce on a simulator, or only on a physical device?

(The more info the faster we will be able to address it!)

**Comment by max-mironov** [comment]
Hey @harshithpawar94, I'm sorry but I don't understand completely what is the question based on the info you have provided. Could you please create new issue and include only the relevant information in the body of the issue, also please provide us with valid repro steps and clear actual/expected information. Thanks in advance!
