### ISSUE TITLE
Hanging on "[CodePush] Checking for update."

### ISSUE THREAD

**Issue by claykohut** [Microsoft/react-native-code-push#993]
I've been seeing my builds occasionally hang / never finish loading on the codepush 'checking for update' sync step recently

Could this be related to the following code-push issue? https://github.com/Microsoft/code-push/issues/511 

Does the .sync promise not reject after failing to check for updates after a certain timeout? Would it be possible to make this happen?

**Comment by max-mironov** [comment]
Hey @claykohut, thanks for notifying, I believe that this issue is related to https://github.com/Microsoft/code-push/issues/511. If you don't mind we'll close this issue because it relates more to code-push service rather then SDK's, so it would be easier to have all discussion in one place.
