### ISSUE TITLE
Code push giving runtime errors after upgrading to React 0.48.1

### ISSUE THREAD

**Issue by kandiva** [Microsoft/react-native-code-push#996]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

### Steps to Reproduce
1. Update your react-native version to 0.48.1
2. Try to build and run the project

### Expected Behavior
What you expected to happen?

### Actual Behavior
What actually happens?
It is giving runtime errors
  STACK TRACE AND/OR SCREENSHOTS

### Environment

* react-native-code-push version: 5.0.0-beta
* react-native version: 0.48.1
* iOS/Android/Windows version: IOS 10.3
* Does this reproduce on a debug build or release build? 
* Does this reproduce on a simulator, or only on a physical device? Simulator and Device

(The more info the faster we will be able to address it!)

**Comment by sergey-akhalkov** [comment]
Hi @kandiva, thanks for reaching us. Could you please fill out all relevant fields from issue template (above)? What the version of RN you've used before? Have you incremented your binary app version after RN update?

**Comment by kandiva** [comment]
I filled environment version above. 

It was working fine before in RN 0.47.1

**Comment by max-mironov** [comment]
Hi @kandiva, probably you should reinstall code-push and try again. 
You can also checkout this comment https://github.com/Microsoft/react-native-code-push/issues/970#issuecomment-324854648 and try to do the same things on your side. 
Please let us know if it helps.

**Comment by max-mironov** [comment]
@kandiva please let us know if you have a chance to look at this

**Comment by max-mironov** [comment]
Closing the issue for now, please feel free to reopen or create a new one if you still have any troubles with this.

**Comment by kandiva** [comment]
@max-mironov I don't see any valid information related to version 0.48 code push runtime errors. I tried getting latest but issue is not resolved yet. I am going to reopen this.

**Comment by max-mironov** [comment]
@kandiva so you have done the following but with no luck, correct? 
Xcode Clean, close Xcode, delete node_modules, npm cache clean, npm install, open Xcode and try to build?

**Comment by kandiva** [comment]
@max-mironov I did not cache clean... l am going to try now

**Comment by kandiva** [comment]
I see it is working fine after delete and clean and reinstall npm modules. Thank you.
