### ISSUE TITLE
[ iOS ] Release build crash "Something went wrong. Please verify if generated JS bundle is correct"

### ISSUE THREAD

**Issue by esutton** [Microsoft/react-native-code-push#998]
Debug build on an iOS device works fine.

A release build crashes throws RCTFatal from CodePush.m

https://github.com/Microsoft/react-native-code-push/blob/638025a67383b32ce44ed0e0ff84696e2d56960e/ios/CodePush/CodePush.m#L355

```
2017-09-13 15:53:07.247688-0500 FieldScout[348:20632] AppDelegate:RELEASE jsbundle
2017-09-13 15:53:07.247950-0500 FieldScout[348:20632] [CodePush overrideAppVersion:1.4.413.536]
2017-09-13 15:53:07.251 [fatal][tid:main] Something went wrong. Please verify if generated JS bundle is correct. 
2017-09-13 15:53:07.254314-0500 FieldScout[348:20632] Something went wrong. Please verify if generated JS bundle is correct.
2017-09-13 15:53:07.259691-0500 FieldScout[348:20632] *** Terminating app due to uncaught exception 'RCTFatalException: Something went wrong. Please verify if generated JS bundle is correct. ', reason: 'Something went wrong. Please verify if generated JS bundle is correct. '
*** First throw call stack:
(0x185ac3d38 0x184fd8528 0x185ac3c80 0x1005e00ec 0x1009ef224 0x1009ee70c 0x100578f78 0x18ef42050 0x18f135898 0x18f13a6e4 0x18f3c8454 0x18f6981f0 0x18f3c80b8 0x18f3c8928 0x18fb316e8 0x18fb3158c 0x18f8ad9c0 0x18fa42fc8 0x18f8ad870 0x18f697850 0x18f138e28 0x18f53c6ec 0x188165768 0x18816e070 0x1014bd45c 0x1014c9b74 0x188199a04 0x1881996a8 0x188199c44 0x185a6c358 0x185a6c2d8 0x185a6bb60 0x185a69738 0x18598a2d8 0x18781bf84 0x18ef36880 0x100579358 0x1854ae56c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

### Environment
* react-native-code-push version: **5.0.0-beta**
* react-native version: 0.42.3
* iOS 10 and iOS 11
* Xcode 8 and Xcode 9
* Reproduce on Release build ONLY
* Reproduce on both iOS Simulator and Physical device

* I am using **yarn** and a **Podfile** to install react-native-firebase and react-native-google-analytics-bridge
* The xcode project shows **libCodePush.a** is being linked.
* Running **react-native link react-native-code-push** did not help.

Should I rollback to something earlier **5.0.0-beta** ?

```
nvm ls
->       system
node -> stable (-> N/A) (default)
iojs -> N/A (default)
```

```
react-native link
...
rnpm-install info iOS module react-native-code-push is already linked 
"CodePush.h" header already imported.
"jsCodeLocation" already pointing to "[CodePush bundleURL]".
Could not determine correct xcode proj path to retrieve related plist file, there are multiple xcodeproj under the solution.
"CodePushDeploymentKey" already specified in the plist file.
"getJSBundleFile" is already overridden
"codepush.gradle" is already linked in the build definition
```

Is this bad?

**Could not determine correct xcode proj path to retrieve related plist file, there are multiple xcodeproj under the solution.**
```
find ios -name '*.xcodeproj'
ios/MyApp.xcodeproj
ios/Pods/Pods.xcodeproj

ios/MyApp.xcworkspace
```

Today I did a git clone of my project and built from scratch. Yesterday, **5.0.0-beta**  was working.  

Today I cannot get a release build to run using wither Xcode 9 or Xcode 8.

Troubleshooting tips are much appreciated.

**Comment by esutton** [comment]
I tried deleting libCodePush.a from "Link Binaries With Libraries" and adding the following to my apps ios/Podfile and then runing posd install.

`react-native link react-native-code-push`

Same crash.  I see my loading screen and company logo, then 'RCTFatalException: Something went wrong.'

I hate to remove CodePush and waste all time invested.  I am running out of things to try.

**Comment by esutton** [comment]
Sorry for the noise. Closing.

I removed CodePush and still have similar problem:

2017-09-14 09:24:02.253 [fatal][tid:main] No bundle URL present.

```
Make sure you're running a packager server or have included a .jsbundle file in your application bundle.
2017-09-14 09:24:02.256467-0500 FieldScout[454:125024] No bundle URL present.
```

More react native adventure game fun.

**Comment by EskelCz** [comment]
@esutton: I`m getting the same warning message. Why did you close this?

**Comment by omeraplak** [comment]
I'm getting the same error.

**Comment by sergey-akhalkov** [comment]
Hi @EskelCz, @omeraplak, please feel free to create new issues if needed.

**Comment by limitsapp** [comment]
Hey , i still have this issue anyone able to fix it ?

**Comment by ruslan-bikkinin** [comment]
Hello @limitsapp please submit new issue with the description of specifics of your problem so will could help you.
